### ISSUE TITLE
OpInfo JIT tests do not work with Tensor kwarg arguments

### ISSUE THREAD

**Issue by heitorschueroff** [pytorch/pytorch#58507]
Remove the skip here https://github.com/pytorch/pytorch/blob/911952220ddfd8330532e516499959c1a77c613a/torch/testing/_internal/common_methods_invocations.py#L4301 to trigger the error below.

```
________________________________________________________________________________________________ TestCommonCPU.test_variant_consistency_jit_cov_cpu_complex64 ________________________________________________________________________________________________
Traceback (most recent call last):
  File "/shared/users/heitorschueroff/pytorch/test/test_ops.py", line 413, in test_variant_consistency_jit
    check_against_reference(self,
  File "/shared/users/heitorschueroff/pytorch/torch/testing/_internal/common_jit.py", line 84, in check_against_reference
    outputs_test = self.runAndSaveRNG(func, nograd_inputs, kwargs)
  File "/shared/users/heitorschueroff/pytorch/torch/testing/_internal/common_jit.py", line 154, in runAndSaveRNG
    results = func(*inputs, **kwargs)
  File "/shared/users/heitorschueroff/pytorch/torch/testing/_internal/jit_metaprogramming_utils.py", line 307, in script_fn
    fn, tensors = gen_script_fn_and_args(method_name, func_type, *args, **kwargs)
  File "/shared/users/heitorschueroff/pytorch/torch/testing/_internal/jit_metaprogramming_utils.py", line 298, in gen_script_fn_and_args
    CU = torch.jit.CompilationUnit(script)
RuntimeError: 
undefined value tensor:
  File "<string>", line 3

def the_method(i0):
    return torch.cov(i0, correction=0, fweights=None, aweights=tensor([0.0518, 0.4681], dtype=torch.float32, requires_grad=True))
```

**Comment by Lilyjjo** [comment]
@heitorschueroff is this issue only reproducible with the changes in #58311? I can work on adding support once that lands if you're not planning on adding the support

**Comment by heitorschueroff** [comment]
@Lilyjjo I've only encountered the issue with this PR. As I understand it, the problem is that some codepaths assume that keyword arguments are never Tensor or TensorList, which is true in most cases (maybe all cases prior to this PR?).

I'm not planning to work on this issue for now. If you'd like to work on it that would be great but this is not high priority as it is not a problem for most operators.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
