### ISSUE TITLE
fx: unable to symbolically trace model with torch.full(Proxy)

### ISSUE THREAD

**Issue by alexander-soare** [pytorch/pytorch#58555]
This is very much like https://github.com/pytorch/pytorch/issues/44887. There the solution was to use `new_ones` but unfortunately in my case that won't work.

My scenario is that I'm trying to initialize the first set of embeddings for an RNN decoder like this:

```python
start_tokens = torch.full(batch_size, sos_token, dtype=torch.int)
embeddings = self.embedding(start_tokens)
```
Here is the full stack trace:

```
Traceback (most recent call last):
  File "fx_quantization.py", line 105, in <module>
    model_q = prepare_fx(model_q, qconfig_dict)
  File "/home/alex/cpu-venv/lib/python3.8/site-packages/torch/quantization/quantize_fx.py", line 378, in prepare_fx
    return _prepare_fx(model, qconfig_dict, prepare_custom_config_dict)
  File "/home/alex/cpu-venv/lib/python3.8/site-packages/torch/quantization/quantize_fx.py", line 171, in _prepare_fx
    graph_module = GraphModule(model, tracer.trace(model))
  File "/home/alex/cpu-venv/lib/python3.8/site-packages/torch/fx/symbolic_trace.py", line 355, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "fx_quantization.py", line 68, in forward
    outputs = self.decoder.predict(encoder_outputs, self.seq_length+2,
  File "/home/alex/model_definitions.py", line 214, in predict
    start_tokens = torch.full(batch_size, sos_token, dtype=torch.int)
TypeError: full() received an invalid combination of arguments - got (Proxy, int, dtype=torch.dtype), but expected one of:
 * (tuple of ints size, Number fill_value, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, Number fill_value, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

**Comment by jamesr66a** [comment]
cc @Chillee
