### ISSUE TITLE
ONNX exported EmbeddingBag fails for not strictly increasing offset.

### ISSUE THREAD

**Issue by Mrpatekful** [pytorch/pytorch#58567]
## 🐛 Bug

After exporting EmbeddingBag to ONNX and running it with onnxruntime, it raises a runtime exception, when provided with offset values that are not strictly increasing.

## To Reproduce

```python
import io
import onnx
import torch
import onnxruntime

ONNX_OPSET = 12

def export(
    model,
    dummy_inputs,
    input_names,
    output_names,
    input_dynamic_axes,
    output_dynamic_axes,
):
    with io.BytesIO() as onnx_bytes:
        torch.onnx.export(
            model,
            dummy_inputs,
            onnx_bytes,
            export_params=True,
            do_constant_folding=True,
            opset_version=ONNX_OPSET,
            input_names=input_names,
            output_names=output_names,
            dynamic_axes={**input_dynamic_axes, **output_dynamic_axes},
        )

        return onnx_bytes.getvalue()


model = torch.nn.EmbeddingBag(num_embeddings=10, embedding_dim=8)

input = torch.arange(10)
offsets = torch.tensor([0, 2, 4, 4, 6])

print(model(input, offsets))

dummy_inputs = input, offsets
input_names = ["input", "offsets"]
output_names = ["output"]
input_dynamic_axes = {"input": {0: "N"}, "offsets": {0: "B"}}
output_dynamic_axes = {"output": {0: "B"}}

model_proto = export(
    model,
    dummy_inputs,
    input_names,
    output_names,
    input_dynamic_axes,
    output_dynamic_axes,
)

session = onnxruntime.InferenceSession(model_proto)
print(session.run(None, {"input": input.numpy(), "offsets": offsets.numpy()}))
```

Stack trace:

```
2021-05-19 17:36:03.889855360 [W:onnxruntime:, graph_utils.cc:193 CanUpdateImplicitInputNameInSubgraphs]  Implicit input name 14 cannot be safely updated to 9 in one of the subgraphs.
2021-05-19 17:36:03.889942432 [W:onnxruntime:, graph_utils.cc:193 CanUpdateImplicitInputNameInSubgraphs]  Implicit input name 14 cannot be safely updated to 9 in one of the subgraphs.
2021-05-19 17:36:03.890050846 [W:onnxruntime:, graph_utils.cc:193 CanUpdateImplicitInputNameInSubgraphs]  Implicit input name 14 cannot be safely updated to 9 in one of the subgraphs.
2021-05-19 17:36:03.890939913 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running ReduceMean node. Name:'ReduceMean_22' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:503 void onnxruntime::CommonReduce(onnxruntime::OpKernelContext*, std::vector<long int>, int64_t, onnxruntime::ResultsNoTransposePrepareForReduce&, bool) [with T = float; AGG = onnxruntime::ReduceAggregatorMean<float, float>; int64_t = long int] keepdims_ was false. Can't reduce on dim with value of 0 if 'keepdims' is false. Invalid output shape would be produced. input_shape:{0,8}

2021-05-19 17:36:03.890959547 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Loop node. Name:'Loop_15' Status Message: Non-zero status code returned while running ReduceMean node. Name:'ReduceMean_22' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:503 void onnxruntime::CommonReduce(onnxruntime::OpKernelContext*, std::vector<long int>, int64_t, onnxruntime::ResultsNoTransposePrepareForReduce&, bool) [with T = float; AGG = onnxruntime::ReduceAggregatorMean<float, float>; int64_t = long int] keepdims_ was false. Can't reduce on dim with value of 0 if 'keepdims' is false. Invalid output shape would be produced. input_shape:{0,8}

Traceback (most recent call last):
  File "test_embedding_bag_onnx_issue.py", line 57, in <module>
    print(session.run(None, {"input": input.numpy(), "offsets": offsets.numpy()}))
  File "/media/patrik/666E8519690F733B/talkabot/amira/venv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Loop node. Name:'Loop_15' Status Message: Non-zero status code returned while running ReduceMean node. Name:'ReduceMean_22' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:503 void onnxruntime::CommonReduce(onnxruntime::OpKernelContext*, std::vector<long int>, int64_t, onnxruntime::ResultsNoTransposePrepareForReduce&, bool) [with T = float; AGG = onnxruntime::ReduceAggregatorMean<float, float>; int64_t = long int] keepdims_ was false. Can't reduce on dim with value of 0 if 'keepdims' is false. Invalid output shape would be produced. input_shape:{0,8}
```

## Expected behavior

Output should be the same as the pytorch version (vector filled with zeros for that bucket).

## Environment

PyTorch version: 1.7.0+cu101
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-73-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1660
Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.7.0+cu101
[conda] Could not collect

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by BowenBao** [comment]
cc @neginraoof

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1524600>

**Comment by thiagocrepaldi** [comment]
Can you retry this with latest onnxruntime and pytorch?

`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
