### ISSUE TITLE
[feature request] random integer generator

### ISSUE THREAD

**Issue by Stonesjtu** [pytorch/pytorch#5874]
I couldn't find an easy way to generate uniform distributed **integer**.

Currently I work it around like this:
```Python
def torch.randint(max, size):
    return (torch.rand(size) * max).long()
```

Or we can generate random integer in C backend.

I can make a PR if it's OK.

**Comment by zou3519** [comment]
You can use [tensor.random_](http://pytorch.org/docs/0.3.1/tensors.html?highlight=random_#torch.Tensor.random_) as so:
```
torch.zeros(size).long().random_(low, high)
```

**Comment by Stonesjtu** [comment]
Thx zou!

**Comment by Naman-ntc** [comment]
Can I try to add this feature? I want to indulge in open source and would love to get started with pytorch!

**Comment by Stonesjtu** [comment]
@Naman-ntc I recommend you to read the blogs on pytorch.org to understand the building system and the `ATEN` document.

**Comment by SsnL** [comment]
@Naman-ntc randn and randperm are good references. https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L393-L406

**Comment by Naman-ntc** [comment]
Thanks alot @SsnL !! 
This makes the work lot easier!
Was reading build system blogs, as soon as I finish reading part will write the functions!

**Comment by Naman-ntc** [comment]
I understood the basic ATEN structure and logic. But I am not sure on how to implement randint type functionality. 
I have a hacky solution :- generating a Tensor via uniform distribution and taking the floor of all values to get integers.
Will it do or what approach should I have??

**Comment by colesbury** [comment]
The `random_(from, to)` function will fill a tensor with random integers in the specified range.

You'll want to do something like `randn` but with `random_` instead of `normal_`. (See SsnL's pointer to relevant files above).

**Comment by Naman-ntc** [comment]
Oh!! Didnt know that random_ function exists in ATEN library as well! Then it's trivial. Thanks

**Comment by SsnL** [comment]
See https://github.com/pytorch/pytorch/tree/master/aten/doc for functions available in aten

**Comment by Naman-ntc** [comment]
Hi, so I did the additions in yaml file as well as in TensorFactories.cpp.
Now we would need to create an entry in python as well right where we will call the backend ATEN function randint? How will it be done??

**Comment by zou3519** [comment]
@Naman-ntc a Python entry gets auto-generated when compiling after you write an entry in `native_functions.yaml` and have code for it. You can test this out by compiling (`python setup.py build develop`) and then trying out `torch.randint` or whatever the name of the function is.

**Comment by Naman-ntc** [comment]
I thought so! 
Had a query then, there are many functions in yaml file I never found in documentation like 'randn_like' and neither I am able to use them.
Also torch.conv1d is not callable though torch.nn.functional uses it. So I thought we need additional registeration!
Will learn the system in more detail!

**Comment by Naman-ntc** [comment]
I made a pull request to master!

**Comment by Naman-ntc** [comment]
With reference to @colesbury comment on [#6136](https://github.com/pytorch/pytorch/pull/6136) regarding [numpy like randint behaviour](https://github.com/pytorch/pytorch/pull/6136) : in numpy we enclose the size/shape in a single tuple parameter unlike in pytorch where we pass all dimensions as separate arguments.

So we can't really achieve default parameters like numpy right as we cant distinguish dimensions of Tensor in case of default argument or is there any way around?

`torch.randint(4,10,2,3) # should mean a 2x3 dim, tensor having random ints in range [4,10)`
`# If default arguments supported then we cant distinguish it with tensor of dim. 10x2x3`

Should we implement tuple based shaping? (It'll be inconsistent with other initialization methods!)

**Comment by Naman-ntc** [comment]
Also I am not understanding how definitions in ATEN yaml files get translated into python definitions. For example the out parameter in [torch.randn](http://pytorch.org/docs/master/torch.html#torch.randn) is not defined in ATEN randn but it probably uses ATEN randn_out definition. How does that take place? Any pointer would be of great help. (search in the pytorch blog though not thoroughly)

**Comment by SsnL** [comment]
@Naman-ntc tuple args also works with `IntList` I believe.
```python
>>> torch.randn((2, 3))

-0.2666 -1.2418 -0.0355
-1.6426 -0.9291  0.4355
[torch.FloatTensor of size (2,3)]

>>>
```

**Comment by Naman-ntc** [comment]
Oh! I didnt know about this behaviour and neither did docs mentioned them. Thnx for quick reply.
If someone gives input as
`torch.randint(2,3,5)` ATEN function would be called as `randint(int64_t low = 2, int64_t high = 3,Intlist=[5])` right and not be confused with `randint(int64_t low = 0, int64_t high = 2,Intlist=[3,5])`?

**Comment by SsnL** [comment]
I'm actually not quite sure on that part. Can you try it out? I believe you also need to define the `yaml` entry as `randint(..., IntList size, *, Generator* generator=nullptr) -> Tensor`.

**Comment by Naman-ntc** [comment]
Yeah, will try out. Thanks, I'm still confused how arguments are parsed from python to C though

**Comment by Naman-ntc** [comment]
To give the default parameter type functionality could I use function overloading? i.e. 

Create to instances of randint in Tensorfactories.cpp and yaml file, one which takes 2 arguments and other taking three arguments because keeping to default parameter would make the code confusing.
Otherwise I can make the second and third parameter (high and sizes) of randint function as NULL and proceed similar to numpy.

**Comment by Naman-ntc** [comment]
@SsnL I am getting these behaviours on corner cases

> torch.randint(5,(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: randint(): argument 'size' (position 2) must be tuple of ints, not int

> torch.randint(5,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: randint(): argument 'size' (position 2) must be tuple of ints, not int

> torch.randint(5,10,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: randint() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int high, tuple of ints size, torch.Generator generator, torch.dtype dtype, int device, bool requires_grad)
 * (int low, int high, tuple of ints size, torch.Generator generator, torch.dtype dtype, int device, bool requires_grad)

Second and third work but in first case it is not desirable I believe. Any fix for it??
