### ISSUE TITLE
Flaky test: not reentrant test_matmul_4d_1d and test_matmul_4d_4d on OS X

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5886]
```
20:00:22 ======================================================================
20:00:22 ERROR: test_matmul_4d_1d (__main__.TestAutograd)
20:00:22 ----------------------------------------------------------------------
20:00:22 Traceback (most recent call last):
20:00:22   File "test_autograd.py", line 3064, in do_test
20:00:22     check(name)
20:00:22   File "test_autograd.py", line 2996, in check
20:00:22     output_variable, (self_variable,) + args_variable)
20:00:22   File "test_autograd.py", line 2929, in run_grad_and_gradgrad_checks
20:00:22     test_case.assertTrue(gradgradcheck(apply_method, input_variables, gen_non_contig_grad_outputs=True))
20:00:22   File "/private/var/lib/jenkins/workspace/pytorch-builds/pytorch-macos-10.13-py3-build-test/miniconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 265, in gradgradcheck
20:00:22     return gradcheck(new_func, inputs + grad_outputs, eps, atol, rtol, raise_exception)
20:00:22   File "/private/var/lib/jenkins/workspace/pytorch-builds/pytorch-macos-10.13-py3-build-test/miniconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 186, in gradcheck
20:00:22     return fail_test('not reentrant')
20:00:22   File "/private/var/lib/jenkins/workspace/pytorch-builds/pytorch-macos-10.13-py3-build-test/miniconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 166, in fail_test
20:00:22     raise RuntimeError(msg)
20:00:22 RuntimeError: not reentrant
20:00:22 
20:00:22 ======================================================================
20:00:22 ERROR: test_matmul_4d_4d (__main__.TestAutograd)
20:00:22 ----------------------------------------------------------------------
20:00:22 Traceback (most recent call last):
20:00:22   File "test_autograd.py", line 3064, in do_test
20:00:22     check(name)
20:00:22   File "test_autograd.py", line 2996, in check
20:00:22     output_variable, (self_variable,) + args_variable)
20:00:22   File "test_autograd.py", line 2929, in run_grad_and_gradgrad_checks
20:00:22     test_case.assertTrue(gradgradcheck(apply_method, input_variables, gen_non_contig_grad_outputs=True))
20:00:22   File "/private/var/lib/jenkins/workspace/pytorch-builds/pytorch-macos-10.13-py3-build-test/miniconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 265, in gradgradcheck
20:00:22     return gradcheck(new_func, inputs + grad_outputs, eps, atol, rtol, raise_exception)
20:00:22   File "/private/var/lib/jenkins/workspace/pytorch-builds/pytorch-macos-10.13-py3-build-test/miniconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 186, in gradcheck
20:00:22     return fail_test('not reentrant')
20:00:22   File "/private/var/lib/jenkins/workspace/pytorch-builds/pytorch-macos-10.13-py3-build-test/miniconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 166, in fail_test
20:00:22     raise RuntimeError(msg)
20:00:22 RuntimeError: not reentrant
20:00:22 
20:00:22 ----------------------------------------------------------------------
20:00:22 Ran 772 tests in 85.303s
20:00:22 
```

Test log: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-macos-10.13-py3-build-test/3462//console

Host was  worker-macos-high-sierra-0

Subsequent master PR did not fail this way.

**Comment by ezyang** [comment]
Haven't seen this one in a while.
