### ISSUE TITLE
PackageExporter fails on some __import__ statements.

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#58863]
## 🐛 Bug

PackageExporter fails when it looks at code that has import statements that are not fully constant nor fully dynamic.

## To Reproduce

```
import torch

with torch.package.PackageExporter("output") as e:
    e.save_source_string('m',  '__import__("these", dont, have, to, be, contants)')
```

```
Traceback (most recent call last):
  File "p.py", line 4, in <module>
    e.save_source_string('m',  '__import__("these", dont, have, to, be, contants)')
  File "/raid/zdevito/pytorch/torch/package/package_exporter.py", line 307, in save_source_string
    deps = self._get_dependencies(src, module_name, is_package)
  File "/raid/zdevito/pytorch/torch/package/package_exporter.py", line 258, in _get_dependencies
    dep_pairs = find_files_source_depends_on(src, package_name)
  File "/raid/zdevito/pytorch/torch/package/find_file_dependencies.py", line 17, in run
    visitor.visit(tree)
  File "/private/home/zdevito/miniconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/private/home/zdevito/miniconda3/lib/python3.8/ast.py", line 371, in generic_visit
    self.visit(item)
  File "/private/home/zdevito/miniconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/private/home/zdevito/miniconda3/lib/python3.8/ast.py", line 373, in generic_visit
    self.visit(value)
  File "/private/home/zdevito/miniconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/raid/zdevito/pytorch/torch/package/find_file_dependencies.py", line 68, in visit_Call
    for v in node.args[3].elts:
AttributeError: 'Name' object has no attribute 'elts'
```

## Expected behavior

Package is exported.

**Comment by suo** [comment]
cc @Lilyjjo: I remember you were looking into this, right?

**Comment by Lilyjjo** [comment]
Hmmm, I did disable importing dynamic cases in #57283 because of issues of trying to import non-modules like in https://github.com/pytorch/pytorch/issues/57193#issuecomment-829388456. If there are reasons why we need to support dynamic importing I can design another solution

**Comment by Lilyjjo** [comment]
I can for sure add a better error message than the `AttributeError` being thrown above, that is a bad UX I was unaware of

**Comment by suo** [comment]
Dynamic importing is out of scope for us I think. Definitely we want a better error message though. And we should be checking that the error is properly caught and displayed as a `PackagingError` post-https://github.com/pytorch/pytorch/pull/58573

**Comment by Lilyjjo** [comment]
Okay, I can do the error message fix up 👍

**Comment by zdevito** [comment]
Even if we don't support finding dependencies from dynamic import statements (which is halting-problem impossible), I don't think this should be an error. It should just not log any new dependencies and move on. This example in particular shows how the code is not definitive enough about what might appear in the AST.

I also wonder where`__import__` is being used where the values are constants. Why write `__import__` in that case rather than just use an import statement?

**Comment by zdevito** [comment]
Furthermore, there is a whole class of `importlib.import_module` that aren't handled either. I am wondering about the use of `__import__` with explicit arguments because I think the more natural boundary of support would be to support explicit import statements but not try to guess at the meaning of functions via AST parsing, which is not generally possible.

**Comment by Lilyjjo** [comment]
I agree that the current code isn't enough to capture all use cases. I wasn't totally sure of the limitations of the AST parser when I was writing it. There are examples of `__import__` with constants being used internally, e.g. [this](https://www.internalfb.com/intern/diffusion/FBS/browsefile/master/fbcode/github/third-party/PyTorchLightning/pytorch-lightning/pytorch_lightning/__init__.py?lines=36) usage was causing issues when I was trying to help someone package their model. I can put the logic in a try-catch block to enable limited support for `__import__` and issue a warning about the import lines which are parsed but not added

**Comment by Lilyjjo** [comment]
Whoops I forgot that the dynamic imports will still be parsed in the importer. We can't just skipped failed dunder imports due to situations like this:
```
import torch
from textwrap import dedent

src = dedent(
                """\
                fake_name = "time"
                __import__(fake_name)
                """
            )

with torch.package.PackageExporter("output", verbose=False) as e:
    e.save_source_string('m',  src)


importer = torch.package.PackageImporter("output")
importer.import_module("m") # will fail to be able to resolve module 'time'
```

**Comment by zdevito** [comment]
The dependency resolver can never 100% find all the dependencies of a module. So I don't think it is an error for it to see an `__import__` statement and not be able to resolve it. Arguably it shouldn't be a warning either -- there are a lot of ways someone can already cause a package to be imported (e.g. importlib.import_module) that we won't know about and that `__import__` statement itself might be conditional. So from this perspective, I think the "right" behavior is to just silently pass over `__import__` calls that aren't statically resolvable.

The actual usage is a bogus use of `__import__` to begin with. The same behavior is accomplished with the much more idiomatic:
```
from pkg_resources import declare_namespace as _declare_namespace
_declare_namespace(__name__)
```
So this is not a situation I think will arise a lot in the future..

**Comment by Lilyjjo** [comment]
I like the plan of not causing the module to throw a dependency error when an `__import__` statement isn't resolvable, I'm just worried that users might find the behavior surprising without a warning. I think that have a warning issued, at least when the PackageExporter is in verbose=True mode, would be worthwhile for the end user. 

The one thing I don't like about this plan is that it breaks the goal of ensuring that when a package is exportable that is it also loadable. @Suo what are your opinions on not throwing an error? 

I agree that the example I gave is a bad use of `__import__`, but that example was of a 3rd party-ish module that our users didn't have access to easily change. Some `__import__`s  are usages that we can cover and I think we should handle them when we can

**Comment by suo** [comment]
yeah I actually was going to write a comment about "a third behavior is failing silently" but I got distracted and wandered away…

So we have the basic problem of:
- There is some class of dependencies that are impossible to capture using our system (dynamic ones)
- The can lead to confusing failures at import time
- But making it a hard error might be too harsh. Importing still *might* work, and it's not guaranteed you can freely edit the offending code.

One thing: it's surprisingly not that rare? We've run into variations of dynamic imports on almost everything we're tried to package (ClassyVision, DPER, Fairseq, etc.). But since those mostly take the form of `importlib` stuff, we just pass them through.

I would say: for now we can just catch and eat the error. I actually think we should re-work the verbose messaging with the new dep graph info anyway, so maybe that would be a good place to insert extra info (e.g. "hey we couldn't resolve X" or "hey we saw you imported importlib, pretty sus").
