### ISSUE TITLE
[Android] Latest nightly build causes error: library "libpytorch_jni.so" not found

### ISSUE THREAD

**Issue by rubengrab** [pytorch/pytorch#58913]
## 🐛 Bug

Following the latest nightly(snapshots) build that was published, loading the model on an Android device is no longer possible. It raises an error: `java.lang.UnsatisfiedLinkError: dlopen failed: library "libpytorch_jni.so" not found`
 
## To Reproduce

1. Convert a model from PyTorch to TorchScript(cpu or nnapi)
2. Import it in the ObjectDetection Demo App
3. Import repository explicitly

> ```
> repositories {
>     maven {
>         url "https://oss.sonatype.org/content/repositories/snapshots"
>     }
> }
> 
> dependencies {
>     ...
>     implementation 'org.pytorch:pytorch_android:1.9.0-SNAPSHOT'
>     implementation 'org.pytorch:pytorch_android_torchvision:1.9.0-SNAPSHOT'
>     ...
> }
> ```

4. Load it in app: `PyTorchAndroid.loadModuleFromAsset(getAssets(), "model.torchscript.pt");`

## Actual behavior

It raises the following exception:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.pytorch.demo.objectdetection, PID: 5629
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libpytorch_jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:22)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43)
        at org.pytorch.NativePeer.<clinit>(NativePeer.java:10)
        at org.pytorch.PyTorchAndroid.loadModuleFromAsset(PyTorchAndroid.java:31)
        at org.pytorch.demo.objectdetection.MainActivity.onCreate(MainActivity.java:166)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

## Expected behavior

The application should at least be able to load the model, and then it should be able to run the model.

## Environment(used to convert the model from PyTorch to TorchScript + NNAPI)
```
PyTorch version: 1.9.0.dev20210525
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.8.0-41-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.0.194
GPU models and configuration: GPU 0: GeForce RTX 2070 with Max-Q Design
Nvidia driver version: 460.67
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==1.2.10
[pip3] torch==1.9.0.dev20210525
[pip3] torch-tb-profiler==0.1.0
[pip3] torchaudio==0.9.0a0+bfd1d33
[pip3] torchmetrics==0.2.0
[pip3] torchvision==0.10.0.dev20210525
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.3.0            py38h54f3939_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.9.0.dev20210525 py3.8_cuda10.2_cudnn7.6.5_0    pytorch-nightly
[conda] pytorch-lightning         1.2.10                   pypi_0    pypi
[conda] torch-tb-profiler         0.1.0                    pypi_0    pypi
[conda] torchaudio                0.9.0.dev20210525            py38    pytorch-nightly
[conda] torchmetrics              0.2.0                    pypi_0    pypi
[conda] torchvision               0.10.0.dev20210525      py38_cu102    pytorch-nightly

```

## Additional context

I have used both an old converted model that was previously working and a newly converted model(with the lastest nightly  version) and in both cases, the model was not able to be loaded.

**Comment by cccclai** [comment]
We are transitioning to use lite interpreter for Android, targeting smaller library size. Currently the new nightly build is lite interpreter. The new library name is `libpytorch_jni_lite.so`. 

To use lite interpreter, the model can be generated following the example:
```
import torch

model = torch.hub.load('pytorch/vision:v0.7.0', 'deeplabv3_resnet50', pretrained=True)
model.eval()

scripted_module = torch.jit.script(model)
# Export full jit version model (not compatible lite interpreter), leave it here for comparison
scripted_module.save("deeplabv3_scripted.pt")
# Export lite interpreter version model (compatible with lite interpreter)
scripted_module._save_for_lite_interpreter("deeplabv3_scripted.ptl")
```

To load the model:
```
import org.pytorch.LiteModuleLoader
...
mModule = LiteModuleLoader.load(MainActivity.assetFilePath(getApplicationContext(), "deeplabv3_scripted.ptl"));
...
```

This tutorial will be updated soon, but it can still be used as a reference now: https://pytorch.org/tutorials/prototype/lite_interpreter.html

**Comment by rubengrab** [comment]
Thank you, @cccclai! The solution works and I am able to run the model and get predictions.


Note: _However, in the last layer I am multiplying the normalised coordinates of the bboxes with the width & height of the image, but although on PC the multiplication takes place, it seems that on the Android it doesn't and I have to do it outside of the model. 
Could it be that the mutliplication/division/addition with a constant is omitted by the lite interpreter?_

**Comment by rubengrab** [comment]
Thank you, @cccclai! The solution works and I am able to run the model and get predictions.
