### ISSUE TITLE
 _pickle.UnpicklingError: invalid load key, '\x0a'. 

### ISSUE THREAD

**Issue by Ankita-020696** [pytorch/pytorch#59132]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
Hi,
How to fix following error?

```
$ ./run_local.sh --dataset coco-1200 --profile ssd-resnet34-pytorch
INFO:main:Namespace(accuracy=False, backend='pytorch-native', cache=0, count=None, data_format=None, dataset='coco-1200', dataset_list=None, dataset_path='/home/root/Ankita/data/coco', debug=False, find_peak_performance=False, inputs=['image'], max_batchsize=32, max_latency=None, mlperf_conf='../../mlperf.conf', model='/home/root/Ankita/model/resnet50_v1.pb', model_name='ssd-resnet34', output='/home/root/Ankita/inference/vision/classification_and_detection/output/tf-cpu/resnet50', outputs=['bboxes', 'labels', 'scores'], profile='ssd-resnet34-pytorch', qps=None, samples_per_query=None, scenario='SingleStream', threads=4, time=None, user_conf='user.conf')
Error in cpuinfo: processor architecture is not supported in cpuinfo
INFO:coco:reduced image list, 4999 images not found
INFO:coco:loaded 1 images, cache=0, took=8.7sec
/home/root/Ankita/inference/vision/classification_and_detection/python/coco.py:115: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
self.label_list = np.array(self.label_list)
Traceback (most recent call last):
File "python/main.py", line 558, in
main()
File "python/main.py", line 436, in main
model = backend.load(args.model, inputs=args.inputs, outputs=args.outputs)
File "/home/root/Ankita/inference/vision/classification_and_detection/python/backend_pytorch_native.py", line 26, in load
self.model = torch.load(model_path,map_location=lambda storage, loc: storage)
File "/usr/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "/usr/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.



```

Thanks

cc @mruberry @fmassa @vfdev-5 @pmeier

**Comment by mrshenli** [comment]
Hey @Ankita-020696, we usually use the [forum](https://discuss.pytorch.org/) for questions. I am closing this issue for now. Please feel free to create another issue if this turns out to be a bug report or feature request. BTW, when you post on the form, please consider include a self-contained repro, so that other users can help debug. Thanks!
