### ISSUE TITLE
ONNX export: RuntimeError: rINTERNAL ASSERT FAILED at "..\\aten\\src\\ATen/core/jit_type_base.h":172

### ISSUE THREAD

**Issue by lasa01** [pytorch/pytorch#59179]
## 🐛 Bug

I'm trying to export Mozilla TTS Tacotron2 model into ONNX using TorchScript.

Here is my current progress: https://github.com/lasa01/TTS/tree/onnx.

Here is the export script: https://github.com/lasa01/TTS/blob/onnx/TTS/bin/convert_tacotron2_torch_to_onnx.py.

However, the export fails with the following error:

```
python -m TTS.bin.convert_tacotron2_torch_to_onnx.py --config_path ".\TTS\tts\configs\config.json" --output_path ".\data\converted_models\tts_model.onnx"
Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'outputs.17'. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'stop_tokens.15'. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'alignments.15'. This changes graph semantics.
D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\symbolic_opset9.py:2119: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  "or define the initial states (h0/c0) as inputs of the model. ")
D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\symbolic_opset11.py:573: UserWarning: This model contains a squeeze operation on dimension 1. The size of this dimension in the given input is 560. The model will be exported without the squeeze node. If the model is intended to be used with dynamic input shapes, please export with dynamic_axes argument.
  "input shapes, please export with dynamic_axes argument.")
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "D:\lasa\Code\TTS\TTS\bin\convert_tacotron2_torch_to_onnx.py", line 102, in <module>
    verbose=True,
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 693, in _export
    dynamic_axes=dynamic_axes)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 465, in _model_to_graph
    module=module)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 1087, in _run_symbolic_function
    is_sub_block)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 1087, in _run_symbolic_function
    is_sub_block)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\lasa\Code\tts_venv\lib\site-packages\torch\onnx\utils.py", line 1088, in _run_symbolic_function
    new_op_outputs = torch._C._jit_pass_fixup_onnx_controlflow_node(new_node, opset_version)
RuntimeError: rINTERNAL ASSERT FAILED at "..\\aten\\src\\ATen/core/jit_type_base.h":172, please report a bug to PyTorch.
```

## To Reproduce

1. Clone https://github.com/lasa01/TTS/tree/onnx
1. Install dependencies.
1. Run `python -m TTS.bin.convert_tacotron2_torch_to_onnx.py --config_path "./TTS/tts/configs/config.json" --output_path "./data/converted_models/tts_model.onnx"`

## Expected behavior

The export succeeds.

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0.dev20210529+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: 12.0.0
CMake version: version 3.18.4
Libc version: N/A

Python version: 3.6 (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.9.0.dev20210529+cu102
[pip3] torchaudio==0.9.0.dev20210529
[pip3] torchvision==0.11.0.dev20210529
[conda] Could not collect
```

Same issue also happened with PyTorch 1.8.1.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity @gmagogsfm

**Comment by BowenBao** [comment]
Thanks for reporting. Will take a look.

**Comment by hwangdeyu** [comment]
TensorList of Uninitialized Output problem.

**Comment by hwangdeyu** [comment]
Hi @lasa01

This issue can be fixed by [[ONNX] Support tensorList when Infers shape and type uninitialized output](https://github.com/pytorch/pytorch/pull/60534). This PR will be merged into PyTorch master branch in a few days later.

You can fix this error after doing the several steps:

1. rebase your PyTorch code from source to latest version.

2. change the cpp file code as [fixup_onnx_controlflow.cpp]
(https://github.com/pytorch/pytorch/pull/60534/files#diff-453587fcffee7672220dd198a09ce803d7663779142e6c52872f435a37d7ba07) and build PyTorch again.

3. change the [TTS torch.onnx.export()](https://github.com/lasa01/TTS/blob/52629e882b43abdf9b8aa6be5a34dd981460d372/TTS/bin/convert_tacotron2_torch_to_onnx.py#L91) function opset_version to latest one ( is **opset_version=13** now ).

**Comment by lasa01** [comment]
Thanks, can confirm that the export now succeeds with those changes (even with opset 11).

**Comment by hwangdeyu** [comment]
> Thanks, can confirm that the export now succeeds with those changes (even with opset 11).

Sure, I closed this issue.

**Comment by garymm** [comment]
@hwangdeyu in the future please don't close issues until the fix is merged into master.

**Comment by hwangdeyu** [comment]
> @hwangdeyu in the future please don't close issues until the fix is merged into master.

Sure, get it in duty rotation doc.

**Comment by hwangdeyu** [comment]
PR merged into master. Closed it.

**Comment by garymm** [comment]
@hwangdeyu are you sure the change is in master? If so, then what is this doing still open? https://github.com/pytorch/pytorch/pull/66175

**Comment by BowenBao** [comment]
@garymm #66175 seems to be obsolete, after another PR stack created for it, closing that one. Going forward I will close these kind of PRs in a more timely manner. The change from @hwangdeyu are in c16f192fe1712ecf14ddd679d68b08c0e6c867e8. Feel free to close this.

**Comment by garymm** [comment]
Thanks for clarifying.
