### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by TalWac** [pytorch/pytorch#59219]
## 🐛 Bug

There are 2 files of a python script that used to work (until a few weeks ago). 

The files are:
1. [preprocess.py](https://github.com/Qiong-Yang/GNN-RT/blob/master/preprocess.py) - which is still works
2. [train.py](https://github.com/Qiong-Yang/GNN-RT/blob/master/train.py) - which produces the error in the title

The 2 scripts are based on this [data](https://github.com/Qiong-Yang/GNN-RT/tree/master/data) library.

## To Reproduce

Can use the links to the scripts supplied above (I was not sure if needed to add the script in addition to the links) 
 

This is the error when running the[ train.py](https://github.com/Qiong-Yang/GNN-RT/blob/master/train.py):

```

The code uses a GPU!
The code uses a GPU!
SMRT_train_set.txt
SMRT_test_set.txt
dataset_test
The code uses a GPU!
----------------------------------------------------------------------------------------------------
Just a moment......
----------------------------------------------------------------------------------------------------
The preprocess has finished!
# of training data samples: 63163
# of development data samples: 7019
# of test data samples: 7798
----------------------------------------------------------------------------------------------------
Creating a model.
# of model parameters: 268273
----------------------------------------------------------------------------------------------------
Start training.
The result is saved in the output directory every epoch!

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/BCDD/Documents/Tal/Projects/RT-Prediction/GNN-RT/train.py", line 229, in <module>
    loss_train = trainer.train(dataset_train)
  File "D:/BCDD/Documents/Tal/Projects/RT-Prediction/GNN-RT/train.py", line 110, in train
    loss = self.model.forward_regressor(data_batch, train=True)
  File "D:/BCDD/Documents/Tal/Projects/RT-Prediction/GNN-RT/train.py", line 81, in forward_regressor
    correct_values = torch.cat(data_batch[-1])
RuntimeError: CUDA error: no kernel image is available for execution on the device

```

(It does work to some extent)
## Expected behavior
To work without errors and produce the files it used to do.

## Environment
I am using working on conda environment for this project on Windows 10.

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

```
Collecting environment information...
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A
OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A
Python version: 3.8 (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.2.142
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.7.1+cu110
[pip3] torch-package==1.0.1
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.8.2+cu110
[conda] _pytorch_select           0.1                       cpu_0  
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hb195166_8    conda-forge
[conda] libblas                   3.8.0                    14_mkl    conda-forge
[conda] libcblas                  3.8.0                    14_mkl    conda-forge
[conda] liblapack                 3.8.0                    14_mkl    conda-forge
[conda] libmklml                  2019.0.5             haa95532_0  
[conda] mkl                       2021.2.0                 pypi_0    pypi
[conda] mkl-service               2.3.0            py38hfa6e2cd_0    conda-forge
[conda] numpy                     1.20.2           py38h09042cb_0    conda-forge
[conda] torch                     1.8.1                    pypi_0    pypi
[conda] torch-package             1.0.1                    pypi_0    pypi
[conda] torchaudio                0.8.1                      py38    pytorch
[conda] torchvision               0.8.2+cu110              pypi_0    pypi

```
You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.7.1+cu110
 - OS (e.g., Linux): Winows 10
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source): at the beginning `conda install pytorch` but after searching tried other things that I do not completely understand 
 - Python version: 3.8
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context
I was searching for other [open issues ](https://github.com/pytorch/pytorch/issues?page=2&q=is%3Aissue+no+kernel+image+is+available+for+execution+on+the+device) 
and [close issues](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+no+kernel+image+is+available+for+execution+on+the+device+is%3Aclosed)

Kindly your guidance  \ assistants any hint will be appreciated 

Best regards,
Tal

**Comment by ngimel** [comment]
The error indicates that you are trying to run on a GPU model that's not supported by precompiled pytorch binary. 
According to your enviroment, you are using pytorch 1.7.1 that has not changed. Please look for things that changed in how your are trying to run pytorch (or GPU that you are trying to run it on).

**Comment by TalWac** [comment]
thank you for your reply!

> Please look for things that changed in how your are trying to run pytorch (or GPU that you are trying to run it on).

I'm not sure what you meant?  or what am I looking for?  the script has not been changed, I'm using it as it is. the computer is the same.
Can you please give examples of what should I be looking for?  

Tahnks !

**Comment by ngimel** [comment]
If the script has not changed, the computer has not changed, and the pytorch version that you are using (1.7.1) has not changed, I don't see a possible explanation.

**Comment by TalWac** [comment]
Sorry for my inexperience but clearly I'm doing something wrong, maybe something did change. Are there steps to approach the error `CUDA error: no kernel image is available for execution on the device`  

Many thanks!

**Comment by ngimel** [comment]
This error typically happens when you are trying to run pytorch on a GPU that it doesn't support. Can you please show the results of `nvidia-smi` command in the terminal, and `python -c "import torch; print(*torch.__config__.show().split("\n"), sep="\n")"`

**Comment by TalWac** [comment]
Sure:

```
C:\Program Files\NVIDIA Corporation\NVSMI>nvidia-smi.exe
Thu Jun  3 12:30:10 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 461.09       Driver Version: 461.09       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GT 710     WDDM  | 00000000:02:00.0 N/A |                  N/A |
| 40%   49C    P8    N/A /  N/A |   1642MiB /  2048MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

And the second opened python from command line 
```
(GNN-RT-env-1) D:\BCDD\Documents\Tal\Projects\RT-Prediction\GNN-RT>python
Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:04:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; print(*torch.__config__.show().split("\n"), sep="\n")
PyTorch built with:
  - C++ Version: 199711
  - MSVC 192729112
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.4
  - Magma 2.5.4
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_VULKAN_WRAPPER, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

>>>

```
Thank you !

**Comment by ngimel** [comment]
GEForce GT 710 is an old card with compute capability 3.0. Pytorch doesn't support it and hasn't supported it for a long time. https://forums.developer.nvidia.com/t/what-is-the-compute-capability-of-a-geforce-gt-710/146956/

**Comment by TalWac** [comment]
Thank you for your time and patience!

**Comment by dizcza** [comment]
It *is* possible to run pytorch v1.10.2 on old-fashioned sm_30 arch gpus.

For further issues like this you can refer to the Dockerfile I'm maintaining specifically for this need. https://github.com/dizcza/pytorch-sm30-docker
