### ISSUE TITLE
unittest error: ModuleNotFoundError: No module named 'torch._C'

### ISSUE THREAD

**Issue by nicehiro** [pytorch/pytorch#59217]
## ❓ Questions and Help

Hi, I'm trying to run pytorch unittest. 
For example
```
python -m unittest test.test_autograd.TestAutograd.test_function
```

Then I got this error
```
ModuleNotFoundError: No module named 'test.test_autograd'
```

So I add the `__init__.py` file to the submodule `test` folder, and I got this error
```
Traceback (most recent call last):
  File "/Users/wangfangyuan/anaconda3/envs/cvenv/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/wangfangyuan/Projects/github/pytorch/test/test_autograd.py", line 7, in <module>
    import torch
  File "/Users/wangfangyuan/Projects/github/pytorch/torch/__init__.py", line 81, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'torch._C'
```

The wired thing is that when I run `import torch` in pytorch console, it works fine.

Could someone help me solve this problem? 
Thanks.

**Comment by ngimel** [comment]
Pytorch unittests are directly runnable as 
```
python test/test_autograd.py
```
you can filter to the desired tests only with `-k`.
