### ISSUE TITLE
How to solve the AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by aktaseren** [pytorch/pytorch#59231]
For the usage of the repo based on PyTorch(Person_reID_baseline_pytorch), I followed the guidance on its readme.md. However, I've got an error on the training step below: (I used --gpu_ids -1 as I use CPU only option in my MacOS)

`python train.py --gpu_ids -1 --name ft_ResNet50 --train_all --batchsize 32 --data_dir /Users/455832/Person_reID_baseline_pytorch/Market-1501-v15.09.15/pytorch`

The error I got is below:

```
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /Users/455832/.cache/torch/checkpoints/resnet50-19c8e357.pth
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 102502400/102502400 [00:14<00:00, 7210518.23it/s]
ft_net(
  (model): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): Bottleneck(
        (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace)
        (downsample): Sequential(
          (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): Bottleneck(
        (conv1): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace)
      )
      (2): Bottleneck
.......
.......
)
Traceback (most recent call last):
  File "train.py", line 386, in <module>
    model = model.cuda()
  File "/Users/455832/opt/anaconda3/envs/reid_conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/Users/455832/opt/anaconda3/envs/reid_conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/Users/455832/opt/anaconda3/envs/reid_conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/Users/455832/opt/anaconda3/envs/reid_conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/Users/455832/opt/anaconda3/envs/reid_conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/Users/455832/opt/anaconda3/envs/reid_conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/Users/455832/opt/anaconda3/envs/reid_conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

As suggested in its readme.md, I installed pytorch=1.1.0 and torchvision=0.3.0 and numpy=1.13.1, which are requirements, into my virtual environment using 3.6.12 python requirement over the instructions in PyTorch official website (https://pytorch.org/get-started/previous-versions/#wheel-10)

`conda install pytorch==1.1.0 torchvision==0.3.0 -c pytorch`

Can you please guide me to solve this issue?

**Comment by imaginary-person** [comment]
Did you try omitting `--gpu_ids` since you aren't using a GPU?

**Comment by ngimel** [comment]
Please ask the questions in that repo. Apparently, train script (train.py) is calling model.cuda(), which is an unsupported operation for your cpu-only build

**Comment by aktaseren** [comment]
Thank you for a quick reply. My question actually was: How can I install also CUDA with pytorch==1.1.0 torchvision==0.3.0 for my Big Sur MacOS system? 

According to PyTorch official website [https://pytorch.org/get-started/previous-versions/#wheel-10], I can only see that command below but it did not work.

`conda install pytorch==1.1.0 torchvision==0.3.0 -c pytorch`

**Comment by ngimel** [comment]
CUDA is not supported with Mac, because Macs typically don't have nvidia GPUs.

**Comment by imaginary-person** [comment]
@technocreep, GT 750M has [Compute Capability 3](https://developer.nvidia.com/cuda-gpus), which is below the minimum Compute Capability in the current PyTorch codebase. Moreover, CUDA toolkit was discontinued for MacOS, starting CUDA Toolkit 11. 

So, for such systems, I suppose one would have to try building from source for lower Compute Capability and CUDA Toolkit 10.x instead.
