### ISSUE TITLE
Troubles downloading CIFAR10 dataset with pytorch

### ISSUE THREAD

**Issue by pepe78** [pytorch/pytorch#59344]
## 🐛 Bug

CIFAR-10 dataset not loading:

Device cuda
==> Preparing data..
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 1415, in connect
    super().connect()
  File "/usr/lib/python3.9/http/client.py", line 919, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pepe/code/cifar_pytorch/main.py", line 63, in <module>
    trainset = torchvision.datasets.CIFAR10(
  File "/home/pepe/.local/lib/python3.9/site-packages/torchvision/datasets/cifar.py", line 65, in __init__
    self.download()
  File "/home/pepe/.local/lib/python3.9/site-packages/torchvision/datasets/cifar.py", line 143, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/home/pepe/.local/lib/python3.9/site-packages/torchvision/datasets/utils.py", line 316, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/pepe/.local/lib/python3.9/site-packages/torchvision/datasets/utils.py", line 124, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/home/pepe/.local/lib/python3.9/site-packages/torchvision/datasets/utils.py", line 75, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

## To Reproduce

1. pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
2. git clone https://github.com/pepe78/cifar_pytorch.git
3. cd cifar_pytorch
4. python3 main.py

## Expected behavior

Download Cifar-10 and continue training

## Environment

Ubuntu 21.04
pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

pepe@pepe-MS-7C90:~$ python3 collect_env.py
Collecting environment information...
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 21.04 (x86_64)
GCC version: (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.33

Python version: 3.9 (64-bit runtime)
Python platform: Linux-5.11.0-17-generic-x86_64-with-glibc2.33
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.1+cu111
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1+cu111
[conda] Could not collect

**Comment by pepe78** [comment]
It started to work now...

**Comment by dhruv-bhatia246** [comment]
> It started to work now...

But how?
Facing the same issue
