### ISSUE TITLE
CUDNN_STATUS_NOT_INITIALIZED when built from source

### ISSUE THREAD

**Issue by hitvoice** [pytorch/pytorch#5942]
### environment

- OS: Ubuntu 16.04.3 LTS
- PyTorch version: 0.4.0a0+e9f144b
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6.2
- CUDA/cuDNN version: V9.0.176/7005
- GPU driver version: 384.81   
- GCC version (if compiling from source): gcc version 5.4.0 20160609

### script

```python
import torch.nn as nn
lstm = nn.LSTM(3, 3)
lstm.cuda()
```

### output
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-d89616d6776d> in <module>()
      1 import torch.nn as nn
      2 lstm = nn.LSTM(3, 3)
----> 3 lstm.cuda()

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in cuda(self, device)
    228             Module: self
    229         """
--> 230         return self._apply(lambda t: t.cuda(device))
    231 
    232     def cpu(self):

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py in _apply(self, fn)
     98     def _apply(self, fn):
     99         ret = super(RNNBase, self)._apply(fn)
--> 100         self.flatten_parameters()
    101         return ret
    102 

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py in flatten_parameters(self)
     91                     weight_arr, weight_stride0,
     92                     self.input_size, rnn.get_cudnn_mode(self.mode), self.hidden_size, self.num_layers,
---> 93                     self.batch_first, bool(self.bidirectional))
     94 
     95             self._param_buf_size = weight_buf.size(0)

RuntimeError: CUDNN_STATUS_NOT_INITIALIZED
```

But the file `~/anaconda3/lib/python3.6/site-packages/torch/lib/libcudnn.so.7` exists, and 
```python
from torch.backends import cudnn
print(cudnn.version())
```
gives "7005".

**Comment by zou3519** [comment]
Does `rm -rf ~/.nv` help?

**Comment by hitvoice** [comment]
No. I ran `rm -rf ~/.nv ` and installed from source again and this problem still exists.

**Comment by HandsomeDevilv112** [comment]
I had a very similar problem the other day. I managed to solve it by downloading and installing the newest version of cudnn

**Comment by hitvoice** [comment]
After these updates:
- Nvidia driver: 384.81-> 387.26 
- CUDA: V9.0.176 -> V9.1.85
- CuDNN: 7005 -> 7102

The installation completes without error. Thanks!

**Comment by bueche** [comment]
similar problem as described at top but with later software:
nvidia driver 390.12
cuda release 9.1, V9.1.85
cudnn v7.1.4 
pytorch 0.5.0a0+01f5b )build from source)

also, the test_cuda.py in pytorch core dumps after printing out many lines of periods and s's.

**Comment by bueche** [comment]
Thanks. That did not solve the problem. I don't know if the original problem noted above is related to the test core dump, but for information the test failure happens here:

```
test_DoubleTensor_put_ (__main__.TestCuda) ... ok
test_DoubleTensor_put__accumulate (__main__.TestCuda) ... ok
test_DoubleTensor_put__empty (__main__.TestCuda) ... ok
test_DoubleTensor_qr_big (__main__.TestCuda) ... Segmentation fault (core dumped)

```
other tests fail as well:
```
Running test_autograd ...
...........................................................................................s..................................................................................................................................................................................s.......................................................s........................................................................................................................................................................................................................................................................................................E...............................................................................................................................................................s............................
======================================================================
ERROR: test_rnn_backward_to_input_but_not_parameters_cuda (__main__.TestAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_autograd.py", line 2301, in test_rnn_backward_to_input_but_not_parameters_cuda
    l = torch.nn.LSTM(2, 3).to(dev)
  File "/home/bueche/miniconda2/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 370, in to
    return self._apply(convert)
  File "/home/bueche/miniconda2/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 112, in _apply
    self.flatten_parameters()
  File "/home/bueche/miniconda2/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 105, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: CUDNN_STATUS_NOT_INITIALIZED

```

**Comment by bueche** [comment]
I think i'm back in business. loaded pytorch 0.4. as noted in this [discussion](https://discuss.pytorch.org/t/pytorch-no-longer-supports-this-gpu-because-it-is-too-old/13803/26).
