### ISSUE TITLE
Test timeout and assertion failure in distributed/rpc/test_tensorpipe_agent

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#59436]
## 🐛 Bug

When running the distributed/rpc/test_tensorpipe_agent I get a timeout and an assertion failure that is said to be reported here.

## To Reproduce

1. Compile PyTorch with CUDA 11 for A100 (CC 8.0)
1. run_test.py -i distributed/rpc/test_tensorpipe_agent

```
test_dist_autograd_sync_streams (__main__.TensorPipeTensorPipeDistAutogradTestWithSpawn) ... [E thread_pool.cpp:112] Exception in thread pool task: !completed() INTERNAL ASSERT FAILED at "../aten/src/ATen/cor
e/ivalue_inl.h":534, please report a bug to PyTorch. 
Exception raised from setErrorInternal at ../aten/src/ATen/core/ivalue_inl.h:534 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x57 (0x2ad28564e657 in /tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8
/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xa4f80c (0x2ad25e10480c in /tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0xa4f94e (0x2ad25e10494e in /tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0xd8d208 (0x2ad25e442208 in /tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0xd7d541 (0x2ad25e432541 in /tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: c10::ThreadPool::main_loop(unsigned long) + 0x285 (0x2ad28563eda5 in /tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #6: <unknown function> + 0xe2a40 (0x2ad24f5a1a40 in /scratch/ws/1/s3248973-EasyBuild/easybuild-rome/software/GCCcore/10.2.0/lib64/libstdc++.so.6)
frame #7: <unknown function> + 0x7ea5 (0x2ad232243ea5 in /lib64/libpthread.so.0)
frame #8: clone + 0x6d (0x2ad23275996d in /lib64/libc.so.6)

(same "Exception in thread pool task" repeated 3 more times)


Timing out after 400 seconds and killing subprocesses.
ERROR

======================================================================
ERROR: test_dist_autograd_sync_streams (__main__.TensorPipeTensorPipeDistAutogradTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 282, in wrapper
    self._join_processes(fn)
  File "/tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 399, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 440, in _check_return_codes
    raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
RuntimeError: Process 0 terminated or timed out after 400.0380153656006 seconds


----------------------------------------------------------------------
Ran 411 tests in 1763.226s

FAILED (errors=1, skipped=4)
distributed/rpc/test_tensorpipe_agent failed!
```

(I increased the timeout already to 400s)

## Expected behavior

Test succeeds

## Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `CMAKE_BUILD_TYPE=Release BUILD_TEST=0 PYTORCH_BUILD_VERSION=1.8.1 PYTORCH_BUILD_NUMBER=1 MAX_JOBS=$(nproc) BLAS=Eigen USE_FFMPEG=1 BUILD_CUSTOM_PROTOBUF=0 USE_IBVERBS=1 USE_CUDA=1 CUDNN_LIB_DIR=$EBROOTCUDNN/lib64 CUDNN_INCLUDE_DIR=$EBROOTCUDNN/include  USE_SYSTEM_NCCL=1 NCCL_INCLUDE_DIR=$EBROOTNCCL/include USE_METAL=0 USE_KINETO=0 python setup.py install`
 - Python version: 3.8.6
 - CUDA/cuDNN version: 11.1.1/8.0.4.30
 - GPU models and configuration: 8x A100

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd @agolynski @cbalioglu @gcramer23

**Comment by Flamefire** [comment]
So it looks like an assertion fails which sets an exception into a future which is already marked as completed which triggers the assertion failure seen above.
Printing the first assertion error message yields:
```
match.success() INTERNAL ASSERT FAILED at "../aten/src/ATen/core/ivalue.cpp":219, please report a bug to PyTorch. Cannot infer type of <class 'torch.testing._internal.distributed.rpc.dist_autograd_test.TensorPipeDistAutogradTest.MyRemoteCompute'>
:Only tensors and (possibly nested) tuples of tensors, lists, or dictsare supported as inputs or outputs of traced functions, but instead got value of type type.
Exception raised from getSubValues at ../aten/src/ATen/core/ivalue.cpp:219 (most recent call first):
```

So something is going very wrong here.
- The value in question derived from `torch.nn.Module`: https://github.com/pytorch/pytorch/blob/fc55290e5b128d82fa3854565a4d89f60d747fa7/torch/testing/_internal/distributed/rpc/dist_autograd_test.py#L2291
- This should at least trigger this: https://github.com/pytorch/pytorch/blob/fc55290e5b128d82fa3854565a4d89f60d747fa7/torch/csrc/jit/python/pybind_utils.h#L399-L403
- However it does not and falls through to the `tryToInferContainerType` which then fails.

I would very much like to debug this further, but due to this being distributed it is pretty much impossible to attach GDB.

**Comment by Flamefire** [comment]
@ezyang Was there any commit that fixed this? Would be great to know.
