### ISSUE TITLE
fatal error: torch/torch.h: No such file or directory

### ISSUE THREAD

**Issue by prigoyal** [pytorch/pytorch#5964]
I pulled master today and did following steps

```
python setup.py build develop
python test/run_test.py -v
```

and then I got this error:

```
/home/prigoyal/pytorch/torch/utils/cpp_extension.py:79: UserWarning:
Your compiler (g++ 4.8) may be ABI-incompatible with PyTorch.
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.
  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
building 'torch_test_cpp_extension' extension
creating build
creating build/temp.linux-x86_64-3.6
gcc -pthread -B /home/prigoyal/anaconda3/envs/pth-dev/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/prigoyal/pytorch/torch/lib/include -I/home/prigoyal/pytorch/torch/lib/include/TH -I/home/prigoyal/pytorch/torch/lib/include/THC -I/home/prigoyal/anaconda3/envs/pth-dev/include/python3.6m -c extension.cpp -o build/temp.linux-x86_64-3.6/extension.o -g -DTORCH_EXTENSION_NAME=torch_test_cpp_extension -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
extension.cpp:1:25: fatal error: torch/torch.h: No such file or directory
 #include <torch/torch.h>
                         ^
compilation terminated.
error: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "test/run_test.py", line 241, in <module>
    main()
  File "test/run_test.py", line 233, in main
    raise RuntimeError('{} failed!'.format(test_module))
RuntimeError: test_cpp_extensions.py failed!
```

**Comment by prigoyal** [comment]
cc @goldsborough for any insights :)

**Comment by goldsborough** [comment]
Right now you have to `build install` pytorch for that header to be installed correctly. There's three options:
1. Merge https://github.com/pytorch/pytorch/pull/5772 which fixes this and looks ready anyway,
2. `python setup.py build install`
3. `python run_test.py --exclude cpp_extensions`
(1) is probably best

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/5772

**Comment by YerongLi** [comment]
I cloned from the most recent version and build pytorch with
`python setup.py install`
But similar error as this
```
pytorch/test$ python run_test.py
...
writing manifest file 'torch_test_cpp_extension.egg-info/SOURCES.txt'
reading manifest file 'torch_test_cpp_extension.egg-info/SOURCES.txt'
writing manifest file 'torch_test_cpp_extension.egg-info/SOURCES.txt'
Copying torch_test_cpp_extension.egg-info to ./install/home/yerong/local/Anaconda3/envs/gpu/lib/python3.6/site-packages/torch_test_cpp_extension-0.0.0-py3.6.egg-info
running install_scripts
.s..Es
======================================================================
ERROR: test_jit_compile_extension (__main__.TestCppExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yerong/local/Anaconda3/envs/gpu/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 502, in verify_ninja_availability
    subprocess.check_call('ninja --version'.split(), stdout=devnull)
  File "/home/yerong/local/Anaconda3/envs/gpu/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/yerong/local/Anaconda3/envs/gpu/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/yerong/local/Anaconda3/envs/gpu/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/yerong/local/Anaconda3/envs/gpu/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_cpp_extensions.py", line 54, in test_jit_compile_extension
    verbose=True)
  File "/home/yerong/local/Anaconda3/envs/gpu/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 437, in load
    verify_ninja_availability()
  File "/home/yerong/local/Anaconda3/envs/gpu/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 504, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

----------------------------------------------------------------------
Ran 6 tests in 0.055s

FAILED (errors=1, skipped=2)
Traceback (most recent call last):
  File "run_test.py", line 256, in <module>
    main()
  File "run_test.py", line 248, in main
    raise RuntimeError('{} failed!'.format(test_module))
RuntimeError: test_cpp_extensions.py failed!
```

**Comment by goldsborough** [comment]
`RuntimeError: Ninja is required to load C++ extensions`

`pip install ninja`

**Comment by goldsborough** [comment]
I'll improve the error message
