### ISSUE TITLE
Failed to substitute string at {fn}:{lineno}; did you use triple quotes? on Python 3.8 and later

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#59705]
Steps to reproduce:
1. Build PyTorch on Python 3.8
2. Update a multiline expect test and try to use EXPECTTEST_ACCEPT=1

It doesn't work

```
======================================================================
FAIL: test_basic (__main__.TestPythonDispatch)                                                               
----------------------------------------------------------------------              
Traceback (most recent call last):
  File "test/test_python_dispatch.py", line 107, in test_basic
    self.assertExpectedInline('\n'.join(logs), '''\                                                          
  File "/data/users/ezyang/pytorch-tmp2/torch/testing/_internal/expecttest.py", line 233, in assertExpectedIn
line
    assert old != new, f"Failed to substitute string at {fn}:{lineno}; did you use triple quotes?"
AssertionError: Failed to substitute string at test/test_python_dispatch.py:107; did you use triple quotes?

----------------------------------------------------------------------
```

It looks like the reason is that Python is now reporting the error to be on the BEGINNING of the line rather than the end of the line, oopsies.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @Varal7

**Comment by ezyang** [comment]
https://bugs.python.org/issue37647 seems related
