### ISSUE TITLE
Kineto leaks file descriptors during normal `processName()` call

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#59746]
CUDA 10.2 builds on GHA started to fail earlier day after https://github.com/pytorch/pytorch/commit/0897df18a314f7a74dce9fcd065d6d7e4cab47d7 was merged in.

The error it fails with looks like ([logs](https://github.com/pytorch/pytorch/runs/2786062691?check_suite_focus=true)):
```
Traceback (most recent call last):
  File "test_foreach.py", line 994, in <module>
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 301, in run_tests
  File "/opt/conda/lib/python3.6/unittest/main.py", line 95, in __init__
  File "/opt/conda/lib/python3.6/unittest/main.py", line 256, in runTests
  File "/opt/conda/lib/python3.6/site-packages/xmlrunner/runner.py", line 112, in run
  File "/opt/conda/lib/python3.6/site-packages/xmlrunner/result.py", line 621, in generate_reports
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
OSError: [Errno 24] Too many open files: '/opt/conda/lib/python3.6/xml/dom/__init__.py'
Traceback (most recent call last):
  File "test/run_test.py", line 1254, in <module>
    main()
  File "test/run_test.py", line 1233, in main
    raise RuntimeError(err_message)
RuntimeError: test_foreach failed!
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @Varal7 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by seemethere** [comment]
Temporary fix here (to disable `foreach` tests for GHA):

https://github.com/pytorch/pytorch/pull/59748

**Comment by malfet** [comment]
Would increasing file limit inside GHA container work?

**Comment by malfet** [comment]
Should be fixed by https://github.com/pytorch/kineto/pull/281 and module update

**Comment by ngimel** [comment]
I reverted the PR a bit earlier, but I'd like to reland it. Let me know what the appropriate fix should be - skipping the test or increasing the file limit. Also, do you have an idea why there would be multiple files open? 
The tests themselves complain
```
  test_unary_slowpath__foreach_tan_cuda_float64 (__main__.TestForeachCUDA) ... Failed to read process name for pid 87572
Failed to read process name for pid 87572
Failed to read process name for pid 87572
Failed to read process name for pid 87572
```
but pass.

**Comment by malfet** [comment]
@ngimel appropriate fix would be to update kineto not to leak file descriptors and after that everything will be fine.
