### ISSUE TITLE
export torchscript module to onnx failed

### ISSUE THREAD

**Issue by seanxcwang** [pytorch/pytorch#59781]
## 🐛 Bug

export torchscript module to onnx failed

## To Reproduce

1. tranning res18 base model with cifar10
1. qat aware trainning
1. export to torchscript module

```
import torch
from tempfile import TemporaryFile

cpu_device = torch.device("cpu:0")
model = torch.jit.load('saved_models/resnet18_quantized_cifar10.pt', map_location=cpu_device)
inputs = model.graph.inputs()
print(inputs)

dummy_input = torch.ones(1, 3, 32, 32)

torch.onnx.export(model, dummy_input, 'quant.onnx', export_params=True,  operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK
```

## Expected behavior

get onnx model without error

## Environment

python 3.6.8
torch 1.8.1+cu111

## Additional context
```
/usr/local/lib64/python3.6/site-packages/torch/onnx/utils.py:264: UserWarning: `add_node_names' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `add_node_names` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
/usr/local/lib64/python3.6/site-packages/torch/onnx/utils.py:264: UserWarning: `do_constant_folding' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `do_constant_folding` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
/usr/local/lib64/python3.6/site-packages/torch/onnx/utils.py:348: UserWarning: Model has no forward function
  warnings.warn("Model has no forward function")
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    torch.onnx.export(model, dummy_input, 'quant.onnx', export_params=True,  operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
  File "/usr/local/lib64/python3.6/site-packages/torch/onnx/__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib64/python3.6/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib64/python3.6/site-packages/torch/onnx/utils.py", line 701, in _export
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib64/python3.6/site-packages/torch/onnx/utils.py", line 468, in _model_to_graph
    module=module)
  File "/usr/local/lib64/python3.6/site-packages/torch/onnx/utils.py", line 185, in _optimize_graph
    torch._C._jit_pass_onnx_unpack_quantized_weights(graph, params_dict)
RuntimeError: false INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/passes/onnx/unpack_quantized_weights.cpp":94, please report a bug to PyTorch. Unrecognized quantized operator while trying to compute q_scale for operator aten::flatten
```
======================
at "/pytorch/torch/csrc/jit/passes/onnx/unpack_quantized_weights.cpp", I found `flatten` is not in `noscale_ops`, may be that is why I export failed
attach is the torchscript model
[resnet18_quantized_cifar10.zip](https://github.com/pytorch/pytorch/files/6630036/resnet18_quantized_cifar10.zip)

cc @garymm @BowenBao @neginraoof @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @gmagogsfm

**Comment by seanxcwang** [comment]
I have tried to add `aten::flatten` and `aten::adaptive_avg_pool2d` to the function`getScaleFromInput`(unpack_quantized_weights.cpp), got another error "RuntimeError: bad optional access"

any suggestions will be helpful

**Comment by supriyar** [comment]
Hi @seanxcwang,
We currently don't support onnx export of quantized pytorch models using the flow above. The onnx export was designed specifically to convert pytorch quantized model to caffe2 (via onnx), so the intermediate onnx output is also specific to caffe2 operator signatures.

You could potentially try this using the flow https://github.com/pytorch/pytorch/pull/42835 without `torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK`

**Comment by jinfagang** [comment]
@supriyar  Hi, the pr link seems not work anymore:

```
import torch
from torch import quantization

from torchvision import models

qat_resnet18 = models.resnet18(pretrained=True).cuda()

qat_resnet18.qconfig = quantization.QConfig(
    activation=quantization.default_fake_quant,
    weight=quantization.default_per_channel_weight_fake_quant,
)
quantization.prepare_qat(qat_resnet18, inplace=True)
qat_resnet18.apply(quantization.enable_observer)
qat_resnet18.apply(quantization.enable_fake_quant)

dummy_input = torch.randn(16, 3, 224, 224).cuda()
_ = qat_resnet18(dummy_input)
for module in qat_resnet18.modules():
    if isinstance(module, quantization.FakeQuantize):
        module.calculate_qparams()
qat_resnet18.apply(quantization.disable_observer)

qat_resnet18.cuda()

input_names = ["actual_input_1"]
output_names = ["output1"]


torch.onnx.export(
    qat_resnet18, dummy_input, "quant_model.onnx", verbose=True, opset_version=13
)
```

Just got this error:

```
RuntimeError: Expected node type 'onnx::Constant' for argument 'scale' of node 'fake_quantize_per_tensor_affine', got 'prim::Param'.

```
