### ISSUE TITLE
DISABLED test_ddp_comparison_uneven_inputs (__main__.ProcessGroupDdpComparisonTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#59796]
https://app.circleci.com/pipelines/github/pytorch/pytorch/333542/workflows/d747e3b8-0023-4952-8f3d-a126536843bf/jobs/14023171/steps

```
Jun 09 23:10:42 ======================================================================
Jun 09 23:10:42 ERROR [105.096s]: test_ddp_comparison_uneven_inputs (__main__.ProcessGroupDdpComparisonTestWithSpawn)
Jun 09 23:10:42 ----------------------------------------------------------------------
Jun 09 23:10:42 Traceback (most recent call last):
Jun 09 23:10:42   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 398, in wrapper
Jun 09 23:10:42     self._join_processes(fn)
Jun 09 23:10:42   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 590, in _join_processes
Jun 09 23:10:42     self._check_return_codes(elapsed_time)
Jun 09 23:10:42   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 638, in _check_return_codes
Jun 09 23:10:42     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Jun 09 23:10:42 RuntimeError: Process 0 terminated or timed out after 105.05770897865295 seconds
```

```
Jun 09 22:57:58 Process 0 timed out with traceback: 
Jun 09 22:57:58 
Jun 09 22:57:58 Thread 0x00007f84c5ffb700 (most recent call first):
Jun 09 22:57:58 
Jun 09 22:57:58 Current thread 0x00007f84f65d5700 (most recent call first):
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 483 in _event_listener
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/threading.py", line 864 in run
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/threading.py", line 916 in _bootstrap_inner
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/threading.py", line 884 in _bootstrap
Jun 09 22:57:58 
Jun 09 22:57:58 Thread 0x00007f8517e74740 (most recent call first):
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/threading.py", line 295 in wait
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/threading.py", line 551 in wait
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 213 in _all_gather
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 77 in wrapper
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 277 in _wait_all_workers
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 77 in wrapper
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 334 in shutdown
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 77 in wrapper
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 103 in new_test_method
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400 in wrapper
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516 in run_test
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 503 in _run
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93 in run
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258 in _bootstrap
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 118 in _main
Jun 09 22:57:58   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 105 in spawn_main
Jun 09 22:57:58   File "<string>", line 1 in <module>
Jun 09 22:57:58 
Jun 09 22:58:03 Could not retrieve traceback for timed out process: 1
Jun 09 22:58:03 Process 2 timed out with traceback: 
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by mrshenli** [comment]
Closed by #60407
