### ISSUE TITLE
DISABLED test_ddp_dist_autograd_local_vs_remote (__main__.ProcessGroupDdpComparisonTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#59792]
https://app.circleci.com/pipelines/github/pytorch/pytorch/333902/workflows/a5fc7b35-61a3-4f11-a06c-b243b3741796/jobs/14036193/steps

```
Jun 10 06:09:14 ======================================================================
Jun 10 06:09:14 ERROR [62.080s]: test_ddp_dist_autograd_local_vs_remote (__main__.ProcessGroupDdpComparisonTestWithSpawn)
Jun 10 06:09:14 ----------------------------------------------------------------------
Jun 10 06:09:14 Traceback (most recent call last):
Jun 10 06:09:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 398, in wrapper
Jun 10 06:09:14     self._join_processes(fn)
Jun 10 06:09:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 590, in _join_processes
Jun 10 06:09:14     self._check_return_codes(elapsed_time)
Jun 10 06:09:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 633, in _check_return_codes
Jun 10 06:09:14     raise RuntimeError(error)
Jun 10 06:09:14 RuntimeError: Process 1 exited with error code 10 and exception:
Jun 10 06:09:14 Traceback (most recent call last):
Jun 10 06:09:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 10 06:09:14     getattr(self, test_name)()
Jun 10 06:09:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 10 06:09:14     fn()
Jun 10 06:09:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
Jun 10 06:09:14     return_value = old_test_method(self, *arg, **kwargs)
Jun 10 06:09:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 633, in test_ddp_dist_autograd_local_vs_remote
Jun 10 06:09:14     layer1.weight = remote_layer1.module_rref.to_here().weight
Jun 10 06:09:14 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
```

```
Jun 10 05:54:56   test_ddp_dist_autograd_local_vs_remote (__main__.ProcessGroupDdpComparisonTestWithSpawn) ... /opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/__init__.py:163: UserWarning: RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend. PyTorch v1.9 will be the last release that carries PROCESS_GROUP RPC backend. If you have concerns or suggestions please comment in https://github.com/pytorch/pytorch/issues/55615
Jun 10 05:54:56   "RPC was initialized with the PROCESS_GROUP backend which is "
Jun 10 05:54:56 ERROR:torch.testing._internal.common_distributed:Caught exception: 
Jun 10 05:54:56 Traceback (most recent call last):
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 10 05:54:56     getattr(self, test_name)()
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 10 05:54:56     fn()
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
Jun 10 05:54:56     return_value = old_test_method(self, *arg, **kwargs)
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 633, in test_ddp_dist_autograd_local_vs_remote
Jun 10 05:54:56     layer1.weight = remote_layer1.module_rref.to_here().weight
Jun 10 05:54:56 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Jun 10 05:54:56  exiting process with exit code: {MultiProcessTestCase.TEST_ERROR_EXIT_CODE}
Jun 10 05:54:56 /opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/__init__.py:163: UserWarning: RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend. PyTorch v1.9 will be the last release that carries PROCESS_GROUP RPC backend. If you have concerns or suggestions please comment in https://github.com/pytorch/pytorch/issues/55615
Jun 10 05:54:56   "RPC was initialized with the PROCESS_GROUP backend which is "
Jun 10 05:54:56 ERROR:torch.testing._internal.common_distributed:Caught exception: 
Jun 10 05:54:56 Traceback (most recent call last):
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 10 05:54:56     getattr(self, test_name)()
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 10 05:54:56     fn()
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
Jun 10 05:54:56     return_value = old_test_method(self, *arg, **kwargs)
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 654, in test_ddp_dist_autograd_local_vs_remote
Jun 10 05:54:56     args=(remote_layer1.module_rref, context_id),
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
Jun 10 05:54:56     return func(*args, **kwargs)
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 757, in rpc_sync
Jun 10 05:54:56     return fut.wait()
Jun 10 05:54:56 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Jun 10 05:54:56  exiting process with exit code: {MultiProcessTestCase.TEST_ERROR_EXIT_CODE}
Jun 10 05:54:56 /opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/__init__.py:163: UserWarning: RPC was initialized with the PROCESS_GROUP backend which is deprecated and slated to be removed and superseded by the TENSORPIPE backend. It is recommended to migrate to the TENSORPIPE backend. PyTorch v1.9 will be the last release that carries PROCESS_GROUP RPC backend. If you have concerns or suggestions please comment in https://github.com/pytorch/pytorch/issues/55615
Jun 10 05:54:56   "RPC was initialized with the PROCESS_GROUP backend which is "
Jun 10 05:54:56 ERROR:torch.testing._internal.common_distributed:Caught exception: 
Jun 10 05:54:56 Traceback (most recent call last):
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 10 05:54:56     getattr(self, test_name)()
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 10 05:54:56     fn()
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
Jun 10 05:54:56     return_value = old_test_method(self, *arg, **kwargs)
Jun 10 05:54:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 633, in test_ddp_dist_autograd_local_vs_remote
Jun 10 05:54:56     layer1.weight = remote_layer1.module_rref.to_here().weight
Jun 10 05:54:56 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Jun 10 05:54:56  exiting process with exit code: {MultiProcessTestCase.TEST_ERROR_EXIT_CODE}
Jun 10 05:54:56 Process 1 terminated with exit code 10, terminating remaining processes.
Jun 10 05:54:56 ERROR (62.080s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by mrshenli** [comment]
closed by #60407
