### ISSUE TITLE
DISABLED test_backward_rref (__main__.TensorPipeDistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#59798]
https://app.circleci.com/pipelines/github/pytorch/pytorch/333382/workflows/1c7a602f-7ee9-48a2-ae22-c13c21ef21e1/jobs/14017608/steps

```
Jun 09 21:32:31 ======================================================================
Jun 09 21:32:31 ERROR [105.097s]: test_backward_rref (__main__.TensorPipeDistAutogradTestWithSpawn)
Jun 09 21:32:31 ----------------------------------------------------------------------
Jun 09 21:32:31 Traceback (most recent call last):
Jun 09 21:32:31   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 398, in wrapper
Jun 09 21:32:31     self._join_processes(fn)
Jun 09 21:32:31   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 590, in _join_processes
Jun 09 21:32:31     self._check_return_codes(elapsed_time)
Jun 09 21:32:31   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 638, in _check_return_codes
Jun 09 21:32:31     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Jun 09 21:32:31 RuntimeError: Process 0 terminated or timed out after 105.03704762458801 seconds
```

```
Jun 09 21:15:49   test_backward_rref (__main__.TensorPipeDistAutogradTestWithSpawn) ... Failed to respond to 'Shutdown Proceed' in time, got error RPCErr:1:RPC ran for more than set timeout (5000 ms) and will now be marked with an error
Jun 09 21:15:49 Failed to respond to 'Shutdown Proceed' in time, got error RPCErr:1:RPC ran for more than set timeout (5000 ms) and will now be marked with an error
Jun 09 21:15:49 Failed to respond to 'Shutdown Proceed' in time, got error RPCErr:1:RPC ran for more than set timeout (5000 ms) and will now be marked with an error
Jun 09 21:16:44 [E request_callback_no_python.cpp:552] Received error while processing request type 275: Unexpected end of pickler archive.
Jun 09 21:16:44 Exception raised from readSlowWithBuffer at /var/lib/jenkins/workspace/torch/csrc/jit/serialization/unpickler.cpp:756 (most recent call first):
Jun 09 21:16:44 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7fa9a19ebdcb in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 09 21:16:44 frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0xd1 (0x7fa9a19e7761 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 09 21:16:44 frame #2: <unknown function> + 0x3ea6768 (0x7fa9b514f768 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #3: torch::jit::Unpickler::run() + 0xdf (0x7fa9b515a49f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #4: torch::jit::Unpickler::parse_ivalue() + 0x2e (0x7fa9b515a60e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #5: torch::jit::unpickle(std::function<unsigned long (char*, unsigned long)>, std::function<c10::StrongTypePtr (c10::QualifiedName const&)>, c10::ArrayRef<at::Tensor>) + 0x22f (0x7fa9b512a9cf in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #6: torch::jit::unpickle(char const*, unsigned long, std::function<c10::StrongTypePtr (c10::QualifiedName const&)>, c10::ArrayRef<at::Tensor>) + 0xd0 (0x7fa9b512af00 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #7: torch::distributed::autograd::CleanupAutogradContextReq::fromMessage(torch::distributed::rpc::Message const&) + 0xcb (0x7fa9b53c788b in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #8: torch::distributed::rpc::deserializeRequest(torch::distributed::rpc::Message const&) + 0x1ed (0x7fa9b5412efd in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #9: torch::distributed::rpc::RequestCallbackNoPython::processMessage(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x7e (0x7fa9b53e1e1e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #10: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x57 (0x7fa9b53dd4d7 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #11: <unknown function> + 0xe2ceb2 (0x7fa9be15eeb2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Jun 09 21:16:44 frame #12: c10::ThreadPool::main_loop(unsigned long) + 0x2db (0x7fa9a19bcf6b in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 09 21:16:44 frame #13: <unknown function> + 0xc819d (0x7fa9c180019d in /opt/conda/lib/libstdc++.so.6)
Jun 09 21:16:44 frame #14: <unknown function> + 0x76ba (0x7fa9fcb916ba in /lib/x86_64-linux-gnu/libpthread.so.0)
Jun 09 21:16:44 frame #15: clone + 0x6d (0x7fa9fc8c751d in /lib/x86_64-linux-gnu/libc.so.6)
Jun 09 21:16:44 
Jun 09 21:16:44 [E request_callback_no_python.cpp:552] Received error while processing request type 267: Unexpected end of pickler archive.
Jun 09 21:16:44 Exception raised from readSlowWithBuffer at /var/lib/jenkins/workspace/torch/csrc/jit/serialization/unpickler.cpp:756 (most recent call first):
Jun 09 21:16:44 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7fa9a19ebdcb in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 09 21:16:44 frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0xd1 (0x7fa9a19e7761 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 09 21:16:44 frame #2: <unknown function> + 0x3ea6768 (0x7fa9b514f768 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #3: torch::jit::Unpickler::run() + 0xdf (0x7fa9b515a49f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #4: torch::jit::Unpickler::parse_ivalue() + 0x2e (0x7fa9b515a60e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #5: torch::jit::unpickle(std::function<unsigned long (char*, unsigned long)>, std::function<c10::StrongTypePtr (c10::QualifiedName const&)>, c10::ArrayRef<at::Tensor>) + 0x22f (0x7fa9b512a9cf in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #6: torch::jit::unpickle(char const*, unsigned long, std::function<c10::StrongTypePtr (c10::QualifiedName const&)>, c10::ArrayRef<at::Tensor>) + 0xd0 (0x7fa9b512af00 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #7: <unknown function> + 0x4153beb (0x7fa9b53fcbeb in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #8: torch::distributed::rpc::ForkMessageBase::fromMessage(torch::distributed::rpc::Message const&, torch::distributed::rpc::MessageType) + 0x28 (0x7fa9b53fe2d8 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #9: torch::distributed::rpc::RRefUserDelete::fromMessage(torch::distributed::rpc::Message const&) + 0x2c (0x7fa9b53fe43c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #10: torch::distributed::rpc::deserializeRequest(torch::distributed::rpc::Message const&) + 0x14d (0x7fa9b5412e5d in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #11: torch::distributed::rpc::RequestCallbackNoPython::processMessage(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x7e (0x7fa9b53e1e1e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #12: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x57 (0x7fa9b53dd4d7 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 09 21:16:44 frame #13: <unknown function> + 0xe2ceb2 (0x7fa9be15eeb2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Jun 09 21:16:44 frame #14: c10::ThreadPool::main_loop(unsigned long) + 0x2db (0x7fa9a19bcf6b in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 09 21:16:44 frame #15: <unknown function> + 0xc819d (0x7fa9c180019d in /opt/conda/lib/libstdc++.so.6)
Jun 09 21:16:44 frame #16: <unknown function> + 0x76ba (0x7fa9fcb916ba in /lib/x86_64-linux-gnu/libpthread.so.0)
Jun 09 21:16:44 frame #17: clone + 0x6d (0x7fa9fc8c751d in /lib/x86_64-linux-gnu/libc.so.6)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd @agolynski @cbalioglu @gcramer23

**Comment by mrshenli** [comment]
Same error is also reported in #59768 cc @pritamdamania87

**Comment by clee2000** [comment]
I'm fairly sure this test was either renamed or deleted
