### ISSUE TITLE
DISABLED test_backward_rref_nested (__main__.TensorPipeDistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#59794]
https://app.circleci.com/pipelines/github/pytorch/pytorch/333990/workflows/e14e5809-c30d-452d-b4db-f88643749354/jobs/14041353/steps

```
Jun 10 11:57:18 ======================================================================
Jun 10 11:57:18 ERROR [105.098s]: test_backward_rref_nested (__main__.TensorPipeDistAutogradTestWithSpawn)
Jun 10 11:57:18 ----------------------------------------------------------------------
Jun 10 11:57:18 Traceback (most recent call last):
Jun 10 11:57:18   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 398, in wrapper
Jun 10 11:57:18     self._join_processes(fn)
Jun 10 11:57:18   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 590, in _join_processes
Jun 10 11:57:18     self._check_return_codes(elapsed_time)
Jun 10 11:57:18   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 638, in _check_return_codes
Jun 10 11:57:18     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Jun 10 11:57:18 RuntimeError: Process 0 terminated or timed out after 105.03801655769348 seconds
```

```
Jun 10 11:41:35 [E request_callback_no_python.cpp:552] Received error while processing request type 275: Unexpected end of pickler archive.
Jun 10 11:41:35 Exception raised from readSlowWithBuffer at /var/lib/jenkins/workspace/torch/csrc/jit/serialization/unpickler.cpp:756 (most recent call first):
Jun 10 11:41:35 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7fed005eb81b in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 10 11:41:35 frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0xd1 (0x7fed005e71b1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 10 11:41:35 frame #2: <unknown function> + 0x3ead658 (0x7fed13d52658 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 10 11:41:35 frame #3: torch::jit::Unpickler::run() + 0xdf (0x7fed13d5d38f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 10 11:41:35 frame #4: torch::jit::Unpickler::parse_ivalue() + 0x2e (0x7fed13d5d4fe in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 10 11:41:35 frame #5: torch::jit::unpickle(std::function<unsigned long (char*, unsigned long)>, std::function<c10::StrongTypePtr (c10::QualifiedName const&)>, c10::ArrayRef<at::Tensor>) + 0x22f (0x7fed13d2d8bf in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 10 11:41:35 frame #6: torch::jit::unpickle(char const*, unsigned long, std::function<c10::StrongTypePtr (c10::QualifiedName const&)>, c10::ArrayRef<at::Tensor>) + 0xd0 (0x7fed13d2ddf0 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 10 11:41:35 frame #7: torch::distributed::autograd::CleanupAutogradContextReq::fromMessage(torch::distributed::rpc::Message const&) + 0xcb (0x7fed13fca57b in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 10 11:41:35 frame #8: torch::distributed::rpc::deserializeRequest(torch::distributed::rpc::Message const&) + 0x1ed (0x7fed1401580d in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 10 11:41:35 frame #9: torch::distributed::rpc::RequestCallbackNoPython::processMessage(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x7e (0x7fed13fe4a0e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 10 11:41:35 frame #10: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x57 (0x7fed13fe01c7 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 10 11:41:35 frame #11: <unknown function> + 0xe2b422 (0x7fed1cd7a422 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Jun 10 11:41:35 frame #12: c10::ThreadPool::main_loop(unsigned long) + 0x2db (0x7fed005bc9bb in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 10 11:41:35 frame #13: <unknown function> + 0xc819d (0x7fed2041a19d in /opt/conda/lib/libstdc++.so.6)
Jun 10 11:41:35 frame #14: <unknown function> + 0x76ba (0x7fed5b7ab6ba in /lib/x86_64-linux-gnu/libpthread.so.0)
Jun 10 11:41:35 frame #15: clone + 0x6d (0x7fed5b4e151d in /lib/x86_64-linux-gnu/libc.so.6)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd @agolynski @cbalioglu @gcramer23

**Comment by clee2000** [comment]
I'm fairly sure this test was either renamed or deleted
