### ISSUE TITLE
DISABLED test_dist_autograd_sync_streams (__main__.TensorPipeTensorPipeCudaDistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#59793]
https://app.circleci.com/pipelines/github/pytorch/pytorch/333666/workflows/83f83244-bbfb-4acc-91f8-29fe1a19d6d7/jobs/14028695/steps

```
Jun 10 00:34:27 ======================================================================
Jun 10 00:34:27 ERROR [5.038s]: test_dist_autograd_sync_streams (__main__.TensorPipeTensorPipeCudaDistAutogradTestWithSpawn)
Jun 10 00:34:27 ----------------------------------------------------------------------
Jun 10 00:34:27 Traceback (most recent call last):
Jun 10 00:34:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 398, in wrapper
Jun 10 00:34:27     self._join_processes(fn)
Jun 10 00:34:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 590, in _join_processes
Jun 10 00:34:27     self._check_return_codes(elapsed_time)
Jun 10 00:34:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 633, in _check_return_codes
Jun 10 00:34:27     raise RuntimeError(error)
Jun 10 00:34:27 RuntimeError: Process 3 exited with error code 10 and exception:
Jun 10 00:34:27 Traceback (most recent call last):
Jun 10 00:34:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 10 00:34:27     getattr(self, test_name)()
Jun 10 00:34:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 10 00:34:27     fn()
Jun 10 00:34:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 93, in wrapper
Jun 10 00:34:27     return func(*args, **kwargs)
Jun 10 00:34:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2342, in test_dist_autograd_sync_streams
Jun 10 00:34:27     self.assertEqual(input.grad, grads[input])
Jun 10 00:34:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1361, in assertEqual
Jun 10 00:34:27     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
Jun 10 00:34:27   File "/opt/conda/lib/python3.6/unittest/case.py", line 682, in assertTrue
Jun 10 00:34:27     raise self.failureException(msg)
Jun 10 00:34:27 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 0 element(s) (out of 10000000) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.0 (0.7901588082313538 vs. 0.7901588082313538), which occurred at index (0, 0).
```

```
Jun 10 00:34:20   test_dist_autograd_sync_streams (__main__.TensorPipeTensorPipeCudaDistAutogradTestWithSpawn) ... Caught exception: 
Jun 10 00:34:20 Traceback (most recent call last):
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 10 00:34:20     getattr(self, test_name)()
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 10 00:34:20     fn()
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 93, in wrapper
Jun 10 00:34:20     return func(*args, **kwargs)
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2342, in test_dist_autograd_sync_streams
Jun 10 00:34:20     self.assertEqual(input.grad, grads[input])
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1361, in assertEqual
Jun 10 00:34:20     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/unittest/case.py", line 682, in assertTrue
Jun 10 00:34:20     raise self.failureException(msg)
Jun 10 00:34:20 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 0 element(s) (out of 10000000) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.0 (0.7901588082313538 vs. 0.7901588082313538), which occurred at index (0, 0).
Jun 10 00:34:20  exiting process with exit code: {MultiProcessTestCase.TEST_ERROR_EXIT_CODE}
Jun 10 00:34:20 [E request_callback_no_python.cpp:552] Received error while processing request type 271: TypeError: 'NoneType' object is not callable
Jun 10 00:34:20 
Jun 10 00:34:20 At:
Jun 10 00:34:20   /opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/internal.py(169): deserialize
Jun 10 00:34:20   /opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/internal.py(190): deserialize
Jun 10 00:34:20 
Jun 10 00:34:20 [W tensorpipe_agent.cpp:797] RPC agent for worker2 encountered error when reading incoming request from worker3: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
Jun 10 00:34:20 [W tensorpipe_agent.cpp:797] RPC agent for worker0 encountered error when reading incoming request from worker3: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
Jun 10 00:34:20 [W tensorpipe_agent.cpp:1002] RPC agent for worker2 encountered error when reading incoming response from worker3: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
Jun 10 00:34:20 [W tensorpipe_agent.cpp:978] RPC agent for worker2 encountered error when sending outgoing request #52 to worker3: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
Jun 10 00:34:20 Caught exception: 
Jun 10 00:34:20 Traceback (most recent call last):
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 10 00:34:20     getattr(self, test_name)()
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 10 00:34:20     fn()
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 93, in wrapper
Jun 10 00:34:20     return func(*args, **kwargs)
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2336, in test_dist_autograd_sync_streams
Jun 10 00:34:20     result = local_compute(input)
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1054, in _call_impl
Jun 10 00:34:20     return forward_call(*input, **kwargs)
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py", line 2305, in forward
Jun 10 00:34:20     return self.next_stage.rpc_sync().forward(input)
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/rref_proxy.py", line 34, in _invoke_rpc
Jun 10 00:34:20     timeout=timeout
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
Jun 10 00:34:20     return func(*args, **kwargs)
Jun 10 00:34:20   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 757, in rpc_sync
Jun 10 00:34:20     return fut.wait()
Jun 10 00:34:20 RuntimeError: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
Jun 10 00:34:20  exiting process with exit code: {MultiProcessTestCase.TEST_ERROR_EXIT_CODE}
Jun 10 00:34:20 Process 3 terminated with exit code 10, terminating remaining processes.
Jun 10 00:34:20 ERROR (5.038s)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by pritamdamania87** [comment]
The assertion error for this is really weird:

```
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 0 element(s) (out of 10000000) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.0 (0.7901588082313538 vs. 0.7901588082313538), which occurred at index (0, 0).
```

cc @mruberry Was wondering if you knew why would we see an error like this? It seems like the tensors are actually equal yet the framework complains they aren't?

**Comment by mrshenli** [comment]
I recall hitting similar errors before, and the reason was that the comparison is done in CUDA and the print requiring pulling it to CPU. So the compared value and the print value can be different.

**Comment by H-Huang** [comment]
potential fix in https://github.com/pytorch/pytorch/pull/60127

**Comment by mcarilli** [comment]
https://github.com/pytorch/pytorch/pull/60127 definitely isn't a fix for the funny
```
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 0 element(s) (out of 10000000) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.0 (0.7901588082313538 vs. 0.7901588082313538), which occurred at index (0, 0).
```
(although I saw the same thing, seems like a common symptom when assertEqual is used to check race conditions, and I agreed with https://github.com/pytorch/pytorch/issues/59793#issuecomment-861600946).

https://github.com/pytorch/pytorch/pull/60127 adds syncs needed when `torch.autograd.grad` creates grads out of place on side streams. If there's an analogous bug in distributed autograd, you should definitely skim https://github.com/pytorch/pytorch/pull/60127 to see if it helps (which it might, depending what parts of engine.cpp distributed autograd recycles) or if the solution can be ported.

**Comment by mrshenli** [comment]
@malfet this issue doesn't seem to skip the test on master. Is there a recent change on how we should disable tests?

https://app.circleci.com/pipelines/github/pytorch/pytorch/340439/workflows/5cccc696-da6a-49fb-9c7e-049db4443532/jobs/14319080/steps

https://app.circleci.com/pipelines/github/pytorch/pytorch/340521/workflows/1857a0c8-8080-49ae-a35c-203fc13590c5/jobs/14325566/steps
