### ISSUE TITLE
Python scalars should be promoted to the same `dtype` as the respective tensor

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#59868]
The [array API specification stipulates](https://data-apis.org/array-api/latest/API_specification/type_promotion.html#mixing-arrays-with-python-scalars) that for binary operations involving a tensor and a Python scalar, the scalar needs to be converted to the same `dtype` as the tensor before the operation is performed. PyTorch casts the scalar to a tensor based on its `dtype` and afterwards performs the default type promotion for the operator. 

This can lead to overflows if the tensor `dtype` can hold the values of the scalar, but the automatically determined `dtype` cannot.

```python
>>> torch.tensor(0, dtype=torch.float32) + 2.0 ** 63
tensor(9.2234e+18)
>>> torch.tensor(0, dtype=torch.float32) + 2 ** 63
RuntimeError: Overflow when unpacking long
```

**Comment by rgommers** [comment]
So the `2.0 ** 63` result is correct here (retains `float32` dtype), but the logic for the `2 ** 63` case seems to be:

1. Convert Python scalar to a tensor without looking at the dtype of the other operand (`torch.tensor(2 ** 63)` raises the "unpacking long" exception)
2. Then do `tensor1 + tensor2` using the regular tensor type promotion rules.

I'm sure there's older discussions about how to handle `tensor <op> scalar` that were had here - can you try to dig those up? I suspect the PyTorch logic is simpler to implement, and the trade-off is that in corner cases the intermediate dtype can cause an issue like the one you show here.

**Comment by mruberry** [comment]
> The [array API specification stipulates](https://data-apis.org/array-api/latest/API_specification/type_promotion.html#mixing-arrays-with-python-scalars) that for binary operations involving a tensor and a Python scalar, the scalar needs to be converted to the same `dtype` as the tensor before the operation is performed. 

This is not entirely accurate. The conversion is only required when the scalar has a "compatible type and value." 

>PyTorch casts the scalar to a tensor based on its `dtype` and afterwards performs the default type promotion for the operator.

Correct. Stepping back, I think we may need to more carefully review the type promotion rules the Python Array API proposes. Type promotion is very complicated and poorly documented wherever it's implemented. Even for binary elementwise operators there are multiple kinds of type promotion. cc @rgommers 

First, let's talk about what type promotion is. "Type promotion" is (1) the selection of a "common computation type" to perform  an operation in and (2) the promotion of inputs to that common computation type. Now, let's talk about different kinds of type promotion for the three classes of operation it's most naturally defined for: unary elementwise, binary elementwise, and reduction operations.

For all of these op classes there are two types of type promotion:

- "normal" type promotion (ex. abs, add, sum)
- "require floating" type promotion (ex. sin, true_divide, mean)

Note also that type promotion is about the INPUTS to a function, not the OUTPUTS nor the ACCUMULATION TYPE for reductions. This makes the rules for actually determining an output even more complicated!

Type promotion for other types of operations gets a lot trickier because these operations often don't belong to a significant natural "class" or some of their inputs would naturally participate in type promotion but others wouldn't. For example, some operations require that a particular tensor be an index tensor, and the type of that index tensor has to be int64, so it doesn't participate in type promotion.

What I would like to suggest is that the Python Array API define type promotion for the three classes where its most natural, separately define accumulation/output types (for reductions and "test" functions which always return bool, for example), and not define type promotion for other operators, even where it's straightforward to define (like stack and concat). If the Array API REALLY wants to define type promotion for those ops (which makes it harder to track down dtype-related errors, which I think is much more of an issue for deep learning) then we should think about some way to express that class naturally.

From a deep learning perspective, I wonder if PyTorch would have been better off without type promotion at all. It's often important to be very precise about dtypes. It's the classic "easier to compile but harder to verify your code works properly" conundrum for programming languages. We might add a "strict typing mode" to PyTorch in the future to deal with, but these global flags are not silver bullets because libraries built on PyTorch may or may not support them.

**Comment by rgommers** [comment]
> First, let's talk about what type promotion is. "Type promotion" is (1) the selection of a "common computation type" to perform an operation in and (2) the promotion of inputs to that common computation type.

This is a definition I don't agree with. It's about determining the output dtype from input dtypes. This is the user-observable behavior. If inside the compution you want to, for example, do a temporary upcast to a higher-precision dtype to avoid floating point errors, and then downcast again at the end, that's perfectly fine.

In the vast majority of cases, computation dtype and output dtype will be the same. But an implementer of a function should have the freedom to do something different, for performance or accuracy reasons.

Xref https://numpy.org/doc/stable/reference/ufuncs.html#casting-rules, which starts with _"In NumPy 1.6.0, a type promotion API was created to encapsulate the mechanism for determining output types."_

This is also consistent with the design goal of the array API standard to not prescribe anything about how to implement functionality - all it cares about is syntax (like function signatures) and semantics (what is the expected output - shapes, dtypes, numerical results), and not performance, algorithmic choices or the precision with which to obtain numerical results.

> The Python Array API simplifies the input types to just scalars and tensors, consistent with JAX and NumPy today.

Actually NumPy has a whole separate class of objects called "array scalars", which are not in the array API design. And value-based casting. Both of those don't matter much for this discussion (and are considered design mistakes in NumPy), but I just want to point out that's it's not "let's do what NumPy does" - the casting rules of the array API are actually closer to those of PyTorch than those of NumPy.

> What I would like to suggest is that the Python Array API define type promotion for the three classes where its most natural, separately define accumulation/output types (for reductions and "test" functions which always return bool, for example), and not define type promotion for other operators,

This is definitely worth considering. We'll need to review what operators we're talking about here. And then if the above makes sense, change the design and make the test suite more strict.

> From a deep learning perspective, I wonder if PyTorch would have been better off without type promotion at all.

That goes a bit far I'd say:) That's about what TensorFlow does, and it makes for a very uncomfortable user experience.

**Comment by mruberry** [comment]
> > First, let's talk about what type promotion is. "Type promotion" is (1) the selection of a "common computation type" to perform an operation in and (2) the promotion of inputs to that common computation type.
> 
> This is a definition I don't agree with. It's about determining the output dtype from input dtypes. This is the user-observable behavior. If inside the compution you want to, for example, do a temporary upcast to a higher-precision dtype to avoid floating point errors, and then downcast again at the end, that's perfectly fine.
> 
> In the vast majority of cases, computation dtype and output dtype will be the same. But an implementer of a function should have the freedom to do something different, for performance or accuracy reasons.
> 
> Xref https://numpy.org/doc/stable/reference/ufuncs.html#casting-rules, which starts with _"In NumPy 1.6.0, a type promotion API was created to encapsulate the mechanism for determining output types."_
> 
> This is also consistent with the design goal of the array API standard to not prescribe anything about how to implement functionality - all it cares about is syntax (like function signatures) and semantics (what is the expected output - shapes, dtypes, numerical results), and not performance, algorithmic choices or the precision with which to obtain numerical results.

Broadening "type promotion" to this is OK (especially when not supporting the out= kwarg) but then we're going to have to define more classes of type promotion to handle accumulate types and operations that always return bool or a specific dtype. 

> > The Python Array API simplifies the input types to just scalars and tensors, consistent with JAX and NumPy today.
> 
> Actually NumPy has a whole separate class of objects called "array scalars", which are not in the array API design. And value-based casting. Both of those don't matter much for this discussion (and are considered design mistakes in NumPy), but I just want to point out that's it's not "let's do what NumPy does" - the casting rules of the array API are actually closer to those of PyTorch than those of NumPy.

Good point, NumPy does have some additional stuff that I neglected to mention.

**Comment by rgommers** [comment]
>  nor the ACCUMULATION TYPE for reductions

I tried to investigate this a bit to see if there's a sensible (set of) rule(s) to define. That doesn't seem easy. Trying a collection of reduction ops (https://pytorch.org/docs/stable/torch.html#reduction-ops):

```python
>>> t = torch.tensor([1, 2, 3], dtype=torch.int8)
>>> torch.std(t)
Traceback (most recent call last):
  File "<ipython-input-17-b1fc1aba9e65>", line 1, in <module>
    torch.std(t)
RuntimeError: std and var only support floating point and complex dtypes

>>> torch.all(t)
tensor(True)

>>> torch.mean(t)
Traceback (most recent call last):
  File "<ipython-input-20-96a18be4908f>", line 1, in <module>
    torch.mean(t)
RuntimeError: Can only calculate the mean of floating types. Got Long instead.

>>> torch.mode(t)
torch.return_types.mode(
values=tensor(1, dtype=torch.int8),
indices=tensor(0))
>>> torch.nansum(t)
tensor(6)
>>> torch.nansum(t).dtype
torch.int64
```

There's no systematic behavior I can discern there.

NumPy is a little more consistent, but there's still 4 flavors for the output: keep input dtype, return a bool dtype, return the default integer dtype, or return the default floating-point dtype:

```python
>>> x = np.arange(3, dtype=np.int8)
>>> np.sum(x)
3
>>> np.sum(x, keepdims=True)  # use keepdims so we retain an array whose dtype we can check
array([3])
>>> np.sum(x, keepdims=True).dtype
dtype('int64')
>>> np.std(x, keepdims=True).dtype
dtype('float64')
>>> np.var(x, keepdims=True).dtype
dtype('float64')
>>> np.mean(x, keepdims=True).dtype
dtype('float64')
>>> np.max(x, keepdims=True).dtype
dtype('int8')
>>> np.median(x, keepdims=True).dtype
dtype('float64')
>>> np.any(x, keepdims=True).dtype
dtype('bool')
```

**Comment by rgommers** [comment]
I opened https://github.com/data-apis/array-api/issues/202 for the promotion rules for reduction topic.
