### ISSUE TITLE
Inconsistent CUDA errors using PyTorch Docker image

### ISSUE THREAD

**Issue by adamtupper** [pytorch/pytorch#59890]
## 🐛 Bug

I have been developing using Docker and PyTorch (for easy deployment) and I have been encountering inconsistent CUDA errors, namely:

```
RuntimeError: CUDA error: an illegal memory access was encountered
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

What has been difficult is that I haven't been able to identify a pattern to the errors, occasionally there are none at all. As such, I'm not sure whether this is a configuration issue or a bug (and where that bug might lie). I've tried to see whether using different versions of the `pytorch/pytorch` Docker image solve the issue (i.e. older PyTorch and CUDA versions), but none have.

## To Reproduce

In an attempt to nail down the issue I have created the following (subset) of files:

```
Dockerfile
requirements.txt
lightning_test.py
```

1. Build the image (via `docker build -t "my-image:dev" .`).
2. Execute the script (via `docker run --rm --gpus all my-image:dev python lightning_test.py`).

**Dockerfile**

```Dockerfile
FROM pytorch/pytorch:latest

# Copy files to a new 'work' directory
RUN mkdir -p /work/
COPY ./ /work/

# Install requirements
RUN apt update && apt install -y git
RUN pip install --ignore-installed -r /work/requirements.txt

# Set the working directory
WORKDIR /work/
```

**requirements.txt**

```
dvc
pytest
pytorch-lightning
pre-commit
```

**lightning_test.py**

```python
import os

import pytorch_lightning as pl
import torch
from torch import nn
import torch.nn.functional as F
from torchvision.datasets import CIFAR100
from torch.utils.data import DataLoader, random_split
from torchvision import transforms
from torchvision.models import resnet18


class LitResNet(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.resnet = resnet18()
        self.resnet.fc = nn.Linear(512, 100)

    def forward(self, x):
        # in lightning, forward defines the prediction/inference actions
        output = self.resnet(x)
        return output

    def training_step(self, batch, batch_idx):
        # training_step defined the train loop. It is independent of forward
        x, y = batch
        y_hat = self.resnet(x)
        loss = F.cross_entropy(y_hat, y)
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self.resnet(x)
        loss = F.cross_entropy(y_hat, y)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer


dataset = CIFAR100(os.getcwd(), download=True, transform=transforms.ToTensor())
train, val = random_split(dataset, [45000, 5000])

model = LitResNet()
trainer = pl.Trainer(max_epochs=1, gpus=1)
trainer.fit(model,
            DataLoader(train, batch_size=64, num_workers=4),
            DataLoader(val, batch_size=64, num_workers=4))
```

## Expected behavior

Repeating Step 2 above (sometimes in quick succession, sometimes with a few minutes gap), sometimes I observe no errors, while other times the errors listed above. The outputs and stack traces are given below.

**No Errors**
```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name   | Type   | Params
----------------------------------
0 | resnet | ResNet | 11.2 M
----------------------------------
11.2 M    Trainable params
0         Non-trainable params
11.2 M    Total params
44.911    Total estimated model params size (MB)
Files already downloaded and verified
Epoch 0: 100%|██████████| 783/783 [00:18<00:00, 41.93it/s, loss=3.27, v_num=60]
```

**CUDA error: an illegal memory access was encountered**
```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name   | Type   | Params
----------------------------------
0 | resnet | ResNet | 11.2 M
----------------------------------
11.2 M    Trainable params
0         Non-trainable params
11.2 M    Total params
44.911    Total estimated model params size (MB)
Files already downloaded and verified
Epoch 0:   1%|▏         | 11/783 [00:00<00:35, 21.78it/s, loss=4.79, v_num=60]Traceback (most recent call last):
  File "src/lightning_test.py", line 48, in <module>
    trainer.fit(model,
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 869, in run_train
    self.train_loop.run_training_epoch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 499, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 752, in run_training_batch
    batch_outputs = self._process_closure_result(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 813, in _process_closure_result
    self.accumulated_loss.append(opt_closure_result.loss)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 74, in append
    x = x.to(self.memory)
RuntimeError: CUDA error: an illegal memory access was encountered
Exception ignored in: <function tqdm.__del__ at 0x7f3386738790>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1299, in close
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1492, in display
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __str__
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1450, in format_dict
TypeError: cannot unpack non-iterable NoneType object
```

**CUDA error: CUBLAS_STATUS_EXECUTION_FAILED**
```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name   | Type   | Params
----------------------------------
0 | resnet | ResNet | 11.2 M
----------------------------------
11.2 M    Trainable params
0         Non-trainable params
11.2 M    Total params
44.911    Total estimated model params size (MB)
Files already downloaded and verified
Epoch 0:  11%|█▏        | 90/783 [00:02<00:19, 35.72it/s, loss=4.06, v_num=60]Traceback (most recent call last):
  File "src/lightning_test.py", line 48, in <module>
    trainer.fit(model,
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 869, in run_train
    self.train_loop.run_training_epoch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 499, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 738, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 434, in optimizer_step
    model_ref.optimizer_step(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1403, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 214, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 134, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 329, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 336, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 193, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/optim/adam.py", line 66, in step
    loss = closure()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 732, in train_step_and_backward_closure
    result = self.training_step_and_backward(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 823, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 290, in training_step
    training_step_output = self.trainer.accelerator.training_step(args)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 204, in training_step
    return self.training_type_plugin.training_step(*args)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 155, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "src/lightning_test.py", line 28, in training_step
    y_hat = self.resnet(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/models/resnet.py", line 249, in forward
    return self._forward_impl(x)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/models/resnet.py", line 244, in _forward_impl
    x = self.fc(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Exception ignored in: <function tqdm.__del__ at 0x7f6a0efe5790>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1299, in close
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1492, in display
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __str__
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1450, in format_dict
TypeError: cannot unpack non-iterable NoneType object
```

## Environment

**Running `collect_env.py` inside my container**

```
Collecting environment information...
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.8.0-50-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2060
Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.3.5
[pip3] torch==1.8.1
[pip3] torchelastic==0.2.2
[pip3] torchmetrics==0.3.2
[pip3] torchtext==0.9.1
[pip3] torchvision==0.9.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.8.1           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] pytorch-lightning         1.3.5                    pypi_0    pypi
[conda] torch                     1.8.1                    pypi_0    pypi
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchmetrics              0.3.2                    pypi_0    pypi
[conda] torchtext                 0.9.1                      py38    pytorch
[conda] torchvision               0.9.1                    pypi_0    pypi
```

**`nvidia-smi` output on my Docker host**

```
Fri Jun 11 14:44:07 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    On   | 00000000:01:00.0 Off |                  N/A |
| 33%   31C    P8    18W / 160W |     96MiB /  5933MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1221      G   /usr/lib/xorg/Xorg                 86MiB |
|    0   N/A  N/A      1361      G   /usr/bin/gnome-shell                6MiB |
+-----------------------------------------------------------------------------+
```

**Other information about my Docker host (PC)**

- Intel(R) Core(TM) i7-8700 CPU
- 32GB RAM

## Additional context

cc @csarofeen @ptrblck @xwang233 @ngimel

**Comment by adamtupper** [comment]
I think adding `--ipc=host` to the Docker run command (I missed this originally) and not running the container in quick succession has fixed (or reduced the occurrence rate) of the errors. I will close this issue soon if this proves to be the case.

**Comment by adamtupper** [comment]
> I think adding `--ipc=host` to the Docker run command (I missed this originally) and not running the container in quick succession has fixed (or reduced the occurrence rate) of the errors. I will close this issue soon if this proves to be the case.

This was not the case, even with `--ipc=host` the issue still exists.

**Comment by adamtupper** [comment]
I've just had the chance to run the example above on another machine, and I didn't encounter any issues. I'm now assuming that the issue lies with the specific configuration of the original machine. I'm not sure what the policy on closing issues is, but feel free to close this one now.

**Comment by ngimel** [comment]
We usually close the issues that cannot be reproduced and thus aren't actionable. Feel free to reopen if needed.
