### ISSUE TITLE
Can't perform any operation on Vulkan device - macOS M1

### ISSUE THREAD

**Issue by caillonantoine** [pytorch/pytorch#59936]
## 🐛 Bug

I'm trying to use the Vulkan api on my macbook pro M1. I've followed the build instruction provided here [https://pytorch.org/tutorials/prototype/vulkan_workflow.html](https://pytorch.org/tutorials/prototype/vulkan_workflow.html) and successfully built pytorch with Vulkan enabled. `torch.is_vulkan_available()` returns `True`, and I can send tensors and scripted models on the GPU without any problem.

However, when trying to perform _any_ kind of transform on the tensor (convolution, addition, multiplication), it results in a `RuntimeError`.

## To Reproduce

```python
import torch

if not torch.is_vulkan_available():
    raise Exception("Pytorch not compiled with Vulkan enabled")

x = torch.randn(1, 16, 128).to(device="vulkan")
conv = torch.nn.Conv1d(16, 16, 1).to(device="vulkan")

conv(x)
```

results in

```
Traceback (most recent call last):
  File "debug.py", line 9, in <module>
    conv(x)
  File "/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/python3.9/site-packages/torch/nn/modules/conv.py", line 263, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/python3.9/site-packages/torch/nn/modules/conv.py", line 259, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Could not run 'aten::as_strided' with arguments from the 'Vulkan' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::as_strided' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradNestedTensor, UNKNOWN_TENSOR_TYPE_ID, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at ~/code/pytorch/build/aten/src/ATen/RegisterCPU.cpp:5925 [kernel]
QuantizedCPU: registered at ~/code/pytorch/build/aten/src/ATen/RegisterQuantizedCPU.cpp:641 [kernel]
BackendSelect: fallthrough registered at ~/code/pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: fallthrough registered at ~/code/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:11 [kernel]
AutogradOther: registered at ~/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:10140 [autograd kernel]
AutogradCPU: registered at ~/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:10140 [autograd kernel]
AutogradCUDA: registered at ~/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:10140 [autograd kernel]
AutogradXLA: registered at ~/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:10140 [autograd kernel]
AutogradNestedTensor: registered at ~/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:10140 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at ~/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:10140 [autograd kernel]
AutogradPrivateUse1: registered at ~/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:10140 [autograd kernel]
AutogradPrivateUse2: registered at ~/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:10140 [autograd kernel]
AutogradPrivateUse3: registered at ~/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:10140 [autograd kernel]
Tracer: registered at ~/code/pytorch/torch/csrc/autograd/generated/TraceType_3.cpp:10706 [kernel]
Autocast: fallthrough registered at ~/code/pytorch/aten/src/ATen/autocast_mode.cpp:250 [backend fallback]
Batched: registered at ~/code/pytorch/aten/src/ATen/BatchingRegistrations.cpp:1020 [kernel]
VmapMode: fallthrough registered at ~/code/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
```

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0a0+56b43f4
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.4 (arm64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.20.3
Libc version: N/A

Python version: 3.9 (64-bit runtime)
Python platform: macOS-11.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.10.0a0+gitff15d93
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] torch                     1.8.0a0+56b43f4          pypi_0    pypi
```

**Comment by albanD** [comment]
Hey!
Could you rerun the code with `TORCH_SHOW_CPP_STACKTRACES=1` please? To see where this as_strided call comes from.

Unfortunately, we don't have that many ops implemented for vulkan, you can find them here: https://github.com/pytorch/pytorch/blob/af66356d47a3ec485273517e99626dcc58833d89/aten/src/ATen/native/vulkan/VulkanAten.cpp#L539-L570

**Comment by caillonantoine** [comment]
Thanks ! concerning the Vulkan ops, are you planning to add more of them ?

Here is the output of the script using `TORCH_SHOW_CPP_STACKTRACES=1`

```python
Traceback (most recent call last):
  File "/Users/acaillon/code/audio_flow/vulkan.py", line 9, in <module>
    conv(x)
  File "/Users/acaillon/miniforge3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1054, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/acaillon/miniforge3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 301, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/acaillon/miniforge3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 297, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
NotImplementedError: Could not run 'aten::as_strided' with arguments from the 'Vulkan' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::as_strided' is only available for these backends: [CPU, Meta, QuantizedCPU, BackendSelect, Named, Conjugate, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

CPU: registered at /Users/acaillon/code/pytorch/build/aten/src/ATen/RegisterCPU.cpp:18075 [kernel]
Meta: registered at /Users/acaillon/code/pytorch/build/aten/src/ATen/RegisterMeta.cpp:11511 [kernel]
QuantizedCPU: registered at /Users/acaillon/code/pytorch/build/aten/src/ATen/RegisterQuantizedCPU.cpp:1026 [kernel]
BackendSelect: fallthrough registered at /Users/acaillon/code/pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: fallthrough registered at /Users/acaillon/code/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:11 [kernel]
Conjugate: registered at /Users/acaillon/code/pytorch/aten/src/ATen/ConjugateFallback.cpp:117 [backend fallback]
ADInplaceOrView: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/ADInplaceOrViewType_0.cpp:2376 [kernel]
AutogradOther: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
AutogradCPU: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
AutogradCUDA: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
AutogradXLA: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
AutogradMLC: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
AutogradHPU: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
AutogradNestedTensor: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
AutogradPrivateUse1: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
AutogradPrivateUse2: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
AutogradPrivateUse3: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:11344 [autograd kernel]
Tracer: registered at /Users/acaillon/code/pytorch/torch/csrc/autograd/generated/TraceType_3.cpp:10215 [kernel]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at /Users/acaillon/code/pytorch/aten/src/ATen/autocast_mode.cpp:452 [backend fallback]
Autocast: fallthrough registered at /Users/acaillon/code/pytorch/aten/src/ATen/autocast_mode.cpp:285 [backend fallback]
Batched: registered at /Users/acaillon/code/pytorch/aten/src/ATen/BatchingRegistrations.cpp:1023 [kernel]
VmapMode: fallthrough registered at /Users/acaillon/code/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]

Exception raised from reportError at /Users/acaillon/code/pytorch/aten/src/ATen/core/dispatch/OperatorEntry.cpp:399 (most recent call first):
frame #0: c10::impl::OperatorEntry::reportError(c10::DispatchKey) const + 484 (0x1047e3578 in libtorch_cpu.dylib)
frame #1: at::Tensor::as_strided(c10::ArrayRef<long long>, c10::ArrayRef<long long>, c10::optional<long long>) const + 300 (0x105579c50 in libtorch_cpu.dylib)
frame #2: at::native::unsqueeze(at::Tensor const&, long long) + 1840 (0x104b6baac in libtorch_cpu.dylib)
frame #3: at::redispatch::unsqueeze(c10::DispatchKeySet, at::Tensor const&, long long) + 136 (0x1050fdbec in libtorch_cpu.dylib)
frame #4: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&, long long), &(torch::ADInplaceOrView::(anonymous namespace)::unsqueeze(c10::DispatchKeySet, at::Tensor const&, long long))>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&, long long> >, at::Tensor (c10::DispatchKeySet, at::Tensor const&, long long)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, long long) + 84 (0x106e6390c in libtorch_cpu.dylib)
frame #5: at::redispatch::unsqueeze(c10::DispatchKeySet, at::Tensor const&, long long) + 136 (0x1050fdbec in libtorch_cpu.dylib)
frame #6: c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&, long long), &(torch::autograd::VariableType::(anonymous namespace)::unsqueeze(c10::DispatchKeySet, at::Tensor const&, long long))>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&, long long> >, at::Tensor (c10::DispatchKeySet, at::Tensor const&, long long)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, long long) + 320 (0x1068e6384 in libtorch_cpu.dylib)
frame #7: at::Tensor::unsqueeze(long long) const + 216 (0x1055b8cdc in libtorch_cpu.dylib)
frame #8: at::native::_convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long long>, c10::ArrayRef<long long>, c10::ArrayRef<long long>, bool, c10::ArrayRef<long long>, long long, bool, bool, bool, bool) + 4904 (0x1048eefd0 in libtorch_cpu.dylib)
frame #9: at::_convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long long>, c10::ArrayRef<long long>, c10::ArrayRef<long long>, bool, c10::ArrayRef<long long>, long long, bool, bool, bool, bool) + 520 (0x104d5c370 in libtorch_cpu.dylib)
frame #10: at::native::convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long long>, c10::ArrayRef<long long>, c10::ArrayRef<long long>, bool, c10::ArrayRef<long long>, long long) + 292 (0x1048ed184 in libtorch_cpu.dylib)
frame #11: at::convolution(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long long>, c10::ArrayRef<long long>, c10::ArrayRef<long long>, bool, c10::ArrayRef<long long>, long long) + 460 (0x104d5b6e4 in libtorch_cpu.dylib)
frame #12: at::native::conv1d(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long long>, c10::ArrayRef<long long>, c10::ArrayRef<long long>, long long) + 140 (0x1048eba48 in libtorch_cpu.dylib)
frame #13: at::conv1d(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long long>, c10::ArrayRef<long long>, c10::ArrayRef<long long>, long long) + 288 (0x104d223c8 in libtorch_cpu.dylib)
frame #14: torch::autograd::THPVariable_conv1d(_object*, _object*, _object*) + 1844 (0x1037678d8 in libtorch_python.dylib)
<omitting python frames>
frame #40: start + 4 (0x19712d450 in libdyld.dylib)
```

**Comment by ducha-aiki** [comment]
Same here.
However, even simple operations do not work:
```python
import torch

if not torch.is_vulkan_available():
    raise Exception("Pytorch not compiled with Vulkan enabled")
dev = torch.device('vulkan')
x = torch.ones(1, 1, 16, 128).to(dev) 
y = torch.ones(1, 1, 16, 128).to(dev) 
z = (x+y)
print (z.cpu())
```

Output:

```
tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]])
```
