### ISSUE TITLE
Error /usr/local/lib/libopenblas.so: error adding symbols: File in wrong format while building pytorch for ppc64le

### ISSUE THREAD

**Issue by Mathanraj-Sharma** [pytorch/pytorch#59935]
```
[ 83%] Linking CXX shared library ../lib/libtorch_cpu.so
/usr/local/lib/libopenblas.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
gmake[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/build.make:17176: lib/libtorch_cpu.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:6717: caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
gmake: *** [Makefile:161: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 818, in <module>
    build_deps()
  File "setup.py", line 320, in build_deps
    cmake=cmake)
  File "/home/mathanraj/mojo2/temp/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/home/mathanraj/mojo2/temp/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/mathanraj/mojo2/temp/pytorch/tools/setup_helpers/cmake.py", line 140, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake3', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '160']' returned non-zero exit status 2.
[root@25a6f068dd89 pytorch]# 
```

OS: centos7 running in docker container
arch: ppc64le
python: 3.7

Installation steps:
```
export PYTORCH_VERSION=v1.8.1

export USE_MKLDNN=False  MKLDNN_ENABLE_CONCURRENT_EXEC=OFF USE_FBGEMM=OFF  USE_NUMA=OFF USE_MPI=OFF 

source /opt/rh/devtoolset-7/enable 
python3 -m pip install typing_extensions pyyaml dataclasses
git clone --branch ${PYTORCH_VERSION} --recursive https://github.com/pytorch/pytorch 
cd pytorch
git submodule update --init --recursive
git cherry-pick -n 1c64f862f6e03ce09152d45289dd37577c277aaf
python3 setup.py bdist_wheel
```

**Comment by cdeepali** [comment]
Mathanraj-Sharma, please share complete build log.
