### ISSUE TITLE
Char-RNN tutorial giving Error.

### ISSUE THREAD

**Issue by ayush1999** [pytorch/pytorch#5993]
I was running the code for Char level RNN in the PyTorch docs, found here: http://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html . 
I got the error:
```
Traceback (most recent call last):
  File "names.py", line 86, in <module>
    rnn = RNN(n_letters, n_hidden, n_categories)
  File "names.py", line 72, in __init__
    self.i2o = nn.Linear(input_size + hidden_size, output_size)
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 46, in __init__
    self.reset_parameters()
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 49, in reset_parameters
    stdv = 1. / math.sqrt(self.weight.size(1))
RuntimeError: invalid argument 2: dimension 1 out of range of 0D tensor at /opt/conda/conda-bld/pytorch-cpu_1518282373170/work/torch/lib/TH/generic/THTensor.c:24
```
System specs: I was running this on the CPU.
Why is this happening? The examples from the docs should work just fine.

**Comment by apaszke** [comment]
Thanks for the report, but we're using issues here to only track bugs in the core PyTorch library. Please reopen it in [the tutorials repository](https://github.com/pytorch/tutorials).
