### ISSUE TITLE
[jit] AttributeError on Final attributes when inheriting from parent module with __constants__ defined

### ISSUE THREAD

**Issue by ozars** [pytorch/pytorch#59947]
## 🐛 Bug

Inheriting from a parent module with `__constants__` defined as a list type causes error when setting an attribute `Final` in the child module.

## To Reproduce

```py
import torch
from torch import nn
from typing import Final

class Net(nn.Linear):
    x: Final[int]

    def __init__(self):
        super().__init__(5, 10)
        self.x = 0

net = torch.jit.script(Net())
```

```console
Traceback (most recent call last):
  File "inh.py", line 12, in <module>
    net = torch.jit.script(Net())
  File "/home/omer/.conda/envs/dl/lib/python3.8/site-packages/torch/jit/_script.py", line 942, in script
    return torch.jit._recursive.create_script_module(
  File "/home/omer/.conda/envs/dl/lib/python3.8/site-packages/torch/jit/_recursive.py", line 391, in create_script_module
    concrete_type = get_module_concrete_type(nn_module, share_types)
  File "/home/omer/.conda/envs/dl/lib/python3.8/site-packages/torch/jit/_recursive.py", line 367, in get_module_concrete_type
    concrete_type = concrete_type_store.get_or_create_concrete_type(nn_module)
  File "/home/omer/.conda/envs/dl/lib/python3.8/site-packages/torch/jit/_recursive.py", line 308, in get_or_create_concrete_type
    concrete_type_builder = infer_concrete_type_builder(nn_module)
  File "/home/omer/.conda/envs/dl/lib/python3.8/site-packages/torch/jit/_recursive.py", line 187, in infer_concrete_type_builder
    constants_set.add(name)
AttributeError: 'list' object has no attribute 'add'
```

Related parts on the v1.8.1 release:

https://github.com/pytorch/pytorch/blob/56b43f4fec1f76953f15a627694d4bba34588969/torch/nn/modules/linear.py#L70

https://github.com/pytorch/pytorch/blob/56b43f4fec1f76953f15a627694d4bba34588969/torch/jit/_recursive.py#L180-L186

## Environment

python 3.8.8, pytorch 1.8.1 via conda

cc @gmagogsfm

**Comment by ozars** [comment]
Seems like inheriting from another module isn't supported by JIT anyway: #42885
