### ISSUE TITLE
test_sparse_allreduce_basics is flaky on windows

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#59965]
## 🐛 Bug

https://app.circleci.com/pipelines/github/pytorch/pytorch/336280/workflows/2b1e50f7-5b65-434c-8073-73e1596ffa90/jobs/14123525
https://app.circleci.com/pipelines/github/pytorch/pytorch/336280/workflows/e32350af-36c3-46d5-825d-402e7806e4d8/jobs/14123524

```
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 398, in wrapper
    self._join_processes(fn)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 590, in _join_processes
    self._check_return_codes(elapsed_time)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 639, in _check_return_codes
    self.assertEqual(
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 1419, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing 3221226505 and 0 gives a difference of 3221226505, but the allowed difference with rtol=0 and atol=0 is only 0!
Expect process 2 exit code to match Process 0 exit code of 0, but got 3221226505
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @peterjc123 @mszhanyi @skyline75489 @nbcsm @pietern @rohan-varma @agolynski @SciPioneer @mrzzd @cbalioglu @gcramer23

**Comment by mantaionut** [comment]
I could not reproduce this failing test locally, and that test is no longer run in Windows CI because it is part of the distributed test.
@clee2000 I saw in https://github.com/pytorch/pytorch/pull/76848 that there is minimal interest in maintaining distributed for windows.  Is it something that should be supported and we should fix the failing distributed tests on windows?
