### ISSUE TITLE
torch.jit.trace hangs indefinitely

### ISSUE THREAD

**Issue by zheng-ningxin** [pytorch/pytorch#60002]
## ❓ torch.jit.trace hangs indefinitely

Hi, I tried to trace a pytorch model and `jit.trace` hanged indefinitely. The model inference runs smoothly without `jit.trace`. Because it's an internal of the company, I cannot upload the model to debug. 

I want ask what kinds of reasons may cause `jit.trace` to hang all the time? Looking forward to your reply, thanks.

cc @gmagogsfm

**Comment by SplitInfinity** [comment]
It's difficult for us to help if you cannot share your model.

@tugsbayasgalan, you have been looking into tracing performance, right? Do you have any idea of what sorts of things might cause tracing to be slow?

**Comment by gmagogsfm** [comment]
> ## ❓ torch.jit.trace hangs indefinitely
> Hi, I tried to trace a pytorch model and `jit.trace` hanged indefinitely. The model inference runs smoothly without `jit.trace`. Because it's an internal of the company, I cannot upload the model to debug.
> 
> I want ask what kinds of reasons may cause `jit.trace` to hang all the time? Looking forward to your reply, thanks.
> 
> cc @gmagogsfm

Is it "indefinitely"? Or does it take really long? We have seen bugs that causing trace to be extremely slow. If you trim down size of your module (number of layers, width of layers, etc), does `jit.trace` finish?

**Comment by zheng-ningxin** [comment]
Hi~ Thanks for the quick reply~ @SplitInfinity @gmagogsfm 

Maybe `Indefinitely` is a bit exaggerated, I monitor the resource usage and found that there is only one thread running on the CPUand the others are all slept, besides, no GPU resource is used at all(the model is on the GPU).

![image](https://user-images.githubusercontent.com/49771382/121997978-c1ee0480-cddd-11eb-970d-11dc2d596fbb.png)
![image](https://user-images.githubusercontent.com/49771382/121998042-d3cfa780-cddd-11eb-8f28-e0f86cffa47b.png)

In addition, I interrupted the process and get the trace as following, I hope there will be some useful information in it 
```
/root/anaconda3/envs/nni/lib/python3.8/site-packages/axial_positional_embedding/axial_positional_embedding.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!  assert (t <= self.max_seq_len), f'Sequence length ({t}) must be less than the maximum sequence length allowed ({self.max_seq_len})'net.py:541: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!  if tokens.shape[1] > total_seq_len:net.py:120: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!  k = max(int((1 - thres) * num_logits), 1)^CTraceback (most recent call last):  File "net.py", line 610, in <module>    scripted_model = torch.jit.trace(net, inputs)  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/jit/_trace.py", line 733, in trace    return trace_module(  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/jit/_trace.py", line 934, in trace_module    module._c._create_method_from_trace(  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 887, in _call_impl    result = self._slow_forward(*input, **kwargs)  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward    result = self.forward(*input, **kwargs)  File "net.py", line 477, in forward    logits = self.forward_({'source_ids': text, 'imgs': image_}, mask=mask, return_loss=False)  File "net.py", line 548, in forward_    out = self.transformer(tokens, mask=mask)  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 887, in _call_impl    result = self._slow_forward(*input, **kwargs)  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward    result = self.forward(*input, **kwargs)  File "net.py", line 358, in forward    return self.layers(x, **kwargs)  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 887, in _call_impl    result = self._slow_forward(*input, **kwargs)  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward    result = self.forward(*input, **kwargs)  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/dalle_pytorch/reversible.py", line 139, in forward    x = x + f(x, **f_args)  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 887, in _call_impl    result = self._slow_forward(*input, **kwargs)  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "net.py", line 266, in forward
    return self.fn(x, **kwargs) * self.scale
  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "net.py", line 276, in forward
    return self.fn(self.norm(x), **kwargs)
  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "net.py", line 165, in forward
    q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> (b h) n d', h=h), qkv)
  File "net.py", line 165, in <lambda>
    q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> (b h) n d', h=h), qkv)
  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/einops/einops.py", line 424, in rearrange
    return reduce(tensor, pattern, reduction='rearrange', **axes_lengths)
  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/einops/einops.py", line 368, in reduce
    return recipe.apply(tensor)
  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/einops/einops.py", line 204, in apply
    init_shapes, reduced_axes, axes_reordering, added_axes, final_shapes = self.reconstruct_from_shape(
  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/einops/einops.py", line 192, in reconstruct_from_shape
    final_shapes.append(_product(lengths))
  File "/root/anaconda3/envs/nni/lib/python3.8/site-packages/einops/einops.py", line 22, in _product
    result *= element
KeyboardInterrupt
```

Thanks~

**Comment by gmagogsfm** [comment]
We recently implemented several performance improvement to `jit.trace`. Please try again to see if your problem is resolved. Thanks.

CC @tugsbayasgalan

**Comment by zheng-ningxin** [comment]
Thanks it doesn't hang any more.
