### ISSUE TITLE
Segmentation fault with PyTorch 1.8.1+cu111 and GTX 1070

### ISSUE THREAD

**Issue by jonathan-conder-sm** [pytorch/pytorch#60082]
## 🐛 Bug

A segfault triggered from a python script. Might be related to existing issues but I thought I'd make the repro steps available anyway.

## To Reproduce

Save the following script as `entrypoint.py`:
```Python
import torch

matrix = torch.nn.Parameter(torch.zeros(2, 1, device="cuda"))
batch = torch.zeros(1, 2, device="cuda")
optimizer = torch.optim.Adam([matrix])

for _ in range(50):
    loss = (batch @ matrix @ matrix.t()).sum()
    loss.backward()
    optimizer.step()
```

Save the following `Dockerfile` in the same folder:
```Dockerfile
FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu20.04

ARG DEBIAN_FRONTEND='noninteractive'
ENV PYTHONUNBUFFERED='TRUE'

RUN apt-get update && \
    apt-get install -y gdb python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install --no-cache-dir -f 'https://download.pytorch.org/whl/torch_stable.html' torch==1.8.1+cu111

COPY entrypoint.py /entrypoint.py

CMD [ \
    "gdb", \
    "-ex", "set confirm off", \
    "-ex", "set pagination off", \
    "-ex", "run", \
    "-ex", "backtrace", \
    "-ex", "quit", \
    "--args", "python3", "/entrypoint.py" \
]
```

Then run this in the folder:
```ShellSession
# docker build --tag pytorch:segfault .
# docker run --rm -it --gpus all pytorch:segfault
```

You might need to install NVIDIA container toolkit. It might also happen if you run the script directly. It seems like the `1.8.1+cu111` package is important, I can't reproduce with either `1.9.0+cu111` or `1.8.1` (from PyPI). I also couldn't reproduce with the `pytorch:1.8.1-cuda11.1-cudnn8-runtime` image.

Backtrace:
```GDB
Thread 16 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f3c91006700 (LWP 27)]
0x00007f3d43c5e48f in at::cuda::getCurrentCUDABlasHandle() () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#0  0x00007f3d43c5e48f in at::cuda::getCurrentCUDABlasHandle() () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#1  0x00007f3d43c4c7dd in void at::cuda::blas::gemm<float>(char, char, long, long, long, float, float const*, long, float const*, long, float, float*, long) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#2  0x00007f3d44e688f0 in at::native::(anonymous namespace)::addmm_out_cuda_impl(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar, c10::Scalar) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#3  0x00007f3d44e6a092 in at::native::mm_cuda(at::Tensor const&, at::Tensor const&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#4  0x00007f3d43ca3848 in at::(anonymous namespace)::(anonymous namespace)::wrapper_mm(at::Tensor const&, at::Tensor const&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#5  0x00007f3d43ca388f in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&), &at::(anonymous namespace)::(anonymous namespace)::wrapper_mm>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&> >, at::Tensor (at::Tensor const&, at::Tensor const&)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
#6  0x00007f3d3211f596 in at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&)> const&, at::Tensor const&, at::Tensor const&) const [clone .constprop.4808] () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#7  0x00007f3d32124bbf in at::mm(at::Tensor const&, at::Tensor const&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#8  0x00007f3d33a0891c in torch::autograd::VariableType::(anonymous namespace)::mm(at::Tensor const&, at::Tensor const&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#9  0x00007f3d33a08e8f in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, at::Tensor const&), &torch::autograd::VariableType::(anonymous namespace)::mm>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&> >, at::Tensor (at::Tensor const&, at::Tensor const&)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#10 0x00007f3d325717d6 in at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&)> const&, at::Tensor const&, at::Tensor const&) const [clone .constprop.1487] () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#11 0x00007f3d325759ff in at::Tensor::mm(at::Tensor const&) const () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#12 0x00007f3d34448831 in torch::autograd::generated::details::mm_mat2_backward(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::Scalar const&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#13 0x00007f3d33834bbe in torch::autograd::generated::MmBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#14 0x00007f3d33eda771 in torch::autograd::Node::operator()(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#15 0x00007f3d33ed657b in torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#16 0x00007f3d33ed719f in torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#17 0x00007f3d33ece979 in torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so
#18 0x00007f3da4652293 in torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) () from /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so
#19 0x00007f3da5669d84 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007f3da643a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007f3da6576293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6
```

## Expected behavior

Script should exit cleanly (or with an exception if there's something wrong with the script).

## Environment

Container:
```
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1070
Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.1+cu111
[conda] Could not collect
```

Host:
```
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1070
Nvidia driver version: 465.19.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.8.1+cu111
[pip3] torch-model-archiver==0.3.1
[pip3] torchaudio==0.8.1
[pip3] torchserve==0.4.0
[pip3] torchtext==0.9.1
[pip3] torchvision==0.9.1+cu111
[conda] numpy                     1.20.2                   pypi_0    pypi
[conda] torch                     1.8.1+cu111              pypi_0    pypi
[conda] torch-model-archiver      0.4.0                    pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchserve                0.4.0                    pypi_0    pypi
[conda] torchtext                 0.9.1                    pypi_0    pypi
[conda] torchvision               0.9.1+cu111              pypi_0    pypi
```

## Additional context

Relevant parts of `/etc/apt/sources.list`:
```
deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
```
I'm using the `cuda-11-1` and `libcudnn8-dev` packages.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel @vincentqb @iramazanli

**Comment by ngimel** [comment]
That's a known issue that, as you note, has been fixed on recent versions.
