### ISSUE TITLE
caffe_translator.py Unable to convert Power Layer

### ISSUE THREAD

**Issue by madhusoodanan1989** [pytorch/pytorch#60083]
While converting my caffe model to caffe2 model I get the below error. 

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Lib\site-packages\caffe2\python\caffe_translator.py", line 212, in TranslateLayer
    caffe_ops, params = cls.registry_[layer.type](
KeyError: 'Power'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Lib\site-packages\caffe2\python\caffe_translator.py", line 921, in <module>
    input_dims=args.input_dims
  File "C:\ProgramData\Anaconda3\Lib\site-packages\caffe2\python\caffe_translator.py", line 284, in TranslateModel
    return TranslatorRegistry.TranslateModel(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\caffe2\python\caffe_translator.py", line 273, in TranslateModel
    net_params=net_params, input_dims=input_dims)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\caffe2\python\caffe_translator.py", line 216, in TranslateLayer
    str(layer))
KeyError: 'No translator registered for layer:

Looks like there is no support for Power layer. 

Are there any possible ways of adding this support?

**Comment by gchanan** [comment]
Caffe2 is deprecated, so we are unable to help here.

**Comment by madhusoodanan1989** [comment]
Thank you gchanan for your response, 
I would also like to know if there are any conversion scripts which can convert caffe models to pytorch or ONNX models.
