### ISSUE TITLE
torch.package: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by tchaton** [pytorch/pytorch#60089]
## To Reproduce

This happens with `pytorch_lightning.loggers.base.DummyExperiment` which can be found at: 
https://github.com/PyTorchLightning/pytorch-lightning/blob/9097347ea8e354c5bed1aec186be305c1216bc81/pytorch_lightning/loggers/base.py#L429

```
Traceback (most recent call last):
  File "tabular_classification.py", line 49, in <module>
    model.to_package('tabular_package.zip', verbose=True)
  File "/Users/thomas/Documents/GitHub/lightning-flash/flash/core/model.py", line 652, in to_package
    exporter.save_pickle('models', 'model.pkl', self)
  File "/Users/thomas/Documents/GitHub/lightning-flash/.venv/lib/python3.7/site-packages/torch/package/package_exporter.py", line 497, in save_pickle
    pickler.dump(obj)
  File "/Users/thomas/Documents/GitHub/lightning-flash/.venv/lib/python3.7/site-packages/torch/package/package_exporter.py", line 737, in _persistent_id
    if self.serialized_reduces.get(id(obj)) is None:
TypeError: 'NoneType' object is not iterable
```

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by nikithamalgifb** [comment]
@Lilyjjo @SplitInfinity @suo : Do you guys have any idea about this?

**Comment by tchaton** [comment]
Hey @Lilyjjo,

Here is the associated PR in Lightning Flash: https://github.com/PyTorchLightning/lightning-flash/pull/416/files

How to reproduce:
* Clone the project
* Install the reps
* Run https://github.com/PyTorchLightning/lightning-flash/pull/416/files

Best
T.C

**Comment by Lilyjjo** [comment]
Hi @tchaton, are you able to create a smaller minimal repro? That would help me help you faster!
