### ISSUE TITLE
torch.package: Module did not match against any action pattern. Extern, mock, or intern it.

### ISSUE THREAD

**Issue by tchaton** [pytorch/pytorch#60090]
## To Reproduce

A draft PR is created on Lightning Flash, built on top of PyTorch Lightning.
https://github.com/PyTorchLightning/lightning-flash/pull/416/files#diff-e5d65c19fb43635dc8b91e9020e558acc1cb64c547f9829eaac732aa46ea3895R653

When running `python tabular_classification.py`, it seems some module are not properly package.
I browsed through the doc and PackageExporter codebase, but couldn't find the solution. 

```
Traceback (most recent call last):
  File "tabular_classification.py", line 49, in <module>
    model.to_package('tabular_package.zip', verbose=True)
  File "/Users/thomas/Documents/GitHub/lightning-flash/flash/core/model.py", line 653, in to_package
    exporter.save_pickle('models', 'model.pkl', self)
  File "/Users/thomas/Documents/GitHub/lightning-flash/.venv/lib/python3.7/site-packages/torch/package/package_exporter.py", line 757, in __exit__
    self.close()
  File "/Users/thomas/Documents/GitHub/lightning-flash/.venv/lib/python3.7/site-packages/torch/package/package_exporter.py", line 850, in close
    self._execute_dependency_graph()
  File "/Users/thomas/Documents/GitHub/lightning-flash/.venv/lib/python3.7/site-packages/torch/package/package_exporter.py", line 786, in _execute_dependency_graph
    self._validate_dependency_graph()
  File "/Users/thomas/Documents/GitHub/lightning-flash/.venv/lib/python3.7/site-packages/torch/package/package_exporter.py", line 773, in _validate_dependency_graph
    raise PackagingError(self.dependency_graph)
torch.package.package_exporter.PackagingError: 
* Module did not match against any action pattern. Extern, mock, or intern it.
    flash.tabular.classification.model
    pytorch_lightning.utilities.parsing
    torchmetrics.classification.accuracy
    torchmetrics.utilities.data
    torchmetrics.utilities.enums
    torchmetrics.classification.precision_recall
    pytorch_tabnet.tab_network
    pytorch_tabnet.sparsemax
    flash.core.trainer
    pytorch_lightning.utilities.debugging
    pytorch_lightning.trainer.configuration_validator
    pytorch_lightning.trainer.connectors.data_connector
    pytorch_lightning.trainer.connectors.optimizer_connector
    pytorch_lightning.trainer.connectors.accelerator_connector
    pytorch_lightning.utilities.enums
    pytorch_lightning.plugins.precision.precision_plugin
    pytorch_lightning.plugins.training_type.single_device
    pytorch_lightning.plugins.environments.lightning_environment
    pytorch_lightning.accelerators.cpu
    pytorch_lightning.trainer.connectors.logger_connector.logger_connector
    pytorch_lightning.trainer.connectors.logger_connector.metrics_holder
    pytorch_lightning.trainer.states
    pytorch_lightning.trainer.connectors.logger_connector.epoch_result_store
    pytorch_lightning.trainer.connectors.logger_connector.callback_hook_validator
    pytorch_lightning.trainer.connectors.model_connector
    pytorch_lightning.trainer.connectors.callback_connector
    pytorch_lightning.trainer.connectors.debugging_connector
    pytorch_lightning.trainer.connectors.training_trick_connector
    pytorch_lightning.trainer.connectors.profiler_connector
    pytorch_lightning.trainer.connectors.checkpoint_connector
    pytorch_lightning.trainer.connectors.slurm_connector
    pytorch_lightning.tuner.tuning
    pytorch_lightning.trainer.training_loop
    pytorch_lightning.trainer.supporters
    pytorch_lightning.utilities.warnings
    pytorch_lightning.trainer.evaluation_loop
    pytorch_lightning.trainer.predict_loop
    pytorch_lightning.callbacks.progress
    pytorch_lightning.callbacks.model_checkpoint
    fsspec.spec
    fsspec.implementations.local
    flash.tabular.classification.data
    flash.core.data.data_pipeline
    flash.core.data.data_source
    numpy.core.multiarray
    numpy
    pandas.core.series
    pandas.core.internals.managers
    pandas.core.indexes.base
    flash.core.data.callback
    flash.core.data.splits
    flash.core.data.auto_dataset
    flash.core.data.utils
    pytorch_lightning.callbacks.gradient_accumulation_scheduler
    flash.core.data.batch
    pytorch_lightning.profiler.profilers
    pytorch_lightning.loggers.base
    pytorch_lightning.core.step_result
    flash.core.classification
    _operator
```

## Expected behavior

Properly packaged.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @gmagogsfm

**Comment by muellerzr** [comment]
I get this as well for fastai's `Module` class. I think we need to write a proper `__reduce_package__` function inside the module we want to use, but I've failed at doing so thus far

**Comment by nikithamalgifb** [comment]
@Lilyjjo @SplitInfinity @suo : Do you guys have any idea about this?

**Comment by Lilyjjo** [comment]
Hi! @tchaton we do have docs explaining what intern/extern/mocking are in our unreleased [master documentation](https://pytorch.org/docs/master/package.html). The information you need should be there!

@muellerzr There is an example of defining `__reduce_package__` for custom classes in the documentation as well. The problem you are hitting is due to the fact that `torch.package` is unable to package code in the `__main__` module. You'll need to move your code for `Flatten` to another file/module.

**Comment by muellerzr** [comment]
@Lilyjjo thank you! After moving everything to a `model.py`, it worked successfully when specifying only `pe.extern('model')`. Is this expected behavior? (IE I need to assume they have access to `model.py` to be able to load it back in?)

**Comment by Lilyjjo** [comment]
@muellerzr good to hear! And yes, if you use `extern` then your loading environment will need `model.py`! If you `intern` `model.py` instead, then you aren't required to have `model.py` around as it will be contained in the `torch.package` archive.

**Comment by muellerzr** [comment]
Great! That worked perfectly. Thank you so much @Lilyjjo!
