### ISSUE TITLE
test_forward_async_script is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#60100]
https://www.internalfb.com/intern/opensource/ci/job/log/1402983250083761/

```
2021-06-15T23:55:37.5505553Z   test_forward_async_script (__main__.TensorPipeRemoteModuleTestWithSpawn) ... Caught exception: 
2021-06-15T23:55:37.5507394Z Traceback (most recent call last):
2021-06-15T23:55:37.5509628Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
2021-06-15T23:55:37.5510982Z     getattr(self, test_name)()
2021-06-15T23:55:37.5512685Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
2021-06-15T23:55:37.5513939Z     fn()
2021-06-15T23:55:37.5515416Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
2021-06-15T23:55:37.5516843Z     return_value = old_test_method(self, *arg, **kwargs)
2021-06-15T23:55:37.5518865Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/nn/api/remote_module_test.py", line 181, in test_forward_async_script
2021-06-15T23:55:37.5520560Z     ret = run_forward_async(scripted_remote_module)
2021-06-15T23:55:37.5522313Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 134, in prof_func_call
2021-06-15T23:55:37.5523732Z     return prof_callable(func_call, *args, **kwargs)
2021-06-15T23:55:37.5525480Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 131, in prof_callable
2021-06-15T23:55:37.5526822Z     return callable(*args, **kwargs)
2021-06-15T23:55:37.5528087Z RuntimeError: The following operation failed in the TorchScript interpreter.
2021-06-15T23:55:37.5529442Z Traceback of TorchScript (most recent call last):
2021-06-15T23:55:37.5531680Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/nn/api/remote_module_test.py", line 178, in run_forward_async
2021-06-15T23:55:37.5533660Z         def run_forward_async(scripted_remote_module: RemoteMyModuleInterface):
2021-06-15T23:55:37.5535197Z             ret_fut = scripted_remote_module.forward_async(torch.ones(1), 2, "3")
2021-06-15T23:55:37.5536245Z             ret = ret_fut.wait()
2021-06-15T23:55:37.5537130Z                   ~~~~~~~~~~~~ <--- HERE
2021-06-15T23:55:37.5537793Z             return ret
2021-06-15T23:55:37.5539009Z RuntimeError: attempted to get undefined function _remote_forward
2021-06-15T23:55:37.5540729Z Exception raised from get_function at /var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h:72 (most recent call first):
2021-06-15T23:55:37.5543815Z frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7fb926a5d3b9 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
2021-06-15T23:55:37.5547371Z frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xd2 (0x7fb926a59472 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
2021-06-15T23:55:37.5551771Z frame #2: torch::distributed::rpc::RequestCallbackImpl::runJitFunction(c10::QualifiedName const&, std::vector<c10::IValue, std::allocator<c10::IValue> >&, std::vector<c10::Stream, std::allocator<c10::Stream> >, bool) const + 0x890 (0x7fb933511fa0 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
2021-06-15T23:55:37.5556694Z frame #3: torch::distributed::rpc::RequestCallbackImpl::processScriptCall(torch::distributed::rpc::RpcCommandBase&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x3a1 (0x7fb9335128b1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
2021-06-15T23:55:37.5561657Z frame #4: torch::distributed::rpc::RequestCallbackNoPython::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType const&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0xb4 (0x7fb92ae146a4 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
2021-06-15T23:55:37.5566965Z frame #5: torch::distributed::rpc::RequestCallbackImpl::processRpcWithErrors(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType const&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x65 (0x7fb93350f2d5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
2021-06-15T23:55:37.5570554Z frame #6: <unknown function> + 0x41923ea (0x7fb92ae113ea in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
2021-06-15T23:55:37.5574109Z frame #7: torch::distributed::rpc::RequestCallbackNoPython::processMessage(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0xa07 (0x7fb92ae12557 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
2021-06-15T23:55:37.5578450Z frame #8: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x57 (0x7fb92ae0a097 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
2021-06-15T23:55:37.5581431Z frame #9: <unknown function> + 0xd1e9f1 (0x7fb9335209f1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
2021-06-15T23:55:37.5583895Z frame #10: c10::ThreadPool::main_loop(unsigned long) + 0x2a3 (0x7fb926a138b3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
2021-06-15T23:55:37.5585598Z frame #11: <unknown function> + 0xc8421 (0x7fb926947421 in /opt/conda/lib/libstdc++.so.6)
2021-06-15T23:55:37.5587309Z frame #12: <unknown function> + 0x76ba (0x7fb94156e6ba in /lib/x86_64-linux-gnu/libpthread.so.0)
2021-06-15T23:55:37.5588923Z frame #13: clone + 0x6d (0x7fb9412a451d in /lib/x86_64-linux-gnu/libc.so.6)
2021-06-15T23:55:37.5589748Z 
2021-06-15T23:55:37.5590108Z 
2021-06-15T23:55:37.5591256Z  exiting process with exit code: {MultiProcessTestCase.TEST_ERROR_EXIT_CODE}
2021-06-15T23:55:37.6583242Z [W tensorpipe_agent.cpp:704] RPC agent for worker1 encountered error when reading incoming request from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
2021-06-15T23:55:37.7211344Z Process 0 terminated with exit code 10, terminating remaining processes.
2021-06-15T23:55:37.7247257Z ERROR (1.117s)

...

2021-06-16T00:01:30.5265330Z ERROR [1.117s]: test_forward_async_script (__main__.TensorPipeRemoteModuleTestWithSpawn)
2021-06-16T00:01:30.5266717Z ----------------------------------------------------------------------
2021-06-16T00:01:30.5267199Z Traceback (most recent call last):
2021-06-16T00:01:30.5268047Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 398, in wrapper
2021-06-16T00:01:30.5268689Z     self._join_processes(fn)
2021-06-16T00:01:30.5303418Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 590, in _join_processes
2021-06-16T00:01:30.5304626Z     self._check_return_codes(elapsed_time)
2021-06-16T00:01:30.5306146Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 633, in _check_return_codes
2021-06-16T00:01:30.5307087Z     raise RuntimeError(error)
2021-06-16T00:01:30.5307962Z RuntimeError: Process 0 exited with error code 10 and exception:
2021-06-16T00:01:30.5308792Z Traceback (most recent call last):
2021-06-16T00:01:30.5310095Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
2021-06-16T00:01:30.5311077Z     getattr(self, test_name)()
2021-06-16T00:01:30.5311886Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
2021-06-16T00:01:30.5312515Z     fn()
2021-06-16T00:01:30.5313236Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
2021-06-16T00:01:30.5313958Z     return_value = old_test_method(self, *arg, **kwargs)
2021-06-16T00:01:30.5314894Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/nn/api/remote_module_test.py", line 181, in test_forward_async_script
2021-06-16T00:01:30.5315656Z     ret = run_forward_async(scripted_remote_module)
2021-06-16T00:01:30.5316468Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 134, in prof_func_call
2021-06-16T00:01:30.5317125Z     return prof_callable(func_call, *args, **kwargs)
2021-06-16T00:01:30.5317925Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 131, in prof_callable
2021-06-16T00:01:30.5318554Z     return callable(*args, **kwargs)
2021-06-16T00:01:30.5319266Z RuntimeError: The following operation failed in the TorchScript interpreter.
2021-06-16T00:01:30.5319904Z Traceback of TorchScript (most recent call last):
2021-06-16T00:01:30.5320832Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/nn/api/remote_module_test.py", line 178, in run_forward_async
2021-06-16T00:01:30.5321735Z         def run_forward_async(scripted_remote_module: RemoteMyModuleInterface):
2021-06-16T00:01:30.5322446Z             ret_fut = scripted_remote_module.forward_async(torch.ones(1), 2, "3")
2021-06-16T00:01:30.5322917Z             ret = ret_fut.wait()
2021-06-16T00:01:30.5323345Z                   ~~~~~~~~~~~~ <--- HERE
2021-06-16T00:01:30.5323644Z             return ret
2021-06-16T00:01:30.5324117Z RuntimeError: attempted to get undefined function _remote_forward
2021-06-16T00:01:30.5324886Z Exception raised from get_function at /var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h:72 (most recent call first):
2021-06-16T00:01:30.5326331Z frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7fb926a5d3b9 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
2021-06-16T00:01:30.5327980Z frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xd2 (0x7fb926a59472 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
2021-06-16T00:01:30.5330050Z frame #2: torch::distributed::rpc::RequestCallbackImpl::runJitFunction(c10::QualifiedName const&, std::vector<c10::IValue, std::allocator<c10::IValue> >&, std::vector<c10::Stream, std::allocator<c10::Stream> >, bool) const + 0x890 (0x7fb933511fa0 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
2021-06-16T00:01:30.5332228Z frame #3: torch::distributed::rpc::RequestCallbackImpl::processScriptCall(torch::distributed::rpc::RpcCommandBase&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x3a1 (0x7fb9335128b1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
2021-06-16T00:01:30.5334479Z frame #4: torch::distributed::rpc::RequestCallbackNoPython::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType const&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0xb4 (0x7fb92ae146a4 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
2021-06-16T00:01:30.5336907Z frame #5: torch::distributed::rpc::RequestCallbackImpl::processRpcWithErrors(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType const&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x65 (0x7fb93350f2d5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
2021-06-16T00:01:30.5338768Z frame #6: <unknown function> + 0x41923ea (0x7fb92ae113ea in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
2021-06-16T00:01:30.5340426Z frame #7: torch::distributed::rpc::RequestCallbackNoPython::processMessage(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0xa07 (0x7fb92ae12557 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
2021-06-16T00:01:30.5342429Z frame #8: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x57 (0x7fb92ae0a097 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
2021-06-16T00:01:30.5343790Z frame #9: <unknown function> + 0xd1e9f1 (0x7fb9335209f1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
2021-06-16T00:01:30.5344946Z frame #10: c10::ThreadPool::main_loop(unsigned long) + 0x2a3 (0x7fb926a138b3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
2021-06-16T00:01:30.5345726Z frame #11: <unknown function> + 0xc8421 (0x7fb926947421 in /opt/conda/lib/libstdc++.so.6)
2021-06-16T00:01:30.5346624Z frame #12: <unknown function> + 0x76ba (0x7fb94156e6ba in /lib/x86_64-linux-gnu/libpthread.so.0)
2021-06-16T00:01:30.5347385Z frame #13: clone + 0x6d (0x7fb9412a451d in /lib/x86_64-linux-gnu/libc.so.6)
2021-06-16T00:01:30.5347714Z 
2021-06-16T00:01:30.5347879Z 
2021-06-16T00:01:30.5348041Z 
2021-06-16T00:01:30.5348205Z 
2021-06-16T00:01:30.5348356Z 
2021-06-16T00:01:30.5348846Z ----------------------------------------------------------------------
2021-06-16T00:01:30.5349251Z Ran 367 tests in 550.465s
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @agolynski @SciPioneer @H-Huang @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
cc @SciPioneer regarding RemoteModule test
