### ISSUE TITLE
test_remote_module_py_pickle_not_supported_script is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#60109]
```
Jun 16 02:28:19   test_remote_module_py_pickle_not_supported_script (__main__.TensorPipeRemoteModuleTestWithSpawn) ... Caught exception: 
Jun 16 02:28:19 Traceback (most recent call last):
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 16 02:28:19     getattr(self, test_name)()
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 16 02:28:19     fn()
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
Jun 16 02:28:19     return_value = old_test_method(self, *arg, **kwargs)
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/nn/api/remote_module_test.py", line 467, in test_remote_module_py_pickle_not_supported_script
Jun 16 02:28:19     dst_worker_name, modes=[ModuleCreationMode.MODULE_CTOR_WITH_INTERFACE]
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/nn/api/remote_module_test.py", line 123, in _create_remote_module_iter
Jun 16 02:28:19     _module_interface_cls=MyModuleInterface,
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/nn/api/remote_module.py", line 241, in __init__
Jun 16 02:28:19     fut.wait()  # Ensure remote_module_cls is available on remote side.
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/internal.py", line 218, in _handle_exception
Jun 16 02:28:19     raise result.exception_type(result.msg.encode("utf-8").decode("unicode_escape"))
Jun 16 02:28:19 OSError: On WorkerInfo(id=1, name=worker1):
Jun 16 02:28:19 OSError("Can't get source for <function _remote_forward at 0x7f278e430378>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.",)
Jun 16 02:28:19 Traceback (most recent call last):
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/_utils_internal.py", line 59, in get_source_lines_and_file
Jun 16 02:28:19     sourcelines, file_lineno = inspect.getsourcelines(obj)
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/inspect.py", line 955, in getsourcelines
Jun 16 02:28:19     lines, lnum = findsource(object)
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/inspect.py", line 786, in findsource
Jun 16 02:28:19     raise OSError('could not get source code')
Jun 16 02:28:19 OSError: could not get source code
Jun 16 02:28:19 
Jun 16 02:28:19 The above exception was the direct cause of the following exception:
Jun 16 02:28:19 
Jun 16 02:28:19 Traceback (most recent call last):
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/internal.py", line 204, in _run_function
Jun 16 02:28:19     result = python_udf.func(*python_udf.args, **python_udf.kwargs)
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/nn/api/remote_module.py", line 76, in _instantiate_template
Jun 16 02:28:19     module_interface_cls, enable_moving_cpu_tensors_to_cuda
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/nn/jit/instantiator.py", line 140, in instantiate_scriptable_remote_module_template
Jun 16 02:28:19     generated_module_name, str_dict, enable_moving_cpu_tensors_to_cuda
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/nn/jit/instantiator.py", line 99, in _do_instantiate_remote_module_template
Jun 16 02:28:19     generated_module = importlib.import_module(f"{generated_module_name}")
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
Jun 16 02:28:19     return _bootstrap._gcd_import(name[level:], package, level)
Jun 16 02:28:19   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 16 02:28:19   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 16 02:28:19   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
Jun 16 02:28:19   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
Jun 16 02:28:19   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
Jun 16 02:28:19   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jun 16 02:28:19   File "/tmp/tmp7v7ts2xx/_remote_module___torch___torch_testing__internal_distributed_nn_api_remote_module_test_MyModuleInterface.py", line 46, in <module>
Jun 16 02:28:19     module_rref: RRef[module_interface_cls], device: str, is_device_map_set: bool, tensor: Tensor, number: int, word: str) -> Tuple[str, int, Tensor]:
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/jit/_script.py", line 1166, in script
Jun 16 02:28:19     ast = get_jit_def(obj, obj.__name__)
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 269, in get_jit_def
Jun 16 02:28:19     sourcelines, file_lineno, filename = get_source_lines_and_file(fn, torch._C.ErrorReport.call_stack())
Jun 16 02:28:19   File "/opt/conda/lib/python3.6/site-packages/torch/_utils_internal.py", line 66, in get_source_lines_and_file
Jun 16 02:28:19     raise OSError(msg) from e
Jun 16 02:28:19 OSError: Can't get source for <function _remote_forward at 0x7f278e430378>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
Jun 16 02:28:19 
Jun 16 02:28:19  exiting process with exit code: {MultiProcessTestCase.TEST_ERROR_EXIT_CODE}
Jun 16 02:28:19 [W tensorpipe_agent.cpp:704] RPC agent for worker1 encountered error when reading incoming request from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
Jun 16 02:28:19 ERROR (1.330s)

...

Jun 16 02:37:26 ======================================================================
Jun 16 02:37:26 ERROR [1.330s]: test_remote_module_py_pickle_not_supported_script (__main__.TensorPipeRemoteModuleTestWithSpawn)
Jun 16 02:37:26 ----------------------------------------------------------------------
Jun 16 02:37:26 Traceback (most recent call last):
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 398, in wrapper
Jun 16 02:37:26     self._join_processes(fn)
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 590, in _join_processes
Jun 16 02:37:26     self._check_return_codes(elapsed_time)
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 633, in _check_return_codes
Jun 16 02:37:26     raise RuntimeError(error)
Jun 16 02:37:26 RuntimeError: Process 0 exited with error code 10 and exception:
Jun 16 02:37:26 Traceback (most recent call last):
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 16 02:37:26     getattr(self, test_name)()
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 16 02:37:26     fn()
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
Jun 16 02:37:26     return_value = old_test_method(self, *arg, **kwargs)
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/nn/api/remote_module_test.py", line 467, in test_remote_module_py_pickle_not_supported_script
Jun 16 02:37:26     dst_worker_name, modes=[ModuleCreationMode.MODULE_CTOR_WITH_INTERFACE]
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/nn/api/remote_module_test.py", line 123, in _create_remote_module_iter
Jun 16 02:37:26     _module_interface_cls=MyModuleInterface,
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/nn/api/remote_module.py", line 241, in __init__
Jun 16 02:37:26     fut.wait()  # Ensure remote_module_cls is available on remote side.
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/internal.py", line 218, in _handle_exception
Jun 16 02:37:26     raise result.exception_type(result.msg.encode("utf-8").decode("unicode_escape"))
Jun 16 02:37:26 OSError: On WorkerInfo(id=1, name=worker1):
Jun 16 02:37:26 OSError("Can't get source for <function _remote_forward at 0x7f278e430378>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.",)
Jun 16 02:37:26 Traceback (most recent call last):
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/_utils_internal.py", line 59, in get_source_lines_and_file
Jun 16 02:37:26     sourcelines, file_lineno = inspect.getsourcelines(obj)
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/inspect.py", line 955, in getsourcelines
Jun 16 02:37:26     lines, lnum = findsource(object)
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/inspect.py", line 786, in findsource
Jun 16 02:37:26     raise OSError('could not get source code')
Jun 16 02:37:26 OSError: could not get source code
Jun 16 02:37:26 
Jun 16 02:37:26 The above exception was the direct cause of the following exception:
Jun 16 02:37:26 
Jun 16 02:37:26 Traceback (most recent call last):
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/internal.py", line 204, in _run_function
Jun 16 02:37:26     result = python_udf.func(*python_udf.args, **python_udf.kwargs)
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/nn/api/remote_module.py", line 76, in _instantiate_template
Jun 16 02:37:26     module_interface_cls, enable_moving_cpu_tensors_to_cuda
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/nn/jit/instantiator.py", line 140, in instantiate_scriptable_remote_module_template
Jun 16 02:37:26     generated_module_name, str_dict, enable_moving_cpu_tensors_to_cuda
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/nn/jit/instantiator.py", line 99, in _do_instantiate_remote_module_template
Jun 16 02:37:26     generated_module = importlib.import_module(f"{generated_module_name}")
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
Jun 16 02:37:26     return _bootstrap._gcd_import(name[level:], package, level)
Jun 16 02:37:26   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jun 16 02:37:26   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jun 16 02:37:26   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
Jun 16 02:37:26   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
Jun 16 02:37:26   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
Jun 16 02:37:26   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jun 16 02:37:26   File "/tmp/tmp7v7ts2xx/_remote_module___torch___torch_testing__internal_distributed_nn_api_remote_module_test_MyModuleInterface.py", line 46, in <module>
Jun 16 02:37:26     module_rref: RRef[module_interface_cls], device: str, is_device_map_set: bool, tensor: Tensor, number: int, word: str) -> Tuple[str, int, Tensor]:
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/jit/_script.py", line 1166, in script
Jun 16 02:37:26     ast = get_jit_def(obj, obj.__name__)
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/jit/frontend.py", line 269, in get_jit_def
Jun 16 02:37:26     sourcelines, file_lineno, filename = get_source_lines_and_file(fn, torch._C.ErrorReport.call_stack())
Jun 16 02:37:26   File "/opt/conda/lib/python3.6/site-packages/torch/_utils_internal.py", line 66, in get_source_lines_and_file
Jun 16 02:37:26     raise OSError(msg) from e
Jun 16 02:37:26 OSError: Can't get source for <function _remote_forward at 0x7f278e430378>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
```

https://www.internalfb.com/intern/opensource/ci/job/log/198096968881685/

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @agolynski @SciPioneer @H-Huang @cbalioglu @gcramer23

**Comment by mrshenli** [comment]
cc @SciPioneer
