### ISSUE TITLE
[C++] grad_input may have different memory_format from grad_output in structured kernels

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#60137]
## 🐛 Bug

[C++] grad_input may have different memory_format from grad_output in structured kernels

## To Reproduce

1. Apply the following diff to current master (691183bb740a890d6972803e996bcca63673a7c4)

```diff
diff --git a/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu b/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu
index cb77158036..5bf0616bab 100644
--- a/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu
+++ b/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu
@@ -294,6 +294,12 @@ IntArrayRef dilation,
 bool ceil_mode,
 const Tensor& output,
 const Tensor& indices) {
+  if (input_.suggest_memory_format() == at::MemoryFormat::ChannelsLast) {
+    TORCH_INTERNAL_ASSERT(output.suggest_memory_format() == at::MemoryFormat::ChannelsLast,
+      "max_pool2d_with_indices_out_cuda output is not channels_last");
+    printf("ok, max_pool2d_with_indices_out_cuda output is channels_last\n");
+  }
+
   NoNamesGuard guard;
 
   TensorArg output_arg{ output, "output", 1 };
@@ -415,6 +421,12 @@ IntArrayRef dilation,
 bool ceil_mode,
 const Tensor& indices,
 const Tensor& gradInput) {
+  if (gradOutput_.suggest_memory_format() == at::MemoryFormat::ChannelsLast) {
+    TORCH_INTERNAL_ASSERT(gradInput.suggest_memory_format() == at::MemoryFormat::ChannelsLast,
+      "max_pool2d_with_indices_backward_out_cuda output is not channels_last");
+    printf("ok, max_pool2d_with_indices_backward_out_cuda output is channels_last\n");
+  }
+
   NoNamesGuard guard;
 
   TensorArg gradInput_arg{ gradInput, "gradInput", 1 };
diff --git a/aten/src/ATen/native/cuda/UpSampleNearest2d.cu b/aten/src/ATen/native/cuda/UpSampleNearest2d.cu
index b893cf8d1a..c8369159c7 100644
--- a/aten/src/ATen/native/cuda/UpSampleNearest2d.cu
+++ b/aten/src/ATen/native/cuda/UpSampleNearest2d.cu
@@ -267,6 +267,11 @@ TORCH_IMPL_FUNC(upsample_nearest2d_out_cuda) (
     c10::optional<double> scales_h,
     c10::optional<double> scales_w,
     const Tensor& output) {
+  if (input.suggest_memory_format() == at::MemoryFormat::ChannelsLast) {
+    TORCH_INTERNAL_ASSERT(output.suggest_memory_format() == at::MemoryFormat::ChannelsLast,
+      "upsample_nearest2d_out_cuda output is not channels_last");
+    printf("ok, upsample_nearest2d_out_cuda output is channels_last\n");
+  }
   upsample_nearest2d_out_cuda_template(output, input, output_size, scales_h, scales_w);
 }
 
@@ -277,6 +282,11 @@ TORCH_IMPL_FUNC(upsample_nearest2d_backward_out_cuda) (
     c10::optional<double> scales_h,
     c10::optional<double> scales_w,
     const Tensor& grad_input) {
+  if (grad_output.suggest_memory_format() == at::MemoryFormat::ChannelsLast) {
+    TORCH_INTERNAL_ASSERT(grad_input.suggest_memory_format() == at::MemoryFormat::ChannelsLast,
+      "upsample_nearest2d_backward_out_cuda grad_input is not channels_last");
+    printf("ok, upsample_nearest2d_backward_out_cuda grad_input is channels_last\n");
+  }
   upsample_nearest2d_backward_out_cuda_template(
       grad_input, grad_output, output_size, input_size, scales_h, scales_w);
 }

```

2. Run the following script

```python
import torch
import traceback

print(torch.__version__)

def test(f):
    try:
        _test(f)
    except:
        traceback.print_exc()

def _test(f):
    x = torch.randn(1, 2, 8, 8, dtype=torch.float, device='cuda')\
        .to(memory_format=torch.channels_last)
    x.requires_grad_()

    # y = torch.nn.functional.relu(x)
    y = f(x)
    g = torch.randn_like(y)

    assert y.is_contiguous(memory_format=torch.channels_last)
    assert g.is_contiguous(memory_format=torch.channels_last)
    y.backward(g)
    assert x.grad.is_contiguous(memory_format=torch.channels_last)

    torch.cuda.synchronize()


if __name__ == '__main__':
    test(lambda x: torch.nn.functional.max_pool2d(x, 3))
    test(torch.nn.functional.relu)
    test(lambda x: torch.nn.functional.interpolate(x, 16))
```

See sample output

```
1.10.0a0+git691183b
ok, max_pool2d_with_indices_out_cuda output is channels_last
/home/xwang/Developer/pytorch/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1301.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
ok, max_pool2d_with_indices_backward_out_cuda output is channels_last
ok, upsample_nearest2d_out_cuda output is channels_last
Traceback (most recent call last):
  File "/home/xwang/Developer/pytorch-test/random-things/temp-gradinput-structured.py", line 8, in test
    _test(f)
  File "/home/xwang/Developer/pytorch-test/random-things/temp-gradinput-structured.py", line 23, in _test
    y.backward(g)
  File "/home/xwang/Developer/pytorch/torch/_tensor.py", line 256, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/xwang/Developer/pytorch/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: grad_input.suggest_memory_format() == at::MemoryFormat::ChannelsLastINTERNAL ASSERT FAILED at "/home/xwang/Developer/pytorch/aten/src/ATen/native/cuda/UpSampleNearest2d.cu":286, please report a bug to PyTorch. upsample_nearest2d_backward_out_cuda grad_input is not channels_last
```

It is seen that `upsample_nearest2d_backward_out_cuda grad_input is not channels_last`.

## Expected behavior

If I understand correctly, those `TORCH_IMPL_FUNC` in the source code mean the usage of structured kernels? 

For the relu kernels, both forward and backward use TensorIterator. The memory format of grads and outputs are preserved (channels_last), which is great. 

For max_pool2d, which uses structured kernels, the memory format of grads and outputs are preserved (channels_last), which is great.

However, for interpolate, which uses structured kernels, the memory format (channels_last) is only preserved in the forward pass, but is not in the backward pass. This makes it a bit complicated to work on channels_last path of native kernels. See #56322 and https://github.com/pytorch/pytorch/pull/56322#discussion_r642134654.

## Environment

```
Collecting environment information...
PyTorch version: 1.10.0a0+git691183b
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.33

Python version: 3.9 (64-bit runtime)
Python platform: Linux-5.10.36-2-MANJARO-x86_64-with-glibc2.33
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: 
GPU 0: GeForce RTX 2070 SUPER
GPU 1: GeForce GTX 1070 Ti

Nvidia driver version: 460.80
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.2.0
/usr/lib/libcudnn_adv_infer.so.8.2.0
/usr/lib/libcudnn_adv_train.so.8.2.0
/usr/lib/libcudnn_cnn_infer.so.8.2.0
/usr/lib/libcudnn_cnn_train.so.8.2.0
/usr/lib/libcudnn_ops_infer.so.8.2.0
/usr/lib/libcudnn_ops_train.so.8.2.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0a0+git691183b
[pip3] torchvision==0.10.0a0+7d955df
[conda] Could not collect
```

## Additional context

cc @VitalyFedyunin @jamesr66a @ppwwyyxx @ezyang @ngimel @zasdfgbnm @ptrblck

**Comment by ngimel** [comment]
The problem is most likely in the META function that handles the allocation of grad_input. Note that after fixing META function (probably in similar way that MaxPooling operates today) cpu implementation will also need to be changed to be able to handle channels-last grad_input (just by copying whatever format cpu implementation produces to correctly strided grad_input).

**Comment by ezyang** [comment]
Yes, what @ngimel said!
