### ISSUE TITLE
[1.9.0] torch.profiler.tensorboard_trace_handler doesn't generate valid data

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#60145]
## 🐛 Bug

I tried to replicate: https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html 

when the log is generated and I try to load it, when I go to  http://localhost:6006/ I get:

```
tensorboard --logdir=./log                           
2021-06-16 19:25:39.748760: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

I0616 19:25:40.729878 139909655127808 plugin.py:292] Monitor runs begin
I0616 19:25:40.731639 139909655127808 plugin.py:310] Find run directory /mnt/nvme1/code/huggingface/torch-profiler/log/resnet18
I0616 19:25:40.732423 139911335974656 plugin.py:358] Load run resnet18
I0616 19:25:40.737549 139911335974656 loader.py:56] starting all processing
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.5.0 at http://localhost:6006/ (Press CTRL+C to quit)
I0616 19:25:41.582570 139911335974656 plugin.py:362] Run resnet18 loaded
I0616 19:25:41.582768 139911478585088 plugin.py:327] Add run resnet18
W0616 19:25:49.419933 139909848078080 security_validator.py:46] In 3.0, this warning will become an error:
Requires default-src for Content-Security-Policy
E0616 19:25:49.833019 139909848078080 _internal.py:113] Error on request:
Traceback (most recent call last):
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/application.py", line 525, in __call__
    return self._app(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/application.py", line 566, in wrapper
    return wsgi_app(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/security_validator.py", line 77, in __call__
    return self._application(environ, start_response_proxy)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py", line 68, in __call__
    return self._application(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py", line 73, in __call__
    return self._application(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py", line 43, in __call__
    return self._application(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/application.py", line 589, in wrapper
    return wsgi_app(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/application.py", line 548, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/werkzeug/wrappers/base_request.py", line 238, in application
    resp = f(*args[:-2] + (request,))
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch_tb_profiler/plugin.py", line 153, in overview_route
    gpu_metrics_data, gpu_metrics_tooltip = profile.get_gpu_metrics_data_tooltip()
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch_tb_profiler/run.py", line 217, in get_gpu_metrics_data_tooltip
    data, has_occupancy, has_sm_efficiency = get_gpu_metrics_data(self)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch_tb_profiler/run.py", line 199, in get_gpu_metrics_data
    round(profile.sm_efficency[gpu_id] * 100, 2))})
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

I tried the samples provided with https://github.com/pytorch/kineto/tree/master/tb_plugin and they load just fine.

So my guess is that `torch.profiler.tensorboard_trace_handler` is not writing something out as expected by `torch_tb_profiler`.

## Environment
```
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-73-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1070 Ti
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0+cu111
[pip3] torch-tb-profiler==0.2.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0+cu111
[conda] mkl                       2021.2.0           h06a4308_296
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.9.0+cu111              pypi_0    pypi
[conda] torch-tb-profiler         0.2.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchvision               0.10.0+cu111             pypi_0    pypi
```

```
tensorboard 2.5.0
```
I also tried to downgrade `tensorboard` but the error is the same.

Originally filed under https://github.com/pytorch/kineto/issues/300, but I think this bug actually belongs here.

**Comment by gaoteng-git** [comment]
@stas00 Same with this: https://github.com/pytorch/kineto/issues/299#issuecomment-863064825

**Comment by stas00** [comment]
I confirm that https://github.com/pytorch/kineto/pull/305 fixed it - thank you for the quick fix, @gaoteng-git!
