### ISSUE TITLE
Tensor.permute() & Conv2d activation checkpointing cause RuntimeError on GPU 

### ISSUE THREAD

**Issue by gahdritz** [pytorch/pytorch#60148]
## 🐛 Bug

Permuting more than two axes of a Tensor before feeding it to a checkpointed Conv2d layer causes a crash during the backward pass when CUDA is enabled. All three conditions appear to be necessary: if exactly 2 axes are permuted, if the first layer in the checkpoint is not specifically of type torch.nn.Conv2d, or if the operations are performed on CPU, no error occurs.

## To Reproduce

Here's some (fairly) minimal reproduction code, tested on my Ubuntu machine and on Google Colab. It crashes iff CUDA is available:

```
import torch
from torch.utils.checkpoint import checkpoint

class ConvModel(torch.nn.Module):
    def __init__(self, n_in):
        super(ConvModel, self).__init__()
        self.init = torch.nn.Conv2d(n_in, n_in, 1)
        self.conv = torch.nn.Conv2d(n_in, n_in, 1)

    def forward(self, x):
        x = x.permute(0, 3, 1, 2)
        x = self.init(x) # natural way to enable x.requires_grad before the checkpoint
        x = checkpoint(self.conv, x)
        return x


# Some constants
batch_size = 1
n_in = 10
h_w = 10

cuda = torch.cuda.is_available()

m = ConvModel(n_in)
if(cuda):
    m = m.cuda()
optimizer = torch.optim.Adam(m.parameters())
loss_fn = torch.nn.CrossEntropyLoss()

# Simple training loop; nothing fancy here
for i in range(1000):
    optimizer.zero_grad()

    # Arbitrary inputs
    inp = torch.rand((batch_size, h_w, h_w, n_in))
    target = torch.zeros((batch_size, h_w, h_w), dtype=torch.int64)
    if(cuda):
        inp = inp.cuda()
        target = target.cuda()

    out = m(inp)
    loss = loss_fn(out, target)
    loss.backward() # crash occurs here
    optimizer.step()
```

Note that the input to the checkpoint is passed through an initial convolutional layer. This has the effect of enabling `requires_grad` for `x`. This is a prerequisite for at least one of the inputs to each checkpoint (see e.g. [this thread](https://discuss.pytorch.org/t/checkpoint-with-no-grad-requiring-inputs-problem/19117)).

## Trace
```
Traceback (most recent call last):
  File "reproduce_checkpoint_bug.py", line 64, in <module>
    loss.backward()
  File "/home/ga122/openfold/code/venv/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ga122/openfold/code/venv/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: set_sizes_and_strides is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)
```

## Environment

The output of torch/utils/collect_env.py in the former environment:

```
Collecting environment information...
PyTorch version: 1.8.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.25

Python version: 3.6 (64-bit runtime)
Python platform: Linux-4.15.0-58-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 430.40
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] light-the-torch==0.3.1
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.3.3
[pip3] torch==1.8.1+cu101
[pip3] torchmetrics==0.3.2
[pip3] torchvision==0.9.1
[conda] Could not collect
```

Alternatively, the crash can be reproduced on Colab, which is also running torch==1.8.1+cu101 by default at the moment.

**Comment by gchanan** [comment]
CC @albanD

**Comment by albanD** [comment]
This has already been fixed IIRC
Using the latest release 1.9 or nightly build will fix that.

**Comment by Lmy0217** [comment]
@albanD 

I got same error with follow code:
```
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.checkpoint import checkpoint


class LayerNorm2d(nn.LayerNorm):

    def __init__(self, normalized_shape, eps=1e-6):
        super().__init__(normalized_shape, eps=eps)

    def forward(self, x):
        return F.layer_norm(x.permute(0, 2, 3, 1), self.normalized_shape, self.weight, self.bias, self.eps).permute(0, 3, 1, 2)


if __name__ == '__main__':
    device = torch.device('cuda')

    layernorm = LayerNorm2d(3).to(device)
    conv = nn.Conv2d(3, 3, kernel_size=1).to(device)

    x = torch.ones(4, 3, 224, 224, device=device, requires_grad=True)
    x = layernorm(x)
    x = checkpoint(conv, x)

    loss = torch.mean(x)
    loss.backward()
```

The error is
```
Traceback (most recent call last):
  File "D:/works/MedicalImaging/test/convnext2.py", line 28, in <module>
    l.backward()
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\function.py", line 199, in apply
    return user_fn(self, *args)
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\checkpoint.py", line 122, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: set_sizes_and_strides is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)
```

Environment
```
PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 企业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.19.2
Libc version: N/A

Python version: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 471.41
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] adabelief-pytorch==0.2.1
[pip3] nfnets-pytorch==0.1.3
[pip3] numpy==1.21.4
[pip3] robust-loss-pytorch==0.0.2
[pip3] torch==1.10.1+cu113
[pip3] torch-dct==0.1.5
[pip3] torchaudio==0.10.1+cu113
[pip3] torchio==0.18.70
[pip3] torchstat==0.0.7
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.11.2+cu113
[conda] Could not collect
```

**Comment by albanD** [comment]
I can't reproduce that on CPU.
Can you open a new issue please to track what is happening?

**Comment by Lmy0217** [comment]
@albanD Yes, there are errors on cuda but not on cpu.

**Comment by Lmy0217** [comment]
#72569
