### ISSUE TITLE
PEP-585 type annotations not supported for class-level annotations

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#60156]
## 🐛 Bug

Pytorch 1.9 supports PEP-585 type annotations, but JIT fails when annotations are used outside functions. The same works with `List[torch.Tensor]`.

## To Reproduce

```py
import torch

class Test(torch.nn.Module):
    ys: list[torch.Tensor]

    def __init__(self):
        super().__init__()
        self.ys = []

torch.jit.script(Test())
```
```sh
$ python jit2.py
Traceback (most recent call last):
  File "/pool01/home/twoertwe/git/python-tools/jit2.py", line 14, in <module>
    torch.jit.script(Test())
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.9/lib/python3.9/site-packages/torch/jit/_script.py", line 1096, in script
    return torch.jit._recursive.create_script_module(
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.9/lib/python3.9/site-packages/torch/jit/_recursive.py", line 410, in create_script_module
    concrete_type = get_module_concrete_type(nn_module, share_types)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.9/lib/python3.9/site-packages/torch/jit/_recursive.py", line 386, in get_module_concrete_type
    concrete_type = concrete_type_store.get_or_create_concrete_type(nn_module)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.9/lib/python3.9/site-packages/torch/jit/_recursive.py", line 327, in get_or_create_concrete_type
    concrete_type_builder = infer_concrete_type_builder(nn_module)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.9/lib/python3.9/site-packages/torch/jit/_recursive.py", line 291, in infer_concrete_type_builder
    attr_type, inferred = infer_type(name, value)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.9/lib/python3.9/site-packages/torch/jit/_recursive.py", line 139, in infer_type
    ann_to_type = torch.jit.annotations.ann_to_type(class_annotations[name], _jit_internal.fake_range())
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.9/lib/python3.9/site-packages/torch/jit/annotations.py", line 376, in ann_to_type
    raise ValueError(f"Unknown type annotation: '{ann}' at {loc.highlight()}")
ValueError: Unknown type annotation: 'list[torch.Tensor]' at
```

cc @gmagogsfm

**Comment by walterddr** [comment]
# TODO add test to use PEP585 type annotation for return type after py3.9        # see: https://www.python.org/dev/peps/pep-0585/#id5<br class="Apple-interchange-newline">

**Comment by walterddr** [comment]
I think this is captured in https://github.com/pytorch/pytorch/pull/57363#discussion_r626219073:
Since we are still supporting py36 until its EOL, we can't do something like `from __future__ import annotations` which is not there until py3.7

See TODO in
https://github.com/pytorch/pytorch/blob/59b10036d557cf99df90a25d3a3a04d6312ac4f6/test/jit/test_types.py#L25-L26

**Comment by twoertwein** [comment]
Something like the following works

```py
import torch

def fun(x: torch.Tensor) -> torch.Tensor:
    xs: list[torch.Tensor] = []
    xs.append(x)
    return xs.pop()

torch.jit.script(fun)
```
and this works too
```py
import torch

class Test(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.ys: list[torch.Tensor] = []
```
but the example from the first post does not work.

Might be about time to drop 3.6 (numpy dropped support for it with numpy 1.20).

**Comment by twoertwein** [comment]
PEP-585 type annotations do also not work when nested inside `typing.Optional`.
```py
from typing import Optional
import torch

def fun(x: torch.Tensor) -> torch.Tensor:
    xs: Optional[list[torch.Tensor]] = []
    assert xs is not None
    xs.append(x)
    return xs.pop()

torch.jit.script(fun)
```

```
Traceback (most recent call last):
  File "/pool01/home/twoertwe/git/python-tools/foobar.py", line 13, in <module>
    torch.jit.script(fun)
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.9/lib/python3.9/site-packages/torch/jit/_script.py", line 1143, in script
    fn = torch._C._jit_script_compile(
  File "/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.9/lib/python3.9/site-packages/torch/jit/annotations.py", line 324, in try_ann_to_type
    assert valid_type, msg.format(repr(ann), repr(contained))
AssertionError: Unsupported annotation typing.Optional[list[torch.Tensor]] could not be resolved because list[torch.Tensor] could not be resolved.
```

**Comment by randolf-scholz** [comment]
Python 3.6 EOL is next week, this would be an appreciated addition for the next release of pytorch.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
