### ISSUE TITLE
torch.load non backwards compatible on Transformer between 1.8.1 and 1.9.0

### ISSUE THREAD

**Issue by jhoareau** [pytorch/pytorch#60165]
## 🐛 Bug

A Transformer that I used `torch.save` on with Pytorch 1.8.1 cannot load on Pytorch 1.9.0.

## To Reproduce

On Pytorch 1.8.1:
```python
import torch
from torch.nn import Transformer
torch.save(Transformer(), 'transformer.pt')
```
Then update Pytorch to 1.9.0
```python
import torch
torch.load('transformer.pt')
```
The following stacktrace will show:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File ".../python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File ".../python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute '_LinearWithBias' on <module 'torch.nn.modules.linear' from '.../python3.8/site-packages/torch/nn/modules/linear.py'>
```

## Expected behavior

`torch.save()` on Pytorch X should be able to load modules that are saved on previous versions (https://github.com/pytorch/pytorch/issues/6801#issuecomment-383178266 says that torch.load is supposed to be backwards-compatible)

In this specific case, redefining the `_LinearWithBias` module in torch.nn.modules.linear would solve the issue.

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): macOS (but it also happens on Linux with a model loaded & saved there)
 - How you installed PyTorch (`conda`, `pip`, source): `pip`
 - Python version: 3.8.7
 - CUDA/cuDNN version: None
 - GPU models and configuration: No

**Comment by jhoareau** [comment]
@bhosmer It looks like the breaking of backwards compatibility was introduced in your PR here https://github.com/pytorch/pytorch/pull/58727

**Comment by jhoareau** [comment]
And @gchanan https://github.com/pytorch/pytorch/pull/52537#issuecomment-782443763 - this might also be related to this issue.

**Comment by gchanan** [comment]
see https://pytorch.org/docs/stable/notes/serialization.html#id4 -- you should serialize the state_dict, not the module.

**Comment by zou3519** [comment]
Marking for triage review because I think we should really do something about https://pytorch.org/docs/stable/notes/serialization.html#id4 -- this is not the first time this has happened

**Comment by mruberry** [comment]
I think the doc is correct, though, right? It's just undiscoverable?

**Comment by jhoareau** [comment]
https://pytorch.org/tutorials/beginner/saving_loading_models.html#save-load-entire-model is mentioning the risk in refactoring our own application but does not warn about the risk of Pytorch cross-version incompatibilities.

**Comment by mruberry** [comment]
cc @brianjo for the tutorial update
