### ISSUE TITLE
cannot build with tensorrt

### ISSUE THREAD

**Issue by beew** [pytorch/pytorch#60228]
pytorch fails to build with tensorrt

Tried to build pytorch with the environmental variables

```
export CMAKE_LIBRARY_PATH=/opt/intel/oneapi/mkl/latest/lib/intel64:/usr/local/tensorrt/lib
export CMAKE_INCLUDE_PATH=/opt/intel/oneapi/mkl/latest/include:/usr/local/tensorrt/include
export USE_CUDA=1 USE_CUDNN=1 USE_MKLDNN=1  USE_OPENCV=1 USE_FFMPEG=1 GPU_ARCH=sm_6 USE_TENSORRT=1

```
Build fails with (below from building with pytorch 1.8, it is similar for 1.9)

```
building CXX object third_party/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o
FAILED: third_party/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o 
/usr/bin/c++  -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -I../third_party/foxi -Ithird_party/foxi -isystem third_party/gloo -isystem ../cmake/../third_party/gloo -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party/protobuf/src -isystem /opt/intel/oneapi/mkl/latest/include -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party/XNNPACK/include -isystem ../third_party -isystem /home/bernard/opt/opencv/include/opencv4 -isystem ../cmake/../third_party/eigen -isystem /home/bernard/opt/python38/include/python3.8 -isystem /home/bernard/opt/python38/lib/python3.8/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -isystem /opt/openmpi/include -isystem /usr/local/cuda/include -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DTENSORRT_VERSION_MAJOR=8 -DTENSORRT_VERSION_MINOR=0 -Wall -Wno-deprecated-declarations -Wno-unused-function -O3 -DNDEBUG -fPIC   -DCAFFE2_USE_GLOO -std=gnu++11 -MD -MT third_party/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o -MF third_party/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o.d -o third_party/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o -c ../third_party/onnx-tensorrt/builtin_op_importers.cpp
In file included from ../third_party/onnx-tensorrt/onnx2trt_utils.hpp:26,
                 from ../third_party/onnx-tensorrt/builtin_op_importers.cpp:24:
../third_party/onnx-tensorrt/trt_utils.hpp: In function ‘nvinfer1::Dims onnx2trt::insert_dim(const Dims&, int, int)’:
../third_party/onnx-tensorrt/trt_utils.hpp:69:14: error: ‘using Dims = class nvinfer1::Dims32’ {aka ‘class nvinfer1::Dims32’} has no member named ‘type’
   69 |     new_dims.type[i] = dims.type[i];
      |              ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp:69:29: error: ‘const Dims’ {aka ‘const class nvinfer1::Dims32’} has no member named ‘type’
   69 |     new_dims.type[i] = dims.type[i];
      |                             ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp:74:14: error: ‘using Dims = class nvinfer1::Dims32’ {aka ‘class nvinfer1::Dims32’} has no member named ‘type’
   74 |     new_dims.type[i] = dims.type[i - 1];
      |              ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp:74:29: error: ‘const Dims’ {aka ‘const class nvinfer1::Dims32’} has no member named ‘type’
   74 |     new_dims.type[i] = dims.type[i - 1];
      |                             ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp: In function ‘nvinfer1::Dims onnx2trt::remove_dim(const Dims&, int)’:
../third_party/onnx-tensorrt/trt_utils.hpp:85:14: error: ‘using Dims = class nvinfer1::Dims32’ {aka ‘class nvinfer1::Dims32’} has no member named ‘type’
   85 |     new_dims.type[i] = dims.type[i];
      |              ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp:85:29: error: ‘const Dims’ {aka ‘const class nvinfer1::Dims32’} has no member named ‘type’
   85 |     new_dims.type[i] = dims.type[i];
      |                             ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp:89:14: error: ‘using Dims = class nvinfer1::Dims32’ {aka ‘class nvinfer1::Dims32’} has no member named ‘type’
   89 |     new_dims.type[i] = dims.type[i + 1];
      |              ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp:89:29: error: ‘const Dims’ {aka ‘const class nvinfer1::Dims32’} has no member named ‘type’
   89 |     new_dims.type[i] = dims.type[i + 1];
      |                             ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp:95:14: error: ‘using Dims = class nvinfer1::Dims32’ {aka ‘class nvinfer1::Dims32’} has no member named ‘type’
   95 |     new_dims.type[0] = nvinfer1::DimensionType::kCHANNEL;
      |              ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp:95:34: error: ‘nvinfer1::DimensionType’ has not been declared
   95 |     new_dims.type[0] = nvinfer1::DimensionType::kCHANNEL;
      |                                  ^~~~~~~~~~~~~
In file included from ../third_party/onnx-tensorrt/onnx2trt_utils.hpp:26,
                 from ../third_party/onnx-tensorrt/builtin_op_importers.cpp:24:
../third_party/onnx-tensorrt/trt_utils.hpp: In function ‘nvinfer1::Dims onnx2trt::set_dims_CHW(const Dims&)’:
../third_party/onnx-tensorrt/trt_utils.hpp:146:12: error: ‘using Dims = class nvinfer1::Dims32’ {aka ‘class nvinfer1::Dims32’} has no member named ‘type’
  146 |   new_dims.type[0] = nvinfer1::DimensionType::kCHANNEL;
      |            ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp:146:32: error: ‘nvinfer1::DimensionType’ has not been declared
  146 |   new_dims.type[0] = nvinfer1::DimensionType::kCHANNEL;
      |                                ^~~~~~~~~~~~~
../third_party/onnx-tensorrt/trt_utils.hpp:148:14: error: ‘using Dims = class nvinfer1::Dims32’ {aka ‘class nvinfer1::Dims32’} has no member named ‘type’
  148 |     new_dims.type[i] = nvinfer1::DimensionType::kSPATIAL;
      |              ^~~~
../third_party/onnx-tensorrt/trt_utils.hpp:148:34: error: ‘nvinfer1::DimensionType’ has not been declared
  148 |     new_dims.type[i] = nvinfer1::DimensionType::kSPATIAL;
      |                                  ^~~~~~~~~~~~~
In file included from ../third_party/onnx-tensorrt/builtin_op_importers.cpp:24:
../third_party/onnx-tensorrt/onnx2trt_utils.hpp: At global scope:
../third_party/onnx-tensorrt/onnx2trt_utils.hpp:38:1: error: expected class-name before ‘{’ token
   38 | {
      | ^
../third_party/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importAveragePool(onnx2trt::IImporterContext*, const onnx_torch::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)’:
../third_party/onnx-tensorrt/builtin_op_importers.cpp:159:19: error: ‘DimsNCHW’ is not a member of ‘nvinfer1’; did you mean ‘DimsHW’?
  159 |         nvinfer1::DimsNCHW new_shape(dims.d[0], dims.d[1], dims.d[2], 1);
      |                   ^~~~~~~~
      |                   DimsHW
../third_party/onnx-tensorrt/builtin_op_importers.cpp:160:55: error: ‘new_shape’ was not declared in this scope
  160 |         tensor_ptr = reshape_tensor(ctx, *tensor_ptr, new_shape);
      |                                                       ^~~~~~~~~
../third_party/onnx-tensorrt/builtin_op_importers.cpp:177:29: error: ‘class nvinfer1::INetworkDefinition’ has no member named ‘setPoolingOutputDimensionsFormula’
  177 |             ctx->network()->setPoolingOutputDimensionsFormula(&ceilingPool);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importGemm(onnx2trt::IImporterContext*, const onnx_torch::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)’:
../third_party/onnx-tensorrt/builtin_op_importers.cpp:836:20: error: the type ‘const onnx2trt::{anonymous}::importGemm(onnx2trt::IImporterContext*, const onnx_torch::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)::<lambda(const nvinfer1::ITensor&, bool)>’ of ‘constexpr’ variable ‘getMatrixOp’ is not literal
  836 |     constexpr auto getMatrixOp = [](const nvinfer1::ITensor& input, bool transpose) {
      |                    ^~~~~~~~~~~
../third_party/onnx-tensorrt/builtin_op_importers.cpp:836:35: note: ‘onnx2trt::{anonymous}::importGemm(onnx2trt::IImporterContext*, const onnx_torch::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)::<lambda(const nvinfer1::ITensor&, bool)>’ is not literal because:
  836 |     constexpr auto getMatrixOp = [](const nvinfer1::ITensor& input, bool transpose) {
      |                                   ^
cc1plus: note:   ‘onnx2trt::{anonymous}::importGemm(onnx2trt::IImporterContext*, const onnx_torch::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)::<lambda(const nvinfer1::ITensor&, bool)>’ is a closure type, which is only literal in C++17 and later
../third_party/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importMatMul(onnx2trt::IImporterContext*, const onnx_torch::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)’:
../third_party/onnx-tensorrt/builtin_op_importers.cpp:1273:20: error: the type ‘const onnx2trt::{anonymous}::importMatMul(onnx2trt::IImporterContext*, const onnx_torch::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)::<lambda(const nvinfer1::ITensor&)>’ of ‘constexpr’ variable ‘getMatrixOp’ is not literal
 1273 |     constexpr auto getMatrixOp = [](const nvinfer1::ITensor& input) {
      |                    ^~~~~~~~~~~
../third_party/onnx-tensorrt/builtin_op_importers.cpp:1273:35: note: ‘onnx2trt::{anonymous}::importMatMul(onnx2trt::IImporterContext*, const onnx_torch::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)::<lambda(const nvinfer1::ITensor&)>’ is not literal because:
 1273 |     constexpr auto getMatrixOp = [](const nvinfer1::ITensor& input) {
      |                                   ^
cc1plus: note:   ‘onnx2trt::{anonymous}::importMatMul(onnx2trt::IImporterContext*, const onnx_torch::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)::<lambda(const nvinfer1::ITensor&)>’ is a closure type, which is only literal in C++17 and later
../third_party/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importMaxPool(onnx2trt::IImporterContext*, const onnx_torch::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)’:
../third_party/onnx-tensorrt/builtin_op_importers.cpp:1300:19: error: ‘DimsNCHW’ is not a member of ‘nvinfer1’; did you mean ‘DimsHW’?
 1300 |         nvinfer1::DimsNCHW new_shape(dims.d[0], dims.d[1], dims.d[2], 1);
      |                   ^~~~~~~~
      |                   DimsHW
../third_party/onnx-tensorrt/builtin_op_importers.cpp:1301:55: error: ‘new_shape’ was not declared in this scope
 1301 |         tensor_ptr = reshape_tensor(ctx, *tensor_ptr, new_shape);
      |                                                       ^~~~~~~~~
../third_party/onnx-tensorrt/builtin_op_importers.cpp:1320:29: error: ‘class nvinfer1::INetworkDefinition’ has no member named ‘setPoolingOutputDimensionsFormula’
 1320 |             ctx->network()->setPoolingOutputDimensionsFormula(&ceilingPool);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/onnx-tensorrt/builtin_op_importers.cpp: In lambda function:
../third_party/onnx-tensorrt/builtin_op_importers.cpp:1820:45: error: too many initializers for ‘nvinfer1::Dims’ {aka ‘nvinfer1::Dims32’}
 1820 |         nvinfer1::Dims result{nbDims, {}, {}};
      |                                             ^
[2365/6032] Building CXX object third_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/src/FbgemmI8Depthwise3DAvx2.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 818, in <module>
    build_deps()
  File "setup.py", line 315, in build_deps
    build_caffe2(version=version,
  File "/home/bernard/opt/python38/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/home/bernard/opt/python38/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/bernard/opt/python38/pytorch/tools/setup_helpers/cmake.py", line 140, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/bernard/opt/python38/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.
```

PyTorch Version 1.8 and 1.9
 OS Ubuntu 20.04
 install pytorch from source
build command: python setup.py build
Python version: 3.8.10
CUDA 11.0 CUDNN 8.1 TensorRT 8.0

GPU Nvidia GTX1070

Without Tensorrt build was successful, seems Onnx doesn't play well with tensorrt. Does it make sense to disable Onnx? if yes, how. I tried USE_ONNX=0, but it was ignored as an invalid option.

P.S pytorch's build system couldn't find tensorrt (and MKL) without setting the CMAKE_LIBRARY_PATH and CMAKE_INCLUDE_PATH environmental variables as above  even though the tensorrt libs were symlinked to /usr/local/cuda/lib64 which cmake did detect in finding CUDA. See also https://github.com/pytorch/pytorch/issues/24334, it is closed but apparently never really resolved.

cc @malfet @seemethere @walterddr @ngimel

**Comment by h6197627** [comment]
Unfortunately, it is not compatible with newly released TensorRT 8 as it removed many deprecated features that are still in use by PyTorch/Caffe2. Currently one solution is to downgrade TensorRT to 7.x

**Comment by pallgeuer** [comment]
Is there any plan for PyTorch to support TensorRT 8 in the near future?
The last TensorRT 7 is over a year old now, and wants the now also old cuDNN 8.1.1...

**Comment by aifartist** [comment]
And even a year later than the comment above saying TensorRT 7 is over a year old I get the same problem now.
We've had TRT 8.5.1, 8.5.2.2 and now 8.5.3 and PyTorch is still stuck on a very old TRT.

**Comment by Jj202307** [comment]
Any updates on TensorRT support???
