### ISSUE TITLE
Failing tests in TestUnaryUfuncsCPU

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#60259]
## 🐛 Bug

As written at https://github.com/pytorch/pytorch/pull/59382#issuecomment-855809842 there are 2 new failing tests in master/1.9.0

- test_reference_numerics_hard_atanh_cpu_complex64
- test_complex_edge_values_cpu_complex64

Those refer to acos and atanh which dispatch to the std variants and those return nan/inf for the tested input values (on PPC and x86) as can be checked with:
```
#include <iostream>
#include <complex>

int main(){
  auto bar = std::acos(std::complex<float>(0, 1e+20));
  auto baz = std::atanh(std::complex<float>(-501, 1e+20));
  std::cout << bar << std::endl;
  std::cout << baz << std::endl;
}
```
--> `(1.5708,-inf) (-nan,1.5708)`

## To Reproduce

1. Build and run tests

## Log
```
======================================================================
FAIL: test_complex_edge_values_cpu_complex64 (__main__.TestUnaryUfuncsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/easybuild-tmp/eb-QUShZT/tmpWnHUca/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "test_unary_ufuncs.py", line 554, in test_complex_edge_values
    self.compare_with_numpy(torch.acos, np.arccos, x)
  File "/tmp/easybuild-tmp/eb-QUShZT/tmpWnHUca/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1145, in compare_with_numpy
    self.assertEqual(np_result, torch_result, **kwargs)
  File "/tmp/easybuild-tmp/eb-QUShZT/tmpWnHUca/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1269, in assertEqual
    self.assertEqual(x, y.item(), atol=atol, rtol=rtol, msg=msg,
  File "/tmp/easybuild-tmp/eb-QUShZT/tmpWnHUca/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1400, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing the imaginary part 46.74484634399414 and inf gives a difference of inf, but the allowed difference with rtol=1.3e-06 and atol=
1e-05 is only inf!

======================================================================
FAIL: test_reference_numerics_hard_atanh_cpu_complex64 (__main__.TestUnaryUfuncsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/easybuild-tmp/eb-QUShZT/tmpWnHUca/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/tmp/easybuild-tmp/eb-QUShZT/tmpWnHUca/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "/tmp/easybuild-tmp/eb-QUShZT/tmpWnHUca/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 626, in wrapper
    fn(*args, **kwargs)
  File "test_unary_ufuncs.py", line 348, in test_reference_numerics_hard
    self._test_reference_numerics(dtype, op, tensors)
  File "test_unary_ufuncs.py", line 321, in _test_reference_numerics
    _helper_reference_numerics(expected, actual, msg, exact_dtype, equal_nan)
  File "test_unary_ufuncs.py", line 299, in _helper_reference_numerics
    self.assertEqualHelper(actual, expected, msg, dtype=dtype, equal_nan=equal_nan, exact_dtype=exact_dtype)
  File "test_unary_ufuncs.py", line 261, in assertEqualHelper
    self.assertEqual(actual.item(), expected, **kwargs)
  File "/tmp/easybuild-tmp/eb-QUShZT/tmpWnHUca/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1400, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing the real part nan and -5.009999621329317e-38 gives a difference of nan, but the allowed difference with rtol=1.3e-06 and atol=
1e-05 is only 1e-05!
```

Note that those tests fail across all tested architectures

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @VitalyFedyunin @walterddr

**Comment by mruberry** [comment]
These tests appear to be passing in our CI -- do you have some more details about when they fail?

**Comment by Flamefire** [comment]
This behavior depends on the implementation of `std::acos`, and `std:.atanh` and hence the used standard libraries. Maybe your CI doesn't test the relevant stdlib? Or in this case libc/libm
On my own Ubuntu machine the above test case does not return nan/inf, on the RHEL and CentOS machines of our cluster it does.

Might be related to https://github.com/pytorch/pytorch/issues/52310

In any case: The tests or the code should not assume either stdlib

**Comment by ezyang** [comment]
Yeah if you can tell us more details about your stdlib/OS setup that would be helpful.

**Comment by Flamefire** [comment]
I'm using the libstdc++ which comes with GCC but the actual acos is done by libm from the CentOS 7 base package. Checking the strings it tells me it is libm 2.17 which matches `/lib64/libc.so.6 --version`:

```
GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.5 20150623 (Red Hat 4.8.5-39).
Compiled on a Linux 3.10.0 system on 2020-09-30.
Available extensions:
	The C stubs add-on version 2.1.2.
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
	RT using linux kernel aio
libc ABIs: UNIQUE IFUN
```

Anything else you need me to check?

**Comment by Flamefire** [comment]
Another datapoint: For atanh the "normal" and "extremal" tests are already excluded, just the "hard" one not, which looks like a plain oversight: Why skip "normal" but not "hard"? Maybe "hard" was intended? See https://github.com/pytorch/pytorch/blob/f2bb0932da3bc61a75867e4fec241ae8ca65b63e/torch/testing/_internal/common_methods_invocations.py#L5004-L5007
