### ISSUE TITLE
DISABLED test_ddp_dist_autograd_local_vs_remote (__main__.TensorPipeDdpComparisonTestWithSpawn)

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#60274]
## 🐛 Bug

https://app.circleci.com/pipelines/github/pytorch/pytorch/338732/workflows/fc60f41b-07d2-418f-907c-0a9c9996ad92/jobs/14235817

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd @agolynski @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
similar to https://github.com/pytorch/pytorch/issues/59792

**Comment by ezyang** [comment]
another occurrence https://github.com/pytorch/pytorch/pull/60050/checks?check_run_id=2842523351

**Comment by rohan-varma** [comment]
The following C++ stacktrace after python time out is also in the test logs:

```
Jun 18 14:38:28 Traceback (most recent call last):
Jun 18 14:38:28   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 18 14:38:28     getattr(self, test_name)()
Jun 18 14:38:28   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 18 14:38:28     fn()
Jun 18 14:38:28   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
Jun 18 14:38:28     return_value = old_test_method(self, *arg, **kwargs)
Jun 18 14:38:28   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py", line 633, in test_ddp_dist_autograd_local_vs_remote
Jun 18 14:38:28     layer1.weight = remote_layer1.module_rref.to_here().weight
Jun 18 14:38:28 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
Jun 18 14:38:28  exiting process with exit code: {MultiProcessTestCase.TEST_ERROR_EXIT_CODE}
Jun 18 14:38:28 [E request_callback_no_python.cpp:552] Received error while processing request type 275: Unexpected end of pickler archive.
Jun 18 14:38:28 Exception raised from readSlowWithBuffer at /var/lib/jenkins/workspace/torch/csrc/jit/serialization/unpickler.cpp:756 (most recent call first):
Jun 18 14:38:28 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f591684aed9 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 18 14:38:28 frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0xc5 (0x7f5916847155 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 18 14:38:28 frame #2: <unknown function> + 0x3f7c3b8 (0x7f591a9f83b8 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #3: torch::jit::Unpickler::run() + 0xdf (0x7f591aa028ef in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #4: torch::jit::Unpickler::parse_ivalue() + 0x2e (0x7f591aa02a5e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #5: torch::jit::unpickle(std::function<unsigned long (char*, unsigned long)>, std::function<c10::StrongTypePtr (c10::QualifiedName const&)>, c10::ArrayRef<at::Tensor>) + 0x25c (0x7f591a9d599c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #6: torch::jit::unpickle(char const*, unsigned long, std::function<c10::StrongTypePtr (c10::QualifiedName const&)>, c10::ArrayRef<at::Tensor>) + 0xdd (0x7f591a9d5ead in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #7: torch::distributed::autograd::CleanupAutogradContextReq::fromMessage(torch::distributed::rpc::Message const&) + 0xcb (0x7f591acce3fb in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #8: torch::distributed::rpc::deserializeRequest(torch::distributed::rpc::Message const&) + 0x1ed (0x7f591ad450bd in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #9: torch::distributed::rpc::RequestCallbackNoPython::processMessage(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x7f (0x7f591acf967f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #10: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x57 (0x7f591acf1b47 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #11: <unknown function> + 0x42abd41 (0x7f591ad27d41 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #12: c10::ThreadPool::main_loop(unsigned long) + 0x2a3 (0x7f5916820bd3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 18 14:38:28 frame #13: <unknown function> + 0xc8421 (0x7f5916744421 in /opt/conda/lib/libstdc++.so.6)
Jun 18 14:38:28 frame #14: <unknown function> + 0x76ba (0x7f59313ed6ba in /lib/x86_64-linux-gnu/libpthread.so.0)
Jun 18 14:38:28 frame #15: clone + 0x6d (0x7f593112351d in /lib/x86_64-linux-gnu/libc.so.6)
Jun 18 14:38:28 
Jun 18 14:38:28 [E request_callback_no_python.cpp:552] Received error while processing request type 275: Unexpected end of pickler archive.
Jun 18 14:38:28 Exception raised from readSlowWithBuffer at /var/lib/jenkins/workspace/torch/csrc/jit/serialization/unpickler.cpp:756 (most recent call first):
Jun 18 14:38:28 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f591684aed9 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 18 14:38:28 frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0xc5 (0x7f5916847155 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 18 14:38:28 frame #2: <unknown function> + 0x3f7c3b8 (0x7f591a9f83b8 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #3: torch::jit::Unpickler::run() + 0xdf (0x7f591aa028ef in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #4: torch::jit::Unpickler::parse_ivalue() + 0x2e (0x7f591aa02a5e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #5: torch::jit::unpickle(std::function<unsigned long (char*, unsigned long)>, std::function<c10::StrongTypePtr (c10::QualifiedName const&)>, c10::ArrayRef<at::Tensor>) + 0x25c (0x7f591a9d599c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #6: torch::jit::unpickle(char const*, unsigned long, std::function<c10::StrongTypePtr (c10::QualifiedName const&)>, c10::ArrayRef<at::Tensor>) + 0xdd (0x7f591a9d5ead in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #7: torch::distributed::autograd::CleanupAutogradContextReq::fromMessage(torch::distributed::rpc::Message const&) + 0xcb (0x7f591acce3fb in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #8: torch::distributed::rpc::deserializeRequest(torch::distributed::rpc::Message const&) + 0x1ed (0x7f591ad450bd in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #9: torch::distributed::rpc::RequestCallbackNoPython::processMessage(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x7f (0x7f591acf967f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #10: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x57 (0x7f591acf1b47 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #11: <unknown function> + 0x42abd41 (0x7f591ad27d41 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Jun 18 14:38:28 frame #12: c10::ThreadPool::main_loop(unsigned long) + 0x2a3 (0x7f5916820bd3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Jun 18 14:38:28 frame #13: <unknown function> + 0xc8421 (0x7f5916744421 in /opt/conda/lib/libstdc++.so.6)
Jun 18 14:38:28 frame #14: <unknown function> + 0x76ba (0x7f59313ed6ba in /lib/x86_64-linux-gnu/libpthread.so.0)
Jun 18 14:38:28 frame #15: clone + 0x6d (0x7f593112351d in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by ezyang** [comment]
> Do we know why these aren't getting skipped in CI? Test is test_ddp_dist_autograd_local_vs_remote (__main__.TensorPipeDdpComparisonTestWithSpawn), it looks like the issue formatting is right so it should get picked up by the service that disables tests every so often.

That log is from six days ago so it lines up.
