### ISSUE TITLE
ZeroRedundancyOptimizer rank_local_state_dict()

### ISSUE THREAD

**Issue by andwgu** [pytorch/pytorch#60284]
## 🐛 Bug

`ZeroRedundancyOptimizer`'s static method `rank_local_state_dict()` errors due to a reliance on the key ``"partitions"`` in the input ``state_dict``, which is not naturally present (i.e. in the `state_dict` output by the optimizer's `state_dict()` function).

## To Reproduce

To reproduce the behavior, run the following script (with at least 2 GPUs available):
```
import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
from torch.distributed.optim import ZeroRedundancyOptimizer
from torch.nn.parallel import DistributedDataParallel as DDP

def worker(rank, world_size):
    torch.manual_seed(0)
    torch.cuda.manual_seed(0)
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '29500'
    dist.init_process_group("gloo", rank=rank, world_size=world_size)

    model = nn.Sequential(*[nn.Linear(2000, 2000).to(rank) for _ in range(20)])
    ddp_model = DDP(model, device_ids=[rank])
    loss_fn = nn.MSELoss()
    optimizer = ZeroRedundancyOptimizer(
        ddp_model.parameters(),
        optimizer_class=torch.optim.Adam,
        lr=0.01
    )

    outputs = ddp_model(torch.randn(20, 2000).to(rank))
    labels = torch.randn(20, 2000).to(rank)
    loss_fn(outputs, labels).backward()
    optimizer.step()

    optimizer.consolidate_state_dict(0)
    if rank == 0:
        print(ZeroRedundancyOptimizer.rank_local_state_dict(0, optimizer.state_dict()))

def main():
    world_size = 2
    mp.spawn(worker,
             args=(world_size,),
             nprocs=world_size,
             join=True)

if __name__ == "__main__":
    main()
```

Running the script (in my case, named `scratch.py`) generates the following error:
```
Traceback (most recent call last):
  File "scratch.py", line 46, in <module>
  File "scratch.py", line 39, in main
    args=(world_size,),
  File "/fsx/users/andgu/work/pytorch/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/fsx/users/andgu/work/pytorch/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/fsx/users/andgu/work/pytorch/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/fsx/users/andgu/work/pytorch/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/fsx/users/andgu/work/milestone3/scratch.py", line 33, in worker
    print(ZeroRedundancyOptimizer.rank_local_state_dict(0, optimizer.state_dict()))
  File "/fsx/users/andgu/work/pytorch/torch/distributed/optim/zero_redundancy_optimizer.py", line 519, in rank_local_state_dict
    param_groups = state_dict["param_groups"][state_dict["partition"][rank][0] : state_dict["partition"][rank][1]]
KeyError: 'partition'
```

## Expected behavior

The script should print rank 0's local `state_dict`.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0a0+git179141e
 - OS (e.g., Linux): Ubuntu 18.04.5 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py develop`
 - Python version: 3.8 (64-bit runtime)
 - CUDA/cuDNN version: 11.1.105
 - GPU models and configuration: 4 Tesla V100
 - Any other relevant information:

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by andwgu** [comment]
This method will not be supported since there is not a strong motivation for it at this time.
