### ISSUE TITLE
C++ version 1.9.0 libtorch dynamic load fails -- GCC only

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#60341]
## 🐛 Bug

When building our shared library application with libtorch 1.9.0 (and the nightly build),
we are seeing an error from the GCC build (clang is fine)

```
.so: undefined symbol: _ZTIN5torch2nn6ModuleE

> echo _ZTIN5torch2nn6ModuleE|c++filt
typeinfo for torch::nn::Module
```

In GCC, the first non-inline virtual method is used to determine the the translation unit where the vtable and typeinfo objects are created -- was there some change to _nn::Module_'s virtual functions that might cause this(?).

I'm seeing the problem on the CPU or CUDA 11.1 versions for Linux.

Thanks for looking into this.

**Comment by meganset** [comment]
An example to reproduce the problem:

```
> mkdir /tmp/test
> cd /tmp/test
> wget --quiet https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.9.0%2Bcpu.zip
> unzip -q libtorch-shared-with-deps-1.9.0+cpu.zip
```

build a shared library:

```
> cat m.cpp
#include "torch/torch.h"
void f() {
 torch::nn::Linear m(1,2);
 std::cerr << m << "\n";
}

> g++ -std=c++14 -std=gnu++14 -fPIC -O3 -D_GLIBCXX_USE_CXX11_ABI=0 -isystem /tmp/test/libtorch/include -isystem /tmp/test/libtorch/include/torch/csrc/api/include -c -o m.o m.cpp

> g++ -o m.so m.o -shared -L/tmp/test/libtorch/lib -l torch -Wl,-rpath /tmp/test/libtorch/lib
```

build an executable that opens the library:

```
> cat a.cpp
#include <iostream>
#include <dlfcn.h>

int main() {
 if(!dlopen("./a.so", RTLD_NOW))
  std::cerr << "Cannot load library: " << dlerror() << '\n';
 return 0;
}


> g++ a.cpp -ldl

> ./a.out
Cannot load library: ./m.so: undefined symbol: _ZTVN5torch2nn6ModuleE

> echo _ZTVN5torch2nn6ModuleE | c++filt
vtable for torch::nn::Module
```

If I build the shared library with clang, I don't get the _"undefined symbol"_ error.

**Comment by ezyang** [comment]
There aren't any recent changes to module.h or module.cpp. 

The first noninline virtual method in torch::nn::Module is

```
  virtual std::shared_ptr<Module> clone(
      const optional<Device>& device = nullopt) const;
```

which is defined in torch/csrc/api/src/nn/module.cpp

**Comment by malfet** [comment]
@meganset , what version of gcc are you using as I can not reproduce the failure using gcc-10
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=/usr/bin/g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.0.1 20200328 (Red Hat 10.0.1-0.11) (GCC) 
$ g++ -o m.so -shared -std=c++14 -fPIC -O3 -D_GLIBCXX_USE_CXX11_ABI=0 -Ilibtorch/include -Ilibtorch/include/torch/csrc/api/include m.cpp -Wl,-rpath,libtorch/lib -Llibtorch/lib -ltorch
$ ldd -r m.so 
	linux-vdso.so.1 (0x00007ffdbb7f5000)
	libtorch.so => libtorch/lib/libtorch.so (0x00007fc76c8f7000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fc76c6c7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc76c581000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc76c566000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc76c39c000)
	libtorch_cpu.so => /home/nshulga/test/libtorch-gcc/libtorch/lib/libtorch_cpu.so (0x00007fc759b17000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc76c902000)
	libgomp-a34b3233.so.1 => /home/nshulga/test/libtorch-gcc/libtorch/lib/libgomp-a34b3233.so.1 (0x00007fc7598eb000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc7598c9000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fc7598be000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc7598b7000)
	libc10.so => /home/nshulga/test/libtorch-gcc/libtorch/lib/libc10.so (0x00007fc75980c000)
$ python -c "from ctypes import cdll; print(cdll.LoadLibrary('./m.so'))"
<CDLL './m.so', handle 55994970c500 at 0x7fd1d9ede340>
```

**Comment by meganset** [comment]
```
> g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
```

**Comment by meganset** [comment]
The ldd output:

```
> ldd -r m.so | c++filt
	linux-vdso.so.1 (0x00007ffecff40000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4b4dd0a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4b4daf2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4b4d701000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4b4d363000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4b4e297000)
undefined symbol: vtable for torch::nn::Module	(./m.so)
undefined symbol: c10::UndefinedTensorImpl::_singleton	(./m.so)
undefined symbol: VTT for torch::nn::LinearImpl	(./m.so)
undefined symbol: vtable for torch::nn::LinearImpl	(./m.so)
undefined symbol: torch::nn::LinearImpl::LinearImpl(torch::nn::LinearOptions const&)	(./m.so)
undefined symbol: torch::nn::operator<<(std::basic_ostream<char, std::char_traits<char> >&, torch::nn::Module const&)	(./m.so)
undefined symbol: torch::nn::LinearOptions::LinearOptions(long, long)	(./m.so)
```

```
> python -c "from ctypes import cdll; print(cdll.LoadLibrary('./m.so'))" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/t/miniconda3/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "/home/t/miniconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./m.so: undefined symbol: _ZTVN5torch2nn6ModuleE

> echo _ZTVN5torch2nn6ModuleE | c++filt
vtable for torch::nn::Module
```

**Comment by malfet** [comment]
> The ldd output:
> 
> ```
> > ldd -r m.so | c++filt
> 	linux-vdso.so.1 (0x00007ffecff40000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4b4dd0a000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4b4daf2000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4b4d701000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4b4d363000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f4b4e297000)
> undefined symbol: vtable for torch::nn::Module	(./m.so)
> undefined symbol: c10::UndefinedTensorImpl::_singleton	(./m.so)
> undefined symbol: VTT for torch::nn::LinearImpl	(./m.so)
> undefined symbol: vtable for torch::nn::LinearImpl	(./m.so)
> undefined symbol: torch::nn::LinearImpl::LinearImpl(torch::nn::LinearOptions const&)	(./m.so)
> undefined symbol: torch::nn::operator<<(std::basic_ostream<char, std::char_traits<char> >&, torch::nn::Module const&)	(./m.so)
> undefined symbol: torch::nn::LinearOptions::LinearOptions(long, long)	(./m.so)
> ```

`ldd` output shows, that your m.so does not depend on `libtorch.so`, which explains missing symbols. I I would not link against m.o against libtorch, I would see similar list of missing symbols:
```
$ ldd -r m.so|c++filt
	linux-vdso.so.1 (0x00007ffd46597000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f91fc690000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f91fc54a000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f91fc52f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f91fc365000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f91fc8c8000)
undefined symbol: torch::nn::operator<<(std::basic_ostream<char, std::char_traits<char> >&, torch::nn::Module const&)	(./m.so)
undefined symbol: torch::nn::LinearOptions::LinearOptions(long, long)	(./m.so)
undefined symbol: torch::nn::LinearImpl::LinearImpl(torch::nn::LinearOptions const&)	(./m.so)

```

**Comment by meganset** [comment]
If I perform the same link & compile steps with clang instead:

```
> clang -std=c++14 -std=gnu++14 -fPIC -O3 -D_GLIBCXX_USE_CXX11_ABI=0 -isystem /tmp/test/libtorch/include -isystem /tmp/test/libtorch/include/torch/csrc/api/include -c -o m.o m.cpp

> clang -o m.so m.o -shared -L/tmp/test/libtorch/lib -l torch -Wl,-rpath /tmp/test/libtorch/lib
```
now, libtorch.so is loaded correctly without any undefined symbols:

```
> ldd m.so
	linux-vdso.so.1 (0x00007ffcaf900000)
	libtorch.so => /tmp/test/libtorch/lib/libtorch.so (0x00007f06f5507000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f06f4ec8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f06f4ad7000)
	libtorch_cpu.so => /tmp/test/libtorch/lib/libtorch_cpu.so (0x00007f06e2252000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f06f52e3000)
	libgomp-a34b3233.so.1 => /tmp/test/libtorch/lib/libgomp-a34b3233.so.1 (0x00007f06e2028000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f06e1e09000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f06e1c01000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f06e19fd000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f06e165f000)
	libc10.so => /tmp/test/libtorch/lib/libc10.so (0x00007f06f543e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f06e12d6000)

> python -c "from ctypes import cdll; print(cdll.LoadLibrary('./m.so'))" 
<CDLL './m.so', handle 5629daa76770 at 0x7feed12480d0>
```
With libtorch v1.8.1 and all prior versions, gcc or clang were both fine.
I'm not sure what changed with the new version..since it doesn't look like an explicit code change involving virtual methods for torch::nn::module, maybe it's due to some other build-related change (?)

**Comment by meganset** [comment]
_"ldd output shows, that your m.so does not depend on libtorch.so"_

I tried a newer gcc - version 9.4.0 - and understand some of the confusion.
with the newer version, after compile and link:

```
> g++ -std=c++14 -std=gnu++14 -fPIC -O3 -D_GLIBCXX_USE_CXX11_ABI=0 -isystem /tmp/test/libtorch/include -isystem /tmp/test/libtorch/include/torch/csrc/api/include -c -o m.o m.cpp
> g++ -o m.so m.o -shared -L/tmp/test/libtorch/lib -l torch -Wl,-rpath /tmp/test/libtorch/lib

> ldd m.so
	linux-vdso.so.1 (0x00007fffecfd5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1c19b13000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1c198fb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1c1950a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1c1916c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1c1a123000)
```

There is a dependency on torchlib.so (torch::nn::Linear in the test file _m.cpp_)
```
> cat m.cpp
#include "torch/torch.h"
void f() {
 torch::nn::Linear m(1,2);  // dependency here
 std::cerr << m << "\n";
}
```
and an attempt to load the .so will error out:
```
> python -c "from ctypes import cdll; print(cdll.LoadLibrary('./m.so'))" 
Traceback ..
    self._handle = _dlopen(self._name, mode)
OSError: ./m.so: undefined symbol: _ZN5torch2nnlsERSoRKNS0_6ModuleE
```
**It seems that gcc is not able to follow the path from libtorch.so -> libtorch_cpu.so/libtorch_cuda.so 
that clang manages to find.**

If I include _-l torch_cpu_ explicitly, then gcc picks up the dependency.
```
> g++ -o m.so m.o -shared -L/tmp/test/libtorch/lib -l torch_cpu -Wl,-rpath /tmp/test/libtorch/lib
                                                    ^^^^^^^^^^^
> ldd m.so
	linux-vdso.so.1 (0x00007ffeb83da000)
	libtorch_cpu.so => /tmp/test/libtorch/lib/libtorch_cpu.so (0x00007f72641f5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7263de8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7263bd0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f72637df000)
	libgomp-a34b3233.so.1 => /tmp/test/libtorch/lib/libgomp-a34b3233.so.1 (0x00007f72635b5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7263396000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f726318e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7262f8a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7262bec000)
	libc10.so => /tmp/test/libtorch/lib/libc10.so (0x00007f7276ddc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7276c7d000)
```

**Comment by meganset** [comment]
I still see the same problem in v.1.9.1
that was introduced with v.1.9.0

It seems that gcc is not able to follow the path from libtorch.so -> libtorch_cpu.so / libtorch_cuda.so
that clang manages to find.

I think this was grouped as "when older linkers fail to trace transitive dependencies"
but a fairly recent version of GCC (9.4.0) has this problem as well.

**Comment by meganset** [comment]
This problem persists in v.1.10.0 and v.1.10.1
It's been tagged as "needs reproduction" so I'll try a simple example:

Download Linux CPU-only version of libtorch:

```
> mkdir /tmp/test
> cd /tmp/test
> wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.10.1%2Bcpu.zip
> unzip libtorch-shared-with-deps-1.10.1+cpu.zip 
```

creating a simple function:
```
> cat m.cpp
#include "torch/torch.h"
void f() {torch::nn::Linear m(1,2);}
```

I can compile and create a loadable shared library with clang:
```
> clang -std=c++14 -std=gnu++14 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -I libtorch/include -I libtorch/include/torch/csrc/api/include -c -o m.o m.cpp
> clang -o m.so m.o -shared -Llibtorch/lib -l torch -Wl,-rpath libtorch/lib
```

clang is given the **_-l torch_** library and from there, it is able to include **_libtorch_cpu.so_** (and **_libtorch_cuda.so_** on CUDA builds)

The test **_m.so_** is loadable, and ldd output shows **_libtorch_cpu.so_** in the output:

```
> python -c "from ctypes import cdll; print(cdll.LoadLibrary('./m.so'))"
<CDLL './m.so', handle 5651913b0770 at 0x7f53c5bd40d0>

> ldd m.so
	linux-vdso.so.1 (0x00007ffce1154000)
	libtorch.so => libtorch/lib/libtorch.so (0x00007f6a01e4e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6a018a7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6a014b6000)
	libtorch_cpu.so => /tmp/test/libtorch/lib/libtorch_cpu.so (0x00007f69eba65000)
	libgomp-a34b3233.so.1 => /tmp/test/libtorch/lib/libgomp-a34b3233.so.1 (0x00007f69eb83b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6a01cc4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f69eb61c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f69eb414000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f69eb210000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f69eae72000)
	libc10.so => /tmp/test/libtorch/lib/libc10.so (0x00007f6a01dab000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f69eaa65000)
```

Performing the same steps with g++ version 9.4.0

```
> g++ -std=c++14 -std=gnu++14 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -I libtorch/include -I libtorch/include/torch/csrc/api/include -c -o m.o m.cpp
> g++ -o m.so m.o -shared -Llibtorch/lib -l torch -Wl,-rpath libtorch/lib

> python -c "from ctypes import cdll; print(cdll.LoadLibrary('./m.so'))"
OSError: ./m.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE

> echo _ZN3c1019UndefinedTensorImpl10_singletonE |c++filt
c10::UndefinedTensorImpl::_singleton
```

g++ is no longer able to make the connection from **_-l torch_** to pick up **_libtorch_cpu.so_**:

```
> ldd m.so
	linux-vdso.so.1 (0x00007ffdbb5ce000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbb1dc7d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbb1da65000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbb1d674000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbb1d2d6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbb1e2a8000)
```

The workaround is to explicitly specify the **_-l torch_cpu_** ( and **_torch_cuda_**) libraries to the linker,
but the _libtorch_ releases through 1.8.1 were able to pick up this relationship implicitly for both clang and g++

Somehow the transitive dependencies gcc was previously able to pick up have changed(?)
