### ISSUE TITLE
test_dist_optim is flaky again

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#60406]
https://app.circleci.com/pipelines/github/pytorch/pytorch/339608/workflows/8e7861c5-7ad2-4367-b30d-9150cd3d8124/jobs/14276942

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 398, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 590, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 633, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 2 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
    fn()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
    return_value = old_test_method(self, *arg, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_optimizer_test.py", line 209, in test_dist_optim
    self._test_dist_optim_base(optim.RMSprop, lr=0.05)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_optimizer_test.py", line 174, in _test_dist_optim_base
    self.assertEqual(old_w2, remote_param2.to_here())
RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error

Process 3 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
    fn()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
    return_value = old_test_method(self, *arg, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_optimizer_test.py", line 208, in test_dist_optim
    self._test_dist_optim_base(optim.Adadelta, rho=0.95)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_optimizer_test.py", line 189, in _test_dist_optim_base
    dist_optim.step(context_id)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/optim/optimizer.py", line 274, in step
    _wait_for_all(rpc_futs)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/optim/optimizer.py", line 133, in _wait_for_all
    raise exception
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/optim/optimizer.py", line 128, in _wait_for_all
    results.append(fut.wait())
RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error
```

cc @mruberry @VitalyFedyunin @walterddr @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by pritamdamania87** [comment]
This test has been permanently retired: https://github.com/pytorch/pytorch/pull/60407.
