### ISSUE TITLE
ROCm miopenStatusInternalError /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file

### ISSUE THREAD

**Issue by Felix-Petersen** [pytorch/pytorch#60477]
## 🐛 Bug

On ROCm 4.2, with PyTorch 1.9.0 installed via 

```shell
pip3 install torch -f https://download.pytorch.org/whl/rocm4.2/torch_stable.html
```

Running https://github.com/pytorch/examples/tree/master/mnist crashes oftentimes with the error below. 
I use an MI50 GPU.
The error sometimes occurs at the very beginning of training, sometimes after the first epoch, sometimes within an epoch and sometimes not at all.
As a rule of thumb, the larger the batch size, the more likely that the error occurs / occurs at the beginning.
Usually, it does not allow any training at the first run and when rerunning it usually comes further and sometimes even succeeds.

```
MIOpen(HIP): Warning [FindWinogradSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindDataDirectSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindDataImplicitGemmSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindFftSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindWinogradSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindDataDirectSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindDataImplicitGemmSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindFftSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindWinogradSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindDataDirectSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindDataImplicitGemmSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindFftSolutions] /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
MIOpen Error: /MIOpen/src/sqlite_db.cpp:109: open memvfs: unable to open database file
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    main()
  File "main.py", line 128, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "main.py", line 44, in train
    loss.backward()
  File "/home/ssml/petersenf/testing/.env1/lib64/python3.6/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ssml/petersenf/testing/.env1/lib64/python3.6/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: miopenStatusInternalError
```

## To Reproduce

On a setup as described above:

1. `wget https://raw.githubusercontent.com/pytorch/examples/master/mnist/main.py`
1. python main.py

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0+rocm4.2
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 4.2.21155-37cb3a34

OS: Scientific Linux release 7.9 (Nitrogen) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.3.4

Python version: 3.6 (64-bit runtime)
Python platform: Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-redhat-7.9-Nitrogen
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Vega 20
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 3.27.5
MIOpen runtime version: 2.11.0

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0+rocm4.2
[pip3] torchvision==0.10.0
[conda] Could not collect
```

**Comment by Felix-Petersen** [comment]
Some updates:

My impression is, that it might have to do with latency or data access. 
The Python environment installation is on a data server connected via Infiniband. 
The error is thrown from "/infiniband-shared-storage/.env1/lib64/python3.6/site-packages/torch/lib/libMIOpen-12425ccb.so.1".
 
On this device, I usually have to start my code 1-2 times before it actually works without crashing, but then there seems to be no problem. I have also installed it on a slow shared storage and there the problem is much more severe. 

My interpretation of this is that there could be some connection instability for the specific command or that it requires getting the data within a short time frame.

We also have local installations of ROCm / MIOpen on each server ("/opt/rocm/lib/libMIOpen.so.1").
_Is it possible to use the local shared object file instead of the one delivered with PyTorch? If yes, how can I do that?_ 
(I suppose deleting and creating a symlink does not work)

**Comment by abedicodes** [comment]
I am also getting this error "RuntimeError: miopenStatusInternalError". I installed the stable and nightly versions of the torch using the following commands:
pip3 install torch -f https://download.pytorch.org/whl/rocm4.2/torch_stable.html
pip3 install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/rocm4.2/torch_nightly.html

**Comment by jithunnair-amd** [comment]
@Felix-Petersen This is an odd use-case as you have determined. Could you try `LD_PRELOAD=<local shared object file path>` to see if that helps? You probably want to use the same name as `MIOpen-12425ccb.so.1` in case the linker is looking for that specific shared object file name.

**Comment by jithunnair-amd** [comment]
@abedicodes Does your usage environment match @Felix-Petersen's? Specifically, is your PyTorch installation on a slow access path as well?

**Comment by abedicodes** [comment]
Can you please explain what you mean by "shared object file" and "slow access path"?
I have installed torch on a cluster, used Anaconda for Python, and slurm for running python files.

Thanks

**Comment by Felix-Petersen** [comment]
@abedicodes 
shared object file: that is the .so files, e.g., a compiled PyTorch library.
slow access path: a directory on a network server. This is, e.g., almost certainly your home directory on your cluster.

@jithunnair-amd 
I am sorry, I cannot test the "LD_PRELOAD" at the moment because I cannot use the cluster right now.
However, I think this could work.
What did (kind of) work for me (with a ~95% Success Rate) was doing `./vmtouch -dl .env1/`. This keeps them in memory preventing the issue.
Another (kind of) solution is to just `cat` all respective files into `/dev/null`. 

In my opinion, this is an instability of the ROCm implementation. A wrapper that checks/retries accessing the database or a longer timeout would probably solve this issue.
To reproduce it, if you have some NAS etc., I believe you could install it on the NAS.

**Comment by chwan-rice** [comment]
Is there any update? I have a similar sqlite issue when the last batch is fed to the network. If `drop_last` of data loader is enabled, the code works well except the issue mentioned by the author. My ROCm version is 4.1.

**Comment by Griffintaur** [comment]
Any update on the issue?

**Comment by cjekel** [comment]
I ran into this with mi250x.

Adding this in my script before running pytorch seemed to help.
```bash
export MIOPEN_USER_DB_PATH="/tmp/my-miopen-cache"
export MIOPEN_CUSTOM_CACHE_DIR=${MIOPEN_USER_DB_PATH}
rm -rf ${MIOPEN_USER_DB_PATH}
mkdir -p ${MIOPEN_USER_DB_PATH}
```

**Comment by hongxiayang** [comment]
> I ran into this with mi250x.
> 
> Adding this in my script before running pytorch seemed to help.
> 
> ```shell
> export MIOPEN_USER_DB_PATH="/tmp/my-miopen-cache"
> export MIOPEN_CUSTOM_CACHE_DIR=${MIOPEN_USER_DB_PATH}
> rm -rf ${MIOPEN_USER_DB_PATH}
> mkdir -p ${MIOPEN_USER_DB_PATH}
> ```
> 
> I should add that /tmp is using tmpfs

Can you provide details how to reproduce in your setup in mi250x? We would like to reproduce this. Is this in a cluster?

**Comment by bergentruckung** [comment]
I'm seeing a similar issue when using MI210 as well. 

```
MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/sqlite_db.cpp:220: Internal error while accessing SQLite database: unable to open database file
```

I can workaround for now using the env variables as mentioned above, but this issue has been open since 2021. Any chance when we can have a patch for this? I'd like to use a similar environment for both Nvidia and AMD cards.

**Comment by KISSEsWHISPERsFEEtBACKHUGs** [comment]
```
CLIPVisionEncode
miopenStatusInternalError
MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/src/MLOpen/src/gemm_v2.cpp:920: rocBlas error encountered
!!! Exception during processing !!! miopenStatusInternalError
Traceback (most recent call last):
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/nodes.py", line 985, in encode
    output = clip_vision.encode_image(image, crop=crop_image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/clip_vision.py", line 62, in encode_image
    out = self.model(pixel_values=pixel_values, intermediate_output=-2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/clip_model.py", line 216, in forward
    x = self.vision_model(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/clip_model.py", line 195, in forward
    x = self.embeddings(pixel_values)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/clip_model.py", line 168, in forward
    embeds = self.patch_embedding(pixel_values).flatten(2).transpose(1, 2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/ops.py", line 96, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/.8A/terminal/ComfyAI/ComfyUI/comfy/ops.py", line 92, in forward_comfy_cast_weights
    return self._conv_forward(input, weight, bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyt2c1k/pyenv/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: miopenStatusInternalError

fatal: No names found, cannot describe anything.
```
### Reproductions,
(1) Download & run this workflow for Comfy on your AMD APU HW system. https://pastebin.com/qfKUrJc9, with downloading Shutt1eMix and Shutt1e3D Official SFT ckpt model images (CivitAI) onto `$COMFY_ROOT/models/unet`, and Comfy’s ClipVisionG (HF) onto `$COMFY_ROOT/models/clip_vision`,
(2) Look at ClipVision portrait wallpaper encode phase if MIOpen bugs are,
(3) Workflow previews and demonstraitions of errors in pink,
![spectac1e 110301 122324](https://github.com/user-attachments/assets/51755c3c-5e5e-46fd-9c83-e2ce890c8c3b)
### HW
AMD Zen2 R4750G APU (HSA 9.0.0) × 14.9GiB UniVRAM’s with OpenCL-ROCm 6.3.0
