### ISSUE TITLE
`test_transpose_inplace_view_xla` & `test_t_inplace_view_xla` are flaky

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#60501]
## 🐛 Bug

`test_transpose_inplace_view_xla` & `test_t_inplace_view_xla` are flaky & failed in a CI run of the CI check [`pytorch_xla_linux_bionic_py3_6_clang9_test`](https://app.circleci.com/pipelines/github/pytorch/pytorch/340270/workflows/02ccad71-d52e-42ad-87b2-a22104872f71/jobs/14312357)

## To Reproduce
This failure might not reproduce in a subsequent CI run of [`pytorch_xla_linux_bionic_py3_6_clang9_test`](https://app.circleci.com/pipelines/github/pytorch/pytorch/340270/workflows/02ccad71-d52e-42ad-87b2-a22104872f71/jobs/14312357), but here are the errors -
```
======================================================================
FAIL [0.023s]: test_t_inplace_view_xla (__main__.TestViewOpsXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 397, in instantiated_test
    result = test_fn(self, *args)
  File "/var/lib/jenkins/workspace/xla/test/../../test/test_view_ops.py", line 488, in test_t_inplace_view
    self.assertEqual(t[1, 0], v[0, 1])
  File "/var/lib/jenkins/workspace/xla/test/pytorch_test_base.py", line 605, in assertEqual
    return DeviceTypeTestBase.assertEqual(self, x, y, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1422, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=0.001 and atol=0.001, found 1 element(s) (out of 1) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.0 (1.0 vs. 0.0), which occurred at index 0.

======================================================================
FAIL [0.006s]: test_transpose_inplace_view_xla (__main__.TestViewOpsXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 397, in instantiated_test
    result = test_fn(self, *args)
  File "/var/lib/jenkins/workspace/xla/test/../../test/test_view_ops.py", line 458, in test_transpose_inplace_view
    self.assertEqual(t[1, 0], v[0, 1])
  File "/var/lib/jenkins/workspace/xla/test/pytorch_test_base.py", line 605, in assertEqual
    return DeviceTypeTestBase.assertEqual(self, x, y, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1422, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=0.001 and atol=0.001, found 1 element(s) (out of 1) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.0 (1.0 vs. 0.0), which occurred at index 0
```

## Expected behavior

The tests shouldn't fail

## Environment

[CI](https://app.circleci.com/pipelines/github/pytorch/pytorch/340270/workflows/02ccad71-d52e-42ad-87b2-a22104872f71/jobs/14312357)

## Additional context

The changes in the PR are not XLA-related.

cc @ailzhang @gmagogsfm

**Comment by imaginary-person** [comment]
Another occurrence on the master branch - https://circleci.com/gh/pytorch/pytorch/14317415

**Comment by ailzhang** [comment]
@imaginary-person This test was failing consistently on master yesterday so I disabled them for XLA first. @bdhirsh and I will look into the root cause later today. Thanks for reporting!

**Comment by ailzhang** [comment]
Reference: https://github.com/pytorch/xla/pull/3007
https://ezyang.github.io/pytorch-ci-hud/build2/pytorch-master

**Comment by imaginary-person** [comment]
Oops, sorry. It wasn't flaky, then.
