### ISSUE TITLE
Exporting normalization modules introduces numerical errors

### ISSUE THREAD

**Issue by calvinmccarter-at-lightmatter** [pytorch/pytorch#60582]
## 🐛 Bug

When we `torch.onnx.export` various normalization modules to ONNX, the resulting models have slightly different results on other ONNX backends. Here we illustrate the issue with InstanceNorm and onnxruntime, but I've also found the issue with BatchNorm, and when converting the ONNX back to PyTorch via [onnx2pytorch](https://github.com/ToriML/onnx2pytorch). Note that in the following example, I've set `affine=False` so it's not due to training-mode updates to the scale/bias parameters.

## To Reproduce

The following code snippet reproduces the issue for `nn.InstanceNorm2d` on ONNXRunTime:
```import io
import numpy as np
import onnxruntime as ort
import torch

from torch import nn

num_features = 32
batch = 4
img_dims = 1200
dims = (2, 3)
model = nn.InstanceNorm2d(num_features=num_features, eps=0., affine=False)

torch.manual_seed(42)
x = 1e-3 * torch.randn(batch, num_features, img_dims, img_dims)
y = model(x)

bitstream = io.BytesIO()
torch.onnx.export(
    model=model,
    args=(x,),
    f=bitstream,
    input_names=["x"],
    opset_version=11,
)
bitstream_data = bitstream.getvalue()
ort_session = ort.InferenceSession(bitstream_data)
ort_inputs = {"x": x.numpy()}
ort_outputs = ort_session.run(None, ort_inputs)
ort_y = ort_outputs[0]

np.testing.assert_allclose(ort_y, y.detach().numpy(), rtol=1e-5, atol=1e-5)
```

## Expected behavior

I would expect to pass the assert statement, but instead get:
```Traceback (most recent call last):
  File "instancenorm.py", line 32, in <module>
    np.testing.assert_allclose(ort_y, y.detach().numpy(), rtol=1e-5, atol=1e-5)
  File "/home/calvin/miniconda3/envs/onnx2pytorch/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/calvin/miniconda3/envs/onnx2pytorch/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 842, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-05

Mismatched elements: 60014622 / 184320000 (32.6%)
Max absolute difference: 0.00012732
Max relative difference: 3.3601735
 x: array([[[[ 1.927266e+00,  1.487702e+00,  9.012247e-01, ...,
           1.756508e+00,  2.119050e-01,  1.486437e+00],
         [ 5.590721e-01,  3.497388e-01,  8.488822e-01, ...,...
 y: array([[[[ 1.927225e+00,  1.487670e+00,  9.012055e-01, ...,
           1.756471e+00,  2.119005e-01,  1.486405e+00],
         [ 5.590602e-01,  3.497313e-01,  8.488641e-01, ...,...
```

These assertion-failures are pretty easy to produce with other ways of randomly-generated input data. For example, substituting in:
```
x = 1e-3 * torch.rand(batch, num_features, img_dims, img_dims)
```
produces:
```AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-05

Mismatched elements: 7082919 / 184320000 (3.84%)
Max absolute difference: 3.4451485e-05
Max relative difference: 43.929726
 x: array([[[[ 1.325652,  1.43907 , -0.404667, ..., -0.673192, -0.129214,
          -0.420119],
         [-0.8741  , -0.549184, -0.625497, ...,  0.967343, -0.684575,...
 y: array([[[[ 1.325638,  1.439054, -0.40466 , ..., -0.673182, -0.12921 ,
          -0.420112],
         [-0.874087, -0.549175, -0.625487, ...,  0.967333, -0.684565,...
```

## Environment

```Collecting environment information...
PyTorch version: 1.4.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-4.15.0-128-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: A100-PCIE-40GB
GPU 1: A100-PCIE-40GB
GPU 2: A100-PCIE-40GB
GPU 3: A100-PCIE-40GB
GPU 4: A100-PCIE-40GB
GPU 5: A100-PCIE-40GB
GPU 6: A100-PCIE-40GB
GPU 7: A100-PCIE-40GB

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] onnx2pytorch==0.3.0
[pip3] torch==1.4.0
[conda] numpy                     1.20.2                   pypi_0    pypi
[conda] onnx2pytorch              0.3.0                     dev_0    <develop>
[conda] torch                     1.4.0                    pypi_0    pypi
```

## Additional context

cc @garymm @BowenBao @neginraoof

**Comment by garymm** [comment]
If the implementation of a particular operator is wrong in either PyTorch or ONNX Runtime, please file a bug about that. However numerical differences are expected between different implementations.
This is documented here (will be updated in master branch soon):
https://github.com/pytorch/pytorch/blob/onnx_ms_1/docs/source/onnx.rst#differences-in-operator-implementations

I wouldn't be surprised if there were some differences within PyTorch between e.g. CUDA, RoCM, or different CPUs.

**Comment by calvinmccarter-at-lightmatter** [comment]
@garymm - thanks for the explanation and link! Is there a rule of thumb for how large the differences may be (either relative or absolute) between implementations? In a particular network I'm looking at, these cascading small differences accumulate into actually different predictions (and thus accuracy). For such sensitive network architectures, even if it's not fair to call a particular backend "wrong", one still has to worry about portability between backends. (IE, should I be fine-tuning my model for each backend?)

**Comment by garymm** [comment]
There may be some formal or informal expectations between different implentations of a given ONNX operator (I'm not sure). For that you could ask in the ONNX GitHub or Slack. But between ONNX and PyTorch I don't think there's any standard other than basic correctness.
