### ISSUE TITLE
[jit]][script] handling of 'void' returns

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#6064]
Methods returning no values generate weird error messages:

For instance:

```
    def test_script_module_for(self):
        class M(torch.jit.ScriptModule):
            def __init__(self):
                super(M, self).__init__(False)
               
            @torch.jit.script_method
            def forward(self):
                return
```

produces 
```
Traceback (most recent call last):
  File "test/test_jit.py", line 2059, in test_script_module_for
    class M(torch.jit.ScriptModule):
  File "test/test_jit.py", line 2064, in M
    @torch.jit.script_method
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 539, in script_method
    return ScriptMethodStub(createResolutionCallback(), get_jit_ast(fn))
  File "/data/users/zdevito/pytorch/torch/jit/frontend.py", line 127, in get_jit_ast
    return build_def(SourceRangeFactory(source), py_ast.body[0])
  File "/data/users/zdevito/pytorch/torch/jit/frontend.py", line 146, in build_def
    [build_stmt(ctx, stmt) for stmt in body])
  File "/data/users/zdevito/pytorch/torch/jit/frontend.py", line 135, in __call__
    return method(ctx, node)
  File "/data/users/zdevito/pytorch/torch/jit/frontend.py", line 207, in build_Return
    return Return(r, [build_expr(ctx, val) for val in values])
  File "/data/users/zdevito/pytorch/torch/jit/frontend.py", line 134, in __call__
    raise UnsupportedNodeError(ctx, node)
  File "/data/users/zdevito/pytorch/torch/jit/frontend.py", line 110, in __init__
    source_range = ctx.make_range(offending_node.lineno,
AttributeError: 'NoneType' object has no attribute 'lineno'
```

What is expected?

* omitting a return statement should be valid and just return 0 values (someone might just be print debugging at this point and hasn't written the return yet)
* `return` with no value should work.

**Comment by apaszke** [comment]
I'm on this
