### ISSUE TITLE
DISABLED test_collective_hang (__main__.ProcessGroupGlooWrapperTest)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#60652]
```
Jun 24 00:59:14 ======================================================================
Jun 24 00:59:14 ERROR [0.477s]: test_collective_hang (__main__.ProcessGroupGlooWrapperTest)
Jun 24 00:59:14 ----------------------------------------------------------------------
Jun 24 00:59:14 Traceback (most recent call last):
Jun 24 00:59:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 398, in wrapper
Jun 24 00:59:14     self._join_processes(fn)
Jun 24 00:59:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 590, in _join_processes
Jun 24 00:59:14     self._check_return_codes(elapsed_time)
Jun 24 00:59:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 633, in _check_return_codes
Jun 24 00:59:14     raise RuntimeError(error)
Jun 24 00:59:14 RuntimeError: Process 0 exited with error code 10 and exception:
Jun 24 00:59:14 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [172.17.0.2]:21400
Jun 24 00:59:14 
Jun 24 00:59:14 During handling of the above exception, another exception occurred:
Jun 24 00:59:14 
Jun 24 00:59:14 Traceback (most recent call last):
Jun 24 00:59:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
Jun 24 00:59:14     getattr(self, test_name)()
Jun 24 00:59:14   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
Jun 24 00:59:14     fn()
Jun 24 00:59:14   File "distributed/test_pg_wrapper.py", line 270, in test_collective_hang
Jun 24 00:59:14     self._test_collective_hang(pg)
Jun 24 00:59:14   File "distributed/test_pg_wrapper.py", line 52, in _test_collective_hang
Jun 24 00:59:14     wrapper_pg.allreduce([tensor])
Jun 24 00:59:14   File "/opt/conda/lib/python3.6/unittest/case.py", line 217, in __exit__
Jun 24 00:59:14     expected_regex.pattern, str(exc_value)))
Jun 24 00:59:14   File "/opt/conda/lib/python3.6/unittest/case.py", line 135, in _raiseFailure
Jun 24 00:59:14     raise self.test_case.failureException(msg)
Jun 24 00:59:14 AssertionError: "Ranks 1 failed to pass monitoredBarrier" does not match "[/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [172.17.0.2]:21400"
```

https://www.internalfb.com/intern/opensource/ci/job/log/225221175921058/

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
should be fixed by https://github.com/pytorch/pytorch/pull/60662
