### ISSUE TITLE
Windows binary wheels are broken on master

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#60665]
## 🐛 Bug

```
  Traceback (most recent call last):
    File "C:\w\b\windows\conda\envs\py37\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 280, in <module>
      main()
    File "C:\w\b\windows\conda\envs\py37\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\w\b\windows\conda\envs\py37\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\circleci\AppData\Local\Temp\pip-build-env-3s1oyvc5\overlay\Lib\site-packages\setuptools\build_meta.py", line 155, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\circleci\AppData\Local\Temp\pip-build-env-3s1oyvc5\overlay\Lib\site-packages\setuptools\build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "C:\Users\circleci\AppData\Local\Temp\pip-build-env-3s1oyvc5\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 219, in <module>
      from tools.build_pytorch_libs import build_caffe2
  ModuleNotFoundError: No module named 'tools'
```

From: https://app.circleci.com/pipelines/github/pytorch/pytorch/341279/workflows/9604d7b7-db22-4b73-95b5-b36676488858/jobs/14360766

This has been failing since https://github.com/pytorch/pytorch/pull/60408

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @malfet @seemethere @walterddr @pytorch/pytorch-dev-infra @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by seemethere** [comment]
After some investigation I've found that this boils down to these lines:

https://github.com/pytorch/builder/blob/4b9d97bf6f3548508705142dce317ad8adc8a612/windows/internal/setup.bat#L92-L95

Perhaps we can change these lines to build using `python setup.py bdist_wheel` instead of using `pip wheel`

**Comment by samestep** [comment]
Just to clarify, is it indeed caused by the addition of `pyproject.toml`?

**Comment by seemethere** [comment]
Failures started with the inclusion of `pyproject.toml`

**Comment by samestep** [comment]
Oh I had forgotten that these binaries were built on every `master` commit

**Comment by seemethere** [comment]
This should be resolved by https://github.com/pytorch/builder/pull/792, keeping open until we can verify

**Comment by seemethere** [comment]
Fixed as of https://app.circleci.com/jobs/github/pytorch/pytorch/14375396?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Closing this issue now

**Comment by xkszltl** [comment]
We're having similar issue on Linux when pip install from local repo.
To me it sounds like a missing sys.path.
Is there anything changed recently, on pytorch or pip side, that can affect the behavior?

```
  Successfully installed setuptools-57.0.0 wheel-0.36.2
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Removed build tracker: '/tmp/pip-req-tracker-xqy8njkn'
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp400sv6fc
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 155, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 219, in <module>
      from tools.build_pytorch_libs import build_caffe2
  ModuleNotFoundError: No module named 'tools'
  Getting requirements to build wheel: finished with status 'error'
WARNING: Discarding file:///tmp/scratch/pytorch. Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp400sv6fc Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp400sv6fc Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
    req, requested_extras=()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 444, in make_requirement_from_install_req
    raise self._build_failures[ireq.link]
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 205, in _make_candidate_from_link
    version=version,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 312, in __init__
    version=version,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
    self._ireq, parallel_builds=True
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 571, in _prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/distributions/sdist.py", line 34, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/distributions/sdist.py", line 88, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/wrappers.py", line 169, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/wrappers.py", line 268, in _call_hook
    extra_environ=extra_environ
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 278, in runner
    spinner=spinner,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp400sv6fc Check the logs for full command output.
Removed file:///tmp/scratch/pytorch from build tracker '/tmp/pip-req-tracker-xqy8njkn'
Removed build tracker: '/tmp/pip-req-tracker-xqy8njkn'
```
