### ISSUE TITLE
Potential memory leaks reported by static analysis tool

### ISSUE THREAD

**Issue by endjkv** [pytorch/pytorch#60732]
Hi, there are several bug reports about memory leaks from static analysis.

Could you please help confirm them?

**1**

In file torch/csrc/jit/tensorexpr/kernel.cpp, function `TensorExprKernel::compile()`.

There is a memory leak on `block` when an exception is thrown. (those `std::runtime_error`s)

**2**

In file torch/csrc/jit/tensorexpr/ir_simplifier.cpp, function `mulMultilane`.

In the constructor of `Broadcast` (line 144), a `malformed_input` of "dtype lanes dont match" may be thrown, causing a memory leak on `new Mul(...)`.

Same as function `combineMultilane`, which may cause a memory leak on `new Op(...)`.

**3**

These are memory leaks when `torchCheckFail` is called.

In file torch/csrc/jit/runtime/profiling_record.cpp, function `ProfilingRecord::instrumentGraph`.

There might be a check fail in `new_g->appendNode(pop)`, causing a memory leak on `pop`.

In file torch/csrc/jit/passes/fixup_trace_scope_blocks.cpp, function `convertTracedForksToRealForks`.

There might be a check fail in `g->insertNode(...)`, causing a memory leak on `g->create(...)`.

**Thanks**

**Comment by showgood163** [comment]
I meet a similar problem.

Run the code from "https://github.com/NVlabs/stylegan2-ada-pytorch" and error pops at [this line](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/metrics/metric_utils.py#L218), note that this `detector` is loaded with `torch.jit.load()`.

When I manually run `detector(images.to(opts.device), **detector_kwargs)`, the output is normal.
When I manually run `features = detector(images.to(opts.device), **detector_kwargs)`, the output is:
```
Traceback (most recent call last):
  File "/home/xxx/.vscode/extensions/ms-python.python-2021.6.944021595/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 419, in evaluate_expression
    compiled = compile(_expression_to_evaluate(expression), '<string>', 'eval')
  File "<string>", line 1
    features = detector(images.to(opts.device), **detector_kwargs)
             ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: MALFORMED INPUT: lanes dont match
```

After that, the console reports
```
Evaluating metrics...
/usr/lib/python3.9/site-packages/torch/nn/modules/module.py:1051: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1153.)
  return forward_call(*input, **kwargs)
/usr/bin/env /usr/bin/python  36917 --   20.79s user 3.30s system 60% cpu 39.608 total
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 34 leaked semaphore objects to clean up at shutdown
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
