### ISSUE TITLE
#57081 creates a `grad_fn` for newly created tensors and fails in the backward

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#60733]
## 🐛 Bug

https://github.com/pytorch/pytorch/pull/57081 added the support in DDP for use cases where not all outputs are used in the loss calculation. 
In use cases where tensors are created in the `forward` method and where `find_unused_parameters=True` #57081 could cause errors during the `backward()` operation, as Autograd tries to delete already freed intermediates.
We encountered this issue in TransformerXL and were able to narrow it down to this PR (thanks @xwang233 for bisecting and isolating this PR) and come up with a minimal code snippet.

## To Reproduce

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.parallel import DistributedDataParallel
import types
import argparse


class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10, 10, bias=False)
        self.fc2 = nn.Linear(10, 10, bias=False)

    def __init_opt(self):
        param = next(self.parameters())
        opt = torch.randn(1, 10, device=param.device)
        return opt

    def forward(self, x, opt):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        if opt is None:
            opt = self.__init_opt()
        return x, opt


def main():
    parser = argparse.ArgumentParser(description='fdsa')
    parser.add_argument("--local_rank", default=0, type=int)

    args = parser.parse_args()
    args.gpu = args.local_rank
    torch.cuda.set_device(args.gpu)
    torch.distributed.init_process_group(backend='nccl',
                                         init_method='env://')
    args.world_size = torch.distributed.get_world_size()

    model = MyModel().to(args.gpu)
    model = DistributedDataParallel(
        model,
        device_ids=[args.gpu],
        output_device=args.local_rank,
        broadcast_buffers=False,
        find_unused_parameters=False
    )

    opt = [None]
    for i in range(2):
        model.zero_grad()
        x = torch.randn(1, 10, device=args.gpu)
        out, opt[0] = model(x, opt=opt[0])
        print('iter {}, out.sum() {}, device {}, opt.grad_fn {}, opt.device {}'.format(
            i, out.sum(), out.device, opt[0].grad_fn, opt[0].device))
        out.mean().backward()

if __name__ == "__main__":
    main()
```
Execute the code via:
```python
python -m torch.distributed.launch --nproc_per_node=2 lala.py
```
Building PyTorch from  source with the parent PR:
```
HEAD detached at abb215e229

abb215e229 (HEAD) Fix dtype inference in sparse_csr_tensor_ctor (#58631)
9ac0bd23a2 Fix bug in test_fx_experimental codegen (#58587)
bf00d26deb Enables builds with Compute Library backend for oneDNN (#55913)
145a6f7985 DOC Adds code comment to clarify nn.Linear.reset_parameters (#58487)
```
works fine and returns (I've removed the DDP logging output for brevity):
```python
# find_unused_parameter=False
iter 0, out.sum() 0.4703005850315094, device cuda:0, opt.grad_fn None, opt.device cuda:0
iter 0, out.sum() 0.7102077603340149, device cuda:1, opt.grad_fn None, opt.device cuda:1
iter 1, out.sum() -0.24561020731925964, device cuda:0, opt.grad_fn None, opt.device cuda:0
iter 1, out.sum() -0.4937245845794678, device cuda:1, opt.grad_fn None, opt.device cuda:1
{"name": "torchelastic.worker.status.SUCCEEDED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 0, "group_rank": 0, "worker_id": "40222", "role": "default", "hostname": "63d37ea1f705", "state": "SUCCEEDED", "total_run_time": 5, "rdzv_backend": "static", "raw_error": null, "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [0], \"role_rank\": [0], \"role_world_size\": [2]}", "agent_restarts": 0}}

# find_unused_parameters=True
iter 0, out.sum() 0.4020804166793823, device cuda:0, opt.grad_fn None, opt.device cuda:0
[W reducer.cpp:1156] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
iter 0, out.sum() 0.07896003127098083, device cuda:1, opt.grad_fn None, opt.device cuda:1
iter 1, out.sum() 0.19146957993507385, device cuda:0, opt.grad_fn None, opt.device cuda:0
iter 1, out.sum() -0.32873281836509705, device cuda:1, opt.grad_fn None, opt.device cuda:1
{"name": "torchelastic.worker.status.SUCCEEDED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 0, "group_rank": 0, "worker_id": "40382", "role": "default", "hostname": "63d37ea1f705", "state": "SUCCEEDED", "total_run_time": 5, "rdzv_backend": "static", "raw_error": null, "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [0], \"role_rank\": [0], \"role_world_size\": [2]}", "agent_restarts": 0}}
```
As can be seen, the `opt[0].grad_fn` is set to `None` and the script finishes successfully.

Rebuilding PyTorch with #57081:
```
HEAD detached at faa7d3793d

faa7d3793d (HEAD) [DDP] Support not all outputs used in loss calculation (#57081)
abb215e229 Fix dtype inference in sparse_csr_tensor_ctor (#58631)
9ac0bd23a2 Fix bug in test_fx_experimental codegen (#58587)
bf00d26deb Enables builds with Compute Library backend for oneDNN (#55913)
145a6f7985 DOC Adds code comment to clarify nn.Linear.reset_parameters (#58487)
```
gives:
```python
# find_unused_parameters=False
iter 0, out.sum() -0.15716691315174103, device cuda:0, opt.grad_fn None, opt.device cuda:0
iter 0, out.sum() 0.37608635425567627, device cuda:1, opt.grad_fn None, opt.device cuda:1
iter 1, out.sum() -0.5610430240631104, device cuda:0, opt.grad_fn None, opt.device cuda:0
iter 1, out.sum() -0.6621178388595581, device cuda:1, opt.grad_fn None, opt.device cuda:1
{"name": "torchelastic.worker.status.SUCCEEDED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 0, "group_rank": 0, "worker_id": "41202", "role": "default", "hostname": "63d37ea1f705", "state": "SUCCEEDED", "total_run_time": 5, "rdzv_backend": "static", "raw_error": null, "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [0], \"role_rank\": [0], \"role_world_size\": [2]}", "agent_restarts": 0}}

# find_unused_parameters=True
iter 0, out.sum() 0.460982084274292, device cuda:1, opt.grad_fn <torch.autograd.function._DDPSinkBackward object at 0x7fc8e0f922e0>, opt.device cuda:1
iter 0, out.sum() 2.505180835723877, device cuda:0, opt.grad_fn <torch.autograd.function._DDPSinkBackward object at 0x7f79a070d2e0>, opt.device cuda:0
[W reducer.cpp:1188] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1188] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
iter 1, out.sum() 0.9564222693443298, device cuda:1, opt.grad_fn <torch.autograd.function._DDPSinkBackward object at 0x7fc8e0f923c0>, opt.device cuda:1
iter 1, out.sum() 0.4020279347896576, device cuda:0, opt.grad_fn <torch.autograd.function._DDPSinkBackward object at 0x7f79a070d3c0>, opt.device cuda:0
Traceback (most recent call last):
  File "lala.py", line 58, in <module>
Traceback (most recent call last):
  File "lala.py", line 58, in <module>
    main()
  File "lala.py", line 55, in main
    out.mean().backward()
  File "/workspace/src/libs/pytorch/torch/_tensor.py", line 255, in backward
    main()
  File "lala.py", line 55, in main
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/workspace/src/libs/pytorch/torch/autograd/__init__.py", line 147, in backward
    out.mean().backward()
  File "/workspace/src/libs/pytorch/torch/_tensor.py", line 255, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time (or directly access saved variables after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved variables after calling backward.
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/workspace/src/libs/pytorch/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time (or directly access saved variables after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved variables after calling backward.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 41061) of binary: /opt/conda/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
```
Now in the `find_unused_parameters=True` case `opt[0].grad_fn` is set to `torch.autograd.function._DDPSinkBackward` and the error is raised.

## Environment

Reproduced on different systems using the aforementioned commits.

CC @mcarilli who was discussing this issue with me.
CC @rohan-varma as the author of the related PR

## Additional information
Unrelated to this issue, but maybe the `inputs` should be stored using `ctx.save_for_backward` instead of an assignment in:
https://github.com/pytorch/pytorch/blob/963c9833668d239fcef59126a0dfe3df4b31e452/torch/nn/parallel/distributed.py#L139

Thanks @t-vi for the helpful additional discussion and for pointing out this potential issue.
Note that changing the assignment to `ctx.save_for_backward` didn't solve the initial error.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
@ptrblck @xwang233 @mcarilli A potential solution might be to save the tensors that have `None` grad_fn and avoid overwriting those with the tensor that has the DDPSink grad_fn. This will make it so that only tensors with a non-None grad_fn have it set to `torch.autograd.function._DDPSinkBackward`.

I tested this and it seems to work for this case, but would like your thoughts on whether this might introduce any other issues or if there's something I didn't consider.

**Comment by mcarilli** [comment]
Replied on slack
