### ISSUE TITLE
Record file/line number when creating test data, and then report it in backtraces associated with this data

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#60748]
One of the big problems with metaprogrammed tests is that it is not obvious where the test data that generated the metaprogrammed test lives. For example, here is a recent backtrace I got from a test:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 402, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 397, in instantiated_test
    result = test_fn(self, *args)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 369, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 685, in test_inplace_grad
    self._grad_test_helper(device, dtype, op, self._get_safe_inplace(op.get_inplace()))
  File "test_ops.py", line 656, in _grad_test_helper
    return self._check_helper(device, dtype, op, variant, 'gradcheck', check_forward_ad=check_forward_ad)
  File "test_ops.py", line 637, in _check_helper
    check_forward_ad=check_forward_ad))
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2303, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 1265, in gradcheck
    return _gradcheck_helper(**args)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 1273, in _gradcheck_helper
    func_out = func(*tupled_inputs)
  File "test_ops.py", line 622, in fn
    output = op.gradcheck_wrapper(variant, *inputs, **sample.kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_methods_invocations.py", line 497, in <lambda>
    gradcheck_wrapper=lambda op, *args, **kwargs: op(*args, **kwargs),  # wrapper function for gradcheck
  File "test_ops.py", line 590, in _fn
    return inplace_variant(t.clone(), *args, **kwargs)
RuntimeError: result tensor does not match matmul output shape
```

Do you know where the data for this tests lives? In fact, it is very difficult to make this determination based on the backtrace alone. The best technique that I know about is to look at the test name, guess where the "split" between the op info test name (`test_inplace_grad`) and the operator name (`addmm`) and the variant (empty in this case) and then grep for the operator name in a folder (but not the `test/` folder, that would make too much sense).

There is a very simple thing we can do to make an uninformed end user's life much easier: record a file/line number (or even backtrace, if you wanna be fancy) when we create the test data, and then augment error reporting in test cases to report the data that generated the metaprogrammed test in question (this probably is most easily done by catching exceptions being thrown and adding more information to the exception).

cc @mruberry

**Comment by zou3519** [comment]
On a similar note, if I had a magic wand, if a test failed I would want to get a "very simple minimum repro" that doesn't call PyTorch testing internals. For example, if an autograd test on torch.sin, it would be nice to get a script that looks like:

```
x = torch.tensor([...], requires_grad=True)
expected = torch.tensor([...])
x.sin().backward()
assert x.grad == expected
```
instead of needing to pdb through the testing harness
