### ISSUE TITLE
Bug in `pytorch/benchmarks/tensorexpr/pt_engine.py`

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#60802]
## 🐛 Bug

https://github.com/pytorch/pytorch/blob/dd045ab540ad47e0205cc1c53be400947f4e7477/benchmarks/tensorexpr/pt_engine.py#L21
should be replaced by `return t.detch().cpu().numpy()`

## To Reproduce

1. Run `python -m benchmarks.tensorexpr --device cpu`

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/pytorch/benchmarks/tensorexpr/__main__.py", line 323, in <module>
    main()
  File "/pytorch/benchmarks/tensorexpr/__main__.py", line 266, in main
    run_default_configs(benchmark_cls, allow_skip=True)
  File "/pytorch/benchmarks/tensorexpr/__main__.py", line 221, in run_default_configs
    bench.run(args)
  File "/pytorch/benchmarks/tensorexpr/benchmark.py", line 136, in run
    return self.run_impl(True)
  File "/pytorch/benchmarks/tensorexpr/benchmark.py", line 171, in run_impl
    self.check()
  File "/pytorch/benchmarks/tensorexpr/benchmark.py", line 52, in check
    self.reference(), self.numpy(self.compute()), atol=1e-2
  File "/pytorch/benchmarks/tensorexpr/elementwise.py", line 59, in reference
    [d1, d2, d3, d4] = [self.numpy(d) for d in [self.d1, self.d2, self.d3, self.d4]]
  File "/pytorch/benchmarks/tensorexpr/elementwise.py", line 59, in <listcomp>
    [d1, d2, d3, d4] = [self.numpy(d) for d in [self.d1, self.d2, self.d3, self.d4]]
  File "/pytorch/benchmarks/tensorexpr/pt_engine.py", line 21, in numpy
    return t.cpu().numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

## Expected behavior

This error shouldn't be encountered

## Environment

Built from source

**Comment by imaginary-person** [comment]
Ah, there are probably more of them -

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/pytorch/benchmarks/tensorexpr/__main__.py", line 323, in <module>
    main()
  File "/pytorch/benchmarks/tensorexpr/__main__.py", line 266, in main
    run_default_configs(benchmark_cls, allow_skip=True)
  File "/pytorch/benchmarks/tensorexpr/__main__.py", line 221, in run_default_configs
    bench.run(args)
  File "/pytorch/benchmarks/tensorexpr/benchmark.py", line 136, in run
    return self.run_impl(True)
  File "/pytorch/benchmarks/tensorexpr/benchmark.py", line 182, in run_impl
    engine.backward([z], [self.result_grad], self.grad_variables)
  File "/pytorch/benchmarks/tensorexpr/pt_engine.py", line 42, in backward
    torch.autograd.backward(tensors, grad_tensors=grad_tensors)
  File "/pytorch/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
