### ISSUE TITLE
[Docker] Incompatible torchvision for 1.9.0-cuda10.2-cudnn7-runtime tag.

### ISSUE THREAD

**Issue by sebastian-sz** [pytorch/pytorch#61030]
## 🐛 Bug
When attempting to use torchvision ops inside the Pytorch's docker container of tag `1.9.0-cuda10.2-cudnn7-runtime` the following error will be displayed:
```
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision
versions are incompatible, or if you had errors while compiling
torchvision from source. For further information on the compatible versions, check 
https://github.com/pytorch/vision#installation for the compatibility matrix. 
Please check your PyTorch version with torch.__version__ and your torchvision
version with torchvision.__version__ and verify if they are compatible, and if not please 
reinstall torchvision so that it matches your PyTorch install.
```

## To Reproduce

One can run an example torchvision op inside the mentioned container:

```bash
docker run --rm pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime \
 python -c "import torchvision;torchvision.ops.nms(1,2,3)"
```

## Expected behavior
For the example above, the error should be that I'm passing scalar and not a tensor. For a better example the ops should be 
correctly executed. Either way, there should not be incompatibility error.

## Environment
N/A 

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): Docker
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7
 - CUDA/cuDNN version: 7
 - GPU models and configuration: Tesla K80
 - Any other relevant information: N/A

**Comment by vladserkoff** [comment]
I can confirm the same for cuda 11 version:
```
sudo docker run --rm -it pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime python -c "import torchvision;torchvision.ops.nms(1,2,3)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 34, in nms
    _assert_has_ops()
  File "/opt/conda/lib/python3.7/site-packages/torchvision/extension.py", line 63, in _assert_has_ops
    "Couldn't load custom C++ ops. This can happen if your PyTorch and "
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
```
