### ISSUE TITLE
CUDNN_STATUS_NOT_INITIALIZED while building  for Jetson

### ISSUE THREAD

**Issue by el3ctrician** [pytorch/pytorch#6106]
- OS: Ubuntu 16.04
- PyTorch version: 0.3.0b0+af3964a
- How you installed PyTorch : Source 
- Python version: 3.5.2
- CUDA/cuDNN version: 9.0.252 /  7005 // using torch.backends.cudnn.version()
- GPU models and configuration: Jetson TX2 
- GCC version (if compiling from source): 5.4.0 20160609

i am trying to run a model on jetson tx, i fllowed the instruction on how to compile from the source and if i run `print(torch.backends.cudnn.is_acceptable(torch.cuda.FloatTensor(1)))` it prints `True` however running this code :
```
import torch.nn as nn
lstm = nn.LSTM(3, 3)
lstm.cuda()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 85, in flatten_parameters
    handle = cudnn.get_handle()
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/__init__.py", line 296, in get_handle
    handle = CuDNNHandle()
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/__init__.py", line 110, in __init__
    check_error(lib.cudnnCreate(ctypes.byref(ptr)))
  File "/usr/local/lib/python3.5/dist-packages/torch/backends/cudnn/__init__.py", line 283, in check_error
    raise CuDNNError(status)
torch.backends.cudnn.CuDNNError: 1: b'CUDNN_STATUS_NOT_INITIALIZED'
```
any guesses on what i need to change ?

Thanks

**Comment by el3ctrician** [comment]
tried to compile pytorch 0.3.1 and i run onto a new issue, same code above produces this error now 
```
>>> import torch
>>> torch.backends.cudnn.enabled()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'bool' object is not callable
>>> torch.backends.cudnn.enabled
True
>>> import torch.nn as nn
>>> lstm = nn.LSTM(3, 3)
>>> lstm.cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 122, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 152, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 216, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.5/dist-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/usr/local/lib/python3.5/dist-packages/torch/cuda/__init__.py", line 358, in _lazy_new
    _lazy_init()
  File "/usr/local/lib/python3.5/dist-packages/torch/cuda/__init__.py", line 120, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.5/dist-packages/torch/cuda/__init__.py", line 71, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError: 
The NVIDIA driver on your system is too old (found version 8000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: http://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.
```

**Comment by SsnL** [comment]
@csarofeen

**Comment by ngimel** [comment]
What is your driver version (or rather, what's your jetpack version)? JetPack 3.1 supports cuda 8 only, for cuda 9 you need JetPack 3.2 https://developer.nvidia.com/embedded/jetpack-notes

**Comment by dusty-nv** [comment]
Hi, have you tried building using this repo?  http://github.com/dusty-nv/jetson-reinforcement

**Comment by el3ctrician** [comment]
updating to latest JetPack and recompiling from source solved the issue, thanks
