### ISSUE TITLE
error when installing pytorch

### ISSUE THREAD

**Issue by aisri** [pytorch/pytorch#6117]
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- OS: Ubuntu 
- PyTorch version: tip of master
- How you installed PyTorch (conda, pip, source): source
- Python version: python3.5.2
- CUDA/cuDNN version: 9.1/7.1.2
- GPU models and configuration: Tesla K80
- GCC version (if compiling from source): 5.4.0

In addition, including the following information will also be very helpful for us to diagnose the problem:
```
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
copying third_party/pybind11/include/pybind11/eigen.h -> torch/lib/include/pybind11
copying third_party/pybind11/include/pybind11/pybind11.h -> torch/lib/include/pybind11
copying third_party/pybind11/include/pybind11/common.h -> torch/lib/include/pybind11
copying third_party/pybind11/include/pybind11/pytypes.h -> torch/lib/include/pybind11
copying torch/torch.h -> torch/lib/include/torch
running build
running build_py
Traceback (most recent call last):
  File "setup.py", line 846, in <module>
    'lib/include/torch/torch.h',
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 436, in run
    setuptools.command.install.install.run(self)
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 65, in run
    orig.install.run(self)
  File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
    self.run_command('build')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 35, in finalize_options
    self.exclude_package_data = (self.distribution.exclude_package_data or
AttributeError: 'Distribution' object has no attribute 'exclude_package_data'
```

- Context around what you are trying to do

cc @malfet @seemethere @walterddr

**Comment by ezyang** [comment]
What if you upgrade pip and try again?

**Comment by aisri** [comment]
in Anaconda I see version being **pip 9.0.1**

```
conda list | grep pip -
(standard input):167:pip                       9.0.1                    py36_5 
```

**Comment by seemethere** [comment]
I see this issue is more than 2 years old, @aisri if you're still having this issue feel free to re-open
