### ISSUE TITLE
RuntimeError: Unsupported: ONNX export of operator adaptive_max_pool1d

### ISSUE THREAD

**Issue by JackCaster** [pytorch/pytorch#61172]
## 🐛 Bug
I am trying to export a model built with Pytorch-lightning to onnx. I received the error
```
RuntimeError: Unsupported: ONNX export of operator adaptive_max_pool1d, since output size is not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub.
```
I am using Pytorch 1.8.1 and according to [this page](https://pytorch.org/docs/1.8.1/onnx.html) `adaptive_max_pool1d` is supported.

## To Reproduce
My model is fairly vanilla (a collection of 1d conv layers and an output linear layer for classification), The only custom layer is `AdaptiveConcatPool1d`, which incorporates `AdaptiveAvgPool1d` and `AdaptiveMaxPool1d`:

```python
class AdaptiveConcatPool1d(nn.Module):
    """Layer that concats `AdaptiveAvgPool2d` and `AdaptiveMaxPool2d`.
    Adapted from:
    https://fastai1.fast.ai/layers.html#AdaptiveConcatPool2d
    https://github.com/fastai/fastai1/blob/master/fastai/layers.py#L176
    """

    def __init__(self, sz=None):
        "Output will be 2*sz or 2 if sz is None"
        super().__init__()
        self.output_size = sz or 1
        self.ap = nn.AdaptiveAvgPool1d(self.output_size)
        self.mp = nn.AdaptiveMaxPool1d(self.output_size)

    def forward(self, x):
        return torch.cat([self.mp(x), self.ap(x)], 2)
```
when the model is trained, I can use `.to_onnx()` to export it
```python
input_sample = torch.randn((1, 2, 130))
model.to_onnx(
        file_path='model.onnx',
        input_sample=input_sample,
        export_params=True,
    )
```
Traceback:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\pytorch_lightning\core\lightning.py", line 1749, in to_onnx
    torch.onnx.export(self, input_sample, file_path, **kwargs)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\torch\onnx\__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\torch\onnx\utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\torch\onnx\utils.py", line 701, in _export
    dynamic_axes=dynamic_axes)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\torch\onnx\utils.py", line 468, in _model_to_graph
    module=module)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\torch\onnx\utils.py", line 206, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\torch\onnx\__init__.py", line 309, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\torch\onnx\utils.py", line 997, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\torch\onnx\symbolic_opset9.py", line 930, in symbolic_fn
    return sym_help._onnx_unsupported(name + ', since output size is not factor of input size')
  File "C:\dev\miniconda\envs\xxx\lib\site-packages\torch\onnx\symbolic_helper.py", line 225, in _onnx_unsupported
    'Please feel free to request support or submit a pull request on PyTorch GitHub.'.format(op_name))
RuntimeError: Unsupported: ONNX export of operator adaptive_max_pool1d, since output size is not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

## Environment

```
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.18362-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==1.3.8
[pip3] torch==1.8.1
[pip3] torchmetrics==0.4.0
[conda] blas                      1.0                         mkl    anaconda
[conda] cpuonly                   1.0                           0    pytorch-lts
[conda] mkl                       2020.2                      256    anaconda
[conda] mkl-service               2.3.0            py36h196d8e1_0
[conda] mkl_fft                   1.0.6            py36hdbbee80_0    anaconda
[conda] mkl_random                1.1.1            py36h47e9c7a_0    anaconda
[conda] numpy                     1.19.2           py36hadc3359_0
[conda] numpy-base                1.19.2           py36ha3acd2a_0
[conda] pytorch                   1.8.1               py3.6_cpu_0  [cpuonly]  pytorch-lts
[conda] pytorch-lightning         1.3.8                    pypi_0    pypi
[conda] torchmetrics              0.4.0                    pypi_0    pypi
```
## Additional context

cc @BowenBao @neginraoof

**Comment by hwangdeyu** [comment]
@JackCaster  I can't reproduce using `adaptive_max_pool1d` op. Could you share the samll repro code?

**Comment by JackCaster** [comment]
This is a minimal example:
```python
import torch
from torch import nn

class Net(nn.Module):
  def __init__(self):
    super().__init__()
    _layer_size = 23
    self.net = nn.Sequential(
        nn.Linear(10, 100),
        nn.AdaptiveMaxPool1d(_layer_size)
        )

  def forward(self, x):
    return self.net(x)

net = Net()
net.eval()

x = torch.randn((1, 1, 10))
y = net(x)
print(f"x shape: {x.shape}, y.shape: {y.shape}")

torch.onnx.export(net, x, "main.onnx")
```

if `_layer_size = 23` I will get the error:
```
RuntimeError: Unsupported: ONNX export of operator adaptive_max_pool1d, since output size is not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub.
```
instead, if `_layer_size = 25` (25 is a factor of the layer input size 100) then it works. 

I understand there are some limitations on how to perform `AdaptiveMaxPool1d` for some input/output size. I opened this issue as suggested by the error message nonetheless. Do you think this limitation will be addressed in the future?

**Comment by hwangdeyu** [comment]
@JackCaster  Thanks for provide the example! This doesn't have plan to support it yet.
However, this is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1408925.
Same with https://github.com/pytorch/pytorch/issues/42653.
