### ISSUE TITLE
DISABLED test_allgather_coalesced_checks (__main__. ProcessGroupGlooTest)

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#61201]
## 🐛 Bug
https://app.circleci.com/pipelines/github/pytorch/pytorch/345997/workflows/fc0c1bff-e875-4ffb-9ce8-0f5da0b61a5d/jobs/14572814

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 398, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 610, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 653, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 3 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 529, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
    fn()
  File "distributed/test_c10d_gloo.py", line 1074, in test_allgather_coalesced_checks
    pg = c10d.ProcessGroupGloo(store, self.rank, self.world_size, self.opts())
RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:48270
```

**Comment by rohan-varma** [comment]
https://github.com/pytorch/pytorch/pull/61396 might be a fix, close to let it run in CI
