### ISSUE TITLE
ONNX export doubles RAM usage

### ISSUE THREAD

**Issue by piotrm-nvidia** [pytorch/pytorch#61263]
## ONNX export doubles RAM usage during conversion of model.

A model during conversion to ONNX is duplicated by converter. It seams that the new tensors are created as copies of the tensors in the PyTorch model. It temporary doubles the model RAM usage. It means that you needs 2xRAM to convert model than to just do inference with it. It vastly limits practical applications of very large ONNX models or requires workaround with manual split of model structure before it is converted to ONNX.

## To Reproduce

Modify this script to use 60% of your RAM for inference and run it:

```python
import torch
import math

# Size in GB
tensor_size = 4
print("Tensor size ", tensor_size, "GB")
# Change this to ~60% of your RAM size
model_size = 16
print("Model size ", model_size, "GB")
# The number of layer will be adjusted to fit in less than model size
layers_num = model_size // tensor_size
kB = 1024
MB = kB * kB
GB = MB * kB
#Number size
precision_size = 4
activation_size = math.floor(math.sqrt(tensor_size * GB / precision_size))
print("Activation size ", math.floor(activation_size / kB * precision_size), "kB")

class Net(torch.nn.Module):
    def __init__(self, empty_init = False):
        super(Net, self).__init__()
        for i in range(layers_num):
            name = "fc_%d" % i
            linear = torch.nn.Linear(activation_size, activation_size)
            setattr(self, name, linear)
    def forward(self, x):
        for i in range(layers_num):
            name = "fc_%d" % i
            linear = getattr(self, name)
            x = linear(x)
        return x

model = Net()


print("Model created")

input = torch.zeros(activation_size, requires_grad=True)
output = model(input)
print("Output ", output.size())


with torch.no_grad():
    torch.onnx.export(model, (input, ), './model_large.onnx', do_constant_folding=False, opset_version=13,  use_external_data_format=True, enable_onnx_checker=False)

print("ONNX saved")

```
The output from this script at machine with 32 GB RAM:

```
user@myhost:/home/user# python ./double_onnx_ram.py
Tensor size  4 GB
Model size  16 GB
Activation size  128 kB
Model created
Output  torch.Size([32768])
Traceback (most recent call last):
  File "./double_onnx_ram.py", line 45, in <module>
    torch.onnx.export(model, (input, ), './model_large.onnx', do_constant_folding=False, opset_version=13,  use_external_data_format=True, enable_onnx_checker=False)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 86, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 671, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 442, in _model_to_graph
    graph, params, torch_out = _create_jit_graph(model, args,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 412, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 374, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 1139, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 125, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 112, in wrapper
    tuple(x.clone(memory_format=torch.preserve_format) for x in args)
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 112, in <genexpr>
    tuple(x.clone(memory_format=torch.preserve_format) for x in args)
RuntimeError: [enforce fail at CPUAllocator.cpp:60] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 4294967296 bytes. Error code 12 (Cannot allocate memory)

```

## Expected behavior

The ONNX converter should just use references to tensors from model. You don't need deep copy to just save ONNX model to file. It will reduce RAM usage 50% and speed up whole process.

If you modify test model to use less than 50% of your RAM, the conversion to ONNX is successfull. 

## Environment

I'm using NGC PyTorch 21.02 container:
```
nvidia-docker run -ti --net=host -v /mnt/nvdl/:/mnt/nvdl/ nvcr.io/nvidia/pytorch:21.02-py3
```

**IMPORTANT:**
This example uses old PyTorch because 2GB ONNX tensors are broken in master PyTorch:
https://github.com/pytorch/pytorch/issues/59906

Environment:
 - PyTorch Version: 1.8.0a0+52ea372
 - OS: Ubuntu 20.04.1 LTS (x86_64)
 - How you installed PyTorch: From NVIDIA container 21.02
 - Build command you used (if compiling from source):
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.2.67/8.1
 - GPU models and configuration: 1 NVIDIA A100 80 GB
 - Any other relevant information:

collect_env.py output:
```
PyTorch version: 1.8.0a0+52ea372
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.19.4
Libc version: glibc-2.31

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-147-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.2.67
GPU models and configuration: GPU 0: XXXXXXX
Nvidia driver version: 470.42.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.8.0a0+52ea372
[pip3] torchtext==0.9.0a0
[pip3] torchvision==0.9.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.19.2           py38h6163131_0  
[conda] numpy-base                1.19.2           py38h75fe3a5_0  
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.8.0a0+52ea372          pypi_0    pypi
[conda] torchtext                 0.9.0a0                  pypi_0    pypi
[conda] torchvision               0.9.0a0                  pypi_0    pypi

```

**Comment by hwangdeyu** [comment]
Will take a look and dive into which part is duplicated the use of RAM resources.

**Comment by BowenBao** [comment]
```
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 125, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 112, in wrapper
    tuple(x.clone(memory_format=torch.preserve_format) for x in args)
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 112, in <genexpr>
    tuple(x.clone(memory_format=torch.preserve_format) for x in args)
```

Log shows tracer clones all arguments. would like your thoughts on this @jamesr66a . Do you think there is a way we can reduce  RAM usage here?

**Comment by leimao** [comment]
From the ONNX export's perspective, I think this is normal because it will essentially make copy of the model parameters. Did you try `use_external_data_format=True`? I am thinking with a good implementation for this, it is possible to achieve negligible extra memory for ONNX export.

**Comment by leimao** [comment]
Sorry, I just saw you already used `use_external_data_format=True`. Then this is definitely something that PyTorch could improve.

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1410447>

**Comment by SnoozingSimian** [comment]
@garymm Is there any update on this?

**Comment by dashesy** [comment]
This is a blocker because some models cannot be exported with CPU (e.g. float16 not supported by PyTorch conv, so we cannot export with CPU)

Has anyone found a workaround?

**Comment by un-certainty** [comment]
Hi @dashesy !

I am facing the same issue as yours. Have you found out a workaround?

**Comment by BowenBao** [comment]
cc @wschin These are great cases for symbolic export.

**Comment by dasheasy** [comment]
I have a workaround I post tomorrow. Yes symbolic export may also be useful here. But I guess it's retiring in Pytorch2 no?

**Comment by dashesy** [comment]
I have a workaround I post tomorrow. Yes symbolic export may also be useful here. But I guess it's retiring in Pytorch2 no?

**Comment by dashesy** [comment]
As workaround I use these 2 patches

This patch is to avoid clone (of course after this you cannot use the model anymore, so you export and throw away the object)

```patch
diff --git a/opt/miniconda/envs/pt/lib/python3.7/site-packages/torch/jit/_trace.py b/_trace.py
index 5a2f6e5..a236c5c 100644
--- a/opt/miniconda/envs/pt/lib/python3.7/site-packages/torch/jit/_trace.py
+++ b/_trace.py
@@ -110,8 +110,11 @@ class ONNXTracedModule(torch.nn.Module):
 
             trace_inputs = _unflatten(in_args, in_desc)
 
+            #ret_inputs.append(
+            #    tuple(x.clone(memory_format=torch.preserve_format) for x in args)
+            #)
             ret_inputs.append(
-                tuple(x.clone(memory_format=torch.preserve_format) for x in args)
+                tuple(x for x in args)
             )
             if self._return_inputs_states:
                 inputs_states.append(_unflatten(in_args, in_desc))
```

and this patch is to go back to cpu at the end. This is fine at this state because the forward pass is already done.

```patch
diff --git a/opt/miniconda/envs/pt/lib/python3.7/site-packages/torch/onnx/utils.py b/utils.py
index b0418f7..5a217de 100644
--- a/opt/miniconda/envs/pt/lib/python3.7/site-packages/torch/onnx/utils.py
+++ b/utils.py
@@ -492,6 +492,15 @@ def _model_to_graph(model, args, verbose=False,
 
     graph, params, torch_out, module = _create_jit_graph(model, args)
 
+    if isinstance(torch_out, (tuple, list)):
+        torch_out = type(torch_out)([p.cpu() for p in torch_out])
+    else:
+        torch_out = torch_out.cpu()
+    params = [p.cpu() for p in params]
+
     params_dict = _get_named_param_dict(graph, params)
 
     graph = _optimize_graph(graph, operator_export_type,
```

Looking at symbolic export, there may be also another way
