### ISSUE TITLE
jit.trace dost not support dict of dict?

### ISSUE THREAD

**Issue by zheng-ningxin** [pytorch/pytorch#61397]
## ❓ Trace does not support `dict` of `dict`
Hi, we have a complicated model whose return value is a `dict of dict`:
![image](https://user-images.githubusercontent.com/49771382/124853152-ff5a4200-dfd7-11eb-8844-7f370b9b2545.png)

We want to trace the model and get the error:
```
Traceback (most recent call last):
  File "/root/ScaleGodiva/godiva/model/t2v/net.py", line 608, in <module>
    torch.jit.trace(net, inputs, strict=False)
  File "/root/anaconda3/envs/godiva/lib/python3.9/site-packages/torch/jit/_trace.py", line 735, in trace
    return trace_module(
  File "/root/anaconda3/envs/godiva/lib/python3.9/site-packages/torch/jit/_trace.py", line 952, in trace_module
    module._c._create_method_from_trace(
RuntimeError: output 1 ({logits: {gt_vae: Columns 1 to 13 3161  3403  2117   663  3282  3374  3077  4118  2119   292  3784  2412  4035
 1197  3576   725  3062  4132   499  3598   961  3519  2537  2551  2550   725
 1645  3259  1935  3952  1093  2655  1379  3942  2639  2713  3491  1970  4015

Columns 14 to 26  494   262  2198  2175  2963  2630  2366  1521  3598  4126  2581  4072  2239
 2252  3367  2039  3061  2232   862  2544  3874  2387  2359  1507  2456  3131
 2494  2551  3874  1100  2643  3487  2966  2117  2971   242  1703  3927  3349
......
[ CUDAFloatType{6,3,64,64} ]}, loss: {loss_img: 9.3907
[ CUDAFloatType{} ], total_loss: 9.3907
[ CUDAFloatType{} ]}, metric: {a:  1
[ CPUFloatType{1} ]}}) of traced region cannot be understood by the tracer, only outputs matchingdict[Union[str, Tensor], Union[Tensor, Tuple[Tensor, ...]]] can be a dictionary output of a traced function
```
Is there any workaround for this error? Thanks

cc @gmagogsfm

**Comment by tugsbayasgalan** [comment]
can you post a reproducible script?
