### ISSUE TITLE
MemoryError with pip Install even with --no-cache-dir option

### ISSUE THREAD

**Issue by PVinay737** [pytorch/pytorch#61516]
16 GB Empty space in the disk.  Does it take much longer than that ?

Similar to [#25164](https://github.com/pytorch/pytorch/issues/25164) ?

```
Collecting torch<2.0.0,>=1.4.0 (from lm-scorer)
  Downloading https://files.pythonhosted.org/packages/a1/1f/a372f2e9f0a54fc479fcee3ac072f8cd5091054e9d7293dd4372338e5277/torch-1.9.0-cp36-cp36m-manylinux1_x86_64.whl (831.4MB)
    100% |################################| 831.4MB 62.0MB/
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 346, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 381, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 623, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python3.6/site-packages/pip/download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 609, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 498, in unzip_file
    data = zip.read(name)
  File "/usr/lib64/python3.6/zipfile.py", line 1338, in read
    return fp.read()
  File "/usr/lib64/python3.6/zipfile.py", line 858, in read
    buf += self._read1(self.MAX_N)
  File "/usr/lib64/python3.6/zipfile.py", line 948, in _read1
    data = self._decompressor.decompress(data, n)
MemoryError
```

**Comment by malfet** [comment]
Modified label a bit, as it has nothing to do with PyTorch memory usage, but rather with the way piputils/zip packages are implemented in Python-3.6

@PVinay737 are suggestions mentioned in #25164 work for you? I.e. would downloading the package manually and then installing it solve the issue? Also, if you don't need GPU acceleration, can you try installing CPU-only version, which is much smaller?

**Comment by PVinay737** [comment]
OK

Going ahead with CPU-only version for now
