### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by hanhao2019102935** [pytorch/pytorch#61522]
I tried to run my model on coLab. When my gpu version is Telsa T4.It shows the previous error.But when the system was assigned to me the Telsa K80, the problem was solved naturally.My environment is cuda9.0 torch3.1. Looking forward to your help

cc @ngimel @csarofeen @ptrblck @xwang233

**Comment by ngimel** [comment]
Please provide repro instructions.

**Comment by hanhao2019102935** [comment]
@ngimel Thank you very much for your reply. My project requires that my Torch version must be less than 0.4.0.
Below are the details of my bug.
Traceback (most recent call last):
  File "train_metarcnn.py", line 388, in <module>
    num_boxes_list)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/sample_data/MetaR-CNN/lib/model/faster_rcnn/faster_rcnn.py", line 61, in forward
    attentions = self.prn_network(prn_data)
  File "/content/sample_data/MetaR-CNN/lib/model/faster_rcnn/resnet.py", line 328, in prn_network
    base_feat = self.RCNN_base(self.meta_conv1(im_data))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7fe2f68f51d0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 333, in __del__
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 319, in _shutdown_workers
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 337, in get
TypeError: 'NoneType' object is not callable

**Comment by ngimel** [comment]
Pytorch 0.4 does not support T4, as those GPUs were released much later.

**Comment by hanhao2019102935** [comment]
OK, thank you @ngimel
