### ISSUE TITLE
Pytorch Mobile on Android, LAPACK library not found in compilation

### ISSUE THREAD

**Issue by yingbo** [pytorch/pytorch#61693]
## LAPACK library not found in compilation (Pytorch Mobile, Android, Java)

From post in  [Discussion Forum](https://discuss.pytorch.org/t/problems-with-lapack-on-android/73111), I think someone has the same issue, but the solution is not clear and the download link  was removed. Is there an official document to solve the problem?

More details on what I'm facing. In my `build.gradle`, I tried both `org.pytorch:pytorch_android_lite:1.9.0` and `org.pytorch:pytorch_android_torchvision:1.9.0`. But I got the same error like:

```
RuntimeError: inverse: LAPACK library not found in compilation
    
        at org.pytorch.NativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:52)
```

Shouldn't this problem be a bug?

**Comment by cccclai** [comment]
@IvanKobzarev do you know how to resolve?

**Comment by girgink** [comment]
I'm not sure if it is the case also with Java version, during compilation PyTorch (1.9.0) BLAS auto detection selects BLIS first, although OpenBLAS exists. BLIS doesn't have LAPACK support, therefore torch gives "LAPACK library not found in compilation". You can correct this by setting WITH_BLAS=open, or by editing cmake/Modules/FindBLAS.cmake and setting default value to "open".
