### ISSUE TITLE
HTTP Error 403 for torch.hub ResNet

### ISSUE THREAD

**Issue by n2cholas** [pytorch/pytorch#61755]
## 🐛 Bug

`torch.hub` pretrained resnet doesn't work.

## To Reproduce

On colab:

```py
import torch

model = torch.hub.load('pytorch/vision:v0.9.0', 'resnet18', pretrained=True)
```

Error:

```py
/usr/lib/python3.7/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: rate limit exceeded
```

This is identical to the code snippet on the [website](https://pytorch.org/hub/pytorch_vision_resnet/)

## Expected behavior

The code should run.

## Environment

Google colab.

cc @nairbv

**Comment by nairbv** [comment]
Is this a duplicate of https://github.com/pytorch/vision/issues/4156 ?

**Comment by n2cholas** [comment]
Yes, thanks!

**Comment by mattpopovich** [comment]
Is this an issue for pytorch/vision or pytorch/pytorch? I get the same error if loading other models (not from pytorch/vision) as well:
```python
root@pc:~# python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.9.0a0+gitd69c22d'
>>> model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 362, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 162, in _get_cache_or_reload
    _validate_not_a_forked_repo(repo_owner, repo_name, branch)
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 124, in _validate_not_a_forked_repo
    with urlopen(url) as r:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
```

**Comment by nairbv** [comment]
> Is this an issue for pytorch/vision or pytorch/pytorch?

That's right, the fix is in pytorch core. The rate limit is triggered by the _validate_not_a_forked_repo function seen in your error trace as well:
https://github.com/pytorch/pytorch/pull/61761

**Comment by malfet** [comment]
As a workaround, can you please adding the following line before making any "torch.hub" calls:
```
torch.hub._validate_not_a_forked_repo=lambda a,b,c: True
```

**Comment by mattpopovich** [comment]
@malfet that works for me! Thank you!

**Comment by harisgulzar1** [comment]
> As a workaround, can you please adding the following line before making any "torch.hub" calls:
> 
> ```
> torch.hub._validate_not_a_forked_repo=lambda a,b,c: True
> ```

Worked for me, for MobileNetV2

**Comment by monajalal** [comment]
using the suggestion by @malfet led to

```
(fashcomp) [jalal@goku fashion-compatibility]$ python main.py --test --l2_embed --resume runs/nondisjoint_l2norm/model_best.pth.tar --datadir ../../../data/fashion
/scratch3/venv/fashcomp/lib/python3.8/site-packages/torchvision/transforms/transforms.py:310: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  warnings.warn("The use of the transforms.Scale transform is deprecated, " +
Downloading: "https://github.com/pytorch/vision/archive/v1.9.0.zip" to /home/grad3/jalal/.cache/torch/hub/v1.9.0.zip
Traceback (most recent call last):
  File "main.py", line 314, in <module>
    main()    
  File "main.py", line 106, in main
    model = torch.hub.load('pytorch/vision:v1.9.0', 'resnet18', pretrained=True)
  File "/scratch3/venv/fashcomp/lib/python3.8/site-packages/torch/hub.py", line 362, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
  File "/scratch3/venv/fashcomp/lib/python3.8/site-packages/torch/hub.py", line 169, in _get_cache_or_reload
    download_url_to_file(url, cached_file, progress=False)
  File "/scratch3/venv/fashcomp/lib/python3.8/site-packages/torch/hub.py", line 419, in download_url_to_file
    u = urlopen(req)
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by Coderx7** [comment]
@monajalal use:
```python
 model = torch.hub.load('pytorch/vision:v0.9.0', 'resnet18', pretrained=True)
```
note its pytorch/vision:**v0.9.0**  and not **v1.9.0**

**Comment by bhavik-cipio** [comment]
It is working, Thanks

**Comment by sammlapp** [comment]
I get the same HTTP error 403 with this code when running on Github workflows:
```
    architecture_ft = torch.hub.load(
        "NVIDIA/DeepLearningExamples:torchhub",
        "nvidia_efficientnet_b0",
        pretrained=False,
    )
```
Package versions: torch 1.13.1,  torchvision 0.14.1

I can't tell if a solution to this issue has been given here or in the related issues (https://github.com/pytorch/vision/issues/4156, https://github.com/pytorch/vision/issues/1876)

Please let me know if there is a solution
