### ISSUE TITLE
RuntimeError: Exporting the operator square to ONNX opset version 9 is not supported

### ISSUE THREAD

**Issue by emanuelgollob** [pytorch/pytorch#61766]
I am trying to export a stylegan2-ada-pytorch to ONNX opset version 9.
Whenever I run:

torch.onnx.export(G_ema, args=(z, c), f="TextureGAN.onnx", export_params=True, opset_version=9, do_constant_folding=True, input_names=["z", "c"], output_names = ['Y'])

I get the error: RuntimeError: Exporting the operator square to ONNX opset version 9 is not supported
My setup: 64-bit Python 3.7 and PyTorch 1.7.1

My questions:
Is there a workaround for the square operator?

Traceback:
Traceback (most recent call last):
File "train.py", line 541, in
main() # pylint: disable=no-value-for-parameter
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\click\core.py", line 1137, in call
return self.main(*args, **kwargs)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\click\core.py", line 1062, in main
rv = self.invoke(ctx)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\click\core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\click\core.py", line 763, in invoke
return _callback(*args, **kwargs)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\click\decorators.py", line 26, in new_func
return f(get_current_context(), *args, **kwargs)
File "train.py", line 534, in main
subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
File "train.py", line 386, in subprocess_fn
training_loop.training_loop(rank=rank, **args)
File "C:\Users\emanu\Downloads\stylegan2-ada-pytorch-main\stylegan2-ada-pytorch-main\training\training_loop.py", line 241, in training_loop
torch.onnx.export(G_ema, args=(z, c), f="TextureGAN.onnx", export_params=True, opset_version=9, do_constant_folding=True, input_names=["z", "c"], output_names = ['Y'])
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx_init.py", line 230, in export
custom_opsets, enable_onnx_checker, use_external_data_format)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 91, in export
use_external_data_format=use_external_data_format)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 639, in _export
dynamic_axes=dynamic_axes)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 421, in _model_to_graph
dynamic_axes=dynamic_axes, input_names=input_names)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 203, in _optimize_graph
graph = torch._C.jit_pass_onnx(graph, operator_export_type)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx_init.py", line 263, in _run_symbolic_function
return utils._run_symbolic_function(*args, **kwargs)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 930, in _run_symbolic_function
symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\utils.py", line 888, in _find_symbolic_in_registry
return sym_registry.get_registered_op(op_name, domain, opset_version)
File "C:\Users\emanu\anaconda3\envs\stgpytorch\lib\site-packages\torch\onnx\symbolic_registry.py", line 111, in get_registered_op
raise RuntimeError(msg)
RuntimeError: Exporting the operator square to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.

cc @BowenBao @neginraoof

**Comment by neginraoof** [comment]
Hi @emanuelgollob 
Thanks for reporting this. We can always extend the exporter to support a new op.
What is the source repo for this model? Could you maybe replace this operator in model code?

**Comment by emanuelgollob** [comment]
Hi @neginraoof 
The model source repo is https://github.com/NVlabs/stylegan2-ada-pytorch
Yes, one way could be to replace this operator in model code. Still thinking ahead it could be great to have ONNX to support this operator as well. How difficult is it to add a new op?

**Comment by neginraoof** [comment]
Thanks, yeah we should be able to add the symbolic easily. 
I'll send a PR today.

**Comment by neginraoof** [comment]
@emanuelgollob I can confirm that square has been added to the exporter about 7 months back: https://github.com/pytorch/pytorch/commit/aeefe2ce31cac554d48de1372eb426dcf4a3a301

Which version of torch are you using? Can you use the latest stable build?

**Comment by emanuelgollob** [comment]
@neginraoof I was using PyTorch 1.7.1 as the Stylegan2-ada-pytorch demands PyTorch 1.7.1
But in that case, I will try to load and export the trained model in PyTorch 1.9.0 
Thank you so much for looking into it!
