### ISSUE TITLE
ONNX export fails for trivial torch.autograd.Function

### ISSUE THREAD

**Issue by piotrm-nvidia** [pytorch/pytorch#61813]
## ONNX export fails for trivial torch.autograd.Function

The torch.autograd.Function is very useful solution for training GPT3-like models with multi-GPU code.

It was used in very efficient implementation of transformer training developed by NVIDIA:
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/mpu/random.py#L319

The PyTorch ONNX trace can't correctly interpret simple usage of this function like this:
```
return CheckpointFunction.apply(function, *args)
```
It generates error for unknown Checkpoint.Function Python operator:
```
RuntimeError: ONNX export failed: Couldn't export Python operator CheckpointFunction
```

## To Reproduce

```python
import torch

class CheckpointFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, run_function, *args):
        return run_function(*args)

def checkpoint(function, *args):
    return CheckpointFunction.apply(function, *args)

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
  
    def forward(self, input):
        def custom_forward(*inputs):
            x_ = inputs[0]
            return x_

        return checkpoint(custom_forward, input)

  
model = Net()
input = torch.zeros(2)
output = model(input, )
print(output)

with torch.no_grad():
    torch.onnx.export(model, (input, ), './check.onnx',)

```

The output from script:

```
Traceback (most recent call last):
  File "./apply_onnx.py", line 35, in <module>
    output = model(input, )
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "./apply_onnx.py", line 27, in forward
    return checkpoint(custom_forward, input)
  File "./apply_onnx.py", line 16, in checkpoint
    return CheckpointFunction.apply(function, *args)
AttributeError: type object 'CheckpointFunction' has no attribute 'apply'
root@nvdl-bsg-intel01:/mnt/nvdl/usr/piotrm/src/pytorch_multi_node# vim apply_onnx.py
root@nvdl-bsg-intel01:/mnt/nvdl/usr/piotrm/src/pytorch_multi_node# python3 ./apply_onnx.py
tensor([0., 0.])
Traceback (most recent call last):
  File "./apply_onnx.py", line 36, in <module>
    torch.onnx.export(model, (input, ), './check.onnx',)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 690, in _export
    proto, export_map = graph._export_onnx(
RuntimeError: ONNX export failed: Couldn't export Python operator CheckpointFunction

Defined at:
./apply_onnx.py(12): checkpoint
./apply_onnx.py(23): forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(1051): _call_impl
/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py(118): wrapper
/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py(127): forward
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py(1051): _call_impl
/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py(1160): _get_trace_graph
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py(373): _trace_and_get_graph_from_model
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py(409): _create_jit_graph
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py(445): _model_to_graph
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py(676): _export
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py(88): export
/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py(271): export
./apply_onnx.py(36): <module>


Graph we tried to export:
graph(%input : Float(2, strides=[1], requires_grad=0, device=cpu)):
  %1 : Float(2, strides=[1], requires_grad=0, device=cpu) = ^CheckpointFunction(<function Net.forward.<locals>.custom_forward at 0x7f75e83ebdc0>)(%input) # ./apply_onnx.py:12:0
  return (%1)

```

## Expected behavior

Trivial model with one input/output should be generated by ONNX trace.

## Environment

```
PyTorch version: 1.9.0a0+c3d40fd
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.20.4
Libc version: glibc-2.31

Python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-121-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA Graphics Device
Nvidia driver version: 470.42.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] nvidia-dlprof-pytorch-nvtx==1.2.0
[pip3] pytorch-quantization==2.1.0
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.9.0a0+c3d40fd
[pip3] torchtext==0.10.0a0
[pip3] torchvision==0.10.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.20.3           py38h9894fe3_1    conda-forge
[conda] nvidia-dlprof-pytorch-nvtx 1.2.0                    pypi_0    pypi
[conda] pytorch-quantization      2.1.0                    pypi_0    pypi
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.9.0a0+c3d40fd          pypi_0    pypi
[conda] torchtext                 0.10.0a0                 pypi_0    pypi
[conda] torchvision               0.10.0a0                 pypi_0    pypi

```

## Additional context

cc @BowenBao @neginraoof

**Comment by neginraoof** [comment]
@piotrm-nvidia I don't think the exporter supports the autograd functions out of the box. But you can define an export subgraph using a "symbolic" function and it'll be used by the exporter.
Can you check if this doc would help? https://pytorch.org/docs/master/onnx.html#torch-autograd-functions

**Comment by piotrm-nvidia** [comment]
It is obvious that one can just do TRIVIAL thing inside class Net directly and don't use CheckpointFunction at all. It is not the point here.

What is the issue here is that this trivial scenario is not handled by export and requires redesign of a model to just satisfy limitations of ONNX exporter. It renders export very impractical for any complex model like GPT3 in Megatron from NVIDIA repository:
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/mpu/random.py#L319

**Comment by neginraoof** [comment]
Again, you can use the CheckpointFunction class and you can export it if you define a symbolic to that class.
You can find the documentation on exporting autograd functions here : https://pytorch.org/docs/master/onnx.html#torch-autograd-functions. Please try the example for exporting autograd functions and let us know if any other questions.

**Comment by garymm** [comment]
I believe @shubhambhokare1 is working on something that will fix this.
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1096979>

For now the custom symbolic function solution mentioned above is the only way to make this work.
