### ISSUE TITLE
Can not load model from BytesIO

### ISSUE THREAD

**Issue by BIGBALLON** [pytorch/pytorch#61817]
## To Reproduce

1 download the official resnet18 mode(`resnet18-5c106cde.pth`)，**I make sure ``torch.load('resnet18-5c106cde.pth')`` is work fine.**
2 test the following code:

``` python
import io
import torch
with open('resnet18-5c106cde.pth', 'rb') as f:
    buffer = io.BytesIO(f.read())
torch.load(buffer)
```

3 got the following error:

``` bash
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    torch.load(buffer)
  File "/mnt/test/miniconda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/mnt/test/miniconda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

```

## Environment

- [pip3] numpy==1.20.3
- [pip3] torch==1.7.0
- [pip3] torchvision==0.8.1
- [conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- [conda] cudatoolkit               10.1.243             h6bb024c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
- [conda] mkl                       2021.2.0           h06a4308_296    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- [conda] mkl-service               2.3.0            py37h27cfd23_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- [conda] mkl_fft                   1.3.0            py37h42c9631_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- [conda] mkl_random                1.2.1            py37ha9443f7_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- [conda] numpy                     1.20.3                   pypi_0    pypi
- [conda] pytorch                   1.7.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
- [conda] torchvision               0.8.1                py37_cu101    pytorch

## Additional context

1. I also test with pytorch1.8.1/pytorch1.5.1, got the same error.
2. Both Mac OS and Linux has the same issue.
3. https://github.com/pytorch/pytorch/issues/31615

**Comment by BIGBALLON** [comment]
This issue was fixed in https://github.com/pytorch/vision/issues/2068
