### ISSUE TITLE
[cuda 5.0] windows binaries somewhere ?

### ISSUE THREAD

**Issue by kpoman** [pytorch/pytorch#6183]
I am wondering if someone could post or point to where to get PyTorch Windows binaries supporting cuda 5.0. I do have a "not so old" Quadro M1000M (from a Thinkpad P50 bought less that 2 years ago!!!). I am not skilled enough to build on windows, so I was wondering if someone already did that and can post the binaries.
Thank you a lot

**Comment by peterjc123** [comment]
There're unofficial CI packages available [here](https://github.com/peterjc123/pytorch-scripts). But the binary files are not bundled so you may have to install the dependencies by yourself.

**Comment by apaszke** [comment]
We dont have official binaries for Windows yet. 0.4 is the first version we will be packaging and should be released fairly soon

**Comment by kpoman** [comment]
@peterjc123 mine environment would be cp36, win10 64 bits and a maxwell (quadro m1000m). I checked this CI build which look to succeed: Environment: APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2017, PYTHON_VERSION=3.6, TORCH_CUDA_ARCH_LIST=Maxwell
I do have Visual Studio Community 2015, is there a problem with that env ?

**Comment by peterjc123** [comment]
@kpoman No problem. It is only a sign for the build system.

**Comment by kpoman** [comment]
@peterjc123 ok it seemed to work:
`(base) C:\Users\kpoman\conda_mnist>python -c "import torch; from torch.autograd import Variable; print(torch.cuda.is_available()); print(Variable(torch.randn(3, 1, 2).float().cuda(), requires_grad=True));"
True
C:\Anaconda3\lib\site-packages\torch\cuda\__init__.py:116: UserWarning:
    Found GPU0 Quadro M1000M which is of cuda capability 5.0.
    PyTorch no longer supports this GPU because it is too old.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Variable containing:
(0 ,.,.) =
 -0.0707 -0.4637

(1 ,.,.) =
  1.7680 -1.3497

(2 ,.,.) =
  0.0431 -1.2016
[torch.cuda.FloatTensor of size 3x1x2 (GPU 0)]


(base) C:\Users\kpoman\conda_mnist>`

However it seems there are some issues with DataLoaders as per the output of this sample script:
`
(base) C:\Users\kpoman\conda_mnist>python main.py
C:\Anaconda3\lib\site-packages\torch\cuda\__init__.py:116: UserWarning:
    Found GPU0 Quadro M1000M which is of cuda capability 5.0.
    PyTorch no longer supports this GPU because it is too old.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
C:\Anaconda3\lib\site-packages\torch\cuda\__init__.py:116: UserWarning:
    Found GPU0 Quadro M1000M which is of cuda capability 5.0.
    PyTorch no longer supports this GPU because it is too old.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kpoman\conda_mnist\main.py", line 112, in <module>
    train(epoch)
  File "C:\Users\kpoman\conda_mnist\main.py", line 78, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "C:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "C:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 234, in __init__
    w.start()
  File "C:\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
`

**Comment by kpoman** [comment]
@peterjc123 sorry, my post was not very specific. See here:

# this code is executed
import torch
from torchvision import datasets, transforms

use_cuda = True
batch_size = 64

kwargs = {'num_workers': 1, 'pin_memory': True} if use_cuda else {}
train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=batch_size, shuffle=True, **kwargs)

for batch_idx, (data, target) in enumerate(train_loader):
    print(batch_idx)




# and this is the result on the console (it even hangs the python process that I need to kill with task manager)
(base) C:\Users\kpoman\conda_mnist>python test.py
C:\Anaconda3\lib\site-packages\torch\cuda\__init__.py:116: UserWarning:
    Found GPU0 Quadro M1000M which is of cuda capability 5.0.
    PyTorch no longer supports this GPU because it is too old.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
C:\Anaconda3\lib\site-packages\torch\cuda\__init__.py:116: UserWarning:
    Found GPU0 Quadro M1000M which is of cuda capability 5.0.
    PyTorch no longer supports this GPU because it is too old.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kpoman\conda_mnist\test.py", line 16, in <module>
    for batch_idx, (data, target) in enumerate(train_loader):
  File "C:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "C:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 234, in __init__
    w.start()
  File "C:\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

(base) C:\Users\kpoman\conda_mnist>

**Comment by kpoman** [comment]
Oh @peterjc123 I understood. I put a if name main and it worked. Weird. The example works on linux without it. Wtf ...
