### ISSUE TITLE
load  pretrained vgg11 model error

### ISSUE THREAD

**Issue by NewRegin** [pytorch/pytorch#6184]
env:
-Pytorch
-Pytorch version:0.4.0a0+2a4b33b(installed from conda)
-Python 3.6.4
-CUDA
-GPU-Nvidia P100
-GCC:gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
-torchvision(installed from master)

error descripes:
When exec:
models.vgg11(pretrained=True), Then:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lzh3/anaconda3/lib/python3.6/site-packages/torchvision/models/vgg.py", line 124, in vgg13
    model.load_state_dict(model_zoo.load_url(model_urls['vgg13']))
  File "/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 66, in load_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 470, in _load
    result = unpickler.load()
  File "/home/lzh3/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 79, in __setstate__
    self.requires_grad, _, self._backward_hooks = state
ValueError: too many values to unpack (expected 3)

I find the len(state) is 4, and state is:
([0,0...][torch.FloatStorage of size 1728], 0, (64, 3, 3, 3), (27, 9, 3, 1)))

**Comment by NewRegin** [comment]
Thanks
