### ISSUE TITLE
Error in quicklint

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#61917]
I ran `make quicklint -j 20` and got the following error:
```
x shellcheck: Regenerate workflows
Traceback (most recent call last):
  File ".github/scripts/generate_ci_workflows.py", line 292, in <module>
    (jinja_env.get_template("linux_ci_workflow.yml.j2"), LINUX_WORKFLOWS),
  File "/private/home/suo/.conda/envs/py3/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/private/home/suo/.conda/envs/py3/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/private/home/suo/.conda/envs/py3/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/private/home/suo/.conda/envs/py3/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/private/home/suo/.conda/envs/py3/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/private/home/suo/.conda/envs/py3/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/raid/suo/pytorch/.github/templates/linux_ci_workflow.yml.j2", line 110, in template
    {% block build +%}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '+'
```

I was on 593e8f41cae82a279a323510dfcf1da6466ad5c9

**Comment by suo** [comment]
cc @driazati maybe?

**Comment by driazati** [comment]
What's your `pip list | grep -i jinja2`? I have `3.0.0` and it processes that line with no issues

**Comment by suo** [comment]
```
Jinja2                2.11.3
```
Upgrading `jinja2` fixes it! Thanks :)

**Comment by ejguan** [comment]
Closing the issue as it has been solved. Feel free to re-open if needed.
