### ISSUE TITLE
Vulkan error -5 when trying to use it

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#61951]
## 🐛 Bug

When attempting to use Vulkan backend, it failed with error -5 (VK_ERROR_MEMORY_MAP_FAILED)

## To Reproduce

$ python3 -c 'import torch; x = torch.randn(1,3,112,112); x = x.to("vulkan")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: VkResult:-5

Also, my original image I had attempted failed with -2 (VK_ERROR_OUT_OF_DEVICE_MEMORY) even though the size did not seem unreasonable.

$ python3 -c 'import torch; x = torch.randn(8,3,1024,768); x = x.to("vulkan")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: VkResult:-2

## Expected behavior

It works, I suppose.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0a0+gitdb11619
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python3 setup.py develop
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: Titan V
 - Any other relevant information: Used nvidia vulkan

**Comment by SS-JIA** [comment]
As a sanity check, are you able to run other Vulkan programs on your machine? For example the Vulkan samples: https://github.com/LunarG/VulkanSamples
