### ISSUE TITLE
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:70

### ISSUE THREAD

**Issue by ProGamerGov** [pytorch/pytorch#6198]
- PyTorch or Caffe2: PyTorch
- OS: Ubuntu: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1038-aws x86_64)
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): pip
- Python version: Python 2.7
- CUDA/cuDNN version: Cuda 9, cuDNN v7
- GPU models and configuration: Tesla K80
- GCC version (if compiling from source): N/A
- CMake version: cmake version 3.5.1
- Build command you used (if compiling from source): N/A
- Versions of any other relevant libraries: N/A

Running this script:
```
import torch
import torch.nn as nn

input = torch.randn(3,64,64).cuda()
print(input.size()) # Works
test = input[:, [1,-2], [1,-2]]
input = input.cpu() # Doesn't work.
```

Will result in this error message: 

```
(3L, 64L, 64L)
/pytorch/torch/lib/THC/THCTensorIndex.cu:417: long calculateOffset(IndexType, LinearIndexCalcData<IndexType, Dims>) [with IndexType = unsigned int, Dims = 3U]: block: [0,0,0], thread: [1,0,0] Assertion `indexAtDim < data.baseSizes[dim]` failed.
/pytorch/torch/lib/THC/THCTensorIndex.cu:417: long calculateOffset(IndexType, LinearIndexCalcData<IndexType, Dims>) [with IndexType = unsigned int, Dims = 3U]: block: [0,0,0], thread: [3,0,0] Assertion `indexAtDim < data.baseSizes[dim]` failed.
/pytorch/torch/lib/THC/THCTensorIndex.cu:417: long calculateOffset(IndexType, LinearIndexCalcData<IndexType, Dims>) [with IndexType = unsigned int, Dims = 3U]: block: [0,0,0], thread: [5,0,0] Assertion `indexAtDim < data.baseSizes[dim]` failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCTensorCopy.c line=70 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    input = input.cpu()
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 45, in cpu
    return self.type(getattr(torch, self.__class__.__name__))
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 396, in type
    return super(_CudaBase, self).type(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/_utils.py", line 38, in _type
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:70
```

And running this script: 

```
import torch
import torch.nn as nn

input = torch.randn(3,64,64).cuda()
print(input.size()) # Works
test = input[:, [1,-2], [1,-2]]
print(test) # Doesn't work
```

Will result in this error message: 

```
(3L, 64L, 64L)
/pytorch/torch/lib/THC/THCTensorIndex.cu:417: long calculateOffset(IndexType, LinearIndexCalcData<IndexType, Dims>) [with IndexType = unsigned int, Dims = 3U]: block: [0,0,0], thread: [1,0,0] Assertion `indexAtDim < data.baseSizes[dim]` failed.
/pytorch/torch/lib/THC/THCTensorIndex.cu:417: long calculateOffset(IndexType, LinearIndexCalcData<IndexType, Dims>) [with IndexType = unsigned int, Dims = 3U]: block: [0,0,0], thread: [3,0,0] Assertion `indexAtDim < data.baseSizes[dim]` failed.
/pytorch/torch/lib/THC/THCTensorIndex.cu:417: long calculateOffset(IndexType, LinearIndexCalcData<IndexType, Dims>) [with IndexType = unsigned int, Dims = 3U]: block: [0,0,0], thread: [5,0,0] Assertion `indexAtDim < data.baseSizes[dim]` failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCTensorCopy.c line=70 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    print(test)
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 154, in __str__
    return _tensor_str._str(self).encode(
  File "/usr/local/lib/python2.7/dist-packages/torch/_tensor_str.py", line 297, in _str
    strt = _matrix_str(self)
  File "/usr/local/lib/python2.7/dist-packages/torch/_tensor_str.py", line 216, in _matrix_str
    min_sz=5 if not print_full_mat else 0)
  File "/usr/local/lib/python2.7/dist-packages/torch/_tensor_str.py", line 79, in _number_format
    tensor = torch.DoubleTensor(tensor.size()).copy_(tensor).abs_().view(tensor.nelement())
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:70
```

**Comment by ProGamerGov** [comment]
Using `.cpu()` instead of `.cuda()`: 

```
import torch
import torch.nn as nn

input = torch.randn(3,64,64).cpu() #.cuda()
print(input.size()) # Works
test = input[:, [1,-2], [1,-2]]
print(test)
```

Results in: 


```
(3L, 64L, 64L)
Traceback (most recent call last):
  File "t.py", line 6, in <module>
    test = input[:, [1,-2], [1,-2]]
RuntimeError: index out of range at /pytorch/torch/lib/TH/generic/THTensorMath.c:277
```

**Comment by soumith** [comment]
we dont support negative indices, and that's the reflection of the error.

**Comment by ProGamerGov** [comment]
@soumith Is there any way to work with negative indices at the moment, like in Torch7?


```
th> input = torch.randn(3,64,64)
                                                                      [0.0023s]
th> test = input[{{}, {1, -2}, {1, -2}}]
                                                                      [0.0001s]
th> print(test) -- Works
```
