### ISSUE TITLE
torchelastic Failed with std::bad_alloc

### ISSUE THREAD

**Issue by Godricly** [pytorch/pytorch#62029]
## 🐛 Bug
I was trying to the same thing following this topic, but come across this error message. 
https://discuss.pytorch.org/t/api-alternative-for-torch-distributed-launch/122498/2

A simple demo script is provided to reproduce.
## To Reproduce

1. copy and save file.
2. change IP in script.
3. run demo.py in 2 server.
#### demo script
```python
import torch.distributed as dist
from torch.distributed.launcher.api import LaunchConfig, elastic_launch
import os
import torch

def main_func():
    while(1):
        print(torch.zeros(2).cuda(), int(os.environ["RANK"]))


def _distributed_worker(
    main_func,
    args,
):
    master_addr = os.environ["MASTER_ADDR"]
    master_port = os.environ["MASTER_PORT"]
    world_size = int(os.environ["WORLD_SIZE"])
    rank = int(os.environ["RANK"])
    machine_rank = int(os.environ["GROUP_RANK"])
    local_rank = int(os.environ["LOCAL_RANK"])

    print(rank, world_size)
    dist.init_process_group(
        backend='NCCL',
        world_size=world_size,
        rank=rank,
    )
    torch.cuda.set_device(local_rank)
    main_func(*args)


if __name__ == '__main__':
    num_gpus_per_machine = 4
    rdzv_endpoint = '192.168.0.100:12345'
    # change IP if needed.
    config = LaunchConfig(min_nodes=1, max_nodes=4,
                          nproc_per_node=num_gpus_per_machine,
                          rdzv_endpoint=rdzv_endpoint,
                          run_id='qwertyuiop',
                          rdzv_backend='c10d')
    args = ()
    outputs = elastic_launch(config, _distributed_worker)(main_func, args)
```
#### Error message
```
/python3env/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py:52: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
Exception in thread RendezvousKeepAliveTimer_0:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/utils.py", line 255, in _run
    ctx.function(*ctx.args, **ctx.kwargs)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1002, in _keep_alive_weak
    self._keep_alive()
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1012, in _keep_alive
    self._op_executor.run(op, deadline)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 546, in run
    has_set = self._state_holder.sync()
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 376, in sync
    get_response = self._backend.get_state()
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 63, in get_state
    base64_state: bytes = self._call_store("get", self._key)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 103, in _call_store
    return getattr(self._store, store_op)(*args, **kwargs)
MemoryError: std::bad_alloc
{"name": "torchelastic.worker.status.FAILED", "source": "AGENT", "timestamp": 0, "metadata": {"run_id": "qwertyuiop", "global_rank": null, "group_rank": 1, "worker_id": null, "role": "default_role", "hostname": "Server", "state": "FAILED", "total_run_time": 69, "rdzv_backend": "c10d", "raw_error": "Traceback (most recent call last):\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/launcher/api.py\", line 238, in launch_agent\n    result = agent.run()\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py\", line 700, in run\n    result = self._invoke_run(role)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py\", line 822, in _invoke_run\n    self._initialize_workers(self._worker_group)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py\", line 670, in _initialize_workers\n    self._rendezvous(worker_group)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py\", line 541, in _rendezvous\n    master_addr, master_port = self._get_master_addr_port(store)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py\", line 514, in _get_master_addr_port\n    master_addr = store.get(\"MASTER_ADDR\").decode(encoding=\"UTF-8\")\nRuntimeError: Stop_waiting response is expected\n", "metadata": "{\"group_world_size\": 3, \"entry_point\": \"_distributed_worker\"}", "agent_restarts": 0}}
The node 'Server_1667446_0' has failed to shutdown the rendezvous 'qwertyuiop' due to an error of type RendezvousConnectionError.
{
  "message": {
    "message": "RuntimeError: Stop_waiting response is expected",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 348, in wrapper\n    return f(*args, **kwargs)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/launcher/api.py\", line 238, in launch_agent\n    result = agent.run()\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py\", line 700, in run\n    result = self._invoke_run(role)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py\", line 822, in _invoke_run\n    self._initialize_workers(self._worker_group)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py\", line 670, in _initialize_workers\n    self._rendezvous(worker_group)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py\", line 541, in _rendezvous\n    master_addr, master_port = self._get_master_addr_port(store)\n  File \"/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py\", line 514, in _get_master_addr_port\n    master_addr = store.get(\"MASTER_ADDR\").decode(encoding=\"UTF-8\")\nRuntimeError: Stop_waiting response is expected\n",
      "timestamp": "1626962059"
    }
  }
}
Traceback (most recent call last):
  File "demo.py", line 41, in <module>
    outputs = elastic_launch(config, _distributed_worker)(main_func, args)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 238, in launch_agent
    result = agent.run()
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 700, in run
    result = self._invoke_run(role)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 822, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 670, in _initialize_workers
    self._rendezvous(worker_group)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 541, in _rendezvous
    master_addr, master_port = self._get_master_addr_port(store)
  File "/python3env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 514, in _get_master_addr_port
    master_addr = store.get("MASTER_ADDR").decode(encoding="UTF-8")
RuntimeError: Stop_waiting response is expected
```
## Expected behavior

slave node failed  with similiar log.

## Environment

Collecting environment information...
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-65-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090
GPU 2: GeForce RTX 3090
GPU 3: GeForce RTX 3090

Nvidia driver version: 460.84
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] torch==1.9.0+cu111
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0+cu111
[conda] Could not collect

**Comment by Godricly** [comment]
Could anyone take a look at this？
