### ISSUE TITLE
[ppc64le] FAIL: test_tan (test_torch.TestTorch) PyTorch

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#6206]
I'm wondering if the precision for the assert just needs to be adjusted on this test.   It happens on Ubuntu 16.04 (on docker container) but not on RedHat 7.4 (baremetal)

I'm getting:
FAIL: test_tan (test_torch.TestTorch)
Traceback (most recent call last):
  File "/home/jenkins/pytorch_builder/pytorch/test/test_torch.py", line 299, in test_tan
    self._testMathByName('tan')
  File "/home/jenkins/pytorch_builder/pytorch/test/test_torch.py", line 262, in _testMathByName
    self._testMath(torchfn, mathfn)
  File "/home/jenkins/pytorch_builder/pytorch/test/test_torch.py", line 257, in _testMath
    _testMathSize((10, 50000), self, torchfn, mathfn, torch.float, precs[1])
  File "/home/jenkins/pytorch_builder/pytorch/test/test_torch.py", line 242, in _testMathSize
    self.assertEqual(res1, res2, prec)
  File "/home/jenkins/pytorch_builder/pytorch/test/common.py", line 253, in assertEqual
    assertTensorsEqual(x, y)
  File "/home/jenkins/pytorch_builder/pytorch/test/common.py", line 245, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError:
1.00000e-04 *
  9.7656
[torch.FloatTensor of size ()]
 not less than or equal to 0.0001 :

- OS: Ubuntu  16.04 (on Docker)
- PyTorch version: (0.4.0a0+4c81282)
- How you installed PyTorch (conda, pip, source):
- Python version: conda 3.6.2
- CUDA/cuDNN version:   cuda 8/ cudnn 6

**Comment by avmgithub** [comment]
I'm closing this.  It may have been fixed by #6200. This is now passing
