### ISSUE TITLE
NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled cuda error, NCCL version 2.7.8

### ISSUE THREAD

**Issue by Arrebol2020** [pytorch/pytorch#62316]
## Environment
Ubuntu 18.04
GeForce RTX 3090
torch  1.7.1+cu110  
torchvision  0.8.2+cu110 

## Full error info
> Traceback (most recent call last):
  File "/home/sevati/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sevati/anaconda3/envs/cosypose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sevati/projects/6D-Pose/cosypose/cosypose/scripts/example_multigpu.py", line 9, in <module>
    init_distributed_mode()
  File "/home/sevati/projects/6D-Pose/cosypose/cosypose/utils/distributed.py", line 69, in init_distributed_mode
    init_method=f'file://{initfile.as_posix()}'
  File "/home/sevati/anaconda3/envs/cosypose/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/sevati/anaconda3/envs/cosypose/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled cuda error, NCCL version 2.7.8
Setting OMP and MKL num threads to 1.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by H-Huang** [comment]
@Arrebol2020 do you have a script we could run locally to reproduce this error?

**Comment by Arrebol2020** [comment]
@H-Huang I‘m so sorry for my delays in replying to you. I'm a beginner of Pytorch, recently I want to use someone's code to train a model, then I got this error. 

But when I wrote a simple code with torch.distributed to train a model on MNIST, this error didn't occur.
So maybe I need to checkout his code.

Thank you for your reply.
Have a nice day!

**Comment by H-Huang** [comment]
Feel free to reopen if you hit the issue again
