### ISSUE TITLE
[jit]][script] handling of 'void' returns

### ISSUE THREAD

**Issue by YuantianGao** [pytorch/pytorch#62325]
Hello, I want to optimise a model but I meet the error:

```
Traceback (most recent call last):
  File "mobile_test.py", line 129, in <module>
    data_loader,bn_list[0],net_config))
  File "mobile_test.py", line 62, in prepare_subnet
    script_subnet = torch.jit.script(subnet)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/_script.py", line 943, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 391, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 448, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/_script.py", line 391, in _construct
    init_fn(script_module)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 428, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 404, in create_script_module_impl
    property_stubs = get_property_stubs(nn_module)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 697, in get_property_stubs
    properties_asts = get_class_properties(module_ty, self_name="RecursiveScriptModule")
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 153, in get_class_properties
    getter = get_jit_def(prop[1].fget, f"__{prop[0]}_getter", self_name=self_name)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 271, in get_jit_def
    return build_def(ctx, fn_def, type_line, def_name, self_name=self_name)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 305, in build_def
    build_stmts(ctx, body))
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 129, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 129, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 279, in __call__
    return method(ctx, node)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 445, in build_Return
    return Return(r, None if stmt.value is None else build_expr(ctx, stmt.value))
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 279, in __call__
    return method(ctx, node)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 781, in build_Dict
    return DictLiteral(range, [build_expr(ctx, e) for e in expr.keys],
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 781, in <listcomp>
    return DictLiteral(range, [build_expr(ctx, e) for e in expr.keys],
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 278, in __call__
    raise UnsupportedNodeError(ctx, node)
  File "/home/yuantian/.local/lib/python3.6/site-packages/torch/jit/frontend.py", line 111, in __init__
    source_range = ctx.make_range(offending_node.lineno,
AttributeError: 'NoneType' object has no attribute 'lineno'
```
And this is my code:
```
#quantize model
subnet.qconfig = torch.quantization.default_qconfig
subnet.qconfig = torch.quantization.get_default_qconfig('qnnpack')
torch.backends.quantized.engine = 'qnnpack'
torch.quantization.prepare(subnet, inplace=True)
# Calibrate 
torch.quantization.convert(subnet, inplace=True)
print(subnet)
print(type(subnet))
#optimize
script_subnet = torch.jit.script(subnet)
script_subnet_optimized = optimize_for_model(script_model)
```
And how to solve this problem? @zdevito @apaszke
Kind regards.

**Comment by ansley** [comment]
@YuantianGao  Could you please provide a runnable example? I can see where the error is occurring, but I can't ensure that my fix would be correct without being able to reproduce the issue.

**Comment by YuantianGao** [comment]
@ansley Thanks so much for reply, I think my model's lack something, if I change the model to `subnet = torchvision.models.resnet50(pretrained=True)` It can run successfully, but it had error when I use OFA model: 
> https://github.com/UoS-EEC/DynamicOFA
Therefore, do you know which part of my model lack?
Kind regards.

**Comment by ansley** [comment]
@YuantianGao That's really good info, thanks! Could you please link a fully runnable example? It should be something that I can simply copy onto my machine and run to see the same error that you're seeing.

**Comment by YuantianGao** [comment]
Sorry, the image database is too large, about 6G, is it ok running on your machine?

**Comment by YuantianGao** [comment]
https://github.com/YuantianGao/Mobile-DynamicOFA-test

@ansley Thanks so much again, and you can run the test1.py file. I modify code that you can run without the database, because it's too large, about 6G. And the file named mobile_test.py is the original file.

**Comment by ansley** [comment]
@YuantianGao Hey, sorry to keep asking this, but what you sent me doesn't run. I fixed the syntax errors in `test1.py` myself and I've been working on adding the necessary auxiliary files to the folder, but I'm not sure I'm adding the same ones that you added. Please change the repo you linked so that it can be run by itself. Thank you for understanding!

**Comment by YuantianGao** [comment]
@ansley So sorry about that. I have updated test1.py file, and it would run a same error as I said. And thanks for the reply.
Kind regards.

**Comment by YuantianGao** [comment]
@ansley  I am so sorry that github's upload function may has problems, and you can download files here: https://drive.google.com/drive/folders/172QoQxYoB1fUPvwjudHWgBmRv-IfE8Mg?usp=sharing
So sorry again.
Kind regards.

**Comment by YuantianGao** [comment]
@ansley  Dear ansely, can you help me? Do you know why my model can not be received by the script function?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
