### ISSUE TITLE
cannot divide a Variable by its sum

### ISSUE THREAD

**Issue by davidenitti** [pytorch/pytorch#624]
Dear,
give the code:
```
a=Variable(torch.randn(5, 5))
b=a.sum()
c=a/b
```
I have the error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/torch/autograd/variable.py", line 716, in __div__
    return self.div(other)
  File "/usr/local/lib/python3.6/site-packages/torch/autograd/variable.py", line 318, in div
    return Div()(self, other)
  File "/usr/local/lib/python3.6/site-packages/torch/autograd/_functions/basic_ops.py", line 47, in forward
    return a.div(b)
RuntimeError: inconsistent tensor size at /home/soumith/local/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:657

with tensors this does not happen. This works fine:
```
a=torch.randn(5, 5)
b=a.sum()
c=a/b
```

**Comment by apaszke** [comment]
Yes, this is expected. Some operations on tensors like summing all numbers, taking their mean, max, min, indexing a 1D tensor will give you a Python number, while Variables will always repackage such number is a Variable. This will work:

```python
a = torch.randn(5, 5)
b = a.sum()
c = a / b.unsqueeze(0).expand_as(a)
```
