### ISSUE TITLE
undefined symbol: GOMP_parallel

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#625]
I get this error when I import torch:

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guismay/anaconda2/lib/python2.7/site-packages/torch/__init__.py", line 45, in <module>
    from torch._C import *
ImportError: /home/guismay/anaconda2/lib/python2.7/site-packages/torch/lib/libTH.so.1: undefined symbol: GOMP_parallel
```

But somehow, I don't have it I `import numpy` before.

**Comment by apaszke** [comment]
What's kind of system is that and how did you install pytorch?

**Comment by glample** [comment]
It's CentOS, and I installed from source.
