### ISSUE TITLE
Installation with pip/rocm fails

### ISSUE THREAD

**Issue by apalazzi** [pytorch/pytorch#62538]
## 🐛 Bug

Installation following the instructions for pytorch stable (1.9.0)/Linux/pip/Rocm4.2 here https://pytorch.org/get-started/locally/ fails with a linker error.

## To Reproduce
```
andrea@marcopolo:~$ pip3 install torch -f https://download.pytorch.org/whl/rocm4.2/torch_stable.html
andrea@marcopolo:~$ pip3 install ninja && pip3 install 'git+https://github.com/pytorch/vision.git@v0.10.0'
[...]
    /usr/bin/ld: /tmp/pip-req-build-q4wip4fv/build/temp.linux-x86_64-3.9/tmp/pip-req-build-q4wip4fv/torchvision/csrc/vision_hip.o: in function `c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<long (*)(), long, c10::guts::typelist::typelist<> >::operator()()':
    /home/andrea/.local/lib/python3.9/site-packages/torch/include/ATen/core/function_schema.h:132: multiple definition of  'vision::cuda_version()'; /tmp/pip-req-build-q4wip4fv/build/temp.linux-x86_64-3.9/tmp/pip-req-build-q4wip4fv/torchvision/csrc/vision.o:/home/andrea/.local/lib/python3.9/site-packages/torch/include/ATen/core/function_schema.h:132: first defined here
    collect2: error: ld returned 1 exit status
    error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-q4wip4fv/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-q4wip4fv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qdtge0qc/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/andrea/.local/include/python3.9/torchvision Check the logs for full command output.
```

## Expected behavior

Should build and install pytorch for Rocm

## Environment
```
andrea@marcopolo:~$ python3 collect_env.py 
Collecting environment information...
Traceback (most recent call last):
  File "/home/andrea/collect_env.py", line 480, in <module>
    main()
  File "/home/andrea/collect_env.py", line 463, in main
    output = get_pretty_env_info()
  File "/home/andrea/collect_env.py", line 458, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/home/andrea/collect_env.py", line 320, in get_env_info
    hip_runtime_version = [s.rsplit(None, 1)[-1] for s in cfg if 'HIP Runtime' in s][0]
IndexError: list index out of range

# For security purposes, please check the contents of collect_env.py before running it.
```
 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Linux Pop! OS 21.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): see above
 - Python version: 3.9.5
 - CUDA/cuDNN version: Rocm 4.2.0
 - GPU models and configuration: R9 290x

cc @ezyang @seemethere @malfet @walterddr @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by sunway513** [comment]
Hi @apalazzi , it seems the official document needs to be updated (cc @pruthvistony, @jithunnair-amd ), for PyTorch 1.9.0 release there is a torchvision WHL package available. The following command would install:
```
pip3 install torch -f https://download.pytorch.org/whl/rocm4.2/torch_stable.html
pip3 install torchvision==0.10.0 -f https://download.pytorch.org/whl/rocm4.2/torch_stable.html
```
However, I’d like to point out that your GPU (R9 290x) is not supported by ROCm. 
You can refer to the following document for the list of ROCm4.2 supported GPUs:
https://github.com/RadeonOpenCompute/ROCm#supported-gpus
