### ISSUE TITLE
CUDA errors while dealing with complex tensors via fft module

### ISSUE THREAD

**Issue by HJ-harry** [pytorch/pytorch#62535]
## 🐛 Bug

When dealing with complex data, via ```torch.fft``` module, I am randomly getting ```RuntimeError: CUDA error```.

```
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:97: block: [6,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:97: block: [2,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "C:/Users/Harry/PycharmProjects/fastmri_regression/test_cuda_v2.py", line 72, in <module>
    est = model(img_abs)
  File "C:\Users\Harry\anaconda3\envs\fastmri\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Harry\PycharmProjects\fastmri_regression\models\unet.py", line 83, in forward
    output = layer(output)
  File "C:\Users\Harry\anaconda3\envs\fastmri\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Harry\PycharmProjects\fastmri_regression\models\unet.py", line 41, in forward
    return self.layers(tensor)
  File "C:\Users\Harry\anaconda3\envs\fastmri\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Harry\anaconda3\envs\fastmri\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\Harry\anaconda3\envs\fastmri\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Harry\anaconda3\envs\fastmri\lib\site-packages\torch\nn\modules\conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Harry\anaconda3\envs\fastmri\lib\site-packages\torch\nn\modules\conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Process finished with exit code 1
```

## To Reproduce

1. Get helper functions from [https://github.com/facebookresearch/fastMRI/blob/master/fastmri/fftc.py](https://github.com/facebookresearch/fastMRI/blob/master/fastmri/fftc.py)

2. Then run

```python
import torch
from torch import nn, optim
import numpy as np
from utils import fft2c_new, ifft2c_new, complex_abs

device = 'cuda:0'

model = nn.Conv2d(1, 1, kernel_size=(3, 3), padding=1).to(device)
Niter = 10000
optimizer = optim.Adam(model.parameters(), lr=1e-4)
loss_fn = nn.MSELoss(reduction='mean')

# Helper functions

def kspace_to_nchw(tensor):
    """
    Convert torch tensor in (Slice, Coil, Height, Width, Complex) 5D format to
    (N, C, H, W) 4D format for processing by 2D CNNs.
    """
    assert isinstance(tensor, torch.Tensor)
    assert tensor.dim() == 5
    s = tensor.shape
    assert s[-1] == 2
    tensor = tensor.permute(dims=(0, 1, 4, 2, 3)).reshape(shape=(s[0], 2 * s[1], s[2], s[3]))
    return tensor


def nchw_to_kspace(tensor):
    """
    Convert a torch tensor in (N, C, H, W) format to the (Slice, Coil, Height, Width, Complex) format.
    """
    assert isinstance(tensor, torch.Tensor)
    assert tensor.dim() == 4
    s = tensor.shape
    if tensor.shape[1] == 1:
        imag_tensor = torch.zeros(s, device=tensor.device)
        tensor = torch.cat((tensor, imag_tensor), dim=1)
        s = tensor.shape
    tensor = tensor.view(size=(s[0], s[1] // 2, 2, s[2], s[3])).permute(dims=(0, 1, 3, 4, 2))
    return tensor


def get_mask(img, size, acc_factor=8, device='cuda:0'):
    mux_in = size ** 2
    Nsamp = mux_in // acc_factor
    mask = torch.zeros_like(img, dtype=torch.float32, device=device)
    cov_factor = size * (1.5 / 128)
    mean = [size // 2, size // 2]
    cov = [[size * cov_factor, 0], [0, size * cov_factor]]
    samples = np.random.multivariate_normal(mean, cov, int(Nsamp))
    int_samples = samples.astype(int)
    mask[..., int_samples[:, 0], int_samples[:, 1]] = 1
    return mask

# Main script

for step, i in enumerate(range(Niter), start=1):
    optimizer.zero_grad()
    img = torch.randn([1, 1, 128, 128], device=device)
    target = torch.randn([1, 1, 128, 128], device=device)

    kspace = kspace_to_nchw(fft2c_new(nchw_to_kspace(img)))
    mask = get_mask(kspace, 128,
                    acc_factor=8,
                    device=device)
    # this is where the error stems from
    # u_kspace = torch.where(mask > 0., kspace, torch.tensor(0., dtype=torch.float32, device=device))
    u_kspace = kspace * mask
    img_complex = ifft2c_new(nchw_to_kspace(u_kspace))
    img_abs = complex_abs(img_complex)
    est = model(img_abs)
    loss = loss_fn(est, target)
    loss.backward()
    optimizer.step()
    # log
    print(f'step: {step}/{Niter}')
    print(f'loss: {loss.data}')
```

## Expected behavior

Before I updated the pytorch version to >1.7.0, where the new ```torch.fft``` module was introduced, I wasn't getting errors when running for example the reproducing scripts.

## Environment

PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19042-SP0
Is CUDA available: True
CUDA runtime version: 11.0.194
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.1               heb2d755_7    conda-forge
[conda] mkl                       2021.3.0           haa95532_524  
[conda] mkl-service               2.4.0            py38h2bbff1b_0  
[conda] mkl_fft                   1.3.0            py38h277e83a_2  
[conda] mkl_random                1.2.2            py38hf11a4ad_0  
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.20.3           py38hc2deb75_0  
[conda] pytorch                   1.9.0           py3.8_cuda11.1_cudnn8_0    pytorch
[conda] torchaudio                0.9.0                      py38    pytorch
[conda] torchvision               0.10.0               py38_cu111    pytorch

**Comment by mruberry** [comment]
@peterbell10 -- would you see if you can reproduce this?

**Comment by peterbell10** [comment]
There is a bug in your code:
```python
samples = np.random.multivariate_normal(mean, cov, int(Nsamp))
int_samples = samples.astype(int)
mask[..., int_samples[:, 0], int_samples[:, 1]] = 1
```

`multivariate_normal` doesn't have an upper or lower bound, so what's to say the indices will be in bounds? A quick fix is
```python
int_samples = np.clip(int_samples, 0, size - 1)
```
and the assert no longer triggers. This will skew your distribution though, so you probably want to do something else.
