### ISSUE TITLE
FAIL: test_threshold (test_jit_fuser.TestFuser)

### ISSUE THREAD

**Issue by HangJie720** [pytorch/pytorch#62543]
$ pytorch/test# python -m unittest test_jit_fuser.TestFuser.test_threshold
Couldn't download test skip set, leaving all tests enabled...
F
======================================================================
FAIL: test_threshold (test_jit_fuser.TestFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jhang/bi/hj/pytorch_ori_v1.8/test/test_jit_fuser.py", line 556, in test_threshold
    self.assertAllFused(scripted.graph_for(x))
  File "/home/jhang/bi/hj/pytorch_ori_v1.8/test/test_jit_fuser.py", line 49, in assertAllFused
    'got {}'.format(graph))
AssertionError: False is not true : got graph(%x.1 : Tensor):
  %26 : Double(6, strides=[1], requires_grad=0, device=cuda:0), %27 : bool = prim::TypeCheck[types=[Double(6, strides=[1], requires_grad=0, device=cuda:0)]](%x.1)
  %28 : Tensor = prim::If(%27)
    block0():
      %17 : Double(6, strides=[1], requires_grad=0, device=cuda:0) = prim::TensorExprGroup_0(%26)
      -> (%17)
    block1():
      %37 : Function = prim::Constant[name="fallback_function", fallback=1]()
      %38 : (Tensor) = prim::CallFunction(%37, %x.1)
      %39 : Tensor = prim::TupleUnpack(%38)
      -> (%39)
  return (%28)
with prim::TensorExprGroup_0 = graph(%1 : Double(6, strides=[1], requires_grad=0, device=cuda:0)):
  %8 : int = prim::Constant[value=1]()
  %11 : int = prim::Constant[value=-10]()
  %10 : int = prim::Constant[value=0]()
  %12 : Double(6, strides=[1], requires_grad=0, device=cuda:0) = aten::threshold(%1, %10, %11) # /home/jhang/bi/hj/pytorch_ori_v1.8/test/test_jit_fuser.py:552:19
  %9 : Double(6, strides=[1], requires_grad=0, device=cuda:0) = aten::add(%12, %1, %8) # /home/jhang/bi/hj/pytorch_ori_v1.8/test/test_jit_fuser.py:552:19
  %6 : Double(6, strides=[1], requires_grad=0, device=cuda:0) = aten::add(%9, %1, %8) # /home/jhang/bi/hj/pytorch_ori_v1.8/test/test_jit_fuser.py:552:19
  %3 : Double(6, strides=[1], requires_grad=0, device=cuda:0) = aten::add(%6, %1, %8) # /home/jhang/bi/hj/pytorch_ori_v1.8/test/test_jit_fuser.py:552:19
  return (%3)

----------------------------------------------------------------------
Ran 1 test in 4.262s

FAILED (failures=1)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ansley** [comment]
Could you please add some additional context? Thanks!

**Comment by HangJie720** [comment]
test_jit_fuser.py is in pytorch/test directory, you can execute "python test_jit_fuser.py" in NV platform.

**Comment by ansley** [comment]
Sorry, what do you mean by "NV platform"? The test passes on the master branch on my machine. Can you explain more about the environment you're using--e.g. what OS, what version of Python, etc.?

**Comment by HangJie720** [comment]
I install torch-1.8.1-cp36-cp36m-manylinux1_x86_64.whl in Ubuntu docker environment(cuda10.2) with GTX 1080.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
