### ISSUE TITLE
[Export onnx] Context: Bad node spec: output: "18" name: "Constant_8" op_type: "Constant" attribute 

### ISSUE THREAD

**Issue by guxuhong** [pytorch/pytorch#62568]
## To Reproduce

```python
# ...
# do something
# ...

torch.onnx.export(model, inputs, path,
                        opset_version=9,
                        example_outputs=None,
                        input_names=["X"], output_names=["Y"],
                        custom_opsets={"my_domain": 1},
                        verbose=False)
```

error
```
/root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/onnx/symbolic_opset9.py:2099: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  "or define the initial states (h0/c0) as inputs of the model. ")
graph(%X : Long(5, strides=[1], requires_grad=0, device=cpu),
      %hidden2tag.weight : Float(3, 6, strides=[6, 1], requires_grad=1, device=cpu),
      %hidden2tag.bias : Float(3, strides=[1], requires_grad=1, device=cpu),
      %120 : Long(1, strides=[1], requires_grad=0, device=cpu),
      %121 : Long(1, strides=[1], requires_grad=0, device=cpu),
      %122 : Long(1, strides=[1], requires_grad=0, device=cpu),
      %123 : Long(1, strides=[1], requires_grad=0, device=cpu),
      %124 : Long(1, strides=[1], requires_grad=0, device=cpu),
      %125 : Long(1, strides=[1], requires_grad=0, device=cpu),
      %126 : Long(1, strides=[1], requires_grad=0, device=cpu),
      %144 : Float(1, 24, 6, strides=[144, 6, 1], requires_grad=0, device=cpu),
      %145 : Float(1, 24, 6, strides=[144, 6, 1], requires_grad=0, device=cpu),
      %146 : Float(1, 48, strides=[48, 1], requires_grad=0, device=cpu),
      %147 : Long(1, strides=[1], requires_grad=0, device=cpu)):
  %8 : Long(1, strides=[1], device=cpu) = onnx::Shape(%X)
  %9 : Long(device=cpu) = onnx::Constant[value={0}]()
  %10 : Long(device=cpu) = onnx::Gather[axis=0](%8, %9) 
  %12 : Long(1, strides=[1], device=cpu) = onnx::Unsqueeze[axes=[0]](%10)
  %14 : Long(2, strides=[1], device=cpu) = onnx::Concat[axis=0](%12, %120)
  %15 : Float(5, 6, strides=[6, 1], requires_grad=0, device=cpu) = onnx::ConstantOfShape[value={0}](%14) 
  %16 : Long(2, strides=[1], device=cpu) = onnx::Shape(%15)
  %17 : Float(5, 6, strides=[6, 1], requires_grad=0, device=cpu) = onnx::ConstantOfShape[value={0}](%16) # /root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/nn/init.py:64:0
  %18 : Tensor = onnx::Constant[value="dynamic_embedding"]() 
  %19 : Tensor = onnx::Constant[value="UUID"]() 
  %20 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={6002}]()
  %21 : Float(5, 6, strides=[6, 1], requires_grad=0, device=cpu) = weps_domain::get_embed_op(%X, %17, %18, %19, %20) 
  %22 : Long(1, strides=[1], device=cpu) = onnx::Shape(%X)
  %23 : Long(device=cpu) = onnx::Constant[value={0}]()
  %24 : Long(device=cpu) = onnx::Gather[axis=0](%22, %23) # seq_model.py:73:0
  %27 : Long(1, strides=[1], device=cpu) = onnx::Unsqueeze[axes=[0]](%24)
  %30 : Long(3, strides=[1], device=cpu) = onnx::Concat[axis=0](%27, %121, %122)
  %31 : Float(5, 1, 6, strides=[6, 6, 1], requires_grad=1, device=cpu) = onnx::Reshape(%21, %30) # seq_model.py:73:0
  %32 : Long(3, strides=[1], device=cpu) = onnx::Shape(%31)
  %33 : Long(device=cpu) = onnx::Constant[value={1}]()
  %34 : Long(device=cpu) = onnx::Gather[axis=0](%32, %33) # /root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/nn/modules/rnn.py:658:0
  %38 : Long(1, strides=[1], device=cpu) = onnx::Unsqueeze[axes=[0]](%34)
  %40 : Long(3, strides=[1], device=cpu) = onnx::Concat[axis=0](%123, %38, %124)
  %41 : Float(1, 1, 6, strides=[6, 6, 1], requires_grad=0, device=cpu) = onnx::ConstantOfShape[value={0}](%40) # /root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/nn/modules/rnn.py:667:0
  %45 : Long(1, strides=[1], device=cpu) = onnx::Unsqueeze[axes=[0]](%34)
  %47 : Long(3, strides=[1], device=cpu) = onnx::Concat[axis=0](%125, %45, %126)
  %48 : Float(1, 1, 6, strides=[6, 6, 1], requires_grad=0, device=cpu) = onnx::ConstantOfShape[value={0}](%47) # /root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/nn/modules/rnn.py:670:0
  %49 : Tensor? = prim::Constant()
  %106 : Float(5, 1, 1, 6, strides=[6, 6, 6, 1], device=cpu), %107 : Float(1, 1, 6, strides=[6, 6, 1], requires_grad=1, device=cpu), %108 : Float(1, 1, 6, strides=[6, 6, 1], requires_grad=1, device=cpu) = onnx::LSTM[hidden_size=6](%31, %144, %145, %146, %49, %41, %48) # /root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/nn/modules/rnn.py:680:0
  %109 : Float(5, 1, 6, strides=[6, 6, 1], requires_grad=1, device=cpu) = onnx::Squeeze[axes=[1]](%106) # /root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/nn/modules/rnn.py:680:0
  %110 : Long(1, strides=[1], device=cpu) = onnx::Shape(%X)
  %111 : Long(device=cpu) = onnx::Constant[value={0}]()
  %112 : Long(device=cpu) = onnx::Gather[axis=0](%110, %111) # seq_model.py:74:0
  %114 : Long(1, strides=[1], device=cpu) = onnx::Unsqueeze[axes=[0]](%112)
  %116 : Long(2, strides=[1], device=cpu) = onnx::Concat[axis=0](%114, %147)
  %117 : Float(5, 6, strides=[6, 1], requires_grad=1, device=cpu) = onnx::Reshape(%109, %116) # seq_model.py:74:0
  %118 : Float(5, 3, strides=[3, 1], requires_grad=1, device=cpu) = onnx::Gemm[alpha=1., beta=1., transB=1](%117, %hidden2tag.weight, %hidden2tag.bias) # /root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/nn/functional.py:1847:0
  %Y : Float(5, 3, strides=[3, 1], requires_grad=1, device=cpu) = onnx::LogSoftmax[axis=1](%118) # /root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/nn/functional.py:1768:0
  return (%Y)

Traceback (most recent call last):
  File "seq_model.py", line 150, in <module>
    export_onnx()
  File "seq_model.py", line 146, in export_onnx
    verbose=True)
  File "/root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/root/.conda/envs/weint_onnx/lib/python3.6/site-packages/torch/onnx/utils.py", line 718, in _export
    _check_onnx_proto(proto)
RuntimeError: Mismatched attribute type in 'Constant_8 : value'

==> Context: Bad node spec: output: "18" name: "Constant_8" op_type: "Constant" attribute { name: "value" s: "dynamic_embedding" type: STRING }
(weint_onnx) [root@mmkvsvrtestmem2 /app/simple_model/sequence_model]# 


```

## Environment

```
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Tencent tlinux 2.2 (Final) (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.107-1-tlinux2-0050-x86_64-with-centos-7.2-Final
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.9.0
[pip3] torch-weps==0.0.1
[pip3] torchtext==0.10.0
[conda] Could not collect

```
## Additional context

cc @BowenBao @neginraoof

**Comment by guxuhong** [comment]
What should I do to fix it?

**Comment by jiafatom** [comment]
@guxuhong can you try latest opset, for example `opset_version=14`? Also you have a ` %21 : Float(5, 6, strides=[6, 1], requires_grad=0, device=cpu) = weps_domain::get_embed_op(%X, %17, %18, %19, %20) 
` which is not converted to ONNX operators. Could you share the small repro?

**Comment by garymm** [comment]
Closing due to lack of response from @guxuhong. If you still have a problem with the latest pytorch nightly and latest opset version, please open a new issue that includes enough model code for us to reproduce the issue.

**Comment by Carry955** [comment]
> Closing due to lack of response from @guxuhong. If you still have a problem with the latest pytorch nightly and latest opset version, please open a new issue that includes enough model code for us to reproduce the issue.

Thanks, You solved my problem
