### ISSUE TITLE
[ROCM]: Process termination logic #61602 sometimes ending in errors

### ISSUE THREAD

**Issue by arindamroy-eng** [pytorch/pytorch#62595]
## To Reproduce
Due to the merged PR:

https://github.com/pytorch/pytorch/pull/61602

Sometimes CI is throwing errors:

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.2-py3.6-test2/11061//console

17:46:33 /opt/conda/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/error_handler.py:68: UserWarning: Unable to enable fault handler. UnsupportedOperation: fileno
17:46:33   warnings.warn(f"Unable to enable fault handler. {type(e).__name__}: {e}")
17:46:33 Closing processes via signal 15
17:46:33 Unable to shutdown processes via 15, forcefully exitting via 9
17:46:33 ERROR (0.122s)
..................
17:46:33   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
17:46:33     raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
17:46:33 torch.distributed.elastic.multiprocessing.api.SignalException: Process 50911 got signal: 15

1.
1.
1.

## Expected behavior
The issue is not related to ROCM stack itself. Request the author of the PR to take a look.

@aivanou 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).
This is a ROCM CI Node:

15:21:04 Started by upstream project "pytorch-builds/pytorch-linux-bionic-rocm4.2-py3.6-trigger" build number 13268
15:21:04 originally caused by:
15:21:04  Started by upstream project "pytorch-master" build number 30211
15:21:04  originally caused by:
15:21:04   Started by GitHub push by facebook-github-bot
15:21:04 [EnvInject] - Loading node environment variables.
15:21:04 Building remotely on jenkins-worker-rocm-amd-34 (rocm docker) in workspace /var/lib/jenkins/workspace/pytorch-builds/pytorch-linux-bionic-rocm4.2-py3.6-test2

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by jithunnair-amd** [comment]
@aivanou it seems like the CUDA builds for that PR #61602 also get the same error eg: https://circleci.com/api/v1.1/project/github/pytorch/pytorch/14955592/output/107/0?file=true&allocation-id=60fa4781bdb86a2820fe7fa8-0-build%2F6FE0D62A

```Jul 23 04:50:20   test_function_large_ret_val (__main__.StartProcessesTest) ... /opt/conda/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/error_handler.py:68: UserWarning: Unable to enable fault handler. UnsupportedOperation: fileno
Jul 23 04:50:20   warnings.warn(f"Unable to enable fault handler. {type(e).__name__}: {e}")
Jul 23 04:50:20 /opt/conda/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/error_handler.py:68: UserWarning: Unable to enable fault handler. UnsupportedOperation: fileno
Jul 23 04:50:20   warnings.warn(f"Unable to enable fault handler. {type(e).__name__}: {e}")
Jul 23 04:50:20 /opt/conda/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/error_handler.py:68: UserWarning: Unable to enable fault handler. UnsupportedOperation: fileno
Jul 23 04:50:20   warnings.warn(f"Unable to enable fault handler. {type(e).__name__}: {e}")
Jul 23 04:50:20 /opt/conda/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/error_handler.py:68: UserWarning: Unable to enable fault handler. UnsupportedOperation: fileno
Jul 23 04:50:20   warnings.warn(f"Unable to enable fault handler. {type(e).__name__}: {e}")
Jul 23 04:50:20 Closing processes via signal 15
Jul 23 04:50:20 Unable to shutdown processes via 15, forcefully exitting via 9
```

Are the tests supposed to get these errors by design?

**Comment by jithunnair-amd** [comment]
However, there is one test that actually fails in the CI build log mentioned in the description:
```
17:46:37 ======================================================================
17:46:37 ERROR [2.020s]: test_multiprocess_context_close (__main__.StartProcessesTest)
17:46:37 ----------------------------------------------------------------------
17:46:37 Traceback (most recent call last):
17:46:37   File "distributed/elastic/multiprocessing/api_test.py", line 236, in tearDown
17:46:37     shutil.rmtree(self.test_dir)
17:46:37   File "/opt/conda/lib/python3.6/shutil.py", line 477, in rmtree
17:46:37     onerror(os.lstat, path, sys.exc_info())
17:46:37   File "/opt/conda/lib/python3.6/shutil.py", line 475, in rmtree
17:46:37     orig_st = os.lstat(path)
17:46:37 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/StartProcessesTest_u2apqell'
```
Does it indicate some sort of race condition?
