### ISSUE TITLE
[FX] Support pytree `concrete_args` for *args

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#62683]
Referenced in this issue: https://github.com/pytorch/pytorch/issues/60069

```
import torch
from torch import Tensor
import torch.nn as nn
import torch.fx as fx

class Module(nn.Module):
    def forward(self, x):
        return x

class Container(nn.Module):
    def __init__(self):
        super().__init__()
        self._module = Module()

    def forward(self, *args):
        return self._module(*args)

model = Container()
model(Tensor())

concrete_args = ((torch.fx.PH,),)
trace = fx.symbolic_trace(model, concrete_args=concrete_args)
"""
Traceback (most recent call last):
  File "/home/jamesreed/kwargs.py", line 22, in <module>
    trace = fx.symbolic_trace(model, concrete_args=concrete_args)
  File "/data/users/jamesreed/pytorch/torch/fx/_symbolic_trace.py", line 875, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/data/users/jamesreed/pytorch/torch/fx/_symbolic_trace.py", line 556, in trace
    fn, args = self.create_args_for_root(fn, isinstance(root, torch.nn.Module), concrete_args)
  File "/data/users/jamesreed/pytorch/torch/fx/_symbolic_trace.py", line 460, in create_args_for_root
    assert(len(arg_names) == len(concrete_args))
AssertionError

"""
```

It would be nice if we had some way of informing the system of the arity of `args` such that we can make it into a tuple of `Proxy` and further calls with the exploded form will work.

**Comment by byronyi** [comment]
A short repro for detectron2:

```
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg

cfg = get_cfg()
# add project-specific config (e.g., TensorMask) here if you're not running a model in detectron2's core library
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
# Find a model from detectron2's model zoo. You can use the https://dl.fbaipublicfiles... url as well
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.DEVICE = 'cpu'
predictor = DefaultPredictor(cfg)

import torch.fx

traced_model = torch.fx.symbolic_trace(predictor.model)
```

gives

```bash
File "/home/byronyi/.virtualenv/fx/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 907, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/home/byronyi/.virtualenv/fx/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 615, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/home/byronyi/.virtualenv/fx/lib/python3.9/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 146, in forward
    return self.inference(batched_inputs)
  File "/home/byronyi/.virtualenv/fx/lib/python3.9/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 199, in inference
    images = self.preprocess_image(batched_inputs)
  File "/home/byronyi/.virtualenv/fx/lib/python3.9/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 224, in preprocess_image
    images = [x["image"].to(self.device) for x in batched_inputs]
  File "/home/byronyi/.virtualenv/fx/lib/python3.9/site-packages/torch/fx/proxy.py", line 248, in __iter__
    return self.tracer.iter(self)
  File "/home/byronyi/.virtualenv/fx/lib/python3.9/site-packages/torch/fx/proxy.py", line 161, in iter
    raise TraceError('Proxy object cannot be iterated. This can be '
torch.fx.proxy.TraceError: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.fx docs on pytorch.org for a more detailed explanation of what types of control flow can be traced, and check out the Proxy docstring for help troubleshooting Proxy iteration errors
```

 cc @ppwwyyxx
