### ISSUE TITLE
Issue in loading of a saved pytorch model

### ISSUE THREAD

**Issue by t-naveenkumar** [pytorch/pytorch#62706]
## 🐛 Bug

loading of a saved pytorch model is failing if its been run through optimize_for_inference API. but loading of a saved frozen pytorch model is successful.

## To Reproduce

1. setup 
```
conda create -n pt19 python=3.8 -y
conda activate pt19
conda install pytorch torchvision torchaudio cpuonly -c pytorch

```
2. run code
```
import torch
import torchvision.models as models

inp = torch.randn(128, 3, 224, 224)
model = models.__dict__['resnet50'](pretrained=True).eval()
model = torch.jit.script(model)
model = torch.jit.optimize_for_inference(model)
out1 = model(inp)
model.save("resent50_model.pt")
loaded_mod = torch.jit.load("resent50_model.pt")
out2 = loaded_mod(inp)

```
3. issue/error message

```
Traceback (most recent call last):
  File "issue.py", line 10, in <module>
    loaded_mod = torch.jit.load("resent50_model.pt")
  File "/home/naveen/anaconda3/envs/pt19/lib/python3.8/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: required keyword attribute 'value' is undefined
```

## Expected behavior

load API should have run without any issues and inference using that loaded model should also be successful.

## Environment
output of:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
python collect_env.py
```
```
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.11 (default, Aug  3 2021, 15:09:35)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.8.0-63-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.20.3           py38hf144106_0  
[conda] numpy-base                1.20.3           py38h74d4b33_0  
[conda] pytorch                   1.9.0               py3.8_cpu_0  [cpuonly]  pytorch
[conda] torchaudio                0.9.0                      py38    pytorch
[conda] torchvision               0.10.0                 py38_cpu  [cpuonly]  pytorch
```
## Additional context

cc @gmagogsfm

**Comment by eellison** [comment]
This passes on master for me now.
