### ISSUE TITLE
CMake-based integration causes segfault on nightly build

### ISSUE THREAD

**Issue by mthrok** [pytorch/pytorch#62754]
## 🐛 Bug

torchaudio CI test jobs started to exhibit segfault since the morning of Wednesday August 4th.
https://app.circleci.com/pipelines/github/pytorch/audio/6876/workflows/63aa2db2-9588-4a95-b452-215f80869a8e

<details>
<summary>Logs</summary>

```
Collecting environment information...
PyTorch version: 1.10.0.dev20210804
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-1106-aws-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0.dev20210804
[pip3] torchaudio==0.10.0a0+17a3bbf
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch-nightly
[conda] libblas                   3.9.0                    10_mkl    conda-forge
[conda] libcblas                  3.9.0                    10_mkl    conda-forge
[conda] liblapack                 3.9.0                    10_mkl    conda-forge
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] numpy                     1.19.5           py36hfc0c790_2    conda-forge
[conda] pytorch                   1.10.0.dev20210804     py3.6_cpu_0  [cpuonly]  pytorch-nightly
[conda] torchaudio                0.10.0a0+17a3bbf          pypi_0    pypi
============================= test session starts ==============================
platform linux -- Python 3.6.13, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /root/project/env/bin/python
cachedir: .pytest_cache
rootdir: /root/project
plugins: cov-2.12.1, hydra-core-1.0.7
collecting ... 
collecting 2 items                                                             
collecting 1276 items                                                          
collecting 2705 items                                                          Fatal Python error: Aborted

Current thread 0x00007ff6cc3d9240 (most recent call first):
  File "/root/project/env/lib/python3.6/ctypes/__init__.py", line 348 in __init__
  File "/root/project/env/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 185 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "/root/project/env/lib/python3.6/site-packages/llvmlite/binding/dylib.py", line 3 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/root/project/env/lib/python3.6/site-packages/llvmlite/binding/__init__.py", line 4 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/root/project/env/lib/python3.6/site-packages/numba/core/config.py", line 16 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "/root/project/env/lib/python3.6/site-packages/numba/__init__.py", line 19 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/root/project/env/lib/python3.6/site-packages/librosa/util/utils.py", line 10 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/root/project/env/lib/python3.6/site-packages/librosa/util/__init__.py", line 83 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 941 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/root/project/env/lib/python3.6/site-packages/librosa/core/notation.py", line 8 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "/root/project/env/lib/python3.6/site-packages/librosa/core/convert.py", line 7 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/root/project/env/lib/python3.6/site-packages/librosa/core/__init__.py", line 5 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "/root/project/env/lib/python3.6/site-packages/librosa/__init__.py", line 211 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/root/project/test/torchaudio_unittest/functional/librosa_compatibility_test_impl.py", line 14 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/root/project/test/torchaudio_unittest/functional/librosa_compatibility_cpu_test.py", line 2 in <module>
  File "/root/project/env/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 170 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 994 in _gcd_import
  File "/root/project/env/lib/python3.6/importlib/__init__.py", line 126 in import_module
  File "/root/project/env/lib/python3.6/site-packages/_pytest/pathlib.py", line 524 in import_path
  File "/root/project/env/lib/python3.6/site-packages/_pytest/python.py", line 578 in _importtestmodule
  File "/root/project/env/lib/python3.6/site-packages/_pytest/python.py", line 500 in _getobj
  File "/root/project/env/lib/python3.6/site-packages/_pytest/python.py", line 291 in obj
  File "/root/project/env/lib/python3.6/site-packages/_pytest/python.py", line 516 in _inject_setup_module_fixture
  File "/root/project/env/lib/python3.6/site-packages/_pytest/python.py", line 503 in collect
  File "/root/project/env/lib/python3.6/site-packages/_pytest/runner.py", line 341 in <lambda>
  File "/root/project/env/lib/python3.6/site-packages/_pytest/runner.py", line 311 in from_call
  File "/root/project/env/lib/python3.6/site-packages/_pytest/runner.py", line 341 in pytest_make_collect_report
  ...
.circleci/unittest/linux/scripts/run_test.sh: line 26:  2953 Aborted                 (core dumped) pytest "${args[@]}" torchaudio_unittest

Exited with code exit status 134
```

</details>

I suspect that this might be due to something with the PyTorch nightly build.

## To Reproduce

1. Install PyTorch nightly (`conda install -y -c pytorch-nightly pytorch-nightly::pytorch`)
1. Build torchaudio (`BUILD_RNNT=1 BUILD_SOX=1 python setup.py install`)
1. Run test (`pytest torchaudio_unittest`)

from [install.sh](https://github.com/pytorch/audio/blob/main/.circleci/unittest/linux/scripts/install.sh)

## Expected behavior

segfault does not happen

## Environment

```
PyTorch version: 1.10.0.dev20210804
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-1106-aws-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0.dev20210804
[pip3] torchaudio==0.10.0a0+17a3bbf
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch-nightly
[conda] libblas                   3.9.0                    10_mkl    conda-forge
[conda] libcblas                  3.9.0                    10_mkl    conda-forge
[conda] liblapack                 3.9.0                    10_mkl    conda-forge
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] numpy                     1.19.5           py36hfc0c790_2    conda-forge
[conda] pytorch                   1.10.0.dev20210804     py3.6_cpu_0  [cpuonly]  pytorch-nightly
[conda] torchaudio                0.10.0a0+17a3bbf          pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by malfet** [comment]
Here is the backtrace:
```
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  <signal handler called>
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#3  0x00007f6fcb886921 in __GI_abort () at abort.c:79
#4  0x00007f6fcb87648a in __assert_fail_base (fmt=0x7f6fcb9fd750 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f6fbe2b248e "findOption(Name) == Values.size() && \"Option already exists!\"", 
    file=file@entry=0x7f6fbe1bdb20 "/tmp/llvm/include/llvm/Support/CommandLine.h", line=line@entry=813, 
    function=function@entry=0x7f6fbeab2ba0 <void llvm::cl::parser<llvm::FunctionPass* (*)()>::addLiteralOption<llvm::FunctionPass* (*)()>(llvm::StringRef, llvm::FunctionPass* (* const&)(), llvm::StringRef)::__PRETTY_FUNCTION__> "void llvm::cl::parser<DataType>::addLiteralOption(llvm::StringRef, const DT&, llvm::StringRef) [with DT = llvm::FunctionPass* (*)(); DataType = llvm::FunctionPass* (*)()]") at assert.c:92
#5  0x00007f6fcb876502 in __GI___assert_fail (assertion=0x7f6fbe2b248e "findOption(Name) == Values.size() && \"Option already exists!\"", file=0x7f6fbe1bdb20 "/tmp/llvm/include/llvm/Support/CommandLine.h", line=813, 
    function=0x7f6fbeab2ba0 <void llvm::cl::parser<llvm::FunctionPass* (*)()>::addLiteralOption<llvm::FunctionPass* (*)()>(llvm::StringRef, llvm::FunctionPass* (* const&)(), llvm::StringRef)::__PRETTY_FUNCTION__> "void llvm::cl::parser<DataType>::addLiteralOption(llvm::StringRef, const DT&, llvm::StringRef) [with DT = llvm::FunctionPass* (*)(); DataType = llvm::FunctionPass* (*)()]") at assert.c:101
#6  0x00007f6fbcf6ddd0 in void llvm::cl::parser<llvm::FunctionPass* (*)()>::addLiteralOption<llvm::FunctionPass* (*)()>(llvm::StringRef, llvm::FunctionPass* (* const&)(), llvm::StringRef) () from /root/project/env/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so
#7  0x00007f6fbcf6def3 in llvm::RegisterPassParser<llvm::RegisterRegAlloc>::NotifyAdd(llvm::StringRef, llvm::FunctionPass* (*)(), llvm::StringRef) () from /root/project/env/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so
#8  0x00007f6fa5cf3209 in _GLOBAL__sub_I_RegAllocBasic.cpp () from /root/project/env/lib/python3.6/site-packages/llvmlite/binding/../../../../libLLVM-10.so
#9  0x00007f6fcc60b8d3 in call_init (env=0x56363a78b480, argv=0x7ffd2970c268, argc=8, l=<optimized out>) at dl-init.c:72
#10 _dl_init (main_map=main_map@entry=0x56363bb4bea0, argc=8, argv=0x7ffd2970c268, env=0x56363a78b480) at dl-init.c:119
#11 0x00007f6fcc61039f in dl_open_worker (a=a@entry=0x7ffd296f59a0) at dl-open.c:522
#12 0x00007f6fcb9ad1ef in __GI__dl_catch_exception (exception=exception@entry=0x7ffd296f5980, operate=operate@entry=0x7f6fcc60ff60 <dl_open_worker>, args=args@entry=0x7ffd296f59a0) at dl-error-skeleton.c:196
#13 0x00007f6fcc60f96a in _dl_open (file=0x7f6faa638c20 "/root/project/env/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so", mode=-2147483646, caller_dlopen=0x7f6fcb5a6ff8 <py_dl_open+216>, nsid=<optimized out>, argc=8, argv=<optimized out>, 
    env=0x56363a78b480) at dl-open.c:605
#14 0x00007f6fcc3f7f96 in dlopen_doit (a=a@entry=0x7ffd296f5bd0) at dlopen.c:66
#15 0x00007f6fcb9ad1ef in __GI__dl_catch_exception (exception=exception@entry=0x7ffd296f5b70, operate=operate@entry=0x7f6fcc3f7f40 <dlopen_doit>, args=args@entry=0x7ffd296f5bd0) at dl-error-skeleton.c:196
#16 0x00007f6fcb9ad27f in __GI__dl_catch_error (objname=objname@entry=0x563638322530, errstring=errstring@entry=0x563638322538, mallocedp=mallocedp@entry=0x563638322528, operate=operate@entry=0x7f6fcc3f7f40 <dlopen_doit>, args=args@entry=0x7ffd296f5bd0)
    at dl-error-skeleton.c:215
#17 0x00007f6fcc3f8745 in _dlerror_run (operate=operate@entry=0x7f6fcc3f7f40 <dlopen_doit>, args=args@entry=0x7ffd296f5bd0) at dlerror.c:162
#18 0x00007f6fcc3f8051 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#19 0x00007f6fcb5a6ff8 in py_dl_open () at /usr/local/src/conda/python-3.6.13/Modules/_ctypes/callproc.c:1364
#20 0x00005636362ceda1 in _PyCFunction_FastCallDict (kwargs=0x0, nargs=<optimized out>, args=<optimized out>, func_obj=0x7f6fcb5c57e0) at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Objects/methodobject.c:234
#21 _PyCFunction_FastCallKeywords (kwnames=<optimized out>, nargs=<optimized out>, stack=<optimized out>, func=<optimized out>) at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Objects/methodobject.c:294
#22 call_function () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:4851
#23 0x00005636362ec39f in _PyEval_EvalFrameDefault () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:3335
#24 0x000056363627c994 in PyEval_EvalFrameEx (throwflag=0, f=0x7f6fcb722848) at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:754
#25 _PyEval_EvalCodeWithName () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:4166
#26 0x00005636362bf161 in _PyFunction_FastCallDict (kwargs=0x0, nargs=2, args=0x7ffd296f5f80, func=<optimized out>) at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:5084
#27 _PyObject_FastCallDict (kwargs=0x0, nargs=2, args=0x7ffd296f5f80, func=<optimized out>) at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Objects/abstract.c:2310
#28 _PyObject_Call_Prepend (kwargs=0x0, args=<optimized out>, obj=<optimized out>, func=<optimized out>) at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Objects/abstract.c:2373
#29 method_call () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Objects/classobject.c:314
#30 0x000056363627e9fe in PyObject_Call () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Objects/abstract.c:2261
#31 0x00005636362c1e90 in slot_tp_init () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Objects/typeobject.c:6420
#32 0x00005636362a37d7 in type_call () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Objects/typeobject.c:915
#33 0x000056363627d28c in _PyObject_FastCallDict () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Objects/abstract.c:2331
#34 0x00005636362cf135 in call_function () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:4875
#35 0x00005636362ec39f in _PyEval_EvalFrameDefault () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:3335
#36 0x000056363627c160 in PyEval_EvalFrameEx (throwflag=0, f=0x56363bb680c8) at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:754
#37 _PyEval_EvalCodeWithName () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:4166
#38 0x00005636362e917c in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, locals=0x7f6faa642d38, globals=0x7f6faa642d38, _co=0x7f6faa6534b0)
    at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:4187
#39 PyEval_EvalCode (locals=0x7f6faa642d38, globals=0x7f6faa642d38, co=0x7f6faa6534b0) at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/ceval.c:731
#40 builtin_exec_impl.isra.11 (locals=0x7f6faa642d38, globals=0x7f6faa642d38, source=0x7f6faa6534b0) at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/bltinmodule.c:983
#41 builtin_exec () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Python/clinic/bltinmodule.c.h:283
#42 0x00005636362a35ef in PyCFunction_Call () at /home/builder/ktietz/cos6/ci_cos6/python_1622833237666/work/Objects/methodobject.c:114
```

**Comment by malfet** [comment]
Which seem to point at https://github.com/pytorch/builder/commit/f91a15821936704a8f52b03ca5f519be0e04eb6b

**Comment by seemethere** [comment]
cc @bertmaher

**Comment by bertmaher** [comment]
Rats, I thought I tested this a while back, but I must have done something wrong in the test.  Hiding the symbols in our .so *should* work so hopefully I can get that done tomorrow.
