### ISSUE TITLE
torch.jit.trace RuntimeError for LEDForConditionalGeneration encoder

### ISSUE THREAD

**Issue by jatinganhotra** [pytorch/pytorch#62756]
## 🐛 Bug

Tracing the LEDForConditionalGeneration encoder results in an Runtime error -

```
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:1664: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if padding_len > 0:
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:1788: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  is_global_attn = is_index_global_attn.flatten().any().item()
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:191: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:410: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:413: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert query.size() == key.size()
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:220: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert list(attn_scores.size()) == [
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:478: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert seq_len % (window_overlap * 2) == 0
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:479: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_probs.size()[:3] == value.size()[:3]
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:480: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_probs.size(3) == 2 * window_overlap + 1
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:362: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  chunked_hidden_states = chunked_hidden_states[
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:289: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_output.size() == (batch_size, seq_len, self.num_heads, self.head_dim), "Unexpected size"
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:929: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if torch.isinf(hidden_states).any() or torch.isnan(hidden_states).any():
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:1854: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if padding_len > 0:
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py:1856: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  hidden_states = hidden_states[:, :-padding_len]
Traceback (most recent call last):
  File "example.py", line 31, in <module>
    traced_script_module(example_concurrent_batch)
  File "envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py(446): _sliding_chunks_query_key_matmul
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py(201): forward
envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py(709): _slow_forward
envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py(725): _call_impl
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py(718): forward
envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py(709): _slow_forward
envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py(725): _call_impl
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py(907): forward
envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py(709): _slow_forward
envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py(725): _call_impl
envs/triton/lib/python3.8/site-packages/transformers/models/led/modeling_led.py(1831): forward
envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py(709): _slow_forward
envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py(725): _call_impl
example.py(24): forward
envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py(709): _slow_forward
envs/triton/lib/python3.8/site-packages/torch/nn/modules/module.py(725): _call_impl
envs/triton/lib/python3.8/site-packages/torch/jit/_trace.py(934): trace_module
envs/triton/lib/python3.8/site-packages/torch/jit/_trace.py(733): trace
example.py(28): <module>
RuntimeError: shape '[12, 1, 512, 513]' is invalid for input of size 12607488
```

## To Reproduce

```
import torch
from transformers import *

from transformers import LEDTokenizer, LEDForConditionalGeneration
class WrappedModel(torch.nn.Module):
    def __init__(self):
        super(WrappedModel, self).__init__()
        self.model = LEDForConditionalGeneration.from_pretrained("allenai/led-base-16384", torchscript=True).led.encoder.cuda()
    def forward(self, data):
        return self.model(data.cuda())

example = torch.zeros((1,128), dtype=torch.long) # bsz , seqlen
pt_model = WrappedModel().eval()
traced_script_module = torch.jit.trace(pt_model, example)
# traced_script_module.save("traced_model.pt")
example_concurrent_batch = torch.zeros((4,128), dtype=torch.long) # bsz , seqlen
traced_script_module(example_concurrent_batch)
```

The example_concurrent_batch input is meant to simulate a dynamic batch created by Triton inference server, when the traced model is deployed and concurrent requests are sent via the Triton inference client.

Tracing the BERT model works fine when providing a higher batch size.

```
class WrappedModel(torch.nn.Module):
    def __init__(self):
        super(WrappedModel, self).__init__()
        self.model = BertForSequenceClassification.from_pretrained('bert-base-uncased', torchscript=True).cuda()
    def forward(self, data):
        return self.model(data.cuda())
```

## Expected behavior

There should not be any error.

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Red Hat (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.8.0 (default, Nov  6 2019, 21:49:08)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB

Nvidia driver version: 440.33.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] torch==1.7.1
[conda] numpy                     1.21.1                   pypi_0    pypi
[conda] torch                     1.7.1                    pypi_0    pypi

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
`jit.trace` tracks Tensor-values in a program. For shapes passed around as raw ints/tuples/lists may (likely) get baked into the traced module as constant. Passing input of a different batch size may break some shape invariant in the model, thus resulting in the error you experienced.
