### ISSUE TITLE
distributed/elastic/multiprocessing/api_test is flaky on ROCm

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#62902]
## 🐛 Bug

Example failure:
```
12:45:06 ======================================================================
12:45:06 ERROR [3.945s]: test_multiprocess_context_close (__main__.StartProcessesListTest)
12:45:06 ----------------------------------------------------------------------
12:45:06 Traceback (most recent call last):
12:45:06   File "distributed/elastic/multiprocessing/api_test.py", line 236, in tearDown
12:45:06     shutil.rmtree(self.test_dir)
12:45:06   File "/opt/conda/lib/python3.6/shutil.py", line 477, in rmtree
12:45:06     onerror(os.lstat, path, sys.exc_info())
12:45:06   File "/opt/conda/lib/python3.6/shutil.py", line 475, in rmtree
12:45:06     orig_st = os.lstat(path)
12:45:06 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/StartProcessesListTest_wbdco4lw'
12:45:06 
12:45:06 ----------------------------------------------------------------------
12:45:06 Ran 38 tests in 23.323s
12:45:06 
12:45:06 FAILED (errors=1)
12:45:06 
12:45:06 Generating XML reports...
12:45:06 Generated XML report: test-reports/dist-gloo/distributed.elastic.multiprocessing.api_test/TEST-RunProcResultsTest-20210806124443.xml
12:45:06 Generated XML report: test-reports/dist-gloo/distributed.elastic.multiprocessing.api_test/TEST-StartProcessesListTest-20210806124443.xml
12:45:06 Generated XML report: test-reports/dist-gloo/distributed.elastic.multiprocessing.api_test/TEST-StartProcessesTest-20210806124443.xml
12:45:06 Generated XML report: test-reports/dist-gloo/distributed.elastic.multiprocessing.api_test/TEST-StdTest-20210806124443.xml
12:45:07 Traceback (most recent call last):
12:45:07   File "test/run_test.py", line 1091, in <module>
12:45:07     main()
12:45:07   File "test/run_test.py", line 1070, in main
12:45:07     raise RuntimeError(err_message)
12:45:07 RuntimeError: distributed/elastic/multiprocessing/api_test failed!
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.2-py3.6-test2/11988/console

**Comment by arindamroy-eng** [comment]
@rohan-varma Seems like a duplicate of https://github.com/pytorch/pytorch/issues/62595.

**Comment by jithunnair-amd** [comment]
cc @aivanou
