### ISSUE TITLE
[JIT] NVRTC unknown error 

### ISSUE THREAD

**Issue by BelongAl** [pytorch/pytorch#62962]
## 🐛 Bug
This is a demo of my model.
I found that when reasoning the model established by the above code, an error will be reported if it is cycled three times. What is the reason?

**code:** 
```
import torch
import torch.nn as nn

def torch_distributions_Categorical_probs_p__entropy__(p):
    return torch.distributions.Categorical(probs=p).entropy()
trace_torch_distributions_Categorical_probs_p__entropy__ = torch.jit.trace(torch_distributions_Categorical_probs_p__entropy__, torch.tensor([0.25, 0.25, 0.25, 0.25]))

def normal_shannon_entropy(p, labels_num):
    # type: (torch.Tensor, int) -> torch.Tensor
    """normal_shannon_entropy"""
    entropy = trace_torch_distributions_Categorical_probs_p__entropy__(p)
    normal = -torch.log(torch.tensor(1.0) / torch.tensor(labels_num))
    return entropy / normal

class test(nn.Module):
    def __init__(self):
        super(test, self).__init__()
        self.layer_num = 2
        self.output_layer = torch.nn.Linear(64, 2)

    def forward(self, input):
        # type: (torch.Tensor)
        idxs: List[int] = [i for i in range(5)]
        output_1 = torch.rand(1, 128).to("cuda:0")
        logits_this_layer = self.output_layer(output_1)
        probs = nn.functional.softmax(logits_this_layer, dim=1)
        entropys = normal_shannon_entropy(probs, self.layer_num)
        print(entropys)

m = test().to("cuda:0")
m = torch.jit.script(m)
for i in range(3):
    m(torch.randn(16, 1, 20, 20).to("cuda:0"))
```

**error:**
```
 0.9470
[ CUDAFloatType{1} ]
 0.9308
[ CUDAFloatType{1} ]
Traceback (most recent call last):
  File "tesr.py", line 33, in <module>
    m(torch.randn(16, 1, 20, 20).to("cuda:0"))
  File "/home/users/wangrui39/Python-3.6.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: default_program(26): error: extra text after expected end of number

default_program(26): error: extra text after expected end of number

default_program(27): error: extra text after expected end of number

default_program(27): error: extra text after expected end of number

4 errors detected in the compilation of "default_program".

nvrtc compilation failed:

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)


template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_div_clamp_log_clamp_mul(float* t_, float* t__, float* aten_mul, float* aten_clamp, float* aten_log, float* aten_clamp_1, float* aten_div) {
{
  if (512 * blockIdx.x + threadIdx.x<2 ? 1 : 0) {
    float t__1 = __ldg(t_ + (512 * blockIdx.x + threadIdx.x) % 2);
    float t___1 = __ldg(t__ + 0);
    aten_div[512 * blockIdx.x + threadIdx.x] = t__1 / t___1;
    aten_clamp_1[512 * blockIdx.x + threadIdx.x] = (t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1)>0.9999998807907104f ? 0.9999998807907104f : (t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1);
    aten_log[512 * blockIdx.x + threadIdx.x] = logf((t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1)>0.9999998807907104f ? 0.9999998807907104f : (t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1));
    aten_clamp[512 * blockIdx.x + threadIdx.x] = (logf((t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1)>0.9999998807907104f ? 0.9999998807907104f : (t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1)))<-3.402823466385289e+38.f ? -3.402823466385289e+38.f : (logf((t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1)>0.9999998807907104f ? 0.9999998807907104f : (t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1)));
    aten_mul[512 * blockIdx.x + threadIdx.x] = ((logf((t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1)>0.9999998807907104f ? 0.9999998807907104f : (t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1)))<-3.402823466385289e+38.f ? -3.402823466385289e+38.f : (logf((t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1)>0.9999998807907104f ? 0.9999998807907104f : (t__1 / t___1<1.192092895507812e-07f ? 1.192092895507812e-07f : t__1 / t___1)))) * (t__1 / t___1);
  }
}
}
```

 - PyTorch Version (e.g., 1.0):
 - OS : linux
 - Python version: 1.9.0
 - CUDA version: 10.2
 - GPU models and configuration: T4

cc @gmagogsfm

**Comment by pqn** [comment]
I've seen a similar issue. My guess is that the code it is attempting to compile contains an invalid floating point literal `-3.402823466385289e+38.f` (it should be `-3.402823466385289e+38f`). Not sure how this is being generated, but note that this value is `-FLT_MAX`.

**Comment by bluaxe** [comment]
Seen a similar issue on https://huggingface.co/albert-base-v2 : 

`Error: input model incompatible with test data, exception: default_program(24): error: extra text after expected end of number

default_program(29): error: extra text after expected end of number

2 errors detected in the compilation of "default_program".

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)


template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_mul_div_add(float* tattention_scores_1, float* t_, float* aten_add, float* aten_mul) {
{
  float t__1 = __ldg(t_ + (512 * blockIdx.x + threadIdx.x) % 16);
  if (blockIdx.x<1 ? 1 : 0) {
    if (512 * blockIdx.x + threadIdx.x<16 ? 1 : 0) {
      if (blockIdx.x<1 ? 1 : 0) {
        aten_mul[512 * blockIdx.x + threadIdx.x] = (float)((double)(t__1) * -3.402823466385289e+38.0);
      }
    }
  }
  double v = (double)(__ldg(tattention_scores_1 + (512 * blockIdx.x + threadIdx.x) % 3072));
  aten_add[512 * blockIdx.x + threadIdx.x] = (float)(v / 8.0) + (float)((double)(t__1) * -3.402823466385289e+38.0);
}
}`

PyTorch Version (e.g., 1.0): 1.9.1+cu111
OS : linux
Python version: 3.7.5
CUDA version: 11.1
GPU models and configuration: T4

**Comment by SeungsuBaek** [comment]
Got same error in "Bert-base-uncased"

```
Thread [0] had error: PyTorch execute failure: default_program(24): error: extra text after expected end of number

default_program(27): error: extra text after expected end of number

2 errors detected in the compilation of "default_program".

nvrtc compilation failed:

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)


template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_mul_div_add(float* tattention_scores_2, float* tv_, float* aten_add, float* aten_mul) {
{
if (blockIdx.x<1ll ? 1 : 0) {
if ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)<384ll ? 1 : 0) {
if (blockIdx.x<1ll ? 1 : 0) {
        float v = __ldg(tv_ + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
        aten_mul[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = v * -3.402823466385289e+38.f;
      }    }  }  float v_1 = __ldg(tattention_scores_2 + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
  float v_2 = __ldg(tv_ + ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)) % 384ll);
  aten_add[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = v_1 / 8.f + v_2 * -3.402823466385289e+38.f;
}
}
```

Pytorch Version : v1.12.0
CUDA Version : 11.7
GPU : RTX 3090

**Comment by DSXiangLi** [comment]
Any update on this issue， I ran into the same problem?

**Comment by ReactiveCJ** [comment]
In torch 1.2.1, this problem is existed as well.   Torch JIT will optimize the bert model and such nv fuse error happens

**Comment by SeungsuBaek** [comment]
@DSXiangLi 
If you don't need to fuse your model, just disable nvfuser options.

**Comment by LinjianLi** [comment]
> @DSXiangLi If you don't need to fuse your model, just disable nvfuser options.

I solve the problem by setting
```
# torch.jit.fuser('off')
# torch._C._jit_override_can_fuse_on_cpu(False)
# torch._C._jit_override_can_fuse_on_gpu(False)
# torch._C._jit_set_texpr_fuser_enabled(False)
# torch._C._jit_set_nvfuser_enabled(False)
```

But acturally I do not understand the underlying reason of this problem. Why does the model work fine in the first several forwards but have the error at the later forwards? Does simply forwarding the data through the model change the model? Would you please provide some references or documents for me to learn about that? It would be a great help.

**Comment by SeungsuBaek** [comment]
@LinjianLi 

As i know it, nvfuser works in the first few iterations. 

When model is executing with input data, nvfuser finds some optimizing points to fuse model graph. Due to that, the first few iterations shows slow inference time.

Maybe, the reason why some of few iteration works fine is that nvfuser does not touch error point.

It is just my opinion. If you want to more information, it is good to you to find some documents of nvfuser.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
