### ISSUE TITLE
[utils.bottleneck] Bottleneck crashes with multi-threaded data loader

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#6313]
`torch.utils.bottleneck` doesn't work properly when the code contains a data loader that uses more than 0 threads.

Minimum reproducible example (`mwe.py`):
```python
import argparse
import torch
import torch.utils.data

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='mwe')
    parser.add_argument('--num-workers', default=0, type=int)
    args = parser.parse_args()

    data = torch.rand(10, 1000)
    target = torch.rand(10)
    dataset = torch.utils.data.TensorDataset(data, target)
    data_loader = torch.utils.data.DataLoader(dataset,
        batch_size=2, num_workers=args.num_workers)
    for i, batch in enumerate(data_loader):
        pass
```

Running the script via:
```
python -m torch.utils.bottleneck -- mwe.py --num-workers 0
```
works fine, while
```
python -m torch.utils.bottleneck -- mwe2.py --num-workers 1
```
crashes with the following stack trace:
```
Traceback (most recent call last):
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/bottleneck/__main__.py", line 280, in <module>
    main()
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/bottleneck/__main__.py", line 261, in main
    autograd_prof_cpu, autograd_prof_cuda = run_autograd_prof(code, globs)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/bottleneck/__main__.py", line 155, in run_autograd_prof
    result.append(run_prof(use_cuda=True))
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/bottleneck/__main__.py", line 149, in run_prof
    exec(code, globs, None)
  File "mwe2.py", line 15, in <module>
    for i, batch in enumerate(data_loader):
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 285, in __next__
    return self._process_next_batch(batch)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 306, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 40, in __getitem__
    return tuple(tensor[index] for tensor in self.tensors)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 40, in <genexpr>
    return tuple(tensor[index] for tensor in self.tensors)
RuntimeError: /private/home/fmassa/github/pytorch/torch/csrc/autograd/profiler.h:52: initialization error
```

assigning this to @zou3519 , even thought I'm not sure if it's a problem in the profiler or in the `bottleneck` tool.

pytorch version `'0.4.0a0+b21e135'`

**Comment by zou3519** [comment]
Yikes, thanks for the catch. I'll look into it

**Comment by TiRune** [comment]
Ran into this problem as well on unix; Would be great if we could still use the bottleneck functionality with multiple dataloaders :)

**Comment by jhagege** [comment]
Hi, has anyone found any workaround with this issue ? 
I am trying to identify bottleneck in a PyTorch code and have a hard time doing it without proper profiling.
Can anyone recommend good resources for identifying bottleneck (even with other techniques) ? 
Thanks !

**Comment by stmharry** [comment]
This thread deserves more visibility.

Tried many ways to avoid `/pytorch/torch/csrc/autograd/profiler.h:52: initialization error`, and ended up here, just to realize the problem is the number of workers.

Have not been able to locate a good tool in identifying the bottleneck.

**Comment by dcela** [comment]
This is still an issue for me as well

**Comment by yaceben** [comment]
Still an issue for me as well

**Comment by XiaobingSuper** [comment]
I also meet a similar issue when using autograd profiler on GPU device.  You can reproduce the result by running the following code:

```bash
import argparse
import torch
import torch.utils.data

if __name__ == '__main__':
     parser = argparse.ArgumentParser(description='mwe')
     parser.add_argument('--num-workers', default=0, type=int)
     args = parser.parse_args()

     data = torch.rand(10, 1000)
     target = torch.rand(10)
     dataset = torch.utils.data.TensorDataset(data, target)
     data_loader = torch.utils.data.DataLoader(dataset,batch_size=2, num_workers=args.num_workers)
     with torch.autograd.profiler.profile(use_cuda=True) as prof:
         for i, batch in enumerate(data_loader):
             pass
     print(prof)
```
Running the script via:
```bash
python test.py --num-workers 0
```
works fine, while
```bash
python test.py --num-workers 1
```
can get the following error:
```bash
Traceback (most recent call last):
  File "my_test.py", line 15, in <module>
    for i, batch in enumerate(data_loader):
  File "/home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 40, in __getitem__
    return tuple(tensor[index] for tensor in self.tensors)
  File "/home/xiaobinz/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 40, in <genexpr>
    return tuple(tensor[index] for tensor in self.tensors)
RuntimeError: /opt/conda/conda-bld/pytorch_1549628766161/work/torch/csrc/autograd/profiler.h:81: initialization error
```
Torch version is
``` bash
pytorch                   1.0.1           py3.6_cuda9.0.176_cudnn7.4.2_2    pytorch
```
Perhaps they are same issue, thanks!

**Comment by rgommers** [comment]
This is still an issue; the failure mode changed after the significant rewrite of `dataloader.py` in #19228:
```
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 15030) is killed by signal: Aborted.
...
RuntimeError: DataLoader worker (pid(s) 15030) exited unexpectedly
```

Full traceback:

<details>

```
$ python -m torch.utils.bottleneck -- torch_6313.py --num-workers 1
`bottleneck` is a tool that can be used as an initial step for debugging
bottlenecks in your program.

It summarizes runs of your script with the Python profiler and PyTorch's
autograd profiler. Because your script will be profiled, please ensure that it
exits in a finite amount of time.

For more complicated uses of the profilers, please see
https://docs.python.org/3/library/profile.html and
https://pytorch.org/docs/master/autograd.html#profiler for more information.
Running environment analysis...
Running your script with cProfile
Running your script with the autograd profiler...
terminate called after throwing an instance of 'std::runtime_error'
  what():  /opt/conda/conda-bld/pytorch-nightly_1563772086834/work/torch/csrc/autograd/profiler_cuda.cpp:22: initialization error
Traceback (most recent call last):
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 683, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 15030) is killed by signal: Aborted. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/utils/bottleneck/__main__.py", line 231, in <module>
    main()
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/utils/bottleneck/__main__.py", line 210, in main
    autograd_prof_cpu, autograd_prof_cuda = run_autograd_prof(code, globs)
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/utils/bottleneck/__main__.py", line 104, in run_autograd_prof
    result.append(run_prof(use_cuda=True))
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/utils/bottleneck/__main__.py", line 98, in run_prof
    exec(code, globs, None)
  File "torch_6313.py", line 15, in <module>
    for i, batch in enumerate(data_loader):
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 763, in __next__
    idx, data = self._get_data()
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 730, in _get_data
    success, data = self._try_get_data()
  File "/home/rgommers/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 696, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 15030) exited unexpectedly
```

</details>

**Comment by andfoy** [comment]
I'll work on this one

**Comment by hongliny** [comment]
Still an issue as of v1.2

**Comment by zou3519** [comment]
So the root problem is the following:
- DataLoader uses `fork` to create a new process
- the autograd profiler in CUDA mode initializes CUDA. Bottleneck uses the CUDA mode autograd profiler if it is available
- the CUDA API does not support `fork`-ing after CUDA has been initialized.

I'm not sure what the best way to resolve this is. From the user side, one can change the multiprocessing method to `spawn` (instead of `fork`), but this might have different performance characteristics. Here are some potential action items:

- Give a nice error message. Something like: "autograd profiler in CUDA mode is not supported with dataloader"
- figure out some way to benchmark data loading.

**Comment by zou3519** [comment]
FWIW, nvprof also has the restriction that it can't profile a process that forks. Trying to benchmark a dataloader with nvprof gives the same error:
```
(/scratch/rzou/pt/workspace-env) [0 0] rzou@devfair0317:/scratch/rzou/pt/workspace (better-msg) $ nvprof -o
 mwe.nvprof python mwe.py --num-workers=1
==48352== NVPROF is profiling process 48352, command: python mwe.py --num-workers=1
inside profiler
terminate called after throwing an instance of 'std::runtime_error'
  what():  ../torch/csrc/autograd/profiler_cuda.cpp:36: CUDA initialization error. This can occur if one ru
ns the profiler in CUDA mode on code that creates a DataLoader with num_workers > 0. This operation is curr
ently unsupported; potential workarounds are: (1) don't use the profiler in CUDA mode or (2) use num_worker
s=0 in the DataLoader or (3) Don't profile the data loading portion of your code. https://github.com/pytorc
h/pytorch/issues/6313 tracks profiler support for multi-worker DataLoader.
Traceback (most recent call last):
  File "/scratch/rzou/pt/workspace/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/scratch/rzou/pt/workspace-env/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/scratch/rzou/pt/workspace-env/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/scratch/rzou/pt/workspace-env/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/scratch/rzou/pt/workspace-env/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/scratch/rzou/pt/workspace-env/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/scratch/rzou/pt/workspace/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 49090) is killed by signal: Aborted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mwe.py", line 16, in <module>
    for i, batch in enumerate(data_loader):
  File "/scratch/rzou/pt/workspace/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/scratch/rzou/pt/workspace/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/scratch/rzou/pt/workspace/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/scratch/rzou/pt/workspace/torch/utils/data/dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 49090) exited unexpectedly
==48352== Generated result file: /scratch/rzou/pt/workspace/mwe.nvprof
======== Error: Application returned non-zero code 1
```

Futhermore, the design of the autograd profiler requires it to initialize CUDA; otherwise, it is difficult to accurately create a timeline.

Regarding torch.utils.bottleneck, we should do at least one of the following
1) Switch to CPU-only profiling as the default
2) Document that we don't support multi-process profiling
3) Add some graceful error handling so that bottleneck doesn't crash when doing multi-process profiling.

**Comment by Baranowski** [comment]
AFAICT zou3517 has implemented 2. and 3. from https://github.com/pytorch/pytorch/issues/6313#issuecomment-568041169 in the merged PR https://github.com/pytorch/pytorch/pull/31473. Should this issue be closed, or is there still something left to do?

**Comment by ezyang** [comment]
cc @zou3519

**Comment by zou3519** [comment]
@Baranowski: Yeah, it looks like we've done 2&3.

For 2, we missed adding an entry to the bottleneck docs: https://pytorch.org/docs/stable/bottleneck.html . So that remains to be done.

For action item 1, I'm not sure if it is a good idea to switch to CPU-only profiling for bottleneck. That is a separate issue though; to finish resolving the issue of this crash, we should add a line to the bottleneck docs about the limitation.

**Comment by makslevental** [comment]
how do you change from `fork` to `spawn` in dataloader? i'm having this issue right now

**Comment by ngimel** [comment]
closing due to age.
