### ISSUE TITLE
RuntimeError: ArrayRef: invalid index Index = 1; Length = 1. When export pytorch model to onnx

### ISSUE THREAD

**Issue by ZJG0** [pytorch/pytorch#63146]
## error info:
Traceback (most recent call last):
  File "private_test.py", line 269, in <module>
    main()
  File "private_test.py", line 265, in main
    test(args, model)
  File "private_test.py", line 189, in test
    private_model = construct_private_model(input_size, model, args)
  File "private_test.py", line 179, in construct_private_model
    private_model = crypten.nn.from_pytorch(model_upd, dummy_input).encrypt(src=0)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 45, in from_pytorch
    f = _from_pytorch_to_bytes(pytorch_model, dummy_input)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 106, in _from_pytorch_to_bytes
    _export_pytorch_model(f, pytorch_model, dummy_input)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/crypten-0.1.0-py3.8.egg/crypten/nn/onnx_converter.py", line 131, in _export_pytorch_model
    torch.onnx.export(pytorch_model, dummy_input, f, **kwargs)
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 694, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/root/anaconda3/envs/crypten-vit/lib/python3.8/site-packages/torch/onnx/utils.py", line 488, in _model_to_graph
    torch._C._jit_pass_onnx_assign_output_shape(graph, output_tensors, out_desc, _onnx_shape_inference)
RuntimeError: ArrayRef: invalid index Index = 1; Length = 1

## Issue description

When i want to export torch model to onnx, there are many errors as above.
I have tried to change the "loop + append" form, but it didn't work. 
[model.txt](https://github.com/pytorch/pytorch/files/6975507/model.txt)

## System Info
```
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.11 (default, Aug  3 2021, 15:09:35)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.9.0-050900-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] torch==1.8.1
[pip3] torchvision==0.9.1
[conda] numpy                     1.21.1                    <pip>
[conda] torch                     1.8.1                     <pip>
[conda] torchvision               0.9.1                     <pip>
``` 
I have tested the PyTorch 1.9.0, which isn't instrumental. 

cc @BowenBao @neginraoof

**Comment by jiafatom** [comment]
@bdhirsh could you please provide a small repro? Thanks!

**Comment by ZJG0** [comment]
[pytorch2onnx-repro.zip](https://github.com/pytorch/pytorch/files/6979336/pytorch2onnx-repro.zip)
You can reproduce the error by running `test_onnx.py`.
```
python test_onnx.py
```

**Comment by jiafatom** [comment]
@ZJG0 can you make the model as small as possible? It really takes a long time to convert the model.

**Comment by ZJG0** [comment]
[pytorch2onnx-repro.zip](https://github.com/pytorch/pytorch/files/7035731/pytorch2onnx-repro.zip)
Model structure cannot be changed, I reduced the number of hidden layers and reduced the size of the model.

**Comment by garymm** [comment]
Attempting to repro it seems there's a bug in the model.

Repro steps:
1. Downloaded zip file from https://github.com/pytorch/pytorch/issues/63146#issuecomment-904243721
2. Expanded it to a dir named repro63146
3. touch `repro63146/__init__.py`
4. Change `repro63146/test_onnx.py` to contain:

```python
import torch
from repro63146.modeling import VisionTransformer, CONFIGS

config = CONFIGS['ViT-B_16']
model = VisionTransformer(config, 224, zero_head=True, num_classes=10)
x = torch.randn(1, 512, 10, 10)
dummy_input = torch.randn(64, 3, 224, 224)
model(dummy_input)
```

I get the error:

```sh
➜  python repro63146/test_onnx.py
Traceback (most recent call last):
  File "/home/azureuser/src/pytorch/pytorch-master/repro63146/test_onnx.py", line 8, in <module>
    model(dummy_input)
  File "/home/azureuser/miniconda3/envs/pytorch-master/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/azureuser/src/pytorch/pytorch-master/repro63146/modeling.py", line 273, in forward
    x, attn_weights = self.transformer(x)
  File "/home/azureuser/miniconda3/envs/pytorch-master/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/azureuser/src/pytorch/pytorch-master/repro63146/modeling.py", line 258, in forward
    encoded, attn_weights = self.encoder(embedding_output)
  File "/home/azureuser/miniconda3/envs/pytorch-master/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/azureuser/src/pytorch/pytorch-master/repro63146/modeling.py", line 243, in forward
    hidden_states, weights = layer_block(hidden_states)
  File "/home/azureuser/miniconda3/envs/pytorch-master/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/azureuser/src/pytorch/pytorch-master/repro63146/modeling.py", line 183, in forward
    x, weights = self.attn(x)
  File "/home/azureuser/miniconda3/envs/pytorch-master/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/azureuser/src/pytorch/pytorch-master/repro63146/modeling.py", line 94, in forward
    attention_output = self.out(context_layer)
  File "/home/azureuser/miniconda3/envs/pytorch-master/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/azureuser/miniconda3/envs/pytorch-master/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/azureuser/miniconda3/envs/pytorch-master/lib/python3.9/site-packages/torch/nn/functional.py", line 1896, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (12608x255 and 256x256)
```

@ZJG0 we need a working and resonably sized repro case to make progress on this.

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
