### ISSUE TITLE
test_nn fail with source build PyTorch 0.4 Google Cloud K80

### ISSUE THREAD

**Issue by subcomputes** [pytorch/pytorch#6333]
[test_nn.py](https://github.com/pytorch/pytorch/blob/master/test/test_nn.py) fails when running on google cloud standard compute image with K80 GPU
- OS: Ubuntu 16.04 LTS
- PyTorch version: 0.4.0a0+afdaf52
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6.4
- CUDA/cuDNN version: 9.1
- GPU models and configuration: K80 on google cloud
- GCC version (if compiling from source): 5.4.0
- CMake version: 3.9.4
- Build command you used (if compiling from source): python setup.py build develop
- Versions of any other relevant libraries: N/A

Most python tests work, but 1 failure and 18 errors:
```
======================================================================
ERROR: test_LayerNorm_1d_elementwise_affine_tracking_stats (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5066, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 943, in __call__
    module = self.constructor(*self.constructor_args)
TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given

======================================================================
ERROR: test_LayerNorm_1d_elementwise_affine_tracking_stats_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5078, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 1018, in test_cuda
    cpu_module = self.constructor(*self.constructor_args)
TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given

======================================================================
ERROR: test_LayerNorm_1d_elementwise_affine_tracking_stats_eval (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5066, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 943, in __call__
    module = self.constructor(*self.constructor_args)
  File "/home/subcompute/pytorch/test/test_nn.py", line 7011, in eval_constructor
    cons = constructor(*args, **kwargs)
TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given

======================================================================
ERROR: test_LayerNorm_1d_elementwise_affine_tracking_stats_eval_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5078, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 1018, in test_cuda
    cpu_module = self.constructor(*self.constructor_args)
  File "/home/subcompute/pytorch/test/test_nn.py", line 7011, in eval_constructor
    cons = constructor(*args, **kwargs)
TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given

======================================================================
ERROR: test_LayerNorm_1d_no_elementwise_affine (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5066, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 943, in __call__
    module = self.constructor(*self.constructor_args)
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

======================================================================
ERROR: test_LayerNorm_1d_no_elementwise_affine_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5078, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 1018, in test_cuda
    cpu_module = self.constructor(*self.constructor_args)
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

======================================================================
ERROR: test_LayerNorm_1d_no_elementwise_affine_eval (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5066, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 943, in __call__
    module = self.constructor(*self.constructor_args)
  File "/home/subcompute/pytorch/test/test_nn.py", line 7011, in eval_constructor
    cons = constructor(*args, **kwargs)
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

======================================================================
ERROR: test_LayerNorm_1d_no_elementwise_affine_eval_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5078, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 1018, in test_cuda
    cpu_module = self.constructor(*self.constructor_args)
  File "/home/subcompute/pytorch/test/test_nn.py", line 7011, in eval_constructor
    cons = constructor(*args, **kwargs)
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

======================================================================
ERROR: test_LayerNorm_3d_elementwise_affine_tracking_stats (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5066, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 943, in __call__
    module = self.constructor(*self.constructor_args)
TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given

======================================================================
ERROR: test_LayerNorm_3d_elementwise_affine_tracking_stats_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5078, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 1018, in test_cuda
    cpu_module = self.constructor(*self.constructor_args)
TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given

======================================================================
ERROR: test_LayerNorm_3d_elementwise_affine_tracking_stats_eval (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5066, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 943, in __call__
    module = self.constructor(*self.constructor_args)
  File "/home/subcompute/pytorch/test/test_nn.py", line 7011, in eval_constructor
    cons = constructor(*args, **kwargs)
TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given

======================================================================
ERROR: test_LayerNorm_3d_elementwise_affine_tracking_stats_eval_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5078, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 1018, in test_cuda
    cpu_module = self.constructor(*self.constructor_args)
  File "/home/subcompute/pytorch/test/test_nn.py", line 7011, in eval_constructor
    cons = constructor(*args, **kwargs)
TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given

======================================================================
ERROR: test_LayerNorm_3d_no_elementwise_affine (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5066, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 943, in __call__
    module = self.constructor(*self.constructor_args)
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

======================================================================
ERROR: test_LayerNorm_3d_no_elementwise_affine_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5078, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 1018, in test_cuda
    cpu_module = self.constructor(*self.constructor_args)
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

======================================================================
ERROR: test_LayerNorm_3d_no_elementwise_affine_eval (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5066, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 943, in __call__
    module = self.constructor(*self.constructor_args)
  File "/home/subcompute/pytorch/test/test_nn.py", line 7011, in eval_constructor
    cons = constructor(*args, **kwargs)
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

======================================================================
ERROR: test_LayerNorm_3d_no_elementwise_affine_eval_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 5078, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "/home/subcompute/pytorch/test/common_nn.py", line 1018, in test_cuda
    cpu_module = self.constructor(*self.constructor_args)
  File "/home/subcompute/pytorch/test/test_nn.py", line 7011, in eval_constructor
    cons = constructor(*args, **kwargs)
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

======================================================================
ERROR: test_LayerNorm_general (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 1789, in test_LayerNorm_general
    self._test_LayerNorm_general(torch.FloatTensor)
  File "/home/subcompute/pytorch/test/test_nn.py", line 1764, in _test_LayerNorm_general
    elementwise_affine=False, track_running_stats=True).type(type)
TypeError: __init__() got an unexpected keyword argument 'momentum'

======================================================================
ERROR: test_LayerNorm_general_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 1793, in test_LayerNorm_general_cuda
    self._test_LayerNorm_general(torch.cuda.FloatTensor)
  File "/home/subcompute/pytorch/test/test_nn.py", line 1764, in _test_LayerNorm_general
    elementwise_affine=False, track_running_stats=True).type(type)
TypeError: __init__() got an unexpected keyword argument 'momentum'

======================================================================
FAIL: test_noncontig_conv_grad (__main__.TestNN) (dtype=<class 'torch.HalfTensor'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subcompute/pytorch/test/test_nn.py", line 65, in call_helper
    f(self, *args, dtype=dtype)
  File "/home/subcompute/pytorch/test/test_nn.py", line 3735, in test_noncontig_conv_grad
    self.assertEqual(result, input.grad.data)
  File "/home/subcompute/pytorch/test/common.py", line 253, in assertEqual
    assertTensorsEqual(x, y)
  File "/home/subcompute/pytorch/test/common.py", line 245, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: 
1.00000e-04 *
  9.7656
[torch.cuda.HalfTensor of size () (GPU 0)]
 not less than or equal to 1e-05 : 

----------------------------------------------------------------------
Ran 1106 tests in 594.896s

FAILED (failures=1, errors=18, skipped=25)
 ```

**Comment by SsnL** [comment]
The commit you pull shouldn't have some of these tests. It is most likely that you didn't get the correct version. Please check your files as this is not a PyTorch bug.

**Comment by SsnL** [comment]
Do you also have other fails like `test_LayerNorm_3d_no_elementwise_affine_cuda`?

**Comment by subcomputes** [comment]
No, just that one fail.

**Comment by SsnL** [comment]
It's likely precision issue as it is testing `half`. We probably can increase the epsilon here.

**Comment by subcomputes** [comment]
Should I create a detailed PR for this change?

**Comment by SsnL** [comment]
@subcomputes That would be great! Thanks!

**Comment by subcomputes** [comment]
I busy with work right now, I will have it up by tomorrow. Thanks for the help @SsnL

**Comment by SsnL** [comment]
Thanks for willing to contribute :)
