### ISSUE TITLE
test_variant_consistency intermittently fails on Windows

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#63444]
Just looking at the HUD failures for "win-vs2019-cuda11.1-py3 / test":

https://github.com/pytorch/pytorch/runs/3354615096 
<details>
<summary>  test_variant_consistency_eager_nn_functional_conv_transpose2d_cuda_float32</summary>

```
======================================================================
FAIL [0.031s]: test_variant_consistency_eager_nn_functional_conv_transpose2d_cuda_float32 (__main__.TestCommonCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\pytorch-1140395279\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 373, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\pytorch-1140395279\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 766, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 468, in test_variant_consistency_eager
    _test_consistency_helper(samples, variants)
  File "test_ops.py", line 460, in _test_consistency_helper
    self.assertEqual(expected_forward, variant_forward)
  File "C:\actions-runner\_work\pytorch\pytorch\pytorch-1140395279\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 1552, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 1 element(s) (out of 392) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.52587890625e-05 (0.577723503112793 vs. 0.5777082443237305), which occurred at index (0, 4, 3, 3).

----------------------------------------------------------------------
Ran 13533 tests in 2919.222s

FAILED (failures=1, skipped=5668)
```
</details>

https://github.com/pytorch/pytorch/runs/3354798475
<details>
<summary> test_variant_consistency_eager_nn_functional_conv_transpose2d_cuda_float32 (__main__.TestCommonCUDA)</summary>

```
======================================================================
FAIL [0.031s]: test_variant_consistency_eager_nn_functional_conv_transpose2d_cuda_float32 (__main__.TestCommonCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\pytorch-1140437192\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 373, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\pytorch-1140437192\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 766, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 468, in test_variant_consistency_eager
    _test_consistency_helper(samples, variants)
  File "test_ops.py", line 460, in _test_consistency_helper
    self.assertEqual(expected_forward, variant_forward)
  File "C:\actions-runner\_work\pytorch\pytorch\pytorch-1140437192\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 1552, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 1 element(s) (out of 392) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.52587890625e-05 (0.577723503112793 vs. 0.5777082443237305), which occurred at index (0, 4, 3, 3).

----------------------------------------------------------------------
Ran 13533 tests in 2778.578s

FAILED (failures=1, skipped=5668)
```
</details>

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @gmagogsfm @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by zou3519** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/63389

**Comment by mantaionut** [comment]
Closing this issue since these tests are no longer failing in CI.
