### ISSUE TITLE
multi-gpu error sgd backward pass learning rate reduced by half

### ISSUE THREAD

**Issue by kirk86** [pytorch/pytorch#6347]
PyTorch GitHub Issues Guidelines
--------------------------------
- PyTorch
- OS: ubuntu 16.04
- PyTorch version: 0.4
- How you installed PyTorch (source):
- Python version: 3.6
- CUDA/cuDNN version: cuda8/cudnn6
- GPU models and configuration: 1080Ti
- GCC version (if compiling from source): gcc-7
- CMake version: 3.5.1
- Build command you used (if compiling from source):
```
export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" # [anaconda root directory]

# Install basic dependencies
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing

# Add LAPACK support for the GPU
conda install -c pytorch magma-cuda80 
python setup.py install
```

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
```
import torch
import torchvision
from torchvision.models import densenet201

model = densenet201()
# set the optimizer to SGD
optimizer = optim.SGD(filter(lambda p: p.requires_grad, net.parameters()),
                         lr=lr/2 if (num_iters % iter_smooth == 0) else lr, momentum=0.9, weight_decay=0.0001)
rate = get_learning_rate(optimizer)  #load all except learning rate
optimizer.load_state_dict(checkpoint['optimizer'])
adjust_learning_rate(optimizer, rate)

# usual training step follows:
```

- Error messages and/or stack traces of the bug
```
in  40638,138,Traceback (most recent call last):
  File "train_0.py", line 516, in <module>
    run_train()
  File "train_0.py", line 352, in run_train
    loss.backward()
  File "/home/user/miniconda3/envs/torch/lib/python3.6/site-packages/torch/autograd/variable.py", line 120, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/user/miniconda3/envs/torch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 81, in backward
    variables, grad_variables, retain_graph, create_graph)
RuntimeError: arguments are located on different GPUs at /home/user/pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:231
```
- Context around what you are trying to do

Train a model on multiple gpus with SGD and reduce learning rate by half every x epochs.

**Comment by ailzhang** [comment]
Hi @kirk86 , which commit of pytorch0.4 are you on? 
Also could you try this simple script?
```
import torch
import torch.nn as nn
import torch.nn.functional as F

batch_size = 4

class Encoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv1d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
        self.pool = nn.AvgPool1d(2)

    def forward(self, x):
        return self.pool(self.conv(x))

model = nn.DataParallel(Encoder()).cuda()

import pdb
pdb.set_trace()
x = torch.rand([batch_size, 1, 20]).cuda()
z = model(x)
loss = nn.L1Loss()

l = loss(z, torch.rand(z.shape).cuda())

l.backward()
```
If this doesn't work, please try rebuild your pytorch with master branch. If this passes, could you send us a complete minimal repro script?

**Comment by ailzhang** [comment]
Closing, feel free to reopen if there's further information.
