### ISSUE TITLE
[jit cpp extensions] Possible file corruption in distributed setting

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#6353]
I believe there might be some sort of race condition that might happen when compiling jit cpp extensions in a distributed setting.

Here a summary of what happens:
- I launch my code from multiple different processes (to use with DistributedDataParallel, via `torch.distributed.launch`)
- each process starts to compile the extension
- they all try to save the extension to the same file
- sometimes, the file gets corrupted because of that

Here is part of the stack trace of the error I obtain (the rest is just the same error repeated):
```
  1 0: Traceback (most recent call last):
  2 0:   File "/private/home/fmassa/github/detectron.pytorch/torch_detectron/training_faster_rcnn.py", line 190, in <module>
  3 0:     from lib.faster_rcnn import fasterrcnn_resnet18, C2ResNetFasterRCNN
  4 0:   File "/private/home/fmassa/github/detectron.pytorch/torch_detectron/lib/faster_rcnn.py", line 13, in <module>
  5 0:     from lib.layers import ROIAlign, ROIPool, FixedBatchNorm2d
  6 0:   File "/private/home/fmassa/github/detectron.pytorch/torch_detectron/lib/layers/__init__.py", line 28, in <module>
  7 0:     _C = _load_C_extensions()
  8 0:   File "/private/home/fmassa/github/detectron.pytorch/torch_detectron/lib/layers/__init__.py", line 26, in _load_C_extensions
  9 0:     '-gencode arch=compute_70,code=sm_70'])
 10 0:   File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 330, in load
 11 0:     build_directory = _get_build_directory(name, verbose)
 12 0:   File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 392, in _get_build_directory
 13 0:     os.makedirs(build_directory)
 14 0:   File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/os.py", line 220, in makedirs
 15 0:     mkdir(name, mode)
 16 0: FileExistsError: [Errno 17] File exists: '/tmp/torch_extensions/detectron_modules'
 17 0: Traceback (most recent call last):
 18 0:   File "/private/home/fmassa/github/detectron.pytorch/torch_detectron/training_faster_rcnn.py", line 190, in <module>
 19 0:     from lib.faster_rcnn import fasterrcnn_resnet18, C2ResNetFasterRCNN
 20 0:   File "/private/home/fmassa/github/detectron.pytorch/torch_detectron/lib/faster_rcnn.py", line 13, in <module>
 21 0:     from lib.layers import ROIAlign, ROIPool, FixedBatchNorm2d
 22 0:   File "/private/home/fmassa/github/detectron.pytorch/torch_detectron/lib/layers/__init__.py", line 28, in <module>
 23 0:     _C = _load_C_extensions()
 24 0:   File "/private/home/fmassa/github/detectron.pytorch/torch_detectron/lib/layers/__init__.py", line 26, in _load_C_extensions
 25 0:     '-gencode arch=compute_70,code=sm_70'])
 26 0:   File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 361, in load
 27 0:     return _import_module_from_library(name, build_directory)
 28 0:   File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 414, in _import_module_from_library
 29 0:     return imp.load_module(module_name, file, path, description)
 30 0:   File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/imp.py", line 243, in load_module
 31 0:     return load_dynamic(name, filename, file)
 32 0:   File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/imp.py", line 343, in load_dynamic
 33 0:     return _load(spec)
 34 0: ImportError: /tmp/torch_extensions/detectron_modules/detectron_modules.so: file too short
...
```
We can see that two types of errors pop out: `FileExistsError` and `ImportError: modules.so: file too short`.

Let me know if you need a minimal reproducible example.

pytorch version `'0.4.0a0+b21e135'`

**Comment by fmassa** [comment]
Here is a `mwe.py`

```python
import argparse

def compile_ext():
    import os.path
    from torch.utils.cpp_extension import load as load_ext
    pytorch_dir = '/private/home/fmassa/github/pytorch/test/cpp_extensions'
    source = [
        'extension.cpp',
    ]
    source = [os.path.join(pytorch_dir, s) for s in source]
    return load_ext('multiprocess_bug', source)


_C = compile_ext()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Bug!')
    parser.add_argument('--local_rank', default=0)

    args = parser.parse_args()
    print(args)
```

Run it with
```
python -m torch.distributed.launch --nproc_per_node=8 mwe.py
```

On the first run I tried, I got:
```
Traceback (most recent call last):
  File "mwe.py", line 16, in <module>
    _C = compile_ext()
  File "mwe.py", line 13, in compile_ext
    return load_ext('multiprocess_bug', source)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 361, in load
    return _import_module_from_library(name, build_directory)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 411, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'multiprocess_bug'
Traceback (most recent call last):
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 400, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mwe.py", line 16, in <module>
    _C = compile_ext()
  File "mwe.py", line 13, in compile_ext
    return load_ext('multiprocess_bug', source)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 357, in load
    _build_extension_module(name, build_directory)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 406, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'multiprocess_bug': [1/2] c++ -MMD -MF extension.o.d -DTORCH_EXTENSION_NAME=multiprocess_bug -I/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/lib/include -I/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/lib/include/TH -I/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/lib/include/THC -I/private/home/fmassa/.conda/envs/detectron_v2/include/python3.6m -fPIC -std=c++11 -c /private/home/fmassa/github/pytorch/test/cpp_extensions/extension.cpp -o extension.o
[2/2] c++ -shared extension.o -o multiprocess_bug.so
FAILED: multiprocess_bug.so
c++ -shared extension.o -o multiprocess_bug.so
extension.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "mwe.py", line 16, in <module>
    _C = compile_ext()
  File "mwe.py", line 13, in compile_ext
    return load_ext('multiprocess_bug', source)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 361, in load
    return _import_module_from_library(name, build_directory)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 411, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'multiprocess_bug'
Traceback (most recent call last):
  File "mwe.py", line 16, in <module>
    _C = compile_ext()
  File "mwe.py", line 13, in compile_ext
    return load_ext('multiprocess_bug', source)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 361, in load
    return _import_module_from_library(name, build_directory)
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 411, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/private/home/fmassa/.conda/envs/detectron_v2/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'multiprocess_bug'
```
