### ISSUE TITLE
IndexError: Caught IndexError in DataLoader worker process 0. Original Traceback (most recent call last):

### ISSUE THREAD

**Issue by ayush714** [pytorch/pytorch#63566]
## ❓ Questions and Help
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):

I am getting this error 
```
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/welcome/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/welcome/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/welcome/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/tmp/ipykernel_30887/2750369577.py", line 53, in __getitem__
    target_encoding = tokenizer(
  File "/home/welcome/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2368, in __call__
    return self.batch_encode_plus(
  File "/home/welcome/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2553, in batch_encode_plus
    return self._batch_encode_plus(
  File "/home/welcome/.local/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 438, in _batch_encode_plus
    for key in tokens_and_encodings[0][0].keys():
IndexError: list index out of range
```

and code can be found here:- https://gist.github.com/ayush714/7d0a6e6fc3d0b26e312b10d837b81653

cc @SsnL @VitalyFedyunin @ejguan

**Comment by mruberry** [comment]
Try asking this question on the forums (https://discuss.pytorch.org/) with a self-contained program that demonstrates the issue, @ayush714. The github issues are more appropriate for bug reports.
