### ISSUE TITLE
Cannot specify character encoding in cpp_extension.py for C++ compiler info

### ISSUE THREAD

**Issue by sun-jiao** [pytorch/pytorch#63584]
## 🐛 Bug

Cannot specify character encoding in cpp_extension.py for C++ compiler info and error message. 
UnicodeDecodeError will be raised in Chinese environment.
I think it's a good idea to add a parameter for it.

![Snipaste_2021-08-20_00-40-33](https://user-images.githubusercontent.com/14086980/130109658-b346c02e-611f-4170-b25c-9ffe4d162c9a.jpg)

## To Reproduce

1. Install C++ in Chinese.
1. call cpp_extension

## Expected behavior

```
Traceback (most recent call last):
  File "C:/Users/sunji/PycharmProjects/KAIR/main_test_face_enhancement.py", line 39, in <module>
    from models.network_faceenhancer import FullGenerator as enhancer_net
  File "C:\Users\sunji\PycharmProjects\KAIR\models\network_faceenhancer.py", line 10, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "C:\Users\sunji\PycharmProjects\KAIR\models\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\sunji\PycharmProjects\KAIR\models\op\fused_act.py", line 10, in <module>
    fused = load(
  File "C:\Users\sunji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "C:\Users\sunji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\cpp_extension.py", line 1293, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\sunji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\cpp_extension.py", line 1405, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Users\sunji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\cpp_extension.py", line 1681, in _run_ninja_build
    message += f": {error.output.decode()}"  # type: ignore[union-attr]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 1029: invalid continuation byte
```

## Environment

Windows 10 21H1 Chinese as main display language
python 3.8
pytorch 1.9
Visual Studio 2019

**Comment by mruberry** [comment]
I am not sure how this is related to PyTorch, the deep learning framework. Can you clarify how this is a PyTorch issue and include a sample program we can run to replicate the issue?

**Comment by peterjc123** [comment]
@sun-jiao 

>   File "C:\Users\sunji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\cpp_extension.py", line 1681, in _run_ninja_build
    message += f": {error.output.decode()}"  # type: ignore[union-attr]

Does it help if you change this line to the following one?
```
    message += f": {error.output.decode('oem')}"
```

**Comment by sun-jiao** [comment]
> @sun-jiao
> 
> > File "C:\Users\sunji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\cpp_extension.py", line 1681, in _run_ninja_build
> > message += f": {error.output.decode()}"  # type: ignore[union-attr]
> 
> Does it help if you change this line to the following one?
> 
> ```python
>     message += f": {error.output.decode('oem')}"
> ```

I changed it to ' gbk' (space cannot be ommited) (gbk is China's national standard for character encoding) in yesterday and it worked. But obviously it will not work in every language.

Does 'oem' works for all languages? I'll try it and tell you whether it works.

**Comment by peterjc123** [comment]
@sun-jiao I tried this locally and this should work. Fix is on the way.
