### ISSUE TITLE
Calling backward with create_graph on the output of a DistributedDataParallel throws error

### ISSUE THREAD

**Issue by carlosgmartin** [pytorch/pytorch#63812]
## 🐛 Bug

Calling [`backward`](https://pytorch.org/docs/stable/generated/torch.Tensor.backward.html) with `create_graph=True` on the output of a [`DistributedDataParallel`](https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html) throws a `RuntimeError`.

## To Reproduce

```python3
import torch
from torch import nn
from torch.distributed import init_process_group
from torch.nn.parallel import DistributedDataParallel as DDP

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.p = nn.Parameter(torch.tensor(1.))
    def forward(self):
        return self.p.pow(2)

model = Model()
init_process_group(
    'gloo',
    'tcp://localhost:12355',
    rank=0,
    world_size=1,
)
ddp_model = DDP(model)
ddp_model().backward(create_graph=True)
```

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    ddp_model().backward(create_graph=True)
  File "/usr/local/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: mul(): functions with out=... arguments don't support automatic differentiation, but one of the arguments requires grad.
```

## Expected behavior

No error.

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.5.2 (x86_64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.9)
CMake version: version 3.20.1
Libc version: N/A

Python version: 3.8.8 (default, Feb 27 2021, 02:19:17)  [Clang 12.0.0 (clang-1200.0.32.29)] (64-bit runtime)
Python platform: macOS-11.5.2-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.2.10
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0.dev20210313
[pip3] torchmetrics==0.2.0
[pip3] torchvision==0.10.0
[conda] Could not collect
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
Verified I can repro the issue. The error is coming from at::mul_out here: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/reducer.cpp#L382. It doesn't occur if `create_graph=False` which is the default.

@albanD do you have any suggestions for what `create_graph` changes to result in this error in `at::mul_out`? My thought is that it is because `grad` ends up requiring grad itself because create_graph is for higher order derivatives?

**Comment by albanD** [comment]
Yes, the `out` variants are never differentiable. So if you try to use create_graph=True (which differentiates through the backward), that will fail.

**Comment by mrshenli** [comment]
closing this issue since this is expected behavior.

**Comment by carlosgmartin** [comment]
@mrshenli What do you mean "this is expected behavior"? What's the solution?

**Comment by mrshenli** [comment]
> What do you mean "this is expected behavior"? 

I was referring to DDP does not work with higher-order derivatives is an expected behavior today. 

Re-opening this issue in case the intention was not calculating higher-order derivatives. Could you please share a bit more on the motivation for setting `create_graph=True`? Are you going to calculate grad on grads?

**Comment by carlosgmartin** [comment]
@mrshenli The motivation was indeed to calculate higher-order derivatives. If DDP doesn't support that, a more informative error message would be helpful.

What would it take for DDP to support higher-order derivatives?

**Comment by mrshenli** [comment]
> What would it take for DDP to support higher-order derivatives?

Today's DDP expects interleaving forward-backward passes. For higher-order derivatives, I assume you need to calculate the loss based on the grads and call a 2nd backward? If so, this would mess up DDP's internal states. We probably need to disable DDP's autograd hooks in the first backward, and enable that in the 2nd backward invocation. `DistributedDataParallel.no_sync()` won't work here, as it requires another forward after exiting the context. 

One hacky and dangerous solution might be exposing a private API to toggle this flag. Say, `with ddp._ignore_hooks():`.

https://github.com/pytorch/pytorch/blob/4a0776100e347c887378b676f3deabd14b88d7b2/torch/csrc/distributed/c10d/reducer.cpp#L571


Hey @carlosgmartin, could you pease help us understand what are the applications that require higher-order derivatives? Thanks!

**Comment by rohan-varma** [comment]
We are fixing the crash in #63831 since it is not ideal to crash here, but will also add a warning indicating that DDP doesn't currently support higher order gradients.

**Comment by mcarilli** [comment]
I think it IS ideal to crash here. In current code, DDP-filled leaf grads with a differentiable history are a false, nonsensical promise.

**Comment by carlosgmartin** [comment]
@mrshenli Two examples are:

- Equilibrium-finding: https://arxiv.org/pdf/1905.12103.pdf#page=7

- Variance reduction with control variates: https://arxiv.org/pdf/1711.00123.pdf#page=3

**Comment by carlosgmartin** [comment]
@mcarilli Crashing without an informative error message is definitely not ideal.

**Comment by mcarilli** [comment]
@carlosgmartin informative error message would be good.

Even if allreduces were included in the autograd history, such that double-backwarding from allreduced grads did the right math, it's unclear if the use case makes sense, because at the end of the second backward pass you'd end up with grad values that got allreduced twice.

Right now, the "least bad practice" for interoperating double-backward use cases (eg gradient penalty) with DDP is using `torch.autograd.grad(..., create_graph=True)` to create intermediate grads out of place in each process. The returned out-of-place grads are intercepted before they reach allreduce hooks, and therefore hold purely intraprocess values, but they don't trigger any allreduces. You can use the out-of-place grads in some forward work (e.g. computing a penalty), call an ordinary backward() on the penalty+whatever else, and the backward()'s grads will propagate all the back to the allreduce hooks (some via the double-backward path left by the torch.autograd.grad).

The limitation is that intermediate grads holding purely intraprocess values may or may not be what you want. Maybe you wanted to compute the penalty with allreduced grad values, for example. Please tell us if so. It's trickier, but in theory, doesn't seem impossible.

**Comment by rohan-varma** [comment]
Created a tracking issue for support for this feature: https://github.com/pytorch/pytorch/issues/63929. Gauging how frequently this feature is asked for will help the team prioritize it appropriately.
