### ISSUE TITLE
[TensorExpr] torch.jit.freeze causes CUDA compilation error

### ISSUE THREAD

**Issue by robieta** [pytorch/pytorch#63923]
## 🐛 Bug

This failure was detected in TorchBench: https://github.com/pytorch/benchmark/tree/master/torchbenchmark/models/timm_efficientnet

I've distilled the failure into a pretty minimal repro (apologies for using a third party lib, but hopefully timm is established enough that you'll forgive it.) This is almost certainly from https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/tensorexpr/codegen.cpp

CC @ZolotukhinM @navahgar

## To Reproduce

```
import torch
import timm.models.efficientnet
model = timm.create_model('mixnet_m', pretrained=False, scriptable=True)
model.to(device="cuda", dtype=torch.float32)
jit_model = torch.jit.script(model).eval()

# This line causes the failure.
jit_model = torch.jit.freeze(jit_model)

x = torch.rand((1, 3, 224, 224), device="cuda")
for i in range(10):
    print(f"Begin {i}")
    jit_model(x)
```

```
Begin 0
Begin 1
Traceback (most recent call last):
  File "debug.py", line 13, in <module>
    jit_model(x)
  File "/home/ec2-user/anaconda3/envs/robieta_debug_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1065, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: default_program(18): error: expected a ")"

default_program(18): error: extra text after expected end of number

default_program(18): error: extra text after expected end of number

default_program(21): error: expected a ";"

default_program(21): error: extra text after expected end of number

default_program(21): error: extra text after expected end of number

default_program(22): error: "const_self" has already been declared in the current scope

default_program(22): error: expected a ";"

default_program(22): error: extra text after expected end of number

default_program(22): error: extra text after expected end of number

default_program(23): error: extra text after expected end of number

default_program(23): error: expression must have class type

default_program(23): error: expected a ")"

default_program(23): error: extra text after expected end of number

default_program(23): error: expression must have class type

default_program(23): error: expected a ")"

default_program(23): error: extra text after expected end of number

default_program(23): error: expression must have class type

default_program(23): error: expected a ")"

default_program(23): error: extra text after expected end of number

default_program(23): error: expression must have class type

default_program(23): error: expected a ")"

default_program(23): error: extra text after expected end of number

default_program(23): error: expression must have class type

default_program(23): error: expected a ")"

default_program(23): error: extra text after expected end of number

default_program(23): error: expression must have class type

default_program(23): error: expected a ")"

default_program(21): warning: variable "const_self" was declared but never referenced

28 errors detected in the compilation of "default_program".

nvrtc compilation failed:

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)


template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_cat_batch_norm(float* t_, float* t__, float* aten_batch_norm, float* aten_cat, float* const_self.blocks.1.0.bn1.running_mean, float* const_self.blocks.1.0.bn1.running_var) {
{
  aten_cat[threadIdx.x + 512 * blockIdx.x] = ((((threadIdx.x + 512 * blockIdx.x) / 12544) % 144<72 ? 1 : 0) ? __ldg(t_ + (threadIdx.x + 512 * blockIdx.x) % 1806336) : __ldg(t__ + (threadIdx.x + 512 * blockIdx.x) % 1806336 - 903168));
  float const_self.blocks.1.0.bn1.running_var_1 = __ldg(const_self.blocks.1.0.bn1.running_var + ((threadIdx.x + 512 * blockIdx.x) / 12544) % 144);
  float const_self.blocks.1.0.bn1.running_mean_1 = __ldg(const_self.blocks.1.0.bn1.running_mean + ((threadIdx.x + 512 * blockIdx.x) / 12544) % 144);
  aten_batch_norm[threadIdx.x + 512 * blockIdx.x] = (float)((double)(((((threadIdx.x + 512 * blockIdx.x) / 12544) % 144<72 ? 1 : 0) ? __ldg(t_ + (threadIdx.x + 512 * blockIdx.x) % 1806336) : __ldg(t__ + (threadIdx.x + 512 * blockIdx.x) % 1806336 - 903168
))) * ((rsqrt((double)(const_self.blocks.1.0.bn1.running_var_1) + 1e-05)) * (double)(const_self.blocks.1.0.bn1.running_var_1)) + ((double)(const_self.blocks.1.0.bn1.running_mean_1) - (double)(const_self.blocks.1.0.bn1.running_mean_1) * ((rsqrt((double)(c
onst_self.blocks.1.0.bn1.running_var_1) + 1e-05)) * (double)(const_self.blocks.1.0.bn1.running_var_1))));
}
}
```

## Expected behavior

We should emit legal code. (Or abort / fallback if compilation fails.)

## Environment

TorchBench CI machine. If you can't repro, talk to me and I can get you access. Install is PyTorch nightly as of 08/24, `timm` version 0.4.5, GPU is an Nvidia T4.

```
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

**Comment by ZolotukhinM** [comment]
Thanks for the report, I'll take a look!

**Comment by ZolotukhinM** [comment]
@robieta, if you have a reproducer handy, could you please run the test with the following env variables?
```
PYTORCH_JIT_LOG_LEVEL=">>kernel:>>cuda_codegen"
```

**Comment by robieta** [comment]
@ZolotukhinM Certainly: https://gist.github.com/robieta/38b6306d47f4c77e3b70dd010c11f787
