### ISSUE TITLE
when import torch, an AttributeError is raised saying `` 'module' object has no attribute 'cuda' "

### ISSUE THREAD

**Issue by zengxianyu** [pytorch/pytorch#6412]
A script to reproduce the bug. Please try to provide as minimal of a test case as possible:

There's a file "select.py" in a folder, containing only one line ```from torch.autograd import Variable```

I open a python console in this folder and type ```import torch```, and then an AttributeError: 'module' object has no attribute 'cuda' is raised.

- OS: Ubuntu 14.04
- PyTorch version: '0.3.1.post2'
- How you installed PyTorch (conda, pip, source): conda
- Python version: 2.7
- CUDA/cuDNN version: 8.0
- GPU models and configuration: GTX1080

**Comment by SsnL** [comment]
What does the trace say?

**Comment by zengxianyu** [comment]
@SsnL 

Traceback (most recent call last):
  File "select.py", line 1, in <module>
    from torch.autograd import Variable
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/torch/__init__.py", line 311, in <module>
    import torch.cuda
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 19, in <module>
    from multiprocessing.util import register_after_fork as _register_after_fork
  File "/home/zeng/anaconda2/lib/python2.7/multiprocessing/__init__.py", line 65, in <module>
    from multiprocessing.util import SUBDEBUG, SUBWARNING
  File "/home/zeng/anaconda2/lib/python2.7/multiprocessing/util.py", line 41, in <module>
    from subprocess import _args_from_interpreter_flags
  File "/home/zeng/anaconda2/lib/python2.7/subprocess.py", line 72, in <module>
    import select
  File "/home/zeng/haha/select.py", line 1, in <module>
    from torch.autograd import Variable
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 10, in <module>
    from .variable import Variable
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 502, in <module>
    from ._functions import *
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/torch/autograd/_functions/__init__.py", line 3, in <module>
    from .pointwise import *
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/torch/autograd/_functions/pointwise.py", line 6, in <module>
    from ..._thnn import type2backend
  File "/home/zeng/anaconda2/lib/python2.7/site-packages/torch/_thnn/__init__.py", line 67, in <module>
    type2backend.backends[getattr(torch.cuda, '{}Tensor'.format(py_name))] = backend
AttributeError: 'module' object has no attribute 'cuda'

**Comment by SsnL** [comment]
That is quite weird since all our binaries should have `.cuda` module. Are you sure that no folder named `torch` exists?

**Comment by zengxianyu** [comment]
@SsnL I'm sure there's no folder named torch exists in the folder I run this script. There's no other folder in the folder where I run the script, and the only file in this folder is select.py, which contains only one line ```from torch.autograd import Variable```

**Comment by zengxianyu** [comment]
@SsnL That happens only when the folder contains a file named "select.py". I can import torch without error if I change the filename "select.py" to other strings.

**Comment by SsnL** [comment]
Oh here is your problem:
```
File "/home/zeng/anaconda2/lib/python2.7/site-packages/torch/init.py", line 311, in 
import torch.cuda
File "/home/zeng/anaconda2/lib/python2.7/site-packages/torch/cuda/init.py", line 19, in 
from multiprocessing.util import register_after_fork as _register_after_fork
File "/home/zeng/anaconda2/lib/python2.7/multiprocessing/init.py", line 65, in 
from multiprocessing.util import SUBDEBUG, SUBWARNING
File "/home/zeng/anaconda2/lib/python2.7/multiprocessing/util.py", line 41, in 
from subprocess import _args_from_interpreter_flags
File "/home/zeng/anaconda2/lib/python2.7/subprocess.py", line 72, in 
import select <------ this here
File "/home/zeng/haha/select.py", line 1, in  
from torch.autograd import Variable  
```

Python's multiprocessing module imports select, and due to how Python import works, it imports your file rather than the actual select module. I don't think that we can do much here. Same thing happens if you have 
```
# math.py
print(1/0)

# console
import numpy
```

**Comment by zengxianyu** [comment]
Thank you @SsnL
