### ISSUE TITLE
F.conv2d: confusing error message when using uint8 input instead of float32

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#64145]
```python
import torch
import torchvision

model = torchvision.models.resnet18(pretrained = False)

x = torch.zeros(4, 3, 128, 128, dtype = torch.uint8)

model(x)
```
```
Traceback (most recent call last):
  File "/home/.../lab/vadim/mask2cad_pytorch/bug.py", line 8, in <module>
    model(x)
  File "/home/.../lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/.../lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torchvision/models/resnet.py", line 249, in forward
    return self._forward_impl(x)
  File "/home/.../lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torchvision/models/resnet.py", line 232, in _forward_impl
    x = self.conv1(x)
  File "/home/.../lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/.../lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/.../lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: expected scalar type Byte but found Float
```

**Comment by vadimkantorov** [comment]
I think it's because it's doing dispatch based on the first argument which is input. I think it would be better to have a more verbose message that clears up that input.dtype = torch.uint8 is not compatible with model's weight.dtype = torch.float32 and suggest to make sure input.dtype matches weight.dtype

**Comment by Bleyddyn** [comment]
I ran into the same backwards error message. I think I would have solved my problem a lot faster if the error had been clearer about which type was the correct one.

PyTorch 1.9.1.
