### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by cjfghk5697** [pytorch/pytorch#64414]
## 🐛 Bug

1. System information
Environment: Colab 
all other libraries cloned from 
https://colab.research.google.com/drive/1OmVafk9rWK7fNWW5lEBwiwRjZea3BR2e?usp=sharing
2. Error Code
Full Error code was saved in
 https://colab.research.google.com/drive/1OmVafk9rWK7fNWW5lEBwiwRjZea3BR2e?usp=sharing

# Error code

``` python
    model = MyModelWrapper(model_name, model=model, device=device, optimizer=optimizer, criterion=criterion)
```
# Error

```python
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "<ipython-input-27-a89894855d57>", line 74, in __getitem__
    image = self.transform_fn(image)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 97, in __call__
    return F.to_tensor(pic)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py", line 102, in to_tensor
    raise TypeError('pic should be PIL Image or ndarray. Got {}'.format(type(pic)))
TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>
```
I use a Numpy file. But It happen TypeError in DataLoader.  So I wish want to know how do fix this error.

cc @SsnL @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
Hi,
We use github issues only for bugs or feature requests.
Please use the forum to ask questions:  https://discuss.pytorch.org/

The backtrace is really apparent.
Your image data has already been Tensor, you don't need to transform using `ToTensor().
