### ISSUE TITLE
It' so strange!!!

### ISSUE THREAD

**Issue by fmbao** [pytorch/pytorch#64488]
## To Reproduce
I save model as ptl.The  input shape of this ptl model file is 4 dims. When I load this ptl model on android.It throw an Error.:
```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xiaomi.recordtest, PID: 9775
    com.facebook.jni.CppException: Expected 4 elements in a list but found 3
      
      debug_handle:-1
      
    Exception raised from listUnpack at ../torch/csrc/jit/runtime/vararg_functions.cpp:187 (most recent call first):
    (no backtrace available)
        at org.pytorch.LiteNativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:52)
```

In fact, I input a 4 dims data. When I input 3 dims data ,it throw same Error. When I input 5 dim data, it throws    com.facebook.jni.CppException: Expected 4 elements in a list but found 5.
HHHHH, this error is so funny. Schrodinger's error.

1. 
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by fmbao** [comment]
up  up up

**Comment by fmbao** [comment]
And, when i use ` org.pytorch.Tensor outputTensor = model.forward(IValue.from(inTensor)).toTensor();` It throw the error E/libc: Access denied finding property "ro.hardware.chipname"

**Comment by dreiss** [comment]
Are you able to share the model, or a smaller model that reproduces the issue?

I think the error is referring to the number of elements in a list being unpacked, rather than the number of dims in a tensor.
