### ISSUE TITLE
TestTensorCreationCPU.test_trilu_indices_cpu  crashes in ParallellTBB mode

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#64571]
## To Reproduce

1. Build PyTorch with TBB support:
```
ATEN_THREADING=TBB REL_WITH_DEB_INFO=ON USE_TBB=ON USE_CUDA=OFF BUILD_CAFFE2_OPS=OFF python setup.py develop --user
```
2. Run test_trilu_indices_cpu: it has a roughly 50-50 chance of hitting internal assert or crashing
```
$ python test_tensor_creation_ops.py -v TestTensorCreationCPU.test_trilu_indices_cpu
test_trilu_indices_cpu (__main__.TestTensorCreationCPU) ... ERROR

======================================================================
ERROR: test_trilu_indices_cpu (__main__.TestTensorCreationCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nshulga/git/pytorch/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    raise rte
  File "/home/nshulga/git/pytorch/torch/testing/_internal/common_device_type.py", line 373, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/nshulga/git/pytorch/torch/testing/_internal/common_device_type.py", line 913, in only_fn
    return fn(slf, *args, **kwargs)
  File "test_tensor_creation_ops.py", line 1176, in test_trilu_indices
    _compare_trilu_indices(self, *test_args)
  File "/home/nshulga/git/pytorch/torch/testing/_internal/common_methods_invocations.py", line 9458, in _compare_trilu_indices
    torch.ones(row, col, device='cpu')
RuntimeError: out_ptr == out_accessor[thread_count_nonzero[tid + 1]].data()INTERNAL ASSERT FAILED at "../aten/src/ATen/native/TensorAdvancedIndexing.cpp":1717, please report a bug to PyTorch. 

----------------------------------------------------------------------
Ran 1 test in 0.021s

FAILED (errors=1)

```

## Expected behavior

Test should pass
## Environment

```
Collecting environment information...
PyTorch version: 1.10.0a0+gite161872
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Fedora release 32 (Thirty Two) (x86_64)
GCC version: (GCC) 10.0.1 20200328 (Red Hat 10.0.1-0.11)
Clang version: 10.0.1 (Fedora 10.0.1-3.fc32)
CMake version: version 3.17.4
Libc version: glibc-2.31

Python version: 3.8.7 (default, Jan 20 2021, 00:00:00)  [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] (64-bit runtime)
Python platform: Linux-5.11.12-100.fc32.x86_64-x86_64-with-glibc2.2.5
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 460.73.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.0
[pip3] torch==1.10.0a0+gite161872
[pip3] torchaudio==0.8.1
[conda] Could not collect
```

**Comment by malfet** [comment]
Test is being disabled in https://github.com/pytorch/pytorch/pull/64193, but it was failing for a while, not sure how/why our CI/CD system never hit it before

**Comment by malfet** [comment]
More minimal reproducer:
```
python -c "import torch;print(torch.ones(257,258).tril(1).nonzero())"
```

**Comment by malfet** [comment]
The culprit is the logic in `nonzero_out_cpu` that assumes that thread ids returned by `at::get_thread_num` in two identical `at::parallel_for` loops are the same, but they are no if TBB is used.

Compare those two loops:
https://github.com/pytorch/pytorch/blob/2c351c76e0980fede8020b25adec467635f1c2a0/aten/src/ATen/native/TensorAdvancedIndexing.cpp#L1633-L1637
And
https://github.com/pytorch/pytorch/blob/2c351c76e0980fede8020b25adec467635f1c2a0/aten/src/ATen/native/TensorAdvancedIndexing.cpp#L1660-L1664

But those are not the same, as `tbb::this_task_arena::current_thread_index()` is not sequential for parallel groups less than current concurrency limit, as can be easily verified by adding a debug printfs to the above-mentioned loops, which yield following:
```
// First loop
tid=0 thread_begin[tid] = 0 thread_count_nonzero[tid+1]=2208
tid=5  thread_begin[tid] = 16576 thread_count_nonzero[tid+1]=6305
tid=2  thread_begin[tid] = 49729 thread_count_nonzero[tid+1]=14497
tid=3 thread_begin[tid] = 33153 thread_count_nonzero[tid+1]=10400
// Second loop
tid=0 thread_being[tid]=0 being=0
tid=3 thread_being[tid]=33153 being=33153
tid=5 thread_being[tid]=16576 being=49729
tid=1 thread_being[tid]=-1 being=16576
```

**Comment by ngimel** [comment]
cc @peterbell10, indeed, `tbb` does not guarantee that this thread will have the same thread id in the different parallel regions.
