### ISSUE TITLE
Four distributions tests are failing on Windows

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#64595]
Relevant snippet:

```
======================================================================
ERROR [0.034s]: test_binomial_sample (__main__.TestDistributions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "distributions/test_distributions.py", line 1060, in test_binomial_sample
    self._check_sampler_discrete(Binomial(total_count=count, probs=prob),
  File "distributions/test_distributions.py", line 812, in _check_sampler_discrete
    chisq, p = scipy.stats.chisquare(counts[msk], pmf[msk] * num_samples)
  File "C:\Jenkins\Miniconda3\lib\site-packages\scipy\stats\stats.py", line 6852, in chisquare
    return power_divergence(f_obs, f_exp=f_exp, ddof=ddof, axis=axis,
  File "C:\Jenkins\Miniconda3\lib\site-packages\scipy\stats\stats.py", line 6694, in power_divergence
    raise ValueError(msg)
ValueError: For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are:
0.00010002000400080016

======================================================================
ERROR [0.000s]: test_geometric_sample (__main__.TestDistributions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "distributions/test_distributions.py", line 1042, in test_geometric_sample
    self._check_sampler_discrete(Geometric(prob),
  File "distributions/test_distributions.py", line 812, in _check_sampler_discrete
    chisq, p = scipy.stats.chisquare(counts[msk], pmf[msk] * num_samples)
  File "C:\Jenkins\Miniconda3\lib\site-packages\scipy\stats\stats.py", line 6852, in chisquare
    return power_divergence(f_obs, f_exp=f_exp, ddof=ddof, axis=axis,
  File "C:\Jenkins\Miniconda3\lib\site-packages\scipy\stats\stats.py", line 6694, in power_divergence
    raise ValueError(msg)
ValueError: For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are:
0.008265582255680495

======================================================================
ERROR [0.000s]: test_poisson_gpu_sample (__main__.TestDistributions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "distributions/test_distributions.py", line 1362, in test_poisson_gpu_sample
    self._check_sampler_discrete(Poisson(torch.tensor([rate]).cuda()),
  File "distributions/test_distributions.py", line 812, in _check_sampler_discrete
    chisq, p = scipy.stats.chisquare(counts[msk], pmf[msk] * num_samples)
  File "C:\Jenkins\Miniconda3\lib\site-packages\scipy\stats\stats.py", line 6852, in chisquare
    return power_divergence(f_obs, f_exp=f_exp, ddof=ddof, axis=axis,
  File "C:\Jenkins\Miniconda3\lib\site-packages\scipy\stats\stats.py", line 6694, in power_divergence
    raise ValueError(msg)
ValueError: For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are:
3.6727285765597826e-05

======================================================================
ERROR [0.000s]: test_poisson_sample (__main__.TestDistributions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "distributions/test_distributions.py", line 1352, in test_poisson_sample
    self._check_sampler_discrete(Poisson(rate),
  File "distributions/test_distributions.py", line 812, in _check_sampler_discrete
    chisq, p = scipy.stats.chisquare(counts[msk], pmf[msk] * num_samples)
  File "C:\Jenkins\Miniconda3\lib\site-packages\scipy\stats\stats.py", line 6852, in chisquare
    return power_divergence(f_obs, f_exp=f_exp, ddof=ddof, axis=axis,
  File "C:\Jenkins\Miniconda3\lib\site-packages\scipy\stats\stats.py", line 6694, in power_divergence
    raise ValueError(msg)
ValueError: For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are:
4.535600093557479e-05
```

from https://github.com/pytorch/pytorch/runs/3536602436

**Comment by fritzo** [comment]
I think we can fix this by rescaling in a normalized way.
```diff
- scipy.stats.chisquare(counts[msk], pmf[msk] * num_samples)
+ counts_msk = counts[msk]
+ pmf_msk = pmf[msk]
+ pmf_msg = pmf_msk * (counts_msk.sum() / pmf_msk.sum())
- scipy.stats.chisquare(counts_msk, pmf_msk)
```

**Comment by malfet** [comment]
Likely related to https://github.com/pytorch/pytorch/issues/60347 (As it started to happen after scipy update on Windows)

**Comment by malfet** [comment]
Should it be closed as duplicate of https://github.com/pytorch/pytorch/issues/64595

**Comment by jbschlosser** [comment]
Doesn't that link back to this same issue?

**Comment by malfet** [comment]
Closing this one, will update another issue with the current status
@fritzo if you have a change in mind, please do not hesitate to create a PR
