### ISSUE TITLE
Error when exiting tutorial script

### ISSUE THREAD

**Issue by SNEKBOI** [pytorch/pytorch#6461]
OS: 
Ubuntu 18.04

PyTorch version:  
0.3.1.post2

Python version:
3.6.5

How you installed PyTorch:
conda install pytorch-cpu torchvision -c pytorch

Script to reproduce the bug:
the tutorial script for cifar10 classification: http://pytorch.org/tutorials/_downloads/cifar10_tutorial.py

At the end of the script execution, I have the following error message:
```
Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f0b579b8470>>
Traceback (most recent call last):
  File "/home/snakeone/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 333, in __del__
  File "/home/snakeone/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 319, in _shutdown_workers
  File "/home/snakeone/anaconda3/envs/torch/lib/python3.6/multiprocessing/queues.py", line 337, in get
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by SsnL** [comment]
I am aware of this and will have a fix.
