### ISSUE TITLE
[jit] cannot compile staticmethod of classes when they have a unscriptable __init__

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#64628]
## 🐛 Bug

Calling a staticmethod of a class has nothing to do with the class's `__init__`. However, it seems torchscript requires `__init__` to be scriptable in order to script the staticmethod.

## To Reproduce

```python
import torch

class A:
    pass

class B(A):
    def __init__(self):
        super().__init__()

    @staticmethod
    def test(x):
        return x + 1


def f(image):
    return B.test(image)

script_f = torch.jit.script(f)
```
```
Traceback (most recent call last):
  File "/test/a.py", line 19, in <module>
    script_f = torch.jit.script(f)
  File "/home/test/.local/lib/python3.9/site-packages/torch/jit/_script.py", line 1143, in script
    fn = torch._C._jit_script_compile(
  File "/home/test/.local/lib/python3.9/site-packages/torch/jit/annotations.py", line 364, in try_ann_to_type
    return torch.jit._script._recursive_compile_class(ann, loc)
  File "/home/test/.local/lib/python3.9/site-packages/torch/jit/_script.py", line 1260, in _recursive_compile_class
    return _compile_and_register_class(obj, rcb, _qual_name)
  File "/home/test/.local/lib/python3.9/site-packages/torch/jit/_script.py", line 138, in _compile_and_register_class
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError: 
'Tensor' object has no attribute or method '__init__'.:
  File "/test/a.py", line 9
    def __init__(self):
        super().__init__()
        ~~~~~~~~~~~~~~ <--- HERE
'B.__init__' is being compiled since it was called from '__torch__.B'
  File "/test/a.py", line 17
def f(image):
    return B.test(image)
           ~ <--- HERE
'__torch__.B' is being compiled since it was called from 'f'
  File "/test/a.py", line 17
def f(image):
    return B.test(image)
           ~~~~~~~~~~~~ <--- HERE


```

## Expected behavior

I expect `B.test` to be jit-scriptable. This should have nothing to do with `__init__`.
Removing `B.__init__` can make it scriptable.

In the real use case, `B.__init__` contains useful unscriptable code that we need in eager mode, but we only need to script `B.test`.

## Environment

 - PyTorch Version (e.g., 1.0): 1.9
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.9

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
