### ISSUE TITLE
Add support to profiler to profile all threads on a process

### ISSUE THREAD

**Issue by gcramer23** [pytorch/pytorch#64799]
## 🚀 Feature

Add support to the profiler to profile all threads that are run on a process.

## Motivation

It is hard to gain visibility into parameter server implementations with the current state of the profiler. A vanilla parameter server implementation using RPC will have a @rpc.functions.async_execution decorated function. This function will be executed by worker threads created during the RPC initialization. The code below is an example of a parameter server implementation.

```python
import os
from threading import Lock

import torch
import torch.distributed.rpc as rpc
import torch.multiprocessing as mp
import torch.nn as nn
from torch.distributed.rpc import RRef, TensorPipeRpcBackendOptions
from torch.profiler import ProfilerActivity, profile


class MyParameterServer:
    def __init__(self, trainers):
        self.lock = Lock()
        self.trainers = trainers
        self.iteration = 0
        self.updates = 0
        self.futures = []
        self.total = None
        self.gradient = None
        self.p = profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA])
        self.p.start()

    @staticmethod
    def get_gradient(rref):
        return rref.local_value().gradient

    @staticmethod
    def stop(rref):
        self = rref.local_value()
        self.p.stop()

    @staticmethod
    @rpc.functions.async_execution
    def average(rref, riteration, tensor):
        self = rref.local_value()
        fut = torch.futures.Future()
        with self.lock:
            if riteration > self.iteration:
                self.iteration = riteration
                self.updates = 0
                self.futures.clear()
            self.futures.append(fut)
            if self.total is None:
                self.total = tensor
            else:
                self.total += tensor
            self.updates += 1
            if self.trainers == self.updates:
                self.gradient = self.total / float(self.trainers)
                for fut in self.futures:
                    result = self.total / float(self.trainers)
                    fut.set_result(result)
        return fut


class MyEmbeddingBagModel(torch.nn.Module):
    def __init__(self, sparse):
        super().__init__()
        self.eb = torch.nn.EmbeddingBag(
            10,
            10,
            sparse=sparse
        )

    def forward(self, x):
        return self.eb(x)


def trainer_func(rref, sparse=False):
    m = MyEmbeddingBagModel(sparse=sparse)
    loss_fn = nn.MSELoss()
    for i in range(10):
        outputs = m(torch.rand(10, 10).long())
        loss_fn(outputs, torch.rand(10, 10)).backward()
        gradient = list(m.parameters())[0].grad
        fut = rref.rpc_async().average(rref, i, gradient.to_sparse())
        fut.wait()


def basic_ps(rank, world_size):
    rpc_backend_options = TensorPipeRpcBackendOptions(
        num_worker_threads=2
    )
    os.environ['MASTER_ADDR'] = "localhost"
    os.environ['MASTER_PORT'] = "12345"
    if rank == 0:
        rpc.init_rpc(
            f"server{rank}",
            rank=rank,
            world_size=world_size,
            rpc_backend_options=rpc_backend_options
        )
        ps_rref = RRef(MyParameterServer(2))
        futures = []
        for index in range(1, world_size):
            futures.append(
                rpc.rpc_async(
                    f"trainer{index}",
                    trainer_func,
                    args=(
                        ps_rref,
                    ),
                )
            )
        torch.futures.wait_all(futures)
        ps_rref.rpc_sync().stop(ps_rref)
    else:
        rpc.init_rpc(
            f"trainer{rank}",
            rank=rank,
            world_size=world_size,
            rpc_backend_options=rpc_backend_options
        )

    rpc.shutdown()


class MyModel(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.fc = torch.nn.Linear(4, 4)

    def forward(self, x):
        return self.fc(x)


if __name__ == "__main__":
    mp.spawn(basic_ps, nprocs=3, args=(3,))

```

## Pitch

The profiler profiles all threads that are run on a process.  In the code below, the profiler is started on a process that runs a created thread. The profiler does not profile the created thread, which is seen in the trace.

```python
import threading

import torch
from torch.profiler import ProfilerActivity, profile


def basic_add():
    x = torch.rand(1000, 1000).to_sparse() + torch.rand(1000, 1000).to_sparse()


def main():
    p = profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA])
    p.start()
    threads = []
    for i in range(1):
        threads.append(threading.Thread(target=basic_add))
        threads[i].start()
    for i in range(1):
        threads[i].join()
    p.stop()
    p.export_chrome_trace("basic_add.json")


if __name__ == "__main__":
    main()

```

<img width="1630" alt="Screen Shot 2021-09-09 at 23 43 07" src="https://user-images.githubusercontent.com/80843680/132796500-dc03d772-ad05-4378-9bcc-e483c1494820.png">

## Additional context

The screenshot below is an example of what is expected in the trace.
<img width="1632" alt="Screen Shot 2021-09-09 at 23 43 41" src="https://user-images.githubusercontent.com/80843680/132796788-c131c109-2166-49ce-ab6e-868bbbf8c0a7.png">

[traces.zip](https://github.com/pytorch/pytorch/files/7141142/traces.zip)

**Comment by gdankel** [comment]
Hi @gcramer23, can you elaborate a little: What do you see in the collected profile currently and what do you want to see?

**Comment by pritamdamania87** [comment]
@gcramer23 I think if you just enable the profiler on the client side, it should profile everything including execution on the server side, ex:

```
with torch.profiler.profile(...)
   res = rpc.sync(...)
 ```
 cc @rohan-varma

**Comment by gcramer23** [comment]
client side profiling does not capture execution when I use rpc_sync.

![Screen Shot 2021-09-14 at 10 09 28](https://user-images.githubusercontent.com/80843680/133273893-466a17e9-fba1-45b5-ba75-c5c2e5d4523b.png)

```python
def create_tensor():
    x = torch.rand(10)
    y = torch.rand(10)
    z = torch.add(x, y)
    return z

def worker_func(rank):
    with torch.profiler.profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as p:
        for i in range(10):
            ret = rpc.rpc_sync(to="server0",func=create_tensor)
    p.export_chrome_trace(f"create_tensor.json")
```

local run

![Screen Shot 2021-09-14 at 10 10 03](https://user-images.githubusercontent.com/80843680/133273969-5359d207-046e-4c9f-ad95-6ec0cd98a869.png)

```python
def create_tensor():
    x = torch.rand(10)
    y = torch.rand(10)
    z = torch.add(x, y)
    return z

def worker_func(rank):
    with torch.profiler.profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as p:
        for i in range(10):
            ret = create_tensor()
    p.export_chrome_trace(f"create_tensor_local.json")
```

[create_tensor_traces.zip](https://github.com/pytorch/pytorch/files/7162649/create_tensor_traces.zip)

**Comment by gcramer23** [comment]
@gdankel 
> Hi @gcramer23, can you elaborate a little: What do you see in the collected profile currently and what do you want to see?

I want to start a profiler on the server side and stop the profiler on the server side with an RPC call.

```python
  @staticmethod
  def stop(rref):
      self = rref.local_value()
      self.p.stop()
```
If I start the profiler on the server side during the class init, the profiler will be on a thread. When I call the server to stop the profiler, it will crash if it is not the same thread because I didn't start the profiler on that thread.

```
On WorkerInfo(id=0, name=server0):
RuntimeError("Can't disable Kineto profiler when it's not running",)
Traceback (most recent call last):
  File "/fsx/users/gcramer/work/pytorch/torch/distributed/rpc/internal.py", line 204, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
  File "/fsx/users/gcramer/work/pytorch/torch/distributed/rpc/functions.py", line 162, in wrapper
    return fn(*args, **kwargs)
  File "/fsx/users/gcramer/work/pytorch/torch/distributed/rpc/rref_proxy.py", line 13, in _local_invoke_async_execution
    return getattr(rref.local_value(), func_name)(*args, **kwargs)
  File "/fsx/users/gcramer/work/pytorch/torch/distributed/rpc/functions.py", line 162, in wrapper
    return fn(*args, **kwargs)
  File "/data/home/gcramer/cluster/work/pytorch/benchmarks/distributed/rpc/parameter_server/test.py", line 54, in average
    self.p.stop()
  File "/fsx/users/gcramer/work/pytorch/torch/profiler/profiler.py", line 270, in stop
    self._exit_actions()
  File "/fsx/users/gcramer/work/pytorch/torch/profiler/profiler.py", line 425, in _exit_actions
    self._stop_trace()
  File "/fsx/users/gcramer/work/pytorch/torch/profiler/profiler.py", line 453, in _stop_trace
    self.profiler.__exit__(None, None, None)
  File "/fsx/users/gcramer/work/pytorch/torch/autograd/profiler.py", line 202, in __exit__
    self.kineto_results = _disable_profiler()
RuntimeError: Can't disable Kineto profiler when it's not running

terminate called after throwing an instance of 'c10::Error'
  what():  Expected debug info of type 2
Exception raised from _pop at /fsx/users/gcramer/work/pytorch/c10/util/ThreadLocalDebugInfo.cpp:48 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7fef9abfb54b in /fsx/users/gcramer/work/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xce (0x7fef9abf719e in /fsx/users/gcramer/work/pytorch/torch/lib/libc10.so)
frame #2: c10::ThreadLocalDebugInfo::_pop(c10::DebugInfoKind) + 0x692 (0x7fef9abfdff2 in /fsx/users/gcramer/work/pytorch/torch/lib/libc10.so)
frame #3: torch::autograd::profiler::disableProfilerLegacy(c10::optional<torch::autograd::profiler::ProfilerDisableOptions>) + 0xe5 (0x7fefac2f7da5 in /fsx/users/gcramer/work/pytorch/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x3e312ed (0x7fefac9cb2ed in /fsx/users/gcramer/work/pytorch/torch/lib/libtorch_cpu.so)
frame #5: torch::distributed::rpc::RequestCallbackNoPython::processRunWithProfilingReq(torch::distributed::rpc::RpcCommandBase&) const + 0x6c9 (0x7fefac9c9c99 in /fsx/users/gcramer/work/pytorch/torch/lib/libtorch_cpu.so)
frame #6: torch::distributed::rpc::RequestCallbackNoPython::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType const&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x285 (0x7fefac9ca345 in /fsx/users/gcramer/work/pytorch/torch/lib/libtorch_cpu.so)
frame #7: torch::distributed::rpc::RequestCallbackImpl::processRpcWithErrors(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType const&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x65 (0x7fefb36ce645 in /fsx/users/gcramer/work/pytorch/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x3e29e93 (0x7fefac9c3e93 in /fsx/users/gcramer/work/pytorch/torch/lib/libtorch_cpu.so)
frame #9: torch::distributed::rpc::RequestCallbackNoPython::processMessage(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x4b4 (0x7fefac9c49f4 in /fsx/users/gcramer/work/pytorch/torch/lib/libtorch_cpu.so)
frame #10: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&, std::vector<c10::Stream, std::allocator<c10::Stream> >) const + 0x57 (0x7fefac9bfc07 in /fsx/users/gcramer/work/pytorch/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x3e5e442 (0x7fefac9f8442 in /fsx/users/gcramer/work/pytorch/torch/lib/libtorch_cpu.so)
frame #12: c10::ThreadPool::main_loop(unsigned long) + 0x2db (0x7fef9abe99fb in /fsx/users/gcramer/work/pytorch/torch/lib/libc10.so)
frame #13: <unknown function> + 0xbd6df (0x7fefc223a6df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #14: <unknown function> + 0x76db (0x7fefe7afc6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #15: clone + 0x3f (0x7fefe6e7871f in /lib/x86_64-linux-gnu/libc.so.6)
```
So I see nothing when starting the profiler on the server side during class init.

If I start the profiler on an RPC worker thread, and there are N threads, I can't profile the N - 1 threads.

**Comment by rohan-varma** [comment]
@pritamdamania87 @gcramer23 The feature to enable the profiler remotely was built for `torch.autograd.profiler` (`torch.profiler` did not exist at the time), and I don't think we enabled this for `torch.profiler` yet (there were also thoughts about deprecating this feature - cc @ilia-cher). 

@gcramer23 The profiler will only be enabled on the thread it is created on, and we only propagate profiler across a few boundaries i.e. autograd, JIT fork. If we want to enable the profiler across all RPC worker threads, we'd need some way for these worker threads to understand that the profiler should be on and set the appropriate thread local state.
