### ISSUE TITLE
Distributed Elastic Training Got Stuck on Rendezvous Stage With Multiple NICs

### ISSUE THREAD

**Issue by vycezhong** [pytorch/pytorch#64926]
## 🐛 Bug

I launched a simple distributed job with new distributed APIs in PyTorch v1.9.0 but got stuck on rendezvous stage. 

But it works when I use old APIs (`rdzv_backend=static` and specify `node_rank`).  

## To Reproduce

Here is the script. 
```sh
#!/bin/bash

NNODES=2
NPROC_PER_NODE=2
MASTER_IP=10.28.1.16

python -m torch.distributed.run \
	--nnodes=$NNODES --nproc_per_node=$NPROC_PER_NODE \
	--rdzv_id=1234 --rdzv_backend=c10d \
	--rdzv_endpoint=$MASTER_IP \
	main.py
```

The `main.py` is still under development and here is the code. 
```py
import argparse
import os
from datetime import timedelta

import torch

parser = argparse.ArgumentParser(
    description='Pipeline Parallel ResNet50 Arguments')
parser.add_argument('--pipeline-model-parallel-size', type=int,
                    default=1, help='Degree of pipeline model parallelism')
parser.add_argument('--num-classes', type=int, default=1000,
                    help='num of classes in vision classification task')
parser.add_argument('--micro-batch-size', type=int, default=None,
                    help='Batch size per model instance (local batch size).')
parser.add_argument('--global-batch-size', type=int,
                    default=None, help='Training batch size.')


def main():
    args = parser.parse_args()

    args.world_size = int(os.environ['WORLD_SIZE'])
    args.rank = int(os.environ['RANK'])
    args.local_rank = int(os.environ['LOCAL_RANK'])

    torch.cuda.set_device(args.local_rank)
    torch.distributed.init_process_group(
        'nccl', world_size=args.world_size, rank=args.rank,
        timeout=timedelta(seconds=10)
    )


if __name__ == '__main__':
    main()
```

I run the script on both machines and then the program stuck on rendezvous stage. 

```sh
(yczhong) ➜  pipeline_resnet50 git:(pytorch-pipeline) ✗ ./run.sh
[INFO] 2021-09-13 22:17:26,651 run: Running torch.distributed.run with args: ['/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/run.py', '--nnodes=2', '--nproc_per_node=2', '--rdzv_id=1234', '--rdzv_backend=c10d', '--rdzv_endpoint=10.28.1.16', 'main.py']
[INFO] 2021-09-13 22:17:26,653 run: Using nproc_per_node=2.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
[INFO] 2021-09-13 22:17:26,653 api: Starting elastic_operator with launch configs:
  entrypoint       : main.py
  min_nodes        : 2
  max_nodes        : 2
  nproc_per_node   : 2
  run_id           : 1234
  rdzv_backend     : c10d
  rdzv_endpoint    : 10.28.1.16
  rdzv_configs     : {'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

[ERROR] 2021-09-13 22:18:26,678 error_handler: {
  "message": {
    "message": "RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py\", line 146, in _create_tcp_store\n    host, port, is_master=is_server, timeout=timedelta(seconds=read_timeout)\nRuntimeError: connect() timed out.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 348, in wrapper\n    return f(*args, **kwargs)\n  File \"/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/launcher/api.py\", line 214, in launch_agent\n    rdzv_handler = rdzv_registry.get_rendezvous_handler(rdzv_parameters)\n  File \"/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/registry.py\", line 64, in get_rendezvous_handler\n    return handler_registry.create_handler(params)\n  File \"/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/api.py\", line 253, in create_handler\n    handler = creator(params)\n  File \"/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/registry.py\", line 35, in _create_c10d_handler\n    backend, store = create_backend(params)\n  File \"/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py\", line 204, in create_backend\n    store = _create_tcp_store(params)\n  File \"/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py\", line 165, in _create_tcp_store\n    ) from exc\ntorch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.\n",
      "timestamp": "1631542706"
    }
  }
}
Traceback (most recent call last):
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 146, in _create_tcp_store
    host, port, is_master=is_server, timeout=timedelta(seconds=read_timeout)
RuntimeError: connect() timed out.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/run.py", line 637, in <module>
    main()
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/run.py", line 629, in main
    run(args)
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/run.py", line 624, in run
    )(*cmd_args)
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 214, in launch_agent
    rdzv_handler = rdzv_registry.get_rendezvous_handler(rdzv_parameters)
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 64, in get_rendezvous_handler
    return handler_registry.create_handler(params)
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/api.py", line 253, in create_handler
    handler = creator(params)
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 35, in _create_c10d_handler
    backend, store = create_backend(params)
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 204, in create_backend
    store = _create_tcp_store(params)
  File "/home/yczhong/.conda/envs/yczhong/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 165, in _create_tcp_store
    ) from exc
torch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.
```

## Expected behavior

It should go well.

## Environment

```sh
(yczhong) ➜  snippets python collect_env.py
Collecting environment information...
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Clang version: 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
CMake version: version 3.19.6
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-123-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla P100-PCIE-12GB
GPU 1: Tesla P100-PCIE-12GB

Nvidia driver version: 455.32.00
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torchvision               0.10.0                   pypi_0    pypi
```

## Additional context

Each machine has two NICs. One is `eth0` and the other is `eth2`. The `eth2` NIC is connected to a 50 Gbps switch and thus we prefer to use it. 

Machine One: 
- `eth0`: 202.45.128.221
- `eth2`: 10.28.1.16

Machine Two:
- `eth0`: 202.45.128.222
- `eth2`: 10.28.1.17

`ifconfig` on Machine One
```sh
(yczhong) ➜  ~ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.16.60.1  netmask 255.255.255.0  broadcast 172.16.60.255
        ether 02:42:67:9e:a9:51  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 202.45.128.221  netmask 255.255.255.0  broadcast 202.45.128.255
        inet6 fe80::6613:8ce9:ab05:d1c8  prefixlen 64  scopeid 0x20<link>
        ether ac:1f:6b:24:b5:f8  txqueuelen 1000  (Ethernet)
        RX packets 290000592  bytes 258506800001 (258.5 GB)
        RX errors 0  dropped 55274  overruns 2676  frame 0
        TX packets 112088042  bytes 51296182408 (51.2 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xfbe20000-fbe3ffff

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether ac:1f:6b:24:b5:f9  txqueuelen 1000  (Ethernet)
        RX packets 2114414  bytes 723008317 (723.0 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5438164  bytes 906272443 (906.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xfbe00000-fbe1ffff

eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.28.1.16  netmask 255.255.255.0  broadcast 10.28.1.255
        inet6 fe80::ee0d:9aff:fe6f:a336  prefixlen 64  scopeid 0x20<link>
        ether ec:0d:9a:6f:a3:36  txqueuelen 1000  (Ethernet)
        RX packets 945893601  bytes 1414369686495 (1.4 TB)
        RX errors 0  dropped 111121  overruns 0  frame 0
        TX packets 756968333  bytes 1124135505920 (1.1 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4476984934  bytes 1009599979392 (1.0 TB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4476984934  bytes 1009599979392 (1.0 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tunl0: flags=193<UP,RUNNING,NOARP>  mtu 1440
        inet 192.168.70.192  netmask 255.255.255.255
        tunnel   txqueuelen 1000  (IPIP Tunnel)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

And I am sure two machines can talk to each other.

```sh
(yczhong) ➜  ~ ping 10.28.1.17
PING 10.28.1.17 (10.28.1.17) 56(84) bytes of data.
64 bytes from 10.28.1.17: icmp_seq=1 ttl=64 time=0.239 ms
64 bytes from 10.28.1.17: icmp_seq=2 ttl=64 time=0.158 ms
64 bytes from 10.28.1.17: icmp_seq=3 ttl=64 time=0.150 ms
^C
--- 10.28.1.17 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2055ms
rtt min/avg/max/mdev = 0.150/0.182/0.239/0.041 ms
(yczhong) ➜  ~ ping 202.45.128.222
PING 202.45.128.222 (202.45.128.222) 56(84) bytes of data.
64 bytes from 202.45.128.222: icmp_seq=1 ttl=64 time=0.244 ms
64 bytes from 202.45.128.222: icmp_seq=2 ttl=64 time=0.184 ms
^C
--- 202.45.128.222 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1015ms
rtt min/avg/max/mdev = 0.184/0.214/0.244/0.030 ms
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @cbalioglu @gcramer23

**Comment by pritamdamania87** [comment]
@vycezhong If you don't specify any port, port number 29400 is used for rendezvous. Could you check connectivity across both nodes for that port? In certain setups it is possible to ping nodes, but a firewall might block connectivity on TCP/IP ports.

Another thing you can try out is just run on a single node with two processes to check if everything works fine.

**Comment by vycezhong** [comment]
@pritamdamania87 I am sure port number 29400 is available. 

On 10.28.1.17 
```sh
(yczhong) ➜  ~ nc -l 29400
```

On 10.28.16
```sh
(yczhong) ➜  ~ nc -z -v 10.28.1.17 29400
Connection to 10.28.1.17 29400 port [tcp/*] succeeded!
```

> Another thing you can try out is just run on a single node with two processes to check if everything works fine.

It only works when I use "localhost" as `rdzv_endpoint`.  If I use its IP address (10.28.1.16) then it still didn't work.

**Comment by vycezhong** [comment]
**[Update]** It cannot work on two Amazon g4dn.xlage instances either. I got the same error.

**Comment by vycezhong** [comment]
@pritamdamania87  I am sure that port number 29400 is available. I tested it with `nc` command. 

> Another thing you can try out is just run on a single node with two processes to check if everything works fine.

It only works when `rdzv_endpoint` is "localhost" and fails when `rdzv_endpoint` is 10.28.1.16.

**Comment by pritamdamania87** [comment]
cc @cbalioglu

**Comment by pritamdamania87** [comment]
@vycezhong It looks like TCPStore might prefer IPv6 over IPv4 and that could be a potential reason for this issue. Could you try the IPv6 address instead and see if that works?

**Comment by vycezhong** [comment]
@pritamdamania87 It did not work with IPv6 address.

**Comment by rohan-varma** [comment]
@cbalioglu @H-Huang do you know why this would work with an older version of torch.distributed.run/torch.distributed.launch (i.e. rdzv_backend=static and node_rank) but not with the new approach? Wondering if the rendezvous process is somehow different and resulting in this timeout error.

**Comment by cbalioglu** [comment]
@vycezhong Are this issue and #64990 related? Have you tried using that fix here as well?

**Comment by vycezhong** [comment]
@cbalioglu Unfortunately, it did not help here. It still got an timeout error even if I specify `NCCL_SOCKET_IFNAME=enp94s0`.

**Comment by cbalioglu** [comment]
cc @kiukchung @aivanou

**Comment by kiukchung** [comment]
Looks like a classic dual stack IP issue for TCPStore. @vycezhong  can you try setting up `/etc/gai.conf` as suggested here: https://github.com/pytorch/pytorch/pull/49124#issuecomment-885341914 (the context of the problem is also noted in that PR).

One way to isolate the problem to elastic or TCPStore is by running the `main.py` manually as:

```
# assuming init_method = "env://"

$ MASTER_PORT=29500 MASTER_ADDR=10.28.1.16 WORLD_SIZE=2 RANK=0 python main.py
$ MASTER_PORT=29500 MASTER_ADDR=10.28.1.16 WORLD_SIZE=2 RANK=1 python main.py
```

if that works then there's an issue with elastic if that doesn't work then its TCPStore.

**Comment by vycezhong** [comment]
@kiukchung Thank you very much for your reply. 

The command returns `False` on the master node (10.28.1.16) whose hostname is "net-g1". It works after explicitly passing `--rdzv_conf is_host=true` on the master node. 

So basically I should use the hostname instead of the ip address as the `rdzv_endpoint`?

**Comment by vycezhong** [comment]
Interestingly, the same command returns `True` in my Amazon g4dn.xlarge instance. (https://github.com/pytorch/pytorch/issues/64990)

Other information
```sh
(dev) ➜  ~ hostname
ip-172-30-2-12
(dev) ➜  ~ cat /etc/hosts
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
(dev) ➜  ~
```

https://github.com/pytorch/pytorch/blob/d69c22dd61a2f006dcfe1e3ea8468a3ecaf931aa/torch/distributed/elastic/rendezvous/utils.py#L133-L135
The above function call returns 
```sh
(dev) ➜  snippets python test.py
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, 'ip-172-30-2-12', ('172.30.2.12', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('172.17.0.1', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::849:bdff:fe5d:f1ec', 0, 0, 0))]
True
```
