### ISSUE TITLE
torch.nn.functional.linear function doesn't validate weight dimension == 2

### ISSUE THREAD

**Issue by poutyface** [pytorch/pytorch#64978]
## 🐛 Bug
torch.nn.functional.linear function doesn't validate weight dimension == 2. 
It only asserts  weight.t() expects a tensor with <= 2 dimension.

From doc: https://pytorch.org/docs/stable/generated/torch.nn.functional.linear.html#torch.nn.functional.linear
```
 Weight: (out_features,in_features)
```

For example, it works with weight 1-d
```
>>> import torch
>>> a = torch.ones([1,1,10])
>>> b = torch.ones([10])   # weight is 1-d
>>> c = torch.nn.functional.linear(a, b)
>>> c
tensor([[10.]])
```
But, **onnx.export** is fail on torch v1.9.0, otherwise torch v1.8.0 ~ v1.4.0 works. 

## To Reproduce

```
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, a):
        b = torch.ones([10])
        return F.linear(a, b)

net = Net()
a = torch.ones([1,1,10])
out = net(a)
print(out)
torch.onnx.export(net, (a,), "tmp.onnx")
```

stdout:
```
tensor([[10.]])
[W shape_type_inference.cpp:419] Warning: Constant folding in symbolic shape inference fails: number of dims don't match in permute
Exception raised from permute at /pytorch/aten/src/ATen/native/TensorShape.cpp:934 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f5d363dba22 in /usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x5f (0x7f5d363d84af in /usr/local/lib/python3.8/dist-packages                                          /torch/lib/libc10.so)
frame #2: at::native::permute(at::Tensor const&, c10::ArrayRef<long>) + 0x407 (0x7f5d7a0150d7 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_                                          cpu.so)
frame #3: <unknown function> + 0x1af6e02 (0x7f5d7a853e02 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x194020c (0x7f5d7a69d20c in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #5: at::redispatch::permute(c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<long>) + 0x61 (0x7f5d7a69d7a1 in /usr/local/lib/python3.8/dist-pack                                          ages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x34c1a5f (0x7f5d7c21ea5f in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x34c1dc5 (0x7f5d7c21edc5 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x194020c (0x7f5d7a69d20c in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #9: at::redispatch::permute(c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<long>) + 0x61 (0x7f5d7a69d7a1 in /usr/local/lib/python3.8/dist-pack                                          ages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x2f965d4 (0x7f5d7bcf35d4 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x2f96975 (0x7f5d7bcf3975 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #12: at::Tensor::permute(c10::ArrayRef<long>) const + 0x12c (0x7f5d7aa5d56c in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #13: torch::jit::onnx_constant_fold::runTorchBackendForOnnx(torch::jit::Node const*, std::vector<at::Tensor, std::allocator<at::Tensor> >&, int) + 0x                                          d3d (0x7f5d8cfbb0ed in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0xaecf7e (0x7f5d8cff8f7e in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #15: torch::jit::ONNXShapeTypeInference(torch::jit::Node*, std::map<std::string, c10::IValue, std::less<std::string>, std::allocator<std::pair<std::s                                          tring const, c10::IValue> > > const&, int) + 0x906 (0x7f5d8cffdd36 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #16: <unknown function> + 0xa70d59 (0x7f5d8cf7cd59 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #17: <unknown function> + 0x5011ee (0x7f5d8ca0d1ee in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #22: python() [0x50b868]
frame #36: <unknown function> + 0xaa705b (0x7f5d8cfb305b in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #37: torch::jit::NodeToONNX(torch::jit::Node*, torch::jit::Block*, torch::onnx::OperatorExportTypes, std::unordered_map<torch::jit::Value*, torch::ji                                          t::Value*, std::hash<torch::jit::Value*>, std::equal_to<torch::jit::Value*>, std::allocator<std::pair<torch::jit::Value* const, torch::jit::Value*> > >&) +                                           0x52a (0x7f5d8cfae75a in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #38: torch::jit::BlockToONNX(torch::jit::Block*, torch::jit::Block*, torch::onnx::OperatorExportTypes, std::unordered_map<torch::jit::Value*, torch::                                          jit::Value*, std::hash<torch::jit::Value*>, std::equal_to<torch::jit::Value*>, std::allocator<std::pair<torch::jit::Value* const, torch::jit::Value*> > >)                                           + 0x125 (0x7f5d8cfafba5 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #39: torch::jit::ToONNX(std::shared_ptr<torch::jit::Graph>&, torch::onnx::OperatorExportTypes) + 0x469 (0x7f5d8cfb02e9 in /usr/local/lib/python3.8/di                                          st-packages/torch/lib/libtorch_python.so)
frame #40: <unknown function> + 0xa9a393 (0x7f5d8cfa6393 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #41: <unknown function> + 0x5011ee (0x7f5d8ca0d1ee in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #62: python() [0x67e161]
frame #63: python() [0x67e1df]
 (function ComputeConstantFolding)
[W shape_type_inference.cpp:419] Warning: Constant folding in symbolic shape inference fails: number of dims don't match in permute
Exception raised from permute at /pytorch/aten/src/ATen/native/TensorShape.cpp:934 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f5d363dba22 in /usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x5f (0x7f5d363d84af in /usr/local/lib/python3.8/dist-packages                                          /torch/lib/libc10.so)
frame #2: at::native::permute(at::Tensor const&, c10::ArrayRef<long>) + 0x407 (0x7f5d7a0150d7 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_                                          cpu.so)
frame #3: <unknown function> + 0x1af6e02 (0x7f5d7a853e02 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x194020c (0x7f5d7a69d20c in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #5: at::redispatch::permute(c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<long>) + 0x61 (0x7f5d7a69d7a1 in /usr/local/lib/python3.8/dist-pack                                          ages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x34c1a5f (0x7f5d7c21ea5f in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x34c1dc5 (0x7f5d7c21edc5 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x194020c (0x7f5d7a69d20c in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #9: at::redispatch::permute(c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<long>) + 0x61 (0x7f5d7a69d7a1 in /usr/local/lib/python3.8/dist-pack                                          ages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x2f965d4 (0x7f5d7bcf35d4 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x2f96975 (0x7f5d7bcf3975 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #12: at::Tensor::permute(c10::ArrayRef<long>) const + 0x12c (0x7f5d7aa5d56c in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so)
frame #13: torch::jit::onnx_constant_fold::runTorchBackendForOnnx(torch::jit::Node const*, std::vector<at::Tensor, std::allocator<at::Tensor> >&, int) + 0x                                          d3d (0x7f5d8cfbb0ed in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0xaecf7e (0x7f5d8cff8f7e in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #15: torch::jit::ONNXShapeTypeInference(torch::jit::Node*, std::map<std::string, c10::IValue, std::less<std::string>, std::allocator<std::pair<std::s                                          tring const, c10::IValue> > > const&, int) + 0x906 (0x7f5d8cffdd36 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #16: <unknown function> + 0xaf49e4 (0x7f5d8d0009e4 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #17: <unknown function> + 0xa70c00 (0x7f5d8cf7cc00 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #18: <unknown function> + 0x5011ee (0x7f5d8ca0d1ee in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #39: python() [0x67e161]
frame #40: python() [0x67e1df]
frame #41: python() [0x67e281]
frame #45: __libc_start_main + 0xf3 (0x7f5d8ef320b3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
 (function ComputeConstantFolding)
Traceback (most recent call last):
  File "tmp.py", line 17, in <module>
    torch.onnx.export(net, (a,), "tmp.onnx")
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 501, in _model_to_graph
    params_dict = torch._C._jit_pass_onnx_constant_fold(graph, params_dict,
RuntimeError: number of dims don't match in permute
```

**Comment by mruberry** [comment]
I think it's OK that the linear layer doesn't require the dim == 2, but when exporting to ONNX we may need to pad the tensor?

**Comment by poutyface** [comment]
@mruberry 

>I think it's OK that the linear layer doesn't require the dim == 2

I think so too. That is more convenient. 
However, it is not consistent with the document. 

I think it is better to support it like v1.8. It's hard to understand what the error message is.

v1.8 onnx.export: verbose 
```
graph(%a : Float(1, 1, 10, strides=[10, 10, 1], requires_grad=0, device=cpu)):
  %1 : Float(10, strides=[1], requires_grad=0, device=cpu) = onnx::Constant[value= 1  1  1  1  1  1  1  1  1  1 [ CPUFloatType{10} ]]()
  %2 : Float(1, 1, strides=[1, 1], requires_grad=0, device=cpu) = onnx::MatMul(%a, %1) # /home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/functional.py:1753:0
  return (%2)
```

**Comment by BowenBao** [comment]
@mruberry I can help patch the exporter side. Will you update the document of linear to be consistent?

**Comment by mruberry** [comment]
cc @jbschlosser for changing the docs

**Comment by jbschlosser** [comment]
Looks like we need these updates to the `F.linear` docs:
```
Input: (*, in_features), where * means any number of additional dimensions, including none
Weight: (out_features, in_features) or (in_features)
Bias: (out_features) or ()
Output: (*, in_features) or (*), based on the shape of the weight
```

**Comment by AllenTiTaiWang** [comment]
@BowenBao I will leave this issue to you.

**Comment by BowenBao** [comment]
This could be a good first issue, and we'd welcome open source contribution.

**Comment by ShisuiUzumaki** [comment]
@BowenBao Is this issue still open? If it is I would like to try it. Also, I might need guidance in solving it, so if you could provide instructions that would be really helpful

**Comment by Adesoji1** [comment]
@poutyface It appears that you are having issues exporting a PyTorch model to ONNX when using the `torch.nn.functional.linear` function with a weight tensor of rank 1. This issue arises from the fact that the weight tensor is expected to be 2-dimensional, as specified in the documentation, but the provided weight tensor is 1-dimensional. Although it does not produce an error when using the `torch.nn.functional.linear` function, it fails during the ONNX export process.

To resolve this issue, you can modify the weight tensor to have an appropriate shape (2-dimensional). Here's how to modify your example code:

import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, a):
        b = torch.ones([1, 10])  # weight is now 2-d
        return F.linear(a, b)

net = Net()
a = torch.ones([1, 1, 10])
out = net(a)
print(out)
torch.onnx.export(net, (a,), "tmp.onnx")

This should resolve the issue with ONNX export. The modified code now uses a 2-dimensional weight tensor, which is the expected shape for the `torch.nn.functional.linear ` function.

**Comment by soumya1729** [comment]
@poutyface seems to be fixed in torch 2.0.1+cu118
