### ISSUE TITLE
Distributed Elastic Training Failed on Two Amazon g4dn.xlarge Instances

### ISSUE THREAD

**Issue by vycezhong** [pytorch/pytorch#64990]
## 🐛 Bug

I got an error when I launched a simple distributed job with Elastic PyTorch v1.9.0 on two Amazon g4dn.xlarge instances. 

## To Reproduce

The code I used is the same as https://github.com/pytorch/pytorch/issues/64926

Logs on Machine One (172.30.2.12)
```sh
➜  pipeline_resnet50 git:(pytorch-pipeline) ✗ ./run.sh
[INFO] 2021-09-14 14:02:15,538 run: Running torch.distributed.run with args: ['/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/run.py', '--nnodes=2', '--nproc_per_node=1', '--rdzv_id=1234', '--rdzv_backend=c10d', '--rdzv_endpoint=172.30.2.12', 'main.py']
[INFO] 2021-09-14 14:02:15,540 run: Using nproc_per_node=1.
[INFO] 2021-09-14 14:02:15,540 api: Starting elastic_operator with launch configs:
  entrypoint       : main.py
  min_nodes        : 2
  max_nodes        : 2
  nproc_per_node   : 1
  run_id           : 1234
  rdzv_backend     : c10d
  rdzv_endpoint    : 172.30.2.12
  rdzv_configs     : {'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

[INFO] 2021-09-14 14:02:15,544 c10d_rendezvous_backend: Process 22645 hosts the TCP store for the C10d rendezvous backend.
[INFO] 2021-09-14 14:02:15,547 local_elastic_agent: log directory set to: /tmp/torchelastic_bhmbwv8h/1234_4mhmlrg7
[INFO] 2021-09-14 14:02:15,547 api: [default] starting workers for entrypoint: python3
[INFO] 2021-09-14 14:02:15,547 api: [default] Rendezvous'ing worker group
[INFO] 2021-09-14 14:02:15,547 dynamic_rendezvous: The node 'ip-172-30-2-12_22645_0' attempts to join the next round of the rendezvous '1234'.
[INFO] 2021-09-14 14:02:29,579 dynamic_rendezvous: The node 'ip-172-30-2-12_22645_0' has joined round 0 of the rendezvous '1234' as rank 0 in a world of size 2.
/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/utils/store.py:53: FutureWarning: This is an experimental API and will be changed in future.
  "This is an experimental API and will be changed in future.", FutureWarning
[INFO] 2021-09-14 14:02:29,581 api: [default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=ip-172-30-2-12
  master_port=38517
  group_rank=0
  group_world_size=2
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[2]
  global_world_sizes=[2]

[INFO] 2021-09-14 14:02:29,582 api: [default] Starting worker group
[INFO] 2021-09-14 14:02:29,582 __init__: Setting worker0 reply file to: /tmp/torchelastic_bhmbwv8h/1234_4mhmlrg7/attempt_0/0/error.json
[INFO] 2021-09-14 14:02:39,596 api: [default] Detected 1 new nodes from group_rank=0; will restart worker group
[INFO] 2021-09-14 14:02:39,597 api: [default] Stopping worker group
[INFO] 2021-09-14 14:02:39,645 api: [default] Rendezvous'ing worker group
[INFO] 2021-09-14 14:02:39,645 dynamic_rendezvous: The node 'ip-172-30-2-12_22645_0' attempts to join the next round of the rendezvous '1234'.
[INFO] 2021-09-14 14:02:40,791 dynamic_rendezvous: The node 'ip-172-30-2-12_22645_0' has joined round 1 of the rendezvous '1234' as rank 0 in a world of size 2.
[INFO] 2021-09-14 14:02:40,794 api: [default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=ip-172-30-2-12
  master_port=38183
  group_rank=0
  group_world_size=2
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[2]
  global_world_sizes=[2]

[INFO] 2021-09-14 14:02:40,794 api: [default] Starting worker group
[INFO] 2021-09-14 14:02:40,795 __init__: Setting worker0 reply file to: /tmp/torchelastic_bhmbwv8h/1234_4mhmlrg7/attempt_0/0/error.json
[INFO] 2021-09-14 14:02:50,804 api: [default] Detected 1 new nodes from group_rank=0; will restart worker group
[INFO] 2021-09-14 14:02:50,805 api: [default] Stopping worker group
[INFO] 2021-09-14 14:02:50,846 api: [default] Rendezvous'ing worker group
[INFO] 2021-09-14 14:02:50,846 dynamic_rendezvous: The node 'ip-172-30-2-12_22645_0' attempts to join the next round of the rendezvous '1234'.
[INFO] 2021-09-14 14:02:51,848 dynamic_rendezvous: The node 'ip-172-30-2-12_22645_0' has joined round 2 of the rendezvous '1234' as rank 0 in a world of size 2.
[INFO] 2021-09-14 14:02:51,851 api: [default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=ip-172-30-2-12
  master_port=52205
  group_rank=0
  group_world_size=2
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[2]
  global_world_sizes=[2]

[INFO] 2021-09-14 14:02:51,851 api: [default] Starting worker group
[INFO] 2021-09-14 14:02:51,851 __init__: Setting worker0 reply file to: /tmp/torchelastic_bhmbwv8h/1234_4mhmlrg7/attempt_0/0/error.json
[INFO] 2021-09-14 14:03:01,866 api: [default] Detected 1 new nodes from group_rank=0; will restart worker group
[INFO] 2021-09-14 14:03:01,866 api: [default] Stopping worker group
[INFO] 2021-09-14 14:03:01,913 api: [default] Rendezvous'ing worker group
[INFO] 2021-09-14 14:03:01,913 dynamic_rendezvous: The node 'ip-172-30-2-12_22645_0' attempts to join the next round of the rendezvous '1234'.
[INFO] 2021-09-14 14:03:02,917 dynamic_rendezvous: The node 'ip-172-30-2-12_22645_0' has joined round 3 of the rendezvous '1234' as rank 0 in a world of size 2.
[INFO] 2021-09-14 14:03:02,919 api: [default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=ip-172-30-2-12
  master_port=52795
  group_rank=0
  group_world_size=2
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[2]
  global_world_sizes=[2]

[INFO] 2021-09-14 14:03:02,919 api: [default] Starting worker group
[INFO] 2021-09-14 14:03:02,920 __init__: Setting worker0 reply file to: /tmp/torchelastic_bhmbwv8h/1234_4mhmlrg7/attempt_0/0/error.json
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main()
  File "main.py", line 29, in main
    timeout=timedelta(seconds=10)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 222, in _store_based_barrier
    rank, store_key, world_size, worker_count, timeout))
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=2, worker_count=1, timeout=0:00:10)
[ERROR] 2021-09-14 14:03:27,949 api: failed (exitcode: 1) local_rank: 0 (pid: 22895) of binary: /usr/bin/python3
[ERROR] 2021-09-14 14:03:27,949 local_elastic_agent: [default] Worker group failed
[INFO] 2021-09-14 14:03:27,950 api: [default] Worker group FAILED. 3/3 attempts left; will restart worker group
[INFO] 2021-09-14 14:03:27,950 api: [default] Stopping worker group
[INFO] 2021-09-14 14:03:27,950 api: [default] Rendezvous'ing worker group
[INFO] 2021-09-14 14:03:27,950 dynamic_rendezvous: The node 'ip-172-30-2-12_22645_0' attempts to join the next round of the rendezvous '1234'.
```

Logs on Machine Two (172.30.2.79)
```sh
➜  pipeline_resnet50 git:(pytorch-pipeline) ✗ ./run.sh
[INFO] 2021-09-14 14:02:29,295 run: Running torch.distributed.run with args: ['/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/run.py', '--nnodes=2', '--nproc_per_node=1', '--rdzv_id=1234', '--rdzv_backend=c10d', '--rdzv_endpoint=172.30.2.12', 'main.py']
[INFO] 2021-09-14 14:02:29,297 run: Using nproc_per_node=1.
[INFO] 2021-09-14 14:02:29,297 api: Starting elastic_operator with launch configs:
  entrypoint       : main.py
  min_nodes        : 2
  max_nodes        : 2
  nproc_per_node   : 1
  run_id           : 1234
  rdzv_backend     : c10d
  rdzv_endpoint    : 172.30.2.12
  rdzv_configs     : {'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

[INFO] 2021-09-14 14:02:29,309 local_elastic_agent: log directory set to: /tmp/torchelastic_ozl1psve/1234_31eglxsv
[INFO] 2021-09-14 14:02:29,309 api: [default] starting workers for entrypoint: python3
[INFO] 2021-09-14 14:02:29,309 api: [default] Rendezvous'ing worker group
[INFO] 2021-09-14 14:02:29,309 dynamic_rendezvous: The node 'ip-172-30-2-79_28389_0' attempts to join the next round of the rendezvous '1234'.
[INFO] 2021-09-14 14:02:29,438 dynamic_rendezvous: The node 'ip-172-30-2-79_28389_0' has joined round 0 of the rendezvous '1234' as rank 1 in a world of size 2.
/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/utils/store.py:53: FutureWarning: This is an experimental API and will be changed in future.
  "This is an experimental API and will be changed in future.", FutureWarning
[INFO] 2021-09-14 14:02:29,583 api: [default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=ip-172-30-2-12
  master_port=38517
  group_rank=1
  group_world_size=2
  local_ranks=[0]
  role_ranks=[1]
  global_ranks=[1]
  role_world_sizes=[2]
  global_world_sizes=[2]

[INFO] 2021-09-14 14:02:29,583 api: [default] Starting worker group
[INFO] 2021-09-14 14:02:29,583 __init__: Setting worker0 reply file to: /tmp/torchelastic_ozl1psve/1234_31eglxsv/attempt_0/0/error.json
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main()
  File "main.py", line 29, in main
    timeout=timedelta(seconds=10)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 520, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 199, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
ValueError: host not found: Temporary failure in name resolution
[ERROR] 2021-09-14 14:02:34,592 api: failed (exitcode: 1) local_rank: 0 (pid: 28398) of binary: /usr/bin/python3
[ERROR] 2021-09-14 14:02:34,592 local_elastic_agent: [default] Worker group failed
[INFO] 2021-09-14 14:02:34,592 api: [default] Worker group FAILED. 3/3 attempts left; will restart worker group
[INFO] 2021-09-14 14:02:34,592 api: [default] Stopping worker group
[INFO] 2021-09-14 14:02:34,592 api: [default] Rendezvous'ing worker group
[INFO] 2021-09-14 14:02:34,592 dynamic_rendezvous: The node 'ip-172-30-2-79_28389_0' attempts to join the next round of the rendezvous '1234'.
[INFO] 2021-09-14 14:02:39,859 dynamic_rendezvous: The node 'ip-172-30-2-79_28389_0' has joined round 1 of the rendezvous '1234' as rank 1 in a world of size 2.
[INFO] 2021-09-14 14:02:40,795 api: [default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=ip-172-30-2-12
  master_port=38183
  group_rank=1
  group_world_size=2
  local_ranks=[0]
  role_ranks=[1]
  global_ranks=[1]
  role_world_sizes=[2]
  global_world_sizes=[2]

[INFO] 2021-09-14 14:02:40,795 api: [default] Starting worker group
[INFO] 2021-09-14 14:02:40,796 __init__: Setting worker0 reply file to: /tmp/torchelastic_ozl1psve/1234_31eglxsv/attempt_1/0/error.json
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main()
  File "main.py", line 29, in main
    timeout=timedelta(seconds=10)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 520, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 199, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
ValueError: host not found: Temporary failure in name resolution
[ERROR] 2021-09-14 14:02:45,802 api: failed (exitcode: 1) local_rank: 0 (pid: 28418) of binary: /usr/bin/python3
[ERROR] 2021-09-14 14:02:45,802 local_elastic_agent: [default] Worker group failed
[INFO] 2021-09-14 14:02:45,802 api: [default] Worker group FAILED. 2/3 attempts left; will restart worker group
[INFO] 2021-09-14 14:02:45,802 api: [default] Stopping worker group
[INFO] 2021-09-14 14:02:45,802 api: [default] Rendezvous'ing worker group
[INFO] 2021-09-14 14:02:45,802 dynamic_rendezvous: The node 'ip-172-30-2-79_28389_0' attempts to join the next round of the rendezvous '1234'.
[INFO] 2021-09-14 14:02:51,812 dynamic_rendezvous: The node 'ip-172-30-2-79_28389_0' has joined round 2 of the rendezvous '1234' as rank 1 in a world of size 2.
[INFO] 2021-09-14 14:02:51,852 api: [default] Rendezvous complete for workers. Result:
  restart_count=2
  master_addr=ip-172-30-2-12
  master_port=52205
  group_rank=1
  group_world_size=2
  local_ranks=[0]
  role_ranks=[1]
  global_ranks=[1]
  role_world_sizes=[2]
  global_world_sizes=[2]

[INFO] 2021-09-14 14:02:51,852 api: [default] Starting worker group
[INFO] 2021-09-14 14:02:51,853 __init__: Setting worker0 reply file to: /tmp/torchelastic_ozl1psve/1234_31eglxsv/attempt_2/0/error.json
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main()
  File "main.py", line 29, in main
    timeout=timedelta(seconds=10)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 520, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 199, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
ValueError: host not found: Temporary failure in name resolution
[ERROR] 2021-09-14 14:02:56,862 api: failed (exitcode: 1) local_rank: 0 (pid: 28436) of binary: /usr/bin/python3
[ERROR] 2021-09-14 14:02:56,862 local_elastic_agent: [default] Worker group failed
[INFO] 2021-09-14 14:02:56,862 api: [default] Worker group FAILED. 1/3 attempts left; will restart worker group
[INFO] 2021-09-14 14:02:56,862 api: [default] Stopping worker group
[INFO] 2021-09-14 14:02:56,862 api: [default] Rendezvous'ing worker group
[INFO] 2021-09-14 14:02:56,862 dynamic_rendezvous: The node 'ip-172-30-2-79_28389_0' attempts to join the next round of the rendezvous '1234'.
[INFO] 2021-09-14 14:03:02,872 dynamic_rendezvous: The node 'ip-172-30-2-79_28389_0' has joined round 3 of the rendezvous '1234' as rank 1 in a world of size 2.
[INFO] 2021-09-14 14:03:02,920 api: [default] Rendezvous complete for workers. Result:
  restart_count=3
  master_addr=ip-172-30-2-12
  master_port=52795
  group_rank=1
  group_world_size=2
  local_ranks=[0]
  role_ranks=[1]
  global_ranks=[1]
  role_world_sizes=[2]
  global_world_sizes=[2]

[INFO] 2021-09-14 14:03:02,920 api: [default] Starting worker group
[INFO] 2021-09-14 14:03:02,921 __init__: Setting worker0 reply file to: /tmp/torchelastic_ozl1psve/1234_31eglxsv/attempt_3/0/error.json
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main()
  File "main.py", line 29, in main
    timeout=timedelta(seconds=10)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 520, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 199, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
ValueError: host not found: Temporary failure in name resolution
[ERROR] 2021-09-14 14:03:07,930 api: failed (exitcode: 1) local_rank: 0 (pid: 28454) of binary: /usr/bin/python3
[ERROR] 2021-09-14 14:03:07,930 local_elastic_agent: [default] Worker group failed
[INFO] 2021-09-14 14:03:07,930 api: Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish
/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/utils/store.py:71: FutureWarning: This is an experimental API and will be changed in future.
  "This is an experimental API and will be changed in future.", FutureWarning
[ERROR] 2021-09-14 14:03:12,874 api: Error waiting on exit barrier. Elapsed: 4.943624496459961 seconds
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 889, in _exit_barrier
    barrier_timeout=self._exit_barrier_timeout,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/utils/store.py", line 74, in barrier
    synchronize(store, data, rank, world_size, key_prefix, barrier_timeout)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/utils/store.py", line 57, in synchronize
    agent_data = get_all(store, key_prefix, world_size)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/utils/store.py", line 32, in get_all
    data = store.get(f"{prefix}{idx}")
RuntimeError: Stop_waiting response is expected
Exception in thread RendezvousKeepAliveTimer_0:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/utils.py", line 255, in _run
    ctx.function(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1002, in _keep_alive_weak
    self._keep_alive()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1012, in _keep_alive
    self._op_executor.run(op, deadline)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 546, in run
    has_set = self._state_holder.sync()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 364, in sync
    set_response = self._backend.set_state(state_bits, self._token)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 88, in set_state
    base64_state: bytes = self._call_store("compare_set", self._key, token, base64_state_str)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 103, in _call_store
    return getattr(self._store, store_op)(*args, **kwargs)
MemoryError: std::bad_alloc

{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "1234", "global_rank": 1, "group_rank": 1, "worker_id": "28454", "role": "default", "hostname": "ip-172-30-2-79", "state": "FAILED", "total_run_time": 43, "rdzv_backend": "c10d", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 2, \"entry_point\": \"python3\", \"local_rank\": [0], \"role_rank\": [1], \"role_world_size\": [2]}", "agent_restarts": 3}}
{"name": "torchelastic.worker.status.SUCCEEDED", "source": "AGENT", "timestamp": 0, "metadata": {"run_id": "1234", "global_rank": null, "group_rank": 1, "worker_id": null, "role": "default", "hostname": "ip-172-30-2-79", "state": "SUCCEEDED", "total_run_time": 43, "rdzv_backend": "c10d", "raw_error": null, "metadata": "{\"group_world_size\": 2, \"entry_point\": \"python3\"}", "agent_restarts": 3}}
[ERROR] 2021-09-14 14:03:12,880 error_handler: {
  "message": {
    "message": "MemoryError: std::bad_alloc",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/launcher/api.py\", line 247, in launch_agent\n    failures=result.failures,\ntorch.distributed.elastic.multiprocessing.errors.ChildFailedError: \n***************************************\n             main.py FAILED            \n=======================================\nRoot Cause:\n[0]:\n  time: 2021-09-14_14:03:07\n  rank: 1 (local_rank: 0)\n  exitcode: 1 (pid: 28454)\n  error_file: <N/A>\n  msg: \"Process failed with exitcode 1\"\n=======================================\nOther Failures:\n  <NO_OTHER_FAILURES>\n***************************************\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 348, in wrapper\n    return f(*args, **kwargs)\n  File \"/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/launcher/api.py\", line 260, in launch_agent\n    rdzv_handler.shutdown()\n  File \"/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py\", line 976, in shutdown\n    self._close()\n  File \"/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py\", line 992, in _close\n    self._op_executor.run(op, deadline)\n  File \"/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py\", line 546, in run\n    has_set = self._state_holder.sync()\n  File \"/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py\", line 364, in sync\n    set_response = self._backend.set_state(state_bits, self._token)\n  File \"/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py\", line 88, in set_state\n    base64_state: bytes = self._call_store(\"compare_set\", self._key, token, base64_state_str)\n  File \"/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py\", line 103, in _call_store\n    return getattr(self._store, store_op)(*args, **kwargs)\nMemoryError: std::bad_alloc\n",
      "timestamp": "1631628192"
    }
  }
}
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
***************************************
             main.py FAILED
=======================================
Root Cause:
[0]:
  time: 2021-09-14_14:03:07
  rank: 1 (local_rank: 0)
  exitcode: 1 (pid: 28454)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/run.py", line 637, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/run.py", line 629, in main
    run(args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/run.py", line 624, in run
    )(*cmd_args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 260, in launch_agent
    rdzv_handler.shutdown()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 976, in shutdown
    self._close()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 992, in _close
    self._op_executor.run(op, deadline)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 546, in run
    has_set = self._state_holder.sync()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 364, in sync
    set_response = self._backend.set_state(state_bits, self._token)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 88, in set_state
    base64_state: bytes = self._call_store("compare_set", self._key, token, base64_state_str)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 103, in _call_store
    return getattr(self._store, store_op)(*args, **kwargs)
MemoryError: std::bad_alloc
```

## Expected behavior

It should work. 

## Environment

2 x Amazon g4dn.xlarge instances. Deep Learning AMI (Ubuntu 18.04) Version 49.0 

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Ubuntu 18.04 
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): 
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.2/7.6.5
 - GPU models and configuration: T4 
 - Any other relevant information:

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @cbalioglu @gcramer23

**Comment by vycezhong** [comment]
I figured out the problem. I noticed that it used `_env_rendezvous_handler` rather than `_tcp_rendezvous_handler`. Then I realized that I should specify `init_method` in `init_process_group` . And now it works. 

The weird thing is that I cannot use the same port as the port used in `rdzv_endpoint`.  It throws an error that the address is already in use. It seems that there are two `TCPStore`: one for the agent, the other for the c10d. I have no idea why we need two stores here.

**Comment by cbalioglu** [comment]
Hi @vycezhong,

Recently we merged #64826 that should address your problem. It will be released as part of v1.9.1. We deliberately avoided the details of how the stores are initialized, because the goal is to make the initialization and rank assignment as transparent as possible. Ideally as a user you should not care about any port allocations.

If you have the chance, I suggest giving one of the recent nightly builds a chance and see if your problem (with your original code) still persists. In such case, please let us know. Thanks!

**Comment by vycezhong** [comment]
@cbalioglu  I tried the lastest night build but it did not work when I used the same port for both `torch.distributed.run` and `init_method=tcp://`.

**Comment by cbalioglu** [comment]
cc @kiukchung @aivanou

**Comment by kiukchung** [comment]
If you can, try using `init_method=env://` (e.g. don't pass anything but the backend when creating the process group)

```
# in your main.py
dist.init_process_group(backend="nccl")
```

**Comment by kiukchung** [comment]
> @cbalioglu I tried the latest nightly build but I still got an error that the address is in use when I used the same port for both `torch.distributed.run` and `init_method=tcp://`.

@vycezhong thanks for trying this out and apologize for the churn. To close the loop here I've validated that your script (modified a bit to run on CPU) works with pytorch nightly:

Here's the main I ran with:
```
import argparse
import os
from datetime import timedelta

import torch

parser = argparse.ArgumentParser(
    description='minimal code to reproduce the bug')
parser.add_argument('--master_ip', default=None, type=str,
                    help='master ip for c10d')
parser.add_argument('--master_port', default=None, type=int,
                    help='master port for c10d')


def main():
    args = parser.parse_args()

    args.world_size = int(os.environ['WORLD_SIZE'])
    args.rank = int(os.environ['RANK'])
    args.local_rank = int(os.environ['LOCAL_RANK'])

    init_method = "tcp://{}:{}".format(args.master_ip, args.master_port)
    torch.distributed.init_process_group(
        'gloo', init_method=init_method,
        world_size=args.world_size, rank=args.rank,
        timeout=timedelta(seconds=10)
    )

    x = torch.randn((1000))

    if torch.distributed.get_rank() == 0:
        torch.distributed.send(x, 1)
    elif torch.distributed.get_rank() == 1:
        torch.distributed.recv(x, 0)

    print(x)


if __name__ == '__main__':
    main()
```

and the launch command

```
$ python -m torch.distributed.run --rdzv_backend c10d  --nnodes 1 --nproc_per_node 2 main_test.py --master_port 29500 --master_ip 127.0.0.1
```

I'm passing `127.0.0.1:29500` deliberately because this is the default values for the master_addr and master_port that the runner will use if none provided (hence I wanted to test whether manually making the addr and port collide between torchelastic and main.py would cause issues)

**Comment by vycezhong** [comment]
@kiukchung I would kindly like to point out that the default port is `29400`. 

https://github.com/pytorch/pytorch/blob/d69c22dd61a2f006dcfe1e3ea8468a3ecaf931aa/torch/distributed/run.py#L609

The same error occurs when setting `--master_port 29400`. 

___

> If you can, try using `init_method=env://` (e.g. don't pass anything but the backend when creating the process group)
> 
> ```
> # in your main.py
> dist.init_process_group(backend="nccl")
> ```

It will get the error I described above. (https://github.com/pytorch/pytorch/issues/64990#issue-996065118)

**Comment by kiukchung** [comment]
@vycezhong thanks for pointing out the default port `29400` and with it I was able to repro the timeout error. So to summarize:

0. When running multiple nodes you HAVE to specify a port if you are overriding `--rdzv_endpoint`. In your case, since you did not specify a port in `--rdzv_endpoint=172.30.2.12` the runner chose a random port on the host_0 (172.30.2.12). Since a random port was chosen on host_0, host_1 cannot possibly know about this hence the timeout. 

1. When possible, initialize process group with no `init_method` (`dist.init_process_group(backend=BACKEND)`). Per documentation:
![image](https://user-images.githubusercontent.com/43595115/135509552-765a572d-40b6-4a7d-b4a3-2519a59817f8.png)
https://pytorch.org/docs/stable/elastic/run.html#usage

![image](https://user-images.githubusercontent.com/43595115/135509707-0d152ec8-aaf4-4e2a-b23e-040c20d089f0.png)
https://pytorch.org/docs/stable/distributed.html#launch-utility

2. (undocumented since we'd like folks to not manually set `init_method` going forward). `init_method=tcp://MASTER_ADDR:MASTER_PORT` will work in the following conditions:
     1. `--rdzv_backend=static` 
     2. AND master_port in the init_method URL is equal to the one of the runner
  
Examples (for TCP):
```
# assuming the following in training_script.py
dist.init_process_group(init_method=INIT_METHOD)
```
1. (OK) `python -m torch.distributed.run --rdzv_backend=static --master_addr=localhost --master_port=29400` and `INIT_METHOD=tcp://localhost/29400`
2. (NOT OK) `python -m torch.distributed.run --rdzv_backend=static --master_addr=localhost --master_port=29400` and `INIT_METHOD=tcp://localhost/29500`
3. (NOT OK) `python -m torch.distributed.run --rdzv_backend=c10d` and `INIT_METHOD=tcp://localhost/*ANY`

note: the goal in #2 was to make this compatible with `torch.distributed.launch` which launches with `static` rdzv backend.

**Comment by vycezhong** [comment]
@kiukchung  We figure out the problem - `MASTER_ADDR is the hostname of the master node but the hostname may not be resolved by other nodes. That's why we need to specify the master ip address in `init_process_group` explicitly. 

For example, in Amazon g4dn.instance, the hostname is `ip-172-30-2-12` which is not recognized by other nodes.
