### ISSUE TITLE
deepcopy of Lazy modules returns an exception

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#65051]
## 🐛 Bug

Calling `copy.deepcopy` on a lazy module returns an exception (before the module is initialized).

## To Reproduce

```python
import copy
import torch
l = torch.nn.LazyLinear(4)
copy.deepcopy(l) # returns an error
l(torch.randn(1,3))
copy.deepcopy(l) # works fine
```
Error message:
```
/path/to/my/conda_env/lib/python3.8/site-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/my/conda_env/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/path/to/my/conda_env/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/path/to/my/conda_env/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/path/to/my/conda_env/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/path/to/my/conda_env/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/path/to/my/conda_env/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/path/to/my/conda_env/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/path/to/my/conda_env/lib/python3.8/site-packages/torch/nn/parameter.py", line 32, in __deepcopy__
    result = type(self)(self.data.clone(memory_format=torch.preserve_format), self.requires_grad)
  File "/path/to/my/conda_env/lib/python3.8/site-packages/torch/nn/parameter.py", line 153, in __new__
    data = torch.tensor([], **factory_kwargs)
TypeError: tensor(): argument 'device' must be torch.device, not bool
```

## Expected behavior

should return a non-initialized lazy module

## Environment

 - PyTorch Version (e.g., 1.9.0):
 - OS (e.g., Linux): MacOs / Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): Conda
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: V100

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @hameerabbasi @rgommers @peterbell10 @ezyang

**Comment by albanD** [comment]
I think https://github.com/pytorch/pytorch/blob/master/torch/nn/parameter.py#L151 should not modify the `__new__` signature this way indeed. We should fix that.

**Comment by jbschlosser** [comment]
Right, the call to `_make_subclass()` expects a signature of `__new__(cls, data, requires_grad)` and `UninitializedParameter.__new__` doesn't match that.

Might not be the cleanest solution, but changing `UninitializedParameter.__new__` to this works:
```python
def __new__(cls, data=None, requires_grad=True, device=None, dtype=None) -> None:
    if data is None:
        factory_kwargs = {'device': device, 'dtype': dtype}
        data = torch.tensor([], **factory_kwargs)
    return torch.Tensor._make_subclass(cls, data, requires_grad)
```

**Comment by jaketae** [comment]
I was able to reproduce this error. This issue seems unfixed in master:

https://github.com/pytorch/pytorch/blob/2b52db9c953d063db7b46c12f4df35b47aca4381/torch/nn/parameter.py#L175-L178

Can we simply add a `_data=None` to match the expected `__new__` function signature, similar to the suggestion by @jbschlosser above?

```python
def __new__(cls, _data=None, requires_grad=True, device=None, dtype=None) -> None:
```

**Comment by zeshengzong** [comment]
Seems already fixed in main branch, issue may be closed

```python
In [12]: import copy
    ...: import torch
    ...: l = torch.nn.LazyLinear(4)
    ...: copy.deepcopy(l) # returns an error
Out[12]: LazyLinear(in_features=0, out_features=4, bias=True)
```
