### ISSUE TITLE
[Caffe2] Onnx to Caffe2 Blob error

### ISSUE THREAD

**Issue by wesleyw72** [pytorch/pytorch#6505]
Trying to convert a model from PyTorch to Caffe2. I have the model in Onnx form, however when I try to go from Onnx to Caffe2 using the tool in caffe2.python.onnx.bin.conversion, I get an output but running them in Caffe2 produces:

'W0411 14:04:06.918320 13911 workspace.cc:174] Blob 1 not in the workspace.
WARNING:caffe2.python.workspace:Original python traceback for operator `1647504248` in network 
torch-jit-export_predict^
0
1
25"Conv*
strides00*
	dilations00*
group*
kernels00*
pads00003
56PadImage*
pads0000*
mode"reflect^
6
3
47"Conv*
strides00*
	dilations00*
group*
kernels00*
pads0000
78"Relu:0:1:2:3:4B8` in exception above (most recent call last):
Traceback (most recent call last):
  File "Caffe2WCT.py", line 32, in <module>
    workspace.RunNetOnce(predict_net)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 199, in RunNetOnce
    StringifyProto(net),
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at operator.cc:42] blob != nullptr. op Conv: Encountered a non-existing input blob: 1'

OS: Ubuntu 16.04
Caffe2: Built from source this morning
Python: 2.7

**Comment by MacroBull** [comment]
you may need to prepare input tensor as blob 1 before run

**Comment by wesleyw72** [comment]
@MacroBull tried that and it gives the same error but for blob 0 then. Using the ONNX files directly works fine, but converting them to Caffe2 files does not. It seems to me there is a problem with the conversion process.

**Comment by BIGBALLON** [comment]
@MacroBull and @khurramHazen is right, we need create blob before we initialize our net, it seems there are problems with the conversion process. 

```cpp
    // define a caffe2 Workspace
    Workspace workSpace;

    // define initNet and predictNet
    NetDef initNet, predictNet;
    DeviceOption deviceOption;
    deviceOption.set_cuda_gpu_id(0);
    deviceOption.set_device_type(CUDA);
    auto context = new CUDAContext(deviceOption);
    // read protobuf

    workSpace.CreateBlob("0");
    CAFFE_ENFORCE(ReadProtoFromFile(FLAGS_init_net, &initNet));
    CAFFE_ENFORCE(ReadProtoFromFile(FLAGS_predict_net, &predictNet));

    predictNet.mutable_device_option()->CopyFrom(deviceOption);
    initNet.mutable_device_option()->CopyFrom(deviceOption);

    // load network
    CAFFE_ENFORCE(workSpace.RunNetOnce(initNet));
    CAFFE_ENFORCE(workSpace.CreateNet(predictNet));

```

it works for me `` workSpace.CreateBlob("0")``

**Comment by garymm** [comment]
This issue doesn't mention `torch.onnx`, so removing label `module: onnx`. Please add it back and clarify if this does relate to `torch.onnx`.
