### ISSUE TITLE
Bug: torch.jit.load cannot load from IOBuffer

### ISSUE THREAD

**Issue by jbuckman** [pytorch/pytorch#65098]
Taking code straight from the documentation on [this page](http://man.hubwiz.com/docset/PyTorch.docset/Contents/Resources/Documents/jit.html):

```
import torch
import io

class MyModule(torch.nn.Module):
    def forward(self, x):
        return x + 10

m = torch.jit.script(MyModule())

# Save to io.BytesIO buffer
buffer = io.BytesIO()
torch.jit.save(m, buffer)
```

If we then run:

```torch.jit.load(buffer)```

We see:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/jit/_serialization.py", line 163, in load
    cpp_module = torch._C.import_ir_module_from_buffer(
RuntimeError: PytorchStreamReader failed reading zip archive: not a ZIP archive
```

Also worth noting that if you save to a file, and then read into a buffer, and load from there, it does work as intended:

```
torch.jit.save(m, 'scriptmodule.pt')
with open('scriptmodule.pt', 'rb') as f: buffer = io.BytesIO(f.read())
torch.jit.load(buffer)
```

This is on Mac and Linux, Python3.9, torch 1.9.0.

**Comment by peterjc123** [comment]
You'll need to move the cursor of the file before loading it.
```py
buffer = io.BytesIO()
torch.jit.save(m, buffer)
buffer.seek(0)
new_m = torch.jit.load(buffer)
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
