### ISSUE TITLE
Test reporting misses breakages in test framework

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#65091]
See https://github.com/pytorch/pytorch/runs/3612142217 and the corresponding HUD page: https://hud.pytorch.org/commit/fb8bdb8039fe8dde4b3eea0a740c859f9dde7f87

linux-bionic-cuda10.2-py3.9-gcc7 / test (default, 1, 2, linux.8xlarge.nvidia.gpu) failed in the test step but the `rendered test results` step shows no errors. The actual failure is an import problem in `torch`, so the tests don't actually run. This is still annoying to find since it means trudging through lots of logs.

<details>

```
2021-09-15T15:58:51.3278408Z the rest: ['test_jit_fuser_te', 'test_fx', 'test_profiler', 'test_autograd', 'test_type_hints', 'test_sparse_csr', 'test_openmp', 'test_complex', 'test_logging', 'test_model_dump', 'test_native_functions', 'autograd/test_complex', 'test_set_default_mobile_cpu_allocator', 'test_type_info', 'test_vulkan', 'benchmark_utils/test_benchmark_utils', 'distributions/test_constraints', 'test_binary_ufuncs', 'test_bundled_inputs', 'test_cpp_extensions_aot_no_ninja', 'test_cuda', 'test_dataloader', 'test_functional_optim', 'test_fx_experimental', 'test_jit', 'test_license', 'test_mkldnn', 'test_multiprocessing', 'test_namedtensor', 'test_nn', 'test_ops', 'test_overrides', 'test_pruning_op', 'test_pytree', 'test_reductions', 'test_shape_ops', 'test_sort_and_select', 'test_tensorexpr', 'test_testing', 'test_type_promotion', 'test_utils', 'test_vmap']
2021-09-15T15:58:51.3281472Z 
2021-09-15T15:58:51.3804607Z Running test_jit_fuser_te ... [2021-09-15 15:58:51.380061]
2021-09-15T15:58:51.3805935Z Executing ['/opt/conda/bin/python', 'test_jit_fuser_te.py', '-v', '--import-slow-tests', '--import-disabled-tests'] ... [2021-09-15 15:58:51.380132]
2021-09-15T15:58:54.4814927Z Traceback (most recent call last):
2021-09-15T15:58:54.4816914Z   File "/var/lib/jenkins/workspace/test/test_jit_fuser_te.py", line 24, in <module>
2021-09-15T15:58:54.4819246Z     from torch.testing._internal.common_methods_invocations import op_db
2021-09-15T15:58:54.4823203Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_methods_invocations.py", line 9348, in <module>
2021-09-15T15:58:54.4849412Z     SkipInfo('TestJit', 'test_variant_consistency_jit'),
2021-09-15T15:58:54.4851574Z NameError: name 'SkipInfo' is not defined
2021-09-15T15:58:54.7560590Z test_jit_fuser_te failed!
2021-09-15T15:58:54.7563516Z Running test_fx ... [2021-09-15 15:58:54.755951]
2021-09-15T15:58:54.7564741Z Executing ['/opt/conda/bin/python', 'test_fx.py', '-v', '--import-slow-tests', '--import-disabled-tests'] ... [2021-09-15 15:58:54.756026]
2021-09-15T15:58:57.8192586Z Traceback (most recent call last):
2021-09-15T15:58:57.8194487Z   File "/var/lib/jenkins/workspace/test/test_fx.py", line 21, in <module>
2021-09-15T15:58:57.8196744Z     from torch.testing._internal.common_methods_invocations import op_db
2021-09-15T15:58:57.8200686Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_methods_invocations.py", line 9348, in <module>
2021-09-15T15:58:57.8231318Z     SkipInfo('TestJit', 'test_variant_consistency_jit'),
2021-09-15T15:58:57.8233453Z NameError: name 'SkipInfo' is not defined
2021-09-15T15:58:58.0983823Z test_fx failed!
2021-09-15T15:58:58.0986924Z Running test_profiler ... [2021-09-15 15:58:58.098292]
2021-09-15T15:58:58.0988200Z Executing ['/opt/conda/bin/python', 'test_profiler.py', '-v', '--import-slow-tests', '--import-disabled-tests'] ... [2021-09-15 15:58:58.098368]
2021-09-15T15:59:01.0538681Z Test results will be stored in test-reports/python-unittest/test_profiler
```

</details>

cc @ezyang @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra @mruberry

**Comment by malfet** [comment]
By the way, why none of CircleCI jobs are displayed in hud.pytorch.org/commit/ ?

**Comment by malfet** [comment]
For a comparison, here is CircleCI log for the same failure (and looks like run-thru-failure policy is applied only to GHA jobs):  https://app.circleci.com/pipelines/github/pytorch/pytorch/380552/workflows/3f10959c-c9bf-457f-81c9-f292b392d111/jobs/16032595

**Comment by zengk95** [comment]
closing this since this is regarding the old HUD.
