### ISSUE TITLE
ChannelShuffle: Missing CUDA implementation

### ISSUE THREAD

**Issue by oliland** [pytorch/pytorch#65325]
## 🐛 Bug

ChannelShuffle support appears to be missing a CUDA implementation when pytorch is installed with conda. I'm not sure if this is a bug or if it hasn't been implemented just yet.

## To Reproduce

```
>>> import torch
>>> x = torch.rand(1, 3, 240, 320)
>>> device = torch.device('cuda')
>>> x = x.to(device)
>>> s = torch.nn.ChannelShuffle(3)
>>> s(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oliland/miniconda3/envs/lensless/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/oliland/miniconda3/envs/lensless/lib/python3.9/site-packages/torch/nn/modules/channelshuffle.py", line 49, in forward
    return F.channel_shuffle(input, self.groups)
NotImplementedError: Could not run 'aten::channel_shuffle' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::channel_shuffle' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/build/aten/src/ATen/RegisterCPU.cpp:16286 [kernel]
QuantizedCPU: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/build/aten/src/ATen/RegisterQuantizedCPU.cpp:1025 [kernel]
BackendSelect: fallthrough registered at /opt/conda/conda-bld/pytorch_1623448255797/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
ADInplaceOrView: fallthrough registered at /opt/conda/conda-bld/pytorch_1623448255797/work/aten/src/ATen/core/VariableFallbackKernel.cpp:60 [backend fallback]
AutogradOther: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
AutogradCPU: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
AutogradCUDA: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
AutogradXLA: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
AutogradMLC: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
AutogradHPU: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
AutogradNestedTensor: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
AutogradPrivateUse1: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
AutogradPrivateUse2: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
AutogradPrivateUse3: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/VariableType_3.cpp:10820 [autograd kernel]
Tracer: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/autograd/generated/TraceType_3.cpp:10078 [kernel]
Autocast: fallthrough registered at /opt/conda/conda-bld/pytorch_1623448255797/work/aten/src/ATen/autocast_mode.cpp:255 [backend fallback]
Batched: registered at /opt/conda/conda-bld/pytorch_1623448255797/work/aten/src/ATen/BatchingRegistrations.cpp:1019 [backend fallback]
VmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1623448255797/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
```

## Expected behavior

Channels shuffled.

## Environment

 - PyTorch Version (e.g., 1.0): 1.9
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): -
 - Python version: 
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: 2x GTX 2080
 - Any other relevant information: torchvision also installed

cc @ngimel

**Comment by soulitzer** [comment]
Thanks for the report, the CUDA implementation for ChannelShuffle hasn't been implemented yet

**Comment by fengkh** [comment]
how about now?

**Comment by fengkh** [comment]
> how about now?

https://github.com/pytorch/pytorch/issues/121208#issuecomment-1978363983
solved!
