### ISSUE TITLE
PyTorch Profiler is not working with CUDA

### ISSUE THREAD

**Issue by marewi** [pytorch/pytorch#65393]
Hi,
For me, Torch.Profiler is not working with CUDA activity only. With CPU it is working for me.

`import torch
from torch.profiler import profile, record_function, ProfilerActivity

with profile(
        activities=[torch.profiler.ProfilerActivity.CUDA],
        schedule=torch.profiler.schedule(wait=1, warmup=1, active=3, repeat=2),        
        on_trace_ready=torch.profiler.tensorboard_trace_handler('./log/model'),
        profile_memory=False,
        record_shapes=True,
        with_stack=True,
    ) as prof:
        for _ in range(10):
            y = torch.randn(1).cuda() + torch.randn(1).cuda()
            prof.step()
            

print(prof.key_averages())`

**Full stack error:**
`C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\profiler.py:440: UserWarning: CUPTI tracing is not available, falling back to legacy CUDA profiling
  warn("CUPTI tracing is not available, falling back to legacy CUDA profiling")
Traceback (most recent call last):
  File "test_profiler.py", line 14, in <module>
    prof.step()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\profiler\profiler.py", line 282, in step
    self._start_warmup()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\profiler\profiler.py", line 413, in _start_warmup
    self.profiler = prof.profile(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\profiler.py", line 447, in __init__
    assert len(self.kineto_activities) > 0, \
AssertionError: No activities specified for Kineto profiler

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_profiler.py", line 14, in <module>
    prof.step()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\profiler\profiler.py", line 253, in __exit__
    self._exit_actions()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\profiler\profiler.py", line 404, in _exit_actions
    self._start_trace()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\profiler\profiler.py", line 425, in _start_trace
    assert self.profiler is not None
AssertionError`

**System Info**
- torch: 1.9.0+cu111 (installed with pip)
- Python: 3.8.0
- OS: Windows Server
- GPU: NVIDIA Tesla V100-PCIE-16GB
- torch-tb-profiler==0.2.0

**Comment by cadop** [comment]
I have the same issue.

**Comment by mich-lee** [comment]
Do you have the CUPTI library installed?  If not, then that might be the reason for your error.

If you look at the stack trace, it shows that the legacy profiler in autograd is being used.  It seems like the new profiler will use the old profiler if the CUPTI library is not available.  Specifically, in torch/profiler/profiler.py it says:
> Note: profiler uses CUPTI library to trace on-device CUDA kernels.
>     In case when CUDA is enabled but CUPTI is not available, passing
>     ``ProfilerActivity.CUDA`` to profiler results in using the legacy CUDA
>     profiling code (same as in the legacy ``torch.autograd.profiler``).
>     This, in turn, results in including CUDA time in the profiler table output,
>     but not in the JSON trace.

So installing CUPTI might be the solution, provided you have not already done so.

**Comment by vladimir-aubrecht** [comment]
@marewi / @you74674 / @cadop Could you please provide steps to reproduce the issue?

**Comment by guotuofeng** [comment]
I don't think cupti on windows is supported. https://github.com/pytorch/pytorch/pull/65608 is the PR @cloudhan try to enable cupti on windows.

**Comment by vladimir-aubrecht** [comment]
@guotuofeng Thank you! Seems you are right. CUPTI support must be solved first.

**Comment by aaronenyeshi** [comment]
Since we have root caused this issue to https://github.com/pytorch/pytorch/issues/93855, let's close this one, and trace CUPTI w/ Windows in that issue.
