### ISSUE TITLE
Address is already in use with RPC framework in standalone mode

### ISSUE THREAD

**Issue by vycezhong** [pytorch/pytorch#65463]
## 🐛 Bug

I got an error that address is already in use when using RPC framework. 

## To Reproduce

Here is the minimal reproducible code. 
```py
import os
from datetime import timedelta

import torch
import torch.distributed.rpc as rpc


def main():
    world_size = int(os.environ['WORLD_SIZE'])
    rank = int(os.environ['RANK'])

    torch.distributed.init_process_group(
        'gloo', world_size=world_size,
        rank=rank, timeout=timedelta(seconds=10)
    )

    name = "worker{}".format(rank)
    rpc.init_rpc(name, rank=rank, world_size=world_size)
    torch.distributed.barrier()

if __name__ == "__main__":
    main()
```

Start the script with the command 
```sh
python -m torch.distributed.run --standalone --nnodes=1 --nproc_per_node=2 main.py
```

Error message 
```sh
(dev) ➜  rpc git:(torch_rpc) ✗ lsof -i:29400
(dev) ➜  rpc git:(torch_rpc) ✗ python -m torch.distributed.run --standalone --nnodes=1 --nproc_per_node=2 main.py
WARNING:__main__:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    main()
  File "main.py", line 18, in main
    rpc.init_rpc(name, rank=rank, world_size=world_size)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/rpc/__init__.py", line 185, in init_rpc
    store, _, _ = next(rendezvous_iterator)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 230, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 159, in _create_c10d_store
    hostname, port, world_size, start_daemon, timeout
RuntimeError: Address already in use
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    main()
  File "main.py", line 18, in main
    rpc.init_rpc(name, rank=rank, world_size=world_size)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/rpc/__init__.py", line 203, in init_rpc
    _init_rpc_backend(backend, store, name, rank, world_size, rpc_backend_options)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/rpc/__init__.py", line 243, in _init_rpc_backend
    rpc_backend_options=rpc_backend_options,
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/rpc/backend_registry.py", line 99, in init_backend
    return backend.value.init_backend_handler(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/rpc/backend_registry.py", line 306, in _tensorpipe_init_backend_handler
    group = _init_process_group(store, rank, world_size)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/rpc/backend_registry.py", line 122, in _init_process_group
    group = dist.ProcessGroupGloo(store, rank, world_size, process_group_timeout)
RuntimeError: Connection reset by peer
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 11270) of binary: /home/ubuntu/anaconda3/envs/dev/bin/python
/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:367: UserWarning:

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 11270 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/run.py", line 702, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 361, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/run.py", line 698, in main
    run(args)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/run.py", line 692, in run
    )(*cmd_args)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
***************************************
             main.py FAILED
=======================================
Root Cause:
[0]:
  time: 2021-09-22_13:30:03
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 11270)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2021-09-22_13:30:03
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 11271)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************
```

I got the same error even when I set `nproc_per_node=1`. 

## Expected behavior

It should work. 

## Environment

Amazon g4dn.xlarge instance. Deep Learning AMI (Ubuntu 18.04) Version 49.0

PyTorch Version (e.g., 1.0): **1.9.1**
OS (e.g., Linux): Ubuntu 18.04
How you installed PyTorch (conda, pip, source): pip
Build command you used (if compiling from source):
Python version: 3.6.9
CUDA/cuDNN version: 10.2/7.6.5
GPU models and configuration: T4
Any other relevant information:

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @gcramer23

**Comment by vycezhong** [comment]
I quickly browsed the code in the [tutorials](https://pytorch.org/docs/stable/rpc.html#tutorials). It seems that `init_process_group` is never used combined with `rpc.init_rpc`. Is there any conflict when using them both? I thought RPC and collective communication are orthogonal.

**Comment by vycezhong** [comment]
I solved it myself. I read the code in the tutorial and found I need to use different ports for `init_rpc` and `init_process_group`. https://pytorch.org/tutorials/advanced/rpc_ddp_tutorial.html

The modified code works. 
```py
import os
from datetime import timedelta

import torch
import torch.distributed.rpc as rpc


def main():
    world_size = int(os.environ['WORLD_SIZE'])
    rank = int(os.environ['RANK'])

    torch.distributed.init_process_group(
        'gloo', world_size=world_size,
        rank=rank, timeout=timedelta(seconds=10)
    )

    name = "worker{}".format(rank)
    rpc.init_rpc(name, rank=rank, world_size=world_size,
                 rpc_backend_options=rpc.TensorPipeRpcBackendOptions(
                     init_method="tcp://localhost:29401"
                 ))

    torch.distributed.barrier()



if __name__ == "__main__":
    main()
```
