### ISSUE TITLE
API torch.ops.image.read_file reports RuntimeError - No such operator image::read_file

### ISSUE THREAD

**Issue by Starballoon** [pytorch/pytorch#65473]
## To Reproduce

I'm new to PyTorch and I can't find helpful infomation from google or pytorch forum about this question.

1. Lanuch python intepreter on my devices (on Windows without / CentOS with Nvidia GPUs)
2. Import torch and run torch.ops.image.read_file()
3. Reports error

Originally I found this error trying to use API torchvision.io.read_image which calls torch.ops.image.read_file
But there is a weird phenomenon that I can not understand.
When I import **torch** and **torchvision both**, the API torch.ops.image.read_file works well but fails while **torch only**.

**Content from CMD on Windows:**

```
Microsoft Windows [Version 10.0.19042.1237] (c) Microsoft Corporation. All rights reserved.

C:\Users\zhaox\Desktop>conda activate zxq

(zxq) C:\Users\zhaox\Desktop>pip list | findstr torch
torch                              1.9.0
torchaudio                     0.9.0
torchvision                     0.10.0

(zxq) C:\Users\zhaox>python
Python 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
`>>> import torch`
`>>> torch.ops.image.read_file('')`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Environment\Anaconda3\envs\zxq\lib\site-packages\torch\_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
**RuntimeError: No such operator image::read_file**
`>>> import torchvision`
`>>> torch.ops.image.read_file('')`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**_RuntimeError: [Errno 2] No such file or directory: ''_**
**!!!Working well here!!!**
```

**Content from bash on CentOS:**

```
[zxq@bcm ~]$ python
Python 3.7.5 (default, Nov 30 2020, 13:16:00)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
`>>> import torch`
`>>> torch.ops.image.read_file('')`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cm/shared/apps/pytorch-py37-cuda11.2-gcc8/1.9.0/lib/python3.7/site-packages/torch/_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
**RuntimeError: No such operator image::read_file**
`>>> import torchvision`
`>>> torch.ops.image.read_file('')`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cm/shared/apps/pytorch-py37-cuda11.2-gcc8/1.9.0/lib/python3.7/site-packages/torch/_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
**RuntimeError: No such operator image::read_file**
```

## Expected behavior
It should work well that the file can be open.

## Environment

Both devices have torch==1.9.0 and torchvision==0.10.0.

PyTorch version: 1.9.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: 11.0.1
CMake version: version 3.20.0-rc3
Libc version: N/A

Python version: 3.8 (64-bit runtime)
Python platform: Windows-10-10.0.19042-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.2.0                 pypi_0    pypi
[conda] mkl-random         1.2.2                    pypi_0    pypi
[conda] mkl-service           2.4.0                    pypi_0    pypi
[conda] mkl_fft                  1.3.0            py38h277e83a_2
[conda] numpy                  1.20.3                   pypi_0    pypi
[conda] numpydoc            1.1.0              pyhd3eb1b0_1
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torchaudio            0.9.0                    pypi_0    pypi
[conda] torchvision            0.10.0                   pypi_0    pypi

## Additional Info
I also referred to this issue https://githubmemory.com/repo/pytorch/vision/issues/4181.
And the following is the linking check result of image.so of torchvision on a CentOS server with RTX 3090.
Another blog pointed out that questions about operators may be caused by version mismatch between torch and torchvision. So is torch==1.9.0 and torchvision==0.10.0 a mismatch combination?

```
[zxq@bcm ~]$ ldd /home/zxq/.local/lib/python3.7/site-packages/torchvision/image.so
ldd: warning: you do not have execution permission for `/home/zxq/.local/lib/python3.7/site-packages/torchvision/image.so'
        linux-vdso.so.1 =>  (0x00002aaaaaacd000)
        libpng16.7f72a3c5.so.16 => /home/zxq/.local/lib/python3.7/site-packages/torchvision/../torchvision.libs/libpng16.7f72a3c5.so.16 (0x00002aaaaaf0d000)
        libjpeg.ceea7512.so.62 => /home/zxq/.local/lib/python3.7/site-packages/torchvision/../torchvision.libs/libjpeg.ceea7512.so.62 (0x00002aaaab144000)
        libnvjpeg.a6b52b54.so.10 => /home/zxq/.local/lib/python3.7/site-packages/torchvision/../torchvision.libs/libnvjpeg.a6b52b54.so.10 (0x00002aaaab399000)
        libc10.so => /cm/shared/apps/pytorch-py37-cuda11.2-gcc8/1.9.0/lib/python3.7/site-packages/torch/lib/libc10.so (0x00002aaaab915000)
        libtorch.so => /cm/shared/apps/pytorch-py37-cuda11.2-gcc8/1.9.0/lib/python3.7/site-packages/torch/lib/libtorch.so (0x00002aaaabba0000)
        libtorch_cpu.so => /cm/shared/apps/pytorch-py37-cuda11.2-gcc8/1.9.0/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so (0x00002aaaabda2000)
        libtorch_python.so => /cm/shared/apps/pytorch-py37-cuda11.2-gcc8/1.9.0/lib/python3.7/site-packages/torch/lib/libtorch_python.so (0x00002aaab525d000)
        libcudart.459720b2.so.10.2 => /home/zxq/.local/lib/python3.7/site-packages/torchvision/../torchvision.libs/libcudart.459720b2.so.10.2 (0x00002aaab6ad5000)
        libc10_cuda.so => /cm/shared/apps/pytorch-py37-cuda11.2-gcc8/1.9.0/lib/python3.7/site-packages/torch/lib/libc10_cuda.so (0x00002aaab6d53000)
        libtorch_cuda.so => /cm/shared/apps/pytorch-py37-cuda11.2-gcc8/1.9.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so (0x00002aaab6f7b000)
        libstdc++.so.6 => /cm/shared/apps/gcc8/8.4.0/lib64/libstdc++.so.6 (0x00002aaaf1903000)
        libm.so.6 => /lib64/libm.so.6 (0x00002aaaf1c86000)
        libgcc_s.so.1 => /cm/shared/apps/gcc8/8.4.0/lib64/libgcc_s.so.1 (0x00002aaaf1f88000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaf21a0000)
        libc.so.6 => /lib64/libc.so.6 (0x00002aaaf23bc000)
        /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
        libz.1328edc3.so.1 => /home/zxq/.local/lib/python3.7/site-packages/torchvision/../torchvision.libs/libz.1328edc3.so.1 (0x00002aaaf278a000)
        librt.so.1 => /lib64/librt.so.1 (0x00002aaaf29a0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaf2ba8000)
        libnuma.so.1 => /lib64/libnuma.so.1 (0x00002aaaf2dac000)
        libgomp.so.1 => /cm/shared/apps/gcc8/8.4.0/lib64/libgomp.so.1 (0x00002aaaf2fb7000)
        libmpi.so.40 => /cm/shared/apps/openmpi4-cuda11.2-ofed50-gcc8/4.1.0/lib/libmpi.so.40 (0x00002aaaf31e5000)
        libopenblas.so.0 => /cm/shared/apps/openblas/0.3.7/lib/libopenblas.so.0 (0x00002aaaf34ed000)
        libcudart.so.11.0 => /cm/shared/apps/cuda11.2/toolkit/11.2.0/targets/x86_64-linux/lib/libcudart.so.11.0 (0x00002aaaf4eb5000)
        libshm.so => /cm/shared/apps/pytorch-py37-cuda11.2-gcc8/1.9.0/lib/python3.7/site-packages/torch/lib/libshm.so (0x00002aaaf5144000)
        libnvToolsExt.so.1 => /cm/shared/apps/cuda11.2/toolkit/11.2.0/targets/x86_64-linux/lib/libnvToolsExt.so.1 (0x00002aaaf534c000)
        libcudnn.so.8 => /cm/shared/apps/cudnn8.1-cuda11.2/8.1.1.33/lib64/libcudnn.so.8 (0x00002aaaf5555000)
        libcusparse.so.11 => /cm/shared/apps/cuda11.2/toolkit/11.2.0/targets/x86_64-linux/lib/libcusparse.so.11 (0x00002aaaf577e000)
        libcurand.so.10 => /cm/shared/apps/cuda11.2/toolkit/11.2.0/targets/x86_64-linux/lib/libcurand.so.10 (0x00002aab003cd000)
        libcusolver.so.11 => /cm/shared/apps/cuda11.2/toolkit/11.2.0/targets/x86_64-linux/lib/libcusolver.so.11 (0x00002aab05323000)
        libnccl.so.2 => /cm/shared/apps/nccl2-cuda11.2-gcc8/2.9.8/lib/libnccl.so.2 (0x00002aab28433000)
        libcufft.so.10 => /cm/shared/apps/cuda11.2/toolkit/11.2.0/targets/x86_64-linux/lib/libcufft.so.10 (0x00002aab2fb0c000)
        libcublas.so.11 => /cm/shared/apps/cuda11.2/toolkit/11.2.0/targets/x86_64-linux/lib/libcublas.so.11 (0x00002aab3b253000)
        libopen-rte.so.40 => /cm/shared/apps/openmpi4-cuda11.2-ofed50-gcc8/4.1.0/lib/libopen-rte.so.40 (0x00002aab4223b000)
        libopen-pal.so.40 => /cm/shared/apps/openmpi4-cuda11.2-ofed50-gcc8/4.1.0/lib/libopen-pal.so.40 (0x00002aab424f3000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00002aab427a3000)
        libhwloc.so.5 => /cm/shared/apps/hwloc/1.11.11/lib/libhwloc.so.5 (0x00002aab429a6000)
        libudev.so.1 => /lib64/libudev.so.1 (0x00002aab42be4000)
        libxml2.so.2 => /lib64/libxml2.so.2 (0x00002aab42dfa000)
        libevent_core-2.0.so.5 => /lib64/libevent_core-2.0.so.5 (0x00002aab43164000)
        libevent_pthreads-2.0.so.5 => /lib64/libevent_pthreads-2.0.so.5 (0x00002aab4338f000)
        libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00002aab43592000)
        libcublasLt.so.11 => /cm/shared/apps/cuda11.2/toolkit/11.2.0/targets/x86_64-linux/lib/libcublasLt.so.11 (0x00002aab438b4000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00002aab4f039000)
        libdw.so.1 => /lib64/libdw.so.1 (0x00002aab4f23e000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00002aab4f48f000)
        libquadmath.so.0 => /cm/shared/apps/gcc8/8.4.0/lib64/libquadmath.so.0 (0x00002aab4f6b5000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00002aab4f8f5000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00002aab4fafa000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00002aab4fd12000)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @bhosmer @smessmer @ljk53 @fmassa @vfdev-5 @pmeier

**Comment by ezyang** [comment]
for hysterical raisins 0.10 torchvision targets 1.9 torch, so there is not a version mismatch, AFAICT (cc @malfet)

**Comment by ezyang** [comment]
This is still probably an environment problem of some sort. What happens if you create a fresh conda environment and reinstall everything there

**Comment by malfet** [comment]
I can reproduce it in fresh conda env on my MacOS.

**Comment by ezyang** [comment]
bumping prio

**Comment by Starballoon** [comment]
> This is still probably an environment problem of some sort. What happens if you create a fresh conda environment and reinstall everything there

Another new environment with totally new installed torch series packages.
But unfortunately, is still  reproduces.
The following is from my CMD on Windows:]

Microsoft Windows [Version 10.0.19042.1237]
(c) Microsoft Corporation. All rights reserved.

C:\Users\zhaox>conda activate torchtest

(torchtest) C:\Users\zhaox>pip list
Package           Version
----------------- --------
astroid           2.4.2
autopep8          1.5.6
colorama          0.4.4
isort             5.6.4
lazy-object-proxy 1.4.3
mccabe            0.6.1
numpy             1.21.2
Pillow            8.3.2
pip               21.1.1
pycodestyle       2.7.0
pylint            2.6.0
setuptools        56.0.0
six               1.15.0
toml              0.10.2
torch             1.9.1
torchaudio        0.9.1
torchvision       0.10.1
typing-extensions 3.10.0.2
wrapt             1.12.1
WARNING: You are using pip version 21.1.1; however, version 21.2.4 is available.
You should consider upgrading via the 'c:\environment\python39\python.exe -m pip install --upgrade pip' command.

(torchtest) C:\Users\zhaox>python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.ops.image.read_file('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Environment\Python39\lib\site-packages\torch\_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::read_file
>>> import torchvision
>>> torch.ops.image.read_file('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: [Errno 2] No such file or directory: ''
>>>

**Comment by malfet** [comment]
@ezyang but I believe it works as expected (sort of):  
From https://github.com/pytorch/vision/blob/main/torchvision/io/image.py#L9 `torch.ops.load_library()` is called, which loads `image.so` library into the `torch.ops.` namespace, see 
https://github.com/pytorch/pytorch/blob/facff2ec6562d61eab2ccd9f1c16872e54eec92d/torch/_ops.py#L56-L69

**Comment by ezyang** [comment]
Actually this works for me on stock OS X install:

```
(base) ezyang-mbp:~ ezyang$ python b.py
Traceback (most recent call last):
  File "b.py", line 4, in <module>
    torch.ops.image.read_file('')
RuntimeError: [Errno 2] No such file or directory: ''
(base) ezyang-mbp:~ ezyang$ cat b.py
import torch
import torchvision

torch.ops.image.read_file('')
```

But torchvision is a little older, smh

```
torch                     1.9.0                    pypi_0    pypi
torchvision               0.8.2                  py37_cpu    pytorch
```

**Comment by Starballoon** [comment]
@ezyang 

I've tested the following combinations on Windows:
python 3.9.5 + torch 1.9.0 + torchvision 0.10.0
python 3.9.5 + torch 1.8.1 + torchvision 0.9.1
python 3.9.5 + torch 1.7.1 + torchvision 0.8.2
python 3.7.11 + torch 1.7.1 + torchvision 0.8.2

It reproduces the same every time.

**Comment by ashafaei** [comment]
Just updated to the latest version and got the same error.
The previous version work just fine for me `torch-1.9.0+cu111 torchaudio-0.9.0 torchvision-0.10.0+cu111`.
Running Python 3.7.6 on linux.

**Comment by ashafaei** [comment]
I found the problem. There's a part of the code where `torchvision` silently registers a library.
```
try:
    lib_path = _get_extension_path("image")
    torch.ops.load_library(lib_path)
except (ImportError, OSError):
    pass
```
When this import fails, no exception is raised. I commented the try-except block to see what happens. In my case, it was failing to load the library, because it depended on `libnvjpeg.so.11` which was apparently not present in my environment.

```
OSError: libnvjpeg.so.11: cannot open shared object file: No such file or directory
```

after digging in a bit, I found that this library comes from `cudatoolkit` which is installed through Conda in my environment. The currently installed cuda-toolkit was 10, but it was looking for version 11.

I installed cuda-toolkit 11 through Conda, 
```
conda install -c anaconda cudatoolkit
```
and I could see the libs here:
```
/home/user/anaconda3/pkgs/cudatoolkit-11.0.221-h6bb024c_0/lib/
```
but it was still failing to find it. I'm not sure what's the right way to handle this, but the quick workaround is to do this

```
export LD_LIBRARY_PATH=/home/user/anaconda3/pkgs/cudatoolkit-11.0.221-h6bb024c_0/lib/
```
so that the library is found during the import. After that, everything worked just fine. If you're doing this, just make sure the path you're setting is pointing to the correct `/lib` directory in Conda.

I'm not sure why this has happened, but I suspect that I've installed PyTorch thorough `pip` rather than `conda`, so the dependencies were not properly handled.

**Comment by carlogrisetti** [comment]
Can confirm that on windows the issue can be reproduced up to the latest nightly build.
The issue however is not present with torchvision==0.10.1 (hence torch==1.9.1)
I am using PIP wheels, and this works both in the CPU and CU111 flavors (and doesn't work on both flavors for other versions)

**Comment by Starballoon** [comment]
> Can confirm that on windows the issue can be reproduced up to the latest nightly build. The issue however is not present with torchvision==0.10.1 (hence torch==1.9.1) I am using PIP wheels, and this works both in the CPU and CU111 flavors (and doesn't work on both flavors for other versions) Got it respectively broken and working under Python 3.7.0 venv
> 
> I however did _not_ test torch==1.9.0 and torchvision==0.10.0
> 
> @Starballoon \ @malfet can you try with 1.9.1\0.10.1 and confirm it's working in that version pair?
> 
> Edit: I just noticed that both me and @ashafaei are on python 3.7.x and have 1.9.x working fine

Nothing different till the newest version **1.10.0\0.11.1** on Windows. I'm not sure if there is something wrong with the sequence of my PATH variables.

```CMD
Microsoft Windows [Version 10.0.19043.1348]
(c) Microsoft Corporation. All rights reserved.

C:\Users\zhaox>conda activate zxq

(zxq) C:\Users\zhaox>python
Python 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.ops.image.read_file('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Environment\Anaconda3\envs\zxq\lib\site-packages\torch\_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::read_file
>>> import torchvision
>>> torch.ops.image.read_file('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: [Errno 2] No such file or directory: ''
```

**Comment by carlogrisetti** [comment]
After importing torch vision it seems to be working, check your log output.
What happens if you pass an actual image filename instead of an empty string?

**Comment by Starballoon** [comment]
> After importing torchvision it seems to be working, check your log output. What happens if you pass an actual image filename instead of an empty string?

```CMD
Microsoft Windows [Version 10.0.19043.1387]
(c) Microsoft Corporation. All rights reserved.

C:\Users\zhaox\Desktop>conda activate zxq

(zxq) C:\Users\zhaox\Desktop>python
Python 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.ops.image.open_file('IMG_20210916_092059.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Environment\Anaconda3\envs\zxq\lib\site-packages\torch\_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::open_file
>>> import torchvision
>>> torch.ops.image.open_file('IMG_20210916_092059.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Environment\Anaconda3\envs\zxq\lib\site-packages\torch\_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::open_file
>>>
```

**Comment by carlogrisetti** [comment]
Well... I'm out of options. The only thing different from my setup is that I am using Python 3.7 as the system interpreter, and not in a conda environment.
Also I am using torch 1.9.1 and torchvision 0.10.1, but I think you already tried that.

**Comment by ashafaei** [comment]
@Starballoon it seems to me that you are having the same issue as I did. The image open file depends on libnvjpeg from cuda toolkit 11, and when it fails to load, it does so silently and you’ll only know through these operator not found messages. You can at least verify this is the problem by finding the code snippet I shared above in your PyTorch code and raise the exception instead of passing it. I’m not sure what to do on Windows, but it might work if you manually download and install the lastest cuda toolkit 11 from Nvidia.

**Comment by dantreiman** [comment]
I have a working stack on windows (Windows 10, conda, python 3.9) using:
```
% conda install pytorch torchvision torchtext torchaudio cudatoolkit=11.3 -c pytorch

torch=='1.10.1'
torchaudio='0.10.1'
torchtext=='0.11.1'
torchvision=='0.11.2'
```

before installing ludwig.  This all works for me, so I'm thinking that the issue is fixed in torchvision 0.11+.  @ashafaei @Starballoon Are you able to install the latest torchvision, and is this issue resolved for you also?

I'm considering removing the pinned dependencies for Windows: https://github.com/ludwig-ai/ludwig/pull/1998 - if this would cause a problem please let me know.

**Comment by zou3519** [comment]
This issue is stale so I'm closing it. If anyone else still experiences this then please file a new issue.
