### ISSUE TITLE
Exception when DataLoader's num_workers parameter is specified

### ISSUE THREAD

**Issue by nikoliazekter** [pytorch/pytorch#6548]
Code to reproduce is taken from tutorial:
```python
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)
dataiter = iter(trainloader)
images, labels = dataiter.next()
```

```
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f34ecb0e128>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 344, in __del__
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 325, in _shutdown_workers
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
```

**Comment by nikoliazekter** [comment]
Well it appeared again and I believe it's PyCharm problem as I could not reproduce it elsewhere. Putting `del dataiter` at the end of the code seems to solve it.

**Comment by Baltazahr** [comment]
I had the same problem in PyCharm and your solution works to fix it in PyCharm.
Would be nice if the examples worked though....still think this is a PyTorch issue.

**Comment by Baltazahr** [comment]
Also, for the images to show I had to add plt.show().
This is an old known issue from other examples in other frameworks that really should be updated in the tutorial...

**Comment by Baltazahr** [comment]
Also it seems like nobody has really tested this tutorial. I had to write 
net = net.to(device)

rather than the suggested:
net.to(device)

in order to get the net loaded onto GPU (which makes more sense since the tensors follow this syntax according to the tutorial).

I would have hoped a little more consistency from the very first tutorial one sees when trying out a new framework... :-(

**Comment by soumith** [comment]
@Baltazahr `net = net.to(device)` is not needed. nn.Module unlike a Tensor does a `to` recursively on it's members.

```
In [4]: x = torch.nn.Linear(10, 20)

In [5]: x
Out[5]: Linear(in_features=10, out_features=20, bias=True)

In [6]: x.weight.device
Out[6]: device(type='cpu')

In [7]: x.to('cuda:0')
Out[7]: Linear(in_features=10, out_features=20, bias=True)

In [8]: x.weight.device
Out[8]: device(type='cuda', index=0)
```

**Comment by gdymind** [comment]
`del dataiter` solved my problem. But why?
