### ISSUE TITLE
I cannot use x.to(GPU) or x.cuda(GPU)

### ISSUE THREAD

**Issue by ljz756245026** [pytorch/pytorch#65528]
## To Reproduce

```
>>> import torch
>>> x=torch.rand(2)
>>> x
tensor([0.8933, 0.5460])
>>> x.to(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: operation would make the legacy stream depend on a capturing blocking stream
>>> x.cuda(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: operation would make the legacy stream depend on a capturing blocking stream


```

![image](https://user-images.githubusercontent.com/21344631/134495818-75a703aa-e87d-4a0d-8d75-a17415c972c1.png)

## Expected behavior
```
>>> import torch
>>> x=torch.rand(2)
>>> x
tensor([0.9744, 0.4073])
>>> print(torch.cuda.is_available())
True
>>> x.to(0)
tensor([0.9744, 0.4073], device='cuda:0')
>>> quit();
```

## Environment
1.pytorch version:1.9.1
2.cuda 11.1 or 10.2
3.GPU:A100

![image](https://user-images.githubusercontent.com/21344631/134495616-bc51d100-f4f6-4fbd-8a07-eee6939ccc9f.png)
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.9.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.7.10 (default, Jun  4 2021, 14:48:32)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-34-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.1
[pip3] torchaudio==0.9.0a0+a85b239
[pip3] torchvision==0.10.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.3.0           h06a4308_520
[conda] mkl-service               2.4.0            py37h5e8e339_0    conda-forge
[conda] mkl_fft                   1.3.0            py37h42c9631_2
[conda] mkl_random                1.2.2            py37h219a48f_0    conda-forge
[conda] numpy                     1.20.3           py37hf144106_0
[conda] numpy-base                1.20.3           py37h74d4b33_0
[conda] pytorch                   1.9.1           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.9.1                      py37    pytorch
[conda] torchvision               0.10.1               py37_cu111    pytorch

 - PyTorch Version (e.g., 1.0):1.9.1
 - OS (e.g., Linux):Ubuntu 20.04.3 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Build command you used (if compiling from source):conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge

 - Python version:3.7.10
 - CUDA/cuDNN version: both 10.2 and 11.1
 - GPU models and configuration: A100
 - Any other relevant information:

**Comment by ngimel** [comment]
cc @mcarilli

**Comment by mcarilli** [comment]
This is very strange. You should only see this error if you're attempting cuda graph capture, but nothing in those simple ops should trigger graph capture.

On my machine with a recent build of master and cuda 11.4
```
>>> import torch
>>> x=torch.rand(2)
>>> x.to(0)
tensor([0.1777, 0.5853], device='cuda:0')
```
works without any errors.

**Comment by ptrblck** [comment]
Additionally, I also tested the conda 1.9.1 CUDA11.1 binaries, which also work on an A100 node.

> 2.cuda 11.1 or 10.2
CUDA/cuDNN version: both 10.2 and 11.1

Your A100 system would need CUDA>=11 and I'm unsure which CUDA Toolkit/Driver you've installed. Besides the question about the bad state, was this setup working previously and if so did you update anything recently e.g. without a restart?

**Comment by ljz756245026** [comment]
> This is very strange. You should only see this error if you're attempting cuda graph capture, but nothing in those simple ops should trigger graph capture.
> 
> On my machine with a recent build of master and cuda 11.4
> 
> ```
> >>> import torch
> >>> x=torch.rand(2)
> >>> x.to(0)
> tensor([0.1777, 0.5853], device='cuda:0')
> ```
> 
> works without any errors.
> 
> Did you try graph capture earlier, in a separate Python run, that may have left the cuda driver in a bad state?

I tried to run GraphSAGE code before. However, pytorch 1.7.1 works well on GraphSAGE.

**Comment by ljz756245026** [comment]
> Additionally, I also tested the conda 1.9.1 CUDA11.1 binaries, which also work on an A100 node.
> 
> > 2.cuda 11.1 or 10.2
> > CUDA/cuDNN version: both 10.2 and 11.1
> 
> Your A100 system would need CUDA>=11 and I'm unsure which CUDA Toolkit/Driver you've installed. Besides the question about the bad state, was this setup working previously and if so did you update anything recently e.g. without a restart?

![image](https://user-images.githubusercontent.com/21344631/134622334-42111120-bbec-4272-a704-e9a2abcd745d.png)
This is the cuda driver I used in this machine.

**Comment by ptrblck** [comment]
Thanks, I cannot reproduce the issue on a newly installed Ubuntu 20.04, NVIDIA driver 460.32.03 on an A100 node using the PyTorch `1.9.1` CUDA11.1 conda binaries.

**Comment by MTachon** [comment]
Hi,

I am also getting the same error as @ljz756245026.

I installed pytorch with conda by running the following:

`conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`

Running the **collect_env.py** script gives me the following output:

Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: Tesla V100S-PCIE-32GB
Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.11.0
[pip3] torch-points-kernels==0.7.1
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.9.2+cu111
[conda] blas 1.0 mkl
[conda] cudatoolkit 11.3.1 h2bc3f7f_2
[conda] ffmpeg 4.3 hf484d3e_0 pytorch
[conda] mkl 2021.4.0 h06a4308_640
[conda] mkl-service 2.4.0  y39h7f8727e_0
[conda] mkl_fft 1.3.1 py39hd3c417c_0
[conda] mkl_random 1.2.2 y39h51133e4_0
[conda] numpy 1.19.5 pypi_0 pypi
[conda] pytorch 1.11.0 py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex 1.0 cuda    pytorch
[conda] torch-points-kernels 0.7.1 pypi_0    pypi
[conda] torchaudio 0.11.0 py39_cu113    pytorch
[conda] torchvision 0.12.0 py39_cu113    pytorch

Do you know what could be the reason for not being able to perform a tensor device conversion?

**Comment by groucho64738** [comment]
Similar issues, basically any pytorch version > 1.8.1 fails with the same message. Is there an option or something that can be enabled to make this error go away since obviously it's something in pytorch that used to work and no longer does.

**Comment by ngimel** [comment]
As you've seen, we cannot reproduce this error, so we'd need some reproduction instructions to be able to look into it. To quote an earlier message 
>Did you try graph capture earlier, in a separate Python run, that may have left the cuda driver in a bad state?
Or anything else specific that you are doing?

**Comment by freemotionstudios** [comment]
I am getting this same error on a machine with an Nvidia TItan Xp. I was able to diagnose a few situations for reproducing the error and a possible workaround that might make sense to some pytorch folks. 
The error occurs if I use pytorch 1.13 or higher, with cuda 11x. 
I can make the error go away using pytorch 2.x with cuda 117 by changing the code to:
`print(x.to(torch.device("cuda")))
`
I do not get the error if I downgrade to pytorch 1.12.x with cuda 107. However, the application I am running cannot use pytorch < 1.13 so I am stuck. I have so far been unsuccessful trying to patch the application with this workaround, it is a rather large code base.
