### ISSUE TITLE
DISABLED test_profiler (__main__.TestJit)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#65521]
See https://github.com/pytorch/pytorch/runs/3682832751. Relevant snippet:

```
======================================================================
ERROR [0.013s]: test_profiler (__main__.TestJit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit.py", line 2728, in test_profiler
    traced_fn(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/profiler.py", line 202, in __exit__
    self.kineto_results = _disable_profiler()
RuntimeError: cpu_trace->activities.size() == kineto_events_.size()INTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/torch/csrc/autograd/profiler_kineto.cpp":239, please report a bug to PyTorch. 

======================================================================
ERROR [0.017s]: test_always_alive_values (jit.test_freezing.TestMKLDNNReinplacing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/jit/test_freezing.py", line 2134, in test_always_alive_values
    self.checkResults(mod_eager, mod)
  File "/var/lib/jenkins/workspace/test/jit/test_freezing.py", line 2091, in checkResults
    self.assertEqual(mod1(inp), mod2(inp))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 406, in prof_meth_call
    return prof_callable(meth_call, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 400, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: Couldn't find method: '_conv_forward' on class: '__torch__.torch.nn.modules.conv.___torch_mangle_2152.Conv2d (of Python compilation unit at: 0x56250e1ebd80)'

======================================================================
ERROR [0.010s]: test_merge_liveness (jit.test_freezing.TestMKLDNNReinplacing)
----------------------------------------------------------------------
  File "test_jit.py", line 5156, in test_cat
    self.assertAutodiffNode(func2.graph_for(x, y), True, ['aten::cat'], [])
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 282, in assertAutodiffNode
    found_all_nonfusible_nodes and found_all_fusible_nodes, err_msg)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1946, in assertEqual
    super().assertTrue(x == y, msg=msg)
AssertionError: False is not true : 
Failure in testing nodes' autodifferentiation. One or more nodes were expected to be autodiffed, but were not found in specified fusible/nonfusible DifferentiableGraph groups. 
Specifically:
  ['aten::cat'] were not in one of the DifferentiableGraphs when they were expected to be. Did you intend for these nodes to be autodiffed? If not, remove them from the list of nonfusible nodes.

======================================================================
FAIL [0.008s]: test_stack (__main__.TestScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit.py", line 5198, in test_stack
    self.assertAutodiffNode(func2.graph_for(x, y), True, ['aten::stack'], [])
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_jit.py", line 282, in assertAutodiffNode
    found_all_nonfusible_nodes and found_all_fusible_nodes, err_msg)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1946, in assertEqual
    super().assertTrue(x == y, msg=msg)
AssertionError: False is not true : 
Failure in testing nodes' autodifferentiation. One or more nodes were expected to be autodiffed, but were not found in specified fusible/nonfusible DifferentiableGraph groups. 
Specifically:
  ['aten::stack'] were not in one of the DifferentiableGraphs when they were expected to be. Did you intend for these nodes to be autodiffed? If not, remove them from the list of nonfusible nodes.

======================================================================
FAIL [0.004s]: test_tensor_requires_grad (__main__.TestScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit.py", line 7165, in test_tensor_requires_grad
    self.assertFalse(out_inp[2].requires_grad())
AssertionError: True is not false

======================================================================
FAIL [0.004s]: test_size_and_sizes (jit.test_symbolic_shape_analysis.TestSymbolicShapeAnalysis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/jit/test_symbolic_shape_analysis.py", line 160, in test_size_and_sizes
    self.assertEqual(next(graph.outputs()).type().symbolic_sizes(), [5, 8, sym1])
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1957, in assertEqual
    super().assertEqual(x, y, msg=msg)
AssertionError: None != [5, 8, -4896]

======================================================================
FAIL [0.007s]: test_canonicalize_tensor_iterator (jit.test_tracer.TestTracer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/jit/test_tracer.py", line 244, in test_canonicalize_tensor_iterator
    self.assertTrue(str(traced.graph_for(x)).count(': int = prim::Constant') == 5)
AssertionError: False is not true

======================================================================
FAIL [0.002s]: test_inplace_check (jit.test_tracer.TestTracer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/jit/test_tracer.py", line 342, in test_inplace_check
    ge(x)
AssertionError: RuntimeError not raised

----------------------------------------------------------------------
Ran 2564 tests in 86.085s

FAILED (failures=33, errors=16, skipped=91, expected failures=1)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by suo** [comment]
@eellison can you/someone look into the freezing tests?

**Comment by eellison** [comment]
@mruberry do you know when these started failing ?

**Comment by mruberry** [comment]
> @mruberry do you know when these started failing ?

I just saw them fail yesterday

**Comment by mruberry** [comment]
Happened again just now: https://github.com/pytorch/pytorch/runs/3741154257. Maybe an issue with the profiler or test_profiler triggering a cascade of failures?

**Comment by mruberry** [comment]
Continuing to occur: https://github.com/pytorch/pytorch/runs/3784790656

**Comment by eellison** [comment]
I'll disable the test_profiler tests or look into them... weird

**Comment by suo** [comment]
hm, another example: https://github.com/pytorch/pytorch/runs/3804782432.

@eellison can I disable these tests for now pending an investigation?

**Comment by eellison** [comment]
Sure can you disable https://github.com/pytorch/pytorch/blob/master/test/test_profiler.py  ? that seems to be source of error

**Comment by suo** [comment]
I think it's actually the `test_profiler` method in `test_jit`, but I will change this issue to disable that.

**Comment by sraikund16** [comment]
This test does not seem to be in test_profiler anymore

**Comment by davidberard98** [comment]
@sraikund16 I think this is actually this test:

https://github.com/pytorch/pytorch/blob/4154c8358a757f118b8ee6dbc61f7a2ede10cd15/test/test_jit.py#L370-L377
