### ISSUE TITLE
Derivative not implemented for narrow_copy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#65617]
```
>>> torch.narrow_copy(torch.zeros(2, requires_grad=True), 0, 0, 1)
tensor([0.], grad_fn=<NotImplemented>)
```

cc @bdhirsh

**Comment by nikitaved** [comment]
I could have a look.

**Comment by ezyang** [comment]
I think @bdhirsh was planning on giving this to a newbie :)

**Comment by nikitaved** [comment]
All right :)

**Comment by bdhirsh** [comment]
Thanks @nikitaved :)

@sean-ngo posting some of the stuff we talked about here:

(a) `narrow_copy` is an existing operator in pytorch, but it doesn't have a derivative formula currently implemented. That means that autograd will fail if you try to run it:
```
>>> import torch
>>> a = torch.ones(2, 2, requires_grad=True)  # requires_grad=True tells pytorch to keep track of autograd metadata about every operator that we call on `a`.
>>> b = torch.narrow_copy(a, 0, 0, 1)  # Uh oh, narrow_copy doesn't have a derivative formula. Can't autograd through this!
>>> b.backward() # This breaks.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/hirsheybar/pytorch-env/lib/python3.9/site-packages/torch/_tensor.py", line 320, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/scratch/hirsheybar/pytorch-env/lib/python3.9/site-packages/torch/autograd/__init__.py", line 150, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_)
  File "/scratch/hirsheybar/pytorch-env/lib/python3.9/site-packages/torch/autograd/__init__.py", line 51, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs
```

(b) There's a great tutorial on autograd / how it's used in pytorch in this collab notebook: https://colab.research.google.com/drive/1aWNdmYt7RcHMbUk-Xz2Cv5-cGFSWPXe0#scrollTo=armw9qKe7a-k

(c) The file `tools/autograd/derivatives.yaml` contains the derivative formula entries for every "primitive" operator in pytorch. You'll have to write a new entry for `narrow_copy`, that will have a structure like:
```
- name: narrow_copy(Tensor self, int dim, int start, int length) -> Tensor
  self: grad * <create_a_tensor_that_represents_derivative_of_narrow_copy_wrt_self>
```
In the above, `grad` is a special tensor created in the codegen, that represents the gradient of the output (`grad_output`). Through the chain rule, you're computing `grad_input = [d_output/d_input] * grad_output`.

(d) `narrow` is a type of view operation: it takes a slice into the input, but doesn't change any of the values. You can think about the gradient that you're computing as a "mask" of 1's and 0's. A similar type of operation that might give some intuition is `diag`, which takes the diagonal along a tensor. For example:
```
>>> a = torch.full((2, 2), 7, dtype=torch.float32, requires_grad=True) # compute a 2x2 tensor of 7's
>>> a
tensor([[7., 7.],
             [7., 7.]], requires_grad=True)
>>> b = a.diag()  # take the diagonal of the above square tensor
>>> b.sum().backward()
>>> a.grad
tensor([[1., 0.],
             [0., 1.]])
```
the gradient tensor contains 1's along the diagonal, because the diagonal elements of `a` directly contribute to the output. It contains 0's everywhere else, because the other elements of `a` didn't contribute at all to the output.

(e) Finally, take a look at the docs for [torch.narrow](https://pytorch.org/docs/stable/generated/torch.narrow.html) to get an idea of what it does. Taking an example:
```
>>> import torch
>>> a = torch.arange(16, dtype=torch.float32).reshape(4, 4)
>>> a
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
>>> a.narrow_copy(0, 0, 1) # Basically grabs the first row of `a`
tensor([[0., 1., 2., 3.]]
>>> a.narrow_copy(1, 0, 1) # Grabs the first column of `a`
tensor([[ 0.],
        [ 4.],
        [ 8.],
        [12.]])
```
the gradient for `narrow_copy` will be a similar type of mask of 1's and 0's.  In the first example (grabbing the first row of `a`), only the values of the first row of `a` have an effect on the output tensor. So the gradient should look something like:
```
grad_output * torch.tensor([[ 1., 1., 1., 1.],
                                                [ 0., 0., 0., 0.,],
                                                [ 0., 0., 0., 0.,],
                                                [ 0., 0., 0., 0.,]])
```
