### ISSUE TITLE
AttributeError: module 'torch.jit' has no attribute 'unused'

### ISSUE THREAD

**Issue by seyeeet** [pytorch/pytorch#65641]
## 🐛 Bug

I installed the new pytorch 1.9.1  on my env and although it says that it successfully intalled torchvision, when I try to import torch vision I get the following:

```
>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/seyeeet/anaconda3/envs/pytorch1.9/lib/python3.6/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import models
  File "/scratch/seyeeet/anaconda3/envs/pytorch1.9/lib/python3.6/site-packages/torchvision/models/__init__.py", line 5, in <module>
    from .inception import *
  File "/scratch/seyeeet/anaconda3/envs/pytorch1.9/lib/python3.6/site-packages/torchvision/models/inception.py", line 63, in <module>
    class Inception3(nn.Module):
  File "/scratch/seyeeet/anaconda3/envs/pytorch1.9/lib/python3.6/site-packages/torchvision/models/inception.py", line 195, in Inception3
    @torch.jit.unused
AttributeError: module 'torch.jit' has no attribute 'unused'
>>> 
```

**Comment by seyeeet** [comment]
I uninstalled and install each of the packages separately, now it is working.
