### ISSUE TITLE
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [0,0,0] Assertion `input_val >= zero && input_val <= one` failed.

### ISSUE THREAD

**Issue by seyeeet** [pytorch/pytorch#65659]
## 🐛 Bug
not sure what is wrong but I installed pytorch 1.9.1 and keep getting this error times to time although I am using cuda 10.2 and when I print `torch.version.cuda` it says cuda 102.
I installed pytorch via 
`conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`
the full error is like this
```
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [0,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [1,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [2,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [4,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [5,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [6,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [7,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [8,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [9,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [10,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [14,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [15,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [16,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [17,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [18,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [19,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [20,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [21,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [22,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [23,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [24,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [25,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [29,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [30,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [31,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [33,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [34,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [36,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [37,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [38,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [39,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [40,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [41,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [46,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [47,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [48,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [49,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [50,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [51,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [53,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [54,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [55,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [56,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [57,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [62,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1631630806732/work/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [0,0,0], thread: [63,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "run.py", line 148, in <module>
    main()
  File "run.py", line 140, in main
    train(args, train_dataloader, model, optimizer, epoch, global_step, train_writer, our_device)
  File "/scratch/seyeeet/train_utils.py", line 54, in train
    loss.backward()
  File "/scratch/seyeeet/anaconda3/envs/pytorch1.9/lib/python3.6/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/scratch/seyeeet/anaconda3/envs/pytorch1.9/lib/python3.6/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

just fyi I am not doing any debugging

**Comment by gchanan** [comment]
We cannot help without debugging (particularly setting CUDA_LAUNCH_BLOCKING), so I am going to close this issue.

**Comment by seyeeet** [comment]
@gchanan  I am not sure what you mean exactly. but i did have CUDA_LAUNCH_BLOCKING in my code also, and that is why I was confused why did error even happens :)
