### ISSUE TITLE
torch.onnx.export error 

### ISSUE THREAD

**Issue by kdheejb7** [pytorch/pytorch#65698]
## ❓ Questions and Help

Hello, I want to convert torch model to onnx file because of using tensorrt.
But I have one trouble with the torch.onnx.export function.
```
model = init_training_model(conf, paths.output)
model.eval()  
dummy_data = Variable(torch.randn(4, 3, 384, 1280, device="cuda:0"))  
torch.onnx.export(rpn_net.module, dummy_data, "output.onnx", export_params=True, verbose=True)  
````

When I run the codes, I have an error with some error messages.
```
Traceback (most recent call last):
  File "scripts/train_rpn_3d.py", line 347, in <module>
    main(args)
  File "scripts/train_rpn_3d.py", line 154, in main
    torch.onnx.export(rpn_net.module, dummy_data, "output.onnx", export_params = True, verbose = True)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 132, in export
    strip_doc_string, dynamic_axes)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 64, in export
    example_outputs=example_outputs, strip_doc_string=strip_doc_string, dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 329, in _export
    _retain_param_name, do_constant_folding)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 213, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 171, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 256, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 325, in forward
    torch._C._tracer_exit(tuple(out_vars))
RuntimeError: output of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.
```

But I don't know how to solve the error "RuntimeError: output of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer". 

Any issues in the torch repository don't solve the error. 
Please help me solve this error. 

Thank you

### Setup
python 3.6
torch==1.2.0
torchvision==0.4.0
cuda 10.0
Ubuntu 18.04

**Comment by jiafatom** [comment]
Can you try `torch==1.9.0` and just use
`dummy_data = torch.randn(4, 3, 384, 1280, device="cuda:0")` ?

**Comment by kdheejb7** [comment]
Thanks for your replying, @jiafatom !
I tried one more as you said, but a similar error happened.
```
...
...
...
 1043.5000   235.5000  1475.5000   523.5000    35.0000                            
 1051.5000   235.5000  1483.5000   523.5000    35.0000                            
 1059.5000   235.5000  1491.5000   523.5000    35.0000                            
[ CUDAFloatType{276480,5} ]) of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.                                                                     
```

**Comment by thiagocrepaldi** [comment]
@kdheejb7 Is this issue still relevant for you?

If so, please provide a full repro for us to proceed. The provided snippet is not runnable.
