### ISSUE TITLE
CUDA ROCm grad tests sometimes leak memory 

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#65797]
See https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test1/1881//console.

Relevant snippet:

```
03:35:56 ======================================================================
03:35:56 FAIL [0.197s]: test_fn_gradgrad_polygamma_polygamma_n_0_cuda_float64 (__main__.TestGradientsCUDA)
03:35:56 ----------------------------------------------------------------------
03:35:56 Traceback (most recent call last):
03:35:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
03:35:56     method(*args, **kwargs)
03:35:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
03:35:56     method(*args, **kwargs)
03:35:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1168, in __exit__
03:35:56     self.name, after - before, i))
03:35:56   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1955, in assertEqual
03:35:56     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
03:35:56 AssertionError: False is not true : Scalars failed to compare as equal! 0 != 512
03:35:56 __main__.TestGradientsCUDA.test_fn_gradgrad_polygamma_polygamma_n_0_cuda_float64 leaked 512 bytes CUDA memory on device 0
03:35:56 
03:35:56 ----------------------------------------------------------------------
03:35:56 Ran 7271 tests in 1429.642s
03:35:56 
03:35:56 FAILED (failures=1, skipped=3972)
```

I wonder if there is an actual memory leak with polygamma or there is a test suite or ROCm issue that makes a variety of tests sometimes report a memory leak?

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @mruberry

**Comment by mruberry** [comment]
We are also seeing this outside of ROCm jobs now, as tracked in issue https://github.com/pytorch/pytorch/issues/65797. Could be the same root issue.

**Comment by malfet** [comment]
Closing this one, as https://github.com/pytorch/pytorch/pull/65973 has landed
