### ISSUE TITLE
 GPU cannot load the video frames

### ISSUE THREAD

**Issue by H-B-L** [pytorch/pytorch#65925]
I’m trying to load a video with 100 frames, using Python 3+, by reading it frame-by-frame and then feed to CNN.

I want to use GPU to speed up this process, The code works properly on my laptop which has just CPU but when I am running the same code on a machine with 2 GPU and set the num_workers = 36 raised with error below:

" AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/exx/Documents/Hamed/Lab1528/Third Paper/3rd paper/video_loader.py", line 171, in __getitem__
    train_video_load_x = self.loader(fidx, 'video_x')[0] # [0] deletes the extra bach from loader
  File "/home/exx/Documents/Hamed/Lab1528/Third Paper/3rd paper/video_loader.py", line 146, in loader
    for i,videos_x in enumerate(data_loader_x):
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/exx/Documents/Hamed/Lab1528/Third Paper/3rd paper/video_loader.py", line 44, in __getitem__
    video = self.transform(video)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/exx/Documents/Hamed/Lab1528/Third Paper/3rd paper/video_loader.py", line 80, in __call__
    assert(cap.isOpened())
AssertionError "

Here is my try which the video loader taken from "https://github.com/YuxinZhaozyx/pytorch-VideoDataset" :
"
```
import os
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
import torchvision
import pandas as pd
import cv2

num = 32
epochs = 1
batch_size = 16
num_workers = 36

np.random.seed(0)
torch.manual_seed(0)
torch.cuda.manual_seed(0)

class VideoDataset(Dataset):   
    def __init__(self, csv_file, transform=None):
        self.dataframe = pd.read_csv(csv_file)
        self.transform = transform 

    def __len__(self):
        """
        Returns:
            int: number of rows of the csv file (not include the header).
        """
        return len(self.dataframe)

    def __getitem__(self, index):
        """ get a video """
        video = self.dataframe.iloc[index].path
        if self.transform:         
            video = self.transform(video)        
        return video
    
class VideoFilePathToTensor(object):
       def __init__(self, max_len=None, fps=None, padding_mode=None):
        self.max_len = max_len
        self.fps = fps
        assert padding_mode in (None, 'zero', 'last')
        self.padding_mode = padding_mode
        self.channels = 3  # only available to read 3 channels video

    def __call__(self, path):
        """
        Args:
            path (str): path of video file.
            
        Returns:
            torch.Tensor: Video Tensor (C x L x H x W)
        """
         # open video file
        cap = cv2.VideoCapture(path)   
        assert(cap.isOpened())
```
 
I expect the code to output the video frames with a dimension of [ batches, 3, frames, height, width]

## Environment

 - PyTorch Version: 1.9.0
 - OS:Linux
 - Python version: 3.8
 - CUDA/cuDNN version: 11
 - GPU models and configuration: 2 TITAN RTX 24G

cc @SsnL @VitalyFedyunin @ejguan @NivekT @ngimel

**Comment by ejguan** [comment]
Hey @H-B-L ,
Could you please re-format this issue? It's too hard for me to understand the it.
