### ISSUE TITLE
Negative view test fails for resize_

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#65945]
## To Reproduce

Adding `inplace_variant=torch.Tensor.resize_,` to OpInfo of `resize_` makes the `test_neg_view` test from `test/test_ops.py` fail.

```python
FAIL [0.002s]: test_neg_view_resize__cpu_float64 (__main__.TestMathBitsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 1054, in test_neg_view
    lambda x: not torch.is_complex(x))
  File "test_ops.py", line 1005, in _test_math_view
    self.assertEqual(inplace_forward, expected_forward)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1875, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1e-07 and atol=1e-07, found 124 element(s) (out of 125) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 16.141727638660463 (-7.630780794546761 vs. 8.5109468441137), which occurred at index (19, 3).
```

## Expected behavior

Test should pass.

## Additional context

`resize_as_` has the `inplace_variant` entry and I decided to add it to `resize_` as well in https://github.com/pytorch/pytorch/pull/65714 but tests began to [fail](https://github.com/pytorch/pytorch/runs/3743157620).

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry @anjali411 @dylanbespalko @Lezcano @nikitaved

**Comment by mruberry** [comment]
cc @anjali411 -- what's going on here?

**Comment by anjali411** [comment]
can repro it on latest master:

```py
>>> x = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.cdouble)
>>> y=x.conj().imag
>>> y
tensor([[-0., -0.],
        [-0., -0.],
        [-0., -0.]], dtype=torch.float64)
>>> y.resize_(2, 2)
tensor([[-0., 2.],
        [-0., 3.]], dtype=torch.float64)
```

**Comment by albanD** [comment]
As mentioned in the `resize_` doc: "The storage is reinterpreted as C-contiguous, ignoring the current strides".
So I think this is expected behavior.
