### ISSUE TITLE
Scale-down lambda incorrectly marking runners for deletion

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#65978]
We have multiple workflows getting cancelled at the moment due to _what we believe_ is a runner daemon crash / cancellation

![image](https://user-images.githubusercontent.com/1700823/135551345-e69c5de1-158e-41f9-85ce-85877de2ceaa.png)

Example: https://github.com/pytorch/pytorch/actions/runs/1293201795

<details>
<summary> Logs from the runner daemons </summary>

```
VENTS  1633050519752   [2021-10-01 01:08:34Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/mBh68xKhi8LyM7tp3vECvYXNFvuV4gyVGgmYCteuEZP9JH92QN/_apis/distributedtask/pools/1/messages?sessionId=50a0311f-5d33-4b5d-a292-568c30b2bcab&lastMessageId=1 timed out after 60 seconds.   1633050514725
EVENTS  1633050519752   [2021-10-01 01:08:34Z ERR  MessageListener] Catch exception during get next message.    1633050514725
EVENTS  1633050519752   [2021-10-01 01:08:34Z ERR  MessageListener] System.TimeoutException: The HTTP request timed out after 00:01:00.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)       1633050514726
EVENTS  1633050519752   [2021-10-01 01:08:34Z ERR  MessageListener] #####################################################       1633050514726
EVENTS  1633050519752   [2021-10-01 01:08:34Z ERR  MessageListener] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToke
n)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)   1633050514726
EVENTS  1633050519752   [2021-10-01 01:08:34Z ERR  MessageListener] #####################################################       1633050514726
EVENTS  1633050519752   [2021-10-01 01:08:34Z ERR  MessageListener] System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)     1633050514726
EVENTS  1633050519752   [2021-10-01 01:08:34Z ERR  MessageListener] #####################################################       1633050514726
EVENTS  1633050519752   [2021-10-01 01:08:34Z ERR  MessageListener] System.Net.Sockets.SocketException (125): Operation canceled        1633050514726
EVENTS  1633050519752   [2021-10-01 01:08:34Z INFO MessageListener] Retriable exception: The HTTP request timed out after 00:01:00.     1633050514726
EVENTS  1633050519752   [2021-10-01 01:08:34Z ERR  Terminal] WRITE ERROR: 2021-10-01 01:08:34Z: Runner connect error: The HTTP request timed out after 00:01:00.. Retrying until reconnected.  1633050514726
```

</details>

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by seemethere** [comment]
Looks like the first occurrence I can find of this starting to happen is here: https://github.com/pytorch/pytorch/actions/runs/1292977166

Which puts the incident timeline start at around `2021-09-30 23:35:30Z`, judging from the logs from the runner daemon

Command used to gather logs:
```
aws logs get-log-events --log-group-name /github-self-hosted-runners/gh-ci/linux_runner --log-stream-name i-0591aba1444676d44 --region us-east-1 --output text
```

**Comment by seemethere** [comment]
Basically the root cause is this: https://github.com/seemethere/terraform-aws-github-runner/commit/299b0dd66db1703e34183d91cb01fe7e22caf031

Yesterday we added a busy check for runners within our scale down lambda in order to not blindly try and scale them down through the API (which was the previous behaviour that lead to our rate limit hits yesterday)

I didn't think that this would affect the scale-down lambda like this but I had neglected the fact that ghRunner in this context doesn't actually refer to the actual runner we want to scale down until it reaches the conditional ([resolved in this commit](https://github.com/seemethere/terraform-aws-github-runner/commit/dd77fdb3985301b8c10f9462d88c668c198aa39e))

**Comment by seemethere** [comment]
This should now be resolved, going to try and write a script to re-trigger jobs on master so we can still get signal
