### ISSUE TITLE
How to use `MASTER_ADDR` in a distributed training script

### ISSUE THREAD

**Issue by vycezhong** [pytorch/pytorch#65992]
## ❓ Questions and Help

https://pytorch.org/docs/stable/elastic/run.html

> `MASTER_ADDR` - The FQDN of the host that is running worker with rank 0; used to initialize the Torch Distributed backend.

The document says `MASTER_ADDR` is the hostname of the master node. But the hostname may not be resolved by other nodes. What's the use case of `MASTER_ADDR`?

For example, in AWS, the hostname of the master node is `ip-172-30-2-12` which is not recognized by other nodes.

On "ip-172-30-2-12":
```sh
(dev) ➜  ~ hostname
ip-172-30-2-12
```
On another machine:
```sh
(dev) ➜  ~ getent hosts ip-172-30-2-12

(dev) ➜  ~
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by wanchaol** [comment]
@vycezhong I saw you already close the related issue, is this still an open issue?

**Comment by vycezhong** [comment]
@wanchaol  The two questions are not the same. That issue is more than a context of the this issue. Here is the full story.

According to this [comment](https://github.com/pytorch/pytorch/issues/64990#issuecomment-931570902), the following code should be the best practice when using `torch.distributed`. 
```py
dist.init_process_group("nccl")
```

Users do not need to specify `init_method` by themselves because the program will read the hyper-parameters from the environment variables, which are passed by the agent. 

Unfortunately, it does not work in my case. The reason for the problem is that the `MASTER_ADDR` environment variable uses the hostname of the master node, not the ip address, which cannot be successfully recognized by other nodes. 

https://github.com/pytorch/pytorch/blob/3bd26792c06a4537883537997078de9d4a73e48d/torch/distributed/elastic/agent/server/api.py#L506-L518

Therefore, I need to explicitly specify the master ip address in `init_method`, which would have been unnecessary.

**Comment by vycezhong** [comment]
We have found a workaround. 

https://github.com/horovod/horovod/issues/3118#issuecomment-961765762

**Comment by mtaha2509** [comment]
I am pretty new to Kubernetes, I have created a cluster of 3 GPUs and tried to run a model's inference but I am coming across this error:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/openlrm/launch.py", line 36, in <module>
    main()
  File "/app/openlrm/launch.py", line 31, in main
    with RunnerClass() as runner:
         ^^^^^^^^^^^^^
  File "/app/openlrm/runners/infer/lrm.py", line 124, in __init__
    super().__init__()
  File "/app/openlrm/runners/infer/base_inferrer.py", line 35, in __init__
    self.accelerator = Accelerator()
                       ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/accelerator.py", line 425, in __init__
    self.state = AcceleratorState(
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/state.py", line 861, in __init__
    PartialState(cpu, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/accelerate/state.py", line 227, in __init__
    raise ValueError(
ValueError: Tried to launch on distributed with multinode, but `MASTER_ADDR` env was not set, please try exporting rank 0's hostname as `MASTER_ADDR`
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/openlrm/launch.py", line 36, in <module>
    main()
  File "/app/openlrm/launch.py", line 31, in main
    with RunnerClass() as runner:
         ^^^^^^^^^^^^^
  File "/app/openlrm/runners/infer/lrm.py", line 124, in __init__
    super().__init__()
  File "/app/openlrm/runners/infer/base_inferrer.py", line 35, in __init__
    self.accelerator = Accelerator()
                       ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/accelerator.py", line 425, in __init__
    self.state = AcceleratorState(
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/state.py", line 861, in __init__
    PartialState(cpu, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/accelerate/state.py", line 227, in __init__
    raise ValueError(
ValueError: Tried to launch on distributed with multinode, but `MASTER_ADDR` env was not set, please try exporting rank 0's hostname as `MASTER_ADDR`
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[19782,1],1]
  Exit code:    1
--------------------------------------------------------------------------


If anyone guides me, it would mean a lot!
