### ISSUE TITLE
Segmentation fault after removing hook within its associated hook function.

### ISSUE THREAD

**Issue by tesfaldet** [pytorch/pytorch#66037]
## 🐛 Bug

When removing a registered hook from within its associated hook function (after `.backward()` is called), a segmentation fault occurs.

This is what a more knowledgeable colleague had to say from his quick glance:

---

"From what I glean it's
```
torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) ()
```
calling into
```
torch::autograd::PyFunctionPreHook::operator()(std::vector<at::Tensor, std::allocator<at::Tensor> > const&) ()
```
calling into
```
check_single_result(_object*, _object*, _object*) ()
```
calling into
```
hook_name(_object*) ()
```
all somewhere in `libtorch_python.so`, and vomiting when it tries to get a Python string hook name that is no longer alive. Many of these are here: https://github.com/pytorch/pytorch/blob/release/1.9/torch/csrc/autograd/python_hook.cpp. [It] explodes while at this line: https://github.com/pytorch/pytorch/blob/release/1.9/torch/csrc/autograd/python_hook.cpp#L175

Also, from looking at this file, it is rather clear to me that (with methods like `check_result()` to check return values of hooks, and that use `hook_name()` to print error messages with its name) there is an implicit assumption that the hook is still a live Python object after it has returned. But if it itself removed during its own execution the before-last reference to itself, and then (by returning) lost the only remaining reference to itself, then Python will destruct it then and there, its name with it. So that by the time an attempt is made to access the name, it's gone and a segfault occurs.

Hence my suggestion to keepalive the hooks in a `doomed_list`, which retains one refcount to the hook and prevents its early destruction

Yep, here's what I see:
https://github.com/pytorch/pytorch/blob/release/1.7/torch/csrc/autograd/python_hook.cpp#L46-L49
`PyObject_CallFunctionObjArgs(hook, value.get(), nullptr)` but no `Py_INCREF(hook)` before the call, so that it is possible for the `hook` to have reached refcount 0 and been destroyed by the time the function returns, and then three lines later `check_single_result(value.get(), res.get(), hook);` leads into the segfaulting path by accessing the dead hook's name."

---

## To Reproduce

1. Register a hook on a tensor that will be used in the backward pass. Save hook handle for later.
2. Within the hook function, the hook will be removed via the handle that was saved previously.
3. Execute backward pass

### Minimal working example (adapted from [DEQ](https://github.com/locuslab/deq))
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.autograd as autograd
import numpy as np


def _safe_norm(v):
    if not torch.isfinite(v).all():
        return np.inf
    return torch.norm(v)


def line_search(update, x0, g0, g, nstep=0, on=True):
    """
    `update` is the propsoed direction of update.

    Code adapted from scipy.
    """
    tmp_s = [0]
    tmp_g0 = [g0]
    tmp_phi = [torch.norm(g0)**2]
    s_norm = torch.norm(x0) / torch.norm(update)

    def phi(s, store=True):
        if s == tmp_s[0]:
            return tmp_phi[0]    # If the step size is so small... just return something
        x_est = x0 + s * update
        g0_new = g(x_est)
        phi_new = _safe_norm(g0_new)**2
        if store:
            tmp_s[0] = s
            tmp_g0[0] = g0_new
            tmp_phi[0] = phi_new
        return phi_new
    
    if on:
        pass
    if (not on) or s is None:
        s = 1.0
        ite = 0

    x_est = x0 + s * update
    if s == tmp_s[0]:
        g0_new = tmp_g0[0]
    else:
        g0_new = g(x_est)
    return x_est, g0_new, x_est - x0, g0_new - g0, ite

def rmatvec(part_Us, part_VTs, x):
    # Compute x^T(-I + UV^T)
    # x: (N, 2d, L')
    # part_Us: (N, 2d, L', threshold)
    # part_VTs: (N, threshold, 2d, L')
    if part_Us.nelement() == 0:
        return -x
    xTU = torch.einsum('bij, bijd -> bd', x, part_Us)   # (N, threshold)
    return -x + torch.einsum('bd, bdij -> bij', xTU, part_VTs)    # (N, 2d, L'), but should really be (N, 1, (2d*L'))

def matvec(part_Us, part_VTs, x):
    # Compute (-I + UV^T)x
    # x: (N, 2d, L')
    # part_Us: (N, 2d, L', threshold)
    # part_VTs: (N, threshold, 2d, L')
    if part_Us.nelement() == 0:
        return -x
    VTx = torch.einsum('bdij, bij -> bd', part_VTs, x)  # (N, threshold)
    return -x + torch.einsum('bijd, bd -> bij', part_Us, VTx)     # (N, 2d, L'), but should really be (N, (2d*L'), 1)

def broyden(f, x0, threshold, eps=1e-3, stop_mode="rel", ls=False, name="unknown"):
    bsz, total_hsize, seq_len = x0.size()
    g = lambda y: f(y) - y
    dev = x0.device
    alternative_mode = 'rel' if stop_mode == 'abs' else 'abs'
    
    x_est = x0           # (bsz, 2d, L')
    gx = g(x_est)        # (bsz, 2d, L')
    nstep = 0
    tnstep = 0
    
    # For fast calculation of inv_jacobian (approximately)
    Us = torch.zeros(bsz, total_hsize, seq_len, threshold).to(dev) # One can also use an L-BFGS scheme to further reduce memory
    VTs = torch.zeros(bsz, threshold, total_hsize, seq_len).to(dev)
    update = -matvec(Us[:,:,:,:nstep], VTs[:,:nstep], gx)      # Formally should be -torch.matmul(inv_jacobian (-I), gx)
    prot_break = False
    
    # To be used in protective breaks
    protect_thres = (1e6 if stop_mode == "abs" else 1e3) * seq_len
    new_objective = 1e8

    trace_dict = {'abs': [],
                  'rel': []}
    lowest_dict = {'abs': 1e8,
                   'rel': 1e8}
    lowest_step_dict = {'abs': 0,
                        'rel': 0}
    nstep, lowest_xest, lowest_gx = 0, x_est, gx

    while nstep < threshold:
        x_est, gx, delta_x, delta_gx, ite = line_search(update, x_est, gx, g, nstep=nstep, on=ls)
        nstep += 1
        tnstep += (ite+1)
        abs_diff = torch.norm(gx).item()
        rel_diff = abs_diff / (torch.norm(gx + x_est).item() + 1e-9)
        diff_dict = {'abs': abs_diff,
                     'rel': rel_diff}
        trace_dict['abs'].append(abs_diff)
        trace_dict['rel'].append(rel_diff)
        for mode in ['rel', 'abs']:
            if diff_dict[mode] < lowest_dict[mode]:
                if mode == stop_mode: 
                    lowest_xest, lowest_gx = x_est.clone().detach(), gx.clone().detach()
                lowest_dict[mode] = diff_dict[mode]
                lowest_step_dict[mode] = nstep

        new_objective = diff_dict[stop_mode]
        if new_objective < eps: break
        if new_objective < 3*eps and nstep > 30 and np.max(trace_dict[stop_mode][-30:]) / np.min(trace_dict[stop_mode][-30:]) < 1.3:
            # if there's hardly been any progress in the last 30 steps
            break
        if new_objective > trace_dict[stop_mode][0] * protect_thres:
            prot_break = True
            break

        part_Us, part_VTs = Us[:,:,:,:nstep-1], VTs[:,:nstep-1]
        vT = rmatvec(part_Us, part_VTs, delta_x)
        u = (delta_x - matvec(part_Us, part_VTs, delta_gx)) / torch.einsum('bij, bij -> b', vT, delta_gx)[:,None,None]
        vT[vT != vT] = 0
        u[u != u] = 0
        VTs[:,nstep-1] = vT
        Us[:,:,:,nstep-1] = u
        update = -matvec(Us[:,:,:,:nstep], VTs[:,:nstep], gx)

    # Fill everything up to the threshold length
    for _ in range(threshold+1-len(trace_dict[stop_mode])):
        trace_dict[stop_mode].append(lowest_dict[stop_mode])
        trace_dict[alternative_mode].append(lowest_dict[alternative_mode])

    return {"result": lowest_xest,
            "lowest": lowest_dict[stop_mode],
            "nstep": lowest_step_dict[stop_mode],
            "prot_break": prot_break,
            "abs_trace": trace_dict['abs'],
            "rel_trace": trace_dict['rel'],
            "eps": eps,
            "threshold": threshold}

def tensor2vec(x):
    b = x.shape[0]
    return x.reshape(b, -1, 1)

def vec2tensor(x, shape):
    b = x.shape[0]
    return x.reshape(b, *shape)

def remove_hook(hook, removed_hooks) -> None:
	hooks_dict = hook.hooks_dict_ref()
	if hooks_dict is not None and hook.id in hooks_dict:
		removed_hooks.append(hooks_dict.pop(hook.id, None))

class ResNetLayer(nn.Module):
    def __init__(self, n_channels, n_inner_channels, kernel_size=3, num_groups=8):
        super().__init__()
        self.conv1 = nn.Conv2d(n_channels, n_inner_channels, kernel_size, padding=kernel_size//2, bias=False)
        self.conv2 = nn.Conv2d(n_inner_channels, n_channels, kernel_size, padding=kernel_size//2, bias=False)
        self.norm1 = nn.GroupNorm(num_groups, n_inner_channels)
        self.norm2 = nn.GroupNorm(num_groups, n_channels)
        self.norm3 = nn.GroupNorm(num_groups, n_channels)
        self.conv1.weight.data.normal_(0, 0.01)
        self.conv2.weight.data.normal_(0, 0.01)
        
    def forward(self, z, x):
        y = self.norm1(F.relu(self.conv1(z)))
        return self.norm3(F.relu(z + self.norm2(x + self.conv2(y))))


class DEQModel(nn.Module):
    def __init__(self, f, solver, **kwargs):
        super().__init__()
        self.f = f
        self.solver = solver
        self.kwargs = kwargs
        self.hook = None
        self.removed_hooks = []
    
    def forward(self, x):
        # Preparation
        _, c, h, w = x.shape
        z0 = tensor2vec(torch.zeros_like(x))  # initial z state is zero
        func = lambda z: tensor2vec(self.f(vec2tensor(z, (c, h, w)), x))

        # Forward pass. Solve for fixed point of f -> z_star.
        with torch.no_grad():
            z_star = self.solver(func, z0, **self.kwargs)['result']

        # Backward pass
        if self.training:
            # re-engage autograd tape
            z_star_old = z_star.requires_grad_()
            z_star = func(z_star_old)

            def backward_hook(grad):
                if self.hook is not None:
                    self.hook.remove()  # To avoid infinite recursion when calling autograd.grad(z_star, ...)
                    # remove_hook(self.hook, self.removed_hooks) # uncomment to use custom remove hook function
                    torch.cuda.synchronize()
                # Compute the fixed point of yJ + grad, where J=J_f is the Jacobian of f at z_star
                # look at http://implicit-layers-tutorial.org/deep_equilibrium_models/
                grad_func = lambda y: autograd.grad(z_star, z_star_old, y, retain_graph=True)[0] + grad
                new_grad = self.solver(grad_func, torch.zeros_like(grad), **self.kwargs)['result']
                return new_grad

            self.hook = z_star.register_hook(backward_hook)
        return vec2tensor(z_star, (c, h, w))

def train():
    # Models
    f = ResNetLayer(64, 128)
    deq = DEQModel(f, broyden, threshold=30, stop_mode='abs', eps=1e-3)

    # Optimizer
    opt = torch.optim.Adam(deq.parameters(), 1e-3)

    # Inputs and ground truths
    x = torch.randn(10, 64, 32, 32)
    y = torch.randn_like(x)

    deq.train()
    for i in range(100):
        # Output and loss
        y_hat = deq(x)
        loss = F.mse_loss(y_hat, y)

        # Backward pass and logging
        with torch.no_grad():
            opt.zero_grad()
            loss.backward()
            opt.step()

            # Let garbage collector deal with removed hook references
            # uncomment when using custom remove hook function
            # if i % 2:
            #     deq.removed_hooks = []

            print('iter: {} loss: {}'.format(i, loss.item()))

if __name__ == '__main__':
    train()
```

### GDB backtrace
```
(gdb) r
Starting program: /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/bin/python deq_example.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffebc699700 (LWP 32585)]
[New Thread 0x7ffebbe98700 (LWP 32586)]
[New Thread 0x7ffebb697700 (LWP 32587)]
[New Thread 0x7ffebae96700 (LWP 32588)]
[New Thread 0x7ffeba695700 (LWP 32589)]
[New Thread 0x7ffeb1f6c700 (LWP 32600)]
[New Thread 0x7ffeb176b700 (LWP 32601)]
[New Thread 0x7ffeb0f6a700 (LWP 32603)]
[New Thread 0x7ffe91fff700 (LWP 32606)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
func_get_name (op=0x7ffebce3c280, _unused_ignored=0x0) at /tmp/build/80754af9/python-split_1628000493704/work/Objects/funcobject.c:302
302	/tmp/build/80754af9/python-split_1628000493704/work/Objects/funcobject.c: No such file or directory.
(gdb) backtrace
#0  func_get_name (op=0x7ffebce3c280, _unused_ignored=0x0) at /tmp/build/80754af9/python-split_1628000493704/work/Objects/funcobject.c:302
#1  0x000055555568e144 in _PyObject_GenericGetAttrWithDict (suppress=0, dict=0x0, name=0x7ffec24c38b0, obj=0x7ffebce3c280)
    at /tmp/build/80754af9/python-split_1628000493704/work/Objects/object.c:1254
#2  PyObject_GenericGetAttr (name=0x7ffec24c38b0, obj=0x7ffebce3c280)
    at /tmp/build/80754af9/python-split_1628000493704/work/Objects/object.c:1335
#3  PyObject_GetAttr () at /tmp/build/80754af9/python-split_1628000493704/work/Objects/object.c:941
#4  0x000055555568e989 in PyObject_GetAttrString () at /tmp/build/80754af9/python-split_1628000493704/work/Objects/object.c:846
#5  0x00005555555ce5ab in PyObject_HasAttrString (v=<optimized out>, name=<optimized out>)
    at /tmp/build/80754af9/python-split_1628000493704/work/Objects/object.c:854
#6  0x00007fffc5d7dd8b in hook_name(_object*) ()
   from /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#7  0x00007fffc5d7e1ae in check_single_result(_object*, _object*, _object*) ()
   from /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#8  0x00007fffc5d7e7aa in torch::autograd::PyFunctionPreHook::operator()(std::vector<at::Tensor, std::allocator<at::Tensor> > const&) ()
   from /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#9  0x00007fff4fba7bfb in torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) ()
   from /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#10 0x00007fff4fba9a0b in torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) ()
   from /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#11 0x00007fff4fba76fb in torch::autograd::Engine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>, torch::autograd::InputBuffer&&) ()
   from /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#12 0x00007fffc5d6dfec in torch::autograd::python::PythonEngine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>, torch::autograd::InputBuffer&&) ()
   from /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#13 0x00007fff4fba586e in torch::autograd::Engine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) () from /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#14 0x00007fffc5d6df46 in torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) ()
   from /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#15 0x00007fffc5d6ec35 in THPEngine_run_backward(_object*, _object*, _object*) ()
   from /home/mila/m/mattie.tesfaldet/.conda/envs/pytorch1.9/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#16 0x00005555556908ee in cfunction_call_varargs () at /tmp/build/80754af9/python-split_1628000493704/work/Objects/call.c:743
#17 0x000055555568575f in _PyObject_MakeTpCall () at /tmp/build/80754af9/python-split_1628000493704/work/Objects/call.c:159
#18 0x000055555572f00a in _PyObject_Vectorcall (kwnames=0x7ffebda6d500, nargsf=<optimized out>, args=<optimized out>, callable=0x7ffebce3e810)
    at /tmp/build/80754af9/python-split_1628000493704/work/Include/cpython/abstract.h:125
#19 call_function (kwnames=0x7ffebda6d500, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=<optimized out>)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:4963
#20 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:3515
#21 0x0000555555720480 in PyEval_EvalFrameEx (throwflag=0, f=0x7ffff681fc40)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:741
#22 _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:4298
#23 0x0000555555721a44 in _PyFunction_Vectorcall () at /tmp/build/80754af9/python-split_1628000493704/work/Objects/call.c:436
#24 0x000055555572b159 in _PyObject_Vectorcall (kwnames=0x7ffec2492430, nargsf=<optimized out>, args=<optimized out>, callable=0x7ffebd9d04c0)
    at /tmp/build/80754af9/python-split_1628000493704/work/Include/cpython/abstract.h:127
#25 call_function (kwnames=0x7ffec2492430, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=<optimized out>)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:4963
#26 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:3515
#27 0x0000555555720480 in PyEval_EvalFrameEx (throwflag=0, f=0x7ffebd3e0040)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:741
#28 _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:4298
#29 0x00005555557219e4 in _PyFunction_Vectorcall () at /tmp/build/80754af9/python-split_1628000493704/work/Objects/call.c:436
#30 0x000055555572a070 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x5555589e8ee0, callable=0x7ffec23c4700)
    at /tmp/build/80754af9/python-split_1628000493704/work/Include/cpython/abstract.h:127
#31 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x5555558f3110)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:4963
#32 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:3486
#33 0x0000555555721667 in PyEval_EvalFrameEx (throwflag=0, f=0x5555589e8d20)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:741
#34 function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=<optimized out>)
    at /tmp/build/80754af9/python-split_1628000493704/work/Objects/call.c:284
---Type <return> to continue, or q <return> to quit---
#35 _PyFunction_Vectorcall () at /tmp/build/80754af9/python-split_1628000493704/work/Objects/call.c:411
#36 0x000055555572a2cb in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff7e695b0, callable=0x7ffebce3ae50)
    at /tmp/build/80754af9/python-split_1628000493704/work/Include/cpython/abstract.h:127
#37 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x5555558f3110)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:4963
#38 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:3500
#39 0x0000555555720480 in PyEval_EvalFrameEx (throwflag=0, f=0x7ffff7e69440)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:741
#40 _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:4298
#41 0x0000555555721d33 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0,
    locals=<optimized out>, globals=<optimized out>, _co=<optimized out>)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:4327
#42 PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/ceval.c:718
#43 0x00005555557954a2 in run_eval_code_obj () at /tmp/build/80754af9/python-split_1628000493704/work/Python/pythonrun.c:1166
#44 0x00005555557a6292 in run_mod () at /tmp/build/80754af9/python-split_1628000493704/work/Python/pythonrun.c:1188
#45 0x00005555557a942b in pyrun_file () at /tmp/build/80754af9/python-split_1628000493704/work/Python/pythonrun.c:1085
#46 0x00005555557a960f in pyrun_simple_file (flags=0x7fffffffcbb8, closeit=1, filename=0x7ffff6d379f0, fp=0x5555559c9a50)
    at /tmp/build/80754af9/python-split_1628000493704/work/Python/pythonrun.c:439
#47 PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python-split_1628000493704/work/Python/pythonrun.c:472
#48 0x00005555557a9ae9 in pymain_run_file (cf=0x7fffffffcbb8, config=0x5555558f2320)
    at /tmp/build/80754af9/python-split_1628000493704/work/Modules/main.c:391
#49 pymain_run_python (exitcode=0x7fffffffcbb0) at /tmp/build/80754af9/python-split_1628000493704/work/Modules/main.c:616
#50 Py_RunMain () at /tmp/build/80754af9/python-split_1628000493704/work/Modules/main.c:695
#51 0x00005555557a9ce9 in Py_BytesMain () at /tmp/build/80754af9/python-split_1628000493704/work/Modules/main.c:1127
#52 0x00007ffff703fbf7 in __libc_start_main (main=0x55555565c860 <main>, argc=2, argv=0x7fffffffcda8, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffcd98) at ../csu/libc-start.c:310
#53 0x000055555574b847 in _start ()
```

## Expected behavior

Hook should be removed without causing a segmentation fault.

## Environment
 
 ```
 (pytorch1.9) mattie.tesfaldet@cn-c040:~$ python collect_env.py
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.2 LTS (x86_64)
GCC version: (GCC) 7.4.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.11 (default, Aug  3 2021, 15:09:35)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-45-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro RTX 8000
Nvidia driver version: 460.56
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0
[pip3] torch-tb-profiler==0.2.1
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.9.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torch-tb-profiler         0.2.1                    pypi_0    pypi
[conda] torchaudio                0.9.0                      py38    pytorch
[conda] torchvision               0.10.0               py38_cu111    pytorch
(pytorch1.9) mattie.tesfaldet@cn-c040:~$ nvidia-smi
Fri Oct  1 18:02:42 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.56       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 8000     On   | 00000000:C3:00.0 Off |                  Off |
| 33%   25C    P8     9W / 260W |      1MiB / 48601MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
 ```

## Additional context

If you place a `breakpoint()` before `self.hook.remove()` and repeatedly, but slowly, "continue" to that breakpoint, you can avoid the segmentation fault, leading me to believe it's a race condition issue.

**Comment by ezyang** [comment]
Suggested fix seems reasonable, but @albanD may have a more nuanced opinion

**Comment by kshitij12345** [comment]
This was fixed in https://github.com/pytorch/pytorch/pull/61250

Can you try the latest nightly once?

**Comment by tesfaldet** [comment]
Nightly works 👍  I'm surprised I didn't notice that fix or the issue it referenced! Thanks :)
