### ISSUE TITLE
TestZeroRedundancyOptimizerDistributed.test_multiple_groups is failing intermittently

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#66059]
See https://github.com/pytorch/pytorch/runs/3778916355, relevant snippet:

```
ERROR: TestZeroRedundancyOptimizerDistributed.test_multiple_groups
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 423, in wrapper
    self._join_processes(fn)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 642, in _join_processes
    self._check_return_codes(elapsed_time)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 692, in _check_return_codes
    raise RuntimeError(
RuntimeError: Process 0 terminated or timed out after 100.03042507171631 seconds
```

Test did not fail on preceding or subsequent run. 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @mruberry

**Comment by mruberry** [comment]
Still happening (see duped issue)

**Comment by mrshenli** [comment]
Hey @rohan-varma, do we need to revert https://github.com/pytorch/pytorch/pull/65385? Seems all failures are on Windows.

**Comment by rohan-varma** [comment]
Taking a look now.

**Comment by rohan-varma** [comment]
@awgu Would you like to take a look at this one?

**Comment by awgu** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/73842.
