### ISSUE TITLE
torch.jit.script fails to cast explicit Optional parameter to bool

### ISSUE THREAD

**Issue by hsakbo** [pytorch/pytorch#66065]
## 🐛 Bug

I have a parameter in my model with explicit type  Optional[Tuple[int, int]] where python can seem to convert to bool without a problem. Jit module seem to fail here.

## To Reproduce

```
import torch
from torch import nn
from typing import Optional, Tuple
class test_model(nn.Module):
    def __init__(self, size: Optional[Tuple[int, int]] = None) -> None:
        super(test_model, self).__init__()
        self.size = size

    def forward(self, x):
        if self.size:
            ...
        return x

if __name__ == "__main__":
    test = torch.Tensor(1, 3, 8, 10)
    model = test_model((10, 8))
    torch.jit.script(model)  # replace to see if it actually works in plain python
    print(model(test).shape)
```

1. Run the above code
2. Comment uncomment jit.script to see the difference

```
Traceback (most recent call last):
  File "/home/sflash/Documents/php/oca/oca-server/src/models/ddrnet_dappm.py", line 156, in <module>
    torch.jit.script(model)
  File "/home/sflash/miniconda3/envs/oca-dev/lib/python3.9/site-packages/torch/jit/_script.py", line 1096, in script
    return torch.jit._recursive.create_script_module(
  File "/home/sflash/miniconda3/envs/oca-dev/lib/python3.9/site-packages/torch/jit/_recursive.py", line 412, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/sflash/miniconda3/envs/oca-dev/lib/python3.9/site-packages/torch/jit/_recursive.py", line 478, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/sflash/miniconda3/envs/oca-dev/lib/python3.9/site-packages/torch/jit/_recursive.py", line 355, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Could not cast value of type Tuple[int, int] to bool:
  File "/home/sflash/Documents/php/oca/oca-server/src/models/ddrnet_dappm.py", line 145
    def forward(self, x):
        if self.size:
           ~~~~~~~~~ <--- HERE
            ...
        return x

```

## Expected behavior

ability to cast like normal python

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip and conda
 - Build command you used (if compiling from source):
 - Python version: 3.9.*
 - CUDA/cuDNN version: not-used
 - GPU models and configuration: not-used
 - Any other relevant information: ...

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
