### ISSUE TITLE
TestZeroRedundancyOptimizerDistributed.test_multiple_groups is timing out

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#66062]
See https://github.com/pytorch/pytorch/runs/3783229580 and https://github.com/pytorch/pytorch/runs/3778916355. Relevant snippet:

```
ERROR: TestZeroRedundancyOptimizerDistributed.test_multiple_groups
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 423, in wrapper
    self._join_processes(fn)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 642, in _join_processes
    self._check_return_codes(elapsed_time)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 692, in _check_return_codes
    raise RuntimeError(
RuntimeError: Process 0 terminated or timed out after 100.22691631317139 seconds
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by mruberry** [comment]
Dupe of https://github.com/pytorch/pytorch/issues/66059
