### ISSUE TITLE
facebook.com outage affecting upload of test stats causing workflows to fail

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#66088]
With the current outage for facebook.com we're currently seeing failures on workflows when attempting to upload test stats to scribe, we can probably just ignore these until facebook.com comes back up but flagging so that people are aware of why these particular things are failing.

```
[scribe] Scribe access token provided, sending report via http...
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f61e28abc70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='graph.facebook.com', port=443): Max retries exceeded with url: /scribe_logs (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f61e28abc70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/circleci/project/tools/stats/upload_binary_size_to_scuba.py", line 158, in <module>
    report_android_sizes(file_dir)
  File "/home/circleci/project/tools/stats/upload_binary_size_to_scuba.py", line 136, in report_android_sizes
    send_message(list(gen_messages()))
  File "/home/circleci/project/tools/stats/upload_binary_size_to_scuba.py", line 80, in send_message
    res = send_to_scribe(logs)
  File "/home/circleci/project/tools/stats/scribe.py", line 45, in send_to_scribe
    return _send_to_scribe_via_http(access_token, logs)
  File "/home/circleci/project/tools/stats/scribe.py", line 59, in _send_to_scribe_via_http
    r = requests.post(
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='graph.facebook.com', port=443): Max retries exceeded with url: /scribe_logs (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f61e28abc70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

Exited with code exit status 1

```

see: https://app.circleci.com/pipelines/github/pytorch/pytorch/389397/workflows/3c329baa-c86a-4322-be5d-05106c3062d4/jobs/16327089

**Comment by malfet** [comment]
Things seems to be getting back to normal..

**Comment by seemethere** [comment]
Yup closing this now
