### ISSUE TITLE
[pytorch] nan, After Big Numbers

### ISSUE THREAD

**Issue by sherif7810** [pytorch/pytorch#6610]
Hi, I made a kernel for Titanic in Kaggle [there](https://www.kaggle.com/sherif924/first-kernel).

The output of the model's `forward` function'd have been nan, if `x` was returned before `if`. I found that I get nan, after `self.fc1(x)`.
It may be, because some numbers in the input vector are large.

I tried using `torch.DoubleTensor` for `train` and `label` then I got:
`Traceback (most recent call last):
  File "main.py", line 56, in <module>
    out = model(train)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 30, in forward
    x = self.tanh(self.fc1(x))
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/functional.py", line 837, in linear
    output = input.matmul(weight.t())
  File "/usr/local/lib64/python3.6/site-packages/torch/autograd/variable.py", line 386, in matmul
    return torch.matmul(self, other)
  File "/usr/local/lib64/python3.6/site-packages/torch/functional.py", line 169, in matmul
    return torch.mm(tensor1.unsqueeze(0), tensor2).squeeze_(0)
RuntimeError: Expected object of type Variable[torch.DoubleTensor] but found type Variable[torch.FloatTensor] for argument #1 'mat2'`

- PyTorch or Caffe2: PyTorch.
- OS: Linux (64-bit Fedora 27 with Gnome).
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): pip3.
- Python version: 3.6.5.
- I use CPU (No CUDA).

**Comment by apaszke** [comment]
That looks more like a user error than a bug and we're using GitHub issues for bug reports only. You can post your question on [our forums](https://discuss.pytorch.org).

**Comment by sherif7810** [comment]
You are right. It's a user error. I didn't notice the missing age which gave nan.
