### ISSUE TITLE
FX throws NameError: name 'Proxy' is not defined

### ISSUE THREAD

**Issue by datumbox** [pytorch/pytorch#66151]
## 🐛 Bug

I'm using the FX API to build a util that replaces the normal additions of residual shortcuts with a custom `nn.Module`. When I transform the module using FX and try to run it I receive an `"NameError: name 'Proxy' is not defined"` exception despite the `Proxy` class being clearly defined. Is this a bug or it's me that I'm doing something wrong?

## To Reproduce

```python
import operator
import torch

from torch.fx import Proxy, symbolic_trace
from torchvision.models import *


class ShortcutAdd(torch.nn.Module):
    def forward(self, x, y):
        print(x, y)
        return x + y


def replace_shortcut(m: torch.nn.Module) -> torch.nn.Module:
    gm = symbolic_trace(m)
    patterns = {operator.add, torch.add, "add"}

    input = None
    for node in gm.graph.nodes:
        if node.op == 'call_function':
            if node.target in patterns and input in node.args:
                with gm.graph.inserting_after(node):
                    fn_impl_traced = symbolic_trace(ShortcutAdd())
                    proxy_args = [Proxy(x) for x in node.args]
                    fn_impl_output_node = fn_impl_traced(*proxy_args)
                    node.replace_all_uses_with(fn_impl_output_node)
                gm.graph.erase_node(node)
                break
        elif node.op == "placeholder":
            input = node

    gm.recompile()

    return gm


m = resnet18()
block = m.layer1[0]

block2 = replace_shortcut(block)
out = block2(torch.randn((7, 64, 224, 224)))
```

Throws the following exception
```
Traceback (most recent call last):
  File "./torch/fx/graph_module.py", line 608, in wrapped_call
    return super(type(self), self).__call__(*args, **kwargs)
  File "./torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.2", line 11, in forward
    relu_1 = self.relu(Proxy(add_1))
NameError: name 'Proxy' is not defined

Call using an FX-traced Module, line 11 of the traced Module's generated forward function:
    add_1 = bn2 + x;  bn2 = x = None
    relu_1 = self.relu(Proxy(add_1))

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return relu_1

    

Traceback (most recent call last):
  File "./test.py", line 42, in <module>
    block2(torch.randn((7, 64, 224, 224)))
  File "./torch/fx/graph_module.py", line 616, in wrapped_call
    raise e.with_traceback(None)
NameError: name 'Proxy' is not defined
```

## Expected behavior

Return the result without error.

## Environment

 - PyTorch Version (e.g., 1.0): pytorch-1.11.0.dev20211005
 - OS (e.g., Linux): macOS
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): n/a
 - Python version: 3.8
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information: n/a

**Comment by datumbox** [comment]
There was a typo/bug on my code. Instead of:
```
node.replace_all_uses_with(fn_impl_output_node)
```

I had to do:
```
node.replace_all_uses_with(fn_impl_output_node.node)
```

I'll close the ticket but we might need to improve the error message.
