### ISSUE TITLE
[Caffe2] CUDNN_STATUS_BAD_PARAM Error with the LRN layer while trying to run the code using CUDA. The training works fine on CPU

### ISSUE THREAD

**Issue by pradeephike** [pytorch/pytorch#6618]
Original python traceback for operator 39 in network `fast_style_train` in exception above (most recent call last):
  File "styleCaffe.py", line 284, in <module>
  File "styleCaffe.py", line 250, in main
  File "styleCaffe.py", line 126, in styleNetModelDef
  File "styleCaffe.py", line 68, in customVGGY
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/brew.py", line 121, in scope_wrapper
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/helpers/normalization.py", line 43, in lrn
Traceback (most recent call last):
  File "styleCaffe.py", line 284, in <module>
    main()
  File "styleCaffe.py", line 260, in main
    workspace.CreateNet(train_model.net, overwrite=True)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 166, in CreateNet
    StringifyProto(net), overwrite,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 192, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at local_response_normalization_op_cudnn.cc:39] status == CUDNN_STATUS_SUCCESS. 3 vs 0. , Error at: /home/prasanna/Installations/caffe2/caffe2/operators/local_response_normalization_op_cudnn.cc:39: CUDNN_STATUS_BAD_PARAM 

I am facing the error of Bad parameters while creating the LRN Layer. I have defined the layer in the following way:

    conv1_vggx = brew.conv(model, data, 'conv1_vggx', 3, 96,kernel= 7,stride=2,weight_init=('GaussianFill',{'mean':0.0, 'std':1e-2}))
    relu1_vggx = brew.relu(model, conv1_vggx, 'relu1_vggx')
    inst1_vggx = brew.lrn(model,relu1_vggx,'inst1_vggx',size = 5)
    pool1_vggx = brew.max_pool(model, inst1_vggx, 'pool1_vggx', kernel=3, stride=2)

brew.lrn is the layer in which    
CUDNN_ENFORCE(
        cudnnSetLRNDescriptor(norm_desc_, size_, alpha_, beta_, bias_));

is failing.

I looked at the parameter they seem to be correct to me.

How to workaround this problem?

**Comment by CarlosYeverino** [comment]
I have the same issue. Any update on this?
