### ISSUE TITLE
test_import_stats is flaky

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#66184]
`test_import_stats.py` accidentally fails during call to `register_rds_schema`:
Traceback (most recent call last):
  File "test_import_stats.py", line 63, in <module>
    "time_ms": "int",
  File "/var/lib/jenkins/workspace/tools/stats/scribe.py", line 94, in register_rds_schema
    invoke_rds(event)
  File "/var/lib/jenkins/workspace/tools/stats/scribe.py", line 72, in invoke_rds
    return invoke_lambda("rds-proxy", events)
  File "/var/lib/jenkins/workspace/tools/stats/scribe.py", line 33, in invoke_lambda
    raise Exception(payload)
Exception: {"errorMessage":"2021-10-06T01:14:28.434Z ae80dd87-8803-4ab6-843b-08f1011c22a3 Task timed out after 3.00 seconds"}

For example for https://hud.pytorch.org/commit/83bac89d6477d084ac4020de56c13ecc42e0f7ac it failed for 3 jobs:
https://github.com/pytorch/pytorch/runs/3809711391#step:16:23571
https://github.com/pytorch/pytorch/runs/3809744116#step:16:3818
https://github.com/pytorch/pytorch/runs/3809744150#step:16:3822

Another fun fact: this kind of error does not register in generated test_results.xml

**Comment by malfet** [comment]
One more failure in ONNX stack: https://github.com/pytorch/pytorch/runs/3809277548
