### ISSUE TITLE
CUDA extension gets build error when no GPU/driver is present.

### ISSUE THREAD

**Issue by suffiank** [pytorch/pytorch#66333]
## 🐛 Bug

CUDA extension build is getting error in an environment where GPU/driver is not present but CUDA software stack is (e.g. during docker build). The CUDA driver should not be necessary to compile CUDA extension. And the same extension appears to build OK when against ROCm software stack, also with no GPU/driver mapped.

## To Reproduce

docker --version
Docker version 19.03.12, build 48a66213fe

Just build this Dockerfile (no special arguments needed):
```
# ONNX Runtime Training Module for PyTorch
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# CUDA development image for building sources
FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04 as builder

ARG TORCH_CUDA_VERSION=cu111
ARG TORCH_VERSION=1.9.0
ARG TORCHVISION_VERSION=0.10.0

# Install and update tools to minimize security vulnerabilities
RUN apt-get update
RUN apt-get install -y software-properties-common wget apt-utils patchelf git libprotobuf-dev protobuf-compiler cmake
RUN unattended-upgrade
RUN apt-get autoremove -y

# Python and pip
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN apt-get install -y python3-pip
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
RUN pip install --upgrade pip

# PyTorch
RUN pip install onnx ninja
RUN pip install torch==${TORCH_VERSION}+${TORCH_CUDA_VERSION} torchvision==${TORCHVISION_VERSION}+${TORCH_CUDA_VERSION} -f https://download.pytorch.org/whl/torch_stable.html

# ORT Module
RUN pip install --pre onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_nightly_cu111.html

RUN pip install torch-ort
RUN python -m torch_ort.configure

WORKDIR /workspace

# Basic testing
#   git clone https://github.com/pytorch/ort.git
#   pip install wget pandas transformers sklearn
#   python ./ort/tests/bert_for_sequence_classification.py
```

The problematic step is _RUN python -m torch_ort.configure_. It compiles a CUDA extension and generates the below stack trace due to an index out of range.

```
2021-10-07T19:24:27.5046002Z [91mTraceback (most recent call last):
2021-10-07T19:24:27.5047234Z   File "/usr/local/lib/python3.6/dist-packages/onnxruntime/training/ortmodule/torch_cpp_extensions/cuda/adam_optimizer/setup.py", line 30, in <module>
2021-10-07T19:24:27.5048340Z     cmdclass={'build_ext': cpp_extension.BuildExtension})
2021-10-07T19:24:27.5049430Z   File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
2021-10-07T19:24:27.5050290Z     return distutils.core.setup(**attrs)
2021-10-07T19:24:27.5050913Z   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
2021-10-07T19:24:27.5051485Z     dist.run_commands()
2021-10-07T19:24:27.5052034Z   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
2021-10-07T19:24:27.5052829Z     self.run_command(cmd)
2021-10-07T19:24:27.5053529Z   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
2021-10-07T19:24:27.5054065Z     cmd_obj.run()
2021-10-07T19:24:27.5054609Z   File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
2021-10-07T19:24:27.5055197Z     self.run_command(cmd_name)
2021-10-07T19:24:27.5055775Z   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
2021-10-07T19:24:27.5056362Z     self.distribution.run_command(command)
2021-10-07T19:24:27.5056932Z   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
2021-10-07T19:24:27.5057475Z     cmd_obj.run()
2021-10-07T19:24:27.5058286Z   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 79, in run
2021-10-07T19:24:27.5058903Z     _build_ext.run(self)
2021-10-07T19:24:27.5059457Z   File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
2021-10-07T19:24:27.5060028Z     self.build_extensions()
2021-10-07T19:24:27.5060850Z   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
2021-10-07T19:24:27.5061507Z     build_ext.build_extensions(self)
2021-10-07T19:24:27.5062117Z   File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
2021-10-07T19:24:27.5062717Z     self._build_extensions_serial()
2021-10-07T19:24:27.5063339Z   File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
2021-10-07T19:24:27.5063946Z     self.build_extension(ext)
2021-10-07T19:24:27.5064762Z   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 202, in build_extension
2021-10-07T19:24:27.5065437Z     _build_ext.build_extension(self, ext)
2021-10-07T19:24:27.5066127Z   File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
2021-10-07T19:24:27.5066854Z     depends=ext.depends)
2021-10-07T19:24:27.5067888Z   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 525, in unix_wrap_ninja_compile
2021-10-07T19:24:27.5068613Z     cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
2021-10-07T19:24:27.5069472Z   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 424, in unix_cuda_flags
2021-10-07T19:24:27.5070138Z     cflags + _get_cuda_arch_flags(cflags))
2021-10-07T19:24:27.5070978Z   File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1562, in _get_cuda_arch_flags
2021-10-07T19:24:27.5071748Z     arch_list[-1] += '+PTX'
2021-10-07T19:24:27.5072261Z IndexError: list index out of range
2021-10-07T19:24:27.6556003Z [0mNo CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
2021-10-07T19:24:27.6556729Z There was an error compiling "adam_optimizer" PyTorch CPP extension
2021-10-07T19:24:28.0130053Z The command '/bin/sh -c python -m torch_ort.configure' returned a non-zero code: 1
2021-10-07T19:24:28.0190658Z ##[error]Bash exited with code '1'.
```
This extension builds okay when run in an environment where CUDA device count > 0. Just launch the image cached before the failed step with flag "--gpus all". Then try "python -m torch_ort.configure" and see it works okay.

## Expected behavior

Building CUDA files should not require the GPU be available (e.g. in container without GPU mapped in). It only needs the CUDA toolchain. And the above extension appears to compile fine for the ROCm case.

## Environment

Below is the output from collect_env.py script. It may or may not be correct for it to say CUDA is not available. However the CUDA software stack is in fact available at /usr/local/cuda. We are simply building off the nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04 container from nvidia.

```
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1+cu111
[pip3] torch-ort==1.9.0
[pip3] torchvision==0.9.1+cu111
[conda] Could not collect
```

## Additional context

Same issue appears for different CUDA version or torch. It doesn't seem to happen for corresponding ROCm build.

**Comment by suffiank** [comment]
Nevermind. It looks like this is intended behavior after reading the documentation at https://github.com/pytorch/pytorch/blob/731cf494f26bec59bc5f3419854f4e2c743bd3d0/torch/utils/cpp_extension.py#L885
