### ISSUE TITLE
Unsupported prim::Constant kind: `ival`

### ISSUE THREAD

**Issue by OYCN** [pytorch/pytorch#66365]
## 🐛 Bug

Bescause my model have some OP(e.g. `inverse`) which can't be exported to onnx, and the inputs of these OP come from some constant. In order to avoid these unsupported operations, I want to fold the constant in torchscript before export to onnx, but I got the error `RuntimeError: Unsupported prim::Constant kind: 'ival'. Send a bug report.` when using `torch.onnx.export`

## To Reproduce

After split my model, there is the sample which will rise the error:

```
import torch
import torch.nn as nn
import torch.nn.functional as F

class Test(nn.Module):
    def __init__(self):
        super().__init__()
        self.T = nn.Parameter(torch.eye(512))
        self.conv = nn.Conv2d(3, 32, 3, 2, 1)
        self.bn = nn.BatchNorm2d(32)
        self.relu = nn.ReLU(True)

    def forward(self, x):
        x = torch.inverse(self.T).matmul(x)
        out = self.conv(x)
        out = self.bn(out)
        out = self.relu(out)
        return out

if __name__ == '__main__':
    print(torch.__version__)

    model = Test().eval()

    x = torch.randn((1, 3, 512, 512))
    out = model(x)

    # TorchScript
    model_jit = torch.jit.trace(model, (x))
    model_jit.save("model_jit.pt")
    print(model_jit.code)

    # Optimize
    from torch.utils.mobile_optimizer import optimize_for_mobile
    model_jit_opt = optimize_for_mobile(model_jit)
    model_jit_opt.save("model_jit_opt.pth")
    print(model_jit_opt.code)

    model_jit_opt = model_jit_opt.eval()

    # export to Onnx
    torch.onnx.export(model_jit_opt,
        (x),
        'output.onnx',
        opset_version=11,
        verbose=True,
        example_outputs = out
    )
```

In my env, the output is below.

```
1.11.0.dev20211008
def forward(self,
    x: Tensor) -> Tensor:
  relu = self.relu
  bn = self.bn
  conv = self.conv
  T = self.T
  input = torch.matmul(torch.inverse(T), x)
  _0 = (bn).forward((conv).forward(input, ), )
  return (relu).forward(_0, )

def forward(self,
    x: Tensor) -> Tensor:
  input = torch.matmul(CONSTANTS.c0, x)
  _0 = ops.prepacked.conv2d_clamp_run(input, CONSTANTS.c1)
  return _0

/home/x/anaconda3/envs/py37torchPre/lib/python3.7/site-packages/torch/onnx/utils.py:100: UserWarning: `example_outputs' is deprecated and ignored. Will be removed in next PyTorch release.
  warnings.warn("`example_outputs' is deprecated and ignored. Will be removed in "
/home/x/anaconda3/envs/py37torchPre/lib/python3.7/site-packages/torch/onnx/utils.py:356: UserWarning: Model has no forward function
  warnings.warn("Model has no forward function")
Traceback (most recent call last):
  File "deploy_pipline.py", line 47, in <module>
    example_outputs = out
  File "/home/x/anaconda3/envs/py37torchPre/lib/python3.7/site-packages/torch/onnx/__init__.py", line 321, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/x/anaconda3/envs/py37torchPre/lib/python3.7/site-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "/home/x/anaconda3/envs/py37torchPre/lib/python3.7/site-packages/torch/onnx/utils.py", line 724, in _export
    dynamic_axes=dynamic_axes)
  File "/home/x/anaconda3/envs/py37torchPre/lib/python3.7/site-packages/torch/onnx/utils.py", line 501, in _model_to_graph
    module=module)
  File "/home/x/anaconda3/envs/py37torchPre/lib/python3.7/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/x/anaconda3/envs/py37torchPre/lib/python3.7/site-packages/torch/onnx/__init__.py", line 374, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/x/anaconda3/envs/py37torchPre/lib/python3.7/site-packages/torch/onnx/utils.py", line 1043, in _run_symbolic_function
    n.kindOf("value")))
RuntimeError: Unsupported prim::Constant kind: `ival`. Send a bug report.
```

## Expected behavior

I wannt to export the onnx which constant has been folded.

## Environment

```
PyTorch version: 1.11.0.dev20211008
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 7.0.1 (tags/RELEASE_701/final)
CMake version: version 3.21.1
Libc version: glibc-2.17

Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-87-generic-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: 10.0.326
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.11.0.dev20211008
[pip3] torchaudio==0.11.0.dev20211008
[pip3] torchtoolbox==0.1.8.3
[pip3] torchvision==0.12.0.dev20211008
[conda] blas                      1.0                         mkl    defaults
[conda] cpuonly                   2.0                           0    pytorch-nightly
[conda] mkl                       2020.2                      256    defaults
[conda] mkl-service               2.3.0            py37he8ac12f_0    defaults
[conda] mkl_fft                   1.3.0            py37h54f3939_0    defaults
[conda] mkl_random                1.1.1            py37h0573a6f_0    defaults
[conda] numpy                     1.19.2           py37h54aff64_0    defaults
[conda] numpy-base                1.19.2           py37hfa32c7d_0    defaults
[conda] pytorch                   1.11.0.dev20211008     py3.7_cpu_0    pytorch-nightly
[conda] pytorch-mutex             1.0                         cpu    pytorch-nightly
[conda] torchaudio                0.11.0.dev20211008        py37_cpu  [cpuonly]  pytorch-nightly
[conda] torchtoolbox              0.1.8.3                   <pip>
[conda] torchvision               0.12.0.dev20211008        py37_cpu  [cpuonly]  pytorch-nightly
```

**Comment by olegggatttor** [comment]
Hi, I met same issue: I've created class from nn.Module where I want to store params in dicts and preprocess data. I want to precompute some statistics and then convert it to TorchScript using torch.hit.script and then export as onyx model (to load it later). That's how I am trying to do it:

Model:

```from typing import Dict, List
import torch
import torch.nn as nn
class FeatureNormalizer(nn.Module):
    def __init__(self, feature_names, is_map_negative : Dict[str, bool], types : Dict[str, str], params : Dict[str, float]):
        super(FeatureNormalizer, self).__init__()
        self.feature_names: List[str] = feature_names
        self.is_map_negative : Dict[str, bool] = is_map_negative
        self.types : Dict[str, str] = types
        self.params : Dict[str, float] = params
        self.means : Dict[str, float] = {}
        self.stds : Dict[str, float] = {}
        self.is_train: bool = False
    def forward(self, x):
        columns = []
        for i, feature_name in enumerate(self.feature_names):
            tmp = x[:, i].clone()
            if self.is_map_negative[feature_name]:
                tmp = torch.clamp(tmp, min=0.0)
            if self.types[feature_name] == 'log1p':
                tmp = torch.log1p(tmp)
            elif self.types[feature_name] == 'boxcox1p':
                lamb = self.params[feature_name]
                if lamb == 0.0:
                    tmp = torch.log1p(tmp)
                else:
                    tmp = (torch.pow((1.0 + tmp), lamb) - 1.0) / lamb
            
            if self.is_train:
                self.means[feature_name] = tmp.mean().item()
                self.stds[feature_name] = tmp.std().item()

            tmp = (tmp - self.means[feature_name]) / self.stds[feature_name]
            columns.append(tmp)
        res = torch.stack(columns, dim=1)
        return res

        
# Exporting:
inp = torch.zeros(1, 100).float().cpu()
out = torch.ones(1, 100).float().cpu()
scripted_module = torch.jit.script(norm_model.cpu())
torch.onnx.export(scripted_module, [inp], 
                  'normalizer.onnx', 
                  verbose=True, example_outputs=out,
                  opset_version=11)
```
                  
But I get such error instead: **RuntimeError: Unsupported prim::Constant kind: `ival`. Send a bug report.**

**Comment by carter54** [comment]
I'm facing the same issue...
RuntimeError: Unsupported prim::Constant kind: `ival`. Send a bug report.

**Comment by olegggatttor** [comment]
> I'm facing the same issue...
> 
> RuntimeError: Unsupported prim::Constant kind: `ival`. Send a bug report.

I fixed it removing dicts (I switched it ti tensors) and if statements (I switched it to but masks) in my code provided above. If you are interested I can provide you my solution.

**Comment by mollon650** [comment]
> > I'm facing the same issue...
> > RuntimeError: Unsupported prim::Constant kind: `ival`. Send a bug report.
> 
> I fixed it removing dicts (I switched it ti tensors) and if statements (I switched it to but masks) in my code provided above. If you are interested I can provide you my solution.

can u show your solution?

**Comment by AllenTiTaiWang** [comment]
duplicate to #83801
