### ISSUE TITLE
test_Conv2d_naive_groups_cuda_float16 (__main__.TestNNDeviceTypeCUDA) is flaky on ROCm

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#66378]
See https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/3865//console

Relevant snippet:

```
18:11:11 ======================================================================
18:11:11 FAIL [3.839s]: test_Conv2d_naive_groups_cuda_float16 (__main__.TestNNDeviceTypeCUDA)
18:11:11 ----------------------------------------------------------------------
18:11:11 Traceback (most recent call last):
18:11:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1398, in wrapper
18:11:11     method(*args, **kwargs)
18:11:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1398, in wrapper
18:11:11     method(*args, **kwargs)
18:11:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
18:11:11     result = test(self, **param_kwargs)
18:11:11   File "test_nn.py", line 16292, in test_Conv2d_naive_groups
18:11:11     self.assertEqual(output, torch.cat([output1, output2], 1))
18:11:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1877, in assertEqual
18:11:11     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
18:11:11 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=0.001 and atol=1e-05, found 34 element(s) (out of 128) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.0009765625 (-0.5205078125 vs. -0.51953125), which occurred at index (0, 3, 0, 2).
18:11:11 
18:11:11 ----------------------------------------------------------------------
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @mruberry

**Comment by mruberry** [comment]
Another instance: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/3865//console

**Comment by mrshenli** [comment]
another instance: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/9120//console

**Comment by jithunnair-amd** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/77438
