### ISSUE TITLE
TestBenchmarkUtils.test_timer_tiny_fast_snippet raises divide by 0 error

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#66487]
Encountered this failure on trunk CI for the slow tests in linux-xenial-cuda10.2-py3.6-gcc7: https://hud.pytorch.org/commit/71e17d9827bb20b2452697a77e8db9b4b0575348.

Seems like a lack of error handling in benchmark
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 981, in wrapper
    fn(*args, **kwargs)
  File "benchmark_utils/test_benchmark_utils.py", line 177, in test_timer_tiny_fast_snippet
    median = timer.blocked_autorange().median
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/benchmark/utils/timer.py", line 389, in blocked_autorange
    number = self._estimate_block_size(min_run_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/benchmark/utils/timer.py", line 307, in _estimate_block_size
    relative_overhead = overhead / time_taken
ZeroDivisionError: float division by zero
```

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
Closing in favor of https://github.com/pytorch/pytorch/issues/66503
