### ISSUE TITLE
DISABLED test_timer_tiny_fast_snippet (__main__.TestBenchmarkUtils)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#66503]
See https://github.com/pytorch/pytorch/runs/3872033982, relevant snippet:

```
  test_timer_tiny_fast_snippet (__main__.TestBenchmarkUtils) ... ERROR (21.201s)

======================================================================
ERROR [21.201s]: test_timer_tiny_fast_snippet (__main__.TestBenchmarkUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 981, in wrapper
    fn(*args, **kwargs)
  File "benchmark_utils/test_benchmark_utils.py", line 177, in test_timer_tiny_fast_snippet
    median = timer.blocked_autorange().median
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/benchmark/utils/timer.py", line 389, in blocked_autorange
    number = self._estimate_block_size(min_run_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/benchmark/utils/timer.py", line 307, in _estimate_block_size
    relative_overhead = overhead / time_taken
ZeroDivisionError: float division by zero

----------------------------------------------------------------------
Ran 9 tests in 409.563s

FAILED (errors=1, skipped=5)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry

**Comment by seemethere** [comment]
Should we go ahead and just disable this test for now?
