### ISSUE TITLE
Pytorch 1.11nightly suddenly not compiling my cuda extensions?

### ISSUE THREAD

**Issue by EMCP** [pytorch/pytorch#66759]
## 🐛 Bug

I've been utilizing a project which relies on compiling some Cpp extensions in order to run .. things were fine with the nightly build back in September but when I went to reinstall my libraries I am hitting an error I'd not seen before.. 

## To Reproduce

1. `pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html`
2. `pip install -e .` on my cpp's `setup.py` 
3. usually by now i can start running my `training.py` , but instead getting met with error that I will attached below

## setup.py for my modules

```
#!/usr/bin/env python
import glob
import os

from setuptools import find_packages
from setuptools import setup

import torch
from torch.utils.cpp_extension import CUDA_HOME
from torch.utils.cpp_extension import CppExtension
from torch.utils.cpp_extension import CUDAExtension


def get_extensions():

    this_dir = os.path.dirname(os.path.abspath(__file__))
    extensions_dir = os.path.join(this_dir, "model", "csrc")

    main_file = glob.glob(os.path.join(extensions_dir, "*.cpp"))
    source_cpu = glob.glob(os.path.join(extensions_dir, "cpu", "*.cpp"))
    source_cuda = glob.glob(os.path.join(extensions_dir, "cuda", "*.cu"))

    sources = main_file + source_cpu
    extension = CppExtension

    extra_compile_args = {"cxx": []}
    define_macros = []

    if torch.cuda.is_available() and CUDA_HOME is not None:
        extension = CUDAExtension
        sources += source_cuda
        define_macros += [("WITH_CUDA", None)]
        extra_compile_args["nvcc"] = [
            "-DCUDA_HAS_FP16=1",
            "-D__CUDA_NO_HALF_OPERATORS__",
            "-D__CUDA_NO_HALF_CONVERSIONS__",
            "-D__CUDA_NO_HALF2_OPERATORS__",
        ]

    sources = [os.path.join(extensions_dir, s) for s in sources]

    include_dirs = [extensions_dir]

    ext_modules = [
        extension(
            "model._C",
            sources,
            include_dirs=include_dirs,
            define_macros=define_macros,
            extra_compile_args=extra_compile_args,
        )
    ]

    return ext_modules

setup(
    name="faster_rcnn",
    version="0.3",
    description="object detection in pytorch",
    packages=find_packages(exclude=("configs", "tests",)),
    install_requires=["torch", "torchvision", "ninja"],
    ext_modules=get_extensions(),
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
)
```

This is what comes out from `pip install -e .` OR from `pip install -r requirements.txt` if I am trying via git

```
(venv_nightly) ubuntu@juju-9c16c5-2:~/Dev/git/faster-rcnn-private-pypi-libs$ pip install -e . --no-cache
Obtaining file:///home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages (from faster-rcnn==0.3) (1.11.0.dev20211016+cu113)
Requirement already satisfied: torchvision in /home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages (from faster-rcnn==0.3) (0.12.0.dev20211016+cu113)
Requirement already satisfied: ninja in /home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages (from faster-rcnn==0.3) (1.10.2.2)
Requirement already satisfied: typing-extensions in /home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages (from torch->faster-rcnn==0.3) (3.10.0.2)
Requirement already satisfied: numpy in /home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages (from torchvision->faster-rcnn==0.3) (1.21.2)
Requirement already satisfied: pillow!=8.3.0,>=5.3.0 in /home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages (from torchvision->faster-rcnn==0.3) (8.4.0)
Installing collected packages: faster-rcnn
  Running setup.py develop for faster-rcnn
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/Dev/git/venv_nightly/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/setup.py'"'"'; __file__='"'"'/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/
    Complete output (89 lines):
    running develop
    running egg_info
    writing faster_rcnn.egg-info/PKG-INFO
    writing dependency_links to faster_rcnn.egg-info/dependency_links.txt
    writing requirements to faster_rcnn.egg-info/requires.txt
    writing top-level names to faster_rcnn.egg-info/top_level.txt
    reading manifest file 'faster_rcnn.egg-info/SOURCES.txt'
    writing manifest file 'faster_rcnn.egg-info/SOURCES.txt'
    running build_ext
    building 'model._C' extension
    Emitting ninja build file /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/build/temp.linux-x86_64-3.8/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/3] /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/TH -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/Dev/git/venv_nightly/include -I/usr/include/python3.8 -c -c /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/nms.cu -o /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/build/temp.linux-x86_64-3.8/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/nms.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
    FAILED: /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/build/temp.linux-x86_64-3.8/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/nms.o
    /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/TH -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/Dev/git/venv_nightly/include -I/usr/include/python3.8 -c -c /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/nms.cu -o /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/build/temp.linux-x86_64-3.8/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/nms.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
    /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/nms.cu:6:10: fatal error: THC/THCDeviceUtils.cuh: No such file or directory
        6 | #include <THC/THCDeviceUtils.cuh>
          |          ^~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [2/3] /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/TH -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/Dev/git/venv_nightly/include -I/usr/include/python3.8 -c -c /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIAlign_cuda.cu -o /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/build/temp.linux-x86_64-3.8/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIAlign_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
    FAILED: /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/build/temp.linux-x86_64-3.8/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIAlign_cuda.o
    /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/TH -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/Dev/git/venv_nightly/include -I/usr/include/python3.8 -c -c /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIAlign_cuda.cu -o /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/build/temp.linux-x86_64-3.8/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIAlign_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
    /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIAlign_cuda.cu:7:10: fatal error: THC/THCDeviceUtils.cuh: No such file or directory
        7 | #include <THC/THCDeviceUtils.cuh>
          |          ^~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [3/3] /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/TH -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/Dev/git/venv_nightly/include -I/usr/include/python3.8 -c -c /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIPool_cuda.cu -o /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/build/temp.linux-x86_64-3.8/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIPool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
    FAILED: /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/build/temp.linux-x86_64-3.8/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIPool_cuda.o
    /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/TH -I/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/Dev/git/venv_nightly/include -I/usr/include/python3.8 -c -c /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIPool_cuda.cu -o /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/build/temp.linux-x86_64-3.8/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIPool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
    /home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/model/csrc/cuda/ROIPool_cuda.cu:7:10: fatal error: THC/THCDeviceUtils.cuh: No such file or directory
        7 | #include <THC/THCDeviceUtils.cuh>
          |          ^~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1718, in _run_ninja_build
        subprocess.run(
      File "/usr/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/Dev/git/faster-rcnn-private-pypi-libs/setup.py", line 56, in <module>
        setup(
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 736, in build_extensions
        build_ext.build_extensions(self)
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 557, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1400, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/ubuntu/Dev/git/venv_nightly/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1734, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ubuntu/Dev/git/venv_nightly/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/ubuntu/Dev/git/pypi-libs/setup.py'"'"'; __file__='"'"'/home/ubuntu/Dev/git/pypi-libs/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

```

## Expected behavior

I am on an RTX3090, so I have to use the lightlys in order to run my training.. but this nightly is the first time I cannot get it to work

## Environment

```
(venv_nightly) ubuntu@juju-9c16c5-2:~/Dev/git/JRGEMCP_AILAB/faster-rcnn-private-pypi-libs$ python3 collect_env.py 
Collecting environment information...
PyTorch version: 1.11.0.dev20211016+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-37-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1060 6GB
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 465.19.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.11.0.dev20211016+cu113
[pip3] torchaudio==0.11.0.dev20211016+cu113
[pip3] torchvision==0.12.0.dev20211016+cu113
[conda] Could not collect

```

**Comment by EMCP** [comment]
just wanted to express gratitude @ngimel , I successfully bumped the project now to 1.13.x pytorch .. having it train now on Cuda 11.7 based machine.  thank you again for all your hard work
