### ISSUE TITLE
test_nccl_timeout (__main__.NcclErrorHandlingTest) is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#66882]
https://github.com/pytorch/pytorch/runs/3932764533

```
======================================================================
ERROR [17.751s]: test_nccl_timeout (__main__.NcclErrorHandlingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 424, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 643, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 688, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 0 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 542, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 426, in wrapper
    fn()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 176, in wrapper
    ret = func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2904, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/distributed/test_c10d_nccl.py", line 2397, in test_nccl_timeout
    process_group.allreduce(torch.rand(10).cuda(self.rank)).wait(timeout=timedelta(seconds=1))
  File "/opt/conda/lib/python3.6/unittest/case.py", line 203, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/opt/conda/lib/python3.6/unittest/case.py", line 135, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: RuntimeError not raised
```

```
2021-10-18T23:19:56.6473270Z   test_nccl_timeout (__main__.NcclErrorHandlingTest) ... Caught exception: 
2021-10-18T23:19:56.6474520Z Traceback (most recent call last):
2021-10-18T23:19:56.6476216Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 542, in run_test
2021-10-18T23:19:56.6477098Z     getattr(self, test_name)()
2021-10-18T23:19:56.6478173Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 426, in wrapper
2021-10-18T23:19:56.6478950Z     fn()
2021-10-18T23:19:56.6479949Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 176, in wrapper
2021-10-18T23:19:56.6480779Z     ret = func(*args, **kwargs)
2021-10-18T23:19:56.6481770Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2904, in wrapper
2021-10-18T23:19:56.6482606Z     return func(*args, **kwargs)
2021-10-18T23:19:56.6483636Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 112, in wrapper
2021-10-18T23:19:56.6484990Z     return func(*args, **kwargs)
2021-10-18T23:19:56.6485796Z   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_nccl.py", line 2397, in test_nccl_timeout
2021-10-18T23:19:56.6486818Z     process_group.allreduce(torch.rand(10).cuda(self.rank)).wait(timeout=timedelta(seconds=1))
2021-10-18T23:19:56.6487741Z   File "/opt/conda/lib/python3.6/unittest/case.py", line 203, in __exit__
2021-10-18T23:19:56.6489110Z     self._raiseFailure("{} not raised".format(exc_name))
2021-10-18T23:19:56.6489914Z   File "/opt/conda/lib/python3.6/unittest/case.py", line 135, in _raiseFailure
2021-10-18T23:19:56.6490760Z     raise self.test_case.failureException(msg)
2021-10-18T23:19:56.6491498Z AssertionError: RuntimeError not raised
2021-10-18T23:19:56.6492152Z  exiting process 0 with exit code: 10
2021-10-18T23:19:58.8717381Z Process 0 terminated with exit code 10, terminating remaining processes.
2021-10-18T23:19:58.8729159Z ERROR (17.751s)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
I modified this one recently, will look into it

**Comment by mrshenli** [comment]
another instance: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/1130//console
