### ISSUE TITLE
DISABLED test_ddp_comparison (__main__.TensorPipeDdpComparisonTest)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#66951]
Found flaky on CI:
https://github.com/pytorch/pytorch/runs/3954816134?check_suite_focus=true

```
======================================================================
ERROR [105.069s]: test_ddp_comparison (__main__.TensorPipeDdpComparisonTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 424, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 643, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 695, in _check_return_codes
    i, elapsed_time
RuntimeError: Process 0 terminated or timed out after 105.05612325668335 seconds
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by H-Huang** [comment]
Still seeing failure on 11/1
https://github.com/pytorch/pytorch/runs/4059791464?check_suite_focus=true
```
======================================================================
ERROR [105.062s]: test_ddp_comparison (__main__.TensorPipeDdpComparisonTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 457, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 676, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 728, in _check_return_codes
    i, elapsed_time
RuntimeError: Process 0 terminated or timed out after 105.04890513420105 seconds

----------------------------------------------------------------------
```

**Comment by rohan-varma** [comment]
Closing to see if https://github.com/pytorch/pytorch/pull/68821 helps, or at least provides a better repro command.
