### ISSUE TITLE
DISABLED test_fs_sharing (__main__.TestMultiprocessing)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#67002]
Flaky failures in the last week: https://fburl.com/scuba/opensource_ci_jobs/inmj698k. They only appear to be on windows

Platforms: rocm

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @VitalyFedyunin

**Comment by ZainRizvi** [comment]
It's still flaking. cc @huydhn 
https://github.com/pytorch/pytorch/actions/runs/3795179842/jobs/6454171292

**Comment by ZainRizvi** [comment]
for some reason I thought the bot also checked to see how recently the test had last failed in the wild...guess not, but it might be a good feature to add

**Comment by huydhn** [comment]
Although the log classifier marks the failure as related to this test, it looks like more than one of them fails, i.e. https://ossci-raw-job-status.s3.amazonaws.com/log/10337314591

```
2022-12-28T17:18:33.8488970Z ======================================================================
2022-12-28T17:18:33.8489407Z FAIL [0.620s]: test_fs (__main__.TestMultiprocessing)
2022-12-28T17:18:33.8490040Z ----------------------------------------------------------------------
2022-12-28T17:18:33.8490520Z Traceback (most recent call last):
2022-12-28T17:18:33.8490975Z   File "test_multiprocessing.py", line 370, in test_fs
2022-12-28T17:18:33.8491380Z     queue_put()
2022-12-28T17:18:33.8491790Z   File "test_multiprocessing.py", line 360, in queue_put
2022-12-28T17:18:33.8492242Z     x = torch.DoubleStorage(4)
2022-12-28T17:18:33.8492737Z   File "test_multiprocessing.py", line 361, in <graph break in queue_put>
2022-12-28T17:18:33.8493166Z     q = mp.Queue()
2022-12-28T17:18:33.8493621Z   File "test_multiprocessing.py", line 362, in <graph break in queue_put>
2022-12-28T17:18:33.8494122Z     self.assertFalse(lc.has_shm_files())
2022-12-28T17:18:33.8494680Z   File "test_multiprocessing.py", line 362, in <graph break in queue_put>
2022-12-28T17:18:33.8495188Z     self.assertFalse(lc.has_shm_files())
2022-12-28T17:18:33.8495613Z AssertionError: True is not false
2022-12-28T17:18:33.8495863Z 
2022-12-28T17:18:33.8496026Z ======================================================================
2022-12-28T17:18:33.8496447Z FAIL [3.997s]: test_fs_pool (__main__.TestMultiprocessing)
2022-12-28T17:18:33.8497092Z ----------------------------------------------------------------------
2022-12-28T17:18:33.8497686Z Traceback (most recent call last):
2022-12-28T17:18:33.8498013Z   File "test_multiprocessing.py", line 355, in test_fs_pool
2022-12-28T17:18:33.8498339Z     self._test_pool(repeat=TEST_REPEATS)
2022-12-28T17:18:33.8498715Z   File "test_multiprocessing.py", line 327, in _test_pool
2022-12-28T17:18:33.8499007Z     do_test()
2022-12-28T17:18:33.8499321Z   File "test_multiprocessing.py", line 206, in __exit__
2022-12-28T17:18:33.8499702Z     self.test_case.assertFalse(self.has_shm_files())
2022-12-28T17:18:33.8500049Z AssertionError: True is not false
2022-12-28T17:18:33.8500245Z 
2022-12-28T17:18:33.8500390Z ======================================================================
2022-12-28T17:18:33.8500780Z FAIL [0.664s]: test_fs_preserve_sharing (__main__.TestMultiprocessing)
2022-12-28T17:18:33.8501344Z ----------------------------------------------------------------------
2022-12-28T17:18:33.8501709Z Traceback (most recent call last):
2022-12-28T17:18:33.8502093Z   File "test_multiprocessing.py", line 351, in test_fs_preserve_sharing
2022-12-28T17:18:33.8502517Z     self._test_preserve_sharing(repeat=TEST_REPEATS)
2022-12-28T17:18:33.8502926Z   File "test_multiprocessing.py", line 306, in _test_preserve_sharing
2022-12-28T17:18:33.8503248Z     do_test()
2022-12-28T17:18:33.8503569Z   File "test_multiprocessing.py", line 206, in __exit__
2022-12-28T17:18:33.8503947Z     self.test_case.assertFalse(self.has_shm_files())
2022-12-28T17:18:33.8504292Z AssertionError: True is not false
2022-12-28T17:18:33.8504487Z 
2022-12-28T17:18:33.8504630Z ======================================================================
2022-12-28T17:18:33.8505004Z FAIL [1.863s]: test_fs_sharing (__main__.TestMultiprocessing)
2022-12-28T17:18:33.8505540Z ----------------------------------------------------------------------
2022-12-28T17:18:33.8505925Z Traceback (most recent call last):
2022-12-28T17:18:33.8506277Z   File "test_multiprocessing.py", line 347, in test_fs_sharing
2022-12-28T17:18:33.8506649Z     self._test_sharing(repeat=TEST_REPEATS)
2022-12-28T17:18:33.8507015Z   File "test_multiprocessing.py", line 289, in _test_sharing
2022-12-28T17:18:33.8507338Z     test_receive()
2022-12-28T17:18:33.8507643Z   File "test_multiprocessing.py", line 206, in __exit__
2022-12-28T17:18:33.8508021Z     self.test_case.assertFalse(self.has_shm_files())
2022-12-28T17:18:33.8508357Z AssertionError: True is not false
2022-12-28T17:18:33.8508545Z 
2022-12-28T17:18:33.8508842Z ----------------------------------------------------------------------
2022-12-28T17:18:33.8509213Z Ran 49 tests in 38.459s
2022-12-28T17:18:33.8509525Z 
2022-12-28T17:18:33.8509707Z FAILED (failures=4, skipped=18, expected failures=12)
```

The failed check https://github.com/pytorch/pytorch/blob/master/test/test_multiprocessing.py#L206 hasn't been changed for a while, so this probably a case where a bunch of tests are disabled and forgot

**Comment by ZainRizvi** [comment]
Could be. Also, interesting that today this is only failing on dynamo

**Comment by huydhn** [comment]
This's only failing under dynamo with`PYTORCH_TEST_WITH_DYNAMO=1`, and it doesn't look flaky AFAICT

Platforms: dynamo

**Comment by ZainRizvi** [comment]
The bot reopened this issue before @huydhn's 2 week check went in...though even with that, we're at about the two week mark for this check and it's still failing regularly
https://github.com/pytorch/test-infra/pull/1346

@peterjc123 @mszhanyi @skyline75489 @nbcsm @VitalyFedyunin, who might be the right person to take a look at root causing this error?  Multiple repros can be found here: https://hud.pytorch.org/failure/test_fs_sharing%2CTestMultiprocessing

**Comment by huydhn** [comment]
Looking at the list https://hud.pytorch.org/failure/test_fs_sharing%2CTestMultiprocessing, I realize that the test has been disabled everywhere except ROCm.  I'll disable it there too

@clee2000 is ROCm not added automatically because it's a periodic job?

**Comment by huydhn** [comment]
Platforms: rocm
