### ISSUE TITLE
[ppc64le pytorch] random failures in test_det_logdet_slogdet (test_torch.TestTorch)

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#6704]
- PyTorch or Caffe2:  PyTorch
- OS: RedHat 7.4
- PyTorch version:  
- How you installed PyTorch (conda, pip, source):
- Python version:  master branch as of 4/17/2018
- CUDA/cuDNN version:  7
- GPU models and configuration:   Nvidia P100
- GCC version (if compiling from source):  4.8.5
- CMake version:  3+
- Build command you used (if compiling from source):   python setup.py install
- Versions of any other relevant libraries:  

The following random failures has been happening for some time.  We do a nightly build and most of the time the test passes.  But in this case  both of the nightly builds using python 2 and 3 failed.  And it had different failures.   If I re-build and test several times in succession,  it may fail  1 out of  10 times.

1st failure type

FAIL: test_det_logdet_slogdet (test_torch.TestTorch)

Traceback (most recent call last):
  File "common.py", line 66, in wrapper
    fn(*args, **kwargs)
  File "test_torch.py", line 3577, in test_det_logdet_slogdet
    self._test_det_logdet_slogdet(self, lambda x: x)
  File "test_torch.py", line 3573, in _test_det_logdet_slogdet
    test(u.mm(s.diag()).mm(v))
  File "test_torch.py", line 3512, in test
    test_single_det(M_clone, target, 'two columns are same')
  File "test_torch.py", line 3466, in test_single_det
    self.assertEqual(logabsdet.exp(), det.abs(), 1e-7, '{} (slogdet logabsdet negative case)'.format(desc))
  File "common.py", line 243, in assertEqual
    assertTensorsEqual(x, y)
  File "common.py", line 235, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: two columns are same (slogdet logabsdet negative case)

2nd Failure

FAIL: test_det_logdet_slogdet (test_torch.TestTorch)

Traceback (most recent call last):
  File "/home/jenkins/pytorch/test/common.py", line 66, in wrapper
    fn(*args, **kwargs)
  File "/home/jenkins/pytorch/test/test_torch.py", line 3577, in test_det_logdet_slogdet
    self._test_det_logdet_slogdet(self, lambda x: x)
  File "/home/jenkins/pytorch/test/test_torch.py", line 3573, in _test_det_logdet_slogdet
    test(u.mm(s.diag()).mm(v))
  File "/home/jenkins/pytorch/test/test_torch.py", line 3521, in test
    test_single_det(M_clone, target, 'exchanging rows')
  File "/home/jenkins/pytorch/test/test_torch.py", line 3473, in test_single_det
    self.assertTrue(sdet.item() == 1, '{} (slogdet sign  positive case)'.format(desc))
AssertionError: False is not true : exchanging rows (slogdet sign  positive case)

cc @vishwakftw @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @ezyang @gchanan @zou3519 @bdhirsh

**Comment by ezyang** [comment]
@avmgithub Do you know if this is still affecting you?

**Comment by avmgithub** [comment]
@ezyang I'll close this for now. We'll re-open or create a new issue if necessary.  thanks.
