### ISSUE TITLE
test_local_optimizer_parity (__main__.TestZeroRedundancyOptimizerDistributed) is flaky on rocm

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#67159]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/1547//console

```
01:04:01 ======================================================================
01:04:01 ERROR [17.766s]: test_local_optimizer_parity (__main__.TestZeroRedundancyOptimizerDistributed)
01:04:01 When combined with DDP, check that ZeroRedundancyOptimizer(optimizer) and the same monolithic optimizer
01:04:01 ----------------------------------------------------------------------
01:04:01 Traceback (most recent call last):
01:04:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 424, in wrapper
01:04:01     self._join_processes(fn)
01:04:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 643, in _join_processes
01:04:01     self._check_return_codes(elapsed_time)
01:04:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 688, in _check_return_codes
01:04:01     raise RuntimeError(error)
01:04:01 RuntimeError: Process 2 exited with error code 10 and exception:
01:04:01 Traceback (most recent call last):
01:04:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 542, in run_test
01:04:01     getattr(self, test_name)()
01:04:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 426, in wrapper
01:04:01     fn()
01:04:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 77, in wrapper
01:04:01     return func(*args, **kwargs)
01:04:01   File "/var/lib/jenkins/workspace/test/distributed/optim/test_zero_redundancy_optimizer.py", line 688, in test_local_optimizer_parity
01:04:01     check_optimizer_equivalence(opt)
01:04:01   File "/var/lib/jenkins/workspace/test/distributed/optim/test_zero_redundancy_optimizer.py", line 685, in check_optimizer_equivalence
01:04:01     check_step()
01:04:01   File "/var/lib/jenkins/workspace/test/distributed/optim/test_zero_redundancy_optimizer.py", line 651, in check_step
01:04:01     ), "Losses differ in between Pytorch optim and ZeroRedundancyOptimizer"
01:04:01 AssertionError: Losses differ in between Pytorch optim and ZeroRedundancyOptimizer
01:04:01 
01:04:01 Process 3 exited with error code 10 and exception:
01:04:01 Traceback (most recent call last):
01:04:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 542, in run_test
01:04:01     getattr(self, test_name)()
01:04:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 426, in wrapper
01:04:01     fn()
01:04:01   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 77, in wrapper
01:04:01     return func(*args, **kwargs)
01:04:01   File "/var/lib/jenkins/workspace/test/distributed/optim/test_zero_redundancy_optimizer.py", line 688, in test_local_optimizer_parity
01:04:01     check_optimizer_equivalence(opt)
01:04:01   File "/var/lib/jenkins/workspace/test/distributed/optim/test_zero_redundancy_optimizer.py", line 685, in check_optimizer_equivalence
01:04:01     check_step()
01:04:01   File "/var/lib/jenkins/workspace/test/distributed/optim/test_zero_redundancy_optimizer.py", line 651, in check_step
01:04:01     ), "Losses differ in between Pytorch optim and ZeroRedundancyOptimizer"
01:04:01 AssertionError: Losses differ in between Pytorch optim and ZeroRedundancyOptimizer
01:04:01 
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by rohan-varma** [comment]
Removing oncall: distributed label as it appears to be ROCM specific. Please feel free to loop in distributed if it turns out to be a wider issue or debugging help is needed.
