### ISSUE TITLE
CUDA gradcheck tests can occasionally leak memory in HUD CI

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#67450]
TestGradientsCUDA.test_fn_grad_fft_hfft_cuda_complex128 leaked memory on a commit but then passed on the next: 
https://hud.pytorch.org/commit/pytorch/pytorch/3a1aa31a2f21f584fb82c850d2c23d6f6c47b33d
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1422, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1422, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1187, in __exit__
    self.name, after - before, i))
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1983, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! 0 != 7168
__main__.TestGradientsCUDA.test_fn_grad_fft_hfft_cuda_complex128 leaked 7168 bytes CUDA memory on device 0
```

### Versions

Happened on the linux-xenial-cuda11.3-py3.6-gcc7 config.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel @mruberry

**Comment by mruberry** [comment]
Updated title. Also hit with test test_inplace_grad_log10_cuda_complex128. See https://github.com/pytorch/pytorch/runs/4056970067?check_suite_focus=true. Upgrading priority, too.

**Comment by mruberry** [comment]
See also https://github.com/pytorch/pytorch/issues/65797. This may happen more often on ROCm just because of timing differences.

**Comment by suo** [comment]
Failures seem specific to complex128 tests: https://fburl.com/scuba/opensource_ci_jobs/h9ljo50y

**Comment by mruberry** [comment]
There might be small CUDA memory leak checks occurring very rarely on other tests, too. Maybe @malfet's idea to ignore tiny leaks is correct, or maybe we should just add a retry to the leak checker.

**Comment by mruberry** [comment]
Another instance: https://github.com/pytorch/pytorch/runs/4218623413?check_suite_focus=true

**Comment by suo** [comment]
Another instance: https://github.com/pytorch/pytorch/runs/4438208561?check_suite_focus=true

**Comment by suo** [comment]
@mruberry any progress on ignoring/retrying these errors?

**Comment by mruberry** [comment]
> @mruberry any progress on ignoring/retrying these errors?

Yep; @ngimel and I had the opportunity to review the approach and I'm working on an alternate PR

**Comment by mruberry** [comment]
See https://github.com/pytorch/pytorch/pull/69556
