### ISSUE TITLE
The connection to the C10d store has failed

### ISSUE THREAD

**Issue by qiankunli** [pytorch/pytorch#67547]
virtualbox vm
os version: ubuntu server 20.04
python version : 3.8.8
pytorch version: 1.10.0
ip : 192.168.56.101
command: `python3 -m torch.distributed.run --rdzv_backend=c10d --rdzv_endpoint=192.168.56.101:29400 --rdzv_id=1 --nnodes=1:2 --nproc_per_node=1 --rdzv_conf timeout=3 --monitor_interval 3 imagenet.py /data/tiny-imagenet-200`

```
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py\", line 155, in _create_tcp_store\n    store = TCPStore(\nRuntimeError: connect() timed out. Original timeout was 60000 ms.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 345, in wrapper\n    return f(*args, **kwargs)\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py\", line 719, in main\n    run(args)\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py\", line 710, in run\n    elastic_launch(\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py\", line 131, in __call__\n    return launch_agent(self._config, self._entrypoint, list(args))\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py\", line 228, in launch_agent\n    rdzv_handler = rdzv_registry.get_rendezvous_handler(rdzv_parameters)\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/registry.py\", line 64, in get_rendezvous_handler\n    return handler_registry.create_handler(params)\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/api.py\", line 253, in create_handler\n    handler = creator(params)\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/registry.py\", line 35, in _create_c10d_handler\n    backend, store = create_backend(params)\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py\", line 250, in create_backend\n    store = _create_tcp_store(params)\n  File \"/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py\", line 175, in _create_tcp_store\n    raise RendezvousConnectionError(\ntorch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.\n",
      "timestamp": "1635517706"
    }
  }
}
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 155, in _create_tcp_store
    store = TCPStore(
RuntimeError: connect() timed out. Original timeout was 60000 ms.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 228, in launch_agent
    rdzv_handler = rdzv_registry.get_rendezvous_handler(rdzv_parameters)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 64, in get_rendezvous_handler
    return handler_registry.create_handler(params)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/api.py", line 253, in create_handler
    handler = creator(params)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 35, in _create_c10d_handler
    backend, store = create_backend(params)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 250, in create_backend
    store = _create_tcp_store(params)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 175, in _create_tcp_store
    raise RendezvousConnectionError(
torch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.
```

when I use `127.0.0.1` instead of `192.168.56.101`, `python3 -m torch.distributed.run --rdzv_backend=c10d --rdzv_endpoint=127.0.0.1:29400 --rdzv_id=1 --nnodes=1:2 --nproc_per_node=1 --rdzv_conf timeout=3 --monitor_interval 3 imagenet.py /data/tiny-imagenet-200`, it is ok

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by qiankunli** [comment]
I found the problem, because c10 use hostname to access other , and I have not config hostname in `/etc/hosts`

**Comment by m-aqeeljanjua** [comment]
> I found the problem, because c10d use hostname to access other , and I have not config hostname in `/etc/hosts`

@qiankunli can you share the solution how u did that?
I'm having the same issue :
` File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 191, in _create_c10d_store
    return TCPStore(
TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 42649).`

**Comment by JingxinLee** [comment]
> I found the problem, because c10d use hostname to access other , and I have not config hostname in `/etc/hosts`
How u did that?

**Comment by JingxinLee** [comment]
> 

What if my all 3 machine the same hostname?

**Comment by kumarme072** [comment]
raise RendezvousConnectionError(
torch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.      getting this same error here is the script for slurm #!/bin/bash

#SBATCH --job-name=torchnode
#SBATCH --error=%J.err
#SBATCH --output=%J.out
#SBATCH --partition=gpu
#SBATCH --nodes=2
#SBATCH --ntasks=4
#SBATCH --gres=gpu:2
##SBATCH --gpus-per-task=1
#SBATCH --cpus-per-task=2

# Getting the head node IP address
nodes_array=($(scontrol show hostnames $SLURM_JOB_NODELIST))
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)

echo "Node IP: $head_node_ip"
export LOGLEVEL=INFO

# Activating the conda environment
eval "$(conda shell.bash hook)"
conda activate myenv1

# Running the PyTorch script in a distributed manner
srun torchrun \
--nnodes=2 \
--nproc_per_node=2 \
--rdzv_id=389 \
--rdzv_backend=c10d \
--rdzv_endpoint=$head_node_ip:50125 \
zz12.py 8 10
