### ISSUE TITLE
Strange nested exception during wrong call of load_state_dict

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#67549]
```
Traceback (most recent call last):
  File "/lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1336, in _load_from_state_dict
    param.copy_(input_param)
TypeError: copy_(): argument 'other' (position 1) must be Tensor, not numpy.ndarray

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lab/vadim/detregwsod/train.py", line 49, in <module>
    main(args)
  File "/lab/vadim/detregwsod/train.py", line 38, in main
    model.backbone.load_state_dict(state_dict)
  File "/lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1392, in load_state_dict
    load(self)
  File "/lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1390, in load
    load(child, prefix + name + '.')
  File "/lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1390, in load
    load(child, prefix + name + '.')
  File "/lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1386, in load
    module._load_from_state_dict(
  File "/lab/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1342, in _load_from_state_dict
    .format(key, param.size(), input_param.size(), ex.args))
TypeError: 'int' object is not callable
```  

cc @albanD @mruberry @jbschlosser @walterddr

**Comment by jbschlosser** [comment]
Hey @vadimkantorov, thanks for the report! This script reproduces the problem on master:

```python
import numpy as np
import torch

m = torch.nn.Linear(2, 2, bias=False)
state_dict = {
    'weight': np.random.randn(2, 2)
}
m.load_state_dict(state_dict)
```

Problem comes from here: https://github.com/pytorch/pytorch/blob/fcba8018c227b7dcfed3af8a439aa18e89e09efa/torch/nn/modules/module.py#L1412

Could possibly catch `TypeError` separately, but might be more trouble than it's worth.

**Comment by albanD** [comment]
We should just check that by the time we get here, both are actual Tensors right?

**Comment by vadimkantorov** [comment]
> Could possibly catch `TypeError` separately, but might be more trouble than it's worth.

Yep, I think before formatting it's better to check `torch.is_tensor`

**Comment by albanD** [comment]
Actionable to raise a nice error for non-Tensor objects.

**Comment by vadimkantorov** [comment]
Also, may be good to replace `.size()` calls to `.shape` calls
