### ISSUE TITLE
[testing] `gradient` OpInfo tests fail in Python 3.10

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#67612]
EDIT: The failure is due to update in Python 3.10 behaviour.

The following OpInfo tests fail locally (with Python 3.10) but pass on CI for `gradient` op

https://github.com/pytorch/pytorch/blob/97f29bda59deab8c063cf01f0a8ff4321b93c55e/torch/testing/_internal/common_methods_invocations.py#L8277-L8282

<details>

<summary>Local failure log</summary>

```
_____________________________________________________________________________________ TestCommonCPU.test_dtypes_gradient_cpu _____________________________________________________________________________________
Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/pytorch_testing_native_device/test/test_ops.py", line 158, in test_dtypes
    self.assertEqual(supported_dtypes, claimed_supported, msg=msg)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1946, in assertEqual
    super().assertEqual(x, y, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/unittest/case.py", line 837, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/unittest/case.py", line 1097, in assertSetEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/unittest/case.py", line 667, in fail
    raise self.failureException(msg)
AssertionError: Items in the second set but not the first:
torch.int32
torch.int16
torch.int8
torch.int64 : Attempted to compare [set] types: Expected: {torch.float64, torch.complex64, torch.bfloat16, torch.complex128, torch.float16, torch.float32}; Actual: {torch.float64, torch.int16, torch.int32, torch.complex64, torch.int64, torch.bfloat16, torch.complex128, torch.float16, torch.float32, torch.int8}.
The supported dtypes for gradient on cpu according to its OpInfo are
        {torch.float64, torch.int16, torch.int32, torch.complex64, torch.int64, torch.bfloat16, torch.complex128, torch.float16, torch.float32, torch.int8}, but the detected supported dtypes are {torch.float64, torch.complex64, torch.bfloat16, torch.complex128, torch.float16, torch.float32}.
        The following dtypes should be removed from the OpInfo: {torch.int32, torch.int16, torch.int8, torch.int64}.
__________________________________________________________________________ TestCommonCPU.test_noncontiguous_samples_gradient_cpu_int64 ___________________________________________________________________________
Traceback (most recent call last):
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 747, in sample_inputs
    samples = self.sample_inputs_func(self, device, dtype, requires_grad, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 2683, in sample_inputs_gradient
    a = torch.tensor(coords, dtype=dtype, device=device)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/pytorch_testing_native_device/test/test_ops.py", line 220, in test_noncontiguous_samples
    sample_inputs = op.sample_inputs(device, dtype, requires_grad=test_grad)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 749, in sample_inputs
    samples = self.sample_inputs_func(self, device, dtype, requires_grad)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 2683, in sample_inputs_gradient
    a = torch.tensor(coords, dtype=dtype, device=device)
TypeError: 'float' object cannot be interpreted as an integer
_________________________________________________________________________ TestCommonMETA.test_noncontiguous_samples_gradient_meta_int64 __________________________________________________________________________
Traceback (most recent call last):
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 747, in sample_inputs
    samples = self.sample_inputs_func(self, device, dtype, requires_grad, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 2683, in sample_inputs_gradient
    a = torch.tensor(coords, dtype=dtype, device=device)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/pytorch_testing_native_device/test/test_ops.py", line 220, in test_noncontiguous_samples
    sample_inputs = op.sample_inputs(device, dtype, requires_grad=test_grad)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 749, in sample_inputs
    samples = self.sample_inputs_func(self, device, dtype, requires_grad)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 2683, in sample_inputs_gradient
    a = torch.tensor(coords, dtype=dtype, device=device)
TypeError: 'float' object cannot be interpreted as an integer
____________________________________________________________________________________ TestCommonCUDA.test_dtypes_gradient_cuda ____________________________________________________________________________________
Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/pytorch_testing_native_device/test/test_ops.py", line 158, in test_dtypes
    self.assertEqual(supported_dtypes, claimed_supported, msg=msg)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1946, in assertEqual
    super().assertEqual(x, y, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/unittest/case.py", line 837, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/unittest/case.py", line 1097, in assertSetEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/unittest/case.py", line 667, in fail
    raise self.failureException(msg)
AssertionError: Items in the second set but not the first:
torch.int32
torch.int16
torch.int8
torch.int64 : Attempted to compare [set] types: Expected: {torch.float64, torch.complex64, torch.bfloat16, torch.complex128, torch.float16, torch.float32}; Actual: {torch.float64, torch.int16, torch.int32, torch.complex64, torch.int64, torch.bfloat16, torch.complex128, torch.float16, torch.float32, torch.int8}.
The supported dtypes for gradient on cuda according to its OpInfo are
        {torch.float64, torch.int16, torch.int32, torch.complex64, torch.int64, torch.bfloat16, torch.complex128, torch.float16, torch.float32, torch.int8}, but the detected supported dtypes are {torch.float64, torch.complex64, torch.bfloat16, torch.complex128, torch.float16, torch.float32}.
        The following dtypes should be removed from the OpInfo: {torch.int32, torch.int16, torch.int8, torch.int64}.
____________________________________________________________________________ TestCommonCUDA.test_multiple_devices_gradient_cuda_int64 ____________________________________________________________________________
Traceback (most recent call last):
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 747, in sample_inputs
    samples = self.sample_inputs_func(self, device, dtype, requires_grad, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 2683, in sample_inputs_gradient
    a = torch.tensor(coords, dtype=dtype, device=device)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/pytorch_testing_native_device/test/test_ops.py", line 188, in test_multiple_devices
    samples = op.sample_inputs(cuda_device, dtype)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 749, in sample_inputs
    samples = self.sample_inputs_func(self, device, dtype, requires_grad)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 2683, in sample_inputs_gradient
    a = torch.tensor(coords, dtype=dtype, device=device)
TypeError: 'float' object cannot be interpreted as an integer
_________________________________________________________________________ TestCommonCUDA.test_noncontiguous_samples_gradient_cuda_int64 __________________________________________________________________________
Traceback (most recent call last):
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 747, in sample_inputs
    samples = self.sample_inputs_func(self, device, dtype, requires_grad, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 2683, in sample_inputs_gradient
    a = torch.tensor(coords, dtype=dtype, device=device)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/pytorch_testing_native_device/test/test_ops.py", line 220, in test_noncontiguous_samples
    sample_inputs = op.sample_inputs(device, dtype, requires_grad=test_grad)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 749, in sample_inputs
    samples = self.sample_inputs_func(self, device, dtype, requires_grad)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_methods_invocations.py", line 2683, in sample_inputs_gradient
    a = torch.tensor(coords, dtype=dtype, device=device)
TypeError: 'float' object cannot be interpreted as an integer
==================================================================================
```

</details>

But looks like it works on CI

All tests on CI pass on this PR: https://github.com/pytorch/pytorch/runs/4058942158?check_suite_focus=true#step:16:1931

Cause of failure on local:
https://github.com/pytorch/pytorch/blob/97f29bda59deab8c063cf01f0a8ff4321b93c55e/torch/testing/_internal/common_methods_invocations.py#L2675-L2683

`a = torch.tensor(coords, dtype=dtype, device=device) ` is where error occurs. Here `dtype` could be int but `coords` are always float and hence the error.

```python
>>> t = torch.tensor([1.0], dtype=torch.int64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
```

@mruberry any idea?

cc @mruberry

**Comment by krshrimali** [comment]
@kshitij12345 - Can you test this on the master branch? Locally (not on `master`, but close to that):

```python
>>> import torch
>>> torch.__version__
'1.11.0a0+git21a596b'
>>> t = torch.tensor([1.0], dtype=torch.int64)
<stdin>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
>>> t
tensor([1])
```

**Comment by kshitij12345** [comment]
I tested it on a very recent commit from master
```python
>>> import torch
>>> torch.__version__
'1.11.0a0+git767ba7c'
>>> t = torch.tensor([1.0], dtype=torch.int64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
```

Surprisingly same branch passes on PR CI (for https://github.com/pytorch/pytorch/pull/65201) but fails locally for this op.

**Comment by krshrimali** [comment]
> I tested it on a very recent commit from master
> 
> ```python
> >>> import torch
> >>> torch.__version__
> '1.11.0a0+git767ba7c'
> >>> t = torch.tensor([1.0], dtype=torch.int64)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: 'float' object cannot be interpreted as an integer
> ```
> 
> Looking at the example, I would presume that yours is slightly older branch (when only DeprecationWarning) was raised. And it has been updated to a hard error now.
> 
> Surprisingly same branch passes on PR CI (for #65201) but fails locally for this op.

Just curious, what is the Python version you are using?

**Comment by kshitij12345** [comment]
`3.10`

And that solves the mystery! Thanks @krshrimali .

I thought the failure was due to update in `torch.tensor` but the failure is due to update in the behavior of Python!

**Comment by mruberry** [comment]
We would definitely take a fix for this.

**Comment by ankitaS11** [comment]
Hi, @kshitij12345 and @mruberry,

I wished to work on this issue, and was wondering if it will be fine if I can work on this? Thanks!

**Comment by kshitij12345** [comment]
@ankitaS11 SGTM! Thanks it would be helpful
