### ISSUE TITLE
Pytorch AssertionError: Torch not compiled with CUDA enabled [Pytorch]

### ISSUE THREAD

**Issue by wilberever100** [pytorch/pytorch#67627]
I'm trying to run this repo:  https://github.com/lxdv/ecg-classification
I solved some problems from dependency errors, now I'm getting this issue:
 PS D:\Computer Science\2021-2\proyectos1\Github\ecg-classification-master> python pipeline.py --config configs/pipelines/config.json
Trainer:  Pipeline1D <class 'pipelines.pipelines.Pipeline1D'>
Traceback (most recent call last):
  File "D:\Computer Science\2021-2\proyectos1\Github\ecg-classification-master\pipeline.py", line 19, in <module>
    pipeline = pipeline_type(config)
  File "D:\Computer Science\2021-2\proyectos1\Github\ecg-classification-master\pipelines\pipelines.py", line 8, in __init__
    super().__init__(config)
  File "D:\Computer Science\2021-2\proyectos1\Github\ecg-classification-master\pipelines\base_pipeline.py", line 25, in __init__
    self.model = self._init_net()
  File "D:\Computer Science\2021-2\proyectos1\Github\ecg-classification-master\pipelines\pipelines.py", line 14, in _init_net
    model = model.to(self.config["device"])
  File "C:\Users\wilbe\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 899, in to
    return self._apply(convert)
  File "C:\Users\wilbe\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 570, in _apply
    module._apply(fn)
  File "C:\Users\wilbe\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 593, in _apply
    param_applied = fn(param)
  File "C:\Users\wilbe\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\wilbe\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\cuda\__init__.py", line 208, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

I want to disable CUDA, but I dont know how, please, any suggestion?

**Comment by mruberry** [comment]
It looks like there may be a configuration error in the json file you're using, but this question is more appropriate for that package or possibly for the PyTorch Forums.
