### ISSUE TITLE
`test_variant_consistency_jit` failing for `max_unpool2d`

### ISSUE THREAD

**Issue by krshrimali** [pytorch/pytorch#67659]
## 🐛 Bug

While trying to add OpInfo for `max_unpool2d`, following error is raised:

```python
======================================================================
ERROR: test_variant_consistency_jit_nn_functional_max_unpool2d_cpu_float32 (__main__.TestJitCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/krshrimali/Documents/Projects/Quansight/pytorch/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    raise rte
  File "/home/krshrimali/Documents/Projects/Quansight/pytorch/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/krshrimali/Documents/Projects/Quansight/pytorch/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "/home/krshrimali/Documents/Projects/Quansight/pytorch/test/test_ops.py", line 800, in test_variant_consistency_jit
    check_alias_annotation(name, (get_sample(),) + sample.args, sample.kwargs,
  File "/home/krshrimali/Documents/Projects/Quansight/pytorch/torch/testing/_internal/jit_metaprogramming_utils.py", line 524, in check_alias_annotation
    torch._C._jit_check_alias_annotation(CU.the_method.graph, tuple(tensors), aten_name)
RuntimeError: There should be exactly two elements (height, width) in output_size, but found: 0 elements.

----------------------------------------------------------------------
```

This happens when `output_size` is not passed to the kwargs in sample inputs. Please note that on `cuda` device, it instead leads to a segmentation fault. 

## To Reproduce

1. Checkout to the branch: https://github.com/krshrimali/pytorch/tree/origin/max_unpoolNd
2. Run the OpInfo tests after removing the skips for `max_unpool2d`. `python3 test/test_ops.py -k max_unpool2d`

As mentioned earlier, on my local system (CUDA), I get segmentation fault, so I had to add a skip for CUDA for this test to see the above failure on CPU:

```python
DecorateInfo(unittest.skip("Skipped!"), 'TestJit', 'test_variant_consistency_jit', device_type='cuda', dtypes=(torch.float32,)),
```

If anyone else can reproduce this segmentation fault, please let me know.

## Expected behavior

The test should pass.

## Additional context

Please see https://github.com/pytorch/pytorch/pull/67328 for the OpInfo PR.

cc: @mruberry @eellison

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
