### ISSUE TITLE
torch.jit.script fails to find attribute '_modules' of nn.Module

### ISSUE THREAD

**Issue by JiahangXu** [pytorch/pytorch#67674]
## 🐛 Bug

I have a model using `self.add_module` from `nn.Module`, and the forward function is designed by calling `self._module`. However the torch.jit.script fails to parse the code.

## To Reproduce

Run the following code:
``` python
import torch
import torch.nn as nn


class Demo1(nn.Module):
    def __init__(self):
        super().__init__()
        self.add_module('linear',nn.Linear(3, 64, bias=True))

    def forward(self, x):
        for module in self._modules.values():
            x = module(x)
        return x

if __name__ == '__main__':
    model = Demo1()
    script_module = torch.jit.script(model)
```
And the error is:
```
Traceback (most recent call last):
  File "/home/jiahang/working/test_torch_jit.py", line 29, in <module>
    script_module = torch.jit.script(model)
  File "/home/jiahang/anaconda3/envs/py36/lib/python3.6/site-packages/torch/jit/_script.py", line 1097, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/home/jiahang/anaconda3/envs/py36/lib/python3.6/site-packages/torch/jit/_recursive.py", line 412, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/jiahang/anaconda3/envs/py36/lib/python3.6/site-packages/torch/jit/_recursive.py", line 478, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/jiahang/anaconda3/envs/py36/lib/python3.6/site-packages/torch/jit/_recursive.py", line 355, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Module 'Demo1' has no attribute '_modules' :
  File "/home/jiahang/working/test_torch_jit.py", line 13
    def forward(self, x):
        for module in self._modules.values():
                      ~~~~~~~~~~~~~ <--- HERE
            x = module(x)
        return x
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): windows 10 WSL
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.10

**Comment by singagan** [comment]
Hi, Any updates on this?

**Comment by taras-janea** [comment]
`_modules` itself shouldn't be exposed. Instead, the accessor method should be used, for example, `children`:

```
import torch
import torch.nn as nn

class Demo1(nn.Module):
    def __init__(self):
        super().__init__()
        self.add_module('linear', nn.Linear(3, 64, bias=True))

    def forward(self, x):
        for module in self.children():
            x = module(x)
        return x

if __name__ == '__main__':
    model = Demo1()
    script_module = torch.jit.script(model)
```
