### ISSUE TITLE
[feature request] torch.clamp on BoolTensors

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#67684]
```python
torch.tensor([True, False]).clamp(0, 1)
# *** RuntimeError: "clamp_scalar_cpu" not implemented for 'Bool'
``` 

This one should be no-op, but probably even other clamps could be supported if clamp_min is below <= 1 (or for a stricter version <= 0)

**Comment by KeshavML** [comment]
I just got the same error, but I have no clue as to what it means. Please guide me to some resources for this.

`Traceback (most recent call last):
  File "Train.py", line 111, in <module>
    main()
  File "Train.py", line 107, in main
    folder="saved_images/", device=DEVICE)
  File "/home/keshav/Desktop/project notes/Code/Bone_Suppression/utils.py", line 101, in save_predictions_as_imgs
    torchvision.utils.save_image(y.unsqueeze(1), f"{folder}/{epoch}_{idx}.png")
  File "/home/keshav/anaconda3/envs/MINOR/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/keshav/anaconda3/envs/MINOR/lib/python3.6/site-packages/torchvision/utils.py", line 134, in save_image
    ndarr = grid.mul(255).add_(0.5).clamp_(0, 255).permute(1, 2, 0).to('cpu', torch.uint8).numpy()
RuntimeError: "clamp_scalar_cpu" not implemented for 'Half'`

**Comment by vadimkantorov** [comment]
You seem to be that you're using float16/half on CPU which does not support many of the operators. If you need float16 tensors to support clamp on CPU, please open a separate issue.

**Comment by bhack** [comment]
This is going to create a problem with the Pytorch Vision library with `float16` images/tensor. See https://github.com/pytorch/vision/issues/4915#issuecomment-1515367700

**Comment by bhack** [comment]
@vadimkantorov Done https://github.com/pytorch/pytorch/issues/99563
