### ISSUE TITLE
DISABLED test_pointwise_op_fastpath__foreach_addcmul_cuda_uint8 (__main__.TestForeachCUDA)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#67723]
Seems flaky on CI -- showed up in one commit but was fine the next:

In [qnnpack] Remove redundant fp16 dependency (#67281) on trunk
https://github.com/pytorch/pytorch/runs/4083010308?check_suite_focus=true

```
======================================================================
FAIL [0.936s]: test_pointwise_op_fastpath__foreach_addcmul_cuda_uint8 (__main__.TestForeachCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1422, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1422, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 772, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_foreach.py", line 311, in test_pointwise_op_fastpath
    self._test_pointwise_op(device, dtype, op, N, True, disable_fastpath, values=scalar)
  File "test_foreach.py", line 287, in _test_pointwise_op
    self._pointwise_test(dtype, inplace_op, inplace_ref, inputs, is_fastpath, is_inplace=True, values=values)
  File "test_foreach.py", line 261, in _pointwise_test
    actual = op(inputs, self.is_cuda, is_fastpath)
  File "test_foreach.py", line 80, in __call__
    assert e.count == self.n_expected_cudaLaunchKernels
AssertionError
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @crcrpar @mcarilli @ngimel

**Comment by crcrpar** [comment]
Related issue: https://github.com/pytorch/pytorch/issues/67208
