### ISSUE TITLE
INTERNAL ASSERT FAILED at "..\\aten\\src\\ATen\\MapAllocator.cpp":135

### ISSUE THREAD

**Issue by Jdogzz** [pytorch/pytorch#67844]
## To Reproduce

1. Here's a simple script I just wrote naively mirroring what I would do with a standard multiprocessing queue:
```
import numpy
import torch
import time
import torch.multiprocessing as mp
import queue
from PIL import Image

def myproducer(thequeue,writerfinishqueue):
   for i in range(2000):
      thearray=numpy.full((2048,2048),255,dtype=numpy.uint8)
      thequeue.put(torch.from_numpy(thearray))

def mywriter(thequeue,writerfinishqueue):
   filecounter=0
   starttime=0
   while True:
      try:
         mytensor=thequeue.get_nowait()
         filecounter=filecounter+1
         if filecounter==1:
            starttime=time.time()
         mynumpyarray=mytensor.numpy()
         Image.fromarray(mynumpyarray).convert("L").save(str(filecounter)+".bmp","BMP")
         if filecounter==2000:
            print(time.time()-starttime)
            break
      except queue.Empty:
         pass
      
if __name__ == '__main__':
   thequeue=mp.Queue()
   myproducerproc=mp.Process(target=myproducer,args=(thequeue))
   myproducerproc.start()
   mywriterproc=mp.Process(target=mywriter,args=(thequeue))
   mywriterproc.start()
   myproducerproc.join()
   mywriterproc.join()
```
Running this results in this error message:
```Process Process-2:
Traceback (most recent call last):
  File "C:\Users\myuser\.conda\envs\ppump38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\myuser\.conda\envs\ppump38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\myuser\Desktop\writertest\testtens.py", line 22, in mywriter
    mytensor=thequeue.get_nowait()
  File "C:\Users\myuser\.conda\envs\ppump38\lib\multiprocessing\queues.py", line 129, in get_nowait
    return self.get(False)
  File "C:\Users\myuser\.conda\envs\ppump38\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\myuser\.conda\envs\ppump38\lib\site-packages\torch\multiprocessing\reductions.py", line 305, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: falseINTERNAL ASSERT FAILED at "..\\aten\\src\\ATen\\MapAllocator.cpp":135, please report a bug to PyTorch. Couldn't open shared file mapping: <00000218E50CF0F2>, error code: <2>
```

## Expected behavior

Ideally this would run to completion without throwing any errors (in my trials it crashes ~20 frames before the end of the program). If I understand correctly, it's crashing because the producer process ends while the writer process is still reading the queue backed by shared memory. I solved this by adding an extra queue for the producer queue to receive a message from the writer queue signalling it's done, but if pytorch could extend the life of the shared memory behind the scenes I think that would be a better option. (If there's a more elegant way of handling this I would appreciate a pointer)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19043-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 3GB
Nvidia driver version: 471.96
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.3.0           haa95532_524
[conda] mkl-service               2.4.0            py38h2bbff1b_0
[conda] mkl_fft                   1.3.1            py38h277e83a_0
[conda] mkl_random                1.2.2            py38hf11a4ad_0
[conda] numpy                     1.21.2           py38hfca59bb_0
[conda] numpy-base                1.21.2           py38h0829f74_0
[conda] pytorch                   1.10.0          py3.8_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchvision               0.11.1               py38_cu113    pytorch
```

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @peterjc123 @mszhanyi @skyline75489 @nbcsm @VitalyFedyunin

**Comment by LucaBonfiglioli** [comment]
A similar error is bugging me too, same file but line 263 instead of 135.

**Comment by soulitzer** [comment]
I was able to run using the following script, but I did could not reproduce the error (using main branch on Ubuntu).

```python
import numpy
import torch
import time
import torch.multiprocessing as mp
import queue
from PIL import Image

def myproducer(thequeue):
   for i in range(100):
      thearray=numpy.full((2048,2048),255,dtype=numpy.uint8)
      thequeue.put(torch.from_numpy(thearray))

def mywriter(thequeue):
   filecounter=0
   starttime=0
   while True:
      try:
         mytensor=thequeue.get_nowait()
         filecounter=filecounter+1
         if filecounter==1:
            starttime=time.time()
         mynumpyarray=mytensor.numpy()
         Image.fromarray(mynumpyarray).convert("L").save(str(filecounter)+".bmp","BMP")
         if filecounter==100:
            print(time.time()-starttime)
            break
      except queue.Empty:
         pass

# On ubuntu 
torch.multiprocessing.set_sharing_strategy("file_system")

thequeue=mp.Queue()
myproducerproc=mp.Process(target=myproducer,args=(thequeue,))
myproducerproc.start()
mywriterproc=mp.Process(target=mywriter,args=(thequeue,))
mywriterproc.start()
myproducerproc.join()
mywriterproc.join()
```

**Comment by albanD** [comment]
Might be the same as https://github.com/pytorch/pytorch/issues/18797 ?

**Comment by soulitzer** [comment]
From Triage Review: We should try to reproduce this on Windows. The error code is different from the linked issue above.

**Comment by malfet** [comment]
@mszhanyi can you please try to reproduce it on your end?

**Comment by mszhanyi** [comment]
In my machine, the stacktrance is 
```
Traceback (most recent call last):
  File "67844.py", line 32, in <module>
    myproducerproc=mp.Process(target=myproducer,args=(thequeue))
  File "D:\programs\Continuum\anaconda3\envs\py38\lib\multiprocessing\process.py", line 91, in __init__
    self._args = tuple(args)
TypeError: 'Queue' object is not iterable
```

@Jdogzz 
Did you install cudnn?
`CUDA runtime version: Could not collect`
`cuDNN version: Could not collect`

**Comment by mszhanyi** [comment]
@malfet, It could reproduced in my machine

**Comment by mszhanyi** [comment]
And this bug has exited for a long time.
It can be reproduced in another Windows CPU machine with pytorch 1.6.

**Comment by mszhanyi** [comment]
It looks that createevent isn't invoked.
 https://github.com/pytorch/pytorch/blob/a229c3e51a22420d57cfd9e638088da0d8894bfd/aten/src/ATen/MapAllocator.cpp#L115

```
(nightly) d:\dev\67844>python test2.py
eventname is 0000021602392822
open event 0000013CF4140762
eventname is 00000216023925E2
open event 0000013CF4140B22
event is null eventname is tProcess Process-2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\nightly\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\nightly\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\dev\67844\test2.py", line 18, in mywriter
    mytensor=thequeue.get_nowait()
  File "C:\ProgramData\Anaconda3\envs\nightly\lib\multiprocessing\queues.py", line 129, in get_nowait
    return self.get(False)
  File "C:\ProgramData\Anaconda3\envs\nightly\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "e:\git\zyrepo\pytorch\torch\multiprocessing\reductions.py", line 311, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: falseINTERNAL ASSERT FAILED at "..\\aten\\src\\ATen\\MapAllocator.cpp":129, please report a bug to PyTorch. Couldn't open shared event: <0000013CF4140B22>, error code: <2>
```

**Comment by mlowell28** [comment]
I am running windows I and I just got it randomly after a few epochs of training. What do you need?

**Comment by mszhanyi** [comment]
I could reproduce it stably now.
So far, the reason is OpenEvent is called while CreateEvent not called.
https://github.com/pytorch/pytorch/blob/a229c3e51a22420d57cfd9e638088da0d8894bfd/aten/src/ATen/MapAllocator.cpp#L115-L117

**Comment by mszhanyi** [comment]
stacktrace
```
Exception raised from MapAllocator at ..\aten\src\ATen\MapAllocator.cpp:127 (most recent call first):
00007FFDD6DFA23200007FFDD6DFA1D0 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFDD6DF9AFE00007FFDD6DF9AB0 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FFDD6DF9BAF00007FFDD6DF9B70 c10.dll!c10::detail::torchInternalAssertFail [<unknown file> @ <unknown line number>]
00007FFDA802CDF500007FFDA802C630 torch_cpu.dll!at::MapAllocator::MapAllocator [<unknown file> @ <unknown line number>]
00007FFDA802C5B600007FFDA802C550 torch_cpu.dll!at::MapAllocator::MapAllocator [<unknown file> @ <unknown line number>]
00007FFDA802D6FB00007FFDA802D680 torch_cpu.dll!at::RefcountedMapAllocator::RefcountedMapAllocator [<unknown file> @ <unknown line number>]
00007FFDDC6E116D00007FFDDC6E1120 shm.dll!THManagedMapAllocator::makeDataPtr [<unknown file> @ <unknown line number>]
00007FFDA770891E00007FFDA77046B0 torch_python.dll!initModule [<unknown file> @ <unknown line number>]
00007FFDCB32A0D200007FFDCB329FD0 python38.dll!PyCFunction_Call [<unknown file> @ <unknown line number>]
00007FFDCB33EC3500007FFDCB33DEE0 python38.dll!Py_CheckFunctionResult [<unknown file> @ <unknown line number>]
00007FFDCB3408C700007FFDCB33FE10 python38.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDCB33CA5D00007FFDCB33C980 python38.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFDCB31587A00007FFDCB31580C python38.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFDCB2FBBA900007FFDCB2FBB68 python38.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFDCB2FAC3100007FFDCB2FA6EC python38.dll!PyUnicode_DecodeUTF32Stateful [<unknown file> @ <unknown line number>]
00007FFDCB338F4000007FFDCB338A24 python38.dll!Py_HashPointer [<unknown file> @ <unknown line number>]
00007FFDCB2FD36500007FFDCB2FD0A0 python38.dll!PyComplex_FromCComplex [<unknown file> @ <unknown line number>]
00007FFDCB2FD20400007FFDCB2FD0A0 python38.dll!PyComplex_FromCComplex [<unknown file> @ <unknown line number>]
00007FFDCB30706900007FFDCB306CF0 python38.dll!PyArg_UnpackStack [<unknown file> @ <unknown line number>]
00007FFDCB33E30600007FFDCB33DEE0 python38.dll!Py_CheckFunctionResult [<unknown file> @ <unknown line number>]
00007FFDCB3408C700007FFDCB33FE10 python38.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDCB33BBD800007FFDCB33B9B0 python38.dll!PyEval_EvalCodeWithName [<unknown file> @ <unknown line number>]
00007FFDCB33E94600007FFDCB33DEE0 python38.dll!Py_CheckFunctionResult [<unknown file> @ <unknown line number>]
00007FFDCB34063400007FFDCB33FE10 python38.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDCB33E64E00007FFDCB33DEE0 python38.dll!Py_CheckFunctionResult [<unknown file> @ <unknown line number>]
00007FFDCB34063400007FFDCB33FE10 python38.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDCB33CA5D00007FFDCB33C980 python38.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFDCB31587A00007FFDCB31580C python38.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFDCB31570B00007FFDCB3153C8 python38.dll!PySequence_GetItem [<unknown file> @ <unknown line number>]
00007FFDCB34174200007FFDCB33FE10 python38.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDCB33E64E00007FFDCB33DEE0 python38.dll!Py_CheckFunctionResult [<unknown file> @ <unknown line number>]
00007FFDCB34063400007FFDCB33FE10 python38.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDCB33BBD800007FFDCB33B9B0 python38.dll!PyEval_EvalCodeWithName [<unknown file> @ <unknown line number>]
00007FFDCB33E94600007FFDCB33DEE0 python38.dll!Py_CheckFunctionResult [<unknown file> @ <unknown line number>]
00007FFDCB34063400007FFDCB33FE10 python38.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDCB33E64E00007FFDCB33DEE0 python38.dll!Py_CheckFunctionResult [<unknown file> @ <unknown line number>]
00007FFDCB34049F00007FFDCB33FE10 python38.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDCB33BBD800007FFDCB33B9B0 python38.dll!PyEval_EvalCodeWithName [<unknown file> @ <unknown line number>]
00007FFDCB33E94600007FFDCB33DEE0 python38.dll!Py_CheckFunctionResult [<unknown file> @ <unknown line number>]
00007FFDCB340CFE00007FFDCB33FE10 python38.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDCB33BBD800007FFDCB33B9B0 python38.dll!PyEval_EvalCodeWithName [<unknown file> @ <unknown line number>]
00007FFDCB36822B00007FFDCB368190 python38.dll!PyEval_EvalCodeEx [<unknown file> @ <unknown line number>]
00007FFDCB36818900007FFDCB36815C python38.dll!PyEval_EvalCode [<unknown file> @ <unknown line number>]
00007FFDCB367EB600007FFDCB367C1C python38.dll!PyFuture_FromASTObject [<unknown file> @ <unknown line number>]
00007FFDCB367E4500007FFDCB367C1C python38.dll!PyFuture_FromASTObject [<unknown file> @ <unknown line number>]
00007FFDCB2F730500007FFDCB2F727C python38.dll!PyRun_StringFlags [<unknown file> @ <unknown line number>]
00007FFDCB35BC8500007FFDCB35BC40 python38.dll!PyRun_SimpleStringFlags [<unknown file> @ <unknown line number>]
00007FFDCB43691200007FFDCB434FF8 python38.dll!PyCode_NewEmpty [<unknown file> @ <unknown line number>]
00007FFDCB3E491F00007FFDCB3E47DC python38.dll!Py_RunMain [<unknown file> @ <unknown line number>]
00007FFDCB3E47F100007FFDCB3E47DC python38.dll!Py_RunMain [<unknown file> @ <unknown line number>]
00007FFDCB3E453E00007FFDCB3E4464 python38.dll!PyArgv_AsWstrList [<unknown file> @ <unknown line number>]
00007FFDCB4388B900007FFDCB438894 python38.dll!Py_Main [<unknown file> @ <unknown line number>]
00007FF6488E1268 <unknown symbol address> python.exe!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFDEB8684D400007FFDEB8684C0 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FFDED60179100007FFDED601770 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]
```

**Comment by mszhanyi** [comment]
The root cause is the producer process might exit earlier than the consumer process to open the event.
One way to verify it is to add time.sleep(3) in producer function, thus the script won't throw exception.
```
def myproducer(thequeue):
   for i in range(100):
      thearray=numpy.full((2048,2048),255,dtype=numpy.uint8)
      thequeue.put(torch.from_numpy(thearray))
   time.sleep(3)
```
So, I think the sync logic should be improved.


The below script could reproduce the error more easily.
We only add time.sleep(5) before reading the queue.
```
import numpy
import torch
import time
import torch.multiprocessing as mp
import queue
from PIL import Image

def myproducer(thequeue):
   for i in range(1):
      thearray=numpy.full((2048,2048),255,dtype=numpy.uint8)
      thequeue.put(torch.from_numpy(thearray))

def mywriter(thequeue):
   filecounter=0
   starttime=0
   while True:
      try:
         time.sleep(10)
         mytensor=thequeue.get_nowait()
         filecounter=filecounter+1
         if filecounter==1:
            starttime=time.time()
         mynumpyarray=mytensor.numpy()
         # Image.fromarray(mynumpyarray).convert("L").save(str(filecounter)+".bmp","BMP")
         if filecounter==1:
            print(time.time()-starttime)
            break
      except queue.Empty:
         pass

if __name__ == '__main__':
  thequeue=mp.Queue()
  myproducerproc=mp.Process(target=myproducer,args=(thequeue,))
  myproducerproc.start()
  mywriterproc=mp.Process(target=mywriter,args=(thequeue,))
  mywriterproc.start()
  myproducerproc.join()
  mywriterproc.join()
```

**Comment by mszhanyi** [comment]
@soulitzer @albanD @malfet 
Could we ask users to exit producer process while the queue is empty  for safety?
```
def myproducer(thequeue):
    for i in range(100):
      thearray=numpy.full((2048,2048),255,dtype=numpy.uint8)
      thequeue.put(torch.from_numpy(thearray))
    while True:
        if thequeue.empty():
            break;
        else:
            time.sleep(1)
```

**Comment by malfet** [comment]
@mszhanyi can you please share what exception are you seeing? Because indeed I can trigger the exception by running the code, but its not in MapAllocator, but in the multiprocessing code.

**Comment by malfet** [comment]
> I was able to run using the following script, but I did could not reproduce the error (using main branch on Ubuntu).
>

**Comment by malfet** [comment]
Here is the modified example that I've been running for hours without running into the problem:
```
import numpy
import torch
import time
import torch.multiprocessing as mp
import queue
from PIL import Image


queue_length = 100000

def myproducer(thequeue, waitev):
   for i in range(queue_length):
      thearray=numpy.full((2048,2048),255,dtype=numpy.uint8)
      thequeue.put(torch.from_numpy(thearray))

   waitev.wait()   

def mywriter(thequeue, waitenv):
   filecounter=0
   starttime=0
   while True:
      try:
         mytensor=thequeue.get_nowait()
         filecounter=filecounter+1
         if filecounter==1:
            starttime=time.time()
         mynumpyarray=mytensor.numpy()
         Image.fromarray(mynumpyarray).convert("L").save(str(filecounter%1000)+".bmp","BMP")
         if filecounter % 1000 == 0 and filecounter > 0:
            print(filecounter, time.time()-starttime)
         if filecounter==queue_length:
            print(time.time()-starttime)
            waitev.set()
            break
      except queue.Empty:
         pass

thequeue=mp.Queue()
waitev=mp.Event()
myproducerproc=mp.Process(target=myproducer,args=(thequeue,waitev))
myproducerproc.start()
mywriterproc=mp.Process(target=mywriter,args=(thequeue,waitev))
mywriterproc.start()
mywriterproc.join()
myproducerproc.join()
```

**Comment by msgfs** [comment]
Got the same error in google colab, so it's not only windows related.

**Comment by mszhanyi** [comment]
I think we could improve the error message at least. 
We could extract the producer process id from the event name.
Once it fails to get the event, we could check if the producer exists and provide clearer message to users

**Comment by sinhong96** [comment]
Hi, is this problem solved? I faced the same problem

**Comment by VitalyFedyunin** [comment]
Please try to use pytorch 1.11 it has better error messaging which will help to diagnose the problem.

**Comment by mantaionut** [comment]
I managed to reproduce this on 1.11.1 with the following error: ```Process Process-2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Work\TestPY\test_pytorch.py", line 18, in mywriter
    mytensor=thequeue.get_nowait()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 135, in get_nowait
    return self.get(False)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\multiprocessing\reductions.py", line 311, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: Couldn't open shared event: <000001DF49AA9BA2>, error code: <2>```
But I could not reproduce this on 1.13.1. 
If this issue still happens please open another issue.
