### ISSUE TITLE
Pytorch 1.10.0 missing fft support on android? RuntimeError: fft: ATen not compiled with FFT support

### ISSUE THREAD

**Issue by cronoikt2k** [pytorch/pytorch#67842]
## 🐛 Bug
Hi everyone,

I am currently trying to port [silero-vad](https://github.com/snakers4/silero-vad) to android (mentioning @snakers4 FYI). The app is still in an early stage and I have zero experience with android. It is highly likely that it isn't a bug and I am just doing something wrong, but it looks like the android PyTorch builds do not have fft support. 

According to the [release notes](https://github.com/pytorch/pytorch/releases/tag/v1.10.0) (Misc section) of 1.10.0, PyTorch for arm should be compiled with fft support but I receive the following error messages during the forward pass:

org.pytorch:pytorch_android_lite:1.10.0:
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.example.testVAD, PID: 6113
    com.facebook.jni.CppException: fft: ATen not compiled with FFT support
      
      Debug info for handle(s): -1, was not found.
      
    Exception raised from _fft_r2c_mkl at ../aten/src/ATen/native/mkl/SpectralOps.cpp:569 (most recent call first):
    (no backtrace available)
        at org.pytorch.LiteNativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:52)
        at com.example.testVAD.MainActivity.recognize(MainActivity.java:210)
        at com.example.testVAD.MainActivity.run(MainActivity.java:188)
        at java.lang.Thread.run(Thread.java:919)
```
org.pytorch:pytorch_android:1.10.0
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.example.testVAD, PID: 10231
    java.lang.RuntimeException: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/models/number_vad_model.py", line 17, in forward
        x: Tensor) -> Tensor:
        feature_extractor = self.feature_extractor
        x0 = (feature_extractor).forward(x, )
              ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        adaptive_normalization = self.adaptive_normalization
        x1 = (adaptive_normalization).forward(x0, )
      File "code/__torch__/models/number_vad_model.py", line 42, in forward
        win_length = self.win_length
        hop_length = self.hop_length
        stft_sample = __torch__.torch.functional.stft(wav, n_fft, hop_length, win_length, None, True, "reflect", False, None, None, )
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        mag, phase, = _1(stft_sample, 1., )
        mode = self.mode
      File "code/__torch__/torch/functional.py", line 21, in stft
      else:
        input0 = input
      _2 = torch.stft(input0, n_fft, hop_length, win_length, window, normalized, onesided, return_complex)
           ~~~~~~~~~~ <--- HERE
      return _2
    
    Traceback of TorchScript, original code (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/torch/functional.py", line 515, in stft
            input = F.pad(input.view(extended_shape), (pad, pad), pad_mode)
            input = input.view(input.shape[-signal_dim:])
        return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore
               ~~~~~~~~ <--- HERE
                        normalized, onesided, return_complex)
    RuntimeError: fft: ATen not compiled with FFT support
    
        at org.pytorch.NativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:52)
        at com.example.testVAD.MainActivity.recognize(MainActivity.java:210)
        at com.example.testVAD.MainActivity.run(MainActivity.java:188)
        at java.lang.Thread.run(Thread.java:919)
```

## To Reproduce

On an x86 machine:
```
import torch
model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad', model='silero_vad', force_reload=True)
model._save_for_lite_interpreter("AndroidStudioProjects/testVAD/app/src/main/assets/silero_vad.ptl")
```
 *I started with the [s2t demo](https://github.com/pytorch/android-demo-app/tree/master/SpeechRecognition) and can load the model but the forward pass leads to the error message above.
Android app:
```
//loading the model
    private void load_encoder() throws FileNotFoundException{
        String silero_vad_path = null;
        File file = new File(getApplicationContext().getFilesDir(), "silero_vad.ptl");

        try (InputStream is = getApplicationContext().getAssets().open("silero_vad.ptl")) {
            OutputStream os = new FileOutputStream(file);
            byte[] buffer = new byte[4 * 1024];
            int read;
            while ((read = is.read(buffer)) != -1) {
                os.write(buffer, 0, read);
            }
            os.flush();

            silero_vad_path = file.getAbsolutePath();
        } catch (IOException e) {
            throw new FileNotFoundException("silero_vad pytorch model not found");
        }

        //vad_encoder = LiteModuleLoader.load(silero_vad_path);
        vad_encoder = Module.load(silero_vad_path);
    }


    private String recognize(float[] floatInputBuffer){
        double audio_input[] = new double[RECORDING_LENGTH];
        for (int n = 0; n < RECORDING_LENGTH; n++)
            audio_input[n] = floatInputBuffer[n];

        FloatBuffer inTensorBuffer = Tensor.allocateFloatBuffer(RECORDING_LENGTH);
        for (double val : audio_input)
            inTensorBuffer.put((float)val);

        Tensor inTensor = Tensor.fromBlob(inTensorBuffer, new long[]{1, RECORDING_LENGTH});
        final String result = vad_encoder.forward(IValue.from(inTensor)).toStr();

        return result;
    }
```

## Expected behavior

Pytorch Android packages should be built with fft support or in case the error is different, provide a better error message.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0+cpu
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version:-
 - GPU models and configuration:-
 - Any other relevant information:

@peterbell10 could you please have a look?

cc @mruberry @peterbell10

**Comment by snakers4** [comment]
As for [silero-vad](https://github.com/snakers4/silero-vad) there is a mobile friendly model, that does not use a built-in FFT, but a manual layer, so you can use that one.

https://github.com/snakers4/silero-vad/blob/master/files/model_micro_mobile.jit

As for the future, all of our models will use a manual module instead of build-in FFT for this particular reason.

**Comment by cronoikt2k** [comment]
@snakers4 That's great news. Thank you for the quick response. How is the performance of this new architecture compared to the build-in fft?

**Comment by snakers4** [comment]
This particular layer should be more or less equivalent

**Comment by favrei** [comment]
+1
having the identical issue.

getting `fft: ATen not compiled with FFT support` for both
`org.pytorch:pytorch_android_lite:1.10.0`
and
`org.pytorch:pytorch_android:1.10.0`

Is the torch.fft supported at this version? I am testing with a Pixel 5 running Android 12.
