### ISSUE TITLE
[Caffe2]

### ISSUE THREAD

**Issue by why702** [pytorch/pytorch#6794]
When I run the `lmdb_create_example.py --output_file ~/git/caffe2/build/caffe2/python/examples/test.lmdb`

I got the below error:

>>> Write database...
Inserted 0 rows
Inserted 16 rows
Inserted 32 rows
Inserted 48 rows
Inserted 64 rows
Inserted 80 rows
Inserted 96 rows
Inserted 112 rows
Checksum/write: 1744642
>>> Read database...
Traceback (most recent call last):
  File "/home/bill/git/caffe2/build/caffe2/python/examples/lmdb_create_example.py", line 107, in <module>
    main()
  File "/home/bill/git/caffe2/build/caffe2/python/examples/lmdb_create_example.py", line 103, in main
    read_db_with_caffe2(args.output_file, checksum)
  File "/home/bill/git/caffe2/build/caffe2/python/examples/lmdb_create_example.py", line 71, in read_db_with_caffe2
    db=db_file, db_type="lmdb")
  File "/home/bill/git/caffe2/build/caffe2/python/model_helper.py", line 436, in TensorProtosDBInput
    return helpers.db_input.db_input(
AttributeError: 'module' object has no attribute 'db_input'

However I check the /git/caffe2/build/caffe2/python/helpers/db_input.db_input is existed.
I'm new in Caffe2. 
Do anyone know how to fix this?

- PyTorch or Caffe2: Caffe2
- OS: Ubuntu 16.04
- PyTorch version:
- How you installed PyTorch (conda, pip, source): source
- Python version: 2.7
- CUDA/cuDNN version: 9.0
- GPU models and configuration: NVRM version: NVIDIA UNIX x86_64 Kernel Module  390.30  Wed Jan 31 22:08:49 PST 2018
- GCC version (if compiling from source): 5.4.0 20160609
- CMake version: 3.5.1
- Build command you used (if compiling from source):
- Versions of any other relevant libraries:

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

**Comment by joey3639570** [comment]
I encounted the same problem, any update?

**Comment by lhq1208** [comment]
I simply added
'from caffe2.python.helpers import db_input'
in model_helper.py and fixed this bug.
But I encountered another problem:  
RuntimeError: [enforce fail at db.h:190] db_. Cannot open db: test of type lmdb Error from operator: 
output: "dbreader_test" name: "" type: "CreateDB" arg { name: "db" s: "test" } arg { name: "db_type" s: "lmdb" }
Can anyboby tell me how to deal with it???

**Comment by lichangW** [comment]
me too, any solution?

**Comment by rix161** [comment]
any solution?

**Comment by aswin1980** [comment]
Having same problem
Any solutions?
>>> Write database...
Inserted 0 rows
Inserted 16 rows
Inserted 32 rows
Inserted 48 rows
Inserted 64 rows
Inserted 80 rows
Inserted 96 rows
Inserted 112 rows
Checksum/write: 1746063
>>> Read database...
Traceback (most recent call last):
  File "pytorch/caffe2/python/examples/lmdb_create_example.py", line 107, in <module>
    main()
  File "pytorch/caffe2/python/examples/lmdb_create_example.py", line 103, in main
    read_db_with_caffe2(args.output_file, checksum)
  File "pytorch/caffe2/python/examples/lmdb_create_example.py", line 71, in read_db_with_caffe2
    db=db_file, db_type="lmdb")
  File "/home/aswin/anaconda2/lib/python2.7/site-packages/caffe2/python/model_helper.py", line 435, in TensorProtosDBInput
    return helpers.db_input.db_input(
AttributeError: 'module' object has no attribute 'db_input'

**Comment by silenceli** [comment]
has the same problem;

using conda install -c pytorch pytorch-caffe2-cuda9.0-cudnn7

**Comment by abx67** [comment]
@hq-liu Thanks for your solution. I met the same issue with you. 
Add 'from caffe2.python.helpers import db_input' in model_helper.py and the bug fix. And comes out another error:

`
No handlers could be found for logger "caffe2.python.workspace"
Traceback (most recent call last):
  File "trainingSet/lmdb_create_example.py", line 139, in <module>
    main()
  File "trainingSet/lmdb_create_example.py", line 136, in main
    read_db_with_caffe2(output_db, checksum)
  File "trainingSet/lmdb_create_example.py", line 113, in read_db_with_caffe2
    workspace.RunNetOnce(model.param_init_net)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 236, in RunNetOnce
    StringifyProto(net),
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 215, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at db.h:196] db_. Cannot find db implementation of type lmdb (while trying to open /work/caffe2_cpp/trainingSet/db)
Error from operator: 
output: "dbreader_/work/caffe2_cpp/trainingSet/db" name: "" type: "CreateDB" arg { name: "db_type" s: "lmdb" } arg { name: "db" s: "/work/caffe2_cpp/trainingSet/db" }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x78 (0x7faf9fabb158 in /usr/local/lib/libc10.so)
frame #1: <unknown function> + 0x25f179b (0x7faf5e9b679b in /usr/local/lib/libtorch.so)
frame #2: <unknown function> + 0x23f0615 (0x7faf5e7b5615 in /usr/local/lib/libtorch.so)
frame #3: caffe2::SimpleNet::Run() + 0x180 (0x7faf5e893a60 in /usr/local/lib/libtorch.so)
frame #4: caffe2::Workspace::RunNetOnce(caffe2::NetDef const&) + 0x46 (0x7faf5e8df4d6 in /usr/local/lib/libtorch.so)
frame #5: <unknown function> + 0x54948 (0x7fafa020c948 in /usr/local/lib/python2.7/dist-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
frame #6: <unknown function> + 0x54ad7 (0x7fafa020cad7 in /usr/local/lib/python2.7/dist-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
frame #7: <unknown function> + 0x99d1d (0x7fafa0251d1d in /usr/local/lib/python2.7/dist-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
<omitting python frames>
frame #23: __libc_start_main + 0xe7 (0x7fafa3beab97 in /lib/x86_64-linux-gnu/libc.so.6)
`

**Comment by abx67** [comment]
I solved my problem, by switch db flag in CMakeLists.txt:
`
line 107: option(USE_LEVELDB "Use LEVELDB" ON)
line 109: option(USE_LMDB "Use LMDB" ON)
`
then recompile pytorch.

**Comment by hq-liu** [comment]
您的邮件已经收到，谢谢
