### ISSUE TITLE
Error when using torch.fx on bert

### ISSUE THREAD

**Issue by lethean1** [pytorch/pytorch#67970]
I am trying to use symbolic_trace on bert model and getting this error:
```
Traceback (most recent call last):
File "/workspace/fuse/hugging_face_competiton/train.py", line 196, in <module>
    model = fusion.fuse(model)
  File "/workspace/fuse/hugging_face_competiton/fusion.py", line 72, in fuse
    fx_model = fx.symbolic_trace(model)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/fx/symbolic_trace.py", line 858, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/fx/symbolic_trace.py", line 570, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/root/miniconda3/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 941, in forward
    raise ValueError("You cannot specify both input_ids and inputs_embeds at the same time")
ValueError: You cannot specify both input_ids and inputs_embeds at the same time
```
## Model
```
    configuration = BertConfig(hidden_size=args.hidden_size, num_hidden_layers=args.num_hidden_layers,
                               num_attention_heads=args.num_attention_heads, intermediate_size=4 * args.hidden_size)
    model = BertModel(configuration).cuda()
    model.eval()
    fused_model = fusion.fuse(model)
```
I wonder why inputs_embeds are specified.
And any help on how to run this correctly is appreciated. Thanks

**Comment by byronyi** [comment]
Use transformers.utils.fx.symbolic_trace instead.

**Comment by BowenBao** [comment]
Updating on this, when trying torch.fx on bert, with both latest pytorch and transformers built from source, I'm observing
```
  File "/home/bowbao/transformers/src/transformers/models/bert/modeling_bert.py", line 987, in forward
    buffered_token_type_ids = self.embeddings.token_type_ids[:, :seq_length]
TypeError: slice indices must be integers or None or have an __index__ method
```
Repro script:
```python
from transformers import BertForSequenceClassification, BertTokenizer

device = "cuda"
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
text_batch = ["Hello, my dog is cute"]
encoding = tokenizer(text_batch, return_tensors="pt", padding=True, truncation=True)
input_ids = encoding["input_ids"].to(device)
attention_mask = encoding["attention_mask"].to(device)
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", return_dict=False).to(device)

args = (input_ids, attention_mask)

concrete_args = {
    'token_type_ids': None,
    'position_ids': None,
    'head_mask': None,
    'inputs_embeds': None,
    'labels': None,
    'output_attentions': None,
    'output_hidden_states': None,
    'return_dict': None,
}

out = model(*args, **concrete_args)
print("pass forward")

from torch import fx
# Fail with TypeError: slice indices must be integers or None or have an __index__ method
gm = fx.symbolic_trace(model, concrete_args=concrete_args)
```

@byronyi 's suggestion works perfectly, I can successfully symbolic trace using `transformers.utils.fx.symbolic_trace`. However I feel there shouldn't be anything special with this model that stock fx symbolic trace cannot handle right? @ezyang

```
torch                         1.13.0a0+git0ca0ab1
transformers                  4.22.0.dev0
```

**Comment by ezyang** [comment]
If you import this monkey patch https://gist.github.com/zdevito/6832c1a149a06c79f0c4efe15fb4185c does it work?

**Comment by absudabsu** [comment]
Hi, I believe the issue is more general

```
import torch 
model = torch.nn.TransformerEncoderLayer(d_model=512, nhead=8, dim_feedforward=2048, dropout=0.1, layer_norm_eps=1e-05, batch_first=False, norm_first=False, bias=True, device=None, dtype=None)

graph_module = torch.fx.symbolic_trace(model)
```

results in the error:
```
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 graph_module = torch.fx.symbolic_trace(model)

File .venv/lib/python3.12/site-packages/torch/fx/_symbolic_trace.py:1314, in symbolic_trace(root, concrete_args)
   1264 """
   1265 Symbolic tracing API
   1266 
   (...)   1311     GraphModule: a Module created from the recorded operations from ``root``.
   1312 """
   1313 tracer = Tracer()
-> 1314 graph = tracer.trace(root, concrete_args)
   1315 name = (
   1316     root.__class__.__name__ if isinstance(root, torch.nn.Module) else root.__name__
   1317 )
   1318 return _make_graph_module(tracer.root, graph, name)

File .venv/lib/python3.12/site-packages/torch/fx/_symbolic_trace.py:838, in Tracer.trace(self, root, concrete_args)
    831         for module in self._autowrap_search:
    832             _autowrap_check(
    833                 patcher, module.__dict__, self._autowrap_function_ids
    834             )
    835         self.create_node(
    836             "output",
    837             "output",
--> 838             (self.create_arg(fn(*args)),),
    839             {},
    840             type_expr=fn.__annotations__.get("return", None),
    841         )
    843     self.submodule_paths = None
    844 except RuntimeError as e:

File .venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py:787, in TransformerEncoderLayer.forward(self, src, src_mask, src_key_padding_mask, is_causal)
    760 def forward(
    761     self,
    762     src: Tensor,
   (...)    765     is_causal: bool = False,
    766 ) -> Tensor:
    767     r"""Pass the input through the encoder layer.
    768 
    769     Args:
   (...)    782         see the docs in :class:`~torch.nn.Transformer`.
    783     """
    784     src_key_padding_mask = F._canonical_mask(
    785         mask=src_key_padding_mask,
    786         mask_name="src_key_padding_mask",
--> 787         other_type=F._none_or_dtype(src_mask),
    788         other_name="src_mask",
    789         target_type=src.dtype,
    790     )
    792     src_mask = F._canonical_mask(
    793         mask=src_mask,
    794         mask_name="src_mask",
   (...)    798         check_other=False,
    799     )
    801     is_fastpath_enabled = torch.backends.mha.get_fastpath_enabled()

File .venv/lib/python3.12/site-packages/torch/nn/functional.py:5978, in _none_or_dtype(input)
   5976 elif isinstance(input, torch.Tensor):
   5977     return input.dtype
-> 5978 raise RuntimeError("input to _none_or_dtype() must be None or torch.Tensor")

RuntimeError: input to _none_or_dtype() must be None or torch.Tensor
```

I understand the error (mostly) is due to `Proxy` being used to create the symbolic trace, but its not clear what a suitable workaround is. Any suggestions?
