### ISSUE TITLE
error: use of undeclared identifier 'FaultyTensorPipeRpcBackendOptions'

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#68002]
## 🐛 Bug

I'm trying to compile PyTorch 1.10.0 with `USE_DISTRIBUTED=ON` on macOS 10.15.7 with Python 3.8.12 and Apple Clang 12.0.0 and compilation fails with the following error message.

## To Reproduce

```console
$ export USE_DISTRIBUTED=ON
$ python setup.py install
...
FAILED: caffe2/torch/CMakeFiles/torch_python.dir/csrc/distributed/rpc/testing/init.cpp.o
...
/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-torch-1.10.0-247rofhd7emnipb2gkoxzfl3u5orrfoa/spack-src/torch/csrc/distributed/rpc/testing/init.cpp:37:21: error: use of undeclared identifier 'FaultyTensorPipeRpcBackendOptions'
  shared_ptr_class_<FaultyTensorPipeRpcBackendOptions>(
                    ^
/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-torch-1.10.0-247rofhd7emnipb2gkoxzfl3u5orrfoa/spack-src/torch/csrc/distributed/rpc/testing/init.cpp:66:21: error: use of undeclared identifier 'FaultyTensorPipeAgent'
  shared_ptr_class_<FaultyTensorPipeAgent>(
                    ^
```

## Expected behavior

PyTorch Lightning seems to require PyTorch to be built with distributed support, so I would expect this to build, even on macOS.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0
 - OS (e.g., Linux): macOS
 - How you installed PyTorch (`conda`, `pip`, source): `spack`
 - Build command you used (if compiling from source): `spack install py-torch+distributed`
 - Python version: 3.8.12
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

## Additional context

Full build log and env:

* [build log](https://github.com/pytorch/pytorch/files/7498342/spack-build-out.txt)
* [build env](https://github.com/pytorch/pytorch/files/7498343/spack-build-env-mods.txt)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd

**Comment by mrshenli** [comment]
cc @H-Huang

**Comment by H-Huang** [comment]
Hi @adamjstewart, thank you for raising the issue. This is indeed a bug.

By default MacOS has `USE_TENSORPIPE=OFF` which is causing the classes to not be found. #68080 will correct this so that the classes are ignored. As a workaround you can manually set the environment variable to `USE_TENSORPIPE=ON` along with your current `USE_DISTRIBUTED=ON`. We will fix this ASAP so you do not need to manually set `USE_TENSORPIPE`.

**Comment by adamjstewart** [comment]
@H-Huang I used your patch and PyTorch with `USE_DISTRIBUTED=ON` builds successfully, but when I try to build torchvision it crashes with:
```
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    import torch
  File "/Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/apple-clang-12.0.0/py-torch-1.10.0-ik4jqx2ofri3jwuz2ysb3omdlhwwwefo/lib/python3.8/site-packages/torch/__init__.py", line 643, in <module>
    from .functional import *  # noqa: F403
  File "/Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/apple-clang-12.0.0/py-torch-1.10.0-ik4jqx2ofri3jwuz2ysb3omdlhwwwefo/lib/python3.8/site-packages/torch/functional.py", line 6, in <module>
    import torch.nn.functional as F
  File "/Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/apple-clang-12.0.0/py-torch-1.10.0-ik4jqx2ofri3jwuz2ysb3omdlhwwwefo/lib/python3.8/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/apple-clang-12.0.0/py-torch-1.10.0-ik4jqx2ofri3jwuz2ysb3omdlhwwwefo/lib/python3.8/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/apple-clang-12.0.0/py-torch-1.10.0-ik4jqx2ofri3jwuz2ysb3omdlhwwwefo/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 6, in <module>
    from .. import functional as F
  File "/Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/apple-clang-12.0.0/py-torch-1.10.0-ik4jqx2ofri3jwuz2ysb3omdlhwwwefo/lib/python3.8/site-packages/torch/nn/functional.py", line 11, in <module>
    from .._jit_internal import boolean_dispatch, _overload, BroadcastingList1, BroadcastingList2, BroadcastingList3
  File "/Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/apple-clang-12.0.0/py-torch-1.10.0-ik4jqx2ofri3jwuz2ysb3omdlhwwwefo/lib/python3.8/site-packages/torch/_jit_internal.py", line 24, in <module>
    import torch.distributed.rpc
  File "/Users/Adam/spack/opt/spack/darwin-catalina-ivybridge/apple-clang-12.0.0/py-torch-1.10.0-ik4jqx2ofri3jwuz2ysb3omdlhwwwefo/lib/python3.8/site-packages/torch/distributed/rpc/__init__.py", line 27, in <module>
    from torch._C._distributed_rpc import (
ImportError: cannot import name '_TensorPipeRpcBackendOptionsBase' from 'torch._C._distributed_rpc' (unknown location)
```
Here are the relevant logs:

* [build log](https://github.com/pytorch/pytorch/files/7551020/spack-build-out.txt)
* [build env](https://github.com/pytorch/pytorch/files/7551021/spack-build-env-mods.txt)

Any idea what could be causing this? Does `USE_DISTRIBUTED` require at least one of MPI/gloo/tensorpipe in order to work properly?

**Comment by DhruvKoolRajamani** [comment]
Any updates on this? I'm seeing the same issue after compiling on Linux.

**Comment by frobnitzem** [comment]
I am experiencing the same issue.  I compiled using distributed, but disabled gloo, fbgemm and nccl.
