### ISSUE TITLE
Instance of Device 2 Device transfer non-differentiable

### ISSUE THREAD

**Issue by csarofeen** [pytorch/pytorch#6813]
```.py
import torch
from torch.autograd import Variable

input = Variable(torch.randn(1).cuda(0), requires_grad = True)
output = input.cuda(1) + input.cuda(1)
output.sum().backward()
```

is producing the following error:

```Traceback (most recent call last):
  File "tmp.py", line 6, in <module>
    output.sum().backward()
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: arguments are located on different GPUs at /opt/pytorch/pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:233
```

however, the following runs fine

```.py
import torch
from torch.autograd import Variable

input = Variable(torch.randn(1).cuda(0), requires_grad = True)
input = input.cuda(1)
output = input + input
output.sum().backward()
```

**Comment by gchanan** [comment]
I'm taking a look.
