### ISSUE TITLE
DISABLED test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#68222]
Platforms: rocm

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/4942//console

```
22:20:08 ----------------------------------------------------------------------
22:20:08 Test results will be stored in test-reports/dist-gloo/distributed.test_distributed_spawn
22:20:08   test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn) ... [W Module.cpp:494] Warning: Disabling benchmark mode for MIOpen is NOT supported. Overriding value to True (function operator())
22:20:20 munmap_chunk(): invalid pointer
22:20:20 SIGABRT(6), PID: 17317, Thread 17317: 
22:20:20  frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x82 (0x7f55e78274e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
22:20:20 frame #1: c10::FatalSignalHandler::fatalSignalHandler(int) + 0x152 (0x7f55e78278c2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
22:20:20 frame #2: <unknown function> + 0x12980 (0x7f5627967980 in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #3: gsignal + 0xc7 (0x7f56275a2fb7 in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 frame #4: abort + 0x141 (0x7f56275a4921 in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 frame #5: <unknown function> + 0x89967 (0x7f56275ed967 in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 frame #6: <unknown function> + 0x909da (0x7f56275f49da in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 frame #7: cfree + 0x58c (0x7f56275fbfbc in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 frame #8: <unknown function> + 0x5159ec5 (0x7f5619d1eec5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
22:20:20 frame #9: <unknown function> + 0x514aa79 (0x7f5619d0fa79 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
22:20:20 frame #10: <unknown function> + 0x514aa89 (0x7f5619d0fa89 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
22:20:20 frame #11: <unknown function> + 0x51514b8 (0x7f5619d164b8 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
22:20:20 frame #12: <unknown function> + 0x51393b2 (0x7f5619cfe3b2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
22:20:20 frame #13: torch::autograd::profiler::disableProfiler() + 0x2d7 (0x7f5617bd2347 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
22:20:20 frame #14: <unknown function> + 0xc20027 (0x7f561ee37027 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
22:20:20 frame #15: <unknown function> + 0x8a3baf (0x7f561eababaf in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
22:20:20 frame #16: <unknown function> + 0x18327c (0x56210da8127c in /opt/conda/bin/python3.6)
22:20:20 frame #17: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)
22:20:20 frame #18: <unknown function> + 0x16cec4 (0x56210da6aec4 in /opt/conda/bin/python3.6)
22:20:20 frame #19: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)
22:20:20 frame #20: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)
22:20:20 frame #21: <unknown function> + 0x16cec4 (0x56210da6aec4 in /opt/conda/bin/python3.6)
22:20:20 frame #22: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)
22:20:20 frame #23: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)
22:20:20 frame #24: <unknown function> + 0x16cec4 (0x56210da6aec4 in /opt/conda/bin/python3.6)
22:20:20 frame #25: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)
22:20:20 frame #26: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)
22:20:20 frame #27: <unknown function> + 0x16cec4 (0x56210da6aec4 in /opt/conda/bin/python3.6)
22:20:20 frame #28: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)
22:20:20 frame #29: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)
22:20:20 frame #30: <unknown function> + 0x173044 (0x56210da71044 in /opt/conda/bin/python3.6)
22:20:20 frame #31: _PyObject_FastCallDict + 0x17c (0x56210da2f28c in /opt/conda/bin/python3.6)
22:20:20 frame #32: PyObject_CallFunctionObjArgs + 0xec (0x56210da38bcc in /opt/conda/bin/python3.6)
22:20:20 frame #33: _PyEval_EvalFrameDefault + 0x1b6e (0x56210da9fb5e in /opt/conda/bin/python3.6)
22:20:20 frame #34: <unknown function> + 0x130160 (0x56210da2e160 in /opt/conda/bin/python3.6)
22:20:20 frame #35: <unknown function> + 0x16d41b (0x56210da6b41b in /opt/conda/bin/python3.6)
22:20:20 frame #36: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)
22:20:20 frame #37: _PyEval_EvalFrameDefault + 0x1a2e (0x56210da9fa1e in /opt/conda/bin/python3.6)
22:20:20 frame #38: <unknown function> + 0x130160 (0x56210da2e160 in /opt/conda/bin/python3.6)
22:20:20 frame #39: <unknown function> + 0x172a4b (0x56210da70a4b in /opt/conda/bin/python3.6)
22:20:20 frame #40: PyObject_Call + 0x3e (0x56210da309fe in /opt/conda/bin/python3.6)
22:20:20 frame #41: _PyEval_EvalFrameDefault + 0x4b87 (0x56210daa2b77 in /opt/conda/bin/python3.6)
22:20:20 frame #42: <unknown function> + 0x130994 (0x56210da2e994 in /opt/conda/bin/python3.6)
22:20:20 frame #43: <unknown function> + 0x172a4b (0x56210da70a4b in /opt/conda/bin/python3.6)
22:20:20 frame #44: PyObject_Call + 0x3e (0x56210da309fe in /opt/conda/bin/python3.6)
22:20:20 frame #45: _PyEval_EvalFrameDefault + 0x4b87 (0x56210daa2b77 in /opt/conda/bin/python3.6)
22:20:20 frame #46: <unknown function> + 0x130994 (0x56210da2e994 in /opt/conda/bin/python3.6)
22:20:20 frame #47: <unknown function> + 0x172a4b (0x56210da70a4b in /opt/conda/bin/python3.6)
22:20:20 frame #48: PyObject_Call + 0x3e (0x56210da309fe in /opt/conda/bin/python3.6)
22:20:20 frame #49: _PyEval_EvalFrameDefault + 0x4b87 (0x56210daa2b77 in /opt/conda/bin/python3.6)
22:20:20 frame #50: <unknown function> + 0x130994 (0x56210da2e994 in /opt/conda/bin/python3.6)
22:20:20 frame #51: <unknown function> + 0x16d41b (0x56210da6b41b in /opt/conda/bin/python3.6)
22:20:20 frame #52: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)
22:20:20 frame #53: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)
22:20:20 frame #54: <unknown function> + 0x130994 (0x56210da2e994 in /opt/conda/bin/python3.6)
22:20:20 frame #55: <unknown function> + 0x16d41b (0x56210da6b41b in /opt/conda/bin/python3.6)
22:20:20 frame #56: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)
22:20:20 frame #57: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)
22:20:20 frame #58: <unknown function> + 0x130160 (0x56210da2e160 in /opt/conda/bin/python3.6)
22:20:20 frame #59: <unknown function> + 0x16d41b (0x56210da6b41b in /opt/conda/bin/python3.6)
22:20:20 frame #60: <unknown function> + 0x1830f7 (0x56210da810f7 in /opt/conda/bin/python3.6)
22:20:20 frame #61: _PyEval_EvalFrameDefault + 0x3af (0x56210da9e39f in /opt/conda/bin/python3.6)
22:20:20 frame #62: <unknown function> + 0x173044 (0x56210da71044 in /opt/conda/bin/python3.6)
22:20:20 frame #63: PyObject_Call + 0x3e (0x56210da309fe in /opt/conda/bin/python3.6)
22:20:20 
22:20:20 SIGABRT(6), PID: 17317, Thread 17494: 
22:20:20  frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x82 (0x7f55e78274e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
22:20:20 frame #1: <unknown function> + 0x12980 (0x7f5627967980 in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #2: ioctl + 0x7 (0x7f562767a317 in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 frame #3: <unknown function> + 0xbb18 (0x7f55ba42db18 in /opt/rocm/hip/lib/../../lib/libhsakmt.so.1)
22:20:20 frame #4: hsaKmtWaitOnMultipleEvents + 0xfa (0x7f55ba427d7a in /opt/rocm/hip/lib/../../lib/libhsakmt.so.1)
22:20:20 frame #5: <unknown function> + 0x76185 (0x7f55ca305185 in /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1)
22:20:20 frame #6: <unknown function> + 0x57c4e (0x7f55ca2e6c4e in /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1)
22:20:20 frame #7: <unknown function> + 0x6e502 (0x7f55ca2fd502 in /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1)
22:20:20 frame #8: <unknown function> + 0x16497 (0x7f55ca2a5497 in /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1)
22:20:20 frame #9: <unknown function> + 0x76db (0x7f562795c6db in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #10: clone + 0x3f (0x7f562768571f in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 
22:20:20 SIGABRT(6), PID: 17317, Thread 17497: 
22:20:20  frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x82 (0x7f55e78274e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
22:20:20 frame #1: <unknown function> + 0x12980 (0x7f5627967980 in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #2: epoll_wait + 0x57 (0x7f5627685a47 in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 frame #3: gloo::transport::tcp::Loop::run() + 0x62 (0x7f5619b991e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
22:20:20 frame #4: <unknown function> + 0xc9039 (0x7f55e773f039 in /opt/conda/lib/libstdc++.so.6)
22:20:20 frame #5: <unknown function> + 0x76db (0x7f562795c6db in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #6: clone + 0x3f (0x7f562768571f in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 
22:20:20 SIGABRT(6), PID: 17317, Thread 17503: 
22:20:20  frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x82 (0x7f55e78274e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
22:20:20 frame #1: <unknown function> + 0x12980 (0x7f5627967980 in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #2: pthread_cond_wait + 0x243 (0x7f5627962ad3 in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #3: std::condition_variable::wait(std::unique_lock<std::mutex>&) + 0x9 (0x7f55e773b399 in /opt/conda/lib/libstdc++.so.6)
22:20:20 frame #4: c10d::ProcessGroupGloo::runLoop(int) + 0x211 (0x7f56183812b1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
22:20:20 frame #5: <unknown function> + 0xc9039 (0x7f55e773f039 in /opt/conda/lib/libstdc++.so.6)
22:20:20 frame #6: <unknown function> + 0x76db (0x7f562795c6db in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #7: clone + 0x3f (0x7f562768571f in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 
22:20:20 SIGABRT(6), PID: 17317, Thread 17504: 
22:20:20  frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x82 (0x7f55e78274e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
22:20:20 frame #1: <unknown function> + 0x12980 (0x7f5627967980 in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #2: pthread_cond_wait + 0x243 (0x7f5627962ad3 in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #3: std::condition_variable::wait(std::unique_lock<std::mutex>&) + 0x9 (0x7f55e773b399 in /opt/conda/lib/libstdc++.so.6)
22:20:20 frame #4: c10d::ProcessGroupGloo::runLoop(int) + 0x211 (0x7f56183812b1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
22:20:20 frame #5: <unknown function> + 0xc9039 (0x7f55e773f039 in /opt/conda/lib/libstdc++.so.6)
22:20:20 frame #6: <unknown function> + 0x76db (0x7f562795c6db in /lib/x86_64-linux-gnu/libpthread.so.0)
22:20:20 frame #7: clone + 0x3f (0x7f562768571f in /lib/x86_64-linux-gnu/libc.so.6)
22:20:20 
22:21:20 ERROR:torch.testing._internal.common_distributed:Caught exception: 
22:21:20 Traceback (most recent call last):
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 575, in run_test
22:21:20     getattr(self, test_name)()
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 459, in wrapper
22:21:20     fn()
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 112, in wrapper
22:21:20     return func(*args, **kwargs)
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2994, in wrapper
22:21:20     return func(*args, **kwargs)
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2994, in wrapper
22:21:20     return func(*args, **kwargs)
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 5710, in test_ddp_profiling_torch_profiler
22:21:20     self._test_ddp_profiling(profiler_ctx=torch_profiler_ctx)
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 5671, in _test_ddp_profiling
22:21:20     find_unused_parameters=True,
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 601, in __init__
22:21:20     dist._verify_params_across_processes(self.process_group, parameters)
22:21:20 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:133] Timed out waiting 60000ms for send operation to complete
22:21:20  exiting process 0 with exit code: 10
22:21:20 ERROR:torch.testing._internal.common_distributed:Caught exception: 
22:21:20 Traceback (most recent call last):
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 575, in run_test
22:21:20     getattr(self, test_name)()
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 459, in wrapper
22:21:20     fn()
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 112, in wrapper
22:21:20     return func(*args, **kwargs)
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2994, in wrapper
22:21:20     return func(*args, **kwargs)
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2994, in wrapper
22:21:20     return func(*args, **kwargs)
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 5710, in test_ddp_profiling_torch_profiler
22:21:20     self._test_ddp_profiling(profiler_ctx=torch_profiler_ctx)
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 5671, in _test_ddp_profiling
22:21:20     find_unused_parameters=True,
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 603, in __init__
22:21:20     self._sync_params_and_buffers(authoritative_rank=0)
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 625, in _sync_params_and_buffers
22:21:20     module_states, self.broadcast_bucket_size, authoritative_rank
22:21:20   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 1420, in _distributed_broadcast_coalesced
22:21:20     self.process_group, tensors, buffer_size, authoritative_rank
22:21:20 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 60000ms for recv operation to complete
22:21:20  exiting process 1 with exit code: 10
22:21:22 Process 0 terminated with exit code 10, terminating remaining processes.
22:21:22 ERROR (74.079s)
22:21:22 
22:21:22 ======================================================================
22:21:22 ERROR [74.079s]: test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn)
22:21:22 ----------------------------------------------------------------------
22:21:22 Traceback (most recent call last):
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 457, in wrapper
22:21:22     self._join_processes(fn)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 676, in _join_processes
22:21:22     self._check_return_codes(elapsed_time)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 721, in _check_return_codes
22:21:22     raise RuntimeError(error)
22:21:22 RuntimeError: Process 0 exited with error code 10 and exception:
22:21:22 Traceback (most recent call last):
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 575, in run_test
22:21:22     getattr(self, test_name)()
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 459, in wrapper
22:21:22     fn()
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 112, in wrapper
22:21:22     return func(*args, **kwargs)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2994, in wrapper
22:21:22     return func(*args, **kwargs)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2994, in wrapper
22:21:22     return func(*args, **kwargs)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 5710, in test_ddp_profiling_torch_profiler
22:21:22     self._test_ddp_profiling(profiler_ctx=torch_profiler_ctx)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 5671, in _test_ddp_profiling
22:21:22     find_unused_parameters=True,
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 601, in __init__
22:21:22     dist._verify_params_across_processes(self.process_group, parameters)
22:21:22 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:133] Timed out waiting 60000ms for send operation to complete
22:21:22 
22:21:22 Process 1 exited with error code 10 and exception:
22:21:22 Traceback (most recent call last):
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 575, in run_test
22:21:22     getattr(self, test_name)()
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 459, in wrapper
22:21:22     fn()
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 112, in wrapper
22:21:22     return func(*args, **kwargs)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2994, in wrapper
22:21:22     return func(*args, **kwargs)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2994, in wrapper
22:21:22     return func(*args, **kwargs)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 5710, in test_ddp_profiling_torch_profiler
22:21:22     self._test_ddp_profiling(profiler_ctx=torch_profiler_ctx)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 5671, in _test_ddp_profiling
22:21:22     find_unused_parameters=True,
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 603, in __init__
22:21:22     self._sync_params_and_buffers(authoritative_rank=0)
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 625, in _sync_params_and_buffers
22:21:22     module_states, self.broadcast_bucket_size, authoritative_rank
22:21:22   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 1420, in _distributed_broadcast_coalesced
22:21:22     self.process_group, tensors, buffer_size, authoritative_rank
22:21:22 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 60000ms for recv operation to complete
22:21:22 
22:21:22 
22:21:22 
22:21:23 ----------------------------------------------------------------------
22:21:23 Ran 1 test in 74.080s
22:21:23 
22:21:23 FAILED (errors=1)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by malfet** [comment]
Hmm, it's already supposed to be disabled by https://github.com/pytorch/pytorch/issues/68189 but it does not seem to work correctly, let's add an old fashioned skip here

**Comment by mruberry** [comment]
> Hmm, it's already supposed to be disabled by #68189 but it does not seem to work correctly, let's add an old fashioned skip here

That's worrying! cc @janeyx99

**Comment by jaglinux** [comment]
Works fine on ROCm 5.2 when run in loop.
Need to close this issue to test https://github.com/pytorch/pytorch/pull/82749
