### ISSUE TITLE
[Runtime Error in ddp_pipeline.py] RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.

### ISSUE THREAD

**Issue by heathersherry** [pytorch/pytorch#68407]
## 🐛 Bug

When following the [PyTorch tutorial (Training Transformer models using Distributed Data Parallel and Pipeline Parallelism)](https://github.com/pytorch/tutorials/blob/master/advanced_source/ddp_pipeline.py), there is a Runtime Error.
```
RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.
```
The full error message is as follows.
```
(base) root@xxx:/xxx# python ddp_pipeline.py
[RANK 1]: Total parameters in model: 1,041,444,974
[RANK 0]: Total parameters in model: 1,041,444,974
Traceback (most recent call last):
  File "xxx.py", line 452, in <module>
    mp.spawn(run_worker, args=(world_size, ), nprocs=world_size, join=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/xxx/xxx/ddp_pipeline.py", line 419, in run_worker
    train()
  File "/xxx/xxx/ddp_pipeline.py", line 370, in train
    output = model(data).local_value()
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 878, in forward
    self._sync_params()
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1382, in _sync_params
    authoritative_rank,
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1335, in _distributed_broadcast_coalesced
    self.process_group, tensors, buffer_size, authoritative_rank
RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.
```

## To Reproduce

1. Execute [ddp_pipeline.py](https://github.com/pytorch/tutorials/blob/master/advanced_source/ddp_pipeline.py)

## Expected behavior

The code runs and doesn't crash.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0+cu102
 - OS (e.g., Linux): Ubuntu 18.04.6 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): python ddp_pipeline.py
 - Python version: 3.7.4
 - CUDA/cuDNN version: 10.1.243
 - GPU models and configuration: Tesla V100-PCIE-32GB (*8)

**Comment by jhoareau** [comment]
Hi, I am experiencing the same error in our Transformer-based model. Everything works fine with Pytorch 1.9.1 but I am encountering the same error in 1.10.0.

**Comment by FLYING37520** [comment]
i meet this problem too , but i don't know how to solve it

**Comment by jhoareau** [comment]
Hi @VitalyFedyunin if it's been triaged could we have some more information on either a possible workaround, or if a fix is in the pipeline from the PyTorch team? This is a blocker for us to upgrade to Pytorch 1.10 and the error is a bit too low-level within DDP for me to understand how to work around it.

**Comment by jhoareau** [comment]
Digging in the code in `nn/parallel/distributed.py`, I could see the issue comes from the PositionalEmbedding buffer `self.register_buffer('pe', pe)`. If this buffer is removed (or replaced by a parameter with gradient), then the sample code runs fine. I still don't understand why it works in PyTorch 1.9.1 with buffers though, while it does not work in 1.10.

**Comment by jhoareau** [comment]
Maybe @rohan-varma can have a look?

**Comment by Yuki-Nagato** [comment]
> If this buffer is removed (or replaced by a parameter without gradient), then the sample code runs fine. I can only assume it's not working anymore being related to this PR: #64776
> 
> Workaround: replace the PositionaEncoding class with this class:
> 
> ```python
> class PositionalEncoding(nn.Module):
> 
>     def __init__(self, d_model, dropout=0.1, max_len=5000):
>         super(PositionalEncoding, self).__init__()
>         self.dropout = nn.Dropout(p=dropout)
> 
>         pe = torch.zeros(max_len, d_model)
>         position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
>         div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
>         pe[:, 0::2] = torch.sin(position * div_term)
>         pe[:, 1::2] = torch.cos(position * div_term)
>         pe = pe.unsqueeze(0).transpose(0, 1)
>         self.register_parameter('pe', nn.Parameter(pe, requires_grad=False))
> 
>     def forward(self, x):
>         x = x + self.pe[:x.size(0), :]
>         return self.dropout(x)
> ```

Same issue here. This workaround still does not solve the problem. Removing the PositionalEncoding module obviates the error.

Env: python 3.8.12, pytorch 1.10.1 (py3.8_cuda11.3_cudnn8.2.0_0), ubuntu 20.04 LTS.

**Comment by jhoareau** [comment]
@rohan-varma Do you have an update on this?

**Comment by deepsworld** [comment]
Facing similar issue with DDP training and `register_buffer` with pytorch:1.10 , python:3.9 in the conda envirnment. Workaround suggested by @jhoareau  seems to work for us.

**Comment by rohan-varma** [comment]
Sorry for the late follow up - I'll be able to have a close look at the end of this week or the week of 3/7.

@deepsworld, would you be able to help with a repro of your issue (especially if you are just using `register_buffer` + DDP and not Pipeline Parallelism)?

**Comment by deepsworld** [comment]
Hey @rohan-varma, please find the repro with DDP
```py
import os
import math

import torch
from torch import nn
import torch.distributed as dist

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, dropout=0.1, max_len=5000):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0).transpose(0, 1)
        self.register_buffer('pe', pe)
        # FIXME: workaround for DDP issue: https://github.com/pytorch/pytorch/issues/68407
        # self.register_parameter('pe', nn.Parameter(pe, requires_grad=False))

    def forward(self, x):
        x = x + self.pe[:x.size(0), :]
        return self.dropout(x)

class TestModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(16, 16)
        self.pos = PositionalEncoding(16)

    def forward(self, x):
        # x = (s, bs, dim)
        return self.linear(self.pos(x))

def run(dev):
    """ Distributed function to be implemented later. """
    model = TestModel()
    model.to(dev)
    model = nn.parallel.DistributedDataParallel(model, device_ids=[dev])
    inp = torch.rand(10, 2, 16, device=dev)
    out = model(inp)
    print(out.shape)
    
def setup_dist(cfg):
    if "WORLD_SIZE" in os.environ:
        cfg.world_size = int(os.environ["WORLD_SIZE"])
    cfg.dist = cfg.world_size > 1

    local_rank = int(os.environ.get("LOCAL_RANK", -1))

    if cfg.dist:
        if local_rank != -1: # for torch.distributed.launch
            cfg.rank = local_rank
            cfg.gpu = local_rank
        elif 'SLURM_PROCID' in os.environ: # for slurm scheduler
            cfg.rank = int(os.environ['SLURM_PROCID'])
            cfg.gpu = cfg.rank % torch.cuda.device_count()

        # init dist
        dist.init_process_group(backend=cfg.dist_backend, init_method=cfg.dist_url,
                                world_size=cfg.world_size, rank=cfg.rank)
        # set gpu device
        torch.cuda.set_device(cfg.gpu)
    else:
        raise NotImplementedError('Only DDP training supported')

def init_processes(fn, backend='nccl'):
    """ Initialize the distributed environment. """
    world_size = int(os.environ["WORLD_SIZE"])
    rank = int(os.environ["LOCAL_RANK"])
    gpu = rank % torch.cuda.device_count()
    dist.init_process_group(backend, init_method='env://', rank=rank, world_size=world_size)
    torch.cuda.set_device(gpu)
    fn(gpu)

if __name__ == "__main__":
    init_processes(run)
```

**Comment by zhaojuanmao** [comment]
maybe related to #66504

**Comment by rohan-varma** [comment]
@zhaojuanmao Might be different and might be due to a bad diff that landed a while ago - I'll take a look soon.

**Comment by jhoareau** [comment]
This is still happening in Pytorch 1.11 by the way, I reproduced it again.

**Comment by ksapiej** [comment]
still happening in Pytorch 1.12.0 ...

**Comment by jhoareau** [comment]
@rohan-varma any updates here? :)

**Comment by shaibagon** [comment]
Maybe related to this issue.
PyTorch version 1.13 and also 2.0
CUDA version 11.7 and also 11.8
NCCL version 2.14.3+cuda11.8 (I don't have the nccl version for the cuda 11.7 environment).

Having a `register_buffer` in my `nn.Module` (small buffer with 8 elements) results with NCCL timeout:
```
[E ProcessGroupNCCL.cpp:828] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=18, OpType=BROADCAST, Timeout(ms)=5400000) ran for 5406374 milliseconds before timing out.
Traceback (most recent call last):
  File "/home/.../train.py", line 525, in <module>
    train(args)
[...]
  File "/home/.../lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Trying to create tensor with negative dimension -1101811590: [-1101811590]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 77894 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 77895) of binary: /home/.../bin/python
Traceback (most recent call last):
  File "/home/.../bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/.../lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/.../lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/.../lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/.../lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/.../lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

Note that the NCCL timeout triggered the `RuntimeError: Trying to create tensor with negative dimension -1101811590: [-1101811590]`.

The behavior I see:  
1. Running code on a single GPU - everything is perfect.  
2. Running on 2 GPUs without `register_buffer` - everything is perfect.  
3. Running on 2 GPUs with `register_buffer` (the code does not use the buffer, it's just there) - code runs for one iteration than "hangs". GPU utilization is high, but nothing actually happens. The second iteration is not being executed. After the predefined timeout limit, NCCL throws the `Watchdog caught collective operation timeout`. Sometimes the `RuntimeError` is also displayed, but not always.
4. Replacing the buffer with `nn.Parameter` works.

It seems like there's an NCCL sync issue with registered buffers.

**Comment by boyuaner** [comment]
torch 1.13.1 still have this issue...

**Comment by Frank-ZY-Dou** [comment]
hi Guys~ Studied the code of FAIR, and found a solution:
```

class PositionalEncoding(nn.Module):
    """Positional encoding.

    Args:
        d_model: Embedding dimension.
        dropout_rate: Dropout rate.
        max_len: Maximum input length.
        reverse: Whether to reverse the input position.
    """

    def __init__(self, d_model, dropout_rate, max_len=5000, reverse=False):
        """Construct an PositionalEncoding object."""
        super(PositionalEncoding, self).__init__()
        self.d_model = d_model
        self.reverse = reverse
        self.xscale = math.sqrt(self.d_model)
        self.dropout = nn.Dropout(p=dropout_rate)
        self.pe = None
        self.extend_pe(torch.tensor(0.0).expand(1, max_len))

    def extend_pe(self, x):
        """Reset the positional encodings."""
        if self.pe is not None:
            if self.pe.size(1) >= x.size(1):
                if self.pe.dtype != x.dtype or self.pe.device != x.device:
                    self.pe = self.pe.to(dtype=x.dtype, device=x.device)
                return
        pe = torch.zeros(x.size(1), self.d_model)
        if self.reverse:
            position = torch.arange(
                x.size(1) - 1, -1, -1.0, dtype=torch.float32
            ).unsqueeze(1)
        else:
            position = torch.arange(0, x.size(1), dtype=torch.float32).unsqueeze(1)
        div_term = torch.exp(
            torch.arange(0, self.d_model, 2, dtype=torch.float32)
            * -(math.log(10000.0) / self.d_model)
        )
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.pe = pe.to(device=x.device, dtype=x.dtype)

    def forward(self, x: torch.Tensor):
        """Add positional encoding.
        Args:
            x (torch.Tensor): Input tensor B X T X C
        Returns:
            torch.Tensor: Encoded tensor B X T X C
        """
        self.extend_pe(x)
        x = x * self.xscale + self.pe[:, : x.size(1)]
        return self.dropout(x)
```
