### ISSUE TITLE
DISABLED test_bottleneck_cpu_only (__main__.TestBottleneck)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#68433]
See https://github.com/pytorch/pytorch/runs/4221582535?check_suite_focus=true. Relevant snippet:

```

2021-11-16T10:05:58.7795940Z   test_bottleneck_cpu_only (__main__.TestBottleneck) ... FAIL (30.029s)
2021-11-16T10:06:18.9412500Z     test_bottleneck_cpu_only failed - num_retries_left: 3
2021-11-16T10:06:18.9413310Z   test_bottleneck_cpu_only (__main__.TestBottleneck) ... ok (20.162s)
2021-11-16T10:06:28.8624360Z     test_bottleneck_cpu_only succeeded - num_retries_left: 2
2021-11-16T10:06:28.8625230Z   test_bottleneck_cpu_only (__main__.TestBottleneck) ... ok (9.921s)
2021-11-16T10:06:38.7689690Z     test_bottleneck_cpu_only succeeded - num_retries_left: 1
2021-11-16T10:06:38.7691190Z   test_bottleneck_cpu_only (__main__.TestBottleneck) ... ok (9.906s)
2021-11-16T10:06:38.7702930Z     test_bottleneck_cpu_only succeeded - num_retries_left: 0

2021-11-16T10:08:17.3358120Z ======================================================================
2021-11-16T10:08:17.3358790Z FAIL [30.029s]: test_bottleneck_cpu_only (__main__.TestBottleneck)
2021-11-16T10:08:17.3360380Z ----------------------------------------------------------------------
2021-11-16T10:08:17.3360980Z Traceback (most recent call last):
2021-11-16T10:08:17.3361540Z   File "test_utils.py", line 498, in test_bottleneck_cpu_only
2021-11-16T10:08:17.3362630Z     self.assertEqual(rc, 0, msg='Run failed with\n{}'.format(err))
2021-11-16T10:08:17.3364030Z   File "/usr/local/miniconda/envs/build/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2065, in assertEqual
2021-11-16T10:08:17.3365000Z     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
2021-11-16T10:08:17.3366190Z AssertionError: False is not true : Scalars failed to compare as equal! -9 != 0
2021-11-16T10:08:17.3366770Z Run failed with
2021-11-16T10:08:17.3367010Z 
2021-11-16T10:08:17.3367210Z 
2021-11-16T10:08:17.3583350Z ----------------------------------------------------------------------
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @VitalyFedyunin @ngimel

**Comment by mruberry** [comment]
@mrshenli do you know the appropriate labels/owners for this test?

**Comment by mrshenli** [comment]
Maybe "module: cpu" and "module: performance"?

**Comment by ngimel** [comment]
"-9" exit code is oom

**Comment by malfet** [comment]
Who is the owner of test_bottleneck?

**Comment by malfet** [comment]
@mruberry to create an RFC to deprecate it
