### ISSUE TITLE
RuntimeError: size mismatch in matmul

### ISSUE THREAD

**Issue by monajalal** [pytorch/pytorch#6852]
I am using this git repo. I had no problem running it on CPU without F1 measure. Now that I want to run it on GPU with F1 measure I get this error:

Do you know how to fix the below error?

```
[jalal@goku AttentionTargetSentiment]$ python main.py -cuda -getF1 -which-model contextualized -which-embedding 200dt -device 0 

Loading data...
all 23095
notfound: 9849
ratio: 0.4264559428447716

Parameters:
	ATTENTION_SIZE=150
	BATCH_SIZE=16
	CLIP_NORM=None
	CUDA=True
	DEVICE=0
	DROPOUT_EMBED=0.2
	DROPOUT_RNN=0.4
	EMBED_DIM=200
	EMBED_NUM=23095
	EPOCHS=30
	GETF1=True
	GRAYSCALE=None
	HIDDEN_SIZE=150
	IF_RE=False
	LABEL_NUM=3
	LOG_INTERVAL=1
	LR=0.01
	LR_SCHEDULER=None
	MAX_NORM=None
	MESSAGE=tt
	NEED_SMALLEMBED=False
	SAVE_DIR=snapshot/tt
	SAVE_INTERVAL=100
	SHUFFLE=True
	SNAPSHOT=None
	TEST=False
	TEST_INTERVAL=100
	USE_EMBEDDING=True
	WEIGHT_DECAY=1e-06
	WHICH_DATA=Z
	WHICH_EMBEDDING=200dt
	WHICH_INIT=xavier
	WHICH_MODEL=contextualized
	WHICH_OPTIM=Adagrad
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    train.getF1(args, m_model, test_data.iterator, train_data.vocabulary_label)
  File "/scratch2/debate_tweets/sentiment/AttentionTargetSentiment/train.py", line 152, in getF1
    logit = model(feature, batch.target_start, batch.target_end)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch2/debate_tweets/sentiment/AttentionTargetSentiment/model/contextualized.py", line 90, in forward
    s = self.attention(x, average_target)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch2/debate_tweets/sentiment/AttentionTargetSentiment/model/attention.py", line 22, in forward
    m_combine = F.tanh(self.linear(m_combine))
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/functional.py", line 837, in linear
    output = input.matmul(weight.t())
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/autograd/variable.py", line 386, in matmul
    **return torch.matmul(self, other)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/functional.py", line 192, in matmul
    output = torch.mm(tensor1, tensor2)
RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:247**
```

https://github.com/vipzgy/AttentionTargetSentiment/issues/4

```
[jalal@goku AttentionTargetSentiment]$ conda list torch
# packages in environment at /scratch/sjn/anaconda:
#
# Name                    Version                   Build  Channel
torch                     0.3.1                     <pip>
[jalal@goku AttentionTargetSentiment]$ python -V
Python 3.6.3 :: Anaconda custom (64-bit)
[jalal@goku AttentionTargetSentiment]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core

```

**Comment by faizaan09** [comment]
I am not an expert on this, but this seems like an error in the parameters of the model. I am not sure if just switching to CUDA can cause this error. Can you run the same config with F1 on CPU and see if its working?

CPU execution tends to give more information on what went wrong where

**Comment by SsnL** [comment]
Your input and weight has incompatible sizes. Check if the number of features match.

**Comment by zou3519** [comment]
@monajalal please give us the sizes of the matrices you're multiplying, that would help a lot in debugging why the CUDA version has different behavior than the CPU.

**Comment by ngimel** [comment]
closing due to age.
