### ISSUE TITLE
torch.elastic could react faster on exit / Ctrl+C

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#68553]
I'm having a model run with torch.distributed.launch with only 1 rank for interactive debugging. I'm exiting pdb with Ctrl+D (graceful exit), but torchelastic is slow to detect an exit is requested and interpreter hangs for some seconds (which is not good because it's not clear why it's hanging). Then I hit Ctrl+C and I get the following stack trace.

I wonder if that server/api.py could also detect that exit is requested with Ctrl+D. Maybe it's some Linux signal that's not currently handled?

```
  File "/home/vadim/prefix/miniconda/lib/python3.9/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/home/vadim/prefix/miniconda/lib/python3.9/bdb.py", line 174, in dispatch_exception
    if self.quitting: raise BdbQuit
bdb.BdbQuit

^CTraceback (most recent call last):
  File "/home/vadim/prefix/miniconda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vadim/prefix/miniconda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 700, in run
    result = self._invoke_run(role)
  File "/home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 828, in _invoke_run
    time.sleep(monitor_interval)
```

**Comment by rohan-varma** [comment]
Moving over to r2p oncall for elastic issue.

**Comment by vadimkantorov** [comment]
The reason I guess is the time.sleep, and monitor_interval is a bit too large. But it would be nice if it could somehow react faster if possible. Or the main process could print something on console on termination e.g. "Please wait a few seconds for termination of worker processes...."

**Comment by vadimkantorov** [comment]
Same problem for torch.distributed.run. In the simplest cast of 1 worker (for debugging) running on a single node: when it throws an exception, the torch.distributed.run launcher still waits quite a few seconds before exit. This slows down the debug loop. Could the worker send some signal to the launcher process on an unhandler exception? At least for a single-node debugging, this will make it simpler. A related request for fast, coordinated exit for dist workers: https://github.com/pytorch/pytorch/issues/72099

**Comment by vadimkantorov** [comment]
@rohan-varma I would say, this is more distributed / torch.distributed.run issue.
