### ISSUE TITLE
ONNX Export of LayoutLMv2

### ISSUE THREAD

**Issue by fadi212** [pytorch/pytorch#68598]
I am trying to export LayoutLMv2 model to onnx format which is implemented in pytorch.
When I try to run the below code.

```
from transformers.onnx import OnnxConfig, PatchingSpec
from transformers.configuration_utils import PretrainedConfig
from typing import Any, List, Mapping, Optional, Tuple, Iterable
from collections import OrderedDict
from transformers import LayoutLMv2Processor
from datasets import load_dataset
from PIL import Image
import torch
from transformers import PreTrainedModel, TensorType
from torch.onnx import export
from transformers.file_utils import torch_version, is_torch_onnx_dict_inputs_support_available
from pathlib import Path
from transformers.utils import logging
from inspect import signature
from itertools import chain
from transformers import LayoutLMv2ForTokenClassification
from torch import nn
from torch.onnx import OperatorExportTypes

logger = logging.get_logger(__name__)  # pylint: disable=invalid-name


class LayoutLMv2OnnxConfig(OnnxConfig):
    def __init__(
            self,
            config: PretrainedConfig,
            task: str = "default",
            patching_specs: List[PatchingSpec] = None,
    ):
        super().__init__(config, task=task, patching_specs=patching_specs)
        self.max_2d_positions = config.max_2d_position_embeddings - 1

    @property
    def inputs(self) -> Mapping[str, Mapping[int, str]]:
        return OrderedDict(
            [
                ("input_ids", {0: "batch", 1: "sequence"}),
                ("bbox", {0: "batch", 1: "sequence"}),
                ("image", {0: "batch"}),
                ("attention_mask", {0: "batch", 1: "sequence"}),
                ("token_type_ids", {0: "batch", 1: "sequence"}),
            ]
        )

    def generate_dummy_inputs(
            self,
            processor: LayoutLMv2Processor,
            batch_size: int = -1,
            seq_length: int = -1,
            is_pair: bool = False,
            framework: Optional[TensorType] = None,
    ) -> Mapping[str, Any]:

        datasets = load_dataset("nielsr/funsd")
        example = datasets["test"][0]
        image = Image.open(example['image_path'])
        image = image.convert("RGB")

        if not framework == TensorType.PYTORCH:
            raise NotImplementedError("Exporting LayoutLM to ONNX is currently only supported for PyTorch.")

        input_dict = processor(image, example['words'], boxes=example['bboxes'], word_labels=example['ner_tags'],
                               return_tensors=framework)

        axis = 0
        for key_i in input_dict.data.keys():
            input_dict.data[key_i] = torch.cat((input_dict.data[key_i], input_dict.data[key_i]), axis)

        return input_dict.data


class pool_layer(nn.Module):
    def __init__(self):
        super(pool_layer, self).__init__()
        self.fc = nn.AvgPool2d(kernel_size=[8, 8], stride=[8, 8])

    def forward(self, x):
        output = self.fc(x)
        return output


def ensure_model_and_config_inputs_match(
        model: PreTrainedModel, model_inputs: Iterable[str]
) -> Tuple[bool, List[str]]:
    """

    :param model:
    :param model_inputs:
    :return:
    """
    forward_parameters = signature(model.forward).parameters
    model_inputs_set = set(model_inputs)

    # We are fine if config_inputs has more keys than model_inputs
    forward_inputs_set = set(forward_parameters.keys())
    is_ok = model_inputs_set.issubset(forward_inputs_set)

    # Make sure the input order match (VERY IMPORTANT !!!!)
    matching_inputs = forward_inputs_set.intersection(model_inputs_set)
    ordered_inputs = [parameter for parameter in forward_parameters.keys() if parameter in matching_inputs]
    return is_ok, ordered_inputs


def export_model(
        processor: LayoutLMv2Processor, model: PreTrainedModel, config: LayoutLMv2OnnxConfig, opset: int, output: Path
) -> Tuple[List[str], List[str]]:
    """
    Export a PyTorch backed pipeline to ONNX Intermediate Representation (IR

    Args:
        processor:
        model:
        config:
        opset:
        output:

    Returns:

    """

    if not is_torch_onnx_dict_inputs_support_available():
        raise AssertionError(f"Unsupported PyTorch version, minimum required is 1.8.0, got: {torch_version}")

    logger.info(f"Using framework PyTorch: {torch.__version__}")
    with torch.no_grad():
        model.config.return_dict = True
        model.eval()

        # Check if we need to override certain configuration item
        if config.values_override is not None:
            logger.info(f"Overriding {len(config.values_override)} configuration item(s)")
            for override_config_key, override_config_value in config.values_override.items():
                logger.info(f"\t- {override_config_key} -> {override_config_value}")
                setattr(model.config, override_config_key, override_config_value)

        model_inputs = config.generate_dummy_inputs(processor, framework=TensorType.PYTORCH)
        inputs_match, matched_inputs = ensure_model_and_config_inputs_match(model, model_inputs.keys())
        print(matched_inputs)
        onnx_outputs = list(config.outputs.keys())

        if not inputs_match:
            raise ValueError("Model and config inputs doesn't match")

        config.patch_ops()
        model_inputs.pop("labels")
        export(
            model,
            (model_inputs,),
            f=output.as_posix(),
            input_names=list(config.inputs.keys()),
            output_names=onnx_outputs,
            dynamic_axes={name: axes for name, axes in chain(config.inputs.items(), config.outputs.items())},
            do_constant_folding=True,
            use_external_data_format=config.use_external_data_format(model.num_parameters()),
            enable_onnx_checker=True,
            opset_version=opset,
            # operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK
        )

        config.restore_ops()

    return matched_inputs, onnx_outputs


if __name__ == '__main__':
    processor = LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased", revision="no_ocr")
    model = LayoutLMv2ForTokenClassification.from_pretrained("microsoft/layoutlmv2-base-uncased", torchscript = True)
    model.layoutlmv2.visual.pool = torch.nn.Sequential(pool_layer())
    onnx_config = LayoutLMv2OnnxConfig(model.config)
    export_model(processor=processor, model=model, config=onnx_config, opset=12, output=Path('onnx/layout.onnx'))
```

I am getting the following error.
```
(function ComputeConstantFolding)
Traceback (most recent call last):
  File "/home/muhammad/Layoutv2/LayoutLMv2_onnx.py", line 171, in <module>
    export_model(processor=processor, model=model, config=onnx_config, opset=12, output=Path('onnx/layout.onnx'))
  File "/home/muhammad/Layoutv2/LayoutLMv2_onnx.py", line 146, in export_model
    export(
  File "/home/muhammad/anaconda3/lib/python3.8/site-packages/torch/onnx/_init_.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/muhammad/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/muhammad/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/muhammad/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 501, in _model_to_graph
    params_dict = torch._C._jit_pass_onnx_constant_fold(graph, params_dict,
RuntimeError: torch.cat(): Tensors must have same number of dimensions: got 2 and 1
```

and when I set the `do_constant_folding= False`, I am able to convert the model to onnx but at the time of loading the model in infer session, I am getting the following error.
```
Traceback (most recent call last):
  File "/home/muhammad/Layoutv2/load_model.py", line 15, in <module>
    session = onnxruntime.InferenceSession(model_name)
  File "/home/muhammad/anaconda3/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 324, in _init_
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/muhammad/anaconda3/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 358, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from onnx/layout.onnx failed:Type Error: Type parameter (T) of Optype (Concat) bound to different types (tensor(int64) and tensor(float) in node (Concat_39).
```

PS: Not sure whether the issue is in onnx or pytorch so posting it here.

**Comment by kolia1985** [comment]
+1

**Comment by garymm** [comment]
I'm getting a different error on PyTorch 1.10, transformers 4.12.5:
```
/usr/local/lib/python3.7/dist-packages/transformers/models/layoutlmv2/modeling_layoutlmv2.py in _calc_text_embeddings(self, input_ids, bbox, position_ids, token_type_ids, inputs_embeds)
    753         token_type_embeddings = self.embeddings.token_type_embeddings(token_type_ids)
    754 
--> 755         embeddings = inputs_embeds + position_embeddings + spatial_position_embeddings + token_type_embeddings
    756         embeddings = self.embeddings.LayerNorm(embeddings)
    757         embeddings = self.embeddings.dropout(embeddings)

RuntimeError: The size of tensor a (316) must match the size of tensor b (365) at non-singleton dimension 1
```

Repro notebook: <https://gist.github.com/garymm/4e6ea79c0602bedcf2b1e4abb18ddd45>

Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1524563>

**Comment by vvalouch** [comment]
I am testing conversion to torch script and I am getting the same exception. PyTorch 1.10, Transformer 4.15.0
```
Traceback (most recent call last):
  File "/some_path/python3.8/site-packages/torch/jit/_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
  File "/some_path/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/some_path/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/some_path/python3.8/site-packages/transformers/models/layoutlmv2/modeling_layoutlmv2.py", line 1179, in forward
    outputs = self.layoutlmv2(
  File "/some_path/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/some_path/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/some_path/python3.8/site-packages/transformers/models/layoutlmv2/modeling_layoutlmv2.py", line 888, in forward
    text_layout_emb = self._calc_text_embeddings(
  File "/some_path/python3.8/site-packages/transformers/models/layoutlmv2/modeling_layoutlmv2.py", line 753, in _calc_text_embeddings
    embeddings = inputs_embeds + position_embeddings + spatial_position_embeddings + token_type_embeddings
RuntimeError: The size of tensor a (241) must match the size of tensor b (290) at non-singleton dimension 1
```

It seems to be related to https://github.com/huggingface/transformers/blob/f00f22a3e290fd377b979124dcf9800b3d73eb11/src/transformers/models/layoutlmv2/modeling_layoutlmv2.py#L861 . Is it really intended to update original input_shape?

**Comment by vvalouch** [comment]
I was looking into a bit more and I found out that the reason why the torchscript conversion is crashing is:
 - torch.jit._trace.py ->line 958 module._c._create_method_from_trace is unsqueezing the inputs thus instead of passing original e.g. attention_mask input as {Tensor:(1,241)} it is passing {Tensor:(tensor(1),tensor(241)}

I also rise the issue on HuggingFace repo -> https://github.com/huggingface/transformers/issues/15254

**Comment by shubhambhokare1** [comment]
Hi @fadi212,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
