### ISSUE TITLE
`jit.script` doesn't support `device(type='cuda')`

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#68626]
```
import torch
import torch.fx

def f(x):
  return x.to(torch.device('cuda'))

fx_g = torch.fx.symbolic_trace(f)
print(fx_g.code)
print(torch.jit.script(fx_g).graph)
```

FX symbolic trace gives
```
def forward(self, x):
    to = x.to(device(type='cuda'));  x = None
    return to
```

which then causes
```
Traceback (most recent call last):
  File "/fsx/users/chilli/work/functorch/t2.py", line 14, in <module>
    print(torch.jit.script(fx_g).graph)
  File "/fsx/users/chilli/conda/envs/tensorrt2/lib/python3.9/site-packages/torch/jit/_script.py", line 1258, in script
    return torch.jit._recursive.create_script_module(
  File "/fsx/users/chilli/conda/envs/tensorrt2/lib/python3.9/site-packages/torch/jit/_recursive.py", line 451, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/fsx/users/chilli/conda/envs/tensorrt2/lib/python3.9/site-packages/torch/jit/_recursive.py", line 517, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/fsx/users/chilli/conda/envs/tensorrt2/lib/python3.9/site-packages/torch/jit/_recursive.py", line 368, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 

aten::device(str a) -> (Device):
Argument a not provided.
:
  File "<eval_with_key>.0", line 5
def forward(self, x):
    to = x.to(device(type='cuda'));  x = None
              ~~~~~~ <--- HERE
    return to
```
@eellison @ansley @jamesr66a

**Comment by eellison** [comment]
```
diff --git a/torch/csrc/jit/frontend/builtin_functions.cpp b/torch/csrc/jit/frontend/builtin_functions.cpp
index dca669f2f2..8b30ff40db 100644
--- a/torch/csrc/jit/frontend/builtin_functions.cpp
+++ b/torch/csrc/jit/frontend/builtin_functions.cpp
@@ -70,6 +70,8 @@ def _assert_int_or_pair(vals: List[int], name: str, message: str):
 def list_with_default(out_size: List[int], defaults: List[int]):
   assert len(defaults) > len(out_size)
   return out_size
+def device(type: str):
+  return torch.device(type)
 def _assert(condition : bool, message : str):
   assert condition, message
 def type(self: Tensor, dtype: int, non_blocking: bool=False, copy: bool=False) -> Tensor:
 ```

**Comment by Chillee** [comment]
Works fine now
