### ISSUE TITLE
DISABLED test_ind_worker_queue (__main__.TestIndividualWorkerQueue)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#68643]
Platforms: windows, mac, macos, win

See https://github.com/pytorch/pytorch/runs/4259400670?check_suite_focus=true.

Relevant snippet:

```
======================================================================
ERROR [5.127s]: test_ind_worker_queue (__main__.TestIndividualWorkerQueue)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataloader.py", line 2377, in test_ind_worker_queue
    self._run_ind_worker_queue_test(batch_size=batch_size, num_workers=num_workers + 1)
  File "test_dataloader.py", line 2352, in _run_ind_worker_queue_test
    for i, (worker_ids, sample) in enumerate(loader):
  File "/usr/local/miniconda/envs/build/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/miniconda/envs/build/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/usr/local/miniconda/envs/build/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1139, in _get_data
    raise RuntimeError('DataLoader timed out after {} seconds'.format(self._timeout))
RuntimeError: DataLoader timed out after 5 seconds

----------------------------------------------------------------------
Ran 146 tests in 960.364s

FAILED (errors=1, skipped=17, unexpected successes=3)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @SsnL @VitalyFedyunin @ejguan @NivekT @malfet @albanD

**Comment by rohan-varma** [comment]
This doesn't appear to be a distributed issue and seems to be an issue with the dataloader/multiprocessing, but feel free to ping the distributed team if we can help with the root cause.

**Comment by janeyx99** [comment]
^ Acknowledged and added linux to platforms

**Comment by ejguan** [comment]
Run out of shared memory again

**Comment by janeyx99** [comment]
Updating comment accordingly ^
