### ISSUE TITLE
DISABLED test_default_store_timeout_nccl (__main__.TimeoutTest)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#68716]
Platforms: rocm

See https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/6507//console.

Relevant snippet:

```
12:03:34   test_default_store_timeout_nccl (__main__.TimeoutTest) ... [W socket.cpp:334] The server socket has failed to bind to [::]:38655 (generic error: 98 - Address already in use).
12:03:36 [W socket.cpp:334] The server socket has failed to bind to 0.0.0.0:38655 (generic error: 98 - Address already in use).
12:03:36 [E socket.cpp:368] The server socket has failed to listen on any local network address.
12:03:36 ERROR (2.019s)
12:03:36 
12:03:36 ======================================================================
12:03:36 ERROR [2.019s]: test_default_store_timeout_nccl (__main__.TimeoutTest)
12:03:36 ----------------------------------------------------------------------
12:03:36 Traceback (most recent call last):
12:03:36   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 3041, in wrapper
12:03:36     return func(*args, **kwargs)
12:03:36   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2347, in wrapper
12:03:36     return func(*args, **kwargs)
12:03:36   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 3041, in wrapper
12:03:36     return func(*args, **kwargs)
12:03:36   File "distributed/test_c10d_nccl.py", line 181, in test_default_store_timeout_nccl
12:03:36     self._test_default_store_timeout("nccl")
12:03:36   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_common.py", line 116, in _test_default_store_timeout
12:03:36     raise c2p[0]
12:03:36   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_common.py", line 76, in _test_store_timeout
12:03:36     timeout=timedelta(seconds=1),
12:03:36   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 593, in init_process_group
12:03:36     store, rank, world_size = next(rendezvous_iterator)
12:03:36   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 183, in _tcp_rendezvous_handler
12:03:36     store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
12:03:36   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 158, in _create_c10d_store
12:03:36     hostname, port, world_size, start_daemon, timeout, multi_tenant=True
12:03:36 RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:38655 (generic error: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:38655 (generic error: 98 - Address already in use).
12:03:36 
12:03:36 ----------------------------------------------------------------------
12:03:36 Ran 94 tests in 586.865s
12:03:36 
12:03:36 FAILED (errors=1, skipped=11)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by KyleCZH** [comment]
@mruberry I think this test can be re-enabled because I couldn't reproduce this issue with rocm GPUs (ran in a loop for a few hours). Also, the "Address already in use" seems common so it might happen on other test cases and platforms as well (e.g., https://github.com/pytorch/pytorch/issues/62314, https://github.com/pytorch/pytorch/issues/64093).

**Comment by mruberry** [comment]
> @mruberry I think this test can be re-enabled because I couldn't reproduce this issue with rocm GPUs (ran in a loop for a few hours). Also, the "Address already in use" seems common so it might happen on other test cases and platforms as well (e.g., #62314, #59441, #64093).

OK; let's close this issue.
