### ISSUE TITLE
DISABLED test_variant_consistency_jit_dist_cpu_complex64 (__main__.TestJitCPU)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#68847]
Platforms: win

Was potentially flaky in the last week--captured by flaky tests table [here](https://metrics.pytorch.org/d/L0r6ErGnk/github-status?orgId=1&from=1637618111572&to=1637704511572&viewPanel=57)

Logs: https://github.com/pytorch/pytorch/runs/4256979177?check_suite_focus=true

```
======================================================================
ERROR [5.068s]: test_variant_consistency_jit_dist_cpu_complex64 (__main__.TestJitCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 381, in instantiated_test
    raise rte
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 742, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 840, in test_variant_consistency_jit
    check_against_reference(self,
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_jit.py", line 126, in check_against_reference
    outputs_test = output_func(self.runAndSaveRNG(func, recording_inputs, kwargs))
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_jit.py", line 160, in runAndSaveRNG
    results = func(*inputs, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\jit_metaprogramming_utils.py", line 341, in script_fn
    self.assertExportImport(fn.graph, tensors)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_jit.py", line 148, in assertExportImport
    self.assertExportImportModule(m, inputs)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_jit.py", line 151, in assertExportImportModule
    m_import = self.getExportImportCopy(m)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_jit.py", line 174, in getExportImportCopy
    return torch.jit.load(fname, map_location=map_location)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\jit\_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: open file failed because of errno 22 on fopen: Invalid argument, file path: C:\Users\RUNNER~1\AppData\Local\Temp\tmpnd0mxxha
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by davidberard98** [comment]
Too old to see the logs or the history. But failure looks the same as #73346 (i.e. appears to be an infra failure unrelated to the actual jit test, and can't repro), so I'll close it and take another look if it fails again.
