### ISSUE TITLE
DISABLED test_RNN_dropout_state (__main__.TestNN)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#68849]
Was detected to be flaky by the automatic flaky test detection tool that reports to Grafana [here](https://metrics.pytorch.org/d/L0r6ErGnk/github-status?orgId=1&from=1637618111572&to=1637704511572&viewPanel=57)

Logs: https://github.com/pytorch/pytorch/runs/4293831449?check_suite_focus=true

```
======================================================================
FAIL [0.026s]: test_RNN_dropout_state (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 8810, in test_RNN_dropout_state
    self.assertNotEqual(output1, output2)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2072, in assertNotEqual
    self.assertEqual(x, y, msg, atol=atol, rtol=rtol, **kwargs)
AssertionError: AssertionError not raised
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @mruberry @walterddr

**Comment by jeanschmidt** [comment]
I am reopening this issue, as this test started to fail after reverting https://github.com/pytorch/pytorch/pull/144572
