### ISSUE TITLE
Thank you for the diagnostic script.

### ISSUE THREAD

**Issue by Ascrypto** [pytorch/pytorch#68927]
Thank you for the diagnostic script. 

I have a problem with: from torch.utils.tensorboard import SummaryWriter 
 raise ImportError('TensorBoard logging requires TensorBoard with Python summary writer installed. '
ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above.

Although I have tensorboard 2.7.0 (tried 1.14 before) and tensorflow 2.7.0 installed (I am using pycharm) in a virtual env,  the output of the script says these packages are not installed.  

### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)
INFO: os.name: posix

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
WARNING: The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: no installation among: ['tb-nightly', 'tensorboard', 'tensorflow-tensorboard']
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']

--- check: tensorboard_python_version
Traceback (most recent call last):
  File "test.py", line 522, in main
    suggestions.extend(check())
  File "test.py", line 75, in wrapper
    result = fn()
  File "test.py", line 271, in tensorboard_python_version
    from tensorboard import version
ModuleNotFoundError: No module named 'tensorboard'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "test.py", line 522, in main
    suggestions.extend(check())
  File "test.py", line 75, in wrapper
    result = fn()
  File "test.py", line 278, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_data_server_version
INFO: no data server installed

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/usr/local/bin/tensorboard\n'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (0): []; bad_roots (0): []

--- check: full_pip_freeze
WARNING: The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
INFO: pip freeze --all:
tenacity==8.0.1
terminado==0.12.1
testpath==0.5.0
textwrap3==0.9.2
toml==0.10.2
tomli==1.2.2
torch==1.5.1
tornado==6.1
tqdm==4.62.3
traitlets==5.1.1
Twisted==17.9.0
typing-extensions==3.10.0.2
``````

</details>

### Next steps

Note: no suggestions were provided on how to fix it. 

any suggestion would be helpful. ( I tried all of the above solutions, to no avail.)

_Originally posted by @Ascrypto in https://github.com/pytorch/pytorch/issues/22676#issuecomment-979683435_

**Comment by Ascrypto** [comment]
I was running the script with sudo, this is why it did not recognize the packages (my bad).  But, I still have the same issue: ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. I tried to import SummaryWriter from tensorboardX, but got this: ModuleNotFoundError: No module named 'tensorboardX'. 


The tensorboard server is running just fine.
