### ISSUE TITLE
Breakes with -OO flag in script

### ISSUE THREAD

**Issue by RaulMurillo** [pytorch/pytorch#68920]
## 🐛 Bug

I installed the latest PyTorch (CPU only) in a virtual environment using pip.
However, using Python optimization flag is not allowed, but it was in previous versions.

## To Reproduce

Running `python -OO -c "import torch"` yields the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ramuri01/venv/lib/python3.9/site-packages/torch/__init__.py", line 643, in <module>
    from .functional import *  # noqa: F403
  File "/home/ramuri01/venv/lib/python3.9/site-packages/torch/functional.py", line 6, in <module>
    import torch.nn.functional as F
  File "/home/ramuri01/venv/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/ramuri01/venv/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/home/ramuri01/venv/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 6, in <module>
    from .. import functional as F
  File "/home/ramuri01/venv/lib/python3.9/site-packages/torch/nn/functional.py", line 2231, in <module>
    embedding_bag.__doc__ = embedding_bag.__doc__.format(**reproducibility_notes)
AttributeError: 'NoneType' object has no attribute 'format'
```

Using a single `-O` or no optimization flag, the import does not fail.

## Environment

Using Python 3.9.5 in Ubuntu 21.04 x86_64.

**Comment by samdow** [comment]
High priority for regression

**Comment by malfet** [comment]
@samdow I don't think it is a regression, as I'm seeing the same with pytorch-1.9:
```
% python3 -c "import torch;print(torch.__version__)"
1.9.1
% python3 -OO -c "import torch;print(torch.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nshulga/miniconda3/envs/pytorch-1.9.1/lib/python3.7/site-packages/torch/__init__.py", line 629, in <module>
    from .functional import *  # noqa: F403
  File "/Users/nshulga/miniconda3/envs/pytorch-1.9.1/lib/python3.7/site-packages/torch/functional.py", line 6, in <module>
    import torch.nn.functional as F
  File "/Users/nshulga/miniconda3/envs/pytorch-1.9.1/lib/python3.7/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/nshulga/miniconda3/envs/pytorch-1.9.1/lib/python3.7/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/Users/nshulga/miniconda3/envs/pytorch-1.9.1/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 6, in <module>
    from .. import functional as F
  File "/Users/nshulga/miniconda3/envs/pytorch-1.9.1/lib/python3.7/site-packages/torch/nn/functional.py", line 2230, in <module>
    embedding_bag.__doc__ = embedding_bag.__doc__.format(**reproducibility_notes)
AttributeError: 'NoneType' object has no attribute 'format'

```

**Comment by samdow** [comment]
> @samdow I don't think it is a regression, as I'm seeing the same with pytorch-1.9:

Sorry about that! I thought I was running a 1.9 build but looks like it wasn't. Removing hi pri + triage review

@RaulMurillo do you know what version you were on when this worked for you?

**Comment by RaulMurillo** [comment]
Hi @samdow, I checked the virtual environment I previously used for development.
```bash
$ python3 -OO -c "import torch;print(torch.__version__)"
1.7.1
```
