### ISSUE TITLE
RuntimeError: !node->kind().is_aten() && !node->kind().is_prim() && !node->kind().is_attr()INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by zang5xixi** [pytorch/pytorch#68975]
## Issue description

I want to convert a pytorch model into onnx using ```torch.onnx.export()```, but encounter such a issue when i use ```dynamic_axes```.If i do not use ```dynamic_axes```, there is no erro  in the convertion process.

## error log

```
speechbrain.core - Exception:
Traceback (most recent call last):
  File "speaker_verification_cosine1.py", line 271, in <module>
    torch.onnx.export(params["embedding_model"],(input1,input2),'test.onnx', verbose=True, opset_version=10,do_constant_folding=True,input_names=['input1','input2'],output_names=['output'],dynamic_axes={'input1':[0,1],'input2':[0], 'output':[0]})
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 740, in _export
    val_add_node_names, val_use_external_data_format, model_file_location)
RuntimeError: !node->kind().is_aten() && !node->kind().is_prim() && !node->kind().is_attr()INTERNAL ASSERT FAILED at "/media/nvidia/NVME/pytorch/pytorch-v1.10.0/torch/csrc/jit/serialization/export.cpp":515, please report a bug to PyTorch.
```

## System Info
```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (aarch64)
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.4
Libc version: glibc-2.25

Python version: 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-4.9.140-tegra-aarch64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.0.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0
[pip3] torch2trt==0.3.0
[pip3] torchaudio==0.10.0+d2634d8
[pip3] torchvision==0.9.1
[conda] Could not collect
```

**Comment by BowenBao** [comment]
hi @zang5xixi thanks for reporting. 

Could you please
1. Try with latest PyTorch nightly version and see if the error persists?
2. If so, share with us a runnable script that can repro this issue?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
