### ISSUE TITLE
`TestProfilerCUDA. test_mem_leak` failing for CUDA 11.5 on Linux

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#69023]
The test fails with error: FAIL [4.740s]: test_mem_leak (__main__.TestProfilerCUDA) Checks that there's no memory leak when using profiler with CUDA

More detailed error log:
Running tests...
```
+ TEST_COMMAND=.jenkins/pytorch/test.sh
+++ nproc --ignore=2
++ docker run --gpus all -e BUILD_ENVIRONMENT -e PR_NUMBER -e CUSTOM_TEST_ARTIFACT_BUILD_DIR -e GITHUB_ACTIONS -e IN_CI -e IS_GHA -e BRANCH -e SHA1 -e AWS_DEFAULT_REGION -e IN_WHEEL_TEST -e SHARD_NUMBER -e JOB_BASE_NAME -e TEST_CONFIG -e NUM_TEST_SHARDS -e PYTORCH_IGNORE_DISABLED_ISSUES -e PYTORCH_RETRY_TEST_CASES -e PR_LABELS -e MAX_JOBS=14 -e SCCACHE_BUCKET -e http_proxy=http://internal-tf-lb-20210727220640487900000002-835786077.us-east-1.elb.amazonaws.com:3128 -e https_proxy=http://internal-tf-lb-20210727220640487900000002-835786077.us-east-1.elb.amazonaws.com:3128 -e no_proxy=localhost,127.0.0.1,github.com,amazonaws.com,s3.amazonaws.com,169.254.169.254,169.254.170.2,/var/run/docker.sock -e XLA_CLANG_CACHE_S3_BUCKET_NAME --env-file=/tmp/github_env_1510870016 --ulimit stack=10485760:83886080 --security-opt seccomp=unconfined --cap-add=SYS_PTRACE --shm-size=2g --tty --detach --name= --user jenkins -v /home/ec2-user/actions-runner/_work/pytorch/pytorch:/var/lib/jenkins/workspace -w /var/lib/jenkins/workspace 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-bionic-cuda11.5-cudnn8-py3-gcc7:6c970af5a1e4984eb13b9c790aa13a3a02ac0825
+ container_name=e6e888ecdf9258963ab943df054c07cd46cc36c58a5b7b297e3fdea4d84c0a72
+ docker exec -t e6e888ecdf9258963ab943df054c07cd46cc36c58a5b7b297e3fdea4d84c0a72 sh -c 'sudo chown -R jenkins . && pip install dist/*.whl && .jenkins/pytorch/test.sh'
Processing ./dist/torch-1.11.0a0+git826683b-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: dataclasses in /opt/conda/lib/python3.6/site-packages (from torch==1.11.0a0+git826683b) (0.8)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.6/site-packages (from torch==1.11.0a0+git826683b) (3.10.0.2)
Installing collected packages: torch
Successfully installed torch-1.11.0a0+git826683b
+ COMPACT_JOB_NAME=linux-bionic-cuda11.5-py3.6-gcc7
++ python -c 'import site; print(site.getsitepackages()[0])'
+ TORCH_INSTALL_DIR=/opt/conda/lib/python3.6/site-packages/torch
+ TORCH_BIN_DIR=/opt/conda/lib/python3.6/site-packages/torch/bin
+ TORCH_LIB_DIR=/opt/conda/lib/python3.6/site-packages/torch/lib
+ TORCH_TEST_DIR=/opt/conda/lib/python3.6/site-packages/torch/test
+ BUILD_DIR=build
  test_kineto (__main__.TestProfiler) ... ok (0.504s)
  test_kineto_multigpu (__main__.TestProfiler) ... skip (0.002s)
  test_kineto_profiler_api (__main__.TestProfiler) ... ok (0.030s)
  test_memory_profiler (__main__.TestProfiler) ... ok (0.054s)
  test_module_hierarchy (__main__.TestProfiler) ... ok (0.029s)
  test_profiler_fwd_bwd_link (__main__.TestProfiler) ... ok (0.007s)
  test_profiler_metadata (__main__.TestProfiler) ... ok (0.002s)
  test_profiler_tracing (__main__.TestProfiler) ... ok (0.009s)
  test_source (__main__.TestProfiler)
Checks that source code attribution works for eager, TS and autograd mode ... ok (0.037s)
  test_tensorboard_trace_handler (__main__.TestProfiler) ... ok (0.050s)
  test_mem_leak (__main__.TestProfilerCUDA)
Checks that there's no memory leak when using profiler with CUDA ... FAIL (4.740s)
    test_mem_leak failed - num_retries_left: 3
  test_mem_leak (__main__.TestProfilerCUDA)
Checks that there's no memory leak when using profiler with CUDA ... ok (4.612s)
    test_mem_leak succeeded - num_retries_left: 2
  test_mem_leak (__main__.TestProfilerCUDA)
Checks that there's no memory leak when using profiler with CUDA ... ok (4.655s)
    test_mem_leak succeeded - num_retries_left: 1
  test_mem_leak (__main__.TestProfilerCUDA)
Checks that there's no memory leak when using profiler with CUDA ... ok (4.544s)
    test_mem_leak succeeded - num_retries_left: 0
  test_record_function (__main__.TestRecordFunction) ... ok (0.003s)

======================================================================
FAIL [4.740s]: test_mem_leak (__main__.TestProfilerCUDA)
Checks that there's no memory leak when using profiler with CUDA
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_profiler.py", line 61, in test_mem_leak
    msg='memory usage is increasing, {}'.format(str(last_rss)))
AssertionError: False is not true : memory usage is increasing, deque([2788843520, 2789183488, 2789187584, 2789486592, 2789564416], maxlen=5)

----------------------------------------------------------------------
Ran 18 tests in 20.029s

FAILED (failures=1, skipped=1, unexpected successes=3)

Generating XML reports...
Generated XML report: test-reports/python-unittest/test_profiler/TEST-TestProfiler-20211127180225.xml
Generated XML report: test-reports/python-unittest/test_profiler/TEST-TestProfilerCUDA-20211127180225.xml
Generated XML report: test-reports/python-unittest/test_profiler/TEST-TestRecordFunction-20211127180225.xml
Traceback (most recent call last):
  File "test/run_test.py", line 1051, in <module>
    main()
  File "test/run_test.py", line 1029, in main
    raise RuntimeError(err_message)
RuntimeError: test_profiler failed!

real	42m41.365s
user	47m47.616s
sys	4m40.465s
+ cleanup
+ retcode=1
+ set +x
Error: Process completed with exit code 1.
```

Test Run Results:
https://github.com/pytorch/pytorch/runs/4341886043?check_suite_focus=true

cc @VitalyFedyunin @ngimel @seemethere @malfet @pytorch/pytorch-dev-infra @ilia-cher @robieta @chaekit @gdankel @bitfort @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git @b0noI

**Comment by mruberry** [comment]
I don't think this is related because it looks to me like this test is intentionally triggering a leak and then verifying the profiler can detect it, and I don't recall any updates to this test or the profiler

**Comment by robieta** [comment]
This test seems overly conservative. Kilobytes of jitter in total process memory is actually pretty good; there are all sorts of implementation details in things like cPython and `malloc` that are under no obligation to return to a bytewise identical state. (And therefore can change the *exact* amount of memory used by the process.) My vote would be to threshold what we consider a "leak".

**Comment by seemethere** [comment]
Removing this from the 1.11.0 milestone since this isn't a release blocker for 1.11.0

**Comment by huydhn** [comment]
Closing this as this is not relevant anymore on our CI/CI (CUDA 11.5)
