### ISSUE TITLE
Pruning `torch.nn.MultiheadAttention` causes RuntimeError

### ISSUE THREAD

**Issue by Mu-Y** [pytorch/pytorch#69353]
## 🐛 Bug

I am running into the following RuntimeError when pruning parameters of `torch.nn.MultiheadAttention` module:
```
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

## To Reproduce

Here is the toy example I'm running:
```
import torch.nn as nn
import torch
import torch.nn.utils.prune as prune

class net(nn.Module):
    def __init__(self):
        super().__init__()

        self.att = nn.MultiheadAttention(
            embed_dim=100,
            num_heads=2,
            batch_first=True
        )
        self.proj = nn.Linear(100, 10)
        self.criterion = nn.CrossEntropyLoss()

    def forward(self, x):
        attn_output, attn_weights = self.att(x, x, x)
        logits = self.proj(attn_output)
        return logits

    def compute_loss(self, logits, target):
        loss = self.criterion(logits, target)
        return loss

model = net().cuda()
# prune here
params_to_prune = [
    (model.att, "in_proj_weight"),
    (model.att.out_proj, "weight"),
    (model.proj, "weight")
]
prune.global_unstructured(
    params_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.05,
)

opt = torch.optim.SGD(model.parameters(), lr=0.01)
for step in range(0, 10):
    x = torch.rand((16, 50, 100)).cuda()  # data of batchsize=16, seqlength=50, featuredim=100
    y = torch.ones((16*50, )).long().cuda()
    opt.zero_grad()
    logits = model(x)
    loss = model.compute_loss(logits.reshape(16*50, 10), y)
    loss.backward()
    opt.step()
    print("step {} successful".format(step))

```

Full error stack:
```
step 0 successful
Traceback (most recent call last):
  File "test_MHA_prune.py", line 49, in <module>
    loss.backward()
  File "/scratch2/mxy190019/anaconda3/envs/custom-pytorch/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/scratch2/mxy190019/anaconda3/envs/custom-pytorch/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

## Expected behavior
The pruned model should be able to train without a problem.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0+cu102
 - OS (e.g., Linux): CentOS Linux 7 (Core) (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): `pip install torch`
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8.0 (default, Nov  6 2019, 21:49:08)  [GCC 7.3.0] (64-bit runtime)
 - CUDA/cuDNN version: CUDA 10.2
 - GPU models and configuration: One single GeForce RTX 2080 Ti
 - Any other relevant information: None

## Additional context

It seems that the error is brought by the pruning of this parameter in `torch.nn.MultiheadAttention`: (model.att.out_proj, "weight"). If I remove this line then there is no such RuntimeError. Am I missing anything here for pruning the MultiheadAttention module? How should I properly prune the parameters in `out_proj` (which I believe is just a Linear layer)? 

Thanks!

**Comment by B06901052** [comment]
I met the same error while pruning fairseq MultiheadAttention. I think they have the same reason: When you forward a MultiheadAttention, it direct call the out_proj.weight without forwarding it. (see [#L1113](https://github.com/pytorch/pytorch/blob/cac16e2ee293964033dffa6616f78b68603cd565/torch/nn/modules/activation.py#L1113), [#L1142](https://github.com/pytorch/pytorch/blob/cac16e2ee293964033dffa6616f78b68603cd565/torch/nn/modules/activation.py#L1142), and [#L1153](https://github.com/pytorch/pytorch/blob/cac16e2ee293964033dffa6616f78b68603cd565/torch/nn/modules/activation.py#L1153)) But the mechanism of the torch.nn.utils.prune is that use forward_pre_hook to compute `out_proj.weight=out_proj.weight_orig * out_proj.weight_mask` before it be used. Then if you don't call forward_pre_hook, the out_proj.weight will not be recompute. So the thing will go through like:
1. compute weight when you prune it
2. forward weight
3. backward then the optimizer updates weight_orig (since weight_orig is parameter, while weight is not)
5. forward unchanged weight again
6. backward unchanged weight again

I have not come up with some good idea to fix all this type of problems, but there is a work around solution, just directly call the forward_pre_hook before each forwarding, as below:
```python
module = model.att.out_proj
for hook in module ._forward_pre_hooks.values():
  if isinstance(hook, prune.BasePruningMethod):
    hook(module, None)
# forward your model
```
