### ISSUE TITLE
PyTorch Docker build error

### ISSUE THREAD

**Issue by nzw0301** [pytorch/pytorch#6935]
## Issue description

This issue is a bug report about PyTorch Docker build, I guess.

## Code example

```bash
git clone https://github.com/pytorch/pytorch.git
cd pytorch
docker build -t pytorch -f docker/pytorch/Dockerfile
```

Error message:

```
[ 17%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorSort.cu.o
[ 17%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorTypeUtils.cu.o
[ 17%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCSortUtils.cu.o
[ 18%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorMode.cu.o
Killed
CMake Error at ATen_generated_THCTensorIndex.cu.o.Release.cmake:279 (message):
  Error generating file
  /tmp/pip-3exj0kdt-build/aten/build/src/ATen/CMakeFiles/ATen.dir/__/THC/./ATen_generated_THCTensorIndex.cu.o

src/ATen/CMakeFiles/ATen.dir/build.make:154: recipe for target 'src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorIndex.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorIndex.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:233: recipe for target 'src/ATen/CMakeFiles/ATen.dir/all' failed
make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Running setup.py install for torch: finished with status 'error'

Cleaning up...
  Removing source in /tmp/pip-mt0ht105-build
Command "/opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-mt0ht105-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yh9o2jm1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-mt0ht105-build/
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/opt/conda/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-mt0ht105-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yh9o2jm1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-mt0ht105-build/
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 301 122
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching permanant redirect
Looking up "https://pypi.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.org
"GET /pypi/pip/json HTTP/1.1" 200 15785
Updating cache with response from "https://pypi.org/pypi/pip/json"
Caching due to etag
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     pip install -v .' returned a non-zero code: 1
```

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

```
∫ python collect_env.py
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.4
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
```

And 
- Versions of any other relevant libraries: Docker version `Version 18.03.0-ce-mac60 (23751)`

**Comment by apaszke** [comment]
`Killed` means that the compiler was killed by the kernel because it used too much memory. There are a few workarounds:
- increase the memory limit for docker container
- limit the number of concurrent builds by changing the `Dockerfile` to include `MAX_JOBS=1` [here](https://github.com/pytorch/pytorch/blob/master/docker/pytorch/Dockerfile#L30)

**Comment by nzw0301** [comment]
Thank you for your comment.  I try to do that.
