### ISSUE TITLE
JIT RuntimeError:  'Union[Tensor, List[float], List[int]]' object is not subscriptable

### ISSUE THREAD

**Issue by ProGamerGov** [pytorch/pytorch#69434]
## 🐛 Bug

A properly type hint function or class results in an error with TorchScript is you slice the sequential List or Tensor object.

## To Reproduce

Run this test function and convert it to JIT:

```
from typing import Union, List
import torch

def test(x: Union[List[int], List[float], torch.Tensor]) -> Union[int, float, torch.Tensor]:
      return x[0]
out = torch.jit.script(test)
```

Results in the following error message

```
RuntimeError                              Traceback (most recent call last)

<ipython-input-3-c890700ed60b> in <module>()
      4 def test(x: Union[List[int], List[float], torch.Tensor]) -> Union[int, float, torch.Tensor]:
      5       return x[0]
----> 6 out = torch.jit.script(test)

/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb, example_inputs)
   1309             _rcb = _jit_internal.createResolutionCallbackFromClosure(obj)
   1310         fn = torch._C._jit_script_compile(
-> 1311             qualified_name, ast, _rcb, get_default_args(obj)
   1312         )
   1313         # Forward docstrings

RuntimeError: 
'Union[Tensor, List[float], List[int]]' object is not subscriptable:
  File "<ipython-input-3-c890700ed60b>", line 5
def test(x: Union[List[int], List[float], torch.Tensor]) -> Union[int, float, torch.Tensor]:
      return x[0]
             ~~~~ <--- HERE
```

## Expected behavior

There should be no error message, unless I'm missing something major.

## Environment

```

Collecting environment information...
PyTorch version: 1.10.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.12 (default, Sep 10 2021, 00:21:48)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0+cu111
[pip3] torchaudio==0.10.0+cu111
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.1+cu111
[conda] Could not collect
```

Basically the standard Google Colab environment.

**Comment by ProGamerGov** [comment]
Looks like the issue actually occurs with just lists and tuples as well:

```
def test(x: Union[List[int], List[float]]) -> Union[int, float]:
      return x[0]
out = torch.jit.script(test)
```

```
RuntimeError: 
'Union[List[float], List[int]]' object is not subscriptable:
  File "<ipython-input-4-0d632971daea>", line 5
def test(x: Union[List[int], List[float]]) -> Union[int, float]:#, torch.Tensor]:
      return x[0]
             ~~~~ <--- HERE
```

```
def test(x: Union[Tuple[int], Tuple[float]]) -> Union[int, float]:
      return x[0]
out = torch.jit.script(test)
```

```
RuntimeError: 
'Union[Tuple[float], Tuple[int]]' object is not subscriptable:
  File "<ipython-input-3-5cbe90eff962>", line 5
def test(x: Union[Tuple[int], Tuple[float]]) -> Union[int, float]:#, torch.Tensor]:
      return x[0]
             ~~~~ <--- HERE
```

**Comment by ProGamerGov** [comment]
Looks like Unions of lists and tuples also don't work.

```
def test_jit(x: Union[Tuple[int], Tuple[int, int], List[int]]) -> int:
    return x[0]
torch.jit.script(test_jit)

RuntimeError: 
'Union[Tuple[int], Tuple[int, int], List[int]]' object is not subscriptable:
```

```
def test_jit(x: Union[Tuple[int], Tuple[int, int]]) -> int:
    return x[0]
torch.jit.script(test_jit)
```

```
RuntimeError: 
'Union[Tuple[int], Tuple[int, int]]' object is not subscriptable:
```

**Comment by datumbox** [comment]
We get a similar problem at TorchVision at https://github.com/pytorch/vision/pull/5568. Our goal is to define params as `Union[List[int], List[float], int, float]`. Unfortunately when we do, JIT fails with:
```
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::tensor.float(float t, *, int? dtype=None, Device? device=None, bool requires_grad=False) -> (Tensor):
  Expected a value of type 'float' for argument 't' but instead found type 'Union[List[float], List[int]]'.
  
  aten::tensor.int(int t, *, int? dtype=None, Device? device=None, bool requires_grad=False) -> (Tensor):
  Expected a value of type 'int' for argument 't' but instead found type 'Union[List[float], List[int]]'.
  
  aten::tensor.bool(bool t, *, int? dtype=None, Device? device=None, bool requires_grad=False) -> (Tensor):
  Expected a value of type 'bool' for argument 't' but instead found type 'Union[List[float], List[int]]'.
  
  aten::tensor.complex(complex t, *, int? dtype=None, Device? device=None, bool requires_grad=False) -> (Tensor):
  Expected a value of type 'complex' for argument 't' but instead found type 'Union[List[float], List[int]]'.
  
  aten::tensor(t[] data, *, int? dtype=None, Device? device=None, bool requires_grad=False) -> (Tensor):
  Could not match type Union[List[float], List[int]] to List[t] in argument 'data': Cannot match List[t] to Union[List[float], List[int]].
```

**Comment by ansley** [comment]
Hi, sorry I missed this first message! Please tag me for all Union-related issues, as I'm the owner of TorchScript dynamic typing.

The reason this particular bug happens is because, in our type system, `Union[List[A], List[B]]` is a type, `List[A]` is a different type, and `List[B]` is still another type. In TorchScript, we have a separate implementation for each type that supports subscripting--that is, `List[A]` has one subscript implementation and `List[B]` has another subscript implementation. `Union` as a type does not support subscripting (how could it?). So, when you try to subscript `x`, the compiler says "Hey, you can't subscript a Union type".

The TorchScript compiler works ahead-of-time, and that means that all we can see is what you write. We have no way of knowing what objects you'll pass in the future. If we see e.g. `Union[List[A], B]`, we may be able to say "`B` doesn't support subscripting, and `List[A]` does, so let's just assume that this is actually a `List[A]` even though the user didn't tell us that." (though there are some circumstances in which this doesn't work, fair warning). On the other hand, if the user asks us to subscript `Union[List[A], List[B]`, then we have no way to determine whether our code should include the call to `List[A].subscript_op` or `List[B].subscript_op`.

The best workaround we have right now is adding a statement to assert the type of an object. E.g. `assert isinstance(x, <type>)` or `if isinstance(x, <type>)`. This gives the compiler a lot more information.

I debated dropping some type safety guarantees for an enhanced user experience, but a lot of our optimization passes rely on knowing the exact type of an object. Because many customers use TorchScript for performance, I couldn't justify doing this.

I hope this explanation makes sense. In the future, I'd really like to fix this problem--or at least add enough special-casing logic to cover the majority of users' issues here. That being said, a true fix is not our #1 priority now, because it would be such a technically complex endeavor with very little visible payoff.

Please feel free to open issues for specific bugs. I may be able to add some code to special-case your particular situation

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
