### ISSUE TITLE
Hello, my laptop has AMD Ryzen 7 5700U processor with AMD Ryzen integrated graphic and Windows 11. I am trying to install Pytorch using pip and have tried every command I could find over Pytorch Installation discussion but none are working. Please help. working.

### ISSUE THREAD

**Issue by Sugandha14** [pytorch/pytorch#69572]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by Sugandha14** [comment]
C:\>pip3 install torch -f https://download.pytorch.org/whl/rocm4.0.1/torch.stable.html
Looking in links: https://download.pytorch.org/whl/rocm4.0.1/torch.stable.html
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch


C:\>pip3 install torch -f https://download.pytorch.org/whl/rocm4.0.1/torch.stable.html
Looking in links: https://download.pytorch.org/whl/rocm4.0.1/torch.stable.html
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

C:\>pip3 install torch torchvision
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

C:\>pip3 install torch
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

C:\>pip install torch==1.8.0+cpu torchvision==0.9.0+cpu torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.8.0+cpu (from versions: none)
ERROR: No matching distribution found for torch==1.8.0+cpu

**Comment by Sugandha14** [comment]
C:\>pip install pytorch==1.0.2 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting pytorch==1.0.2
  Using cached pytorch-1.0.2.tar.gz (689 bytes)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pytorch
  Building wheel for pytorch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\sugan\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sugan\\AppData\\Local\\Temp\\pip-install-z87xmfm9\\pytorch_a2fb5beaf3354001848eb8f55c85ed43\\setup.py'"'"'; __file__='"'"'C:\\Users\\sugan\\AppData\\Local\\Temp\\pip-install-z87xmfm9\\pytorch_a2fb5beaf3354001848eb8f55c85ed43\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\sugan\AppData\Local\Temp\pip-wheel-s5a0785v'
       cwd: C:\Users\sugan\AppData\Local\Temp\pip-install-z87xmfm9\pytorch_a2fb5beaf3354001848eb8f55c85ed43\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\sugan\AppData\Local\Temp\pip-install-z87xmfm9\pytorch_a2fb5beaf3354001848eb8f55c85ed43\setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
  ----------------------------------------
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
Installing collected packages: pytorch
    Running setup.py install for pytorch ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\sugan\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sugan\\AppData\\Local\\Temp\\pip-install-z87xmfm9\\pytorch_a2fb5beaf3354001848eb8f55c85ed43\\setup.py'"'"'; __file__='"'"'C:\\Users\\sugan\\AppData\\Local\\Temp\\pip-install-z87xmfm9\\pytorch_a2fb5beaf3354001848eb8f55c85ed43\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sugan\AppData\Local\Temp\pip-record-tpc1uo7i\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\sugan\AppData\Local\Programs\Python\Python310\Include\pytorch'
         cwd: C:\Users\sugan\AppData\Local\Temp\pip-install-z87xmfm9\pytorch_a2fb5beaf3354001848eb8f55c85ed43\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sugan\AppData\Local\Temp\pip-install-z87xmfm9\pytorch_a2fb5beaf3354001848eb8f55c85ed43\setup.py", line 11, in <module>
        raise Exception(message)
    Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\sugan\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sugan\\AppData\\Local\\Temp\\pip-install-z87xmfm9\\pytorch_a2fb5beaf3354001848eb8f55c85ed43\\setup.py'"'"'; __file__='"'"'C:\\Users\\sugan\\AppData\\Local\\Temp\\pip-install-z87xmfm9\\pytorch_a2fb5beaf3354001848eb8f55c85ed43\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sugan\AppData\Local\Temp\pip-record-tpc1uo7i\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\sugan\AppData\Local\Programs\Python\Python310\Include\pytorch' Check the logs for full command output

C:\>pip install torch==1.0.2 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.0.2 (from versions: none)
ERROR: No matching distribution found for torch==1.0.2

**Comment by Sugandha14** [comment]
I have Python3.10 version installed. even a lowest version of pytorch 1.0.2 is not getting installed on my system.

**Comment by Sugandha14** [comment]
nevermind it worked on python version 3.9.7
