### ISSUE TITLE
Fails with Cuda 7.5 (driver 352.xx) 

### ISSUE THREAD

**Issue by arBest** [pytorch/pytorch#696]
Hi,

I installed the binaries via anaconda by doing a "conda install pytorch torchvision -c soumith" with python 2.7.x. It seems to default to require Cuda 8 and a higher version nvidia driver.  
The error I get when I run on Cuda 7.5 (traceback below), however works perfectly fine for me with Cuda 8 and driver version (367.xx).

Thanks,

>>> x.cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cbio/ski/fuchs/home/rajannaa/anaconda2/lib/python2.7/site-packages/torch/_utils.py", line 51, in _cuda
    return self.type(getattr(torch.cuda, self.__class__.__name__), async)
  File "/cbio/ski/fuchs/home/rajannaa/anaconda2/lib/python2.7/site-packages/torch/_utils.py", line 24, in _type
    return new_type(self.size()).copy_(self, async)
  File "/cbio/ski/fuchs/home/rajannaa/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 254, in __new__
    _lazy_init()
  File "/cbio/ski/fuchs/home/rajannaa/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 94, in _lazy_init
    _check_driver()
  File "/cbio/ski/fuchs/home/rajannaa/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 77, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError:
The NVIDIA driver on your system is too old (found version 7050).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org/binaries to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

**Comment by apaszke** [comment]
cc @soumith

**Comment by soumith** [comment]
are you running this in a docker environment? what i see is an error message complaining about driver version being too low, but if you installed cuda75 binaries, i see no reason that this error message should happen. 

can you also try: conda uninstall pytorch
and then reinstalling the cuda75 version.

**Comment by arBest** [comment]
I wasn't running in docker. And thanks @soumith, a higher driver version requirement was it.
