### ISSUE TITLE
DISABLED test_fs_pool (__main__.TestMultiprocessing)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#69659]
This test has been determined flaky through reruns in CI and its instances are reported in our flaky_tests table here https://metrics.pytorch.org/d/L0r6ErGnk/github-status?orgId=1&from=1636426818307&to=1639018818307&viewPanel=57.

```
======================================================================
FAIL [5.016s]: test_fs_pool (__main__.TestMultiprocessing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_multiprocessing.py", line 355, in test_fs_pool
    self._test_pool(repeat=TEST_REPEATS)
  File "test_multiprocessing.py", line 327, in _test_pool
    do_test()
  File "test_multiprocessing.py", line 206, in __exit__
    self.test_case.assertFalse(self.has_shm_files())
AssertionError: True is not false
```

Please look at the table for details from the past 30 days such as
* number of failed instances 
* an example url
* which platforms it failed on
* the number of times it failed on trunk vs on PRs.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @VitalyFedyunin

**Comment by janeyx99** [comment]
Looks like this was reported in https://github.com/pytorch/pytorch/issues/48579 before as well. This test is actually our top flaky test from the past ~15days with 52 failed instances.
