### ISSUE TITLE
DISABLED test_ddp_comparison (__main__.TensorPipeDdpComparisonTest)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#69662]
This test has been determined flaky through reruns in CI and its instances are reported in our flaky_tests table here https://metrics.pytorch.org/d/L0r6ErGnk/github-status?orgId=1&from=1636426818307&to=1639018818307&viewPanel=57.

It is our third flakiest test in the last ~15 days with 20 failed instances.

```
======================================================================
ERROR [105.071s]: test_ddp_comparison (__main__.TensorPipeDdpComparisonTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 458, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 677, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 729, in _check_return_codes
    i, elapsed_time
RuntimeError: Process 0 terminated or timed out after 105.05953598022461 seconds
```

Please look at the table for details from the past 30 days such as

* number of failed instances
* an example url
* which platforms it failed on
* the number of times it failed on trunk vs on PRs.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by janeyx99** [comment]
I noticed two issues with this test were closed 8 days ago, but a recent failure example can be found here: https://github.com/pytorch/pytorch/runs/4463714890?check_suite_focus=true from today 12/8/21
