### ISSUE TITLE
After updated to pytorch1.10.0 cuda11.1, NCCL is not available

### ISSUE THREAD

**Issue by housebaby** [pytorch/pytorch#69663]
I update the pytorch from 1.7 to 1.10, and met some nccl problem.

Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/storage15/huangying/tools/espnet-newest/egs2/AliMeeting/asr/espnet2/tasks/abs_task.py", line 1104, in main_worker
    distributed_option.init_torch_distributed()
  File "/home/storage15/huangying/tools/espnet-newest/egs2/AliMeeting/asr/espnet2/train/distributed_utils.py", line 96, in init_torch_distributed
    torch.distributed.init_process_group(
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 503, in init_process_group
    _update_default_pg(_new_process_group_helper(
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 597, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in

And when I print following option in python, it shows
 print(torch.distributed.is_nccl_available())
 False

**Comment by Ying091909** [comment]
@housebaby , hi, I met the same problem. How did you solve it?
