### ISSUE TITLE
[Torch testing] TypeError: Type List cannot be instantiated; use list() instead

### ISSUE THREAD

**Issue by jaglinux** [pytorch/pytorch#69669]
Observing TypeError after https://github.com/pytorch/pytorch/pull/68290 is merged.
When the test is run with IMPORT_DISABLED_TESTS and IMPORT_SLOW_TESTS not defined (else cases are triggered),
the test fails with below error.

Test command : python test/run_test.py -i distributed/test_distributed_spawn -v
Traceback (most recent call last):
  File "distributed/test_distributed_spawn.py", line 40, in <module>
    run_tests()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 611, in run_tests
    ['--import-slow-tests'] if IMPORT_SLOW_TESTS else List[str]([]))
  File "/opt/conda/lib/python3.6/typing.py", line 1888, in __new__
    raise TypeError("Type List cannot be instantiated; "
TypeError: Type List cannot be instantiated; use list() instead
Traceback (most recent call last):
  File "test/run_test.py", line 1041, in <module>
    main()
  File "test/run_test.py", line 1019, in main
    raise RuntimeError(err_message)
RuntimeError: distributed/test_distributed_spawn failed!

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by jaglinux** [comment]
cc @janeyx99

**Comment by jaglinux** [comment]
Issue is resolved through #69578 , closing the issue.
