### ISSUE TITLE
Nightly/release conda builds are failing

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#69683]
### 🐛 Describe the bug

See https://hud.pytorch.org/ci/pytorch/pytorch/nightly and https://hud.pytorch.org/ci/pytorch/pytorch/release/1.10

All conda builds are failing with the same pattern:
```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 480, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 469, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2135, in build
    m.parse_until_resolved(allow_no_other_outputs=True)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/metadata.py", line 1066, in parse_until_resolved
    self.parse_again(permit_undefined_jinja=True, allow_no_other_outputs=allow_no_other_outputs,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/metadata.py", line 1006, in parse_again
    self.meta = parse(self._get_contents(permit_undefined_jinja,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/metadata.py", line 1573, in _get_contents
    env.globals.update(environ.get_dict(m=self, skip_build_id=skip_build_id))
  File "/opt/conda/lib/python3.9/site-packages/conda_build/environ.py", line 280, in get_dict
    d.update(meta_vars(m, skip_build_id=skip_build_id))
  File "/opt/conda/lib/python3.9/site-packages/conda_build/environ.py", line 483, in meta_vars
    d.update(get_git_info(git_exe, git_dir, meta.config.debug))
  File "/opt/conda/lib/python3.9/site-packages/conda_build/environ.py", line 191, in get_git_info
    from conda._vendor.auxlib.packaging import _get_version_from_git_tag
ModuleNotFoundError: No module named 'conda._vendor.auxlib'
```

### Versions

Irrelevant here

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
`conda update conda-build` seem to fix it

**Comment by malfet** [comment]
Some explanation to what had happened.
By running
https://github.com/pytorch/builder/blob/da79c4c6aa17c61cf166314194940731218df51c/conda/build_pytorch.sh#L359
causes `conda` update which renders `cuda-build`, which is baked into docker image out of date and causes build failure.

More permanent fix should be to get rid of all `conda install` commands in the Linux codepath

**Comment by malfet** [comment]
Removing high priority as issue has been mitigated

**Comment by seemethere** [comment]
Marking this as triaged since it has mostly been resolved

**Comment by seemethere** [comment]
Nightly builds now work, closing
