### ISSUE TITLE
nightly: missing `THC/THCDeviceUtils.cuh`

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#69746]
**update: most likely not an issue with pytorch - I'm tracing it in a fork of Megatron-LM
https://github.com/microsoft/Megatron-DeepSpeed/**

### 🐛 Describe the bug

torch-nightly is missing `THC/THCDeviceUtils.cuh`

I was trying to build Megatron to check if it too suffers from missing symbols as reported here https://github.com/pytorch/pytorch/issues/69666 but it won't even build:

```
Detected CUDA files, patching ldflags
Emitting ninja build file /mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/build/build.ninja...
Building extension module fused_mix_prec_layer_norm_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/local/cuda-11.5/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_mix_prec_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/TH -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.5/include -isystem /home/stas/anaconda3/envs/py38-pt111/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -maxrregcount=50 -gencode arch=compute_80,code=sm_80 -std=c++14 -c /mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/layer_norm_cuda_kernel.cu -o layer_norm_cuda_kernel.cuda.o 
FAILED: layer_norm_cuda_kernel.cuda.o 
/usr/local/cuda-11.5/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_mix_prec_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/TH -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.5/include -isystem /home/stas/anaconda3/envs/py38-pt111/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -maxrregcount=50 -gencode arch=compute_80,code=sm_80 -std=c++14 -c /mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/layer_norm_cuda_kernel.cu -o layer_norm_cuda_kernel.cuda.o 
/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/layer_norm_cuda_kernel.cu:24:10: fatal error: THC/THCDeviceUtils.cuh: No such file or directory
   24 | #include <THC/THCDeviceUtils.cuh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

The issue is the same with pip and conda nightly packages. 

### Versions

```
PyTorch version: 1.11.0.dev20211208+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.21.3
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-90-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1070 Ti
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 495.29.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] torch==1.11.0.dev20211208+cu113
[pip3] torchaudio==0.11.0.dev20211209+cu113
[pip3] torchvision==0.12.0.dev20211209+cu113
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.1            py38hd3c417c_0
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] numpy-base                1.21.2           py38h79a1101_0
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torch                     1.11.0.dev20211208+cu113          pypi_0    pypi
[conda] torchaudio                0.11.0.dev20211209+cu113          pypi_0    pypi
[conda] torchvision               0.12.0.dev20211209+cu113          pypi_0    pypi
```

**Comment by stas00** [comment]
ok, after copying the missing include file manually, it fails in a bunch of new ways. 
```
/home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/ATen/cuda/DeviceUtils.cuh(109): error: function template "doLdg" has already been defined
```
the full log is below.

@jaredcasper, would it be possible for someone on your team at some point to work out the different breakages in pt-nightly for building Megatron? There is absolutely no urgency, I was just trying to check if Megatron has the same linker issue as reported here https://github.com/pytorch/pytorch/issues/69666 but found a bunch of new issues here so I could use it to check.

```
Detected CUDA files, patching ldflags
Emitting ninja build file /mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/build/build.ninja...
Building extension module fused_mix_prec_layer_norm_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/local/cuda-11.5/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_mix_prec_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/TH -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.5/include -isystem /home/stas/anaconda3/envs/py38-pt111/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -maxrregcount=50 -gencode arch=compute_80,code=sm_80 -std=c++14 -c /mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/layer_norm_cuda_kernel.cu -o layer_norm_cuda_kernel.cuda.o 
FAILED: layer_norm_cuda_kernel.cuda.o 
/usr/local/cuda-11.5/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_mix_prec_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/TH -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.5/include -isystem /home/stas/anaconda3/envs/py38-pt111/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -maxrregcount=50 -gencode arch=compute_80,code=sm_80 -std=c++14 -c /mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/layer_norm_cuda_kernel.cu -o layer_norm_cuda_kernel.cuda.o 
/home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/ATen/cuda/DeviceUtils.cuh(109): error: function template "doLdg" has already been defined

1 error detected in the compilation of "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/layer_norm_cuda_kernel.cu".
[2/3] c++ -MMD -MF layer_norm_cuda.o.d -DTORCH_EXTENSION_NAME=fused_mix_prec_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/TH -isystem /home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.5/include -isystem /home/stas/anaconda3/envs/py38-pt111/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/layer_norm_cuda.cpp -o layer_norm_cuda.o 
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1723, in _run_ninja_build
    subprocess.run(
  File "/home/stas/anaconda3/envs/py38-pt111/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pretrain_gpt.py", line 239, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 99, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/initialize.py", line 164, in initialize_megatron
    _compile_dependencies()
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/initialize.py", line 212, in _compile_dependencies
    fused_kernels.load(args)
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/__init__.py", line 88, in load
    fused_mix_prec_layer_norm_cuda = _cpp_extention_load_helper(
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/fused_kernels/__init__.py", line 47, in _cpp_extention_load_helper
    return cpp_extension.load(
  File "/home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1130, in load
    return _jit_compile(
  File "/home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1343, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1455, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1739, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_mix_prec_layer_norm_cuda'
Traceback (most recent call last):
  File "pretrain_gpt.py", line 239, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 99, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/initialize.py", line 164, in initialize_megatron
    _compile_dependencies()
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/initialize.py", line 215, in _compile_dependencies
    torch.distributed.barrier()
  File "/home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2767, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: [1] is setting up NCCL communicator and retreiving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer
[2021-12-09 19:06:57,258] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 1025869
[2021-12-09 19:06:57,259] [INFO] [launch.py:131:sigkill_handler] Killing subprocess 1025870
[2021-12-09 19:06:57,259] [ERROR] [launch.py:137:sigkill_handler] ['/home/stas/anaconda3/envs/py38-pt111/bin/python', '-u', 'pretrain_gpt.py', '--local_rank=1', '--tensor-model-parallel-size', '2', '--pipeline-model-parallel-size', '1', '--distributed-backend', 'nccl', '--num-layers', '2', '--hidden-size', '64', '--num-attention-heads', '2', '--seq-length', '1024', '--max-position-embeddings', '1024', '--micro-batch-size', '1', '--rampup-batch-size', '2', '2', '1_000', '--global-batch-size', '16', '--train-samples', '500', '--optimizer', 'adam', '--adam-beta1', '0.9', '--adam-beta2', '0.95', '--adam-eps', '1e-8', '--lr', '1e-4', '--lr-warmup-samples', '5', '--min-lr', '1e-6', '--lr-decay-style', 'cosine', '--lr-decay-samples', '12', '--override-lr-scheduler', '--clip-grad', '1.0', '--weight-decay', '1e-1', '--fp16', '--partition-activations', '--seed', '42', '--vocab-file', 'data/gpt2-vocab.json', '--merge-file', 'data/gpt2-merges.txt', '--exit-interval', '50', '--log-interval', '10', '--save-interval', '50', '--eval-interval', '100', '--eval-iters', '10', '--checkpoint-activations', '--save', 'checkpoints/gpt2', '--load', 'checkpoints/gpt2', '--data-path', 'data/meg-gpt2_oscar-combined_text_document', '--tensorboard-dir', 'output_dir/tensorboard', '--tensorboard-queue-size', '5', '--log-timers-to-tensorboard', '--log-batch-size-to-tensorboard', '--log-validation-ppl-to-tensorboard', '--deepspeed', '--deepspeed_config', './ds_config.json', '--zero-stage', '1', '--deepspeed-activation-checkpointing'] exits with return code = 1
```

**Comment by stas00** [comment]
OK, it looks like Megatron-Deepspeed fork is outdated then:

https://github.com/microsoft/Megatron-DeepSpeed/blob/acc3e9b5fab400912107c33fbcc9e0d02809dd6e/megatron/fused_kernels/layer_norm_cuda_kernel.cu#L24

since as @ngimel mentioned elsewhere it's not in Megatron-LM, 

https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/fused_kernels/layer_norm_cuda_kernel.cu#L24

Going to see where the fork got diverged. Probably didn't get updated when Megatron-LM got fixed.

**Comment by stas00** [comment]
ok, I replied the fixes from https://github.com/NVIDIA/Megatron-LM/commits/main/megatron/fused_kernels/layer_norm_cuda_kernel.cu to Megatron-DeepSpeed and the problem is gone! 

For posterity the key change is:
```
- #include <THC/THCDeviceUtils.cuh> 
+#include "ATen/cuda/DeviceUtils.cuh"
```

False alarm.

**Comment by ngimel** [comment]
This is weird, because we have THCDeviceUtils.cuh on master (never deleted it), and it is also in src/THC/CMakeLists.txt in `install`, in my local build I see it in torch/include/THC directory, so it's strange that it can't be found in nightlies.

**Comment by stas00** [comment]
It wasn't there before, it was placed there yesterday: https://github.com/pytorch/pytorch/pull/69039/files

**Comment by ngimel** [comment]
Yep, found it, so it'll appear in nightlies soon.

**Comment by malfet** [comment]
Which brings me back to my favorite topic: Is `THCDeviceUtils.cuh` ever supposed to be a public header or an implementation detail? If it was, then it should not have been deleted.

**Comment by ngimel** [comment]
We never had any explicit guarantees on which headers are public or not, so extension writers used whatever seemed good.

**Comment by stas00** [comment]
You appear to be correct, these definitions from `THC/THCDeviceUtils.cuh` aren't in  `ATen/cuda/DeviceUtils.cuh` 

I'd say open a new Issue and to do asap before 1.11 brach is frozen.

This issue was discussing a missing header. You've found that the new header is missing definitions from the old header it replaced.

**Comment by stas00** [comment]
How can a user find the aforementioned PRs?

**Comment by ngimel** [comment]
They will be listed in 1.11 release notes. We've worked with popular extensions to proactively update them at the time the PRs went in. People encountering issues with nightlies are welcome to open issues (and did so), the replacement APIs have been available for a long time, so it's not a question of complicated #ifdef logic, the calls just should be replaced.

**Comment by stas00** [comment]
Could you please quantify "for a long time"? e.g. Deepspeed currently supports pt-1.2.

I guess the same question I asked here https://github.com/pytorch/pytorch/issues/60149 wrt pytorch python API needs to be extended for c++ API.

**Comment by an99990** [comment]
thanks @stas00 and @ngimel .
I was able to build.
