### ISSUE TITLE
Error exporting TorchScript model to ONNX - “ Module contains attributes values that overlaps”

### ISSUE THREAD

**Issue by alealv** [pytorch/pytorch#69842]
I've already [posted](https://stackoverflow.com/posts/68320251/edit) this error in StackOverflow and in the [PyTorch forum](https://discuss.pytorch.org/t/error-when-exporting-torchscript-model-to-onnx-runtimeerror-module-contains-attributes-values-that-overlaps/126379) some months ago but I received no answer.

## Issue description
I'm trying to export a (working) *streaming* TorchScript model to ONNX but run into some issues.

I emphasize the streaming implying it has some control flow, hence it requires to be exported as `torch.jit.script` AFAIK.

```python
...
    with torch.no_grad():
        stream_generator = StreamGenerator(training_config)
        stream_generator.load_state_dict(state_dict_sg)
        stream_generator.to(precision)
        script_model = torch.jit.script(stream_generator)

        # ONNX
        torch.onnx.export(
            model=script_model,
            args=(data, {'is_final': True}),
            f="stream_vocoder.onnx",
            export_params=True,
            opset_version=13,
            do_constant_folding=True,
            input_names=['data', 'is_final'],
            output_names=['audio'],
            dynamic_axes={'data': {0: 'batch_size'},
                          'audio': {0: 'batch_size'}},
            verbose=True,
        )

        # Check
        onnx_model = onnx.load("stream_vocoder.onnx")
        onnx.checker.check_model(onnx_model)
```

 The problem is I get this **RuntimeError**

```bash
Traceback (most recent call last):
  File "onnx_conversion.py", line 78, in <module>
    torch.onnx.export(
  File "/home/aalvarez/.virtualenvs/tts-inference-comp-klfduu67-py3.8/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/aalvarez/.virtualenvs/tts-inference-comp-klfduu67-py3.8/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/aalvarez/.virtualenvs/tts-inference-comp-klfduu67-py3.8/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/aalvarez/.virtualenvs/tts-inference-comp-klfduu67-py3.8/lib/python3.8/site-packages/torch/onnx/utils.py", line 458, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args,
  File "/home/aalvarez/.virtualenvs/tts-inference-comp-klfduu67-py3.8/lib/python3.8/site-packages/torch/onnx/utils.py", line 401, in _create_jit_graph
    freezed_m = torch._C._freeze_module(model._c, preserveParameters=True)
RuntimeError: module contains attributes values that overlaps [ 0
[ torch.LongTensor{1} ],  0
[ torch.LongTensor{1} ],  0
[ torch.LongTensor{1} ]]
```

I look for the error and found this https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/freeze_module.cpp#L348

I don't know where to start looking in order to solve this. Does someone know how to fix this or a walkaround it?nv.py
```

- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): pip install torch
- Build command you used (if compiling from source):
- OS: Linux ml-2 5.4.0-71-generic #79-Ubuntu SMP Wed Mar 24 10:56:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- PyTorch version: 1.10.0
- Python version: 3.8.10
- CUDA/cuDNN version: 11.3.1-1
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by fatcat-z** [comment]
This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1567964.

**Comment by alealv** [comment]
Hi, any news about this?

I recently came back to this and found that when running `optimized_for_inference` I get the same error.

```python
In [6]: script_stream_generator = torch.jit.script(stream_generator)
In [7]: torch.jit.optimize_for_inference(script_stream_generator)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-71f909dc8eb3> in <cell line: 1>()
----> 1 torch.jit.optimize_for_inference(script_stream_generator)

~/.virtualenvs/tts-train-XZ1ykfT_-py3.10/lib/python3.10/site-packages/torch/jit/_freeze.py in optimize_for_inference(mod, other_methods)
    214
    215     if hasattr(mod, "training"):
--> 216         mod = freeze(mod.eval(), preserved_attrs=other_methods)
    217
    218     torch._C._jit_pass_optimize_for_inference(mod._c, other_methods)

~/.virtualenvs/tts-train-XZ1ykfT_-py3.10/lib/python3.10/site-packages/torch/jit/_freeze.py in freeze(mod, preserved_attrs, optimize_numerics)
    113     preserved_attrs = preserved_attrs if preserved_attrs is not None else []
    114
--> 115     out = RecursiveScriptModule(torch._C._freeze_module(mod._c, preserved_attrs))
    116     RecursiveScriptModule._finalize_scriptmodule(out)
    117

RuntimeError: module contains attributes values that overlaps [ 0
[ torch.LongTensor{1} ],  0
[ torch.LongTensor{1} ],  0
[ torch.LongTensor{1} ]]
```

I started debugging the Model by commenting out sections until I hit the error. Finally I discover that the problem was around the `torch.cat()` function.
This is the piece of code failing.
```python
     def forward(self, x: Tensor) -> Tensor:
         if self.is_first_iteration():
             self.state_xt = [torch.empty((x.shape[0], x.shape[1], 0))] * len(self.convs)
             self.state_x = [torch.empty((x.shape[0], x.shape[1], 0))] * len(self.convs)
 
         for idx, c in enumerate(self.convs):
             xt = F.leaky_relu(x, self.LRELU_SLOPE)
             xt = c(xt, self.is_last())
             x = torch.cat([self.state_x[idx], x], dim=-1)
             xt = torch.cat([self.state_xt[idx], xt], dim=-1)
```

### Solution
I think the problem was the concatenation with an empty Tensor. The solution was quite simple:

```diff
     def stream_forward(self, x: Tensor) -> Tensor:
-        if self.is_first():
-            self.state_xt = [torch.empty((x.shape[0], x.shape[1], 0))] * len(self.convs)
-            self.state_x = [torch.empty((x.shape[0], x.shape[1], 0))] * len(self.convs)
-
         for idx, c in enumerate(self.convs):
             xt = F.leaky_relu(x, self.LRELU_SLOPE)
             xt = c(xt, self.is_last())

-            x = torch.cat([self.state_x[idx], x], dim=-1)
-            xt = torch.cat([self.state_xt[idx], xt], dim=-1)
+            if not self.is_first():
+                x = torch.cat([self.state_x[idx], x], dim=-1)
+                xt = torch.cat([self.state_xt[idx], xt], dim=-1)

             # Actually XT will be always equal or shorter than X
             min_len = min(xt.shape[-1], x.shape[-1])
```


## New error
With the previous `torch.jit.optimize_for_inference(script_stream_generator)` works just fine. But now a I have a new error when exporting to ONNX.

```python
> $(poetry env info -p)/bin/python vocoder/export.py exp/hifi-gan/checkpoints/best.ckpt exp/hifi-gan/hifi-gan_stream_generator.onnx --type onnx --method script --stream
Traceback (most recent call last):
  File "/home/aalvarez/Projects/main/apps/tts-train/vocoder/export.py", line 58, in <module>
    main()
  File "/home/aalvarez/Projects/main/apps/tts-train/vocoder/export.py", line 45, in main
    model.to_onnx(
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.10/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/aalvarez/Projects/main/apps/tts-train/vocoder/hifi_gan/__init__.py", line 376, in to_onnx
    torch.onnx.export(model=generator, args=input_sample, f=file_path, **kwargs)
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.10/lib/python3.10/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.10/lib/python3.10/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.10/lib/python3.10/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.10/lib/python3.10/site-packages/torch/onnx/utils.py", line 727, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.10/lib/python3.10/site-packages/torch/onnx/utils.py", line 587, in _create_jit_graph
    graph = _C._propagate_and_assign_input_shapes(
RuntimeError: input_values.size() == param_count_list.size() INTERNAL ASSERT FAILED at "../torch/csrc/jit/python/script_init.cpp":489, please report a bug to PyTorch.
```

Which is related to https://github.com/pytorch/pytorch/issues/72763

**Comment by justinchuby** [comment]
Does the error persist when you use the latest pytorch nightly build?

**Comment by justinchuby** [comment]
Closing since there is no movement. Please feel free to open a new issue if you still see it!
