### ISSUE TITLE
Forward-over-reverse gradgradcheck fails for `torch.gradient` on CUDA

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#69925]
### 🐛 Describe the bug

To replicate: Remove the `expectedFailure` decorator for `test_fn_fwgrad_bwgrad` in `gradient`'s OpInfo
At of time of posting: only fails on this branch #69740

```
======================================================================
ERROR: test_fn_fwgrad_bwgrad_gradient_cuda_complex128 (__main__.TestGradientsCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/pytorch4/torch/testing/_internal/common_utils.py", line 1482, in wrapper
    method(*args, **kwargs)
  File "/local/pytorch4/torch/testing/_internal/common_utils.py", line 1482, in wrapper
    method(*args, **kwargs)
  File "/local/pytorch4/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    raise rte
  File "/local/pytorch4/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/local/pytorch4/torch/testing/_internal/common_device_type.py", line 753, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 827, in test_fn_fwgrad_bwgrad
    self._check_helper(device, dtype, op, op.get_op(), "fwgrad_bwgrad")
  File "test/test_ops.py", line 776, in _check_helper
    self.assertTrue(gradgradcheck(fn, gradcheck_args, **kwargs))
  File "/local/pytorch4/torch/testing/_internal/common_utils.py", line 2893, in gradgradcheck
    return torch.autograd.gradgradcheck(fn, inputs, grad_outputs, **kwargs)
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1544, in gradgradcheck
    return gradcheck(
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1398, in gradcheck
    return _gradcheck_helper(**args)
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1412, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1068, in _gradcheck_real_imag
    gradcheck_fn(imag_fn, imag_func_out, imag_inputs, diff_imag_func_out, eps,
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1281, in _fast_gradcheck
    analytical_vJu = _get_analytical_jacobian_forward_ad(func, inputs, _as_tuple(func_out),
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 343, in _get_analytical_jacobian_forward_ad
    raw_outputs = _as_tuple(fn(*dual_inputs))
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1030, in wrapped_fn
    return _as_tuple(fn(*new_inputs))
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1539, in new_func
    grad_inputs = torch.autograd.grad(outputs, input_args, grad_outputs, create_graph=True,
  File "/local/pytorch4/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

```

### Versions

At of time of posting: only fails on this branch #69740
Once that has been landed: should be able to replicate on main branch

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by jeffdaily** [comment]
Is this related to #70027?  I've been trying to debug it and it seems perhaps ZeroTensor is involved.

**Comment by soulitzer** [comment]
@anjali411 maybe https://github.com/pytorch/pytorch/issues/71160 is related?

**Comment by jeffdaily** [comment]
Why do we have `add_zerotensor` and `mul_zerotensor`, but no `div_zerotensor`?  I added it, and it seems to fix the rocm tests.  No more mem access fault.

**Comment by anjali411** [comment]
yeah #71160 will fix this issue. This issue is being caused because the CUDA dispatch key is not correctly set on EZTs creating with cuda device

**Comment by anjali411** [comment]
@jeffdaily yeah we could certainly add a fastpath for div as well. Here is a complete list of ops that can benefit from the fastpath in the JVP computation: https://github.com/pytorch/pytorch/issues/69687

**Comment by jeffdaily** [comment]
I added `div_zerotensor` in PR #71862.  Waiting for CI to finish.  It did resolve the rocm failures.

**Comment by anjali411** [comment]
fixed by https://github.com/pytorch/pytorch/pull/71611
