### ISSUE TITLE
[pytorch] Not handling python reload properly

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#6998]
Trying to reload some modules cause crashes:

On python 2.7 (crash with ubuntu release, error messages from debug build).

```
>>> import torch
>>> reload(torch)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alban/workspace/dev-pytorch/torch/__init__.py", line 288, in <module>
    from . import _torch_docs, _tensor_docs, _storage_docs
ImportError: cannot import name _torch_docs
>>> exit()
python: ../Objects/typeobject.c:2739: type_dealloc: Assertion `type->tp_flags & (1L<<9)' failed.
Aborted (core dumped)
```

```
>>> from torch import autograd
>>> reload(autograd)
terminate called after throwing an instance of 'std::runtime_error'
  what():  generic_type: cannot initialize type "ProfilerEvent": an object with that name is already defined
Aborted (core dumped)
```

@colesbury can you see an obvious reason for this? Or should I look into more details?

**Comment by apaszke** [comment]
We use static C++ state in a bunch of places, and restarting the interpreter doesn't cause a full destruct -> construct cycle. That's probably what's causing the segfault.

**Comment by GalAvineri** [comment]
I have just encountered this issue as well. Is there a workaround for the mean while?
I tried uninstalling and reinstalling torch but the issue remains.
I tried to create a new virtualenv and install torch there, but the issue still persists.
Do you have an suggestion to how work around this issue?

**Comment by albanD** [comment]
Hi,

There is no workaround at the moment unfortunately.
Could you explain what is your usecase? and why you need to reload pytorch?

**Comment by GalAvineri** [comment]
I deleted my comment because it seemed that my error was caused due to some error on my side.
I'm not entirely sure what caused it, but I believe that due to bad refractoring some import statements included import of the __init__ file.
For example, if i remember correctly, there were these import statements:
'''from torch.__init__ import <something>'''
'''from torch.autograd import __init__"

Once i deleted those the issue disappeared :) 
So I thought it was better if i'll delete my comment here.

**Comment by Almenon** [comment]
This is still an error with python 3, but now the exception is different:

```
C:\Users\almenon>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from importlib import reload
>>> reload(torch)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\caleb\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\caleb\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 67, in <module>
    if all([not os.path.exists(os.path.join(p, 'nvToolsExt64_1.dll')) for p in dll_paths]):
TypeError: all(): argument 'input' (position 1) must be Tensor, not list
```

Windows 10, python 3.6.4. Packages are below:
```
torch==1.8.1+cu102
torchvision==0.9.1+cu102
torchaudio===0.8.1
-f https://download.pytorch.org/whl/torch_stable.html
numpy==1.19.5
```
