### ISSUE TITLE
asdf

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#69991]
### 🚀 The feature, motivation and pitch

asdf

### Alternatives

asdf

### Additional context

asdf

**Comment by Lezcano** [comment]
Are the linalg operators going to be fixed once this PR is merged https://github.com/pytorch/pytorch/pull/69437 ?

**Comment by zou3519** [comment]
> Are the linalg operators going to be fixed once this PR is merged #69437 ?

That will fix linalg.{matrix_power, inv, and cholesky} but not the other ones

**Comment by Lezcano** [comment]
Are the other cases failing because of the same `checkErrors` problem and need to be ported to the fix in that PR, or because of other reasons?

**Comment by zou3519** [comment]
Other reasons. I haven't looked into all of them yet, but as an example, norm / linalg.norm end up calling frobenius_norm: https://github.com/pytorch/pytorch/blob/fe7b6446d52e6322d9c1ceec4940f5c13c66f779/aten/src/ATen/native/LinearAlgebra.cpp#L2287-L2293 
which ends up calling frobenius_norm_out:
https://github.com/pytorch/pytorch/blob/fe7b6446d52e6322d9c1ceec4940f5c13c66f779/aten/src/ATen/native/LinearAlgebra.cpp#L2320-L2321
and that calls .resize_() and .copy_(). The resize_ and copy_ are problematic because if the input to frobenius_norm is a Tensor subclass, then we end up doing `regular_tensor.resize_(shape).copy_(TensorSubclass)`.

In general a CompositeImplicitAutograd operation shouldn't be calling _out variants for functions because it can result in problems like this; but we have a few different options to fix it:
1. Rewrite the out-of-place versions of norm / linalg.norm to not call _out variants
2. write a backward formula for norm / linalg.norm / or something else (e.g. make these non-composite)
3. This is kind of messy but one can guard calls to problematic operations with areAnyTensorSubclassLike from https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/TensorSubclassLikeUtils.h#L6

**Comment by pearu** [comment]
Are there any plans for supporting operators on sparse tensors as composite compliment operators?
Currently, testing the composite compliance of operators having sparse samples fail:
```
Traceback (most recent call last):
  File "/home/pearu/git/pytorch/pytorch/test/test_ops.py", line 689, in test_composite_compliance
    _check_composite_compliance(op, args, kwargs)
  File "/home/pearu/git/pytorch/pytorch/torch/testing/_internal/composite_compliance.py", line 185, in _check_composite_compliance
    kwargs = tree_map(wrap, kwargs)
  File "/home/pearu/git/pytorch/pytorch/torch/utils/_pytree.py", line 179, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/home/pearu/git/pytorch/pytorch/torch/utils/_pytree.py", line 179, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/home/pearu/git/pytorch/pytorch/torch/testing/_internal/composite_compliance.py", line 182, in wrap
    return CompositeCompliantTensor(e) if isinstance(e, torch.Tensor) else e
  File "/home/pearu/git/pytorch/pytorch/torch/testing/_internal/composite_compliance.py", line 110, in __new__
    strides=elem.stride(), storage_offset=elem.storage_offset())
RuntimeError: sparse tensors do not have strides
```
Same error is produced in https://github.com/pytorch/pytorch/runs/4795703604, for instance.

**Comment by zou3519** [comment]
> Are there any plans for supporting operators on sparse tensors as composite compliment operators?
> Currently, testing the composite compliance of operators having sparse samples fail:

We should opt-out operations on sparse tensors for this for now

**Comment by zou3519** [comment]
In terms of priority:
- tensor_split, ctc_loss seem actionable
- as_strided_scatter -> only used in functionalization, so is lower-pri. We should try to make it composite compliant if it's not too difficult.
- The "computation diverges" things -- this is not easily solvable, so we should punt these to the future.


After the first two items are complete we can lower the priority on this
