### ISSUE TITLE
Destructing objects holding CUDA resources

### ISSUE THREAD

**Issue by singam-sanjay** [pytorch/pytorch#7001]
I need to maintain multiple instances of the FusionCompiler class and have created an `unordered_map<size_t,shared_ptr<FusionCompiler>>` to accomplish the same.

On calling `exit()` from Python, the destructor of the `FusionCompiler` object is invoked and that in turn invokes the destructor of the `CompiledFunction`s in the compile cache.
https://github.com/pytorch/pytorch/blob/2b44c420c8e61501ef04a5e4af2347ecc3c86202/torch/csrc/jit/fusion_compiler.h#L151
The destructor attempts to unload the compiled module.
https://github.com/pytorch/pytorch/blob/2b44c420c8e61501ef04a5e4af2347ecc3c86202/torch/csrc/jit/fusion_compiler.cpp#L535
In my case, the destructor fails due to the absence of the CUDA runtime,
```
#8  0x00007fffeca4b451 in torch::cuCheck (result=CUDA_ERROR_DEINITIALIZED, ...
#9  0x00007fffeca4ee7f in torch::jit::compiler::CompiledFusionFunction::~CompiledFusionFunction (this=0x55559ac5b720, ...
```

I recreated this behaviour by having an object hold on to `cudaEvent`s and `cudaEventDestroy`ing them in the destructor. Other people have faced [similar issues and NVIDIA seems to discourage the practice](https://devtalk.nvidia.com/default/topic/1019780/cuda-run-time-library-unload/) of deallocating resources in the destructors.

How did PyTorch get around this issue ?

**Comment by apaszke** [comment]
Hmmm we don't really do anything special. I think the errors are not so much about releasing resources in destructors, but about releasing them only once static objects are destructed (this happens after the driver is unloaded and causes an error). However, we do use a [`static FusionCompiler`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/fusion_compiler.cpp#L799) in our code and it has been ok so far.

I think everything should be fine if only you moved the actual map into the body of a function (as a non-static variable), and then you can keep a
```
static unordered_map<size_t,shared_ptr<FusionCompiler>>* map_ptr;
```
if you don't want to pass it around.
