### ISSUE TITLE
ROCM device not found

### ISSUE THREAD

**Issue by oliverguhr** [pytorch/pytorch#70036]
### 🐛 Describe the bug

Hello,
I installed rocm  4.2 according to the documentation. The GPU is recognized by the rocm tooling. However, pytorch does not detect the GPU.

```
>>>import torch 
>>> torch.tensor([0]).to("cuda")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oli/source/experiment/amd-test/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 214, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available
```

```
>>>import torch 
>>>torch.tensor([0]).to("hip")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: HIP error: hipErrorNoDevice
HIP kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing HIP_LAUNCH_BLOCKING=1.
```

### Versions

I am running Python 3.8.10. I installed pytorch in a virtual env today with this command:
```
pip3 install torch torchvision==0.11.2 -f https://download.pytorch.org/whl/rocm4.2/torch_stable.html
```
ROCM is at 4.2.0.40200-21
```
$apt show rocm-libs -a   
Package: rocm-libs
Version: 4.2.0.40200-21
```

unfortunately running collect_env.py fails with

```
python3 collect_env.py
Collecting environment information...
Traceback (most recent call last):
  File "collect_env.py", line 469, in <module>
    main()
  File "collect_env.py", line 452, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 447, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 309, in get_env_info
    hip_runtime_version = [s.rsplit(None, 1)[-1] for s in cfg if 'HIP Runtime' in s][0]
IndexError: list index out of range

```

running rocminfo gives me:

```
sudo /opt/rocm/bin/rocminfo
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 7 1700 Eight-Core Processor
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 7 1700 Eight-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3000                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            16                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    32877948(0x1f5ad7c) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    32877948(0x1f5ad7c) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    32877948(0x1f5ad7c) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx803                             
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon (TM) RX 480 Graphics    
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26591(0x67df)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1310                               
  BDFID:                   2048                               
  Internal Node ID:        1                                  
  Compute Unit:            36                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8388608(0x800000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***   
```

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by gohjiayi** [comment]
Facing the same issue, any updates so far?

**Comment by sunghwan-choi** [comment]
any updates? 
my server includes 8 AMD GPUs and they properly work.

```
$ rocm-smi


======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp   AvgPwr  SCLK    MCLK     Fan  Perf  PwrCap  VRAM%  GPU%
0    31.0c  34.0W   800Mhz  1600Mhz  0%   auto  300.0W    0%   0%
1    34.0c  34.0W   800Mhz  1600Mhz  0%   auto  300.0W    0%   0%
2    32.0c  34.0W   800Mhz  1600Mhz  0%   auto  300.0W    0%   0%
3    31.0c  37.0W   800Mhz  1600Mhz  0%   auto  300.0W    0%   0%
4    32.0c  34.0W   800Mhz  1600Mhz  0%   auto  300.0W    0%   0%
5    36.0c  34.0W   800Mhz  1600Mhz  0%   auto  300.0W    0%   0%
6    33.0c  34.0W   800Mhz  1600Mhz  0%   auto  300.0W    0%   0%
7    35.0c  34.0W   800Mhz  1600Mhz  0%   auto  300.0W    0%   0%
================================================================================
============================= End of ROCm SMI Log ==============================
```

Using pip, I installed pytorch 

```

$ pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm4.5.2
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/rocm4.5.2
Collecting torch
  Downloading https://download.pytorch.org/whl/rocm4.5.2/torch-1.11.0%2Brocm4.5.2-cp39-cp39-linux_x86_64.whl (1412.2 MB)
     |████████████████████████████████| 1412.2 MB 83 kB/s
Collecting torchvision
  Downloading https://download.pytorch.org/whl/rocm4.5.2/torchvision-0.12.0%2Brocm4.5.2-cp39-cp39-linux_x86_64.whl (66.4 MB)
     |████████████████████████████████| 66.4 MB 734 kB/s
Collecting typing-extensions
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting requests
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 190 kB/s
Collecting numpy
  Downloading numpy-1.22.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     |████████████████████████████████| 16.8 MB 2.2 MB/s
Collecting pillow!=8.3.*,>=5.3.0
  Downloading Pillow-9.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 102.6 MB/s
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 82.8 MB/s
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Requirement already satisfied: certifi>=2017.4.17 in ./env/mi200/lib/python3.9/site-packages (from requests->torchvision) (2022.5.18.1)
Installing collected packages: urllib3, typing-extensions, idna, charset-normalizer, torch, requests, pillow, numpy, torchvision
Successfully installed charset-normalizer-2.0.12 idna-3.3 numpy-1.22.4 pillow-9.1.1 requests-2.27.1 torch-1.11.0+rocm4.5.2 torchvision-0.12.0+rocm4.5.2 typing-extensions-4.2.0 urllib3-1.26.9
```

but my python fails to get GPU... 

```
$ python
Python 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available() and torch.version.hip
False
```

**Comment by arindamroy-eng** [comment]
Single script to properly install all libs (for ROCM 5.1.1)
https://docs.amd.com/bundle/ROCm-Downloads-Guide-v5.1.1/page/Access_Installer_AMDGPU_ROCm_Stack_Remote_Repositories.html

amdgpu-install --usecase=rocm

**Comment by long2ice** [comment]
@sunghwan-choi, same here, did you resolve that?

**Comment by long2ice** [comment]
It's OK if I use docker image

**Comment by long2ice** [comment]
update: add my user to video and render group resolved, hope help someone

**Comment by pruthvistony** [comment]
Please check the below link for critical system configuration on host
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#setting-permissions-for-groups

**Comment by aurooj** [comment]
> https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#setting-permissions-for-groups

How did you resolve this issue?

**Comment by pruthvistony** [comment]
@aurooj ,
The username needs to be video and render groups to get access to AMD GPU driver on each host machine. 
Were you not able to do this? Can you give more details on your problem?

**Comment by damico** [comment]
I just made a python code that tests PyTorch support for AMD GPUs with ROCM: https://gist.github.com/damico/484f7b0a148a0c5f707054cf9c0a0533

**Comment by hongxiayang** [comment]
The solution is proposed "The username needs to be video and render groups to get access to AMD GPU driver on each host machine." . @oliverguhr  Please verify it and then close this issue.

**Comment by oliverguhr** [comment]
@hongxiayang I added my user to both groups back then, but it did not work. However, I don't have this GPU anymore and cannot reproduce this error. So I close this issue.

**Comment by LucianoRodriguez0764** [comment]
> update: add my user to video and render group resolved, hope help someone

AND REMEMBER TO REBOOT SO THE CHANGES CAN APPLY!
