### ISSUE TITLE
[Caffe2] LT and GT cannot be exported to ONNX

### ISSUE THREAD

**Issue by rillomas** [pytorch/pytorch#7020]
When I try to export a simple network using LT (or GT) to ONNX, I get the following error:

## Error log
```
Traceback (most recent call last):
...
  File "/home/masato/repo/pytorch/build/caffe2/python/onnx/frontend.py", line 346, in caffe2_net_to_onnx_model
    model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
  File "/home/masato/repo/pytorch/build/caffe2/python/onnx/frontend.py", line 262, in caffe2_net_to_onnx_graph
    checker.check_graph(graph_def)
  File "/home/masato/repo/onnx/onnx/checker.py", line 45, in checker
    proto.SerializeToString(), ctx)
onnx.onnx_cpp2py_export.checker.ValidationError: No Schema registered for LT with domain_version of 6

==> Context: Bad node spec: input: "in_data_0" input: "bias_0" output: "out_data_1" name: "" op_type: "LT
```

## Sample Code

```python
#!/usr/bin/env python
import onnx
import caffe2.python.onnx.frontend as oc2f
import caffe2.python.predictor.predictor_exporter as pe
import caffe2.python.predictor.mobile_exporter as c2me
from caffe2.python import model_helper, workspace, brew, utils
IN_DATA_NAME = "in_data"
IN_BIAS_NAME = "bias"
OUT_DATA_NAME = "out_data"

WIDTH = 3
HEIGHT = 4
CHAN = 2
AXIS = 1
DATA_SHAPE = (1, CHAN, HEIGHT, WIDTH)

model = model_helper.ModelHelper(name="less_net")
model.net.LT([IN_DATA_NAME, IN_BIAS_NAME], OUT_DATA_NAME)
model.param_init_net.UniformFill([], IN_DATA_NAME, shape=DATA_SHAPE)
model.param_init_net.UniformFill([], IN_BIAS_NAME, shape=DATA_SHAPE)
workspace.RunNetOnce(model.param_init_net)

init_net, predict_net = c2me.Export(workspace, model.net, [IN_DATA_NAME, IN_BIAS_NAME])

value_info = {
}
onnx_model = oc2f.caffe2_net_to_onnx_model(
        predict_net,
        init_net,
        value_info)
onnx.checker.check_model(onnx_model)
print(onnx_model)
outname = "less_no_broadcast.onnx"
with open(outname, 'wb') as f:
    f.write(onnx_model.SerializeToString())
```

## Possible Fix?
If I change Caffe2 like the following, it works.

```diff
diff --git a/caffe2/python/onnx/frontend.py b/caffe2/python/onnx/frontend.py
index c96b86143..b5106d337 100644
--- a/caffe2/python/onnx/frontend.py
+++ b/caffe2/python/onnx/frontend.py
@@ -54,6 +54,8 @@ class Caffe2Frontend(object):
         'AveragePool1D': 'AveragePool',
         'AveragePool2D': 'AveragePool',
         'AveragePool3D': 'AveragePool',
+        'LT': 'Less',
+        'GT': 'Greater',
     }

     # caffe2 arguments that are completely removed in onnx
```

## System Info
- OS: Ubuntu 16.04.4 x86_64
- pytorch: 2e156f3eabb6fa4ae88c2e831aea7da344cf43a3
- onnx: b8c423889b3d15825e90fd5bd8fa1766ba2200ce
- Python: 3.5.2

**Comment by rillomas** [comment]
The same issue goes to `EQ` and `Equal`

**Comment by yinghai** [comment]
@houseroad Do we have ONNX node for `LT` or `GT`?

**Comment by garymm** [comment]
This is not related to torch.onnx, so removing `module: onnx`
