### ISSUE TITLE
[nn] LSTMCell grad failure.

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#70362]
### 🐛 Describe the bug

The grad and gradgrad test fails when adding ModuleInfo for `LSTMCell`.

Reference PR : https://github.com/pytorch/pytorch/pull/70236

```
________________________________________________________________________________ TestModuleCPU.test_grad_nn_LSTMCell_cpu_float64 _________________________________________________________________________________
Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/pytorch_no_batch_rnncells/test/test_modules.py", line 446, in test_grad
    self._test_gradients_helper(device, dtype, module_info, gradcheck)
  File "/home/kshiteej/Pytorch/pytorch_no_batch_rnncells/test/test_modules.py", line 441, in _test_gradients_helper
    self.assertTrue(check(fn_to_gradcheck, grad_input))
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2957, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1398, in gradcheck
    return _gradcheck_helper(**args)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1412, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1057, in _gradcheck_real_imag
    gradcheck_fn(func, func_out, tupled_inputs, outputs, eps,
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1287, in _fast_gradcheck
    analytical_vJu = _get_analytical_vJu_backward_mode(inputs, outputs, nondet_tol, check_grad_dtypes, all_v, all_u_dense)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 555, in _get_analytical_vJu_backward_mode
    all_vJ = _check_analytical_jacobian_attributes(inputs, output, nondet_tol, check_grad_dtypes,
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 535, in _check_analytical_jacobian_attributes
    jacobians1, types_ok, sizes_ok = _stack_and_check_tensors(vjps1, inputs, output_numel)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 492, in _stack_and_check_tensors
    assert out_jacobian[:, j].numel() == dense.numel()
AssertionError

______________________________________________________________________________ TestModuleCPU.test_gradgrad_nn_LSTMCell_cpu_float64 _______________________________________________________________________________
Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/pytorch_no_batch_rnncells/test/test_modules.py", line 451, in test_gradgrad
    self._test_gradients_helper(device, dtype, module_info, gradgradcheck)
  File "/home/kshiteej/Pytorch/pytorch_no_batch_rnncells/test/test_modules.py", line 441, in _test_gradients_helper
    self.assertTrue(check(fn_to_gradcheck, grad_input))
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2977, in gradgradcheck
    return torch.autograd.gradgradcheck(fn, inputs, grad_outputs, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1544, in gradgradcheck
    return gradcheck(
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1398, in gradcheck
    return _gradcheck_helper(**args)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1412, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1057, in _gradcheck_real_imag
    gradcheck_fn(func, func_out, tupled_inputs, outputs, eps,
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1287, in _fast_gradcheck
    analytical_vJu = _get_analytical_vJu_backward_mode(inputs, outputs, nondet_tol, check_grad_dtypes, all_v, all_u_dense)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 555, in _get_analytical_vJu_backward_mode
    all_vJ = _check_analytical_jacobian_attributes(inputs, output, nondet_tol, check_grad_dtypes,
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 535, in _check_analytical_jacobian_attributes
    jacobians1, types_ok, sizes_ok = _stack_and_check_tensors(vjps1, inputs, output_numel)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 492, in _stack_and_check_tensors
    assert out_jacobian[:, j].numel() == dense.numel()
AssertionError
```

### Versions

master

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by kshitij12345** [comment]
Repro:
```python
import torch
import torch.nn as nn

torch.set_default_dtype(torch.double)

rnn = nn.LSTMCell(10, 20)
input = torch.randn(3, 10, requires_grad=True)
hx = (torch.randn(3, 20, requires_grad=True), torch.randn(3, 20, requires_grad=True))

# Works
p = tuple(rnn.parameters())
inp = (input,) + hx + p

def fn(*inp):
    (input, hx_0, hx_1) = inp[:3]
    return rnn(input, (hx_0, hx_1))

torch.autograd.gradcheck(fn, inp)

# Doesn't work (the way gradcheck in test_modules passes it's inputs)
p = tuple(rnn.parameters())
inp = (input, hx) + p

def fn(*inp):
    (input, hx) = inp[:2]
    return rnn(input, hx)

torch.autograd.gradcheck(fn, inp)

```

cc: @jbschlosser
