### ISSUE TITLE
"INTERNAL ASSERT FAILED" in torchmetrics.Accuracy#_accuracy_compute

### ISSUE THREAD

**Issue by cschell** [pytorch/pytorch#70426]
### 🐛 Describe the bug

After upgrading to PyTorch 1.10.1 from 1.7.1 I get the following error during training, more specifically during a call that boils down to `torchmetrics.Accuracy(average="none", num_classes=34).compute()`:

```
Traceback (most recent call last):
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/cs/code/uaixdlamds/run.py", line 30, in main
    return train(config)
  File "/home/cs/code/uaixdlamds/src/train.py", line 125, in train
    trainer.fit(model=identifier, datamodule=datamodule)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit
    self._call_and_handle_interrupt(
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 683, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 773, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1275, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1285, in run_stage
    return self._run_train()
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1315, in _run_train
    self.fit_loop.run()
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 193, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215, in advance
    result = self._run_optimization(
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 266, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    lightning_module.optimizer_step(
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1652, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 164, in step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 336, in optimizer_step
    self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 163, in optimizer_step
    optimizer.step(closure=closure, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/torch/optim/adam.py", line 92, in step
    loss = closure()
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 148, in _wrap_closure
    closure_result = closure()
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 160, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 142, in closure
    step_output = self._step_fn()
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 435, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 216, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 213, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/cs/code/uaixdlamds/src/lightning_module/identifier.py", line 52, in training_step
    self.log(f"{metric_name}_{DatasetPurpose.TRAIN.value}", metric_fn(preds, y), on_step=False, on_epoch=True)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/torchmetrics/metric.py", line 210, in forward
    self._forward_cache = self.compute()
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/torchmetrics/metric.py", line 372, in wrapped_func
    self._computed = compute(*args, **kwargs)
  File "/home/cs/code/uaixdlamds/src/custom_metrics/min_accuracy.py", line 24, in compute
    accuracies = super().compute()
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/torchmetrics/classification/accuracy.py", line 277, in compute
    return _accuracy_compute(tp, fp, tn, fn, self.average, self.mdmc_reduce, self.mode)
  File "/home/cs/.virtualenvs/uaixdlamds-LJIAc_Fv/lib/python3.8/site-packages/torchmetrics/functional/classification/accuracy.py", line 194, in _accuracy_compute
    numerator[meaningless_indeces, ...] = -1
RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == value.numel()INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cuda/Indexing.cu":250, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor321
```

I've tried to come up with a minimal example, which currently looks like this:

```python

import torch
from torchmetrics import Accuracy

device = torch.device("cuda:0")

num_samples = 1000
num_classes = 34

Y = torch.ones(num_samples).long().to(device)
X = torch.zeros(num_samples, num_classes).to(device)

accuracy = Accuracy(average="none", num_classes=num_classes).to(device)

accuracy(X, Y)
```

This works fine if executed as a standalone script, but fails with the same message as above when executed at the top of my model's `training_step` method (I'm using PyTorch Lightning). 

I'm aware that this example is not too helpful, but I am not able to figure out what is triggering this behaviour. I've tried to create a minimal PyTorch Lightning module that reproduces the error, without success (i.e., no error messages here). I'm happy to provide you with more details on request, but currently I have no idea what could be relevant or not.

### Versions

PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.0.194
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 2070 SUPER
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 470.86
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.5.7
[pip3] torch==1.10.1
[pip3] torchmetrics==0.6.2
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @bdhirsh @ngimel

**Comment by gchanan** [comment]
can you post that minimal reproduction that includes lightning?

**Comment by cschell** [comment]
```
import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torch.utils.data import random_split
from torchvision.datasets import MNIST
from torchvision import transforms
import pytorch_lightning as pl


class LitAutoEncoder(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(
                nn.Linear(28 * 28, 64),
                nn.ReLU(),
                nn.Linear(64, 3))
        self.decoder = nn.Sequential(
                nn.Linear(3, 64),
                nn.ReLU(),
                nn.Linear(64, 28 * 28))

    def forward(self, x):
        embedding = self.encoder(x)
        return embedding

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer

    def training_step(self, train_batch, batch_idx):
        ###### test snippet
        import torch
        from torchmetrics import Accuracy

        device = torch.device("cuda:0")

        num_samples = 1000
        num_classes = 34

        Y = torch.ones(num_samples).long().to(device)
        X = torch.zeros(num_samples, num_classes).to(device)

        accuracy = Accuracy(average="none", num_classes=num_classes).to(device)

        accuracy(X, Y)
        ###### test snippet
        x, y = train_batch

        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, val_batch, batch_idx):
        x, y = val_batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)
        self.log('val_loss', loss)


# data
dataset = MNIST('', train=True, download=True, transform=transforms.ToTensor())
mnist_train, mnist_val = random_split(dataset, [55000, 5000])

train_loader = DataLoader(mnist_train, batch_size=32)
val_loader = DataLoader(mnist_val, batch_size=32)

# model
model = LitAutoEncoder()

# training
trainer = pl.Trainer(gpus="1", limit_train_batches=0.5, max_epochs=1)
trainer.fit(model, train_loader, val_loader)
```

This is the basic "LitAutoEncoder" example with the minimal example from above being added at the beginning of `training_step`. However, this works fine for me without any errors, while adding the test snippet in the same way to my "real" lightning module immediately raises mentioned exception.

**Comment by ngimel** [comment]
Should be fixed on master/nightlies

**Comment by dagitses** [comment]
Please reopen if this is still happening.
