### ISSUE TITLE
Tensor loses `bool` method during scripting

### ISSUE THREAD

**Issue by erip** [pytorch/pytorch#70544]
### 🐛 Describe the bug

When scripting a class which relies on `torch.Tensor.bool`, the method is not found and errors out with `'Tensor' object has no attribute or method 'bool'.`.

```python
import torch

class Bar:
    def __init__(self, x: torch.Tensor):
        self.x = x.bool()

f = Bar(torch.tensor(1))
torch.jit.script(f)
```

Error:

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    torch.jit.script(f)
  File "/Users/erip/opt/miniconda3/envs/tmp/lib/python3.8/site-packages/torch/jit/_script.py", line 1318, in script
    return torch.jit._recursive.create_script_class(obj)
  File "/Users/erip/opt/miniconda3/envs/tmp/lib/python3.8/site-packages/torch/jit/_recursive.py", line 419, in create_script_class
    _compile_and_register_class(type(obj), rcb, qualified_class_name)
  File "/Users/erip/opt/miniconda3/envs/tmp/lib/python3.8/site-packages/torch/jit/_recursive.py", line 44, in _compile_and_register_class
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError:
'Tensor' object has no attribute or method 'bool'.:
  File "test.py", line 16
    def __init__(self, x: torch.Tensor):
        self.x = x.bool()
                 ~~~~~~ <--- HERE
```

As a workaround, one can use `self.x = x.to(torch.bool)`

### Versions

```markdown
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.8.12 (default, Oct 12 2021, 06:23:56)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.15.7-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] torch==1.10.1
[pip3] torchtext==0.11.1
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] mkl                       2021.4.0           hecd8cb5_637
[conda] mkl-service               2.4.0            py38h9ed2024_0
[conda] mkl_fft                   1.3.1            py38h4ab4a9b_0
[conda] mkl_random                1.2.2            py38hb2f4e1b_0
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.2           py38h4b4dc7a_0
[conda] numpy-base                1.21.2           py38he0bd621_0
[conda] pytorch                   1.10.1                  py3.8_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchtext                 0.11.1                     py38    pytorch
```

**Comment by yunjiangster** [comment]
Guess I will do` x = x != 0` for now.

**Comment by umarbutler** [comment]
+1 Can we get a fix for this two year old bug?

**Comment by Oktai15** [comment]
@albanD any update?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
