### ISSUE TITLE
CUSOLVER_STATUS_EXECUTION_FAILED when using the torch.logdet()

### ISSUE THREAD

**Issue by LinghaoChan** [pytorch/pytorch#70669]
### 🐛 Describe the bug

My program reports an ERROR message when the ''torch.logdet()'' function was executed for the FIRST time. AMAZINGLY, the error will not be reported when I execute the function AGAIN. 

```python
Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.randn(9, 9)
>>> a = a.cuda()
>>> a
tensor([[-2.6605, -1.5884,  0.7089,  0.7486, -0.5229,  1.6641,  1.2985, -2.0366,
          1.5453],
        [ 1.0522, -2.3295, -0.4025, -0.4814, -1.7643, -0.6771, -0.8490, -1.2713,
          0.2525],
        [ 0.2678, -0.9299, -1.2236, -0.6464,  1.1209, -0.3109,  1.4900,  1.3949,
          0.0460],
        [-0.5451, -0.6144, -0.3387, -0.2821, -0.7145,  0.6141, -0.5563,  0.5543,
          0.0465],
        [-0.9948, -0.8303,  1.1174,  1.5377,  0.8705, -0.5858, -0.1675, -0.2450,
         -0.0192],
        [ 0.7634, -0.8460, -0.4526, -0.5102, -0.2613, -0.3954,  0.1347, -0.7412,
         -0.2037],
        [ 0.9187,  1.4660,  1.2423,  0.8838, -0.0215, -0.4165,  0.4211, -1.8610,
         -0.7167],
        [ 0.4969, -0.8689, -0.4387,  1.0836,  1.1270, -0.2077,  0.1857, -1.9552,
          0.9171],
        [-0.5301, -0.8655, -0.2947, -1.4753,  1.1074,  1.4459, -0.1741,  0.5064,
         -2.0041]], device='cuda:0')
>>> a.requires_grad = True
>>> a
tensor([[-2.6605, -1.5884,  0.7089,  0.7486, -0.5229,  1.6641,  1.2985, -2.0366,
          1.5453],
        [ 1.0522, -2.3295, -0.4025, -0.4814, -1.7643, -0.6771, -0.8490, -1.2713,
          0.2525],
        [ 0.2678, -0.9299, -1.2236, -0.6464,  1.1209, -0.3109,  1.4900,  1.3949,
          0.0460],
        [-0.5451, -0.6144, -0.3387, -0.2821, -0.7145,  0.6141, -0.5563,  0.5543,
          0.0465],
        [-0.9948, -0.8303,  1.1174,  1.5377,  0.8705, -0.5858, -0.1675, -0.2450,
         -0.0192],
        [ 0.7634, -0.8460, -0.4526, -0.5102, -0.2613, -0.3954,  0.1347, -0.7412,
         -0.2037],
        [ 0.9187,  1.4660,  1.2423,  0.8838, -0.0215, -0.4165,  0.4211, -1.8610,
         -0.7167],
        [ 0.4969, -0.8689, -0.4387,  1.0836,  1.1270, -0.2077,  0.1857, -1.9552,
          0.9171],
        [-0.5301, -0.8655, -0.2947, -1.4753,  1.1074,  1.4459, -0.1741,  0.5064,
         -2.0041]], device='cuda:0', requires_grad=True)
>>> b= a+a
>>> b
tensor([[-5.3210, -3.1767,  1.4177,  1.4972, -1.0458,  3.3283,  2.5970, -4.0732,
          3.0906],
        [ 2.1044, -4.6591, -0.8051, -0.9628, -3.5285, -1.3542, -1.6980, -2.5426,
          0.5050],
        [ 0.5355, -1.8599, -2.4472, -1.2927,  2.2419, -0.6218,  2.9800,  2.7899,
          0.0920],
        [-1.0902, -1.2288, -0.6774, -0.5641, -1.4289,  1.2281, -1.1126,  1.1087,
          0.0929],
        [-1.9896, -1.6607,  2.2349,  3.0754,  1.7410, -1.1716, -0.3349, -0.4901,
         -0.0384],
        [ 1.5268, -1.6921, -0.9052, -1.0203, -0.5226, -0.7908,  0.2694, -1.4825,
         -0.4074],
        [ 1.8375,  2.9320,  2.4847,  1.7676, -0.0430, -0.8329,  0.8422, -3.7220,
         -1.4334],
        [ 0.9937, -1.7377, -0.8775,  2.1672,  2.2540, -0.4154,  0.3713, -3.9104,
          1.8341],
        [-1.0601, -1.7309, -0.5895, -2.9506,  2.2148,  2.8917, -0.3481,  1.0128,
         -4.0082]], device='cuda:0', grad_fn=<AddBackward0>)
>>> torch.logdet(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgetrf( handle, m, n, dA, ldda, static_cast<float*>(dataPtr.get()), ipiv, info)`
>>> torch.det(b)
tensor(44733.0117, device='cuda:0', grad_fn=<DetLuBasedHelperBackward0>)
>>> torch.det(b)
tensor(44733.0117, device='cuda:0', grad_fn=<DetLuBasedHelperBackward0>)
>>> torch.det(b).log()
tensor(10.7085, device='cuda:0', grad_fn=<LogBackward0>)
>>> b.logdet()
tensor(10.7085, device='cuda:0', grad_fn=<LogdetBackward0>)
>>> torch.logdet(b)
tensor(10.7085, device='cuda:0', grad_fn=<LogdetBackward0>)
````
---
Motivated by this, I rewrote a new program to validate this.
```python
import torch

a = torch.randn(9, 9)
a = a.cuda()
a.requires_grad = True
print(a)
b= a+a
print(b)
try:
    print(torch.logdet(b))
    print('TRY-PART')
except:
    print(torch.logdet(b))
    print('EXCEPT-PART')
    print(torch.det(b))
    print(torch.det(b).log())
    print(b.logdet())
    print(torch.logdet(b))
```
THE OUTPUT:
```
tensor([[-0.6532,  0.5945,  1.1939, -2.1283, -1.1182,  0.4609, -1.0920,  1.1464,
         -2.6419],
        [-0.9333, -0.8353, -0.6816, -0.5360,  0.8662,  0.0058,  0.6089, -0.6144,
          1.5034],
        [-1.8466,  2.2491,  1.7100, -0.8738, -0.1071, -1.6346, -0.9584,  2.2552,
          1.0694],
        [ 0.1883,  0.7769,  0.5138, -1.3552, -0.6274,  1.5000,  0.0453, -0.8381,
          1.4051],
        [ 0.8021,  0.9736, -1.0843, -1.4855, -0.8864, -0.8064, -0.7061, -0.2059,
         -0.9930],
        [-1.4984,  2.1961,  0.4857, -0.1494,  0.7021,  0.3512,  0.3404,  0.5769,
         -0.7395],
        [ 0.8274, -1.4246,  1.1541, -0.5108, -0.8629, -0.4092, -0.3129,  0.4776,
          0.6271],
        [ 0.5916, -1.1913,  1.5054,  0.7082,  1.1280,  0.2026, -1.6208,  1.4507,
         -0.9418],
        [ 0.8289, -0.6652, -0.1179,  2.6689,  0.3450, -0.2769, -0.9009, -1.0749,
         -0.6171]], device='cuda:0', requires_grad=True)
tensor([[-1.3063,  1.1889,  2.3879, -4.2566, -2.2364,  0.9219, -2.1839,  2.2928,
         -5.2839],
        [-1.8666, -1.6706, -1.3632, -1.0719,  1.7323,  0.0115,  1.2178, -1.2288,
          3.0067],
        [-3.6932,  4.4981,  3.4200, -1.7475, -0.2142, -3.2692, -1.9168,  4.5104,
          2.1389],
        [ 0.3765,  1.5538,  1.0277, -2.7104, -1.2549,  3.0000,  0.0907, -1.6762,
          2.8102],
        [ 1.6041,  1.9472, -2.1685, -2.9710, -1.7728, -1.6128, -1.4121, -0.4118,
         -1.9860],
        [-2.9967,  4.3923,  0.9714, -0.2988,  1.4042,  0.7025,  0.6808,  1.1538,
         -1.4789],
        [ 1.6547, -2.8492,  2.3081, -1.0217, -1.7259, -0.8185, -0.6258,  0.9552,
          1.2542],
        [ 1.1832, -2.3826,  3.0107,  1.4165,  2.2561,  0.4051, -3.2417,  2.9013,
         -1.8836],
        [ 1.6578, -1.3303, -0.2359,  5.3378,  0.6900, -0.5538, -1.8019, -2.1498,
         -1.2343]], device='cuda:0', grad_fn=<AddBackward0>)
tensor(12.9578, device='cuda:0', grad_fn=<LogdetBackward0>)
EXCEPT-PART
tensor(424119.9688, device='cuda:0', grad_fn=<DetLuBasedHelperBackward0>)
tensor(12.9578, device='cuda:0', grad_fn=<LogBackward0>)
tensor(12.9578, device='cuda:0', grad_fn=<LogdetBackward0>)
tensor(12.9578, device='cuda:0', grad_fn=<LogdetBackward0>)
```
The code did not execute the 'try' part but executed successfully on the second attempt.
**WHY must it be executed twice to pass??? A BUG?**

### Versions

Collecting environment information...
PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: A100-SXM4-40GB
GPU 1: A100-SXM4-40GB
GPU 2: A100-SXM4-40GB
GPU 3: A100-SXM4-40GB
GPU 4: A100-SXM4-40GB
GPU 5: A100-SXM4-40GB
GPU 6: A100-SXM4-40GB
GPU 7: A100-SXM4-40GB

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.10.1+cu113
[pip3] torchvision==0.11.2
[conda] mkl                       2022.0.1                 pypi_0    pypi
[conda] mkl-fft                   1.3.1                    pypi_0    pypi
[conda] mkl-random                1.2.2                    pypi_0    pypi
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] torch                     1.10.1+cu113             pypi_0    pypi
[conda] torchvision               0.11.2                   pypi_0    pypi

**Comment by xwang233** [comment]
I can't reproduce this issue on A100 with the pip 1.10.1+cu113 wheel. Is there any chance that you have multiple torch installed in different python environment?

**Comment by LinghaoChan** [comment]
> I can't reproduce this issue on A100 with the pip 1.10.1+cu113 wheel. Is there any chance that you have multiple torch installed in different python environment?

Thanks for your attention. I found out the source of this issue: My A-100 CUDA Version is 11.0 but I installed torch with 1.10.1+cu113 (the only torch installed in my environment). 

It's possible that your A-100 CUDA Version is 11.3 or 11.4.

**However, the phenomenon I described is still very strange. Why will an error command not report an error the second time it is executed?**

**Comment by xwang233** [comment]
Thanks for the comment. If you installed your pytorch wheel from pip, the system CUDA version doesn't matter. Only the CUDA version that comes with torch pip wheel matters. 

The behavior you described is indeed very strange, and pytorch doesn't have such feature that raises an exception in the first run but not the second. Can you check your system with, maybe `dmesg` or `nvidia-smi`, and see if the GPU is working properly?  Is there any other program running on the same GPU? Also check torch environment with 
```
python -c 'import torch; print(torch._C._show_config())'
```
could be helpful.

**Comment by LinghaoChan** [comment]
> Thanks for the comment. If you installed your pytorch wheel from pip, the system CUDA version doesn't matter. Only the CUDA version that comes with torch pip wheel matters.
> 
> The behavior you described is indeed very strange, and pytorch doesn't have such feature that raises an exception in the first run but not the second. Can you check your system with, maybe `dmesg` or `nvidia-smi`, and see if the GPU is working properly? Is there any other program running on the same GPU? Also check torch environment with
> 
> ```
> python -c 'import torch; print(torch._C._show_config())'
> ```
> 
> could be helpful.

Okay. The program will not report any error after I changed the torch version from 1.10.1+cu113 to 1.7.0+cu110. Does it mean that the **the torch CUDA version** should >= **the system CUDA version**?

+ I checked via `watch -n 0.1 nvidia-smi` command, all eight gpus seem well. The phenomenon exists whenever there is any other program running. I checked it more than 10 times.

+ Although I changed the torch version, I saved another copy of the virtual environment with problems. I check the torch environment on this copy via the command you mentioned, here is the result:
```
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

**Comment by Lezcano** [comment]
cc @nikitaved who worked on this function.

**Comment by nikitaved** [comment]
I did not work on logdet, no, but I will have a look once my stack is free.

**Comment by rahulTrial** [comment]
I'm facing the same issue as mentioned above for any `linalg` library; example `torch.det(torch.eye(3).cuda())` returns `{_LinAlgError}cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling cusolverDnSgetrf( handle, m, n, dA, ldda, static_cast<float*>(dataPtr.get()), ipiv, info). This error may appear if the input matrix contains NaN.` on the first try but not on the second or any consequent tries. It fails on the current version of pytorch on a fresh conda build -> 1.11_cu_11.3 
PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

**Comment by xwang233** [comment]
Might be a library loading issue in a wheel build? cc @malfet

**Comment by rahulTrial** [comment]
@xwang233 it works fine with pytorch==1.11.0=py3.7_cuda11.1_cudnn8_0, but not with cudatoolkit 11.3.

**Comment by xwang233** [comment]
Hi @LinghaoChan , @rahulTrial , thank you for reporting this issue. Sorry I still can't reproduce this issue with pytorch wheel of different versions on various GPU models.

To help us better isolate this issue, can you help check if this issue also exists in 
- other linalg functions (`GETRF` is a LU decomposition function, so other LU-related functions may also fail, e.g. `solve`, `inverse`, or `lu`; it's also interesting to know if this only applies to `GETRF`)
- other input precisions (also try double, cfloat, and cdouble)
- pytorch wheel releases of other versions (`{1.11, 1.10.2, 1.10.1, etc} + cuda {11.3, 11.5}`, and [NGC docker image](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) of different releases (no need to install pip wheel inside docker container, use the pre-built pytorch that comes with the docker image)

Thank you!

**Comment by xwang233** [comment]
> Might be a library loading issue in a wheel build? cc @malfet

I was thinking if https://github.com/pytorch/pytorch/pull/73447 or some other build changes could be related. cc @malfet

**Comment by LinghaoChan** [comment]
> Hi @LinghaoChan , @rahulTrial , thank you for reporting this issue. Sorry I still can't reproduce this issue with pytorch wheel of different versions on various GPU models.
> 
> To help us better isolate this issue, can you help check if this issue also exists in
> 
> * other linalg functions (`GETRF` is a LU decomposition function, so other LU-related functions may also fail, e.g. `solve`, `inverse`, or `lu`; it's also interesting to know if this only applies to `GETRF`, so try other non-LU functions, e.g. `svd`, `cholesky`)
> * other input precisions (also try double, cfloat, and cdouble)
> * pytorch wheel releases of other versions (`{1.11, 1.10.2, 1.10.1, etc} + cuda {11.3, 11.5}`, and [NGC docker image](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) of different releases (no need to install pip wheel inside docker container, use the pre-built pytorch that comes with the docker image)
> 
> Thank you!

@xwang233 Thanks for continuing to follow this bug! I did experiments as follows. `qr`, `inv` function fails at first, and it's ok by trying twice. More amazingly, the `solve` function fails twice, but it's ok by trying three times. Besides, non-LU functions also failed at the first time, e.g. `svd` and `cholesky`. After I tried `cholesky` twice, the `torch.det()` can work well. 

**Environment: torch1.10.0+cu113; CUDA:11.0.**

- torch.linalg.qr() 
```python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.randn(9, 9)
>>> a = a.cuda()
>>> b=a+a
>>> torch.linalg.qr(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXgeqrf( handle, params, m, n, CUDA_R_32F, reinterpret_cast<void*>(A), lda, CUDA_R_32F, reinterpret_cast<void*>(tau), CUDA_R_32F, reinterpret_cast<void*>(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast<void*>(bufferOnHost), workspaceInBytesOnHost, info)`
>>> torch.linalg.qr(b)
torch.return_types.linalg_qr(
Q=tensor([[-0.0686, -0.2491,  0.0357, -0.4449, -0.0378,  0.1771,  0.2211,  0.6698,
         -0.4514],
        [-0.2342, -0.3917,  0.0745,  0.0192, -0.2053,  0.7339, -0.1525, -0.4053,
         -0.1323],
        [ 0.2321, -0.5548, -0.1085,  0.0680, -0.2471, -0.3007,  0.6296, -0.2720,
          0.0029],
        [-0.3746, -0.1054, -0.2315, -0.4742, -0.4777, -0.4153, -0.3860, -0.1306,
          0.0584],
        [ 0.3990,  0.3261,  0.3374, -0.0181, -0.7387,  0.1732,  0.0501,  0.1334,
          0.1563],
        [ 0.4254, -0.3261,  0.4709,  0.0324,  0.1035, -0.2808, -0.4981, -0.0923,
         -0.3792],
        [-0.0684, -0.3067, -0.3059,  0.6619, -0.2545, -0.0296, -0.2810,  0.4690,
          0.0710],
        [ 0.1216,  0.3785, -0.4389,  0.1676, -0.1697, -0.0163,  0.0277, -0.2227,
         -0.7361],
        [-0.6218,  0.1253,  0.5533,  0.3234, -0.1313, -0.2389,  0.2283, -0.0168,
         -0.2454]], device='cuda:0'),
R=tensor([[ 7.3727,  0.6636, -0.4630, -1.3452, -0.7168,  3.4763, -1.9394, -3.6124,
         -1.0359],
        [ 0.0000,  6.3276, -0.4478, -4.6093, -2.9818,  1.2913, -3.1906, -3.1673,
         -2.2894],
        [ 0.0000,  0.0000,  7.3484, -1.1829, -2.9950,  3.0791,  0.4160, -0.9785,
         -0.8253],
        [ 0.0000,  0.0000,  0.0000, -2.5093,  1.5384, -0.6011,  0.1043, -0.6343,
         -0.0712],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -2.6208,  1.5552, -1.0658,  0.5179,
         -2.7368],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -5.3373,  3.4718, -1.6501,
         -2.1406],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  2.2416,  1.2716,
         -1.4985],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -2.6127,
          0.9031],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         -2.0623]], device='cuda:0'))
```
- torch.linalg.inv()
```python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.randn(9, 9)
>>> a = a.cuda()
>>> b=a+a
>>> torch.linalg.inv(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgetrf( handle, m, n, dA, ldda, static_cast<float*>(dataPtr.get()), ipiv, info)`
>>> torch.linalg.inv(b)
tensor([[-7.1943e-01,  9.6012e-01, -3.6818e-01, -5.3450e-01,  1.2663e+00,
         -1.9072e+00,  8.1645e-01,  1.9978e+00,  5.1480e-01],
        [-4.5393e-01,  6.6849e-01,  1.2802e-03, -4.9778e-01,  6.7771e-01,
         -1.1853e+00,  4.6653e-01,  1.1055e+00,  2.5328e-01],
        [-1.4325e+00,  1.5370e+00, -1.2352e-01, -8.3005e-01,  1.5597e+00,
         -3.2051e+00,  1.4135e+00,  2.9506e+00,  1.1653e+00],
        [ 6.8591e-01, -8.7293e-01,  7.5469e-02,  4.3382e-01, -9.3761e-01,
          1.5401e+00, -6.8969e-01, -1.6609e+00, -6.1064e-01],
        [ 1.4598e+00, -1.6591e+00,  8.7369e-02,  8.2454e-01, -1.7588e+00,
          3.4630e+00, -1.4090e+00, -3.2407e+00, -1.2015e+00],
        [ 2.3635e+00, -2.9169e+00,  4.1502e-01,  1.8835e+00, -3.1492e+00,
          6.0051e+00, -2.5665e+00, -5.9563e+00, -1.8312e+00],
        [ 5.9793e-01, -7.5141e-01,  1.4493e-01,  5.2844e-01, -5.6691e-01,
          1.7735e+00, -7.6466e-01, -1.4931e+00, -7.2658e-01],
        [-8.9707e-01,  1.1252e+00, -1.6971e-01, -7.5523e-01,  1.3574e+00,
         -2.4739e+00,  1.2414e+00,  2.4312e+00,  7.5737e-01],
        [ 1.5895e+00, -1.7973e+00,  1.7295e-01,  1.2117e+00, -2.1011e+00,
          3.9000e+00, -1.6474e+00, -3.7586e+00, -1.3837e+00]], device='cuda:0')
```
- torch.linalg.solve()
```python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> A = torch.randn(3, 3)
>>> b = torch.randn(3)
>>> A = A.cuda()
>>> b = b.cuda()
>>> x = torch.linalg.solve(A, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgetrf( handle, m, n, dA, ldda, static_cast<float*>(dataPtr.get()), ipiv, info)`
>>> x = torch.linalg.solve(A, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
>>> x = torch.linalg.solve(A, b)
>>> x
tensor([ 1.7064, -0.6342,  1.9499], device='cuda:0')
```
- torchlinalg.svd()
```python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> A = torch.randn(5, 3)
>>> A = A.cuda()
>>> U, S, Vh = torch.linalg.svd(A, full_matrices=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgesvdj( handle, jobz, econ, m, n, A, lda, S, U, ldu, V, ldv, static_cast<float*>(dataPtr.get()), lwork, info, params)`
>>> U, S, Vh = torch.linalg.svd(A, full_matrices=False)
>>> U.shape, S.shape, Vh.shape
(torch.Size([5, 3]), torch.Size([3]), torch.Size([3, 3]))
```
- torch.linalg.cholesky()
```python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> A = torch.randn(2, 2, dtype=torch.complex128)
>>> A = A @ A.T.conj() + torch.eye(2)
>>> A = A.cuda()
>>> torch.linalg.cholesky(A)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXpotrf( handle, params, uplo, n, dataTypeA, A, lda, computeType, bufferOnDevice, workspaceInBytesOnDevice, bufferOnHost, workspaceInBytesOnHost, info )`
>>> torch.linalg.cholesky(A)
tensor([[1.8274+0.0000e+00j, 0.0000+0.0000e+00j],
        [0.9225-3.0222e-01j, 1.7387-3.2841e-18j]], device='cuda:0',
       dtype=torch.complex128)
```

**Comment by Lezcano** [comment]
fwiw, solve calls lu_factor + lu_solve so, even though I don't know why it fails, it makes sense it fails twice before succeeding

**Comment by xwang233** [comment]
Hi @LinghaoChan , @rahulTrial , @yanivnik, sorry for a late response here. I saw that all of those issues were happening in cuda 11.3 wheels. Is it possible to try a cuda 11.5 or cuda 11.6 wheel release? This could be a cuda library issue.

- torch 1.11 + cuda 11.5: 
  ```
  pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu115
  ```
- torch nightly + cuda 11.5:
  ```
  pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu115
  ```
- torch nightly + cuda 11.6:
  ```
  pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu116
  ```
Thank you!

**Comment by siqili1230** [comment]
I meet a similar problem that when I execute "torch.logdet()" at a specific time (roughly the 75000th time, independent to randon seed in my program), the same error message "cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED" is reported.
My environment is torch 1.11 + cuda 11.0.  I also tried it in torch 1.11 + cuda 11.6, and this problem does not occur.
I guess that maybe early versions of cuda all have such problem in "torch.logdet()" but with different trigger timing.
Hope my experiment can help you to locate the source of this problem and finally solve it.
BTW since I don't have the root permission to change the cuda version,  I finally solve it by "try: torch.logdet()" for several times. And thanks to this issue :) @LinghaoChan , or I cannot imagine such solution to skip this error.

**Comment by LinghaoChan** [comment]
> I meet a similar problem that when I execute "torch.logdet()" at a specific time (roughly the 75000th time, independent to randon seed in my program), the same error message "cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED" is reported. My environment is torch 1.11 + cuda 11.0. I also tried it in torch 1.11 + cuda 11.6, and this problem does not occur. I guess that maybe early versions of cuda all have such problem in "torch.logdet()" but with different trigger timing. Hope my experiment can help you to locate the source of this problem and finally solve it. BTW since I don't have the root permission to change the cuda version, I finally solve it by "try: torch.logdet()" for several times. And thanks to this issue :) @LinghaoChan , or I cannot imagine such solution to skip this error.

Aha, So interesting problem and solution. I also met it for the first time. Confusing~
