### ISSUE TITLE
Tests in test_constraints fail when compiled without LAPACK support

### ISSUE THREAD

**Issue by lithuak** [pytorch/pytorch#70670]
### 🐛 Describe the bug

Running `python test/run_test.py` fails when PyTorch is compiled w/o LAPACK support.

The expected behavior is to skip tests relaying on it.

The test that fails is: `test_constraint` in `test/distributions/test_constraints.py`.

The error log is:

```
==================================================================== FAILURES ====================================================================
_______________________________________________ test_constraint[False-constraint_fn3-False-value3] _______________________________________________
Traceback (most recent call last):
  File "/home/soul/pytorch/test/distributions/test_constraints.py", line 61, in test_constraint
    assert constraint_fn.check(t(value)).all() == result
  File "/home/soul/pytorch/torch/distributions/constraints.py", line 500, in check
    return torch.linalg.cholesky_ex(value).info.eq(0)
RuntimeError: Calling torch.linalg.cholesky on a CPU tensor requires compiling PyTorch with LAPACK. Please use PyTorch built with LAPACK support.
_______________________________________________ test_constraint[False-constraint_fn5-False-value5] _______________________________________________
Traceback (most recent call last):
  File "/home/soul/pytorch/test/distributions/test_constraints.py", line 61, in test_constraint
    assert constraint_fn.check(t(value)).all() == result
  File "/home/soul/pytorch/torch/distributions/constraints.py", line 500, in check
    return torch.linalg.cholesky_ex(value).info.eq(0)
RuntimeError: Calling torch.linalg.cholesky on a CPU tensor requires compiling PyTorch with LAPACK. Please use PyTorch built with LAPACK support.
_______________________________________________ test_constraint[False-constraint_fn7-True-value7] ________________________________________________
Traceback (most recent call last):
  File "/home/soul/pytorch/test/distributions/test_constraints.py", line 61, in test_constraint
    assert constraint_fn.check(t(value)).all() == result
  File "/home/soul/pytorch/torch/distributions/constraints.py", line 500, in check
    return torch.linalg.cholesky_ex(value).info.eq(0)
RuntimeError: Calling torch.linalg.cholesky on a CPU tensor requires compiling PyTorch with LAPACK. Please use PyTorch built with LAPACK support.
================================================================ warnings summary ================================================================
../.pyenv/versions/pytorch/lib/python3.9/site-packages/_pytest/config/__init__.py:1114
  /home/soul/.pyenv/versions/pytorch/lib/python3.9/site-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: hypothesis
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================================ short test summary info =============================================================
SKIPPED [8] test/distributions/test_constraints.py:55: CUDA not found.
FAILED test/distributions/test_constraints.py::test_constraint[False-constraint_fn3-False-value3] - RuntimeError: Calling torch.linalg.cholesky...
FAILED test/distributions/test_constraints.py::test_constraint[False-constraint_fn5-False-value5] - RuntimeError: Calling torch.linalg.cholesky...
FAILED test/distributions/test_constraints.py::test_constraint[False-constraint_fn7-True-value7] - RuntimeError: Calling torch.linalg.cholesky ...
=============================================== 3 failed, 5 passed, 8 skipped, 1 warning in 0.08s ================================================
```

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.0

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 460.91.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.11.0a0+git0ece9a4
[pip3] torchvision==0.11.1
[conda] Could not collect

cc @fritzo @neerajprad @alicanb @nikitaved

**Comment by lithuak** [comment]
I think I can contribute a fix based on `skipCPUIfNoLapack`  from `torch.testing._internal.common_device_type` and the pytest.skip() from another test in `test_constraints`.
