### ISSUE TITLE
DISABLED test_broadcast_stress_cuda (__main__.ProcessGroupGlooTest)

### ISSUE THREAD

**Issue by KyleCZH** [pytorch/pytorch#70877]
Platforms: rocm

```
======================================================================
ERROR: test_broadcast_stress_cuda (__main__.ProcessGroupGlooTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 423, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 642, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 687, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 1 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 541, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 425, in wrapper
    fn()
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 2888, in wrapper
    return func(*args, **kwargs)
  File "/var/lib/jenkins/pytorch/test/distributed/test_c10d_gloo.py", line 384, in test_broadcast_stress_cuda
    self._test_broadcast_stress(inputs)
  File "/var/lib/jenkins/pytorch/test/distributed/test_c10d_gloo.py", line 366, in _test_broadcast_stress
    work_handle.wait()
RuntimeError: [/var/lib/jenkins/pytorch/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:84] Timed out waiting 5000ms for recv operation to complete
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by KyleCZH** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.5-py3.7-test-distributed/35//console

```
15:32:01 ----------------------------------------------------------------------
15:32:01   test_broadcast_stress_cuda (__main__.ProcessGroupGlooTest) ... Caught exception: 
15:32:08 Traceback (most recent call last):
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 604, in run_test
15:32:08     getattr(self, test_name)()
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 486, in wrapper
15:32:08     fn()
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 132, in wrapper
15:32:08     return func(*args, **kwargs)
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 3159, in wrapper
15:32:08     return func(*args, **kwargs)
15:32:08   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_gloo.py", line 386, in test_broadcast_stress_cuda
15:32:08     self._test_broadcast_stress(inputs)
15:32:08   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_gloo.py", line 368, in _test_broadcast_stress
15:32:08     work_handle.wait()
15:32:08 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 5000ms for recv operation to complete
15:32:08  exiting process 0 with exit code: 10
15:32:08 Caught exception: 
15:32:08 Traceback (most recent call last):
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 604, in run_test
15:32:08     getattr(self, test_name)()
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 486, in wrapper
15:32:08     fn()
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 132, in wrapper
15:32:08     return func(*args, **kwargs)
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 3159, in wrapper
15:32:08     return func(*args, **kwargs)
15:32:08   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_gloo.py", line 386, in test_broadcast_stress_cuda
15:32:08     self._test_broadcast_stress(inputs)
15:32:08   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_gloo.py", line 368, in _test_broadcast_stress
15:32:08     work_handle.wait()
15:32:08 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 5000ms for recv operation to complete
15:32:08  exiting process 1 with exit code: 10
15:32:08 Caught exception: 
15:32:08 Traceback (most recent call last):
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 604, in run_test
15:32:08     getattr(self, test_name)()
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 486, in wrapper
15:32:08     fn()
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 132, in wrapper
15:32:08     return func(*args, **kwargs)
15:32:08   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 3159, in wrapper
15:32:08     return func(*args, **kwargs)
15:32:08   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_gloo.py", line 386, in test_broadcast_stress_cuda
15:32:08     self._test_broadcast_stress(inputs)
15:32:08   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_gloo.py", line 368, in _test_broadcast_stress
15:32:08     work_handle.wait()
15:32:08 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 5000ms for recv operation to complete
15:32:08  exiting process 3 with exit code: 10
15:32:09 Process 1 terminated with exit code 10, terminating remaining processes.
15:32:09 ERROR (8.337s)
15:32:09 
15:32:09 ======================================================================
15:32:09 ERROR [8.337s]: test_broadcast_stress_cuda (__main__.ProcessGroupGlooTest)
15:32:09 ----------------------------------------------------------------------
15:32:09 Traceback (most recent call last):
15:32:09   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 484, in wrapper
15:32:09     self._join_processes(fn)
15:32:09   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 705, in _join_processes
15:32:09     self._check_return_codes(elapsed_time)
15:32:09   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 750, in _check_return_codes
15:32:09     raise RuntimeError(error)
15:32:09 RuntimeError: Process 1 exited with error code 10 and exception:
15:32:09 Traceback (most recent call last):
15:32:09   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 604, in run_test
15:32:09     getattr(self, test_name)()
15:32:09   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 486, in wrapper
15:32:09     fn()
15:32:09   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py", line 132, in wrapper
15:32:09     return func(*args, **kwargs)
15:32:09   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 3159, in wrapper
15:32:09     return func(*args, **kwargs)
15:32:09   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_gloo.py", line 386, in test_broadcast_stress_cuda
15:32:09     self._test_broadcast_stress(inputs)
15:32:09   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_gloo.py", line 368, in _test_broadcast_stress
15:32:09     work_handle.wait()
15:32:09 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 5000ms for recv operation to complete
15:32:09 
15:32:09 
15:32:09 
15:32:09 ----------------------------------------------------------------------
15:32:09 Ran 1 test in 8.337s
15:32:09 
15:32:09 FAILED (errors=1)
```

**Comment by jithunnair-amd** [comment]
@janeyx99 This doesn't seem to disable the test consistently. We saw a CI run where this test still ran a day after this issue was opened: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.5-py3.7-test-distributed/359/

**Comment by janeyx99** [comment]
Ah, looking into the logs: 
![image](https://user-images.githubusercontent.com/31798555/148614521-f413eac3-6c02-40f6-ba70-0e0934e4cc1f.png)

This is because the download of the disabled tests file timed out so it didn't know what to disable :/

I will add a line to retry if failed for this, but this line doesn't usually time out on our other runners...
