### ISSUE TITLE
DISABLED test_caching_pinned_memory_multi_gpu (__main__.TestCuda)

### ISSUE THREAD

**Issue by KyleCZH** [pytorch/pytorch#70875]
Platforms: rocm

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.5-py3.7-test2/19//console

```
13:43:03 ======================================================================
13:43:03 FAIL [0.031s]: test_caching_pinned_memory_multi_gpu (__main__.TestCuda)
13:43:03 ----------------------------------------------------------------------
13:43:03 Traceback (most recent call last):
13:43:03   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1566, in wrapper
13:43:03     method(*args, **kwargs)
13:43:03   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1566, in wrapper
13:43:03     method(*args, **kwargs)
13:43:03   File "test_cuda.py", line 1394, in test_caching_pinned_memory_multi_gpu
13:43:03     self.assertNotEqual(t.data_ptr(), ptr, msg='allocation re-used too soon')
13:43:03   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 2177, in assertNotEqual
13:43:03     self.assertEqual(x, y, msg, atol=atol, rtol=rtol, **kwargs)
13:43:03 AssertionError: AssertionError not raised : allocation re-used too soon
13:43:03 
13:43:03 ----------------------------------------------------------------------
```

cc @ngimel @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jithunnair-amd** [comment]
Related github issue: https://github.com/pytorch/pytorch/issues/68299?

**Comment by jithunnair-amd** [comment]
@janeyx99 This doesn't seem to disable the test consistently. We saw a CI run where this test still ran a day after this issue was opened: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.5-py3.7-test2/151/console

**Comment by janeyx99** [comment]
@jithunnair-amd Same reason as in https://github.com/pytorch/pytorch/issues/70877#issuecomment-1007783577
