### ISSUE TITLE
falseINTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by moshe8931** [pytorch/pytorch#71092]
### 🐛 Describe the bug

```
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\moshe\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\moshe\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "C:\Users\moshe\anaconda3\lib\site-packages\torch\utils\data\_utils\collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "C:\Users\moshe\anaconda3\lib\site-packages\torch\utils\data\_utils\collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "C:\Users\moshe\anaconda3\lib\site-packages\torch\utils\data\_utils\collate.py", line 54, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "C:\Users\moshe\anaconda3\lib\site-packages\torch\storage.py", line 155, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: falseINTERNAL ASSERT FAILED at "..\\aten\\src\\ATen\\MapAllocator.cpp":141, please report a bug to PyTorch. Couldn't map view of shared file <00000249EFE007A2>, error code: <5>
```

### Versions

it didnt work

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @VitalyFedyunin @SsnL @ejguan @NivekT

**Comment by NivekT** [comment]
Hi, thanks for submitting this issue.  Do you have a minimal code snippet to reproduce the issue?

**Comment by NivekT** [comment]
Yes, you can put a code snippet here (omitting any personal information). Also, information related to your PyTorch version and environment will be helpful as well.

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by moshe8931** [comment]
Ok
Ill do it later
Thanks:)

בתאריך יום ד׳, 12 בינו׳ 2022, 17:21, מאת Kevin Tse ‏<
***@***.***>:

**Comment by mszhanyi** [comment]
https://pytorch.org/docs/stable/multiprocessing.html
`2. Keep producer process running until all consumers exits. This will prevent the situation when the producer process releasing memory which is still in use by the consumer.`

https://github.com/pytorch/pytorch/issues/67844

**Comment by VitalyFedyunin** [comment]
Feel free to reopen issue if error appears in pytorch >= 1.11
