### ISSUE TITLE
expected scalar type Float but found UNKNOWN_SCALAR when running model using vulkan backend on Android

### ISSUE THREAD

**Issue by dinhkt** [pytorch/pytorch#71264]
### 🐛 Describe the bug

Hi,
I'm trying to use pytorch support with vulkan backend on android.
I can successfully built the arrs file for my target device with the command:
```ANDROID_ABI=arm64-v8a USE_VULKAN=1 ./scripts/build_android.sh```
```USE_VULKAN=1  ./scripts/build_pytorch_android.sh arm64-v8a```
then use them in my android project. I built from the pytorch source code which latest commit is fca8a0acaa (#71025).

I use this script to convert to lite model:
```
import torch
from torchvision import models
from torch.utils.mobile_optimizer import optimize_for_mobile
model = models.mobilenet_v2(pretrained=True)
scripted_model=torch.jit.script(model)
opt_m=optimize_for_mobile(scripted_model,backend='vulkan')
opt_m._save_for_lite_interpreter("mobilenet_v2_vulkan.ptl")
```

Then using LiteModuleLoader to load the generated model.
```mModule = LiteModuleLoader.load(MainActivity.assetFilePath(getApplicationContext(), "mobilenet_v2_vulkan.ptl"),null,Device.VULKAN);```
Loading model cause no problem but when using the forward method, this error happen: 
```
D/vulkan: searching for layers in '/data/app/~~6X6QTp32KMcR8eVHPxXxig==/org.pytorch.demo.visionapp-piC9n-4XNbzkluPaB9oXoQ==/lib/arm64'
D/vulkan: searching for layers in '/data/app/~~6X6QTp32KMcR8eVHPxXxig==/org.pytorch.demo.visionapp-piC9n-4XNbzkluPaB9oXoQ==/base.apk!/lib/arm64-v8a'
I/AdrenoVK-0: ===== BEGIN DUMP OF OVERRIDDEN SETTINGS =====
    ===== END DUMP OF OVERRIDDEN SETTINGS =====
I/AdrenoVK-0: QUALCOMM build          : 7fef9cd1c4, I30979edc94
    Build Date              : 03/23/21
    Shader Compiler Version : EV031.32.02.08
    Local Branch            : 
    Remote Branch           : 
    Remote Branch           : 
    Reconstruct Branch      : 
    Build Config            : S P 10.0.7 AArch64
    Driver Path             : /vendor/lib64/hw/vulkan.adreno.so
E/AndroidRuntime: FATAL EXCEPTION: ModuleActivity
    Process: org.pytorch.demo.visionapp, PID: 27822
    com.facebook.jni.CppException: expected scalar type Float but found UNKNOWN_SCALAR
      
      Debug info for handle(s): debug_handles:{-1}, was not found.
      
    Exception raised from data_ptr at /home/ncl/ktdinh/pytorch/build_android_arm64-v8a/aten/src/ATen/core/TensorMethods.cpp:18 (most recent call first):
    (no backtrace available)
        at org.pytorch.LiteNativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:52)
        at org.pytorch.demo.vision.imgclassification.ICActivity.analyzeImage(ICActivity.java:111)
        at org.pytorch.demo.vision.imgclassification.ICActivity.analyzeImage(ICActivity.java:32)
        at org.pytorch.demo.vision.AbstractCameraXActivity.lambda$setupCameraX$2$AbstractCameraXActivity(AbstractCameraXActivity.java:92)
        at org.pytorch.demo.vision.-$$Lambda$AbstractCameraXActivity$t0OjLr-l_M0-_0_dUqVE4yqEYnE.analyze(Unknown Source:2)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.analyzeImage(ImageAnalysisAbstractAnalyzer.java:57)
        at androidx.camera.core.ImageAnalysisNonBlockingAnalyzer$1.run(ImageAnalysisNonBlockingAnalyzer.java:135)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
I/ViewRootImpl@94542bc[MainActivity]: stopped(false) old=true
I/ViewRootImpl@94542bc[MainActivity]: stopped(false) old=false
I/Process: Sending signal. PID: 27822 SIG: 9
```

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.20.20210615-gb302dd7
Libc version: glibc-2.27

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: 11.5.119
GPU models and configuration: GPU 0: GeForce RTX 3060
Nvidia driver version: 460.91.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchvision==0.11.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.1            py38hd3c417c_0
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] numpy-base                1.21.2           py38h79a1101_0
[conda] pytorch                   1.10.1          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.10.1                   pypi_0    pypi
[conda] torchaudio                0.10.1               py38_cu113    pytorch
[conda] torchvision               0.11.2                   pypi_0    pypi

**Comment by SS-JIA** [comment]
Hi, what if you try without lite interpreter?

So when creating the model
```
import torch
from torchvision import models
from torch.utils.mobile_optimizer import optimize_for_mobile
model = models.mobilenet_v2(pretrained=True)
scripted_model=torch.jit.script(model)
opt_m=optimize_for_mobile(scripted_model,backend='vulkan')
torch.jit.save(opt_m, "mobilenet_v2_vulkan.pt")
opt_m._save_for_lite_interpreter("mobilenet_v2_vulkan.ptl")
```

And then in the app
```
Module mModule = Module.load(MainActivity.assetFilePath(getApplicationContext(), "mobilenet_v2_vulkan.ptl"), Device.VULKAN)
```

**Comment by dinhkt** [comment]
It seems Module.load now need another arguments called Map<String,String> extraFiles (based on the suggestion from Android Studio ```Module.load(String modelPath,Map<String,String> extraFiles,Device device) ```), I don't know what to put there so I set it null:
```Module.load(MainActivity.assetFilePath(getApplicationContext(), "mobilenet_v2_vulkan.pt"),null, Device.VULKAN);```

It failed when loading the model:
```D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.pytorch.demo.visionapp, PID: 16216
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libpytorch_jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:22)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43)
        at org.pytorch.NativePeer.<clinit>(NativePeer.java:10)
        at org.pytorch.Module.load(Module.java:28)
        at org.pytorch.demo.vision.imgclassification.ICActivity.onCreate(ICActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:8207)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3808)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process: Sending signal. PID: 16216 SIG: 9
```
There is a similar problem https://discuss.pytorch.org/t/unable-to-get-pytorch-1-9-working-on-android-couldnt-find-libpytorch-jni-so/124280 . It seems libpytorch_jni.so doesn't exist in the built apk, only libpytorch_jni_lite.so

**Comment by dinhkt** [comment]
I figured it out. By default, ```./scripts/build_android.sh``` will build for lite interpreter support. So I need to specify BUILD_LITE_INTERPRETER=0 and then my generated aars can work with Module.load. I can use your model from this comment https://github.com/pytorch/pytorch/issues/57893#issuecomment-836750112, but when I generated the model myself, I met the same problem as the author in that post.

**Comment by SS-JIA** [comment]
ah yes, sorry I forgot to mention you will need to build without Lite Interpreter support. Glad you figured it out though 😄 

So to fix the build error, you will need to install Vulkan on your host machine. To do this,

* Download the correct package from https://vulkan.lunarg.com/sdk/home
* Unpack it to some directory (call is `VULKAN_SDK_ROOT`

Then run
```
cd $VULKAN_SDK_ROOT
source setup-env.sh
sudo python install_vulkan.py
```

After this, reload your terminal so that VULKAN_SDK is set. You should be able to build successfully now.

Let me know if there are any other issues!

**Comment by dinhkt** [comment]
yes I can successfully built torch with vulkan support now. Thank you! 
There is a problem when I use yolov5 model. I can convert the model successfully but when using it in the app, this error happen:
```
2022-01-18 22:07:52.462 11171-11558/org.pytorch.demo.visionapp E/AndroidRuntime: FATAL EXCEPTION: ModuleActivity
    Process: org.pytorch.demo.visionapp, PID: 11171
    java.lang.RuntimeException: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/models/yolo/___torch_mangle_839.py", line 261, in forward
        _79 = torch.size(_78, 0)
        _80 = [_79, 3, 85, torch.size(_78, 2), torch.size(_78, 3)]
        _81 = torch.permute(torch.view(_78, _80), [0, 1, 3, 4, 2])
                            ~~~~~~~~~~ <--- HERE
        _82 = torch.contiguous(_81)
        y = torch.sigmoid(_82)
    
    Traceback of TorchScript, original code (most recent call last):
    /home/arik/vulkan_pytorch/pytorch/script_model/yolov5/yolov5/models/yolo.py(54): forward
    /home/arik/.local/lib/python3.8/site-packages/torch/nn/modules/module.py(1090): _slow_forward
    /home/arik/.local/lib/python3.8/site-packages/torch/nn/modules/module.py(1102): _call_impl
    /home/arik/vulkan_pytorch/pytorch/script_model/yolov5/yolov5/models/yolo.py(149): _forward_once
    /home/arik/vulkan_pytorch/pytorch/script_model/yolov5/yolov5/models/yolo.py(126): forward
    /home/arik/.local/lib/python3.8/site-packages/torch/nn/modules/module.py(1090): _slow_forward
    /home/arik/.local/lib/python3.8/site-packages/torch/nn/modules/module.py(1102): _call_impl
    /home/arik/.local/lib/python3.8/site-packages/torch/jit/_trace.py(958): trace_module
    /home/arik/.local/lib/python3.8/site-packages/torch/jit/_trace.py(741): trace
    export.py(77): export_torchscript
    export.py(434): run
    /home/arik/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py(28): decorate_context
    export.py(500): main
    export.py(505): <module>
    RuntimeError: falseINTERNAL ASSERT FAILED at "/home/ncl/ktdinh/pytorch/aten/src/ATen/native/vulkan/ops/Tensor.cpp":255, please report a bug to PyTorch. Only Tensors with 1 <= dim <= 4 can be represented as a Vulkan Image!
    
        at org.pytorch.NativePeer.forward(Native Method)
        at org.pytorch.Module.forward(Module.java:52)
        at org.pytorch.demo.vision.objectdetection.ObjectDetectionActivity.analyzeImage(ObjectDetectionActivity.java:131)
        at org.pytorch.demo.vision.objectdetection.ObjectDetectionActivity.analyzeImage(ObjectDetectionActivity.java:35)
        at org.pytorch.demo.vision.AbstractCameraXActivity.lambda$setupCameraX$2$AbstractCameraXActivity(AbstractCameraXActivity.java:92)
        at org.pytorch.demo.vision.-$$Lambda$AbstractCameraXActivity$t0OjLr-l_M0-_0_dUqVE4yqEYnE.analyze(Unknown Source:2)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.analyzeImage(ImageAnalysisAbstractAnalyzer.java:57)
        at androidx.camera.core.ImageAnalysisNonBlockingAnalyzer$1.run(ImageAnalysisNonBlockingAnalyzer.java:135)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-01-18 22:07:52.482 11171-11171/org.pytorch.demo.visionapp I/ViewRootImpl@94542bc[MainActivity]: stopped(false) old=true
2022-01-18 22:07:52.483 11171-11171/org.pytorch.demo.visionapp I/ViewRootImpl@94542bc[MainActivity]: stopped(false) old=false
2022-01-18 22:07:52.490 11171-11558/org.pytorch.demo.visionapp I/Process: Sending signal. PID: 11171 SIG: 9
```
Is this due to the limit of vulkan? I tried some other models and the same problem happened.
Should I open a new issue about this?

**Comment by SS-JIA** [comment]
Ah yes, unfortunately it's a limitation of the Vulkan backend right now. We currently do not have a way to represent tensors that are 5 dimensional or more. This is something we plan to address in the future.

Just curious, what kind of models are you trying to run with the Vulkan backend?

**Comment by dinhkt** [comment]
Thank you for your support!
The error I post above is when I use yolov5, I also want to run my custom pose estimation model.

**Comment by SS-JIA** [comment]
Gotcha. We'll keep YOLO v5 and similar models in mind when deciding what features to add to the backend.
