### ISSUE TITLE
The jit model will fail when calling the torch.autograd.functional.jacobian with multiple inputs and setting the vectorize to true.

### ISSUE THREAD

**Issue by zhangylch** [pytorch/pytorch#71261]
### 🐛 Describe the bug

When i try to obtain the jacobian of a jit model with vectorize setting to true, I will encounter the error "Cannot access data pointer of Tensor that doesn't have storage". And if a disable the jit.scipt, the model can be excuted in the right way. Next is the code that can reproduce the error.
```
import torch
from torch import nn
from torch.nn import Linear,Sequential,LayerNorm
from torch.autograd.functional import jacobian
class jaco_bug(torch.nn.Module):
    def __init__(self):
        super(jaco_bug,self).__init__()
        self.linear=Linear(10,10)
        self.layernorm=LayerNorm(10)
        self.linear1=Linear(10,5)
        self.silu=nn.SiLU()
        
    def forward(self,x,y):
        x=x+y
        return torch.sum(self.linear1(self.layernorm(self.silu(self.linear(x)))),dim=0)

testmodel=jaco_bug().eval()
testmodel=torch.jit.script(testmodel)

for i in range(100):
    x=torch.randn(3,10) 
    y=torch.randn(3,10) 
    hess=jacobian(lambda x: testmodel(x,y) ,x,create_graph=False,vectorize=True)
    print(hess)

```
![Uploading 捕获.JPG…]()

### Versions

Torch: 1.10

**Comment by davidberard98** [comment]
```
#0  __cxxabiv1::__cxa_throw (obj=0x55555825de00, tinfo=0x7fffe242c8b8 <typeinfo for c10::Error>, dest=0x7fffcbb30c96 <c10::Error::~Error()>) at /home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/.build/x86_64-conda-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:80
#1  0x00007fffcbb4ed17 in c10::detail::torchCheckFail (func=0x7fffce0cbaa9 <c10::TensorImpl::data() const::__func__> "data", file=0x7fffce0cb13e "../c10/core/TensorImpl.h", line=1222, msg=0x7fffce0cb158 "Cannot access data pointer of Tensor that doesn't have storage") at ../c10/util/Exception.cpp:94
#2  0x00007fffd3372c32 in c10::TensorImpl::data (this=0x55555801cdf0) at ../c10/core/TensorImpl.h:1220
#3  0x00007fffd3373374 in at::TensorBase::data_ptr (this=0x555558073580) at ../aten/src/ATen/core/TensorBase.h:496
#4  0x00007fffd6f215f1 in torch::jit::tensorexpr::TensorExprKernel::prepareRunArgs (this=0x5555580e4690, inputs=..., outputs=...) at ../torch/csrc/jit/tensorexpr/kernel.cpp:1644
#5  0x00007fffd6f21a90 in torch::jit::tensorexpr::TensorExprKernel::runKernel (this=0x5555580e4690, stack=...) at ../torch/csrc/jit/tensorexpr/kernel.cpp:1687
#6  0x00007fffd6f20d2e in torch::jit::tensorexpr::TensorExprKernel::run (this=0x5555580e4690, stack=...) at ../torch/csrc/jit/tensorexpr/kernel.cpp:1578
#7  0x00007fffd6b469d0 in torch::jit::<lambda(torch::jit::Stack&)>::operator()(torch::jit::Stack &) const (__closure=0x555558215e40, stack=...) at ../torch/csrc/jit/passes/tensorexpr_fuser.cpp:1244
...
```

cc @huiguoo (oncall for NNC) - this looks like there is a functorch tensor getting into NNC somehow (`BatchedTensorImpl.h`)

**Comment by zhangylch** [comment]
May I ask there is any progress? The error still exists in torch1.12.

**Comment by zhangylch** [comment]
> 


May I ask there is any progress? The error still exists in torch1.12.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
