### ISSUE TITLE
numpy dependency issue causing many test failures across CI

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#71320]
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
Root caused and currently being mitigated by https://github.com/pytorch/pytorch/pull/71327. Docker jobs are still building so the CI will still be broken until those are completed.

## Error looks like
```
2022-01-14T14:36:41.8516735Z Running test_quantization ... [2022-01-14 14:36:41.851282]
2022-01-14T14:36:41.8517319Z Executing ['/opt/conda/bin/python', 'test_quantization.py', '-v', '--import-slow-tests', '--import-disabled-tests'] ... [2022-01-14 14:36:41.851337]
2022-01-14T14:36:43.0396491Z RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
2022-01-14T14:36:43.0396980Z Traceback (most recent call last):
2022-01-14T14:36:43.0397348Z   File "test_quantization.py", line 25, in <module>
2022-01-14T14:36:43.0397801Z     from quantization.core.test_workflow_ops import TestFakeQuantizeOps  # noqa: F401
2022-01-14T14:36:43.0398207Z   File "/var/lib/jenkins/workspace/test/quantization/core/test_workflow_ops.py", line 32, in <module>
2022-01-14T14:36:43.0398941Z     from torch.testing._internal.common_cuda import TEST_CUDA
2022-01-14T14:36:43.0399807Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_cuda.py", line 31, in <module>
2022-01-14T14:36:43.0400282Z     import numba.cuda
2022-01-14T14:36:43.0400816Z   File "/opt/conda/lib/python3.7/site-packages/numba/__init__.py", line 38, in <module>
2022-01-14T14:36:43.0401159Z     from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
2022-01-14T14:36:43.0401562Z   File "/opt/conda/lib/python3.7/site-packages/numba/core/decorators.py", line 12, in <module>
2022-01-14T14:36:43.0401859Z     from numba.stencils.stencil import stencil
2022-01-14T14:36:43.0402234Z   File "/opt/conda/lib/python3.7/site-packages/numba/stencils/stencil.py", line 11, in <module>
2022-01-14T14:36:43.0402551Z     from numba.core import types, typing, utils, ir, config, ir_utils, registry
2022-01-14T14:36:43.0403178Z   File "/opt/conda/lib/python3.7/site-packages/numba/core/ir_utils.py", line 16, in <module>
2022-01-14T14:36:43.0405219Z     from numba.core.extending import _Intrinsic
2022-01-14T14:36:43.0405927Z   File "/opt/conda/lib/python3.7/site-packages/numba/core/extending.py", line 19, in <module>
2022-01-14T14:36:43.0407278Z     from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
2022-01-14T14:36:43.0408006Z   File "/opt/conda/lib/python3.7/site-packages/numba/core/pythonapi.py", line 12, in <module>
2022-01-14T14:36:43.0408443Z     from numba import _helperlib
2022-01-14T14:36:43.0408679Z ImportError: numpy.core.multiarray failed to import
2022-01-14T14:36:43.2026600Z Traceback (most recent call last):
2022-01-14T14:36:43.2026882Z   File "test/run_test.py", line 1101, in <module>
2022-01-14T14:36:43.2029008Z     main()
2022-01-14T14:36:43.2029251Z   File "test/run_test.py", line 1079, in main
2022-01-14T14:36:43.2031254Z     raise RuntimeError(err_message)
2022-01-14T14:36:43.2031648Z RuntimeError: test_quantization failed!
2022-01-14T14:36:43.4385380Z + cleanup
2022-01-14T14:36:43.4385599Z + retcode=1
```

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>

e.g.
- 1/14/22 around 12:00am incident began
- 1/14/22 6:30am detected by @mruberry on the HUD
- 1/14/22 12:18pm root caused by @malfet who tried "running "import torch" and figuring out that it does not raise the error, and then reading backtrace once again"
- 1/14/22 12:41pm mitigated by @malfet's fix: https://github.com/pytorch/pytorch/pull/71327
- 1/14/22  closed by…

</details>

## User impact
Linux CI broken on HUD and across PRs.

## Root cause
*What was the root cause of this issue?*
as the newly released buggy numba v0.55 was not compatible with an older numpy (we have numpy 1.18.5)

## Mitigation
*How did we mitigate the issue?*
By pinning numba to v0.54

## Prevention/followups
*How do we prevent issues like this in the future?* (The below are NOT mutually exclusive)
1. pin all dependencies to prevent future breakages, but also schedule monthly reviews to update the pins
2. just not install anything in the scripts and put everything in a requirements-ci.txt and only install this in Docker
3. add test to our Docker build script to just `import numpy` and `numba` and print its versions

**Comment by seemethere** [comment]
I don't believe https://github.com/pytorch/builder/pull/927 is the root cause here since images from `pytorch/builder` don't get used outside of binary builds

**Comment by malfet** [comment]
Hmm, looks like we are already testing against "1.21.5", according to logs:

Also, builds are indeed done against 1.18.5:
```
jenkins@27817bc7fc2d:~/workspace$ python
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.18.5'
>>> 
```

**Comment by atalman** [comment]
The pytorch/builder#927 is test PR and not deployed to prod .

**Comment by malfet** [comment]
I was reading the error wrong all the time, here is a single line repro:
```
t$ python -c "import numba"
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/numba/__init__.py", line 38, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/opt/conda/lib/python3.7/site-packages/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/opt/conda/lib/python3.7/site-packages/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/opt/conda/lib/python3.7/site-packages/numba/core/ir_utils.py", line 16, in <module>
    from numba.core.extending import _Intrinsic
  File "/opt/conda/lib/python3.7/site-packages/numba/core/extending.py", line 19, in <module>
    from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
  File "/opt/conda/lib/python3.7/site-packages/numba/core/pythonapi.py", line 12, in <module>
    from numba import _helperlib
ImportError: numpy.core.multiarray failed to import
```

**Comment by janeyx99** [comment]
Oh I see you are fixing it with https://github.com/pytorch/pytorch/commit/ac7f188c64805f2f9dd134f5781d3b584688e677

**Comment by atalman** [comment]
Ok, so latest numba is not compatible with the numpy version we use and breaks the test

**Comment by malfet** [comment]
It is not, but it is, as `pip uninstall numba; pip install numba` solves the problem:
```
[ec2-user@ip-10-0-3-220 ~]$ docker image list
REPOSITORY                                                                               TAG                                        IMAGE ID       CREATED        SIZE
308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-bionic-py3.7-clang9   0d18ad2827487386d2a7864b11fec5bc83de6545   95b0c1b232dd   6 hours ago    9.83GB
308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine                                 latest                                     6dbb9cc54074   9 months ago   5.61MB
[ec2-user@ip-10-0-3-220 ~]$ docker run -it 95b0c1b232dd bash -c "python -c 'import numba' || pip uninstall -y numba; pip install numba; python -c 'import numba;print(True)'"
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/numba/__init__.py", line 38, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/opt/conda/lib/python3.7/site-packages/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/opt/conda/lib/python3.7/site-packages/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/opt/conda/lib/python3.7/site-packages/numba/core/ir_utils.py", line 16, in <module>
    from numba.core.extending import _Intrinsic
  File "/opt/conda/lib/python3.7/site-packages/numba/core/extending.py", line 19, in <module>
    from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
  File "/opt/conda/lib/python3.7/site-packages/numba/core/pythonapi.py", line 12, in <module>
    from numba import _helperlib
ImportError: numpy.core.multiarray failed to import
Found existing installation: numba 0.55.0
Uninstalling numba-0.55.0:
  Successfully uninstalled numba-0.55.0
Collecting numba
  Downloading numba-0.55.0-1-cp37-cp37m-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 38.6 MB/s 
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /opt/conda/lib/python3.7/site-packages (from numba) (0.38.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from numba) (58.0.4)
Requirement already satisfied: numpy<1.22,>=1.18 in /opt/conda/lib/python3.7/site-packages (from numba) (1.18.5)
Installing collected packages: numba
Successfully installed numba-0.55.0
True
```
