### ISSUE TITLE
Download Error about Windows Version

### ISSUE THREAD

**Issue by shinalone** [pytorch/pytorch#7132]
## env:
windows 10, python3.5.4, pip10.1, cuda9.1, cudnn7

## error code:
```
(ame) C:\Users\shina>pip install http://download.pytorch.org/whl/cu91/torch-0.4.0-cp35-cp35m-win_amd64.whl
Collecting torch==0.4.0 from http://download.pytorch.org/whl/cu91/torch-0.4.0-cp35-cp35m-win_amd64.whl
  Downloading http://download.pytorch.org/whl/cu91/torch-0.4.0-cp35-cp35m-win_amd64.whl (607.0MB)
    7% |██▎                             | 42.6MB 221kB/s eta 0:42:28
Exception:
Traceback (most recent call last):
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\commands\install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\operations\prepare.py", line 310, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\download.py", line 678, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\utils\misc.py", line 575, in unpack_file
    flatten=not filename.endswith('.whl')
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\utils\misc.py", line 460, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "c:\install\anaconda3\envs\ame\lib\zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "c:\install\anaconda3\envs\ame\lib\zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
[Help, thanks!]()

**Comment by shinalone** [comment]
@peterjc123 help!

**Comment by peterjc123** [comment]
@shinalone Use a better proxy and everything will be fine.

**Comment by shinalone** [comment]
@peterjc123 
```
  File "c:\install\anaconda3\envs\ame\lib\site-packages\pip\_internal\utils\misc.py", line 460, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "c:\install\anaconda3\envs\ame\lib\zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "c:\install\anaconda3\envs\ame\lib\zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
Are you sure?  NOT  ` ReadTimeoutError`.

**Comment by shinalone** [comment]
@peterjc123 I updated pip to version10, about it?

**Comment by peterjc123** [comment]
@shinalone Yes, it's a network error. You can see apparently from the info you provided that the download process is not complete. So the error may not be at our side.

**Comment by shinalone** [comment]
@peterjc123 Okay, thank you.

**Comment by shashanka300** [comment]
hi i am facing the same issue i tried both cpu and gpu version
the error remains the same ,any on e found a fix
  Downloading http://download.pytorch.org/whl/cu90/torch-0.4.0-cp36-cp36m-win_amd64.whl
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\commands\install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "c:\program files\python36\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\program files\python36\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\program files\python36\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "c:\program files\python36\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\operations\prepare.py", line 310, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "c:\program files\python36\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "c:\program files\python36\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\download.py", line 678, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "c:\program files\python36\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\utils\misc.py", line 575, in unpack_file
    flatten=not filename.endswith('.whl')
  File "c:\program files\python36\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\utils\misc.py", line 460, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "c:\program files\python36\lib\zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "c:\program files\python36\lib\zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by shashanka300** [comment]
figured out its the network issue

**Comment by amandalmia14** [comment]
Not able to download !!
pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp35-cp35m-win_amd64.whl
Error - 
Windows only CPU.

**Comment by peterjc123** [comment]
@amandalmia14 It's a network problem. The wheel downloads well here.
