### ISSUE TITLE
Cannot import PyTorch in Alpine Docker Container

### ISSUE THREAD

**Issue by barissayil** [pytorch/pytorch#71381]
### 🐛 Describe the bug

The MRE below should be enough to explain what I'm trying to do. Google doesn't help as it seems to be a unique error, which surprised me since Alpine & PyTorch are both fairly popular.

Dockerfile:
```
FROM nginx:stable-alpine as production
WORKDIR /app
RUN apk update && apk add --no-cache python3 bash && \
  python3 -m ensurepip && \
  rm -r /usr/lib/python*/ensurepip && \
  pip3 install --upgrade pip setuptools && \
  if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
  if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
  rm -r /root/.cache
RUN apk update && apk add gcc g++ python3-dev musl-dev
RUN pip install torch==1.10.1 --find-links https://download.pytorch.org/whl/torch_stable.html
```

Build & bash into it:
```
sudo docker build -t mini .
sudo docker run --name torch-pls -it --entrypoint bash mini
```

Launch Python:
```
bash-5.1# python
Python 3.9.5 (default, Nov 24 2021, 21:19:13) 
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

Import PyTorch and see it fail:
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/torch/__init__.py", line 196, in <module>
    _load_global_deps()
  File "/usr/lib/python3.9/site-packages/torch/__init__.py", line 149, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: Error relocating /usr/lib/python3.9/site-packages/torch/lib/libgomp-a34b3233.so.1: pthread_attr_setaffinity_np: symbol not found
```

Can anyone help?

### Versions

```
Connecting to raw.githubusercontent.com (185.199.111.133:443)
saving to 'collect_env.py'
collect_env.py       100% |************************************************************************************************************************************************| 16723  0:00:00 ETA
'collect_env.py' saved
bash-5.1# ls
collect_env.py
bash-5.1# python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Alpine Linux v3.14 (x86_64)
GCC version: (Alpine 10.3.1_git20210424) 10.3.1 20210424
Clang version: Could not collect
CMake version: Could not collect
Libc version: -

Python version: 3.9.5 (default, Nov 24 2021, 21:19:13)  [GCC 10.3.1 20210424] (64-bit runtime)
Python platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] torch==1.10.1+rocm4.2
[conda] Could not collect
```

**Comment by wparam** [comment]
Same here +1

**Comment by nguyenvinhlinh** [comment]
same here! +1

**Comment by yoniker** [comment]
@barissayil You closed the issue, how did you solve it?

**Comment by nguyenvinhlinh** [comment]
I work around is to use different python image tag! 
I use non-alpine image ex: python:3.9.7 for example.

**Comment by jakwisn** [comment]
Did someone got it to work with alpine?

**Comment by Turkish** [comment]
@barissayil  this is still open big time, why did you close the isse ? It's still unresolved and it's crucial for security to support alpine.

**Comment by Turkish** [comment]
@nguyenvinhlinh  non alpine has far more os packages, with many security vulnerabilities in them. It's not a work around it's a security compromise. For production environments you can't afford to do this.

**Comment by hteeyeoh** [comment]
any solution on this, I am facing this issue as well

**Comment by vishwa3908** [comment]
OSError: Error relocating /usr/local/lib/python3.10/site-packages/torch/lib/libgomp-a34b3233.so.1: pthread_attr_setaffinity_np: symbol not found
getting this error when using torch with python 3.10 alpine image 
ubuntu have far more vulnerability issues any workaround for alpine ?

**Comment by n-traore** [comment]
Same issue here. It works well when I build my image using debian-slim. Though it would be better to use alpine.

**Comment by mvdiogo** [comment]
on python:3.12.5-alpine3.20 i got the error:
OSError: Error relocating /usr/local/lib/python3.12/site-packages/torch/lib/libgomp-a34b3233.so.1: pthread_attr_setaffinity_np: symbol not found
the install was:
python -m pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu && \

**Comment by MaxClau** [comment]
Any news on this topic ? Still experimenting this error with python:3-10-alpine
