### ISSUE TITLE
[feature request] [discussion] Generalize / recommend behavior of reset_parameters (and potentially rename)

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#71404]
### 🚀 The feature, motivation and pitch

It seems that FX isn't playing nice with any instance methods except forward: https://github.com/pytorch/vision/pull/5197#discussion_r786695774

This also seems to prevent reset_parameters being supported, as additional instance methods will not work after FX (?)

Methods of this kind exist in practically all models, but have different names: `reset_parameters`, `_reset_parameters`, `_init_parameters` etc

Related issues: https://github.com/pytorch/vision/issues/3410, https://github.com/pytorch/pytorch/issues/66335

**Comment by datumbox** [comment]
@jamesr66a for some context, the FX issue highlighted here by @vadimkantorov is related to the fact that `nn.Module` class info is lost for custom layers during tracing (related to #66335). This means that standard [model initialization idiom](https://github.com/pytorch/vision/blob/eac3dc7bab436725b0ba65e556d3a6ffd43c24e1/torchvision/models/resnet.py#L206-L221) of traversing the `modules()` of the model and checking their instance via `isinstance()` to decide the initialization scheme won't work.

**Comment by vadimkantorov** [comment]
One solution is to provide a decorator @torch.jit.fx.throw_if_fx_traced, that will throw if self is FX traced

**Comment by jbschlosser** [comment]
Somewhat related to supporting `reset_parameters()` - the function as a concept has fundamental conflicts with inheritance. I ran into this when originally trying to support reset_parameters() across torch.nn modules (see [here](https://github.com/pytorch/pytorch/pull/54508#discussion_r602015661)).
```python
import torch

class BaseModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(3, 3)
        self.reset_parameters()

    def forward(self, x):
        return self.linear(x)

    def reset_parameters(self):
        torch.nn.init.kaiming_normal_(self.linear.weight)


class SubModule(BaseModule):
    def __init__(self):
        super().__init__()
        self.sub_linear = torch.nn.Linear(3, 3)
        self.reset_parameters()

    def forward(self, x):
        return self.sub_linear(super()(x))

    def reset_parameters(self):
        torch.nn.init.kaiming_normal(self.sub_linear.weight)

m = SubModule()
```
```
Traceback (most recent call last):
  File "inherit.py", line 28, in <module>
    m = SubModule()
  File "inherit.py", line 18, in __init__
    super().__init__()
  File "inherit.py", line 7, in __init__
    self.reset_parameters()
  File "inherit.py", line 26, in reset_parameters
    torch.nn.init.kaiming_normal(self.sub_linear.weight)
  File "torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SubModule' object has no attribute 'sub_linear'
```

As described in the link, the following happens:
1. `SubModule.__init__()` is called
2. `super().__init__()` is called (AKA `BaseModule.__init__()`)
3. In `BaseModule.__init__()`, `self.reset_parameters()` calls the overridden `SubModule.reset_parameters()`
4. `SubModule.reset_parameters()` tries to reset parameters or buffers that haven't been created yet - error

This comes up in practice in a few places within the torch.nn modules where inheritance is used.

**Comment by vadimkantorov** [comment]
One other work that does use resetting particular layers during training: https://twitter.com/nikishin_evg/status/1527682443184115713

**Comment by vadimkantorov** [comment]
Another recent work that does reset and retrain last layer to improve robustness: https://twitter.com/polkirichenko/status/1511883670923137026

**Comment by datumbox** [comment]
@jbschlosser I recently stumbled upon a technique that uses meta-classes to solve the inheritance problem you described. See [here](https://stackoverflow.com/a/68939584).

**Comment by jbschlosser** [comment]
@datumbox Interesting! Looks like that might work for the cases in torch.nn. It'd be the responsibility of the user to do that for any custom modules that use inheritance.

**Comment by vadimkantorov** [comment]
IMO the init code should be available for user calls as standardized method, not being able to call it after FX is okay and could be mentioned explicitly via decorators / docs + FX could create stub impls for all methods except forward that throw exception with comprehensible message

**Comment by datumbox** [comment]
@vadimkantorov I understand where you are coming from. For some users, JIT or FX might not be as important. For others who are into mobile deployment or quantization, they are critical. As PyTorch devs, we need to ensure we provide a consistent experience across the various solutions. Right now there are ways for users to reinitialize the models, without a `reset_parameters()`. The solutions are not as elegant and often require context (is the model jit-scripted? Is it parallelized? Is it FX-traced?). My view is that in cases where the solution requires too much context, it's preferable to let the users choose what works for them rather than drive them towards a solution that works in some cases or might shoot them on the foot. 

Please note that I am not trying to convince you, I understand we might have to agree we disagree on this. Having said that, I agree with you that this is an interesting problem worth solving and worth revisiting (part of the reason I come to it every now and then). Sometimes problems like this might require a bit more time to plan carefully. Thankfully @jbschlosser has also his eyes on it and trust me, he has previously snipped a couple of long standing issues on PyTorch. Perhaps this is the next one to aim for once there is bandwidth. :)

**Comment by vadimkantorov** [comment]
> The solutions are not as elegant and often require context

Worst of all, they now require quite deeper acquaintance with PyTorch codebase to even find the place where the module/model is initialized to find the correct place to copy-paste from
