### ISSUE TITLE
torch.bincount doesn't seem to output the result based on minlength

### ISSUE THREAD

**Issue by Dayro-9** [pytorch/pytorch#71405]
I ran the following code on google colab. 
```
class ConfusionMatrix(object):
    def __init__(self, num_classes):
        self.num_classes = num_classes
        self.mat = None


    def update(self, target, output):
        """
        Update confusion matrix.

        Args:
            target: ground truth
            output: predictions of models

        Shape:
            - target: :math:`(minibatch, C)` where C means the number of classes.
            - output: :math:`(minibatch, C)` where C means the number of classes.
        """
        n = self.num_classes
       #n = 11
        if self.mat is None:
            self.mat = torch.zeros((n, n), dtype=torch.int64, device=target.device)
            #selt.mat is torch.Size([11, 11])
        with torch.no_grad():
            print("target shape:{}, :{}".format(target.shape, target))
            k = (target >= 0) & (target < n)
            #k is torch.Size([32]), tensor([True,..., True], device='cuda:0')
            inds = n * target[k].to(torch.int64) + output[k]
            #inds is torch.Size([32]), tensor([ 66,..., 130], device='cuda:0')
            self.mat += torch.bincount(inds, minlength=n**2).reshape(n, n)
           #torch.bincount(inds, minlength=n**2) is torch.Size([131]) . This is wrong.           
```
`torch.bincount` cannot output a 1D vector of` minlength` length, and reported an error as follows. Where is the problem? I am not a native English speaker, so please forgive me if there exist inappropriate expressions.
```
Traceback (most recent call last):
  File "osbp.py", line 285, in <module>
    main(args)
  File "osbp.py", line 110, in main
    h_score = validate(val_loader, classifier, args)
  File "osbp.py", line 211, in validate
    confmat.update(target, output.argmax(1))
  File "../../../common/utils/metric/__init__.py", line 72, in update
    self.mat += torch.bincount(inds, minlength=n**2).reshape(n, n)
RuntimeError: shape '[11, 11]' is invalid for input of size 131
```
- PyTorch 
- PyTorch version: 1.10.0+cu111
- Python version:3.7.12
- CUDA version:11.1, V11.1.105
- GPU models and configuration: Tesla P100-PCIE
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries: prettytable, torch

**Comment by Dayro-9** [comment]
> From the [bincount documentation](https://pytorch.org/docs/stable/generated/torch.bincount.html)
> 
> > The number of bins (size 1) is one larger than the largest value in input unless input is empty, in which case the result is a tensor of size 0.
> 
> Since the tensor has an element of value 130 (it appears to be the last element), the size of the tensor after bincount will be at least 131. `minlength` will give the guaranteed minimum size for the returned tensor but since 131 > 121, the returning tensor will be of size 131.
> 
> If you need more help, [the forum](https://discuss.pytorch.org/) is a the recommended place for asking questions about the API. We try to use issues for feature requests or bugs

Thank you very much, my problem is solved.
