### ISSUE TITLE
apply_ fails within test_ceil/_round/_floor

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#7144]
Changes:

```
diff --git a/test/test_torch.py b/test/test_torch.py
index a14c6a9..97d3651 100644
--- a/test/test_torch.py
+++ b/test/test_torch.py
@@ -260,6 +260,8 @@ class TestTorch(TestCase):
             input = []
             input.append(list(range(-5, 5)))
             input.append([x + 1e-6 for x in range(-5, 5)])
+            input.append([x + 1e10 for x in range(-5, 5)])
+            input.append([x + 1e30 for x in range(-5, 5)])
             input.append(torch.randn(10).tolist())
             input.append((torch.randn(10) + 1e6).tolist())
             input.append([math.pi * (x / 2) for x in range(-5, 5)])
jenkins@978044efae99:~/workspace$ python test/test_torch.py
```

Error log

```
jenkins@978044efae99:~/workspace$ python test/test_torch.py
...............s..........................E.........sss.............................s................s.E...........s....................s...........................................s..........ss......s........................s...E............ss........s...............................ss....................s.....ss..ss.
======================================================================
ERROR: test_ceil (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_torch.py", line 493, in test_ceil
    self._test_math_by_name('ceil')
  File "test/test_torch.py", line 340, in _test_math_by_name
    self.__test_math_by_name(function_name + "_", function_name, True)
  File "test/test_torch.py", line 336, in __test_math_by_name
    self._test_math(torchfn, mathfn)
  File "test/test_torch.py", line 276, in _test_math
    compare_reference(input, torch.double)
  File "test/test_torch.py", line 272, in compare_reference
    res2 = input.clone().apply_(lambda x: mathfn(x))
RuntimeError: Overflow when unpacking double

======================================================================
ERROR: test_floor (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_torch.py", line 490, in test_floor
    self._test_math_by_name('floor')
  File "test/test_torch.py", line 340, in _test_math_by_name
    self.__test_math_by_name(function_name + "_", function_name, True)
  File "test/test_torch.py", line 336, in __test_math_by_name
    self._test_math(torchfn, mathfn)
  File "test/test_torch.py", line 276, in _test_math
    compare_reference(input, torch.double)
  File "test/test_torch.py", line 272, in compare_reference
    res2 = input.clone().apply_(lambda x: mathfn(x))
RuntimeError: Overflow when unpacking double

======================================================================
ERROR: test_round (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_torch.py", line 524, in test_round
    self._test_math(torch.round, round)
  File "test/test_torch.py", line 276, in _test_math
    compare_reference(input, torch.double)
  File "test/test_torch.py", line 272, in compare_reference
    res2 = input.clone().apply_(lambda x: mathfn(x))
RuntimeError: Overflow when unpacking double

----------------------------------------------------------------------
Ran 318 tests in 40.219s

FAILED (errors=3, skipped=23)
```

On `pytorch-linux-trusty-py3.6-gcc5.4`

Debugging shows this errors appears within [recursive apply](https://github.com/pytorch/pytorch/blob/30ec06c140b0428d591e2f5007bc8046d1bdf7c4/torch/csrc/utils/tensor_apply.cpp#L30) if the values is 1e30. I'm not able to reproduce this within the environment of my dev machine.

**Comment by cpuhrsch** [comment]
cc @colesbury

**Comment by ngimel** [comment]
Closing due to age, please reopen if this is still an issue.
