### ISSUE TITLE
Can't except IndexError when indexing a CUDA Tensor with a Tensor

### ISSUE THREAD

**Issue by maxwell-aladago** [pytorch/pytorch#71572]
### 🐛 Describe the bug

Unlike the the normal behavior of throwing an `IndexError` when the index is out-of-bounds, a highly uninformative device-side assert is triggered when data `tensor` is in `CUDA` and the indexing variable is a `Tensor`.  This makes it impossible to catch the error by excepting `IndexError`.

**Reproducing Error**

```
import torch
x = torch.rand(10).to('cuda')
y = torch.tensor([11]).to('cuda')
print(x[y])
```
Instead of an `IndexError`, the program returns the following error message

```
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/IndexKernel.cu:97: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(x[y])
  File "/usr/lib/python3/dist-packages/torch/_tensor.py", line 203, in __repr__
    return torch._tensor_str._str(self)
  File "/usr/lib/python3/dist-packages/torch/_tensor_str.py", line 406, in _str
    return _str_intern(self)
  File "/usr/lib/python3/dist-packages/torch/_tensor_str.py", line 381, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/usr/lib/python3/dist-packages/torch/_tensor_str.py", line 242, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/lib/python3/dist-packages/torch/_tensor_str.py", line 90, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

In the example above, this message is returned when 

- `x[y]` where `x` and `y` are `tensors` in `CUDA`
- `x[y]` where `x` is in `CUDA` and `y` is a `tensor` in `cpu`

It throws the expected `IndexError` when 

- `x[y]` where `x` and `y` are in `cpu`
- `x[y]` where `x` is in `CUDA` or  in `cpu` and `y` is a plain integer

This problem is magnified when dealing with bigger `tensors` such as `nn.Embedding`. As an example, 

```
import torch
try:
    x = torch.nn.Embedding(100, 10)

    y = torch.randint(low=0, high=101, size=(30, 77))
    z = x(y)
except IndexError as e:
    print(e)
```

throws the expected error _`index out of range in self`_. But the following evades the `try-except` 

```
import torch
try:
    x = torch.nn.Embedding(100, 10)
     x.cuda()
    y = torch.randint(low=0, high=200, size=(30, 77)).to('cuda')
    z = x(y)
except IndexError as e:
    print(e)
```

and throws the following gigantic error message

```
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [13,0,0], thread: [92,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [13,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [13,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [13,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [65,0,0], thread: [50,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [65,0,0], thread: [51,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [65,0,0], thread: [52,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [65,0,0], thread: [53,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [65,0,0], thread: [54,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [65,0,0], thread: [55,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [65,0,0], thread: [56,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [65,0,0], thread: [57,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [65,0,0], thread: [58,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [65,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [177,0,0], thread: [84,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [177,0,0], thread: [85,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [177,0,0], thread: [86,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [177,0,0], thread: [87,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [177,0,0], thread: [88,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [177,0,0], thread: [89,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [177,0,0], thread: [90,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [177,0,0], thread: [91,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [177,0,0], thread: [92,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [177,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [6,0,0], thread: [72,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [6,0,0], thread: [73,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [6,0,0], thread: [74,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [6,0,0], thread: [75,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [6,0,0], thread: [76,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [6,0,0], thread: [77,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [6,0,0], thread: [78,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [6,0,0], thread: [79,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [6,0,0], thread: [80,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [6,0,0], thread: [81,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [36,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [36,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [36,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [36,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [36,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [36,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [36,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [36,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [36,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [36,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [59,0,0], thread: [68,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [59,0,0], thread: [69,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [59,0,0], thread: [70,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [59,0,0], thread: [71,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [59,0,0], thread: [72,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [59,0,0], thread: [73,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [59,0,0], thread: [74,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [59,0,0], thread: [75,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [59,0,0], thread: [76,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [59,0,0], thread: [77,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [77,0,0], thread: [54,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [77,0,0], thread: [55,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [77,0,0], thread: [56,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [77,0,0], thread: [57,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [77,0,0], thread: [58,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [77,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [77,0,0], thread: [60,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [77,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [77,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/build/pytorch-M3LgCG/pytorch-1.9.1+ds/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [77,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
...
```

This may well be an expected behavior. If this is the case, producing a more understandable error message will be helpful.   

### Versions

I have reproduced the error in two different `CUDA` versions (`10.2` and `11.1`) with both PyTorch `1.7` and `1.9`. Below is 
 the details of one of the machines

```
PyTorch version: 1.9.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-43-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: NVIDIA RTX A5000
GPU 1: NVIDIA RTX A5000
GPU 2: NVIDIA RTX A5000
GPU 3: NVIDIA RTX A5000

Nvidia driver version: 470.74
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.9.1
[pip3] torchvision==0.10.1
[conda] Could not collect
```

cc @ngimel

**Comment by maxwell-aladago** [comment]
When the tensors are big, it kills `cuda` without reporting it until an attempt is made to access the device. For example, 

```
import torch
x = torch.randn(30000, 768).to('cuda') 
r = torch.randn(20).to('cuda') 
index = torch.randint(low=0, high=49000, size=(30, 77)).to('cuda')
y = x[index]. # kills the kernel but does not report it. 

# normal execution continues
print(y.device). # prints 'cuda:0'
print(y.shape) # prints the appropriate shape: 30, 77, 768

# error gets thrown when an attempt is made to access cuda
z = torch.randn(10).to('cuda'). # throws the error
print(r) # throws error
print(y) throws error
```

**Comment by gchanan** [comment]
For the not being reported case, the error message describes why this is and how to address it:
```
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by ngimel** [comment]
Device asserts invalidate existing cuda context and program execution can't continue, so there's no point in trying to catch this error. The assertion error message indicates that your index is out of range. This is expected behavior.
