### ISSUE TITLE
INTERNAL ASSERT in svd_cpu

### ISSUE THREAD

**Issue by peterbell10** [pytorch/pytorch#71645]
### 🐛 Describe the bug

`test_svd_errors_and_warnings` is failing in master CI:
```
RuntimeError: falseINTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/aten/src/ATen/native/LinearAlgebraUtils.h":310, please report a bug to PyTorch. svd_cpu: Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
```
https://github.com/pytorch/pytorch/runs/4898981904?check_suite_focus=true#step:17:16119

To reproduce you need to rebuild with the latest dependencies on conda with `conda upgrade --all` after which both `test_norm_extreme_values` and `test_svd_errors_and_warnings` in `test_linalg.py` fail.

### Versions

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2060
GPU 1: NVIDIA GeForce RTX 2060

Nvidia driver version: 465.19.01
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.11.0a0+git5f28641
[conda] cudatoolkit               11.2.2               he111cf0_8    conda-forge
[conda] magma-cuda102             2.5.2                         1    pytorch
[conda] mkl                       2022.0.1           h8d4b97c_803    conda-forge
[conda] mkl-include               2022.0.1           h8d4b97c_803    conda-forge
[conda] numpy                     1.22.0           py38h6ae9a64_1    conda-forge
[conda] torch                     1.11.0a0+git5f28641          pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by mruberry** [comment]
Another example with relevant snippet https://github.com/pytorch/pytorch/runs/4899725416?check_suite_focus=true:

```
🚨 ERROR: TestLinalgCPU.test_norm_extreme_values_cpu

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 1910, in test_norm_extreme_values
    result = torch.linalg.norm(x, ord=ord)
RuntimeError: falseINTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/aten/src/ATen/native/LinearAlgebraUtils.h":310, please report a bug to PyTorch. svd_cpu: Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
		
🚨 ERROR: TestLinalgCPU.test_svd_errors_and_warnings_cpu_complex128

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 2948, in test_svd_errors_and_warnings
    svd(a)
RuntimeError: falseINTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/aten/src/ATen/native/LinearAlgebraUtils.h":310, please report a bug to PyTorch. svd_cpu: Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
		
🚨 ERROR: TestLinalgCPU.test_svd_errors_and_warnings_cpu_complex64

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 2948, in test_svd_errors_and_warnings
    svd(a)
RuntimeError: falseINTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/aten/src/ATen/native/LinearAlgebraUtils.h":310, please report a bug to PyTorch. svd_cpu: Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
		
🚨 ERROR: TestLinalgCPU.test_svd_errors_and_warnings_cpu_float32

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 2948, in test_svd_errors_and_warnings
    svd(a)
RuntimeError: falseINTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/aten/src/ATen/native/LinearAlgebraUtils.h":310, please report a bug to PyTorch. svd_cpu: Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
		
🚨 ERROR: TestLinalgCPU.test_svd_errors_and_warnings_cpu_float64

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 2948, in test_svd_errors_and_warnings
    svd(a)
RuntimeError: falseINTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/aten/src/ATen/native/LinearAlgebraUtils.h":310, please report a bug to PyTorch. svd_cpu: Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
```

This might be the #1 CI reliability issue currently. There may be other flaky linear algebra tests, too, however. @IvanYashchuk just saw an lstsq failure that may or may not be related to a PR he's working on.

**Comment by IvanYashchuk** [comment]
The source of the problem is Reference LAPACK changing its behavior for matrices with non-finite values (see https://github.com/pytorch/pytorch/issues/67693#issuecomment-958057993).

OpenBLAS was first to update to the latest LAPACK and the problem was reported in https://github.com/pytorch/pytorch/issues/67693
Now with the new year, MKL has released its new version which also uses the latest LAPACK that lead to our tests breaking.

`torch.linalg.norm`, `torch.linalg.cond` use `torch.linalg.svdvals` and NumPy does the same and the behavior changes rapidly with the new MKL:
```py
# With MKL 2021.4.0
In [1]: import numpy as np

In [2]: a = np.full((3, 3), float('nan'))

In [3]: np.linalg.svd(a, compute_uv=False)

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 5 was incorrect on entry to DLASCL.
Out[3]: array([nan, nan, nan])

# With new MKL 2022
In [1]: import numpy as np

In [2]: a = np.full((3, 3), float('nan'))

In [3]: np.linalg.svd(a, compute_uv=False)
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-3-48fccc58801d> in <module>
----> 1 np.linalg.svd(a, compute_uv=False)

~/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/numpy/core/overrides.py in svd(*args, **kwargs)

~/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/numpy/linalg/linalg.py in svd(a, full_matrices, compute_uv, hermitian)
   1658
   1659         signature = 'D->d' if isComplexType(t) else 'd->d'
-> 1660         s = gufunc(a, signature=signature, extobj=extobj)
   1661         s = s.astype(_realType(result_t), copy=False)
   1662         return s

~/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/numpy/linalg/linalg.py in _raise_linalgerror_svd_nonconvergence(err, flag)
     95
     96 def _raise_linalgerror_svd_nonconvergence(err, flag):
---> 97     raise LinAlgError("SVD did not converge")
     98
     99 def _raise_linalgerror_lstsq(err, flag):

LinAlgError: SVD did not converge
```
