### ISSUE TITLE
DISABLED test_data_parallel_module_cuda_float16 (__main__.TestDataParallelDeviceTypeCUDA)

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#71770]
platforms: rocm

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.5-py3.7-test-distributed/3045/console

```
09:10:50 ======================================================================
09:10:50 FAIL [0.018s]: test_data_parallel_module_cuda_float16 (__main__.TestDataParallelDeviceTypeCUDA)
09:10:50 ----------------------------------------------------------------------
09:10:50 Traceback (most recent call last):
09:10:50   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1553, in wrapper
09:10:50     method(*args, **kwargs)
09:10:50   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1553, in wrapper
09:10:50     method(*args, **kwargs)
09:10:50   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
09:10:50     result = test(self, **param_kwargs)
09:10:50   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 907, in only_fn
09:10:50     return fn(slf, *args, **kwargs)
09:10:50   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
09:10:50     return fn(slf, *args, **kwargs)
09:10:50   File "distributed/test_data_parallel.py", line 784, in test_data_parallel_module
09:10:50     self.assertEqual(out, expected_out, atol=dtype2prec_DONTUSE[dtype], rtol=0)
09:10:50   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 2078, in assertEqual
09:10:50     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
09:10:50 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=0 and atol=0.01, found 25 element(s) (out of 100) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.9091796875 (-1.443359375 vs. 0.4658203125), which occurred at index (18, 3).
```

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jaglinux** [comment]
Test ran successfully after applying https://github.com/pytorch/pytorch/pull/78824
cc @jeffdaily
