### ISSUE TITLE
`torch._sources.normalize_source_lines()` and consequently `torch.jit.script` fail with lambda functions

### ISSUE THREAD

**Issue by senarvi** [pytorch/pytorch#71912]
### 🐛 Describe the bug

[`normalize_source_lines()`](https://github.com/pytorch/pytorch/blob/master/torch/_sources.py#L50) crashes if there are no lines that start with "def". This happens with lambda functions.

If a function that is scripted using `torch.jit.script` calls a lambda function, [`parse_def()` calls `normalize_source_lines()`](https://github.com/pytorch/pytorch/blob/master/torch/_sources.py#L97) and the user sees an exception:

    UnboundLocalError: local variable 'idx' referenced before assignment

Minimal example to produce the error:
```python
import torch

f = lambda x, y: x + y

@torch.jit.script
def call_f():
    f(1, 2)
```

Output:
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    def call_f():
  File ".../lib/python3.9/site-packages/torch/jit/_script.py", line 1143, in script
    fn = torch._C._jit_script_compile(
  File ".../lib/python3.9/site-packages/torch/jit/_recursive.py", line 795, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File ".../lib/python3.9/site-packages/torch/jit/_script.py", line 1140, in script
    ast = get_jit_def(obj, obj.__name__)
  File ".../lib/python3.9/site-packages/torch/jit/frontend.py", line 270, in get_jit_def
    sourcelines = normalize_source_lines(sourcelines)
  File ".../lib/python3.9/site-packages/torch/jit/frontend.py", line 240, in normalize_source_lines
    fn_def = sourcelines[idx]
UnboundLocalError: local variable 'idx' referenced before assignment
```

### Versions

PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1650 Ti with Max-Q Design
Nvidia driver version: 471.41
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.790
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.6.0.dev0
[pip3] pytorch-lightning-bolts==0.2.5
[pip3] torch==1.9.0
[pip3] torch-tb-profiler==0.3.1
[pip3] torchmetrics==0.6.2
[pip3] torchtext==0.10.0
[pip3] torchvision==0.10.0

**Comment by jehnes** [comment]
I had the same issue. I was using python 3.8 though, and in my case the function normalize_source_lines that caused the error happened to be in the file lib/python3.8/site-packages/torch/_sources.py inside of my venv. (And not .../site-packages/torch/jit/frontend.py where it appears to be in python 3.9 according to the original post)

As a workaround/possible fix I modified the function as follows:

I added a line to define idx as None before the loop looking for "def"s and then added a check after that loop. In case idx is still None, which means there was no "def" found, I simply return the original source lines. I assume that it doesn't matter so much in this case if the comments or string literals are formatted nicely (certainly better than crashing). But of course, someone more familiar with the Torch JIT please check if this assumption is valid and if not, handle this case (no "def" in the source lines, lambda functions) appropriately.

Below is the function with my modifications (comments that start with "(JE)" ):



```python
def normalize_source_lines(sourcelines: List[str]) -> List[str]:
    """
    This helper function accepts a list of source lines. It finds the
    indentation level of the function definition (`def`), then it indents
    all lines in the function body to a point at or greater than that
    level. This allows for comments and continued string literals that
    are at a lower indentation than the rest of the code.
    Args:
        sourcelines: function source code, separated into lines by
                        the '\n' character
    Returns:
        A list of source lines that have been correctly aligned
    """

    def remove_prefix(text, prefix):
        return text[text.startswith(prefix) and len(prefix):]

    idx = None  # (JE) Make sure it is defined and we can check if a "def" has been found below

    # Find the line and line number containing the function definition
    for i, l in enumerate(sourcelines):
        if l.lstrip().startswith("def"):
            idx = i
            break

    # (JE) Need to check that the idx actually exists. If not, just return the original source lines (no new indentation if there is no def)
    if idx is None:
        return sourcelines

    fn_def = sourcelines[idx]

    # Get a string representing the amount of leading whitespace
    whitespace = fn_def.split("def")[0]

    # Add this leading whitespace to all lines before and after the `def`
    aligned_prefix = [whitespace + remove_prefix(s, whitespace) for s in sourcelines[:idx]]
    aligned_suffix = [whitespace + remove_prefix(s, whitespace) for s in sourcelines[idx + 1:]]

    # Put it together again
    aligned_prefix.append(fn_def)
    return aligned_prefix + aligned_suffix

```

Hope it helps!,
Jochen

**Comment by jehnes** [comment]
Sorry, I forgot to mention that my Torch version is 1.10.2+cu102, which probably is more relevant than the python version.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
