### ISSUE TITLE
Test fail on windows with cudnn v8.3.2.44 and cuda 11.5 

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#72026]
### 🐛 Describe the bug

Following test have failed on windows :
periodic-win-vs2019-cuda11.5-py3 periodic-win-vs2019-cuda11.5-py3
After upgrading to cuddn8.3.2.44

[GHA](Ref:https://github.com/pytorch/pytorch-canary/runs/4985534200?check_suite_focus=true)

Looks like both Test1 and Test2 are failed with same error:
RuntimeError: Error building extension 'torch_test_cudnn_extension'

Here is an error from the log1
22-01-28T21:44:18.5399345Z C:\Jenkins\Miniconda3\Include\pyerrors.h(315): note: see previous definition of 'HAVE_SNPRINTF'
2022-01-28T21:44:18.6418638Z [2/2] "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64/link.exe" main.o /nologo /DLL c10.lib torch_cpu.lib torch.lib /LIBPATH:C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\lib torch_python.lib /LIBPATH:C:\Jenkins\Miniconda3\libs /out:test_set_default_type.pyd
2022-01-28T21:44:18.6418861Z    Creating library test_set_default_type.lib and object test_set_default_type.exp
2022-01-28T21:44:18.6727494Z Loading extension module test_set_default_type...
2022-01-28T21:44:18.6728083Z   test_set_default_type_also_changes_aten_default_type (__main__.TestCppExtensionJIT) ... ok (15.263s)
2022-01-28T21:44:34.2244721Z   test_warning (__main__.TestCppExtensionJIT) ... [W C:\Users\runneruser\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu115\warn_mod\main.cpp:12] Warning: Error with CPUDoubleType (function foo)
2022-01-28T21:44:34.2247999Z [W C:\Users\runneruser\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu115\warn_mod\main.cpp:12] Warning: Error with CPUDoubleType (function foo)
2022-01-28T21:44:34.2256537Z [W C:\Users\runneruser\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu115\warn_mod\main.cpp:12] Warning: Error with CPUDoubleType (function foo)
2022-01-28T21:44:34.2259995Z [W C:\Users\runneruser\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu115\warn_mod\main.cpp:12] Warning: Error with CPUDoubleType (function foo)
2022-01-28T21:44:49.6741524Z UserWarning: Error with torch.DoubleTensor (Triggered internally at  C:\Users\runneruser\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu115\warn_mod\main.cpp:12.)
2022-01-28T21:44:49.6743717Z ok (31.007s)
2022-01-28T21:44:49.6745414Z Not wiping extensions build folder because Windows
2022-01-28T21:44:49.6746711Z 
2022-01-28T21:44:49.6746837Z ======================================================================
2022-01-28T21:44:49.6747177Z ERROR [17.565s]: test_jit_cudnn_extension (__main__.TestCppExtensionJIT)
2022-01-28T21:44:49.6749683Z ----------------------------------------------------------------------
2022-01-28T21:44:49.6750284Z Traceback (most recent call last):
2022-01-28T21:44:49.6761667Z   File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\utils\cpp_extension.py", line 1726, in _run_ninja_build
2022-01-28T21:44:49.6762164Z     subprocess.run(
2022-01-28T21:44:49.6762516Z   File "C:\Jenkins\Miniconda3\lib\subprocess.py", line 516, in run
2022-01-28T21:44:49.6762926Z     raise CalledProcessError(retcode, process.args,
2022-01-28T21:44:49.6763344Z subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '8']' returned non-zero exit status 1.
2022-01-28T21:44:49.6763612Z 
2022-01-28T21:44:49.6763788Z The above exception was the direct cause of the following exception:
2022-01-28T21:44:49.6763998Z 
2022-01-28T21:44:49.6764116Z Traceback (most recent call last):
2022-01-28T21:44:49.6764467Z   File "test_cpp_extensions_jit.py", line 215, in test_jit_cudnn_extension
2022-01-28T21:44:49.6764812Z     module = torch.utils.cpp_extension.load(
2022-01-28T21:44:49.6765313Z   File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\utils\cpp_extension.py", line 1130, in load
2022-01-28T21:44:49.6765700Z     return _jit_compile(
2022-01-28T21:44:49.6766169Z   File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\utils\cpp_extension.py", line 1343, in _jit_compile
2022-01-28T21:44:49.6766610Z     _write_ninja_file_and_build_library(
2022-01-28T21:44:49.6767311Z   File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\utils\cpp_extension.py", line 1455, in _write_ninja_file_and_build_library
2022-01-28T21:44:49.6767771Z     _run_ninja_build(
2022-01-28T21:44:49.6768251Z   File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\utils\cpp_extension.py", line 1742, in _run_ninja_build
2022-01-28T21:44:49.6768694Z     raise RuntimeError(message) from e
2022-01-28T21:44:49.6769026Z RuntimeError: Error building extension 'torch_test_cudnn_extension'
2022-01-28T21:44:49.6769236Z 
2022-01-28T21:44:49.6895563Z ----------------------------------------------------------------------
2022-01-28T21:44:49.6895930Z Ran 27 tests in 285.031s
2022-01-28T21:44:49.6896088Z 
2022-01-28T21:44:49.6896234Z FAILED (errors=1, skipped=5, expected failures=3)
2022-01-28T21:44:49.6896414Z 
2022-01-28T21:44:49.6896531Z Generating XML reports...
2022-01-28T21:44:49.6896947Z Generated XML report: test-reports\dist-gloo\test_cpp_extensions_jit\TEST-TestCppExtensionJIT-20220128214004.xml
2022-01-28T21:44:50.0188318Z Traceback (most recent call last):
2022-01-28T21:44:50.0188808Z   File "run_test.py", line 1101, in <module>
2022-01-28T21:44:50.0189059Z     main()
2022-01-28T21:44:50.0189336Z   File "run_test.py", line 1079, in main
2022-01-28T21:44:50.0189615Z     raise RuntimeError(err_message)
2022-01-28T21:44:50.0189911Z RuntimeError: test_cpp_extensions_jit failed!
2022-01-28T21:44:50.3585033Z 

Error log 2:
======================================================================
ERROR [17.565s]: test_jit_cudnn_extension (__main__.TestCppExtensionJIT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\utils\cpp_extension.py", line 1726, in _run_ninja_build
    subprocess.run(
  File "C:\Jenkins\Miniconda3\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '8']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_cpp_extensions_jit.py", line 215, in test_jit_cudnn_extension
    module = torch.utils.cpp_extension.load(
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\utils\cpp_extension.py", line 1130, in load
    return _jit_compile(
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\utils\cpp_extension.py", line 1343, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\utils\cpp_extension.py", line 1455, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\utils\cpp_extension.py", line 1742, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'torch_test_cudnn_extension'

----------------------------------------------------------------------
Ran 27 tests in 285.031s

FAILED (errors=1, skipped=5, expected failures=3)

Generating XML reports...
Generated XML report: test-reports\dist-gloo\test_cpp_extensions_jit\TEST-TestCppExtensionJIT-20220128214004.xml
Traceback (most recent call last):
  File "run_test.py", line 1101, in <module>
    main()
  File "run_test.py", line 1079, in main
    raise RuntimeError(err_message)
RuntimeError: test_cpp_extensions_jit failed!

(base) C:\actions-runner\_work\pytorch-canary\pytorch-canary\test>popd

(base) C:\actions-runner\_work\pytorch-canary\pytorch-canary>if ERRORLEVEL 1 exit /b 1 

### Versions

cudnn v8.3.2.44 

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by atalman** [comment]
This looks like possible problem with cudnn installation:

"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64/link.exe" cudnn_extension.o /nologo /DLL cudnn.lib c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?_torch_cuda_cu_linker_symbol_op_cuda@native@at@@YA?AVTensor@2@AEBV32@@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\lib torch_python.lib /LIBPATH:C:\Jenkins\Miniconda3\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\lib/x64" cudart.lib /out:torch_test_cudnn_extension.pyd
LINK : fatal error LNK1181: cannot open input file 'cudnn.lib'

**Comment by atalman** [comment]
Fixed by adding cudnn.lib to a proper lib\x64 folder
