### ISSUE TITLE
TorchScript to ONNX conversion failing

### ISSUE THREAD

**Issue by rom1K** [pytorch/pytorch#72174]
### 🐛 Describe the bug

When trying to convert a Scripted module for a greedy decoding function to ONNX I get an error which I can't make sense of. The TorchScript module seems to work fine.

To reproduce, see [this minimal GIST](https://gist.github.com/rom1K/31913aeea79f3ff602c52bb78a4bfd7f). The encoder / decoder cache are there to mimic cached key / values in Transfomer models.

I get the following error:

```
/home/romain/.pyenv/versions/model-optimization/lib/python3.9/site-packages/torch/onnx/utils.py:100: UserWarning: `example_outputs' is deprecated and ignored. Will be removed in next PyTorch release.
  warnings.warn("`example_outputs' is deprecated and ignored. Will be removed in "
/home/romain/.pyenv/versions/model-optimization/lib/python3.9/site-packages/torch/onnx/utils.py:363: UserWarning: Skipping _decide_input_format
 -1
  warnings.warn("Skipping _decide_input_format\n {}".format(e.args[0]))
Traceback (most recent call last):
  File "/home/romain/Work/Repositories/model-optimization/greedy.py", line 131, in <module>
    torch.onnx.export(
  File "/home/romain/.pyenv/versions/model-optimization/lib/python3.9/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/romain/.pyenv/versions/model-optimization/lib/python3.9/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/romain/.pyenv/versions/model-optimization/lib/python3.9/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/romain/.pyenv/versions/model-optimization/lib/python3.9/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/romain/.pyenv/versions/model-optimization/lib/python3.9/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph = _propagate_and_assign_input_shapes(
RuntimeError: s_iter != stack.end()INTERNAL ASSERT FAILED at "../torch/csrc/jit/python/script_init.cpp":483, please report a bug to PyTorch. 
```

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.9 (main, Nov 22 2021, 14:45:23)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-27-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.4.120
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060
Nvidia driver version: 470.86
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.4
[pip3] torch==1.10.0+cu113
[conda] Could not collect

**Comment by rom1K** [comment]
Woops my bad I found the error. It seems the `args` I was specifying as a `dict` was an error. Using a `tuple` instead and removing the bitwise or made this work. I think [this issue](https://github.com/pytorch/pytorch/issues/61033) was probably the same thing.

Anyway cheers, closing this.
