### ISSUE TITLE
Seeing several addmm_sparse_csr_cuda float16/bf16 failures

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#72234]
### 🐛 Describe the bug

Seeing several addmm_sparse_csr_cuda float16/bf16 failures

Earliest failures seen 01/25/22

Failed tests:

- TestSparseCSRCUDA.test_addmm_all_sparse_csr_cuda_float16
- TestSparseCSRCUDA.test_addmm_all_sparse_csr_cuda_bfloat16
- TestSparseCSRCUDA.test_addmm_sizes_all_sparse_csr_cuda_float16
- TestSparseCSRCUDA.test_addmm_sizes_all_sparse_csr_cuda_bfloat16

Manually confirmed that float32 and float64 dtypes test passed.

Sample failure message:

```
$ python test/test_sparse_csr.py -v -k addmm_all_sparse_csr_cuda_float16
/home/xwang/Developer/pytorch/torch/testing/_deprecated.py:33: FutureWarning: torch.testing.get_all_complex_dtypes() is deprecated and will be removed in a future release. This call to get_all_complex_dtypes(...) can be replaced with [torch.complex64, torch.complex128].
  warnings.warn(msg, FutureWarning)
/home/xwang/Developer/pytorch/torch/testing/_deprecated.py:33: FutureWarning: torch.testing.get_all_fp_dtypes() is deprecated and will be removed in a future release. This call to get_all_fp_dtypes(...) can be replaced with [torch.float32, torch.float64].
  warnings.warn(msg, FutureWarning)
/home/xwang/Developer/pytorch/torch/testing/_deprecated.py:33: FutureWarning: torch.testing.get_all_fp_dtypes() is deprecated and will be removed in a future release. This call to get_all_fp_dtypes(...) can be replaced with [torch.float32, torch.float64, torch.float16].
  warnings.warn(msg, FutureWarning)
/home/xwang/Developer/pytorch/torch/testing/_deprecated.py:33: FutureWarning: torch.testing.floating_and_complex_types() is deprecated and will be removed in a future release. This call to floating_and_complex_types(...) can be replaced with (torch.float32, torch.float64, torch.complex64, torch.complex128).
  warnings.warn(msg, FutureWarning)
Test results will be stored in test-reports/python-unittest/test.test_sparse_csr

Running tests...
----------------------------------------------------------------------
 ** On entry to cusparseSpMM_bufferSize(): data type combination not supported, matA/matB: CUDA_R_16F, matC: CUDA_R_16F, compute: CUDA_R_16F

  test_addmm_all_sparse_csr_cuda_float16 (__main__.TestSparseCSRCUDA) ... ERROR (1.710s)

======================================================================
ERROR [1.710s]: test_addmm_all_sparse_csr_cuda_float16 (__main__.TestSparseCSRCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xwang/Developer/pytorch/torch/testing/_internal/common_utils.py", line 1753, in wrapper
    method(*args, **kwargs)
  File "/home/xwang/Developer/pytorch/torch/testing/_internal/common_utils.py", line 1753, in wrapper
    method(*args, **kwargs)
  File "/home/xwang/Developer/pytorch/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    raise rte
  File "/home/xwang/Developer/pytorch/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/xwang/Developer/pytorch/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/home/xwang/Developer/pytorch/torch/testing/_internal/common_device_type.py", line 788, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/home/xwang/Developer/pytorch/test/test_sparse_csr.py", line 877, in test_addmm_all_sparse_csr
    _test_addmm_addmv(self, torch.addmm, M, m1, m2, layout=torch.sparse_csr, all_sparse=True)
  File "/home/xwang/Developer/pytorch/test/test_sparse_csr.py", line 83, in _test_addmm_addmv
    f(t, convert_layout(m), v, alpha=alpha, beta=beta, out=res2)
RuntimeError: CUDA error: operation not supported when calling `cusparseSpMM_bufferSize( handle, opA, opB, &alpha_, descA.descriptor(), descB.descriptor(), &beta_, descC.descriptor(), compute_type, algorithm, &buffer_size )`
Exception raised from operator() at /home/xwang/Developer/pytorch/aten/src/ATen/native/sparse/cuda/SparseBlasImpl.cpp:592 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x68 (0x7faf31425308 in /home/xwang/Developer/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xef (0x7faf31402c1b in /home/xwang/Developer/pytorch/torch/lib/libc10.so)
frame #2: <unknown function> + 0x2dda8b5 (0x7faf342868b5 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cuda.so)
frame #3: at::native::addmm_out_sparse_csr_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar const&, c10::Scalar const&, c10::optional<c10::ScalarType>, at::Tensor&) + 0x2d8 (0x7faf342789f8 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x2d446f6 (0x7faf341f06f6 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cuda.so)
frame #5: at::_ops::addmm_out::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar const&, c10::Scalar const&, c10::optional<c10::ScalarType>, at::Tensor&) + 0xdb (0x7faf3f06b7eb in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x2ce70ab (0x7faf4083c0ab in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #7: at::_ops::addmm_out::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar const&, c10::Scalar const&, c10::optional<c10::ScalarType>, at::Tensor&) + 0xdb (0x7faf3f06b7eb in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x2841db8 (0x7faf40396db8 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #9: at::_ops::addmm_out::call(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar const&, c10::Scalar const&, c10::optional<c10::ScalarType>, at::Tensor&) + 0x1c7 (0x7faf3f0c53c7 in /home/xwang/Developer/pytorch/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x43dbbc (0x7faf47042bbc in /home/xwang/Developer/pytorch/torch/lib/libtorch_python.so)
<omitting python frames>


----------------------------------------------------------------------
Ran 1 test in 1.710s

FAILED (errors=1)
```

Seeing failures on various GPU models and different cuda/cusparse versions.

### Versions

cuda 11.5.119
pytorch built from source 774e0847c9534909d21b38887780a5630d3a8618

cc @nikitaved @pearu @cpuhrsch @ngimel @jianyuh @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @ptrblck

**Comment by ngimel** [comment]
Right, only CUDA_R_32F compute is supported for low precision inputs https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spmm. How did these tests ever pass?

**Comment by IvanYashchuk** [comment]
Current CUDA documentation (version 11.6) has the table for the "Uniform-precision computation" specifying only CUDA_R_32F, CUDA_R_64F, CUDA_C_32F, CUDA_C_64F. But if we look at older documentation for example 11.3 (https://docs.nvidia.com/cuda/archive/11.3.0/cusparse/index.html#cusparse-generic-function-spmm) then we'll see larger "Uniform-precision computation" table also including CUDA_R_16F, CUDA_R_16BF, CUDA_C_16F, CUDA_C_16BF.

**Comment by IvanYashchuk** [comment]
The code should probably be changed to use `get_opmath_t<scalar_t>::opmath_t` for the compute type.

**Comment by IvanYashchuk** [comment]
Compiled with CUDA 11.5.50 and the float16 tests pass on RTX 2060.

**Comment by IvanYashchuk** [comment]
Alright CUDA 11.5.0 documentation still has [a long list of supported uniform precision computation](https://docs.nvidia.com/cuda/archive/11.5.0/cusparse/index.html#cusparse-generic-function-spmm). While the 11.5.1 version [truncates the supported combinations](https://docs.nvidia.com/cuda/archive/11.5.1/cusparse/index.html#cusparse-generic-function-spmm).

**Comment by ngimel** [comment]
Thanks for checking @IvanYashchuk. Nice way to (not) maintain semantic versioning in cuSparse.

**Comment by xwang233** [comment]
Thanks for checking the cusparse doc, @IvanYashchuk . I also double checked it. In cuda 11.6, it says

```
NOTE: Uniform CUDA_R_16F, CUDA_R_16BF, CUDA_C_16F, and CUDA_C_16BF always imply mixed-precision computation.
```

I think we can always explicitly use FP16 inputs + FP32 compute_type to avoid confusions. I also created a PR to fix this issue.
