### ISSUE TITLE
torch.distributed.new_group() should consolidate the type of rank list

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#72346]
### 🐛 Describe the bug

If we create a new PG using `torch.distributed.new_group(torch.tensor([0, 1, 2, 3]), ...)`, we will end up with ranks in tensor, not int.

For example, if we print out `_pg_group_ranks[group]` in line 277, it's `{tensor(0): 0, tensor(1): 1, tensor(2): 2, tensor(3): 3}`.

```
# From torch/distributed/distributed_c10d.py

 265 def _get_group_rank(group: ProcessGroup, rank):
 266     """
 267     Helper that gets a given group's local rank in the group from a given global
 268     rank.
 269     """
 270     if group is GroupMember.WORLD:
 271         raise RuntimeError(
 272             "group.WORLD does not have local rank to global " "rank mapping"
 273         )
 274     if group not in _pg_group_ranks:
 275         raise RuntimeError("The given group does not exist")
 276     try:
 277         group_rank = _pg_group_ranks[group][rank]
 278     except KeyError:
 279         raise RuntimeError(
 280             f"The global rank {rank} is not part of the group {group}"
 281         ) from None
 282     return group_rank
```

If we later use `tensor(0)` as rank in `broadcast()`, or any other combination that doesn't have native int on both side, we will get a very confusing exception `RuntimeError: The global rank 0 is not part of the group`.

### Versions

Python 3.9.10 + torch 1.10.2 on macOS

**Comment by pritamdamania87** [comment]
@xkszltl Do you have a minimal repro for this? I'm running this code: https://gist.github.com/pritamdamania87/b1765933930d9a971627b50e5c9ffcee and I see ranks as integers as expected:

```
$ python /tmp/test.py
1
0
-1
-1
```

**Comment by xkszltl** [comment]
```
Python 3.9.10 (main, Jan 15 2022, 11:48:00) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.distributed.init_process_group("gloo", init_method="tcp://localhost:13102", world_size=1, rank=0)
>>> g = torch.distributed.new_group(torch.tensor([0]), backend="gloo")
>>> torch.distributed.broadcast(torch.tensor([1]), torch.tensor(0), g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1161, in broadcast
    group_src_rank = _get_group_rank(group, src)
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 279, in _get_group_rank
    raise RuntimeError(
RuntimeError: The global rank 0 is not part of the group <torch._C._distributed_c10d.ProcessGroupGloo object at 0x109bc01f0>
>>> torch.distributed.broadcast(torch.tensor([1]), 0, g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1161, in broadcast
    group_src_rank = _get_group_rank(group, src)
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 279, in _get_group_rank
    raise RuntimeError(
RuntimeError: The global rank 0 is not part of the group <torch._C._distributed_c10d.ProcessGroupGloo object at 0x109bc01f0>
>>> g = torch.distributed.new_group([torch.tensor(0)], backend="gloo")
>>> torch.distributed.broadcast(torch.tensor([1]), torch.tensor(0), g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1161, in broadcast
    group_src_rank = _get_group_rank(group, src)
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 279, in _get_group_rank
    raise RuntimeError(
RuntimeError: The global rank 0 is not part of the group <torch._C._distributed_c10d.ProcessGroupGloo object at 0x109bc0630>
>>> torch.distributed.broadcast(torch.tensor([1]), 0, g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1161, in broadcast
    group_src_rank = _get_group_rank(group, src)
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 279, in _get_group_rank
    raise RuntimeError(
RuntimeError: The global rank 0 is not part of the group <torch._C._distributed_c10d.ProcessGroupGloo object at 0x109bc0630>
>>> g = torch.distributed.new_group([0], backend="gloo")
>>> torch.distributed.broadcast(torch.tensor([1]), torch.tensor(0), g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1161, in broadcast
    group_src_rank = _get_group_rank(group, src)
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 279, in _get_group_rank
    raise RuntimeError(
RuntimeError: The global rank 0 is not part of the group <torch._C._distributed_c10d.ProcessGroupGloo object at 0x109bc03f0>
>>> torch.distributed.broadcast(torch.tensor([1]), 0, g)
>>> 
```

**Comment by ad8e** [comment]
I experienced this issue as well. My workaround is changing `new_group(ranks=device_mesh.mesh, backend="nccl")` to `new_group(ranks=device_mesh.mesh.tolist(), backend="nccl")`

**Comment by xkszltl** [comment]
Yes, there won't be any issue if it wasn't started with a tensor.
The complaint here is the existence of a malformed call path leading to an invalid error msg, and this call path exists because of over-permissive interface without internal casting.
