### ISSUE TITLE
[feature request] show name of damaged file in DataLoader

### ISSUE THREAD

**Issue by medakk** [pytorch/pytorch#7238]
I am using DataLoader to get some images from a dataset with a few bad images. It would be nice if the DataLoader mentioned the name of the damaged image in the exception thrown:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-cc88ea5f8bd3> in <module>()
      1 model_ft = train_model(model_ft, criterion, optimizer_ft, exp_lr_scheduler,
----> 2                        num_epochs=25)

<ipython-input-6-373a4f614762> in train_model(model, criterion, optimizer, scheduler, num_epochs)
     21 
     22             # Iterate over data.
---> 23             for inputs, labels in data_loaders[phase]:
     24                 inputs = inputs.to(device)
     25                 labels = labels.to(device)

~/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    284                 self.reorder_dict[idx] = batch
    285                 continue
--> 286             return self._process_next_batch(batch)
    287 
    288     next = __next__  # Python 2 compatibility

~/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    305         self._put_indices()
    306         if isinstance(batch, ExceptionWrapper):
--> 307             raise batch.exc_type(batch.exc_msg)
    308         return batch
    309 

OSError: Traceback (most recent call last):
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 101, in __getitem__
    sample = self.loader(path)
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 147, in default_loader
    return pil_loader(path)
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 130, in pil_loader
    return img.convert('RGB')
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/PIL/Image.py", line 879, in convert
    self.load()
  File "/home/karthik/.virtualenvs/pytorch-sandbox/lib/python3.6/site-packages/PIL/ImageFile.py", line 228, in load
    "(%d bytes not processed)" % len(b))
OSError: image file is truncated (5 bytes not processed)
```

**Comment by apaszke** [comment]
Can you please open the same issue but in a torchvision package? This can't be done in DataLoader because it's not specific to images nor even to loading files from disk, but `FolderDataset` could raise a nicer error message. Thanks!
