### ISSUE TITLE
Newest librosa update causing test breakages in CI

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#72432]
## Current Status
mitigated

## Error looks like
```
ERROR [0.004s]: test_stft_cpu_float64 (__main__.TestFFTCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 796, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 951, in only_fn
    return fn(self, *args, **kwargs)
  File "test_spectral_ops.py", line 913, in test_stft
    _test((10,), 7, center=center)
  File "test_spectral_ops.py", line 903, in _test
    ref_result = librosa_stft(x, n_fft, hop_length, win_length, window, center)
  File "test_spectral_ops.py", line 884, in librosa_stft
    ri = librosa.stft(xi.cpu().numpy(), n_fft, hop_length, win_length, window, center=center)
TypeError: stft() takes 1 positional argument but 5 positional arguments (and 1 keyword-only argument) were given
```

## Incident timeline (all times pacific)
- 2/7 7:50a incident began
- 2/7 7:50a detected by contributor @ShijunK 
- 2/7 8:11a root caused as latest librosa upgrade
- 2/7 ?? mitigated by https://github.com/pytorch/pytorch/pull/72433
- 2/7 ?? closed by…

## User impact
*How does this affect users of PyTorch CI?*
Several test jobs are failing

## Root cause
*What was the root cause of this issue?*
Latest librosa update 

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment]
Closing
