### ISSUE TITLE
Memory parity with JAX attention

### ISSUE THREAD

**Issue by gahdritz** [pytorch/pytorch#72450]
Our attention module is essentially standard multi-head attention, just with arbitrarily many bias tensors. It’s approximately as follows:

```
a = torch.matmul(q, k)

for b in biases:
    a += b

a = softmax(a, dim=-1)

o = torch.matmul(a, v.transpose(-1, -2))
```

where `q`, `k`, and `v` are `[batch_dim, heads, Q/K/V, C]` query, key, and value tensors, respectively, and `biases` is a list of up to 2 bias tensors (e.g. a mask), all of which broadcast along at least one dimension such that their sizes are insignificant (they’re much smaller than the full `[batch_dim, heads, Q, K]` attention logit matrix `a`, in any case). During the backwards pass, since `batch_dim`, `Q` and `K` are >> `C`, memory consumption is dominated by the first matrix multiplication and the softmax, which together contribute (`2 * batch_dim * heads * Q * K * (2 bytes)`) to the module total. Equivalent JAX code requires just (`batch_dim * heads * Q * K * (2 bytes)`), half as much.

torch doesn’t have anything like an in-place softmax, and for various reasons I’ve been unable to shrink the memory requirements using keops (apparently incompatible with the bias tensors) or by manually building an in-place softmax myself (breaks auto-differentiation).

Is there a (`batch_dim * heads * Q * K * (2 bytes)`) solution in torch?

**Comment by gchanan** [comment]
@Chillee might have a solution.

**Comment by Chillee** [comment]
@gahdritz When you're talking about memory consumption, are you talking about "peak" memory consumption, or about the activations saved?

If it's about the activations saved, I don't think an in-place softmax would help you - you still need to save the same activations for backwards.

The one possibility I can think of here is that you could recompute the softmax in the backwards pass - that's something AOTAutograd could help you with if needed.

**Comment by Chillee** [comment]
Natalia pointed out that softmax only saves its output for backwards, so recomputation wouldn't actually help you here.

One possibility is that we recently landed a PR that optimized softmax to only save the input, which might be the cause of the excess memory here :) 

https://github.com/pytorch/pytorch/issues/72450

**Comment by ngimel** [comment]
The PR in question is #66018. Prior to it, both softmax input and output were saved for backward, afterwards only output is. This PR is not present in 1.10, so you might see bigger memory consumption on 1.10, but nightlies should have the PR and thus use less memory.

**Comment by gahdritz** [comment]
Thanks! I'll give the nightly build a try and report back if it worked.

**Comment by gahdritz** [comment]
Sorry for the late response.

I can confirm that, using the nightly build, softmax no longer saves a copy of its inputs, and the value reported by `torch.cuda.memory_allocated()` at the end of the forward pass is now commensurately smaller.

However, large amounts of memory are still consumed during the backward pass. Consider the following simplified code snippet:

```
import torch

q = torch.rand(3072, 8, 384, 8, requires_grad=True).cuda()
k = torch.rand(3072, 8, 8, 384, requires_grad=True).cuda()

a = torch.einsum('bhqc,bhck->bhqk', q, k)

print(f"after_einsum: {torch.cuda.memory_allocated()}")

a = torch.nn.functional.softmax(a, dim=-1)

print(f"after_softmax: {torch.cuda.memory_allocated()}")

loss = torch.mean(a)
loss.backward()
```

It's a little tricky to choose values because torch unpredictably reserves a fraction of the memory on the GPU, but the sizes of my "queries" and "keys" here are chosen such that `a` is less than one half of the total GPU memory available on my 40GB A100. Here are my results when I run this snippet using the nightly torch build:

```
after_einsum: 15099494400
after_softmax: 15099494400
Traceback (most recent call last):
  File "torch_experiment.py", line 15, in <module>
    loss.backward()
  File "/mnt/home/dberenberg/gustaf_stuff/openfold_experimental/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/mnt/home/dberenberg/gustaf_stuff/openfold_experimental/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 13.50 GiB (GPU 0; 39.59 GiB total capacity; 27.56 GiB already allocated; 9.98 GiB free; 27.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

`torch.autograd.detect_anomaly` reveals that the crash occurs during the softmax.

Equivalent JAX code works fine:

```
import jax
import numpy as np

def test(query, key):
    a = jax.numpy.einsum('bhqc,bhck->bhqk', query, key)
    a = jax.nn.softmax(a)
    return jax.numpy.mean(a)

q = np.random.rand(3072, 8, 384, 8).astype(np.float32)
k = np.random.rand(3072, 8, 8, 384).astype(np.float32)
q = jax.device_put(q)
k = jax.device_put(k)

derivative_fn = jax.jit(jax.grad(test))
grad = derivative_fn(q, k)
```

It's difficult to know whether this is just a result of JAX utilizing more than 27GB of the GPU's memory, but, anecdotally, JAX can get away with this operation even when `a` is larger than half of the total memory available (during the training of AlphaFold, for example, `a` is supposedly 12GB on 16GB TPUs).

**Comment by gahdritz** [comment]
I just wanted to bump this up---are any of you able to reproduce the discrepancy in my previous post?

**Comment by ngimel** [comment]
For the snippet above, apparently jax is able to get away without fully materializing gradOutput for the softmax_backward operation (it's probably just an expanded single-element tensor), whereas pytorch needs to fully materialize it, leading to 2 full-size tensors being present, and this causes OOM. 
In real workloads though I wouldn't expect gradients flowing into softmax_backward to be expanded small tensors.

**Comment by gahdritz** [comment]
What do you mean by the gradients being expanded small tensors?

**Comment by ngimel** [comment]
Like single element tensor implicitly broadcasted to the full size of softmax output

**Comment by gahdritz** [comment]
And you're saying that the memory would be comparable if there were more operations after the softmax?

**Comment by ngimel** [comment]
Yes, I think so (although I didn't test) - at the expense of jax probably using more memory.

**Comment by gahdritz** [comment]
Is there anything else that might account for the AlphaFold 2 anecdotal evidence I mentioned above (fitting a 12GB softmax onto a 16GB TPUv3 core)?

**Comment by Chillee** [comment]
@ngimel 

I think the in-place operations are also what matters.

First of all, re: @gahdritz, I think this is a pretty tricky situation to solve, particularly in an eager-mode framework :P Since you can't even maintain 2x the `softmax` tensor in memory, lots of things that would normally be fairly easy become quite tricky.

This is true in many situations - for example, the class of in-place sorts is much more restricted than all sorts (https://en.wikipedia.org/wiki/In-place_algorithm).

That being said, lemme explain what needs to be done here, from my understanding.

AOTAutograd tells me the backwards graph looks something like

```
def forward(self, transpose, _softmax, transpose_1, tangents_1):
    expand = torch.ops.aten.expand(tangents_1, [768, 8, 384, 384]);  tangents_1 = None
    div = torch.ops.aten.div(expand, 905969664);  expand = None
    _softmax_backward_data = torch.ops.aten._softmax_backward_data(div, _softmax, -1, 6);  div = _softmax = None
    view_4 = torch.ops.aten.view(_softmax_backward_data, [768, 8, 384, 384, 1]);  _softmax_backward_data = None
    permute_5 = torch.ops.aten.permute(view_4, [0, 1, 2, 4, 3]);  view_4 = None
    view_5 = torch.ops.aten.view(permute_5, [6144, 384, 384]);  permute_5 = None
    bmm_1 = torch.ops.aten.bmm(transpose, view_5);  transpose = None
    bmm_2 = torch.ops.aten.bmm(view_5, transpose_1);  view_5 = transpose_1 = None
    view_6 = torch.ops.aten.view(bmm_1, [768, 8, 8, 384, 1]);  bmm_1 = None
    permute_6 = torch.ops.aten.permute(view_6, [0, 1, 4, 3, 2]);  view_6 = None
    view_7 = torch.ops.aten.view(bmm_2, [768, 8, 384, 8, 1]);  bmm_2 = None
    permute_7 = torch.ops.aten.permute(view_7, [0, 1, 2, 4, 3]);  view_7 = None
    permute_8 = torch.ops.aten.permute(permute_6, [0, 1, 4, 3, 2]);  permute_6 = None
    squeeze = torch.ops.aten.squeeze(permute_8, -1);  permute_8 = None
    permute_9 = torch.ops.aten.permute(permute_7, [0, 1, 2, 4, 3]);  permute_7 = None
    squeeze_1 = torch.ops.aten.squeeze(permute_9, -1);  permute_9 = None
    return [squeeze_1, squeeze]
```
So, `_softmax` is the largest input tensor here, and that represents the saved activation.

So, as @ngimel  mentioned, one of the issues is simply that we expand before we call `div`, and this'll cause an extraneous allocation.

That is, at `div = torch.ops.aten.div`, we will have both `_softmax` and `div` in existence at the same time, which will use excess memory.

So, if you replace the `mean` with a `sum` that'll get rid of the divide. Alternately, ideally, we could swap the order of the 2 operations around.
```
    div = torch.ops.aten.div(expand, 905969664);  expand = None
    expand = torch.ops.aten.expand(tangents_1, [768, 8, 384, 384]);  tangents_1 = None
```
Also, as @ngimel mentioned, this extraneous allocation probably doesn't show up in the middle of a model.

However, the real problem here is `aten._softmax_backward_data`. This function uses a peak memory ~= 3x softmax memory. One for `div`, one for `_softmax`, and one for the output allocated tensor. It seems that even if `div` is a non-contiguous tensor, `_softmax_backward_data` ends up making it contiguous.

So, ideally, what we would do here is to call the out variant of `aten._softmax_backward_data`, and 2. avoid forcing the `div` input to be contiguous for `_softmax_backward_data`.

These are difficult to do in eager-mode, but in principle, it might be plausible to do with AOTAutograd. We have some other minor nits that would prevent you from doing it today, but we are interested in doing things like optimizing memory planning/usage.

**Comment by gahdritz** [comment]
Thanks @Chillee! This is super helpful.

One little addendum to the original issue: I had initially written that torch's softmax requires 2x the memory of its input. I ran some even simpler experiments, and that appears to be an underestimate. Even if I use the nightly build,
the real multiple seems to be 5x:

```python3
import torch

x = torch.rand([5120, 2, 384, 384], dtype=torch.bfloat16, device="cuda:0", requires_grad=True)
print(f"After allocation: {torch.cuda.memory_allocated()}")
x = torch.nn.functional.softmax(x, dim=-1)
loss = torch.mean(x)
print(f"After forward pass: {torch.cuda.memory_allocated()}")
loss.backward()
print(f"After backward: {torch.cuda.memory_allocated()}")
print(f"Max memory allocated: {torch.cuda.max_memory_allocated()}")
```

This yields the following:

```
After allocation: 3019898880
After forward pass: 6039798272
After backward: 9059697152
Max memory allocated: 15099495424
```

I thought at first this had something to do with the bfloat16 tensors being silently promoted to FP32 tensors somewhere in the softmax implementation, but the same thing happens when `x` is FP32 to begin with (in that case, the peak memory consumption is 30GB, also 5x the original 6GB).

**Comment by ngimel** [comment]
@gahdritz in your example, you have a large leaf variable that pytorch has to hold on to, and it artificially inflates memory values that you are getting. I slightly modified your script, to make the leaf variable small:
```
In [7]: import torch
   ...: 
   ...: y = torch.rand([20, 2, 1, 1], dtype=torch.bfloat16, device="cuda:0", requires_grad=True)
   ...: x = y.expand(20,2,384,384)
   ...: print(f"After allocation: {torch.cuda.memory_allocated()}")
   ...: x = torch.nn.functional.softmax(x, dim=-1)
   ...: loss = torch.mean(x)
   ...: print(f"After forward pass: {torch.cuda.memory_allocated()}")
   ...: loss.backward()
   ...: print(f"After backward: {torch.cuda.memory_allocated()}")
   ...: print(f"Max memory allocated: {torch.cuda.max_memory_allocated()}")
   ...: 
After allocation: 2048
After forward pass: 12583936
After backward: 12584448
Max memory allocated: 62915584
```
Note that in this case memory after forward = size of the allocated tensor (softmax does not hold on to extra memory), memory after backward is also = size of the allocated tensor (no extra allocation for `.grad`), but peak memory still does not budge, because of 3x the large tensor size needed in softmax backward due to what @Chillee described, and probably caching allocator fragmentation.

**Comment by gahdritz** [comment]
Unfortunately, the leaf tensors in my use case are very large (actually 4x larger than this one).

**Comment by Chillee** [comment]
> I think fragmentation might be playing a role,

I don't think so. Tbh, I think folks think that fragmentation is a bigger problem than it really is :P In particular, in this case, there aren't even that many memory allocations at all, so I don't expect fragmentation to be a significant problem.

The 5x peak memory occurs during `aten::_softmax_backward_data`. 1x comes from the original leaf tensor, 1x comes from div (one of the inputs to softmax backward) , 1x comes from the output of softmax being saved (one of the inputs to softmax backward), 1x more comes from memory being allocated for the output of `aten::_softmax_backward_data`, and 1x more just seems to come from internal memory being allocated for `aten::_softmax_backward_data`.

It seems like it comes from this line

https://github.com/pytorch/pytorch/blob/master/aten%2Fsrc%2FATen%2Fnative%2Fcuda%2FSoftMax.cu#L941

Tbh, I suspect all of these are resolveable with some relatively simple memory planning - I might take a crack at a pass soon.

**Comment by ngimel** [comment]
@chillee in my example there's no original leaf tensor (leaf tensor is negligibly small), good catch with `tmp`, I've forgotten about it. We should probably get rid of it.
