### ISSUE TITLE
Error during training: falseINTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by rvandeghen** [pytorch/pytorch#72782]
### 🐛 Describe the bug

I have the following error after some iterations:

```
Traceback (most recent call last):
  File "/home/rvandeghen/anaconda3/envs/SNv3-detection/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/rvandeghen/anaconda3/envs/SNv3-detection/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/rvandeghen/anaconda3/envs/SNv3-detection/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: falseINTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1639180487213/work/aten/src/ATen/MapAllocator.cpp":323, please report a bug to PyTorch. unable to mmap 24 bytes from file </torch_2921092_75376>: Cannot allocate memory (12)
```
using `torchrun --nproc_per_node=4 train.py`
where `train.py` is a variant of [https://github.com/pytorch/vision/blob/9ae0169dd0ce815eebf1aff2963e8e1eb580eb3e/references/detection/train.py](url).
Note that it only happens with a (large) dataset and always after the same number of iterations.

### Versions

Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 8.2.2004 (Core) (x86_64)
GCC version: (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.18.0-193.6.3.el8_2.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 450.57
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.1
[pip3] torchvision==0.11.2
[conda] blas 1.0 mkl
[conda] cudatoolkit 11.3.1 h2bc3f7f_2
[conda] ffmpeg 4.3 hf484d3e_0 pytorch
[conda] mkl 2021.4.0 h06a4308_640
[conda] mkl-service 2.4.0 py39h7f8727e_0
[conda] mkl_fft 1.3.1 py39hd3c417c_0
[conda] mkl_random 1.2.2 py39h51133e4_0
[conda] numpy 1.21.2 py39h20f2e39_0
[conda] numpy-base 1.21.2 py39h79a1101_0
[conda] pytorch 1.10.1 py3.9_cuda11.3_cudnn8.2.0_0 pytorch
[conda] pytorch-mutex 1.0 cuda pytorch
[conda] torchvision 0.11.2 py39_cu113 pytorch

**Comment by VitalyFedyunin** [comment]
Likely duplicate of #68501

**Comment by VitalyFedyunin** [comment]
Could you please try with nightly versions of PyTorch

**Comment by soulitzer** [comment]
@rvandeghen Could you provide a piece of code that we can run to reproduce this? You mention that you used a variant of the code that you linked.

**Comment by albanD** [comment]
Also note that shared memory is usually pretty limited by default. So you might want to look into increasing the amount of allowed shared memory.

**Comment by rvandeghen** [comment]
@soulitzer The variant is mostly in the `Dataset` class because I don't use COCO, so my training loop is the same as in [https://github.com/pytorch/vision/blob/0db67d857d612b8b5f196d1b9e1314d07b8a7a29/references/detection/engine.py#L12](url). Also note that my code is working when the dataset has 25k images but gives the error when the dataset has 500k images.
@albanD I tried the same training on 2 different clusters and the same error happens. For the second cluster, my docker uses `--ipc=host` so I don't think it is related to shared memory.
@VitalyFedyunin I will try with the nightly and get back to you.

**Comment by rvandeghen** [comment]
@VitalyFedyunin Got the same error with nightly versions. Here is a list of my packages:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
blas                      1.0                         mkl  
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.15.0           py39hd667e15_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cryptography              36.0.0           py39h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.23          py39he80948d_1    conda-forge
ffmpeg                    4.2.2                h20bf706_0  
freetype                  2.11.0               h70c0345_0  
giflib                    5.2.1                h7b6447c_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
idna                      3.3                pyhd3eb1b0_0  
intel-openmp              2021.4.0          h06a4308_3561  
jpeg                      9d                   h7f8727e_0  
kiwisolver                1.3.1            py39h2531618_0  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libidn2                   2.3.2                h7f8727e_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libvpx                    1.7.0                h439df22_0  
libwebp                   1.2.0                h89dd481_0  
libwebp-base              1.2.0                h27cfd23_0  
lz4-c                     1.9.3                h295c915_1  
matplotlib-base           3.3.4            py39h2fa2bec_0    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
ncurses                   6.3                  h7f8727e_2  
nettle                    3.7.3                hbbd107a_1  
numpy                     1.21.2           py39h20f2e39_0  
numpy-base                1.21.2           py39h79a1101_0  
olefile                   0.46               pyhd3eb1b0_0  
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1l               h7f98852_0    conda-forge
pillow                    8.4.0            py39h5aabda8_0  
pip                       21.2.4           py39h06a4308_0  
pycocotools               2.0.4            py39hce5d2b2_0    conda-forge
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.12.0.dev20220214 py3.9_cuda11.3_cudnn8.2.0_0    pytorch-nightly
pytorch-mutex             1.0                        cuda    pytorch-nightly
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd3eb1b0_0  
setuptools                58.0.4           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.37.2               hc218d9a_0  
tabulate                  0.8.9                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
torchvision               0.13.0.dev20220214      py39_cu113    pytorch-nightly
tornado                   6.1              py39h3811e60_2    conda-forge
typing_extensions         3.10.0.2           pyh06a4308_0  
tzdata                    2021e                hda174b7_0  
urllib3                   1.26.8             pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7f8727e_4  
zstd                      1.4.9                haebb681_0  
```

**Comment by rvandeghen** [comment]
@soulitzer @VitalyFedyunin @albanD small update: I tried to run my code (with the 1.10 version) with 20 workers and I don't have anymore problems.
However, with the different tests I've made, I have seen that the problem happens at the iteration ~1330*`num_workers`. I don't know how it can be related but my logs confirm this behavior.

**Comment by maxwellzh** [comment]
Any update on this issue? I got the same error while DataLoader `num_worker>=1`, but it works with `num_worker=0`

**Comment by rvandeghen** [comment]
Hi,

here is a small script to reproduce the error:

```
import torch
import torch.utils.data
import os
import torch.distributed as dist

class MyDataset(torch.utils.data.Dataset):
    
    def __init__(self, size=1000000):

        self.targets = list()
        self.size = size

        for i in range(size):
            boxes = list()
            labels = list()
            areas = list()
            iscrowds = list()
            for _ in range(torch.randint(1, 20, (1,)).item()):
                labels.append(torch.randint(1, 10, (1,)).item())
                bbox = torch.randint(400, (4,))
                bbox[2:] += bbox[:2]
                boxes.append(list(bbox))
                a = (bbox[2] - bbox[0])*(bbox[3] - bbox[1])
                areas.append(a)
                iscrowds.append(0)
            image_id = int(i)
            self.targets.append({'boxes': torch.tensor(boxes),
                                 'labels': torch.tensor(labels),
                                 'image_id': torch.tensor(image_id),
                                 'area': torch.tensor(areas),
                                 'iscrowd': torch.tensor(iscrowds)})

    def __len__(self,):
        return self.size
    
    def __getitem__(self, idx):
        
        image = torch.randint(255, (3, 1000, 1000))

        targets = self.targets[idx]

        return image, targets

def setup_for_distributed(is_master):
    """
    This function disables printing when not in master process
    """
    import builtins as __builtin__

    builtin_print = __builtin__.print

    def print(*args, **kwargs):
        force = kwargs.pop("force", False)
        if is_master or force:
            builtin_print(*args, **kwargs)

    __builtin__.print = print


def is_dist_avail_and_initialized():
    if not dist.is_available():
        return False
    if not dist.is_initialized():
        return False
    return True


def get_world_size():
    if not is_dist_avail_and_initialized():
        return 1
    return dist.get_world_size()


def get_rank():
    if not is_dist_avail_and_initialized():
        return 0
    return dist.get_rank()


def is_main_process():
    return get_rank() == 0

def init_distributed_mode():
    if "RANK" in os.environ and "WORLD_SIZE" in os.environ:
        rank = int(os.environ["RANK"])
        world_size = int(os.environ["WORLD_SIZE"])
        gpu = int(os.environ["LOCAL_RANK"])
    elif "SLURM_PROCID" in os.environ:
        rank = int(os.environ["SLURM_PROCID"])
        gpu = rank % torch.cuda.device_count()
    else:
        print("Not using distributed mode")
        distributed = False
        return

    distributed = True

    torch.cuda.set_device(gpu)
    dist_backend = "nccl"
    dist_url='env://'
    print(f"| distributed init (rank {rank}): {dist_url}", flush=True)
    torch.distributed.init_process_group(
        backend=dist_backend, init_method=dist_url, world_size=world_size, rank=rank
    )
    torch.distributed.barrier()
    setup_for_distributed(rank == 0)

def collate_fn(batch):
    return tuple(zip(*batch))

def reduce_dict(input_dict, average=True):
    """
    Args:
        input_dict (dict): all the values will be reduced
        average (bool): whether to do average or sum
    Reduce the values in the dictionary from all processes so that all processes
    have the averaged results. Returns a dict with the same fields as
    input_dict, after reduction.
    """
    world_size = get_world_size()
    if world_size < 2:
        return input_dict
    with torch.inference_mode():
        names = []
        values = []
        # sort the keys so that they are consistent across processes
        for k in sorted(input_dict.keys()):
            names.append(k)
            values.append(input_dict[k])
        values = torch.stack(values, dim=0)
        dist.all_reduce(values)
        if average:
            values /= world_size
        reduced_dict = {k: v for k, v in zip(names, values)}
    return reduced_dict

def main():
    init_distributed_mode()
    print('Starting')

    dataset = MyDataset(size=1000000)
    train_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
    train_batch_sampler = torch.utils.data.BatchSampler(train_sampler, 8, drop_last=True)
    data_loader = torch.utils.data.DataLoader(
        dataset, batch_sampler=train_batch_sampler, num_workers=2, collate_fn=collate_fn
    )

    print('Loading finished')

    for e in range(10):
        print('Epoch: {}'.format(e))
        train_sampler.set_epoch(e)

        for i, (images, targets) in enumerate(data_loader):
            images = list(image.to('cuda') for image in images)
            targets = [{k: v.to('cuda') for k, v in t.items()} for t in targets]

            loss_dict = {'loss': torch.rand((1,), device='cuda')}
            loss_dict_reduced = reduce_dict(loss_dict)

            if i%10 == 0:
                print(i)

if __name__ == '__main__':

    main()
```

and here is the output I have:

```
Start training
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
| distributed init (rank 0): env://| distributed init (rank 1): env://

Starting
Loading finished
Epoch: 0
0
10
20
30
40
50
60
70
80
90
100
110
...
3150
3160
3170
3180
3190
3200
3210
3220
3230
Traceback (most recent call last):
  File "/home/rvandeghen/anaconda3/envs/cuda10.2_pytorch/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/rvandeghen/anaconda3/envs/cuda10.2_pytorch/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/rvandeghen/anaconda3/envs/cuda10.2_pytorch/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: falseINTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1640811756765/work/aten/src/ATen/MapAllocator.cpp":323, please report a bug to PyTorch. unable to mmap 144 bytes from file </torch_1103001_77786>: Cannot allocate memory (12)
Traceback (most recent call last):
  File "/home/rvandeghen/anaconda3/envs/cuda10.2_pytorch/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/rvandeghen/anaconda3/envs/cuda10.2_pytorch/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/rvandeghen/anaconda3/envs/cuda10.2_pytorch/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: falseINTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1640811756765/work/aten/src/ATen/MapAllocator.cpp":323, please report a bug to PyTorch. unable to mmap 288 bytes from file </torch_1103033_77783>: Cannot allocate memory (12)
```

pytorch version: 1.10.2

**Comment by VitalyFedyunin** [comment]
Can you please check avaible shared memory and try to increase limit: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/tuning_and_optimizing_red_hat_enterprise_linux_for_oracle_9i_and_10g_databases/chap-oracle_9i_and_10g_tuning_guide-setting_shared_memory

Also you can check shared memory usage with `df -h` (look for `shm` device)

**Comment by rvandeghen** [comment]
@VitalyFedyunin I ran the code above where I print the shared memory at every iteration and it remains constant and way below the limit.

**Comment by rvandeghen** [comment]
@VitalyFedyunin any news ?
