### ISSUE TITLE
`BatchNorm{1,2,3}d` works when `num_features != C`!

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#72821]
### 🐛 Describe the bug

`BatchNorm{1,2,3}d` works when `num_features != C` when C is 0. Based on its documentation, num_features is C from an expected input of size (N, C, H, W), so it should not work.

```python
import torch

a = torch.rand([1, 0, 2, 2])
batchnorm = torch.nn.BatchNorm2d(5)
batchnorm(a)
# work
```

By contrast, `LazyBatchNorm` will fail when C is 0.
```python
import torch

a = torch.rand([1, 0, 2, 2])
lazybatchnorm = torch.nn.LazyBatchNorm2d()
lazybatchnorm(a)
# IndexError: select(): index 0 out of range for tensor of size [0] at dimension 0
```

### Versions

pytorch: 1.10.1

**Comment by ignasa007** [comment]
I think the title is slightly misleading - Batch/Instance Norm work when `num_features != C` only if `C = 0`, eg. not when `C = 1`:
```bash
>>> a = torch.rand([1, 1, 2, 2])
>>> batchnorm(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".../miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File ".../miniconda3/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 175, in forward
    return F.batch_norm(
  File ".../miniconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 2509, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 1 elements not 5
```

Also, the error is not unique to LazyBatchNorm, but BatchNorm initialization with `C = 0` in general:
```bash
>>> batchnorm = torch.nn.BatchNorm2d(0)
>>> a = torch.rand([1, 0, 2, 2])
>>> batchnorm(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".../miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File ".../miniconda3/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 175, in forward
    return F.batch_norm(
  File ".../miniconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 2509, in batch_norm
    return torch.batch_norm(
IndexError: select(): index 0 out of range for tensor of size [0] at dimension 0
```

**Comment by StEvUgnIn** [comment]
Any idea?
