### ISSUE TITLE
Toggling deterministic mode for individual autograd backward functions

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#72831]
### 🚀 The feature, motivation and pitch

At the moment, we can easily turn off deterministic mode for one or more operations in forward mode by just doing this:

```python
torch.use_deterministic_algorithms(False)
operation()
torch.use_deterministic_algorithms(True)
```

However, when we call the backward function, the entire thing is either deterministic or not. For instance:

```python
import torch

torch.use_deterministic_algorithms(True)

a = torch.randn(10, 10, requires_grad=True, device='cuda')
index = torch.tensor([[0]], device='cuda')

torch.use_deterministic_algorithms(False)
r = a.gather(0, index)
torch.use_deterministic_algorithms(True)

r.backward()
```

When this is run in Pytorch 1.11, this is the output:

```
Traceback (most recent call last):
  File "/home/kurtamohler/tmp/tmp.py", line 12, in <module>
    r.backward()
  File "/work2/kurtamohler/development/pytorch-storage-followup/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/work2/kurtamohler/development/pytorch-storage-followup/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
```

The backward function for `torch.gather` is nondeterministic, so it throws an error. It might be useful if we could toggle determinism for individual backward functions. There might be a couple different ways to offer this feature.

One way could be for each backward function to just use the same deterministic mode that was used during the corresponding forward function call. Maybe a way to implement this would be to add a bool to each autograd node, indicating whether it's deterministic or not.

### Additional context

This idea was first discussed here: https://github.com/pytorch/pytorch/issues/50469#issuecomment-1031828294

**Comment by albanD** [comment]
I am not sure the same determinism as the forward is wanted here? forward/backward function tend to have unrelated behavior in that domain (where a scattering becomes reductions).

You should be able to easily do that by adding hooks around the function you want?

**Comment by ezyang** [comment]
If we are serious about this mode of use, we should add a context manager, and have some way of making the mode sticky in autograd in the same way that streams are sticky (autograd engine is responsible for restoring the determinism mode recorded in forwards). There is no need to introduce a boolean flag to backwards formulas, and frankly it is counter to our goals with mintorch

**Comment by ajtulloch** [comment]
More of a meta-question - what are the use-cases where people are toggling determinism on/off at function level granularities? 

Most of the use-cases I know of where people toggle determinism on, they care about end-to-end numerical reproducibility of a training process - for example, during program initialization they consistently set seeds, ensure the data loader is strictly deterministic, enable deterministic algorithms, and so on, with the idea that they can guarantee that the training process is strictly deterministic which helps debugging, regression testing, and so on.  In all these cases, determinism is more of a program-level flag that gets set in program initialization and never toggled on/off, so this feature isn't really needed.

**Comment by kurtamohler** [comment]
> what are the use-cases where people are toggling determinism on/off at function level granularities?

That's a good question, and I don't know the answer to it. Your points make sense to me, and we shouldn't add this feature if there are no real use cases. I think I remember discussing toggling determinism in another issue somewhere a while back, but I don't remember what use cases there were. I'll look for it

**Comment by kurtamohler** [comment]
@ajtulloch, here's the discussion I mentioned about why someone might want to toggle determinism for individual operations: https://github.com/pytorch/pytorch/issues/64883#issuecomment-924602901

Though I still don't know if the number of users that would benefit from this feature is large enough to justify the effort to add it

**Comment by mruberry** [comment]
To summarize: 

- if we did this I think we'd do it as @ezyang suggests, updating the autograd engine to require determinism for each op that require it in forward. This is probably a moderate amount of effort and slightly complicates an already complicated system.
- given @ajtulloch's point it'd be interesting to see more users request this functionality specifically to justify that complication

**Comment by andrei-rusu** [comment]
Just my 2 cents: ``gather`` is very often used in RL to select actions. In the backward pass of this operation, ``scatter_add_cuda_kernel`` is called. This means that currently one can never achieve full determinism in most RL codebases out there.

**Comment by JingyuQian** [comment]
I ran into a similar problem. Since I couldn't find proper solutions I'll put it here. Hope someone can help me figure it out.

`RuntimeError: upsample_linear1d_backward_out_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.`

**Comment by kurtamohler** [comment]
@JingyuQian, could you please open a new issue for that like the error message says? It helps to have separate issues for each of the operators that people want to be deterministic.

**Comment by JingyuQian** [comment]
@kurtamohler Thank you. For my case it turned out it wasn't a problem with determinism after inspection. Just FYI.

**Comment by kurtamohler** [comment]
@tristanengst, I assume that you're suggesting that `torch.use_deterministic_algorithms` could change the `CUBLAS_WORKSPACE_CONFIG` variable automatically. Unfortunately, CUDA only checks the `CUBLAS_WORKSPACE_CONFIG` variable once, when the runtime is first loaded. So the variable has to be set before importing PyTorch. If the variable is changed later, CUDA doesn't check it.

Also, the `CUBLAS_WORKSPACE_CONFIG` variable isn't really related to this issue. If I misunderstood your suggestion and you would like to discuss it further, please open a new issue and tag me on it
