### ISSUE TITLE
DISABLED test_data_parallel_module_cuda_float64 (__main__.TestDataParallelDeviceTypeCUDA)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#72868]
### 🐛 Describe the bug

platforms: rocm

https://our.intern.facebook.com/intern/opensource/ci/job/log/367335521549970/

See also https://github.com/pytorch/pytorch/issues/71770

```
2022-02-15T18:03:58.0131662Z ======================================================================
2022-02-15T18:03:58.0132929Z FAIL [0.037s]: test_data_parallel_module_cuda_float64 (__main__.TestDataParallelDeviceTypeCUDA)
2022-02-15T18:03:58.0137117Z ----------------------------------------------------------------------
2022-02-15T18:03:58.0138538Z Traceback (most recent call last):
2022-02-15T18:03:58.0140336Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper
2022-02-15T18:03:58.0141592Z     method(*args, **kwargs)
2022-02-15T18:03:58.0143265Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
2022-02-15T18:03:58.0144381Z     result = test(self, **param_kwargs)
2022-02-15T18:03:58.0145994Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 915, in only_fn
2022-02-15T18:03:58.0146942Z     return fn(slf, *args, **kwargs)
2022-02-15T18:03:58.0148278Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 796, in dep_fn
2022-02-15T18:03:58.0149870Z     return fn(slf, *args, **kwargs)
2022-02-15T18:03:58.0150723Z   File "distributed/test_data_parallel.py", line 795, in test_data_parallel_module
2022-02-15T18:03:58.0151815Z     self.assertEqual(out, expected_out, atol=dtype2prec_DONTUSE[dtype], rtol=0)
2022-02-15T18:03:58.0153329Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 2154, in assertEqual
2022-02-15T18:03:58.0154236Z     msg=msg,
2022-02-15T18:03:58.0155484Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1081, in assert_equal
2022-02-15T18:03:58.0156393Z     raise error_metas[0].to_error()
2022-02-15T18:03:58.0158118Z AssertionError: Tensor-likes are not close!
2022-02-15T18:03:58.0158615Z 
2022-02-15T18:03:58.0158878Z Mismatched elements: 75 / 100 (75.0%)
2022-02-15T18:03:58.0160047Z Greatest absolute difference: 1.4500386636277105 at index (19, 3) (up to 1e-05 allowed)
2022-02-15T18:03:58.0161033Z Greatest relative difference: 1.0403183913191243 at index (9, 2) (up to 0 allowed)
```

### Versions

b9ccbe4ff285af8dc89050dac6dbeeaced63e21d

**Comment by jaglinux** [comment]
Test ran successfully after applying https://github.com/pytorch/pytorch/pull/78824
cc @jeffdaily
