### ISSUE TITLE
Mask-RCNN Tracing fails

### ISSUE THREAD

**Issue by skaldesh** [pytorch/pytorch#72920]
### 🐛 Describe the bug

Tracing `maskrcnn_resnet50_fpn` does not work.   

Script to reproduce:  
```py
import torch
import torchvision


# Needed since lists and dicts are not supported as output types.
# We simply put them inside a tuple.
class TraceWrapper(torch.nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, input):
        out = self.model(input)
        return out[0]["boxes"], out[0]["scores"], out[0]["labels"], out[0]["masks"]

print('Torch', torch.__version__, 'TorchVision', torchvision.__version__)

# An instance of your model.
model = TraceWrapper(torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True, pretrained_backbone=True))

# Switch the model to eval model
model.eval()

# An example input you would normally provide to your model's forward() method.
example = torch.rand(1, 3, 320, 320)

# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
traced_script_module = torch.jit.trace(model, example)
traced_script_module.eval()

# Save the TorchScript model
traced_script_module.save("maskrcnn-resnet50-fpn.pt")
```

The error message is enormous. It basically says that the graphs differ, I include here the first message and the very last message, leaving the huge diff out.  
```
/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torch/nn/functional.py:3679: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  (torch.floor((input.size(i + 2).float() * torch.tensor(scale_factors[i], dtype=torch.float32)).float()))
/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torchvision/models/detection/anchor_utils.py:122: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  strides = [[torch.tensor(image_size[0] // g[0], dtype=torch.int64, device=device),
/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torchvision/models/detection/anchor_utils.py:123: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(image_size[1] // g[1], dtype=torch.int64, device=device)] for g in grid_sizes]
/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torchvision/ops/boxes.py:146: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  boxes_x = torch.min(boxes_x, torch.tensor(width, dtype=boxes.dtype, device=boxes.device))
/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torchvision/ops/boxes.py:148: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  boxes_y = torch.min(boxes_y, torch.tensor(height, dtype=boxes.dtype, device=boxes.device))
/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torchvision/models/detection/transform.py:282: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(s, dtype=torch.float32, device=boxes.device) /
/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torchvision/models/detection/transform.py:283: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(s_orig, dtype=torch.float32, device=boxes.device)
/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torchvision/models/detection/roi_heads.py:372: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(M + 2 * padding).to(torch.float32) / torch.tensor(M).to(torch.float32)
Traceback (most recent call last):
  File "/home/skaldesh/projects/openvino/open_model_zoo/trace_model.py", line 41, in <module>
    traced_script_module = torch.jit.trace(model, example)
  File "/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torch/jit/_trace.py", line 735, in trace
    return trace_module(
  File "/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torch/jit/_trace.py", line 977, in trace_module
    _check_trace(
  File "/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/skaldesh/projects/openvino/open_model_zoo/pve/lib/python3.9/site-packages/torch/jit/_trace.py", line 521, in _check_trace
    raise TracingCheckError(*diag_info)
torch.jit._trace.TracingCheckError: Tracing failed sanity checks!
ERROR: Graphs differed across invocations!
	Graph diff:
		  graph(%self.1 : __torch__.TraceWrapper,
...
...
...
 First diverging operator:
	Node diff:
		- %2 : __torch__.torchvision.models.detection.mask_rcnn.MaskRCNN = prim::GetAttr[name="model"](%self.1)
		+ %2 : __torch__.torchvision.models.detection.mask_rcnn.___torch_mangle_362.MaskRCNN = prim::GetAttr[name="model"](%self.1)
```

### Versions

PyTorch version: 1.9.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.2.0
Clang version: 13.0.1
CMake version: version 3.22.2
Libc version: glibc-2.35

Python version: 3.9.10 (main, Feb  7 2022, 09:55:00)  [GCC 11.1.0] (64-bit runtime)
Python platform: Linux-5.15.23-1-lts-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0+cpu
[pip3] torchvision==0.10.0+cpu
[conda] Could not collect

**Comment by davidberard98** [comment]
@skaldesh, a few comments here.

1. This looks like an issue with the model that you're tracing, not an issue with pytorch.
2. I'm not sure torchvision intends to support tracing for maskrcnn. See https://github.com/pytorch/vision/issues/4158. You can ask in https://github.com/pytorch/vision if you have further questions about this.
3. From [maskrcnn docs](https://pytorch.org/vision/master/generated/torchvision.models.detection.maskrcnn_resnet50_fpn.html), it seems like input to forward is expected to be a list of tensors. You can trace this using `torch.jit.trace(module, ((example,),))`
4. The reason that tracing is failing is as follows. First, you call torch.jit.trace and the module is traced. Then, torch.jit.trace traces the module *again* as a sanity check. Then torch.jit.trace does a comparison to make sure the two outputs are the same. In this case, the outputs are **not** the same, so torch.jit.trace fails. I suspect that the reason for the failure is that the model may change after the first invocation. Note that jit tracing isn't supported for all models - see the warning in the documentation on [torch.jit.trace](https://pytorch.org/docs/stable/generated/torch.jit.trace.html) for details. If you already understand why the trace check failure is happening and are confident that tracing is still valid, you can use `torch.jit.trace(model, example_inputs, check_trace=False)`. 
5. You can instead [script](https://pytorch.org/docs/stable/generated/torch.jit.script.html) the model, which I believe torchvision intends to support for maskrcnn. In your example here, you'll have to add an annotation to the forward method, e.g. `def forward(self, input: List[Tensor]):`

**Comment by skaldesh** [comment]
> From [maskrcnn docs](https://pytorch.org/vision/master/generated/torchvision.models.detection.maskrcnn_resnet50_fpn.html), it seems like input to forward is expected to be a list of tensors. You can trace this using torch.jit.trace(module, ((example,),))  

Gives me:
`ValueError: images is expected to be a list of 3d tensors of shape [C, H, W], got torch.Size([1, 3, 320, 320])`
