### ISSUE TITLE
Tensor's .size() method returns wrong type during jit.script() 

### ISSUE THREAD

**Issue by Luonic** [pytorch/pytorch#73004]
### 🐛 Describe the bug

If-expression's true branch has type int but false branch has type Tensor, when in torchscript context `tensor.size()` should return tensor as well.

Minimal example to reproduse problem:
```python
import torch
from typing import Optional, List

class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()

    def forward(self, x, pkv: Optional[List[torch.Tensor]] = None, ql: Optional[torch.Tensor] = None):
        real_seq_length = x.size(1)
        if pkv is not None:
            real_seq_length += pkv[0].size(2) if ql is None else ql

torch.jit.script(Model())
```

Error:
```
Traceback (most recent call last):
  File "ts_bug.py", line 13, in <module>
    torch.jit.script(Model())
  File "/home/alex/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 1257, in script
    return torch.jit._recursive.create_script_module(
  File "/home/alex/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 451, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/alex/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 517, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/alex/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 368, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
if-expression's true branch has type int but false branch has type Tensor:
  File "ts_bug.py", line 11
        real_seq_length = x.size(1)
        if pkv is not None:
            real_seq_length += pkv[0].size(2) if ql is None else ql
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

### Versions

```
PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-28-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 470.103.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] botorch==0.6.0
[pip3] gpytorch==1.6.0
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.18.0
[pip3] pytorch-ignite==0.4.7
[pip3] pytorch-lightning==1.4.2
[pip3] torch==1.10.2+cu113
[pip3] torch-model-archiver==0.5.2
[pip3] torch-ort==1.9.0
[pip3] torch-stft==0.1.4
[pip3] torch-workflow-archiver==0.2.2
[pip3] torchaudio==0.10.2+cu113
[pip3] torchmetrics==0.5.0
[pip3] torchserve==0.5.2
[pip3] torchtext==0.10.0
[pip3] torchvision==0.11.3+cu113
[conda] Could not collect
```

**Comment by Luonic** [comment]
Changing type annotation of `ql` to `int` seems to fix issue
I had to reference torchscript typing system better
