### ISSUE TITLE
bad_alloc after np.exp when creating a tensor

### ISSUE THREAD

**Issue by kaiopen** [pytorch/pytorch#73356]
### 🐛 Describe the bug

I have tested on 4 computers (all are Ubuntu 20.04, pytorch==1.10.2 and python==3.9) but only reproduced the error on my computer. So I am not sure it is a bug from pytorch. However, the bug is unreasonable, so I just report it here. And of course, it is could not be better if it can be fixed.

Run a bash terminal and just run a python IDLE:
```
$ python
```
input:
```
>>> import numpy as np
>>> import torch
>>> np.exp([1])
array([2.71828183])
>>> torch.tensor([1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: std::bad_alloc
```

I also have tested:
```
>>> import torch
>>> np.exp([1,2])
array([2.71828183, 7.3890561 ])
>>> torch.zeros([1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: std::bad_alloc
```
and
```
>>> import numpy as np
>>> import torch
>>> np.exp([1])
array([2.71828183])
>>> torch.ones([1,2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: std::bad_alloc
```
and
```
>>> import numpy as np
>>> import torch
>>> np.exp(1)
2.718281828459045e+00
>>> torch.tensor([1])
tensor([1])
```
and 
```
>>> import numpy as np
>>> import torch
>>> np.exp([1])
array([2.71828183])
>>> torch.tensor(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: std::bad_alloc
```
Please note that running a new python IDLE before every testing.

If creating a torch.Tensor before np.exp, everything is OK.
```
>>> import numpy as np
>>> import torch
>>> torch.tensor(1)
tensor(1)
>>> np.exp([1])
array([2.71828183])
>>> torch.tensor(1)
tensor(1)
```

### Versions

```
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.2
[pip3] torchaudio==0.10.2
[pip3] torchvision==0.11.3
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pytorch                   1.10.2          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.2               py39_cu113    pytorch
[conda] torchvision               0.11.3               py39_cu113    pytorch
```

cc @mruberry @rgommers

**Comment by mrshenli** [comment]
cc @aazzolini jfyi :)

**Comment by kaiopen** [comment]
It is solved after updating to the latest version.
