### ISSUE TITLE
TestSparse misses out on TestCase.setUp() + thus disabling doesn't work

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#73363]
### 🐛 Describe the bug

The TestSparse test suite inherits from TestCase but overrides the parents' setUp functionality which includes the code that would allow these tests to be disabled (https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L1404). This was noticed when a flaky Sparse test kept recurring in CI when we expected it to be disabled by this issue (see https://github.com/pytorch/pytorch/issues/73145#issuecomment-1046952585). 

I had worked on a fix that would call the parent's setUp function, but that cause weird CI errors like CUDA illegal memory access: 
```
======================================================================
2022-02-22T18:45:35.4989229Z ERROR [0.298s]: test_basic_ops_cuda_float64 (__main__.TestSparseCUDA)
2022-02-22T18:45:35.4990133Z ----------------------------------------------------------------------
2022-02-22T18:45:35.4990756Z Traceback (most recent call last):
2022-02-22T18:45:35.4991700Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1745, in wrapper
2022-02-22T18:45:35.4992381Z     method(*args, **kwargs)
2022-02-22T18:45:35.4993362Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
2022-02-22T18:45:35.4994105Z     raise rte
2022-02-22T18:45:35.4995098Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
2022-02-22T18:45:35.4995814Z     result = test(self, **param_kwargs)
2022-02-22T18:45:35.4996763Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 2950, in wrapped
2022-02-22T18:45:35.4997505Z     f(self, *args, **kwargs, coalesced=True)
2022-02-22T18:45:35.4998121Z   File "test_sparse.py", line 1629, in test_basic_ops
2022-02-22T18:45:35.4998668Z     _test_basic_ops_hybrid()
2022-02-22T18:45:35.4999275Z   File "test_sparse.py", line 1622, in _test_basic_ops_hybrid
2022-02-22T18:45:35.4999984Z     self._test_basic_ops_shape(9, 12, [10, 10, 10], [2, 0], dtype, device, coalesced)
2022-02-22T18:45:35.5000952Z   File "test_sparse.py", line 1541, in _test_basic_ops_shape
2022-02-22T18:45:35.5001526Z     y1 = x1 * x2
2022-02-22T18:45:35.5002116Z RuntimeError: CUDA error: an illegal memory access was encountered
2022-02-22T18:45:35.5003000Z CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
2022-02-22T18:45:35.5003847Z For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
2022-02-22T18:45:35.5004246Z 
2022-02-22T18:45:35.5004754Z ----------------------------------------------------------------------
``` 
See https://hud.pytorch.org/pr/pytorch/pytorch/73217

### Versions

CI

cc @nikitaved @pearu @cpuhrsch

**Comment by cpuhrsch** [comment]
@pearu Can you take a look?

**Comment by pearu** [comment]
This issue raises when applying mul to sparse tensors having zero dimensions. Here is a reproducer:
```
>>> import torch
>>> x=torch.sparse_coo_tensor([[0, 1], [0, 1]], [[], []], size=(2,2,0), device='cuda')
>>> x * x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
