### ISSUE TITLE
ONNX export failed for torch_scatter ops in TAPAS model

### ISSUE THREAD

**Issue by jiahong-liu** [pytorch/pytorch#73388]
### 🐛 Describe the bug

I am trying to convert the [TAPAS](https://huggingface.co/docs/transformers/v4.16.2/en/model_doc/tapas) model from HuggingFace into ONNX format. However, it has [torch-scatter](https://github.com/rusty1s/pytorch_scatter) dependency which cannot be export to ONNX.
For easy replication: 
```
    import torch
    from transformers import TapasForQuestionAnswering

    model_name = "google/tapas-base-finetuned-wtq"
    model = TapasForQuestionAnswering.from_pretrained(model_name, torchscript=True)

    bs = 1
    seq_len = 512
    dummy_inputs = (torch.ones(bs, seq_len, dtype=torch.long), torch.ones(bs, seq_len), torch.zeros(bs, seq_len, 7, dtype=torch.long))
 
    torch.onnx.export(
        model,
        dummy_inputs,
        args.save,
        export_params=True,
        opset_version=13,
        input_names=["input_ids", "attention_mask", "token_type_ids"],
        output_names=["logits", "logits_aggregation"],
        dynamic_axes={"input_ids": [0, 1], "token_type_ids": [0, 1], "attention_mask": [0, 1], "logits": [0, 1], "logits_aggregation": [0, 1]},
    )
```
And I am getting the following error msg:
```
Traceback (most recent call last):
  File "export.py", line 21, in <module>
    torch.onnx.export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 301, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 728, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 358, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1192, in _run_symbolic_function
    raise RuntimeError("ONNX export failed on an operator with unrecognized namespace {}::{}. "
RuntimeError: ONNX export failed on an operator with unrecognized namespace torch_scatter::scatter_min. If you are trying to export a custom operator, make sure you registered it with the right domain and version.
```

### Versions

Collecting environment information...
PyTorch version: 1.11.0a0+bfe5ad2
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A
 
OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.31
 
Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-1066-aws-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.55
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 450.142.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A
 
Versions of relevant libraries:
[pip3] numpy==1.22.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.11.0a0+bfe5ad2
[pip3] torch-scatter==2.0.9
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchtext==0.12.0a0
[pip3] torchvision==0.12.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.22.0           py38h6ae9a64_0    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.11.0a0+bfe5ad2          pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchtext                 0.12.0a0                 pypi_0    pypi
[conda] torchvision               0.12.0a0                 pypi_0    pypi

**Comment by shubhambhokare1** [comment]
Here is some documentation to get you started on exporting custom operators not in the default namespaces
https://pytorch.org/docs/stable/onnx.html#custom-operators

**Comment by symphonylyh** [comment]
For TAPAS model at least, the following naive scatter implementation can be used to replace the PyTorch Geometric's scatter ops and let onnx export succeed. Note: This work was intended to make TAPAS running in TensorRT, rather than in PyTorch -- in PyTorch it's definitely much slower than PyG, but in TensorRT the end-to-end is great for inference.

```    
def scatter_naive1D(src, index, dim, dim_size, reduce):
        # Assume 1D tensor. 
        assert dim == 0 and src.dim() == 1 and index.dim() == 1, "Only support 1D scatter!"

        def reduce_op(l, op):
            result = 0
            if op == 'min':
                result = torch.min(l)
            elif op == 'max':
                result = torch.max(l)
            elif op == 'sum':
                result = torch.sum(l)
            elif op == 'mean':
                result = torch.mean(l)
            else:
                assert False, 'Reduce op not supported!'

            return result 
            
        output = torch.zeros(dim_size, dtype=src.dtype, device=src.device)
        
        index_range = torch.max(index) + 1
        bucket = [[] for _ in range(index_range)]

        for i in range(len(src)):
            bucket[index[i]].append(src[i])
        
        for i in range(len(bucket)):
            if bucket[i]:
                bucket[i] = reduce_op(torch.as_tensor(bucket[i], dtype=src.dtype, device=src.device), reduce)
            else:
                bucket[i] = 0
        
        output[:len(bucket)] = torch.as_tensor(bucket, dtype=src.dtype, device=src.device)
        
        return output
```

**Comment by samvanstroud** [comment]
Thanks @symphonylyh, unfortunately I need 2D `scatter_max`. I'm looking into whether we can get this supported directly, see https://github.com/onnx/onnx/issues/4322 and https://github.com/pyg-team/pytorch_geometric/issues/728.

**Comment by thiagocrepaldi** [comment]
The following repro

````python
import torch
from transformers import TapasForQuestionAnswering

model_name = "google/tapas-base-finetuned-wtq"
model = TapasForQuestionAnswering.from_pretrained(model_name, torchscript=True)

bs = 1
seq_len = 512
dummy_inputs = (
    torch.ones(bs, seq_len, dtype=torch.long),
    torch.ones(bs, seq_len),
    torch.zeros(bs, seq_len, 7, dtype=torch.long),
)

torch.onnx.export(
    model,
    dummy_inputs,
    "scatter.onnx",
    export_params=True,
    opset_version=13,
    input_names=["input_ids", "attention_mask", "token_type_ids"],
    output_names=["logits", "logits_aggregation"],
    dynamic_axes={
        "input_ids": [0, 1],
        "token_type_ids": [0, 1],
        "attention_mask": [0, 1],
        "logits": [0, 1],
        "logits_aggregation": [0, 1],
    },
)

````

Produces

````bash
/home/thiagofc/dev/github/pytorch-dev1/torch/onnx/utils.py:2039: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input input_ids
  warnings.warn(
/home/thiagofc/dev/github/pytorch-dev1/torch/onnx/utils.py:2039: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input token_type_ids
  warnings.warn(
/home/thiagofc/dev/github/pytorch-dev1/torch/onnx/utils.py:2039: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input attention_mask
  warnings.warn(
/home/thiagofc/dev/github/pytorch-dev1/torch/onnx/utils.py:2039: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input logits
  warnings.warn(
/home/thiagofc/dev/github/pytorch-dev1/torch/onnx/utils.py:2039: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input logits_aggregation
  warnings.warn(
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1613: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  self.indices = torch.as_tensor(indices)
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1614: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  self.num_segments = torch.as_tensor(num_segments, device=indices.device)
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1719: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  batch_size = torch.prod(torch.tensor(list(index.batch_shape())))
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1795: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  [torch.as_tensor([-1], dtype=torch.long), torch.as_tensor(vector_shape, dtype=torch.long)], dim=0
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1798: TracerWarning: Converting a tensor to a Python list might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  flat_values = values.reshape(flattened_shape.tolist())
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1804: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dim_size=int(flat_index.num_segments),
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1811: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  torch.as_tensor(index.batch_shape(), dtype=torch.long),
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1812: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  torch.as_tensor([index.num_segments], dtype=torch.long),
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1813: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  torch.as_tensor(vector_shape, dtype=torch.long),
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1818: TracerWarning: Converting a tensor to a Python list might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  output_values = segment_means.view(new_shape.tolist())
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1746: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  batch_shape = torch.as_tensor(
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1750: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  num_segments = torch.as_tensor(num_segments)  # create a rank 0 tensor (scalar) containing num_segments (e.g. 64)
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1761: TracerWarning: Converting a tensor to a Python list might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  new_shape = [int(x) for x in new_tensor.tolist()]
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1764: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  multiples = torch.cat([batch_shape, torch.as_tensor([1])], dim=0)
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1765: TracerWarning: Converting a tensor to a Python list might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  indices = indices.repeat(multiples.tolist())
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:321: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  torch.as_tensor(self.config.max_position_embeddings - 1, device=device), position - first_position
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1273: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  indices=torch.min(row_ids, torch.as_tensor(self.config.max_num_rows - 1, device=row_ids.device)),
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1278: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  indices=torch.min(column_ids, torch.as_tensor(self.config.max_num_columns - 1, device=column_ids.device)),
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1976: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  column_logits += CLOSE_ENOUGH_TO_LOG_ZERO * torch.as_tensor(
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:1981: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  column_logits += CLOSE_ENOUGH_TO_LOG_ZERO * torch.as_tensor(
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:2017: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  labels_per_column, _ = reduce_sum(torch.as_tensor(labels, dtype=torch.float32, device=labels.device), col_index)
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:2040: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  torch.as_tensor(labels, dtype=torch.long, device=labels.device), cell_index
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:2047: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  column_mask = torch.as_tensor(
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:2072: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  selected_column_id = torch.as_tensor(
/home/thiagofc/miniconda3/envs/dev1-cu113-py39/lib/python3.9/site-packages/transformers/models/tapas/modeling_tapas.py:2077: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  selected_column_mask = torch.as_tensor(
Traceback (most recent call last):
  File "/home/thiagofc/dev/pytorch_repros/stale_repro.py", line 15, in <module>
    torch.onnx.export(
  File "/home/thiagofc/dev/github/pytorch-dev1/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/thiagofc/dev/github/pytorch-dev1/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/thiagofc/dev/github/pytorch-dev1/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/home/thiagofc/dev/github/pytorch-dev1/torch/onnx/utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/thiagofc/dev/github/pytorch-dev1/torch/onnx/utils.py", line 1909, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: ONNX export failed on an operator with unrecognized namespace torch_scatter::scatter_min. If you are trying to export a custom operator, make sure you registered it with the right domain and version.
```

meaning it does not recognize `torch_scatter::scatter_min` as an operator. Indeed, `torch.onnx.export` only supports operators with domain `aten::*`. 

As pointed out by @shubhambhokare1, a custom operator is needed to support this scenario as documented at https://pytorch.org/docs/master/onnx.html#custom-operators
