### ISSUE TITLE
[JIT] fix test_jit_cuda_fuser.py - test_category_rule 

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#73395]
### 🐛 Describe the bug

Currently, test is disabled due to failures.

```
FAIL [1.266s]: test_category_rule (__main__.TestCudaFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit_cuda_fuser.py", line 628, in test_category_rule
    run_scalar(x, z)
  File "test_jit_cuda_fuser.py", line 596, in run_scalar
    self.assertEqual(o.dtype, jit_o.dtype)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 2145, in assertEqual
    msg=msg,
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1064, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Object comparison failed: torch.float64 != torch.float32
```

from line 628:
```python3
        # n-dim with scalar (type-promote)
        x = torch.randn(4, 8, 32, 32, device="cuda").to(dtype=torch.long)
        z = torch.tensor(3., dtype=torch.double)
        run_scalar(x, z) # <-- line 628
```

https://github.com/pytorch/pytorch/runs/5312624683?check_suite_focus=true

### Versions

see CI

**Comment by jjsjann123** [comment]
Will investigate this when we prepare for the next upstream push. Thanks for reporting and tagging.

**Comment by jjsjann123** [comment]
Don't have the repro with latest upstream after the merge. I saw it in the other issue where this test seems to be flaky?!

**Comment by davidberard98** [comment]
Sounds like it hasn't failed after #75340 , so probably it's been fixed.
