### ISSUE TITLE
After XNNPack update `TestXNNPACKSerDes.test_linear` started to fail

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#73488]
### 🐛 Describe the bug

TestXNNPACKSerDes.test_linear started to fail (but only on ROCm testers) after updating https://github.com/google/XNNPACK/commit/ae108ef49aa5623b896fc93d4298c49d1750d9b
with the following signature:
```
======================================================================
FAIL [0.446s]: test_linear (__main__.TestXNNPACKOps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_xnnpack_integration.py", line 25, in test_linear
    data_shape=hu.array_shapes(1, 3, 2, 64),
  File "/opt/conda/lib/python3.7/site-packages/hypothesis/core.py", line 1116, in wrapped_test
    raise the_error_hypothesis_found
  File "test_xnnpack_integration.py", line 39, in test_linear
    torch.testing.assert_close(ref_result, output_linearprepacked, rtol=1e-2, atol=1e-3)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1321, in assert_close
    msg=msg,
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 446 / 1250 (35.7%)
Greatest absolute difference: 1.7944009453058243 at index (1, 17, 22) (up to 0.001 allowed)
Greatest relative difference: 1.1037873159796914e+18 at index (1, 24, 16) (up to 0.01 allowed)


======================================================================
FAIL [3.459s]: test_combined_model (__main__.TestXNNPACKSerDes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_xnnpack_integration.py", line 440, in test_combined_model
    input_channels_per_group=st.integers(1, 32),
  File "/opt/conda/lib/python3.7/site-packages/hypothesis/core.py", line 1116, in wrapped_test
    raise the_error_hypothesis_found
  File "test_xnnpack_integration.py", line 553, in test_combined_model
    torch.testing.assert_close(ref_result, xnnpack_result, rtol=1e-2, atol=1e-3)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1321, in assert_close
    msg=msg,
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 195 / 1235 (15.8%)
Greatest absolute difference: 0.2513161301612854 at index (0, 4, 12, 17) (up to 0.001 allowed)
Greatest relative difference: inf at index (0, 4, 10, 16) (up to 0.01 allowed)


======================================================================
FAIL [1.274s]: test_linear (__main__.TestXNNPACKSerDes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_xnnpack_integration.py", line 186, in test_linear
    data_shape=hu.array_shapes(1, 3, 2, 64),
  File "/opt/conda/lib/python3.7/site-packages/hypothesis/core.py", line 1116, in wrapped_test
    raise the_error_hypothesis_found
  File "test_xnnpack_integration.py", line 218, in test_linear
    torch.testing.assert_close(ref_result, output_linearprepacked, rtol=1e-2, atol=1e-3)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1321, in assert_close
    msg=msg,
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 480 / 1188 (40.4%)
Greatest absolute difference: 7.112247561849998e+22 at index (1, 10, 50) (up to 0.001 allowed)
Greatest relative difference: 42.11850658475976 at index (1, 6, 39) (up to 0.01 allowed)


----------------------------------------------------------------------
```
For more details, see 
https://github.com/pytorch/pytorch/runs/5342822407?check_suite_focus=true

### Versions

Nightly

**Comment by malfet** [comment]
@jeffdaily can you please share cpuinfo for ROCm runners?

**Comment by jeffdaily** [comment]
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  2
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        4
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               1
Model name:          AMD EPYC 7601 32-Core Processor
Stepping:            2
CPU MHz:             1066.933
CPU max MHz:         2200.0000
CPU min MHz:         1200.0000
BogoMIPS:            4391.37
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           64K
L2 cache:            512K
L3 cache:            8192K
NUMA node0 CPU(s):   0-7,32-39
NUMA node1 CPU(s):   8-15,40-47
NUMA node2 CPU(s):   16-23,48-55
NUMA node3 CPU(s):   24-31,56-63
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
```

**Comment by digantdesai** [comment]
Any update on this?

**Comment by kimishpatel** [comment]
@jeffdaily will you be able to repro this at your end?
