### ISSUE TITLE
ONNX export fails with a `resolve_conj` op when a tensor slice is printed.

### ISSUE THREAD

**Issue by mvhv** [pytorch/pytorch#73619]
### 🐛 Describe the bug

Exporting a module as ONNX fails when the module involves a tensor slice being (maybe also any view) passed to `print()`. The export fails with a message stating that the `resolve_conj` op is not available.

It appears that printing a view invokes `resolve_conj`, which causes ONNX exports to fail even in cases where the branch is extraneous. As far as I understand, the ONNX optimiser can remove these kinds of extraneous branches, but in this case it fails before pruning.

Example:
```python
import torch
from torch import nn

class BadFirst(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_firsts = x[:, 0]
        print(f"x_firsts: {x_firsts}") # removing this line fixes the issue.
        return x_firsts


m = BadFirst().eval()
x = torch.rand(10, 5)

res = m(x) # this works
torch.onnx.export(m, x, "m.onnx") # this fails due to a resolve_conj op
```
Observed Output:
```
x_firsts: tensor([0.8206, 0.7061, 0.0366, 0.7012, 0.4380, 0.0920, 0.7127, 0.1474, 0.5061,
        0.9991])
x_firsts: tensor([0.8206, 0.7061, 0.0366, 0.7012, 0.4380, 0.0920, 0.7127, 0.1474, 0.5061,
        0.9991])
Traceback (most recent call last):
  File "~\scratch\pytorch\example.py", line 18, in <module>
    torch.onnx.export(m, x, "m.onnx") # this fails due to a resolve_conj op
  File "~\.virtualenvs\pytorch-jk_rFARN\lib\site-packages\torch\onnx\__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "~\.virtualenvs\pytorch-jk_rFARN\lib\site-packages\torch\onnx\utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "~\.virtualenvs\pytorch-jk_rFARN\lib\site-packages\torch\onnx\utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "~\.virtualenvs\pytorch-jk_rFARN\lib\site-packages\torch\onnx\utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "~\.virtualenvs\pytorch-jk_rFARN\lib\site-packages\torch\onnx\utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "~\.virtualenvs\pytorch-jk_rFARN\lib\site-packages\torch\onnx\__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "~\.virtualenvs\pytorch-jk_rFARN\lib\site-packages\torch\onnx\utils.py", line 1028, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "~\.virtualenvs\pytorch-jk_rFARN\lib\site-packages\torch\onnx\utils.py", line 982, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "~\.virtualenvs\pytorch-jk_rFARN\lib\site-packages\torch\onnx\symbolic_registry.py", line 125, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator resolve_conj to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```
I think I understand why `resolve_conj` is invoked here, but causing an ONNX export failure feels like an unintentional side-effect, that could potentially be avoided by pruning the graph before invoking the ONNX optimiser.

If `torch.jit.script` is run first, then exporting the ONNX model succeeds, but `torch.jit.trace` fails in the same way.

### Versions

Test 1 (python 3.9.6/torch 1.10.2):
```
PyTorch version: 1.10.2+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.21.0-rc3
Libc version: N/A

Python version: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19042-SP0
Is CUDA available: False
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Quadro P400
Nvidia driver version: 461.55

cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudnn64_7.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] torch==1.10.2
[conda] Could not collect
```
Test 2 (python 3.9.10/torch 1.9.1):
```
PyTorch version: 1.9.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19042-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro P2000
Nvidia driver version: 462.30
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] torch==1.9.1
[conda] Could not collect
```

**Comment by fatcat-z** [comment]
This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1685669

**Comment by mvhv** [comment]
@Kroshtan `torch.conj()` creates a view of a tensor with the conjugate bit set to avoid excessive copying. If a later op can't operate on a view then `torch.resolve_conj()` is called which materialises the conjugate on-demand.

I don't know the exact workings (and don't really care enough to check further), but my guess is that whatever string formatter is used for displaying tensors makes a copy to avoid hogging memory from the runtime while blocking on IO, and that copy triggers resolve_conj because you may as well materialise it now in-case you need it later.

The ops should just be pruned off the tree by ONNX, but it can't know that until it's loaded the graph, and it can't load the graph while it has unknown ops in it.

**Comment by justinchuby** [comment]
@BowenBao reproducible in nightly

```
Torch IR graph at exception: graph(%0 : Float(10, 5, strides=[5, 1], requires_grad=0, device=cpu)):
  %174 : Long(device=cpu) = prim::Constant[value={0}](), scope: __main__.BadFirst::
  %175 : Long(device=cpu) = prim::Constant[value={9223372036854775807}](), scope: __main__.BadFirst::
  %176 : Long(device=cpu) = prim::Constant[value={1}](), scope: __main__.BadFirst::
  %93 : Float(10, 5, strides=[5, 1], requires_grad=0, device=cpu) = aten::slice(%0, %174, %174, %175, %176), scope: __main__.BadFirst:: # <ipython-input-3-cc5d0ee6a95d>:9:0
  %inp : Float(10, strides=[5], requires_grad=0, device=cpu) = aten::select(%93, %176, %174), scope: __main__.BadFirst:: # <ipython-input-3-cc5d0ee6a95d>:9:0
  %172 : Float(10, strides=[5], requires_grad=0, device=cpu) = aten::resolve_conj(%inp), scope: __main__.BadFirst:: # pytorch/torch/_tensor_str.py:232:0
  %173 : Float(10, strides=[5], requires_grad=0, device=cpu) = aten::resolve_neg(%172), scope: __main__.BadFirst:: # pytorch/torch/_tensor_str.py:232:0
  return (%173)
```

**Comment by lix19937** [comment]
But what is the solution ?
