### ISSUE TITLE
IOError: [Errno 4] Interrupted system call

### ISSUE THREAD

**Issue by zjtgit** [pytorch/pytorch#7364]
## Training Error

Using pytorch training my network, got an error when training the 104th epoch.

## Code example
```python
Train Epoch: 104 [5000/5005 (100%)]	Loss: 1.302228	LR: 0.00150062502236	Top1 Acc:65.1956	Top5 Acc:85.9462
Best Accuracy: 68.10%
Traceback (most recent call last):
  File "train.py", line 438, in <module>
    test(epoch)
  File "train.py", line 351, in test
    print('Best Accuracy: {:.2f}%\n'.format(best_acc))
IOError: [Errno 4] Interrupted system call
```

## System Info
```
PyTorch version: 0.3.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: Could not collect

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GT 710
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp
GPU 4: TITAN Xp
GPU 5: TITAN Xp
GPU 6: TITAN Xp
GPU 7: TITAN Xp
GPU 8: TITAN Xp

Nvidia driver version: 390.25
cuDNN version: Probably one of the following:
/usr/local/MATLAB/R2017b/bin/glnxa64/libcudnn.so.5.1.5
/usr/local/cuda-9.1/lib64/libcudnn.so
/usr/local/cuda-9.1/lib64/libcudnn.so.7
/usr/local/cuda-9.1/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.1/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] msgpack-numpy (0.4.3)
[pip] numpy (1.13.3)
[pip] numpydoc (0.7.0)
[pip] torch (0.3.1.post2)
[pip] torchvision (0.2.0)
[conda] pytorch                   0.3.1           py27_cuda9.1.85_cudnn7.0.5_2  [cuda91] 
[conda] pytorch-imagenet-dataloader 0.0.1                     <pip>
[conda] torchvision               0.2.0            py27hfb27419_1 
```

**Comment by SsnL** [comment]
Some syscall in print was interrupted. Not really a PyTorch issue. See this PEP: https://bugs.python.org/issue9867
