### ISSUE TITLE
JIT: Fuser failures when calling a script function from multiple threads

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#73789]
### 🐛 Describe the bug

I'm seeing crashes of various from an shape when trying to run a program that calls the following function
```python
@torch.jit.script
def weighted_sum(a, alpha: float, b, beta: float):
    return a * alpha + b * beta
```
from multiple threads.

Unfortunately, I cannot share the full repro code, but here is a sample traceback:

```
#0  0x00007fffafe6e455 in std::_Hashtable<std::shared_ptr<torch::jit::tensorexpr::Buf>, std::pair<std::shared_ptr<torch::jit::tensorexpr::Buf> const, void*>, std::allocator<std::pair<std::shared_ptr<torch::jit::tensorexpr::Buf> const, void*> >, std::__detail::_Select1st, std::equal_to<std::shared_ptr<torch::jit::tensorexpr::Buf> >, std::hash<std::shared_ptr<torch::jit::tensorexpr::Buf> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find(std::shared_ptr<torch::jit::tensorexpr::Buf> const&) ()
   from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cpu.so
#1  0x00007fffafe7f2e3 in torch::jit::tensorexpr::SimpleIREvaluatorImpl::visit(std::shared_ptr<torch::jit::tensorexpr::Store>) () from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cpu.so
#2  0x00007fffafeb59b5 in torch::jit::tensorexpr::StmtNode<torch::jit::tensorexpr::Store>::accept(torch::jit::tensorexpr::IRVisitor*) () from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cpu.so
#3  0x00007fffafe2fa5c in torch::jit::tensorexpr::SimpleIREvaluator::call_raw(std::vector<void*, std::allocator<void*> > const&) () from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cpu.so
#4  0x00007fffa7042b63 in torch::jit::tensorexpr::ExprEval<torch::jit::tensorexpr::SimpleIREvaluator>::call_raw(std::vector<void*, std::allocator<void*> > const&) ()
   from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda.so
#5  0x00007fffa70264bf in torch::jit::tensorexpr::CudaCodeGen::call_raw(std::vector<void*, std::allocator<void*> > const&) () from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda.so
#6  0x00007fffa7020502 in torch::jit::tensorexpr::CudaCodeGen::call(std::vector<torch::jit::tensorexpr::CodeGen::CallArg, std::allocator<torch::jit::tensorexpr::CodeGen::CallArg> > const&) ()
   from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda.so
#7  0x00007fffaff2ef4a in torch::jit::tensorexpr::TensorExprKernel::runKernel(std::vector<c10::IValue, std::allocator<c10::IValue> >&) () from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cpu.so
#8  0x00007fffafcb4af6 in torch::jit::createTensorExprOp(torch::jit::Node const*)::{lambda(std::vector<c10::IValue, std::allocator<c10::IValue> >&)#2}::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >&) const [clone .isra.0] () from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cpu.so
#9  0x00007fffafd077f7 in torch::jit::InterpreterStateImpl::runImpl(std::vector<c10::IValue, std::allocator<c10::IValue> >&) () from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cpu.so
#10 0x00007fffafd08e3c in torch::jit::InterpreterStateImpl::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) () from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cpu.so
#11 0x00007fffafcebacd in torch::jit::GraphExecutorImplBase::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) () from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cpu.so
#12 0x00007fffb5b4f07e in torch::jit::runAndInsertCall(torch::jit::Function&, torch::jit::tuple_slice const&, pybind11::kwargs const&, c10::optional<c10::IValue>, std::function<torch::jit::Value* (torch::jit::Graph&, torch::jit::MatchedSchema const&)> const&) () from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so
#13 0x00007fffb5be1572 in pybind11::cpp_function::initialize<torch::jit::initJitScriptBindings(_object*)::{lambda(pybind11::args, pybind11::kwargs)#53}, pybind11::object, pybind11::args, pybind11::kwargs, pybind11::name, pybind11::is_method, pybind11::sibling>(torch::jit::initJitScriptBindings(_object*)::{lambda(pybind11::args, pybind11::kwargs)#53}&&, pybind11::object (*)(pybind11::args, pybind11::kwargs), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) ()
   from /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so
```

### Versions

Version: master branch from Feb 24.

**Comment by eellison** [comment]
Fix here: https://github.com/pytorch/pytorch/pull/73800

**Comment by eellison** [comment]
Closed on master..
