### ISSUE TITLE
TypeError: cannot pickle 'torch._C._distributed_c10d._ProcessGroupWrapper' object

### ISSUE THREAD

**Issue by adk9** [pytorch/pytorch#73825]
### 🐛 Describe the bug

I'm trying to save a simple model (`LinLayerNet` in the example below) that takes as input a reference to a new process group being used for collective communication:

```python
import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp

class LinLayerNet(torch.nn.Module):
    def __init__(self, group):
        super().__init__()
        self.a = torch.nn.Linear(10, 10, bias=False)
        self.group = group

    def forward(self, x):
        a = self.a(x)
        dist.all_reduce(a, group=self.group)
        return a

def worker(rank):
    dist.init_process_group("gloo", rank=rank, world_size=1)
    group_gloo = dist.new_group(backend="gloo")
    model = LinLayerNet(group_gloo)
    ddp_model = torch.nn.parallel.DistributedDataParallel(model)
    inp = torch.randn(10, 10)

    torch.save(ddp_model, 'ddp_model.pt')

    for _ in range(20):
        output = ddp_model(inp)
        loss = output[0] + output[1]
        loss.sum().backward()

if __name__ == "__main__":
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "29501"
    mp.spawn(worker, nprocs=1, args=())
```

`torch.save` fails with the following traceback:
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/Users/adk9/dist.py", line 24, in worker
    torch.save(ddp_model, 'ddp_model.pt')
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 484, in _save
    pickler.dump(obj)
TypeError: cannot pickle 'torch._C._distributed_c10d.ProcessGroupGloo' object
```

Any idea how I can get around this issue?

### Versions

1.10.2

**Comment by H-Huang** [comment]
@adk9 thanks for the repro! A workaround is to save the state_dict:

```python
torch.save(ddp_model.module.state_dict(), 'model_state.pt')
```

which can be loaded like this:

```python
new_model = LinLayerNet(group_gloo)
new_model.load_state_dict(torch.load('model_state.pt'))
```

cc @pritamdamania87, should we add pickling support for ProcessGroups?

**Comment by adk9** [comment]
> @adk9 thanks for the repro! A workaround is to save the state_dict:
> 
> ```python
> torch.save(ddp_model.module.state_dict(), 'model_state.pt')
> ```
> 
> which can be loaded like this:
> 
> ```python
> new_model = LinLayerNet(group_gloo)
> new_model.load_state_dict(torch.load('model_state.pt'))
> ```
> 
> cc @pritamdamania87, should we add pickling support for ProcessGroups?

@H-Huang Thanks for the suggestion. In my actual use case, I run into this error when cloning/deep-copying the model. Is there a workaround you can think of that'd work for all models where I only have access to the model object and not the `Module` class that was used to instantiate it?

**Comment by pritamdamania87** [comment]
> @H-Huang Thanks for the suggestion. In my actual use case, I run into this error when cloning/deep-copying the model. Is there a workaround you can think of that'd work for all models where I only have access to the model object and not the Module class that was used to instantiate it?

Is there a reason to clone/deep copy the DDP module itself instead of ddp.module and then wrapping that with DDP instead?

**Comment by pritamdamania87** [comment]
> cc @pritamdamania87, should we add pickling support for ProcessGroups?

Pickling ProcessGroups is tricky and needs more careful attention since there is a lot of dependency on the environment (rank, world_size, backend etc.). I don't see a way of it working as-is with `torch.save` since at load time the environment might be different and we probably need some sort of specialized API to pickle/unpickle ProcessGroup. Although, in terms of DDP and the use case here, pickling ProcessGroup shouldn't really be the solution here. The goal here is to actually pickle ddp.module and not DDP itself. The model is ddp.module, whereas DDP is just the runtime configuration.

**Comment by adk9** [comment]
> Is there a reason to clone/deep copy the DDP module itself instead of ddp.module and then wrapping that with DDP instead?

Thanks @pritamdamania87. Using ddp.module works for the reproducer above. In my actual use case however, the model I'm trying to deep-copy is not a DDP module and, yet, it contains ProcessGroup information. Is it possible to skip pickling/unpickling of ProcessGroup in this case?

**Comment by pritamdamania87** [comment]
> Thanks @pritamdamania87. Using ddp.module works for the reproducer above. In my actual use case however, the model I'm trying to deep-copy is not a DDP module and, yet, it contains ProcessGroup information. Is it possible to skip pickling/unpickling of ProcessGroup in this case?

You could define a custom `state_dict` and `load_state_dict` method for this module to only extract out the state needed and not pickle everything.
