### ISSUE TITLE
SummaryWriter reports encoding error

### ISSUE THREAD

**Issue by wyy-class** [pytorch/pytorch#73909]
### Problem Description
Encoding error is reported just by introducing a class
```
# conding=utf-8
from torch.utils.tensorboard import SummaryWriter
```
### error
```
Traceback (most recent call last):
  File "D:/workstation/python/practice1/torch_test/Tensorboard_demo2.py", line 2, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "D:\anaconda\anaconda\envs\pytorch\lib\site-packages\torch\utils\tensorboard\__init__.py", line 8, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa F401
  File "D:\anaconda\anaconda\envs\pytorch\lib\site-packages\torch\utils\tensorboard\writer.py", line 339
            """
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xbf in position 338: invalid start byte
```

### Versions

torch : 1.6.0
tensorboard : 2.8.0

**Comment by 15bonte** [comment]
I had the same problem yesterday, and for some reason it disappears when running the code as admin (on Windows)...
