### ISSUE TITLE
User raised TypeError from __torch_dispatch__ gets turned into generic "unsupported operand type" message

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#73930]
### 🐛 Describe the bug

https://github.com/albanD/subclass_zoo/blob/1829825ecb74eba57945f6900a6fd22399311978/bug_zoo.py#L8-L16

```
        class BuggyTensor(BaseTensor):
            @classmethod
            def __torch_dispatch__(cls, func, types, args=(), kwargs=None):
                raise TypeError("foobar")

        x = BuggyTensor(torch.tensor(1.0))
        self.assertRaisesRegex(TypeError, "foobar", lambda: x + x)
```

This doesn't work, instead you get

```
TypeError: unsupported operand type(s) for +: 'BuggyTensor' and 'BuggyTensor'
```

Suppressing the original TypeError message is confusing because it might have been due to a bug in `__torch_dispatch__` which we would like to surface to user.

### Versions

master

**Comment by ezyang** [comment]
I think this is our fault, somehow. Here is the direct Python magic method behavior:

```
(/home/ezyang/local/pytorch-tmp-env) [ezyang@devvm066.ash0 ~/local/subclass_zoo] python a.py
Traceback (most recent call last):
  File "/data/users/ezyang/subclass_zoo/a.py", line 5, in <module>
    C() + C()
  File "/data/users/ezyang/subclass_zoo/a.py", line 3, in __add__
    raise TypeError("boof")
TypeError: boof
(/home/ezyang/local/pytorch-tmp-env) [ezyang@devvm066.ash0 ~/local/subclass_zoo] cat a.py
class C:
    def __add__(self, other):
        raise TypeError("boof")

C() + C()
```

**Comment by hameerabbasi** [comment]
Well, `.tp_add` "incorrectly" catches `TypeError` and returns `NotImplemented`, which results in the above.

**Comment by ezyang** [comment]
We should redo what @peterbell10 but instead of the global try catch, teach the argument parser to handle this directly (and return NotImplementedError instead of raising). Or we can have a special sentinel exception that gets NotImplementedError'ized when it gets to the boundary.

**Comment by hannahsalameh** [comment]
Hello! I am a beginner to contributing and would like to take this bug up. Is there any relevant resources that could help me that I could be pointed to?
