### ISSUE TITLE
torch/lib/libATen.so--Program received signal SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by BUPTAlanMa** [pytorch/pytorch#7401]
## Issue description
An Error **Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)** reported by PyCharm with the code ```out = net(input)```. In the gdb mode, the Error information is *Program received signal SIGSEGV, Segmentation fault.* and seems point to "torch/lib/libATen.so". 
Provide a short description.
I install Pytorch by conda on unbuntu.  When I run the code of *Neural Networks* of the tutorial. An Error **Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)** reported by PyCharm.  In the gdb mode, the Error  is *Program received signal SIGSEGV, Segmentation fault.* and seems point to "torch/lib/libATen.so".  My GCC Version is GCC 4.8.4. Need Update?
## Code example
This is gdb Error Info:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
10
(6, 1, 5, 5)
[New Thread 0x7fffba86e700 (LWP 25754)]
True
[New Thread 0x7fffba06c780 (LWP 25755)]
[New Thread 0x7fffb9c6b800 (LWP 25756)]
[New Thread 0x7fffb986a880 (LWP 25757)]
[New Thread 0x7fffb9469900 (LWP 25758)]
[New Thread 0x7fffb9068980 (LWP 25759)]
[New Thread 0x7fffb8c67a00 (LWP 25760)]
[New Thread 0x7fffb8866a80 (LWP 25761)]
[New Thread 0x7fffb8465b00 (LWP 25762)]
[New Thread 0x7fff9bffeb80 (LWP 25763)]
[New Thread 0x7fff9bbfdc00 (LWP 25764)]
[New Thread 0x7fff9b7fcc80 (LWP 25765)]
[New Thread 0x7fff9b3fbd00 (LWP 25766)]
[New Thread 0x7fff9affad80 (LWP 25767)]
[New Thread 0x7fff9abf9e00 (LWP 25768)]
[New Thread 0x7fff9a7f8e80 (LWP 25769)]

Program received signal SIGSEGV, Segmentation fault.
0x000000000060fbe0 in ?? ()
(gdb) where
#0  0x000000000060fbe0 in ?? ()
#1  0x00007fffbf97d5d2 in mkl_blas_avx2_sgemm_initialize_kernel_info ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/torch/lib/libATen.so
#2  0x00007fff754dd894 in ?? ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/numpy/core/../../../../libmkl_avx2.so
#3  0x00007ffff2e05c3f in ?? ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/numpy/core/../../../../libmkl_intel_thread.so
#4  0x00007ffff2e32ca1 in ?? ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/numpy/core/../../../../libmkl_intel_thread.so
#5  0x00007ffff46a8145 in ?? ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/numpy/core/../../../../libmkl_intel_lp64.so
#6  0x00007fffbdcb9671 in THFloatBlas_gemm ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/torch/lib/libATen.so
#7  0x00007fffbda55941 in THFloatTensor_addmm ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/torch/lib/libATen.so
#8  0x00007fffbddaa540 in THNN_FloatSpatialConvolutionMM_updateOutput_frame(THFloatTensor*, THFloatTensor*, THFloatTensor*, THFloatTensor*, THFloatTensor*, int, int, int, int, int, int, long, long, long, long, long, long) ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/torch/lib/libATen.so
---Type <return> to continue, or q <return> to quit---
#9  0x00007fffbddaa62a in THNN_FloatSpatialConvolutionMM_updateOutput._omp_fn.98 () from /home/rjzn/anaconda2/lib/python2.7/site-packages/torch/lib/libATen.so
#10 0x00007ffff0ce7441 in ?? ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/numpy/core/../../../../libiomp5.so
#11 0x00007fffbddac82a in THNN_FloatSpatialConvolutionMM_updateOutput ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/torch/lib/libATen.so
#12 0x00007fffbd774a29 in at::CPUFloatType::thnn_conv2d_forward(at::Tensor const&, at::Tensor const&, at::ArrayRef<long>, at::Tensor const&, at::ArrayRef<long>, at::ArrayRef<long>) const ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/torch/lib/libATen.so
#13 0x00007fffe2c06b27 in torch::autograd::VariableType::thnn_conv2d_forward (
    this=0x1076270, self=..., weight=..., kernel_size=..., bias=..., 
    stride=..., padding=...)
    at torch/csrc/autograd/generated/VariableType.cpp:16920
#14 0x00007fffbd9438fd in at::Type::thnn_conv2d(at::Tensor const&, at::Tensor const&, at::ArrayRef<long>, at::Tensor const&, at::ArrayRef<long>, at::ArrayRef<long>) const ()
   from /home/rjzn/anaconda2/lib/python2.7/site-packages/torch/lib/libATen.so
#15 0x00007fffe2ba117b in torch::autograd::VariableType::thnn_conv2d (
    this=0x1076270, self=..., weight=..., kernel_size=..., bias=..., 
    stride=..., padding=...)
    at torch/csrc/autograd/generated/VariableType.cpp:16859
---Type <return> to continue, or q <return> to quit---q

```
## System Info
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 14.04.4 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
CMake version: version 2.8.12.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: Tesla M40 24GB
Nvidia driver version: 375.20
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.11.3)
[pip] numpydoc (0.6.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] torch                     0.4.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

**Comment by ezyang** [comment]
I'm going to guess we've fixed this on master, feel free to reopen if you can still repro on 1.7
