### ISSUE TITLE
arguments are located on different GPUs 

### ISSUE THREAD

**Issue by lan2720** [pytorch/pytorch#7405]
Hi, I trained a model and when it was early stopping, the train part was finished and test part started.

But here was a runtime error when I used the gpuid != 0 (when gpuid=0, it's ok).
```
epoch: 52 / dev_acc: 0.6304668304668305
early stopping by dev_acc!
max dev acc: 0.667027027027027
A model is saved successfully as /home/saved_models/dev_acc_0.667027027027027.pkl!
====================TRAINING FINISHED====================
====================TESTING STARTED====================
Traceback (most recent call last):
  File "difficulty.py", line 460, in <module>
    main()
  File "difficulty.py", line 451, in main
    test_acc = test(args, test_data, model, True)
  File "difficulty.py", line 413, in test
    batch_pred_cuda = model(paragraph, sentence, answer, paragraph_mask, sentence_mask, answer_mask, length, oov)
  File "/home/jiananwang/anaconda2/envs/daqg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/jiananwang/difficulty/model.py", line 384, in forward
    para = self.embedding(paragraph).view(-1, self.para_limit*self.sent_limit, self.word_dim) #[B, PL*SL, D]
  File "/home/jiananwang/anaconda2/envs/daqg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jiananwang/anaconda2/envs/daqg/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 108, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/jiananwang/anaconda2/envs/daqg/lib/python3.6/site-packages/torch/nn/functional.py", line 1076, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCTensorIndex.cu:563
```
The nn.Embedding Layer is embedded in the overall model, but its initial weights are loaded from a numpy array. 
Could anyone provide some clue to resolve it?

**Comment by lan2720** [comment]
#3452

**Comment by apaszke** [comment]
The error message is clear. Your weights are probably on a different GPU than the input to the network.

We're using GitHub issues for bug reports only, and all questions should be posted on [our forums](http://discuss.pytorch.org).

**Comment by lan2720** [comment]
`.cuda(gpuid)` doesn't work as you expect. When running the model, part of it will still use gpu=0. So use `CUDA_VISIBLE_DEVICES` instead for security.
