### ISSUE TITLE
torch.jit.script does not custom state_dicts

### ISSUE THREAD

**Issue by alanhdu** [pytorch/pytorch#74112]
### 🐛 Describe the bug

It looks like `torch.jit.script` does *not* preserve custom state dicts. If you run the following script:

```python
import torch
from torch import nn

linear = nn.quantized.Linear(1, 1)
scripted = torch.jit.script(linear)

print(linear.state_dict())
print(scripted.state_dict())
```

you can see that the `scripted` state dict is now empty!

```
OrderedDict([('scale', tensor(1.)), ('zero_point', tensor(0)), ('_packed_params.dtype', torch.qint8), ('_packed_params._packed_params', (tensor([[34.]], size=(1, 1), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=1.0, zero_point=0), tensor([0.])))])
OrderedDict()
```

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Fedora release 34 (Thirty Four) (x86_64)
GCC version: (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Clang version: 12.0.1 (Fedora 12.0.1-1.fc34)
CMake version: Could not collect
Libc version: glibc-2.33

Python version: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:53:36)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.18-100.fc34.x86_64-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[conda] blas                      2.16                        mkl    conda-forge
[conda] cpuonly                   2.0                           0    pytorch
[conda] libblas                   3.8.0                    16_mkl    conda-forge
[conda] libcblas                  3.8.0                    16_mkl    conda-forge
[conda] liblapack                 3.8.0                    16_mkl    conda-forge
[conda] liblapacke                3.8.0                    16_mkl    conda-forge
[conda] mkl                       2020.2                      256  
[conda] numpy                     1.22.3           py38h05e7239_0    conda-forge
[conda] pytorch                   1.11.0              py3.8_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
```

**Comment by davidberard98** [comment]
Thanks for the report @alanhdu.

A few more details here:
This is an issue with `_save_to_state_dict`. In `torch.nn.quantized.Linear`, a custom `_save_to_state_dict` implementation is defined. In order for it to be recognized by jit, it needs to be exported with `@torch.jit.export`. e.g., [here](https://github.com/pytorch/pytorch/blob/9233af181f5459793885ed9ddb1fdddcb543fd44/test/jit/test_module_apis.py#L54-L58)

However, the _save_to_state_dict implementation is not scriptable because of `super()._save_to_state_dict(...)`:
```
Traceback (most recent call last):
  File "/data/users/dberard/scripts/74056/mm.py", line 5, in <module>
    scripted = torch.jit.script(linear)
  File "/data/users/dberard/pytorch/torch/jit/_script.py", line 1266, in script
    return torch.jit._recursive.create_script_module(
  File "/data/users/dberard/pytorch/torch/jit/_recursive.py", line 454, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/data/users/dberard/pytorch/torch/jit/_recursive.py", line 520, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/data/users/dberard/pytorch/torch/jit/_recursive.py", line 371, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
'Tensor' object has no attribute or method '_save_to_state_dict'.:
  File "/data/users/dberard/pytorch/torch/nn/quantized/modules/linear.py", line 194
    @torch.jit.export
    def _save_to_state_dict(self, destination, prefix, keep_vars):
        super()._save_to_state_dict(destination, prefix, keep_vars)
        ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        destination[prefix + 'scale'] = torch.tensor(self.scale)
        destination[prefix + 'zero_point'] = torch.tensor(self.zero_point)
```

Not quite sure how to fix this - it might be possible to add a special case for _save_to_state_dict for this purpose

**Comment by davidberard98** [comment]
cc @dzdang

**Comment by andrewor14** [comment]
Hi @alanhdu, unfortunately using quantization with `torch.jit.script` is no longer actively maintained so we will likely not get to fixing this issue. Were you able to find a workaround?
