### ISSUE TITLE
Override tests in test/test_overrides.py failing for some functions

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/pytorch#74122]
### 🐛 Describe the bug

[`generate_tensor_like_override_tests(TestTorchFunctionOverride)`](https://github.com/pytorch/pytorch/blob/22a3a17ea0d61660b53f6642fe22529a7e4e2649/test/test_overrides.py#L693) in `test/test_overrides.py` was disabled since #64841. As a result, the associated tests have not been run since then. Re-enabling this in #74121 surfaced issues, particularly with 

- TestTorchFunctionOverride.test_torch_functional_histogramdd
- TestTorchFunctionOverride.test_Tensor_storage_type

These are skipped for now but should be fixed, opening this issue to track.

2022-03-11T20:23:14.4580034Z ERROR [0.001s]: test_torch_functional_histogramdd (__main__.TestTorchFunctionOverride)
2022-03-11T20:23:14.4580499Z ----------------------------------------------------------------------
2022-03-11T20:23:14.4580766Z Traceback (most recent call last):
2022-03-11T20:23:14.4580990Z   File "test_overrides.py", line 646, in test
2022-03-11T20:23:14.4581189Z     ret = func(*func_args, **kwargs)
2022-03-11T20:23:14.4581762Z   File "/opt/conda/lib/python3.7/site-packages/torch/functional.py", line 464, in histogramdd
2022-03-11T20:23:14.4582024Z     if bins and isinstance(bins[0], int):
2022-03-11T20:23:14.4582308Z TypeError: 'TensorLike' object is not subscriptable
2022-03-11T20:23:14.4582453Z 
2022-03-11T20:23:14.4582543Z ======================================================================
2022-03-11T20:23:14.4582785Z FAIL [0.001s]: test_Tensor_storage_type (__main__.TestTorchFunctionOverride)
2022-03-11T20:23:14.4583150Z ----------------------------------------------------------------------
2022-03-11T20:23:14.4583385Z Traceback (most recent call last):
2022-03-11T20:23:14.4583601Z   File "test_overrides.py", line 655, in test
2022-03-11T20:23:14.4583832Z     self.assertEqual(ret, -1)
2022-03-11T20:23:14.4584208Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 2154, in assertEqual
2022-03-11T20:23:14.4584470Z     msg=msg,
2022-03-11T20:23:14.4584794Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
2022-03-11T20:23:14.4585070Z     raise error_metas[0].to_error()
2022-03-11T20:23:14.4585349Z AssertionError: Object comparison failed: <class 'int'> != -1
2022-03-11T20:23:14.4585502Z 

### Versions

CI

cc @mruberry @hameerabbasi @rgommers @peterbell10

**Comment by ezyang** [comment]
cc @albanD
