### ISSUE TITLE
[docker] test_corrcoef_cpu_complex64 fails on CPU build

### ISSUE THREAD

**Issue by dizcza** [pytorch/pytorch#74187]
### 🐛 Describe the bug

I'm building pytorch from sources out of curiosity and I noticed that several tests fail consistently across different platforms I'm using.

## Dockerfile

```Dockerfile
FROM ubuntu:18.04
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        libjpeg-dev \
        libpng-dev && \
    rm -rf /var/lib/apt/lists/*
ENV PATH /opt/conda/bin:$PATH

ENV INSTALL_CHANNEL pytorch
ENV PYTHON_VERSION 3.9
ENV PYTORCH_VERSION v1.10.2

RUN curl -fsSL -o ~/miniconda.sh -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda install -y python=${PYTHON_VERSION} conda-build pyyaml numpy ipython requests typing_extensions && \
    /opt/conda/bin/conda clean -ya

WORKDIR /opt/pytorch
RUN curl -fsSL -o pytorch.tar.gz https://github.com/pytorch/pytorch/releases/download/${PYTORCH_VERSION}/pytorch-${PYTORCH_VERSION}.tar.gz && tar xzf pytorch.tar.gz && rm pytorch.tar.gz

RUN cd pytorch-${PYTORCH_VERSION} && \
    echo ${PYTORCH_VERSION} | tail -c +2 > version.txt && \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    USE_ROCM=0 USE_CUDA=0 \
    python setup.py install

ENV PATH /opt/conda/bin:$PATH
```

## Failed tests

Test command (inside a docker container)
```
$ python /opt/pytorch/pytorch-v1.11.0/test/test_torch.py
```

Test output

```
======================================================================
FAIL: test_corrcoef_cpu_complex64 (__main__.TestTorchDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 951, in only_fn
    return fn(self, *args, **kwargs)
  File "/opt/pytorch/pytorch-v1.11.0/test/test_torch.py", line 1745, in test_corrcoef
    self.assertEqual(res, ref, exact_dtype=False)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2121, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1080, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 4 / 4 (100.0%)
Greatest absolute difference: nan at index (0, 1) (up to 1e-05 allowed)
Greatest relative difference: nan at index (0, 1) (up to 1.3e-06 allowed)


======================================================================
FAIL: test_cov_cpu_complex64 (__main__.TestTorchDeviceTypeCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/pytorch/pytorch-v1.11.0/test/test_torch.py", line 1758, in test_cov
    check(x)
  File "/opt/pytorch/pytorch-v1.11.0/test/test_torch.py", line 1755, in check
    self.assertEqual(res, ref, atol=1e-05, rtol=1e-05, exact_dtype=False)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2121, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1080, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 4 / 4 (100.0%)
Greatest absolute difference: 83.38657060851698 at index (1, 1) (up to 1e-05 allowed)
Greatest relative difference: 1.6077072050069752 at index (0, 0) (up to 1e-05 allowed)

----------------------------------------------------------------------
Ran 599 tests in 14.380s

FAILED (failures=2, skipped=90)
```

I'm not sure if I'm testing pytorch correctly. Following [this guide](https://github.com/pytorch/pytorch/blob/b7307687e9cee6689c8ad513939ac406221efd9a/CONTRIBUTING.md#unit-testing), I'm getting another issue:

```
$ python /opt/pytorch/pytorch-v1.11.0/test/run_test.py

======================================================================
FAIL: test_join_kwargs (__main__.TestJoin)
Tests passing keyword arguments to the context manager.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 484, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 703, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 758, in _check_return_codes
    self.assertEqual(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2121, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1080, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Expect process 1 exit code to match Process 0 exit code of -6, but got 0

----------------------------------------------------------------------
Ran 9 tests in 10.582s

FAILED (failures=1)
Traceback (most recent call last):
  File "/opt/pytorch/pytorch-v1.11.0/test/run_test.py", line 1114, in <module>
    main()
  File "/opt/pytorch/pytorch-v1.11.0/test/run_test.py", line 1092, in main
    raise RuntimeError(err_message)
RuntimeError: distributed/algorithms/test_join failed!
```

### Versions

Tested v1.10.2 and v1.11.0.

```
$ python collect_env.py 

Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-161-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.11.0+gitunknown
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] torch                     1.11.0+gitunknown          pypi_0    pypi
```

**Comment by malfet** [comment]
@dizcza can you please try using [pytorch/pytorch/1.11.0-cuda11.3-cudnn8-devel](https://hub.docker.com/layers/pytorch/pytorch/1.11.0-cuda11.3-cudnn8-devel/images/sha256-9bfcfa72b6b244c1fbfa24864eec97fb29cfafc065999e9a9ba913fa1e690a02?context=explore) docker image as see if the test will still fail?

Also, `numpy-1.21` is known to be numerically less accurate than numpy-1.19, so for all CI/CD that is currently run we are sticking to it

**Comment by malfet** [comment]
And can't repro the failure on my Mac using 1.11 repease, by running the following command:
```
(py_39) nshulga@nshulga-mbp test % python -c "import torch;print(torch.__version__)";python test_torch.py -v -k test_corrcoef_cpu_complex64
1.11.0
Fail to import hypothesis in common_utils, tests are not derandomized
test_corrcoef_cpu_complex64 (__main__.TestTorchDeviceTypeCPU) ... /Users/nshulga/git/pytorch-release/test/test_torch.py:1743: UserWarning: cov(): degrees of freedom is <= 0 (Triggered internally at  /Users/distiller/project/conda/conda-bld/pytorch_1646756029501/work/aten/src/ATen/native/Correlation.cpp:99.)
  res = torch.corrcoef(x)
/Users/nshulga/miniconda3/envs/py_39/lib/python3.9/site-packages/numpy/lib/function_base.py:380: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/Users/nshulga/miniconda3/envs/py_39/lib/python3.9/site-packages/numpy/core/_methods.py:181: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(
/Users/nshulga/miniconda3/envs/py_39/lib/python3.9/site-packages/numpy/lib/function_base.py:2683: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/Users/nshulga/miniconda3/envs/py_39/lib/python3.9/site-packages/numpy/lib/function_base.py:2542: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
/Users/nshulga/miniconda3/envs/py_39/lib/python3.9/site-packages/numpy/lib/function_base.py:2542: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
ok

----------------------------------------------------------------------
Ran 1 test in 0.019s

OK
```

**Comment by dizcza** [comment]
@malfet the issue happens *only* when I build pytorch from sources with the Dockerfile I've shown. I've indeed tested the abusing tests with pytorch installed from anaconda channel (CPU only) and saw no issues. So it's not surprising that the tests pass on your Mac unless you've built pytorch from sources.
As a matter of fact, I did try running the tests inside a cuda-enabled docker container - see the original [Dockerfile](https://github.com/dizcza/pytorch-sm30-docker/blob/master/Dockerfile) where I first found out about the failed tests. Same issue.

I cannot install numpy-1.19 because it's not available for python 3.9 I'm running.

```
$ conda install numpy==1.19.1

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - numpy==1.19.1 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0
  - numpy==1.19.1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.27
```

And I cannot run `conda uninstall numpy && pip install numpy==1.19.1` because of
```
$ python -c "import torch;print(torch.__version__)";python test_torch.py -v -k test_corrcoef_cpu_complex64
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/opt/conda/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/opt/conda/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory
python: can't open file '/root/test_torch.py': [Errno 2] No such file or directory
root@cd5e3f7880cb:~# ls   
collect_env.py
root@cd5e3f7880cb:~# cd /opt/pytorch/pytorch-v1.11.0/test/
root@cd5e3f7880cb:/opt/pytorch/pytorch-v1.11.0/test# python -c "import torch;print(torch.__version__)";python test_torch.py -v -k test_corrcoef_cpu_complex64
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/opt/conda/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/opt/conda/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/pytorch/pytorch-v1.11.0/test/test_torch.py", line 4, in <module>
    import torch
  File "/opt/conda/lib/python3.9/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/opt/conda/lib/python3.9/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/opt/conda/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory
```

IMHO, python 3.7 is old and will reach the end of life in a year.
