### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

### ISSUE THREAD

**Issue by kaofang38573** [pytorch/pytorch#74232]
### 🐛 Describe the bug

Help me, after the train is complete, I get an error, what should I do?

![image](https://user-images.githubusercontent.com/58837369/158334234-f6f9d889-5ef8-434f-916d-cf96325fd6ac.png)

Python   3.9.9
torch      1.11.0+cu113
torchvision    0.12.0+cu113
cuda        11.5.0
cudnn      8.3.2.44

Error:
Exception ignored in: <function StorageWeakRef.__del__ at 0x000002D0C3DFDCA0>
Traceback (most recent call last):
  File "C:\Users\kuy50\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\multiprocessing\reductions.py", line 36, in __del__
  File "C:\Users\kuy50\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

**Help!!!!**

**Comment by H-Huang** [comment]
Hi, do you have a code snippet which can reproduce this error? It may be helpful to post that on the PyTorch forum (https://discuss.pytorch.org/) and get help there.
