### ISSUE TITLE
 init_process_group constructor hangs when using gloo

### ISSUE THREAD

**Issue by Asciotti** [pytorch/pytorch#74316]
### 🐛 Describe the bug

I am having trouble getting mulit-node, multi-gpu training established. I have tried a variety of methods and setups (because there are a bunch of examples/tutorials that conflict with each other). I'm actually not sure which setup I should provide as a reproducible example because I don't even know what _is_ the correct methodology.

I have looked at the following guides/tutorials:
* [This](https://pytorch.org/docs/master/elastic/run.html#fault-tolerant-fixed-sized-number-of-workers-no-elasticity-tolerates-3-failures) dist.run example on how to invoke these calls
* [This](https://github.com/pytorch/pytorch/issues/65992#issuecomment-953930352) comment for someone trying to figure out what `MASTER_ADDR/PORT` does, and the comment seems to contradict with what I have experienced (the master_addr/port does actually matter)
* [This](https://github.com/pytorch/pytorch/issues/52916) other pytorch issue, but it is about nccl and I cannot even get past the `gloo` backend setup. 

I'll provide my most successful example and its outcome:
Essentially what I am doing is setting the `rdvz` backend to point to one open port on node1 (`29500`), and the master process to point to the other open port on node1 (`29501`)

node 1
```
import io
import os
import pprint
import sys
import torch.distributed as dist
from datetime import timedelta
import torch.distributed as dist

if __name__ == "__main__":
    os.environ["MASTER_PORT"]="29501"
    dist.init_process_group(backend="gloo")
    dist.barrier()
```
node 2
```
import io
import os
import pprint
import sys
from datetime import timedelta
import torch.distributed as dist


if __name__ == "__main__":
    os.environ["MASTER_ADDR"] = "<eth0 interface ip of node 1>"
    os.environ["MASTER_PORT"] = "29501"
    dist.init_process_group(backend="gloo")
    dist.barrier()
```

Func call on node 1: `python -m torch.distributed.run --nnodes=2 --nproc_per_node 1 --max_restarts 0 --node_rank 0 --rdzv_id 1 --rdzv_backend=c10d --rdzv_endpoint="localhost:29500" blah2.py`

Func call on node2: `python -m torch.distributed.run --nnodes=2 --nproc_per_node 1 --max_restarts 0 --node_rank 1 --rdzv_id 1 --rdzv_backend=c10d --rdzv_endpoint="<ip_of_node1>:29500" blah.py`

Log inside: [misc.log](https://github.com/pytorch/pytorch/files/8267553/misc.log)

Some other things I have tried, in no special order:
* Do not set MASTER_PORT -> results in the `run` module attempting to make processes on misc ports, i only have 29501 connected
* Set `--master_port` in the CLI, does absolutely nothing, `MASTER_PORT` in the env gets set to a random port
* Remove the rdzv setup and just use master_port/master_addr, the process does not even appear to attempt to connect together
* Manually make the TCPStore and feed that into the `init_process_group` (with rank and world_size set), this makes the TCPStore but the init still just hangs.

Some additional information:
* I am running this on a kubernetes cluster, each on their own pod, networked together with a service (+ miscellaneous things) such that the ports `29500` and `29501` are reachable on both ends.
* I can `nc -l -p 2950{0,1}` and connect via `echo hi | nc <ip_of_node1> 2950{0,1}` on the other machine.
* I am able to manually setup a `TCPStore` between the two nodes via `dist.TCPStore(ip, port, 2, {True,False}, timedelta(seconds=30))`, with the ip/port set accordingly

### Versions

PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.26

Python version: 3.7.5 (default, Feb 23 2021, 13:22:40)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-4.14.238-182.422.amzn2.x86_64-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4

Nvidia driver version: 470.57.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.11.0
[conda] Could not collect

**Comment by Asciotti** [comment]
I tried the follow  #74146 issue as well, using gloo rather than nccl. I set `init_method='tcp://localhost:29501'` on the "host" and `init_method='tcp://<ip_of_host>:29501'` on the non-host. I get the following errors, same python setup.

Host error:
```
python another.py 0
[W socket.cpp:401] [c10d] The server socket cannot be initialized on [::]:29501 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [localhost]:29501 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [localhost]:29501 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [localhost]:29501 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [localhost]:29501 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [localhost]:29501 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [localhost]:29501 (errno: 97 - Address family not supported by protocol).
Traceback (most recent call last):
  File "another.py", line 7, in <module>
    dist.init_process_group(backend=backend, rank=rank,init_method='tcp://localhost:29501',  world_size=2,timeout=datetime.timedelta(seconds=15))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 610, in init_process_group
    timeout=timeout,
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 703, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.h:324] Connect timeout [10.106.152.156]:38318
```
Non-host error:
```
python another.py 1
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [node-1-ddp-node-1-akazgbhmuk]:29501 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [node-1-ddp-node-1-akazgbhmuk]:29501 (errno: 97 - Address family not supported by protocol).
Traceback (most recent call last):
  File "another.py", line 7, in <module>
    dist.init_process_group(backend=backend, rank=rank,init_method='tcp://10.106.111.224:29501',  world_size=2,timeout=datetime.timedelta(seconds=15))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 627, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 258, in _store_based_barrier
    rank, store_key, world_size, worker_count, timeout
RuntimeError: Timed out initializing process group in store based barrier on rank: 1, for key: store_based_barrier_key:1 (world_size=2, worker_count=1, timeout=0:00:15)

```

On the host, I see `Connect timeout [10.106.152.156]:38318` which implies there is a connection attempting to occur to the non-host over a random port (10.106.152.156 is the non-host ip).


**How many ports do I need available between these machines and can I limit them/specify them?**

**Comment by Asciotti** [comment]
Big edit on both, apparently on kubernetes I have full routing between pretty much any arbitrary port, so I have access to much more than `29500` and `29501` which makes my errors even more confusing.

**Comment by Asciotti** [comment]
I have to be honest, I have no idea what I did, but I am able to get past the `init_process_group` stage at least, so I will close in favor of another set of debugging on how to make it past moving a model into the `DDP` constructor.

For what it is worth
```
import os
import torch.distributed as dist
import datetime
import sys
dist.init_process_group(backend="nccl")
print(f"[ {os.getpid()} ] world_size = {dist.get_world_size()}, " + f"rank = {dist.get_rank()}, backend={dist.get_backend()}")
```

with
```
python -m torch.distributed.run --nnodes=2 --node_rank=0 --nproc_per_node 1 --max_restarts 0 --master_addr="<ip_of_node1>" --master_port=12345 ddp.py
```

seemed to do the trick. I did not need a `rdvz` set, nor any env vars set in my script (which you see frequently throughout various guides).
