### ISSUE TITLE
SystemError: <class 'UserWarning'> returned a result with an error set  

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#74334]
### 🐛 Describe the bug

Sometimes when running tests involving `__torch_dispatch__` I get this:

```
The above exception was the direct cause of the following exception:                      
                                                                                          
Traceback (most recent call last):                                                        
  File "/data/users/ezyang/subclass_zoo/aten2torch.py", line 88, in test_against_cpu      
    res = op.op(*args, **kwargs)                                                          
  File "/data/users/ezyang/subclass_zoo/python_meta_tensor.py", line 90, in __torch_dispatch__                                                                                      
    return super().__torch_dispatch__(func, types, args, kwargs)                          
SystemError: <class 'UserWarning'> returned a result with an error set  
```

This shouldn't happen.

I don't have a clear repro as running the test individually doesn't have this problem.

### Versions

master

cc @albanD @zou3519

**Comment by ezyang** [comment]
relevant bt

```
#0  __cxxabiv1::__cxa_throw (obj=0x555557efa8c0, 
    tinfo=0x7fffe227af90 <typeinfo for python_error>, 
    dest=0x7fffe1b03080 <python_error::~python_error()>)
    at /home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/.build/x86_64-conda-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:80
#1  0x00007fffe1c16b3d in torch::PyWarningHandler::~PyWarningHandler() ()
   from /data/users/ezyang/pytorch-tmp/torch/lib/libtorch_python.so
#2  0x00007fffe1f5a99c in THPModule_disable_torch_dispatch(_object*, _object*) ()
   from /data/users/ezyang/pytorch-tmp/torch/lib/libtorch_python.so
#3  0x00005555556c8738 in cfunction_call (func=0x7fffe91f8450, args=<optimized out>, 
    kwargs=<optimized out>)
    at /tmp/build/80754af9/python-split_1631797238431/work/Objects/methodobject.c:552
#4  0x00005555556989ef in _PyObject_MakeTpCall (tstate=0x555555912f80, 
    callable=0x7fffe91f8450, args=<optimized out>, nargs=<optimized out>, 
    keywords=<optimized out>)

```

**Comment by ezyang** [comment]
figured it out. phew, what a terrible situation haha
