### ISSUE TITLE
torch.package unpickling transforms: ModuleNotFoundError: No module named 'torch._C._linalg'; 'torch._C' is not a package

### ISSUE THREAD

**Issue by dasturge** [pytorch/pytorch#74389]
### 🐛 Describe the bug

I was writing some tests for my model and transform packaging code to deploy both the model and preprocessing at once...

As an example preprocessing transform, I chose `torch.linalg.vector_norm`, but apparently this give issues.  For example, I don't get this error if I use `torch.sin`

```
from functools import partial
import torch
import torch.nn as nn
from torch import package

model = nn.Sequential(
        nn.Linear(10, 10),
        nn.ReLU(),
        nn.Linear(10, 1),
        nn.Sigmoid(),
)
transform = partial(torch.linalg.vector_norm, dim=1)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
with open("./model_package.pt", "wb") as fd:
        with package.PackageExporter(fd) as pe:
            pe.intern(["surgical_modeling.transforms.**"])
            pe.extern(["torch"])
            pe.save_pickle("model", "model.pkl", model)
            pe.save_pickle("transform", "transform.pkl", transform)
            pe.save_pickle("optimizer", "optimizer.pkl", optimizer)

importer = torch.package.PackageImporter("./model_package.pt")
print(importer.depen)
loaded_model = importer.load_pickle("model", "model.pkl")
loaded_transform = importer.load_pickle("transform", "transform.pkl")
loaded_optimizer = importer.load_pickle("optimizer", "optimizer.pkl")
```

on importing the transform module, I get:
```
Traceback (most recent call last):
  File "/home/user/projects/test_cookiecutter/./scratch.py", line 24, in <module>
    loaded_transform = importer.load_pickle("transform", "transform.pkl")
  File "/home/user/anaconda3/envs/testrepo/lib/python3.9/site-packages/torch/package/package_importer.py", line 254, in load_pickle
    result = unpickler.load()
  File "/home/user/anaconda3/envs/testrepo/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/user/anaconda3/envs/testrepo/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/home/user/anaconda3/envs/testrepo/lib/python3.9/site-packages/torch/package/_package_unpickler.py", line 25, in find_class
    mod = self._importer.import_module(module)
  File "/home/user/anaconda3/envs/testrepo/lib/python3.9/site-packages/torch/package/package_importer.py", line 132, in import_module
    return self._gcd_import(name)
  File "/home/user/anaconda3/envs/testrepo/lib/python3.9/site-packages/torch/package/package_importer.py", line 443, in _gcd_import
    return self._find_and_load(name)
  File "/home/user/anaconda3/envs/testrepo/lib/python3.9/site-packages/torch/package/package_importer.py", line 413, in _find_and_load
    return self._do_find_and_load(name)
  File "/home/user/anaconda3/envs/testrepo/lib/python3.9/site-packages/torch/package/package_importer.py", line 401, in _do_find_and_load
    raise ModuleNotFoundError(msg, name=name) from None
ModuleNotFoundError: No module named 'torch._C._linalg'; 'torch._C' is not a package
```

I tried printing the importer extern_modules as well: `['torch.nn.modules.container', 'collections', 'builtins', 'torch.nn.modules.linear', 'torch._utils', 'torch', 'torch.nn.modules.activation', 'torch._C._linalg', 'torch.optim.adam']`

I also tried removing the `functools.partial` wrapper but that didn't change anything.

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-104-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro RTX 4000 with Max-Q Design
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-ignite==0.4.8
[pip3] pytorchvideo==0.1.5
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89             h8f6ccaa_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] ignite                    0.4.8                      py_0    pytorch
[conda] mkl                       2021.4.0           h8d4b97c_729    conda-forge
[conda] mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pytorch                   1.11.0          py3.9_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorchvideo              0.1.5                    pypi_0    pypi
[conda] torchvision               0.12.0               py39_cu102    pytorch

**Comment by Lezcano** [comment]
@malfet is this caused by the dynamic loading of the library?

**Comment by malfet** [comment]
@Lezcano looking, but unlikely, as this change is not picked into 1.11

**Comment by IvanYashchuk** [comment]
This problem is not specific to the linear algebra module, but for any module registered as `python_module: name` in `native_functions.yaml`.
For example using `transform = torch.fft.fft` would give
```py
ModuleNotFoundError: No module named 'torch._C._fft'; 'torch._C' is not a package
```
or `transform = torch._C._nn.linear` would give
```py
ModuleNotFoundError: No module named 'torch._C._nn'; 'torch._C' is not a package
```
