### ISSUE TITLE
Module parameterlist attr script error

### ISSUE THREAD

**Issue by wukong1992** [pytorch/pytorch#74404]
### 🐛 Describe the bug

when script module which has parameterlist attr, will cause bug.

``` Source code
import torch
from torch import nn

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.module_list = nn.ModuleList([nn.Linear(1,1) for _ in range(10)])
        self.parameter_list = nn.ParameterList([nn.Parameter(torch.zeros(1)) for _ in range(10)])
    def forward(self, x):
        for m in self.module_list:
            x = m(x)
        return x


if __name__ == '__main__':
    model = MyModule()
    optimize = True
    with torch.jit.optimized_execution(optimize):
      a = torch.jit.script(model, 2)
```

``` Error message
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Traceback (most recent call last):
  File "test.py", line 36, in <module>
    a = torch.jit.script(model, 2)
  File "/home/mi/work/pytorch/torch/jit/_script.py", line 1267, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/home/mi/work/pytorch/torch/jit/_recursive.py", line 454, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/mi/work/pytorch/torch/jit/_recursive.py", line 516, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/mi/work/pytorch/torch/jit/_script.py", line 594, in _construct
    init_fn(script_module)
  File "/home/mi/work/pytorch/torch/jit/_recursive.py", line 494, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/mi/work/pytorch/torch/jit/_recursive.py", line 466, in create_script_module_impl
    method_stubs = stubs_fn(nn_module)
  File "/home/mi/work/pytorch/torch/jit/_recursive.py", line 705, in infer_methods_to_compile
    item = getattr(nn_module, name, None)
TypeError: getattr(): attribute name must be string
```

This bug may be caused by this commit [https://github.com/pytorch/pytorch/pull/70499](url).  I can fix this bug if possible. @albanD 

### Versions

master

**Comment by davidberard98** [comment]
@wukong1992 if you have a fix that would be great!

**Comment by wukong1992** [comment]
[https://github.com/pytorch/pytorch/pull/74997](url)

**Comment by davidberard98** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/74997, thanks @wukong1992
