### ISSUE TITLE
can not build pytorch, failing due to missing _ctypes module

### ISSUE THREAD

**Issue by gggh000** [pytorch/pytorch#74421]
### 🐛 Describe the bug

[root@centos pytorch]# !123
python setup.py build --cmake-only
Traceback (most recent call last):
  File "setup.py", line 219, in <module>
Traceback (most recent call last):
  File "setup.py", line 219, in <module>
    from setuptools import setup, Extension, find_packages
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/usr/local/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

### Versions

python --version
Python 3.8.12
uname -r
4.18.0-365.el8.x86_64

cc @malfet @seemethere

**Comment by taras-janea** [comment]
This issue is being closed as it can no longer be reproduced with the latest PyTorch version. 
If you continue to experience this problem or have related concerns, please feel free to open a new issue.
