### ISSUE TITLE
kron has unnecessary and undocumented dependence on memory layout

### ISSUE THREAD

**Issue by kylematoba** [pytorch/pytorch#74442]
### 🐛 Describe the bug

`torch.kron` depends on the memory layout in a totally unnecessary way. 

```
import torch
import numpy as np
if __name__ == "__main__":
    a = torch.rand(8, 4)
    b = torch.rand(12, 8)
    c = torch.kron(b.T, a)
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 1, in Exec
    def Exec(exp, global_vars, local_vars=None):
  File "<string>", line 2, in <module>
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```
The error is wholly unhelpful as well. Indeed, I could not figure out how to make this work short of instantiating a whole new tensor:

```
    bt = torch.empty(8, 12)
    for i in range(8):
        for j in range(12):
            bt[i, j] = b[j, i]

    c2 = torch.kron(bt, a)
    c_np = np.kron(b.T.numpy(), a.numpy())
    np.testing.assert_allclose(c2.numpy(), c_np)
```

### Versions

Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.2.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.11)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10)  [Clang 6.0 (clang-600.0.57)] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.750
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] Could not collect

**Comment by toshas** [comment]
Moreover, calling `contiguous()` directly on arguments does not help either. Below is my way of discovering the issue:
`torch.kron(torch.eye(2), torch.randn(2,1))` - works
`torch.kron(torch.eye(2), torch.randn(2,2).svd().U[:, :1])` - error
`torch.kron(torch.eye(2), torch.randn(2,2).svd().U[:, :1].contiguous())` - error
`torch.kron(torch.eye(2), torch.randn(2,2).svd().U.contiguous()[:, :1])` - works

**Comment by toshas** [comment]
A workaround for matrices:
```
def kron(A, B):
    return (A[:, None, :, None] * B[None, :, None, :]).reshape(A.shape[0] * B.shape[0], A.shape[1] * B.shape[1])
```

**Comment by ianmtaylor1** [comment]
As of July 2024, Torch version 2.3.1+cu121, this appears to still be an issue. Thanks for your workaround for matrices, @toshas. I've extended it to work with n-dimensional tensors, treating them as batches of matrices:

```
import torch

def matrixkron(A: torch.Tensor, B: torch.Tensor):
    """Performs the Kronecker product between two tensors only in their last
    two dimensions, rather than doing the product in all dimensions like
    torch.kron(). I.e., this treats the tensors like batches of matrices."""
    batch_shape = torch.broadcast_shapes(A.shape[:-2], B.shape[:-2])
    result_shape = (A.shape[-2] * B.shape[-2], A.shape[-1] * B.shape[-1])
    return (A.unsqueeze(-1).unsqueeze(-3) * B.unsqueeze(-2).unsqueeze(-4)).reshape(*batch_shape, *result_shape)

## Tests

torch.manual_seed(0)

a = torch.randn(3,5)
b = torch.randn(4,7)
c = matrixkron(a, b)

assert c.shape == torch.Size([12,35])
assert (c == torch.kron(a,b)).all()

x = torch.randn(2,1,2,3,5)
y = torch.randn(1,2,2,4,7)
z = matrixkron(x,y)

assert z.shape == torch.Size([2,2,2,12,35])
assert (z[0,0,0,:,:] == torch.kron(x[0,0,0,:,:], y[0,0,0,:,:])).all()
assert (z[0,0,1,:,:] == torch.kron(x[0,0,1,:,:], y[0,0,1,:,:])).all()
assert (z[0,1,0,:,:] == torch.kron(x[0,0,0,:,:], y[0,1,0,:,:])).all()
assert (z[0,1,1,:,:] == torch.kron(x[0,0,1,:,:], y[0,1,1,:,:])).all()
assert (z[1,0,0,:,:] == torch.kron(x[1,0,0,:,:], y[0,0,0,:,:])).all()
assert (z[1,0,1,:,:] == torch.kron(x[1,0,1,:,:], y[0,0,1,:,:])).all()
assert (z[1,1,0,:,:] == torch.kron(x[1,0,0,:,:], y[0,1,0,:,:])).all()
assert (z[1,1,1,:,:] == torch.kron(x[1,0,1,:,:], y[0,1,1,:,:])).all()
```
