### ISSUE TITLE
torch has no attribute sparse_csr_tensor

### ISSUE THREAD

**Issue by skye95git** [pytorch/pytorch#74454]
### 🐛 Describe the bug

code:
```python
          value = torch.ones(self.nnz(), dtype=dtype, device=self.device())
return torch.sparse_csr_tensor(rowptr, col, value, self.sizes())
```

error:
```
RuntimeError:
object has no attribute sparse_csr_tensor:
  File "/home/linjiayi/anaconda3/envs/graphormer/lib/python3.9/site-packages/torch_sparse/tensor.py", line 511
            value = torch.ones(self.nnz(), dtype=dtype, device=self.device())

        return torch.sparse_csr_tensor(rowptr, col, value, self.sizes())
               ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

### Versions

PyTorch version: 1.9.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: A100-SXM4-40GB
GPU 1: A100-SXM4-40GB
GPU 2: A100-SXM4-40GB
GPU 3: A100-SXM4-40GB
GPU 4: A100-SXM4-40GB
GPU 5: A100-SXM4-40GB
GPU 6: A100-SXM4-40GB
GPU 7: A100-SXM4-40GB

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.9.1+cu111
[pip3] torch-geometric==1.7.2
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torchaudio==0.9.1
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] torch                     1.9.1+cu111              pypi_0    pypi
[conda] torch-geometric           1.7.2                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-sparse              0.6.13                   pypi_0    pypi
[conda] torchaudio                0.9.1                    pypi_0    pypi

**Comment by skye95git** [comment]
> @skye95git - does this error persist on a most recent nightly?

Yes. I've tried this many times today, and it's always the same mistake

**Comment by cpuhrsch** [comment]
@skye95git 

I just tried reproducing it on a recent nightly and didn't get an error

```
>>> torch.__version__
'1.9.0.dev20210604+cu102'
>>> a = torch.randn(3, 4).to_sparse_csr()
>>> torch.sparse_csr_tensor(a.crow_indices(), a.col_indices(), a.values(), a.size())
tensor(crow_indices=tensor([ 0,  4,  8, 12]),
       col_indices=tensor([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]),
       values=tensor([-0.7893,  0.8407,  0.2799, -0.3178, -1.2889, -1.4795,
                      -0.7178,  1.3014,  0.1702,  0.1378,  0.8728, -0.0828]),
       size=(3, 4), nnz=12, layout=torch.sparse_csr)
```

Maybe it helps if you provide a more extensive snippet (e.g. including definitions of `rowptr` and `col` etc.?

**Comment by skye95git** [comment]
@cpuhrsch I run the same example as yours and still get an error.

```
>>> import torch
>>> torch.__version__
'1.9.1+cu111'
>>> a = torch.randn(3, 4).to_sparse_csr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Tensor' object has no attribute 'to_sparse_csr'
```

**Comment by kangleXU** [comment]
ｅｘｃｕｓｅ　ｍｅ！ｈｏｗ　ｔｏ　ｓｌｏｖｅ　ｔｈｉｓ　ｐｒｏｂｌｅｍ？　ｉ　ｎｅｅｄ　ｉｔ．　ｃｏｕｌｄ　ｙｏｕ　ｈｅｌｐ　ｍｅ？

**Comment by kangleXU** [comment]
Python 3.7.0 (default, Oct  9 2018, 10:31:47)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.9.0+cu102'
>>> a = torch.randn(3, 4).to_sparse_csr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Tensor' object has no attribute 'to_sparse_csr'
>>> torch.__version__
'1.9.0+cu102'
>>> a = torch.randn(3, 4).to_sparse_csr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Tensor' object has no attribute 'to_sparse_csr'
>>> a = torch.randn(3, 4).to_sparse_csr()

**Comment by kangleXU** [comment]
> @skye95git
> 
> I just tried reproducing it on a recent nightly and didn't get an error
> 
> ```
> >>> torch.__version__
> '1.9.0.dev20210604+cu102'
> >>> a = torch.randn(3, 4).to_sparse_csr()
> >>> torch.sparse_csr_tensor(a.crow_indices(), a.col_indices(), a.values(), a.size())
> tensor(crow_indices=tensor([ 0,  4,  8, 12]),
>        col_indices=tensor([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]),
>        values=tensor([-0.7893,  0.8407,  0.2799, -0.3178, -1.2889, -1.4795,
>                       -0.7178,  1.3014,  0.1702,  0.1378,  0.8728, -0.0828]),
>        size=(3, 4), nnz=12, layout=torch.sparse_csr)
> ```
> 
> Maybe it helps if you provide a more extensive snippet (e.g. including definitions of `rowptr` and `col` etc.?

Can you share your installation environment

**Comment by cpuhrsch** [comment]
@kangleXU - I installed the recent stable version of PyTorch. You can find instructions for this on https://pytorch.org/get-started/locally/

```
>>> torch.__version__
'1.11.0'
>>> a = torch.randn(3, 4).to_sparse_csr()
>>> torch.sparse_csr_tensor(a.crow_indices(), a.col_indices(), a.values(), a.size())
tensor(crow_indices=tensor([ 0,  4,  8, 12]),
       col_indices=tensor([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]),
       values=tensor([-0.8291,  1.6009,  0.8343,  0.7980, -0.0774,  0.7816,
                      -0.8296,  1.3544, -0.6268,  0.5696,  3.7306, -0.2450]),
       size=(3, 4), nnz=12, layout=torch.sparse_csr)
```

@skye95git @kangleXU - you need to upgrade your version of PyTorch. See the instructions on https://pytorch.org/get-started/locally/

**Comment by skye95git** [comment]
>  you need to upgrade your version of PyTorch. See the instructions on https://pytorch.org/get-started/locally/

@cpuhrsch  In your first example, Pytorch1.9.0 also worked:  

> I just tried reproducing it and didn't get an error

>>> torch.__version__
'1.9.0.dev20210604+cu102'
>>> a = torch.randn(3, 4).to_sparse_csr()
>>> torch.sparse_csr_tensor(a.crow_indices(), a.col_indices(), a.values(), a.size())
tensor(crow_indices=tensor([ 0,  4,  8, 12]),
       col_indices=tensor([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]),
       values=tensor([-0.7893,  0.8407,  0.2799, -0.3178, -1.2889, -1.4795,
                      -0.7178,  1.3014,  0.1702,  0.1378,  0.8728, -0.0828]),
       size=(3, 4), nnz=12, layout=torch.sparse_csr)

But Pytorch1.9.1 did not work in my environment. Need to update PyTorch to 1.11.0?

**Comment by cpuhrsch** [comment]
@skye95git - it's worth a try. What prevents you from updating?

**Comment by kangleXU** [comment]
@cpuhrsch --Thank you very much!   I made it  Need to update PyTorch to 1.11.0

**Comment by lucky6qi** [comment]
so if pytorch version is 1.9x would need torch-sparse==0.6.12
torch-sparse==0.6.13 The minimum PyTorch version required is now indeed PyTorch 1.10.0
https://github.com/rusty1s/pytorch_sparse/issues/207

**Comment by cpuhrsch** [comment]
@lucky6qi - Out of curiosity, what prevents you from upgrading to 1.11.0?

**Comment by skye95git** [comment]
> @skye95git - it's worth a try. What prevents you from updating?

Thanks. I update PyTorch to 1.11.0. It works.

**Comment by JayKumarr** [comment]
> so if pytorch version is 1.9x would need torch-sparse==0.6.12 torch-sparse==0.6.13 The minimum PyTorch version required is now indeed PyTorch 1.10.0 [rusty1s/pytorch_sparse#207](https://github.com/rusty1s/pytorch_sparse/issues/207)
> 
> another way around is to downgrade torch-sparse

Worked for me. I am sharing the commands from scratch on anaconda
```
conda create --name py376 python=3.7.6 --channel conda-forge
conda activate py376
pip install torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
python -c "import torch; print(torch.__version__)"
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.9.0+cu102.html
pip install torch-sparse==0.6.12 -f https://data.pyg.org/whl/torch-1.9.0+cu102.html
```

**Comment by LannyCodes** [comment]
> > > @skye95git - it's worth a try. What prevents you from updating?
> > 
> > 
> > Thanks. I update PyTorch to 1.11.0. It works.
> 
> ## My torch is 1.11.0,and torch-sparse is 0.6.17,but it still persisted.Who can help me please？
> ## torch 1.11.0
> torch-cluster 1.6.1
> torch-geometric 2.1.0
> torch-scatter 2.1.1
> torch-sparse 0.6.17
> torch-spline-conv 1.2.2
> RuntimeError: object has no attribute sparse_csc_tensor: File "/Users/pro/.conda/envs/AIGlasses/lib/python3.7/site-packages/torch_sparse/tensor.py", line 520 value = torch.ones(self.nnz(), dtype=dtype, device=self.device())
> 
> ```
>     return torch.sparse_csc_tensor(colptr, row, value, self.sizes())
>            ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
> ```

Oh my gods! I downlgrade the torch-sparse's vertion to  0.6.14,  taking it  Solved! 
Thinking my  persistence.

**Comment by roccomoretti** [comment]
I can also confirm that downgrading from torch-sparse 0.6.17 to 0.6.14 fixed the issue for me.

**Comment by ccbond** [comment]
> I can also confirm that downgrading from torch-sparse 0.6.17 to 0.6.14 fixed the issue for me.

It alse works for me. TKS

**Comment by zhongxiang117** [comment]
Just a report, I  faced the same issue, my packages info are:

```
pytorch               1.11.0        cuda102py38hfdb21e3_202   conda-forge
torchvision           0.12.0        cuda102py38h6ac7867_1     conda-forge
cudatoolkit           10.2.89       hdec6ad0_12               conda-forge

torch-cluster         1.6.1         pypi_0                    pypi
torch-geometric       2.3.0         pypi_0                    pypi
torch-scatter         2.1.1         pypi_0                    pypi
torch-sparse          0.6.14        pypi_0                    pypi  # <- changed! initial is 0.6.17
torch-spline-conv     1.2.2         pypi_0                    pypi

tensorboard           2.14.0       pyhd8ed1ab_0               conda-forge
```

Besides, I can also confirm that, this error is caused by the after installation of `tensorboard` package from `conda`.

By the way, I maintain packages mostly by `conda`, else by `pip` mostly due to older version `torch_geometric` seemingly prefers to using it.

**Comment by bettyteng21** [comment]
> I can also confirm that downgrading from torch-sparse 0.6.17 to 0.6.14 fixed the issue for me.

worked for me too. thank you a lot!
