### ISSUE TITLE
Installing conda package from pytorch-nighly fails with `libcupti.so.X.Y` not found

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#74473]
### 🐛 Describe the bug

Attempts to run
```
$ conda create -n py_3.7-torch-nightly -c pytorch-nightly cudatoolkit==11.3.1 pytorch python==3.7
$ conda run -n py_3.7-torch-nightly python -c "import torch"
```
will fail with 
```
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '-c', 'import torch']' command failed.  (See above for error)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/fsx/users/nshulga/conda/envs/py_3.7-torch-nightly/lib/python3.7/site-packages/torch/__init__.py", line 199, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.11.3: cannot open shared object file: No such file or directory
```

For more details see https://github.com/pytorch/vision/issues/5635

### Versions

nightly

cc @ezyang @gchanan @zou3519 @malfet @seemethere @ngimel

**Comment by gchanan** [comment]
not a problem with released version.

**Comment by seemethere** [comment]
Adding the [1.12.0](https://github.com/pytorch/pytorch/milestone/28) milestone since we need to fix this prior to the 1.12.0 release

**Comment by malfet** [comment]
Removing high priority, @atalman can you please make sure to add test to prevent those regressions from happening in the future?

**Comment by galipremsagar** [comment]
We seem to be running into this issue with `conda-forge` version of `pytorch` too, for example with the latest release:
```python
_________________________________________________________________________ ERROR collecting cudf/tests/test_subword_tokenizer.py _________________________________________________________________________
ImportError while importing test module '/nvme/0/pgali/cudf/python/cudf/cudf/tests/test_subword_tokenizer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../envs/cudfdev/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
python/cudf/cudf/tests/test_subword_tokenizer.py:7: in <module>
    from transformers import BertTokenizer
../envs/cudfdev/lib/python3.9/site-packages/transformers/file_utils.py:2026: in __getattr__
    module = self._get_module(self._class_to_module[name])
../envs/cudfdev/lib/python3.9/site-packages/transformers/file_utils.py:2035: in _get_module
    return importlib.import_module("." + module_name, self.__name__)
../envs/cudfdev/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../envs/cudfdev/lib/python3.9/site-packages/transformers/models/__init__.py:19: in <module>
    from . import (
../envs/cudfdev/lib/python3.9/site-packages/transformers/models/layoutlm/__init__.py:22: in <module>
    from .configuration_layoutlm import LAYOUTLM_PRETRAINED_CONFIG_ARCHIVE_MAP, LayoutLMConfig
../envs/cudfdev/lib/python3.9/site-packages/transformers/models/layoutlm/configuration_layoutlm.py:19: in <module>
    from ..bert.configuration_bert import BertConfig
../envs/cudfdev/lib/python3.9/site-packages/transformers/models/bert/configuration_bert.py:21: in <module>
    from ...onnx import OnnxConfig
../envs/cudfdev/lib/python3.9/site-packages/transformers/onnx/__init__.py:17: in <module>
    from .convert import export, validate_model_outputs
../envs/cudfdev/lib/python3.9/site-packages/transformers/onnx/convert.py:23: in <module>
    from .. import PreTrainedModel, PreTrainedTokenizer, TensorType, TFPreTrainedModel, is_torch_available
../envs/cudfdev/lib/python3.9/site-packages/transformers/file_utils.py:2026: in __getattr__
    module = self._get_module(self._class_to_module[name])
../envs/cudfdev/lib/python3.9/site-packages/transformers/file_utils.py:2035: in _get_module
    return importlib.import_module("." + module_name, self.__name__)
../envs/cudfdev/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../envs/cudfdev/lib/python3.9/site-packages/transformers/modeling_utils.py:25: in <module>
    import torch
../envs/cudfdev/lib/python3.9/site-packages/torch/__init__.py:202: in <module>
    from torch._C import *  # noqa: F403
E   ImportError: libcupti.so.11.2: cannot open shared object file: No such file or directory
======================================================================================== short test summary info ========================================================================================
ERROR python/cudf/cudf/tests/test_subword_tokenizer.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================================================== 1 error in 0.44s ============================================================================================
(cudfdev) pgali@dt07:/nvme/0/pgali/cudf$ conda list | grep "torch"
pytorch                   1.12.0          cuda112py39ha0cca9b_200    conda-forge
(cudfdev) pgali@dt07:/nvme/0/pgali/cudf$ conda list | grep "cuda"
arrow-cpp                 8.0.0           py39h2f48f8a_4_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
cuda-python               11.7.0           py39h3fd9d12_0    nvidia
cudatoolkit               11.5.1               hcf5317a_9    nvidia
dask-cuda                 22.08.00a220718         py39_28    rapidsai-nightly
librmm                    22.08.00a220718 cuda11_g7f7f9cb8_58    rapidsai-nightly
pyarrow                   8.0.0           py39h1ed2e5d_4_cuda    conda-forge
pytorch                   1.12.0          cuda112py39ha0cca9b_200    conda-forge
rmm                       22.08.00a220718 cuda11_py39_g7f7f9cb8_58    rapidsai-nightly

**Comment by malfet** [comment]
Alas, cupti is a weird library that does not guarantee forward compatibility. We can bundle one into PyTorch package (same as we do with cudnn)

Or link with it statically (I think there is an option for that already)

**Comment by atalman** [comment]
closing this issue since workflow for validation of binaries is implemented here:https://github.com/pytorch/pytorch/issues/82725
