### ISSUE TITLE
Making PyTorch more pythonic:  the PyTorch functions should be inspectable.

### ISSUE THREAD

**Issue by abdulmuneer** [pytorch/pytorch#74539]
### 🚀 The feature, motivation and pitch

I am working on translating an intermediate specification pytorch code.  To map the parameters, I need to inspect the signature of the pytorch functions (e.g. `torch.empty` or `torch.nn.functional.conv2d`) and find out the parameter it is expecting.

But, the usual pythonic way of inspecting a python function with `inspect` does not work with PyTorch.  It results in an exception.

```python
>>> import inspect
>>> import torch
>>> inspect.signature(torch.empty)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda/envs/gc/lib/python3.8/inspect.py", line 3105, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/home/anaconda/envs/gc/lib/python3.8/inspect.py", line 2854, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/home/anaconda/envs/gc/lib/python3.8/inspect.py", line 2308, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "/home/anaconda/envs/gc/lib/python3.8/inspect.py", line 2119, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in method empty of type object at 0x7f382e1321c0>
```
A prerequisite for such inspect-ability is the `__code__` attribute. 
```python
>>> torch.empty.__code__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'builtin_function_or_method' object has no attribute '__code__'
```
Can PyTorch functions be made to carry the `__code__` attribute?

**Comment by matteosantama** [comment]
+1 this would be helpful for me as well. I was surprised to see `inspect.signature` is not supported
