### ISSUE TITLE
torch.jit.Attribute does not work as advertised

### ISSUE THREAD

**Issue by alanhdu** [pytorch/pytorch#74626]
### 🐛 Describe the bug

Currently, the [docs](https://pytorch.org/docs/stable/generated/torch.jit.Attribute.html) say that `torch.jit.Attribute` is a pass-through function with no effect in eager evaluation mode. Unfortunately, this does not seem to be the case -- if I try to run the code linked in the example:

```python
import torch
from typing import Dict

class AttributeModule(torch.nn.Module):
    def __init__(self):
        super(torch.nn.Module, self).__init__()
        self.foo = torch.jit.Attribute(0.1, float)

        # we should be able to use self.foo as a float here
        assert 0.0 < self.foo

        self.names_ages = torch.jit.Attribute({}, Dict[str, int])
        self.names_ages["someone"] = 20
        assert isinstance(self.names_ages["someone"], int)

m = AttributeModule()
```

I get the following error:

```python
Traceback (most recent call last):
  File "repro.py", line 16, in <module>
    a = AttributeModule()
  File "repro.py", line 10, in __init__
    assert 0.0 < self.foo
TypeError: '<' not supported between instances of 'float' and 'Attribute'
```

I'm not sure if this is an implementation error or a documentation error about how to use `torch.jit.Attribute`.

### Versions

```
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Fedora release 34 (Thirty Four) (x86_64)
GCC version: (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Clang version: 12.0.1 (Fedora 12.0.1-1.fc34)
CMake version: Could not collect
Libc version: glibc-2.33

Python version: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:53:36)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.18-100.fc34.x86_64-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[conda] blas                      2.16                        mkl    conda-forge
[conda] cpuonly                   2.0                           0    pytorch
[conda] libblas                   3.8.0                    16_mkl    conda-forge
[conda] libcblas                  3.8.0                    16_mkl    conda-forge
[conda] liblapack                 3.8.0                    16_mkl    conda-forge
[conda] liblapacke                3.8.0                    16_mkl    conda-forge
[conda] mkl                       2020.2                      256  
[conda] numpy                     1.22.3           py38h05e7239_0    conda-forge
[conda] pytorch                   1.11.0              py3.8_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
```

**Comment by davidberard98** [comment]
Docs fixed in https://github.com/pytorch/pytorch/pull/74653. Thanks for the report @alanhdu !
