### ISSUE TITLE
Can't install Pytorch

### ISSUE THREAD

**Issue by mjack3** [pytorch/pytorch#74670]
### 🐛 Describe the bug

I can't install either torch and torchvision.

Commands:
```
pip cache purge
pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113
```
throws next error
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/jack3-tkh/TKH/02_AD - Anomaly Detection/codes/FastFlow_models/FastFlow-AD/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/jack3-tkh/TKH/02_AD - Anomaly Detection/codes/FastFlow_models/FastFlow-AD/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/jack3-tkh/TKH/02_AD - Anomaly Detection/codes/FastFlow_models/FastFlow-AD/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 405, in run
    installed = install_given_reqs(
  File "/home/jack3-tkh/TKH/02_AD - Anomaly Detection/codes/FastFlow_models/FastFlow-AD/venv/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/home/jack3-tkh/TKH/02_AD - Anomaly Detection/codes/FastFlow_models/FastFlow-AD/venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 769, in install
    install_wheel(
  File "/home/jack3-tkh/TKH/02_AD - Anomaly Detection/codes/FastFlow_models/FastFlow-AD/venv/lib/python3.8/site-packages/pip/_internal/operations/install/wheel.py", line 729, in install_wheel
    _install_wheel(
  File "/home/jack3-tkh/TKH/02_AD - Anomaly Detection/codes/FastFlow_models/FastFlow-AD/venv/lib/python3.8/site-packages/pip/_internal/operations/install/wheel.py", line 589, in _install_wheel
    file.save()
  File "/home/jack3-tkh/TKH/02_AD - Anomaly Detection/codes/FastFlow_models/FastFlow-AD/venv/lib/python3.8/site-packages/pip/_internal/operations/install/wheel.py", line 390, in save
    shutil.copyfileobj(f, dest)
  File "/usr/lib/python3.8/shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "/usr/lib/python3.8/zipfile.py", line 940, in read
    data = self._read1(n)
  File "/usr/lib/python3.8/zipfile.py", line 1030, in _read1
    self._update_crc(data)
  File "/usr/lib/python3.8/zipfile.py", line 958, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/libtorch_cuda_cpp.so'
```

### Versions

using pip 22.0.4

**Comment by mjack3** [comment]
I did and still I'm unable to install it property. Just the version CUDA 10.2 (which is not supported in my RTX 3090) :'(

![image](https://user-images.githubusercontent.com/37028633/161215967-9515ad4d-672d-43c4-83b7-d7e4455c9d86.png)

**Comment by seemethere** [comment]
Can't reproduce in my local environment,

```
❯ docker run --rm -it python:3.8 sh -c 'pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113'
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Collecting torch
  Downloading https://download.pytorch.org/whl/torch-1.11.0-cp38-cp38-manylinux2014_aarch64.whl (50.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 MB 21.5 MB/s eta 0:00:00
Collecting torchvision
  Downloading https://download.pytorch.org/whl/torchvision-0.12.0-cp38-cp38-manylinux2014_aarch64.whl (13.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.7/13.7 MB 17.9 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting requests
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 7.6 MB/s eta 0:00:00
Collecting pillow!=8.3.*,>=5.3.0
  Downloading Pillow-9.1.0.tar.gz (49.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.8/49.8 MB 16.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy
  Downloading numpy-1.22.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 17.3 MB/s eta 0:00:00
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.2/149.2 KB 17.1 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 KB 8.9 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 KB 20.6 MB/s eta 0:00:00
Building wheels for collected packages: pillow
  Building wheel for pillow (setup.py) ... done
  Created wheel for pillow: filename=Pillow-9.1.0-cp38-cp38-linux_aarch64.whl size=1326836 sha256=2582ae6db8e0cf2bc33bd0dd78463b9b9a4d36149bf734108a7e140a5c14f0a0
  Stored in directory: /root/.cache/pip/wheels/a0/1f/f5/32e276d3f528f40b9f4b2cb28d0472b279b2d32c7772e18cdc
Successfully built pillow
Installing collected packages: certifi, urllib3, typing-extensions, pillow, numpy, idna, charset-normalizer, torch, requests, torchvision
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.12 idna-3.3 numpy-1.22.3 pillow-9.1.0 requests-2.27.1 torch-1.11.0 torchvision-0.12.0 typing-extensions-4.1.1 urllib3-1.26.9
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

Can you give us some more info on your environment? Like what OS are you running, python version, etc.

**Comment by seemethere** [comment]
Seems similar to https://github.com/pytorch/pytorch/issues/40268
