### ISSUE TITLE
test linux-docs / build-docs (python) is broken

### ISSUE THREAD

**Issue by b0noI** [pytorch/pytorch#74684]
### 🐛 Describe the bug

CI test linux-docs / build-docs (python)  is currently broken:

```
Traceback (most recent call last):
  File "/opt/conda/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/opt/conda/lib/python3.7/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/opt/conda/lib/python3.7/site-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/opt/conda/lib/python3.7/site-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/opt/conda/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/opt/conda/lib/python3.7/site-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/opt/conda/lib/python3.7/site-packages/jinja2/__init__.py)
```

failure: https://github.com/pytorch/pytorch/runs/5678126229?check_suite_focus=true#step:7:1152

### Versions

master

**Comment by b0noI** [comment]
looks like not related to changes, original PR is green: https://github.com/pytorch/pytorch/runs/5668908812?check_suite_focus=true

however same commit is red on master, most likely dependencies that are not pined: https://github.com/pytorch/pytorch/runs/5678126229?check_suite_focus=true#step:7:1152

**Comment by malfet** [comment]
Both Python and CPP docs are broken at the moment
