### ISSUE TITLE
DISABLED test_batch_norm (__main__.TestTEFuserDynamic)

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#74747]
This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_batch_norm%2C%20TestTEFuserDynamic)).

Error:
```
2022-03-25T07:42:24.7198126Z ======================================================================
2022-03-25T07:42:24.7198528Z ERROR [0.681s]: test_batch_norm (__main__.TestTEFuserDynamic)
2022-03-25T07:42:24.7199409Z ----------------------------------------------------------------------
2022-03-25T07:42:24.7199805Z Traceback (most recent call last):
2022-03-25T07:42:24.7200945Z   File "test_jit_fuser_te.py", line 113, in tearDown
2022-03-25T07:42:24.7201457Z     super().tearDown()
2022-03-25T07:42:24.7202262Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/jit_utils.py", line 154, in tearDown
2022-03-25T07:42:24.7202757Z     clear_class_registry()
2022-03-25T07:42:24.7204028Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/jit_utils.py", line 60, in clear_class_registry
2022-03-25T07:42:24.7204704Z     torch._C._jit_clear_class_registry()
2022-03-25T07:42:24.7205638Z RuntimeError: it != dict_.end() INTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h":230, please report a bug to PyTorch. 
2022-03-25T07:42:24.7206093Z 
2022-03-25T07:42:24.7206920Z ======================================================================
2022-03-25T07:42:24.7207467Z ERROR [0.264s]: test_batch_norm (__main__.TestTEFuserStatic)
2022-03-25T07:42:24.7208203Z ----------------------------------------------------------------------
2022-03-25T07:42:24.7208593Z Traceback (most recent call last):
2022-03-25T07:42:24.7209731Z   File "test_jit_fuser_te.py", line 113, in tearDown
2022-03-25T07:42:24.7210233Z     super().tearDown()
2022-03-25T07:42:24.7210973Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/jit_utils.py", line 154, in tearDown
2022-03-25T07:42:24.7211412Z     clear_class_registry()
2022-03-25T07:42:24.7212741Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/jit_utils.py", line 60, in clear_class_registry
2022-03-25T07:42:24.7213387Z     torch._C._jit_clear_class_registry()
2022-03-25T07:42:24.7214154Z RuntimeError: it != dict_.end() INTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h":230, please report a bug to PyTorch. 
2022-03-25T07:42:24.7214574Z 
```

**Comment by davidberard98** [comment]
seems like 3b3bdfd51cab8697c35622526ee5ec2c189cfbab fixed it?
