### ISSUE TITLE
Missing `libcudnn.so.8` in pytorch-nightly build using conda

### ISSUE THREAD

**Issue by wat3rBro** [pytorch/pytorch#74779]
### 🐛 Describe the bug

I encountered the following issue when importing the torch:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ngtceya5/setup.py", line 10, in <module>
        import torch
      File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/torch/__init__.py", line 199, in <module>
        _load_global_deps()
      File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/torch/__init__.py", line 152, in _load_global_deps
        ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
      File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/ctypes/__init__.py", line 373, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libcudnn.so.8: cannot open shared object file: No such file or directory
```
The issue happens during installing Detectron2 and right after installing the pytorch-nightly.
```
conda install pytorch torchvision -c pytorch-nightly
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
```
The above command did work on Mar 23 but failed since Mar 24. After comparing the difference between the logs during conda install, I found that seems that on Mar 23, it uses cudnn8.2.0 (full log: https://github.com/facebookresearch/d2go/runs/5671458969)
```
    pytorch-1.12.0.dev20220323 |py3.8_cuda11.3_cudnn8.2.0_0        1.01 GB  pytorch-nightly
```
while starting from Mar 24, it uses cudnn8.3.2 (full log: https://github.com/facebookresearch/d2go/runs/5685109701)
```
    pytorch-1.12.0.dev20220324 |py3.8_cuda11.3_cudnn8.3.2_0       583.8 MB  pytorch-nightly
```
with significant smaller size, therefore I think this might be related to cuda/cudnn version.

From https://anaconda.org/pytorch/pytorch/files, it seems that cudnn8.3.2 is combined with cuda11.5, but not cuda11.3 (default/latest cuda version for conda).

### Versions

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 11.0.0-2~ubuntu20.04.1
CMake version: version 3.22.2
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-10[28](https://github.com/facebookresearch/d2go/runs/5697151401?check_suite_focus=true#step:5:28)-azure-x86_64-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] Could not collect
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @seemethere @malfet @csarofeen @ptrblck @xwang233 @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
cc: @ptrblck @atalman I think it is likely caused by https://github.com/pytorch/builder/commit/e1876ec56245f5187dcf27dfe17dc884db261779

**Comment by malfet** [comment]
Reverting the change and re-kicking nightly builds
