### ISSUE TITLE
[ONNX] Failed to export aten::flatten of input with unknown rank

### ISSUE THREAD

**Issue by timurlenk07** [pytorch/pytorch#74800]
### 🐛 Describe the bug

When `torch.Tensor.flatten` is called within a list comprehension, ONNX export fails. Based on the warnings emitted during conversion, this is most likely the result of missing shape inference information.

Code to reproduce:
```python
from pathlib import Path
from typing import List

import torch
print(torch.__version__)

x1 = (torch.randn(1, 10, 60, 80), )
x2 = ([torch.randn(1, 10, 60, 80), torch.randn(1, 10, 30, 40), torch.randn(1, 10, 15, 20)], )

def test1(outs: torch.Tensor) -> torch.Tensor:
    return outs.flatten(start_dim=2)

def test2(outs: List[torch.Tensor]) -> List[torch.Tensor]:
    return [x.flatten(start_dim=2) for x in outs]

test1 = torch.jit.script(test1)
test1(*x1)
print(type(test1))
torch.onnx.export(test1, x1, Path('sth.onnx'),
                  opset_version=15)

test2 = torch.jit.script(test2)
test2(*x2)
print(type(test2))
torch.onnx.export(test2, x2, Path('sth.onnx'),
                  opset_version=15)
```

Output:
```
1.11.0+cu115
<class 'torch.jit.ScriptFunction'>
/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py:359: UserWarning: Model has no forward function
  warnings.warn("Model has no forward function")
/home/.../env/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:719: UserWarning: allowzero=0 by default. In order to honor zero value in shape use allowzero=1
  warnings.warn("allowzero=0 by default. In order to honor zero value in shape use allowzero=1")
Finished exporting test1
<class 'torch.jit.ScriptFunction'>
/home/.../env/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:258: UserWarning: ONNX export failed on dim because ONNX and PyTorch use different strategies to split the input. Input rank must be known at export time. not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
WARNING: The shape inference of aten::flatten type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of aten::flatten type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Traceback (most recent call last):
  File "/home/.../random_test.py", line 25, in <module>
    torch.onnx.export(test2, x2, Path('sth.onnx'),
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py", line 738, in _export
    proto, export_map, val_use_external_data_format = graph._export_onnx(
RuntimeError: ONNX export failed: Couldn't export operator aten::flatten

Defined at:
  File "/home/.../random_test.py", line 14
def test2(outs: List[torch.Tensor]) -> List[torch.Tensor]:
    return [x.flatten(start_dim=2) for x in outs]
            ~~~~~~~~~ <--- HERE


Graph we tried to export:
graph(%outs.1 : Tensor[]):
  %1 : Long(device=cpu) = onnx::Constant[value={-1}]()
  %onnx::Loop_2 : Bool(device=cpu) = onnx::Constant[value={1}]()
  %3 : Long(device=cpu) = onnx::Constant[value={2}]()
  %onnx::Loop_4 : FloatTensor(device=cpu)[] = onnx::SequenceEmpty()
  %onnx::Loop_5 : Long(device=cpu) = onnx::SequenceLength(%outs.1) # /home/.../random_test.py:14:11
  %6 : Tensor[] = onnx::Loop(%onnx::Loop_5, %onnx::Loop_2, %onnx::Loop_4) # /home/.../random_test.py:14:11
    block0(%7 : Long(device=cpu), %cond : Bool(device=cpu), %9 : FloatTensor(device=cpu)[]):
      %x : Tensor = onnx::SequenceAt(%outs.1, %7) # /home/.../random_test.py:14:11
      %11 : Tensor = aten::flatten(%x, %3, %1) # /home/.../random_test.py:14:12
      %12 : Tensor[] = onnx::SequenceInsert(%9, %11) # /home/.../random_test.py:14:11
      %13 : Bool(device=cpu) = onnx::Identity(%onnx::Loop_2)
      -> (%13, %12)
  return (%6)
```

### Versions

```
PyTorch version: 1.11.0+cu115
Is debug build: False
CUDA used to build PyTorch: 11.5
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-44-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.5.50
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000

Nvidia driver version: 495.46
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] botorch==0.6.0
[pip3] gpytorch==1.6.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.4
[pip3] pytorch-lightning==1.5.9
[pip3] torch==1.11.0+cu115
[pip3] torchaudio==0.11.0+cu115
[pip3] torchmetrics==0.7.1
[pip3] torchvision==0.12.0+cu115
[conda] Could not collect
```

**Comment by garymm** [comment]
Currently the rank of the input to flatten must be known at export time:
https://github.com/pytorch/pytorch/blob/0ae3aa648e0d997af4d5c092a6ad7a06c8f65798/torch/onnx/symbolic_opset11.py#L825-L828

The code as written could have a different tensor rank for every iteration of the loop, so there's no way to determine the shape.

I'm not sure if the existing requirement of knowing the input rank is actually necessary, just noting that's the proximate cause.

**Comment by AllenTiTaiWang** [comment]
Hi @timurlenk07 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team

**Comment by un-certainty** [comment]
Hi @garymm

I encounter a similar issue when exporting a ScriptModule to ONNX. I have a tensor whose second dimension increases over each loop. But that dimension is never involved in the transpose op. And running `torch.onnx.export` will raise `SymbolicValueError: Unsupported: ONNX export of transpose for the tensor of unknown rank`, which is similar to [#50686](https://github.com/pytorch/pytorch/issues/50686).

I am on `torch==1.13.1`, but the nightly version has become 2.x, which I am not able to use. Any solution to this problem?

**Comment by titaiwangms** [comment]
@un-certainty Could you raise a new issue with a minimal reproduction code ?

**Comment by fernandorovai** [comment]
I'm facing the same issue while trying to convert a multi scale deform attention via scripting.

sampling_value_list = []
    for level, (H_, W_) in enumerate(value_spatial_shapes):
        value_l_ = (value_list[level].flatten(2).transpose(1, 2).reshape(bs * num_heads, embed_dims, H_, W_))       
        **sampling_grid_l_ = sampling_grids[:, :, :, level].transpose(1, 2).flatten(0, 1)** <---- Error

**Comment by SuperKenVery** [comment]
For anyone coming here confused, I found that you could actually tell ONNX the rank of a tensor if you really know it (but ONNX failed to infer):
```python
assert x.shape==(B*C, 4, H, W) # for example
y=x[:, 0, :, :] # ONNX will know the shape (and rank) and allow this
```

Reshape also works:
```python
x=x.reshape(B*C, 4, H, W)
y=x[:, 0, :, :] # ONNX will know the shape (and rank) and allow this
```
