### ISSUE TITLE
BytesWarning causes exception in torch.load() when running Python with -bb flag

### ISSUE THREAD

**Issue by aphedges** [pytorch/pytorch#74812]
### 🐛 Describe the bug

When running Python with the [`-bb`](https://docs.python.org/3.10/using/cmdline.html#cmdoption-b) option, loading a model with `torch.load()` fails with a `BytesWarning`:

```console
$ python -bb -c 'import torch; torch.save(1, "test.pkl"); torch.load("test.pkl")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ahedges/projects/personal/pytorch/torch/serialization.py", line 700, in load
    if _is_zipfile(opened_file):
  File "/Users/ahedges/projects/personal/pytorch/torch/serialization.py", line 59, in _is_zipfile
    while byte != "":
BytesWarning: Comparison between bytes and string
```

This flag is useful to catch additional errors during testing, and I discovered this while working on a project that uses PyTorch. Fixing it here will make it easier to test other projects for errors, as well as reduce the chance for a similar bug in PyTorch.

I will be releasing a PR shortly.

### Versions

PyTorch version: 1.12.0a0+git5375b2e
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.6.5 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.3
Libc version: N/A

Python version: 3.7.13 (default, Mar 17 2022, 14:15:44) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: Darwin-20.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.12.0a0+git5375b2e
[conda] Could not collect

cc @mruberry

**Comment by aphedges** [comment]
This should be re-opened because the fix was reverted after slow tests failed on trunk: <https://github.com/pytorch/pytorch/pull/74813#issuecomment-1159353429>.
