### ISSUE TITLE
C10d Elastic Training master_addr ERROR

### ISSUE THREAD

**Issue by tingshua-yts** [pytorch/pytorch#74824]
### 🐛 Describe the bug

# Describe the bug
I want to train a 2 node 4GPU Elastic training JOB

the training script as below
```python
import argparse
import os
import sys
import time
import tempfile
from urllib.parse import urlparse

import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim

from torch.nn.parallel import DistributedDataParallel as DDP

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))

def train():
    local_rank = int(os.environ["LOCAL_RANK"])
    rank = int(os.environ["RANK"])
    print(f"[{os.getpid()}] (rank = {rank}, local_rank = {local_rank}) training...")
    model = ToyModel().cuda(local_rank)
    ddp_model = DDP(model, [local_rank])

    loss_fn = nn.MSELoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)
    epoch = 100
    for i in range(epoch):
        time.sleep(1)
        optimizer.zero_grad()
        outputs = ddp_model(torch.randn(20, 10).to(local_rank))
        labels = torch.randn(20, 5).to(local_rank)
        loss = loss_fn(outputs, labels)
        loss.backward()
        print(f"[{os.getpid()}] epoch {i} (rank = {rank}, local_rank = {local_rank}) loss = {loss.item()}\n")
        optimizer.step()

def run():
    env_dict = {
        key: os.environ[key]
        for key in ("MASTER_ADDR", "MASTER_PORT", "WORLD_SIZE", "LOCAL_WORLD_SIZE")
    }
    print(f"[{os.getpid()}] Initializing process group with: {env_dict}")

    dist.init_process_group(backend="nccl")
    train()
    dist.destroy_process_group()


if __name__ == "__main__":
    run()
```
the start job script as below:
```shell
export MASTER_ADDR="192.168.9.104"
export MASTER_PORT="1234"
export LOGLEVEL="DEBUG"
torchrun \
    --nnodes=1:3\
    --nproc_per_node=2\
    --max_restarts=3\
    --rdzv_id=1\
    --rdzv_backend=c10d\
    --rdzv_endpoint="192.168.9.104:1234"\
    --master_addr="192.168.9.104" \
    --master_port=1234 \
    train_elastic.py
```
ERROR INFO:
```shell
root@iZ2zefk3g6rwyhrmh35s3jZ:/workspace/DDP# sh run_elastic.sh
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further t
une the variable for optimal performance in your application as needed.
*****************************************
[435] Initializing process group with: {'MASTER_ADDR': 'iZ2ze9q3ftqtxtqlkrk6tuZ', 'MASTER_PORT': '43007', 'WORLD_SIZE': '4', 'LOCAL_WORLD
_SIZE': '2'}
[434] Initializing process group with: {'MASTER_ADDR': 'iZ2ze9q3ftqtxtqlkrk6tuZ', 'MASTER_PORT': '43007', 'WORLD_SIZE': '4', 'LOCAL_WORLD
_SIZE': '2'}
[W socket.cpp:558] [c10d] The IPv6 network addresses of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007) cannot be retrieved (gai error: -2 - Name or ser
vice not known).
[W socket.cpp:558] [c10d] The IPv4 network addresses of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007) cannot be retrieved (gai error: -2 - Name or ser
vice not known).
[E socket.cpp:610] [c10d] The client socket has failed to connect to any network address of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007).
Traceback (most recent call last):
  File "train_elastic.py", line 58, in <module>
[W socket.cpp:558] [c10d] The IPv6 network addresses of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007) cannot be retrieved (gai error: -2 - Name or ser
vice not known).
[W socket.cpp:558] [c10d] The IPv4 network addresses of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007) cannot be retrieved (gai error: -2 - Name or ser
vice not known).
[E socket.cpp:610] [c10d] The client socket has failed to connect to any network address of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007).
    run()
Traceback (most recent call last):
  File "train_elastic.py", line 52, in run
  File "train_elastic.py", line 58, in <module>
    dist.init_process_group(backend="nccl")
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    run()
  File "train_elastic.py", line 52, in run
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 232, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 160, in _create_c10d_store
    return TCPStore(
RuntimeError: The client socket has failed to connect to any network address of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007). The IPv6 network addres
ses of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007) cannot be retrieved (gai error: -2 - Name or service not known). The IPv4 network addresses of (i
Z2ze9q3ftqtxtqlkrk6tuZ, 43007) cannot be retrieved (gai error: -2 - Name or service not known).
    dist.init_process_group(backend="nccl")
```

I have read the pytorch source code, I found when backend is not 'static'，agent will use hostname for the MASTER_ADDR. But in my situation , the hostname can not resolve, I want use the IP. 
```python
def _get_addr_and_port(
    rdzv_parameters: RendezvousParameters,
) -> Tuple[Optional[str], Optional[int]]:
    if rdzv_parameters.backend != "static":
        return (None, None)
    endpoint = rdzv_parameters.endpoint
    endpoint = endpoint.strip()
    if not endpoint:
        raise ValueError(
            "Endpoint is missing in endpoint. Try to add --master_addr and --master_port"
        )
    master_addr, master_port = parse_rendezvous_endpoint(endpoint, default_port=-1)
    if master_port == -1:
        raise ValueError(
            f"port is missing in endpoint: {endpoint}. Try to specify --master_port"
        )
    return (master_addr, master_port)
...
    @staticmethod
    def _set_master_addr_port(
        store: Store, master_addr: Optional[str], master_port: Optional[int]
    ):
        if master_port is None:
            sock = _get_socket_with_port()
            with closing(sock):
                master_port = sock.getsockname()[1]

        if master_addr is None:
            master_addr = _get_fq_hostname()

        store.set("MASTER_ADDR", master_addr.encode(encoding="UTF-8"))
        store.set("MASTER_PORT", str(master_port).encode(encoding="UTF-8"))
```

How can I set MASTER_ADDR ? is it a bug?

### Versions

pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

**Comment by H-Huang** [comment]
For some reason, MASTER_ADDR is not being set correctly under `elastic/agent/server/api.py`, The IP address is being encoded but not decoded? Looping in Pytorch R2P team to investigate

**Comment by pornosaur** [comment]
Any solution?

**Comment by CeadeS** [comment]
Any solution

**Comment by Elec-coder** [comment]
I  encountered the same problem.

**Comment by CeadeS** [comment]
can you printenv HOSTNAME? Is it maybe a local hostname with the name of a docker container? Then you could start the script with HOSTNAME="YOURHOSTNAME"  torchrun ...

**Comment by hchoi-moveworks** [comment]
I encountered the same problem. Is there a solution to this issue?

**Comment by hchoi-moveworks** [comment]
> If this runs in a docker container, you could run it with --network=host. I had the problem because the internal hostname was not recognized by another container that was supposed to connect to the host. Fixing the hostname problem leads to a problem with the internal IP addresses. So I fixed that by starting the containers with the --network=host option.

@CeadeS using `bridge network` for docker container, I was also able to `ping` the other docker container but somehow initializing distributed process group still failed with logs 

```
[W socket.cpp:558] [c10d] The IPv6 network addresses of <container id> cannot be retrieved (gai error: -2 - Name or service not known).
```

**Comment by harubaru** [comment]
I'm encountering a similar issue as well:
``[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-6G21RPU]:29500 (system error: 10049 - The requested address is not valid in its context.).``

**Comment by cailun01** [comment]
A temporary and ugly workaround: hook `SimpleElasticAgent._set_master_addr_port`.

```py
# hook.py
import os
from torch.distributed.elastic.agent.server.api import (
    SimpleElasticAgent, 
    _get_socket_with_port, 
    _get_fq_hostname
)
from contextlib import closing


def _hook_set_master_addr_port(store, master_addr, master_port):
    if master_port is None:
        sock = _get_socket_with_port()
        with closing(sock):
            master_port = sock.getsockname()[1]

        if master_addr is None:
            hostname = _get_fq_hostname()
            # use IP address as master_addr
            master_addr = socket.gethostbyname(hostname)

    store.set("MASTER_ADDR", master_addr.encode(encoding="UTF-8"))
    store.set("MASTER_PORT", str(master_port).encode(encoding="UTF-8"))


setattr(SimpleElasticAgent, "_set_master_addr_port", staticmethod(_hook_set_master_addr_port))
```

**Comment by Alldebrid** [comment]
@cailun01 How to use it please ? how to run train.py after lunch this

**Comment by gitabtion** [comment]
I encountered the same problem. Is there a solution to this issue?

**Comment by lonelyzyp** [comment]
> I'm encountering a similar issue as well: `[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-6G21RPU]:29500 (system error: 10049 - The requested address is not valid in its context.).`

hi!Any solution?

**Comment by rubenschff** [comment]
someone solve this problem? 

`[W C:\b\abs_bao0hdcrdh\croot\pytorch_1675190257512\work\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - O endereþo solicitado nÒo Ú vßlido no contexto.).`

**Comment by lonelyzyp** [comment]
这是来自QQ邮箱的自动回复邮件。你好：      你的来信我已收到，我会尽快回复你。      祝一切顺利！Thank you for your mail.I will reponse to your mail as soon as possible.       Yours sincerely

**Comment by xiaoxiawu-microsoft** [comment]
did we figure this out? how to solve it and how to use the python code?
https://github.com/pytorch/pytorch/issues/74824#issuecomment-1232905723

**Comment by OvJat** [comment]
edit /etc/hosts would solve this problem.

I have two nodes: A1(192.168.1.10), A2(192.168.1.11).

update all the nodes' /etc/hosts:

192.168.1.10 A1
192.168.1.11  A2

**Comment by deJQK** [comment]
Hi @OvJat , how do you update all nodes' file? Is there any demo shell or python script for this purpose? Thanks!

**Comment by OvJat** [comment]
> Hi @OvJat , how do you update all nodes' file? Is there any demo shell or python script for this purpose? Thanks!

@deJQK use rsync:

```bash
#!/bin/bash

NODE_LIST=(A1 A2 A3 A4)
for node in "${NODE_LIST}";do
    echo $node
    rsync -avm local_file_path $node:remote_file_path
done
```

**Comment by xylcbd** [comment]
```
[434] Initializing process group with: {'MASTER_ADDR': 'iZ2ze9q3ftqtxtqlkrk6tuZ', 'MASTER_PORT': '43007', 'WORLD_SIZE': '4', 'LOCAL_WORLD
_SIZE': '2'}
[W socket.cpp:558] [c10d] The IPv6 network addresses of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007) cannot be retrieved (gai error: -2 - Name or ser
vice not known).
[W socket.cpp:558] [c10d] The IPv4 network addresses of (iZ2ze9q3ftqtxtqlkrk6tuZ, 43007) cannot be retrieved (gai error: -2 - Name or ser
vice not known).
```

It can be resolved by add "192.168.9.104 iZ2ze9q3ftqtxtqlkrk6tuZ" to /etc/hosts.

**Comment by xiawei20161308104** [comment]
> 

I have the same mistake as you. Have you resolved it？

**Comment by lonelyzyp** [comment]
这是来自QQ邮箱的自动回复邮件。你好：      你的来信我已收到，我会尽快回复你。      祝一切顺利！Thank you for your mail.I will reponse to your mail as soon as possible.       Yours sincerely

**Comment by xiawei20161308104** [comment]
> someone solve this problem?
> 
> `[W C:\b\abs_bao0hdcrdh\croot\pytorch_1675190257512\work\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - O endereþo solicitado nÒo Ú vßlido no contexto.).`

I have the same mistake as you. Have you resolved it？

**Comment by SuperBruceJia** [comment]
> 这是来自QQ邮箱的自动回复邮件。你好：      你的来信我已收到，我会尽快回复你。      祝一切顺利！Thank you for your mail.I will reponse to your mail as soon as possible.       Yours sincerely

What if we don't have sudo access to add it?

**Comment by lonelyzyp** [comment]
这是来自QQ邮箱的自动回复邮件。你好：      你的来信我已收到，我会尽快回复你。      祝一切顺利！Thank you for your mail.I will reponse to your mail as soon as possible.       Yours sincerely

**Comment by lonelyzyp** [comment]
这是来自QQ邮箱的自动回复邮件。你好：      你的来信我已收到，我会尽快回复你。      祝一切顺利！Thank you for your mail.I will reponse to your mail as soon as possible.       Yours sincerely

**Comment by lonngxiang** [comment]
> export MASTER_ADDR="192.168.9.104"

not work for me

![image](https://github.com/pytorch/pytorch/assets/40717349/88d26ed5-108b-49cc-9ad1-d19b16fe9b53)

**Comment by shinytang6** [comment]
For python 2.x.x, l noticed that func `_set_master_addr_port ` is changed to
```
@staticmethod
    def _set_master_addr_port(
        store: Store,
        master_addr: Optional[str],
        master_port: Optional[int],
        local_addr: Optional[str],
    ):
        if master_port is None:
            sock = _get_socket_with_port()
            with closing(sock):
                master_port = sock.getsockname()[1]

        if master_addr is None:
            # If user specified the address for the local node, use it as the master addr if not exist
            if local_addr:
                master_addr = local_addr
            else:
                master_addr = _get_fq_hostname()
```

l tried to set command args `torchrun --local_addr $POD_NAME --xxx` or env `PET_LOCAL_ADDR=POD_NAME`, both ways can resolve this issue.

**Comment by lonelyzyp** [comment]
这是来自QQ邮箱的自动回复邮件。你好：      你的来信我已收到，我会尽快回复你。      祝一切顺利！Thank you for your mail.I will reponse to your mail as soon as possible.       Yours sincerely
