### ISSUE TITLE
Multiprocessing runtime error freeze_support() in Windows 64 bit 

### ISSUE THREAD

**Issue by banibrata** [pytorch/pytorch#7485]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

When I run the examples of mnist  using python main.py as mentioned in the examples here:
(https://github.com/pytorch/examples/tree/master/mnist)
getting this error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Anaconda\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Anaconda\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Anaconda\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Anaconda\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Anaconda\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\banide\notebooks\examples-master\mnist\main.py", line 106, in <module>
    train(epoch)
  File "C:\Users\banide\notebooks\examples-master\mnist\main.py", line 75, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "C:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "C:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 239, in __init__
    w.start()
  File "C:\Anaconda\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Anaconda\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Anaconda\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows Server 2016 Datacenter
GCC version: Could not collect
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 386.07
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[pip3] numpydoc (0.7.0)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] cuda90                    1.0                           0    pytorch
[conda] pytorch                   0.4.0           py36_cuda90_cudnn7he774522_1  [cuda90]  pytorch
[conda] torchvision               0.2.1                     <pip>

**Comment by peterjc123** [comment]
Read the windows [doc](https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection) please.

**Comment by banibrata** [comment]
This has been open with the examples now, as the fix has to be in there.
https://github.com/pytorch/examples/issues/352

**Comment by MubarkLa** [comment]
> Read the windows [doc](https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection) please.

@peterjc123 

**Hello, thanks a lot for your reply.**
**I have carefully read that but still face the same problem.**
**Actually I am trying to run UCF101_CRNN.py of [https://github.com/HHTseng/video-classification/tree/master/CRNN](url), and I added these at the begining of UCF101_CRNN.py:**

*************************************************
def run():
    torch.multiprocessing.freeze_support()
    print('loop')

if __name__ == '__main__':
    run()
*************************************************


**But still face the same problem. Actually I am quite upset about this because I have tried a lot to fix this problem but still failed. Could you please kindly help me fix this?**
*******************************************************
C:\Anaconda3\envs\pytorch1\python.exe D:/LSTM/study/video-classification-master/CRNN/UCF101_CRNN.py
loop
C:\Anaconda3\envs\pytorch1\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Anaconda3\envs\pytorch1\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "D:/LSTM/study/video-classification-master/CRNN/UCF101_CRNN.py", line 218, in <module>
    exitcode = _main(fd)
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\spawn.py", line 114, in _main
    train_losses, train_scores = train(log_interval, [cnn_encoder, rnn_decoder], device, train_loader, optimizer, epoch)
  File "D:/LSTM/study/video-classification-master/CRNN/UCF101_CRNN.py", line 62, in train
    prepare(preparation_data)
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\spawn.py", line 225, in prepare
    for batch_idx, (X, y) in enumerate(train_loader):
  File "C:\Anaconda3\envs\pytorch1\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Anaconda3\envs\pytorch1\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    run_name="__mp_main__")
  File "C:\Anaconda3\envs\pytorch1\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Anaconda3\envs\pytorch1\lib\runpy.py", line 96, in _run_module_code
    w.start()
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\process.py", line 105, in start
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Anaconda3\envs\pytorch1\lib\runpy.py", line 85, in _run_code
    self._popen = self._Popen(self)
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\context.py", line 223, in _Popen
    exec(code, run_globals)
  File "D:\LSTM\study\video-classification-master\CRNN\UCF101_CRNN.py", line 218, in <module>
    train_losses, train_scores = train(log_interval, [cnn_encoder, rnn_decoder], device, train_loader, optimizer, epoch)
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\LSTM\study\video-classification-master\CRNN\UCF101_CRNN.py", line 62, in train
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\context.py", line 322, in _Popen
    for batch_idx, (X, y) in enumerate(train_loader):
  File "C:\Anaconda3\envs\pytorch1\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return Popen(process_obj)
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\reduction.py", line 60, in dump
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Anaconda3\envs\pytorch1\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
    w.start()
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Anaconda3\envs\pytorch1\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Process finished with exit code 1
*******************************************************

**Comment by peterjc123** [comment]
@MubarkLa No, actually it is not this note want you to do. It wants you to do sth like:
```python
# import modules as usual
import numpy as np

# functions should remain in the global scope
def func():
   pass

def main()
    # any clauses in the global scope (which doesn't have indention)
    data_path = "./jpegs_256/"    # define UCF-101 RGB data path
    action_name_path = './UCF101actions.pkl'
    save_model_path = "./CRNN_ckpt/"
    pass

if __name__ == '__main__':
    main()
```

**Comment by abdallahserag** [comment]
hello guys I try to run this code from GitHub
https://github.com/zllrunning/Deep-Steganography
on my windows 10 but I have error

F:\project\Deep-Steganography\Deep-Steganography>python main.py
main.py:16: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
init.kaiming_normal(m.weight.data, a=0, mode='fan_in')
F:\project\Deep-Steganography\Deep-Steganography\main.py:16: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
init.kaiming_normal(m.weight.data, a=0, mode='fan_in')
Traceback (most recent call last):
Traceback (most recent call last):
File "main.py", line 49, in 
File "", line 1, in 
for i, (secret, cover) in enumerate(dataloader): File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main

File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 193, in iter
exitcode = _main(fd)
File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 114, in _main
prepare(preparation_data)
File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
run_name="mp_main")
File "C:\Program Files\Python36\lib\runpy.py", line 263, in run_path
pkg_name=pkg_name, script_name=fname)
File "C:\Program Files\Python36\lib\runpy.py", line 96, in _run_module_code
mod_name, mod_spec, pkg_name, script_name)
File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "F:\project\Deep-Steganography\Deep-Steganography\main.py", line 49, in 
for i, (secret, cover) in enumerate(dataloader):
File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 193, in iter
return _DataLoaderIter(self)return _DataLoaderIter(self)

File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 469, in init
File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 469, in init
w.start()
File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 105, in start
w.start()
File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 105, in start
self._popen = self._Popen(self)self._popen = self._Popen(self)

File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 223, in _Popen
File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 322, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
return Popen(process_obj)
File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 322, in _Popen
File "C:\Program Files\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in init
return Popen(process_obj)
File "C:\Program Files\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in init
reduction.dump(process_obj, to_child)
prep_data = spawn.get_preparation_data(process_obj._name) File "C:\Program Files\Python36\lib\multiprocessing\reduction.py", line 60, in dump

File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
_check_not_importing_main()
File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
is not going to be frozen to produce an executable.''')
RuntimeError:
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.

    This probably means that you are not using fork to start your
    child processes and you have forgotten to use the proper idiom
    in the main module:

        if _name_ == '_main_':
            freeze_support()
            ...

    The "freeze_support()" line can be omitted if the program
    is not going to be frozen to produce an executable.
ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

please can any one help .....

**Comment by harsh-sprinklr** [comment]
def run():
    torch.multiprocessing.freeze_support()
    model = NERModel('bert','../Model-weights/best_model',use_cuda=False)
    sample = "show me films where jim carrey is a detective."
    predictions, _ = model.predict([sample])
    for idx, sample in enumerate([sample]):
      print('{}: '.format(idx))
      for word in predictions[idx]:
        print('{}'.format(word))

    print('loop')

if __name__ == '__main__':
    run()




This Worked for me

**Comment by zemenfes-afk** [comment]
i have this problem


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\zemen\PycharmProjects\zemen\zemenfes.py", line 7, in <module>
    backend = EQSNBackend()
  File "C:\Users\zemen\PycharmProjects\zemen\qunetsim\backends\eqsn_backend.py", line 123, in __init__
    self.eqsn = EQSN.get_instance()
  File "C:\Users\zemen\PycharmProjects\zemen\venv\lib\site-packages\eqsn\gates.py", line 23, in get_instance
    return EQSN()
  File "C:\Users\zemen\PycharmProjects\zemen\venv\lib\site-packages\eqsn\gates.py", line 30, in __init__
    self.manager = multiprocessing.Manager()
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\managers.py", line 579, in start
    self._process.start()
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\zemen\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by anilsh** [comment]
Following worked for me:

1.  Using spawn start method
   ```
 import torch.multiprocessing as mp
    mp.use_start_method('spawn', force=True) # force is essential as it was returning another error that context has already been set

```
2.  Use main function (`if __name__ == '__main__':`) at the very first line even before imports (many answers on stackoverflow show that start() and join() method should be in the main and it works well. But I guess I am using several scripts and modules so it is not identifying the proper main so I had to include it in the first line of first file).

**Comment by zemenfes-afk** [comment]
from qunetsim.components import Host, Network
from qunetsim.objects import Message, Qubit, Logger
from qunetsim.backends import EQSNBackend
Logger.DISABLED = True
import torch.multiprocessing as mp


# create the EQSN backend object
backend = EQSNBackend()


def protocol_1(host, receiver):
    # Here we write the protocol code for a host.
    for i in range(5):
        s = 'Hi {}.'.format(receiver)
        print("{} sends: {}".format(host.host_id, s))
        host.send_classical(receiver, s, await_ack=True)
    for i in range(5):
        q = Qubit(host)
        q.X()
        print("{} sends qubit in the |1> state".format(host.host_id))
        host.send_qubit(receiver, q, await_ack=True)


def protocol_2(host, sender):
    # Here we write the protocol code for another host.
    for i in range(5):
        sender_message = host.get_classical(sender, wait=5, seq_num=i)
        print("{} Received classical: {}".format(host.host_id, sender_message.content))
    for i in range(5):
        q = host.get_data_qubit(sender, wait=10)
        m = q.measure()
        print("{} measured: {}".format(host.host_id, m))


def main():
    network = Network.get_instance()
    nodes = ['e', 'B', 'r']
    network.generate_topology(nodes, 'mesh')
    network.start(nodes)

    host_e = network.get_host('e')
    host_b = network.get_host('B')
    host_r = network.get_host('r')

    t1 = host_e.run_protocol(protocol_1, (host_r.host_id,))
    t2 = host_r.run_protocol(protocol_2, (host_e.host_id,), blocking=True)
    network.stop(True)
if __name__ == '__main__':
    mp.use_start_method('spawn', force=True)
