### ISSUE TITLE
Gradient computation on modified tensor by in-place operator

### ISSUE THREAD

**Issue by speedcell4** [pytorch/pytorch#74874]
### 🐛 Describe the bug

Yes, I know I can simply `x + y + z`, but the following example is just a simplified script from a complex requirement.

I create an empty tensor without requiring gradients, copy the input to the corresponding positions, and then start to reduce them by putting the intermediate results on the next positions, e.g.,

```
x -> tensor[0]
y -> tensor[1]
z -> tensor[3]
tensor[0] + tensor[1] -> tensor[2]
tensor[2] + tensor[3] -> tensor[4]
```

Finally, the `tensor[4]` is returned as the final result. I found the following code works well if the reduction operator is `torch.add`, 

```python
import torch
from torch import Tensor


def reduce(x: Tensor, y: Tensor, z: Tensor, op) -> Tensor:
    tensor = torch.zeros((5,), dtype=torch.float32, requires_grad=False)
    tensor[0] = x
    tensor[1] = y
    tensor[3] = z

    tensor[2] = op(tensor[0], tensor[1])
    tensor[4] = op(tensor[2], tensor[3])
    return tensor[4]


with torch.autograd.set_detect_anomaly(True):
    inputs = [
        torch.randn((1,), requires_grad=True),
        torch.randn((1,), requires_grad=True),
        torch.randn((1,), requires_grad=True),
    ]

    out = reduce(*inputs, op=torch.add)
    grad = torch.autograd.grad(
        out, inputs, torch.randn_like(out),
    )
    print(f'grad => {grad}')
    # grad => (tensor([1.2525]), tensor([1.2525]), tensor([1.2525]))
```

but switching `op` to any of `torch.logaddexp`, `torch.mul`, or `torch.mul`, it yields an error on the gradient computation step,

```python
out = reduce(*inputs, op=torch.logaddexp)
out = reduce(*inputs, op=torch.max)
out = reduce(*inputs, op=torch.mul)
```

The error information is here,

```
python3.8/site-packages/torch/autograd/__init__.py:275: UserWarning: Error detected in MulBackward0. Traceback of forward call that caused the error:
  File "tensor.py", line 28, in <module>
    out = reduce(*inputs, op=torch.mul)
  File "tensor.py", line 17, in reduce
    tensor[4] = op(tensor[2], tensor[3])
 (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "tensor.py", line 29, in <module>
    grad = torch.autograd.grad(
  File "python3.8/site-packages/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor []], which is output 0 of AsStridedBackward0, is at version 5; expected version 4 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

But I found replacing the slicing operator, i.e., `tensor[2]` with advanced indexing `tensor[torch.tensor([2])]` can solve this.

```python
import torch
from torch import Tensor


def reduce(x: Tensor, y: Tensor, z: Tensor, op) -> Tensor:
    tensor = torch.zeros((5,), dtype=torch.float32, requires_grad=False)
    tensor[torch.tensor([0])] = x
    tensor[torch.tensor([1])] = y
    tensor[torch.tensor([3])] = z

    tensor[torch.tensor([2])] = op(tensor[torch.tensor([0])], tensor[torch.tensor([1])])
    tensor[torch.tensor([4])] = op(tensor[torch.tensor([2])], tensor[torch.tensor([3])])
    return tensor[torch.tensor([4])]


with torch.autograd.set_detect_anomaly(True):
    inputs = [
        torch.randn((1,), requires_grad=True),
        torch.randn((1,), requires_grad=True),
        torch.randn((1,), requires_grad=True),
    ]

    out = reduce(*inputs, op=torch.mul)
    grad = torch.autograd.grad(
        out, inputs, torch.randn_like(out),
    )
    print(f'grad => {grad}')
    # grad => (tensor([2.1379]), tensor([1.0593]), tensor([0.9451]))
```

So is it possible to apply the same mechanism on slicing? I suppose this is relevant to the `.version` of each tensor.

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 8.2.0
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] functorch==0.1.0
[pip3] numpy==1.22.2
[pip3] pytorch-crf==0.7.2
[pip3] torch==1.11.0
[pip3] torch-batch-svd==1.0.0
[pip3] torch-scatter==2.0.9
[pip3] torchaudio==0.9.0
[pip3] torchdevice==0.1.0
[pip3] torchglyph==0.3.2
[pip3] torchlatent==0.4.2
[pip3] torchrua==0.4.0
[pip3] torchvision==0.10.0
[conda] functorch                 0.1.0                    pypi_0    pypi
[conda] numpy                     1.22.2                   pypi_0    pypi
[conda] pytorch-crf               0.7.2                    pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torch-batch-svd           1.0.0                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchdevice               0.1.0                    pypi_0    pypi
[conda] torchglyph                0.3.2                    pypi_0    pypi
[conda] torchlatent               0.4.2                    pypi_0    pypi
[conda] torchrua                  0.4.0                    pypi_0    pypi
[conda] torchvision               0.10.0                   pypi_0    pypi
```

**Comment by speedcell4** [comment]
I have raised an issue but it is roughly closed, so I raise it again here.
