### ISSUE TITLE
JIT autocasting fails on Optional[Tensor]

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#75002]
### 🐛 Describe the bug

The autocasting pass does not insert autocasting nodes for optional tensors.

```python
import torch

from typing import Optional

def fn(inp, weight, bias: Optional[torch.Tensor]):
    with torch.cuda.amp.autocast(enabled=True, dtype=torch.half):
        return torch.nn.functional.conv2d(inp, weight, bias, 1, 3)

fn_s = torch.jit.script(fn)

inp = torch.rand((5, 3, 224, 224), dtype=torch.float).cuda()
weight = torch.rand((3, 3, 7, 7), dtype=torch.float).cuda()
bias = torch.rand((3), dtype=torch.float).cuda()

print("bias is none")
fn_s(inp, weight, None)

print("bias is not none")
fn_s(inp, weight, bias)
```

Output:
```
bias is none
bias is not none
Traceback (most recent call last):
  File "/fsx/users/dberard/scripts/regnet_y_128gf/optional-autocast.py", line 19, in <module>
    fn_s(inp, weight, bias)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/fsx/users/dberard/scripts/regnet_y_128gf/optional-autocast.py", line 7, in fn
def fn(inp, weight, bias: Optional[torch.Tensor]):
    with torch.cuda.amp.autocast(enabled=True, dtype=torch.half):
        return torch.nn.functional.conv2d(inp, weight, bias, 1, 3)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: Input type (torch.cuda.HalfTensor) and bias type (torch.cuda.FloatTensor) should be the same
```

### Versions

AWS cluster, master branch

**Comment by davidberard98** [comment]
possible solution - autocast only if optional[tensor] is not none

```python
import torch

from typing import Optional

class Mod(torch.nn.Module):
    bias: Optional[torch.Tensor]

    def __init__(self):
        super(Mod, self).__init__()
        self.bias: Optional[torch.Tensor] = torch.rand((3), dtype=torch.float)
        self.weight = torch.rand((3, 3, 7, 7), dtype=torch.float)

    def forward(self, x):
        b = self.bias
        if b is None:
            casted_bias = None
        else:
            casted_bias = torch.relu(b) # i.e. replace this with autocast_to_reduced_precision
        #with torch.autocast("cpu", dtype=torch.half):
        return torch.nn.functional.conv2d(x, self.weight, casted_bias, 1, 3)

mod = Mod().eval()

x = torch.rand((3, 3, 224, 224), dtype=torch.float)

mod_s = torch.jit.script(mod)
print(mod_s.graph)
mod_s(x)
print(torch.jit.last_executed_optimized_graph())
mod_s(x)
print(torch.jit.last_executed_optimized_graph())
mod_s(x)
print(torch.jit.last_executed_optimized_graph())

mod_s = torch.jit.freeze(mod_s)

print(mod_s.graph)
mod_s(x)
print(torch.jit.last_executed_optimized_graph())
mod_s(x)
print(torch.jit.last_executed_optimized_graph())
mod_s(x)
print(torch.jit.last_executed_optimized_graph())
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
