### ISSUE TITLE
`TORCH_DISTRIBUTED_DEBUG=DETAIL` raises runtime errors in ddp tests

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#75011]
### 🐛 Describe the bug

While debugging I've exported a few env variables including `TORCH_DISTRIBUTED_DEBUG=DETAIL` and noticed that a lot of ddp tests started to fail suddenly and was able to narrow it down to the usage of `TORCH_DISTRIBUTED_DEBUG`.

Code to reproduce:
```python
TORCH_DISTRIBUTED_DEBUG=DETAIL python distributed/fsdp/test_fsdp_core.py -v
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmplpi1b61s
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmplpi1b61s/_remote_module_non_sriptable.py
test_backward_hooks_after_save (__main__.TestHooks) ... INFO:numba.cuda.cudadrv.driver:init
INFO:torch.testing._internal.common_distributed:Started process 0 with pid 197584
INFO:torch.testing._internal.common_distributed:Started process 1 with pid 197585
...
INFO:torch.testing._internal.common_distributed:Starting event listener thread for rank 0
ERROR:torch.testing._internal.common_distributed:Caught exception: 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 601, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 486, in wrapper
    fn()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 131, in wrapper
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/distributed/fsdp/test_fsdp_core.py", line 265, in test_backward_hooks_after_save
    self._train_for_several_steps(model, num_steps=2, autocast=False)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_fsdp.py", line 430, in _train_for_several_steps
    model.module.run_backward(loss)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_fsdp.py", line 149, in run_backward
    loss.backward()
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 399, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1409, in _post_backward_hook
    dist._reduce_scatter_base(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2513, in _reduce_scatter_base
    work = group._reduce_scatter_base(output, input, opts)
RuntimeError: ProcessGroup nccldoes not support _reduce_scatter_base
Exception raised from _reduce_scatter_base at /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroup.hpp:322 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x7f38b5a9a1dc in /opt/conda/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x7f38b5a77cd4 in /opt/conda/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x3ae89a6 (0x7f38e4a009a6 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x9e0cff (0x7f38eabb2cff in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x345399 (0x7f38ea517399 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: PyCFunction_Call + 0x6e (0x55bd9672ae7e in /opt/conda/bin/python)
frame #6: _PyObject_MakeTpCall + 0x501 (0x55bd96713631 in /opt/conda/bin/python)
frame #7: <unknown function> + 0x13bbfd (0x55bd9672abfd in /opt/conda/bin/python)
frame #8: _PyEval_EvalFrameDefault + 0x48dc (0x55bd9670effc in /opt/conda/bin/python)
frame #9: _PyEval_EvalCodeWithName + 0x2e1 (0x55bd96709461 in /opt/conda/bin/python)
frame #10: _PyFunction_Vectorcall + 0x18c (0x55bd9671b33c in /opt/conda/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x10e8 (0x55bd9670b808 in /opt/conda/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x2e1 (0x55bd96709461 in /opt/conda/bin/python)
frame #13: _PyFunction_Vectorcall + 0x18c (0x55bd9671b33c in /opt/conda/bin/python)
frame #14: PyObject_Call + 0x2d2 (0x55bd9672d172 in /opt/conda/bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x2150 (0x55bd9670c870 in /opt/conda/bin/python)
frame #16: _PyEval_EvalCodeWithName + 0x9f6 (0x55bd96709b76 in /opt/conda/bin/python)
frame #17: _PyFunction_Vectorcall + 0x18c (0x55bd9671b33c in /opt/conda/bin/python)
frame #18: <unknown function> + 0x13ba3b (0x55bd9672aa3b in /opt/conda/bin/python)
frame #19: _PyObject_FastCallDict + 0x390 (0x55bd96712d70 in /opt/conda/bin/python)
frame #20: <unknown function> + 0x1fd1a9 (0x55bd967ec1a9 in /opt/conda/bin/python)
frame #21: _PyObject_MakeTpCall + 0x501 (0x55bd96713631 in /opt/conda/bin/python)
frame #22: <unknown function> + 0x12be0d (0x55bd9671ae0d in /opt/conda/bin/python)
frame #23: PyObject_CallFunctionObjArgs + 0xa1 (0x55bd9671aa41 in /opt/conda/bin/python)
frame #24: torch::autograd::PyFunctionPostHook::operator()(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&) + 0xcc (0x7f38ea80a70c in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #25: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x8ea (0x7f38e4113a7a in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #26: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x5f0 (0x7f38e4115400 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #27: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x9f (0x7f38e410c85f in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #28: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x67 (0x7f38ea7fd527 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #29: <unknown function> + 0xd6de4 (0x7f38ec865de4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #30: <unknown function> + 0x8609 (0x7f3921854609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #31: clone + 0x43 (0x7f3921613163 in /usr/lib/x86_64-linux-gnu/libc.so.6)

 exiting process 7 with exit code: 10
ERROR:torch.testing._internal.common_distributed:Caught exception: 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 601, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 486, in wrapper
    fn()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 131, in wrapper
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/test/distributed/fsdp/test_fsdp_core.py", line 265, in test_backward_hooks_after_save
    self._train_for_several_steps(model, num_steps=2, autocast=False)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_fsdp.py", line 430, in _train_for_several_steps
    model.module.run_backward(loss)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_fsdp.py", line 149, in run_backward
    loss.backward()
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 399, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1409, in _post_backward_hook
    dist._reduce_scatter_base(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2513, in _reduce_scatter_base
    work = group._reduce_scatter_base(output, input, opts)
RuntimeError: ProcessGroup nccldoes not support _reduce_scatter_base
Exception raised from _reduce_scatter_base at /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroup.hpp:322 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x7f6334eae1dc in /opt/conda/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x7f6334e8bcd4 in /opt/conda/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x3ae89a6 (0x7f6363e149a6 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x9e0cff (0x7f6369fc6cff in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x345399 (0x7f636992b399 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: PyCFunction_Call + 0x6e (0x55932727ce7e in /opt/conda/bin/python)
frame #6: _PyObject_MakeTpCall + 0x501 (0x559327265631 in /opt/conda/bin/python)
frame #7: <unknown function> + 0x13bbfd (0x55932727cbfd in /opt/conda/bin/python)
frame #8: _PyEval_EvalFrameDefault + 0x48dc (0x559327260ffc in /opt/conda/bin/python)
frame #9: _PyEval_EvalCodeWithName + 0x2e1 (0x55932725b461 in /opt/conda/bin/python)
frame #10: _PyFunction_Vectorcall + 0x18c (0x55932726d33c in /opt/conda/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x10e8 (0x55932725d808 in /opt/conda/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x2e1 (0x55932725b461 in /opt/conda/bin/python)
frame #13: _PyFunction_Vectorcall + 0x18c (0x55932726d33c in /opt/conda/bin/python)
frame #14: PyObject_Call + 0x2d2 (0x55932727f172 in /opt/conda/bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x2150 (0x55932725e870 in /opt/conda/bin/python)
frame #16: _PyEval_EvalCodeWithName + 0x9f6 (0x55932725bb76 in /opt/conda/bin/python)
frame #17: _PyFunction_Vectorcall + 0x18c (0x55932726d33c in /opt/conda/bin/python)
frame #18: <unknown function> + 0x13ba3b (0x55932727ca3b in /opt/conda/bin/python)
frame #19: _PyObject_FastCallDict + 0x390 (0x559327264d70 in /opt/conda/bin/python)
frame #20: <unknown function> + 0x1fd1a9 (0x55932733e1a9 in /opt/conda/bin/python)
frame #21: _PyObject_MakeTpCall + 0x501 (0x559327265631 in /opt/conda/bin/python)
frame #22: <unknown function> + 0x12be0d (0x55932726ce0d in /opt/conda/bin/python)
frame #23: PyObject_CallFunctionObjArgs + 0xa1 (0x55932726ca41 in /opt/conda/bin/python)
frame #24: torch::autograd::PyFunctionPostHook::operator()(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&) + 0xcc (0x7f6369c1e70c in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #25: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x8ea (0x7f6363527a7a in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #26: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x5f0 (0x7f6363529400 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #27: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x9f (0x7f636352085f in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #28: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x67 (0x7f6369c11527 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #29: <unknown function> + 0xd6de4 (0x7f636bc79de4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #30: <unknown function> + 0x8609 (0x7f63a0c68609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #31: clone + 0x43 (0x7f63a0a27163 in /usr/lib/x86_64-linux-gnu/libc.so.6)

 exiting process 5 with exit code: 10
...
```

Unsure if this env variable should *not* be used while executing tests and if this might thus be an expected failure.
In this case, we might want to raise another error message to avoid debugging it.

### Versions

PyTorch version: 1.12.0a0+bd13bc6
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.12.0a0+bd13bc6
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchtext==0.13.0a0
[pip3] torchvision==0.13.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.22.3           py38h05e7239_0    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.12.0a0+bd13bc6          pypi_0    pypi
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchtext                 0.13.0a0                 pypi_0    pypi
[conda] torchvision               0.13.0a0                 pypi_0    pypi

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @mruberry

**Comment by ptrblck** [comment]
Also reproduced with a clean master build from `1.12.0a0+bd13bc6` to make sure the (unrelated) debugging changes didn't introduce the issue.

**Comment by H-Huang** [comment]
I can repro this as well. Entire FSDP test suite is failing when `TORCH_DISTRIBUTED_DEBUG` is set, while they pass when the env variable is omitted.

cc @cbalioglu @rohan-varma is this related to the recent `TORCH_DISTRIBUTED_DEBUG` refactor?

cc @zhaojuanmao @awgu due to FSDP test (but I think this issue is relevant to more than just FSDP)

**Comment by H-Huang** [comment]
Based on a quick look, what I think is happening is that, when `TORCH_DISTRIBUTED_DEBUG` is set to on, we create a wrapper pg (used to validate the collective calls) via `process_group_wrapper` around the nccl group:

https://github.com/pytorch/pytorch/blob/785972b4ebafdb930304d109e698e3b4a1aecfb4/torch/distributed/distributed_c10d.py#L738-L757

However, this process group is by default Gloo. 

https://github.com/pytorch/pytorch/blob/785972b4ebafdb930304d109e698e3b4a1aecfb4/torch/distributed/distributed_c10d.py#L2864

Gloo does not support `reduce_scatter`, which is causing the failure.

**Comment by rohan-varma** [comment]
Yep, this is expected due to the reason @H-Huang mentioned.

We have an in progress PR to support Gloo for FSDP, which should then allow TDD to work. I should be able to get back to that PR in 2-3 weeks.

@ptrblck Can you provide insight into weather this is blocking on your end so we can prioritize appropriately?

**Comment by ptrblck** [comment]
Thank you for the insight @H-Huang and @rohan-varma!

No, I'm not blocked at all and was just running into the issue randomly while debugging something else.
I'm aware of the current limitation now and will use the env variable for specific tests.
Your plan sounds!

**Comment by rohan-varma** [comment]
Fixed now that PG wrapper supports _reduce_scatter_base.
