### ISSUE TITLE
torch.jit.load fails when path contains non-ascii characters

### ISSUE THREAD

**Issue by liuxingbaoyu** [pytorch/pytorch#75171]
### 🐛 Describe the bug

https://github.com/openai/CLIP/pull/227

`torch.jit.load` fails when path contains non-ascii characters

```py
import torch

torch.jit.load('C:\\Users\\流星暴雨/.cache/clip\\ViT-B-16.pt', "cpu")
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[C:\Users\]()流星暴雨\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\jit\_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: open file failed, file path: [C:\Users\]()流星暴雨/.cache/clip\ViT-B-16.pt
```

Related issues: https://github.com/pytorch/pytorch/issues/47422

### Versions

PS C:\Users\流星暴雨\AppData\Local\Programs\Python\Python39\Lib\site-packages\torch\utils> python collect_env.py
Collecting environment information...
PyTorch version: 1.8.2+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 专业工作站版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 512.15
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.2+cu102
[pip3] torchaudio==0.8.2
[pip3] torchvision==0.9.2+cu102
[conda] Could not collect

**Comment by taras-janea** [comment]
Closing the issue because the fix has not been accepted since `TorchScript` is deprecated.
Please use `torch.export.save` / `torch.export.load` instead of `torch.jit.save` / `torch.jit.load`.
