### ISSUE TITLE
libfb dependency breaks pytorch build

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#75182]
https://github.com/pytorch/pytorch/pull/75176 adds libfb dependency:

https://github.com/pytorch/pytorch/blob/152489a8cf56eb40c9e0a6f7deb6af515f2cc46e/tools/pyi/gen_pyi.py#L14

that breaks pytorch build:
```
[1019/2848] Generating ../../../torch/_C/__init__.pyi, ../../../torch/_C/_VariableFunctions.pyi, ../../../torch/nn/functional.pyi
FAILED: ../torch/_C/__init__.pyi ../torch/_C/_VariableFunctions.pyi ../torch/nn/functional.pyi 
cd /home/pearu/git/pytorch/pytorch && /home/pearu/miniconda3/envs/pytorch-cuda-dev/bin/python -mtools.pyi.gen_pyi --native-functions-path aten/src/ATen/native/native_functions.yaml --deprecated-functions-path tools/autograd/deprecated.yaml
Traceback (most recent call last):
  File "/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pearu/miniconda3/envs/pytorch-cuda-dev/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pearu/git/pytorch/pytorch/tools/pyi/gen_pyi.py", line 14, in <module>
    from libfb.py import parutil
ModuleNotFoundError: No module named 'libfb'
```

I could not find the origin of the libfb package. Is this a Meta internal thing?

cc @malfet @seemethere

**Comment by albanD** [comment]
It got reverted, you can pull master again.
Thanks for the report!
