### ISSUE TITLE
[jit] failing OpInfo JIT tests for conv1d and complex input

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#75309]
### 🐛 Describe the bug

Adding expectedFailure to unblock the PR

Test : `test_nnc_correctness`
Ref: https://github.com/pytorch/pytorch/runs/5838401052?check_suite_focus=true#step:9:22211

Test : `TestDtypeCustomRules`
Stack Trace
```
Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/pytorch_complex_convolution.py/test/jit/test_dtype_analysis.py", line 361, in test_custom_rules
    self.custom_rules_test_base(device, dtype, op)
  File "/home/kshiteej/Pytorch/pytorch_complex_convolution.py/test/jit/test_dtype_analysis.py", line 357, in custom_rules_test_base
    self.assert_output_dtype_equal(expected_res, graph)
  File "/home/kshiteej/Pytorch/pytorch_complex_convolution.py/test/jit/test_dtype_analysis.py", line 323, in assert_output_dtype_equal
    self.assert_tensor_dtype_equal(expected_res, actual_dtype[0])
  File "/home/kshiteej/Pytorch/pytorch_complex_convolution.py/test/jit/test_dtype_analysis.py", line 332, in assert_tensor_dtype_equal
    self.assertEqual(tensor_output.dtype, graph_dtype)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2160, in assertEqual
    assert_equal(
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1084, in assert_equal
    raise error_metas[0].to_error()
AssertionError: None mismatch: torch.complex128 is not None
```

### Versions

master

**Comment by eellison** [comment]
cc @Gamrix

**Comment by Gamrix** [comment]
@kshitij12345 Can you link the related PR?

**Comment by kshitij12345** [comment]
Updated the description. Sorry forgot to add it. Thanks @Gamrix!

**Comment by kshitij12345** [comment]
No. All inputs should have same dtype.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
