### ISSUE TITLE
Pytorch test failure with CUDA 11.6

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#75375]
### 🐛 Describe the bug

We recently introduced CUDA 11.6 to pytorch CI/CD pipeline. We are observing following failure in both windows and linux instances:

Linux:
```
_______________ test_constraint[True-constraint_fn7-True-value7] _______________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/distributions/test_constraints.py", line 71, in test_constraint
    assert constraint_fn.check(t(value)).all() == result
AssertionError: assert tensor(False, device='cuda:0') == True
 +  where tensor(False, device='cuda:0') = <built-in method all of Tensor object at 0x7f2260422950>()
 +    where <built-in method all of Tensor object at 0x7f2260422950> = tensor(False, device='cuda:0').all
 +      where tensor(False, device='cuda:0') = <bound method _PositiveSemidefinite.check of PositiveSemidefinite()>(tensor([[1., 2.],\n        [2., 4.]], device='cuda:0', dtype=torch.float64))
 +        where <bound method _PositiveSemidefinite.check of PositiveSemidefinite()> = PositiveSemidefinite().check
 +        and   tensor([[1., 2.],\n        [2., 4.]], device='cuda:0', dtype=torch.float64) = <class 'torch.cuda.DoubleTensor'>([[1.0, 2], [2.0, 4]])
=========================== short test summary info ============================
SKIPPED [2] distributions/test_constraints.py:83: `biject_to` not implemented.
FAILED distributions/test_constraints.py::test_constraint[True-constraint_fn7-True-value7]
```
[Link](https://github.com/pytorch/pytorch/runs/5858491614?check_suite_focus=true) to a failed job

Windows:
```
================================== FAILURES ===================================
______________ test_constraint[True-constraint_fn7-True-value7] _______________
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\test\distributions\test_constraints.py", line 71, in test_constraint
    assert constraint_fn.check(t(value)).all() == result
AssertionError: assert tensor(False, device='cuda:0') == True
 +  where tensor(False, device='cuda:0') = <built-in method all of Tensor object at 0x000001D2BF8C2950>()
 +    where <built-in method all of Tensor object at 0x000001D2BF8C2950> = tensor(False, device='cuda:0').all
 +      where tensor(False, device='cuda:0') = <bound method _PositiveSemidefinite.check of PositiveSemidefinite()>(tensor([[1., 2.],\n        [2., 4.]], device='cuda:0', dtype=torch.float64))
 +        where <bound method _PositiveSemidefinite.check of PositiveSemidefinite()> = PositiveSemidefinite().check
 +        and   tensor([[1., 2.],\n        [2., 4.]], device='cuda:0', dtype=torch.float64) = <class 'torch.cuda.DoubleTensor'>([[1.0, 2], [2.0, 4]])
```
[Link](https://github.com/pytorch/pytorch/runs/5851046713?check_suite_focus=true) to a failed job

### Versions

Pytorch master
CUDA 11.6

**Comment by ptrblck** [comment]
CC @xwang233 who is already debugging it

**Comment by xwang233** [comment]
Thanks for the report. This is due to a cusolver eigenvalue solver issue in cuda 11.6. We're working on this internally.

**Comment by xwang233** [comment]
The failed test is related to a new function added in #71375 , which checks if a matrix is positive semi-definite (PSD) by comparing its eigenvalues with zeros. It was and should be working well.

However, in cuda 11.6, cusolver symmetric eigenvalue solver introduced a new driver that could be less accurate in some rare cases. In the test case with a 2x2 matrix of `[[1, 2], [2, 4]]`, the supposed eigenvalues are 5 and 0. With double precision, cusolver in cuda 11.6 got 5 and -4.12e-34, which seems to be the minimal numerical error of double precision. Unfortunately, that fails the test.

There isn't a good workaround for the cusolver behavior at this moment. One thing we can do on the pytorch side is to change the input matrix for this test where the eigenvalue solver would be stable. We should also create a doc note for this behavior.

cc @nonconvexopt @ngimel

**Comment by nonconvexopt** [comment]
```
class _PositiveSemidefinite(_Symmetric):
    """
    Constrain to positive-semidefinite matrices.
    """
    def check(self, value):
        sym_check = super().check(value)
        if not sym_check.all():
            return sym_check
        return torch.linalg.eigvalsh(value).ge(-torch.finfo(value).eps).all(-1)
```

How about this solution? I think it is a reasonable way. Not tested, though.

**Comment by xwang233** [comment]
Changing 
```
torch.linalg.eigvalsh(value).ge(-torch.finfo(value).eps).all(-1)
```
to 
```
torch.linalg.eigvalsh(value).ge(-torch.finfo(value.dtype).eps).all(-1)
```

will let the test pass in cuda 11.6 update 1.

Wanted to know what @ngimel thinks.

**Comment by nonconvexopt** [comment]
@xwang233 It is my pleasure.

**Comment by atalman** [comment]
Closed this since CUDA 11.6 is deprecated
