### ISSUE TITLE
Pytorch linalg test failure with cuda 11.6

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#75391]
### 🐛 Describe the bug

We recently introduced CUDA 11.6 to pytorch CI/CD pipeline. We are observing following failure on Linux : 

[linux-bionic-cuda11.6-py3.7-gcc7](https://github.com/pytorch/pytorch/runs/5859582068?check_suite_focus=true)

```
ERROR [0.017s]: test_matrix_rank_empty_cuda_complex128 (__main__.TestLinalgCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1780, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 815, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 815, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 3737, in test_matrix_rank_empty
    run_test(0, 3, batch)
  File "test_linalg.py", line 3723, in run_test
    self.assertEqual(matrix_rank(aHa), matrix_rank(aHa, hermitian=True))
torch._C._LinAlgError: torch.linalg.eigvalsh: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 1).

======================================================================
ERROR [0.015s]: test_matrix_rank_empty_cuda_complex64 (__main__.TestLinalgCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1780, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 815, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 815, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 3737, in test_matrix_rank_empty
    run_test(0, 3, batch)
  File "test_linalg.py", line 3723, in run_test
    self.assertEqual(matrix_rank(aHa), matrix_rank(aHa, hermitian=True))
torch._C._LinAlgError: torch.linalg.eigvalsh: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 1).

======================================================================
ERROR [0.015s]: test_matrix_rank_empty_cuda_float32 (__main__.TestLinalgCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1780, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 815, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 815, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 3737, in test_matrix_rank_empty
    run_test(0, 3, batch)
  File "test_linalg.py", line 3723, in run_test
    self.assertEqual(matrix_rank(aHa), matrix_rank(aHa, hermitian=True))
torch._C._LinAlgError: torch.linalg.eigvalsh: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 1).

======================================================================
ERROR [0.016s]: test_matrix_rank_empty_cuda_float64 (__main__.TestLinalgCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1780, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 815, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 815, in dep_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 3737, in test_matrix_rank_empty
    run_test(0, 3, batch)
  File "test_linalg.py", line 3723, in run_test
    self.assertEqual(matrix_rank(aHa), matrix_rank(aHa, hermitian=True))
torch._C._LinAlgError: torch.linalg.eigvalsh: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 1).

----------------------------------------------------------------------
Ran 757 tests in 328.426s

FAILED (errors=4, skipped=36, expected failures=12)

Generating XML reports...
Generated XML report: test-reports/python-unittest/test_linalg/TEST-TestLinalgCUDA-20220406234138.xml
Traceback (most recent call last):
  File "test/run_test.py", line 1056, in <module>
    main()
  File "test/run_test.py", line 1034, in main
    raise RuntimeError(err_message)
RuntimeError: test_linalg failed!
```

### Versions

CUDA 11.6
Pytorch master

**Comment by ptrblck** [comment]
CC @xwang233

**Comment by xwang233** [comment]
Thanks for the report. This is due to a cusolver eigenvalue solver issue in cuda 11.6. It has already been fixed internally and will be available in the next cuda release.

**Comment by ngimel** [comment]
Do you suggest disabling these tests in the meantime? How wide is the bug surface?

**Comment by Lezcano** [comment]
If we have another fallback backend, we could potentially check for the version and dispatch to the other backend if that version of the library is in use. We already do this to work around bugs in magma.

**Comment by xwang233** [comment]
Hi @ngimel , in cuda 11.6, cusolver added a new kernel for symmetric eigenvalue solver `syevd`. Anything using `eigh` with cusolver `syevd` backend may be affected. 

Pytorch heuristics for eigenvalue solver `syevd`:
https://github.com/pytorch/pytorch/blob/064206df039d48de08c3502dcc03bcba7161de70/aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.cpp#L1390-L1402

**Comment by atalman** [comment]
> Thanks for the report. This is due to a cusolver eigenvalue solver issue in cuda 11.6. It has already been fixed internally and will be available in the next cuda release.

@xwang233 Please let us know if you are talking about major or minor release ? Its important for us, since minor release intergation would take couple of days, vs major release like cuda 11.7 would take at least couple of weeks.

**Comment by xwang233** [comment]
Cusolver eigenvalue solver fixes will be integrated in cuda 11.7

**Comment by andyweizhao** [comment]
@xwang233 

"torch._C._LinAlgError: torch.linalg.eigvalsh: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 1)."

To clarify, is this error message misreported? Usually, the eigendecomposition of a real/complex symmetric matrix can be solved by Lanczos or Divide-Conquer algorithms, both of which may be prone to round-off errors, but they are not relevant to the condition number of the matrix and the repeatedness of eigenvalues, I guess.

**Comment by xwang233** [comment]
@andyweizhao , this depends on your pytorch version. If you're using a pytorch built with 11.6.x, it could likely be a cusolver fault. If you're using pytorch from another version, it could be your input.

**Comment by prinshul** [comment]
What is the fix for this error? Cuda 11.7?

**Comment by Jark5455** [comment]
Any update about this?
