### ISSUE TITLE
DISABLED test_torch_nn_CrossEntropyLoss_2d_indices_target_smoothing_weight_cuda (__main__.TestCppApiParity)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#75417]
platforms: windows

This test is failing on Windows with CUDA 11.6. Example log: https://github.com/pytorch/pytorch/runs/5861322515?check_suite_focus=true. 

Example snippet:

```
======================================================================
ERROR [0.894s]: test_torch_nn_CrossEntropyLoss_2d_indices_target_smoothing_weight_cuda (__main__.TestCppApiParity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\test\cpp_api_parity\module_impl_check.py", line 251, in test_fn
    test_forward_backward(
  File "C:\actions-runner\_work\pytorch\pytorch\test\cpp_api_parity\module_impl_check.py", line 134, in test_forward_backward
    script_module, python_output, python_grad_dict = run_python_forward_backward(unit_test_class, test_params)
  File "C:\actions-runner\_work\pytorch\pytorch\test\cpp_api_parity\module_impl_check.py", line 103, in run_python_forward_backward
    python_output = module(*inputs)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\nn\modules\loss.py", line 1163, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\nn\functional.py", line 2961, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

cc @ezyang @gchanan @zou3519 @peterjc123 @mszhanyi @skyline75489 @nbcsm @jbschlosser @albanD @mruberry @walterddr @kshitij12345 @ngimel

**Comment by atalman** [comment]
cc @ptrblck @xwang233

**Comment by atalman** [comment]
This could be a flaky test, another run with 11.6 have not surfaced this issue:
https://github.com/pytorch/pytorch/runs/5861097296?check_suite_focus=true

```
2022-04-07T06:21:05.4738692Z   test_torch_nn_CrossEntropyLoss_2d_indices_target_smoothing_weight_cuda (__main__.TestCppApiParity) ... ok (0.033s)
```
