### ISSUE TITLE
when inputs includes str, scatter() in dataparallel won't split them correctly.

### ISSUE THREAD

**Issue by mhh0318** [pytorch/pytorch#75442]
### 🐛 Describe the bug

When the datasets include `array` and `str`, the `str` part cannot be splitted and applied to device correctly.

```
from torch.utils.data import Dataset

class CocoDataset(Dataset):
    def __init__(self):
        pass
    def __getitem(self,index):
        pass
        return {'img': Array, 'txt': str}
```

In the training phase, the input to the model is a `dict` as `{'img':Tensors, 'txt': [str,str,...,str]}`

However,  after `torch.nn.parallel.data_parallel.py`
```
inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
```

image part (array) can be split, but text part (str) will remain.

Error log:
```
Traceback (most recent call last):
  File "****miniconda3/envs/th/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "****miniconda3/envs/th/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "****.vscode-server/extensions/ms-python.python-2022.5.10911002/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "****.vscode-server/extensions/ms-python.python-2022.5.10911002/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "****.vscode-server/extensions/ms-python.python-2022.5.10911002/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "****miniconda3/envs/th/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "****miniconda3/envs/th/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "****miniconda3/envs/th/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "********", line 71, in <module>
    exp.run()
  File "********", line 137, in run
    super(DiffusionExperiment, self).run(epochs=self.args.epochs)
  File "********", line 137, in run
    train_dict = self.train_fn(epoch)
  File "********", line 118, in train_fn
    loss = - self.model(x, train=True).sum() / (math.log(2) * num_elem)
  File "****miniconda3/envs/th/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "****miniconda3/envs/th/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "****miniconda3/envs/th/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "****miniconda3/envs/th/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "****miniconda3/envs/th/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AssertionError: Caught AssertionError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "****miniconda3/envs/th/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "****miniconda3/envs/th/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "********", line 487, in forward
    img, txt = self.prepare_input(x)
  File "********", line 481, in prepare_input
    assert img_tokens.shape[0] == txt_tokens.shape[0]
AssertionError
```
The batch size is 8 and the machine has 4 GPUs.
Here `img_tokens.shape[0]` is `2` while `txt_tokens.shape[0]` is `8`. 

### Versions

```
[conda] torch                     1.10.0+cu113             pypi_0    pypi
[conda] torch-tb-profiler         0.3.1                    pypi_0    pypi
[conda] torchaudio                0.10.0+cu113             pypi_0    pypi
[conda] torchmetrics              0.6.0                    pypi_0    pypi
[conda] torchvision               0.11.1+cu113             pypi_0    pypi
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @VitalyFedyunin @ejguan @NivekT

**Comment by kumpera** [comment]
This is the expected behavior of DataParallel. Only tensors are slices and everything else is replicated.

You can work around this with something like the following in your forward pass:

```
    def forward(self, input):
        idx = torch.cuda.current_device()
        count = torch.cuda.device_count()
        txt = input['txt']
        txt = txt[idx * len(txt) : len(txt) // count]
```
