### ISSUE TITLE
Make FSDP Mixed Precision work with BatchNorm

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#75478]
### 🚀 The feature, motivation and pitch

Mixed precision training for FSDP recently landed: https://github.com/pytorch/pytorch/pull/75024, however, it does not work out of the box for batch norm at the moment. 

If mixed precision is attempted to be used with batchnorm/syncbatchnorm, an error similar to the below is encountered:

```
>>> z = torch.ones(128, 128, 128).to(torch.float16)
>>> x = nn.BatchNorm1d(128)
>>> x(z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 179, in forward
    self.eps,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/nn/functional.py", line 2399, in batch_norm
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: "batch_norm" not implemented for 'Half'
```

In general, even if the rest of the model (i.e. dense layers) are using mixed precision, we want to disable mixed precision for BN layers. In general, fp32 full precision computation is recommended for batchnorm, via resources such as https://nvidia.github.io/apex/amp.html.

The proposal here is to force disabling of mixed precision of BN layers, even if user specifies mixed precision for them. If we are wrapping a batchnorm instance in constructor, we simply add an `isinstance` check in constructor, and disable mixed precision if we are in batchnorm.

We'd want to ensure that this works for both ways to wrap FSDP: `enable_wrap` + `wrap`, as well as `auto_wrap_policy`.

As a follow up change, we can also support forcing inputs to fp32 prior to being run in a batchnorm.

To test, we can add unittests to `test_fsdp_mixed_precision` as well as run ResNet internal benchmark to validate that the change works.

It remains an open issue on how to resolve this for modules that contain batchnorm as a submodule, but user wraps these modules instead of just the batchnorm instance. Possibly we will not support this in the near term and document as so.

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
This is fixed.
