### ISSUE TITLE
IndexError: Caught IndexError in replica 0 on device 0.

### ISSUE THREAD

**Issue by hxi667** [pytorch/pytorch#75480]
### 🐛 Describe the bug

This error occurs when I train my model with 8-gpu, and I don't know how to fix it.

Traceback (most recent call last):
  ...
  File "/root/anaconda3/envs/SSGait/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/SSGait/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/anaconda3/envs/SSGait/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/anaconda3/envs/SSGait/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/root/anaconda3/envs/SSGait/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/SSGait/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/envs/SSGait/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/hxi/Gait Recognition/SSGait0.4/models/vgg_c3d.py", line 187, in forward
    feature = feature.matmul(self.fc_bin[0])
  File "/root/anaconda3/envs/SSGait/lib/python3.7/site-packages/torch/nn/modules/container.py", line 426, in __getitem__
    idx = self._get_abs_string_index(idx)
  File "/root/anaconda3/envs/SSGait/lib/python3.7/site-packages/torch/nn/modules/container.py", line 409, in _get_abs_string_index
    raise IndexError('index {} is out of range'.format(idx))
IndexError: index 0 is out of range

I guess this error might be related to this statement in my model, but I don't know how to fix it:
def __init__(self):
      self.fc_bin = nn.ParameterList([
                  nn.Parameter(
                      nn.init.xavier_uniform_(
                          torch.zeros(sum(self.bin_numgl), _set_channels[2], _set_channels[2])))
                          ])
def forward(self, x):
      feature = feature.matmul(self.fc_bin[0])

When this code is commented out, it runs successfully: feature = feature.matmul(self.fc_bin[0])

### Versions

cuda ==11.0  cudatoolkit== 11.0   pytorch==1.7.1

**Comment by kumpera** [comment]
Hi,

Could you provide a complete example that shows the issue you're running into?

**Comment by kamrul-h** [comment]
I am getting the similar problem while using multiple GPU!!!!! TIA..


/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/nn/modules/container.py:542: UserWarning: nn.ParameterList is being used with DataParallel but this is not supported. This list will appear empty for the models replicated on each GPU except the original one.
  warnings.warn("nn.ParameterList is being used with DataParallel but this is not "
/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/nn/modules/container.py:487: UserWarning: Setting attributes on ParameterList is not supported.
  warnings.warn("Setting attributes on ParameterList is not supported.")
Traceback (most recent call last):
  File "/home/user/kamrul_code/gaitset-master-casiaB/train.py", line 24, in <module>
    m.fit()
  File "/home/user/kamrul_code/gaitset-master-casiaB/model/model.py", line 205, in fit
    feature, label_prob = self.encoder(*seq, batch_frame)
  File "/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/kamrul_code/gaitset-master-casiaB/model/network/gaitset.py", line 323, in forward
    feature1 = feature1.matmul(self.fc_bin[0])
  File "/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/nn/modules/container.py", line 477, in __getitem__
    idx = self._get_abs_string_index(idx)
  File "/home/user/anaconda3/envs/pytest39/lib/python3.9/site-packages/torch/nn/modules/container.py", line 460, in _get_abs_string_index
    raise IndexError('index {} is out of range'.format(idx))
IndexError: index 0 is out of range

**Comment by kamrul-h** [comment]
@hxi667 .... Did you able to solve the problem ??? If did then how ???
