### ISSUE TITLE
Connection closed by peer when using dist.isend in gloo backend

### ISSUE THREAD

**Issue by timmywanttolearn** [pytorch/pytorch#75512]
### 🐛 Describe the bug

When I try to use dist.isend in gloo backend, sometimes it will occur that the connection is closed by peers. However nccl won't
gloo code
```
# from model import resnet
import torchvision.models as models

import torch.nn as nn
import torch
import torch.multiprocessing as mp
import torchvision.transforms as transforms

import torchvision
import torch.distributed as dist
from compression_layer import QSendLayer,QRecvLayer,QtensorSendonCPU,QtensorRecvonCPU




def main():
    mp.spawn(main_worker, nprocs=2,
                    args=(2, 1))

def main_worker(rank,process_num,nothing):
    dist.init_process_group(backend="gloo", init_method='tcp://127.0.0.1:1233',
                                    world_size=2, rank=rank)
    print("rank",rank)
    if rank == 0:
        
        input = torch.rand([4,4])
        dist.isend(input,1)


     
     

    else:
        input = torch.rand([4,4])
        dist.recv(input,0)
    print("finish",rank)
 
 
if __name__ == "__main__":
    main()

```
bug report 
```
    pg.recv([tensor], src, tag).wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [18.25.6.30]:28048
```
However nccl won't
If you change backend to 'nccl', these won't happen

### Versions

CUDA -- 10.2
pytorch version -- 1.12.0(nightly)

**Comment by kumpera** [comment]
I added a `time.sleep(10)` at the end of `main_worker` to ensure that this is not racing with shutdown and it does indeed fail to work.

@jiayisuse do you have an idea of what's the issue here?

**Comment by timmywanttolearn** [comment]
> I added a `time.sleep(10)` at the end of `main_worker` to ensure that this is not racing with shutdown and it does indeed fail to work.
> 
> @jiayisuse do you have an idea of what's the issue here?

Sure if you add something to wait will cause the right result. But why nccl backend does not has this issue, there should be no differences

**Comment by timmywanttolearn** [comment]
So, are you going to solve it? Since this bug is still there to be solved

**Comment by dokooh** [comment]
Hi, 

I just run into this issue trying to run a distributed finetune operation:

Traceback (most recent call last):
  File "/root/lightning-sam/lightning_sam/train.py", line 167, in <module>
    main(cfg)
  File "/root/lightning-sam/lightning_sam/train.py", line 160, in main
    model, optimizer = fabric.setup(model, optimizer)
  File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 204, in setup
    module, optimizers = self._strategy.setup_module_and_optimizers(  # type: ignore[assignment]
  File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/strategies/strategy.py", line 123, in setup_module_and_optimizers
    module = self.setup_module(module)
  File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/strategies/ddp.py", line 118, in setup_module
    return DistributedDataParallel(module=module, device_ids=self._determine_ddp_device_ids(), **self._ddp_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: [/opt/conda/conda-bld/pytorch_1679586020379/work/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [169.255.255.2]:946

**Comment by youkaichao** [comment]
A minimal example:

```python
import torch.distributed as dist
import torch

dist.init_process_group(backend="gloo")

data1 = torch.tensor([1] * dist.get_rank())
dist.all_reduce(data1)
print(f"answer from rank {dist.get_rank()}: avg {data1.mean().cpu().item()}")
```

`torchrun --nproc-per-node 2 test.py`

and the error trace:

```text
Traceback (most recent call last):
  File "/home/gcpuser/vllm/test.py", line 7, in <module>
    dist.all_reduce(data1)
  File "/opt/conda/envs/vllm-torch-by-date/lib/python3.9/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/vllm-torch-by-date/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2055, in all_reduce
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.128.0.29]:49834
[2024-03-28 22:57:47,401] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 25783) of binary: /opt/conda/envs/vllm-torch-by-date/bin/python3.9
```

I checked the environment variable, the master ip is `127.0.0.1` . Not sure why it wants to reach 10.128.0.29 .

**Comment by log2win** [comment]
@youkaichao You have error because of different number of values inside tensor
"[1] * dist.get_rank()" will be [] on rank0 and [1] on rank1 and [1, 1] on rank2 and so on
