### ISSUE TITLE
`all_gather_object` not working with NCCL Backend

### ISSUE THREAD

**Issue by mostafarohani** [pytorch/pytorch#75619]
### 🐛 Describe the bug

The below code works perfectly fine with the `gloo` backend
```
import torch.distributed as dist
from torch.multiprocessing import spawn


def main(rank: int, world_size: int) -> None:
    dist.init_process_group("nccl", init_method="tcp://127.0.0.1:23456", rank=rank, world_size=world_size)

    object_list = [None] * world_size

    obj = "hello" if rank == 0 else "world"
    dist.all_gather_object(object_list, obj)
    print(object_list)


if __name__ == "__main__":
    world_size = 2
    spawn(main, (world_size,), nprocs=world_size)
```

However, with `nccl` as the backend, it gives the error
```
    while not context.join():
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/workspaces/svu-models/sandbox/mostafa/dist_all_gather_obj_example.py", line 11, in main
    dist.all_gather_object(object_list, obj)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1649, in all_gather_object
    all_gather(object_size_list, local_size, group=group)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2060, in all_gather
    work = default_pg.allgather([tensor_list], [tensor])
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1169, invalid usage, NCCL version 21.0.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
```
<img width="1199" alt="Screen Shot 2022-04-11 at 1 50 31 PM" src="https://user-images.githubusercontent.com/8623092/162830430-97fef69e-5899-48d3-9e6e-5e124458ffce.png">
<img width="1017" alt="Screen Shot 2022-04-11 at 1 49 30 PM" src="https://user-images.githubusercontent.com/8623092/162830443-e4b9b254-f877-40d3-9eb7-9ee79ed66936.png">

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0+cu115
Is debug build: False
CUDA used to build PyTorch: 11.5
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-163-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration: 
GPU 0: NVIDIA RTX A5000
GPU 1: NVIDIA RTX A5000
GPU 2: NVIDIA RTX A5000
GPU 3: NVIDIA RTX A5000
GPU 4: NVIDIA RTX A5000
GPU 5: NVIDIA RTX A5000
GPU 6: NVIDIA RTX A5000
GPU 7: NVIDIA RTX A5000

Nvidia driver version: 495.29.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] covariant-torch-ops-roi-upsample==0.0.0
[pip3] mypy==0.931
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.6.0
[pip3] torch==1.11.0+cu115
[pip3] torchmetrics==0.7.3
[pip3] torchvision==0.12.0+cu115
[conda] covariant-torch-ops-roi-upsample 0.0.0                    pypi_0    pypi
[conda] mypy                      0.931                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] pytorch-lightning         1.6.0                    pypi_0    pypi
[conda] torch                     1.11.0+cu115             pypi_0    pypi
[conda] torchmetrics              0.7.3                    pypi_0    pypi
[conda] torchvision               0.12.0+cu115             pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
cc @wanchaol Could this be related to the recent changes to `allgather` in NCCL backend?

**Comment by wanchaol** [comment]
> cc @wanchaol Could this be related to the recent changes to `allgather` in NCCL backend?

hmmm the recent changes is only for NCCL `gather`, but not `all_gather`, these two are actually not sharing the same code I think. 

This seems to be high priority and wondering why this wasn't been caught by our CI signals.

**Comment by wanchaol** [comment]
@mostafarohani Looking closer to the repro code, it seems like you are not setting the current device on each rank for nccl process group, 

before the collective, you need to set `torch.cuda.set_device(rank)`, then it should work. Please see the note section in the doc here:https://pytorch.org/docs/stable/distributed.html?highlight=all_gather_object#torch.distributed.all_gather_object
