### ISSUE TITLE
multiprocessing and torch.tensor, Cannot allocate memory error

### ISSUE THREAD

**Issue by Ziaeemehr** [pytorch/pytorch#75662]
### 🐛 Describe the bug

Consider the simple example in the following, if I return a list at `func`, there will be no error, 
if I return a `torch.tensor` I will get this error:

```sh
/work/aten/src/ATen/MapAllocator.cpp":263, please report a bug to PyTorch. unable to open shared memory object </torch_326297_506> in read-write mode')'
```
and If it use  `set_sharing_strategy`, to avoid this error:

```python
from multiprocessing import Pool
from time import sleep
import torch


class A:
    def __init__(self, n_job, N):
        self.n_job = n_job
        self.N = N

    
    def func(self, i):
        # sleep(1)
        print(i)
        return torch.as_tensor([i])
        # return [i]

    data = []

    def read(self):

        torch.multiprocessing.set_sharing_strategy('file_system')

        with Pool(processes=self.n_job) as pool:
            data = pool.map(self.func, range(self.N))
    
        return data
    
if __name__ == "__main__":
    a = A(10, 2**16)
    data = a.read()


    print(len(data))
```

I get another error says 

```sh 
MapAllocator.cpp":323, please report a bug to PyTorch. unable to mmap 72 bytes from file </torch_326588_5707>: Cannot allocate memory (12)
```

is there any solution?
I need to return the tensor, so just removing the tensor is not an option.

I am using 

### Versions

```sh 
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.6.112
GPU models and configuration: GPU 0: NVIDIA RTX A5000
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.10.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.3              h15472ef_10    conda-forge
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pytorch                   1.10.2          cpu_py39hfa7516b_0
```

**Comment by H-Huang** [comment]
> MapAllocator.cpp":323, please report a bug to PyTorch. unable to mmap 72 bytes from file </torch_326588_5707>: Cannot allocate memory (12)

Are you sure this is the error coming from pytorch? I tried to grep for a section of that message and don't find anything. The "cannot allocate memory" sounds like a RAM problem

**Comment by Ziaeemehr** [comment]
The function just returns an integer, I don't expect that to consume more of my machine RAM (64GB).

**Comment by TevenLeScao** [comment]
Seeing the same thing, and also unlikely to be a RAM problem here.

**Comment by yvquanli** [comment]
Seeing the same thing+1

**Comment by VitalyFedyunin** [comment]
Can you please check shared memory status while running this code https://datacadamia.com/os/linux/shared_memory

**Comment by mkrizmancic** [comment]
Hi, I think I have the same issue.

Here is the minimal example.
```python
import multiprocessing as mp
mp.set_sharing_strategy("file_system")  # Without this -> RuntimeError: received 0 items of ancdata

def worker(data):
    return [data, data + 1]
    # return torch.tensor([data, data + 1])

def main():
    """Input list, return list, use multiprocessing."""
    input_data = range(1_000_000)
    # If I increase the range to 100_000_000, the memory usage grows
    # continuously, but swap space handles it and the process finishes normally.

    with mp.Pool() as pool:
        result = pool.map(worker, input_data)

    print(result[1234])

if __name__ == "__main__":
    main()
```

If I run the code as is, there are no problems. Increasing the input data size leads to a continuous increase in memory usage as explained [here](https://github.com/pytorch/pytorch/issues/13246#issuecomment-445446603), but swap space takes the excess memory and the process finishes normally.

If I return the tensor instead of the list, I get:
```# Exception in thread Thread-3 (_handle_results):
# Traceback (most recent call last):
#   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
#     self.run()
#   File "/usr/lib/python3.10/threading.py", line 953, in run
#     self._target(*self._args, **self._kwargs)
#   File "/usr/lib/python3.10/multiprocessing/pool.py", line 579, in _handle_results
#     task = get()
#   File "/usr/lib/python3.10/multiprocessing/connection.py", line 251, in recv
#     return _ForkingPickler.loads(buf.getbuffer())
#   File "/home/.../lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 514, in rebuild_storage_filename
#     storage = torch.UntypedStorage._new_shared_filename_cpu(manager, handle, size)
# RuntimeError: unable to mmap 80 bytes from file </torch_54943_2537684984_4044>: Cannot allocate memory (12)
```
This happens even for smaller input data.

I tried all possible combinations of the following things:
1. Using `multiprocessing` or `torch.multiprocessing`
2. Changing input data to `input_data = torch.arange(0, 100_000)`
3. Doing `.set_start_method("spawn")` on both variants of imported multiprocessing.

[This post](https://github.com/pytorch/pytorch/issues/13246#issuecomment-905703662) summarizes that in a similar issue, one should use objects that have a single refcount (e.g. tensors) instead of Python lists, but that obviously does not help in this case.

While monitoring the shared memory `/dev/shm` with `watch -n .3 df -h`, I do see a gradual increase, but by the time the error is thrown, it doesn't reach 10% of the available space.
