### ISSUE TITLE
Tensorboard Issue with visualizing the connections of encoder-decoder network

### ISSUE THREAD

**Issue by olahsymbo** [pytorch/pytorch#75673]
### 🐛 Describe the bug

We are trying to visualize the connections of the intermediate layers of a deep neural network using tensorboard. Our implementation is below:

```
    model = build_model(cfg) 
    path = 'output/model_0004999.pth' 
    model.load_state_dict(torch.load(path)['model'])  

    # get some random training images
    print(trainloader)
    dataiter = iter(trainloader)
    images = dataiter.next()

    # create grid of images 
    img_grid = torchvision.utils.make_grid(images)

    writer=SummaryWriter('content/logsdir')

    # show images
    matplotlib_imshow(img_grid, one_channel=True)

    # write to tensorboard
    writer.add_image('mtailor_images', img_grid)
    writer.add_graph(model, [images])
    writer.close()

```

However, we keep getting this error pointing to `jit`

```
Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions
Error occurs, No graph saved
Traceback (most recent call last):
  File "convert_model_tensorboard.py", line 96, in <module>
    writer.add_graph(model, [images])
  File "/home/ubuntu/user/.virtualenv/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 723, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "/home/ubuntu/user/.virtualenv/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 293, in graph
    raise e
  File "/home/ubuntu/user/.virtualenv/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 286, in graph
    trace = torch.jit.trace(model, args)
  File "/home/ubuntu/user/.virtualenv/lib/python3.6/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/home/ubuntu/user/.virtualenv/lib/python3.6/site-packages/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
RuntimeError: Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions
```

### Versions

Python 3.6.9

torch==1.8.0
torchsummary==1.5.1
torchvision==0.9.0
tensorboard==2.8.0

**Comment by Moriarty0112** [comment]
same problem,  do you have any ideas now?
