### ISSUE TITLE
NVFuser failing autogen-33 benchmark

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#75708]
### 🐛 Describe the bug

Repro:

```python
import torch

def fn(t1, t2, t3, t4, i1: int, i2: int):
    v1 = torch.sub(t3, t4, alpha=i2)
    v2 = torch.mul(v1, t2)
    v3 = torch.reshape(t1, [1, 12, 64, 4096])
    v4 = torch.add(v3, v2, alpha=i1)
    v5 = torch._softmax(v4, -1, False)
    v6 = torch.reshape(v5, [12, 64, 4096])
    return v6

with torch.jit.fuser("fuser2"):
    fn_s = torch.jit.script(fn)
    other_dtype = torch.double
    t1 = torch.rand((12, 64, 4096), dtype=torch.float).cuda()
    t2 = torch.rand((), dtype=other_dtype).cuda()
    t3 = torch.rand((), dtype=other_dtype).cuda()
    t4 = torch.rand((1, 1, 1, 4096), dtype=torch.float).cuda()

    fn_s(t1, t2, t3, t4, 1, 1)
    fn_s(t1, t2, t3, t4, 1, 1)
```

Or using `https://github.com/pytorch/benchmark/pull/801`, 
```
$ python run_microbenchmarks.py nvfuser --filter autogen-33
```

Run with `PYTORCH_NVFUSER_DISABLE_FALLBACK=1`

Note: same error on autogen-69, I'm not sure if it's caused by the same issue.

Error:

```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: CUDA driver error: too many resources requested for launch
```

Stacktrace
```
frame #0: <unknown function> + 0xe4ae3 (0x7eff8a811ae3 in /fsx/users/dberard/pytorch/torch/lib/libc10.so)
frame #1: std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const + 0x4c (0x7effc3fa4a9a in /fsx/users/dberard/pytorch/torch/lib/libtorch_cpu.so)
frame #2: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x40 (0x7eff8a810964 in /fsx/users/dberard/pytorch/torch/lib/libc10.so)
frame #3: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7b (0x7eff8a80e865 in /fsx/users/dberard/pytorch/torch/lib/libc10.so)
frame #4: torch::jit::fuser::cuda::FusionExecutor::runFusion(c10::ArrayRef<c10::IValue> const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, torch::jit::fuser::cuda::LaunchParams const&, c10::optional<unsigned long> const&) + 0x2023 (0x7effb7a81f53 in /fsx/users/dberard/pytorch/torch/lib/libtorch_cuda_cu.so)
frame #5: <unknown function> + 0x2d3b74b0 (0x7effb7c104b0 in /fsx/users/dberard/pytorch/torch/lib/libtorch_cuda_cu.so)
frame #6: torch::jit::fuser::cuda::FusionKernelRuntime::runKernelWithInput(c10::ArrayRef<c10::IValue> const&, unsigned long, torch::jit::fuser::cuda::SegmentedGroup*) + 0x5aa (0x7effb7c0cbf2 in /fsx/users/dberard/pytorch/torch/lib/libtorch_cuda_cu.so)
frame #7: torch::jit::fuser::cuda::FusionKernelRuntime::runWithInput(c10::ArrayRef<c10::IValue> const&, unsigned long) + 0xa65 (0x7effb7c0df19 in /fsx/users/dberard/pytorch/torch/lib/libtorch_cuda_cu.so)
frame #8: torch::jit::fuser::cuda::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&) + 0x4f8 (0x7effb7c0b862 in /fsx/users/dberard/pytorch/torch/lib/libtorch_cuda_cu.so)
frame #9: <unknown function> + 0x2d3b5daf (0x7effb7c0edaf in /fsx/users/dberard/pytorch/torch/lib/libtorch_cuda_cu.so)
frame #10: <unknown function> + 0x2d48c816 (0x7effb7ce5816 in /fsx/users/dberard/pytorch/torch/lib/libtorch_cuda_cu.so)
frame #11: <unknown function> + 0x2d48d247 (0x7effb7ce6247 in /fsx/users/dberard/pytorch/torch/lib/libtorch_cuda_cu.so)
frame #12: torch::jit::fuser::cuda::runCudaFusionGroup(torch::jit::Node const*, std::vector<c10::IValue, std::allocator<c10::IValue> >&) + 0x2c5 (0x7effb7ce65e8 in /fsx/users/dberard/pytorch/torch/lib/libtorch_cuda_cu.so)
frame #13: torch::jit::fuser::cuda::runFusionGroup(torch::jit::Node const*, std::vector<c10::IValue, std::allocator<c10::IValue> >&) + 0x73 (0x7effc4a77e43 in /fsx/users/dberard/pytorch/torch/lib/libtorch_cpu.so)
```

cc @jjsjann123 

### Versions
p4d24xlarge - A100s
master - commit `c2d4e201a33f7093c2325a93fa4d38555b74aef2`

**Comment by ngimel** [comment]
On repeated runs with CUDA_LAUNCH_BLOCKING misaligned address or IMA is thrown with the stack trace below:
```
import torch

def fn(t1, t2, t3, t4, i1: int, i2: int):
    v1 = torch.sub(t3, t4, alpha=i2)
    v2 = torch.mul(v1, t2)
    v4 = torch.add(t1, v2, alpha=i1)
    v5 = torch._softmax(v4, -1, False)
    v6 = torch.reshape(v5, [12, 64, 4096])
    return v6

with torch.jit.fuser("fuser2"):
    fn_s = torch.jit.script(fn)
    other_dtype = torch.double
    t1 = torch.rand((12, 64, 4096), dtype=torch.float).cuda()
    t2 = torch.rand((), dtype=other_dtype).cuda()
    t3 = torch.rand((), dtype=other_dtype).cuda()
    t4 = torch.rand((1, 1, 1, 4096), dtype=torch.float).cuda()

    fn_s(t1, t2, t3, t4, 1, 1)
    fn_s(t1, t2, t3, t4, 1, 1)
    fn_s(t1, t2, t3, t4, 1, 1)
    torch.cuda.synchronize()
```
```
Thread 1 "python" hit Catchpoint 1 (exception thrown), 0x00007fffb4af97c1 in __cxa_throw () from /lib64/libstdc++.so.6
(gdb) bt
#0  0x00007fffb4af97c1 in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x00007fffa268f4d9 in c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) [clone .cold.73] () from /data/users/ngimel/pytorch/torch/lib/libc10.so
#2  0x00007fffa576f9f9 in torch::jit::fuser::cuda::schedulePointwise(torch::jit::fuser::cuda::Fusion*, torch::jit::fuser::cuda::PointwiseParams const&) ()
   from /data/users/ngimel/pytorch/torch/lib/libtorch_cuda.so
#3  0x00007fffa577eba6 in torch::jit::fuser::cuda::(anonymous namespace)::PointWiseScheduler::schedule(torch::jit::fuser::cuda::Fusion*) ()
   from /data/users/ngimel/pytorch/torch/lib/libtorch_cuda.so
#4  0x00007fffa56b8048 in torch::jit::fuser::cuda::FusionKernelRuntime::runKernelWithInput(c10::ArrayRef<c10::IValue> const&, unsigned long, torch::jit::fuser::cuda::SegmentedGroup*) () from /data/users/ngimel/pytorch/torch/lib/libtorch_cuda.so
#5  0x00007fffa56b8a85 in torch::jit::fuser::cuda::FusionKernelRuntime::runWithInput(c10::ArrayRef<c10::IValue> const&, unsigned long) ()
   from /data/users/ngimel/pytorch/torch/lib/libtorch_cuda.so
#6  0x00007fffa56b9a82 in torch::jit::fuser::cuda::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&) ()
   from /data/users/ngimel/pytorch/torch/lib/libtorch_cuda.so
#7  0x00007fffa56ba089 in torch::jit::fuser::cuda::GraphCache::runGraphWithInputs(c10::ArrayRef<c10::IValue> const&) () from /data/users/ngimel/pytorch/torch/lib/libtorch_cuda.so
#8  0x00007fffa57247d2 in torch::jit::fuser::cuda::runCudaFusionGroup(torch::jit::Node const*, std::vector<c10::IValue, std::allocator<c10::IValue> >&)::{lambda()#3}::operator()() const [clone .isra.1051] () from /data/users/ngimel/pytorch/torch/lib/libtorch_cuda.so
#9  0x00007fffa57254ad in torch::jit::fuser::cuda::runCudaFusionGroup(torch::jit::Node const*, std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /data/users/ngimel/pytorch/torch/lib/libtorch_cuda.so
```

**Comment by jjsjann123** [comment]
hmmm, is this a reliable repro?

running on upstream master I don't get the repro from the given script. What GPU is used here?

**Comment by davidberard98** [comment]
Interesting. It was on A100. I'll re-run on master and see if it's still happening

**Comment by jjsjann123** [comment]
Let me try A100. I was running with a volta and ampere might give me a different schedule.

**Comment by ngimel** [comment]
I'm on V100, it repros reliably for me, and I have a fresh build.

**Comment by ngimel** [comment]
```
(pytorch) [ngimel@devgpu006.prn1 ~/local/playground] cat softmax_bug_nvfuser.py
import torch

def fn(t1, t2, t3, t4, i1: int, i2: int):
    v1 = torch.sub(t3, t4, alpha=i2)
    v2 = torch.mul(v1, t2)
    v4 = torch.add(t1, v2, alpha=i1)
    v5 = torch._softmax(v4, -1, False)
    v6 = torch.reshape(v5, [12, 64, 4096])
    return v6

with torch.jit.fuser("fuser2"):
    fn_s = torch.jit.script(fn)
    other_dtype = torch.double
    t1 = torch.rand((12, 64, 4096), dtype=torch.float).cuda()
    t2 = torch.rand((), dtype=other_dtype).cuda()
    t3 = torch.rand((), dtype=other_dtype).cuda()
    t4 = torch.rand((1, 1, 1, 4096), dtype=torch.float).cuda()

    fn_s(t1, t2, t3, t4, 1, 1)
    fn_s(t1, t2, t3, t4, 1, 1)
    fn_s(t1, t2, t3, t4, 1, 1)
    torch.cuda.synchronize()
(pytorch) [ngimel@devgpu006.prn1 ~/local/playground] CUDA_LAUNCH_BLOCKING=1 python softmax_bug_nvfuser.py 
/data/users/ngimel/playground/softmax_bug_nvfuser.py:20: UserWarning: FALLBACK path has been taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback pathvia setting the env variable`export PYTORCH_NVFUSER_DISABLE_FALLBACK=1` (Triggered internally at  /data/users/ngimel/pytorch/torch/csrc/jit/codegen/cuda/manager.cpp:273.)
  fn_s(t1, t2, t3, t4, 1, 1)
/data/users/ngimel/playground/softmax_bug_nvfuser.py:21: UserWarning: FALLBACK path has been taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback pathvia setting the env variable`export PYTORCH_NVFUSER_DISABLE_FALLBACK=1` (Triggered internally at  /data/users/ngimel/pytorch/torch/csrc/jit/codegen/cuda/manager.cpp:273.)
  fn_s(t1, t2, t3, t4, 1, 1)
Traceback (most recent call last):
  File "/data/users/ngimel/playground/softmax_bug_nvfuser.py", line 21, in <module>
    fn_s(t1, t2, t3, t4, 1, 1)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/data/users/ngimel/playground/softmax_bug_nvfuser.py", line 4, in fallback_cuda_fuser
def fn(t1, t2, t3, t4, i1: int, i2: int):
    v1 = torch.sub(t3, t4, alpha=i2)
         ~~~~~~~~~ <--- HERE
    v2 = torch.mul(v1, t2)
    v4 = torch.add(t1, v2, alpha=i1)
RuntimeError: CUDA error: an illegal memory access was encountered
```
I'm at 20bf0d4502 from Apr 11

**Comment by jjsjann123** [comment]
Looks like the reshape PR is landed on 4/12. That's what's causing the fallback.

```
commit f7e7af80e035a54f44f0668a4d84d4cf00516ac2
Author: jjsjann123 <jiej@nvidia.com>
Date:   Tue Apr 12 02:43:45 2022 +0000

    disabling reshape
    
    Fixes #75282
    
    Temporarily disables reshape to avoid codegen failure.
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/75539
    Approved by: https://github.com/davidberard98
```

But the IMA after the fallback looks a little suspicious. I'm still waiting on my build I can dig it a little bit more after that.

**Comment by ngimel** [comment]
On a fresh master (with disabled reshape) I don't have IMA (but too many resources could still be present on A100)

**Comment by ngimel** [comment]
But fusion produces fp64 output, whereas eager execution (as expected) produces fp32.

**Comment by jjsjann123** [comment]
Yeah, I'm still trying to get an A100.. will try that later.
Also note the type propagation. will double check on that as well.

**Comment by jjsjann123** [comment]
Strangely I don't have a repro with the resource issue on A100. Mind sharing your driver/CUDA version? @davidberard98 

type propagation I can see what's wrong. Our type propagation didn't special case scalar tensor, which we should do. More over, this gets me to think maybe we do NOT want to do type propagation when we have profile information on output of a node and should rely on profiled information instead. :confused:  <- I'll put a quick fix with PR on this and open an issue to figure out what we want to do in the long term.

**Comment by davidberard98** [comment]
```
Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1051-aws-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: A100-SXM4-40GB
Nvidia driver version: 450.119.03
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
```

**Comment by davidberard98** [comment]
@jjsjann123 I'm running into a similar issue on autogen-69, maybe you can check there to see if you hit any fallbacks?

**Comment by jjsjann123** [comment]
> @jjsjann123 I'm running into a similar issue on autogen-69, maybe you can check there to see if you hit any fallbacks?

Ha, thanks for that, let me see if I got lucky there.

I tried to re-run the simpler script on a similar setup (different driver with same CUDA toolkit) machine but didn't get repro. Maybe I should also try to run the real microbenchmark there.
:cry:

**Comment by jjsjann123** [comment]
FYI, I don't have the repro but I figured out a cheesy way to verify the breakage.

Looks like register cap we put there just didn't work for CUDA 11.1. (Thanks to @davidberard98 's log file with debug dump). Will keep you guys updated on the progress of patch
