### ISSUE TITLE
error with having `torch` as a requirement for travis-ci builds

### ISSUE THREAD

**Issue by willfrey** [pytorch/pytorch#759]
```
Collecting torch (from -r requirements.txt (line 4))
  Downloading torch-0.1.tar.gz (286kB)
    100% |################################| 286kB 1.9MB/s 
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-cDqZB1/torch/setup.py", line 12, in <module>
        from tools.setup_helpers.env import check_env_flag
    ImportError: No module named setup_helpers.env
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-cDqZB1/torch/setup.py", line 12, in <module>
    
        from tools.setup_helpers.env import check_env_flag
    
    ImportError: No module named setup_helpers.env
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cDqZB1/torch
The command "pip install -r requirements.txt" failed and exited with 1 during .
```

I see that `pytorch` (under the package name `torch`) is available on PyPI now. However, I don't seem to be able to properly install it using travis-ci.

Any suggestions?

**Comment by soumith** [comment]
someone must've upoaded it to pypi (unfortunately). this sucks.
in your travis-ci script, you prob need to install torch before-hand, maybe from the wheel file...

**Comment by szagoruyko** [comment]
I have it set up for tnt here https://github.com/pytorch/tnt/blob/master/.travis.yml, only py2 though

**Comment by soumith** [comment]
closing this for now, having a pypi `torch` package is tracked separately
