### ISSUE TITLE
test_jit.py TestWarn.test_warn and friends doesn't work under pytest

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#76013]
### 🐛 Describe the bug

```
pytest test/test_jit.py -k test_warn
```

gives

```
__________________________ TestWarn.test_warn_once_per_func ___________________________
Traceback (most recent call last):                                                       File "/data/users/ezyang/pytorch-tmp/test/jit/test_warn.py", line 93, in test_warn_on
ce_per_func                                
    FileCheck() \
RuntimeError: Expected to find "UserWarning: I am warning you" but did not find it
Searched string:                                                                       From CHECK-COUNT-2: UserWarning: I am warning you
                                           
______________________ TestWarn.test_warn_once_per_func_in_loop _______________________
Traceback (most recent call last):                                                     
  File "/data/users/ezyang/pytorch-tmp/test/jit/test_warn.py", line 117, in test_warn_once_per_func_in_loop
    FileCheck() \                          
RuntimeError: Expected to find "UserWarning: I am warning you" but did not find it
Searched string:                                                                       
From CHECK-COUNT-2: UserWarning: I am warning you                                                           
____________________________ TestWarn.test_warn_only_once _____________________________
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/test/jit/test_warn.py", line 50, in test_warn_on
ly_once                                                                                    FileCheck() \
RuntimeError: Expected to find "UserWarning: I am warning you" but did not find it
Searched string:
From CHECK-COUNT-1: UserWarning: I am warning you
```

The warnings then show up in warnings summary so probably there's something going on with pytest's installed warning handler

### Versions

master

**Comment by ezyang** [comment]
This still is failing

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
