### ISSUE TITLE
NVFuser opinfos failing accuracy & dtype checks

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#76046]
### 🐛 Describe the bug

Failing from https://github.com/pytorch/pytorch/runs/6070354238?check_suite_focus=true

These began failing after fixing the issue with opinfo configurations that was preventing the nvfuser code from actually running (it seems like it would compile, but it would never run)

Accuracy:
* test_nvfuser_correctness__masked_var_cuda_float16
* test_nvfuser_correctness_lerp_cuda_float16
* test_nvfuser_correctness_nn_functional_gaussian_nll_loss_cuda_float16
* test_nvfuser_correctness_nn_functional_linear_cuda_float16
* test_nvfuser_correctness_nn_functional_local_response_norm_cuda_float16
* test_nvfuser_correctness_nn_functional_multilabel_soft_margin_loss_cuda_float16
* test_nvfuser_correctness_nn_functional_tanhshrink_cuda_float16

Failing dtype:
* test_nvfuser_correctness_add_cuda_bool
* test_nvfuser_correctness_addcmul_cuda_int32
* test_nvfuser_correctness_addcmul_cuda_int64
* test_nvfuser_correctness_clamp_scalar_cuda_int32
* test_nvfuser_correctness_clamp_scalar_cuda_int64
* test_nvfuser_correctness_squeeze_cuda_bool

logs: 
```
======================================================================
FAIL [1.486s]: test_nvfuser_correctness__masked_var_cuda_float16 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 5 (20.0%)
Greatest absolute difference: 0.0078125 at index (0, 1) (up to 1e-05 allowed)
Greatest relative difference: 0.00133422281521014 at index (0, 1) (up to 0.001 allowed)


======================================================================
FAIL [0.422s]: test_nvfuser_correctness_add_cuda_bool (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: The values for attribute 'dtype' do not match: torch.bool != torch.int64.

======================================================================
FAIL [0.480s]: test_nvfuser_correctness_addcmul_cuda_int32 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: The values for attribute 'dtype' do not match: torch.int32 != torch.float64.

======================================================================
FAIL [0.549s]: test_nvfuser_correctness_addcmul_cuda_int64 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: The values for attribute 'dtype' do not match: torch.int64 != torch.float64.

======================================================================
FAIL [0.637s]: test_nvfuser_correctness_clamp_scalar_cuda_int32 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: The values for attribute 'dtype' do not match: torch.int32 != torch.float64.

======================================================================
FAIL [0.708s]: test_nvfuser_correctness_clamp_scalar_cuda_int64 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: The values for attribute 'dtype' do not match: torch.int64 != torch.float64.

======================================================================
FAIL [0.231s]: test_nvfuser_correctness_lerp_cuda_float16 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 4 / 25 (16.0%)
Greatest absolute difference: 0.00390625 at index (0, 4) (up to 1e-05 allowed)
Greatest relative difference: 0.002967359050445104 at index (1, 2) (up to 0.001 allowed)


======================================================================
FAIL [1.004s]: test_nvfuser_correctness_nn_functional_gaussian_nll_loss_cuda_float16 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 5 (20.0%)
Greatest absolute difference: 0.03125 at index (0,) (up to 1e-05 allowed)
Greatest relative difference: 0.0017793594306049821 at index (0,) (up to 0.001 allowed)


======================================================================
FAIL [0.474s]: test_nvfuser_correctness_nn_functional_linear_cuda_float16 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 32 (3.1%)
Greatest absolute difference: 0.00048828125 at index (1, 3) (up to 1e-05 allowed)
Greatest relative difference: 0.0011261261261261261 at index (1, 3) (up to 0.001 allowed)


======================================================================
FAIL [2.349s]: test_nvfuser_correctness_nn_functional_local_response_norm_cuda_float16 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 18 (5.6%)
Greatest absolute difference: 0.0078125 at index (0, 4, 2) (up to 1e-05 allowed)
Greatest relative difference: 0.0012091898428053204 at index (0, 4, 2) (up to 0.001 allowed)


======================================================================
FAIL [0.252s]: test_nvfuser_correctness_nn_functional_multilabel_soft_margin_loss_cuda_float16 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Scalars are not close!

Absolute difference: 0.0078125 (up to 1e-05 allowed)
Relative difference: 0.001589825119236884 (up to 0.001 allowed)


======================================================================
FAIL [0.215s]: test_nvfuser_correctness_nn_functional_tanhshrink_cuda_float16 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 20 (5.0%)
Greatest absolute difference: 0.0001220703125 at index (12,) (up to 1e-05 allowed)
Greatest relative difference: 0.001996007984031936 at index (12,) (up to 0.001 allowed)


======================================================================
FAIL [0.206s]: test_nvfuser_correctness_squeeze_cuda_bool (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1790, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1097, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_jit_cuda_fuser.py", line 4560, in test_nvfuser_correctness
    self.assertEqual(ref, val)
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2170, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: The values for attribute 'dtype' do not match: torch.bool != torch.int64.

----------------------------------------------------------------------
Ran 4751 tests in 2184.730s

FAILED (failures=13, skipped=211, expected failures=34, unexpected successes=5)

Generating XML reports...
Generated XML report: test-reports/python-unittest/test_jit_cuda_fuser/TEST-TestCudaFuser-20220419002252.xml
Generated XML report: test-reports/python-unittest/test_jit_cuda_fuser/TEST-TestCudaFuserOpInfoCUDA-20220419002252.xml
Generated XML report: test-reports/python-unittest/test_jit_cuda_fuser/TEST-jit.test_fuser_common.TestFuserCommon-20220419002252.xml
Generated XML report: test-reports/python-unittest/test_jit_cuda_fuser/TEST-TestPassManagerCudaFuser-20220419002252.xml
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/run_test.py", line 1058, in <module>
    main()
  File "/var/lib/jenkins/workspace/test/run_test.py", line 1036, in main
    raise RuntimeError(err_message)
RuntimeError: test_jit_cuda_fuser failed!
```

### Versions

master, A100 aws cluster.

**Comment by jjsjann123** [comment]
This one looks fun.

From looking at accuracy, seems to be just numerical issue with float16. We do promote math to fp32 inside kernel... maybe that's the reason for the diff.
```
Mismatched elements: 1 / 5 (20.0%)
Greatest absolute difference: 0.0078125 at index (0, 1) (up to 1e-05 allowed)
Greatest relative difference: 0.00133422281521014 at index (0, 1) (up to 0.001 allowed)
```

dtype will be fun... :) Natalia also pointed this out in the other clamp issue. We can try to patch it in type propagation, but I think it would make more sense for us to peek at the profiled dtype (when it's available) on outputs and do cast at the same time.

cc'ing @kevinstephano @ngimel

**Comment by jjsjann123** [comment]
Do tests error out on ToT master, I think the PR that enables them have been merged already but Ryan seems to not get the repro. cc'ing @rdspring1

**Comment by davidberard98** [comment]
sorry, PR hasn't been merged yet https://github.com/pytorch/pytorch/pull/76000

**Comment by jjsjann123** [comment]
Lerp issue is getting addressed in https://github.com/csarofeen/pytorch/pull/1612

**Comment by jjsjann123** [comment]
On #76459 I don't see tanhshrink failure...
```
root@651e4074af8c:/opt/pytorch/pytorch/test# PYTORCH_TEST_WITH_SLOW=1 python test_jit_cuda_fuser.py -v TestCudaFuserOpInfoCUDA.test_nvfuser_correctness_nn_functional_tanhshrink_cuda_float16


test_nvfuser_correctness_nn_functional_tanhshrink_cuda_float16 (__main__.TestCudaFuserOpInfoCUDA) ... ok

----------------------------------------------------------------------
Ran 1 test in 7.779s

OK
```

Looking at the test, nvfuser handles math in fp32, reference is decompose op in fp16, so I think numerical difference is expected. Do you think it make sense to enable it and have a tolerance override?

**Comment by davidberard98** [comment]
re: tanhshrink - I saw that some of the accuracy failures depend on the inputs: I suspect that depending on what other tests occur before or after, the random inputs will change and this might cause the tests to fail depending on which tests come before the test in question

**Comment by jjsjann123** [comment]
Type promotion has been fixed in https://github.com/pytorch/pytorch/pull/76343/files

**Comment by jjsjann123** [comment]
The remaining one with lerp is patched in: https://github.com/pytorch/pytorch/pull/76459

**Comment by jjsjann123** [comment]
I believe all issues have been patched. This one should be good to close :tada:
