### ISSUE TITLE
HIPFFT_EXEC_FAILED when using AMD GPU run FFT

### ISSUE THREAD

**Issue by CryoSky** [pytorch/pytorch#76071]
### 🐛 Describe the bug

When running the following function in my code, it reports an error:

The code is:
```
import torch
import torch.nn as nn
import torch.fft
import torch.cuda

...

def fft_loss(patterson, electron_density):
    patterson = patterson[0,0,:,:,:]
    electron_density = electron_density[0,0,:,:,:]
    f1 = torch.fft.fftn(electron_density)
    f2 = torch.fft.fftn(torch.roll(torch.flip(electron_density, [0, 1, 2]), shifts=(1, 1, 1), dims=(0, 1, 2)))
    f3 = torch.mul(f1,f2)
    #f3 = torch.mul(f1.real,f1.real)
    f4 = torch.fft.ifftn(f3)
    f4 = f4.real

    vx = f4 - torch.mean(f4)
    vy = patterson - torch.mean(patterson)

    cost = (torch.sum(vx * vy) / (torch.sqrt(torch.sum(torch.square(vx)) + epsilon) * torch.sqrt(torch.sum(torch.square(vy)) + epsilon)))
    return cost
```

The patterson and electron_density are all tensors.

The error is:
Traceback (most recent call last):
  File "20220418_draft_seblock_20.py", line 274, in <module>
    loss5 = fft_loss(x, yhat)
  File "20220418_draft_seblock_20.py", line 187, in fft_loss
    f1 = torch.fft.fftn(electron_density)
RuntimeError: cuFFT error: HIPFFT_EXEC_FAILED

I'm doubting the AMD GPU doesn't support some of the FFT module? The same script runs successfully on NVIDIA GPUs.

Best,
Sky

### Versions

PyTorch version: 1.8.0a0+56b43f4
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 4.2.21155-37cb3a34

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 11.2.0
Clang version: 3.4.2 (tags/RELEASE_34/dot2-final)
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.8.9 (default, Jan 26 2022, 00:42:48)  [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] (64-bit runtime)
Python platform: Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Vega 20
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 3.27.5
MIOpen runtime version: 2.11.0
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.1
[pip3] torch==1.8.0a0+56b43f4
[pip3] torchvision==0.9.0a0+01dfa8e
[conda] Could not collect

**Comment by eshnEnergiDanmark** [comment]
I get the exact same error on an AMD GpU
