### ISSUE TITLE
RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\caffe2\serialize\inline_container.cc:300]

### ISSUE THREAD

**Issue by JeffersonQin** [pytorch/pytorch#76108]
### 🐛 Describe the bug

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py:380, in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
    379 with _open_zipfile_writer(opened_file) as opened_zipfile:
--> 380     _save(obj, opened_zipfile, pickle_module, pickle_protocol)
    381     return

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py:604, in _save(obj, zip_file, pickle_module, pickle_protocol)
    603 num_bytes = storage.nbytes()
--> 604 zip_file.write_record(name, storage.data_ptr(), num_bytes)

RuntimeError: Could not allocate bytes object!

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
Input In [4], in <cell line: 7>()
      4     if epoch < 115: return 0.001
      5     if epoch < 145: return 0.0001
----> 7 yolo.train(net, train_iter, test_iter, 145, lr=lr, momentum=0.9, weight_decay=5e-4, device='cuda', accum_batch_num=4, save_path='./model')

File ~\Desktop\yolo-v1-pytorch\yolo.py:375, in train(net, train_iter, test_iter, num_epochs, lr, momentum, weight_decay, device, accum_batch_num, save_path, load, load_epoch, pretrained)
    372 	animator.add(epoch + 1, (None, test_l))
    374 # save model
--> 375 torch.save(net.state_dict(), os.path.join(save_path, f'./{time.time_ns()}-epoch-{epoch}.pth'))

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py:381, in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
    379     with _open_zipfile_writer(opened_file) as opened_zipfile:
    380         _save(obj, opened_zipfile, pickle_module, pickle_protocol)
--> 381         return
    382 _legacy_save(obj, opened_file, pickle_module, pickle_protocol)

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py:260, in _open_zipfile_writer_buffer.__exit__(self, *args)
    259 def __exit__(self, *args) -> None:
--> 260     self.file_like.write_end_of_file()
    261     self.buffer.flush()

RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\caffe2\serialize\inline_container.cc:300] . unexpected pos 151863680 vs 151863576
```

### Versions

```
PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070 SUPER
Nvidia driver version: 511.65
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchvision==0.12.0+cu113
[conda] Could not collect
```

**Comment by JeffersonQin** [comment]
I have met the bug couple of times, and have no idea how to reproduce. It seems that when the OS is busy with IO the bug would happen.

**Comment by mruberry** [comment]
Thank you for reporting this issue, @JeffersonQin.

**Comment by Fuchai** [comment]
I encountered the same issue when the disk ran out of space
```
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at inline_container.cc:298] . unexpected pos 74176 vs 74080
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x47 (0x7f7f2a44d7a7 in /home/ubuntu/anaconda/envs/py/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x24f19d0 (0x7f7f2cdbd9d0 in /home/ubuntu/anaconda/envs/py/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
```

**Comment by Mehmaam99** [comment]
I encountered a same issue in windows server. Program smoothly run in local machine but got an error in Windows server machine.
`RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 1342177280 bytes.`

**Comment by JeffersonQin** [comment]
@Mehmaam99 I think your problem is different. It is just caused by OOM.

**Comment by Mehmaam99** [comment]
@JeffersonQin  I try almost everything to resolve this error. More than 70GB of disk space, apply garbage collector, cache clear, but issue is still same. If you have an idea then help me to resolve it.
Thanks

**Comment by JeffersonQin** [comment]
@Mehmaam99 disk space does not matter, you are running out of **memory**.

**Comment by JeffersonQin** [comment]
@Mehmaam99 check your memory usage in task manager (since you are using Windows server), and you can also disable `pin_memory` for DataLoader to save memory.

**Comment by Mehmaam99** [comment]
@JeffersonQin Thanks mate, Finally issue  resolve . I assigned virtual memory to my working directory using swap files. Manually memory allocation of windows server.

**Comment by JeffersonQin** [comment]
@Mehmaam99 Great. Have a nice day.

**Comment by skullyhoofd** [comment]
I'm also running into this error, even though I have ample (>1TB) disk space available. It worked before, but suddenly now it keeps giving this error. I even formatted the drive and the issue persists, so it can't be disk space related I don't think :\

**Comment by lordwildbeast** [comment]
@JeffersonQin how to disable `pin_memory` ?

**Comment by pushpendraaa** [comment]
> @JeffersonQin Thanks mate, Finally issue resolve . I assigned virtual memory to my working directory using swap files. Manually memory allocation of windows server.

Can you please explain what exactly you have done?

**Comment by JViggiani** [comment]
I'm also encountering this issue and pin_memory to false did not resolve it

**Comment by briandw** [comment]
I was running into this as well. It was the case where my disk was full. Can this be error be a little less obtuse? Could it check to see if the disk is full and report that instead?

**Comment by Roy-fyq** [comment]
I have met the same problem. There is the description of my error :
```
Traceback (most recent call last):
  File "/home/code/lstm-free/main.py", line 24, in <module>
    torch.save(trained_model, "/home/code/lstm-free/checkpoint/a.pth")
  File "/home/admin/miniconda3/envs/py_310/lib/python3.10/site-packages/torch/serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/home/admin/miniconda3/envs/py_310/lib/python3.10/site-packages/torch/serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/home/admin/miniconda3/envs/py_310/lib/python3.10/site-packages/torch/serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: File /home/code/lstm-free/checkpoint/a.pth cannot be opened.
```

I have tried many methods to solve it. Finally, I found out that the folder where I stored the model did not have enough ```
permissions. So I added root permissions to him and the problem was solved.

`sudo chmod 777 YourPath`
Hope my answer will be useful.
