### ISSUE TITLE
Test failures for `test_batch_norm_impl_index_correctness` and `test_batch_norm_half`

### ISSUE THREAD

**Issue by casparvl** [pytorch/pytorch#76110]
### 🐛 Describe the bug

Test fails with the following traceback:

<details>
<summary>Long traceback...</summary>

```
======================================================================
FAIL: test_batch_norm_half (__main__.TestCudaFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper
    method(*args, **kwargs)
  File "/tmp/jenkins/build/PyTorch/1.11.0/foss-2021a-CUDA-11.3.1/pytorch/test/test_jit_cuda_fuser.py", line 2840, in test_batch_norm_half
    self._test_batch_norm_impl_index_helper(4, 8, 5, affine, track_running_stats, training, torch.half)
  File "/tmp/jenkins/build/PyTorch/1.11.0/foss-2021a-CUDA-11.3.1/pytorch/test/test_jit_cuda_fuser.py", line 2792, in _test_batch_norm_impl_index_helper
    self.assertGraphContainsExactly(t_jit.graph_for(x), FUSION_GUARD, 1, consider_subgraphs=True)
  File "/tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/testing/_internal/jit_utils.py", line 324, in assertGraphContainsExactly
    perform_assert(graph, kind, count, num_kind_nodes,
  File "/tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/testing/_internal/jit_utils.py", line 317, in perform_assert
    raise AssertionError(
AssertionError: graph(%self : __torch__.MyModule,
      %x.1 : Tensor):
  %2 : float = prim::Constant[value=1.0000000000000001e-05]() # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:179:12
  %3 : float = prim::Constant[value=0.10000000000000001]()
  %4 : int = prim::Constant[value=1]() # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:148:46
  %5 : int = prim::Constant[value=4]() # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:406:26
  %6 : str = prim::Constant[value="expected 4D input (got {}D input)"]() # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:407:29
  %7 : NoneType = prim::Constant()
  %8 : str = prim::Constant[value="Expected more than 1 value per channel when training, got input size {}"]() # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/fu
nctional.py:2387:25
  %9 : int = prim::Constant[value=0]() # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2383:22
  %10 : int = prim::Constant[value=2]() # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2384:31
  %11 : bool = prim::Constant[value=1]() # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2422:81
  %12 : float = prim::Constant[value=2.]() # /tmp/jenkins/build/PyTorch/1.11.0/foss-2021a-CUDA-11.3.1/pytorch/test/test_jit_cuda_fuser.py:2738:24
  %bn : __torch__.torch.nn.modules.batchnorm.BatchNorm2d = prim::GetAttr[name="bn"](%self)
  %o.10 : Tensor = aten::mul(%x.1, %12) # /tmp/jenkins/build/PyTorch/1.11.0/foss-2021a-CUDA-11.3.1/pytorch/test/test_jit_cuda_fuser.py:2738:20
  %15 : int = aten::dim(%o.10) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:406:11
  %16 : bool = aten::ne(%15, %5) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:406:11
   = prim::If(%16) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:406:8
    block0():
      %17 : str = aten::format(%6, %15) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:407:29
       = prim::RaiseException(%17, %7) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:407:12
      -> ()
    block1():
      -> ()
  %training.1 : bool = prim::GetAttr[name="training"](%bn)
   = prim::If(%training.1) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:145:11
    block0():
      %num_batches_tracked.7 : Tensor = prim::GetAttr[name="num_batches_tracked"](%bn)
      %20 : Tensor = aten::add_(%num_batches_tracked.7, %4, %4) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py:148:16
      -> ()
    block1():
      -> ()
  %running_mean : Tensor = prim::GetAttr[name="running_mean"](%bn)
  %running_var : Tensor = prim::GetAttr[name="running_var"](%bn)
  %weight : Tensor = prim::GetAttr[name="weight"](%bn)
  %bias : Tensor = prim::GetAttr[name="bias"](%bn)
   = prim::If(%training.1) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2418:4
    block0():
      %25 : int[] = aten::size(%o.10) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2419:27
      %size_prods.1 : int = aten::__getitem__(%25, %9) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2383:17
      %27 : int = aten::len(%25) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2384:19
      %28 : int = aten::sub(%27, %10) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2384:19
      %29 : int = prim::Constant[value=8]()
      %30 : int = aten::__round_to_zero_floordiv(%28, %29)
      %31 : int = aten::mul(%30, %29)
      %32 : int = aten::sub(%28, %31)
      %33 : int, %size_prods.2 : int = prim::Loop(%30, %11, %9, %size_prods.1) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2384:4
        block0(%i.2 : int, %36 : int, %size_prods.12 : int):
          %38 : int = aten::add(%36, %10) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:27
          %39 : int = aten::__getitem__(%25, %38) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:22
          %size_prods.16 : int = aten::mul(%size_prods.12, %39) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:8
          %41 : int = prim::Constant[value=3]()
          %42 : int = aten::add(%36, %41) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:27
          %43 : int = aten::__getitem__(%25, %42) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:22
          %size_prods.20 : int = aten::mul(%size_prods.16, %43) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:8
          %45 : int = aten::add(%36, %5) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:27
          %46 : int = aten::__getitem__(%25, %45) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:22
          %size_prods.22 : int = aten::mul(%size_prods.20, %46) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:8
          %48 : int = prim::Constant[value=5]()
          %49 : int = aten::add(%36, %48) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:27
          %50 : int = aten::__getitem__(%25, %49) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:22
          %size_prods.24 : int = aten::mul(%size_prods.22, %50) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:8
          %52 : int = prim::Constant[value=6]()
          %53 : int = aten::add(%36, %52) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:27
          %54 : int = aten::__getitem__(%25, %53) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:22
          %size_prods.26 : int = aten::mul(%size_prods.24, %54) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:8
          %56 : int = prim::Constant[value=7]()
          %57 : int = aten::add(%36, %56) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:27
          %58 : int = aten::__getitem__(%25, %57) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:22
          %size_prods.28 : int = aten::mul(%size_prods.26, %58) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:8
          %60 : int = aten::add(%36, %29) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:27
          %61 : int = aten::__getitem__(%25, %60) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:22
          %size_prods.30 : int = aten::mul(%size_prods.28, %61) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:8
          %63 : int = prim::Constant[value=9]()
          %64 : int = aten::add(%36, %63) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:27
          %65 : int = aten::__getitem__(%25, %64) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:22
          %size_prods.32 : int = aten::mul(%size_prods.30, %65) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:8
          -> (%11, %60, %size_prods.32)
      %67 : int, %size_prods : int = prim::Loop(%32, %11, %33, %size_prods.2) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2384:4
        block0(%i.1 : int, %70 : int, %size_prods.11 : int):
          %72 : int = aten::add(%70, %10) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:27
          %73 : int = aten::__getitem__(%25, %72) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:22
          %size_prods.14 : int = aten::mul(%size_prods.11, %73) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2385:8
          %75 : int = aten::add(%70, %4)
          -> (%11, %75, %size_prods.14)
      %76 : bool = aten::eq(%size_prods, %4) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2386:7
       = prim::If(%76) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2386:4
        block0():
       = prim::If(%76) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2386:4
        block0():
          %77 : str = aten::format(%8, %25) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2387:25
           = prim::RaiseException(%77, %7) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2387:8
          -> ()
        block1():
          -> ()
      -> ()
    block1():
      -> ()
  %o.6 : Tensor = aten::batch_norm(%o.10, %weight, %bias, %running_mean, %running_var, %training.1, %3, %2, %11) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2421:11
  return (%o.6)

Error: graph contains 0 prim::CudaFusionGuard nodes (including subgraphs) but expected 1
```

</details>

The one for `test_batch_norm_impl_index_correctness` looks very similar (I won't fully include it here due to it's length):

```
======================================================================
FAIL: test_batch_norm_impl_index_correctness (__main__.TestCudaFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper
    method(*args, **kwargs)
  File "/tmp/jenkins/build/PyTorch/1.11.0/foss-2021a-CUDA-11.3.1/pytorch/test/test_jit_cuda_fuser.py", line 2865, in test_batch_norm_impl_index_correctness
    self._test_batch_norm_impl_index_helper(b, c, hw, affine, track_running_stats, training)
  File "/tmp/jenkins/build/PyTorch/1.11.0/foss-2021a-CUDA-11.3.1/pytorch/test/test_jit_cuda_fuser.py", line 2792, in _test_batch_norm_impl_index_helper
    self.assertGraphContainsExactly(t_jit.graph_for(x), FUSION_GUARD, 1, consider_subgraphs=True)
  File "/tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/testing/_internal/jit_utils.py", line 324, in assertGraphContainsExactly
    perform_assert(graph, kind, count, num_kind_nodes,
  File "/tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/testing/_internal/jit_utils.py", line 317, in perform_assert
    raise AssertionError(
AssertionError: graph(%self : __torch__.MyModule,
      %x.1 : Tensor):
...
  %o.6 : Tensor = aten::batch_norm(%o.10, %weight, %bias, %running_mean, %running_var, %training.1, %3, %2, %11) # /tmp/jenkins/tmp/eb-76qv_eih/tmpugsapggj/lib/python3.9/site-packages/torch/nn/functional.py:2421:11
  return (%o.6)

Error: graph contains 0 prim::CudaFusionGuard nodes (including subgraphs) but expected 1
```

Similar errors are mentioned [here](https://github.com/pytorch/pytorch/issues/75029), but not sure if it's in any way related...

### Versions

This PyTorch was built from sources:

```
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux 8.4 (Ootpa) (x86_64)
GCC version: (GCC) 10.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.9.5 (default, Oct  8 2021, 23:16:43)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.18.0-305.34.2.el8_4.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] torch==1.11.0
[conda] Could not collect
```
The cuDNN version is not displayed by the script for some reason, but is 8.2.1.32.

**Comment by xwang233** [comment]
cc @jjsjann123

**Comment by eellison** [comment]
I think you're running a new test with an old version of pytorch. Do you mind repro-ing on master ? Closing, feel free to re-open if you run into this on master.

**Comment by casparvl** [comment]
> I think you're running a new test with an old version of pytorch

I'm not sure what you mean by this comment. I've compiled from the 1.11.0 tagged release, [this test](https://github.com/pytorch/pytorch/blob/v1.11.0/test/test_jit_cuda_fuser.py#L2839) came with the sources for that release, so it should work, right? Or am I missing something here? 

Maybe a bit of context: I'm managing an HPC cluster, and would like to offer PyTorch 1.11 on this cluster. My main concern is whether the installation is correct, hence my desire to run (and succesfully complete) the test suite on my from-source build. If a test fails, I'd mainly care if this test fails because the installation somehow does not perform well / produces incorrect results, as that would clearly be bad for my users.
