### ISSUE TITLE
ONNX - .view() function doesn't seem to export valid Reshape 

### ISSUE THREAD

**Issue by morgangiraud** [pytorch/pytorch#7612]
## Issue description
Exporting to ONNX as reshape call,  `onnx.checker.check_model()` function returns `onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].`

## Code example

```python
import torch
import torch.nn as nn

import torch.onnx
import onnx

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

    def forward(self, x):
        return x.view(-1, 784)

model = Net()
x = torch.randn(64, 1, 28, 28, requires_grad=True)
torch_out = torch.onnx._export(model, x, "view.proto", export_params=True, verbose=True)
model = onnx.load("view.proto")
onnx.checker.check_model(model)    
```

Output:
```
graph(%0 : Float(64, 1, 28, 28)) {
  %1 : Dynamic = onnx::Constant[value=  -1  784 [ CPULongTensor{2} ]](), scope: Net
  %2 : Float(64, 784) = onnx::Reshape(%0, %1), scope: Net
  return (%2);
}

Traceback (most recent call last):
  File "test_view.py", line 19, in <module>
    onnx.checker.check_model(model)    
  File "/Users/morgangiraud/miniconda3/lib/python3.6/site-packages/onnx/checker.py", line 77, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].

==> Context: Bad node spec: input: "0" input: "1" output: "2" op_type: "Reshape"
```

## System Info

PyTorch version: 0.5.0a0+6eec411 **(also tested with version 0.4)**
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.4
GCC version: Could not collect
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[conda] pytorch                   0.4.0           py36_cuda0.0_cudnn0.0_1    pytorch
[conda] torch                     0.5.0a0+6eec411           <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by Casablancaaa** [comment]
@morgangiraud Did you solve this problem? I also encountered the same problem.

**Comment by YueshangGu** [comment]
I have got the same question. I try to convert my caffe2 model to onnx but I got the question when convert ResizeNearest op to onnx.
### Error report
```
onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].

==> Context: Bad node spec: input: "fpn_inner_res5_1_sum" input: "OC2_DUMMY_0" output: "fpn_inner_res4_1_sum_topdown" op_type: "Upsample" attribute { name: "mode" s: "nearest" type: STRING }
```

**Comment by rahulbhat44** [comment]
@YueshangGu @morgangiraud  Did you guys solve this problem ??? I am having the same problem. Could you please tell the solution ???

**Comment by garymm** [comment]
The sample code provided by @morgangiraud appears to work OK on latest nightly PyTorch. Can anyone reproduce the issue with latest nightly PyTorch? If so, please provide code.
