### ISSUE TITLE
Calling storage() on lazy tensor does not work

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#76124]
### 🐛 Describe the bug

```
>>> import torch._lazy.ts_backend
>>> torch._lazy.ts_backend.init()
>>> torch.empty(0, device='lazy')
tensor([], device='lazy:0')
>>> torch.empty(0, device='lazy').storage()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/ezyang/pytorch-tmp/torch/_tensor.py", line 206, in storage
    return torch._TypedStorage(wrap_storage=self._storage(), dtype=self.dtype)
RuntimeError: it != attype_to_py_storage_type.end() INTERNAL ASSERT FAILED at "/data/users/ezyang/pytorch-tmp/torch/csrc/DynamicTypes.cpp":69, please report a bug to PyTorch. Failed to get the Python type of `_UntypedStorage`.
```

cc @kurtamohler 

### Versions

master

**Comment by kurtamohler** [comment]
This error no longer happens, probably after #75459, or maybe #78008:

```python
>>> import torch
>>> import torch._lazy.ts_backend
>>> torch._lazy.ts_backend.init()
>>> torch.empty(0, device='lazy')
tensor([], device='lazy:0')
>>> torch.empty(0, device='lazy').storage()
 
[torch.storage._TypedStorage(dtype=torch.float32, device=lazy:0) of size 0]
```

However, this does seem right:

```python
>>> torch.empty(10, device='lazy').storage()
 
[torch.storage._TypedStorage(dtype=torch.float32, device=lazy:0) of size 0]
```

Admittedly, I don't know very much at all about lazy tensors, but I assume the storage size is supposed to be nonzero if the tensor's size is nonzero

**Comment by ezyang** [comment]
This is LTC's problem, @bdhirsh functionalize storages should fix it, so we can close this.
