### ISSUE TITLE
test_license_for_wheel always fails on my local dev copy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#76128]
### 🐛 Describe the bug

```
python test/test_license.py
sE
======================================================================
ERROR: test_license_for_wheel (__main__.TestLicense)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/test/test_license.py", line 27, in test_license_for_wheel
    create_bundled('third_party', current)
  File "/data/users/ezyang/pytorch-tmp/third_party/build_bundled.py", line 41, in create_bundled
    collected = collect_license(d)
  File "/data/users/ezyang/pytorch-tmp/third_party/build_bundled.py", line 19, in collect_license
    raise ValueError('could not identify license file '
ValueError: could not identify license file for third_party/cudnn_frontend

----------------------------------------------------------------------
Ran 2 tests in 0.168s

FAILED (errors=1, skipped=1)
```

this seems to pass on master CI so I guess it's a problem with my local dev env... would be nice to make this test more robust

### Versions

master

cc @mruberry

**Comment by mruberry** [comment]
cc @seemethere

**Comment by seemethere** [comment]
Assigning myself to look into

**Comment by seemethere** [comment]
Linking the original PR for context: https://github.com/pytorch/pytorch/pull/50745

Submitted https://github.com/pytorch/pytorch/pull/76336 to resolve

**Comment by seemethere** [comment]
Closing since https://github.com/pytorch/pytorch/pull/76336 should resolve

**Comment by ezyang** [comment]
This is still failing on my local copy

```
Running test_license ... [2022-08-22 08:35:59.138697]
Executing ['/home/ezyang/local/pytorch-tmp-env/bin/python', '-bb', 'test_license.py'] ... [2022-08-22 08:35:59.138800]
sE
======================================================================
ERROR: test_license_for_wheel (__main__.TestLicense)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_license.py", line 28, in test_license_for_wheel
    with open(license_file) as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'third_party/LICENSES_BUNDLED.txt'

----------------------------------------------------------------------
```

**Comment by ezyang** [comment]
This error seems to be a CWD error. But when I fix it to look for the file in the right place, it complains that it isn't correct.
