### ISSUE TITLE
test_wishart_log_prob fails locally for me

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#76160]
### 🐛 Describe the bug

```
======================================================================
ERROR: test_wishart_log_prob (__main__.TestDistributions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/test/distributions/test_distributions.py", line 2309, in test_wishart_log_prob
    expected = ref_dist.logpdf(x.transpose(0, 2).numpy())
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.9/site-packages/scipy/stats/_multivariate.py", line 2258, in logpdf
    out = self._dist._logpdf(x, self.dim, self.df, self.scale,
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.9/site-packages/scipy/stats/_multivariate.py", line 1851, in _logpdf
    _, log_det_x[i] = self._cholesky_logdet(x[:, :, i])
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.9/site-packages/scipy/stats/_multivariate.py", line 2221, in _cholesky_logdet
    c_decomp = scipy.linalg.cholesky(scale, lower=True)
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.9/site-packages/scipy/linalg/_decomp_cholesky.py", line 88, in cholesky
    c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.9/site-packages/scipy/linalg/_decomp_cholesky.py", line 37, in _cholesky
    raise LinAlgError("%d-th leading minor of the array is not positive "
numpy.linalg.LinAlgError: 3-th leading minor of the array is not positive definite

----------------------------------------------------------------------
```

I have scipy                    1.8.0 installed

### Versions

master

**Comment by neerajprad** [comment]
cc. @nonconvexopt.

I believe there's a small probability of sampling singular values which results in this error. @nonconvexopt: please correct if my understanding is off. I see that we are not fixing the seed here, so it can happen non-deterministically. Let me push a fix for this.

**Comment by nonconvexopt** [comment]
> cc. @nonconvexopt.
> 
> I believe there's a small probability of sampling singular values which results in this error. @nonconvexopt: please correct if my understanding is off. I see that we are not fixing the seed here, so it can happen non-deterministically. Let me push a fix for this.

@neerajprad Thank you for your effort in the maintenance. It is my bad that I didn't applied practical solution for the numerical instability in matrix distributions. Sorry for that I have been also halting the implemenation of the Invese Wishart distribution (#70275) for several months.

This is the second time that the Wishart distribution fails the test with some change in the PyTorch core. Current Implementation of Wishart distribution have surely systematic instabilities in which cannot be tested in current tests. Generalizing the Wishart distribution to singular support and potentially singular samples will experience less problems in testing, but they will make the user to handle the numerical instability by themselves in application. But, I think there are no other possible solution than this except adding more heuristic techniques like clipping, adding small constant and so on. I will open PR to implement the generalized (singular) matrix distributions, too.

**Comment by neerajprad** [comment]
> But, I think there are no other possible solution than this except adding more heuristic techniques like clipping, adding small constant and so on. I will open PR to implement the generalized (singular) matrix distributions.

What does scipy do? For as long as we have a comparable implementation, it is okay to have the user adjust the number of tries for parameter values which are known to be unstable.

**Comment by nonconvexopt** [comment]
> What does scipy do? For as long as we have a comparable implementation, it is okay to have the user adjust the number of tries for parameter values which are known to be unstable.
Thank you for your advice. We can loose the current tests and make users to handle unstability little bit to make implementation and test faster.

These are the implementation and the tests for the Wishart: [multivariate.py](https://github.com/scipy/scipy/blob/653fd090fe18e28254986cd4c446c47b7051ef57/scipy/stats/_multivariate.py#L1619-L2222), [test_multivariate.py](https://github.com/scipy/scipy/blob/653fd090fe18e28254986cd4c446c47b7051ef57/scipy/stats/tests/test_multivariate.py#L852-L1041)
Current PyTorch implementation have almost similar operations to the SciPy. SciPy did not tested Wishart distributions to unstable parameter regions,`ndim - 1 < df < ndim` while we added tests for such challanging cases. And the tests have been raising issues. It will be much easier if we focus on testing general cases.
