### ISSUE TITLE
[ubsan] Undefined behaviour when a running forwardAD CompositeCompliance on `batch_norm`

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#76283]
### 🐛 Describe the bug

PR adding the test: https://github.com/pytorch/pytorch/pull/75178
```
test_forward_ad_nn_functional_batch_norm_cpu_float32 (__main__.TestCompositeComplianceCPU) ... /var/lib/jenkins/workspace/aten/src/ATen/native/Normalization.cpp:191:31: runtime error: -5.368e+38 is outside the range of representable values of type 'float'
[6456](https://github.com/pytorch/pytorch/runs/6134744920?check_suite_focus=true#step:9:6456)
    #0 0x7ff12d00b5c2 in std::tuple<at::Tensor, at::Tensor> at::native::batch_norm_cpu_update_stats_template<float, at::native::InvStd>(at::Tensor const&, at::Tensor const&, at::Tensor const&, double, double)::'lambda'(long, long)::operator()(long, long) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xc0d35c2)
[6457](https://github.com/pytorch/pytorch/runs/6134744920?check_suite_focus=true#step:9:6457)
    #1 0x7ff12cfe75c9 in .omp_outlined..175 (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xc0af5c9)
[6458](https://github.com/pytorch/pytorch/runs/6134744920?check_suite_focus=true#step:9:6458)
    #2 0x7ff11829fbb2 in __kmp_invoke_microtask (/opt/conda/lib/libiomp5.so+0x13fbb2)
[6459](https://github.com/pytorch/pytorch/runs/6134744920?check_suite_focus=true#step:9:6459)
    #3 0x7ff11821b902 in __kmp_invoke_task_func (/opt/conda/lib/libiomp5.so+0xbb902)
[6460](https://github.com/pytorch/pytorch/runs/6134744920?check_suite_focus=true#step:9:6460)
    #4 0x7ff11821d3dd in __kmp_fork_call (/opt/conda/lib/libiomp5.so+0xbd3dd)
[6461](https://github.com/pytorch/pytorch/runs/6134744920?check_suite_focus=true#step:9:6461)
    #5 0x7ff1181ddcb4 in __kmpc_fork_call (/opt/conda/lib/libiomp5.so+0x7dcb4)
[6462](https://github.com/pytorch/pytorch/runs/6134744920?check_suite_focus=true#step:9:6462)
    #6 0x7ff12d00b825 in void at::internal::invoke_parallel<std::tuple<at::Tensor, at::Tensor> at::native::batch_norm_cpu_update_stats_template<float, at::native::InvStd>(at::Tensor const&, at::Tensor const&, at::Tensor const&, double, double)::'lambda'(long, long)>(long, long, long, std::tuple<at::Tensor, at::Tensor> at::native::batch_norm_cpu_update_stats_template<float, at::native::InvStd>(at::Tensor const&, at::Tensor const&, at::Tensor const&, double, double)::'lambda'(long, long) const&) (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xc0d3825)
```

Ref: https://github.com/pytorch/pytorch/runs/6134744920?check_suite_focus=true#step:9:6455

cc: @zou3519 

### Versions

master

cc @ezyang @gchanan @zou3519 @Chillee @albanD @samdow

**Comment by albanD** [comment]
From offline discussion:
We should make sure that the composite compliance test is not reading un-initialized memory which would lead to this.
