### ISSUE TITLE
torch._remove_batch_dim is interceptable by __torch_function__ / batch tensors don't print correctly

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#76294]
### 🐛 Describe the bug

`_add_batch_dim` and `_remove_batch_dim` are supposed to be internal functions that are not user visible. However, `__torch_function__` makes it possible to observe these functions as well as their inputs/outputs, as they are defined in `native_functions.yaml` and correspondingly overrideable via `__torch_function__`. To avoid leaking in this way, I think we probably should have put a torch function handler on `vmap`, the higher order function, itself.

This being said, there is another problem: batch tensors don't print correctly.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/ezyang/pytorch-tmp/torch/_vmap_internals.py", line 271, in wrapped
    batched_outputs = func(*batched_inputs)
  File "<stdin>", line 1, in <lambda>
  File "/data/users/ezyang/pytorch-tmp/torch/_tensor.py", line 338, in __repr__
    return torch._tensor_str._str(self)
  File "/data/users/ezyang/pytorch-tmp/torch/_tensor_str.py", line 443, in _str
    return _str_intern(self)
  File "/data/users/ezyang/pytorch-tmp/torch/_tensor_str.py", line 418, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/data/users/ezyang/pytorch-tmp/torch/_tensor_str.py", line 264, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/data/users/ezyang/pytorch-tmp/torch/_tensor_str.py", line 112, in __init__
    if value != torch.ceil(value):
RuntimeError: Batching rule not implemented for aten::is_nonzero. We could not generate a fallback.
>>> torch.vmap(lambda x: print(x))(torch.randn(2, 2))
```

which makes debugging problems involving batched tensor inputs quite irritating.

@zou3519 this is partially why I added a way of sniffing out batched tensors; random stuff doesn't work with them so I can't treat them uniformly as dense tensors.

### Versions

master

**Comment by ezyang** [comment]
making them install functorch to use the functionality seems very mild, if it means we can unify the UX earlier rather than later
