### ISSUE TITLE
NVFuser failing extremal opinfos

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#76354]
### 🐛 Describe the bug

[failure logs](https://gist.github.com/davidberard98/d6e30e7c888e04cd884397d0e5922139)

- [ ] nn_functional_binary_cross_entropy_with_logits
- [x] nn_functional_conv_transpose3d (#75363)
- [ ] nn_functional_nll_loss
- [ ] nn_functional_prelu
- [ ] unique_consecutive (https://github.com/pytorch/pytorch/issues/76571)
- [ ] unique  (https://github.com/pytorch/pytorch/issues/76571)

### Versions

https://github.com/pytorch/pytorch/runs/6215506399?check_suite_focus=true
CI, https://github.com/pytorch/pytorch/pull/75917

cc @jjsjann123

**Comment by ngimel** [comment]
Of these most are RuntimeErrors, where eager function errors out on invalid inputs. Most of remaining ones involve random number generation one way or another (dropout, normal, randn, rand), I'm not sure we can expect similar results for nvfuser/eager in this case (how does regular OpInfo testing pass?) but NVFuser team can confirm. 
Can we modify the PR to catch eager mode errors and not attempt tracing in this case?

**Comment by jjsjann123** [comment]
The tracing doesn't look right.

When I look at nll_loss failures, I saw `weight` baked in the graph.
```
[DUMP graph_fuser.cpp:2416] Before Compilation:
[DUMP graph_fuser.cpp:2416] graph(%input : Tensor,
[DUMP graph_fuser.cpp:2416]       %target : Tensor):
[DUMP graph_fuser.cpp:2416]   %4 : int = prim::Constant[value=-100]() # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2416]   %3 : int = prim::Constant[value=0]() # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2416]   %2 : NoneType = prim::Constant()
[DUMP graph_fuser.cpp:2416]   %5 : Tensor = aten::nll_loss_nd(%input, %target, %2, %3, %4) # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2416]   return (%5)
[DUMP graph_fuser.cpp:2336] Before Fusion:
[DUMP graph_fuser.cpp:2336] graph(%input : Tensor,
[DUMP graph_fuser.cpp:2336]       %target : Tensor):
[DUMP graph_fuser.cpp:2336]   %4 : int = prim::Constant[value=-100]() # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2336]   %3 : int = prim::Constant[value=0]() # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2336]   %2 : Tensor = prim::Constant[value=-0.4029  2.3053 -4.5879 [ CUDAFloatType{3} ]]() # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2336]   %5 : Tensor = prim::profile[profiled_type=Float(3, strides=[1], requires_grad=0, device=cuda:0), seen_none=0](%2)
[DUMP graph_fuser.cpp:2336]   %6 : Tensor = aten::nll_loss_nd(%input, %target, %5, %3, %4) # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2336]   %7 : Tensor = prim::profile[profiled_type=Float(2, strides=[1], requires_grad=0, device=cuda:0), seen_none=0](%6)
[DUMP graph_fuser.cpp:2336]   return (%7)
[DUMP graph_fuser.cpp:2416] Before Compilation:
[DUMP graph_fuser.cpp:2416] graph(%input : Tensor,
[DUMP graph_fuser.cpp:2416]       %target : Tensor):
[DUMP graph_fuser.cpp:2416]   %4 : int = prim::Constant[value=-100]() # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2416]   %3 : int = prim::Constant[value=0]() # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2416]   %2 : Float(3, strides=[1], requires_grad=0, device=cuda:0) = prim::Constant[value=-0.4029  2.3053 -4.5879 [ CUDAFloatType{3} ]]() # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2416]   %6 : Tensor = aten::nll_loss_nd(%input, %target, %2, %3, %4) # /opt/pytorch/pytorch/torch/nn/functional.py:2636:0
[DUMP graph_fuser.cpp:2416]   return (%6)
```

While it's taking runtime inputs for the reference.
```
inputs:  [tensor([[inf, inf, inf],
        [inf, inf, inf]], device='cuda:0', dtype=torch.float32), tensor([2, 2], device='cuda:0')]
inputs ke:  {'weight': tensor([inf, inf, inf], device='cuda:0', dtype=torch.float32), 'reduction': 'none'}
out val:  tensor([inf, inf], device='cuda:0', dtype=torch.float32)
out ref:  tensor([-inf, -inf], device='cuda:0', dtype=torch.float32)
```

Consider that there's no fusion for nll_loss, it's not likely that's caused by fusion at all :laughing:

**Comment by davidberard98** [comment]
Whoops! Thanks for looking into it - I though there was supposed to be an assert checking for that but apparently it's not working

**Comment by jjsjann123** [comment]
I'm surprised this doesn't fail.. A brief look at the `create_traced_fn` seems like we are not supposed to update non_tensor inputs...

**Comment by jjsjann123** [comment]
Looks like for all the failing cases, we don't even have codegen kernels at all. And they all have kwargs. I think once we fix the tests we should be good. :crossed_fingers:

**Comment by jjsjann123** [comment]
I know we have a PR fixing the traced/runtime kwargs thing but can't find it. I'm running into some more _masked.var/std failures I'm suspecting could be related to that (since my standalone script doesn't give me the repro)..

**Comment by davidberard98** [comment]
PR fixing kwargs should be in https://github.com/pytorch/pytorch/pull/76768

**Comment by jjsjann123** [comment]
Started seeing more failures from `unique` and `unique_consecutive`. Similarly I think the errors are coming from aten and nvfuser doesn't have any fusion enabled in those.

I saw some expected failure marked on TestJit.. I'll disable these two sets for nvfuser, since we are not fusing anything for them.

```
======================================================================
ERROR: test_nvfuser_correctness_unique_consecutive_cuda_int16 (__main__.TestCudaFuserOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1808, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1808, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 390, in instantiated_test
    raise rte
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 782, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1129, in wrapper
    fn(*args, **kwargs)
  File "test_jit_cuda_fuser.py", line 4709, in test_nvfuser_correctness
    ref = variant(*clone_inputs((sample.input, *sample.args)), **sample.kwargs)
  File "/opt/pytorch/pytorch/torch/_jit_internal.py", line 421, in fn
    return if_true(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_jit_internal.py", line 423, in fn
    return if_false(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/functional.py", line 923, in _consecutive_return_inverse
    output, inverse_indices, _ = _unique_consecutive_impl(input, return_inverse, return_counts, dim)
  File "/opt/pytorch/pytorch/torch/functional.py", line 830, in _unique_consecutive_impl
    output, inverse_indices, counts = _VF.unique_consecutive(  # type: ignore[attr-defined]
RuntimeError: adjacent_difference failed on 1st step: cudaErrorInvalidDeviceFunction: invalid device function

----------------------------------------------------------------------
Ran 1 test in 7.983s

FAILED (errors=1)
```

**Comment by jjsjann123** [comment]
Looks like I'm getting the failure from the script below:

```
In [3]: x = torch.tensor([0., 0., 0., 0., 0.], device='cuda:0', dtype=torch.float32)

In [4]: o = torch.unique(x, sorted= False, return_inverse= True, return_counts= False, dim= -1)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 o = torch.unique(x, sorted= False, return_inverse= True, return_counts= False, dim= -1)

File /opt/pytorch/pytorch/torch/_jit_internal.py:421, in boolean_dispatch.<locals>.fn(*args, **kwargs)
    418     dispatch_flag = args[arg_index]
    420 if dispatch_flag:
--> 421     return if_true(*args, **kwargs)
    422 else:
    423     return if_false(*args, **kwargs)

File /opt/pytorch/pytorch/torch/_jit_internal.py:423, in boolean_dispatch.<locals>.fn(*args, **kwargs)
    421     return if_true(*args, **kwargs)
    422 else:
--> 423     return if_false(*args, **kwargs)

File /opt/pytorch/pytorch/torch/functional.py:861, in _return_inverse(input, sorted, return_inverse, return_counts, dim)
    858 if has_torch_function_unary(input):
    859     return _unique_impl(input, sorted, return_inverse, return_counts, dim)
--> 861 output, inverse_indices, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
    862 return output, inverse_indices

File /opt/pytorch/pytorch/torch/functional.py:757, in _unique_impl(input, sorted, return_inverse, return_counts, dim)
    752     return handle_torch_function(
    753         unique, (input,), input, sorted=sorted, return_inverse=return_inverse,
    754         return_counts=return_counts, dim=dim)
    756 if dim is not None:
--> 757     output, inverse_indices, counts = _VF.unique_dim(
    758         input,
    759         dim,
    760         sorted=sorted,
    761         return_inverse=return_inverse,
    762         return_counts=return_counts,
    763     )
    764 else:
    765     output, inverse_indices, counts = torch._unique2(
    766         input,
    767         sorted=sorted,
    768         return_inverse=return_inverse,
    769         return_counts=return_counts,
    770     )

RuntimeError: adjacent_difference failed on 1st step: cudaErrorInvalidDeviceFunction: invalid device function

```
