### ISSUE TITLE
"Address already in use" from DataLoader on different process with num_workers > 1

### ISSUE THREAD

**Issue by adeandrade** [pytorch/pytorch#76373]
### 🐛 Describe the bug

On a system with multiple GPUs, several independent PyTorch jobs can be run. If a first job has a DataLoader with num_workers > 1, and a second job is launched with num_workers > 1, the latter will throw the following exception:

```
Traceback (most recent call last):
  File "/opt/python/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/python/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/python/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 348, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/opt/python/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/opt/python/lib/python3.9/multiprocessing/resource_sharer.py", line 53, in __init__
    self._id = _resource_sharer.register(send, close)
  File "/opt/python/lib/python3.9/multiprocessing/resource_sharer.py", line 76, in register
    self._start()
  File "/opt/python/lib/python3.9/multiprocessing/resource_sharer.py", line 126, in _start
    self._listener = Listener(authkey=process.current_process().authkey)
  File "/opt/python/lib/python3.9/multiprocessing/connection.py", line 453, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/opt/python/lib/python3.9/multiprocessing/connection.py", line 596, in __init__
    self._socket.bind(address)
OSError: [Errno 98] Address already in use
```

The process will become a zombie process that does not die and does not do anything.

### Versions

1.11.0

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by gaure** [comment]
Hi adeandrade
Is there a solution for this bug?
Thanks
GA

**Comment by NivekT** [comment]
If your GPUs are already occupied with some DDP training, is it possible for you to terminate those processes and re-run this process again?

**Comment by adeandrade** [comment]
The problem I was having had nothing to do with PyTorch. I was running multiple containers and because of IPC isolation, the resulting processes were trying to bind the same ports on the host.

**Comment by gmastrapas** [comment]
Hey @adeandrade so you were using `--ipc=host` and the problem went away with `--ipc=private`? I think this issue is relevant to https://github.com/SeldonIO/seldon-core/issues/3720 and seems to be specific to python3.9

**Comment by mattcleigh** [comment]
> The problem I was having had nothing to do with PyTorch. I was running multiple containers and because of IPC isolation, the resulting processes were trying to bind the same ports on the host.

Hi, I am having the same issue trying to launch a slurm job array each using a Singularity image. I think I am having the exact same issue that you did, but I am not sure how to fix it.
