### ISSUE TITLE
AttributeError: '_thread._local' object has no attribute 'rel_tol' (cannot use TestCase.assertEqual from other threads)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#76609]
### 🐛 Describe the bug

In a test case, write:

```
    def test_foo(self):
        import threading
        def foo():
            self.assertEqual(torch.zeros(2), torch.zeros(2))
        t = threading.Thread(target=foo)
        t.start()
        t.join()
```

This will fail with

```
Traceback (most recent call last):
  File "/private/home/ezyang/pytorch-tmp-env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/private/home/ezyang/pytorch-tmp-env/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "test/test_decomp.py", line 300, in foo
    self.assertEqual(torch.zeros(2), torch.zeros(2))
  File "/private/home/ezyang/pytorch-tmp/torch/testing/_internal/common_utils.py", line 2202, in assertEqual
    rtol_override=self.rel_tol,
  File "/private/home/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 302, in rel_tol
    return self._tls.rel_tol
AttributeError: '_thread._local' object has no attribute 'rel_tol'
```

A non-contrived situation this can occur is a `__torch_dispatch__` invocation inside of an autograd backwards thread; you are unable to do test asserts from inside this callback.

### Versions

master

**Comment by andreigh** [comment]
The above test_foo seems to execute successfully:

(pytorch) C:\work\Repos\pytorch>python -m pytest test\test_torch.py -v -k test_foo
================================================= test session starts =================================================
platform win32 -- Python 3.11.4, pytest-7.4.0, pluggy-1.2.0 -- C:\ProgramData\miniconda3\envs\pytorch\python.exe
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('C:\\work\\Repos\\pytorch\\.hypothesis\\examples')
rootdir: C:\work\Repos\pytorch
configfile: pytest.ini
plugins: anyio-3.5.0, hypothesis-6.82.4
collected 1643 items / 1642 deselected / 1 selected

test/test_torch.py::TestTorch::test_foo PASSED [0.0721s]                                                         [100%]

========================================= 1 passed, 1642 deselected in 7.14s ==========================================

**Comment by ezyang** [comment]
it still seems to be done with tls, unclear to me if the root cause is fixed
