### ISSUE TITLE
hanging process with init_process_group(backend='mpi') cannot be killed 

### ISSUE THREAD

**Issue by mich45208** [pytorch/pytorch#76760]
## Issue description

Running mpirun with torch.distributed hangs. When parts of ranks raised error intentionally and the others are doing allgather, those who raised error cannot be killed and were waiting for all other processes to exit. On the other hand, the process that is doing allgather seems to be waiting for other processes too. This leads to all process hanging eventually.

## Code example

```
import torch.distributed as dist
import torch
import time
import sys
import os

dist.init_process_group(backend='mpi')
rank = dist.get_rank()
size = dist.get_world_size()
pid = os.getpid()

tensor_list = [torch.zeros(1, dtype=torch.int64) for _ in range(size)]
tensor = torch.arange(1, dtype=torch.int64) + rank

if rank == 0:
    print(f"Allgather: PID[{pid}]")
    dist.all_gather(tensor_list, tensor)
else:
    # to kill a process
    print(f"Runtime Error: PID[{pid}]")
    raise RuntimeError
    # sys.exit(-1)
    # dist.destroy_process_group() 
```

Error msg:
```
Runtime Error: PID[16955]
Runtime Error: PID[16956]
Runtime Error: PID[16957]
Traceback (most recent call last):
  File "torch_init.py", line 21, in <module>
    raise RuntimeError
RuntimeError
Traceback (most recent call last):
  File "torch_init.py", line 21, in <module>
    raise RuntimeError
RuntimeError
Traceback (most recent call last):
  File "torch_init.py", line 21, in <module>
    raise RuntimeError
RuntimeError
```
and hangs afterwards. 

tried to use async allgather with timeout, and the wait() was able to terminate but still cannot exit afterwards.

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS: Ubuntu18
- PyTorch version: 1.8.1+cpu
- Python version: python3.7

**Comment by mrshenli** [comment]
Hey @mich45208, does this only occur with MPI backend? Or does this also apply to NCCL and Gloo?

If the goal is to properly handle failures, will TorchElastic help? https://pytorch.org/docs/stable/elastic/run.html

cc @kiukchung

**Comment by mich45208** [comment]
we are limited to MPI backend and the program is actually launched by mpirun instead of torch.distributed.launch.

**Comment by mich45208** [comment]
some helpful traceback:
process that raised error and supposed to be killed:
`Thread 1 (Thread 0x7f9b6fe93600 (LWP 47240)):
#0  0x00007f9b6f12ad2d in __GI___pthread_timedjoin_ex (threadid=140302271559424, thread_return=0x0, abstime=0x0, block=<optimized out>) at pthread_join_common.c:89
#1  0x00007f9b62d618c3 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f9b6202463e in c10d::ProcessGroupMPI::destroy() () from /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#3  0x00007f9b62025a2f in c10d::ProcessGroupMPI::~ProcessGroupMPI() () from /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#4  0x00007f9b62025a81 in c10d::ProcessGroupMPI::~ProcessGroupMPI() () from /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#5  0x00007f9b61e4e8e9 in ?? () from /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#6  0x00007f9b61e4e952 in ?? () from /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#7  0x00007f9b619b7e08 in ?? () from /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#8  0x00007f9b619b8d2f in ?? () from /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#9  0x00007f9b6f85b327 in ?? () from /usr/local/lib/libpython3.7m.so.1.0
#10 0x00007f9b6f85e64b in PyDict_Clear () from /usr/local/lib/libpython3.7m.so.1.0
#11 0x00007f9b6f85e509 in ?? () from /usr/local/lib/libpython3.7m.so.1.0
#12 0x00007f9b6f8ef396 in ?? () from /usr/local/lib/libpython3.7m.so.1.0
#13 0x00007f9b6f945940 in _PyGC_CollectNoFail () from /usr/local/lib/libpython3.7m.so.1.0
#14 0x00007f9b6f8d5403 in PyImport_Cleanup () from /usr/local/lib/libpython3.7m.so.1.0
#15 0x00007f9b6f939098 in Py_FinalizeEx () from /usr/local/lib/libpython3.7m.so.1.0
#16 0x00007f9b6f942eec in ?? () from /usr/local/lib/libpython3.7m.so.1.0
#17 0x00007f9b6f942d9c in _Py_UnixMain () from /usr/local/lib/libpython3.7m.so.1.0
#18 0x00007f9b6f362b97 in __libc_start_main (main=0x55b059fa4730 <main>, argc=2, argv=0x7ffd20fc7be8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd20fc7bd8) at ../csu/libc-start.c:310
#19 0x000055b059fa476a in _start ()`

process that called allgather:
`Thread 66 (Thread 0x7f9aab0eb700 (LWP 47376)):
#0  0x00007f9aaf67e5d2 in ?? () from /usr/lib/x86_64-linux-gnu/libibverbs/libmlx5-rdmav34.so
#1  0x00007f9b65d29fb5 in ibv_poll_cq (wc=0x7f9aab0ea310, num_entries=1, cq=<optimized out>) at /usr/include/infiniband/verbs.h:2056
#2  ips_recvhdrq_progress (recvq=recvq@entry=0x55b05e762ef8) at prov/psm3/psm3/ptl_ips/ips_recvhdrq.c:292
#3  0x00007f9b65d2b3ae in ips_ptl_poll (ptl_gen=0x55b05e75d400, _ignored=<optimized out>) at prov/psm3/psm3/ptl_ips/ptl.c:455
#4  0x00007f9b65cf6ec6 in __psmi_poll_internal (ep=0x55b05e75cc00, poll_amsh=poll_amsh@entry=1) at prov/psm3/psm3/psm.c:1228
#5  0x00007f9b65d02d95 in __psm2_mq_ipeek_dequeue_multi (mq=0x55b05e71e390, status_array=status_array@entry=0x7f9aab0ea580, status_copy=status_copy@entry=0x7f9b65cdfba0 <psmx3_mq_status_copy>, count=count@entry=0x7f9aab0ea57c) at prov/psm3/psm3/psm_mq.c:1177
#6  0x00007f9b65ce2759 in psmx3_cq_poll_mq (cq=cq@entry=0x55b05e1862d0, trx_ctxt=<optimized out>, event_in=<optimized out>, event_in@entry=0x7f9aab0ea6d0, count=count@entry=8, src_addr=src_addr@entry=0x0) at prov/psm3/src/psmx3_cq.c:831
#7  0x00007f9b65ce2984 in psmx3_cq_readfrom (cq=0x55b05e1862d0, buf=0x7f9aab0ea6d0, count=8, src_addr=0x0) at prov/psm3/src/psmx3_cq.c:859
#8  0x00007f9b66a18fb7 in ?? () from /opt/mpich-3.4.3/lib/libmpi.so.12
#9  0x00007f9b669cb20e in ?? () from /opt/mpich-3.4.3/lib/libmpi.so.12
#10 0x00007f9b669cb6c2 in ?? () from /opt/mpich-3.4.3/lib/libmpi.so.12
#11 0x00007f9b66836926 in ?? () from /opt/mpich-3.4.3/lib/libmpi.so.12
#12 0x00007f9b669600ba in ?? () from /opt/mpich-3.4.3/lib/libmpi.so.12
#13 0x00007f9b66961201 in ?? () from /opt/mpich-3.4.3/lib/libmpi.so.12
#14 0x00007f9b668ddc6d in ?? () from /opt/mpich-3.4.3/lib/libmpi.so.12
#15 0x00007f9b666fdf4a in ?? () from /opt/mpich-3.4.3/lib/libmpi.so.12
#16 0x00007f9b666fe1f5 in ?? () from /opt/mpich-3.4.3/lib/libmpi.so.12
#17 0x00007f9b666fecee in PMPI_Allgather () from /opt/mpich-3.4.3/lib/libmpi.so.12
#18 0x00007f9b62028892 in ?? () from /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#19 0x00007f9b6202a7c5 in c10d::ProcessGroupMPI::runLoop() () from /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#20 0x00007f9b62d6166f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#21 0x00007f9b6f1296db in start_thread (arg=0x7f9aab0eb700) at pthread_create.c:463
#22 0x00007f9b6f46288f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95`

Seems like torch distributed with MPI backend didn't manage the usage of MPI fault tolerance correctly.
