### ISSUE TITLE
PrimTorch binary refs do not handle CPU scalar tensors correctly

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#76871]
### 🐛 Describe the bug

```
import torch
import torch._refs as ref

print(torch.add(torch.randn(2, device='cuda'), torch.randn(())))
print(ref.add(torch.randn(2, device='cuda'), torch.randn(())))
```

gives

```
tensor([0.7217, 0.5864], device='cuda:0')
Traceback (most recent call last):
  File "a.py", line 5, in <module>
    print(ref.add(torch.randn(2, device='cuda'), torch.randn(())))
  File "/private/home/ezyang/pytorch-tmp/torch/_refs/__init__.py", line 716, in add
    result = prims.add(a, b)
  File "/private/home/ezyang/pytorch-tmp/torch/_prims/__init__.py", line 173, in _prim
    meta(*args, **kwargs)
  File "/private/home/ezyang/pytorch-tmp/torch/_prims/__init__.py", line 202, in _elementwise_meta
    utils.check_same_device(*args, allow_cpu_scalar_tensors=True)
  File "/private/home/ezyang/pytorch-tmp/torch/_prims/utils.py", line 314, in check_same_device
    raise RuntimeError(msg)
RuntimeError: Tensor on device cpu is not on the expected device cuda:0!
```

The CPU scalar tensor behavior in stock ATen is intentional and we need to replicate it.

### Versions

master

**Comment by ezyang** [comment]
a proposed fix can be found in https://github.com/pytorch/pytorch/pull/76835 but I'm not sure if y'all will like it

**Comment by ngimel** [comment]
Hm, I thought that was fixed in #76727 https://github.com/pytorch/pytorch/pull/76727/files#diff-dd8250f2740baa59fd4ba7431ad9d43f560d801ae2226ad492c2be9858d0b660R298, but apparently not for all ops.

**Comment by ngimel** [comment]
Hah, after broadcasting it's no longer 0d cpu tensor, so that's tough.
