### ISSUE TITLE
Pytorch return TCPStore( RuntimeError: Connection reset by peer) 

### ISSUE THREAD

**Issue by rakhianand** [pytorch/pytorch#76913]
I amtrying to run Cosmic Tagger pytorch benchmark. It runs file up to 256 nodes(1024 ranks). However, when I try to run on higher number of nodes 384 nodes(1536 ranks) it runs fine occasionally. Most of the time it fails

## Issue description

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error executing job with overrides: ['data.data_directory=/lus/grand/projects/Polaris/CosmicTagger/data/', 'run.minibatch_size=1536', 'run.id=at-2022-05-05_384nodes', 'run.iterations=10', 'data.downsample=0']
Traceback (most recent call last):
  File "/home/ranand/bare_metal_Cosmic_tagger/CosmicTagger/bin/exec.py", line 254, in main
    s = exec(cfg)
  File "/home/ranand/bare_metal_Cosmic_tagger/CosmicTagger/bin/exec.py", line 47, in __init__
    self.train()
  File "/home/ranand/bare_metal_Cosmic_tagger/CosmicTagger/bin/exec.py", line 100, in train
    self.make_trainer()
  File "/home/ranand/bare_metal_Cosmic_tagger/CosmicTagger/bin/exec.py", line 181, in make_trainer
    self.trainer = distributed_trainer.distributed_trainer(self.args)
  File "/home/ranand/bare_metal_Cosmic_tagger/CosmicTagger/src/utils/torch/distributed_trainer.py", line 139, in __init__
    torch.distributed.init_process_group(
  File "//home/ranand/bare_metal_Cosmic_tagger/pytorch/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "//home/ranand/bare_metal_Cosmic_tagger/pytorch/torch/distributed/rendezvous.py", line 259, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "//home/ranand/bare_metal_Cosmic_tagger/pytorch/torch/distributed/rendezvous.py", line 191, in _create_c10d_store
    return TCPStore(
RuntimeError: Connection reset by peer

Software installed
Cudatoolkit/11.4
gcc-11.2
pytorch version 1.12.0

**Comment by mrshenli** [comment]
cc @kwen2501

**Comment by mrshenli** [comment]
from @kwen2501: does increasing the timeout help here?

**Comment by rakhianand** [comment]
No, I changed the timeout to 30 minutes and still got the same error.  Basically, few ranks just die in the function above and all other ranks keep on waiting until they timeout.

**Comment by kwen2501** [comment]
30 mins is the default, so I suspect that setting it to 30 would make a difference.

Just to get an idea: in your successful runs, how long does it take for the initialization to finish? I am wondering if the default timeout has too tight a margin for your larger scale run.

Also, any chance that your cluster has a faster IP interface? For example, some cluster with IB cards may also have IP-over-IB service, using those interface for the TCP init may potentially shorten your initialization time.

**Comment by rakhianand** [comment]
In successful cases, the timeout value is just 30 secs. So again I don't think timeout value is the issue. 
Also, I tried to use MPI instead of NCCL/Gloo, but I have an issue to compile. How do I add link libraries in the CMake files so that it compiles using native MPI?

**Comment by zbmap** [comment]
When using PyTorch, I encountered a similar problem when starting on a large scale. I'm not sure if it's for the same reason, but the cause was the syncookie mechanism of the kernel. You can try to solve it by disabling syncookie.

**Comment by liaoyiqiao** [comment]
same problem for 1024 ranks

**Comment by everest33** [comment]
any solution :(
