### ISSUE TITLE
DISABLED test_comprehensive_linalg_ldl_factor_cuda (__main__.TestDecompCUDA)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#76961]
Platforms: linux
It also only fails for CUDA 11.6.

Disabling for both test_comprehensive_linalg_ldl_factor_cuda_complex128 and test_comprehensive_linalg_ldl_factor_cuda_complex64 

This test IS NOT FLAKY. It has been failing on trunk for a while but we did not catch it as periodic jobs failed to run for a few days. 

@ezyang I think you recently modified these tests--they're all failing with the same `RuntimeError: torch.linalg.ldl_factor: complex tensors with hermitian=True flag are not supported.` Should we just be skipping these?

```
ERROR [0.013s]: test_comprehensive_linalg_ldl_factor_cuda_complex128 (__main__.TestDecompCUDA)
2022-05-06T02:20:06.9091292Z ----------------------------------------------------------------------
2022-05-06T02:20:06.9091673Z Traceback (most recent call last):
2022-05-06T02:20:06.9092586Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1800, in wrapper
2022-05-06T02:20:06.9092970Z     method(*args, **kwargs)
2022-05-06T02:20:06.9093469Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1800, in wrapper
2022-05-06T02:20:06.9093845Z     method(*args, **kwargs)
2022-05-06T02:20:06.9094373Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
2022-05-06T02:20:06.9094741Z     raise rte
2022-05-06T02:20:06.9095248Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
2022-05-06T02:20:06.9097450Z     result = test(self, **param_kwargs)
2022-05-06T02:20:06.9098628Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 808, in dep_fn
2022-05-06T02:20:06.9099133Z     return fn(slf, *args, **kwargs)
2022-05-06T02:20:06.9099852Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 808, in dep_fn
2022-05-06T02:20:06.9100274Z     return fn(slf, *args, **kwargs)
2022-05-06T02:20:06.9100786Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 773, in test_wrapper
2022-05-06T02:20:06.9101188Z     return test(*args, **kwargs)
2022-05-06T02:20:06.9101696Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 966, in only_fn
2022-05-06T02:20:06.9102091Z     return fn(self, *args, **kwargs)
2022-05-06T02:20:06.9107467Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 808, in wrapper
2022-05-06T02:20:06.9108065Z     fn(*args, **kwargs)
2022-05-06T02:20:06.9109078Z   File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1150, in wrapper
2022-05-06T02:20:06.9109778Z     fn(*args, **kwargs)
2022-05-06T02:20:06.9110311Z   File "test_decomp.py", line 339, in test_comprehensive
2022-05-06T02:20:06.9111097Z     self.do_cross_ref(device, dtype, op, run_all=True)
2022-05-06T02:20:06.9111612Z   File "test_decomp.py", line 473, in do_cross_ref
2022-05-06T02:20:06.9111886Z     func(*args, **kwargs)
2022-05-06T02:20:06.9112197Z   File "test_decomp.py", line 364, in __torch_dispatch__
2022-05-06T02:20:06.9112548Z     return cls._torch_dispatch(func, types, args, kwargs)
2022-05-06T02:20:06.9112893Z   File "test_decomp.py", line 379, in _torch_dispatch
2022-05-06T02:20:06.9113177Z     return func(*args, **kwargs)
2022-05-06T02:20:06.9113633Z   File "/opt/conda/lib/python3.7/site-packages/torch/_ops.py", line 48, in __call__
2022-05-06T02:20:06.9114004Z     return self._op(*args, **kwargs or {})
2022-05-06T02:20:06.9114394Z RuntimeError: torch.linalg.ldl_factor: complex tensors with hermitian=True flag are not supported.
```

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_comprehensive_linalg_ldl_factor_cuda_complex128%2C%20TestDecompCUDA)).

cc @ezyang @gchanan @zou3519 @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by ezyang** [comment]
It looks like magma isn't being turned on for 11.6

```
void ldl_factor_kernel(
    const Tensor& LD,
    const Tensor& pivots,
    const Tensor& info,
    bool upper,
    bool hermitian) {
  auto preferred_backend = at::globalContext().linalgPreferredBackend();
  switch (preferred_backend) {
    case at::LinalgBackend::Cusolver:
      return ldl_factor_cusolver(
          LD, pivots, info, upper, hermitian);
    case at::LinalgBackend::Magma:
      return ldl_factor_magma(LD, pivots, info, upper, hermitian);
    default:
    // By default use cusolver if available and magma otherwise.
    // If cusolver and magma 2.5.4+ are both available and hermitian=true,
    // call magma for complex inputs
#ifdef USE_CUSOLVER
#if AT_MAGMA_ENABLED() && (MAGMA_VERSION_MAJOR >= 2 && MAGMA_VERSION_MINOR >= 5 && MAGMA_VERSION_MICRO >= 4)
      if (LD.is_complex() && hermitian) {
        return ldl_factor_magma(
            LD, pivots, info, upper, hermitian);
      }
#endif
      return ldl_factor_cusolver(
          LD, pivots, info, upper, hermitian);
#else 
      return ldl_factor_magma(LD, pivots, info, upper, hermitian);
#endif
  }
}
```

**Comment by ezyang** [comment]
@IvanYashchuk you're gonna handle this?

**Comment by IvanYashchuk** [comment]
Yes, there are certain sample inputs that need to be skipped based on the available MAGMA version.

**Comment by ngimel** [comment]
Yeah but we should also fix 11.6 build to include magma

**Comment by IvanYashchuk** [comment]
> Yes, there are certain sample inputs that need to be skipped based on the available MAGMA version.

Strange, it's already there:
https://github.com/pytorch/pytorch/blob/c031643e392d2d5dda14c5876761265ac6bcf32a/torch/testing/_internal/common_methods_invocations.py#L6102-L6105

Maybe it's weird interaction of the `torch.backends.cuda.preferred_linalg_library` since it's a global flag some other test could set it to a non-default value which is then propagated further in the tests.

**Comment by xwang233** [comment]
Sorry for a late response

> Maybe it's weird interaction of the torch.backends.cuda.preferred_linalg_library since it's a global flag some other test could set it to a non-default value which is then propagated further in the tests.

I'm thinking we should add `torch.backends.cuda.preferred_linalg_library('default')` here in the tearDown? Not sure if this is for one test case or the whole TestLinalg suite.

https://github.com/pytorch/pytorch/blob/4ebc4890ddfd432677d46a3096c09a6afe3532f7/test/test_linalg.py#L55-L63

**Comment by xwang233** [comment]
@Lezcano , we have a decorator `setLinalgBackendsToDefaultFinally` that does this. The problem is we're very likely to forget it when adding a new test.

**Comment by Lezcano** [comment]
My suggestion is that, rather than doing the logic of "if the device of the test is cpu, choose default, if it is cuda, iterate over each device, set it and run the test", as in
https://github.com/pytorch/pytorch/blob/417676720e3bf9e77b70eeaff5595f4c80a990e6/test/test_linalg.py#L2580-L2586
we would have something like we have for devices and dtypes:
```python
@testBackends
def mytest(self, dtype, device):
   # rest of the test
```
Then, the backend would do the logic of generating the test `mytest_cpu_float32_default`, but for cuda it'd generate 3 tests, namely `mytest_cuda_float32_default`, `mytest_cuda_float32_magma` and `mytest_cuda_float32_cusolver`. Then, it'd make sure that the default backend is set at the end of the test.
