### ISSUE TITLE
A somewhat cryptic error message (for newcomers) - "Cannot re-initialize CUDA in forked subprocess" - report and suggestion for a possible solution

### ISSUE THREAD

**Issue by YoelShoshan** [pytorch/pytorch#77159]
### 🐛 Describe the bug

I've seen multiple individuals and groups using num_workers=0 in DataLoader, and significantly under-utilizing GPUs due to the following error message which appeared cryptic (to newcomers) when they used num_workers bigger than 0

"Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method"

The error message was gone when they switched to num_workers=0
Using "spawn" start method did not solve the problem.

I analyzed the problem and found that inside their custom Dataset implementation that as a final step there they transfer the tensor into the GPU.
(Which could make sense from the point of view of non-experts, as they remove the need to do this as another step before feeding the tensor to a model.)

I was wondering - perhaps there should be a warning or an exception when a non-cpu tensor is being created inside a worker process spawn by DataLoader? 
Or maybe an exception when a non-cpu tensor is being created inside a Dataset in general?
I can try to investigate and propose a PR if you think it's a good direction.

A short snippet to reproduce the problem:
```python
import torch
from torch.utils.data import DataLoader, Dataset
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm

class SomeDataset(Dataset):   
    def __len__(self):
        return 100
    def __getitem__(self, idx):
        assert idx>=0 and idx<len(self)
        t = torch.rand(3, 400,400, device=torch.device('cuda'))
        return t

class SomeNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
    def forward(self, x):
        x = self.conv1(x)        
        return x

if __name__=='__main__':
    ds = SomeDataset()
    dl = DataLoader(ds, batch_size=8, num_workers=4)
    model = SomeNet().cuda()
    optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
    
    for s in tqdm(iter(dl), total=len(dl)):
        optimizer.zero_grad()        
        pred = model(s)
        pred.mean().backward()
        optimizer.step()

```

the output:
```bash
Traceback (most recent call last):
  File "/some/path/reproduce_dataloader_cuda_tensors_problem.py", line 36, in <module>
    for s in tqdm(iter(dl), total=len(dl)):
  File "/some/path/to/download/miniconda3/envs/bio/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/some/path/to/download/miniconda3/envs/bio/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/some/path/to/download/miniconda3/envs/bio/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/some/path/to/download/miniconda3/envs/bio/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/some/path/to/download/miniconda3/envs/bio/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/some/path/to/download/miniconda3/envs/bio/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/some/path/to/download/miniconda3/envs/bio/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/some/path/to/download/miniconda3/envs/bio/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/some/path/reproduce_dataloader_cuda_tensors_problem.py", line 16, in __getitem__
    t = torch.rand(3, 400,400, device=torch.device('cuda'))
  File "/some/path/to/download/miniconda3/envs/bio/lib/python3.7/site-packages/torch/cuda/__init__.py", line 207, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. To use CUDA with "
Runtim

### Versions

Collecting environment information...
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.17

Python version: 3.7.13 (default, Mar 29 2022, 02:18:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-167-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB

Nvidia driver version: 460.106.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.782
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] pytorch-lightning==1.6.0
[pip3] torch==1.11.0
[pip3] torchmetrics==0.7.3
[pip3] torchvision==0.12.0
[conda] mypy                      0.782                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] pytorch-lightning         1.6.0                    pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchmetrics              0.7.3                    pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

**Comment by ejguan** [comment]
> I was wondering - perhaps there should be a warning or an exception when a non-cpu tensor is being created inside a worker process spawn by DataLoader?
> Or maybe an exception when a non-cpu tensor is being created inside a Dataset in general?

This is not the root cause for your issue. The problem is that multiple processes are trying to access to the same cuda context due to `fork`. You have to use `spawn` to do so.

**Comment by YoelShoshan** [comment]
Hi @ejguan thanks for your answer!

I'm not claiming that this is the root cause, I'm trying to illustrate a user scenario (which I've seen multiple users go through)

In this scenario, typically the correct solution (fast, not wasting gpu mem, etc.) is *not* to switch to using spawn method, it's instead to avoid transferring the tensors into the cuda device in the workers in the first place.

Example non-expert pytorch user scenario (not fictional, I've seen people do it)

Step 1 - as a final step in their Dataset __getitem__ they transfer the tensor(s) to cuda, that way they don't need to transfer it inside the training loop

Step 2 - they encounter the "RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method"

Step 3 - they follow the guide and use `torch.multiprocessing.set_start_method('spawn')`

Step 4 - they get RuntimeError: CUDA out of memory

Step 5 - they try to reduce the minibatch size to reduce memory usage (and also lower num_workers)

My point is that the current error "leads" them down a path of actions which is a bad solution to their problem,
when the solution is simply to not move tensors to cuda in the Dataset/worker process.

What I'm wondering is if there's a way to help users more by providing error message or warning in such scenario that leads them towards the better solution.

I hope that I explained myself more clearly this time - please also see a short snippet that shows both alternative solutions (the one that is based on 'spawn' (CUDA_TENSORS_ON_WORKER=True) crashes on GPU out of mem (which, of course, makes sense on the technical level when you understand the internal, but less for non-experts...)

Short snippet (CUDA_TENSORS_ON_WORKERS can be set to True/False )

```python
import torch
from torch.utils.data import DataLoader, Dataset
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm

CUDA_TENSORS_ON_WORKER = True   #flip this to switch between 2 possible solutions

class SomeDataset(Dataset):   
    def __len__(self):
        return 100000
    def __getitem__(self, idx):
        assert idx>=0 and idx<len(self)        
        t = torch.rand(3, 400,400)
        if CUDA_TENSORS_ON_WORKER:
            t = t.to(torch.device('cuda'))
        return t

class SomeNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 100, 5)
        self.conv2 = nn.Conv2d(100, 100, 5)
        self.conv3 = nn.Conv2d(100, 100, 5)
    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        return x

if __name__=='__main__':
    if CUDA_TENSORS_ON_WORKER:
        torch.multiprocessing.set_start_method('spawn')
    ds = SomeDataset()
    dl = DataLoader(ds, batch_size=60, num_workers=20)
    model = SomeNet().cuda()
    optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
    
    for s in tqdm(iter(dl), total=len(dl)):
        if not CUDA_TENSORS_ON_WORKER:
            s = s.to(torch.device('cuda'))
        optimizer.zero_grad()        
        pred = model(s)
        pred.mean().backward()
        optimizer.step()
```

**Comment by ejguan** [comment]
The problem here is we don't know when/where the cuda context is created. Your proposal needs a flag to indicate if users runs any cuda code in child processes. It means users have to add such flag in their custom Dataset code, which PyTorch can't control.
Besides, since cuda context is lazily initialized, we can't really know if users' code has any cuda-related operations before running multiprocessing. If PyTorch is able to detect your code before execution, we might be able to have a way to indicate users' not-recommended implementation.

**Comment by YoelShoshan** [comment]
@ejguan what about the following suggestion - pytorch default collate function can show a warning if it encounters a tensor which is not on CPU device.
If you think it's a good solution I'll gladly create a PR for this.

**Comment by YoelShoshan** [comment]
@ejguan opened a PR :)
See https://github.com/pytorch/pytorch/pull/77639

**Comment by SsnL** [comment]
I think we should first acknowledge that even a warning doesn't stop the program (like an error) does, it still greatly disrupts user experience, and should be avoided. We should not punish people for using pytorch in the right way. In other words, if one writes their program in the way intended by the framework, they should see zero warnings.

Putting a dataset on gpu and not using multiprocessing loading is a fairly common case (b/c small datasets are better off this way), and does not require any "expert" knowledge of pytorch.

**Comment by SsnL** [comment]
A valid change could be:
1. Change CUDA OOM & context-reinit error to use a custom subclass of `RuntimeError`
2. In worker loop, try-catch this subclass, and use `raise ... from ...` to append additional information that points to the subtlety of CUDA & multiprocessing/dataloader.

This would not disturb experience of users who correctly use the framework, and also adds better guidance to let people know where they might have done things wrongly.

That said, this is a more involved change and may potentially cause other issues. If this is the proposal, a detailed review from a pytorch team member is needed.

**Comment by YoelShoshan** [comment]
@SsnL I understand and agree with the sentiment :)

Modifying the Runtime error (the solution you suggested) into explaining the two options sounds good to me, as the user is experiencing a crash anyway.

**Comment by soheila1370** [comment]
@YoelShoshan Thanks for posting this problem. I worked with Tensorflow before and I've shifter to Pytorch recently and I faced the Error you mentioned. But I saw your useful post and could fix it. However I faced another Error in back propagation. When the number of workers = 0, eveything is fine but when I turn it to > 0 I face the Error:
" loss.backward()
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorMath.cu:29"

I read somewhere if I change to CPU, I can get a clearer Error, I did and I got this Error on CPU with number of workers > 0:

"RuntimeError: grad_input must be contiguous"


Can you help me to fix this Error?

**Comment by WreckItTim** [comment]
I was running into this issue - and just the code snippet you had on the two solutions helped -- otherwise I would have gone with solution 1 which likely would have ended up in me just using num_workers=0 to be honest.
