### ISSUE TITLE
`tensordot` does check the dtype of empty tensor

### ISSUE THREAD

**Issue by upupyy** [pytorch/pytorch#77233]
### 🐛 Describe the bug

`tensordot` does check the dtype of empty tensor

```python
import torch

a = torch.rand([3, 2, 1], dtype=torch.float64)
b = torch.rand([1, 2, 0], dtype=torch.complex128)
torch.tensordot(a, b)
# tensor([], size=(3, 0), dtype=torch.float64)
```

By contrast,
```python
import torch

a = torch.rand([3, 2, 1], dtype=torch.float64)
b = torch.rand([1, 2, 1], dtype=torch.complex128)
torch.tensordot(a, b)
# RuntimeError: expected scalar type Double but found ComplexDouble
```

Interestingly, when the tensor is 2d, it will raise the error even `b` is empty

```python
import torch

a = torch.rand([2, 1], dtype=torch.float64)
b = torch.rand([1, 0], dtype=torch.complex128)
torch.tensordot(a, b)
# RuntimeError: expected scalar type Double but found ComplexDouble
```

### Versions

pytorch: 1.11.0

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by dcci** [comment]
This is fixed in recent versions.

```
>>> import torch
>>> a = torch.rand([3, 2, 1], dtype=torch.float64)
>>> b = torch.rand([1, 2, 0], dtype=torch.complex128)
>>> torch.tensordot(a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/davidino/pytorch/torch/functional.py", line 1360, in tensordot
    return _VF.tensordot(a, b, dims_a, dims_b)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: both inputs should have same dtype
>>> import torch
>>> a = torch.rand([3, 2, 1], dtype=torch.float64)
>>> b = torch.rand([1, 2, 1], dtype=torch.complex128)
>>> torch.tensordot(a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/davidino/pytorch/torch/functional.py", line 1360, in tensordot
    return _VF.tensordot(a, b, dims_a, dims_b)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: both inputs should have same dtype
>>> import torch
>>> a = torch.rand([2, 1], dtype=torch.float64)
>>> b = torch.rand([1, 0], dtype=torch.complex128)
>>> torch.tensordot(a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/davidino/pytorch/torch/functional.py", line 1360, in tensordot
    return _VF.tensordot(a, b, dims_a, dims_b)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: both inputs should have same dtype
```
