### ISSUE TITLE
Torch distributed runtime check failure when using pipeline parallelism

### ISSUE THREAD

**Issue by insujang** [pytorch/pytorch#77319]
### 🐛 Describe the bug

Hope this issue post would be helpful to others who suffer from similar problem.
I am trying to run `examples/pretrain_gpt_distributed_with_mp.sh`, but when pipeline model parallelism is enabled, the following error occurs on every nodes:

```
Traceback (most recent call last):
  File "pretrain_gpt.py", line 127, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/data/insujang/Megatron-LM/megatron/training.py", line 147, in pretrain
    iteration = train(forward_step_func,
  File "/data/insujang/Megatron-LM/megatron/training.py", line 695, in train
    train_step(forward_step_func,
  File "/data/insujang/Megatron-LM/megatron/training.py", line 398, in train_step
    losses_reduced = forward_backward_func(
  File "/data/insujang/Megatron-LM/megatron/schedules.py", line 381, in forward_backward_pipelining_with_interleaving
    p2p_communication.send_forward_recv_forward(
  File "/data/insujang/Megatron-LM/megatron/p2p_communication.py", line 270, in send_forward_recv_forward
    input_tensor, _ = _communicate(
  File "/data/insujang/Megatron-LM/megatron/p2p_communication.py", line 124, in _communicate
    send_next_op = torch.distributed.P2POp(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 827, in __new__
    _check_op(op)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 263, in _check_op
    raise RuntimeError("Invalid ``op``. Expected ``op`` "
RuntimeError: Invalid ``op``. Expected ``op`` to be of type ``torch.distributed.isend`` or ``torch.distributed.irecv``.
```
(for workers error occurs from the receive part but by the same error)

Glancing at the code, I first did not understand why the code does not work since all arguments looked good:
```
def _check_op(op):
    """
    Helper to check that the ``op`` is either isend or irecv.
    """
    if op not in [isend, irecv]:
        raise RuntimeError("Invalid ``op``. Expected ``op`` "
                           "to be of type ``torch.distributed.isend`` or "
                           "``torch.distributed.irecv``.")

send_next_op = torch.distributed.P2POp(
                torch.distributed.isend, tensor_send_next,
                mpu.get_pipeline_model_parallel_next_rank())
```

Strangely `torch.distributed.P2POp` does work if I manually test it with the following example:
```
import torch
tensor = torch.rand(2)
op = torch.distributed.P2POp(torch.distributed.isend, tensor, 1)
```
which means, it is not about a Pytorch problem.

When I print `op` in `_check_op` function (adding `print(op)`), the output is different when I run Megatron.

Manual test:
```
<function isend at [address]>
```

Megatron:
```
<function add_wrapper.<locals>.wrapper_func at [address]>
```
which makes the `_check_op` fails and makes a runtime error.

To prevent it, change P2POp creation function like this:
```
from torch.distributed import isend, irecv

...

if tensor_send_next is not None:
  send_next_op = torch.distributed.P2POp(isend, tensor_send_next, mpu.get_pipeline_model_parallel_next_rank())
  ops.append(send_next_op)
```

I am not familiar with such Python-related errors, so any suggestion of a better solution would be appreciated.

### Versions

```
PyTorch version: 1.8.0a0+1606899
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.18.2
Libc version: glibc-2.31

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.18.0-348.20.1.el8_5.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: NVIDIA A40
Nvidia driver version: 510.60.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.8.0a0+1606899
[pip3] torchtext==0.9.0a0
[pip3] torchvision==0.9.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.19.2           py38h6163131_0  
[conda] numpy-base                1.19.2           py38h75fe3a5_0  
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.8.0a0+1606899          pypi_0    pypi
[conda] torchtext                 0.9.0a0                  pypi_0    pypi
[conda] torchvision               0.9.0a0                  pypi_0    pypi
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by insujang** [comment]
Closing this issue since I uploaded to the wrong place. :(
