### ISSUE TITLE
Circular import issue with torch, torchvision, and onnx

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#77441]
### 🐛 Describe the bug

Circular import issue with torch, torchvision, and onnx

Repro:
```
python -c 'from torchvision import transforms'
```

Error message:
```
root@e0ed6bda8499:/workspace# python -c 'from torchvision import transforms'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/pytorch/vision/torchvision/__init__.py", line 7, in <module>
    from torchvision import models
  File "/opt/pytorch/vision/torchvision/models/__init__.py", line 2, in <module>
    from .convnext import *
  File "/opt/pytorch/vision/torchvision/models/convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation
  File "/opt/pytorch/vision/torchvision/ops/__init__.py", line 30, in <module>
    _register_custom_op()
  File "/opt/pytorch/vision/torchvision/ops/_register_onnx_ops.py", line 11, in _register_custom_op
    from torch.onnx.symbolic_opset11 import select, squeeze, unsqueeze
  File "/opt/pytorch/pytorch/torch/onnx/symbolic_opset11.py", line 6, in <module>
    import torch.onnx.utils
  File "/opt/pytorch/pytorch/torch/onnx/utils.py", line 21, in <module>
    from torch.onnx import (  # noqa: F401
  File "/opt/pytorch/pytorch/torch/onnx/symbolic_caffe2.py", line 5, in <module>
    import torch.onnx.symbolic_registry as sym_registry
  File "/opt/pytorch/pytorch/torch/onnx/symbolic_registry.py", line 176, in <module>
    _import_symbolic_opsets()
  File "/opt/pytorch/pytorch/torch/onnx/symbolic_registry.py", line 32, in _import_symbolic_opsets
    module = importlib.import_module(
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/pytorch/pytorch/torch/onnx/symbolic_opset13.py", line 22, in <module>
    from torch.onnx.symbolic_opset11 import unsqueeze
ImportError: cannot import name 'unsqueeze' from partially initialized module 'torch.onnx.symbolic_opset11' (most likely due to a circular import) (/opt/pytorch/pytorch/torch/onnx/symbolic_opset11.py)
```

### Versions

torch e011a8e18bf469a6a612fd1e7647159c353730a9 
```
root@e0ed6bda8499:/opt/pytorch/pytorch# git log -n1
commit e011a8e18bf469a6a612fd1e7647159c353730a9 (HEAD -> master, origin/master, origin/HEAD)
Author: Kulin Seth <kulinseth@gmail.com>
Date:   Fri May 13 18:28:53 2022 +0000

    Enable PyTorch operations on MPS Backend. (#77343)

    Add PyTorch operations to MPS backend.

    - https://github.com/pytorch/pytorch/issues/77394
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/77343
    Approved by: https://github.com/albanD
```

torchvision pytorch/vision@d585f86d94f07a3bc083e48c6534d93a409cbcb2 
```
root@e0ed6bda8499:/opt/pytorch/vision# git log -n1
commit d585f86d94f07a3bc083e48c6534d93a409cbcb2 (HEAD -> main, origin/main, origin/HEAD)
Author: Hu Ye <xiaohuzc@gmail.com>
Date:   Sat May 14 02:13:57 2022 +0800

    Added revamped quantized resnet docs (#6012)

    * Create resnet_quant.rst

    * add resnet quant

    * refactor docs

    * Minor fix

    * Nit

    Co-authored-by: Nicolas Hug <contact@nicolas-hug.com>
```

env
```
root@e0ed6bda8499:/opt/pytorch/vision# python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.12.0a0+git39bd37f
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-92-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 470.82.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.2.0a0+a76339b
[pip3] numpy==1.21.5
[pip3] torch==1.12.0a0+gite011a8e
[pip3] torchdynamo==0.2.0
[pip3] torchvision==0.13.0a0+d585f86
[conda] functorch                 0.2.0a0+a76339b          pypi_0    pypi
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] nomkl                     3.0                           0
[conda] numpy                     1.21.5           py38h7a5d4dd_2
[conda] numpy-base                1.21.5           py38hb8be1f0_2
[conda] torch                     1.12.0a0+gite011a8e           dev_0    <develop>
[conda] torchdynamo               0.2.0                    pypi_0    pypi
[conda] torchvision               0.13.0a0+d585f86           dev_0    <develop>
```

cc @malfet @ngimel @mruberry

**Comment by xwang233** [comment]
seems fixed

**Comment by malfet** [comment]
Were fixed by reverting https://github.com/pytorch/pytorch/commit/6b366dd3c1d8c6f72e540fdadd26bb7cd5752332

**Comment by xwang233** [comment]
@malfet , should we have some kind of torchvision CI to discover this kind of failures earlier?

**Comment by malfet** [comment]
Yep, though it should not be specific to torchvision

**Comment by xwang233** [comment]
Thank you for adding the test, @malfet ! cc @ptrblck

**Comment by Shivamp9** [comment]
restart your kernel.
