### ISSUE TITLE
TorchScript doesn't support tuple including None type as function return variable

### ISSUE THREAD

**Issue by gumpcarl** [pytorch/pytorch#77482]
### 🐛 Describe the bug
```python
import torch
from torch import nn,Tensor
import torch.nn.functional as F
from typing import Dict,Tuple,Optional,List

class Test(nn.Module):
    def __init__(self) -> None:
        super().__init__()
    
    def forward(self, a:Tensor) -> Tuple[Optional[Tensor]]:
        return (a,a,None)


test_model = torch.jit.script(Test())
```
The error message is as follows:

$ python test.py 
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    test_model = torch.jit.script(Test())
  File "/home/yanggang/hd/anaconda3/envs/vector_net/lib/python3.8/site-packages/torch/jit/_script.py", line 1257, in script
    return torch.jit._recursive.create_script_module(
  File "/home/yanggang/hd/anaconda3/envs/vector_net/lib/python3.8/site-packages/torch/jit/_recursive.py", line 451, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/yanggang/hd/anaconda3/envs/vector_net/lib/python3.8/site-packages/torch/jit/_recursive.py", line 517, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/yanggang/hd/anaconda3/envs/vector_net/lib/python3.8/site-packages/torch/jit/_recursive.py", line 368, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Return value was annotated as having type Tuple[Optional[Tensor]] but is actually of type Tuple[Tensor, Tensor, NoneType]:
  File "test.py", line 12
    def forward(self, a:Tensor) -> Tuple[Optional[Tensor]]:
        return (a,a,None)
        ~~~~~~~~~~~~~~~~ <--- HERE

### Versions

Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.1 (default, Jan  8 2020, 22:29:32)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-28-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 510.54
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.10.2
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==1.7.2
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.12
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.10.2
[pip3] torchvision==0.11.3
[conda] blas                      1.0                         mkl    intel
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2022.0.2                 pypi_0    pypi
[conda] mkl-fft                   1.3.1                    pypi_0    pypi
[conda] mkl-random                1.2.2                    pypi_0    pypi
[conda] mkl-service               2.4.0                    pypi_0    pypi
[conda] mkl_fft                   1.0.15           py38ha843d7b_0  
[conda] mkl_random                1.1.0            py38h962f231_0  
[conda] numpy                     1.19.0                   pypi_0    pypi
[conda] numpy-base                1.20.3           py38hf707ed8_2    intel
[conda] pytorch                   1.10.2          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torch-cluster             1.5.9                    pypi_0    pypi
[conda] torch-geometric           1.7.2                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-sparse              0.6.12                   pypi_0    pypi
[conda] torchaudio                0.10.2               py38_cu113    pytorch
[conda] torchvision               0.11.3               py38_cu113    pytorch

**Comment by davidberard98** [comment]
```python
import torch
from torch import nn,Tensor
import torch.nn.functional as F
from typing import Dict,Tuple,Optional,List

class Test(nn.Module):
    def __init__(self) -> None:
        super().__init__()
    
    def forward(self, a:Tensor) -> Tuple[Optional[Tensor], Optional[Tensor], Optional[Tensor]]:
        return (a,a,None)


test_model = torch.jit.script(Test())
```
^ this should work.

**Comment by negini2020** [comment]
def forward(self, a:Tensor) -> Tuple[Optional[Tensor]]:
    return (a,a,None)

**Comment by negini2020** [comment]
https://www.instagram.com/mohamadrezadavodabadii205
