### ISSUE TITLE
SegFault after average pooling quantization

### ISSUE THREAD

**Issue by kventinel** [pytorch/pytorch#77511]
### 🐛 Describe the bug

After adding `ceil_mode=True` in AveragePooling given code return segfault.

```python3
import torch
import torch.nn as nn


if __name__ == '__main__':
    model = nn.Sequential(
        torch.quantization.QuantStub(),
        nn.Conv1d(40, 40, 5, stride=1, padding=2),
        nn.ReLU(),
        nn.AvgPool1d(32, ceil_mode=True),
        torch.quantization.DeQuantStub()
    )
    model.eval()
    torch.backends.quantized.engine = 'qnnpack'
    model.qconfig = torch.quantization.get_default_qconfig('qnnpack')
    quant_prepared = torch.quantization.prepare(model)
    input_data = torch.randn((32, 40, 32))
    quant_prepared(input_data)
    quant_int8 = torch.quantization.convert(quant_prepared)
    input_data = torch.randn((32, 40, 16))
    print(quant_int8.forward(input_data).shape)
```

### Versions

[pip3] mypy==0.942
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[conda] Could not collect

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by kventinel** [comment]
MaxPooling in that case works fine

**Comment by dzdang** [comment]
Taking a look

**Comment by dzdang** [comment]
@kventinel 
I'm able to reproduce your error on a local build. Are you implying `ceil_mode = false` worked for you? 
using your script, when `ceil_mode = false`, I get the following error
```
Traceback (most recent call last):
  File "/data/users/dzdang/pytorch/oncall.py", line 21, in <module>
    output = quant_int8.forward(input_data)
  File "/data/users/dzdang/pytorch/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/data/users/dzdang/pytorch/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/users/dzdang/pytorch/torch/nn/modules/pooling.py", line 542, in forward
    return F.avg_pool1d(
RuntimeError: qnnpack_avg_pool2d(): the resulting output Tensor size should be >= 0
```

I think the two errors are relocated, so I can look into this further, but prior to doing so, I'm wondering if your sizes in `input_data = torch.randn((32, 40, 16))` is correct? I noticed you calibrated with `[32, 40, 32]` and you also use `32` for the kernel size, but you're doing inference on a different size (16) for the last dimension.

**Comment by kventinel** [comment]
> Are you implying ceil_mode = false worked for you? using your script, when ceil_mode = false, I get the following error

Sorry for misunderstanding, it also write RuntimeError for me. But i think it's ok, because i have too small last dimension for `ceil_mode=False` :) But is starts to work, when i change AvgPool to MaxPool.

> I think the two errors are related, so I can look into this further, but prior to doing so, I'm wondering if your sizes in input_data = torch.randn((32, 40, 16)) are correct? I noticed you calibrated with [32, 40, 32] and you also use 32 for the kernel size, but you're doing inference on a different size (16) for the last dimension.

I want to use tensors of different dimension with this model, so i just reproduce this case in my sample.

**Comment by dzdang** [comment]
I think qnnpack may not support the kernel size being bigger than the input. Max pool is also implemented with qnnpack, but when `ceil_mode = true`, it doesn't use qnnpack (see https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qpool.cpp#L383). This PR here https://github.com/pytorch/pytorch/pull/77792/files mimics this logic for avgpool, and it seems to resolve the issue when I tried it locally. are you able to build pytorch locally? if not, I think you'll have to keep the input size (+ padding) >= kernel size for now until this change makes its way to a future release

**Comment by HDCharles** [comment]
closing due to inactivity
