### ISSUE TITLE
 [Caffe2] Error running imported pytorch-model in caffe2

### ISSUE THREAD

**Issue by Pipoderoso** [pytorch/pytorch#7756]
## Issue description

I am trying to deploy a Pytorch model in C++.  First I am exporting the the model with its weight to ONNX with the function `torch.onnx.export()`. Then importing it with `onnn.load()`. Calling `onnx.helper.printable_graph` produces this output:

```
graph torch-jit-export (
  %0[FLOAT, 1x1x1080x1920]
) initializers (
  %1[FLOAT, 16x1x9x9]
  %2[FLOAT, 16]
  %3[FLOAT, 1]
  %4[FLOAT, 32x16x7x7]
  %5[FLOAT, 32]
  %6[FLOAT, 1]
  %7[FLOAT, 16x32x9x9]
  %8[FLOAT, 16]
  %9[FLOAT, 1]
  %10[FLOAT, 32x16x7x7]
  %11[FLOAT, 32]
  %12[FLOAT, 1]
  %13[FLOAT, 16x32x7x7]
  %14[FLOAT, 16]
  %15[FLOAT, 1]
  %16[FLOAT, 8x16x7x7]
  %17[FLOAT, 8]
  %18[FLOAT, 1]
  %19[FLOAT, 4x8x1x1]
  %20[FLOAT, 4]
  %21[FLOAT, 1]
  %22[FLOAT, 512x4096]
  %23[FLOAT, 512]
  %24[FLOAT, 1]
  %25[FLOAT, 256x512]
  %26[FLOAT, 256]
  %27[FLOAT, 1]
  %28[FLOAT, 10x256]
  %29[FLOAT, 10]
  %30[FLOAT, 1]
  %31[FLOAT, 20x32x7x7]
  %32[FLOAT, 20]
  %33[FLOAT, 1]
  %34[FLOAT, 40x20x5x5]
  %35[FLOAT, 40]
  %36[FLOAT, 1]
  %37[FLOAT, 20x40x5x5]
  %38[FLOAT, 20]
  %39[FLOAT, 1]
  %40[FLOAT, 10x20x5x5]
  %41[FLOAT, 10]
  %42[FLOAT, 1]
  %43[FLOAT, 24x18x3x3]
  %44[FLOAT, 24]
  %45[FLOAT, 1]
  %46[FLOAT, 32x24x3x3]
  %47[FLOAT, 32]
  %48[FLOAT, 1]
  %49[FLOAT, 32x16x4x4]
  %50[FLOAT, 16]
  %51[FLOAT, 1]
  %52[FLOAT, 16x8x4x4]
  %53[FLOAT, 8]
  %54[FLOAT, 1]
  %55[FLOAT, 1x8x1x1]
  %56[FLOAT, 1]
) {
  %57 = Constant[value = <Tensor>]()
  %58 = Conv[dilations = [1, 1], group = 1, kernel_shape = [9, 9], pads = [4, 4, 4, 4], strides = [1, 1]](%57, %1, %2)
  %59 = PRelu(%58, %3)
  %60 = Conv[dilations = [1, 1], group = 1, kernel_shape = [7, 7], pads = [3, 3, 3, 3], strides = [1, 1]](%59, %4, %5)
  %61 = PRelu(%60, %6)
  %62 = Conv[dilations = [1, 1], group = 1, kernel_shape = [9, 9], pads = [4, 4, 4, 4], strides = [1, 1]](%61, %7, %8)
  %63 = PRelu(%62, %9)
  %64 = MaxPool[kernel_shape = [2, 2], pads = [0, 0, 0, 0], strides = [2, 2]](%63)
  %65 = Conv[dilations = [1, 1], group = 1, kernel_shape = [7, 7], pads = [3, 3, 3, 3], strides = [1, 1]](%64, %10, %11)
  %66 = PRelu(%65, %12)
  %67 = MaxPool[kernel_shape = [2, 2], pads = [0, 0, 0, 0], strides = [2, 2]](%66)
  %68 = Conv[dilations = [1, 1], group = 1, kernel_shape = [7, 7], pads = [3, 3, 3, 3], strides = [1, 1]](%67, %13, %14)
  %69 = PRelu(%68, %15)
  %70 = Conv[dilations = [1, 1], group = 1, kernel_shape = [7, 7], pads = [3, 3, 3, 3], strides = [1, 1]](%69, %16, %17)
  %71 = PRelu(%70, %18)
  %72 = Conv[dilations = [1, 1], group = 1, kernel_shape = [7, 7], pads = [3, 3, 3, 3], strides = [1, 1]](%61, %31, %32)
  %73 = PRelu(%72, %33)
  %74 = MaxPool[kernel_shape = [2, 2], pads = [0, 0, 0, 0], strides = [2, 2]](%73)
  %75 = Conv[dilations = [1, 1], group = 1, kernel_shape = [5, 5], pads = [2, 2, 2, 2], strides = [1, 1]](%74, %34, %35)
  %76 = PRelu(%75, %36)
  %77 = MaxPool[kernel_shape = [2, 2], pads = [0, 0, 0, 0], strides = [2, 2]](%76)
  %78 = Conv[dilations = [1, 1], group = 1, kernel_shape = [5, 5], pads = [2, 2, 2, 2], strides = [1, 1]](%77, %37, %38)
  %79 = PRelu(%78, %39)
  %80 = Conv[dilations = [1, 1], group = 1, kernel_shape = [5, 5], pads = [2, 2, 2, 2], strides = [1, 1]](%79, %40, %41)
  %81 = PRelu(%80, %42)
  %82 = Concat[axis = 1](%71, %81)
  %83 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%82, %43, %44)
  %84 = PRelu(%83, %45)
  %85 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%84, %46, %47)
  %86 = PRelu(%85, %48)
  %87 = ConvTranspose[dilations = [1, 1], group = 1, kernel_shape = [4, 4], pads = [1, 1, 1, 1], strides = [2, 2]](%86, %49, %50)
  %88 = PRelu(%87, %51)
  %89 = ConvTranspose[dilations = [1, 1], group = 1, kernel_shape = [4, 4], pads = [1, 1, 1, 1], strides = [2, 2]](%88, %52, %53)
  %90 = PRelu(%89, %54)
  %91 = Conv[dilations = [1, 1], group = 1, kernel_shape = [1, 1], pads = [0, 0, 0, 0], strides = [1, 1]](%90, %55, %56)
  %92 = Relu(%91)
  return %92
}

```

When I try to use the model with `caffe2.python.onnx.backend.run_model(net, [input])` I get the following error.

```
Original python traceback for operator `3` in network `torch-jit-export_init` in exception above (most recent call last):
Traceback (most recent call last):
  File "onnxTest.py", line 16, in <module>
    outputs = backend.run_model(net, [img])
  File "/home/garcir/Downloads/otros/onnx/onnx/backend/base.py", line 76, in run_model
    return backend.run(inputs)
  File "/home/garcir/anaconda3/envs/caffe2-test/lib/python3.6/site-packages/caffe2/python/onnx/backend_rep.py", line 55, in run
    self.workspace.RunNet(self.init_net.name)
  File "/home/garcir/anaconda3/envs/caffe2-test/lib/python3.6/site-packages/caffe2/python/onnx/workspace.py", line 63, in f
    return getattr(workspace, attr)(*args, **kwargs)
  File "/home/garcir/anaconda3/envs/caffe2-test/lib/python3.6/site-packages/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/garcir/anaconda3/envs/caffe2-test/lib/python3.6/site-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at allocator.h:54] posix_memalign(&data, gCaffe2Alignment, nbytes) == 0. 12 vs 0 Error from operator: 
input: "59" input: "4" input: "5" output: "60" name: "" type: "Conv" arg { name: "strides" ints: 1 ints: 1 } arg { name: "pads" ints: 3 ints: 3 ints: 3 ints: 3 } arg { name: "dilations" ints: 1 ints: 1 } arg { name: "kernels" ints: 7 ints: 7 } arg { name: "group" i: 1 } device_option { device_type: 0 cuda_gpu_id: 0 }

```

## System Info
- Built from source, command I used: 
```
CONDA_INSTALL_LOCALLY=1 ./scripts/build_anaconda.sh --cuda 9.0 --cudnn 7 -DNCCL_ROOT_DIR:PATH=/home/garcir/anaconda3/envs/caffe2/lib -DCUDA_HOST_COMPILER=/home/garcir/anaconda3/envs/caffe2/bin/gcc -DUSE_MPI=OFF  -DUSE_CUDA=0N -DUSE_NCCL=ON ..
```

- Script output:

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Debian GNU/Linux 9.4 (stretch)
GCC version: (GCC) 5.2.0
CMake version: version 3.9.5

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 390.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy (1.14.3)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.0)
[pip3] onnx (1.1.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by mruberry** [comment]
Closing this issue due to age. If you're still experiencing an issue with ONNX please file a new issue. ONNX support has changed significantly since this issue was filed.
