### ISSUE TITLE
Exception out_of_range uncaught during torch::jit::load()

### ISSUE THREAD

**Issue by apach301** [pytorch/pytorch#77563]
### 🐛 Describe the bug

Hi,
I found uncaught exception during testing with libFuzzer.
The out_of_range exception occurs at `/pytorch/aten/src/ATen/native/quantized/cpu/conv_serialization.h:309 ` during execution of torch::jit::load() funciton:
```
    307      for (const auto i : c10::irange(kSpatialDim)) {
    308        (void)i; // Suppress unused variable
--->309        output_padding.emplace_back(config_vals.at(idx));
    310        idx++;
    311      }
    312      int64_t groups = config_vals.at(idx);
    313      idx++;
    314      int64_t flags = config_vals.at(idx);
    315      idx++;
    316      TORCH_INTERNAL_ASSERT(idx == static_cast<int64_t>(config_vals.size()),
```

The bug could be reproduced with `aot_model_compiler` binary:
```
aot_model_compiler --model=crash-file --model_name=name --model_version=1 --input_dims='1,3,224,224;2,2' --input_types='float;float'
```
Crashing file is provided in [crash.zip](https://github.com/pytorch/pytorch/files/8701818/crash.zip)

Asan output is:
```
  "AsanReport": [
    "==144206== ERROR: libFuzzer: deadly signal\n",
    "[Detaching after fork from child process 144581]\n",
    "    #0 0x59ec11 in __sanitizer_print_stack_trace /llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3\n",
    "    #1 0x513547 in fuzzer::PrintStackTrace() /llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5\n",
    "    #2 0x4f9753 in fuzzer::Fuzzer::CrashCallback() /llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233:3\n",
    "    #3 0x7fc4cf1a23bf  (/lib/x86_64-linux-gnu/libpthread.so.0+0x153bf)\n",
    "    #4 0x7fc4cefc418a in __libc_signal_restore_set /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h:86:3\n",
    "    #5 0x7fc4cefc418a in raise /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:48:3\n",
    "    #6 0x7fc4cefa3858 in abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79:7\n",
    "    #7 0x7fc4cf3ae910  (/lib/x86_64-linux-gnu/libstdc++.so.6+0x9e910)\n",
    "    #8 0x7fc4cf3ba38b  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa38b)\n",
    "    #9 0x7fc4cf3ba3f6 in std::terminate() (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa3f6)\n",
    "    #10 0x7fc4cf3ba6a8 in __cxa_throw (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa6a8)\n",
    "    #11 0x7fc4cf3b13aa  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xa13aa)\n",
    "    #12 0x7db74f in std::vector<long, std::allocator<long> >::_M_range_check(unsigned long) const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:1073:4\n",
    "    #13 0x1bf015e in std::vector<long, std::allocator<long> >::at(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:1094:2\n",
    "    #14 0x1bf015e in c10::intrusive_ptr<ConvPackedParamsBase<3u>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3u> > > deserialize_conv<3u>(std::tuple<long, std::vector<long, std::allocator<long> >, std::vector<c10::optional<at::Tensor>, std::allocator<c10::optional<at::Tensor> > > >) /pytorch_fuzz/aten/src/ATen/native/quantized/cpu/conv_serialization.h:309:45\n",
    "    #15 0x1becd27 in int register_conv_params<3>()::'lambda'(c10::IValue)::operator()(c10::IValue) const /pytorch_fuzz/aten/src/ATen/native/quantized/cpu/fbgemm_utils.cpp:396:18\n",
    "    #16 0x1becafe in std::enable_if<!(std::is_member_pointer<std::decay<int register_conv_params<3>()::'lambda'(c10::IValue) const&>::type>::value), std::result_of<int register_conv_params<3>()::'lambda'(c10::IValue) const& (c10::IValue&&)>::type>::type c10::guts::invoke<int register_conv_params<3>()::'lambda'(c10::IValue) const&, c10::IValue>(int register_conv_params<3>()::'lambda'(c10::IValue) const&, c10::IValue&&) /pytorch_fuzz/c10/util/C++17.h:177:10\n",
    "    #17 0x1bec6b7 in torch::class_<ConvPackedParamsBase<3> >& torch::class_<ConvPackedParamsBase<3> >::def_pickle<int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&), int register_conv_params<3>()::'lambda'(c10::IValue)>(int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)&&, int register_conv_params<3>()::'lambda'(c10::IValue)&&)::'lambda'(c10::tagged_capsule<ConvPackedParamsBase<3> >, c10::IValue&&)::operator()(c10::tagged_capsule<ConvPackedParamsBase<3> >, c10::IValue&&) const /pytorch_fuzz/torch/custom_class.h:328:11\n",
    "    #18 0x1bec48c in c10::guts::infer_function_traits<int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)>::type::return_type torch::detail::call_torchbind_method_from_stack<torch::class_<ConvPackedParamsBase<3> >& torch::class_<ConvPackedParamsBase<3> >::def_pickle<int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&), int register_conv_params<3>()::'lambda'(c10::IValue)>(int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)&&, int register_conv_params<3>()::'lambda'(c10::IValue)&&)::'lambda'(c10::tagged_capsule<ConvPackedParamsBase<3> >, c10::IValue&&), false, 0ul, 1ul>(int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)&, std::vector<c10::IValue, std::allocator<c10::IValue> >&, std::integer_sequence<unsigned long, 0ul, 1ul>) /pytorch_fuzz/torch/custom_class_detail.h:139:10\n",
    "    #19 0x1bec173 in c10::guts::infer_function_traits<int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)>::type::return_type torch::detail::call_torchbind_method_from_stack<torch::class_<ConvPackedParamsBase<3> >& torch::class_<ConvPackedParamsBase<3> >::def_pickle<int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&), int register_conv_params<3>()::'lambda'(c10::IValue)>(int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)&&, int register_conv_params<3>()::'lambda'(c10::IValue)&&)::'lambda'(c10::tagged_capsule<ConvPackedParamsBase<3> >, c10::IValue&&), false>(int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)&, std::vector<c10::IValue, std::allocator<c10::IValue> >&) /pytorch_fuzz/torch/custom_class_detail.h:153:10\n",
    "    #20 0x1bec173 in torch::detail::BoxedProxy<void, torch::class_<ConvPackedParamsBase<3> >& torch::class_<ConvPackedParamsBase<3> >::def_pickle<int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&), int register_conv_params<3>()::'lambda'(c10::IValue)>(int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)&&, int register_conv_params<3>()::'lambda'(c10::IValue)&&)::'lambda'(c10::tagged_capsule<ConvPackedParamsBase<3> >, c10::IValue&&)>::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >&, torch::class_<ConvPackedParamsBase<3> >& torch::class_<ConvPackedParamsBase<3> >::def_pickle<int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&), int register_conv_params<3>()::'lambda'(c10::IValue)>(int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)&&, int register_conv_params<3>()::'lambda'(c10::IValue)&&)::'lambda'(c10::tagged_capsule<ConvPackedParamsBase<3> >, c10::IValue&&)&) /pytorch_fuzz/torch/custom_class_detail.h:174:5\n",
    "    #21 0x1bec074 in torch::jit::Function* torch::class_<ConvPackedParamsBase<3> >::defineMethod<torch::class_<ConvPackedParamsBase<3> >& torch::class_<ConvPackedParamsBase<3> >::def_pickle<int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&), int register_conv_params<3>()::'lambda'(c10::IValue)>(int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)&&, int register_conv_params<3>()::'lambda'(c10::IValue)&&)::'lambda'(c10::tagged_capsule<ConvPackedParamsBase<3> >, c10::IValue&&)>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::initializer_list<torch::arg>)::'lambda'(std::vector<c10::IValue, std::allocator<c10::IValue> >&)::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >&) /pytorch_fuzz/torch/custom_class.h:407:7\n",
    "    #22 0x1bec074 in int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&) std::__invoke_impl<void, torch::jit::Function* torch::class_<ConvPackedParamsBase<3> >::defineMethod<torch::class_<ConvPackedParamsBase<3> >& torch::class_<ConvPackedParamsBase<3> >::def_pickle<int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&), int register_conv_params<3>()::'lambda'(c10::IValue)>(int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&)&&, int register_conv_params<3>()::'lambda'(c10::IValue)&&)::'lambda'(c10::tagged_capsule<ConvPackedParamsBase<3> >, c10::IValue&&)>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int register_conv_params<3>()::'lambda'(c10::intrusive_ptr<ConvPackedParamsBase<3>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<3> > > const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::initializer_list<torch::arg>)::'lambda'(std::vector<c10::IValue, std::allocator<c10::IValue> >&)&, std::vector<c10::IValue, std::allocator<c10::IValue> >&>(std::__invoke_other, int register_conv_params<3>()::'lambda'(c10::IValue)&&, std::vector<c10::IValue, std::allocator<c10::IValue> >&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:60:14\n",
    "    #23 0xab135c in torch::jit::Function::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) /pytorch_fuzz/aten/src/ATen/core/function.h:61:5\n",
    "    #24 0x9e0533f in torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1::operator()(c10::StrongTypePtr const&, c10::IValue) const /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:159:7\n",
    "    #25 0x9e0533f in c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > std::__invoke_impl<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> >, torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1&, c10::StrongTypePtr, c10::IValue>(std::__invoke_other, torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1&, c10::StrongTypePtr&&, c10::IValue&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:60:14\n",
    "    #26 0x9e044b0 in std::enable_if<__and_<std::__not_<std::is_void<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > > >, std::is_convertible<std::__invoke_result<torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1&, c10::StrongTypePtr, c10::IValue>::type, c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > > >::value, c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > >::type std::__invoke_r<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> >, torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1&, c10::StrongTypePtr, c10::IValue>(torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1&, c10::StrongTypePtr&&, c10::IValue&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:141:14\n",
    "    #27 0x9e0431b in std::_Function_handler<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue), torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1>::_M_invoke(std::_Any_data const&, c10::StrongTypePtr&&, c10::IValue&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:291:9\n",
    "    #28 0x9eed44d in std::function<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue)>::operator()(c10::StrongTypePtr, c10::IValue) const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:622:14\n",
    "    #29 0x9eed0ee in torch::jit::Unpickler::readGlobal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_9::operator()() const /pytorch_fuzz/torch/csrc/jit/serialization/unpickler.cpp:704:20\n",
    "    #30 0x9eed0ee in void std::__invoke_impl<void, torch::jit::Unpickler::readGlobal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_9&>(std::__invoke_other, torch::jit::Unpickler::readGlobal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_9&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:60:14\n",
    "    #31 0x9ecb6d4 in torch::jit::Unpickler::readInstruction() /pytorch_fuzz/torch/csrc/jit/serialization/unpickler.cpp:444:7\n",
    "    #32 0x9ec9ac7 in torch::jit::Unpickler::run() /pytorch_fuzz/torch/csrc/jit/serialization/unpickler.cpp:226:27\n",
    "    #33 0x9ec9762 in torch::jit::Unpickler::parse_ivalue() /pytorch_fuzz/torch/csrc/jit/serialization/unpickler.cpp:183:3\n",
    "    #34 0x9e0c84e in torch::jit::readArchiveAndTensors(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<std::function<c10::StrongTypePtr (c10::QualifiedName const&)> >, c10::optional<std::function<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue)> >, c10::optional<c10::Device>, caffe2::serialize::PyTorchStreamReader&, c10::Type::SingletonOrSharedTypePtr<c10::Type> (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::shared_ptr<torch::jit::DeserializationStorageContext>) /pytorch_fuzz/torch/csrc/jit/serialization/import_read.cpp:54:20\n",
    "    #35 0x9e02779 in torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:171:10\n",
    "    #36 0x9dfe60b in torch::jit::(anonymous namespace)::ScriptModuleDeserializer::deserialize(c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:274:19\n",
    "    #37 0x9e013c4 in torch::jit::load(std::shared_ptr<caffe2::serialize::ReadAdapterInterface>, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:403:23\n",
    "    #38 0x9e01977 in torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:375:17\n",
    "    #39 0x9e0176c in torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>) /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:367:10\n",
    "    #40 0x5cdfd2 in LLVMFuzzerTestOneInput /load_fuzz.cc:45:18\n",
    "    #41 0x4fac81 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15\n",
    "    #42 0x4e4b9c in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6\n",
    "    #43 0x4ea8eb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9\n",
    "    #44 0x513e82 in main /llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10\n",
    "    #45 0x7fc4cefa50b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16\n",
    "    #46 0x4df4bd in _start (/fuzz/load_fuzz_fixed2+0x4df4bd)\n",
```
 

### Versions

PyTorch version: 1.12.0a0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 14.0.0 (https://github.com/llvm/llvm-project.git de5b16d8ca2d14ff0d9b6be9cf40566bc7eb5a01)
CMake version: version 3.22.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-175-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.2
[conda] Could not collect

**Comment by Gamrix** [comment]
torch::jit::load should only be used with trusted inputs. This is a Won't Fix
