### ISSUE TITLE
PrimTorch refs do not match argument naming with their PyTorch counterparts

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#77675]
### 🐛 Describe the bug

```
>>> import torch
>>> torch.nn.functional.elu(input=torch.randn(2))
tensor([-0.3709,  0.5241])
>>> import torch._refs.nn.functional
>>> torch._refs.nn.functional.elu(input=torch.randn(2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/raid/ezyang/pytorch-scratch2/torch/_prims/wrappers.py", line 93, in _fn
    bound = sig.bind(*args, **kwargs)
  File "/scratch/ezyang/pytorch-scratch2-env/lib/python3.8/inspect.py", line 3025, in bind
    return self._bind(args, kwargs)
  File "/scratch/ezyang/pytorch-scratch2-env/lib/python3.8/inspect.py", line 2940, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'a'
```

Unfortunately because nothing in PyTorch is positional-only, the argument names are public API

### Versions

master

**Comment by mruberry** [comment]
Ideally we would make some args positional-only, but yes, in lieu of that we should just make the names consistent
