### ISSUE TITLE
Failed for accumulation of gradients for RNN with cudnn

### ISSUE THREAD

**Issue by meijieru** [pytorch/pytorch#777]
```python
import torch
import torch.nn as nn
from torch.autograd import Variable

lstm = nn.LSTM(2, 3, 1, bidirectional=True)
lstm.cuda()

input = torch.ones(4, 5, 2)  # [T, b, i]
input = input.cuda()
input = Variable(input, requires_grad=True)
output, _ = lstm(input)
output.backward(torch.ones(output.size()).cuda())
output.backward(torch.ones(output.size()).cuda())
```
The desired behavior seems to accumulate the gradients for lstm's parameters, however it failed with error message
```sh
Traceback (most recent call last):
  File "test_lstm.py", line 18, in <module>
    output.backward(torch.ones(output.size()).cuda())
  File "/home/jrmei/.local/lib/python2.7/site-packages/torch/autograd/variable.py", line 158, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
  File "/home/jrmei/.local/lib/python2.7/site-packages/torch/autograd/function.py", line 208, in backward
    nested_gradients = _unflatten(gradients, self._nested_output)
AttributeError: 'CudnnRNN' object has no attribute '_nested_output'
```

**Comment by soumith** [comment]
first step, upgrade your pytorch install to 0.1.9.

Second,

here is a fixed script:

```
import torch
import torch.nn as nn
from torch.autograd import Variable

lstm = nn.LSTM(2, 3, 1, bidirectional=True)
lstm.cuda()

input = torch.ones(4, 5, 2)  # [T, b, i]
input = input.cuda()
input = Variable(input, requires_grad=True)
output, _ = lstm(input)
output.backward(torch.ones(output.size()).cuda(), retain_variables=True)
output.backward(torch.ones(output.size()).cuda())
```
