### ISSUE TITLE
YOLOv5: MPS on Macbook Air M1 NotImplementedError: Could not run 'aten::empty.memory_format' with arguments...

### ISSUE THREAD

**Issue by glenn-jocher** [pytorch/pytorch#77748]
### 🐛 Describe the bug

Following official example here causes an error.
https://pytorch.org/docs/master/notes/mps.html

```python
import torch
x = torch.ones(5, device="mps")

NotImplementedError: Could not run 'aten::empty.memory_format' with arguments from the 'MPS' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty.memory_format' is only available for these backends: [Dense, Conjugate, Negative, VmapMode, FuncTorchGradWrapper, MPS, UNKNOWN_TENSOR_TYPE_ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseXPU, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID].
```

### Versions

```
Collecting environment information...
PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23)  [Clang 6.0 (clang-600.0.57)] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220518
[pip3] torchvision==0.13.0.dev20220518
[conda] numpy                     1.22.3           py39h690d673_0    conda-forge
[conda] pytorch                   1.10.2          cpu_py39hbfdb42d_1    conda-forge
[conda] torchvision               0.11.3          cpu_py39h85ba581_1    conda-forge
```

<img width="698" alt="Screen Shot 2022-05-18 at 5 47 42 PM" src="https://user-images.githubusercontent.com/26833433/169086088-1979613c-e4d4-4e3e-bb01-40970e57a803.png">

**Comment by albanD** [comment]
Hi,

The version of python that you're using is `x86` and not `arm` (as you can see in the collect env report).
You will need to use a native version of python `arm` to be able to use MPS. Can you try that and see if it solves the issue please?

**Comment by glenn-jocher** [comment]
@albanD I see here that as of 3.9.1 this should fully support arm64 in the same macOS executable? Maybe I just got unlucky installing 3.9.0, I'll try again with 3.9.1.
https://docs.python.org/3/whatsnew/3.9.html
<img width="1249" alt="Screen Shot 2022-05-18 at 6 41 04 PM" src="https://user-images.githubusercontent.com/26833433/169096609-43acacf3-0767-4574-aa00-06a11694b7f4.png">

**Comment by albanD** [comment]
Yes, you can see the latest python download page: https://www.python.org/downloads/macos/
There are intel-only binaries and universal binaries there.
You will need to get a universal binary (that contains both x86 and arm version) to get full MPS support.

note that this will also mean that you won't have to go through the Rosetta layer to run your python code which might be faster :)

**Comment by glenn-jocher** [comment]
@albanD I installed Python 3.9.1 universal binary and saw significant speedup with PyTorch stable (torch==1.11.0 torchvision 0.12.0), but am not able to run nightly because it seems the pip installer is pairing torch nightly 1.12 with torchvision stable 0.12. This is the error message:

```
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
```

This is the version info I have now:
```
Collecting environment information...
PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:44:01)  [Clang 12.0.0 (clang-1200.0.32.27)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220518
[pip3] torchvision==0.12.0
```

**Comment by gchanan** [comment]
@albanD perhaps we should change the `mps` note/example to do the equivalent of `torch.cuda.is_available()` check.

**Comment by albanD** [comment]
@glenn-jocher do you still have this issue if you install a nightly version of torchvision alongside the nightly version of torch ?

**Comment by glenn-jocher** [comment]
@albanD I successfully installed torch and torchvision nightly. When I run YOLOv5 inference I get a different error on model load, i.e. caused by `model = torch.load('yolov5s.pt', map_location)` where map_location is `torch.device(type='mps')`. I think perhaps map_location is not ready to accept `mps` as an option?

To reproduce:
```bash
git clone https://github.com/ultralytics/yolov5 -b apple/mps
cd yolov5
pip install --pre -r requirements.txt --extra-index-url https://download.pytorch.org/whl/nightly/cpu
python detect.py

# Error ---
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-da6f12058d13>", line 1, in <cell line: 1>
    torch.load(attempt_download(w), map_location=map_location)
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/torch/serialization.py", line 1016, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/torch/serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/torch/serialization.py", line 973, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/Users/glennjocher/PycharmProjects/yolov5/venv/lib/python3.9/site-packages/torch/serialization.py", line 179, in default_restore_location
    raise RuntimeError("don't know how to restore data location of "
RuntimeError: don't know how to restore data location of torch._UntypedStorage (tagged with mps)
```

**Comment by acostin1** [comment]
I had to compile torchvision from source to get it working.

**Comment by glenn-jocher** [comment]
@acostin1 did the same and am now able to use torch and torchvision arm64 nightly. 

@albanD after installing torch nightly (pip) and torchvision nightly (from source) I'm now seeing a new error message on YOLOv5-nano inference on Macbook Air M1 (this model is only 2M parameters):
```
/AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 25600 bytes
```

Reproduce (after installing torch and torchvision arm64 nightly):
```
git clone https://github.com/ultralytics/yolov5 -b apple/mps
cd yolov5
python detect.py --weights yolov5n.pt --device cpu  # verify CPU inference
python detect.py --weights yolov5n.pt --device mps  # error on MPS inference
```

Versions
```
PyTorch version: 1.12.0.dev20220519
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:44:01)  [Clang 12.0.0 (clang-1200.0.32.27)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220519
[pip3] torchvision==0.13.0a0+9d9cfab
```

**Comment by ElliotQi** [comment]
@albanD  So how is it going?

**Comment by ElliotQi** [comment]
您好,邮件已收到,会尽快处理
