### ISSUE TITLE
Upload Test Stats fails when parsing test reports

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#78138]
### 🐛 Describe the bug

Upload test stats, the workflow that ports our test XMLs to Rockset sometimes fails when unable to parse the job ID from the artifact name: https://github.com/pytorch/pytorch/runs/6562448826?check_suite_focus=true

```
Traceback (most recent call last):
  File "tools/stats/upload_test_stats.py", line 200, in <module>
    xml_report, int(args.workflow_run_id), int(args.workflow_run_attempt)
  File "tools/stats/upload_test_stats.py", line 32, in parse_xml_report
    job_id = int(report.parts[0].rpartition("_")[2])
ValueError: invalid literal for int() with base 10: ''
```

This step is very important for stats tracking + should never fail. If it does fail, it should be retried (though in this case it looks like there are other upstream problems). 

### Versions

CI

https://github.com/pytorch/pytorch/actions/workflows/upload-test-stats.yml?query=is%3Afailure

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
cc @suo
