### ISSUE TITLE
`baddmm` triggers INTERNAL ASSERT FAILED when input requires grad

### ISSUE THREAD

**Issue by upupyy** [pytorch/pytorch#78143]
### 🐛 Describe the bug

`baddmm` triggers INTERNAL ASSERT FAILED when input requires grad

```python
import torch

input_tensor = torch.rand([10, 3, 5], dtype=torch.complex64)
batch1_tensor = torch.randint(-4, 2, [10, 3, 4], dtype=torch.int8)
batch2_tensor = torch.randint(-4, 1, [10, 4, 5], dtype=torch.int8)

input = input_tensor.clone()
batch1 = batch1_tensor.clone()
batch2 = batch2_tensor.clone()
res1 = torch.baddbmm(input, batch1, batch2, )
# Normal Pass

input = input_tensor.clone().requires_grad_()
batch1 = batch1_tensor.clone()
batch2 = batch2_tensor.clone()
res2 = torch.baddbmm(input, batch1, batch2, )
# RuntimeError: isDifferentiableType(variable.scalar_type())INTERNAL ASSERT FAILED at "/Users/distiller/project/pytorch/torch/csrc/autograd/functions/utils.h":65, please report a bug to PyTorch.
```

### Versions

pytorch: 1.11.0

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by dcci** [comment]
This is fixed in '2.6.0a0+git0f474a9'.
```
>>> torch.__version__
'2.6.0a0+git0f474a9'
```

`baddbmm` requires the same dtype, so now the operation errors out earlier (in both cases)

```
>>> import torch
>>> input_tensor = torch.rand([10, 3, 5], dtype=torch.complex64)
>>> batch1_tensor = torch.randint(-4, 2, [10, 3, 4], dtype=torch.int8)
>>> batch2_tensor = torch.randint(-4, 1, [10, 4, 5], dtype=torch.int8)
>>> input = input_tensor.clone()
>>> batch1 = batch1_tensor.clone()
>>> batch2 = batch2_tensor.clone()
>>> res1 = torch.baddbmm(input, batch1, batch2, )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Input dtypes must be the same, got: input c10::complex<float>, batch1: signed char, batch2: signed char
>>> input = input_tensor.clone().requires_grad_()
>>> batch1 = batch1_tensor.clone()
>>> batch2 = batch2_tensor.clone()
>>> res2 = torch.baddbmm(input, batch1, batch2, )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Input dtypes must be the same, got: input c10::complex<float>, batch1: signed char, batch2: signed char
```
