### ISSUE TITLE
torch.fx: symbolic_trace: ones() received an invalid combination of arguments

### ISSUE THREAD

**Issue by silvasean** [pytorch/pytorch#78487]
### 🐛 Describe the bug

Run the following standalone python file.

```
import torch
from torch.fx import symbolic_trace
from transformers import AutoModelForSequenceClassification


class OnlyLogitsHuggingFaceModel(torch.nn.Module):
    """Wrapper that returns only the logits from a HuggingFace model."""

    def __init__(self):
        super().__init__()
        self.model = AutoModelForSequenceClassification.from_pretrained(
            "ProsusAI/finbert",  # The pretrained model name.
            num_labels=3,
            output_attentions=False,
            output_hidden_states=False,
            torchscript=True,
        )
        self.model.eval()

    def forward(self, input):
        # Return only the logits.
        return self.model(input)[0]



traced = symbolic_trace(OnlyLogitsHuggingFaceModel())
```

I get the error:
```
TypeError: ones() received an invalid combination of arguments - got (tuple, device=Attribute), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```
Full error log: https://gist.github.com/silvasean/a11f5219e8d931014ae4046a1fafcef7

### Versions

PyTorch version: 1.13.0.dev20220530+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux rodete (x86_64)
GCC version: (Debian 11.2.0-19) 11.2.0
Clang version: 13.0.1-3+build2
CMake version: version 3.22.4
Libc version: glibc-2.33

Python version: 3.9.12 (main, Mar 24 2022, 13:02:21)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.17.6-1rodete1-amd64-x86_64-with-glibc2.33
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] iree-torch==0.0.1
[pip3] numpy==1.23.0rc1
[pip3] torch==1.13.0.dev20220530+cpu
[pip3] torch-mlir==20220530.482
[pip3] torchvision==0.14.0.dev20220530+cpu
[conda] Could not collect

**Comment by BrettRyland** [comment]
This also affects any model using deformable convolutions, e.g., [trace_dcn_bug.py](https://github.com/pytorch/pytorch/files/9055221/trace_dcn_bug.py.txt) gives
```console
brett@br-workhorse:~/repos/Autosensor/NN/tmp$ python3 trace_dcn_bug.py 
torch.Size([1, 3, 10, 10])
Traceback (most recent call last):
  File "/home/brett/repos/Autosensor/NN/tmp/trace_dcn_bug.py", line 53, in <module>
    symbolic_trace(m)
  File "/home/brett/.local/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 857, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/home/brett/.local/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 566, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/home/brett/repos/Autosensor/NN/tmp/trace_dcn_bug.py", line 47, in forward
    return self.deform_conv2d(x)
  File "/home/brett/.local/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 556, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/home/brett/.local/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 372, in call_module
    return forward(*args, **kwargs)
  File "/home/brett/.local/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 552, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/home/brett/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/brett/repos/Autosensor/NN/tmp/trace_dcn_bug.py", line 37, in forward
    x = self.conv2d(x, offset)
  File "/home/brett/.local/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 556, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/home/brett/.local/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 372, in call_module
    return forward(*args, **kwargs)
  File "/home/brett/.local/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 552, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/home/brett/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/brett/.local/lib/python3.10/site-packages/torchvision/ops/deform_conv.py", line 170, in forward
    return deform_conv2d(
  File "/home/brett/.local/lib/python3.10/site-packages/torchvision/ops/deform_conv.py", line 71, in deform_conv2d
    mask = torch.zeros((input.shape[0], 0), device=input.device, dtype=input.dtype)
TypeError: zeros() received an invalid combination of arguments - got (tuple, dtype=Attribute, device=Attribute), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```
I suspect this is related to #51803 with a potential solution provided by ModelTC/MQBench#82.

**Comment by zjc664656505** [comment]
May I know whether there is any applicable solution to this issue?
