### ISSUE TITLE
RuntimeError: Event device type CUDA does not match blocking stream’s device type CPU 

### ISSUE THREAD

**Issue by pan24n** [pytorch/pytorch#78482]
### 🐛 Describe the bug

when I do the unittest of test_autograd.py on pytorch1.11.0, it throw an RuntimeError: Event device type CUDA does not match blocking stream’s device type CPU. I want to know what causes this error.

Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper
    method(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper
    method(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
    raise rte
  File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 939, in multi_fn
    return fn(slf, devices, *args, **kwargs)
  File "pytorch/test/test_autograd.py", line 8644, in test_backward_device
    Identity.apply(v).backward()
  File "/root/.local/lib/python3.7/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: Event device type CUDA does not match blocking stream's device type CPU.

### Versions

PyTorch version: 1.11.0a0
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 4.3.22211

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: 14.0.0 
CMake version: version 2.8.12.2

Is CUDA available: True

**Comment by albanD** [comment]
Are you trying to run the rocm build with the cuda backend?

**Comment by sunflower93** [comment]
> Are you trying to run the rocm build with the cuda backend?

Traceback (most recent call last):
  File "/home/zjlab/shao/real_business_cycle/train_multi_exps.py", line 108, in <module>
    run_experiment_batch_parallel(
  File "/home/zjlab/shao/real_business_cycle/experiment_utils.py", line 119, in run_experiment_batch_parallel
    m.train()
  File "/home/zjlab/shao/real_business_cycle/rbc/cuda_manager.py", line 1732, in train
    consumer_ppo_step(
  File "/home/zjlab/shao/real_business_cycle/rbc/cuda_manager.py", line 323, in consumer_ppo_step
    loss.backward()
  File "/home/zjlab/anaconda3/envs/shao/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/zjlab/anaconda3/envs/shao/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Event device type CUDA does not match blocking stream's device type CPU.

**Comment by sunflower93** [comment]
> Are you trying to run the rocm build with the cuda backend?
Traceback (most recent call last):
  .........
  File "/home/zjlab/anaconda3/envs/shao/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/zjlab/anaconda3/envs/shao/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Event device type CUDA does not match blocking stream's device type CPU.

**Comment by sunflower93** [comment]
> ### 🐛 Describe the bug
> when I do the unittest of test_autograd.py on pytorch1.11.0, it throw an RuntimeError: Event device type CUDA does not match blocking stream’s device type CPU. I want to know what causes this error.
> 
> ```
> Traceback (most recent call last):
>   File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper
>     method(*args, **kwargs)
>   File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper
>     method(*args, **kwargs)
>   File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test
>     raise rte
>   File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
>     result = test(self, **param_kwargs)
>   File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 939, in multi_fn
>     return fn(slf, devices, *args, **kwargs)
>   File "pytorch/test/test_autograd.py", line 8644, in test_backward_device
>     Identity.apply(v).backward()
>   File "/root/.local/lib/python3.7/site-packages/torch/_tensor.py", line 363, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
>   File "/root/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
>     allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
> RuntimeError: Event device type CUDA does not match blocking stream's device type CPU.
> ```
> 
> ### Versions
> PyTorch version: 1.11.0a0 Is debug build: False CUDA used to build PyTorch: N/A ROCM used to build PyTorch: 4.3.22211
> 
> OS: CentOS Linux 7 (Core) (x86_64) GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5) Clang version: 14.0.0 CMake version: version 2.8.12.2
> 
> Is CUDA available: True
> 
> cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @ngimel @mruberry

Hello, has this problem been solved?

**Comment by pan24n** [comment]
Yes, in the beginning, I didn't use the official ROCM environment, so it had some problems, made some changes, which have now been fixed. I think using the official ROCM package, you probably won't run into this problem. I tested it on Rocm5.1 + Python3.7 + Pytorch1.11, and it worked













在 2022-08-01 13:55:01，"sunflower93" ***@***.***> 写道：

Describe the bug

when I do the unittest of test_autograd.py on pytorch1.11.0, it throw an RuntimeError: Event device type CUDA does not match blocking stream’s device type CPU. I want to know what causes this error.

Traceback (most recent call last):

  File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper

    method(*args, **kwargs)

  File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper

    method(*args, **kwargs)

  File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test

    raise rte

  File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test

    result = test(self, **param_kwargs)

  File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 939, in multi_fn

    return fn(slf, devices, *args, **kwargs)

  File "pytorch/test/test_autograd.py", line 8644, in test_backward_device

    Identity.apply(v).backward()

  File "/root/.local/lib/python3.7/site-packages/torch/_tensor.py", line 363, in backward

    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)

  File "/root/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward

    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass

RuntimeError: Event device type CUDA does not match blocking stream's device type CPU.


Versions

PyTorch version: 1.11.0a0 Is debug build: False CUDA used to build PyTorch: N/A ROCM used to build PyTorch: 4.3.22211

OS: CentOS Linux 7 (Core) (x86_64) GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5) Clang version: 14.0.0 CMake version: version 2.8.12.2

Is CUDA available: True

cc @***@***.***@***@***.***@***@***.***@***@***.***@***@***.***@mruberry

Hello, has this problem been solved?

**Comment by sunflower93** [comment]
> Yes, in the beginning, I didn't use the official ROCM environment, so it had some problems, made some changes, which have now been fixed. I think using the official ROCM package, you probably won't run into this problem. I tested it on Rocm5.1 + Python3.7 + Pytorch1.11, and it worked 在 2022-08-01 13:55:01，"sunflower93" ***@***.***> 写道： Describe the bug when I do the unittest of test_autograd.py on pytorch1.11.0, it throw an RuntimeError: Event device type CUDA does not match blocking stream’s device type CPU. I want to know what causes this error. Traceback (most recent call last): File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper method(*args, **kwargs) File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1754, in wrapper method(*args, **kwargs) File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 389, in instantiated_test raise rte File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test result = test(self, **param_kwargs) File "/root/.local/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 939, in multi_fn return fn(slf, devices, *args, **kwargs) File "pytorch/test/test_autograd.py", line 8644, in test_backward_device Identity.apply(v).backward() File "/root/.local/lib/python3.7/site-packages/torch/_tensor.py", line 363, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "/root/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward allow_unreachable=True, accumulate_grad=True) # Calls into the C++ engine to run the backward pass RuntimeError: Event device type CUDA does not match blocking stream's device type CPU. Versions PyTorch version: 1.11.0a0 Is debug build: False CUDA used to build PyTorch: N/A ROCM used to build PyTorch: 4.3.22211 OS: CentOS Linux 7 (Core) (x86_64) GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5) Clang version: 14.0.0 CMake version: version 2.8.12.2 Is CUDA available: True cc @***@***.***@***@***.***@***@***.***@***@***.***@***@***.***@mruberry Hello, has this problem been solved? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

thx
