### ISSUE TITLE
Latest nightly can not be imported using Python-3.7.0

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#78499]
### 🐛 Describe the bug

Regression introduced by https://github.com/pytorch/pytorch/commit/7ea5fa3dd4c544f2508c5697f103d4ef8f183ed8
```
% python3
Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nshulga/miniconda3/envs/py_37-test/lib/python3.7/site-packages/torch/__init__.py", line 871, in <module>
    from torch import quantization as quantization
  File "/Users/nshulga/miniconda3/envs/py_37-test/lib/python3.7/site-packages/torch/quantization/__init__.py", line 1, in <module>
    from .quantize import *  # noqa: F403
  File "/Users/nshulga/miniconda3/envs/py_37-test/lib/python3.7/site-packages/torch/quantization/quantize.py", line 10, in <module>
    from torch.ao.quantization.quantize import _convert
  File "/Users/nshulga/miniconda3/envs/py_37-test/lib/python3.7/site-packages/torch/ao/quantization/__init__.py", line 3, in <module>
    from .fake_quantize import *  # noqa: F403
  File "/Users/nshulga/miniconda3/envs/py_37-test/lib/python3.7/site-packages/torch/ao/quantization/fake_quantize.py", line 8, in <module>
    from torch.ao.quantization.observer import (
  File "/Users/nshulga/miniconda3/envs/py_37-test/lib/python3.7/site-packages/torch/ao/quantization/observer.py", line 15, in <module>
    from torch.ao.quantization.utils import check_min_max_valid, calculate_qmin_qmax
  File "/Users/nshulga/miniconda3/envs/py_37-test/lib/python3.7/site-packages/torch/ao/quantization/utils.py", line 414, in <module>
    def _get_default_kwargs(f: Callable) -> typing.OrderedDict[str, Any]:
AttributeError: module 'typing' has no attribute 'OrderedDict'
```

### Versions

Nightly

cc @ezyang @gchanan @zou3519

**Comment by malfet** [comment]
Can be easily fixed by stringifying the type, but I wonder if we should just up minversion to 3.7.2?

**Comment by albanD** [comment]
According to https://github.com/pytorch/pytorch/blob/master/RELEASE.md#python we can drop 3.7 altogether.
But colab is still on 3.7 (though they use the latest patch version, 3.7.13 as of writing).
I think that `3.7.8` is a good choice in the middle as it is the last bugfix release for 3.7 (https://peps.python.org/pep-0537/).

**Comment by albanD** [comment]
This is fixed now.
After some offline discussions, we're going to make `3.7.8` the new minimum required version to avoid such issues in the future and get a CI job that runs that minimal version.
