### ISSUE TITLE
JIT test failure

### ISSUE THREAD

**Issue by csarofeen** [pytorch/pytorch#7851]
On recent builds I've been getting the following jit error. Has anything changed that would change the produced jit code?

```
Running test_jit ...
Fs........s......x..x..x.....x..............s........s.........................................................................................
======================================================================
FAIL: test_alexnet (test_jit.TestJit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/test/test_jit.py", line 649, in test_alexnet
    self.assertExpectedGraph(trace)
  File "/opt/pytorch/pytorch/test/test_jit.py", line 111, in assertExpectedGraph
    self.assertExpected(str(graph), *args, **kwargs)
  File "/opt/pytorch/pytorch/test/common.py", line 414, in assertExpected
    self.assertMultiLineEqual(expected, s)
AssertionError: 'grap[3314 chars]9216), %38 : Handle = ^Dropout(0.5, True, Fals[1460 chars]n}\n' != 'grap[3314 chars]9216) = ^Dropout(0.5, True, False)(%36), scope[1432 chars]n}\n'
  graph(%0 : Double(1, 3, 224, 224)
        %1 : Double(64, 3, 11, 11)
        %2 : Double(64)
        %3 : Double(192, 64, 5, 5)
        %4 : Double(192)
        %5 : Double(384, 192, 3, 3)
        %6 : Double(384)
        %7 : Double(256, 384, 3, 3)
        %8 : Double(256)
        %9 : Double(256, 256, 3, 3)
        %10 : Double(256)
        %11 : Double(4096, 9216)
        %12 : Double(4096)
        %13 : Double(4096, 4096)
        %14 : Double(4096)
        %15 : Double(1000, 4096)
        %16 : Double(1000)) {
    %17 : Double(1, 64, 55, 55) = aten::_convolution[stride=[4, 4], padding=[2, 2], dilation=[1, 1], transposed=0, output_padding=[0, 0], groups=1, benchmark=0, deterministic=0, cudnn_enabled=1](%0, %1, %2), scope: AlexNet/Sequential[features]/Conv2d[0]
    %18 : Double(1, 64, 55, 55) = aten::threshold[threshold={0}, value={0}](%17), scope: AlexNet/Sequential[features]/ReLU[1]
    %19 : Double(1, 64, 27, 27), %20 : Long(1, 64, 27, 27) = aten::max_pool2d[kernel_size=[3, 3], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=0](%18), scope: AlexNet/Sequential[features]/MaxPool2d[2]
    %21 : Double(1, 192, 27, 27) = aten::_convolution[stride=[1, 1], padding=[2, 2], dilation=[1, 1], transposed=0, output_padding=[0, 0], groups=1, benchmark=0, deterministic=0, cudnn_enabled=1](%19, %3, %4), scope: AlexNet/Sequential[features]/Conv2d[3]
    %22 : Double(1, 192, 27, 27) = aten::threshold[threshold={0}, value={0}](%21), scope: AlexNet/Sequential[features]/ReLU[4]
    %23 : Double(1, 192, 13, 13), %24 : Long(1, 192, 13, 13) = aten::max_pool2d[kernel_size=[3, 3], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=0](%22), scope: AlexNet/Sequential[features]/MaxPool2d[5]
    %25 : Double(1, 384, 13, 13) = aten::_convolution[stride=[1, 1], padding=[1, 1], dilation=[1, 1], transposed=0, output_padding=[0, 0], groups=1, benchmark=0, deterministic=0, cudnn_enabled=1](%23, %5, %6), scope: AlexNet/Sequential[features]/Conv2d[6]
    %26 : Double(1, 384, 13, 13) = aten::threshold[threshold={0}, value={0}](%25), scope: AlexNet/Sequential[features]/ReLU[7]
    %27 : Double(1, 256, 13, 13) = aten::_convolution[stride=[1, 1], padding=[1, 1], dilation=[1, 1], transposed=0, output_padding=[0, 0], groups=1, benchmark=0, deterministic=0, cudnn_enabled=1](%26, %7, %8), scope: AlexNet/Sequential[features]/Conv2d[8]
    %28 : Double(1, 256, 13, 13) = aten::threshold[threshold={0}, value={0}](%27), scope: AlexNet/Sequential[features]/ReLU[9]
    %29 : Double(1, 256, 13, 13) = aten::_convolution[stride=[1, 1], padding=[1, 1], dilation=[1, 1], transposed=0, output_padding=[0, 0], groups=1, benchmark=0, deterministic=0, cudnn_enabled=1](%28, %9, %10), scope: AlexNet/Sequential[features]/Conv2d[10]
    %30 : Double(1, 256, 13, 13) = aten::threshold[threshold={0}, value={0}](%29), scope: AlexNet/Sequential[features]/ReLU[11]
    %31 : Double(1, 256, 6, 6), %32 : Long(1, 256, 6, 6) = aten::max_pool2d[kernel_size=[3, 3], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=0](%30), scope: AlexNet/Sequential[features]/MaxPool2d[12]
    %33 : Long() = aten::size[dim=0](%31), scope: AlexNet
    %34 : Long() = prim::Constant[value={9216}](), scope: AlexNet
    %35 : Dynamic = aten::stack[dim=0](%33, %34), scope: AlexNet
    %36 : Double(1, 9216) = aten::view(%31, %35), scope: AlexNet
-   %37 : Double(1, 9216), %38 : Handle = ^Dropout(0.5, True, False)(%36), scope: AlexNet/Sequential[classifier]/Dropout[0]
?                        --------------
+   %37 : Double(1, 9216) = ^Dropout(0.5, True, False)(%36), scope: AlexNet/Sequential[classifier]/Dropout[0]
-   %39 : Double(9216!, 4096!) = aten::t(%11), scope: AlexNet/Sequential[classifier]/Linear[1]
?     ^
+   %38 : Double(9216!, 4096!) = aten::t(%11), scope: AlexNet/Sequential[classifier]/Linear[1]
?     ^
-   %40 : Double(1, 4096) = aten::expand[size=[1, 4096], implicit=1](%12), scope: AlexNet/Sequential[classifier]/Linear[1]
?    ^^
+   %39 : Double(1, 4096) = aten::expand[size=[1, 4096], implicit=1](%12), scope: AlexNet/Sequential[classifier]/Linear[1]
?    ^^
-   %41 : Double(1, 4096) = aten::addmm[beta={1}, alpha={1}](%40, %37, %39), scope: AlexNet/Sequential[classifier]/Linear[1]
?     ^                                                       ^^         ^
+   %40 : Double(1, 4096) = aten::addmm[beta={1}, alpha={1}](%39, %37, %38), scope: AlexNet/Sequential[classifier]/Linear[1]
?     ^                                                       ^^         ^
-   %42 : Double(1, 4096) = aten::threshold[threshold={0}, value={0}](%41), scope: AlexNet/Sequential[classifier]/ReLU[2]
?     ^                                                                 ^
+   %41 : Double(1, 4096) = aten::threshold[threshold={0}, value={0}](%40), scope: AlexNet/Sequential[classifier]/ReLU[2]
?     ^                                                                 ^
-   %43 : Double(1, 4096), %44 : Handle = ^Dropout(0.5, True, False)(%42), scope: AlexNet/Sequential[classifier]/Dropout[3]
?     ^                  --------------                                ^
+   %42 : Double(1, 4096) = ^Dropout(0.5, True, False)(%41), scope: AlexNet/Sequential[classifier]/Dropout[3]
?     ^                                                  ^
-   %45 : Double(4096!, 4096!) = aten::t(%13), scope: AlexNet/Sequential[classifier]/Linear[4]
?     ^
+   %43 : Double(4096!, 4096!) = aten::t(%13), scope: AlexNet/Sequential[classifier]/Linear[4]
?     ^
-   %46 : Double(1, 4096) = aten::expand[size=[1, 4096], implicit=1](%14), scope: AlexNet/Sequential[classifier]/Linear[4]
?     ^
+   %44 : Double(1, 4096) = aten::expand[size=[1, 4096], implicit=1](%14), scope: AlexNet/Sequential[classifier]/Linear[4]
?     ^
-   %47 : Double(1, 4096) = aten::addmm[beta={1}, alpha={1}](%46, %43, %45), scope: AlexNet/Sequential[classifier]/Linear[4]
?     ^                                                        ^     -----
+   %45 : Double(1, 4096) = aten::addmm[beta={1}, alpha={1}](%44, %42, %43), scope: AlexNet/Sequential[classifier]/Linear[4]
?     ^                                                        ^ +++++
-   %48 : Double(1, 4096) = aten::threshold[threshold={0}, value={0}](%47), scope: AlexNet/Sequential[classifier]/ReLU[5]
?     ^                                                                 ^
+   %46 : Double(1, 4096) = aten::threshold[threshold={0}, value={0}](%45), scope: AlexNet/Sequential[classifier]/ReLU[5]
?     ^                                                                 ^
-   %49 : Double(4096!, 1000!) = aten::t(%15), scope: AlexNet/Sequential[classifier]/Linear[6]
?     ^
+   %47 : Double(4096!, 1000!) = aten::t(%15), scope: AlexNet/Sequential[classifier]/Linear[6]
?     ^
-   %50 : Double(1, 1000) = aten::expand[size=[1, 1000], implicit=1](%16), scope: AlexNet/Sequential[classifier]/Linear[6]
?    ^^
+   %48 : Double(1, 1000) = aten::expand[size=[1, 1000], implicit=1](%16), scope: AlexNet/Sequential[classifier]/Linear[6]
?    ^^
-   %51 : Double(1, 1000) = aten::addmm[beta={1}, alpha={1}](%50, %48, %49), scope: AlexNet/Sequential[classifier]/Linear[6]
?    ^^                                                       -----      ^
+   %49 : Double(1, 1000) = aten::addmm[beta={1}, alpha={1}](%48, %46, %47), scope: AlexNet/Sequential[classifier]/Linear[6]
?    ^^                                                             ^^^^^^
-   return (%51);
?            ^^
+   return (%49);
?            ^^
  }


----------------------------------------------------------------------
Ran 143 tests in 22.279s

FAILED (failures=1, skipped=4, expected failures=4)
Traceback (most recent call last):
  File "run_test.py", line 342, in <module>
    main()
  File "run_test.py", line 334, in main
    raise RuntimeError(message)
RuntimeError: test_jit failed!
```

**Comment by mruberry** [comment]
I think this test is skipped currently by the CI because Torchvision is installed only after it would be run (and it requires Torchvision to run). That's why it hasn't appeared.

**Comment by ezyang** [comment]
There are some other tests in the test suite which depend on torchvision being installed. It seems reasonable enough to make sure it is preinstalled before any tests run. Should be an easy patch (if everything is actually working, which it might not be!)

**Comment by apaszke** [comment]
This is fixed in master.
