### ISSUE TITLE
Error while loading model weights to mps device

### ISSUE THREAD

**Issue by RRobert92** [pytorch/pytorch#78551]
### 🐛 Describe the bug

Model is trained on Nvidia GPU (A100). This model can be loaded back on GPU or CPU device. However while loading the same weights on MPS device I receives an error RuntimeError: don't know how to restore data location of torch.storage._UntypedStorage (tagged with "mps)".
I tried to load it first to cpu then move to mps, but it produce exactly the same result.

### Versions

[conda] numpy                     1.22.3           py39h25ab29e_0  
[conda] numpy-base                1.22.3           py39h974a1f5_0  
[conda] pytorch                   1.13.0.dev20220530         py3.9_0    pytorch-nightly
[conda] tardis-pytorch            0.1.0a6                   dev_0    <develop>

**Comment by GerardWalsh** [comment]
Same here:
pytorch                   1.13.0.dev20220603         py3.8_0    pytorch-nightly
torchvision               0.14.0.dev20220603          pypi_0    pypi

**Comment by DenisVieriu97** [comment]
Thanks for reporting this issue!
@GerardWalsh , @RRobert92 do you have a small sample that we could use to reproduce the issue?

**Comment by GerardWalsh** [comment]
@DenisVieriu97 
```
import torch
print(torch.__version__)
yolov5s_cpu = torch.load('yolov5s.pt', 'cpu')
yolov5s_mps = torch.load('yolov5s.pt', 'mps')
````

```
python testyolov5.py 
1.13.0.dev20220603
Traceback (most recent call last):
  File "testyolov5.py", line 4, in <module>
    yolov5s_mps = torch.load('yolov5s.pt', 'mps')
  File "/Users/gerardwalsh/yolov5/venv_v3/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/gerardwalsh/yolov5/venv_v3/lib/python3.8/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/Users/gerardwalsh/yolov5/venv_v3/lib/python3.8/site-packages/torch/serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/Users/gerardwalsh/yolov5/venv_v3/lib/python3.8/site-packages/torch/serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/Users/gerardwalsh/yolov5/venv_v3/lib/python3.8/site-packages/torch/serialization.py", line 970, in restore_location
    return default_restore_location(storage, map_location)
  File "/Users/gerardwalsh/yolov5/venv_v3/lib/python3.8/site-packages/torch/serialization.py", line 178, in default_restore_location
    raise RuntimeError("don't know how to restore data location of "
RuntimeError: don't know how to restore data location of torch.storage._UntypedStorage (tagged with mps)
```

**Comment by GerardWalsh** [comment]
Weights downloaded from 
```
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
```

**Comment by kulinseth** [comment]
Can you please check with latest Torch nightly. This issue should be resolved with serialization fix @albanD added for MPS device.

**Comment by RRobert92** [comment]
Works for me. Huge thanks!
