### ISSUE TITLE
nightly docs build failing with katex not found

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#78687]
See: https://github.com/pytorch/pytorch/runs/6700343902?check_suite_focus=true

Might be related to: https://github.com/pytorch/pytorch/commit/2ac09cc6cedb9e5feb8b8a59305bff7c307d14ea

**Comment by janeyx99** [comment]
A relevant log:
```
Error: No such image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.7-gcc5.4:ac4fd6eb2e7e13040a6616856faf82dd5a416cae
```

**Comment by janeyx99** [comment]
The real culprit looks to be https://github.com/pytorch/pytorch/pull/78405

**Comment by liang3zy22** [comment]
I have met this issue in my local environment(ubuntu 20.04). The error log is as below:
```
Traceback (most recent call last):
  File "/home/yanliang/anaconda3/envs/pytorch-dev/lib/python3.11/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/yanliang/anaconda3/envs/pytorch-dev/lib/python3.11/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/home/yanliang/anaconda3/envs/pytorch-dev/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 288, in build_update
    self.build(to_build,
  File "/home/yanliang/anaconda3/envs/pytorch-dev/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 352, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/yanliang/anaconda3/envs/pytorch-dev/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 541, in write
    self._write_parallel(sorted(docnames),
  File "/home/yanliang/anaconda3/envs/pytorch-dev/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 588, in _write_parallel
    tasks.add_task(write_process, arg, on_chunk_done)
  File "/home/yanliang/anaconda3/envs/pytorch-dev/lib/python3.11/site-packages/sphinx/util/parallel.py", line 88, in add_task
    self._join_one()
  File "/home/yanliang/anaconda3/envs/pytorch-dev/lib/python3.11/site-packages/sphinx/util/parallel.py", line 114, in _join_one
    raise SphinxParallelError(*result)
sphinx.errors.SphinxParallelError: FileNotFoundError: [Errno 2] No such file or directory: 'katex'

Sphinx parallel build error:
FileNotFoundError: [Errno 2] No such file or directory: 'katex'
make: *** [Makefile:49: html] Error 2

```

I fixed this issue by installed `sphinxcontrib.katex==0.9.0`.

**Comment by yushangdi** [comment]
> I fixed this issue by installed `sphinxcontrib.katex==0.9.0`.

had the same issue and this fixed it for me! Maybe it's good to update requirements.txt? I see that requirements.txt has `sphinxcontrib.katex==0.8.6`. @janeyx99
