### ISSUE TITLE
Errors import torch installed form source on macOS

### ISSUE THREAD

**Issue by yytdfc** [pytorch/pytorch#788]
I used pip to install the dependencies, and build from source. When I import torch I got this error:
``` python
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pytorch/torch/__init__.py", line 46, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'torch._C'
```

My OS is macOS 10.12.3, python is python3.6

**Comment by apaszke** [comment]
Run python from a different directory than the repository root.
