### ISSUE TITLE
If large enough tensor is being cloned, parallel dataloading hands on M1 Mac

### ISSUE THREAD

**Issue by OlegTheCat** [pytorch/pytorch#78924]
## Issue description
This is really strange issue. I drilled it down to the smallest reproducible example possible.

The dataloader hangs if:
- num_workers > 0
- large enough batches are being produced from a dataloader (see code)
- the large enough (smaller tensors like (100, 100) work ok) is being cloned some time during execution of a program; interestingly it may be any tensor, even the one not related to dataloading (see code)
- the program is being runned on M1 Mac (it works ok on x86 machines)

## Code example

```
import torch
import itertools

def _samples_to_XY(samples):
    X = [x for x, _ in samples]
    X = torch.tensor(X)
    Y = torch.tensor([y for _, y in samples])
    return X, Y

def _gen(tensor_size):
    while True:
        yield (list(range(tensor_size)), 1)

def _gen_batch(tensor_size, batch_size):
    gen = _gen(tensor_size)
    while True:
        xys = list(itertools.islice(gen, batch_size))
        if not xys:
            break
        yield _samples_to_XY(xys)

class TheDataset(torch.utils.data.IterableDataset):
    def __init__(self, tensor_size, batch_size):
        self.batch_size = batch_size
        self.tensor_size = tensor_size
    def __iter__(self):
        return _gen_batch(self.tensor_size, self.batch_size)
    def into_dataloader(self, num_workers):
        mproc_config = {'multiprocessing_context': 'fork'}
        mproc_config = mproc_config if num_workers > 0 else {}
        return torch.utils.data.DataLoader(self,
                                           num_workers=num_workers,
                                           **mproc_config)

if __name__ == '__main__':

    some_tensor = torch.rand(10000, 50)
    
    # if this statement is commented, none of the code below hangs
    some_tensor = some_tensor.clone()

    # works ok
    if next(iter(TheDataset(tensor_size=64, batch_size=512).into_dataloader(num_workers=1))):
        print('ok')

    # works ok
    if next(iter(TheDataset(tensor_size=128, batch_size=256).into_dataloader(num_workers=1))):
        print('ok')

    # hangs
    if next(iter(TheDataset(tensor_size=128, batch_size=512).into_dataloader(num_workers=1))):
        print('ok')
```

Console output:
```
[W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
ok
[W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
ok
[W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
```

Console output with clone statement commented out:
```
ok
ok
ok
```

## System Info
```
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Jun  1 2022, 06:34:44)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi
```

**Comment by dwt** [comment]
I'm also hitting this while trying to work through [the fast ai book](https://github.com/fastai/fastbook/). Not quite sure how to proceed - is there a workaround available until this is fixed?

**Comment by dwt** [comment]
Other places this bug has cropped up: https://github.com/minimaxir/aitextgen/issues/94, they advocate for setting these environment variables:  `environ["TOKENIZERS_PARALLELISM"] = "false"` and `environ["OMP_NUM_THREADS"] = "1"` [also advocated here](https://stackoverflow.com/questions/64772335/pytorch-w-parallelnative-cpp206) - both seem to do nothing for me?

**Comment by ejguan** [comment]
FWIW, if you change the starting method to `spawn`, the Error should go away as all the environment variables won't be inherited from the parent process.

**Comment by OlegTheCat** [comment]
@ejguan Thanks! It indeed fixes the issue! However when this code is used in Jupyter Notebook, `spawn` doesn't work because of this error:

```
AttributeError: Can't get attribute 'TheDataset' on <module '__main__' (built-in)>
```

(which may be related to [this issue](https://github.com/pytorch/pytorch/issues/60319)).

I'm using Jupyter Notebooks most of the time, so setting `spawn` is not an option for me, unfortunately.

**Comment by VitalyFedyunin** [comment]
You can try to `torch.set_num_threads(1)` at the beginning of the code. And update it to the desired number inside the training loop.

**Comment by dwt** [comment]
@VitalyFedyunin that seems to be a viable workaorund. Thanks!

**Comment by maxjay** [comment]
Update, using `torch.set_num_threads(1)` causes this error:
```python
  File "/Users/mjayatil/miniconda3/envs/donut/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/Users/mjayatil/miniconda3/envs/donut/lib/python3.10/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/Users/mjayatil/miniconda3/envs/donut/lib/python3.10/multiprocessing/connection.py", line 262, in poll
    return self._poll(timeout)
  File "/Users/mjayatil/miniconda3/envs/donut/lib/python3.10/multiprocessing/connection.py", line 429, in _poll
    r = wait([self], timeout)
  File "/Users/mjayatil/miniconda3/envs/donut/lib/python3.10/multiprocessing/connection.py", line 936, in wait
    ready = selector.select(timeout)
  File "/Users/mjayatil/miniconda3/envs/donut/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/Users/mjayatil/miniconda3/envs/donut/lib/python3.10/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 6156) is killed by signal: Trace/BPT trap: 5. 
```

**Comment by haowu2651** [comment]
any updates on this issue? it seems to be multiprocessing problem on mac m1?

**Comment by mariusdkm** [comment]
I'm also still experiencing this issue on my M1 Macbook in a Jupyter Notebook
Here is some example code:

```python
class DummyDataset(Dataset):
    def __init__(self, length=10):
        self.length = length

    def __len__(self):
        return self.length

    def __getitem__(self, idx):
        return np.arange(idx, idx + 10)
    
dataset = DummyDataset()
dataloader = DataLoader(dataset, batch_size=1, num_workers=1, shuffle=True)
first_batch = next(iter(dataloader))
```
This then throws the error:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'DummyDataset' on <module '__main__' (built-in)>
```

I'm using `torch==2.1.2` and Python Version `3.11.7 (main, Dec 19 2023, 23:50:53) [Clang 15.0.0 (clang-1500.1.0.2.5)]`

Currently, a workaround is to set `num_workers=0`
I would really appreciate this getting fixed :))
