### ISSUE TITLE
python test/run_test.py

### ISSUE THREAD

**Issue by dbl001** [pytorch/pytorch#79022]
### 🐛 Describe the bug

```
Executing ['/Users/davidlaxer/anaconda3/envs/AI-Feynman/bin/python', 'distributed/fsdp/test_flatten_params_wrapper.py'] ... [2022-06-07 10:09:54.050558]
...F...FFssssssssssssssssss
======================================================================
FAIL: test_output (__main__.TestFlattenParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/davidlaxer/pytorch/test/distributed/fsdp/test_flatten_params_wrapper.py", line 157, in test_output
    self._test_output(module)
  File "/Users/davidlaxer/pytorch/test/distributed/fsdp/test_flatten_params_wrapper.py", line 96, in _test_output
    self.assertEqual(ref_output, flat_output)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2250, in assertEqual
    assert_equal(
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1095, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 2559 / 2560 (100.0%)
Greatest absolute difference: 3.264644742012024 at index (3, 5, 13) (up to 1e-05 allowed)
Greatest relative difference: 50197.72481620972 at index (5, 1, 0) (up to 1.3e-06 allowed)

======================================================================
FAIL: test_shared_params_output (__main__.TestFlattenParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/davidlaxer/pytorch/test/distributed/fsdp/test_flatten_params_wrapper.py", line 161, in test_shared_params_output
    self._test_output(module)
  File "/Users/davidlaxer/pytorch/test/distributed/fsdp/test_flatten_params_wrapper.py", line 96, in _test_output
    self.assertEqual(ref_output, flat_output)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2250, in assertEqual
    assert_equal(
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1095, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 2560 / 2560 (100.0%)
Greatest absolute difference: 2.6104618310928345 at index (0, 2, 22) (up to 1e-05 allowed)
Greatest relative difference: 2277.2177426037156 at index (4, 1, 15) (up to 1.3e-06 allowed)

======================================================================
FAIL: test_shared_params_pnorm_after_step (__main__.TestFlattenParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/davidlaxer/pytorch/test/distributed/fsdp/test_flatten_params_wrapper.py", line 174, in test_shared_params_pnorm_after_step
    self.assertEqual(ref_pnorm_after_step, flat_pnorm_after_step)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2250, in assertEqual
    assert_equal(
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1095, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Scalars are not close!

Absolute difference: 229.60687255859375 (up to 1e-05 allowed)
Relative difference: 0.8628592294616498 (up to 1.3e-06 allowed)

----------------------------------------------------------------------
Ran 27 tests in 0.266s

```

### Versions

```
% python collect_env.py  
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.22.4
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.13.0a0+gitb637810
[pip3] torchvision==0.2.2.post3
[conda] Could not collect
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by fduwjj** [comment]
Hi, thanks for reporting this. I tried to run this on AWS cluster and it seems to be ok. So my guess is that this is a Mac specific environment. I don't have Mac PyTorch Env, I am wondering if any of you guys have that? @rohan-varma @awgu @zhaojuanmao Thanks!

**Comment by fduwjj** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/6937752/173718149-d85f91f2-38cf-4588-a242-8549b4eb71f7.png">


I run it on my local mac, the test actually passed. I have run it 20 times. all passed.

python3 collect_env.py 
Collecting environment information...
PyTorch version: 1.13.0.dev20220614
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.13.0.dev20220614
[pip3] torchaudio==0.13.0.dev20220614
[pip3] torchvision==0.14.0.dev20220614
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-include               2022.0.0           hecd8cb5_105  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.22.3           py39h2e5f0a9_0  
[conda] numpy-base                1.22.3           py39h3b1a694_0  
[conda] pytorch                   1.13.0.dev20220614         py3.9_0    pytorch-nightly
[conda] torchaudio                0.13.0.dev20220614        py39_cpu    pytorch-nightly
[conda] torchvision               0.14.0.dev20220614        py39_cpu    pytorch-nightly

**Comment by dbl001** [comment]
Curious.
I just ran 'python test/run_test.py' again ...
```
OK (skipped=2)
Running distributed/fsdp/test_flatten_params_wrapper ... [2022-06-14 19:17:19.640370]
Executing ['/Users/davidlaxer/anaconda3/envs/AI-Feynman/bin/python', 'distributed/fsdp/test_flatten_params_wrapper.py'] ... [2022-06-14 19:17:19.640446]
...F...FFssssssssssssssssss
======================================================================
FAIL: test_output (__main__.TestFlattenParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/davidlaxer/pytorch/test/distributed/fsdp/test_flatten_params_wrapper.py", line 157, in test_output
    self._test_output(module)
  File "/Users/davidlaxer/pytorch/test/distributed/fsdp/test_flatten_params_wrapper.py", line 96, in _test_output
    self.assertEqual(ref_output, flat_output)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2250, in assertEqual
    assert_equal(
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1095, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 2560 / 2560 (100.0%)
Greatest absolute difference: 2.90878164768219 at index (6, 0, 29) (up to 1e-05 allowed)
Greatest relative difference: 679.8102758229903 at index (9, 7, 9) (up to 1.3e-06 allowed)

======================================================================
FAIL: test_shared_params_output (__main__.TestFlattenParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/davidlaxer/pytorch/test/distributed/fsdp/test_flatten_params_wrapper.py", line 161, in test_shared_params_output
    self._test_output(module)
  File "/Users/davidlaxer/pytorch/test/distributed/fsdp/test_flatten_params_wrapper.py", line 96, in _test_output
    self.assertEqual(ref_output, flat_output)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2250, in assertEqual
    assert_equal(
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1095, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 2560 / 2560 (100.0%)
Greatest absolute difference: 3.341054767370224 at index (7, 2, 16) (up to 1e-05 allowed)
Greatest relative difference: 3547.258095726134 at index (5, 4, 18) (up to 1.3e-06 allowed)

======================================================================
FAIL: test_shared_params_pnorm_after_step (__main__.TestFlattenParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/davidlaxer/pytorch/test/distributed/fsdp/test_flatten_params_wrapper.py", line 174, in test_shared_params_pnorm_after_step
    self.assertEqual(ref_pnorm_after_step, flat_pnorm_after_step)
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2250, in assertEqual
    assert_equal(
  File "/Users/davidlaxer/anaconda3/envs/AI-Feynman/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1095, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Scalars are not close!

Absolute difference: 88.27381134033203 (up to 1e-05 allowed)
Relative difference: 0.7175007621359452 (up to 1.3e-06 allowed)

----------------------------------------------------------------------
Ran 27 tests in 0.260s

FAILED (failures=3, skipped=18)
Traceback (most recent call last):
  File "/Users/davidlaxer/pytorch/test/run_test.py", line 1079, in <module>
    main()
  File "/Users/davidlaxer/pytorch/test/run_test.py", line 1057, in main
    raise RuntimeError(err_message)
RuntimeError: distributed/fsdp/test_flatten_params_wrapper failed!
```

**Comment by awgu** [comment]
Closing this for now since we cannot repro :/
