### ISSUE TITLE
[NVFuser] hitting fallbacks on demucs (from torchbench + lazy tensor)

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#79325]
### 🐛 Describe the bug

NVFuser is hitting a fallback when running demucs on torchbench + lazy tensor.

Repro:
```python
import torch
from torch.utils.jit.log_extract import run_nvfuser, load_graph_and_inputs

ir = """graph(%0 : Float(8, 512, 1452, strides=[764416, 1493, 1], requires_grad=0, device=cuda:0),
      %1 : Float(8, 512, 1452, strides=[743424, 1452, 1], requires_grad=0, device=cuda:0),
      %p32 : int):
  %3 : Float(8, 512, 1452, strides=[743424, 1452, 1], requires_grad=0, device=cuda:0) = aten::relu(%1)
  %4 : Float(8, 512, 1452, strides=[743424, 1452, 1], requires_grad=0, device=cuda:0) = aten::add(%3, %0, %p32)
  return (%4)
"""

_, inputs = load_graph_and_inputs(ir)
run_nvfuser(ir, inputs)
```
Error:
```
RuntimeError: stride == cur_contig_stride || (still_rightmost && stride == 1) || (!still_rightmost && stride % word_size == 0) INTERNAL ASSERT FAILED at "/scratch/dberard/bench-june/pytorch/torch/csrc/jit/codegen/cuda/executor_utils.cpp":599, please report a bug to PyTorch. Vectorization of T0_g[ iS70{( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[0] * ( T0.size[1] * T0.size[2] ) ), 4) ), 1) ), 128) )}, iS69{1}, iS67{4}, iS71{128} ] with word size 4 not possible due to invalid stride. Domain: iS69{1}, stride: 1493
```

Stacktrace:
```
#0  0x00007fffc7966d1d in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007fffa98d671a in c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /scratch/dberard/bench-june/pytorch/torch/lib/libc10.so
#2  0x00007fffa98d848e in c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /scratch/dberard/bench-june/pytorch/torch/lib/libc10.so
#3  0x00007fffb49d8f68 in torch::jit::fuser::cuda::executor_utils::(anonymous namespace)::validateAlignedVectorizedFusionInputOutput(c10::IValue const&, int, torch::jit::fuser::cuda::TensorView*) () from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cuda_cu.so
#4  0x00007fffb49ddf49 in torch::jit::fuser::cuda::executor_utils::validateVectorizedTensors(torch::jit::fuser::cuda::kir::Kernel*, c10::ArrayRef<c10::IValue> const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, torch::jit::fuser::cuda::executor_utils::caching::ExecutorCompileTimeInfoCache*, torch::jit::fuser::cuda::kir::ExpressionEvaluator&) () from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cuda_cu.so
#5  0x00007fffb49bb5e3 in torch::jit::fuser::cuda::FusionExecutor::runFusion(c10::ArrayRef<c10::IValue> const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, torch::jit::fuser::cuda::LaunchParams const&, c10::optional<unsigned long> const&) ()
   from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cuda_cu.so
#6  0x00007fffb4a78925 in torch::jit::fuser::cuda::FusionKernelRuntime::runKernelWithInput(c10::ArrayRef<c10::IValue> const&, unsigned long, torch::jit::fuser::cuda::SegmentedGroup*) () from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cuda_cu.so
#7  0x00007fffb4a79a56 in torch::jit::fuser::cuda::FusionKernelRuntime::runWithInput(c10::ArrayRef<c10::IValue> const&, unsigned long) ()
   from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cuda_cu.so
#8  0x00007fffb4a7c620 in torch::jit::fuser::cuda::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&) ()
   from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cuda_cu.so
#9  0x00007fffb4a7cc9a in torch::jit::fuser::cuda::GraphCache::runGraphWithInputs(c10::ArrayRef<c10::IValue> const&) ()
   from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cuda_cu.so
#10 0x00007fffb4b1182f in torch::jit::fuser::cuda::runCudaFusionGroup(torch::jit::Node const*, std::vector<c10::IValue, std::allocator<c10::IValue> >&)::{lambda()#3}::operator()() const () from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cuda_cu.so
#11 0x00007fffb4b1215e in torch::jit::fuser::cuda::runCudaFusionGroup(torch::jit::Node const*, std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cuda_cu.so
#12 0x00007fffbb1432d3 in torch::jit::InterpreterStateImpl::runImpl(std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cpu.so
#13 0x00007fffbb1315e2 in torch::jit::InterpreterState::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cpu.so
#14 0x00007fffbb124576 in torch::jit::GraphExecutorImplBase::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_cpu.so
#15 0x00007fffc549c263 in torch::jit::runAndInsertCall(torch::jit::Function&, torch::jit::tuple_slice const&, pybind11::kwargs const&, c10::optional<c10::IValue>, std::function<torch::jit::Value* (torch::jit::Graph&, torch::jit::MatchedSchema const&)> const&) ()
   from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_python.so
#16 0x00007fffc552fe69 in void pybind11::cpp_function::initialize<torch::jit::initJitScriptBindings(_object*)::{lambda(pybind11::args, pybind11::kwargs)#53}, pybind11::object, pybind11::args, pybind11::kwargs, pybind11::name, pybind11::is_method, pybind11::sibling>(torch::jit::initJitScriptBindings(_object*)::{lambda(pybind11::args, pybind11::kwargs)#53}&&, pybind11::object (*)(pybind11::args, pybind11::kwargs), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) () from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_python.so
#17 0x00007fffc500adac in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) ()
   from /scratch/dberard/bench-june/pytorch/torch/lib/libtorch_python.so
```

### Versions

A100, torchbench = main, pytorch = viable/strict.

cc @jjsjann123

**Comment by csarofeen** [comment]
I believe this is the same as https://github.com/csarofeen/pytorch/issues/1843
