### ISSUE TITLE
torch failure to open libcuda.so.1 on macOS

### ISSUE THREAD

**Issue by xlla** [pytorch/pytorch#79382]
### 🐛 Describe the bug

the torch had a hardcode of cuda lib soname, it does not match the macOS version, it is libcuda.dylib

I just try to run an example on [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) ,  it raise exception

<pre>
Traceback (most recent call last):
  File "/Users/xlla/test/test-stable-baseline3.py", line 11, in <module>
    model.learn(total_timesteps=10_000)
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 304, in learn
    return super(PPO, self).learn(
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 270, in learn
    self.train()
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 264, in train
    loss.backward()
  File "/usr/local/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Error in dlopen: dlopen(libcuda.so.1, 6): image not found
</pre>

I search this string and found it at 
`aten/src/ATen/cuda/detail/LazyNVRTC.cpp` and `third_party/tensorpipe/tensorpipe/common/cuda_lib.h`

### Versions

PyTorch version: 1.11.0a0+git967238d
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: macOS 10.13.6 (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.13 (main, Jun  3 2022, 08:10:53)  [Clang 10.0.1 (clang-1001.0.46.4)] (64-bit runtime)
Python platform: macOS-10.13.6-x86_64-i386-64bit
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GeForce GTX 1060 6GB
Nvidia driver version: 1.1.0
cuDNN version: Probably one of the following:
/usr/local/cuda/lib/libcudnn.7.dylib
/usr/local/cuda/lib/libcudnn_static.a
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] mypy-protobuf==3.2.0
[pip3] numpy==1.21.5
[pip3] pytorch-lightning==1.6.4
[pip3] torch==1.11.0a0+git967238d
[pip3] torchmetrics==0.9.1
[pip3] torchtext==0.14.0a0+e2fa8d8
[pip3] torchvision==0.14.0a0+5f6e22d
[conda] Could not collect

**Comment by malfet** [comment]
Closing as won't-fix: CUDA is not supported on macOS (there are no macOS CUDA builds), so `libcuda.so.1` is expected to be absent on a Mac.
