### ISSUE TITLE
Conda enviroment

### ISSUE THREAD

**Issue by yvr1037** [pytorch/pytorch#79407]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "/data1/yvr/.conda/envs/opt/bin/opt-baselines", line 33, in <module>
    sys.exit(load_entry_point('metaseq==0.0.1', 'console_scripts', 'opt-baselines')())
  File "/data1/yvr/.conda/envs/opt/lib/python3.7/site-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/launcher/opt_baselines.py", line 314, in cli_main
    get_grid, postprocess_hyperparams, add_extra_options_func=add_extra_options_func
  File "/data1/yvr/.conda/envs/opt/lib/python3.7/site-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/launcher/sweep.py", line 378, in main
    backend_main(get_grid, postprocess_hyperparams, args)
  File "/data1/yvr/.conda/envs/opt/lib/python3.7/site-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/launcher/slurm.py", line 34, in main
    grid = get_grid(args)
  File "/data1/yvr/.conda/envs/opt/lib/python3.7/site-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/launcher/opt_baselines.py", line 78, in get_grid
    raise RuntimeError("Where are you running this?! Check DATA_LOCATIONS.")
RuntimeError: Where are you running this?! Check DATA_LOCATIONS.

### Versions

After I conda environment following the setup.md,I plan to follow the train.md,it comes to the bug?

**Comment by mikaylagawarecki** [comment]
Hi @yvr1037, would you be able to provide a self-contained script which we could use to reproduce the problem and run and paste the output of https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py please?
