### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered on RTX 3080 with enough memory

### ISSUE THREAD

**Issue by j-adamczyk** [pytorch/pytorch#79603]
### 🐛 Describe the bug

I am training a Graph Neural Network with PyTorch, PyTorch Geometric, PyTorch Lightning and Optuna on Lipophilicity dataset, provided through OGB library (PyTorch Geometric interface). I am getting the following error:
```
Traceback (most recent call last):
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\main_gnn.py", line 81, in <module>
    best_params, test_metrics = perform_experiment(
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\main_gnn.py", line 23, in perform_experiment
    train_results: optuna.Study = optimize_and_train(
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\gnn\training.py", line 247, in optimize_and_train
    study.optimize(objective, n_trials=n_hyperparam_trials)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\study.py", line 400, in optimize
    _optimize(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 264, in _run_trial
    raise func_err
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\optuna\study\_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\Jakub\Desktop\Enhanced_GNN_graph_classification\gnn\training.py", line 222, in objective
    trainer.fit(model, datamodule=data_module)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 738, in _call_and_handle_interrupt
    self._teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1300, in _teardown
    self.strategy.teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\single_device.py", line 93, in teardown
    super().teardown()
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 444, in teardown
    optimizers_to_device(self.optimizers, torch.device("cpu"))
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\optimizer.py", line 27, in optimizers_to_device
    optimizer_to_device(opt, device)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\optimizer.py", line 33, in optimizer_to_device
    optimizer.state[p] = apply_to_collection(v, torch.Tensor, move_data_to_device, device)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 107, in apply_to_collection
    v = apply_to_collection(
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 354, in move_data_to_device
    return apply_to_collection(batch, dtype=dtype, function=batch_to)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\Jakub\anaconda3\envs\Enhanced_GNN_graph_classification\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 347, in batch_to
    data_output = data.to(device, **kwargs)
RuntimeError: CUDA error: an illegal memory access was encountered
```

This is not a memory problem, as I am using only about 3-6 GB of VRAM, out of 12 GB on my RTX 3080. It is happening randomly: random epoch, random network (but quite fast - either first or second Optuna trial). Error is the same with `CUDA_LAUNCH_BLOCKING=1` set. Lowering batch size from 64 to 32 also did not help. This error happens both without and with CuDNN installed.

The model is:
```
import pytorch_geometric.nn as pyg_nn

model = pyg_nn.GIN(512, 512, num_layers=5, jk="LSTM")
```

The entire code is very long, but it is basically the OGB example, with modified dataset (`"ogbg-mollipo"`) and regression instead of classification: https://github.com/snap-stanford/ogb/blob/master/examples/graphproppred/mol/main_pyg.py. Many other models seem to work properly, e.g. `GCN`, `GIN` without LSTM.

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 511.79
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.6.4
[pip3] torch==1.11.0
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.0.4
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torch-spline-conv==1.2.1
[pip3] torchmetrics==0.9.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h59b6b97_2  
[conda] mkl                       2021.4.0           haa95532_640  
[conda] mkl-service               2.4.0           py310h2bbff1b_0  
[conda] mkl_fft                   1.3.1           py310ha0764ea_0  
[conda] mkl_random                1.2.2           py310h4ed8f06_0  
[conda] numpy                     1.22.3          py310h6d2d95c_0  
[conda] numpy-base                1.22.3          py310h206c741_0  
[conda] pyg                       2.0.4           py310_torch_1.11.0_cu113    pyg
[conda] pytorch                   1.11.0          py3.10_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-cluster           1.6.0           py310_torch_1.11.0_cu113    pyg
[conda] pytorch-lightning         1.6.4                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-scatter           2.0.9           py310_torch_1.11.0_cu113    pyg
[conda] pytorch-sparse            0.6.13          py310_torch_1.11.0_cu113    pyg
[conda] pytorch-spline-conv       1.2.1           py310_torch_1.11.0_cu113    pyg
[conda] torchmetrics              0.9.1                    pypi_0    pypi

Process finished with exit code 0

cc @ngimel

**Comment by xiurobert** [comment]
Consider taking the issue to pytorch_geometric

**Comment by xiurobert** [comment]
GPU issue?

**Comment by ngimel** [comment]
Can you run with `CUDA_LAUNCH_BLOCKING=1 TORCH_SHOW_CPP_STACKTRACES=1`?

**Comment by j-adamczyk** [comment]
@xiurobert it is a brand-new GPU, with no configuration changes. On stress tests, benchmarks, games etc. it seems to work fine, so I do not suspect a hardware issue.

@ngimel I did, and interestingly after 19 Optuna trials (which means that 19 networks trained without any problems), during 20th trial, process suddenly ended in random training epoch with `Process finished with exit code -1073741819 (0xC0000005)`.

**Comment by xiurobert** [comment]
Ah okay, I'm not so sure then. Sometimes it is a hardware issue. Better to leave it to the folks who are familiar with cuda

**Comment by j-adamczyk** [comment]
The problem (both memory error and 0xC0000005) also happens with a simple, pure PyTorch model (`global_add_pool` just sums the channels):
```
import torch.nn as nn
from torch_geometric.nn import global_add_pool

class DeepMultisets(nn.Module):
    def __init__(
        self, in_channels: int, num_outputs: int, hidden_channels: int, **kwargs
    ):
        super().__init__()
        self.fc_node = nn.Sequential(
            nn.Linear(in_channels, hidden_channels),
            nn.BatchNorm1d(hidden_channels),
            nn.ReLU(),
        )

        self.fc_global_1 = nn.Sequential(
            nn.Linear(hidden_channels, hidden_channels),
            nn.BatchNorm1d(hidden_channels),
            nn.ReLU(),
        )

        self.fc_global_2 = nn.Linear(hidden_channels, num_outputs)

    def forward(self, data):
        x, batch = data.x, data.batch
        x = data.x.float()
        x = self.fc_node(x)
        x = global_add_pool(x, batch)
        x = self.fc_global_1(x)
        x = self.fc_global_2(x)
        return x
```

**Comment by xiurobert** [comment]
@j-adamczyk can you try simply allocating a tensor on the gpu

**Comment by ngimel** [comment]
`global_add_pool` uses `scatter` from `torch_scatter`, so that could still be a torch_scatter bug.
