### ISSUE TITLE
onnx export with dict parameter problems

### ISSUE THREAD

**Issue by pzfm3022** [pytorch/pytorch#79781]
### 🐛 Describe the bug

When trying to export a model to onnx that has a dict parameter, I'm getting a graph printed out (verbose=True) but am getting an onnx.CheckerError raised later, complaining about an unknown type related to that dict parameter.

Here's the example code:

```python
import torch
from typing import Dict

class MyDecisionGate(torch.nn.Module):
    def forward(self, x):
        # print("mdg forward x is", x)
        if x.sum() > 0:
            # print("+ve")
            return x
        else:
            # print("-ve")
            return -x

class MyCell(torch.nn.Module):
    def __init__(self, dg):
        super(MyCell, self).__init__()
        self.dg = dg
        self.linear = torch.nn.Linear(4, 4)

    def forward(self, d: Dict[ str, torch.Tensor ], xx: torch.Tensor, hh: torch.Tensor):
        # print("dd is", dd)
        # print("d is", d)
        # x = d["x"]
        x = xx
        # print("x is", x)
        h = d["h"]
        # h = hh
        # print("h is", h)
        new_h = torch.tanh(self.dg(self.linear(x)) + h)
        # print("new_h is", new_h)
        return new_h, new_h

x = torch.rand(3, 4)
xx = torch.rand(3, 4)
h = torch.rand(3, 4)
hh = torch.rand(3, 4)

scripted_gate = torch.jit.script(MyDecisionGate())
my_cell = MyCell(scripted_gate)
scripted_cell = torch.jit.script(my_cell)

print("gate code")
print(scripted_gate.code)
print("cell code")
print(scripted_cell.code)

print("export")
torch.onnx.export(scripted_cell, ({"x": x, "h": h}, xx, hh ), "test.onnx", verbose=True, input_names=[ "inputdict", "inpx", "inph" ], output_names=[ "output" ],
        opset_version=9)
```

The verbose print of the graph is:
```
graph(%inputdict : Dict(str, Tensor),
      %inpx : Float(3, 4, strides=[4, 1], requires_grad=0, device=cpu),
      %linear.weight : Float(3, 4, strides=[4, 1], requires_grad=0, device=cpu),
      %linear.bias : Float(4, 4, strides=[4, 1], requires_grad=0, device=cpu)):
  %5 : Tensor = onnx::Constant[value="h"]() # example-script-onnx-dict.py:27:14
  %h : Tensor = onnx::Gather[axis=0](%inputdict, %5) # example-script-onnx-dict.py:27:12
  %7 : Float(3, 4, strides=[3, 1], device=cpu) = onnx::Gemm[alpha=1., beta=1., transB=1](%inpx, %linear.weight, %linear.bias) # /home/gordon/AI/orange/env1.11/lib/python3.8/site-packages/torch/nn/modules/linear.py:103:15
  %8 : Float(device=cpu) = onnx::ReduceSum[keepdims=0](%7) # example-script-onnx-dict.py:8:11
  %9 : Float(requires_grad=0, device=cpu) = onnx::Constant[value={0}]()
  %10 : Bool(device=cpu) = onnx::Greater(%8, %9) # example-script-onnx-dict.py:8:11
  %11 : Bool(device=cpu) = onnx::Cast[to=9](%10) # example-script-onnx-dict.py:8:8
  %12 : Float(3, 4, strides=[3, 1], device=cpu) = onnx::If(%11) # example-script-onnx-dict.py:8:8
    block0():
      %13 : Float(3, 4, strides=[3, 1], device=cpu) = onnx::Identity(%7)
      -> (%13)
    block1():
      %14 : Float(3, 4, strides=[3, 1], device=cpu) = onnx::Neg(%7) # example-script-onnx-dict.py:13:19
      -> (%14)
  %15 : FloatTensor = onnx::Add(%12, %h) # example-script-onnx-dict.py:30:27
  %output : Float(*, *, strides=[4, 1], requires_grad=1, device=cpu) = onnx::Tanh(%15) # example-script-onnx-dict.py:30:16
  return (%output, %output)
```

with the later error traceback being:
```
Traceback (most recent call last):
  File "example-script-onnx-dict.py", line 49, in <module>
    torch.onnx.export(scripted_cell, ({"x": x, "h": h}, xx, hh ), "test.onnx", verbose=True, input_names=[ "inputdict", "inpx", "inph" ], output_names=[ "output" ],
  File "/home/gordon/AI/orange/env1.11/lib/python3.8/site-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/gordon/AI/orange/env1.11/lib/python3.8/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/gordon/AI/orange/env1.11/lib/python3.8/site-packages/torch/onnx/utils.py", line 790, in _export
    raise CheckerError(e)
torch.onnx.CheckerError: Unrecognized type value case (value_info name: inputdict): 0
```

### Versions

PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.23.2
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-117-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect

**Comment by shubhambhokare1** [comment]
@pzfm3022 
Currently the exporter is limited in its support for Dictionary types. Especially in scripting mode, Dictionary inputs/outputs are not supported. This PR (currently open) is trying to add Dictionary types to the ONNX spec https://github.com/onnx/onnx/pull/4640.

Feel free to keep track of this issue. Will close this issue for now. Feel free to reopen in the future.
