### ISSUE TITLE
Exporting the operator '::argsort' to ONNX opset version 16 is not supported

### ISSUE THREAD

**Issue by Egozjuer** [pytorch/pytorch#79859]
### 🐛 Describe the bug

Exporting the operator '::argsort' to ONNX opset version 16 is not supported

/home/zjlab/anaconda3/envs/py113/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:1160: UserWarning: ONNX export mode is set to False, but operator 'dropout' is set to train=False. Exporting with train=False.
  warnings.warn(
/home/zjlab/anaconda3/envs/py113/lib/python3.8/site-packages/torch/onnx/_patch_torch.py:67: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at  ../torch/csrc/jit/passes/onnx/shape_type_inference.cpp:1898.)
  torch._C._jit_pass_onnx_node_shape_type_inference(
/home/zjlab/anaconda3/envs/py113/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:1160: UserWarning: ONNX export mode is set to False, but operator 'batch_norm' is set to train=False. Exporting with train=False.
  warnings.warn(
Traceback (most recent call last):
  File "tools/export_bevdet.py", line 306, in <module>
    main()
  File "tools/export_bevdet.py", line 235, in main
    torch_out=torch.onnx.export(
  File "/home/zjlab/anaconda3/envs/py113/lib/python3.8/site-packages/torch/onnx/__init__.py", line 382, in export
    return utils.export(
  File "/home/zjlab/anaconda3/envs/py113/lib/python3.8/site-packages/torch/onnx/utils.py", line 177, in export
    _export(
  File "/home/zjlab/anaconda3/envs/py113/lib/python3.8/site-packages/torch/onnx/utils.py", line 1085, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/zjlab/anaconda3/envs/py113/lib/python3.8/site-packages/torch/onnx/utils.py", line 743, in _model_to_graph
    graph = _optimize_graph(
  File "/home/zjlab/anaconda3/envs/py113/lib/python3.8/site-packages/torch/onnx/utils.py", line 322, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/zjlab/anaconda3/envs/py113/lib/python3.8/site-packages/torch/onnx/__init__.py", line 441, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/zjlab/anaconda3/envs/py113/lib/python3.8/site-packages/torch/onnx/utils.py", line 1433, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator '::argsort' to ONNX opset version 16 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues

### Versions

pytorch 1.13

**Comment by shubhambhokare1** [comment]
PR #80234 should fix this issue
