### ISSUE TITLE
test_meta_vstack_cuda_int16 (__main__.TestMetaCUDA) Fails with DEBUG=1

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#79877]
### 🐛 Describe the bug

`python test/test_meta.py -k test_meta_vstack_cuda_int16`

> ERROR: test_meta_vstack_cuda_int16 (__main__.TestMetaCUDA) 
Traceback (most recent call last):
  File "/scratch/eellison/pytorch/test/test_meta.py", line 325, in run_meta_crossref
    meta_rs = func(*meta_args, **meta_kwargs)
  File "/private/home/eellison/anaconda3/lib/python3.8/site-packages/torch/overrides.py", line 1768, in wrapped
    return f(self, *args, **kwargs)
  File "/private/home/eellison/anaconda3/lib/python3.8/site-packages/torch/overrides.py", line 1873, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: self__storage_saved.value().is_alias_of(result.storage()) INTERNAL ASSERT FAILED at "/raid/eellison/pytorch/torch/csrc/autograd/generated/VariableType_4.cpp":13537, please report a bug to PyTorch. 

### Versions

master

**Comment by albanD** [comment]
Hey!
I'm afraid this is expected? These subclasses do not behave the way they should with respect to views. They should either have storage that do point to the same place or if you don't have storage, make sure they do report the same storage to reflect the fact that you are doing the view behavior as it should.

**Comment by ezyang** [comment]
test_meta.py uses modes but there are no subclasses. Most likely culprit is the vstack meta implementation is not coded correctly.
