### ISSUE TITLE
Devious Error Message when calculating gradient for Pow with wrong device

### ISSUE THREAD

**Issue by half-potato** [pytorch/pytorch#80061]
### 🐛 Describe the bug

Here is a short snippet to demonstrate how difficult this could be to traceback.
```
>>> a = torch.tensor(1.0, device='cuda')
>>> b = torch.tensor(2.0, device='cuda')
>>> c = torch.tensor(2.0, device='cpu')
>>> a.requires_grad = True
>>> (a**c).backward()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amai/.conda/envs/th/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/amai/.conda/envs/th/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected condition, x and y to be on the same device, but condition is on cpu and x and y are on cuda:0 and cuda:0 respectively
>>> (a**b).backward()
```
When running with anomaly mode, it just points to the PowBackward1 as the issue, but there is no explanation of why.

### Versions

1.11.0, 1.13.0. The other issue is present across different environments and comptuers.

**Comment by dagitses** [comment]
This is interesting. We will discuss in triage review to see if this is systematic problem.

**Comment by mruberry** [comment]
The error message here is imperfect, and we could probably improve it by more clearly labeling the where operation as the source for the message.

**Comment by Lezcano** [comment]
My first thought is that we should probably just remove the support for mixed cpu and cuda from this operation. Now, this operation is different, as it's the one behind the notation `a ** b`. These operations, like `add` and so, often support more things than other operations. As such, if this behaviour in the forward is expected, yup, we should just fix the backward to handle this case. That being said, I think we should just error out if the tensors are in different devices, unless we have a very good reason to do so.

**Comment by albanD** [comment]
I don't think we don't want to support this. In particular because this exercises similar code as `t * * 2` where 2 will be converted to a scalar CPU Tensor.
