### ISSUE TITLE
F.binary_cross_entropy_with_logits unexpected behaviour

### ISSUE THREAD

**Issue by sachinruk** [pytorch/pytorch#80208]
### 🐛 Describe the bug

I wanted to see if I put a non-binary input into F. if it will fail. Instead it gives me an answer without failing which is odd, but I can't figure out where the numbers are coming from. See example below (3rd row is confusing).

Two questions regarding below:
1. Why is this not chucking an error because of the 7 in `targets`
2. Why do I have to manually convert targets to `float` when `F.cross_entropy` expects a `LongTensor` and not `FloatTensor`.

```python
import torch
import torch.nn.functional as F

torch.manual_seed(42)

logits = torch.randn((5, 1))
targets = torch.LongTensor([0, 1, 7, 1, 0])[:, None]
log_prob = torch.cat([torch.log1p(-torch.sigmoid(logits)), F.logsigmoid(logits)], dim=-1)
print(F.binary_cross_entropy_with_logits(logits, targets_multilabel.float(), reduction="none"))
print(-log_prob)
"""
Output:
tensor([[ 0.8756],
        [ 0.6308],
        [-0.8240],
        [ 0.5846],
        [ 0.2817]])
tensor([[0.8756, 0.5389],
        [0.7596, 0.6308],
        [0.8172, 0.5828],
        [0.8149, 0.5846],
        [0.2817, 1.4045]])
"""
```

F.binary_cross_entropy_with_logits(logits, targets_multilabel.float(), reduction="none")

### Versions

Got this error, but my pytorch version is `1.11.0` and running on python 3.9
```
Collecting environment information...
Traceback (most recent call last):
  File "collect_env.py", line 492, in <module>
    main()
  File "collect_env.py", line 475, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 470, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 319, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "collect_env.py", line 301, in get_pip_packages
    out = run_with_pip(sys.executable + ' -mpip')
  File "collect_env.py", line 289, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by jbschlosser** [comment]
Hey @sachinruk, thanks for the report!

> Why is this not chucking an error because of the 7 in targets

On CUDA, we don't do this check for performance reasons. We should also do it on CPU, as there is already a check for the input values.

> Why do I have to manually convert targets to float when F.cross_entropy expects a LongTensor and not FloatTensor.

This was also brought up in #78878. As mentioned there, we'd accept a PR implementing integral target support within `binary_cross_entropy_with_logits` to avoid the need to convert.
