### ISSUE TITLE
DataLoader runs out of memory when `batch_size` >> `len(dataset)`  

### ISSUE THREAD

**Issue by alstonlo** [pytorch/pytorch#80493]
### 🐛 Describe the bug

A hack I was using to get datasets in a single batch was to create a `DataLoader` with a very large batch size. This worked fine in PyTorch 1.11.0, but a `MemoryError` is raised in PyTorch 1.12.0. The following is a minimal example:

```python
import torch
from torch.utils import data

X = torch.randn(50, 1)
dataset = data.TensorDataset(X)

# works fine
loader = data.DataLoader(dataset, batch_size=7)
for batch in loader:
    pass

# breaks
loader = data.DataLoader(dataset, batch_size=int(1e10))
for batch in loader:
    pass
```
```
Traceback (most recent call last):
  File "/home/**/main.py", line 14, in <module>
    for batch in loader:
  File "/home/**/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/**/torch/utils/data/dataloader.py", line 691, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/**/torch/utils/data/dataloader.py", line 642, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/**/torch/utils/data/sampler.py", line 245, in __iter__
    batch = [0] * self.batch_size
MemoryError
```

I believe this stems from a recent change to `BatchSampler` (PR #76951) ([line](https://github.com/pytorch/pytorch/pull/76951/files#diff-e902dcbe94290b83e86a079db6d98adf38ca3e27869733c75838c890042d8d88R245)). The `BatchSampler` now preallocates lists for each batch as follows:

```
batch = [0] * self.batch_size
```

For the last batch, if incomplete, this ends up using more memory than is necessary and causes a `MemoryError` because I have set the batch size so high. 

I have labelled this issue a bug for now, but I am unsure if it should be considered one. On one hand, the behaviour is not backward compatible and uses excess memory, but on the other, my usage of `DataLoader` is an edge case and admittedly bad practice.

Thanks!

### Versions

```
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.7.13 (default, Mar 29 2022, 02:18:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-117-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py37h7f8727e_0  
[conda] mkl_fft                   1.3.1            py37hd3c417c_0  
[conda] mkl_random                1.2.2            py37h51133e4_0  
[conda] numpy                     1.21.5           py37h6c91a56_3  
[conda] numpy-base                1.21.5           py37ha15fc14_3  
[conda] pytorch                   1.12.0              py3.7_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.12.0                 py37_cpu    pytorch
[conda] torchvision               0.13.0                 py37_cpu    pytorch
```

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by Elanmarkowitz** [comment]
Couldn't you just do
`loader = data.DataLoader(dataset, batch_size=len(dataset))`?

**Comment by alstonlo** [comment]
Yes, that is what I have already updated my code to do instead!

**Comment by alstonlo** [comment]
That makes sense, thanks!
