### ISSUE TITLE
`torch.ops.aten.find` inconsistent with `str.find`

### ISSUE THREAD

**Issue by qedawkins** [pytorch/pytorch#80580]
### 🐛 Describe the bug

For empty target strings `aten::find` will always return the value of the starting position in the string, even when the given range is invalid.

```
>>> import torch
>>> "example".find("", 100, 0)
-1
>>> torch.ops.aten.find("example", "", 100, 0)
100
```

As far as I can tell the cause of the discrepancy is found in `register_prim_ops.cpp` on [line 1522](https://github.com/pytorch/pytorch/blob/b4e491798c0679ab2e61f36a511484d7b8ecf8d3/torch/csrc/jit/runtime/register_prim_ops.cpp#L1522) where if the target string is empty, it will always search for the target even if the search range is invalid in some way.

Additionally, this can lead to crashes for certain inputs as shown below.
```
>>> import torch
>>> torch.ops.aten.find("example", "a", 100, 200)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quinn/torch-mlir/mlir_venv/lib/python3.10/site-packages/torch/_ops.py", line 148, in __call__
    return self._op(*args, **kwargs or {})
IndexError: basic_string::substr: __pos (which is 100) > this->size() (which is 7)

```

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220623+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 12.1.0
Clang version: 13.0.1
CMake version: version 3.22.5
Libc version: glibc-2.35

Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0] (64-bit runtime)
Python platform: Linux-5.18.5-arch1-1-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070 SUPER
Nvidia driver version: 515.48.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.13.0.dev20220623+cpu
[pip3] torch-mlir==20220620.509
[pip3] torchvision==0.14.0.dev20220623+cpu
[conda] Could not collect

**Comment by akdong91** [comment]
@qedawkins  I think that `FindImpl` does not handle an edge case as your example.  Because it does not check if `start` is valid or not, it just add the `start` position to `pos`.  A couple of things need to be done here if I am not missing something:

1. check if the given start position is in the range of the target string.
2. In the codebase, string.find(subst, 0) seems to return 0 which also doesn't align with your example.
