### ISSUE TITLE
RuntimeError: DataLoader worker (pid 22822) is killed by signal: Aborted. 

### ISSUE THREAD

**Issue by TalonX1** [pytorch/pytorch#80594]
### 🐛 Describe the bug

I set num_workers=4 in dataloader,the training process can run normally, and an error is reported in the verification phase。

### Versions

torch                     1.11.0
torchvision               0.12.0

**Comment by TalonX1** [comment]
```
Traceback (most recent call last):
  File "/home/qinhaobo/anaconda3/envs/pmf/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1011, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/qinhaobo/anaconda3/envs/pmf/lib/python3.9/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/home/qinhaobo/anaconda3/envs/pmf/lib/python3.9/multiprocessing/connection.py", line 262, in poll
    return self._poll(timeout)
  File "/home/qinhaobo/anaconda3/envs/pmf/lib/python3.9/multiprocessing/connection.py", line 429, in _poll
    r = wait([self], timeout)
  File "/home/qinhaobo/anaconda3/envs/pmf/lib/python3.9/multiprocessing/connection.py", line 936, in wait
    ready = selector.select(timeout)
  File "/home/qinhaobo/anaconda3/envs/pmf/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/qinhaobo/anaconda3/envs/pmf/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 22822) is killed by signal: Aborted. 

The above exception was the direct cause of the following exception:
```

**Comment by VitalyFedyunin** [comment]
Hello! Do you have minimal reproducible code. Also please collect data about platform you are using. Thanks.

**Comment by henrykironde** [comment]
I also tried with num_workers=0 and got something similar
