### ISSUE TITLE
PyTorch 1.12.0 weight_norm is not working with float16

### ISSUE THREAD

**Issue by ydshieh** [pytorch/pytorch#80599]
### 🐛 Describe the bug

PyTorch 1.12.0 `weight_norm` is not working with `float16`

**To reproduce**

```python
import torch
from torch import nn

class WeightNormModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv1d(16, 16, 8, padding=4, groups=2)
        self.conv = nn.utils.weight_norm(self.conv, name="weight", dim=2)

    def forward(self, hidden_states):
        hidden_states = self.conv(hidden_states)
        return hidden_states

torch.set_default_dtype(torch.float16)

model = WeightNormModule()
input_values = torch.ones(2, 16, 4, dtype=torch.float16)

model = model.to("cuda")
input_values = input_values.to("cuda")

out = model(input_values)
```

**Error**
```
root@54e594368192:/transformers# python3 test.py
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model = WeightNormModule()
  File "test.py", line 10, in __init__
    self.conv = nn.utils.weight_norm(self.conv, name="weight", dim=2)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/utils/weight_norm.py", line 108, in weight_norm
    WeightNorm.apply(module, name, dim)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/utils/weight_norm.py", line 49, in apply
    setattr(module, name, fn.compute_weight(module))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/utils/weight_norm.py", line 24, in compute_weight
    return _weight_norm(v, g, self.dim)
RuntimeError: "weight_norm_kernel" not implemented for 'Half'
```

### Versions

```
PyTorch version: 1.12.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-1033-gcp-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.2.152
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 470.129.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.11.0+cpu
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] torch==1.12.0+cu113
[pip3] torch-scatter==2.0.9
[pip3] torchaudio==0.12.0+cu113
[pip3] torchvision==0.13.0+cu113
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @VitalyFedyunin

**Comment by ydshieh** [comment]
The code snippet works with ` torch==1.11.0+cu113`
