### ISSUE TITLE
[bug][nvfuser] Applying nvfuser to the model leads to runtime error

### ISSUE THREAD

**Issue by ArmageddonKnight** [pytorch/pytorch#80851]
### 🐛 Describe the bug

```
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    all_metrics = trainer.train(args.steps, args.val_steps, args.save_every, args.eval_every)
  File "/h/zhengboj/SetGan/set-gan/trainer.py", line 127, in train
    d_loss, g_loss, d_aux_losses, g_aux_losses = self.train_step(args_i)
  File "/h/zhengboj/SetGan/set-gan/trainer.py", line 189, in train_step
    d_base_loss_i, d_aux_losses_i = self._discriminator_step(args)
  File "/h/zhengboj/SetGan/set-gan/trainer.py", line 383, in _discriminator_step
    aux_losses[loss_fct.name] = loss_fct(self.discriminator, self.generator, candidate_batch, fake_batch, args, "discriminator", reference_batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/h/zhengboj/SetGan/set-gan/training_utils.py", line 204, in forward
    return self._discriminator_loss(discriminator, generator, real_batch, fake_batch, args, *loss_args, **loss_kwargs)
  File "/h/zhengboj/SetGan/set-gan/training_utils.py", line 236, in _discriminator_loss
    scaled_gradients = torch.autograd.grad(outputs=self.scaler.scale(disc_interpolates), inputs=interpolates,
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: 0INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":602, please report a bug to PyTorch. We don't have an op for aten::cat but it isn't a special case.  Argument types: Tensor, int, 

Candidates:
        aten::cat(Tensor[] tensors, int dim=0) -> (Tensor)
        aten::cat.names(Tensor[] tensors, str dim) -> (Tensor)
        aten::cat.names_out(Tensor[] tensors, str dim, *, Tensor(a!) out) -> (Tensor(a!))
        aten::cat.out(Tensor[] tensors, int dim=0, *, Tensor(a!) out) -> (Tensor(a!))
Generated:
```

I tried to enable nvfuser when training my model but got the above runtime error. I also tried running my code without scripting the model and everything goes fine. It seems that the error is caused by invoking the `torch.cat` operator with a single tensor. However, after checking the source code, I can verify that each `torch.cat` operator is invoked with a list of tensors. Therefore, I am not sure what is causing this issue. Any help is appreciated. Thanks.

### Versions

```
Collecting environment information...
PyTorch version: 1.12.0a0+2c916ef
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.31

Python version: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:42:07)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-110-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.112
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4

Nvidia driver version: 470.103.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.12.0a0+2c916ef
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchtext==0.12.0a0
[pip3] torchvision==0.13.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.22.3           py38h05e7239_0    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.12.0a0+2c916ef          pypi_0    pypi
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchtext                 0.12.0a0                 pypi_0    pypi
[conda] torchvision               0.13.0a0                 pypi_0    pypi
```

FYI, @ wangshangsam

**Comment by ngimel** [comment]
Can you please provide a script reproducing the error?

**Comment by wangshangsam** [comment]
> Can you please provide a script reproducing the error?
> 
> cc @jjsjann123 

Hi @ngimel ,

Thank you so much for checking on this issue! Since we are working on a close-sourced repo, would you (or anyone else who would be helping to debug this) be open to being added into this private repo? Alternatively we could prepare a code snippet that reproduce this error, however, that might take some time (this error message arises during 'torch.autograd.grad' and we are not yet certain which layers/ops led to this bug).

Thanks!

**Comment by jjsjann123** [comment]
I'm taking a wild guess that there's something with the concat/chunk optimization pass inside fusion. Would you mind running your script with debug dump? `PYTORCH_JIT_LOG_LEVEL=graph_fuser python your_script.py &> log`, We should be able to see the last fusion graph and figure out a repro from there.

FYI, there's a `debug nvfuser` section in https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/codegen/cuda/README.md

**Comment by ngimel** [comment]
I won't be working on debugging this issue, but Nvidia's nvfuser team might be interested. @jjsjann123, @wangshangsam can you guys please discuss what the options are?

**Comment by jjsjann123** [comment]
> I won't be working on debugging this issue, but Nvidia's nvfuser team might be interested. @jjsjann123, @wangshangsam can you guys please discuss what the options are?

Hopefully it'll be easy to get some debug dump so we can reverse engineer a repro from there.
Not sure how tricky it would be for me to get into their close-sourced repo, I would at least need to get management approval. Let's consider that as a backup plan~

**Comment by ngimel** [comment]
@wangshangsam, @jjsjann123 can you guys start by following the steps here https://github.com/pytorch/pytorch/tree/master/torch/csrc/jit/codegen/cuda#general-ideas-of-debug-nvfuser-mal-functioning, or is something else a better approach?

**Comment by jjsjann123** [comment]
Yeah, I think doing this `PYTORCH_JIT_LOG_LEVEL=graph_fuser python your_script.py &> log` would be a reasonable first step. Should be able to workout a repro with that.

**Comment by ArmageddonKnight** [comment]
@jjsjann123 Thanks. I have attached the compilation log here.

[nvfuser_compilation.log](https://github.com/pytorch/pytorch/files/9087702/nvfuser_compilation.log)


FYI, @wangshangsam

**Comment by jjsjann123** [comment]
errr, I actually don't see anything went wrong in the graph log (all aten::cat are operating on list of tensors), looks like we are not trying to insert any chunk neither....

Unfortunately we don't have a graph dump in aliasdb. Let's verify if this is nvfuser specific. We can run things with `PYTORCH_JIT_USE_NNC_NOT_NVFUSER=1 PYTORCH_JIT_LOG_LEVEL=profiling_executor_graph_impl python your_script.py &> log`

**Comment by ArmageddonKnight** [comment]
Hi @jjsjann123 

Thanks for your suggestions. The first command gives the following error:

```
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    all_metrics = trainer.train(args.steps, args.val_steps, args.save_every, args.eval_every)
  File "/h/zhengboj/SetGan/set-gan/trainer.py", line 127, in train
    d_loss, g_loss, d_aux_losses, g_aux_losses = self.train_step(args_i)
  File "/h/zhengboj/SetGan/set-gan/trainer.py", line 189, in train_step
    d_base_loss_i, d_aux_losses_i = self._discriminator_step(args)
  File "/h/zhengboj/SetGan/set-gan/trainer.py", line 383, in _discriminator_step
    aux_losses[loss_fct.name] = loss_fct(self.discriminator, self.generator, candidate_batch, fake_batch, args, "discriminator", reference_batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/h/zhengboj/SetGan/set-gan/training_utils.py", line 204, in forward
    return self._discriminator_loss(discriminator, generator, real_batch, fake_batch, args, *loss_args, **loss_kwargs)
  File "/h/zhengboj/SetGan/set-gan/training_utils.py", line 236, in _discriminator_loss
    scaled_gradients = torch.autograd.grad(outputs=self.scaler.scale(disc_interpolates), inputs=interpolates,
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: 0INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":602, please report a bug to PyTorch. We don't have an op for aten::cat but it isn't a special case.  Argument types: Tensor, int, 

Candidates:
	aten::cat(Tensor[] tensors, int dim=0) -> (Tensor)
	aten::cat.names(Tensor[] tensors, str dim) -> (Tensor)
	aten::cat.names_out(Tensor[] tensors, str dim, *, Tensor(a!) out) -> (Tensor(a!))
	aten::cat.out(Tensor[] tensors, int dim=0, *, Tensor(a!) out) -> (Tensor(a!))
Generated:
```

and the second command gives the same error.

**Comment by jjsjann123** [comment]
So this is not nvfuser specific, as NNC also repros this one.

I can still help tho. Would you be able to push the full log somewhere when running with the second config: `PYTORCH_JIT_LOG_LEVEL=profiling_executor_graph_impl python your_script.py &> log`. <- this should dump a graph somewhere and we can stare at that to figure out a repro....

**Comment by ArmageddonKnight** [comment]
Here is the full log:

```
Profiling application [python3 main.py set_gan --task omniglot --n 2 --batch_size 128 --latent_size 128 --hidden_size 256 --lr_d 1e-4 --lr_g 1e-4 --reference_size 8 12 --candidate_size 5 8 --steps 3000000 --val_steps 250 --warmup_steps 200000 --anneal_steps 1000000 --num_heads 8 --disc_blocks 2 --gen_blocks 2 --output_layers 1 --dropout 0.1 --noise_dim 100 --l_smooth 0.2 --p_flip 0.2 --nu 3 --mu0 -0.3 --s0 0.2 --mu_scale 8 --basedir omniglot_runs --save_every 10000 --eval_every 10000 --conv_mode seq --n_critic 5 --criterion wgan --eps 1e-5 --lambda_gp 10.0 --lambda_cyc 0.1 --model_type med --imgsize 64 --gen_sample_size 4 4 --gaussian_noise 0 --checkpoint_dir ./7937413 --run_id 7937413 --n_gpus 1 --no_encoder --gradient_penalty --bn --save_gen_samples --use_apex --use_amp]
Output Filename: tmp
Profile from start?: No (cudaProfilerStart/Stop required)
{}
128, 256
{}
128, 256
Applying torch.jit.script to the model ...
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    all_metrics = trainer.train(args.steps, args.val_steps, args.save_every, args.eval_every)
  File "/h/zhengboj/SetGan/set-gan/trainer.py", line 127, in train
    d_loss, g_loss, d_aux_losses, g_aux_losses = self.train_step(args_i)
  File "/h/zhengboj/SetGan/set-gan/trainer.py", line 191, in train_step
    d_base_loss_i, d_aux_losses_i = self._discriminator_step(args)
  File "/h/zhengboj/SetGan/set-gan/trainer.py", line 385, in _discriminator_step
    aux_losses[loss_fct.name] = loss_fct(self.discriminator, self.generator, candidate_batch, fake_batch, args, "discriminator", reference_batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/h/zhengboj/SetGan/set-gan/training_utils.py", line 204, in forward
    return self._discriminator_loss(discriminator, generator, real_batch, fake_batch, args, *loss_args, **loss_kwargs)
  File "/h/zhengboj/SetGan/set-gan/training_utils.py", line 236, in _discriminator_loss
    scaled_gradients = torch.autograd.grad(outputs=self.scaler.scale(disc_interpolates), inputs=interpolates,
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: 0INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":602, please report a bug to PyTorch. We don't have an op for aten::cat but it isn't a special case.  Argument types: Tensor, int, 

Candidates:
	aten::cat(Tensor[] tensors, int dim=0) -> (Tensor)
	aten::cat.names(Tensor[] tensors, str dim) -> (Tensor)
	aten::cat.names_out(Tensor[] tensors, str dim, *, Tensor(a!) out) -> (Tensor(a!))
	aten::cat.out(Tensor[] tensors, int dim=0, *, Tensor(a!) out) -> (Tensor(a!))
```

Sorry but I do not see a graph dumped somewhere.

**Comment by ArmageddonKnight** [comment]
Hi @jjsjann123. Sorry for bothering you again, but may I know whether you could provide us with more suggestions on how to debug the fuser? Thank you.

**Comment by jjsjann123** [comment]
Oops, sorry I missed last message.

My bad that I gave the wrong instruction :face_with_head_bandage: ... It should be `PYTORCH_JIT_LOG_LEVEL=profiling_graph_executor_impl`. It's using the native jit log https://github.com/pytorch/pytorch/blob/c94706c0118a41d0400e78b01dae897d0f1f9457/torch/csrc/jit/jit_log.h#L8-L39

We should be able to see a very long log dumping graph from this file: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp
We'll be able to see which graph partition hits that assert then.

**Comment by ArmageddonKnight** [comment]
Hi @jjsjann123 I have attached the compilation log here:

[nvfuser_compilation.log](https://github.com/pytorch/pytorch/files/9248139/nvfuser_compilation.log)

Thank you for your help.

**Comment by jjsjann123** [comment]
At the very end of the log, it prints out a `Profiled Graph` and then the assert failure. That graph is unfortunately a backward graph so it's somewhat cryptic and I can't figure out how to reverse-engineer the forward graph from that.  :face_with_head_bandage: 

I'm still leaning towards that one of the passes here (https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp#L658-L678) introduced the issue.

Let's dump the log in verbose mode with `PYTORCH_JIT_LOG_LEVEL=">>profiling_graph_executor_impl"`. We'll unfortunately see a much bigger log, but hopefully it would expose precisely which pass generates an invalid graph. :crossed_fingers: 

Sorry for this back and forth. :cry:

**Comment by ArmageddonKnight** [comment]
Hi. I have attached the verbose compilation log to this thread. Because the file is too large I have to zip it before uploading. Thank you.

[nvfuser_verbose_compilation.log.zip](https://github.com/pytorch/pytorch/files/9253906/nvfuser_verbose_compilation.log.zip)

**Comment by jjsjann123** [comment]
Looks like it's coming from autodiff. We just forgot to update the output type.

A simpler repro:
```
import torch
  
def fn(x):
    o = x + 1
    o = o.split(2, 2)
    o = torch.cat(o, 0)
    return o

device = "cuda"
scripted_ln = torch.jit.script(fn)
x=torch.randn(4, 2, 4, device=device, requires_grad=True)

for _ in range(4):
    out=scripted_ln(x)
    out.sum().backward()
```

Here we seems to forgot to update the output type for `AutogradAdd`
https://github.com/pytorch/pytorch/blob/bcc8f592ba060cdc011c7534a2832ea9b816f733/torch/csrc/jit/runtime/autodiff.cpp#L354-L357

I tried to patch that one and copy input type to output. Which seems to have fixed the original issue. But looks like `AutogradAdd` doesn't really handle list tensors. (Even though there's list in a few other places in symbolic_script.cpp)
https://github.com/pytorch/pytorch/blob/bcc8f592ba060cdc011c7534a2832ea9b816f733/torch/csrc/jit/runtime/register_prim_ops.cpp#L2518-L2549

Here's the updated graph with AutogradAdd return type patched
```
 Forward graph:
 graph(%x.1 : Tensor):
   %11 : int = prim::Constant[value=1]()
   %o.18 : Tensor = aten::add(%x.1, %11, %11) # repro_autodiff.py:4:8
   %6 : int = prim::Constant[value=2]()
   %o.15 : Tensor[] = aten::split(%o.18, %6, %6) # repro_autodiff.py:5:8
   %3 : int = prim::Constant[value=0]()
   %o.10 : Tensor = aten::cat(%o.15, %3) # repro_autodiff.py:6:8
   %17 : bool = prim::Constant[value=1]() # <string>:168:12
   %size.1 : int = aten::len(%o.15) # <string>:166:19
   %20 : int[] = prim::ListConstruct(%3)
   %split_sizes.4 : int[] = aten::mul(%20, %size.1) # <string>:167:26
    = prim::Loop(%size.1, %17) # <string>:168:12
     block0(%i.1 : int):
       %23 : Tensor = aten::__getitem__(%o.15, %i.1) # <string>:169:19
       %24 : int[] = aten::size(%23) # <string>:169:19
       %26 : bool = aten::ne(%24, %20) # <string>:169:19
        = prim::If(%26) # <string>:169:16
         block0():
           %27 : Tensor = aten::__getitem__(%o.15, %i.1) # <string>:170:37
           %28 : int[] = aten::size(%27) # <string>:170:37
           %29 : int = aten::__getitem__(%28, %3) # <string>:170:37
           %30 : int[] = aten::_set_item(%split_sizes.4, %i.1, %29) # <string>:170:20
           -> ()
         block1():
           -> ()
       -> (%17)
   return (%o.10, %o.15, %3, %17, %20, %split_sizes.4)
 Backward graph:
 graph(%0 : Float(8, 2, 2, strides=[4, 2, 1], requires_grad=1, device=cuda:0),
       %1 : Tensor[],
       %o.14 : Tensor[],
       %3 : int,
       %4 : bool,
       %5 : int[],
       %split_sizes.2 : int[]):
   %7 : int = prim::Constant[value=2]()
   %8 : int = prim::Constant[value=0]()
   %9 : Float(8, 2, 2, strides=[4, 2, 1], requires_grad=1, device=cuda:0) = prim::GradOf[name="prim::profile"](%0)
     block0():
       -> (%0)
   %grad_tensors.1 : Tensor[] = prim::GradOf[name="aten::cat"](%9)
     block0():
       %grad_tensors.2 : Tensor[] = aten::split_with_sizes(%9, %split_sizes.2, %8) # <string>:173:31
       -> (%grad_tensors.2)
   %12 : Tensor[] = prim::AutogradAdd(%1, %grad_tensors.1)                                   <- This is the place where return type has been patched from `Tensor` to `Tensor[]`
   %grad_self.4 : Tensor = prim::GradOf[name="aten::split"](%12)
     block0():
       %grad_self.2 : Tensor = aten::cat(%12, %7) # <string>:133:28
       -> (%grad_self.2)
   %grad_self.6 : Tensor = prim::GradOf[name="prim::profile"](%grad_self.4)
     block0():
       -> (%grad_self.4)
   %grad_self.8 : Tensor = prim::GradOf[name="aten::add"](%grad_self.6)
     block0():
       -> (%grad_self.6)
   %grad_self.1 : Tensor = prim::GradOf[name="prim::profile"](%grad_self.8)
     block0():
       -> (%grad_self.8)
   %18 : (Tensor) = prim::TupleConstruct(%grad_self.1)
   return (%18)

```

I can try to add list support in `AutogradAdd`. but I feel like I'm not on the right track....
Pinging @eellison , not sure who's maintaining autodiff at this moment.

**Comment by ArmageddonKnight** [comment]
@jjsjann123 Sorry for bothering you again, but may I know whether there is any update on this bug? Thank you.

**Comment by jjsjann123** [comment]
Oops, totally forgot about this one. Thanks for the reminder~~

I was trying to see if there's any Meta folks that can help us with Autodiff issue. Let me ping @ngimel  to see if she can point us to the right person.

**Comment by ngimel** [comment]
@eellison is the correct person for autodiff issues.

**Comment by ArmageddonKnight** [comment]
Hi, @jjsjann123 May I know whether there is any update on this issue? Thanks.

**Comment by jjsjann123** [comment]
Sorry I missed the message.

I saw @eellison self assigned, wondering if we have assigned any meta folks handling this issue?
