### ISSUE TITLE
[LTC] OOM on mnist example

### ISSUE THREAD

**Issue by Yancey1989** [pytorch/pytorch#80942]
### 🐛 Describe the bug

OOM on the example mnist.py while enabling CUDA device, the error logs is as the following. I just use `torch.cuda.memory_stats` to print the allocated CUDA memory, and we can see the memory is increasing:

``` text
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.305605
allocated_bytes.all.current: 33812992
Train Epoch: 1 [640/60000 (1%)]	Loss: 1.253851
allocated_bytes.all.current: 180380160
....
Train Epoch: 2 [0/60000 (0%)]	Loss: 0.034653
allocated_bytes.all.current: 13733059072
Train Epoch: 2 [640/60000 (1%)]	Loss: 0.074930
allocated_bytes.all.current: 13879101952
Train Epoch: 2 [1280/60000 (2%)]	Loss: 0.003717
allocated_bytes.all.current: 14025144832
Traceback (most recent call last):
  File "test_mnist.py", line 86, in <module>
    train(log_interval, model, device, train_loader, optimizer, epoch)
  File "test_mnist.py", line 49, in train
    torch._lazy.mark_step()
  File "/workspace/BladeDISC/venv-py38/lib/python3.8/site-packages/torch/_lazy/__init__.py", line 12, in mark_step
    torch._C._lazy._mark_step(device, [], wait=wait)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.76 GiB total capacity; 13.18 GiB already allocated; 9.75 MiB free; 13.66 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

## Reproduce Steps
 
``` bash
git clone git@github.com:pytorch/pytorch.git
LTC_TS_CUDA=1 python pytorch/torch/csrc/lazy/test_mnist.py 
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.20.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-162-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration:
GPU 0: Tesla T4
GPU 1: Tesla T4

Nvidia driver version: 460.91.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.12.0+cu113
[conda] Could not collect

**Comment by wconstab** [comment]
Thanks for reporting this. I may not have time to investigate this week, but in the mean time can you collect more metrics such as whether LTC is recompiling the graph on every iteration or how many times it is hitting 'cached compile' and 'uncached compile'?

you could add a call to 'counter_names' and then use a loop over counter names to call 'counter_value' and dump those here.  I'd be interested in 
- one dump at the end of epoch for all counters
- one experiment where you dump 'cached compile' and 'uncached compile' every iteration for enough iterations to see if there is a pattern.  we'd expect uncached compile only happening during the first couple of iterations and then always cached afterward.

https://github.com/pytorch/pytorch/blob/master/torch/_lazy/metrics.py#L7

**Comment by Yancey1989** [comment]
Hi @wconstab , I added some metrics logs, and no uncached compile after about 10 iterations, here is the test code: https://gist.github.com/Yancey1989/bd786321e3901e430fb3715df45eac1d , do you have any advice for this bug or do you have ever reproduce this OOM case on your development environment?

**Comment by wconstab** [comment]
Oh- is this using a BLADE-DISC backend or is this using torchscript + nvfuser?  I was going to suggest trying a different backend too.

**Comment by Yancey1989** [comment]
HI @wconstab , thanks for your reply,  I don't use BladeDISC or NvFuser, and I disable the nvfuser with `export PYTORCH_JIT_ENABLE_NVFUSER=0 `

Actually, I just installed the official PyTorch wheel  in the Nvidia Docker image:

``` bash
 nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04
```

and run `test_mnist.py` in a container, the process OOM after serval iterations:
 
``` bash
python -m pip install torch==1.12.0+cu113 torchvision -f https://download.pytorch.org/whl/torch_stable.html 
PYTORCH_JIT_ENABLE_NVFUSER=0 LTC_TS_CUDA=1 python test_mnist.py
```

**Comment by wconstab** [comment]
@Yancey1989 sorry for the delay. I did run the repro today and confirmed seeing the leak.  I hope to make some progress on this before I go on PTO next week.  If not it'll be on our list.

**Comment by wconstab** [comment]
I found that I could repro this issue from a simple C++ unit test, which made it easier to focus in.  
```c++
TEST_F(LazyOpsTest, TestMemLeak) {
  torch::Device device = torch::lazy::backendDeviceToAtenDevice(torch::lazy::BackendDevice());
  torch::Tensor input = torch::rand(
      {80000000}, torch::TensorOptions(torch::kFloat).device(DefaultDevice()));
  for (int i = 0; i < 1000; i++) {
    torch::Tensor lazy_input = CopyToDevice(input, device);
  }
}
```
I was able to root cause the issue down to a cache that we maintain and never clear, which holds on to tensor data.  This was an oversight in how SymInt support got rolled out, and @Krovatkin has a fix in mind.  @Krovatkin can you also see if you can make my snippet above into a mem-leak unit test that uses code like this
```c++
auto new_stats = c10::cuda::CUDACachingAllocator::getDeviceStats(/*device_id*/0);
size_t bytes_this_loop = new_stats.allocated_bytes.at(0).current - stats.allocated_bytes.at(0).current;
```
to confirm we're not picking up allocations when running a few loops of alloc/destroy?

**Comment by Hurray0** [comment]
cpu mode has the same OOM problem

**Comment by Yancey1989** [comment]
Hi @wconstab , @Krovatkin , thanks for dealing with this issue, do you have any updates?

**Comment by Krovatkin** [comment]
I working on the fix here: https://github.com/pytorch/pytorch/pull/82233 should be merged soon

**Comment by Yancey1989** [comment]
Hi @Krovatkin , it seems this bug is still exciting, I installed the nightly build wheel and also OOM on mnist example,

PyTorch wheel: `torch-1.13.0.dev20220825%2Bcu113-cp38-cp38-linux_x86_64.whl`

**Comment by fortianyou** [comment]
@Yancey1989 @wconstab I can reproduce CUDA OOM just with backward called. It seems Variable grad backed by LazyTensor never run out of its' life time:
```python
import torch._lazy
import torch._lazy.ts_backend

torch._lazy.ts_backend.init()

import torch
from torch.autograd import Variable

data = torch.randn(32, 32, 224, 224).to('lazy')
a = Variable(data, requires_grad=True)
while True:
    b = torch.randn(1, 32, 224, 224).to('lazy')
    out = a * b
    out.backward(a)
    print(a.grad.sum())
    # Will result in CUDA OOM without force delete a.grad
    del a.grad
```

**Comment by wconstab** [comment]
@fortianyou I believe the code snippet above needs to call 'mark_step' in order to trigger that a graph for the loop iteration should be finalized.  If you don't do the mark_step, you are going to keep accumulating the operations forever into one big graph.  (the print is not enough to break the graph, it just executes the graph so-far but lets it continue to build).

Note that @Krovatkin ran the small C++ unit test above (`TEST_F(LazyOpsTest, TestMemLeak) {`) and found no more symint related leak.  So at least for that pre-existing leak, the fix has landed and we aren't able to repro anymore. 

@Yancey1989 is it possible the build you got didn't have the fix yet?  or if not, maybe we need to start over and find a new repro as the `TEST_F(LazyOpsTest, TestMemLeak) {` seems to be fixed.

**Comment by fortianyou** [comment]
> @fortianyou I believe the code snippet above needs to call 'mark_step' in order to trigger that a graph for the loop iteration should be finalized

It still ran out CUDA OOM after I added `mark_step`. It seems `mark_step` does not work as expectly. The code snippet I ran:
```
import torch._lazy
import torch._lazy.ts_backend

torch._lazy.ts_backend.init()

import torch
from torch.autograd import Variable

data = torch.randn(32, 32, 224, 224).to('lazy')
a = Variable(data, requires_grad=True)
while True:
    b = torch.randn(1, 32, 224, 224).to('lazy')
    out = a * b
    out.backward(a)
    print(a.grad.sum())
    torch._lazy.mark_step()
    # Will result in CUDA OOM without force delete a.grad
    # del a.grad
```

**Comment by Krovatkin** [comment]
Some notes:

The following commit definitely passes @wconstab ' test : 

```
commit 53c71e214233b0e97c1cb2bf02676a9f800c1e91 (origin/master, origin/HEAD)
Author: kshitij12345 <kshitijkalambarkar@gmail.com>
Date:   Tue Sep 13 21:02:53 2022 +0000
```

```
(pytorch5) [villedepommes@villedepommes-fedora-MJ0FLNPT pytorch5]$ build/bin/test_lazy --gtest_filter=LazyOpsTest.TestMemLeak
Only one CUDA device detected. Disabling MultiCUDA tests
Note: Google Test filter = LazyOpsTest.TestMemLeak-*_MultiCUDA
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from LazyOpsTest
[ RUN      ] LazyOpsTest.TestMemLeak
[       OK ] LazyOpsTest.TestMemLeak (4242 ms)
[----------] 1 test from LazyOpsTest (4242 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (4242 ms total)
```

**Unfortunately, `python test_mnist.py` still OOMs.**

I also added an assert in a SymIntNodeImpl c-tor: https://github.com/pytorch/pytorch/commit/5f1471b0a9b896f16cf22c490a7794bb13f5c7a8

The assert didn't fire either against `TestMemLeak` or `test_mnist.py`, so we can rule out leaks to symints.

I'm going to test mnist against XLA to see if they are experiencing the leak as well.

**Comment by sAviOr287** [comment]
Hi, 
are there any updates on this as i am experiencing the same problem ...

**Comment by tanyokwok** [comment]
@wconstab @Krovatkin Any updates?

**Comment by wconstab** [comment]
Sorry, we haven't had time to look at this.  If one of you can help debug, we could provide some pointers.  Otherwise this is on our backlog.

**Comment by Yancey1989** [comment]
Okay @wconstab , this bug is blocking our progress, maybe @tanyokwok or I will take some time to fix this issue, if you provide more information about this bugfix, we can fix it faster,  thank you.
