### ISSUE TITLE
torch.onnx.export prim::Constant type and ONNX Expand input shape constraint not satisfied.

### ISSUE THREAD

**Issue by MarcM0** [pytorch/pytorch#80989]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

I am trying to export a very large pytorch model to onnx. I apologize in advance but I can't share a reproducible example. 
When I run

```
tensorRTExampleIn=[torch.zeros([1, 1, 1024, 1280]).cuda(),torch.zeros([1, 1, 1024, 1280]).cuda()]
torch.onnx.export(self.net.module.cuda(), args=tuple(tensorRTExampleIn), f=path,input_names =["left_img","right_img"],output_names=['output'], export_params=True)
```
I get the following error

```
converting to ONNX
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Traceback (most recent call last):
  File "predictor.py", line 27, in __init__
    torch.onnx.export(self.net.module.cuda(), args=tuple(tensorRTExampleIn), f=path,input_names = ["left_img","right_img"],output_names=['output'], export_params=True, opset_version = 13)
  File "/home/marc/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/home/marc/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/home/marc/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/marc/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 731, in _model_to_graph
    graph = _optimize_graph(
  File "/home/marc/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 308, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/marc/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 416, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/marc/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1406, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/marc/.local/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py", line 529, in expand_as
    return g.op("Expand", self, shape)
  File "/home/marc/.local/lib/python3.8/site-packages/torch/onnx/_patch_torch.py", line 66, in _graph_op
    torch._C._jit_pass_onnx_node_shape_type_inference(
RuntimeError: input_shape_value == reshape_value || input_shape_value == 1 || reshape_value == 1 INTERNAL ASSERT FAILED at "../torch/csrc/jit/passes/onnx/shape_type_inference.cpp":567, please report a bug to PyTorch. ONNX Expand input shape constraint not satisfied
```

## System Info
Pyorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-52-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 510.73.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.12.0+cu116
[pip3] torch-tensorrt==1.1.0
[pip3] torch2trt==0.3.0
[pip3] torchaudio==0.12.0+cu116
[pip3] torchvision==0.13.0+cu116
[conda] None
 onnx.__version__ '1.12.0'

**Comment by justinchuby** [comment]
Can you run export with `verbose=True` and share the output?

**Comment by MarcM0** [comment]
I fixed it by converting to jit script first, changing some of the code, and updating the opset, although now I get an error that pops up at random intervals. I will send it in this thread the next time it comes up.

**Comment by MarcM0** [comment]
```
Traceback (most recent call last):
  File "evaluate.py", line 22, in <module>
    evaluator = Evaluator(ckpt_path="./best_model.ckpt",
  File "/home/marc/Documents/tensorRTLong/EESR_SUB_CODE/utils/evaluator.py", line 49, in __init__
    self.predictor = Predictor(ckpt_path, model_params, data_params,tensorRTExampleIn=tensorRTExampleIn)
  File "/home/marc/Documents/tensorRTLong/EESR_SUB_CODE/utils/predictor.py", line 31, in __init__
    torch.onnx.export(self.net.module.cuda(), args=tuple(tensorRTExampleIn), verbose=True, f=path,input_names = ["left_img","right_img"],output_names=["depth", "disp", "edge"], export_params=True,opset_version=14)
  File "/home/marc/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 785, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/home/marc/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 502, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/home/marc/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RecursiveScriptModule' object has no attribute 'module'
```

**Comment by MarcM0** [comment]
Alright, I think I debugged the model. Should I be worried about these warnings? If so, how do I know where they originate from?
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
/home/marc/.local/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:533: UserWarning: Type cannot be inferred, which might cause exported graph to produce incorrect results.
  warnings.warn(
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
/home/marc/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:1130: UserWarning: Default upsampling behavior when mode=trilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details (Triggered internally at  ../torch/csrc/jit/runtime/register_prim_ops_fulljit.cpp:538.)
  return forward_call(*input, **kwargs)
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.

**Comment by MarcM0** [comment]
Thank you

**Comment by MarcM0** [comment]
Thank you

**Comment by MarcM0** [comment]
I fixed it by converting to jit script first, changing some of the code, and updating the opset, although now I get an error that pops up at random intervals. I will send it in this thread the next time it comes up.

Edit: i no longer need jit script, the original error was caused by expand_as, which i replaced with expand(hardcoded_array)

**Comment by lixhk** [comment]
But how to move this warning ?  It seems no solution ...

**Comment by lixhk** [comment]
It generate from   https://github.com/pytorch/pytorch/blob/1dd733644134aed812948d749f9eb6544d508e6a/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L1912

**Comment by justinchuby** [comment]
That looks like some old code we have updated already.

**Comment by lixhk** [comment]
> That looks like some old code we have updated already.

main branch here  
https://github.com/pytorch/pytorch/blob/main/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L1920

**Comment by justinchuby** [comment]
I believe this is a warning you can filter with Python configuration?

**Comment by lix19937** [comment]
> But how to move this warning ? It seems no solution ...

https://github.com/pytorch/pytorch/issues/85015
