### ISSUE TITLE
[primtorch] `torch.masked_fill` ref does not match eager's device promotion semantics.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#81018]
### 🐛 Describe the bug

```
mask = torch.ones(5, dtype=torch.bool, device='cuda')
s = torch.tensor(float('inf'))
val = torch.randn(5, device='cuda')

torch.masked_fill(val, mask, s)
# tensor([inf, inf, inf, inf, inf], device='cuda:0')

torch._refs.masked_fill(val, mask, s)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/chilli/fresh/pytorch/torch/_refs/__init__.py", line 2847, in masked_fill
    return torch.where(mask, prims.to_dtype(value, a.dtype), a)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

cc: @kshitij12345 @mruberry @ngimel 

### Versions

N/A

**Comment by Lezcano** [comment]
Is it expected that `masked_fill` accepts tensors in different devices? If so, which operations are expected to support this, because we usually don't support this behaviour.

**Comment by kshitij12345** [comment]
I think it makes sense for `masked_fill` to allow `value` to be promoted to CUDA as it is a scalar tensor.
