### ISSUE TITLE
Error Validating Libtorch Pod

### ISSUE THREAD

**Issue by harshit-bansal18** [pytorch/pytorch#81037]
### 🐛 Describe the bug

I am trying to publish bitcode enabled cocoapod for LibTorch. I copied the source files from [libtorch_ios_1.8](https://ossci-ios.s3.amazonaws.com/libtorch_ios_1.11.zip), the source for official LibTorch cocoapod. I configured [LibTorch.podspec](https://github.com/pytorch/pytorch/blob/master/ios/LibTorch.podspec) file to add `Bitcode Enable` option in it.
\
This is my `podspec` file:
```
#
# Be sure to run `pod lib lint iOSTorch.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see https://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = '<POD_NAME>'
  s.version          = '<VERSION>'
  s.summary          = 'Bitcode enabled version of LibTorch'

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!

  s.description      = <<-DESC
TODO: Add long description of the pod here.
                       DESC

  s.homepage         = 'https://github.com/<GITHUB_USERNAME>'
  # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  s.license          = { :type => 'Apache 2.0', :file => 'LICENSE' }
  s.author           = { '<GITHUB_USERNAME' => '<EMAIL>' }
  s.source           = { :git => '<LIBTORCH SOURCE>', :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.ios.deployment_target = '13.0'

  s.default_subspec = 'Core'
    s.subspec 'Core' do |ss|
        ss.dependency '<POD_NAME>/Torch'
        ss.source_files = 'src/*.{h,cpp,c,cc}'
        ss.public_header_files = ['src/LibTorch.h']
    end
  s.subspec 'Torch' do |ss|
        ss.header_mappings_dir = 'install/include/'
        ss.preserve_paths = 'install/include/**/*.{h,cpp,cc,c}'
        ss.vendored_libraries = 'install/lib/*.a'
        ss.libraries = ['c++', 'stdc++']
    end

  s.user_target_xcconfig = {
        'HEADER_SEARCH_PATHS' => '$(inherited) "${PODS_ROOT}/<POD_NAME>/install/include/"',
        'OTHER_LDFLAGS' => '-force_load "${PODS_ROOT}/<POD_NAME>/install/lib/libtorch.a" -force_load "${PODS_ROOT}/<POD_NAME>/<POD_NAME>/install/lib/libtorch_cpu.a"',
        #'CLANG_CXX_LANGUAGE_STANDARD' => 'c++14',
        #'CLANG_CXX_LIBRARY' => 'libc++'
    }
  s.pod_target_xcconfig = {
        'HEADER_SEARCH_PATHS' => '$(inherited) "${PODS_ROOT}/<POD_NAME>/install/include/"',
        'VALID_ARCHS' => 'arm64',
        'ENABLE_BITCODE' => 'YES'

    }
  s.library = ['c++', 'stdc++']
  s.frameworks = 'UIKit'
```

* Steps to reproduce the error:
```
pod lib create <POD_NAME>
cd <POD_NAME>
wget https://ossci-ios.s3.amazonaws.com/libtorch_ios_1.8.zip
unzip libtorch_ios_1.8.zip
rm libtorch_ios_1.8.zip
# Now copy the above podspec file to <POD_NAME.podspec> file and fill in the required fields.
# Make a new empty repo on github and add the remote to that repo and push the code. Also tag the commit with the <VERSION>
```
Refer the [blog](https://medium.com/@satishios25/creating-and-publishing-a-custom-pod-to-cocoapods-library-b314c3c7b4f0) for more details on publishing cocoapods.

This is the error I am facing on running the following command:

```
pod lib lint <POD_NAME.podspec> --verbose --no-clean
# some output...
 Ld /Users/harshit/Library/Developer/Xcode/DerivedData/App-eodvlfgtjbosxmfdyzrbzwglbjwm/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/Binary/App normal x86_64 (in target 'App' from project 'App')
        cd /var/folders/5k/p_pc6tbx3lv5krnv31vy2b600000gn/T/CocoaPods-Lint-20220707-81410-1xxfmr9-iOSTorch
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios13.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk -L/Users/harshit/Library/Developer/Xcode/DerivedData/App-eodvlfgtjbosxmfdyzrbzwglbjwm/Build/Products/Release-iphonesimulator -L/var/folders/5k/p_pc6tbx3lv5krnv31vy2b600000gn/T/CocoaPods-Lint-20220707-81410-1xxfmr9-iOSTorch/Pods/../../../../../../../../Users/harshit/tmp/iOSTorch/install/lib -F/Users/harshit/Library/Developer/Xcode/DerivedData/App-eodvlfgtjbosxmfdyzrbzwglbjwm/Build/Products/Release-iphonesimulator -filelist /Users/harshit/Library/Developer/Xcode/DerivedData/App-eodvlfgtjbosxmfdyzrbzwglbjwm/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/harshit/Library/Developer/Xcode/DerivedData/App-eodvlfgtjbosxmfdyzrbzwglbjwm/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -lXNNPACK -lc++ -lc10 -lclog -lcpuinfo -leigen_blas -lpthreadpool -lpytorch_qnnpack -lstdc++ -ltorch -ltorch_cpu -framework UIKit -force_load /var/folders/5k/p_pc6tbx3lv5krnv31vy2b600000gn/T/CocoaPods-Lint-20220707-81410-1xxfmr9-iOSTorch/Pods/iOSTorch/install/lib/libtorch.a -force_load /var/folders/5k/p_pc6tbx3lv5krnv31vy2b600000gn/T/CocoaPods-Lint-20220707-81410-1xxfmr9-iOSTorch/Pods/iOSTorch/install/lib/libtorch_cpu.a -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/harshit/Library/Developer/Xcode/DerivedData/App-eodvlfgtjbosxmfdyzrbzwglbjwm/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/App.app-Simulated.xcent -framework Foundation -framework Pods_App -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/harshit/Library/Developer/Xcode/DerivedData/App-eodvlfgtjbosxmfdyzrbzwglbjwm/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App_dependency_info.dat -o /Users/harshit/Library/Developer/Xcode/DerivedData/App-eodvlfgtjbosxmfdyzrbzwglbjwm/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/Binary/App
    ld: file not found: /var/folders/5k/p_pc6tbx3lv5krnv31vy2b600000gn/T/CocoaPods-Lint-20220707-81410-1xxfmr9-iOSTorch/Pods/iOSTorch/install/lib/libtorch.a
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	Ld /Users/harshit/Library/Developer/Xcode/DerivedData/App-eodvlfgtjbosxmfdyzrbzwglbjwm/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/Binary/App normal x86_64 (in target 'App' from project 'App')
    (1 failure)
   Testing with `xcodebuild`. 
 -> iOSTorch (0.1.0)
    - ERROR | [iOSTorch/Core,iOSTorch/Torch] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOSTorch/Core,iOSTorch/Torch] xcodebuild:  note: Using new build system
    - NOTE  | [iOSTorch/Core,iOSTorch/Torch] xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOSTorch/Core,iOSTorch/Torch] xcodebuild:  note: Build preparation complete
    - NOTE  | [iOSTorch/Core,iOSTorch/Torch] xcodebuild:  note: Planning
    - NOTE  | [iOSTorch/Core,iOSTorch/Torch] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [iOSTorch/Core] xcodebuild:  Headers/Public/iOSTorch/iOSTorch.h:4:10: fatal error: 'torch/script.h' file not found
    - WARN  | [iOSTorch/Core,iOSTorch/Torch] xcodebuild:  /Users/harshit/Library/Developer/Xcode/DerivedData/App-eodvlfgtjbosxmfdyzrbzwglbjwm/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/arm64/main.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'App' from project 'App')
    - NOTE  | [iOS] [iOSTorch/Torch] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Pods workspace available at `/var/folders/5k/p_pc6tbx3lv5krnv31vy2b600000gn/T/CocoaPods-Lint-20220707-81410-1xxfmr9-iOSTorch/App.xcworkspace` for inspection.

[!] iOSTorch did not pass validation, due to 1 error and 1 warning.

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/lib/lint.rb:113:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/lib/lint.rb:75:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/lib/lint.rb:75:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Versions

* Device: Macbook Pro M1 2020
* OS: macOS Monterey Version 12.4
* Cocoapod Version: 1.11.3
* LibTorch Version: 1.8
* Xcode Version: 13.4.1

**Comment by dreiss** [comment]
I think we've found that libtorch doesn't work with bitcode because of our assembly-optimized numerical routines.  I'm not sure if that's what's causing your failure.

**Comment by jmdetloff** [comment]
pod lib lint is used to lint local source, but your podspec points to remote source. You should be using the 'pod spec lint' command. You can step into pytorch/ios and run:
pod spec lint --verbose --allow-warnings --no-clean --use-libraries --skip-import-validation
to confirm our pod lints successfully.
