### ISSUE TITLE
torchvision.transforms.functional.rgb_to_grayscale() + torch.nn.Conv2d() don`t work on 1080 GPU

### ISSUE THREAD

**Issue by MichaelMonashev** [pytorch/pytorch#81106]
### 🐛 Describe the bug

Code to reproduce bug:
```
import gc

import torch
import torchvision


def bench(model, device, memory_format):

    model = model.to(device=device, dtype=torch.float, memory_format=memory_format, non_blocking=False)
    model.eval()

    batch = torch.rand(8,3,256,256, device=device).to(device=device, dtype=torch.float, memory_format=memory_format, non_blocking=False)

    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.synchronize()

    with torch.inference_mode():
        with torch.autocast(device.type, enabled=True):
            model(batch)

    del batch



class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()

        self.conv1 = torch.nn.Conv2d(1, 8, kernel_size=5, stride=1, bias=False)


    def forward(self, x):
        print('before', x.device, x.dtype, x.layout, x.is_contiguous())
        x = torchvision.transforms.functional.rgb_to_grayscale(x, num_output_channels=1)
        print('after', x.device, x.dtype, x.layout, x.is_contiguous())

        x = self.conv1(x)

        return x


def main_worker():

    device = torch.device("cuda")


    bench_model = MyModel()
    bench_model.eval()

    bench(bench_model, device, torch.contiguous_format)
    bench(bench_model, device, torch.torch.channels_last)


if __name__ == '__main__':

    main_worker()
```

Output:
```
before cuda:0 torch.float32 torch.strided True
after cuda:0 torch.float32 torch.strided True
before cuda:0 torch.float32 torch.strided False
after cuda:0 torch.float32 torch.strided True
Traceback (most recent call last):
  File "1.py", line 57, in <module>
    main_worker()
  File "1.py", line 52, in main_worker
    bench(bench_model, device, torch.torch.channels_last)
  File "1.py", line 20, in bench
    model(batch)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "1.py", line 38, in forward
    x = self.conv1(x)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.


import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([8, 1, 256, 256], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(1, 8, kernel_size=[5, 5], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_HALF
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x4f4374d0
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 8, 1, 256, 256,
    strideA = 65536, 1, 256, 1,
output: TensorDescriptor 0x4f448120
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 8, 8, 252, 252,
    strideA = 508032, 1, 2016, 8,
weight: FilterDescriptor 0x4f1b6720
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NHWC
    nbDims = 4
    dimA = 8, 1, 5, 5,
Pointer addresses:
    input: 0x7f9abe800800
    output: 0x7f9abf800000
    weight: 0x7f9abe800000
Forward algorithm: 1
```

### Versions

```
~$ python3 collect_env.py
Collecting environment information...
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-66-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.12.0+cu116
[pip3] torchaudio==0.12.0+cu116
[pip3] torchvision==0.13.0+cu116
[conda] Could not collect
```

```
~$ nvidia-smi
Fri Jul  8 16:16:27 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 38%   56C    P2    40W / 180W |   5261MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1740557      C   /usr/bin/python3                 5259MiB |
+-----------------------------------------------------------------------------+
```

cc @ngimel @fmassa @vfdev-5 @pmeier

**Comment by ptrblck** [comment]
Thanks @MichaelMonashev for the code snippet!

I'm able to reproduce the failure using your code and started to debug it.
The issue is reproducible it:
* the first workload is executed before the `channels_last` one (the latter workload works fine if it's executed in isolation)
* the tensor needs to be transformed via `rgb_to_grayscale` before being passed to the conv

As a workaround you could call `x = x.to(memory_format=torch.channels_last)` after the transformation and before executing the conv which should fix the issue.

We'll continue to debug the issue.

**Comment by vfdev-5** [comment]
My 10-cents into testing failing configs as I was wondering if it is torchvision specific or not:

```python
class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = torch.nn.Conv2d(1, 8, kernel_size=5, stride=1, bias=False)

    def forward(self, x):
        print('before', x.device, x.dtype, x.layout, x.is_contiguous())
        # x = torchvision.transforms.functional.rgb_to_grayscale(x, num_output_channels=1)  # FAIL
        # x = x.sum(dim=-3).unsqueeze(dim=-3)  # FAIL
        # x = x[:, 0, ...].unsqueeze(dim=-3)  # FAIL
        x = x[:, :1, ...]  # OK
        
        print('after', x.device, x.dtype, x.layout, x.is_contiguous())
        x = self.conv1(x)
        return x
```

**Comment by jjsjann123** [comment]
Root cause is false positivie cache hit for cudnn entry.
An easier repro 

```
import torch
import torch.nn as nn
import torchvision

device = 'cuda'

if True:
    x = torch.rand(8, 1, 256, 256, device=device)
    conv = nn.Conv2d(1, 8, 5, bias=False).to(device)
    print("first input: ", x.size(), x.stride())
    with torch.cuda.amp.autocast():
        out = conv(x)


x = torch.rand(8, 1, 256, 256, device=device)
print("second input: ", x.size(), x.stride())

conv = nn.Conv2d(1, 8, 5, bias=False).to(device)
conv = conv.to(memory_format=torch.channels_last)

with torch.cuda.amp.autocast():
    out = conv(x)
print(out.shape)
```

**Comment by ptrblck** [comment]
Adding the `1.12.1` milestone in case we want to add this fix.
CC @atalman
