### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by where2go947** [pytorch/pytorch#81176]
### 🐛 Describe the bug

The model I tried to run requires `torch=1.2.0, CUDA 10.0`, Thus I set up a new virtual environment.

A simple test has been run:
```
import torch

a = torch.randn(1,2,3).cuda()
print(a)
```
It works but too long! (about 2-3min) as:
```
tensor([[[ 0.9284, -0.6863,  1.5324],
         [-0.6943, -0.7309,  0.4542]]], device='cuda:0')
```

When I run the network model, the program also took long but finally raised:
```
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

Could you please give me some advice? Thanks in advance!

### Versions

The system I am using is:
- Ubuntu 20.04
- laptop GeForce RTX 3070
- Driver Version: 510.73.05
- `torch=1.2.0` in virtualenv environment
- installed cuda 10.0 with `.runfile`, also checked with `nvcc -V`

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```
The full error is:
```
Traceback (most recent call last):
  File "predict.py", line 201, in <module>
    main()
  File "predict.py", line 164, in main
    pred_disp = aanet(left, right)[-1]  # [B, H, W]
  File "/home/usr/.virtualenv/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/usr/BIAS_SE/Xue/Projects/aanet-master/nets/aanet.py", line 207, in forward
    left_feature = self.feature_extraction(left_img)
  File "/media/usr/BIAS_SE/Xue/Projects/aanet-master/nets/aanet.py", line 134, in feature_extraction
    feature = self.feature_extractor(img)
  File "/home/usr/.virtualenv/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/usr/BIAS_SE/Xue/Projects/aanet-master/nets/resnet.py", line 178, in forward
    x = self.conv1(x)
  File "/home/usr/.virtualenv/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/usr/.virtualenv/aanet/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/usr/.virtualenv/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/usr/.virtualenv/aanet/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 94, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/usr/.virtualenv/aanet/lib/python3.7/site-packages/torch/nn/functional.py", line 911, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device


```

**Comment by ngimel** [comment]
Cuda 10 doesn't support 3070 gpu.

**Comment by albanD** [comment]
Closing this as expected behavior. Please upgrade your cuda version to a version that supports your GPU.
