### ISSUE TITLE
Error building Caffe2

### ISSUE THREAD

**Issue by briandw** [pytorch/pytorch#8125]
## Issue description

I am trying to build Caffe2. I am following the official instructions on the Caffe2 page. 
I am on the 0.4.0 tag of pytorch.
From the build:
`
cmake .. -DCPU_ONLY=ON
sudo make install
`

and I see the following output:

`
[ 26%] Built target nnpack_reference_layers
[ 26%] Building CXX object third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /home/brian/caffe2/pytorch/third_party/googletest/googletest/src/gtest-all.cc:45:0:
/home/brian/caffe2/pytorch/third_party/googletest/googletest/src/gtest-port.cc: In static member function ‘static bool testing::internal::RE::FullMatch(const char*, const testing::internal::RE&)’:
/home/brian/caffe2/pytorch/third_party/googletest/googletest/src/gtest-port.cc:581:52: error: ‘regexec’ was not declared in this scope
   return regexec(&re.full_regex_, str, 1, &match, 0) == 0;
                                                    ^
/home/brian/caffe2/pytorch/third_party/googletest/googletest/src/gtest-port.cc: In static member function ‘static bool testing::internal::RE::PartialMatch(const char*, const testing::internal::RE&)’:
/home/brian/caffe2/pytorch/third_party/googletest/googletest/src/gtest-port.cc:590:55: error: ‘regexec’ was not declared in this scope
   return regexec(&re.partial_regex_, str, 1, &match, 0) == 0;
                                                       ^
/home/brian/caffe2/pytorch/third_party/googletest/googletest/src/gtest-port.cc: In member function ‘void testing::internal::RE::Init(const char*)’:
/home/brian/caffe2/pytorch/third_party/googletest/googletest/src/gtest-port.cc:603:63: error: ‘regcomp’ was not declared in this scope
   is_valid_ = regcomp(&full_regex_, full_pattern, REG_EXTENDED) == 0;
                                                               ^
third_party/googletest/googletest/CMakeFiles/gtest.dir/build.make:62: recipe for target 'third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o' failed
make[2]: *** [third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
CMakeFiles/Makefile2:621: recipe for target 'third_party/googletest/googletest/CMakeFiles/gtest.dir/all' failed
make[1]: *** [third_party/googletest/googletest/CMakeFiles/gtest.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
`

Thanks for your help

## System Info
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 390.42
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.2
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.0.5
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by briandw** [comment]
Update:
I've switched to trying the builds script.
`/scripts/build_anaconda.sh --install-locally`

This fails in a new way:
`
[ 68%] Built target caffe2_pybind11_state
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/brian/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/brian/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/home/brian/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/home/brian/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/brian/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1776, in build_tree
    notest=notest,
  File "/home/brian/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1122, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/brian/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 676, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/brian/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 672, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/brian/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/brian/anaconda3/conda-bld/caffe2_1528145213240/work/conda_build.sh']' returned non-zero exit status 2.
`

**Comment by pjh5** [comment]
@briandw are your git submodules updated and init-ed? Can you run "git submodule update --init --recursive" in the pytorch directory? That error seems to be coming from the gtest repo, which we only point to.

The Anaconda error you pasted is just conda-build telling you that it detected that there was an error during building. The actual error that crashed will be further up in your output.

Do you already have pytorch installed via conda?

**Comment by briandw** [comment]
Hi @pjh5 
Thanks for having a look at my build issue.

I do already have pytorch installed via conda. But I did make a new env to build caffe2.

I checked out a clean version of pytorch , switched to the v0.4.0 tag, did the  "git submodule update --init --recursive" command then made a build dir,
`cmake ..; sudo make install`

and it results in
`/home/brian/caffe2/pytorch/third_party/onnx/onnx/defs/tensor/defs.cc:60:6: error: ‘class onnx_c2::OpSchema’ has no member named ‘ShapeInferenceFunction’
     .ShapeInferenceFunction([](InferenceContext& ctx) {
      ^
/home/brian/caffe2/pytorch/third_party/onnx/onnx/defs/tensor/defs.cc: In lambda function:
/home/brian/caffe2/pytorch/third_party/onnx/onnx/defs/tensor/defs.cc:61:48: error: ‘hasExactlyNInputTypes’ was not declared in this scope
       if (!hasExactlyNInputTypes(ctx, 1, "Cast")) {
`

I've attached a full log of the output
[out.txt](https://github.com/pytorch/pytorch/files/2078381/out.txt)

**Comment by BanuSelinTosun** [comment]
Hi @pjh5 and @briandw 
I have the same/similar error when I try to build caffe2 in a different environment all from scratch. I am following these instructions: https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#install-with-gpu-support
and getting the same error. 
Any resolutions yet?

Thank you,
Selin

**Comment by BanuSelinTosun** [comment]
@pjh5  No I have not built ONNX. But I also did not change the path either.
