### ISSUE TITLE
[ONNX] Symbolic registration for `pad_sequence` doesn't work in script module from 1.12.0

### ISSUE THREAD

**Issue by xuzijian629** [pytorch/pytorch#81388]
### 🐛 Describe the bug

# Problem
Cannot export onnx with custom `pad_sequence` when model is scripted from v1.12.0.

# Reproduction
```python3
import torch
import torch.onnx.symbolic_helper
import torch.onnx.symbolic_registry
from typing import List

@torch.onnx.symbolic_helper.parse_args("v", "b", "f")
def pad_sequence(g, input, batch_first, padding_value):
    return g.op("custom::MySequencePad", input)

torch.onnx.symbolic_registry.register_op("pad_sequence", pad_sequence, "", 13)

class Model(torch.nn.Module):
    def forward(self, xs: List[torch.Tensor]):
        return torch._C._nn.pad_sequence(xs, True, 0.)

# model = Model()
model = torch.jit.script(Model())
args = ([torch.rand(2, 5), torch.rand(3, 5)],)
torch.onnx.export(model, args, "test.onnx", opset_version=13)
```

```
Traceback (most recent call last):
  File "hoge.py", line 54, in <module>
    torch.onnx.export(model, args, "test.onnx", opset_version=13)
  File "/home/joe/build1012/venv/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/home/joe/build1012/venv/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/home/joe/build1012/venv/lib/python3.8/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/joe/build1012/venv/lib/python3.8/site-packages/torch/onnx/utils.py", line 731, in _model_to_graph
    graph = _optimize_graph(
  File "/home/joe/build1012/venv/lib/python3.8/site-packages/torch/onnx/utils.py", line 234, in _optimize_graph
    _C._jit_pass_lower_all_tuples(graph)
RuntimeError: kind_.is_prim() INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/ir.cpp":1219, please report a bug to PyTorch. Only prim ops are allowed to not have a registered operator but aten::pad_sequence doesn't have one either. We don't know if this op has side effects.
```

|  torch version | model = Model()  | model = torch.jit.script(Model())  |
| ---- | ---- |  ---- |
|  v1.11.0  |  Success  |  Success | 
|  v1.12.0  |  Success  |  **Fail!** |

# Cause of this issue
Maybe related to https://github.com/pytorch/pytorch/pull/57868, introduced from v1.12.0, but I'm not sure.

### Versions

v1.12.0

**Comment by BowenBao** [comment]
@AllenTiTaiWang, looks like the error is from `"../torch/csrc/jit/ir/ir.cpp":1219`, called by `_jit_pass_lower_all_tuples`
```
  File "/home/joe/build1012/venv/lib/python3.8/site-packages/torch/onnx/utils.py", line 234, in _optimize_graph
    _C._jit_pass_lower_all_tuples(graph)
RuntimeError: kind_.is_prim() INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/ir.cpp":1219, please report a bug to PyTorch. Only prim ops are allowed to not have a registered operator but aten::pad_sequence doesn't have one either. We don't know if this op has side effects.
```

Could you check which function in `ir.cpp` it was calling, and check whether an isolated repro which is irrelevant to exporter can be created?

**Comment by AllenTiTaiWang** [comment]
@ngimel Could you also take a look on this if you have time? I think the error comes from jit

**Comment by devyndonahue** [comment]
I am also having this issue, has there been any update on this? @AllenTiTaiWang  @ngimel

**Comment by AllenTiTaiWang** [comment]
@xuzijian629 ,

Are you sure v1.11 works in a right way? Because the reason it worked, the graph used to ignore that input type. Seems buggy:

```bash
[DUMP script_init.cpp:545] graph(%xs.1 : Tensor[]):  # It has no input right here.
[DUMP script_init.cpp:545]   %1 : __torch__.___torch_mangle_1.Model = prim::CreateObject()
[DUMP script_init.cpp:545]   %2 : float = prim::Constant[value=0.](), scope: Model:: # /home/titaiwang/PR_test/pad_seq_script.py:13:51
[DUMP script_init.cpp:545]   %3 : bool = prim::Constant[value=1](), scope: Model:: # /home/titaiwang/PR_test/pad_seq_script.py:13:45
[DUMP script_init.cpp:545]   %4 : Tensor = aten::pad_sequence(%xs.1, %3, %2), scope: Model:: # /home/titaiwang/PR_test/pad_seq_script.py:13:15
[DUMP script_init.cpp:545]   return (%4)
```
And this is actually caused by our previous improvement on https://github.com/pytorch/pytorch/pull/73284, which passes the input into the graph. I suspect pad_sequence in scripting never works... LMK if you have more detail on this.

Honestly, this repro is preferred tracing to scripting.
