### ISSUE TITLE
"Attempted to resize a view tensor to a larger size. This is not allowed in the functionalization pass" reported on non view tensor

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#81385]
### 🐛 Describe the bug

Repro test:

```
    def test_resize_intermediate(self):
        def f(x):
            y = x.clone()
            z = y.view(0)
            y.resize_(20)
            return y

        self.assert_functionalization(f, torch.ones(0))
```

this raises

```
======================================================================
ERROR: test_resize_intermediate (__main__.TestFunctionalization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_functionalization.py", line 120, in test_resize_intermediate
    self.assert_functionalization(f, torch.ones(0))
  File "test/test_functionalization.py", line 93, in assert_functionalization
    out_functional = func(input_functional)
  File "test/test_functionalization.py", line 117, in f
    y.resize_(20)
RuntimeError: Attempted to resize a view tensor to a larger size. This is not allowed in the functionalization pass
```

However, y is not a view.

This variant of the program does work:

```
        def f(x):
            y = x.clone()
            y.resize_(20)
            return y
```

cc @bdhirsh this is low priority

### Versions

master

**Comment by bdhirsh** [comment]
Oh yep, this is a known limitation (the error message is just bad).

If we resize a base tensor that has any outstanding views, we need to arrange for all of those views to be re-generated. That doesn't work today but seems fixable.
