### ISSUE TITLE
DISABLED test_forward_ad_nn_functional_conv_transpose3d_cuda_float32 (__main__.TestCompositeComplianceCUDA)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#81822]
Platforms: linux, win

This test was disabled because it is failing on master. Recent examples:
https://github.com/pytorch/pytorch/runs/7436485022?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/7436588376?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/7437747197?check_suite_focus=true

Logs:
```
======================================================================
2022-07-20T22:14:37.7282403Z FAIL [2.198s]: test_forward_ad_nn_functional_conv_transpose3d_cuda_float32 (__main__.TestCompositeComplianceCUDA)
2022-07-20T22:14:37.7283046Z ----------------------------------------------------------------------
2022-07-20T22:14:37.7283389Z Traceback (most recent call last):
2022-07-20T22:14:37.7288129Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1883, in wrapper
2022-07-20T22:14:37.7288620Z     method(*args, **kwargs)
2022-07-20T22:14:37.7289213Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1883, in wrapper
2022-07-20T22:14:37.7289925Z     method(*args, **kwargs)
2022-07-20T22:14:37.7290802Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
2022-07-20T22:14:37.7291646Z     result = test(self, **param_kwargs)
2022-07-20T22:14:37.7292595Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 813, in test_wrapper
2022-07-20T22:14:37.7293009Z     return test(*args, **kwargs)
2022-07-20T22:14:37.7293381Z   File "/var/lib/jenkins/workspace/test/test_ops.py", line 1259, in test_forward_ad
2022-07-20T22:14:37.7294108Z     composite_compliance.check_forward_ad_formula(
2022-07-20T22:14:37.7294833Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/composite_compliance.py", line 567, in check_forward_ad_formula
2022-07-20T22:14:37.7295298Z     assert_equal_fn(actual_primals, expected_primals, equal_nan=True)
2022-07-20T22:14:37.7296303Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2335, in assertEqual
2022-07-20T22:14:37.7296984Z     assert_equal(
2022-07-20T22:14:37.7297482Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
2022-07-20T22:14:37.7297858Z     raise error_metas[0].to_error(msg)
2022-07-20T22:14:37.7298235Z AssertionError: Tensor-likes are not close!
2022-07-20T22:14:37.7298665Z 
2022-07-20T22:14:37.7298801Z Mismatched elements: 1 / 2744 (0.0%)
2022-07-20T22:14:37.7299259Z Greatest absolute difference: 4.57763671875e-05 at index (2, 3, 4, 4) (up to 2e-05 allowed)
2022-07-20T22:14:37.7299779Z Greatest relative difference: 5.68618647611624e-05 at index (2, 3, 4, 4) (up to 2e-05 allowed)
2022-07-20T22:14:37.7300019Z 
2022-07-20T22:14:37.7300289Z ----------------------------------------------------------------------
```

It looked like it started with https://github.com/pytorch/pytorch/pull/81056, but that may be a coincidence only.

cc @ezyang @gchanan @zou3519 @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are would you be the right owner? is this nn related?

**Comment by janeyx99** [comment]
It looks like it's off by a bit too much (4e-5 vs 2e-5), so would the solution be to relax the test case a bit?

**Comment by janeyx99** [comment]
adding win to the mix as https://github.com/pytorch/pytorch/runs/7439648767?check_suite_focus=true is flaking too

**Comment by ezyang** [comment]
cc @soulitzer
