### ISSUE TITLE
Unknown builtin op: aten::broadcast_shapes

### ISSUE THREAD

**Issue by simplifier89** [pytorch/pytorch#81912]
### 🚀 The feature, motivation and pitch

`torch.broadcast_shapes` doesn't work with torch.jit.script：
```
@torch.jit.script
def broadcast_common_batch_shape(x, x_data, y_data):
    common_shape = torch.broadcast_shapes(x.size()[:-1], x_data.size()[:-1], y_data.size()[:-1])
    return (torch.broadcast_to(x, common_shape + x.size()[-1:]).contiguous(),
                torch.broadcast_to(x_data, common_shape + x_data.size()[-1:]).contiguous(),
                torch.broadcast_to(y_data, common_shape + y_data.size()[-1:]).contiguous())
````
It would be pleased to have this feature.

**Comment by davidberard98** [comment]
@simplifier89 can you include the error?

**Comment by simplifier89** [comment]
Hi, here it is
```
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\project\test.py", line 23, in <module>
    def broadcast_common_batch_shape(x, x_data, y_data):
  File "C:\Users\User\PycharmProjects\project\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 
Unknown builtin op: aten::broadcast_shapes.
Could not find any similar ops to aten::broadcast_shapes. This op may not exist or may not be currently supported in TorchScript.
```

**Comment by nawazishkhan1-nk** [comment]
Any updates on this issue?

**Comment by borisfom** [comment]
I am interested in getting that to work/ workarounds as well.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
