### ISSUE TITLE
test_sparse_spdiags_cpu_bool fails on my local working copy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#81979]
### 🐛 Describe the bug

Error looks like

``` ======================================================================                                              
ERROR: test_sparse_spdiags_cpu_bool (__main__.TestSparseCPU)                                                        
----------------------------------------------------------------------                                              
Traceback (most recent call last):                                                                                  
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 377, in instantiated_tes
t                                                                                                                   
    result = test(self, **param_kwargs)                                                                             
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_device_type.py", line 970, in only_fn         
    return fn(slf, *args, **kwargs)                                                                                 
  File "/data/users/ezyang/pytorch-tmp/test/test_sparse.py", line 3632, in test_sparse_spdiags                      
    check_valid(*case)                                                                                              
  File "/data/users/ezyang/pytorch-tmp/test/test_sparse.py", line 3590, in check_valid                              
    ref_out = reference(diags, offsets, shape)                                                                      
  File "/data/users/ezyang/pytorch-tmp/test/test_sparse.py", line 3583, in reference                                
    data = data[off:]                                                                                               
IndexError: slice() cannot be applied to a 0-dim tensor.                                                            
                                                                                                                    
----------------------------------------------------------------------      
```

Not sure why it's only my local copy.

### Versions

master

**Comment by cpuhrsch** [comment]
cc @bhosmer
