### ISSUE TITLE
test_sparse_matmul_cpu_complex128 fails on my local copy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#81982]
### 🐛 Describe the bug

```
======================================================================
FAIL: test_sparse_matmul_cpu_complex128 (__main__.TestSparseCPU)
This function test `torch.sparse.mm` when both the mat1 and mat2 are sparse tensors.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
    result = test(self, **param_kwargs)
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_utils.py", line 978, in wrapper
    fn(*args, **kwargs)
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_utils.py", line 3226, in wrapped
    f(self, *args, **kwargs, coalesced=True)
  File "test/test_sparse.py", line 3484, in test_sparse_matmul
    test_sparse_matmul(2, 10, [n, m], [m, p])
  File "test/test_sparse.py", line 3458, in test_sparse_matmul
    grad_with_custom_sparsity_pattern_test_helper(sparse_dims, nnz, shape_a, shape_b)
  File "test/test_sparse.py", line 3428, in grad_with_custom_sparsity_pattern_test_helper
    self.assertEqual(a.grad, a_grad)
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_internal/common_utils.py", line 2364, in assertEqual
    assert_equal(
  File "/raid/ezyang/pytorch-scratch2/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Sparse COO values are not close!

Mismatched elements: 4 / 4 (100.0%)
Greatest absolute difference: 3.3639772140974413 at index (2,) (up to 1e-07 allowed)
Greatest relative difference: 2.0993343823035606 at index (0,) (up to 1e-07 allowed)

----------------------------------------------------------------------
```

This is on a CUDA 11.6 build

### Versions

master

**Comment by cpuhrsch** [comment]
cc @bhosmer
