### ISSUE TITLE
NotImplementedError: The operator 'aten::index.Tensor_out' is not current implemented for the MPS device.

### ISSUE THREAD

**Issue by crayon7442** [pytorch/pytorch#82034]
### 🐛 Describe the bug

It works! But another error occurred..
```
> python3 train.py --device mps --img 416 --batch 16 --epochs 50 --data /Users/****/content/dataset/data.yaml --cfg ./models/yolov5s.yaml --weights yolov5s.pt --name hat_yolov5s_results
train: weights=yolov5s.pt, cfg=./models/yolov5s.yaml, data=/Users/****/content/dataset/data.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=50, batch_size=16, imgsz=416, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=mps, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=hat_yolov5s_results, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v6.1-313-g1c5e92a Python-3.9.12 torch-1.13.0.dev20220722 MPS

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
Overriding model.yaml nc=80 with nc=3

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     21576  models.yolo.Detect                      [3, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
YOLOv5s summary: 270 layers, 7027720 parameters, 7027720 gradients, 16.0 GFLOPs

Transferred 342/349 items from yolov5s.pt
/Users/****/content/yolov5/utils/general.py:820: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  x = x[xc[xi]]  # confidence
AMP: checks failed ❌, disabling Automatic Mixed Precision. See https://github.com/ultralytics/yolov5/issues/7908
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 57 weight (no decay), 60 weight, 60 bias
train: Scanning '/Users/****/content/dataset/train.cache' images and labels... 1412 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 1412/1412 [00:00<?, ?it/s]                   
val: Scanning '/Users/****/content/dataset/val.cache' images and labels... 354 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████| 354/354 [00:00<?, ?it/s]                          
Plotting labels to runs/train/hat_yolov5s_results3/labels.jpg... 

AutoAnchor: 5.43 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅
Image sizes 416 train, 416 val
Using 8 dataloader workers
Logging results to runs/train/hat_yolov5s_results3
Starting training for 50 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/89 [00:00<?, ?it/s]                                                                                                                                                     
Traceback (most recent call last):
  File "/Users/****/content/yolov5/train.py", line 642, in <module>
    main(opt)
  File "/Users/****/content/yolov5/train.py", line 537, in main
    train(opt.hyp, opt, device, callbacks)
  File "/Users/****/content/yolov5/train.py", line 328, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/Users/****/content/yolov5/utils/loss.py", line 125, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/Users/****/content/yolov5/utils/loss.py", line 208, in build_targets
    t = t[j]  # filter
NotImplementedError: The operator 'aten::index.Tensor_out' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```
### Versions

PyTorch version: 1.13.0.dev20220722
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.28.1)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.12 (main, Jun  1 2022, 06:34:44)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-13.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.13.0.dev20220722
[pip3] torchvision==0.14.0.dev20220722
[conda] numpy                     1.22.3           py39h25ab29e_0  
[conda] numpy-base                1.22.3           py39h974a1f5_0  
[conda] torch                     1.13.0.dev20220722          pypi_0    pypi
[conda] torchvision               0.14.0.dev20220722          pypi_0    pypi

cc @kulinseth @albanD

**Comment by AnnieL2** [comment]
Same issue when running YOLOv5s with MPS on M1 Mac mini 
YOLOv5 🚀 v6.1-325-g3e85863 Python-3.8.13 torch-1.13.0.dev20220727 MPS

**Comment by glenn-jocher** [comment]
@crayon7442 @AnnieL2 YOLOv5 inference and training are not currently supported on MPS due to unsupported torch ops but the torch team is aware of this issue in https://github.com/pytorch/pytorch/issues/77764 and they and they community are working on PRs to resolve the various unsupported ops.

I would head over to that issue and vote for the ops that are causing you issues to bump their priority.

**Comment by kulinseth** [comment]
the `index.Tensor_out` should be enabled on MPS with latest torch nightly.

**Comment by glenn-jocher** [comment]
@kulinseth thanks for the update! Can confirm that this resolves the original issue in YOLOv5. Further operators (aten:nonzero and aten:nms) remain but this issue is resolved.

<img width="1371" alt="Screenshot 2022-08-23 at 00 08 19" src="https://user-images.githubusercontent.com/26833433/186027293-e9ea35f6-dcdf-4832-a1b0-5d676a2a4827.png">
