### ISSUE TITLE
optimize_for_mobile vulkan_prepack::conv2d_clamp_prepack

### ISSUE THREAD

**Issue by zhuker** [pytorch/pytorch#82065]
### 🐛 Describe the bug

trying to convert a simple resnet18 model to mobile vulkan backend
i am being asked to report the bug `please report a bug to PyTorch. We don't have an op for vulkan_prepack::conv2d_clamp_prepack but it isn't a special case`

```python
import torch
from torch.utils.mobile_optimizer import optimize_for_mobile
print(torch.__version__)
m = torch.jit.load("ptl-models/resnet18_wd4_2_3_scripted.pt")
vm = optimize_for_mobile(m, backend='vulkan')
```

scripted.pt can be downloaded here https://drive.google.com/file/d/1crd0f-jq9GBAE0a7kKXAthgWcsHTNgYH/view?usp=sharing

```
1.12.0+cu102
Traceback (most recent call last):
  File "./pt_vulkan.py", line 5, in <module>
    vm = optimize_for_mobile(m, backend='vulkan')
  File "./venv/lib/python3.8/site-packages/torch/utils/mobile_optimizer.py", line 67, in optimize_for_mobile
    optimized_cpp_module = torch._C._jit_pass_vulkan_optimize_for_mobile(script_module._c, preserved_methods_str)
RuntimeError: 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":614, please report a bug to PyTorch. We don't have an op for vulkan_prepack::conv2d_clamp_prepack but it isn't a special case.  Argument types: Tensor, Tensor?, int[], int[], int[], int, NoneType, NoneType, 
```

### Versions

```
PyTorch version: 1.12.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-41-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Quadro RTX 5000 with Max-Q Design
Nvidia driver version: 515.48.07
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] pytorchcv==0.0.67
[pip3] torch==1.12.0
[conda] Could not collect
```

**Comment by SS-JIA** [comment]
Hey @zhuker - I think you will have to build with `USE_VULKAN=1`. Apologies if this wasn't clear from the docs.

**Comment by dvrogozh** [comment]
> `1.12.0+cu102`
> `Traceback (most recent call last):`

If pytorch is self built from sources I would expect to see version like this unless user did not specially care for the version:
```
$ python -c "import torch; print(torch.__version__)"
2.3.0a0+git77d979f
```

Version printed in the log makes me think that this might be due to the following trap in documentation:
* https://pytorch.org/tutorials/prototype/vulkan_workflow.html#building-pytorch-with-vulkan-backend here doc says to build with `USE_VULKAN=1`. Effectively user gets a build with vulkan support
* https://pytorch.org/tutorials/prototype/vulkan_workflow.html#model-preparation and here doc suggests to run `pip install torchvision` which will fetch pre-built pytorch version and basically override pytorch built by user with vulkan support

To resolve the trap you can just built https://github.com/pytorch/vision from sources. I think documentation might need to be updated accordingly.
