### ISSUE TITLE
upsample_bilinear2d() received an invalid combination of arguments

### ISSUE THREAD

**Issue by styler00dollar** [pytorch/pytorch#82068]
### 🐛 Describe the bug

In the past it was possible to use a Tensor within the `scale_factor` argument, but on newer versions this code fails. 

Works on every version:
```python
import torch
import torch.nn.functional as F
test_input = torch.rand(1,3,256,256)

x = F.interpolate(
    input=test_input, scale_factor=0.5, mode="bilinear", align_corners=False
)
print(x.shape)
```

Does not work on 1.11 and nightly anymore, but works on 1.10.1:
```python
import torch
import torch.nn.functional as F
test_input = torch.rand(1,3,256,256)

scale = torch.Tensor([0.5])
x = F.interpolate(
    input=test_input, scale_factor=scale, mode="bilinear", align_corners=False
)
print(x.shape)
```

It is possible to get it working with the current nightly with a workaround:
```python
import torch
import torch.nn.functional as F
test_input = torch.rand(1,3,256,256)

scale = torch.Tensor([0.5])
x = F.interpolate(
    input=test_input, scale_factor=scale.numpy()[0], mode="bilinear", align_corners=False
)
print(x.shape)
```
I would prefer it if I don't need to append this numpy suffix everywhere in my code and it did work in the past. That means I need to append this everywhere in my code if I decide to update torch. If there is a reason for this, then I would like to hear it, but I am assuming something went wrong when pytorch updated. Thanks.

### Versions

Mentioned above.

**Comment by ngimel** [comment]
cc @vfdev-5

**Comment by vfdev-5** [comment]
@styler00dollar tranks for reporting ! 

Accroding to the docs ([1.10](https://pytorch.org/docs/1.10/generated/torch.nn.functional.interpolate.html?highlight=interp#torch.nn.functional.interpolate)), scale factor is either float or list of floats, not tensor. So, passing a tensor for `scale_factor` is not intended to work.

I tried however to reproduce your second snippet on 1.10.1 and see if it was some how accepting tensors and I also get the same error message as you posted about invalid combination of arguments. So, IMO it does not work neither for 1.10.1 if we pass scale_factor as tensor. Am I missing something from your initial point?

If you want however to make it work, minimal change is to call `.item()` on `scale_factor`:
```python
import torch
print(torch.__version__)
import torch.nn.functional as F
test_input = torch.rand(1,3,256,256)

scale = torch.tensor(0.5)

x = F.interpolate(
    input=test_input, scale_factor=scale.item(), mode="bilinear", align_corners=False
)
print(x.shape)
```

**Comment by styler00dollar** [comment]
Thanks for the suggestion with `.item()`. I tried to reprocude again and I think I made an interesting discovery.
```
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu116 --force-reinstall -U
# torch-1.13.0.dev20220725%2Bcu116-cp38-cp38-linux_x86_64.whl
```
```
print("------------")
print(type(scale))
print(scale)
x = F.interpolate(
    x, scale_factor=1.0 / scale, mode="bilinear", align_corners=False
)
``` 
with 
```
out = model(dummy_input1, dummy_input2)
```
results in 
```
------------
<class 'int'>
8
```
but with 
```
torch.onnx.export(model, (dummy_input1, dummy_input2), f"onnx.onnx")
```
the print changes to
```
------------
<class 'torch.Tensor'>
tensor(8)
Traceback (most recent call last):
  File "bug.py", line 425, in <module>
    torch.onnx.export(model, (dummy_input1, dummy_input2), f"rife_1input.onnx")
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 479, in export
    _export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1411, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1050, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 925, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 833, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 1175, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1174, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "bug.py", line 233, in forward
    flow, mask = block[i](
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1174, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "bug.py", line 162, in forward
    x = F.interpolate(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 3944, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
TypeError: upsample_bilinear2d() received an invalid combination of arguments - got (Tensor, NoneType, bool, list), but expected one of:
 * (Tensor input, tuple of ints output_size, bool align_corners, tuple of floats scale_factors)
      didn't match because some of the arguments have invalid types: (Tensor, NoneType, bool, list)
 * (Tensor input, tuple of ints output_size, bool align_corners, float scales_h, float scales_w, *, Tensor out)
```
Exporting with onnx in `1.13.0.dev20220725+cu116` seems to create a tensor when onnx export is used, which wasnt prior a tensor. I did not expect it to change to a tensor.

But if I use 1.10.1, the export will work like intended.
```
pip install torch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 --force-reinstall -U
```
Gives the output
```
python bug.py
------------
<class 'int'>
8
/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:3679: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
torch.Size([1, 3, 256, 256])
------------
<class 'int'>
8
```

Small reproducer of above:
```python
import torch
import torch.nn.functional as F
import torch.nn as nn
import torch

class IFBlock(nn.Module):
    def __init__(self, in_planes, c=64):
        super(IFBlock, self).__init__()

    def forward(self, x, flow=None, scale=1):
        print("------------")
        print(type(scale))
        print(scale)
        x = F.interpolate(
            x, scale_factor=1.0 / scale, mode="bilinear", align_corners=False
        )
        return x, x

class IFNet(nn.Module):
    def __init__(self):
        super(IFNet, self).__init__()
        self.block0 = IFBlock(7, c=192)

    def forward(
        self,
        img0,
        img1,
        timestep=0.5,
        scale_list=[8, 4, 2, 1],
    ):
        x = torch.cat((img0, img1), 1)

        timestep = (x[:, :1].clone() * 0 + 1) * timestep

        flow, mask = self.block0(
            torch.cat((img0[:, :3], img1[:, :3], timestep), 1),
            None,
            scale=scale_list[0],
        )
        return torch.rand(1,3,256,256)

batch_size = 1
width = 512
height = 512

size = (batch_size,3, height, width)
dummy_input1 = torch.randn(size)
dummy_input2 = torch.randn(size)
input_names = ["input_1", "input_2"]
output_names = ["output_frame"]
model = IFNet()

out = model(dummy_input1, dummy_input2)
print(out.shape)

torch.onnx.export(model, (dummy_input1, dummy_input2), f"onnx.onnx")
```
If this was intended behavior, then I would be curious to know why 1.13 now converts it to a tensor and the issue could be closed. I assume I did some mistake prior and it indeed should have never worked on 1.10.1 like I claimed with my previous minimal example. I probably got confused while debugging, so I apologize for that.

**Comment by vfdev-5** [comment]
@styler00dollar I think this is related to onnx and the fact that it accepts only tensors as inputs: https://pytorch.org/docs/stable/onnx.html#types

I'm not onnx expert, I can only suggest that if `timestep` and `scale_list` are constants you can set them as attributes and there will be no float to Tensor conversion:
```python
class IFNet(nn.Module):
    def __init__(self):
        super(IFNet, self).__init__()
        self.block0 = IFBlock(7, c=192)
        self.timestep = 0.5
        self.scale_list = [8, 4, 2, 1]

    def forward(
        self,
        img0,
        img1,
    ):
        x = torch.cat((img0, img1), 1)

        timestep = (x[:, :1].clone() * 0 + 1) * self.timestep

        flow, mask = self.block0(
            torch.cat((img0[:, :3], img1[:, :3], timestep), 1),
            None,
            scale=self.scale_list[0],
        )
        return torch.rand(1,3,256,256)
```

However, according to the [FAQ](https://pytorch.org/docs/stable/onnx.html#frequently-asked-questions):
> How to export models with primitive type inputs (e.g. int, float)?
>    Support for primitive numeric type inputs was added in PyTorch 1.9. However, the exporter does not support models with str inputs.

Maybe related issue: https://github.com/pytorch/pytorch/issues/79279

**Comment by jbschlosser** [comment]
Is it fair to say this is an issue related to ONNX exporting?

**Comment by thiagocrepaldi** [comment]
> Is it fair to say this is an issue related to ONNX exporting?

not really. Looking the backtrace, the failure happened before the onnx exporter is executed.
