### ISSUE TITLE
[FSDP] FSDP wrapped UNet model running forward crashes

### ISSUE THREAD

**Issue by taoisu** [pytorch/pytorch#82079]
### 🐛 Describe the bug

I tried to use FSDP to wrap a unet model, but somehow after wrapped running forward function always resulted in a crash.

To repro the issue, use this code below:
```python
# main.py

import os
import torch
import torch.distributed as dist
from fsdp_examples.unet import UNetModel
from torch.distributed.fsdp.fully_sharded_data_parallel import (
    FullyShardedDataParallel as FSDP,
)
from torch.distributed.fsdp.wrap import size_based_auto_wrap_policy

dist.init_process_group(backend="nccl")
model = UNetModel(
    in_channels=3,
    model_channels=128,
    out_channels=3,
    num_res_blocks=3,
    attention_resolutions=[8]
)
dev = int(os.environ['LOCAL_RANK'])
fsdp_model = FSDP(model, device_id=dev, auto_wrap_policy=size_based_auto_wrap_policy)
fsdp_model.train()
img = torch.rand((2, 3, 64, 64), dtype=torch.float32)
t = torch.rand(2, dtype=torch.float32)
fsdp_model(img, t)
```

I launched it with `torchrun --nproc_per_node 2 main.py`

The error I got is:
```
(base) root@ccab4f7a6a8b4707903b4b491c065374000001:~/fsdp-examples/scripts# torchrun --nproc_per_node 2 main.py 
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py:9: UserWarning: is_namedtuple is deprecated, please use the python checks instead
  warnings.warn("is_namedtuple is deprecated, please use the python checks instead")
ccab4f7a6a8b4707903b4b491c065374000001:22850:22850 [0] NCCL INFO Bootstrap : Using eth0:10.0.0.5<0>
ccab4f7a6a8b4707903b4b491c065374000001:22850:22850 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

ccab4f7a6a8b4707903b4b491c065374000001:22850:22850 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
ccab4f7a6a8b4707903b4b491c065374000001:22850:22850 [0] NCCL INFO NET/Socket : Using [0]eth0:10.0.0.5<0>
ccab4f7a6a8b4707903b4b491c065374000001:22850:22850 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda11.6
/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py:9: UserWarning: is_namedtuple is deprecated, please use the python checks instead
  warnings.warn("is_namedtuple is deprecated, please use the python checks instead")
ccab4f7a6a8b4707903b4b491c065374000001:22851:22851 [1] NCCL INFO Bootstrap : Using eth0:10.0.0.5<0>
ccab4f7a6a8b4707903b4b491c065374000001:22851:22851 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

ccab4f7a6a8b4707903b4b491c065374000001:22851:22851 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
ccab4f7a6a8b4707903b4b491c065374000001:22851:22851 [1] NCCL INFO NET/Socket : Using [0]eth0:10.0.0.5<0>
ccab4f7a6a8b4707903b4b491c065374000001:22851:22851 [1] NCCL INFO Using network Socket
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Channel 00/04 :    0   1
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Channel 01/04 :    0   1
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Channel 02/04 :    0   1
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Channel 03/04 :    0   1
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO Setting affinity for GPU 1 to 0fffff
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Channel 00 : 0[100000] -> 1[200000] via P2P/IPC
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Channel 01 : 0[100000] -> 1[200000] via P2P/IPC
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Channel 02 : 0[100000] -> 1[200000] via P2P/IPC
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO Channel 00 : 1[200000] -> 0[100000] via P2P/IPC
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Channel 03 : 0[100000] -> 1[200000] via P2P/IPC
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO Channel 01 : 1[200000] -> 0[100000] via P2P/IPC
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO Channel 02 : 1[200000] -> 0[100000] via P2P/IPC
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO Channel 03 : 1[200000] -> 0[100000] via P2P/IPC
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Connected all rings
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO Connected all trees
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO Connected all rings
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO Connected all trees
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO 4 coll channels, 4 p2p channels, 4 p2p channels per peer
ccab4f7a6a8b4707903b4b491c065374000001:22850:22969 [0] NCCL INFO comm 0x7f8300002f70 rank 0 nranks 2 cudaDev 0 busId 100000 - Init COMPLETE
ccab4f7a6a8b4707903b4b491c065374000001:22851:22981 [1] NCCL INFO comm 0x7f72fc002f70 rank 1 nranks 2 cudaDev 1 busId 200000 - Init COMPLETE
ccab4f7a6a8b4707903b4b491c065374000001:22850:22850 [0] NCCL INFO Launch mode Parallel

ccab4f7a6a8b4707903b4b491c065374000001:22851:22851 [1] enqueue.cc:300 NCCL WARN Cuda failure 'an illegal memory access was encountered'
ccab4f7a6a8b4707903b4b491c065374000001:22851:22851 [1] NCCL INFO group.cc:347 -> 1
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    fsdp_model(img, t)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 2412, in forward
    self._rebuild_full_params()
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 3341, in _rebuild_full_params
    output_tensor, p_data, group=self.process_group
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2166, in _all_gather_base
    work = group._allgather_base(output_tensor, input_tensor)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:46, unhandled cuda error, NCCL version 2.10.3
ncclUnhandledCudaError: Call to CUDA function failed.
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from get at ../c10/cuda/CUDACachingAllocator.cpp:315 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7f736e87717e in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2896e (0x7f7397faf96e in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x257 (0x7f7397fb3ff7 in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x4913be (0x7f73bfd353be in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f736e85edf9 in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #5: <unknown function> + 0x6e78d0 (0x7f73bff8b8d0 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: THPVariable_subclass_dealloc(_object*) + 0x308 (0x7f73bff8bcc8 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0xfc547 (0x55e231ac7547 in /opt/conda/bin/python)
frame #8: <unknown function> + 0x163815 (0x55e231b2e815 in /opt/conda/bin/python)
frame #9: _PyGC_CollectNoFail + 0x2a (0x55e231bcc75a in /opt/conda/bin/python)
frame #10: PyImport_Cleanup + 0x4bc (0x55e231b77f9c in /opt/conda/bin/python)
frame #11: Py_FinalizeEx + 0x64 (0x55e231bec714 in /opt/conda/bin/python)
frame #12: <unknown function> + 0x232e20 (0x55e231bfde20 in /opt/conda/bin/python)
frame #13: _Py_UnixMain + 0x3c (0x55e231bfe18c in /opt/conda/bin/python)
frame #14: __libc_start_main + 0xe7 (0x7f73e1ee5c87 in /lib/x86_64-linux-gnu/libc.so.6)
frame #15: <unknown function> + 0x1d803a (0x55e231ba303a in /opt/conda/bin/python)

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 22850 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 22851) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-07-25_00:18:15
  host      : ccab4f7a6a8b4707903b4b491c065374000001.internal.cloudapp.net
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 22851)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 22851
============================================================
```

The complete unet definition is as below:
```python
# unet.py

import math

import numpy as np
import torch as th
import torch.nn as nn
import torch.functional as F

from abc import abstractmethod


def conv_nd(dims, *args, **kwargs):
    """
    Create a 1D, 2D, or 3D convolution module.
    """
    if dims == 1:
        return nn.Conv1d(*args, **kwargs)
    elif dims == 2:
        return nn.Conv2d(*args, **kwargs)
    elif dims == 3:
        return nn.Conv3d(*args, **kwargs)
    raise ValueError(f"unsupported dimensions: {dims}")


def linear(*args, **kwargs):
    """
    Create a linear module.
    """
    return nn.Linear(*args, **kwargs)


def avg_pool_nd(dims, *args, **kwargs):
    """
    Create a 1D, 2D, or 3D average pooling module.
    """
    if dims == 1:
        return nn.AvgPool1d(*args, **kwargs)
    elif dims == 2:
        return nn.AvgPool2d(*args, **kwargs)
    elif dims == 3:
        return nn.AvgPool3d(*args, **kwargs)
    raise ValueError(f"unsupported dimensions: {dims}")


def zero_module(module):
    """
    Zero out the parameters of a module and return it.
    """
    for p in module.parameters():
        p.detach().zero_()
    return module


def normalization(channels):
    """
    Make a standard normalization layer.

    :param channels: number of input channels.
    :return: an nn.Module for normalization.
    """
    return nn.GroupNorm(32, channels)


def timestep_embedding(timesteps, dim, max_period=10000):
    """
    Create sinusoidal timestep embeddings.

    :param timesteps: a 1-D Tensor of N indices, one per batch element.
                      These may be fractional.
    :param dim: the dimension of the output.
    :param max_period: controls the minimum frequency of the embeddings.
    :return: an [N x dim] Tensor of positional embeddings.
    """
    half = dim // 2
    freqs = th.exp(
        -math.log(max_period) * th.arange(start=0, end=half, dtype=th.float32) / half
    ).to(device=timesteps.device)
    args = timesteps[:, None].float() * freqs[None]
    embedding = th.cat([th.cos(args), th.sin(args)], dim=-1)
    if dim % 2:
        embedding = th.cat([embedding, th.zeros_like(embedding[:, :1])], dim=-1)
    return embedding


class TimestepBlock(nn.Module):
    """
    Any module where forward() takes timestep embeddings as a second argument.
    """

    @abstractmethod
    def forward(self, x, emb):
        """
        Apply the module to `x` given `emb` timestep embeddings.
        """


class TimestepEmbedSequential(nn.Sequential, TimestepBlock):
    """
    A sequential module that passes timestep embeddings to the children that
    support it as an extra input.
    """

    def forward(self, x, emb):
        for layer in self:
            if isinstance(layer, TimestepBlock):
                x = layer(x, emb)
            else:
                x = layer(x)
        return x


class Upsample(nn.Module):
    """
    An upsampling layer with an optional convolution.

    :param channels: channels in the inputs and outputs.
    :param use_conv: a bool determining if a convolution is applied.
    :param dims: determines if the signal is 1D, 2D, or 3D. If 3D, then
                 upsampling occurs in the inner-two dimensions.
    """

    def __init__(self, channels, use_conv, dims=2):
        super().__init__()
        self.channels = channels
        self.use_conv = use_conv
        self.dims = dims
        if use_conv:
            self.conv = conv_nd(dims, channels, channels, 3, padding=1)

    def forward(self, x):
        assert x.shape[1] == self.channels
        if self.dims == 3:
            x = F.interpolate(
                x, (x.shape[2], x.shape[3] * 2, x.shape[4] * 2), mode="nearest"
            )
        else:
            x = F.interpolate(x, scale_factor=2, mode="nearest")
        if self.use_conv:
            x = self.conv(x)
        return x


class Downsample(nn.Module):
    """
    A downsampling layer with an optional convolution.

    :param channels: channels in the inputs and outputs.
    :param use_conv: a bool determining if a convolution is applied.
    :param dims: determines if the signal is 1D, 2D, or 3D. If 3D, then
                 downsampling occurs in the inner-two dimensions.
    """

    def __init__(self, channels, use_conv, dims=2):
        super().__init__()
        self.channels = channels
        self.use_conv = use_conv
        self.dims = dims
        stride = 2 if dims != 3 else (1, 2, 2)
        if use_conv:
            self.op = conv_nd(dims, channels, channels, 3, stride=stride, padding=1)
        else:
            self.op = avg_pool_nd(stride)

    def forward(self, x):
        assert x.shape[1] == self.channels
        return self.op(x)


class ResBlock(TimestepBlock):
    """
    A residual block that can optionally change the number of channels.

    :param channels: the number of input channels.
    :param emb_channels: the number of timestep embedding channels.
    :param dropout: the rate of dropout.
    :param out_channels: if specified, the number of out channels.
    :param use_conv: if True and out_channels is specified, use a spatial
        convolution instead of a smaller 1x1 convolution to change the
        channels in the skip connection.
    :param dims: determines if the signal is 1D, 2D, or 3D.
    :param use_checkpoint: if True, use gradient checkpointing on this module.
    """

    def __init__(
        self,
        channels,
        emb_channels,
        dropout,
        out_channels=None,
        use_conv=False,
        use_scale_shift_norm=False,
        dims=2,
        use_checkpoint=False,
    ):
        super().__init__()
        self.channels = channels
        self.emb_channels = emb_channels
        self.dropout = dropout
        self.out_channels = out_channels or channels
        self.use_conv = use_conv
        self.use_checkpoint = use_checkpoint
        self.use_scale_shift_norm = use_scale_shift_norm

        self.in_layers = nn.Sequential(
            normalization(channels),
            nn.SiLU(),
            conv_nd(dims, channels, self.out_channels, 3, padding=1),
        )
        self.emb_layers = nn.Sequential(
            nn.SiLU(),
            linear(
                emb_channels,
                2 * self.out_channels if use_scale_shift_norm else self.out_channels,
            ),
        )
        self.out_layers = nn.Sequential(
            normalization(self.out_channels),
            nn.SiLU(),
            nn.Dropout(p=dropout),
            zero_module(
                conv_nd(dims, self.out_channels, self.out_channels, 3, padding=1)
            ),
        )

        if self.out_channels == channels:
            self.skip_connection = nn.Identity()
        elif use_conv:
            self.skip_connection = conv_nd(dims, channels, self.out_channels, 3, padding=1)
        else:
            self.skip_connection = conv_nd(dims, channels, self.out_channels, 1)

    def forward(self, x, emb):
        """
        Apply the block to a Tensor, conditioned on a timestep embedding.

        :param x: an [N x C x ...] Tensor of features.
        :param emb: an [N x emb_channels] Tensor of timestep embeddings.
        :return: an [N x C x ...] Tensor of outputs.
        """
        h = self.in_layers(x)
        emb_out = self.emb_layers(emb).type(h.dtype)
        while len(emb_out.shape) < len(h.shape):
            emb_out = emb_out[..., None]
        if self.use_scale_shift_norm:
            out_norm, out_rest = self.out_layers[0], self.out_layers[1:]
            scale, shift = th.chunk(emb_out, 2, dim=1)
            h = out_norm(h) * (1 + scale) + shift
            h = out_rest(h)
        else:
            h = h + emb_out
            h = self.out_layers(h)
        return self.skip_connection(x) + h


class AttentionBlock(nn.Module):
    """
    An attention block that allows spatial positions to attend to each other.

    Originally ported from here, but adapted to the N-d case.
    https://github.com/hojonathanho/diffusion/blob/1e0dceb3b3495bbe19116a5e1b3596cd0706c543/diffusion_tf/models/unet.py#L66.
    """

    def __init__(self, channels, num_heads=1, use_checkpoint=False):
        super().__init__()
        self.channels = channels
        self.num_heads = num_heads
        self.use_checkpoint = use_checkpoint

        self.norm = normalization(channels)
        self.qkv = conv_nd(1, channels, channels * 3, 1)
        self.attention = QKVAttention()
        self.proj_out = zero_module(conv_nd(1, channels, channels, 1))

    def forward(self, x):
        b, c, *spatial = x.shape
        x = x.reshape(b, c, -1)
        qkv = self.qkv(self.norm(x))
        qkv = qkv.reshape(b * self.num_heads, -1, qkv.shape[2])
        h = self.attention(qkv)
        h = h.reshape(b, -1, h.shape[-1])
        h = self.proj_out(h)
        return (x + h).reshape(b, c, *spatial)


class QKVAttention(nn.Module):
    """
    A module which performs QKV attention.
    """

    def forward(self, qkv):
        """
        Apply QKV attention.

        :param qkv: an [N x (C * 3) x T] tensor of Qs, Ks, and Vs.
        :return: an [N x C x T] tensor after attention.
        """
        ch = qkv.shape[1] // 3
        q, k, v = th.split(qkv, ch, dim=1)
        scale = 1 / math.sqrt(math.sqrt(ch))
        weight = th.einsum(
            "bct,bcs->bts", q * scale, k * scale
        )  # More stable with f16 than dividing afterwards
        weight = th.softmax(weight.float(), dim=-1).type(weight.dtype)
        return th.einsum("bts,bcs->bct", weight, v)

    @staticmethod
    def count_flops(model, _x, y):
        """
        A counter for the `thop` package to count the operations in an
        attention operation.

        Meant to be used like:

            macs, params = thop.profile(
                model,
                inputs=(inputs, timestamps),
                custom_ops={QKVAttention: QKVAttention.count_flops},
            )

        """
        b, c, *spatial = y[0].shape
        num_spatial = int(np.prod(spatial))
        # We perform two matmuls with the same number of ops.
        # The first computes the weight matrix, the second computes
        # the combination of the value vectors.
        matmul_ops = 2 * b * (num_spatial ** 2) * c
        model.total_ops += th.DoubleTensor([matmul_ops])


class UNetModel(nn.Module):
    """
    The full UNet model with attention and timestep embedding.

    :param in_channels: channels in the input Tensor.
    :param model_channels: base channel count for the model.
    :param out_channels: channels in the output Tensor.
    :param num_res_blocks: number of residual blocks per downsample.
    :param attention_resolutions: a collection of downsample rates at which
        attention will take place. May be a set, list, or tuple.
        For example, if this contains 4, then at 4x downsampling, attention
        will be used.
    :param dropout: the dropout probability.
    :param channel_mult: channel multiplier for each level of the UNet.
    :param conv_resample: if True, use learned convolutions for upsampling and
        downsampling.
    :param dims: determines if the signal is 1D, 2D, or 3D.
    :param num_classes: if specified (as an int), then this model will be
        class-conditional with `num_classes` classes.
    :param use_checkpoint: use gradient checkpointing to reduce memory usage.
    :param num_heads: the number of attention heads in each attention layer.
    """

    def __init__(
        self,
        in_channels,
        model_channels,
        out_channels,
        num_res_blocks,
        attention_resolutions,
        dropout=0,
        channel_mult=(1, 2, 4, 8),
        conv_resample=True,
        dims=2,
        num_classes=None,
        use_checkpoint=False,
        num_heads=1,
        num_heads_upsample=-1,
        use_scale_shift_norm=False,
    ):
        super().__init__()

        if num_heads_upsample == -1:
            num_heads_upsample = num_heads

        self.in_channels = in_channels
        self.model_channels = model_channels
        self.out_channels = out_channels
        self.num_res_blocks = num_res_blocks
        self.attention_resolutions = attention_resolutions
        self.dropout = dropout
        self.channel_mult = channel_mult
        self.conv_resample = conv_resample
        self.num_classes = num_classes
        self.use_checkpoint = use_checkpoint
        self.num_heads = num_heads
        self.num_heads_upsample = num_heads_upsample

        time_embed_dim = model_channels * 4
        self.time_embed = nn.Sequential(
            linear(model_channels, time_embed_dim),
            nn.SiLU(),
            linear(time_embed_dim, time_embed_dim),
        )

        if self.num_classes is not None:
            self.label_emb = nn.Embedding(num_classes, time_embed_dim)

        self.input_blocks = nn.ModuleList(
            [
                TimestepEmbedSequential(
                    conv_nd(dims, in_channels, model_channels, 3, padding=1)
                )
            ]
        )
        input_block_chans = [model_channels]
        ch = model_channels
        ds = 1
        for level, mult in enumerate(channel_mult):
            for _ in range(num_res_blocks):
                layers = [
                    ResBlock(
                        ch,
                        time_embed_dim,
                        dropout,
                        out_channels=mult * model_channels,
                        dims=dims,
                        use_checkpoint=use_checkpoint,
                        use_scale_shift_norm=use_scale_shift_norm,
                    )
                ]
                ch = mult * model_channels
                if ds in attention_resolutions:
                    layers.append(
                        AttentionBlock(
                            ch, use_checkpoint=use_checkpoint, num_heads=num_heads
                        )
                    )
                self.input_blocks.append(TimestepEmbedSequential(*layers))
                input_block_chans.append(ch)
            if level != len(channel_mult) - 1:
                self.input_blocks.append(
                    TimestepEmbedSequential(Downsample(ch, conv_resample, dims=dims))
                )
                input_block_chans.append(ch)
                ds *= 2

        self.middle_block = TimestepEmbedSequential(
            ResBlock(
                ch,
                time_embed_dim,
                dropout,
                dims=dims,
                use_checkpoint=use_checkpoint,
                use_scale_shift_norm=use_scale_shift_norm,
            ),
            AttentionBlock(ch, use_checkpoint=use_checkpoint, num_heads=num_heads),
            ResBlock(
                ch,
                time_embed_dim,
                dropout,
                dims=dims,
                use_checkpoint=use_checkpoint,
                use_scale_shift_norm=use_scale_shift_norm,
            ),
        )

        self.output_blocks = nn.ModuleList([])
        for level, mult in list(enumerate(channel_mult))[::-1]:
            for i in range(num_res_blocks + 1):
                layers = [
                    ResBlock(
                        ch + input_block_chans.pop(),
                        time_embed_dim,
                        dropout,
                        out_channels=model_channels * mult,
                        dims=dims,
                        use_checkpoint=use_checkpoint,
                        use_scale_shift_norm=use_scale_shift_norm,
                    )
                ]
                ch = model_channels * mult
                if ds in attention_resolutions:
                    layers.append(
                        AttentionBlock(
                            ch,
                            use_checkpoint=use_checkpoint,
                            num_heads=num_heads_upsample,
                        )
                    )
                if level and i == num_res_blocks:
                    layers.append(Upsample(ch, conv_resample, dims=dims))
                    ds //= 2
                self.output_blocks.append(TimestepEmbedSequential(*layers))

        self.out = nn.Sequential(
            normalization(ch),
            nn.SiLU(),
            zero_module(conv_nd(dims, model_channels, out_channels, 3, padding=1)),
        )

    def forward(self, x, timesteps, y=None):
        """
        Apply the model to an input batch.

        :param x: an [N x C x ...] Tensor of inputs.
        :param timesteps: a 1-D batch of timesteps.
        :param y: an [N] Tensor of labels, if class-conditional.
        :return: an [N x C x ...] Tensor of outputs.
        """
        assert (y is not None) == (
            self.num_classes is not None
        ), "must specify y if and only if the model is class-conditional"

        hs = []
        emb = self.time_embed(timestep_embedding(timesteps, self.model_channels))

        if self.num_classes is not None:
            assert y.shape == (x.shape[0],)
            emb = emb + self.label_emb(y)

        h = x
        for module in self.input_blocks:
            h = module(h, emb)
            hs.append(h)
        h = self.middle_block(h, emb)
        for module in self.output_blocks:
            cat_in = th.cat([h, hs.pop()], dim=1)
            h = module(cat_in, emb)
        h = h.type(x.dtype)
        return self.out(h)
```

### Versions

PyTorch version: 1.13.0.dev20220723+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.7.13 (default, Mar 29 2022, 02:18:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1063-azure-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 470.82.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==1.6.4
[pip3] torch==1.13.0.dev20220723+cu116
[pip3] torchaudio==0.13.0.dev20220723+cu116
[pip3] torchmetrics==0.9.2
[pip3] torchvision==0.14.0.dev20220723+cu116
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py37h7f8727e_0  
[conda] mkl_fft                   1.3.1            py37hd3c417c_0  
[conda] mkl_random                1.2.2            py37h51133e4_0  
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpy-base                1.21.5           py37ha15fc14_3  
[conda] pytorch-lightning         1.6.4                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.12.0                   pypi_0    pypi
[conda] torchaudio                0.13.0.dev20220723+cu116          pypi_0    pypi
[conda] torchmetrics              0.9.2                    pypi_0    pypi
[conda] torchvision               0.13.0                   pypi_0    pypi

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by taoisu** [comment]
BTW, DDP works perfectly fine:

```python
model.to(dev)
ddp_model = DDP(model, device_ids=[dev], output_device=dev)
ddp_model.train()
ddp_model(img, t)
```

There is a typo in `unet.py`, please change `import torch.functional as F` to `import torch.nn.functional as F`

**Comment by taoisu** [comment]
@zhaojuanmao I just figured out that setting cuda device with `torch.cuda.set_device(dev)` for each process seems to make this issue go away. Please feel free to close this issue.

**Comment by anj-s** [comment]
Thanks @taoisu  for letting us know. Closing the issue now.

**Comment by JerryDaHeLian** [comment]
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1347, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.5
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument'
I have encountered the same problem, has anyone solved it?
