### ISSUE TITLE
OOM during backward() leads to memory leaks

### ISSUE THREAD

**Issue by mutiann** [pytorch/pytorch#82218]
### 🐛 Describe the bug

Like what is shown in the logs below, I print the currently allocated memory by torch.cuda.memory_allocated() before the forward pass in each step. After the OOM in the backward() call, the intermediate tensors are not freed, which will lead to OOM in the following steps. 

OOM in the forward passes will not lead to the issue.

```
[INFO 2022-07-26 14:40:33,673] [Step 10115] 0.501 sec/step (0.555), lr=1.6427E-04, loss=0.15372 (Ave. 0.32287), grad_norm=0.747
[INFO 2022-07-26 14:40:33,675] Current memory: 6413632512
[INFO 2022-07-26 14:40:34,251] [Step 10116] 0.577 sec/step (0.552), lr=1.6426E-04, loss=0.17586 (Ave. 0.32030), grad_norm=1.508
[INFO 2022-07-26 14:40:34,254] Current memory: 6424706560
[ERROR 2022-07-26 14:40:34,609] Failed due to RuntimeError, input shape: torch.Size([28, 69920]), target shape: torch.Size([28, 82])
Traceback (most recent call last):
  File "train.py", line 210, in main
    losses['loss'].backward()
  File "/idiap/user/mhe/miniconda3/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/idiap/user/mhe/miniconda3/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 23.70 GiB total capacity; 20.20 GiB already allocated; 1.69 MiB free; 22.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[INFO 2022-07-26 14:40:34,829] Current memory: 21698449408
```

I've checked all the pytorch tensors with gc.get_objects() and confirmed that there are hundreds of tensors alive after the OOM that don't exist prior to the backward pass, indicating that they are created during the backward() call. Calling gc.collect() will not release them. sys.getrefcount(t) on one of these tensors gives like 4, but gc.get_referrers(t) gives nothing but t itself, so there should be 2 references from untracked objects like something in C extensions.

I attempted to reproduce it with some simpler codes, but they will just work fine. Hopefully we can find some logs somewhere to better locate the error.

Hundreds of following warnings are shown when I stop the program, unknown if relevant:
```
[W python_variable.cpp:200] Warning: Deallocating Tensor that still has live PyObject references.  This probably happened because you took out a weak reference to Tensor and didn't call _fix_weakref() after dereferencing it.  Subsequent accesses to this tensor via the PyObject will now fail. (function concrete_decref_fn)
```

### Versions

PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.10.0-16-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.2.152
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 510.39.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] libblas                   3.9.0            12_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            12_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            12_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            12_linux64_mkl    conda-forge
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpy-base                1.21.5           py39hf524024_1
[conda] pytorch                   1.12.0          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.13.0               py39_cu113    pytorch

**Comment by ezyang** [comment]
The most likely explanation is these are the input buffers that accumulate gradients. I wonder if the problem is you are OOM'ing outside of a user function, and then we do not cleanup appropriately. If you can get a gdb trace of when the OOM happens that would help.

**Comment by mutiann** [comment]
`I wonder if the problem is you are OOM'ing outside of a user function, and then we do not cleanup appropriately.`
It seems to be like that...Is there any documentation/tutorial about getting the gdb trace?

**Comment by ezyang** [comment]
run the script with gdb, `catch throw`, and then let it go until oom

**Comment by ezyang** [comment]
Hmm, `torch::autograd::validate_outputs` looks like it should be handled the same way user exception should be handled. Crumbs! I guess the next step is to audit autograd engine.cpp for appropriate cleanup upon exception...

**Comment by mutiann** [comment]
Found something similar here, possibly related: https://discuss.pytorch.org/t/out-of-memory-and-cant-release-gpu-memory/132601

**Comment by albanD** [comment]
From thinking more about this one, what could be happening is that the OOM error interrupts the backward call. And one of the side affect of the backward call is to free up all the buffers as it goes along.
This means that you will return from the backward call without having done that and thus your `loss` variable (or whatever is the variable you call backward on) has a lot more state associated with it than usual: this variable is keeping the autograd graph alive. And now, the autograd graph holds onto a lot more memory than usual.

if your training loop looks like
```python
for inp in ...:
  loss = compute_loss(inp, ...)
  opt.zero_grad()
  loss.backward()
  opt.step()
```

Then the `loss` variable from the previous iteration is still alive until AFTER the new `compute_loss(inp, ...)` is done and the result is stored, thus replacing the old loss.
This means that at this iteration, you will have two sets of autograd state alive at the same time, which is most likely leading to more OOM.

Could you verify in your code if this is not happening? And make sure to clean up all the temporary variables from the forward before checking the gc.get_objects() result.

**Comment by ezyang** [comment]
I'm wondering if we should delete the buffers by default on error then, since if the OOM isn't handled before it gets to the autograd engine, I don't think there is a way to "resume" autograd execution anymore.

**Comment by albanD** [comment]
We could definitely have a cleanup mode. And once any error happens we go through the graph and clean it up.

**Comment by mutiann** [comment]
> 

Thanks for the hint! Yes I didn't clean up the intermediate variables like model outputs and losses during an exception, and after I did that most memory are released. But there is still some unreleased memory that causes OOM later.

**Comment by jobs-git** [comment]
I also encounter this issue as well, I think when backprop OOMs, the process thread for that gets terminated so it does not reach the memory clearing stage, so you will need to do it manually or else you will OOM as you observed. You can use "try catch" so you can clear the RAM after a failed try as @tmm1  showed.

**Comment by mseeger** [comment]
The solution posted by @tmm1 does not work for me. It deallocates too many tensors. In my use case, I'd like to recover from an OOM error during backward computation. And recover means: I'd like to continue training, with reducing the buffer sizes for some parts so the OOM error does not happen the next time again.

If the issue is to deallocate the arrays created as part of the autograd graph, I manage to do that with using https://docs.pytorch.org/tutorials/intermediate/autograd_saved_tensors_hooks_tutorial.html.

One issue is this also cleans up model weights who end up going into pack hooks as well. But these can be filtered out.

This is all quite complex, and I really have to wonder why PyTorch does not properly clean up things when an OOM error is raised.
