### ISSUE TITLE
PrimTorch out_wrapper semantics are not quite right for factory functions

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#82364]
### 🐛 Describe the bug

Steps to reproduce:

```
>>> import torch
>>> torch.arange(2, out=torch.empty(2, device='cuda'))
tensor([0., 1.], device='cuda:0')
>>> import torch._refs
>>> torch._refs.arange(2, out=torch.empty(2, device='cuda'))
<function arange at 0x7fe602c15b80> (2,) {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/raid/ezyang/pytorch-scratch2/torch/_prims_common/wrappers.py", line 225, in _fn
    _safe_copy_out(copy_from=result, copy_to=out, exact_dtype=exact_dtype)  # type: ignore[arg-type]
  File "/raid/ezyang/pytorch-scratch2/torch/_prims_common/wrappers.py", line 154, in _safe_copy_out
    raise RuntimeError(msg)
RuntimeError: Attempting to copy from device cpu to device cuda:0, but cross-device copies are not allowed!
```

cc @ezyang @mruberry @ngimel @soulitzer

### Versions

master

**Comment by ezyang** [comment]
I'm disabling the out registration for now at https://github.com/pytorch/pytorch/pull/82251 pending a proper fix
