### ISSUE TITLE
torch.load map_location cannot handle meta tensor

### ISSUE THREAD

**Issue by kumpera** [pytorch/pytorch#82412]
### 🐛 Describe the bug

It's not possible to `torch.load` a model into the meta tensor using `map_location`.

Here's the repro:

```python
import io
import torch

t = torch.rand(10)
b = io.BytesIO()

torch.save(t, b)
b.seek(0)
torch.load(b, map_location=torch.device("meta"))
```

This fails with the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kumpera/miniconda3/envs/misc/lib/python3.9/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/kumpera/miniconda3/envs/misc/lib/python3.9/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/Users/kumpera/miniconda3/envs/misc/lib/python3.9/site-packages/torch/serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/Users/kumpera/miniconda3/envs/misc/lib/python3.9/site-packages/torch/serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/Users/kumpera/miniconda3/envs/misc/lib/python3.9/site-packages/torch/serialization.py", line 973, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/Users/kumpera/miniconda3/envs/misc/lib/python3.9/site-packages/torch/serialization.py", line 178, in default_restore_location
    raise RuntimeError("don't know how to restore data location of "
RuntimeError: don't know how to restore data location of torch.storage._UntypedStorage (tagged with meta)
```

### Versions

1.12

**Comment by cpuhrsch** [comment]
cc @ezyang - the "module: meta tensors" tag didn't pull people in by default and I don't know who else to tag.

**Comment by ezyang** [comment]
I added some folks to the list
