### ISSUE TITLE
Order of AT_FORALL_SCALAR_TYPES, and it shouldn't

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#8241]
Steps to reproduce:
1. Go to `aten/src/ATen/ScalarType.h` and reorder `AT_FORALL_SCALAR_TYPES`, e.g., by moving half to the beginning or end of the list
2. Build and run `python test/test_torch.py`

Expected result: tests pass

Actual result:

```
======================================================================
ERROR: test_sum_all (test_torch.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/test/test_torch.py", line 1520, in test_sum_all
    check_sum_all(torch.tensor([1, 2, 3, 4, 5]))
  File "/data/users/ezyang/pytorch-tmp/test/test_torch.py", line 1518, in check_sum_all
    self.assertEqual(tensor.sum(), sum(pylist))
RuntimeError: _sum is not implemented for type torch.HalfTensor

======================================================================
ERROR: test_tensor_factory (test_torch.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/test/test_torch.py", line 1996, in test_tensor_factory
    self.assertEqual(res1, expected)
  File "/data/users/ezyang/pytorch-tmp/test/common.py", line 306, in assertEqual
    assertTensorsEqual(x, y)
  File "/data/users/ezyang/pytorch-tmp/test/common.py", line 290, in assertTensorsEqual
    nan_mask = a != a
RuntimeError: s_ne is not implemented for type torch.HalfTensor

======================================================================
FAIL: test_tensor_factory_type_inference (test_torch.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/test/test_torch.py", line 2046, in test_tensor_factory_type_inference
    test_inference(torch.float64)
  File "/data/users/ezyang/pytorch-tmp/test/test_torch.py", line 2031, in test_inference
    self.assertIs(torch.int64, torch.tensor(((5, 3), (3, 5))).dtype)
AssertionError: torch.int64 is not torch.uint8

----------------------------------------------------------------------
```

So, somehow, we are encoding some assumptions about how the enum is laid out; maybe it's something like, integer types are contiguously numbered, and maybe an assumption about the low bound and the high bound. This is a footgun waiting to happen when someone tries to add a new scalar type.

**Comment by gchanan** [comment]
it's in promoteTypes and I ordered it that way to make the implementation simpler.  I guess you could argue we should use an internal one where we are explicit about the order, but IMO these things are tradeoffs that may or may not be worth doing, not "shouldn't".
