### ISSUE TITLE
Dataloader fails with num_workers > 0 and tensors that require_grad

### ISSUE THREAD

**Issue by balbok0** [pytorch/pytorch#82411]
When constructing a Dataloader with `num_workers` non-zero on top of dataset that contains tensors with `requires_grad=True` it will fail when trying to stack batches from different workers.

Example:
```python
import torch
from torch.utils.data import DataLoader, TensorDataset


set_1 = TensorDataset(torch.randn((1000, 10)))
set_2 = TensorDataset(torch.randn((1000, 10), requires_grad=True))

loader_1 = DataLoader(set_1)
loader_2 = DataLoader(set_2)
loader_3 = DataLoader(set_1, num_workers=4)
loader_4 = DataLoader(set_2, num_workers=4)

for _ in loader_1:
    pass
print("Loader 1 ok")


for _ in loader_2:
    pass
print("Loader 2 ok")

for _ in loader_3:
    pass
print("Loader 3 ok")

for _ in loader_4:  # Fails
    pass
print("Loader 4 ok")
```

with error:
```
Traceback (most recent call last):
  File "/home/balbok/Documents/Personal/nba_project/tmp_minimal_example.py", line 26, in <module>
    for _ in loader_4:
  File "/home/balbok/anaconda3/envs/nba_project/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/balbok/anaconda3/envs/nba_project/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/balbok/anaconda3/envs/nba_project/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/balbok/anaconda3/envs/nba_project/lib/python3.10/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/balbok/anaconda3/envs/nba_project/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/balbok/anaconda3/envs/nba_project/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/balbok/anaconda3/envs/nba_project/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 172, in default_collate
    return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
  File "/home/balbok/anaconda3/envs/nba_project/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 172, in <listcomp>
    return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
  File "/home/balbok/anaconda3/envs/nba_project/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 138, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack(): functions with out=... arguments don't support automatic differentiation, but one of the arguments requires grad.
```

### Versions

Version info:
```
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 12.1.0
Clang version: 14.0.6
CMake version: version 3.23.2
Libc version: glibc-2.35

Python version: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.15.55-1-MANJARO-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 SUPER
Nvidia driver version: 515.57
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.4.1
/usr/lib/libcudnn_adv_infer.so.8.4.1
/usr/lib/libcudnn_adv_train.so.8.4.1
/usr/lib/libcudnn_cnn_infer.so.8.4.1
/usr/lib/libcudnn_cnn_train.so.8.4.1
/usr/lib/libcudnn_ops_infer.so.8.4.1
/usr/lib/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] pytorch-lightning==1.6.4
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchmetrics==0.9.1
[pip3] torchvision==0.12.0
[conda] nomkl                     3.0                           0
[conda] numpy                     1.22.4          py310h4ef5377_0    conda-forge
[conda] pytorch-lightning         1.6.4                    pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchmetrics              0.9.1                    pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi
```

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Can I know your use case to have tensor with gradient in the data-loading stage?

I believe this is kind intentional because you don't want to have gradient calculated within the data-processing stage.

**Comment by NivekT** [comment]
I am not sure if we want to support this use case, but if we need to, we can either stop using `out` or have something like:
```python
with torch.no_grad():
    return torch.stack(batch, 0, out=out)
```

**Comment by balbok0** [comment]
I am learning the representations for a set of players.
The most similar thing that PyTorch provides to my use-case is an embedding layer, though I have some additional features.
I can try to switch to the `nn.Embedding` in my use case, though I think in general this limitation can be highlighted somewhere in docs.

**Comment by ejguan** [comment]
Then, why don't you put embedding out of Dataset? This is more proper implementation at least for `DataLoader` + `Dataset`.

**Comment by balbok0** [comment]
Sounds good! Thank you for the tip, and sorry for creating an unnecessary issue!
