### ISSUE TITLE
AoT_autograd + nvfuser + channels_last models failed with SyntaxError

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#82445]
### 🐛 Describe the bug

AoT_autograd + nvfuser + channels_last models failed with SyntaxError after PR https://github.com/pytorch/pytorch/pull/82238

Repro:
TIMM benchmark.py script https://github.com/rwightman/pytorch-image-models/blob/master/benchmark.py
```
python benchmark.py --model resnet18 -b 128 --img-size 224 --bench train --aot-autograd --fuser nvfuser --amp --channels-last
```

Before:
```python
WARNING: Overriding precision to 'amp' since --amp flag set.
Benchmarking in amp precision. NHWC layout. torchscript disabled
Model resnet18 created, param count: 11689512
Running train benchmark on resnet18 for 40 steps w/ input size (3, 224, 224) and batch size 128.
Train [8/40]. 3484.67 samples/sec. 36.732 ms/step.
Train [16/40]. 3487.22 samples/sec. 36.705 ms/step.
Train [24/40]. 3489.17 samples/sec. 36.685 ms/step.
Train [32/40]. 3489.71 samples/sec. 36.679 ms/step.
Train [40/40]. 3489.49 samples/sec. 36.682 ms/step.
Train benchmark of resnet18 done. 3452.12 samples/sec, 36.68 ms/sample
--result
{
    "model": "resnet18",
    "train_samples_per_sec": 3452.12,
    "train_step_time": 36.682,
    "train_batch_size": 128,
    "train_img_size": 224,
    "param_count": 11.69
}
```

After:
```python
WARNING: Overriding precision to 'amp' since --amp flag set.
Benchmarking in amp precision. NHWC layout. torchscript disabled
Model resnet18 created, param count: 11689512
Running train benchmark on resnet18 for 40 steps w/ input size (3, 224, 224) and batch size 128.
Traceback (most recent call last):
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 721, in <module>
    main()
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 705, in main
    results = benchmark(args)
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 637, in benchmark
    run_results = _try_run(
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 584, in _try_run
    results = bench.run()
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 443, in run
    _step()
  File "/workspace/timm-models/pytorch-image-models/benchmark.py", line 416, in _step
    output = self.model(self.example_inputs)
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/pytorch/pytorch/functorch/functorch/_src/aot_autograd.py", line 581, in forward
    return compiled_f(
  File "/opt/pytorch/pytorch/functorch/functorch/_src/aot_autograd.py", line 519, in returned_function
    out = cached_fn(*flat_tensor_args)
  File "/opt/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 93, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/functorch/functorch/_src/aot_autograd.py", line 205, in forward
    fw_module, bw_module = partition_fn(fx_g, joint_inputs)
  File "/opt/pytorch/pytorch/functorch/functorch/_src/partitioners.py", line 378, in min_cut_rematerialization_partition
    return _extract_fwd_bwd_modules(joint_module, saved_values)
  File "/opt/pytorch/pytorch/functorch/functorch/_src/partitioners.py", line 111, in _extract_fwd_bwd_modules
    bwd_module = fx.GraphModule(joint_module, bwd_graph)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 366, in __init__
    self.graph = graph
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1309, in __setattr__
    super().__setattr__(name, value)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 404, in graph
    self.recompile()
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 641, in recompile
    cls.forward = _forward_from_src(self._code, python_code.globals)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 77, in _forward_from_src
    _exec_with_source(src, globals_copy)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 71, in _exec_with_source
    exec(compile(src, key, 'exec'), globals)
  File "<eval_with_key>.4", line 13
    return [Invalid Node, Invalid Node, Invalid Node, _to_copy_default_24, _to_copy_default_23, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
                    ^
SyntaxError: invalid syntax
```

### Versions

d38ffa6a4ceaaca39ad2b750ae381a2cba781996
cuda 11.7

cc @VitalyFedyunin @jamesr66a @ptrblck @ezyang @jjsjann123

**Comment by ngimel** [comment]
cc @chillee, @ezyang

**Comment by xwang233** [comment]
The AMP + contiguous models were mostly unaffected but most AMP + channels_last models failed with this error.

**Comment by ngimel** [comment]
Channels last + AoT were suspect even before (e.g. they produced wrong results without functionalization, cc @chillee)

**Comment by Chillee** [comment]
@xwang233 I talked with @syed-ahmed about this previously. For channels-last I think we need to enable functionalization to get correct results.

```
import functorch.compile.config
functorch.compile.config.use_functionalize = True
```

**Comment by xwang233** [comment]
@Chillee will this be the default functorch behavior or just a temporary workaround?

**Comment by Chillee** [comment]
@xwang233 This will be the default functorch behavior at some point. However, functionalization currently causes some (potential) performance issues that we need a re-inplacing pass for (cc: @bdhirsh ), and I think there are a couple of other bugs with functionalization today (cc: @anijain2305).

**Comment by ezyang** [comment]
functionalization is now on by default
