### ISSUE TITLE
Does torch.utils.checkpoint compatible with torch.cuda.make_graphed_callables?

### ISSUE THREAD

**Issue by Musisoul** [pytorch/pytorch#82465]
### 🐛 Describe the bug

When attempting to use
```
model = torch.cuda.make_graphed_callables(model, (rand_data,))
```
and our model contains checkpoints or sequential checkpoints like this:
```
input_next = torch.utils.checkpoint.checkpoint_sequential(self.layer, segments, input_prev)
```
then we got this error:
```
Traceback (most recent call last):
  File "multitask.py", line 43, in <module>
    main()
  File "multitask.py", line 36, in main
    S.initialize(args)
  File "/mnt/lustre/chendingyu1/multitask-unify-democode/core/solvers/solver_fp16.py", line 63, in initialize
    super().initialize(args)
  File "/mnt/lustre/chendingyu1/multitask-unify-democode/core/solvers/solver.py", line 317, in initialize
    self.create_model()
  File "/mnt/lustre/chendingyu1/multitask-unify-democode/core/solvers/solver_fp16.py", line 109, in create_model
    model = torch.cuda.make_graphed_callables(model, (rand_data,))
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/cuda/graphs.py", line 264, in make_graphed_callables
    allow_unused=False)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/autograd/__init__.py", line 277, in grad
    allow_unused, accumulate_grad=False)  # Calls into the C++ engine to run the backward pass
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 103, in backward
    "Checkpointing is not compatible with .grad() or when an `inputs` parameter"
RuntimeError: Checkpointing is not compatible with .grad() or when an `inputs` parameter is passed to .backward(). Please use .backward() and do not pass its `inputs` argument.
```
If we don't use checkpoints in our model like
```
input_next = self.layer(input_prev)
```
then we didn't get any errors.

Does checkpoint compatible with torch.cuda.make_graphed_callables?

### Versions

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Is CUDA available: True
CUDA runtime version: 9.0.176

Nvidia driver version: 460.32.03

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] spring==0.7.2+cu112.torch1110.mvapich2.nartgpu.develop.805601a8
[pip3] torch==1.11.0+cu113
[pip3] torchvision==0.12.0+cu113
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] spring                    0.7.0+cu112.torch1110.mvapich2.pmi2.nartgpu          pypi_0    pypi
[conda] torch                     1.11.0+cu113             pypi_0    pypi
[conda] torchvision               0.12.0+cu113             pypi_0    pypi

**Comment by ezyang** [comment]
Reentrant checkpointing seems unlikely to work. How about non-reentrant checkpointing?

**Comment by Musisoul** [comment]
> Reentrant checkpointing seems unlikely to work. How about non-reentrant checkpointing?

Okay I'll try it, thanks.

**Comment by Musisoul** [comment]
> Reentrant checkpointing seems unlikely to work. How about non-reentrant checkpointing?

Unfortunately, I tried to pass `use_reentrant=False` in checkpoint function, and I got the same result as before:

```RuntimeError: Checkpointing is not compatible with .grad() or when an `inputs` parameter is passed to .backward(). Please use .backward() and do not pass its `inputs` argument.```

**Comment by Musisoul** [comment]
> Reentrant checkpointing seems unlikely to work. How about non-reentrant checkpointing?
Update:
Using resnet50 in PyTorch with `checkpoint(use_reentrant=False)`, I got this error:
```
Traceback (most recent call last):
  File "test_resnet.py", line 11, in <module>
    model = torch.cuda.make_graphed_callables(model, (rand_data,))
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/cuda/graphs.py", line 279, in make_graphed_callables
    outputs = func(*args)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/lustre/chendingyu1/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/mnt/lustre/chendingyu1/resnet.py", line 273, in _forward_impl
    x = checkpoint(self.layer1, x, use_reentrant=False)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 240, in checkpoint
    *args
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 333, in _checkpoint_without_reentrant
    fwd_gpu_devices, fwd_gpu_states = get_device_states(*args)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 44, in get_device_states
    fwd_gpu_states.append(torch.cuda.get_rng_state())
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/cuda/random.py", line 31, in get_rng_state
    return default_generator.get_state()
RuntimeError: Cannot call CUDAGeneratorImpl::current_seed during CUDA graph capture. If you need this call to be captured, please file an issue. Current cudaStreamCaptureStatus: cudaStreamCaptureStatusActive
```
If I use `use_reentrant=True`, I got the same error as before.

**Comment by ezyang** [comment]
That's better. Try also passing `preserve_rng_state=False` but note that your dropout will behave differently when recomputing activations.

**Comment by Musisoul** [comment]
> That's better. Try also passing `preserve_rng_state=False` but note that your dropout will behave differently when recomputing activations.

I got this error
```
Traceback (most recent call last):
  File "test_resnet.py", line 11, in <module>
    model = torch.cuda.make_graphed_callables(model, (rand_data,))
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/cuda/graphs.py", line 258, in make_graphed_callables
    outputs = func(*args)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/lustre/chendingyu1/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/mnt/lustre/chendingyu1/resnet.py", line 273, in _forward_impl
    x = checkpoint(self.layer1, x, use_reentrant=False, preserve_rng_state=False)
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 240, in checkpoint
    *args
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.5/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 374, in _checkpoint_without_reentrant
    if torch.cuda._initialized and not had_cuda_in_fwd:
UnboundLocalError: local variable 'had_cuda_in_fwd' referenced before assignment
```
which located at checkpoint.py#372-380:
```
    with torch.autograd.graph.saved_tensors_hooks(pack, unpack):
        output = function(*args)
        if torch.cuda._initialized and not had_cuda_in_fwd:
            # Cuda was not initialized before running the forward, so we didn't
            # stash the CUDA state.
            raise RuntimeError(
                "PyTorch's CUDA state was initialized in the forward pass "
                "of a Checkpoint, which is not allowed. Please open an issue "
                "if you need this feature.")
```

**Comment by ezyang** [comment]
lol. So that's a straight up bug. Can you edit the file to delete this test or something haha
