### ISSUE TITLE
make_fx is broken for all tracing_mode

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#82547]
### 🐛 Describe the bug

Running the script from https://gist.github.com/zou3519/3869d460f8bcb12799967e08a5998d9c raises an error on the `make_fx` call for `symbolic` and `real` tracing modes and segfaults for `tracing_mode="fake"`.

`tracing_mode="real"` :
```py
File ~/dev/pytorch/master/torch/fx/experimental/proxy_tensor.py:134, in proxy_call(func_overload, args, kwargs)
    132     if t.constant is not None:
    133         with maybe_disable_fake_tensor_mode():
--> 134             return t.constant.item()
    135     raise RuntimeError("It appears that you're trying to get value out of a tracing tensor - erroring out! "
    136                        "It's likely that this is caused by data-dependent control flow or similar."
    137                        "Try torch.fx.experimental.proxy_tensor.enable_strict(False) to disable this check")
    139 def unwrap_proxy(e):

AttributeError: 'list' object has no attribute 'item'
```
using `tracing_mode="symbolic"` raises another error:
```py
File ~/dev/pytorch/master/functorch/functorch/_src/vmap.py:484, in _flat_vmap(func, batch_size, flat_in_dims, flat_args, args_spec, out_dims, randomness, **kwargs)
    483 def _flat_vmap(func, batch_size, flat_in_dims, flat_args, args_spec, out_dims, randomness, **kwargs):
--> 484     vmap_level = _vmap_increment_nesting(batch_size, randomness)
    485     try:
    486         batched_inputs = _create_batched_inputs(flat_in_dims, flat_args, vmap_level, args_spec)

TypeError: _vmap_increment_nesting(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int, arg1: str) -> int

Invoked with: <torch.SymIntNode object at 0x7f6275eec3f0>, 'error'
```
and `tracing_mode="fake"` segfaults.

### Versions

Latest master branch.

**Comment by ezyang** [comment]
I'll look into the constant related crash

**Comment by ezyang** [comment]
cc @eellison on fake tensor segfault

Partial backtrace:

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffd52618b6 in c10::SafePyObject::ptr (this=0x0, interpreter=0x555557700750) at /data/users/ezyang/pytorch-tmp/c10/core/SafePyObject.cpp:7
7         TORCH_INTERNAL_ASSERT(interpreter == pyinterpreter_);
(gdb) bt 12
#0  0x00007fffd52618b6 in c10::SafePyObject::ptr (this=0x0, interpreter=0x555557700750)
    at /data/users/ezyang/pytorch-tmp/c10/core/SafePyObject.cpp:7
#1  0x00007fffe236668d in torch::handle_torch_function_no_python_arg_parser (overloaded_args=..., args=0x7fff7ac35d90, 
    kwargs=0x7fff7b6feac0, func_name=0x555555ab31d6 "t", torch_api_function=0x7fff7b0e93a0, 
    module_name=0x7fffffff55e0 "torch.ops.aten", torch_function_name=torch::TorchFunctionName::TorchDispatch)
    at /data/users/ezyang/pytorch-tmp/torch/csrc/utils/python_arg_parser.cpp:389
#2  0x00007fffe1daf9c9 in (anonymous namespace)::concrete_dispatch_fn (op=..., stack=0x7fffffff5d40)
    at /data/users/ezyang/pytorch-tmp/torch/csrc/autograd/python_variable.cpp:2189
#3  0x00007fffd7320f6d in c10::impl::PyInterpreter::dispatch (this=0x555557700750, op=..., stack=0x7fffffff5d40)
    at /data/users/ezyang/pytorch-tmp/c10/core/impl/PyInterpreter.h:205
#4  0x00007fffd7320047 in (anonymous namespace)::pythonFallback (op=..., stack=0x7fffffff5d40)
    at /data/users/ezyang/pytorch-tmp/aten/src/ATen/core/PythonFallbackKernel.cpp:56
#5  0x00007fffd7320da9 in c10::BoxedKernel::make_boxed_function<(anonymous namespace)::pythonFallback> (opHandle=..., 
    stack=0x7fffffff5d40) at /data/users/ezyang/pytorch-tmp/aten/src/ATen/core/boxing/BoxedKernel_impl.h:19
#6  0x00007fffe1f19b93 in c10::BoxedKernel::callBoxed (this=0x555555ab38e8, opHandle=..., dispatchKeySet=..., 
    stack=0x7fffffff5d40) at /data/users/ezyang/pytorch-tmp/aten/src/ATen/core/boxing/BoxedKernel_impl.h:41
#7  0x00007fffd7189a28 in c10::KernelFunction::callBoxed (this=0x555555ab38e8, opHandle=..., dispatchKeySet=..., 
    stack=0x7fffffff5d40) at /data/users/ezyang/pytorch-tmp/aten/src/ATen/core/boxing/KernelFunction_impl.h:36
#8  0x00007fffd718a8d2 in c10::Dispatcher::callBoxed (
    this=0x7fffe0f3b660 <c10::Dispatcher::realSingleton()::_singleton>, op=..., stack=0x7fffffff5d40)
    at /data/users/ezyang/pytorch-tmp/aten/src/ATen/core/dispatch/Dispatcher.h:620
#9  0x00007fffd718a508 in c10::OperatorHandle::callBoxed (this=0x555558f24af0, stack=0x7fffffff5d40)
    at /data/users/ezyang/pytorch-tmp/aten/src/ATen/core/dispatch/Dispatcher.h:372
#10 0x00007fffdbe3512d in c10::OperatorHandle::callBoxed (this=0x555558f24af0, stack=...)
    at /data/users/ezyang/pytorch-tmp/aten/src/ATen/core/dispatch/Dispatcher.h:376
#11 0x00007fffdbe33e3d in torch::jit::(anonymous namespace)::<lambda(torch::jit::Stack&)>::operator()(torch::jit::Stack &) const (__closure=0x555558f24af0, stack=...)
    at /data/users/ezyang/pytorch-tmp/torch/csrc/jit/runtime/register_c10_ops.cpp:15
#12 0x00007fffdbe34b7e in std::_Function_handler<void(std::vector<c10::IValue, std::allocator<c10::IValue> >&), torch::jit::(anonymous namespace)::createOperatorFromC10(const c10::OperatorHandle&)::<lambda(torch::jit::Stack&)> >::_M_invoke(const std::_Any_data &, std::vector<c10::IValue, std::allocator<c10::IValue> > &) (__functor=..., __args#0=...)
    at /usr/include/c++/8/bits/std_function.h:297
#13 0x00007fffe1e3e7b3 in std::function<void (std::vector<c10::IValue, std::allocator<c10::IValue> >&)>::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >&) const (this=0x7fffffff5da0, __args#0=...)
    at /usr/include/c++/8/bits/std_function.h:687
#14 0x00007fffe1e33c9d in torch::jit::Operation::operator() (this=0x7fffffff5da0, stack=...)
    at /data/users/ezyang/pytorch-tmp/aten/src/ATen/core/stack.h:41
#15 0x00007fffe1e39380 in torch::jit::invokeOperatorFromPython (operations=..., args=..., kwargs=...)
    at /data/users/ezyang/pytorch-tmp/torch/csrc/jit/python/pybind_utils.h:1199
#16 0x00007fffe1e39b5a in torch::jit::_get_operation_for_overload_or_packet (operations=..., symbol=..., args=..., 
    kwargs=..., is_overload=true) at /data/users/ezyang/pytorch-tmp/torch/csrc/jit/python/pybind_utils.h:1263
```

**Comment by ezyang** [comment]
can turn it into an internal assert error by making the assert a little more robust

```
diff --git a/torch/csrc/utils/python_arg_parser.cpp b/torch/csrc/utils/python_arg_parser.cpp
index 9ac65068e35..c532590607d 100644
--- a/torch/csrc/utils/python_arg_parser.cpp
+++ b/torch/csrc/utils/python_arg_parser.cpp
@@ -386,7 +386,7 @@ auto handle_torch_function_no_python_arg_parser(
       // in the inner context, the mode could be invalid here.  So just be
       // a bit safe, it doesn't cost us anything since this is error reporting
       const auto& maybe_mode = at::impl::PythonTorchFunctionTLS::get_mode();
-      TORCH_INTERNAL_ASSERT(mode_obj == maybe_mode->ptr(getPyInterpreter()));
+      TORCH_INTERNAL_ASSERT(maybe_mode && mode_obj == maybe_mode->ptr(getPyInterpreter()));
       ss << " nor was it found on the currently active mode "
          << py::repr(mode_obj);
     }
```

**Comment by ezyang** [comment]
I figured it out, patch coming.

**Comment by IvanYashchuk** [comment]
What parts of the problem were fixed?

**Comment by ezyang** [comment]
when I run the repro script on a more recent master I get

```
(/home/ezyang/local/pytorch-tmp-env) [ezyang@devgpu001.pnb3 ~/local/pytorch-tmp (9b50611e)]$ python smaller_repro.py 
quantity using old linear
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/smaller_repro.py", line 74, in <module>
    gm = make_fx(f)(x, False, True)
  File "/data/users/ezyang/pytorch-tmp/torch/fx/experimental/proxy_tensor.py", line 622, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/data/users/ezyang/pytorch-tmp/torch/fx/experimental/proxy_tensor.py", line 392, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/data/users/ezyang/pytorch-tmp/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/data/users/ezyang/pytorch-tmp/torch/fx/experimental/proxy_tensor.py", line 406, in wrapped
    out = f(*tensors)
  File "/data/users/ezyang/pytorch-tmp/smaller_repro.py", line 49, in f
    return vmap(jacrev(predict), (0, None, None))(x, nvtx, use_old_linear)
  File "/data/users/ezyang/pytorch-tmp/functorch/functorch/_src/vmap.py", line 349, in wrapped
    return _flat_vmap(
  File "/data/users/ezyang/pytorch-tmp/functorch/functorch/_src/vmap.py", line 475, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
  File "/data/users/ezyang/pytorch-tmp/functorch/functorch/_src/eager_transforms.py", line 452, in wrapper_fn
    flat_basis = _construct_standard_basis_for(flat_output, flat_output_numels)
  File "/data/users/ezyang/pytorch-tmp/functorch/functorch/_src/eager_transforms.py", line 557, in _construct_standard_basis_for
    chunk.diagonal(diag_start_idx).fill_(1)
  File "/data/users/ezyang/pytorch-tmp/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/data/users/ezyang/pytorch-tmp/torch/fx/experimental/proxy_tensor.py", line 425, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/data/users/ezyang/pytorch-tmp/torch/fx/experimental/proxy_tensor.py", line 444, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "/data/users/ezyang/pytorch-tmp/torch/fx/experimental/proxy_tensor.py", line 234, in proxy_call
    raise RuntimeError(
RuntimeError: It appears that you're trying to get value out of a tracing tensor - erroring out! It's likely that this is caused by data-dependent control flow or similar.
```

**Comment by ngimel** [comment]
Closing, reopen if the problem still needs fixing
