### ISSUE TITLE
Creating iterator from Dataset raises StopIteration instead of IndexError in __getitem__ method

### ISSUE THREAD

**Issue by fortminors** [pytorch/pytorch#82732]
### 🐛 Describe the bug

I usually use a Dataloader to extract items from Dataset, but this time I was checking something out and did `iter(some_dataset)`. I found out that if I produce `IndexError` inside the `__getitem__` method, then `StopIteration` is raised instead of just propagating the original exception. I tried some other exceptions, they were caught and displayed fine. I also tried the same thing with a Dataloader, it also handles everything properly.

Sample code:

```
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):

    def __init__(self):
        self.l = [1,2,3,4,5]
                    
    def __len__(self):
        return len(self.l)

    def __getitem__(self, ix):
        l_fake = []

        elem = l_fake[ix]

        return elem

dataset = MyDataset()

loader = DataLoader(dataset)

dataset_iter = iter(dataset)

print("Start dataset_iter")

for x in dataset_iter:
    print(x)

print("END dataset_iter")

print("Start loader")

for x in loader:
    print(x)

print("END loader")
```

I expected that during `for x in dataset_iter:`, the `IndexError` will be raised, but this is not the case, the loop exits due to `StopIteration`.

Full output:

```
Start dataset_iter
END dataset_iter
Start loader
Traceback (most recent call last):
  File "c:/path/test.py", line 33, in <module>
    for x in loader:
  File "miniconda3\envs\env\lib\site-packages\torch\utils\data\dataloader.py", line 652, in __next__
    data = self._next_data()
  File "miniconda3\envs\env\lib\site-packages\torch\utils\data\dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "miniconda3\envs\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "miniconda3\envs\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:/path/test.py", line 14, in __getitem__
    elem = l_fake[ix]
IndexError: list index out of range
```

### Versions

```
Collecting environment information...
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home Single Language
GCC version: (MinGW.org GCC-6.3.0-1) 6.3.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: 11.4.152
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060 with Max-Q Design
Nvidia driver version: 516.59
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.12.0+cu116
[pip3] torchaudio==0.12.0+cu116
[pip3] torchvision==0.13.0+cu116
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] torch                     1.12.0+cu116             pypi_0    pypi
[conda] torchaudio                0.12.0+cu116             pypi_0    pypi
[conda] torchvision               0.13.0+cu116             pypi_0    pypi
```

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by NivekT** [comment]
> I expected that during `for x in dataset_iter`:, the `IndexError` will be raised, but this is not the case, the loop exits due to `StopIteration`.

I think the behavior that you are describing is not unique to `Dataset`, but it is how Python works.
```python
class Foo:

    def __init__(self):
        self.data = [0, 1]

    def __getitem__(self, index):
        return self.data[index]

f = Foo()
for i in f:
    print(i)  # 0, 1, no exception is raised
```
Essentially, when you create an iterator from an object only with `__getitem__`, Python will catch `IndexError` and raise `StopIteration`.

The reason why an error is raised in your second loop with `DataLoader` is that - there is a mismatch between the length (= 5) and the actual number of elements. If you change `self.l` to `[]`, the iteration will exit without issue.
