### ISSUE TITLE
build instruction is haphazard missing information unclear, build does not work

### ISSUE THREAD

**Issue by gggh000** [pytorch/pytorch#82802]
### 🐛 Describe the bug

STARTED FROM https://pytorch.org/get-started/locally/ --> this has building from source link but ironically it link brings to "windows-from-source" i am not sure what it means, whoever has brought this URL must be some issue with English, nevertheless i decided to go there:
https://pytorch.org/get-started/locally/#windows-from-source
This page does not have a lot and then points to another one:
https://github.com/pytorch/pytorch#from-source

at this point, I am unclear why i have to go through 3 different pages to get the instruction for building:

This main page appears to be main instructions for building pytoch but RIDDLED with errors, haphazardly put information containing several different ways of building but ALL OF THEM DOES NOT work.

https://github.com/pytorch/pytorch#from-source

after satisfying all requirements including anaconda, upgraded python and bunch of libraries, some of them were specified in the page and some not (latter I had to find throuhg gruelling hours of struggle), build still fails

Anaconda3-2021.11-Linux-x86_64.sh  (installed this anaconda)
Python 3.9.10

Following steps ocurrs OK for radeon MI100:
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
# if you are updating an existing checkout
git submodule sync
git submodule update --init --recursive --jobs 0
python tools/amd_build/build_amd.py

but this following never works:

export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
python setup.py install

There is error about makefile missing.
POOR DOCUMENTATION!!

Decided to go manual by "cd pytorch ; mkdir build ; cd build ; cmake .. ; make -j16" it goes for about 88% and fails.

Try these steps on freshly installed Centos 8 Stream and i guaranteed you will never be able to build it with what is in there!

I just dont know how even basic build steps fail fail fail. 

### Versions

release/1.10

**Comment by gggh000** [comment]
manual way: partial log before build collapses (be aware that it is not only the way build fails, it seems to be failng in all sorts of different ways when I repeat:


In file included from /root/bg/git/pyt/pytorch/c10/hip/HIPFunctions.h:12,

cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-macro-redefined’
cc1plus: warning: unrecognized command line option ‘-Wno-implicit-int-float-conversion’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-command-line-argument’
cc1plus: warning: unrecognized command line option ‘-Wno-exceptions’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-macro-redefined’
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-implicit-int-float-conversion’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-command-line-argument’
cc1plus: warning: unrecognized command line option ‘-Wno-exceptions’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-macro-redefined’
[100%] Linking CXX shared library ../../lib/libtorch_python.so
make[3]: Leaving directory '/root/bg/git/pyt/pytorch/build'
[100%] Built target torch_python
make[2]: Leaving directory '/root/bg/git/pyt/pytorch/build'
make[1]: *** [Makefile:144: all] Error 2
make[1]: Leaving directory '/root/bg/git/pyt/pytorch/build'
make: *** [Makefile:6: all] Error 2
exit the shell and issue 1. conda activate 2. python setup.py
python: can't open file '/root/bg/git/pyt/setup.py': [Errno 2] No such file or directory

[END] 8/3/2022 10:08:02 PM

**Comment by gggh000** [comment]
python setup.py install fails immediately:

Building wheel torch-1.10.0a0+git71f889c
Traceback (most recent call last):
  File "/root/gg/git/fba/misc/pytorch/setup.py", line 309, in <module>
    cmake = CMake()
  File "/root/gg/git/fba/misc/pytorch/tools/setup_helpers/cmake.py", line 102, in __init__
    self._cmake_command = CMake._get_cmake_command()
  File "/root/gg/git/fba/misc/pytorch/tools/setup_helpers/cmake.py", line 123, in _get_cmake_command
    if cmake3 is not None and CMake._get_version(cmake3) >= distutils.version.LooseVersion("3.10.0"):
  File "/root/gg/git/fba/misc/pytorch/tools/setup_helpers/cmake.py", line 137, in _get_version
    return distutils.version.LooseVersion(line.strip().split(' ')[2])
AttributeError: module 'distutils' has no attribute 'version'

**Comment by dagitses** [comment]
Reading through this still, but the "build PyTorch from source" links in https://pytorch.org/get-started/locally/ all point to #from-source, not #windows-from-source. Can you double check this?

**Comment by dagitses** [comment]
And to clarify, it's the AMD build instructions you're having difficulty with?

**Comment by jithunnair-amd** [comment]
Looking into issues with following instructions on https://github.com/pytorch/pytorch#from-source on ROCm.

@gggh000 Regarding the #windows-from-source, that's because the chooser is set to Windows OS by default. If you were to select Linux OS, the sections below update and the links in the left sidebar are updated accordingly to https://pytorch.org/get-started/locally/#linux-from-source.

In any case, they all point to https://github.com/pytorch/pytorch#from-source eventually, so we'll look into the updates needed there for ROCm.
