### ISSUE TITLE
Lacking utils.so when building 

### ISSUE THREAD

**Issue by henrydylan** [pytorch/pytorch#82807]
### 🐛 Describe the bug

The bug emerges when I try to finetune a pretrain LM called EVA, the repository can be found in this link: https://github.com/thu-coai/EVA. However, this seems to be a Torch issue. To run the script, enter the `/EVA` directory and type the following command:

```
bash src/scripts/eva_finetune.sh
```

Then, when loading checkpoint parameters, the following error occured:

Traceback (most recent call last):
  File "/mnt/clam/**/EVA/src/eva_finetune.py", line 506, in <module>
    main()
  File "/mnt/**/**/EVA/src/eva_finetune.py", line 486, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args, config, ds_config, args.do_train)
  File "/mnt/**/**/EVA/src/eva_finetune.py", line 146, in setup_model_and_optimizer
    config_params=ds_config
  File "/home/**/.conda/envs/EVA/lib/python3.6/site-packages/deepspeed/__init__.py", line 119, in initialize
    config_params=config_params)
  File "/home/**/.conda/envs/EVA/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 198, in __init__
    util_ops = UtilsBuilder().load()
  File "/home/**/.conda/envs/EVA/lib/python3.6/site-packages/deepspeed/ops/op_builder/builder.py", line 176, in load
    return self.jit_load(verbose)
  File "/home/**/.conda/envs/EVA/lib/python3.6/site-packages/deepspeed/ops/op_builder/builder.py", line 212, in jit_load
    verbose=verbose)
  File "/home/**/.conda/envs/EVA/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "/home/**/.conda/envs/EVA/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1362, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/**/.conda/envs/EVA/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1752, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/**/.cache/torch_extensions/py36_cu113/utils/utils.so: cannot open shared object file: No such file or directory

I tried to reinstall torch, but this doesn't work. 

### Versions

PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 21.04 (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-49-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090
GPU 2: GeForce RTX 3090
GPU 3: GeForce RTX 3090
GPU 4: GeForce RTX 3090
GPU 5: GeForce RTX 3090
GPU 6: GeForce RTX 3090
GPU 7: GeForce RTX 3090

Nvidia driver version: 460.91.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-ignite==0.2.1
[pip3] torch==1.10.2+cu113
[pip3] torchaudio==0.10.2+cu113
[pip3] torchvision==0.11.3+cu113
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] pytorch-ignite            0.2.1                    pypi_0    pypi
[conda] torch                     1.10.2+cu113             pypi_0    pypi
[conda] torchaudio                0.10.2+cu113             pypi_0    pypi
[conda] torchvision               0.11.3+cu113             pypi_0    pypi

**Comment by dagitses** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/. This looks more like a question about how your local environment setup. If it turns out that there is indeed a bug, please file a new issue.
