### ISSUE TITLE
ReduceLROnPlateau when using chained schedulers does not work

### ISSUE THREAD

**Issue by Alex7Li** [pytorch/pytorch#82859]
EDIT: User error

### 🐛 Describe the bug

When I run the reducelronplateau scheduler with a 2 parameter groups optimizer, it seems to change the lr in an incorrect way (in fact I even noticed the lr increasing at one point though this is not in the example). In particular, here is an example where it is incorrect with 2 schedulers (and the behavior is correct with 1 schedulers). I am measuring the lr with opt.param_groups[0]["lr"], is that not a reliable method, or is this a bug?

```python
import math
import torch

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = torch.nn.Conv2d(1,2,3)
        self.conv2 = torch.nn.Conv2d(1,2,4)
        self.new_parameters = self.conv1.parameters()
        self.pretrained_parameters = self.conv2.parameters()

def test_plateau_alone():
    m = Model()
    opt = torch.optim.SGD([
        {"params":m.new_parameters, "lr":1.0},
        {"params":m.pretrained_parameters, 'lr':1.0}
        ])
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(opt,
        factor=.1, patience=0, verbose=True, mode='min')
    opt.step(); scheduler.step(1);
    assert math.isclose(opt.param_groups[0]["lr"], 1.0)
    opt.step(); scheduler.step(1);
    assert math.isclose(opt.param_groups[0]["lr"], 0.1)
    print("This is fine")

def test_plateau_with_friend():
    m = Model()
    opt = torch.optim.SGD([
        {"params":m.new_parameters, "lr":1.0},
        {"params":m.pretrained_parameters, 'lr':1.0}
        ])
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(opt,
        factor=.1, patience=0, verbose=True, mode='min')
    scheduler2 = torch.optim.lr_scheduler.LambdaLR(opt, [lambda _: 1, lambda _: 1])
    opt.step(); scheduler.step(1); scheduler2.step()
    assert math.isclose(opt.param_groups[0]["lr"], 1.0)
    opt.step(); scheduler.step(1); scheduler2.step()
    print("Got lr: " + str(opt.param_groups[0]["lr"]))
    assert math.isclose(opt.param_groups[0]["lr"], 0.1)

print(f"TORCH VERSION: {torch.__version__}")
test_plateau_alone()
test_plateau_with_friend()
```

Output
```
(cvml) [alex.li@stc01spplogin001 utils]$ python pytorch_bug.py 
TORCH VERSION: 1.12.0
Epoch 00002: reducing learning rate of group 0 to 1.0000e-01.
Epoch 00002: reducing learning rate of group 1 to 1.0000e-01.
This is fine
Epoch 00002: reducing learning rate of group 0 to 1.0000e-01.
Epoch 00002: reducing learning rate of group 1 to 1.0000e-01.
Got lr: 1.0
Traceback (most recent call last):
  File "pytorch_bug.py", line 43, in <module>
    test_plateau_with_friend()
  File "pytorch_bug.py", line 39, in test_plateau_with_friend
    assert math.isclose(opt.param_groups[0]["lr"], 0.1)
AssertionError
```

### Versions

```
(cvml) [alex.li@stc01spplogin001 europa]$ wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
--2022-08-04 17:32:00--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16906 (17K) [text/plain]
Saving to: ‘collect_env.py.1’

100%[========================================================================================================================================================>] 16,906      --.-K/s   in 0s      

2022-08-04 17:32:00 (159 MB/s) - ‘collect_env.py.1’ saved [16906/16906]

(cvml) [alex.li@stc01spplogin001 europa]$ 
(cvml) [alex.li@stc01spplogin001 europa]$ python collect_env.py

Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:53:36)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.62.1.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.0
[pip3] pytorch-lightning==1.5.10
[pip3] torch==1.12.0
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.12.0
[pip3] torchmetrics==0.9.2
[pip3] torchvision==0.13.0+cu113
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.6.0              hecad31d_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.21.0                   pypi_0    pypi
[conda] pytorch                   1.12.0          py3.8_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-lightning         1.5.10                   pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.8.0+cu111              pypi_0    pypi
[conda] torchaudio                0.12.0               py38_cu116    pytorch
[conda] torchmetrics              0.9.2                    pypi_0    pypi
[conda] torchvision               0.13.0+cu113             pypi_0    pypi
```

cc @vincentqb @jbschlosser @albanD

**Comment by Alex7Li** [comment]
Sorry, this is my mistake. It is because the LambdaLR will set things as a function of the initial LR rather than the current LR, so when you use a chained scheduler, we simply ignore the scheduler that is not lambdaLR. 
I think this is the same grievance as described in #78917
