### ISSUE TITLE
"RuntimeError: Cannot insert a Tensor..." happened when exporting onnx

### ISSUE THREAD

**Issue by Jamesika** [pytorch/pytorch#82945]
### 🐛 Describe the bug

```python
# Python Code
import torch
import torch.nn as nn

#############################################
# Define 
#############################################

# Custom BI-LSTM, because unity barracuda dont support "bidirectional = True"
class BILSTM():
    def __init__(self, inputSize, hiddenSize, numLayers):
        self.biLayer1 = nn.LSTM(input_size=inputSize,hidden_size=hiddenSize, num_layers=numLayers, batch_first=True, dropout=0.5).cuda()
        self.biLayer2 = nn.LSTM(input_size=inputSize,hidden_size=hiddenSize, num_layers=numLayers, batch_first=True, dropout=0.5).cuda()
 
    def forward(self, x):
        out1, (hidden1, _) = self.biLayer1(x)
        out2, (hidden2, _) = self.biLayer2(torch.flip(x, dims=[1]))
        out2 = torch.flip(out2,dims=[1])
        hidden = torch.cat([hidden1, hidden2], dim = 0)
        return (out1, out2), (hidden, 0)

class Rnn(nn.Module):
    def __init__(self, inputSize, hiddenSize, numLayers):
        super(Rnn, self).__init__()
        self.lstm = BILSTM(inputSize, hiddenSize, numLayers)

    def forward(self, x):
        out, (h_n, c_n) = self.lstm.forward(x)
        return out

net = Rnn(128, 128, 2)
net = net.cuda()

#############################################
# Export 
#############################################

x = torch.randn(1, 233, 128).cuda()
net.eval()
with torch.no_grad(): 
    torch.onnx.export( 
        net, 
        x, 
        "test.onnx", 
        opset_version=11, 
        input_names=['input'], 
        output_names=['output'])
```

```
# Error Message
Traceback (most recent call last):
  File "c:\Users\James\Jamesika\PythonProject\LearnPython\GenerateAudioData\TestExport.py", line 40, in <module>
    torch.onnx.export(
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\onnx\__init__.py", line 350, in export
    return utils.export(
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\onnx\utils.py", line 163, in export
    _export(
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\onnx\utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\onnx\utils.py", line 727, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\onnx\utils.py", line 602, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\onnx\utils.py", line 517, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\jit\_trace.py", line 1175, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\nn\modules\module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "c:\Users\James\Jamesika\PythonProject\LearnPython\GenerateAudioData\TestExport.py", line 27, in forward
    out, (h_n, c_n) = self.lstm.forward(x)
  File "c:\Users\James\Jamesika\PythonProject\LearnPython\GenerateAudioData\TestExport.py", line 15, in forward
    out1, (hidden1, _) = self.biLayer1(x)
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\nn\modules\module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\James\anaconda3\envs\Torch\lib\site-packages\torch\nn\modules\rnn.py", line 769, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home China
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060
Nvidia driver version: 516.59
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl    https://repo.anaconda.com/pkgs/main
[conda] mkl                       2021.4.0           haa95532_640    https://repo.anaconda.com/pkgs/main
[conda] mkl-service               2.4.0            py39h2bbff1b_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_fft                   1.3.1            py39h277e83a_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_random                1.2.2            py39hf11a4ad_0    https://repo.anaconda.com/pkgs/main
[conda] numpy                     1.21.5           py39h7a0a035_1    https://repo.anaconda.com/pkgs/main
[conda] numpy-base                1.21.5           py39hca35cd5_1    https://repo.anaconda.com/pkgs/main
[conda] numpydoc                  1.2                pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main

**Comment by Jamesika** [comment]
The error message doesn't help much...

I try to merge two class into one class, then this problem is solved. 
```python
class Rnn(nn.Module):
    def __init__(self, inputSize, hiddenSize, numLayers):
        super(Rnn, self).__init__()
        self.InitBILSTM(inputSize, hiddenSize, numLayers)

    def InitBILSTM(self, inputSize, hiddenSize, numLayers):
        self.biLayer1 = nn.LSTM(input_size=inputSize,hidden_size=hiddenSize, num_layers=numLayers, batch_first=True, dropout=0.5).cuda()
        self.biLayer2 = nn.LSTM(input_size=inputSize,hidden_size=hiddenSize, num_layers=numLayers, batch_first=True, dropout=0.5).cuda()

    def BILSTMForward(self, x):
        out1, (hidden1, _) = self.biLayer1(x)
        out2, (hidden2, _) = self.biLayer2(torch.flip(x, dims=[1]))
        out2 = torch.flip(out2,dims=[1])
        hidden = torch.cat([hidden1, hidden2], dim = 0)
        return (out1, out2), (hidden, 0)

    def forward(self, x):
        out, (h_n, c_n) = self.BILSTMForward(x)
        return out
```

**Comment by justinchuby** [comment]
It's likely that some tensors were input to the lstm, which should have been scalar values. Were you able to run (1) directly input the tensor to the model and (2) call torch.jit.trace on the model without errors?

**Comment by Jamesika** [comment]
I finally solve it by making the first class `BILSTM` derived from `nn.Module`. 😁😁😁
