### ISSUE TITLE
[JIT] Scripting modules fails for modules that contain nested NamedTuples

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#83045]
### 🐛 Describe the bug

When scripting a module that contains a nested NamedTuple instance variable, scripting fails.

Repro:
```python
import torch

from typing import NamedTuple, List

class AA(NamedTuple):
    a: torch.Tensor

class BB(NamedTuple):
    a: AA

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.x = BB(AA(torch.rand(2, 2)))

    def forward(self, input: BB) -> torch.Tensor:
        return self.x.a.a

torch.jit.script(MyModule())

'''
Traceback (most recent call last):
  File "/data/users/dberard/scripts/oncall/jackie.py", line 19, in <module>
    torch.jit.script(MyModule())
  File "/data/users/dberard/pytorch/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/data/users/dberard/pytorch/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/data/users/dberard/pytorch/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/data/users/dberard/pytorch/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
'Tuple[Tuple[Tensor]]' object has no attribute or method 'a'.:
  File "/path/to/repro.py", line 17
    def forward(self, input: BB) -> torch.Tensor:
        return self.x.a.a
               ~~~~~~~~ <--- HERE
'''
```

### Versions

master branch, `e3dd4242657232d4b404465f2df848050cd7f088`

**Comment by davidberard98** [comment]
**Workaround**:

By explicitly annotating the type of the nested NamedTuple, the model can be scripted.

```python
import torch

from typing import NamedTuple, List

class AA(NamedTuple):
    a: torch.Tensor

class BB(NamedTuple):
    a: AA

class MyModule(torch.nn.Module):
    x: BB  # This line fixes the issue

    def __init__(self):
        super().__init__()
        self.x = BB(AA(torch.rand(2, 2)))

    def forward(self, input: BB) -> torch.Tensor:
        return self.x.a.a

torch.jit.script(MyModule())
```

**Comment by davidberard98** [comment]
cc @jackiexu1992

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
