### ISSUE TITLE
FSDP namedtuple support has issues

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#83053]
### 🐛 Describe the bug

It seems that if we have namedtuple output from an FSDP wrapped unit, we can run into an issue where one of the elements of the namedtuple changes type to a generator. The following reproduces the issue:

```
import torch
import torch.distributed as dist
from collections import namedtuple

from torch.distributed.fsdp import FullyShardedDataParallel
from torch.distributed.fsdp import wrap
import torch.nn as nn
import os

dist.init_process_group(backend="nccl", world_size=1, rank=0)
print("init")

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = nn.Linear(1,1)

    def forward(self, x):
        return x

class Wrapper(nn.Module):
    def __init__(self, w):
        super().__init__()
        self.w = w

    def forward(self, inp):
        out = self.w(inp)
        print(out)
        print(out.image.data)
        return (out.projected_text_embeddings, out.projected_image_embeddings)


m = MyModule()
m = FullyShardedDataParallel(m)
model = Wrapper(m)
model=FullyShardedDataParallel(model)

t = torch.ones(1, device='cuda')
FLAVAOutput = namedtuple(
    "FLAVAOutput",
    [
        "image",
        "image_masked",
        "text",
        "text_masked",
        "multimodal",
        "multimodal_masked",
        "projected_image_embeddings",
        "projected_text_embeddings",
    ],
    defaults=(t,t,t,t,t,t,t,t),
)

inp = FLAVAOutput()
out = model(inp)
print(out)
```

the output is:

```
(pt) $ MASTER_ADDR=localhost MASTER_PORT=29500 python test.py
init
/fsx/users/rvarm1/rvarm1/repos/pytorch/torch/distributed/fsdp/fully_sharded_data_parallel.py:1077: UserWarning: Module is put on CPU and will thus have flattening and sharding run on CPU, which is less efficient than on GPU. We recommend passing in `device_id` argument which will enable FSDP to put module on GPU device, module must also be on GPU device to work with `sync_module_states=True` flag which requires GPU communication.
  warnings.warn(
/fsx/users/rvarm1/rvarm1/repos/pytorch/torch/nn/parallel/scatter_gather.py:9: UserWarning: is_namedtuple is deprecated, please use the python checks instead
  warnings.warn("is_namedtuple is deprecated, please use the python checks instead")
FLAVAOutput(image=<generator object _apply_to_tensors.<locals>.apply.<locals>.<genexpr> at 0x7fd9f02253c0>, image_masked=tensor([1.], device='cuda:0'), text=tensor([1.], device='cuda:0'), text_masked=tensor([1.], device='cuda:0'), multimodal=tensor([1.], device='cuda:0'), multimodal_masked=tensor([1.], device='cuda:0'), projected_image_embeddings=tensor([1.], device='cuda:0'), projected_text_embeddings=tensor([1.], device='cuda:0'))
Traceback (most recent call last):
  File "/fsx/users/rvarm1/rvarm1/repos/pytorch/test.py", line 55, in <module>
    out = model(inp)
  File "/fsx/users/rvarm1/rvarm1/repos/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/rvarm1/rvarm1/repos/pytorch/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 2432, in forward
    outputs = self._fsdp_wrapped_module(*args, **kwargs)
  File "/fsx/users/rvarm1/rvarm1/repos/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/rvarm1/rvarm1/repos/pytorch/torch/distributed/fsdp/flatten_params_wrapper.py", line 156, in forward
    return self.module(*inputs, **kwinputs)
  File "/fsx/users/rvarm1/rvarm1/repos/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/rvarm1/rvarm1/repos/pytorch/test.py", line 29, in forward
    print(out.image.data)
AttributeError: 'generator' object has no attribute 'data'
```

### Versions

main

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by rohan-varma** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/83055
