### ISSUE TITLE
Can't pickle local object 'CDLL.__init__.<locals>._FuncPtr'

### ISSUE THREAD

**Issue by gitlabspy** [pytorch/pytorch#83065]
I am using `torch.multiprocessing.Process` in a reinforcement learning project.  Here's bit of my codes:
```python
class Agent(mp.Process):
  def __init__():
     super()...
     self.dll = CDLL('load a dll here which work fine without mp.Process')
     self.env = some_env


  def run(self):
     action = ...
     self.env.step(action, self.dll)
     ...


if __name__ == "__main__":
  mp.set_start_method("forkserver") 
  workers = [Agent(..) for i in range(n)]
  [w.start() for w in workers]
  [w.join() for w in workers]

```
Here's the errors I got:
```
Traceback (most recent call last):
  File "gym_test.py", line 173, in <module>
    [w.start() for w in workers]
  File "gym_test.py", line 173, in <listcomp>
    [w.start() for w in workers]
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CDLL.__init__.<locals>._FuncPtr'
```

I wonder how to load cdll properly in multiprocessing, any solutions?

cc @VitalyFedyunin

**Comment by VitalyFedyunin** [comment]
`CDLL` is not pickable, and cannot be passed between processes. Avoid loading dll inside of the class init, do it lazily on demand.
