### ISSUE TITLE
Transformer encoder error when encoding long sequence (more than 1024 tokens)

### ISSUE THREAD

**Issue by Xmr-nxbx** [pytorch/pytorch#83142]
### 🐛 Describe the bug

In evaluation mode, Transformer encoder shows a runtime error when the number of tokens is greater than 1024.
```python
import torch
import torch.nn as nn

encoder_layer = nn.TransformerEncoderLayer(
    d_model=512, nhead=8, dim_feedforward=2048, batch_first=True)
encoder = nn.TransformerEncoder(
    encoder_layer, num_layers=6, enable_nested_tensor=True)
encoder.cuda()

x = torch.randn(1, 1026, 512)
x_mask = [[0]*1025+[1]*1]
x_mask = torch.Tensor(x_mask).bool()

x = x.cuda()
x_mask = x_mask.cuda()

encoder.eval()
with torch.no_grad():
    y = encoder(x, src_key_padding_mask=x_mask)
print(y.shape)
```
runtime error:
```
Traceback (most recent call last):
  File "/home/xmr/miniconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xmr/miniconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xmr/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/xmr/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/xmr/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/xmr/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/xmr/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/xmr/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/mnt/e/test/test.py", line 19, in <module>
    y = encoder(x, src_key_padding_mask=x_mask)
  File "/home/xmr/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xmr/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 236, in forward
    output = mod(output, src_mask=mask)
  File "/home/xmr/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xmr/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 437, in forward
    return torch._transformer_encoder_layer_fwd(
RuntimeError: Mask shape should match input shape; transformer_mask is not supported in the fallback case.
```

But if the number of tokens is less than or equal to 1024, then it can run without error.
```python
import torch
import torch.nn as nn

encoder_layer = nn.TransformerEncoderLayer(
    d_model=512, nhead=8, dim_feedforward=2048, batch_first=True)
encoder = nn.TransformerEncoder(
    encoder_layer, num_layers=6, enable_nested_tensor=True)
encoder.cuda()

x = torch.randn(1, 1026, 512)
x_mask = [[0]*1024+[1]*2]     # Here I change the number of tokens to 1024
x_mask = torch.Tensor(x_mask).bool()

x = x.cuda()
x_mask = x_mask.cuda()

encoder.eval()
with torch.no_grad():
    y = encoder(x, src_key_padding_mask=x_mask)
print(y.shape)  # torch.Size([1, 1024, 512])
```

### Versions

PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 9.0.0 (https://github.com/conda-forge/clangdev-feedstock 284a3d5d88509307bcfba64b055653ee347371db)
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 516.59
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.1+cu116
[pip3] torchaudio==0.12.1+cu116
[pip3] torchvision==0.13.1+cu116
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] numpy                     1.22.3           py39he7a7128_0    defaults
[conda] numpy-base                1.22.3           py39hf524024_0    defaults
[conda] torch                     1.12.1+cu116             pypi_0    pypi
[conda] torchaudio                0.12.1+cu116             pypi_0    pypi
[conda] torchvision               0.13.1+cu116             pypi_0    pypi

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @bhosmer @cpuhrsch @erichan1

**Comment by erichan1** [comment]
I'm aware of where this issue is called - we take a fastpath at 1024 tokens for mask addition and there's a bug in there. Debugging.

**Comment by querryton** [comment]
I faced the same problem. Have you solved? @Xmr-nxbx

**Comment by erichan1** [comment]
Working on the fix. Put up test first.
