### ISSUE TITLE
torchgen.model.FunctionSchema.parse fails with following ops' schema 

### ISSUE THREAD

**Issue by SherlockNoMad** [pytorch/pytorch#83214]
### 🐛 Describe the bug

Is this expected? 
Do we want to handle following case? 

```
aten::to.prim_Device(Tensor(a) self, Device? device, int? dtype=None, bool non_blocking=False, bool copy=False) -> Tensor(b|a)
unrecognized alias annotation b|a
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1223, in parse
    returns = parse_returns(return_decl)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2578, in parse_returns
    return tuple(Return.parse(arg) for arg in return_decl.split(", "))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2578, in <genexpr>
    return tuple(Return.parse(arg) for arg in return_decl.split(", "))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1900, in parse
    annotation = Annotation.parse(match.group(1))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1588, in parse
    assert m is not None, f"unrecognized alias annotation {ann}"
AssertionError: unrecognized alias annotation b|a

prims::as_strided(Tensor(a!) a, int[] size, int[] stride, int storage_offset) -> Tensor(a!)
If you have a schema with mutable positional args, we expect them to not be returned. schema: prims::as_strided(Tensor(a!) a, int[] size, int[] stride, int storage_offset) -> Tensor(a!)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1224, in parse
    r = FunctionSchema(name=name, arguments=arguments, returns=returns)
  File "<string>", line 6, in __init__
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1245, in __post_init__
    assert not any(
AssertionError: If you have a schema with mutable positional args, we expect them to not be returned. schema: prims::as_strided(Tensor(a!) a, int[] size, int[] stride, int storage_offset) -> Tensor(a!)

prims::copy_to(Tensor(a!) a, Tensor b) -> Tensor(a!)
If you have a schema with mutable positional args, we expect them to not be returned. schema: prims::copy_to(Tensor(a!) a, Tensor b) -> Tensor(a!)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1224, in parse
    r = FunctionSchema(name=name, arguments=arguments, returns=returns)
  File "<string>", line 6, in __init__
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1245, in __post_init__
    assert not any(
AssertionError: If you have a schema with mutable positional args, we expect them to not be returned. schema: prims::copy_to(Tensor(a!) a, Tensor b) -> Tensor(a!)

prims::resize(Tensor(a!) a, int[] shape) -> Tensor(a!)
If you have a schema with mutable positional args, we expect them to not be returned. schema: prims::resize(Tensor(a!) a, int[] shape) -> Tensor(a!)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1224, in parse
    r = FunctionSchema(name=name, arguments=arguments, returns=returns)
  File "<string>", line 6, in __init__
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1245, in __post_init__
    assert not any(
AssertionError: If you have a schema with mutable positional args, we expect them to not be returned. schema: prims::resize(Tensor(a!) a, int[] shape) -> Tensor(a!)

aten::add.t(t[] a, t[] b) -> t[]
unrecognized type t
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1636, in _parse
    return BaseType(BaseTy[t])
  File "/fsx/users/bahuang/conda/envs/pt_dev/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 't'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1845, in parse
    type = Type.parse(type_s)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1617, in parse
    r = Type._parse(t)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1629, in _parse
    return ListType(elem=Type.parse(m.group(1)), size=size)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1617, in parse
    r = Type._parse(t)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1638, in _parse
    raise RuntimeError(f"unrecognized type {t}")
RuntimeError: unrecognized type t

aten::eq.enum(AnyEnumType a, AnyEnumType b) -> bool
unrecognized type AnyEnumType
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1636, in _parse
    return BaseType(BaseTy[t])
  File "/fsx/users/bahuang/conda/envs/pt_dev/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'AnyEnumType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1845, in parse
    type = Type.parse(type_s)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1617, in parse
    r = Type._parse(t)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1638, in _parse
    raise RuntimeError(f"unrecognized type {t}")
RuntimeError: unrecognized type AnyEnumType

aten::mul.left_t(t[] l, int n) -> t[]
unrecognized type t
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1636, in _parse
    return BaseType(BaseTy[t])
  File "/fsx/users/bahuang/conda/envs/pt_dev/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 't'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1845, in parse
    type = Type.parse(type_s)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1617, in parse
    r = Type._parse(t)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1629, in _parse
    return ListType(elem=Type.parse(m.group(1)), size=size)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1617, in parse
    r = Type._parse(t)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1638, in _parse
    raise RuntimeError(f"unrecognized type {t}")
RuntimeError: unrecognized type t

aten::mul.right_(int n, t[] l) -> t[]
unrecognized type t
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1636, in _parse
    return BaseType(BaseTy[t])
  File "/fsx/users/bahuang/conda/envs/pt_dev/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 't'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1845, in parse
    type = Type.parse(type_s)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1617, in parse
    r = Type._parse(t)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1629, in _parse
    return ListType(elem=Type.parse(m.group(1)), size=size)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1617, in parse
    r = Type._parse(t)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1638, in _parse
    raise RuntimeError(f"unrecognized type {t}")
RuntimeError: unrecognized type t

aten::ne.enum(AnyEnumType a, AnyEnumType b) -> bool
unrecognized type AnyEnumType
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1636, in _parse
    return BaseType(BaseTy[t])
  File "/fsx/users/bahuang/conda/envs/pt_dev/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'AnyEnumType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1845, in parse
    type = Type.parse(type_s)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1617, in parse
    r = Type._parse(t)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1638, in _parse
    raise RuntimeError(f"unrecognized type {t}")
RuntimeError: unrecognized type AnyEnumType

aten::rot90(Tensor self, int k=1, int[] dims=[0, 1]) -> Tensor
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_fft2(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None) -> Tensor
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_fft2.out(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None, *, Tensor(a!) out) -> Tensor(a!)
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_ifft2(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None) -> Tensor
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_ifft2.out(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None, *, Tensor(a!) out) -> Tensor(a!)
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_rfft2(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None) -> Tensor
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_rfft2.out(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None, *, Tensor(a!) out) -> Tensor(a!)
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_irfft2(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None) -> Tensor
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_irfft2.out(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None, *, Tensor(a!) out) -> Tensor(a!)
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_hfft2(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None) -> Tensor
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_hfft2.out(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None, *, Tensor(a!) out) -> Tensor(a!)
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_ihfft2(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None) -> Tensor
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)

aten::fft_ihfft2.out(Tensor self, int[1]? s=None, int[1] dim=[-2, -1], str? norm=None, *, Tensor(a!) out) -> Tensor(a!)
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/fsx/users/bahuang/repos/pytorch_fsx/torch/_ops.py", line 39, in __init__
    self._parsed_schema: FunctionSchema = FunctionSchema.parse(str(schema))
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1222, in parse
    arguments = Arguments.parse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2183, in parse
    positional, kwarg_only, out = Arguments._preparse(args)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 2154, in _preparse
    parg = Argument.parse(arg)
  File "/fsx/users/bahuang/repos/pytorch_fsx/torchgen/model.py", line 1824, in parse
    type_and_annot, name_and_default = arg.rsplit(" ", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

### Versions

master

**Comment by bdhirsh** [comment]
Some of these look like cases where we should beef up the schema parsing in torchgen, while others look like cases where we have prim ops with schemas that don't conform to torchgen's expectations. I think it would be reasonable to fix the schema in that case?

Going through a few of the examples:

> aten::to.prim_Device(Tensor(a) self, Device? device, int? dtype=None, bool non_blocking=False, bool copy=False) -> Tensor(b|a)
> ...
> AssertionError: unrecognized alias annotation b|a

Beefing up aliasing info in torchgen seems reasonable

> prims::as_strided(Tensor(a!) a, int[] size, int[] stride, int storage_offset) -> Tensor(a!)
> If you have a schema with mutable positional args, we expect them to not be returned. schema: prims::as_strided(Tensor(a!) a, int[] size, int[] stride, int storage_offset) -> Tensor(a!)

torchgen is complaining because the alias annotations imply that `prims::as_strided` is an inplace op, so it should be named `as_strided_`. Seems like we should fix that?

> aten::mul.left_t(t[] l, int n) -> t[]
> unrecognized type t

Should this be `Tensor[]` instead of `t[]`?

**Comment by SherlockNoMad** [comment]
@bdhirsh, I will send a PR to fix the problematic schema definitions. 

@larryliu0820 let's beef up the schema parsing :)
