### ISSUE TITLE
torchdynamo is swallowing relevant exceptions even when debug/trace is enabled

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#83538]
### 🐛 Describe the bug

Steps to reproduce: 
* Build PyTorch at https://github.com/ezyang/pytorch/pull/new/dynamo-swallow-repro
* `pytest tests/test_repros.py -k test_convert_boxes_to_pooler_format`

Expected: I see why WONT CONVERT triggered (which causes the test to fail)

Actual: I see

```
WONT CONVERT shapes_to_tensor tests/test_repros.py 99                                                
```

and then no error trace.

When I patch in 

```
diff --git a/torchdynamo/convert_frame.py b/torchdynamo/convert_frame.py
index 5371c66..99c7275 100644
--- a/torchdynamo/convert_frame.py
+++ b/torchdynamo/convert_frame.py
@@ -321,6 +321,7 @@ def convert_frame_assert(compiler_fn: Callable, guard_export_fn=None, one_graph=
         except (Unsupported, TorchRuntimeError, BackendCompilerFailed, AssertionError):
             if config.debug or config.trace or config.print_internal_exceptions:
                 debug_print("WONT CONVERT")
+                traceback.print_exc()
             raise
         except Exception:
             if config.debug or config.trace or config.print_internal_exceptions:
``` 

I can see the exception. The stack trace is

```
Traceback (most recent call last):                                                                   
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/tensor.py", line 142, in create         
    example_value = wrap_fake_exception(                                                             
  File "/data/users/ezyang/torchdynamo/torchdynamo/utils.py", line 495, in wrap_fake_exception       
    return fn()                                                                                      
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/tensor.py", line 143, in <lambda>       
    lambda: cls.run_proxy(proxy, args, kwargs, nnmodule)                                             
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/tensor.py", line 85, in run_proxy       
    return proxy.node.target(*args, **kwargs)                                                        
  File "/data/users/ezyang/pytorch-tmp/torch/utils/_python_dispatch.py", line 74, in wrapped         
    return f(self, *args, **kwargs)                                                                  
  File "/data/users/ezyang/pytorch-tmp/torch/_subclasses/fake_tensor.py", line 604, in __torch_dispat
ch__                                                                                                 
    with self.restore():                                                                             
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.8/contextlib.py", line 113, in __enter__      
    return next(self.gen)                                                                            
  File "/data/users/ezyang/pytorch-tmp/torch/utils/_mode_utils.py", line 95, in _restore_mode        
    raise RuntimeError(f"{mode} does not have any ancestors. Use the standard version instead of rest
ore")                                                                                                
RuntimeError: <torch._subclasses.fake_tensor.FakeTensorMode object at 0x7fc9865ce760> does not have a
ny ancestors. Use the standard version instead of restore                                            
                                                  
The above exception was the direct cause of the following exception: 

Traceback (most recent call last):                                                                   
  File "/data/users/ezyang/torchdynamo/torchdynamo/convert_frame.py", line 288, in _convert_frame_ass
ert                                                                                                  
    code = transform_code_object(frame.f_code, transform)                                            
  File "/data/users/ezyang/torchdynamo/torchdynamo/bytecode_transformation.py", line 338, in transfor
m_code_object                                                                                        
    transformations(instructions, code_options)                                                      
  File "/data/users/ezyang/torchdynamo/torchdynamo/convert_frame.py", line 264, in transform         
    tracer.run()                                                                                     
  File "/data/users/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 312, in run            
    and self.step()                                                                                  
  File "/data/users/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 290, in step           
    getattr(self, inst.opname)(inst)                                                                 
  File "/data/users/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 151, in wrapper        
    return inner_fn(self, inst)                                                                      
  File "/data/users/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 629, in CALL_FUNCTION  
    self.call_function(fn, args, {})                                                                 
  File "/data/users/ezyang/torchdynamo/torchdynamo/symbolic_convert.py", line 226, in call_function  
    self.push(fn.call_function(self, args, kwargs))                                                  
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/torch.py", line 207, in call_function   
    tensor_variable = TensorVariable.create(                                                         
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/tensor.py", line 146, in create         
    raise TorchRuntimeError() from e                                                                 
torchdynamo.exc.TorchRuntimeError 
```

According to PDB, it seems to get suppressed here

```
> /data/users/ezyang/torchdynamo/torchdynamo/convert_frame.py(352)_convert_frame()
-> result = inner_convert(frame, cache_size)
(Pdb) 
> /data/users/ezyang/torchdynamo/torchdynamo/convert_frame.py(355)_convert_frame()
-> except AssertionError:
(Pdb) 
> /data/users/ezyang/torchdynamo/torchdynamo/convert_frame.py(358)_convert_frame()
-> except BackendCompilerFailed:
(Pdb) 
> /data/users/ezyang/torchdynamo/torchdynamo/convert_frame.py(360)_convert_frame()
-> except Exception:
(Pdb) 
> /data/users/ezyang/torchdynamo/torchdynamo/convert_frame.py(361)_convert_frame()
-> pass
(Pdb) 
> /data/u
```

### Versions

master

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by mlazos** [comment]
Fixed by https://github.com/pytorch/torchdynamo/pull/793
