### ISSUE TITLE
FakeTensor internal assert failure running `hf_BigBird` model

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#83768]
In the torchdynamo benchmark suite, when I run:
```
python benchmarks/torchbench.py --training --devices=cuda --accuracy-aot-nop --generate-aot-autograd-stats --use-eval-mode --only=hf_BigBird
```

with `functorch._src.config.use_fake_tensor = True`, so we're trying with fake tensors,

I get this error:
```
ERROR:root:unhandled error
Traceback (most recent call last):
  File "/scratch/hirsheybar/work/benchmark/pytorch/torchdynamo/benchmarks/common.py", line 857, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torchdynamo/benchmarks/torchbench.py", line 360, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/scratch/hirsheybar/work/benchmark/pytorch/torchdynamo/benchmarks/torchbench.py", line 360, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/scratch/hirsheybar/work/benchmark/pytorch/torchdynamo/benchmarks/torchbench.py", line 364, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/lib/python3.9/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2393, in forward
    @add_start_docstrings_to_model_forward(BIG_BIRD_INPUTS_DOCSTRING.format("batch_size, sequence_length"))
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/lib/python3.9/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1984, in forward
    @add_start_docstrings_to_model_forward(BIG_BIRD_INPUTS_DOCSTRING.format("batch_size, sequence_length"))
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/lib/python3.9/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1640, in forward
    layer_outputs = layer_module(
  File "/scratch/hirsheybar/work/benchmark/lib/python3.9/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1640, in forward
    layer_outputs = layer_module(
  File "/scratch/hirsheybar/work/benchmark/lib/python3.9/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1640, in forward
    layer_outputs = layer_module(
  [Previous line repeated 1 more time]
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/lib/python3.9/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1476, in forward
    def forward(
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/lib/python3.9/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 1405, in forward
    self_outputs = self.self(
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/lib/python3.9/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 448, in forward
    def forward(
  File "/scratch/hirsheybar/work/benchmark/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 94, in _fn
    return fn(*args, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/fx/_symbolic_trace.py", line 716, in trace
    (self.create_arg(fn(*args)),),
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/fx/_symbolic_trace.py", line 551, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/fx/experimental/proxy_tensor.py", line 271, in wrapped
    out = f(*tensors)
  File "/scratch/hirsheybar/work/benchmark/pytorch/functorch/functorch/_src/aot_autograd.py", line 88, in joint_forward_backward
    backward_out = torch.autograd.grad(
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/autograd/__init__.py", line 294, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/fx/experimental/proxy_tensor.py", line 290, in __torch_dispatch__
    return self.inner_torch_dispatch(func_overload, types, args, kwargs)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/fx/experimental/proxy_tensor.py", line 318, in inner_torch_dispatch
    out = proxy_call(self, func_overload, args, kwargs)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/fx/experimental/proxy_tensor.py", line 179, in proxy_call
    out = func_overload(*args, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/_subclasses/fake_tensor.py", line 681, in __torch_dispatch__
    return op_impl(self, func, *args, **kwargs)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/_subclasses/fake_tensor.py", line 270, in clone
    return FakeTensor(fake_mode, out, out_device)
  File "/scratch/hirsheybar/work/benchmark/pytorch/torch/_subclasses/fake_tensor.py", line 389, in __init__
    assert device.type != "meta"
AssertionError
```

cc @eellison @ezyang

**Comment by ezyang** [comment]
Is fixed!

**Comment by ezyang** [comment]
My bad, I didn't apply the right config parameters

**Comment by ezyang** [comment]
ok I manually applied the config parameter and it still succeeded
