### ISSUE TITLE
torch.linalg.eigh crashes (C++) / "INTERNAL ASSERT FAILED" (python) for matrices of size 2895×2895 or larger

### ISSUE THREAD

**Issue by Cyp** [pytorch/pytorch#83818]
### From python

```python
>>> import torch as t
>>> t.linalg.eigh(t.randn([2895, 2895]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: false INTERNAL ASSERT FAILED at "/var/tmp/portage/sci-libs/caffe2-1.12.0/work/pytorch-1.12.0/aten/src/ATen/native/LinearAlgebraUtils.h":288, please report a bug to PyTorch. torch.linalg.eigh: Argument 8 has illegal value. Most certainly there is a bug in the implementation calling the backend library.

>>> t.linalg.eigh(t.randn([2894, 2894]))
torch.return_types.linalg_eigh(
eigenvalues=tensor([-107.5161, -107.0879, -106.6525,  ...,  106.2521,  106.6649,
         107.0642]),
eigenvectors=tensor([[ 0.0078, -0.0312,  0.0016,  ..., -0.0169,  0.0231, -0.0228],
        [-0.0116, -0.0156, -0.0480,  ..., -0.0078, -0.0399, -0.0170],
        [-0.0112,  0.0034,  0.0137,  ...,  0.0073,  0.0098,  0.0088],
        ...,
        [ 0.0109, -0.0148,  0.0302,  ...,  0.0077, -0.0162,  0.0146],
        [-0.0004, -0.0294,  0.0220,  ..., -0.0102, -0.0062,  0.0327],
        [-0.0262,  0.0164, -0.0376,  ...,  0.0289, -0.0080, -0.0037]]))
```

### From C++ interface

Can't get a backtrace with gdb, since `bt` says the program already exited. So it's just a mysterious undebuggable crash, until narrowing it down to a `torch::linalg::eigh` call.

```
 ** On entry to SSYEVD parameter number  8 had an illegal value
```

### See also?

Possibly related to #68291 / #51720?

### Versions

1.12

```
$ wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
--2022-08-21 09:45:24--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16906 (17K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py                                       100%[====================================================================================================================>]  16.51K  --.-KB/s    in 0.02s   

2022-08-21 09:45:24 (1009 KB/s) - ‘collect_env.py’ saved [16906/16906]

$ python collect_env.py 
Collecting environment information...
Traceback (most recent call last):
  File "~/collect_env.py", line 492, in <module>
    main()
  File "~/collect_env.py", line 475, in main
    output = get_pretty_env_info()
  File "~/collect_env.py", line 470, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "~/collect_env.py", line 319, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "~/collect_env.py", line 301, in get_pip_packages
    out = run_with_pip(sys.executable + ' -mpip')
  File "~/collect_env.py", line 289, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by Lezcano** [comment]
I can't seem to repro in `master`. Could you try the nightly builds and see if it still fails there?

Also, could you post what does `print(torch.__config__.show())` return in your system?

**Comment by Cyp** [comment]
```python
>>> print(t.__config__.show())
PyTorch built with:
  - GCC 11.3
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: NO AVX
  - Build settings: BUILD_TYPE=RelWithDebInfo, CXX_COMPILER=/usr/bin/x86_64-pc-linux-gnu-g++, CXX_FLAGS=-march=native -O2 -pipe -g -fvisibility-inlines-hidden -fopenmp -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=no, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=ON, USE_GLOG=ON, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=no, USE_OPENMP=yes, USE_ROCM=OFF, 
```
----
Seeing if I can build master to try there…

**Comment by Lezcano** [comment]
There's no need to build master! You can simply install the nightly version. See the grid
![image](https://user-images.githubusercontent.com/3291265/186235060-e2156acb-a271-4977-a635-16306cef06c9.png)

in https://pytorch.org/

**Comment by Cyp** [comment]
Seems to work with docker, once a 2 GB download finally finishes after the 2nd try:

```
$ docker run --gpus all --rm -ti --ipc=host pytorch/pytorch:latest
Unable to find image 'pytorch/pytorch:latest' locally
latest: Pulling from pytorch/pytorch
09db6f815738: Pull complete 
ecd55c89ef07: Pull complete 
4782128c6040: Pull complete 
aa5c1852a419: Pull complete 
Digest: sha256:1ef1f61b13738de8086ae7e1ce57c89f154e075dae0b165f7590b9405efeb6fe
Status: Downloaded newer image for pytorch/pytorch:latest
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

$ docker run --rm -ti --ipc=host pytorch/pytorch:latest
root@a1a9320649ba:/workspace# python
Python 3.7.13 (default, Mar 29 2022, 02:18:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch as t

>>> t.linalg.eigh(t.randn([2895, 2895]))
torch.return_types.linalg_eigh(
eigenvalues=tensor([-106.7264, -106.3273, -106.0622,  ...,  106.5510,  107.0971,
         107.2805]),
eigenvectors=tensor([[-8.3460e-03,  1.6611e-02, -5.1989e-03,  ...,  3.6921e-03,
         -4.9365e-03,  7.8395e-04],
        [ 5.9310e-03,  1.9071e-02,  1.0230e-02,  ...,  7.2159e-03,
          2.7967e-02, -1.0529e-02],
        [-2.4934e-03,  1.9701e-02, -8.3148e-06,  ..., -3.6329e-02,
         -1.0691e-02,  3.5191e-02],
        ...,
        [ 1.3530e-02,  9.0308e-03,  2.2715e-02,  ...,  3.3401e-02,
         -2.1511e-03,  1.3929e-03],
        [ 1.7694e-02, -5.8797e-04, -1.9451e-02,  ...,  5.4486e-03,
         -5.3181e-03,  1.4745e-02],
        [-2.5711e-02,  1.5054e-02, -3.2966e-03,  ..., -4.0560e-03,
         -1.0185e-02,  1.0028e-02]]))

>>> print(t.__config__.show())
PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 
```

Also, instead of taking 33 seconds to do a 2894×2894 matrix, the docker version does it in 1.6 seconds or a 8000×8000 in 36 seconds.

So I don't know whether the difference is because the docker version is different somehow, or that it's a nightly version.

**Comment by IvanYashchuk** [comment]
> ```python
> >>> print(t.__config__.show())
> PyTorch built with:
>   - GCC 11.3
>   - C++ Version: 201402
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - LAPACK is enabled (usually provided by MKL)
>   - CPU capability usage: NO AVX
>   - Build settings: BUILD_TYPE=RelWithDebInfo, CXX_COMPILER=/usr/bin/x86_64-pc-linux-gnu-g++, CXX_FLAGS=-march=native -O2 -pipe -g -fvisibility-inlines-hidden -fopenmp -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=no, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=ON, USE_GLOG=ON, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=no, USE_OPENMP=yes, USE_ROCM=OFF, 
> ```
> 
> Seeing if I can build master to try there…



USE_EIGEN_FOR_BLAS=ON, USE_MKL=OFF

This function uses LAPACK under the hood, in our CI we test only with MKL's implementation of LAPACK. Other providers might have issues, as in this case. An alternative to MKL that's open-source and maintained is OpenBLAS, but we don't test that in our CI either.

**Comment by Balandat** [comment]
I can confirm this issue on 12.2.1 on an Apple M1: 

```
torch.linalg.eigh(torch.eye(2895))

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [31], in <cell line: 1>()
----> 1 torch.linalg.eigh(torch.eye(2895))

RuntimeError: false INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484611838/work/aten/src/ATen/native/LinearAlgebraUtils.h":289, please report a bug to PyTorch. torch.linalg.eigh: Argument 8 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
```

On the other hand, `torch.linalg.eigh(torch.eye(2894))` or smaller works fine.


```
PyTorch built with:
  - GCC 4.2
  - C++ Version: 201402
  - clang 13.1.6
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=accelerate, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode_13.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_PYTORCH_METAL_EXPORT -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -DUSE_COREML_DELEGATE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-range-loop-analysis -Wno-pass-failed -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DUSE_MPS -fno-objc-arc -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, LAPACK_INFO=accelerate, TORCH_VERSION=1.12.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=OFF, USE_ROCM=OFF, 
```

**Comment by Balandat** [comment]
The same issue happens on the latest nightly (version `1.13.0.dev20220926`).

**Comment by norabelrose** [comment]
Just repro'ed this on version 2.0.1

**Comment by deJQK** [comment]
> The same issue happens on the latest nightly (version `1.13.0.dev20220926`).

Same here for the following setting:

```
>>> print(torch.__config__.show())
PyTorch built with:
  - GCC 4.2
  - C++ Version: 201703
  - clang 14.0.3
  - OpenMP 201811
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=accelerate, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode_14.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++, CXX_FLAGS= -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_PYTORCH_METAL_EXPORT -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DUSE_COREML_DELEGATE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=braced-scalar-init -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wvla-extension -Wsuggest-override -Wnewline-eof -Winconsistent-missing-override -Winconsistent-missing-destructor-override -Wno-pass-failed -Wno-error=pedantic -Wno-error=old-style-cast -Wno-error=inconsistent-missing-override -Wno-error=inconsistent-missing-destructor-override -Wconstant-conversion -Wno-invalid-partial-specialization -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -faligned-new -Wno-unused-but-set-variable -fno-math-errno -fno-trapping-math -Werror=format -DUSE_MPS -Wno-unused-private-field -Wno-missing-braces, LAPACK_INFO=accelerate, TORCH_VERSION=2.3.1, USE_CUDA=OFF, USE_CUDNN=OFF, USE_CUSPARSELT=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,
```

**Comment by deJQK** [comment]
> #51720

My current solution is to finish this with scipy and convert back to tensor.
