### ISSUE TITLE
Running simultaneous DataParallels can potentially result in locked models

### ISSUE THREAD

**Issue by daemon** [pytorch/pytorch#8388]
I observed that running simultaneous DataParallels might result in at least one of the models being unable to progress at all.

```
ubuntu@ip-XXX:~/vrex2$ ./run.sh
Loading data file...
Loaded!
^CTraceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/vrex2/utils/train.py", line 121, in <module>
    main()
  File "/home/ubuntu/vrex2/utils/train.py", line 116, in main
    train(config)
  File "/home/ubuntu/vrex2/utils/train.py", line 69, in train
    scores = model(model_in)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 57, in parallel_apply
    thread.join()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/home/ubuntu/anaconda3/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^C^C^C^C^C^C
```

System configuration:
- PyTorch 0.4.0 stable release, installed using `conda install -c pytorch pytorch torchvision`
- EC2 P2.8xlarge (8 x K80s)
- CUDA 8
- Python 3.6

```
ubuntu@ip-96-115-215-139:~/vrex2$ nvidia-smi
Tue Jun 12 18:35:36 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:17.0 Off |                    0 |
| N/A   83C    P0   127W / 149W |   1998MiB / 11439MiB |     67%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:00:18.0 Off |                    0 |
| N/A   67C    P0   130W / 149W |   1878MiB / 11439MiB |     61%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:00:19.0 Off |                    0 |
| N/A   77C    P0   124W / 149W |   1878MiB / 11439MiB |     61%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:00:1A.0 Off |                    0 |
| N/A   63C    P0   128W / 149W |   1878MiB / 11439MiB |     62%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           On   | 00000000:00:1B.0 Off |                    0 |
| N/A   79C    P0   123W / 149W |   1878MiB / 11439MiB |     60%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           On   | 00000000:00:1C.0 Off |                    0 |
| N/A   68C    P0   127W / 149W |   1878MiB / 11439MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           On   | 00000000:00:1D.0 Off |                    0 |
| N/A   75C    P0   112W / 149W |   1878MiB / 11439MiB |     60%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   62C    P0   135W / 149W |   1878MiB / 11439MiB |     61%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     76810      C   python                                      1985MiB |
|    1     76810      C   python                                      1865MiB |
|    2     76810      C   python                                      1865MiB |
|    3     76810      C   python                                      1865MiB |
|    4     76810      C   python                                      1865MiB |
|    5     76810      C   python                                      1865MiB |
|    6     76810      C   python                                      1865MiB |
|    7     76810      C   python                                      1865MiB |
+-----------------------------------------------------------------------------+
```

On a separate machine with 8 x Titan X, the following happened after I tried running multiple parallel models:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:04:00.0     Off |                  N/A |
| 22%   50C    P2    84W / 250W |   2550MiB / 12207MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:05:00.0     Off |                  N/A |
| 22%   41C    P2    67W / 250W |   2394MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:08:00.0     Off |                  N/A |
| 22%   40C    P2    67W / 250W |   2276MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:09:00.0     Off |                  N/A |
| 22%   42C    P2    67W / 250W |   2157MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX TIT...  Off  | 0000:85:00.0     Off |                  N/A |
| 22%   24C    P8    15W / 250W |   1973MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX TIT...  Off  | 0000:86:00.0     Off |                  N/A |
| 22%   23C    P8    15W / 250W |   1975MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX TIT...  Off  | 0000:89:00.0     Off |                  N/A |
| 22%   23C    P8    15W / 250W |   1973MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX TIT...  Off  | 0000:8A:00.0     Off |                  N/A |
| 22%   24C    P8    15W / 250W |   1973MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     20159    C   python                                         400MiB |
|    1     31020    C   python                                         419MiB |
|    2     31020    C   python                                         301MiB |
|    3     31020    C   python                                         182MiB |
+-----------------------------------------------------------------------------+
```

There's RAM that's somehow unaccounted for.

**Comment by apaszke** [comment]
This is expected, and is caused by a NCCL library (which we use for multiGPU communication). Unfortunately there are no workarounds, but in general running multiple networks on the same GPUs is not a good idea.

**Comment by soumith** [comment]
To elaborate on Adam's answer. At the NVIDIA driver level, deadlocks are expected with NCCL -- there are no known workarounds, and no expected solutions. Sharing GPUs for multiple workloads in the distributed setting is not ideal for this reason.

One alternative for you to consider is to move to DistributedDataParallel (even for a single machine) and use the `gloo` backend: https://pytorch.org/docs/stable/distributed.html#launch-utility

**Comment by daemon** [comment]
Ah okay, thanks.
