### ISSUE TITLE
Illegal Memory Access was encountered in AvgPool2d CUDA kernel

### ISSUE THREAD

**Issue by syed-ahmed** [pytorch/pytorch#84018]
### 🐛 Describe the bug

Repro:
```python
import torch
m = torch.nn.AvgPool2d(kernel_size=2, stride=2, padding=0)
input = torch.randn(1024, 64, 228, 228, device="cuda")
output = m(input)
```
Outputs:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/pooling.py", line 623, in forward
    return F.avg_pool2d(input, self.kernel_size, self.stride,
RuntimeError: CUDA error: an illegal memory access was encountered
```

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0a0+08820cb
Is debug build: True
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.2
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-109-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.99
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 515.43.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.13.0a0+08820cb
[pip3] torch-tensorrt==1.2.0a0
[pip3] torchtext==0.13.0a0
[pip3] torchvision==0.14.0a0
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-include               2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.22.4           py38h99721a1_0    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.13.0a0+08820cb          pypi_0    pypi
[conda] torch-tensorrt            1.2.0a0                  pypi_0    pypi
[conda] torchtext                 0.13.0a0                 pypi_0    pypi
[conda] torchvision               0.14.0a0                 pypi_0    pypi
```
CC: @ptrblck 

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel

**Comment by syed-ahmed** [comment]
Initial triaging points to the IMA happening here: 
https://github.com/pytorch/pytorch/blob/1eff853fdc91619ea24abf0cbd51ca992fe10c97/aten/src/ATen/native/cuda/AveragePool2d.cu#L65

**Comment by ngimel** [comment]
As per usual, anything with more than 2**31 elements is problematic.

**Comment by dagitses** [comment]
Is there anything you recommend we do about that Natalia? Is this a fundamental CUDA/Nvidia limitation or is using 64-bit indexing a possibility?

**Comment by ngimel** [comment]
This is a bug in our implementation, nvidia should fix it and generally audit large tensor operations, we are getting bugs filed against large tensors regularly (e.g. #84144)

**Comment by Aidyn-A** [comment]
The issue comes from this line

https://github.com/pytorch/pytorch/blob/1eff853fdc91619ea24abf0cbd51ca992fe10c97/aten/src/ATen/native/cuda/AveragePool2d.cu#L62

where `(n * channels + c) * height * width` overflows. 
I will push a PR with the fix soon.
