### ISSUE TITLE
"compute_indices_weights_linear" not implemented for 'Half'

### ISSUE THREAD

**Issue by sankexin** [pytorch/pytorch#84040]
### 🐛 Describe the bug

from torch.nn import functional as F
x = F.interpolate(x, scale_factor=scale_factor,mode='bilinear', align_corners=False, recompute_scale_factor=False)
 

### Versions

tested：torch1.9-1.12：
when use model.half()，F.interpolate can not surport float16.

bug report：
Traceback (most recent call last):
  File "pth_to_pt_fp16.py", line 21, in <module>
    traced_script_module = torch.jit.trace(model, (src, *rec, downsample_ratio))
  File "/home/.conda/envs/rvm_fp16/lib/python3.8/site-packages/torch/jit/_trace.py", line 750, in trace
    return trace_module(
  File "/home/.conda/envs/rvm_fp16/lib/python3.8/site-packages/torch/jit/_trace.py", line 967, in trace_module
    module._c._create_method_from_trace(
  File "/home/.conda/envs/rvm_fp16/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/.conda/envs/rvm_fp16/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/matt_mobile/RobustVideoMatting/pth_to_pt/model/model.py", line 50, in forward
    src_sm = self._interpolate(src, scale_factor=downsample_ratio)
  File "/home/matt_mobile/RobustVideoMatting/pth_to_pt/model/model.py", line 77, in _interpolate
    x = F.interpolate(x, scale_factor=scale_factor),
  File "/home/.conda/envs/rvm_fp16/lib/python3.8/site-packages/torch/nn/functional.py", line 3938, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: "compute_indices_weights_linear" not implemented for 'Half'

**Comment by ngimel** [comment]
half support on CPU is very limited, and won't be extended.
