### ISSUE TITLE
DISABLED test_normalize_operator_exhaustive_where_cpu_float32 (__main__.TestNormalizeOperatorsCPU)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#84118]
Platforms: macos

Related to #84022, disabling this specific test that has run into this error with M1 specifically:
```
test_normalize_operator_exhaustive_where_cpu_float32 (__main__.TestNormalizeOperatorsCPU) ... Traceback (most recent call last):
File "/opt/homebrew/Caskroom/miniconda/base/envs/build/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
File "/opt/homebrew/Caskroom/miniconda/base/envs/build/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
     return forward_call(*input, **kwargs)
File "<eval_with_key>.23018", line 5, in forward
     where = torch.where(arg_0, arg_1, arg_2);  arg_0 = arg_1 = arg_2 = None
RuntimeError: where expected condition to be a boolean tensor, but got a tensor with dtype Float

Call using an FX-traced Module, line 5 of the traced Module's generated forward function:
def forward(self, arg_0, arg_1, arg_2):
     where = torch.where(arg_0, arg_1, arg_2);  arg_0 = arg_1 = arg_2 = None
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
     return where
```

**Comment by janeyx99** [comment]
Never mind, false alarm!
