### ISSUE TITLE
`linux-bionic-cuda10.2-py3.9-gcc7`  multigpu test are broken

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#84167]
### 🐛 Describe the bug

With the following signature:
```
 File "/var/lib/jenkins/workspace/test/distributed/test_c10d_gloo.py", line 2357, in test_work_wait_gpu
    self._test_work_wait(torch.ones(2, 2, device=self.rank) * self.rank)
  File "/var/lib/jenkins/workspace/test/distributed/test_c10d_common.py", line 1565, in _test_work_wait
    traced_fn.graph.print_tabular()
  File "/opt/conda/lib/python3.9/site-packages/torch/fx/graph.py", line 1237, in print_tabular
    print(tabulate(node_specs,
UnboundLocalError: local variable 'tabulate' referenced before assignment
 exiting process 0 with exit code: 10
ERROR:torch.testing._internal.common_distributed:Caught exception: 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 622, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 503, in wrapper
    fn()
  File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/distributed/test_c10d_gloo.py", line 2357, in test_work_wait_gpu
    self._test_work_wait(torch.ones(2, 2, device=self.rank) * self.rank)
  File "/var/lib/jenkins/workspace/test/distributed/test_c10d_common.py", line 1595, in _test_work_wait
    y = fn(x)
  File "/var/lib/jenkins/workspace/test/distributed/test_c10d_common.py", line 1554, in fn
    work.wait()
RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [172.17.0.2]:5258
 exiting process 1 with exit code: 10
Process 0 terminated with exit code 10, terminating remaining processes.
ERROR (5.020s)
    test_work_wait_gpu errored - num_retries_left: 3
```

### Versions

CI

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Last successful run: https://github.com/pytorch/pytorch/runs/8041300872?check_suite_focus=true
First failing run: https://github.com/pytorch/pytorch/runs/8044611438?check_suite_focus=true
Commits between those two runs:
61b9d8fccd  [Profiler][Trivial] Add null handling to `AppendOnlyList::copy` memcpy path. (#83963)
014a333df3 [Profiler][Minor] Extend Python bindings (#83622)
681c38704e [ONNX] Clean up patch functions (#83136)
ec5b83f768 Make allreduce compatible with fx ProxyTensor (#84126)
f93446adc2 Update proxy_tensor.py to support List input/output (#83302)
527a160169 Expose ProcessGroup::Work.wait() API to TorchScript (#83303)
c6348a7109 Add type hints to torch.save, torch.load (#83937)
582c0833d5 mac circleci workflows (#82780)

**Comment by malfet** [comment]
Tentatively reverting https://github.com/pytorch/pytorch/commit/ec5b83f76847584013a9cd4177d389a408033614 as most likely culprit
