### ISSUE TITLE
[ONNX] Export with export_modules_as_functions fails for ConvXd modules

### ISSUE THREAD

**Issue by bencherian** [pytorch/pytorch#84223]
### 🐛 Describe the bug

Exporting convolutions does not work if you set `export_modules_as_functions` to `True` when calling `torch.onnx.export`

```Python
import torch

example_module = torch.nn.Conv1d(3, 9, 3)
torch.onnx.export(example_module, (torch.ones(5, 3, 11),), "test.onnx", opset_version=16, export_modules_as_functions=True)
```

Error (from running above code in REPL):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in $
xport
    return utils.export(
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in exp$
rt
    _export(
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 1074, in _e$
port
    graph, params_dict, torch_out = _model_to_graph(
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 727, in _mo$
el_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 602, in _cr$
ate_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 517, in _tr$
ce_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/jit/_trace.py", line 1175, in _g$
t_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130$
 in _call_impl
    return forward_call(*input, **kwargs)
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in for$
ard
    graph, out = torch._C._create_graph_by_tracing(
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wra$
per
    outs.append(self.inner(*trace_inputs))
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1137$
 in _call_impl
    result = hook(self, input)
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 926, in _tr$
ck_module_attributes_forward_pre_hook
    setattr(module, attr_name, _get_module_attributes(module))
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 985, in _ge$
_module_attributes
    return {k: getattr(module, k) for k in annotations}
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/onnx/utils.py", line 985, in <di$
tcomp>
    return {k: getattr(module, k) for k in annotations}
  File "<redacted>/envs/athena_dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207$
 in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv1d' object has no attribute '_in_channels'
```

I believe this problem occurs because the Conv module sets `self.in_channels` in the constructor but the annotated attribute is named `self._in_channels`

### Versions

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (conda-forge gcc 10.4.0-16) 10.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-191-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla P100-PCIE-12GB
Nvidia driver version: 510.85.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.2
[pip3] torch==1.12.1
[pip3] torchdata==0.4.1
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] cudatoolkit               11.3.1              h9edb442_10    conda-forge
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.2           py38h3a7f9d9_0    conda-forge
[conda] pytorch                   1.12.1          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchdata                 0.4.1                    pypi_0    pypi

**Comment by justinchuby** [comment]
That's a good point

**Comment by justinchuby** [comment]
Let's try this
