### ISSUE TITLE
'Tensor' object has no attribute or method 'forward'

### ISSUE THREAD

**Issue by mhbassel** [pytorch/pytorch#84268]
### 🐛 Describe the bug

Hi everyone. I cloned the CLIP Repo https://github.com/openai/CLIP and my objective is to parse each model (since CLIP includes text encoder and image encoder) from CLIP on its own, script it and save it in order to deploy both models separately in Triton Server. So I adjusted the file `clip/model.py` a little bit, like adding two new classes CLIP_TEXT and CLIP_IMAGE and edited the `build_model` function. Also I wrote a script `get_encoder.py` to load the CLIP model and its state_dict, build the target model (using CLIP_TEXT or CLIP_IMAGE), load the corresponding state_dict keys then script it. Both scripts can be found here: https://gist.github.com/mhbassel/3f15cdd5c338b402eda66f927429eb3a, and the `get_encoder.py` script includes downloading a model from external link, so just you know.

When I run the `get_encoder.py` script I get the following error:
```
$ CUDA_VISIBLE_DEVICES=0 python get_encoder.py
Using cuda
Traceback (most recent call last):
  File "/media/ssdraid/training/clip/test/get_encoder.py", line 74, in <module>
    model_scripted = torch.jit.script(model)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 458, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 498, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 498, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 498, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 498, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 524, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/torch/jit/_recursive.py", line 375, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
'Tensor' object has no attribute or method 'forward'.:
  File "/media/ssdraid/training/clip/test/model.py", line 156
    def forward(self, x: torch.Tensor):
        orig_type = x.dtype
        ret = super().forward(x.type(torch.float32))
              ~~~~~~~~~~~~~ <--- HERE
        return ret.type(orig_type)
```

Can anyone please tell me how to solve it?

(There is a related issue in here: https://github.com/DiffEqML/torchdyn/issues/163)

Thank you very much in advance.

### Versions
```
Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.4 (main, Apr  8 2022, 17:35:13) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-1020-ibm-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.2.152
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce GTX 980 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.12.1
[pip3] torchvision==0.12.0
[conda] Could not collect
```

**Comment by gchanan** [comment]
Please use https://discuss.pytorch.org/ for questions.

**Comment by ptrblck** [comment]
Seems to be related to: https://github.com/pytorch/pytorch/issues/42885

**Comment by mhbassel** [comment]
Thank you @ptrblck again, just posting my workaround, I took it from the issue you mentioned, here again:

I changed this:
```
class LayerNorm(nn.LayerNorm):
    """Subclass torch's LayerNorm to handle fp16."""

    def forward(self, x: ResidualAttentionBlock):
        orig_type = x.dtype
        ret = super().forward(x.type(torch.float32))
        return ret.type(orig_type)
```
to this:
```
class LayerNorm(nn.Module):
    def __init__(self, *args, **kwargs):
        super(LayerNorm, self).__init__()
        self.inner_layernorm = nn.LayerNorm(*args, **kwargs)

    def forward(self, x: torch.Tensor):
        orig_type = x.dtype
        ret = self.inner_layernorm(x.type(torch.float32))
        return ret.type(orig_type)
```
and it worked.

**Comment by lizhou-cs** [comment]
> Thank you @ptrblck again, just posting my workaround I took it from the issue you mentioned here again:
> 
> I changed this:
> 
> ```
> class LayerNorm(nn.LayerNorm):
>     """Subclass torch's LayerNorm to handle fp16."""
> 
>     def forward(self, x: ResidualAttentionBlock):
>         orig_type = x.dtype
>         ret = super().forward(x.type(torch.float32))
>         return ret.type(orig_type)
> ```
> 
> to this:
> 
> ```
> class LayerNorm(nn.Module):
>     def __init__(self, *args, **kwargs):
>         super(LayerNorm, self).__init__()
>         self.inner_layernorm = nn.LayerNorm(*args, **kwargs)
> 
>     def forward(self, x: torch.Tensor):
>         orig_type = x.dtype
>         ret = self.inner_layernorm(x.type(torch.float32))
>         return ret.type(orig_type)
> ```
> 
> and it worked.

It solve my problem, thanks!
