### ISSUE TITLE
ImportError: symbol not found in flat namespace, when loading custom C++ extension on MAC OSX M1

### ISSUE THREAD

**Issue by fgrymula** [pytorch/pytorch#84339]
### 🐛 Describe the bug

I cannot compile custom C++ extensions on MAC OSX M1, even though, they are compiling on Linux without any problems. The problem occurs whether I use pip or conda installation of Torch, or compile it from source myself using llvm clang compiler. The error message for a compiled Torch reads as below:

```
(venv) m1@75bddaff-430f-4211-a9bc-6211b411517a ~ % python
Python 3.8.9 (default, Aug  3 2021, 19:21:54) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import custom_extensions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/m1/venv/lib/python3.8/site-packages/custom_extensions/__init__.py", line 2, in <module>
    import custom_extensions.ext
ImportError: dlopen(/Users/m1/venv/lib/python3.8/site-packages/custom_extensions/ext.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace (__ZNK2at10TensorBase8data_ptrIlEEPT_v)
```

I don't know what the symbol `ZNK2at10TensorBase8data_ptrIlEEPT_v` stands for, but I can observe that I can find it inside torch .so files in Linux environment:

```
franeg@81LK:~$ grep -r "ZNK2at10TensorBase8data_ptrIlEEPT_v" venv
grep: venv/lib/python3.8/site-packages/custom_extensions/ext.cpython-38-x86_64-linux-gnu.so: binary file matches
grep: venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so: binary file matches
grep: venv/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so: binary file matches
grep: venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so: binary file matches
grep: venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so: binary file matches
grep: venv/lib/python3.8/site-packages/torchvision/_C.so: binary file matches
```

and not in mac environment:

```
(venv) m1@75bddaff-430f-4211-a9bc-6211b411517a ~ % grep -r "ZNK2at10TensorBase8data_ptrIlEEPT_v" venv
Binary file venv/lib/python3.8/site-packages/custom_extensions/ext.cpython-38-darwin.so matches
```

Is there a way to identify what configuration (compiler, compiler version, environment variables) was used to build pip/conda Torch distributions for each OS to find out why do I lack anything in one OS vs the other OS?

I would appreciate any help regarding this topic, as well as suggestions on the source of the discrepancy between the two environments.

### Versions

Mac environment:

```
Collecting environment information...
PyTorch version: 1.13.0a0+gitb044e4c
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.24.1
Libc version: N/A

Python version: 3.8.9 (default, Aug  3 2021, 19:21:54)  [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-12.5.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==1.13.0a0+gitb044e4c
[conda] Could not collect
```

Configuration used for compiling Torch (1.13 nightly):
```
export CMAKE_PREFIX_PATH=/Users/m1/venv
export CC=/opt/homebrew/opt/llvm@13/bin/clang
export CXX=/opt/homebrew/opt/llvm@13/bin/clang++
export USE_MPS=ON
export USE_PYTORCH_METAL=ON
export USE_METAL=ON
export USE_QNNPACK=OFF
export USE_CUDA=OFF
export USE_MAGMA=OFF
```

Compiler used for both Torch and custom extensions:

```
(venv) m1@75bddaff-430f-4211-a9bc-6211b411517a ~ % /opt/homebrew/opt/llvm@13/bin/clang --version
Homebrew clang version 13.0.1
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm@13/bin
```

**Comment by fgrymula** [comment]
The bug is fixed by using int64_t instead long in the extension C++ code, exactly like [here](https://github.com/NVIDIA/MinkowskiEngine/pull/438).
