### ISSUE TITLE
[JIT] Better support tensor constructors (e.g. zeros, ones) under tracing

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8443]
Example code:

```
import torch

def test_ctors(x):
    y = torch.zeros(x.size(0))
    return y

traced = torch.jit.trace(torch.rand(3, 4, 5))(test_ctors)
print(traced.__getattr__('forward').graph)
```

Fails with:

```
Traceback (most recent call last):
  File "constructors.py", line 7, in <module>
    traced = torch.jit.trace(torch.rand(3, 4, 5))(test_ctors)
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/jit/__init__.py", line 308, in wrapper
    return torch._C.GraphExecutor(func, args, **executor_options)
RuntimeError: /Users/jamesreed/onnx-fairseq/pytorch/torch/csrc/jit/tracer.h:150: getTracingState: Assertion `state` failed.
```

Inventory of ops like this (feel free to add more):
- [x] zeros
- [x] ones
- [x] arange
- [x] randn_like

**Comment by zou3519** [comment]
Can we haz torch.tensor support too?
