### ISSUE TITLE
[make_fx] Expected behavior? Resulting FX graph not scriptable.

### ISSUE THREAD

**Issue by silvasean** [pytorch/pytorch#84494]
### 🐛 Describe the bug

In general, I have found FX graphs to be scriptable, but I found a case that it is not. Since FX graphs don't have control flow, tracing them seems to work just fine too, so this isn't a big deal, except that tracing burns in the shapes into the graph, making it unsuitable for dynamic shapes (in Torch-MLIR we have a hacky option `ignore_traced_shapes` to work around this :/ [link](https://github.com/llvm/torch-mlir/blob/51c868f4c0f79e8d4960b03cf8fbea2cbcc3408b/python/torch_mlir/__init__.py#L157)).

I'm just curious if this is intended behavior.

```python
import torch
from torch.fx.experimental.proxy_tensor import make_fx

def f(x):
    return x * 2

input = torch.randn([1, 12])
torch.jit.script(make_fx(f)(input))
```

Output:
```
Traceback (most recent call last):
  File "/tmp/repro2.py", line 8, in <module>
    torch.jit.script(make_fx(f)(input))
  File "/usr/local/google/home/silvasean/pg/torch-mlir/it.venv/lib/python3.10/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/usr/local/google/home/silvasean/pg/torch-mlir/it.venv/lib/python3.10/site-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/usr/local/google/home/silvasean/pg/torch-mlir/it.venv/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/usr/local/google/home/silvasean/pg/torch-mlir/it.venv/lib/python3.10/site-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
attribute lookup is not defined on builtin:
  File "<eval_with_key>.0", line 5
def forward(self, x_1):
    mul_tensor = torch.ops.aten.mul.Tensor(x_1, 2);  x_1 = None
                 ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return mul_tensor
```

### Versions

torch                   1.13.0.dev20220830+cpu

cc @ezyang @SherlockNoMad @soumith

**Comment by ngimel** [comment]
You need to strip overloads to make it scriptable:
```
from functorch._src.compile_utils import strip_overloads
fx_g = make_fx(f)(input)
strip_overloads(fx_g)
scripted=torch.jit.script(fx_g)
```
This (and a few more niceties) are automatically done if you use `ts_compiler` in `functorch/_src/compilers` on your GraphModule.

**Comment by silvasean** [comment]
Thanks! Closing this.
