### ISSUE TITLE
internal assert failed: translate_exception_to_python called with invalid exception pointer when attempting to utilize CUDA with Wine

### ISSUE THREAD

**Issue by Martmists-GH** [pytorch/pytorch#84518]
### 🐛 Describe the bug

When running python under wine, the GPU seems to be unavailable due to an internal error, even if the GPU does support CUDA.

```py
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.zeros(1).cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: e_ptr INTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\builder\\windows\\pytorch\\torch\\csrc\\Exceptions.cpp":147, please report a bug to PyTorch. translate_exception_to_python called with invalid exception pointer
```

Method of installing:
```py
pip install torch
```

### Versions

Wine:
```
Collecting environment information...
PyTorch version: 1.12.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Could not collect
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19043-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==1.12.1
[conda] Could not collect
```
Host:
```
Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 12.2.0
Clang version: 14.0.6
CMake version: version 3.24.1
Libc version: glibc-2.36

Python version: 3.9.7 (default, Mar 12 2022, 16:10:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.6-zen1-1-zen-x86_64-with-glibc2.36
Is CUDA available: True
CUDA runtime version: 11.7.99
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1050 Ti
Nvidia driver version: 515.49.10
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.12.1
[conda] Could not collect
```

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by zou3519** [comment]
I am not sure we support this mode of operation (running Pytorch under WINE)

**Comment by malfet** [comment]
We do not test/plan to test that PyTorch for Windows works under wine, but would consider a non-intrusive PR that fixes the issue.

**Comment by Xom** [comment]
Are you using wine-staging? CUDA support is only in wine-staging. If you use wine-staging and torch still thinks CUDA is unavailable, then try this patch that hasn't yet made it to github: https://bugs.winehq.org/show_bug.cgi?id=52689

For me, torch does think CUDA is available, but when it tries to do math, it fails:
```
data:   0%| <lots of spaces> | 0/1 [00:08<?, ?it/s]
Sampling:   0%| <lots of spaces> | 0/1 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "txt2img.py", line 337, in <module>
  File "txt2img.py", line 288, in main
  File "torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "ldm\models\diffusion\plms.py", line 91, in sample
    self.make_schedule(ddim_num_steps=S, ddim_eta=eta, verbose=verbose)
  File "ldm\models\diffusion\plms.py", line 45, in make_schedule
    ddim_sigmas, ddim_alphas, ddim_alphas_prev = make_ddim_sampling_parameters(alphacums=alphas_cumprod.cpu(),
  File "ldm\modules\diffusionmodules\util.py", line 69, in make_ddim_sampling_parameters
    sigmas = eta * np.sqrt((1 - alphas_prev) / (1 - alphas) * (1 - alphas / alphas_prev))
  File "torch\_tensor.py", line 31, in wrapped
    return f(*args, **kwargs)
  File "torch\_tensor.py", line 610, in __rdiv__
    return self.reciprocal() * other
RuntimeError: e_ptrINTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\builder\\windows\\pytorch\\torch\\csrc\\Exceptions.cpp":167, please report a bug to PyTorch. translate_exception_to_python called with invalid ex
ception pointer
[280] Failed to execute script 'txt2img' due to unhandled exception!
```
I'd like to understand exactly what happens when .reciprocal() is called.

**Comment by iremyux** [comment]
@Martmists-GH , PyTorch for Windows under Wine is presently not supported, and there are no immediate plans for its support. Could you please share your reason for attempting to use it and your specific requirements? This information would help us understand your needs better.

**Comment by seemethere** [comment]
Given this is a fairly rare use case and the fact that the Windows team is not going to look into this I'm going to go ahead and close this issue.

Feel free to utilize this thread for discussion and potentially link a fix if one does come from OSS contributions!
