### ISSUE TITLE
MPS backend appears to be limited to 32 bits

### ISSUE THREAD

**Issue by peardox** [pytorch/pytorch#84520]
### 🐛 Describe the bug

Create a large job for MPS to work on and we hit an inbuilt limit that bombs out with...

/AppleInternal/Library/BuildRoots/20d6c351-ee94-11ec-bcaf-7247572f23b4/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:705: failed assertion `[MPSTemporaryNDArray initWithDevice:descriptor:] Error: product of dimension sizes > 2**31'

This only occurs on MPS, I can easily run larger jobs on Cuda

### Versions

Not overly helpful...

Collecting environment information...
Traceback (most recent call last):
  File "/Users/ec2-user/Library/Lartis/collect_env.py", line 492, in <module>
    main()
  File "/Users/ec2-user/Library/Lartis/collect_env.py", line 475, in main
    output = get_pretty_env_info()
  File "/Users/ec2-user/Library/Lartis/collect_env.py", line 470, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/Users/ec2-user/Library/Lartis/collect_env.py", line 319, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "/Users/ec2-user/Library/Lartis/collect_env.py", line 301, in get_pip_packages
    out = run_with_pip(sys.executable + ' -mpip')
  File "/Users/ec2-user/Library/Lartis/collect_env.py", line 289, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'

**Comment by junukwon7** [comment]
Maybe #84039?

The error seems to be a metal one, and not sure if torch devs would be able to fix it :(

**Comment by kulinseth** [comment]
@peardox please see this [link](https://github.com/pytorch/pytorch/issues/84039#issuecomment-1252680624) for more details.  Can you please provide a use-case or network where you need more that 32-bit support. And we can prioritize for that support.

**Comment by peardox** [comment]
@kulinseth I found this issue using the PyTorch example FNS https://github.com/pytorch/examples/tree/main/fast_neural_style on a M1 Mac. Simply try using that to style an image that's 4kx4k* or larger

I discovered this by writing some code that does a binary search to identify the largest image FNS will run for a given target (it works really well on NVidia GPUs). Basically generate an NxN test image then double its size until it breaks then search N for largest working test image. As GPUs come with different quantities of RAM the largest image a FNS can process is dependent on the available GPU RAM.

Apple M1's, however, use Unified Memory so you could get a machine with > 64 GB (M2s anyway) usable RAM - smaller memory devices will use swap anyway. MPS will prevent the possible styling of an image > 4kx4k* owing to the 32 bit limitation.

* The 4k test was done using a 32 channel FNS model, reducing the number of channels would increase the possible image size (and speed of compute). I think that's the threshold - I'll double check next time I have one running - I seem to remember 4096 being the problem - I'll try it in the next few days (need to run up an AWS M1 to check as I don't possess Apple ARM64)

**Comment by kulinseth** [comment]
@peardox , thanks for providing the use case and trying the experiment. This is indeed helpful.
Just to provide more details on the 32-bit limit in the FW. Its un-related to the Unified memory design but I understand how having more memory allows us to try bigger images, more channels and bigger batch sizes for training. That is indeed an advantage. 

There are architectural differences in HW between 32-bit & 64-bit rate in how computation is performed. For optimization and increased throughput we use 32-bit indexing in our kernels which works well for most scenarios. Moving this to 64-bit will have impact on performance and needs to be done carefully. 

For now, I would recommend if you can limit the images which can fit within the 32-bit computation. I have made a note of this request and will update here if things change.

**Comment by peardox** [comment]
I've already set a limit for MPS Macs - I will improve the limitation though as it appears it depends on image area (not height or width) so while the max square might be 4k you could still process a >4k wide image if it's height was within H x W < 4k x 4k

**Comment by wenbei2006** [comment]
Does latest M2-Chip Mac have this limitation?

**Comment by openSourcerer9000** [comment]
@kulinseth Wait this was a deliberate _decision_ to add this bug??? Apple is making Mac's with 512 GB of unified RAM but only letting us use 4GB of that? 

What is the use case? _Doing anything with the available RAM._ 

 - Run this model AT ALL https://huggingface.co/hunyuanvideo-community/HunyuanVideo-I2V
 - Run SD 3.5 Large with a decently high batch size
 - Train any model with a batch size greater than... well, zero

It should be illegal to market a device with one spec and then software lock it to only use less than 1% of that. This may be the most egregious bug in all of software history.
