### ISSUE TITLE
torch.jit.script IndentationError: unexpected indent

### ISSUE THREAD

**Issue by vemusharan** [pytorch/pytorch#84588]
### 🐛 Describe the bug

```
import torch
import torchvision
import torchvision.models as models
import torch.nn as nn
from torch.utils.mobile_optimizer import optimize_for_mobile

class ModifiedResNet18Model(torch.nn.Module):
	def __init__(self):
		super(ModifiedResNet18Model, self).__init__()
		model = models.resnet18(pretrained=True)
		modules = list(model.children())[:-1]      
		model = nn.Sequential(*modules)
		self.features = model

		for param in self.features.parameters():
			param.requires_grad = False

		self.fc = nn.Sequential(
			nn.Dropout(),
			nn.Linear(512,1024),
			nn.ReLU(inplace=True),
                        nn.Dropout(),
			nn.Linear(1024,512),
			nn.ReLU(inplace=True),
			nn.Linear(512, 4))
	
	def forward(self, x):
		x = self.features(x)
		x = nn.functional.adaptive_avg_pool2d(x, 1).reshape(x.shape[0], -1)
		x = self.fc(x)
		return x
		
		

model = ModifiedResNet18Model()
print(model)
model_scripted = torch.jit.script(model) # thowing the error
opti_model = optimize_for_mobile(model_scripted)
opti_model._save_for_lite_interpreter("resnet4.ptl")
print('Create Model Success')



```

### Versions

Torch  Version: 1.11.0+cu113
TorchVision  Version: 0.12.0+cu113

**Error** 
Traceback (most recent call last):
  File "C:\Users\Visionhealth\Desktop\Experiment_3\onlyforpruning\testtorchscript.py", line 37, in <module>
    model_scripted = torch.jit.script(model)
  File "C:\Users\Visionhealth\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\jit\_script.py", line 1265, in script
    return torch.jit._recursive.create_script_module(
  File "C:\Users\Visionhealth\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\jit\_recursive.py", line 453, in create_script_module
    AttributeTypeIsSupportedChecker().check(nn_module)
  File "C:\Users\Visionhealth\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\jit\_check.py", line 74, in check
    init_ast = ast.parse(textwrap.dedent(source_lines))
  File "C:\Users\Visionhealth\AppData\Local\Programs\Python\Python310\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    def __init__(self):
IndentationError: unexpected indent

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
