### ISSUE TITLE
make_fx fails under TorchRefsMode context

### ISSUE THREAD

**Issue by jjsjann123** [pytorch/pytorch#84734]
### 🐛 Describe the bug

Run into this issue with torchdynamo/benchmarks/huggingface.py with a custom stack (nvprim).

Tried to get a small repro but failed. However, I did manage to get a different failure in this small example vvv:
```
import torch

x = torch.empty(1024, 1, device="cuda")
target = torch.empty(1024, device="cuda").long()

def func(x, target, index):
    nll_loss_forward = torch.ops.aten.nll_loss_forward.default(x, target, None, 1, index)

from torch.fx.experimental.proxy_tensor import make_fx

from torch._decomp import get_decompositions
decomp_table = get_decompositions({torch.ops.aten.nll_loss_forward})
gm = make_fx(func, decomposition_table=decomp_table)(x, target, 512)  # tracing with decomposition works
print(gm.graph)

from torch._prims.context import TorchRefsMode
with TorchRefsMode():
    gm = make_fx(func)(x, target, 512)  # somehow tracing here with decomposition breaks.
    print(gm.graph)
```
Output
```
graph():
    %x_1 : [#users=1] = placeholder[target=x_1]
    %target_1 : [#users=3] = placeholder[target=target_1]
    %index_1 : [#users=0] = placeholder[target=index_1]
    %unsqueeze : [#users=1] = call_function[target=torch.ops.aten.unsqueeze.default](args = (%target_1, 1), kwargs = {})
    %gather : [#users=1] = call_function[target=torch.ops.aten.gather.default](args = (%x_1, 1, %unsqueeze), kwargs = {})
    %squeeze : [#users=1] = call_function[target=torch.ops.aten.squeeze.dim](args = (%gather, 1), kwargs = {})
    %neg : [#users=1] = call_function[target=torch.ops.aten.neg.default](args = (%squeeze,), kwargs = {})
    %ne : [#users=1] = call_function[target=torch.ops.aten.ne.Scalar](args = (%target_1, 512), kwargs = {})
    %scalar_tensor : [#users=1] = call_function[target=torch.ops.aten.scalar_tensor.default](args = (0,), kwargs = {dtype: torch.float32, layout: torch.strided, device: cuda:0})
    %where : [#users=1] = call_function[target=torch.ops.aten.where.self](args = (%ne, %neg, %scalar_tensor), kwargs = {})
    %ne_1 : [#users=1] = call_function[target=torch.ops.aten.ne.Scalar](args = (%target_1, 512), kwargs = {})
    %sum_1 : [#users=1] = call_function[target=torch.ops.aten.sum.default](args = (%ne_1,), kwargs = {})
    %_to_copy : [#users=1] = call_function[target=torch.ops.aten._to_copy.default](args = (%sum_1,), kwargs = {dtype: torch.float32, device: cuda:0})
    %sum_2 : [#users=1] = call_function[target=torch.ops.aten.sum.default](args = (%where,), kwargs = {})
    %div : [#users=0] = call_function[target=torch.ops.aten.div.Tensor](args = (%sum_2, %_to_copy), kwargs = {})
    return None
Traceback (most recent call last):
  File "/jiej/playground/repro_control_flow.py", line 19, in <module>
    gm = make_fx(func)(x, target, 512)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 622, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 392, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/pytorch/pytorch/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 406, in wrapped
    out = f(*tensors)
  File "/jiej/playground/repro_control_flow.py", line 7, in func
    nll_loss_forward = torch.ops.aten.nll_loss_forward.default(x, target, None, 1, index)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/overrides.py", line 1778, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims/context.py", line 187, in __torch_function__
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_decomp/decompositions.py", line 1740, in nll_loss_forward
    total_weight = (target != ignore_index).sum().to(self)
  File "/opt/pytorch/pytorch/torch/overrides.py", line 1778, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims/context.py", line 187, in __torch_function__
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_refs/__init__.py", line 1697, in to
    return prims.convert_element_type(a, dtype)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/overrides.py", line 1778, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims/context.py", line 168, in __torch_function__
    return orig_func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: prims::convert_element_type() Expected a value of type 'int' for argument 'dtype' but instead found type 'Tensor'.
Position: 1
Value: tensor([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], device='cuda:0')
Declaration: prims::convert_element_type(Tensor a, int dtype) -> Tensor
Cast error details: Unable to cast Python instance to C++ type (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)
```

The original error I'm getting is `It appears that you're trying to get value out of a tracing tensor - erroring out! It's likely that this is caused by data-dependent control flow or similar.`
which seems to be originated from tracing with decomposition inside `TorchRefsNvfuserCapabilityMode`

To repro the original issue: running with torchdynamo code from here: https://github.com/IvanYashchuk/torchdynamo/tree/nvprims-backend
run it with `python benchmarks/huggingface.py --training -d cuda --fast --nvprims-nvfuser --skip-accuracy-check --generate-aot-autograd-stats --dump-raw-metrics --float32 -k AlbertForQuestionAnswering`

### Versions

Running with pytorch
```
commit 9addeccb6b1ec9fed0246ba18fdb70550c813a90 (HEAD, origin/master, origin/HEAD, master)
Author: kshitij12345 <kshitijkalambarkar@gmail.com>
Date:   Thu Sep 8 06:23:12 2022 +0000

    [functorch] vmapvjpvjp (re-enable test with skips and xfails) (#83999)
    
    Enable `vmapvjpvjp` test and add relevant skips and xfails.
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/83999
    Approved by: https://github.com/zou3519
```

torchdynamo commit
```
commit cad8185c937f2396ba1c683b86844c0248f2f538 (ivan/nvprims-backend)
Merge: dcd88d1 11873be
Author: Ivan Yashchuk <ivan.yashchuk@aalto.fi>
Date:   Thu Sep 1 10:13:19 2022 +0300

    Merge remote-tracking branch 'upstream/main' into nvprims-backend
```

cc @ezyang @mruberry @ngimel @SherlockNoMad @soumith

**Comment by jjsjann123** [comment]
cc'ing @IvanYashchuk @kevinstephano @rdspring1

**Comment by jjsjann123** [comment]
To clarify, #84735 is NOT a proper solution. I started that PR so we can at least avoid similar failures in torchbench. But there's probably some sharp corner in our tracing that we should get it properly fixed.

**Comment by ezyang** [comment]
I still think y'all should be using TorchRefsMode to do decompositions...

**Comment by kevinstephano** [comment]
What is the alternative design?

**Comment by jjsjann123** [comment]
> I still think y'all shouldn't be using TorchRefsMode to do decompositions...

hahaha, you are probably right from the beginning. But I don't know enough to comment on this, I'll let @IvanYashchuk make the right call~~

**Comment by IvanYashchuk** [comment]
Here's what really happens:
```py
import torch
from torch._prims.context import TorchRefsMode
a = torch.randn(3, 3, device='cuda')
b = torch.randn(3, 3, device='cuda')

def func(a, b):
    return a.to(b)
with TorchRefsMode():
    func(a, b)
```
```py
RuntimeError: prims::convert_element_type() Expected a value of type 'int' for argument 'dtype' but instead found type 'Tensor'.
Position: 1
Value: tensor([[-0.0440, -0.6463, -1.2029],
        [ 0.8581, -0.1144, -0.2697],
        [ 0.3353,  0.1361, -1.8018]], device='cuda:0')
Declaration: prims::convert_element_type(Tensor a, int dtype) -> Tensor
Cast error details: Unable to cast Python instance to C++ type (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)
```
It's not a problem with `TorchRefsMode()` it's a problem with `torch._refs.to`. There are tests that are supposed to verify calling `tensor.to(tensor)`:
https://github.com/pytorch/pytorch/blob/6f72c13f9b749b28b91732a56e997b25aa692a8d/torch/testing/_internal/common_methods_invocations.py#L3904-L3912
And there's an issue for implementing this: https://github.com/pytorch/pytorch/issues/84264.

Closing as duplicate.

**Comment by ezyang** [comment]
@kevinstephano The majority of decomps could be applied via the decompositions table that proxy tensor tracing respects (or you can apply yourself in a TorchDispatchMode). The key is that the decomposition happens later; instead of forcing yourself to accurately handle all Python frontend quirks, you can decompose after it's gotten through the Python arg parser and gotten normalized.

**Comment by IvanYashchuk** [comment]
PrimTorch targets implementing references for all Python frontend quirks. And we are working towards supporting PrimTorch.

There's a nice feature that for operations that overlap in ATen and Python's PyTorch it's possible to register the reference implementations to the decomposition table of `torch._decomp`. So that TorchDispatchMode users can benefit from increased PrimTorch coverage of references.
https://dev-discuss.pytorch.org/t/tracing-with-primitives-update-2/645#registering-python-references-as-decompositions-7

The requirement to support aten->refs mapping is a temporary workaround because backward rules are not yet implemented for prims and AOT Autograd produces a graph with `torch.ops.aten` calls by default. Soon when prims gain backward support we won't need aten->refs mapping.

Thank you, I've heard multiple times how targeting internal ATen CompositeExplicitAutograd functions is great. I will stick with PrimTorch though, supporting Python's user-facing interface, and I will not pivot towards making "ATen CompositeExplicitAutograd" (`torch._decomp.decomposition_table`) the primary target for nvFuser execution.
