### ISSUE TITLE
test_model_dump fails

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#84745]
### 🐛 Describe the bug

The Test fails because the file is empty at the time it is read.

Reproducer (on some systems):  `python test_model_dump.py`

Output:
```
======================================================================
ERROR: test_main (__main__.TestModelDump)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/s3248973-EasyBuild/PyTorch/1.10.0/foss-2021a/pytorch/test/test_model_dump.py", line 136, in test_main
    torch.utils.model_dump.main(
  File "/tmp/easybuild-tmp/eb-nHWk65/tmpCyeXsf/lib/python3.9/site-packages/torch/utils/model_dump/__init__.py", line 377, in main
    info = get_model_info(args.model, title=args.title)
  File "/tmp/easybuild-tmp/eb-nHWk65/tmpCyeXsf/lib/python3.9/site-packages/torch/utils/model_dump/__init__.py", line 205, in get_model_info
    with zipfile.ZipFile(path_or_file) as zf:
  File "/sw/installed/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "/sw/installed/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

----------------------------------------------------------------------
Ran 9 tests in 0.213s

FAILED (errors=1, skipped=3)

```

### Versions

PyTorch 1.10.0 and current master

**Comment by george-qi** [comment]
Thanks for creating the PR to fix this!
