### ISSUE TITLE
test_quantization fails when build without FBGEMM

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#84748]
### 🐛 Describe the bug

When PyTorch is build without FBGEMM the `test_embedding_bag_byte_unpack` fails showing a bug in the implementation (I'll open a PR fixing that)

This happens e.g. on POWER platforms where FBGEMM is not available at all, but I assume it also happens when manually disabling FBGEMM when building PyTorch.

Reproducer: `python test_quantization.py -- TestQuantizedEmbeddingOps.test_embedding_bag_byte_unpack`

Output:
```
Falsifying example: test_embedding_bag_byte_unpack(
    num_embeddings=10,
    embedding_dim=8,
    num_batches=2,
    data_type=numpy.float16,
    self=<quantization.core.test_quantized_op.TestQuantizedEmbeddingOps testMethod=test_embedding_bag_byte_unpack>,
)
F
======================================================================
FAIL: test_embedding_bag_byte_unpack (quantization.core.test_quantized_op.TestQuantizedEmbeddingOps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/s3248973-EasyBuild/PyTorch/1.10.0/foss-2021a/pytorch/test/quantization/core/test_quantized_op.py", line 3313, in test_embedding_bag_byte_unpack
    embedding_dim=st.integers(5, 50).filter(lambda x: x % 4 == 0),
  File "/sw/installed/hypothesis/6.13.1-GCCcore-10.3.0/lib/python3.9/site-packages/hypothesis/core.py", line 1169, in wrapped_test
    raise the_error_hypothesis_found
  File "/dev/shm/s3248973-EasyBuild/PyTorch/1.10.0/foss-2021a/pytorch/test/quantization/core/test_quantized_op.py", line 3320, in test_embedding_bag_byte_unpack
    self._test_embedding_bag_unpack_fn(
  File "/dev/shm/s3248973-EasyBuild/PyTorch/1.10.0/foss-2021a/pytorch/test/quantization/core/test_quantized_op.py", line 3307, in _test_embedding_bag_unpack_fn
    np.testing.assert_allclose(w_packed.numpy(), w_packed_c2.numpy(), atol=1e-6, rtol=1e-6)
  File "/sw/installed/SciPy-bundle/2021.05-foss-2021a/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/sw/installed/SciPy-bundle/2021.05-foss-2021a/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 842, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=1e-06

Mismatched elements: 14 / 320 (4.38%)
Max absolute difference: 193
Max relative difference: 26.71428571
 x: array([[[  0,   0,   0,   0, 192, 222, 194, 255,  19,  19, 243,  59,
           0,   0,   0,   0],
        [255,  89, 206, 131, 142, 244,   0,   4, 101, 101, 101,  59,...
 y: array([[[ 68, 159,  97,  66,   0, 121,   7, 255, 112, 112, 240,  58,
           0,  64, 182,  63],
        [255,  89, 206, 131, 142, 244,   0,   4, 101, 101, 101,  59,...

----------------------------------------------------------------------
Ran 1 test in 0.655s

FAILED (failures=1)
```

### Versions

Affected is PyTorch 1.10.0+ due to this issue introduced by https://github.com/pytorch/pytorch/pull/64081

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by george-qi** [comment]
Thanks for fixing this, appreciate it!
