### ISSUE TITLE
segfault in pytorch while exiting python interpreter

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#84756]
### 🐛 Describe the bug

Put `import torch` into a file. Run it. It results in a segfault on my local machine. The stack trace looks like the following:
```

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) up
#1  0x00007ffff7c58859 in __GI_abort () at abort.c:79
79      abort.c: No such file or directory.
(gdb) up
#2  0x00007fffe0f7735a in __cxxabiv1::__terminate (handler=<optimized out>)
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
48      /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_terminate.cc: No such file or directory.
(gdb) up
#3  0x00007fffe0f773c5 in std::terminate () at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
58      in /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_terminate.cc
(gdb) up
#4  0x00007fffe0f780fd in __cxxabiv1::__cxa_pure_virtual () at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/pure.cc:50
50      /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/pure.cc: No such file or directory.
(gdb) up
#5  0x00007fffefdba719 in c10::SafePyObject::~SafePyObject (this=0x555558eaea48, __in_chrg=<optimized out>) at /raid/rzou/pt/fresh/c10/core/SafePyObject.h:32
32          (*pyinterpreter_)->decref(data_, /*is_tensor*/ false);
(gdb) up
#6  0x00007ffff0599fd0 in torch::impl::dispatch::PythonKernelHolder::~PythonKernelHolder (this=0x555558eaea30, __in_chrg=<optimized out>)
    at /raid/rzou/pt/fresh/torch/csrc/utils/python_dispatch.cpp:60
60      class PythonKernelHolder : public c10::OperatorKernel {
(gdb) up
#7  0x00007ffff0599ffc in torch::impl::dispatch::PythonKernelHolder::~PythonKernelHolder (this=0x555558eaea30, __in_chrg=<optimized out>)
    at /raid/rzou/pt/fresh/torch/csrc/utils/python_dispatch.cpp:60
60      class PythonKernelHolder : public c10::OperatorKernel {
(gdb) up
#8  0x00007fffe69cfa34 in c10::intrusive_ptr<c10::OperatorKernel, c10::detail::intrusive_target_default_null_type<c10::OperatorKernel> >::reset_ (
    this=0x555555ae0bf8) at /raid/rzou/pt/fresh/c10/util/intrusive_ptr.h:291
291             delete target_;
(gdb) quit
```

I verified this happens in a fresh conda installation and a fresh pytorch installation. I've been trying to bisect, but all older versions I've been building seem to have this problem. Possibly a problem with the environment setup, but posting this here just in case there are others who run into it.

### Versions

master

**Comment by zou3519** [comment]
Reverting https://github.com/pytorch/pytorch/pull/84657 fixed the problem for me
