### ISSUE TITLE
Retrocompatibility issue for batchnorm

### ISSUE THREAD

**Issue by Cerbal** [pytorch/pytorch#8481]
Modules created in pytorch v0.4 are not loadable in pytorch master. 
```
        Missing key(s) in state_dict: "batchnorm.num_batches_tracked". 
```

### Minimal code to reproduce:
**Within pytorch 0.4**

Module
``` python
class MyModule(nn.Module):
    """
        Create a toy module with just one batch norm
    """

    def __init__(self):
        super(MyModule, self).__init__()
        self.batchnorm = nn.BatchNorm1d(10)

    def forward(self, inputs):
        return self.batchnorm(inputs)
```

Save the model
```python
model = MyModule()
state_dict = model.state_dict()
torch.save(state_dict, "state_dict.mdl")
```

**Within pytorch master**

```python
state_dict = torch.load("state_dict.mdl")
model = MyModule()
model.load_state_dict(state_dict)
```

Observe:
```
Traceback (most recent call last):
  File "load.py", line 10, in <module>
    model.load_state_dict(state_dict)
  File "/private/home/samuelhumeau/.conda/envs/pytorch-sources/lib/python3.6/site-packages/torch/nn/modules/module.py", line 698, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MyModule:
        Missing key(s) in state_dict: "batchnorm.num_batches_tracked". 
```

### Educated guess of what is going on

```
>>> print(state_dict._metadata)
OrderedDict([('', {'version': 1}), ('batchnorm', {'version': 1})])
```

[This line](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/batchnorm.py#L79 ) seems to only deal with the case where the version is None though.

**Comment by SsnL** [comment]
https://github.com/pytorch/pytorch/pull/6445 didn't bump version. we should fix this.
