### ISSUE TITLE
[FX] How to replace torch.functional with nn.module? TypeError: forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by Tonyhao96** [pytorch/pytorch#84923]
### 🐛 Describe the bug

I would like to use `torch.fx` to replace `toirch.functional` into `nn.module` for further model optimization.

Example:
```Python
# Original
F.adaptive_avg_pool2d(x, 1)
# Target
nn.AdaptiveAvgPool2d(1)
```

Here is my code:

```Python
with model.graph.inserting_before(node):
    new_module_str = str(node._prev).split('_')[0] + ".adaptive_avg_pool2d"
    model.add_submodule(new_module_str, nn.AdaptiveAvgPool2d(node.args[1:]))
    new_node = model.graph.call_module(new_module_str, node.args)
    node.replace_all_uses_with(new_node)
model.graph.erase_node((node))
```

The generated model can be recompiled through fx 
```Python
...
  (conv1): Module(
    (0): Conv2d(320, 1280, kernel_size=(1, 1), stride=(1, 1), B=1)
    (1): BatchNorm2d(1280, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True, B=1)
    (2): ReLU6(inplace=True)
    (adaptive_avg_pool2d): AdaptiveAvgPool2d(output_size=(1,))
  )
  (conv2): Conv2d(1280, 10, kernel_size=(1, 1), stride=(1, 1), B=1)

...
    conv1_0 = getattr(self.conv1, "0")(stage7_residual_7);  stage7_residual_7 = None
    conv1_1 = getattr(self.conv1, "1")(conv1_0);  conv1_0 = None
    conv1_2 = getattr(self.conv1, "2")(conv1_1);  conv1_1 = None
    conv1_adaptive_avg_pool2d = self.conv1.adaptive_avg_pool2d(conv1_2, 1);  conv1_2 = None
    conv2 = self.conv2(conv1_adaptive_avg_pool2d);  conv1_adaptive_avg_pool2d = None
    flatten_replacement = hydro_fx_fuse_flatten_replacement(conv2, 1);  conv2 = None
    return flatten_replacement
```

but can not train:
```bash
Traceback (most recent call last):
  File "/home/xxx/cifar_fuse.py", line 148, in <module>
    train_result = train_epoch(train_loader, model, criterion, optimizer)
  File "/home/xxx/cifar_fuse.py", line 102, in train_epoch
    pred = model(X)
  File "/home/xxx/miniconda3/lib/python3.9/site-packages/torch/fx/graph_module.py", line 652, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/xxx/miniconda3/lib/python3.9/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/home/xxx/miniconda3/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/xxx/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.3", line 157, in forward
  File "/home/xxx/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
```

### Versions

Version: Pytorch 1.12.1

cc @ezyang @SherlockNoMad @soumith

**Comment by vadimkantorov** [comment]
probably `new_node = model.graph.call_module(new_module_str, node.args)` here should be `ew_node = model.graph.call_module(new_module_str, node.args[:1])`?

**Comment by Tonyhao96** [comment]
Thanks! @vadimkantorov
