### ISSUE TITLE
MacOS nightly wheel build is broken

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#85007]
### 🐛 Describe the bug

We have macos nightly builds broken.
Ref: https://hud.pytorch.org/hud/pytorch/pytorch/nightly
Failure:
https://github.com/pytorch/pytorch/actions/runs/3050769788/jobs/4918237006

During running delocate step:
```
ERROR:delocate.libsana:
@rpath/libtorch_python.dylib not found:
  Needed by: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
  Search path:
    /Users/runner/work/_temp/anaconda/envs/wheel_py310/lib
    @loader_path
ERROR:delocate.libsana:
@rpath/libtorch.dylib not found:
  Needed by: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
  Search path:
    /Users/runner/work/_temp/anaconda/envs/wheel_py310/lib
    @loader_path
ERROR:delocate.libsana:
@rpath/libtorch_cpu.dylib not found:
  Needed by: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
  Search path:
    /Users/runner/work/_temp/anaconda/envs/wheel_py310/lib
    @loader_path
ERROR:delocate.libsana:
@rpath/libc10.dylib not found:
  Needed by: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
  Search path:
    /Users/runner/work/_temp/anaconda/envs/wheel_py310/lib
    @loader_path
ERROR:delocate.libsana:
@rpath/libtorch_python.dylib not found:
  Needed by: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
  Search path:
    /Users/runner/work/_temp/anaconda/envs/wheel_py310/lib
    @loader_path
ERROR:delocate.libsana:@rpath/libtorch_python.dylib not found, requested by /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
ERROR:delocate.libsana:
@rpath/libtorch.dylib not found:
  Needed by: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
  Search path:
    /Users/runner/work/_temp/anaconda/envs/wheel_py310/lib
    @loader_path
ERROR:delocate.libsana:@rpath/libtorch.dylib not found, requested by /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
ERROR:delocate.libsana:
@rpath/libtorch_cpu.dylib not found:
  Needed by: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
  Search path:
    /Users/runner/work/_temp/anaconda/envs/wheel_py310/lib
    @loader_path
ERROR:delocate.libsana:@rpath/libtorch_cpu.dylib not found, requested by /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
ERROR:delocate.libsana:
@rpath/libc10.dylib not found:
  Needed by: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
  Search path:
    /Users/runner/work/_temp/anaconda/envs/wheel_py310/lib
    @loader_path
ERROR:delocate.libsana:@rpath/libc10.dylib not found, requested by /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp7bs8a2et/wheel/functorch/_C.cpython-310-darwin.so
Traceback (most recent call last):
Fixing: /Users/runner/work/_temp/dist/torch-1.13.0.dev20220914-cp310-cp310-macosx_10_11_x86_64.whl
  File "/Users/runner/work/_temp/anaconda/envs/wheel_py310/bin/delocate-wheel", line 8, in <module>
    sys.exit(main())
  File "/Users/runner/work/_temp/anaconda/envs/wheel_py310/lib/python3.10/site-packages/delocate/cmd/delocate_wheel.py", line 128, in main
    copied = delocate_wheel(
  File "/Users/runner/work/_temp/anaconda/envs/wheel_py310/lib/python3.10/site-packages/delocate/delocating.py", line 651, in delocate_wheel
    copied_libs = delocate_path(
  File "/Users/runner/work/_temp/anaconda/envs/wheel_py310/lib/python3.10/site-packages/delocate/delocating.py", line 473, in delocate_path
    lib_dict = tree_libs_from_directory(
  File "/Users/runner/work/_temp/anaconda/envs/wheel_py310/lib/python3.10/site-packages/delocate/libsana.py", line 384, in tree_libs_from_directory
    return _tree_libs_from_libraries(
  File "/Users/runner/work/_temp/anaconda/envs/wheel_py310/lib/python3.10/site-packages/delocate/libsana.py", line 325, in _tree_libs_from_libraries
    raise delocate.delocating.DelocationError(
delocate.delocating.DelocationError: Could not find all dependencies.
```

### Versions

nightly 1.13

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Need to figure out how to tell delocate to skip functorch.so....

**Comment by malfet** [comment]
Ok, super simple solution: just ignore them :) Trying it now by passing `--ignore-missing-dependencies` to delocate-wheel

**Comment by malfet** [comment]
Though probably a better one would be to tweak rpath for functorch as follows:
```
diff --git a/functorch/CMakeLists.txt b/functorch/CMakeLists.txt
index 1d156ee635..d203043243 100644
--- a/functorch/CMakeLists.txt
+++ b/functorch/CMakeLists.txt
@@ -19,6 +19,7 @@ target_link_libraries(${PROJECT_NAME} PRIVATE pybind::pybind11)
 
 set_target_properties(${PROJECT_NAME} PROPERTIES LIBRARY_OUTPUT_DIRECTORY
       ${CMAKE_BINARY_DIR}/functorch)
+set_target_properties(${PROJECT_NAME} PROPERTIES INSTALL_RPATH "${_rpath_portable_origin}/../torch/lib")
 
 # Copy-pasted prefix/suffix logic for Python extensions from
 # https://github.com/pytorch/pytorch/blob/33bb8ae350611760139457b85842b1d7edf9aa11/caffe2/CMakeLists.txt#L1975
```
