### ISSUE TITLE
[JIT] addc{div,mul} type issues - scalar accumulation

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8500]
Two operator-level tests failing with `addcdiv` issues with types. It appears the accumulation input (a scalar literal) is Double but the div operands are Float:

Example failure:

```
======================================================================
ERROR: test_addcdiv_scalar_scale (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3498, in check_against_reference
    outputs_test = func(*nograd_inputs)
  File "test/test_autograd.py", line 3474, in script_fn
    return output_process_fn(CU.the_method(*tensors))
RuntimeError: 
Expected object of type CPUDoubleType but found type CPUFloatType for argument #3 'tensor1' (checked_cast_tensor at ../aten/src/ATen/Utils.h:32)
frame #0: at::CPUDoubleType::s_addcdiv(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Scalar) const + 0x8c (0x7fa6c069c2ec in /data/users/zdevito/pytorch/torch/lib/libcaffe2.so.1)
frame #1: at::Type::addcdiv(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Scalar) const + 0x130 (0x7fa6c078ed60 in /data/users/zdevito/pytorch/torch/lib/libcaffe2.so.1)
frame #2: <unknown function> + 0x54bfba (0x7fa6c1ffcfba in /data/users/zdevito/pytorch/torch/_C.so)
frame #3: <unknown function> + 0x424ec6 (0x7fa6c1ed5ec6 in /data/users/zdevito/pytorch/torch/_C.so)
frame #4: <unknown function> + 0x425816 (0x7fa6c1ed6816 in /data/users/zdevito/pytorch/torch/_C.so)
frame #5: <unknown function> + 0x42757b (0x7fa6c1ed857b in /data/users/zdevito/pytorch/torch/_C.so)
frame #6: torch::jit::PropagateInputShapes(torch::jit::Graph&, torch::jit::ArgumentSpec const&) + 0x3b9 (0x7fa6c1ed8a59 in /data/users/zdevito/pytorch/torch/_C.so)
frame #7: torch::jit::GraphExecutorImpl::run(torch::jit::variable_tensor_list) + 0xcfd (0x7fa6c1e8623d in /data/users/zdevito/pytorch/torch/_C.so)
frame #8: torch::jit::GraphExecutor::run(torch::jit::variable_tensor_list&&) + 0x47 (0x7fa6c1e803c7 in /data/users/zdevito/pytorch/torch/_C.so)
frame #9: <unknown function> + 0x62ce29 (0x7fa6c20dde29 in /data/users/zdevito/pytorch/torch/_C.so)
frame #10: <unknown function> + 0x31af88 (0x7fa6c1dcbf88 in /data/users/zdevito/pytorch/torch/_C.so)
frame #11: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #12: <unknown function> + 0x5c64f (0x7fa6d1f0f64f in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #13: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #14: <unknown function> + 0xba2ac (0x7fa6d1f6d2ac in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #15: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #16: PyEval_EvalFrameEx + 0x61d6 (0x7fa6d1fae886 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #17: PyEval_EvalCodeEx + 0x89e (0x7fa6d1fb1c3e in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #18: <unknown function> + 0x79a61 (0x7fa6d1f2ca61 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #19: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #20: PyEval_EvalFrameEx + 0x61d6 (0x7fa6d1fae886 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #21: PyEval_EvalCodeEx + 0x89e (0x7fa6d1fb1c3e in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #22: PyEval_EvalFrameEx + 0x8b47 (0x7fa6d1fb11f7 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #23: PyEval_EvalCodeEx + 0x89e (0x7fa6d1fb1c3e in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #24: PyEval_EvalFrameEx + 0x8b47 (0x7fa6d1fb11f7 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #25: PyEval_EvalCodeEx + 0x89e (0x7fa6d1fb1c3e in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #26: PyEval_EvalFrameEx + 0x8b47 (0x7fa6d1fb11f7 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #27: PyEval_EvalCodeEx + 0x89e (0x7fa6d1fb1c3e in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #28: <unknown function> + 0x79b68 (0x7fa6d1f2cb68 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #29: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #30: PyEval_EvalFrameEx + 0x61d6 (0x7fa6d1fae886 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #31: PyEval_EvalCodeEx + 0x89e (0x7fa6d1fb1c3e in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #32: <unknown function> + 0x79a61 (0x7fa6d1f2ca61 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #33: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #34: <unknown function> + 0x5c64f (0x7fa6d1f0f64f in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #35: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #36: <unknown function> + 0xba2ac (0x7fa6d1f6d2ac in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #37: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #38: PyEval_EvalFrameEx + 0x715d (0x7fa6d1faf80d in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #39: PyEval_EvalCodeEx + 0x89e (0x7fa6d1fb1c3e in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #40: <unknown function> + 0x79b68 (0x7fa6d1f2cb68 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #41: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #42: PyEval_EvalFrameEx + 0x61d6 (0x7fa6d1fae886 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #43: PyEval_EvalCodeEx + 0x89e (0x7fa6d1fb1c3e in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #44: <unknown function> + 0x79a61 (0x7fa6d1f2ca61 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #45: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #46: <unknown function> + 0x5c64f (0x7fa6d1f0f64f in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #47: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #48: <unknown function> + 0xba2ac (0x7fa6d1f6d2ac in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #49: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #50: PyEval_EvalFrameEx + 0x715d (0x7fa6d1faf80d in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #51: PyEval_EvalCodeEx + 0x89e (0x7fa6d1fb1c3e in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #52: <unknown function> + 0x79b68 (0x7fa6d1f2cb68 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #53: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #54: PyEval_EvalFrameEx + 0x61d6 (0x7fa6d1fae886 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #55: PyEval_EvalCodeEx + 0x89e (0x7fa6d1fb1c3e in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #56: <unknown function> + 0x79a61 (0x7fa6d1f2ca61 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #57: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #58: <unknown function> + 0x5c64f (0x7fa6d1f0f64f in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #59: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #60: <unknown function> + 0xba2ac (0x7fa6d1f6d2ac in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #61: PyObject_Call + 0x53 (0x7fa6d1efce93 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #62: PyEval_EvalFrameEx + 0x715d (0x7fa6d1faf80d in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
frame #63: PyEval_EvalFrameEx + 0x8c95 (0x7fa6d1fb1345 in /data/users/zdevito/anaconda2/bin/../lib/libpython2.7.so.1.0)
:
operation failed shape propagation:

def the_method(i0, i1, i2):
    return i0.addcdiv(0.5, i1, i2)
           ~~~~~~~~~~ <--- HERE
```

Affected tests:
- `test_addcdiv_scalar_scale`
- `test_addcdiv_scalar_scale_broadcast_rhs`
- `test_addcmul_scalar_scale`
- `test_addcmul_scalar_scale_broadcast_rhs`

**Comment by jamesr66a** [comment]
This was actually closed by https://github.com/pytorch/pytorch/pull/8574
