### ISSUE TITLE
CUDA Illegal memory access on CrossEntropyLoss with large batch size, cu113, torch 1.12.1

### ISSUE THREAD

**Issue by xeTaiz** [pytorch/pytorch#85005]
### 🐛 Describe the bug

I found that the `nn.CrossEntropyLoss` throws me CUDA illegal memory access when using a too large batch size.
I am running the below code withing the 1.12.1 Docker container with cuda 11.3 on an A100 with 80GB of memory.

```python
import torch
ce = torch.nn.CrossEntropyLoss().cuda()
logits = torch.randn(int(2**16), int(2**16)+1, dtype=torch.float32, device='cuda')
labels = torch.zeros(logits.size(0), dtype=torch.long, device='cuda')
ce(logits, labels)
```

This code throws me an illegal memory access. When using `int(2**15)` for the batch dimension of `logits` (and thus `labels`) the code works. I have seen there were other issues on here claiming that OOMs are reported as illegal memory accesses, however looking at the memory use when using 32K instead of 65K (`2**15` vs `2**16`), I use about 17GB out of the available 80GB of my GPU, indicating to me that this is not a simple OOM.
The stack trace is here:

```
>>> import torch
>>> ce = torch.nn.CrossEntropyLoss().cuda()
>>> logits = torch.randn(int(2**16), int(2**16)+1, device='cuda', dtype=torch.float32)
>>> labels = torch.zeros(logits.size(0), dtype=torch.long, device='cuda')
>>> ce(logits, labels)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 1166, in forward
    label_smoothing=self.label_smoothing)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 3014, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: CUDA error: an illegal memory access was encountered
>>> logits = torch.randn(int(2**15), int(2**16)+1, device='cuda', dtype=torch.float32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: an illegal memory access was encountered
```

I was getting the above while using `CUDA_LAUNCH_BLOCKING=1`
Let me know if you need any more infos

### Versions

```
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.7.13 (default, Mar 29 2022, 02:18:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.18.9-arch1-1-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA A100 80GB PCIe
Nvidia driver version: 515.57
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.21.5
[pip3] pytorch-lightning==1.7.1
[pip3] segmentation-models-pytorch==0.3.0
[pip3] torch==1.12.1
[pip3] torchmetrics==0.9.3
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] efficientnet-pytorch      0.7.1                    pypi_0    pypi
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py37h7f8727e_0
[conda] mkl_fft                   1.3.1            py37hd3c417c_0
[conda] mkl_random                1.2.2            py37h51133e4_0
[conda] numpy                     1.21.5           py37he7a7128_2
[conda] numpy-base                1.21.5           py37hf524024_2
[conda] pytorch                   1.12.1          py3.7_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-lightning         1.7.1                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] segmentation-models-pytorch 0.3.0                    pypi_0    pypi
[conda] torchmetrics              0.9.3                    pypi_0    pypi
[conda] torchtext                 0.13.1                     py37    pytorch
[conda] torchvision               0.13.1               py37_cu113    pytorch
```

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel

**Comment by ptrblck** [comment]
CC @crcrpar could you try to reproduce the issue and debug it, please?

**Comment by crcrpar** [comment]
thank you for the reproducible script. I repro'd with a recent source build and got the following with `TORCH_CPP_SHOW_STACKTRACES=1`. I'm looking into `nll_loss_forward_out_cuda_template`.

```console
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 3020, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: CUDA error: an illegal memory access was encountered
Exception raised from operator() at /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Loss.cu:414 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x7f35714316dc in /opt/conda/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: at::native::(anonymous namespace)::nll_loss_forward_out_cuda_template(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long) + 0x1fe2 (0x7f357335fb82 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x2ea07ad (0x7f35743667ad in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x2ea0925 (0x7f3574366925 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #4: at::_ops::nll_loss_forward::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long) + 0x9a (0x7f359feb04ea in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x349a6a1 (0x7f35a16a96a1 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x349ad27 (0x7f35a16a9d27 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: at::_ops::nll_loss_forward::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long) + 0x1b4 (0x7f359ff4b9c4 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #8: at::native::nll_loss(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long) + 0x5f (0x7f359f694aef in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x22c8bd5 (0x7f35a04d7bd5 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #10: at::_ops::nll_loss::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long) + 0x1b4 (0x7f35a006f224 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #11: at::native::nll_loss_nd(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long) + 0x36a (0x7f359f69ffaa in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x22c8c55 (0x7f35a04d7c55 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #13: at::_ops::nll_loss_nd::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long) + 0x1b9 (0x7f359fe0dac9 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #14: at::native::cross_entropy_loss(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long, double) + 0x19d (0x7f359f69f7ed in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x22c7df5 (0x7f35a04d6df5 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #16: at::_ops::cross_entropy_loss::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long, double) + 0x1c4 (0x7f35a0065d34 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x5d53a2 (0x7f35a8fc83a2 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #43: __libc_start_main + 0xf3 (0x7f35de8dc083 in /usr/lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by ngimel** [comment]
Fixed on master

**Comment by sipie800** [comment]
Exactly the same issue is happening at torch 2.x again

**Comment by frotaur** [comment]
Can confirm I encountered the same issue in pytorch 2.x !!
