### ISSUE TITLE
[JIT] expand: expected at most 3 arguments but found 4

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8503]
Operator-level tests fail with an expand op with four arguments. Example failure:

```
======================================================================
ERROR: test_expand (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3498, in check_against_reference
    outputs_test = func(*nograd_inputs)
  File "test/test_autograd.py", line 3473, in script_fn
    CU = torch.jit.CompilationUnit(script)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 352, in __init__
    self.define(lang, _frames_up=_frames_up + 1)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 358, in define
    self.module._define(lang, rcb, False)
RuntimeError: 
arguments for call are not valid:
  
  for operator expand(Tensor self, IntList size, int64_t implicit=<default>):
  expected at most 3 arguments  but found 4
  
  def the_method(i0):
      return i0.expand(5, 5, 5)
             ~~~~~~~~~ <--- HERE
  
for call at:

def the_method(i0):
    return i0.expand(5, 5, 5)
```

Affected tests:

- `test_expand`
- `test_expand_1_element`
- `test_expand_new_dim`
- `test_expand_new_dim_front_old_front_1`
- `test_expand_scalar_to_dims`
- `test_expand_size`

**Comment by jamesr66a** [comment]
I think this is actually the same task as https://github.com/pytorch/pytorch/issues/8516. Merging
