### ISSUE TITLE
[JIT] gesv operator test needs re-examining

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8504]
```

======================================================================
ERROR: test_gesv (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/zdevito/pytorch/test/common.py", line 77, in wrapper
    fn(*args, **kwargs)
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3587, in check
    check_against_reference(self, create_traced_fn(fn), fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3498, in check_against_reference
    outputs_test = func(*nograd_inputs)
  File "test/test_autograd.py", line 3446, in traced_fn
    return traced(*inputs_tensors)
RuntimeError: 
Lapack Error in gesv : U(1,1) is zero, singular U. at ../aten/src/TH/generic/THTensorLapack.cpp:148:
operation failed shape propagation:
test/test_autograd.py(3580): fn
test/test_autograd.py(3437): new_fn
/data/users/zdevito/pytorch/torch/jit/__init__.py(308): wrapper
test/test_autograd.py(3445): traced_fn
test/test_autograd.py(3498): check_against_reference
test/test_autograd.py(3587): check
test/test_autograd.py(3665): do_test
/data/users/zdevito/pytorch/test/common.py(77): wrapper
/home/zdevito/local/anaconda2/lib/python2.7/unittest/case.py(329): run
/home/zdevito/local/anaconda2/lib/python2.7/unittest/case.py(393): __call__
/home/zdevito/local/anaconda2/lib/python2.7/unittest/suite.py(108): run
/home/zdevito/local/anaconda2/lib/python2.7/unittest/suite.py(70): __call__
/home/zdevito/local/anaconda2/lib/python2.7/unittest/suite.py(108): run
/home/zdevito/local/anaconda2/lib/python2.7/unittest/suite.py(70): __call__
/home/zdevito/local/anaconda2/lib/python2.7/unittest/runner.py(151): run
/home/zdevito/local/anaconda2/lib/python2.7/unittest/main.py(232): runTests
/home/zdevito/local/anaconda2/lib/python2.7/unittest/main.py(95): __init__
/data/users/zdevito/pytorch/test/common.py(50): run_tests
test/test_autograd.py(3683): <module>
```

Probalby need to be more careful in constructing the inputs

**Comment by driazati** [comment]
Test is now passing by #11403
