### ISSUE TITLE
[JIT] Elementwise min/max scalar tests fail with tuple comparison

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8514]
Probably something wrong with the tests themselves:

```
======================================================================
ERROR: test_max_scalar_elementwise (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3499, in check_against_reference
    self.assertEqual(outputs, outputs_test)
  File "/data/users/zdevito/pytorch/test/common.py", line 326, in assertEqual
    super(TestCase, self).assertEqual(x, y, message)
  File "/home/zdevito/local/anaconda2/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/zdevito/local/anaconda2/lib/python2.7/unittest/case.py", line 503, in _baseAssertEqual
    if not first == second:
TypeError: eq() received an invalid combination of arguments - got (tuple), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (!tuple!)
 * (Number other)
      didn't match because some of the arguments have invalid types: (!tuple!)



======================================================================
ERROR: test_min_scalar_elementwise (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3499, in check_against_reference
    self.assertEqual(outputs, outputs_test)
  File "/data/users/zdevito/pytorch/test/common.py", line 326, in assertEqual
    super(TestCase, self).assertEqual(x, y, message)
  File "/home/zdevito/local/anaconda2/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/zdevito/local/anaconda2/lib/python2.7/unittest/case.py", line 503, in _baseAssertEqual
    if not first == second:
TypeError: eq() received an invalid combination of arguments - got (tuple), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (!tuple!)
 * (Number other)
      didn't match because some of the arguments have invalid types: (!tuple!)
```

**Comment by zou3519** [comment]
I was able to renable the tests in #8687 but I'm not sure why my changes would have fixed these. It's probably worth looking at this again.
