### ISSUE TITLE
[JIT] Better handle IntList arguments for ops like permute

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8516]
The following tests show invocations of `permute` that are valid in Python but not script. We should make it so that the behavior of script matches the python arg parser, e.g. https://github.com/pytorch/pytorch/blob/0829d4502de40c77f191e85983edf7f67a843c70/torch/csrc/utils/python_arg_parser.cpp:

```

======================================================================
ERROR: test_permute (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3498, in check_against_reference
    outputs_test = func(*nograd_inputs)
  File "test/test_autograd.py", line 3473, in script_fn
    CU = torch.jit.CompilationUnit(script)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 352, in __init__
    self.define(lang, _frames_up=_frames_up + 1)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 358, in define
    self.module._define(lang, rcb, False)
RuntimeError: 
arguments for call are not valid:
  
  for operator permute(Tensor self, IntList dims):
  expected at most 2 arguments  but found 5
  
  def the_method(i0):
      return i0.permute(0, 2, 3, 1)
             ~~~~~~~~~~ <--- HERE
  
for call at:

def the_method(i0):
    return i0.permute(0, 2, 3, 1)
           ~~~~~~~~~~ <--- HERE


======================================================================
ERROR: test_permute_neg_dim (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3498, in check_against_reference
    outputs_test = func(*nograd_inputs)
  File "test/test_autograd.py", line 3473, in script_fn
    CU = torch.jit.CompilationUnit(script)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 352, in __init__
    self.define(lang, _frames_up=_frames_up + 1)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 358, in define
    self.module._define(lang, rcb, False)
RuntimeError: 
arguments for call are not valid:
  
  for operator permute(Tensor self, IntList dims):
  expected at most 2 arguments  but found 5
  
  def the_method(i0):
      return i0.permute(0, -2, -1, 1)
             ~~~~~~~~~~ <--- HERE
  
for call at:

def the_method(i0):
    return i0.permute(0, -2, -1, 1)
           ~~~~~~~~~~ <--- HERE
```

We should probably improve this.

Affected tests:
- `test_permute`
- `test_permute_neg_dim`
- `test_repeat`
- `test_repeat_scalar`
- `test_repeat_unsqueeze`
- `test_reshape`
- `test_view`
- `test_expand`
- `test_expand_1_element`
- `test_expand_new_dim`
- `test_expand_new_dim_front_old_front_1`
- `test_expand_scalar_to_dims`
- `test_expand_size`
- `test_repeat_single_number`
- `test_reshape_1d`
- `test_reshape_scalar_to_1d`
- `test_view_1d`
- `test_view_scalar_to_1d`

**Comment by zou3519** [comment]
FYI: I'm changing how IntList works in the frontend (to add better support for literals to script). I'm not sure if this will conflict but keep me updated!

**Comment by wanchaol** [comment]
Note: we could be able to fix this issue after @zou3519 PR, then rebase #7444 with additional fix on how script handles single argument of int/list of ints.
