### ISSUE TITLE
[JIT] Passed-in parameter is not a 1D LongTensor when expected

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8519]
Operator-level tests fail. Example failure:

```
======================================================================
ERROR: test_repeat_single_number (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3498, in check_against_reference
    outputs_test = func(*nograd_inputs)
  File "test/test_autograd.py", line 3474, in script_fn
    return output_process_fn(CU.the_method(*tensors))
RuntimeError: 
Expected a 1D LongTensor:
operation failed in interpreter:

def the_method(i0):
    return i0.repeat(2)
           ~~~~~~~~~ <--- HERE
```
Affected tests:
- `test_repeat_single_number`
- `test_reshape_1d`
- `test_reshape_scalar_to_1d`
- `test_view_1d`
- `test_view_scalar_to_1d`

**Comment by jamesr66a** [comment]
Problem is here: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/tensor_conversions.h#L64

The number literals are emitted as 0-d tensors, but this conversion function expects 1d

**Comment by jamesr66a** [comment]
Nevermind, this is a specific case of varargs inputs that's failing. Merging into the other task
