### ISSUE TITLE
OSError libstdc++.so.6 at import

### ISSUE THREAD

**Issue by sebastienwood** [pytorch/pytorch#85211]
### 🐛 Describe the bug

I have a fresh virtual environment with pytorch installed from `pip install -r requirements.txt` which contain 
```
tensorly
numpy
torch
torchvision
torchtyping
scipy
opt_einsum
matplotlib
tqdm
prettytable
antares
numba
-e .
```
I then run a simple `import torch` which gives the following output:
```
python3
Python 3.10.6 (main, Aug  1 2022, 20:38:21) [GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sebwood/workspace/MemSE/.env/lib/python3.10/site-packages/torch/__init__.py", line 201, in <module>
    _load_global_deps()
  File "/home/sebwood/workspace/MemSE/.env/lib/python3.10/site-packages/torch/__init__.py", line 154, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

### Versions

Note that the way the script to collect versions will show Pytorch version as N/A because I cannot import pytorch at all. Instead `pip list` gives:
```
torch 1.12.1
torchvision 0.13.1
```

Here is the script output
```
python collect_env.py 
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.6 (main, Aug  1 2022, 20:38:21) [GCC 5.4.0 20160609] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1650 SUPER
Nvidia driver version: 516.94
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.12.1
[pip3] torchtyping==0.1.4
[pip3] torchvision==0.13.1
[conda] Could not collect
```

**Comment by malfet** [comment]
Hmm, according to [PEP-599](https://peps.python.org/pep-0599/) libstdc++.so.6 should be present in Python environment, so it feel like something is wrong with the way Python-3.10 was build/venv configured. 
@sebastienwood how did you install python on your system? Does it reproduces with stock 3.9?

**Comment by sebastienwood** [comment]
Hey thanks for the answer. My Python is installed through Linuxbrew. I wiped my WSL install entirely today to ensure everything is clean and followed the following procedure:
- I ensured CUDA is working through `nvidia-smi`
- installed LinuxBrew through the site procedure
- ran `brew install python` which install Python 3.10
- created a virtualenv, activated it, 
- installed Pytorch with the following `pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116`
- and finally ran `python3` -> `import torch; torch.zeros(1).cuda()`

The error at import is now resolved, although I have an error with the GPU: `Found no NVIDIA driver on your system`. I also tested it on 3.9, which yields the same issue. I still have no clue as to why the import failed before the wipe.
