### ISSUE TITLE
[asan] ctc_loss fails test_make_fx_fake_exhaustive with ASAN

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#85231]
### 🐛 Describe the bug

```
==729==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61f00041847c at pc 0x7f01905b4988 bp 0x7ffc03665d90 sp 0x7ffc03665d88
[1680](https://github.com/pytorch/pytorch/actions/runs/3074016256/jobs/4966582993#step:10:1681)
READ of size 4 at 0x61f00041847c thread T0
[1681](https://github.com/pytorch/pytorch/actions/runs/3074016256/jobs/4966582993#step:10:1682)
    #0 0x7f01905b4987 in std::tuple<at::Tensor, at::Tensor> at::native::(anonymous namespace)::ctc_loss_cpu_template<float, (c10::ScalarType)4>(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, long)::'lambda'(long, long)::operator()(long, long) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xdc2a987)
[1682](https://github.com/pytorch/pytorch/actions/runs/3074016256/jobs/4966582993#step:10:1683)
    #1 0x7f018fb23557 in std::function<void (long, long)>::operator()(long, long) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xd199557)
```

The test fails on CI for PR https://github.com/pytorch/pytorch/pull/84752

Ref: https://github.com/pytorch/pytorch/pull/84752#issuecomment-1243847936

### Versions

[PR ](https://github.com/pytorch/pytorch/pull/84752)

cc @ezyang @gchanan @zou3519 @albanD @mruberry @jbschlosser @walterddr @saketh-are @SherlockNoMad @soumith

**Comment by ezyang** [comment]
@zou3519 this is probably the ctc loss composite compliance problem

**Comment by ezyang** [comment]
WAIT lol the PR is fixing composite compliance lol

**Comment by ydwu4** [comment]
Is this issue still valid? Do we have a repro if it's valid?  I'll close for now but feel free to re-open.
