### ISSUE TITLE
[JIT] Shape propagation on `split` is broken

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8524]
Operator level test fails:

```
======================================================================
ERROR: test_split (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3498, in check_against_reference
    outputs_test = func(*nograd_inputs)
  File "test/test_autograd.py", line 3474, in script_fn
    return output_process_fn(CU.the_method(*tensors))
RuntimeError: 
torch/csrc/jit/passes/shape_analysis.cpp:103: PropagateShapeOnNodeByRunningIt: Assertion `stack.size() == node->outputs().size()` failed.:
operation failed shape propagation:

def the_method(i0):
    return i0.split(2)
           ~~~~~~~~ <--- HERE
```

There's probably an issue with the number of splits specified not matching the number of outputs of the node in the IR

**Comment by jamesr66a** [comment]
Merging into https://github.com/pytorch/pytorch/issues/8528
