### ISSUE TITLE
Crash in `torch.package.PackageExporter`

### ISSUE THREAD

**Issue by jdanceze** [pytorch/pytorch#85329]
### 🐛 Describe the bug

Passing invalid input to `f` or `importer` in `torch.package.PackageExporter`, can causes a crash with Aborted (core dumped).
## code

```python
import torch

torch.package.PackageExporter(f=1, importer=1)
```

## output
```bash
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  AttributeError: 'int' object has no attribute 'write'
Aborted (core dumped)
```

### Versions

PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-117-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.12.1
[conda] Could not collect

**Comment by ezyang** [comment]
repros on master. The problem is that it's crashing in destructor

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7db2859 in __GI_abort () at abort.c:79
#2  0x00007fffc9505911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fffc951138c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fffc9510369 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fffc9510d21 in __gxx_personality_v0 () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fffdebe3bef in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007fffdebe45aa in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x00007fffbd17534a in caffe2::serialize::PyTorchStreamWriter::writeEndOfFile() [clone .cold] ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#9  0x00007fffbfa90e15 in caffe2::serialize::PyTorchStreamWriter::~PyTorchStreamWriter() ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_cpu.so
#10 0x00007fffc75021dd in pybind11::class_<caffe2::serialize::PyTorchStreamWriter>::dealloc(pybind11::detail::value_and_holder&) () from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_python.so
#11 0x00007fffc70ba173 in pybind11::detail::clear_instance(_object*) ()
   from /raid/ezyang/pytorch-scratch2/torch/lib/libtorch_python.so
#12 0x00007fffc70bb093 in pybind11_object_dealloc ()

```
