### ISSUE TITLE
Skip added to test_compare_cpu_nn_functional_embedding_cuda_float32 because of CI

### ISSUE THREAD

**Issue by srossross** [pytorch/pytorch#85377]
### 🐛 Describe the bug

The PR https://github.com/pytorch/pytorch/pull/85011 to add the test `test_compare_cpu` compares GPU and CPU results. on the CI workflow the test `test_compare_cpu` with the op `nn.functional_embedding` fails with this error message

```
======================================================================
FAIL [0.009s]: test_compare_cpu_nn_functional_embedding_cuda_float32 (__main__.TestCommonCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1950, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 815, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 975, in only_fn
    return fn(slf, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1283, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/test_ops.py", line 187, in test_compare_cpu
    self.assertEqual(cuda_results, cpu_results)
  File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2412, in assertEqual
    assert_equal(
  File "/opt/conda/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 15 / 45 (33.3%)
Greatest absolute difference: 0.5051435921341181 at index (0, 0, 3) (up to 1e-05 allowed)
Greatest relative difference: 0.9674892692698572 at index (0, 0, 2) (up to 1.3e-06 allowed)
```

However when I run this on 
This skip can not be reproduced on my local machine `us.quansight.dev` I can not reproduce the error I get an unexpected success

```
================================================== 434 passed, 501 skipped, 47841 deselected, 26 xfailed, 11 warnings in 34.78s ==================================================
(pytorch2) srossross@qgpu1:~/pytorch$ py.test test/test_ops.py -v -k test_compare_cpu_nn_functional_embedding_cuda_float32
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0 -- /home/srossross/.conda/envs/pytorch2/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/srossross/pytorch/.hypothesis/examples')
rootdir: /home/srossross/pytorch, configfile: pytest.ini
plugins: hypothesis-6.54.4
collected 48802 items / 48801 deselected / 1 selected                                                                                                                            

test/test_ops.py::TestCommonCUDA::test_compare_cpu_nn_functional_embedding_cuda_float32 FAILED                                                                             [100%]

==================================================================================== FAILURES ====================================================================================
______________________________________________________ TestCommonCUDA.test_compare_cpu_nn_functional_embedding_cuda_float32 ______________________________________________________
Unexpected success
============================================================================ short test summary info =============================================================================
FAILED test/test_ops.py::TestCommonCUDA::test_compare_cpu_nn_functional_embedding_cuda_float32
=============================================================== 1 failed, 48801 deselected, 11 warnings in 15.09s ================================================================
```

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.9.0 (default, Nov 15 2020, 14:28:56)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-147-generic-x86_64-with-glibc2.27
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2.89/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[conda] numpy                     1.21.6                   pypi_0    pypi

**Comment by lezcano** [comment]
This can be either a bug or that the function is non-deterministic for some inputs (or both?). @kurtamohler could you have a look?

**Comment by kurtamohler** [comment]
I don't get a failure in my environment either unfortunately.

It would be useful to know exactly what all the args, kwargs, and result values are when it fails, for both the CPU and CUDA calls. @srossross, maybe if you could add printouts in `test_compare_cpu` when `op == torch.nn.functional.embedding` and rerun CI with the embedding test enabled, that would help.

Also, was this failing on all CI test jobs, or just some of them?

My hunch is that the `max_norm` option is causing the difference. I'll look into how `max_norm` is implemented in CPU and CUDA to see if there is anything that jumps out.

**Comment by kurtamohler** [comment]
If `max_norm != None`, then `torch.nn.functional.embedding` calls `torch.embedding_renorm_`, which is implemented [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/Embedding.cu#L347) for CUDA and [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Embedding.cpp#L153) for CPU, to normalize each row vector in the embedding matrix (the `weights` argument of the `embedding` function) inplace, if the index for that row appears in the `input` argument of `embedding` and if the row's norm is greater than `max_norm`.

The scaling factor is calculated and applied inplace to the embedding vector [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/Embedding.cu#L236) for CUDA and [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Embedding.cpp#L178) for CPU. Here's a copy of the code:

CUDA:
```cpp
    auto factor = static_cast<scalar_t>(max_norm / (sdata[0] + 1e-7));
    for (int i = tid; i < dim; i += blockDim.x) {
      weights[base_index + i * weights_stride1] *= factor;
    }
```

CPU:
```cpp
        auto scale = max_norm / (norm + 1e-7);
        row *= scale;
```

For CUDA, `max_norm` and `sdata[0]` have the type `accscalar_t`, which resolves to the same type as whatever the embedding matrix's type is--float32 in the failing CI job. For CPU, `max_norm` and `norm` are always doubles, float64.

I think there's a chance that this is causing the difference is results, if the failure is only happening when `max_norm != None`. However, I'm not sure why it would show up in CI and not our local checkouts.

Another question for you @srossross: Was the float64 test passing, or did it fail too?

**Comment by lezcano** [comment]
So, I think the issue is in the CUDA version. Rather than using `scalar_t`, it should be using `opmath_t` and the division should be performed in that type for extra precision. Could this be it?

**Comment by kurtamohler** [comment]
It looks like `opmath_t` is always set to `using opmath_t = at::opmath_type<scalar_t>;`, and in `aten/src/ATen/OpMathType.h` we have:

<details>
<summary>Click to expand</summary>

```cpp
template <typename scalar_t>
struct OpMathType {
  using type = scalar_t;
};
template <>
struct OpMathType<at::Half> {
  using type = float;
};
template <>
struct OpMathType<at::BFloat16> {
  using type = float;
};
template <>
struct OpMathType<c10::complex<Half>> {
  using type = c10::complex<float>;
};

template <typename T>
using opmath_type = typename OpMathType<T>::type;
```

</details>

Unless I'm missing something, `opmath_t` is only different than `scalar_t` if `scalar_t` is a half type. So I don't thin that would change anything in this case

**Comment by lezcano** [comment]
Ah right. Probably those intermediary values should be kept in the computation type on CPU? What do you think @ngimel?

**Comment by lezcano** [comment]
ping @ngimel

**Comment by ngimel** [comment]
tbh I'm surprised that that would matter, but we could try setting cpu computation to opmath instead of double
