### ISSUE TITLE
Result of backward is wrong with conj_view and neg_view for Tensor.sum_to_size

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#85409]
### 🐛 Describe the bug

Newly added sample inputs in https://github.com/pytorch/pytorch/pull/85338 revealed a problem. All I changed was to pass `shape` argument as a list and not a tuple.
```py
_________________________________________________ TestMathBitsCPU.test_conj_view_sum_to_size_cpu_complex64 _________________________________________________
Traceback (most recent call last):
  File "/home/iyashchuk/dev/pytorch/master/test/test_ops.py", line 1454, in test_conj_view
    self._test_math_view(
  File "/home/iyashchuk/dev/pytorch/master/test/test_ops.py", line 1429, in _test_math_view
    self.assertEqual(tensor.grad, cloned1_tensor.grad)
  File "/home/iyashchuk/dev/pytorch/master/torch/testing/_internal/common_utils.py", line 2435, in assertEqual
    assert_equal(
  File "/home/iyashchuk/dev/pytorch/master/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 5 / 5 (100.0%)
Greatest absolute difference: 1.551922600020548 at index (0,) (up to 1e-05 allowed)
Greatest relative difference: 1.551922600020548 at index (0,) (up to 1.3e-06 allowed)
__________________________________________________ TestMathBitsCPU.test_neg_view_sum_to_size_cpu_float64 ___________________________________________________
Traceback (most recent call last):
  File "/home/iyashchuk/dev/pytorch/master/test/test_ops.py", line 1473, in test_neg_view
    self._test_math_view(
  File "/home/iyashchuk/dev/pytorch/master/test/test_ops.py", line 1429, in _test_math_view
    self.assertEqual(tensor.grad, cloned1_tensor.grad)
  File "/home/iyashchuk/dev/pytorch/master/torch/testing/_internal/common_utils.py", line 2435, in assertEqual
    assert_equal(
  File "/home/iyashchuk/dev/pytorch/master/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 5 / 5 (100.0%)
Greatest absolute difference: 0.5322531452148951 at index (0,) (up to 1e-07 allowed)
Greatest relative difference: 0.5322531452148951 at index (0,) (up to 1e-07 allowed)
________________________________________________ TestMathBitsCUDA.test_conj_view_sum_to_size_cuda_complex64 ________________________________________________
Traceback (most recent call last):
  File "/home/iyashchuk/dev/pytorch/master/test/test_ops.py", line 1454, in test_conj_view
    self._test_math_view(
  File "/home/iyashchuk/dev/pytorch/master/test/test_ops.py", line 1429, in _test_math_view
    self.assertEqual(tensor.grad, cloned1_tensor.grad)
  File "/home/iyashchuk/dev/pytorch/master/torch/testing/_internal/common_utils.py", line 2435, in assertEqual
    assert_equal(
  File "/home/iyashchuk/dev/pytorch/master/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 5 / 5 (100.0%)
Greatest absolute difference: 0.7916027468331712 at index (0,) (up to 1e-05 allowed)
Greatest relative difference: 0.7916027468331712 at index (0,) (up to 1.3e-06 allowed)
_________________________________________________ TestMathBitsCUDA.test_neg_view_sum_to_size_cuda_float64 __________________________________________________
Traceback (most recent call last):
  File "/home/iyashchuk/dev/pytorch/master/test/test_ops.py", line 1473, in test_neg_view
    self._test_math_view(
  File "/home/iyashchuk/dev/pytorch/master/test/test_ops.py", line 1429, in _test_math_view
    self.assertEqual(tensor.grad, cloned1_tensor.grad)
  File "/home/iyashchuk/dev/pytorch/master/torch/testing/_internal/common_utils.py", line 2435, in assertEqual
    assert_equal(
  File "/home/iyashchuk/dev/pytorch/master/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 5 / 5 (100.0%)
Greatest absolute difference: 1.0829307052989563 at index (0,) (up to 1e-07 allowed)
Greatest relative difference: 1.0829307052989563 at index (0,) (up to 1e-07 allowed)
================================================================= short test summary info ==================================================================
FAILED test/test_ops.py::TestMathBitsCPU::test_conj_view_sum_to_size_cpu_complex64 - AssertionError: Tensor-likes are not close!
FAILED test/test_ops.py::TestMathBitsCPU::test_neg_view_sum_to_size_cpu_float64 - AssertionError: Tensor-likes are not close!
FAILED test/test_ops.py::TestMathBitsCUDA::test_conj_view_sum_to_size_cuda_complex64 - AssertionError: Tensor-likes are not close!
FAILED test/test_ops.py::TestMathBitsCUDA::test_neg_view_sum_to_size_cuda_float64 - AssertionError: Tensor-likes are not close!
```

### Versions

Master.

cc @ezyang @gchanan @zou3519 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @anjali411 @dylanbespalko @mruberry

**Comment by ezyang** [comment]
Err, I'm not sure I understand. Aren't you adding error inputs only in the linked PR?

**Comment by IvanYashchuk** [comment]
The linked PR exposes the problem and xfails these tests.

**Comment by ngimel** [comment]
@anjali411 will look into it
