### ISSUE TITLE
torch._refs.permute doesn't support torch.Tensor.permute python binding on variadic arguments

### ISSUE THREAD

**Issue by jjsjann123** [pytorch/pytorch#85452]
### 🐛 Describe the bug

running into this error
```
root@937ced371c77:/opt/pytorch/pytorch# python repro_permute.py
Traceback (most recent call last):
  File "repro_permute.py", line 11, in <module>
    gm = make_fx(f)(a)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 629, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 329, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/pytorch/pytorch/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 343, in wrapped
    out = f(*tensors)
  File "repro_permute.py", line 5, in f
    return a.permute(1, 0)
  File "/opt/pytorch/pytorch/torch/overrides.py", line 1778, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims/context.py", line 186, in __torch_function__
    return func(*args, **kwargs)
TypeError: permute() takes 2 positional arguments but 3 were given
```

Repro script
```
import torch
from torch.fx.experimental.proxy_tensor import make_fx
from torch._prims.context import TorchRefsMode
a = torch.randn(3, 3)
def f(a):
    return a.permute(1, 0)
with TorchRefsMode():
    gm = make_fx(f)(a)
```

Looks like we can do this
```
x = torch.randn(2, 3, 4).permute(1, 2, 0)
torch.permute(x, (1, 2, 0))  # this works
# torch.permute(x, 1, 2, 0)  # this breaks!
```

But torch.permute needs permuted axes to come in as an explicit array. So I'm wondering if `Tensor.permute` variadic argument signature is merely a side effect from python binding? In native_functions.yaml, we have this `- func: permute(Tensor(a) self, int[] dims) -> Tensor(a)`

It's a little bit awkward that we have a decomposition hitting this: https://github.com/pytorch/pytorch/blob/master/torch/_decomp/decompositions.py#L691

Since these are valid code, we need to plumb the support to PrimTorch. And similar issues would arise from other aten ops with a signature `Tensor, int[]`.

### Versions

ToT master commit:
```
commit a998a8eb1027b0e162fd6789efb378edc66d37e9 (HEAD, origin/master, origin/HEAD)
Author: Natalia Gimelshein <[ngimel@fb.com](mailto:ngimel@fb.com)>
Date:   Mon Sep 19 22:00:41 2022 +0000
    Fix segfault for `out` with a large number of dims (#85294)
    Fixes #85166, #85167, #79218, #85251
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/85294
    Approved by: https://github.com/malfet
```

```
Collecting environment information...
PyTorch version: 1.13.0a0+giteb1dad1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A
OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31
Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-40-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration:
GPU 0: NVIDIA Graphics Device
GPU 1: NVIDIA TITAN V
Nvidia driver version: 510.60.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Versions of relevant libraries:
[pip3] functorch==0.3.0a0+eb1dad1
[pip3] numpy==1.21.5
[pip3] torch==1.13.0a0+giteb1dad1
[pip3] torchdynamo==1.13.0.dev0
[pip3] torchvision==0.14.0a0+9c3e2bf
[conda] functorch                 0.3.0a0+eb1dad1           dev_0    <develop>
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] nomkl                     3.0                           0
[conda] numpy                     1.21.5           py38h7a5d4dd_2
[conda] numpy-base                1.21.5           py38hb8be1f0_2
[conda] torch                     1.13.0a0+giteb1dad1           dev_0    <develop>
[conda] torchdynamo               1.13.0.dev0               dev_0    <develop>
[conda] torchvision               0.14.0a0+9c3e2bf           dev_0    <develop>
```

cc @ezyang @mruberry @ngimel @Lezcano @fdrocha

**Comment by t-vi** [comment]
.view probably is the most prominent other example.

**Comment by t-vi** [comment]
> So I'm wondering if Tensor.permute variadic argument signature is merely a side effect from python binding
It is:
https://github.com/pytorch/pytorch/blob/76d60778eb01b4213735be1c6e126fe2da519b8e/torch/csrc/utils/python_arg_parser.cpp#L1264-L1266

**Comment by jjsjann123** [comment]
Hahaha, there's also `hsplit` `vsplit`. :wink: 

Thanks a lot for the quick patch~
