### ISSUE TITLE
INTERNAL ASSERT FAILED at alias_analysis.cpp:614 when tracing a model that uses bitwise_or(tensor, bool)

### ISSUE THREAD

**Issue by mdatres** [pytorch/pytorch#85704]
### 🐛 Describe the bug

Dear all, 

I'm trying to export  a working model into the onnx format using  torch.onnx.export(network), but it returns this error. The error suggests me to report its content as a bug, that's why I'm posting it here. Can you help me?

Thanks in advanced!

Traceback (most recent call last):
  File "exp.py", line 355, in <module>
    exporter.export(network=nettq, input_shape=x.shape, path=path_export, opset_version = 10)
  File "/opt/anaconda3/envs/quantlab/lib/python3.8/site-packages/quantlib-0.2-py3.8.egg/quantlib/backends/base/onnxexporter.py", line 29, in export
    torch.onnx.export(network,
  File "/opt/anaconda3/envs/quantlab/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/opt/anaconda3/envs/quantlab/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/opt/anaconda3/envs/quantlab/lib/python3.8/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/opt/anaconda3/envs/quantlab/lib/python3.8/site-packages/torch/onnx/utils.py", line 727, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/opt/anaconda3/envs/quantlab/lib/python3.8/site-packages/torch/onnx/utils.py", line 602, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/opt/anaconda3/envs/quantlab/lib/python3.8/site-packages/torch/onnx/utils.py", line 517, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/opt/anaconda3/envs/quantlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 1175, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/opt/anaconda3/envs/quantlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/quantlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
RuntimeError: 0 INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":614, please report a bug to PyTorch. We don't have an op for aten::__ior__ but it isn't a special case.  Argument types: Tensor, bool, 

### Versions

torch                         1.12.1
onnx                          1.9.0

**Comment by davidberard98** [comment]
Can you provide a repro?

**Comment by mdatres** [comment]
Yes for sure. You need to install this repository [https://github.com/pulp-platform/quantlab](url) and run the script in attachment. 
[share.py.zip](https://github.com/pytorch/pytorch/files/9662702/share.py.zip)
Thanks in advance!

**Comment by davidberard98** [comment]
okay, here's a minimal repro

```python
import torch

def fn(x):
    b = True
    return x.square() | b

x = torch.tensor([[1, 2], [3, 4]])
fn(x)
torch.jit.trace(fn, (x,))
```

output:
```
Traceback (most recent call last):
  File "/data/users/dberard/scripts/oncall/85704.py", line 9, in <module>
    torch.jit.trace(fn, (x,))
  File "/data/users/dberard/pytorch/torch/jit/_trace.py", line 804, in trace
    traced = torch._C._create_function_from_trace(
RuntimeError: 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":614, please report a bug to PyTorch. We don't have an op for aten::__or__ but it isn't a special case.  Argument types: Tensor, bool,

Candidates:
        aten::__or__.Tensor(Tensor self, Tensor other) -> Tensor
        aten::__or__.Scalar(Tensor self, Scalar other) -> Tensor
        aten::__or__.bool(bool a, bool b) -> bool
        aten::__or__.int(int a, int b) -> int
```

not entirely sure how to trigger `__ior__` instead of `__or__` but afaik this is basically the same issue.

**Comment by davidberard98** [comment]
@mdatres unfortunately this is sort of a known issue, I don't think we really have plans to fix this in the short term. The issue is that booleans are not considered scalars by jit, but they are in pytorch.

If you can find the place where this is happening (_bitwise_or_(tensor, bool)), I'd recommend casting the bool to int() before running the bitwise or.

**Comment by mdatres** [comment]
@davidberard98 ok, thanks. I'm gonna try your suggestion.

**Comment by mdatres** [comment]
@davidberard98 Do you have any suggestion where the operation you have mentioned is applied? I cannot find it
