### ISSUE TITLE
[Meta][MPS] Test regressions in MacOS Ventura

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#85758]
### 🐛 Describe the bug

<details>
<summary>test_output_match_dot_cpu_int64</summary>

```
======================================================================
FAIL: test_output_match_dot_cpu_int64 (__main__.TestConsistencyCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nshulga/git/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    result = test(self, **param_kwargs)
  File "/Users/nshulga/git/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 815, in test_wrapper
    return test(*args, **kwargs)
  File "/Users/nshulga/git/pytorch/pytorch/test/test_mps.py", line 7692, in test_output_match
    raise e
  File "/Users/nshulga/git/pytorch/pytorch/test/test_mps.py", line 7688, in test_output_match
    self.assertEqual(cpu_out, mps_out, atol=atol, rtol=rtol)
  File "/Users/nshulga/git/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2452, in assertEqual
    assert_equal(
  File "/Users/nshulga/git/pytorch/pytorch/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Scalars are not equal!

Absolute difference: 93
Relative difference: 2.325

```
</details>

<details><summary>test_output_match_nn_functional_pairwise_distance_cpu_float16</summary>

```
======================================================================
FAIL: test_output_match_nn_functional_pairwise_distance_cpu_float16 (__main__.TestConsistencyCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nshulga/git/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    result = test(self, **param_kwargs)
  File "/Users/nshulga/git/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 815, in test_wrapper
    return test(*args, **kwargs)
  File "/Users/nshulga/git/pytorch/pytorch/test/test_mps.py", line 7692, in test_output_match
    raise e
  File "/Users/nshulga/git/pytorch/pytorch/test/test_mps.py", line 7688, in test_output_match
    self.assertEqual(cpu_out, mps_out, atol=atol, rtol=rtol)
  File "/Users/nshulga/git/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2452, in assertEqual
    assert_equal(
  File "/Users/nshulga/git/pytorch/pytorch/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Scalars are not close!

Absolute difference: inf (up to 1e-05 allowed)
Relative difference: inf (up to 0.001 allowed)

----------------------------------------------------------------------

```

</details>

```
Ran 3207 tests in 154.114s

FAILED (failures=2, skipped=1961, expected failures=1)
```

### Versions

1.13.0 / nightly

cc @ezyang @gchanan @zou3519 @kulinseth @albanD @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Reopening the issue as there are still 2 issues remaining

**Comment by malfet** [comment]
```
python -c "import torch;x=torch.tensor([-8,  6,  9,  0,  0], device='mps');y=torch.tensor([5, 5, 7, 6, 5], device='mps'); print(torch.dot(x, y), torch.sum(x * y))"
tensor(-40, device='mps:0') tensor(53, device='mps:0')
```

**Comment by malfet** [comment]
Per experimental [Ventura CI run](https://github.com/pytorch/pytorch/actions/runs/3634806203/jobs/6133896430) following 4 tests are failing:
- test_output_match_dot_cpu_int64
- test_output_match_masked_log_softmax_cpu_float32
- test_output_match_masked_softmax_cpu_float32
- test_output_match_masked_softmin_cpu_float32

**Comment by kulinseth** [comment]
@malfet , i think these issues are fixed and since then. We have also added a macos-13 runner to catch any regressions. Please re-open if you see any issues.
