### ISSUE TITLE
[Quant] Default qnnpack per_channel observers/fake_quant cannot be instantiated

### ISSUE THREAD

**Issue by andrewor14** [pytorch/pytorch#85862]
Simple repro:
```
>>> from torch.ao.quantization.observer import per_channel_weight_observer_range_neg_127_to_127
>>> per_channel_weight_observer_range_neg_127_to_127()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/andrewor/pytorch/torch/ao/quantization/observer.py", line 63, in __call__
    return self.p(*args, **keywords)
  File "/data/users/andrewor/pytorch/torch/ao/quantization/observer.py", line 455, in __init__
    raise NotImplementedError(
NotImplementedError: MinMaxObserver's qscheme only support torch.per_tensor_symmetric                     and torch.per_tensor_affine.
```
Same for the QAT equivalent:
```
>>> from torch.ao.quantization.fake_quantize import fused_per_channel_wt_fake_quant_range_neg_127_to_127
>>> fused_per_channel_wt_fake_quant_range_neg_127_to_127()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/andrewor/pytorch/torch/ao/quantization/observer.py", line 63, in __call__
    return self.p(*args, **keywords)
  File "/data/users/andrewor/pytorch/torch/ao/quantization/fake_quantize.py", line 280, in __init__
    super().__init__(observer, quant_min, quant_max, **observer_kwargs)
  File "/data/users/andrewor/pytorch/torch/ao/quantization/fake_quantize.py", line 133, in __init__
    self.activation_post_process = observer(**observer_kwargs)
  File "/data/users/andrewor/pytorch/torch/ao/quantization/observer.py", line 573, in __init__
    raise NotImplementedError(
NotImplementedError: MovingAverageMinMaxObserver's qscheme only support                     torch.per_tensor_symmetric and torch.per_tensor_affine.
```

cc @jerryzh168 @vkuzo @digantdesai

**Comment by andrewor14** [comment]
Also cc @digantdesai

**Comment by jerryzh168** [comment]
I think it's probably the definition of `per_channel_weight_observer_range_neg_127_to_127 ` is incorrect: https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/observer.py#L1546, we shouldn't use `torch.per_channel_symmetric` for MinMaxObserver, we should use PerChannelMinMaxObserver for `torch.per_channel_symmetric`

**Comment by jerryzh168** [comment]
are these configs tested in real models? cc @digantdesai

**Comment by digantdesai** [comment]
Good catch, we don't use per_channel that frequently, I can fix this.

**Comment by andrewor14** [comment]
Resolved here: https://github.com/pytorch/pytorch/pull/85883
