### ISSUE TITLE
Multiple `conftest.py` seemed to be loaded when `python run_test.py --include test_ops`

### ISSUE THREAD

**Issue by crcrpar** [pytorch/pytorch#85923]
### 🐛 Describe the bug

In my local environment, when running `python run_test.py --include test_ops` to understand the behavior of [`run_test_ops`](https://github.com/pytorch/pytorch/blob/6db3539e700ce7a81be356700f0803b2002bc63c/test/run_test.py#L690), `--junit-xml-reruns` seemed to be parsed twice; one for test/conftest.py, the other for functorch/test/conftest.py as follows (the full stacktrace is pasted below).

```
________________________ ERROR collecting test session _________________________
Traceback (most recent call last):
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_manager.py", line 115, in register
    hook._maybe_apply_history(hookimpl)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_hooks.py", line 300, in _maybe_apply_history
    res = self._hookexec(self.name, [method], kwargs, False)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/functorch/conftest.py", line 21, in pytest_addoption
    group.addoption(
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 369, in addoption
    raise ValueError("option names %s already added" % conflict)
ValueError: option names {'--junit-xml-reruns'} already added
```

 I've editable installed PyTorch, FWIW:
```
mkozuki@mkozuki-desktop ~/ghq/github.com/crcrpar/pytorch/test master ⇡
torchdev ❯ python -c 'import torch; print(torch.__path__)'
['/home/mkozuki/ghq/github.com/crcrpar/pytorch/torch']
```

Both functorch contest and pytorch conftest have `--junit-xml-reruns`
https://github.com/pytorch/pytorch/blob/7ec12a559cadbb82a1bd6546908897afedd453af/functorch/test/conftest.py#L22
https://github.com/pytorch/pytorch/blob/7ec12a559cadbb82a1bd6546908897afedd453af/test/conftest.py#L22

the full stacktrace:
```shell
mkozuki@mkozuki-desktop ~/ghq/github.com/crcrpar/pytorch/test master ⇡
torchdev ❯ python run_test.py --include test_ops
Ignoring disabled issues:  []
/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/run_test.py:1010: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if torch.version.cuda is not None and LooseVersion(torch.version.cuda) >= "11.6":
Running test_ops ... [2022-09-29 13:39:42.412497]
Ignoring disabled issues:  []
Executing ['/home/mkozuki/miniconda3/envs/torchdev/bin/python', '-bb', 'test_ops.py', '--use-pytest', '-vv', '-x', '--reruns=2', '-rfEX', '--shard-id=0', '--num-shards=3', '-k=not _linalg_cholesky_'] ... [2022-09-29 13:39:44.820570]
Ignoring disabled issues:  []
Executing ['/home/mkozuki/miniconda3/envs/torchdev/bin/python', '-bb', 'test_ops.py', '--use-pytest', '-vv', '-x', '--reruns=2', '-rfEX', '--shard-id=1', '--num-shards=3', '-k=not _linalg_cholesky_'] ... [2022-09-29 13:39:44.869167]
Ignoring disabled issues:  []
Executing ['/home/mkozuki/miniconda3/envs/torchdev/bin/python', '-bb', 'test_ops.py', '--use-pytest', '-vv', '-x', '--reruns=2', '-rfEX', '--shard-id=2', '--num-shards=3', '-k=not _linalg_cholesky_'] ... [2022-09-29 13:39:44.894791]

PRINT LOG FILE of test_ops (/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test-reports/test_ops_ipb507m7)
##[group]PRINT LOG FILE of test_ops (/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test-reports/test_ops_ipb507m7)
/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test_proxy_tensor.py:123: UserWarning: Couldn't import torchvision. Some of our tests use it, try to install it with commands from pytorch.org, post-fixed with `--no-deps` to avoid overwriting the pytorch installation
  warnings.warn("Couldn't import torchvision. Some of our tests use it, try "
============================= test session starts ==============================
platform linux -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/mkozuki/ghq/github.com/crcrpar/pytorch, configfile: pytest.ini
plugins: xdist-2.5.0, forked-1.4.0, hypothesis-6.50.1, rerunfailures-10.2
collected 0 items / 1 error

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
Traceback (most recent call last):
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_manager.py", line 115, in register
    hook._maybe_apply_history(hookimpl)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_hooks.py", line 300, in _maybe_apply_history
    res = self._hookexec(self.name, [method], kwargs, False)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/functorch/conftest.py", line 21, in pytest_addoption
    group.addoption(
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 369, in addoption
    raise ValueError("option names %s already added" % conflict)
ValueError: option names {'--junit-xml-reruns'} already added
=========================== short test summary info ============================
ERROR .. - ValueError: option names {'--junit-xml-reruns'} already added
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.16s ==========================
If in CI, skip info is located in the xml test reports, please either go to s3 or the hud to download them

##[endgroup]
FINISHED PRINT LOG FILE of test_ops (/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test-reports/test_ops_ipb507m7)


PRINT LOG FILE of test_ops (/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test-reports/test_ops_kunljwkv)
##[group]PRINT LOG FILE of test_ops (/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test-reports/test_ops_kunljwkv)
/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test_proxy_tensor.py:123: UserWarning: Couldn't import torchvision. Some of our tests use it, try to install it with commands from pytorch.org, post-fixed with `--no-deps` to avoid overwriting the pytorch installation
  warnings.warn("Couldn't import torchvision. Some of our tests use it, try "
============================= test session starts ==============================
platform linux -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/mkozuki/ghq/github.com/crcrpar/pytorch, configfile: pytest.ini
plugins: xdist-2.5.0, forked-1.4.0, hypothesis-6.50.1, rerunfailures-10.2
collected 0 items / 1 error

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
Traceback (most recent call last):
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_manager.py", line 115, in register
    hook._maybe_apply_history(hookimpl)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_hooks.py", line 300, in _maybe_apply_history
    res = self._hookexec(self.name, [method], kwargs, False)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/functorch/conftest.py", line 21, in pytest_addoption
    group.addoption(
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 369, in addoption
    raise ValueError("option names %s already added" % conflict)
ValueError: option names {'--junit-xml-reruns'} already added
=========================== short test summary info ============================
ERROR .. - ValueError: option names {'--junit-xml-reruns'} already added
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.15s ==========================
If in CI, skip info is located in the xml test reports, please either go to s3 or the hud to download them

##[endgroup]
FINISHED PRINT LOG FILE of test_ops (/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test-reports/test_ops_kunljwkv)


PRINT LOG FILE of test_ops (/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test-reports/test_ops___3u4ihj)
##[group]PRINT LOG FILE of test_ops (/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test-reports/test_ops___3u4ihj)
/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test_proxy_tensor.py:123: UserWarning: Couldn't import torchvision. Some of our tests use it, try to install it with commands from pytorch.org, post-fixed with `--no-deps` to avoid overwriting the pytorch installation
  warnings.warn("Couldn't import torchvision. Some of our tests use it, try "
============================= test session starts ==============================
platform linux -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/mkozuki/ghq/github.com/crcrpar/pytorch, configfile: pytest.ini
plugins: xdist-2.5.0, forked-1.4.0, hypothesis-6.50.1, rerunfailures-10.2
collected 0 items / 1 error

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
Traceback (most recent call last):
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_manager.py", line 115, in register
    hook._maybe_apply_history(hookimpl)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_hooks.py", line 300, in _maybe_apply_history
    res = self._hookexec(self.name, [method], kwargs, False)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/functorch/conftest.py", line 21, in pytest_addoption
    group.addoption(
  File "/home/mkozuki/miniconda3/envs/torchdev/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 369, in addoption
    raise ValueError("option names %s already added" % conflict)
ValueError: option names {'--junit-xml-reruns'} already added
=========================== short test summary info ============================
ERROR .. - ValueError: option names {'--junit-xml-reruns'} already added
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.17s ==========================
If in CI, skip info is located in the xml test reports, please either go to s3 or the hud to download them

##[endgroup]
FINISHED PRINT LOG FILE of test_ops (/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/test-reports/test_ops___3u4ihj)

Traceback (most recent call last):
  File "/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/run_test.py", line 1161, in <module>
    main()
  File "/home/mkozuki/ghq/github.com/crcrpar/pytorch/test/run_test.py", line 1139, in main
    raise RuntimeError(err_message)
RuntimeError: test_ops failed!
```

cc @mruberry @ptrblck @xwang233 

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0a0+git9072d26
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.14.0-1042-oem-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070 Ti
Nvidia driver version: 515.43.04
cuDNN version: Probably one of the following:
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.5.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.5.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.5.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.5.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.5.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.5.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] torch==1.13.0a0+gite15a48d
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.0.1           h06a4308_117
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] torch                     1.13.0a0+gite15a48d           dev_0    <develop>
```

**Comment by mruberry** [comment]
cc @malfet

**Comment by crcrpar** [comment]
hmm, could it be possible to use a different group name for functorch https://github.com/pytorch/pytorch/blob/af9c6bc851cfc8fba9e4c71830b783cb34d92a05/functorch/test/conftest.py#L20?

https://github.com/pytorch/pytorch/blob/af9c6bc851cfc8fba9e4c71830b783cb34d92a05/test/conftest.py#L20

**Comment by crcrpar** [comment]
could this symlink https://github.com/pytorch/pytorch/blob/master/test/functorch to functorch/test mislead pytest?

**Comment by crcrpar** [comment]
it looks like pytorch/functorch/test/conftest.py was removed when functorch/test was thoroughly moved to test test/functorch directory.
