### ISSUE TITLE
PyTorch don't have an op for aten::constant_pad_nd but it isn't a special case.

### ISSUE THREAD

**Issue by blakechi** [pytorch/pytorch#86063]
### 🐛 Describe the bug

When using `torch.onnx.export` for compiling a model from `transformers`, an error indicated the op `aten::constant_pad_nd` isn't supported but it isn't a special case.

- Code to reproduce:
```python
import torch
from transformers import LEDForConditionalGeneration, LEDConfig, LEDTokenizer

tokenizer = LEDTokenizer.from_pretrained("allenai/led-large-16384-arxiv")
model = LEDForConditionalGeneration.from_pretrained(
    "allenai/led-large-16384-arxiv",
)

input_sample = "This is an example for summarization."
input_sample = tokenizer(
    input_sample,
    return_tensors="pt",
)
filepath = "led-large-163840arxiv.onnx"
torch.onnx.export(
    model, 
    tuple(input_sample.values()),
    f=filepath,
    input_names=['input_ids', 'attention_mask'], 
    output_names=['logits'], 
    dynamic_axes={'input_ids': {0: 'batch_size', 1: 'sequence'}, 
                  'attention_mask': {0: 'batch_size', 1: 'sequence'}, 
                  'logits': {0: 'batch_size', 1: 'sequence'}}, 
    do_constant_folding=True, 
    opset_version=13, 
)
```

- Error Message:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pwchi/fine_tuning/env/lib/python3.8/site-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/pwchi/fine_tuning/env/lib/python3.8/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/pwchi/fine_tuning/env/lib/python3.8/site-packages/torch/onnx/utils.py", line 719, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/pwchi/fine_tuning/env/lib/python3.8/site-packages/torch/onnx/utils.py", line 499, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/pwchi/fine_tuning/env/lib/python3.8/site-packages/torch/onnx/utils.py", line 440, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/pwchi/fine_tuning/env/lib/python3.8/site-packages/torch/onnx/utils.py", line 391, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/pwchi/fine_tuning/env/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/pwchi/fine_tuning/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pwchi/fine_tuning/env/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
RuntimeError: 0INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":607, please report a bug to PyTorch. We don't have an op for aten::constant_pad_nd but it isn't a special case.  Argument types: Tensor, int[], bool, 

Candidates:
        aten::constant_pad_nd(Tensor self, int[] pad, Scalar value=0) -> (Tensor)
```

### Versions

```
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-41-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 510.60.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.961
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.6.4
[pip3] torch==1.11.0
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.11.0
[pip3] torchmetrics==0.9.1
[pip3] torchvision==0.12.0
[conda] Could not collect
```

```
Version of transformers:
transformers==4.18.0
```

**Comment by justinchuby** [comment]
Can you test with the latest pytorch nightly build and report back? Thanks!

**Comment by blakechi** [comment]
Hi @justinchuby , thanks for the advice! I upgraded PyTorch to `1.12.1+cu102` and changed `optset_version` to 14 for `torch.onnx.export`, then everything worked fine and smoothly.

I reported the updated code and environment here for future reference:
### Code
```python
import torch
from transformers import LEDForConditionalGeneration, LEDConfig, LEDTokenizer

tokenizer = LEDTokenizer.from_pretrained("allenai/led-large-16384-arxiv")
model = LEDForConditionalGeneration.from_pretrained(
    "allenai/led-large-16384-arxiv",
)

input_sample = "This is an example for summarization."
input_sample = tokenizer(
    input_sample,
    return_tensors="pt",
)
filepath = "led-large-16384-arxiv.onnx"
torch.onnx.export(
    model, 
    tuple(input_sample.values()),
    f=filepath,
    input_names=['input_ids', 'attention_mask'], 
    output_names=['logits'], 
    dynamic_axes={'input_ids': {0: 'batch_size', 1: 'sequence'}, 
                  'attention_mask': {0: 'batch_size', 1: 'sequence'}, 
                  'logits': {0: 'batch_size', 1: 'sequence'}}, 
    do_constant_folding=True, 
    opset_version=14, 
)
```

### Versions
```bash
Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-41-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 510.60.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.961
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.6.4
[pip3] torch==1.12.1
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.11.0
[pip3] torchmetrics==0.9.1
[pip3] torchvision==0.12.0
[conda] Could not collect
```
```
Version of transformers:
transformers==4.22.2
```

### Validation Code
#### Onnx Checker
Didn't raise errors
```python
import onnx

onnx_path = "led-large-16384-arxiv.onnx"
onnx_model = onnx.load(onnx_path)
onnx.checker.check_model(onnx_model)
```

#### Dummy Input
```python
import onnxruntime as ort

ort_session = ort.InferenceSession(onnx_path)
inputs = tokenizer(100 * "This is a testing sentence.", return_tensors="pt")
input_ids = inputs["input_ids"].cpu().numpy()
attention_mask = inputs["attention_mask"].cpu().numpy()
outputs = ort_session.run(
    None,
    {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        # "decoder_input_ids": None,
        # "decoder_attention_mask": None,
    },
)
```

**Comment by blakechi** [comment]
Problem solved so close the issue.
