### ISSUE TITLE
[ONNX] onnx.export fails on frozen top-level ScriptedModule

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#86325]
### 🐛 Describe the bug

Here, onnx.export fails if called on a Scripted that has been frozen:
```
import torch

class Inner(torch.nn.Module):
    def forward(self, x):
        if x > 0 :  
            return x
        else:
            return x*x

class Outer(torch.nn.Module):
    def __init__(self):   
        super().__init__()
        i = Inner()
        self.inner = torch.jit.script(i)

    def forward(self, x):   
        return self.inner(x)

x = torch.zeros(1)
o=Outer()
o.eval()
m = torch.jit.trace_module(o, { 'forward' : (x)})
# borisf: passes if you comment this line out                                                                                                                                                        
m = torch.jit.optimize_for_inference(torch.jit.freeze(m))

torch.onnx.export(m, (x,), 'test.onnx')
```

Result:
python3 not-part.py
Traceback (most recent call last):
  File "not-part.py", line 26, in <module>
    torch.onnx.export(m, (x,), 'test.onnx')
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 479, in export
    _export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1390, in _export
    with exporter_context(model, training, verbose):
  File "/opt/conda/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 175, in exporter_context
    with select_model_mode_for_export(
  File "/opt/conda/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 93, in select_model_mode_for_export
    originally_training = model.training
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_script.py", line 785, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_script.py", line 502, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1261, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RecursiveScriptModule' object has no attribute 'training'

### Versions

Collecting environment information...
PyTorch version: 1.13.0a0+d321be6
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.3
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.99
GPU models and configuration: GPU 0: NVIDIA RTX A5000
Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] k2==1.19.dev20220911+cuda11.7.torch1.13.0a0
[pip3] numpy==1.22.4
[pip3] pytorch-lightning==1.7.5
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.13.0a0+d321be6
[pip3] torch-tensorrt==1.2.0a0
[pip3] torchaudio==0.13.0
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.14.0a0
[conda] k2                        1.19.dev20220911+cuda11.7.torch1.13.0a0          pypi_0    pypi
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-include               2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.22.4           py38h99721a1_0    conda-forge
[conda] pytorch-lightning         1.7.5                    pypi_0    pypi
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.13.0a0+d321be6          pypi_0    pypi
[conda] torch-tensorrt            1.2.0a0                  pypi_0    pypi
[conda] torchaudio                0.13.0                   pypi_0    pypi
[conda] torchmetrics              0.9.3                    pypi_0    pypi
[conda] torchvision               0.14.0a0                 pypi_0    pypi

**Comment by borisfom** [comment]
Possible fix in select_model_mode_for_export: 
root@30f44d0dcd3f:/git/radtts# diff -ur /opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py.orig /opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py
--- /opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py.orig     2022-10-05 21:20:37.425721244 +0000
+++ /opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py  2022-10-05 21:37:07.644794060 +0000
@@ -89,7 +89,7 @@
         )
     originally_training: bool = False

-    if not isinstance(model, torch.jit.ScriptFunction):
+    if hasattr(model, 'training'):
         originally_training = model.training

         # ONNX opset 12 has better support for training amenable models, with updated
@@ -118,10 +118,7 @@
     try:
         yield
     finally:
-        if not (
-            isinstance(model, torch.jit.ScriptFunction)
-            or mode == _C_onnx.TrainingMode.PRESERVE
-        ):
+        if hasattr(model, 'training') and not mode == _C_onnx.TrainingMode.PRESERVE:
             model.train(originally_training)

**Comment by justinchuby** [comment]
Thanks for reporting this issue!

**Comment by kenkoooo** [comment]
Let me show a workaround for guys who have the same issue. 

You may get an error `'RecursiveScriptModule' object has no attribute 'training'` when you try to convert your TorchScript into ONNX like the following:
```python
import torch

# loading your TorchScript
model = torch.jit.load("model.pt")

# converting the model to ONNX
dummy_input = ...
torch.onnx.export(model, dummy_input, "model.onnx")
```

You can avoid the error by adding the field explicitly:
```python
import torch

# loading your TorchScript
model = torch.jit.load("model.pt")

# ADD THIS LINE
model.training = False

# converting the model to ONNX
dummy_input = ...
torch.onnx.export(model, dummy_input, "model.onnx")
```

**Comment by justinchuby** [comment]
> Possible fix in select_model_mode_for_export:
> 

Thanks for the suggestion!
