### ISSUE TITLE
col2im decomposition breaks

### ISSUE THREAD

**Issue by jjsjann123** [pytorch/pytorch#86332]
### 🐛 Describe the bug

Decomposed `col2im` operation raise error
```
torch.Size([1, 384, 512, 1])
Traceback (most recent call last):
  File "repro_col2im_decomp.py", line 13, in <module>
    gm = make_fx(func, decomposition_table=decomp_table)(x, [512, 1], [9, 1], [1, 1], [4, 0], [1, 1])
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 652, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 400, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/pytorch/pytorch/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/opt/pytorch/pytorch/torch/fx/_symbolic_trace.py", line 614, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 414, in wrapped
    out = f(*tensors)
  File "repro_col2im_decomp.py", line 6, in func
    return torch.ops.aten.col2im(x, o_size, k_size, dilation, padding, stride)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 442, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/utils/_python_dispatch.py", line 101, in __torch_dispatch__
    return old.__torch_dispatch__(func, types, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 440, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 465, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 213, in proxy_call
    r = CURRENT_DECOMPOSITION_TABLE[func](*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims_common/wrappers.py", line 212, in _fn
    result = fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_decomp/decompositions.py", line 63, in inner
    r = f(*tree_map(increase_prec, args), **tree_map(increase_prec, kwargs))
  File "/opt/pytorch/pytorch/torch/_decomp/decompositions.py", line 889, in col2im
    output = F.pad(output, (-padding_h, -padding_h, -padding_w, -padding_w))
  File "/opt/pytorch/pytorch/torch/utils/_python_dispatch.py", line 101, in __torch_dispatch__
    return old.__torch_dispatch__(func, types, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 440, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 465, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 218, in proxy_call
    r = func.decompose(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 279, in decompose
    return self._op_dk(dk, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/utils/_python_dispatch.py", line 101, in __torch_dispatch__
    return old.__torch_dispatch__(func, types, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 440, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 465, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 304, in proxy_call
    out = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 257, in __call__
    return self._op(*args, **kwargs or {})
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 4)
```

repro script:
```
import torch

x = torch.randn(1, 3456, 512, device="cuda")

def func(x, o_size, k_size, dilation, padding, stride):
    return torch.ops.aten.col2im(x, o_size, k_size, dilation, padding, stride)

from torch.fx.experimental.proxy_tensor import make_fx
from torch._decomp import get_decompositions
decomp_table = get_decompositions({torch.ops.aten.col2im})
out = func(x, [512, 1], [9, 1], [1, 1], [4, 0], [1, 1])
print(out.shape)
gm = make_fx(func, decomposition_table=decomp_table)(x, [512, 1], [9, 1], [1, 1], [4, 0], [1, 1])
print(gm.graph)
```

### Versions

Repro'ed on ToT upstream
```
commit 736adc08084814c13d57324f74adad091e304eb2 (HEAD -> master, origin/master, origin/HEAD)
Author: Zachary DeVito <zdevito@meta.com>
Date:   Tue Oct 4 21:50:27 2022 -0700

    Memory snapshots from C++ (#86190)

    Sometimes the driving process want to save memory snapshots but isn't Python.
    Add a simple API to turn it on without python stack traces. It still
    saves to the same format for the vizualization and summary scripts, using
    the C++ Pickler.
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/86190
    Approved by: https://github.com/ezyang
```

cc @SherlockNoMad @ngimel

**Comment by Chillee** [comment]
@lezcano

**Comment by lezcano** [comment]
ooops. I'll look into this tomorrow!

**Comment by jjsjann123** [comment]
> ooops. I'll look into this tomorrow!

Thanks a lot, turns out the failure happens out side of our code path where we can skip decomposition. So currently there's not a clean way for me to WAR this.

**Comment by Chillee** [comment]
@jjsjann123 an easy (but bad) workaround is to turn off fake tensors, which I believe should resolve this.

**Comment by jjsjann123** [comment]
> @jjsjann123 an easy (but bad) workaround is to turn off fake tensors, which I believe should resolve this.

Thanks for the tip. I'm not seeing clearly where fake tensor is enabled in the stack. Looks like the default in fx proxy_tensor is tracing in "real". I tried to change torchdynamo config.py `dynamic_propagation` and `fake_tensor_propagation` to be False but that doesn't seem to get me around this.
Hacking around the stack is also not idea. I'm not trying to get this model to run today, so I'm happy to wait on @lezcano 's fix. :bow:

**Comment by lezcano** [comment]
I put up a PR fixing this issue.
