### ISSUE TITLE
Previous torch version 1.10.1+cu111 fails installation with given link, change link to /whl/cu111/

### ISSUE THREAD

**Issue by jturner116** [pytorch/pytorch#86630]
### 🐛 Describe the bug

The download link for torch version 1.10.1+cu111 should be changed. 

```Python
pipenv install --extra-index-url https://download.pytorch.org/whl/torch_stable.html torch==1.10.1+cu111 torchvision==0.11.2+cu111
```
Returns the following error on Ubuntu 20.4, Python 3.8.10

```
ERROR: Could not find a version that satisfies the requirement torch==1.10.1+cu111 (from -r /tmp/pipenv-251ewxjx-requirements/pipenv-gex9y_do-requirement.txt (line 1)) (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1)
ERROR: No matching distribution found for torch==1.10.1+cu111 (from -r /tmp/pipenv-251ewxjx-requirements/pipenv-gex9y_do-requirement.txt (line 1))
```

Changing the link from ~/whl/torch_stable.html   to ~/whl/cu111/   works as intended.

### Versions

```Collecting environment information...
PyTorch version: 1.10.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-105-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000
GPU 4: NVIDIA RTX A6000
GPU 5: NVIDIA RTX A6000
GPU 6: NVIDIA RTX A6000
GPU 7: NVIDIA RTX A6000

Nvidia driver version: 510.54
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.10.1+cu111
[pip3] torchvision==0.11.2+cu111
[conda] Could not collect
```

cc @svekars @holly1238

**Comment by malfet** [comment]
I assume you are referencing instructions from https://pytorch.org/get-started/previous-versions/

**Comment by jturner116** [comment]
Yes!

**Comment by malfet** [comment]
@jturner116 populated it with the right URLs, would be nice if you can check that they are working from you.

**Comment by jturner116** [comment]
@malfet Thanks for the quick follow up!
I'm still getting weird behavior with the CUDA 11.1 link [here](https://pytorch.org/get-started/previous-versions/#linux-and-windows-5), but I'm trying to use pipenv. I think it is possibly a pipenv issue
```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/cli/command.py", line 194, in install
    do_install(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 2145, in do_install
    do_init(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 1228, in do_init
    do_lock(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 1057, in do_lock
    venv_resolve_deps(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 1314, in venv_resolve_deps
    deps = convert_deps_to_pip(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 1450, in convert_deps_to_pip
    req = new_dep.as_line(sources=indexes if include_index else None).strip()
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2811, in as_line
    index_string = " ".join(source_list)
TypeError: sequence item 11: expected str instance, NoneType found
```
That error is on building requirements for pipfile lock. But using the following link instead, pipfile locks without error
https://download.pytorch.org/whl/cu111/

I'm not sure why the two links would behave differently in pipenv, I treated them identically when testing installs.
Thanks for your help :)
