### ISSUE TITLE
RuntimeError: could not construct a memory descriptor using a format tag

### ISSUE THREAD

**Issue by Co1lin** [pytorch/pytorch#86664]
### 🐛 Describe the bug

Hi! When optimizing the model by `optimize_for_inference`, I encountered this `RuntimeError`. The model works fine in eager mode, and also could be traced. But when using `optimize_for_inference` after tracing, it leads to an error.

```python
import torch
import torch.nn as nn

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(
            1, 2, kernel_size=(509,2), stride=3, padding=255, dilation=(1, 1014),
        )
        
    def forward(self, i0, i1):
        x = torch.max(i0, i1)
        y = self.conv1(x)
        return y

i0 = torch.zeros((1,1,2,505), dtype=torch.float32)
i1 = torch.zeros((1,2,505), dtype=torch.float32)

mod = MyModule()

out = mod(i0, i1)
print(f'eager: out = {out}') # <-- works fine

exported = torch.jit.trace(mod, [i0, i1])
exported = torch.jit.optimize_for_inference(exported) # <-- RuntimeError: could not construct a memory descriptor using a format tag

eout = exported(i0, i1)
print(f'JIT: eout = {eout}')

assert torch.allclose(out, eout)
```

Logs:

```python
eager: out = tensor([[[[-0.0269],
          [-0.0269]],

         [[-0.0094],
          [-0.0094]]]], grad_fn=<ConvolutionBackward0>)
Traceback (most recent call last):
  File "/home/colin/code/bug.py", line 25, in <module>
    exported = torch.jit.optimize_for_inference(exported) # <-- RuntimeError: could not construct a memory descriptor using a format tag
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/jit/_freeze.py", line 218, in optimize_for_inference
    torch._C._jit_pass_optimize_for_inference(mod._c, other_methods)
RuntimeError: could not construct a memory descriptor using a format tag
```

### Versions

```python
PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.12.1+cu116
[pip3] torchaudio==0.12.1+cu116
[pip3] torchvision==0.13.1+cu116
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] torch                     1.12.1+cu116             pypi_0    pypi
[conda] torchaudio                0.12.1+cu116             pypi_0    pypi
[conda] torchvision               0.13.1+cu116             pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin

**Comment by XiaobingSuper** [comment]
It will be fixed at the next ideep upgrade.

**Comment by Co1lin** [comment]
It works now. Thanks!
