### ISSUE TITLE
[PrimTorch] Assertion error in partitioner

### ISSUE THREAD

**Issue by rdspring1** [pytorch/pytorch#86698]
### 🐛 Describe the bug

Repro commands:
`python benchmarks/timm_models.py --training -d cuda --backend nvprims_nvfuser --performance -k convit_base --amp`
`python benchmarks/timm_models.py --training -d cuda --backend nvprims_nvfuser --performance -k poolformer`

Failure Trace:
```python
Traceback (most recent call last):
  File "/home/rds4/workspace/nvprims-torchdynamo/benchmarks/common.py", line 1174, in warmup
    fn(model, example_inputs)
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torchdynamo-1.13.0.dev0-py3.8-linux-x86_64.egg/torchdynamo/eval_frame.py", line 175, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/timm_models.py", line 322, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/timm_models.py", line 323, in <graph break in forward_and_backward_pass>
    cloned_inputs = clone_inputs(inputs)
  File "benchmarks/timm_models.py", line 324, in <graph break in forward_and_backward_pass>
    mod.zero_grad(True)
  File "benchmarks/timm_models.py", line 326, in <graph break in forward_and_backward_pass>
    pred = mod(*cloned_inputs)
  File "/home/rds4/workspace/my_pytorch/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/timm-0.6.5-py3.8.egg/timm/models/convit.py", line 332, in forward
    def forward(self, x):
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torchdynamo-1.13.0.dev0-py3.8-linux-x86_64.egg/torchdynamo/eval_frame.py", line 175, in _fn
    return fn(*args, **kwargs)
  File "/home/rds4/workspace/my_pytorch/functorch/_src/aot_autograd.py", line 812, in forward
    return compiled_f(
  File "/home/rds4/workspace/my_pytorch/functorch/_src/aot_autograd.py", line 803, in new_func
    return compiled_fn(args)
  File "/home/rds4/workspace/my_pytorch/functorch/_src/aot_autograd.py", line 230, in g
    return f(*args)
  File "/home/rds4/workspace/my_pytorch/functorch/_src/aot_autograd.py", line 449, in compiled_function
    return CompiledFunction.apply(*remove_dupe_args(args))
  File "/home/rds4/anaconda3/lib/python3.8/site-packages/torchdynamo-1.13.0.dev0-py3.8-linux-x86_64.egg/torchdynamo/eval_frame.py", line 175, in _fn
    return fn(*args, **kwargs)
  File "/home/rds4/workspace/my_pytorch/functorch/_src/aot_autograd.py", line 416, in forward
    fw_outs = call_func_with_args(
  File "/home/rds4/workspace/my_pytorch/functorch/_src/aot_autograd.py", line 261, in call_func_with_args
    out = normalize_as_list(f(*args))
  File "/home/rds4/workspace/my_pytorch/torch/_prims/executor.py", line 25, in execute
    return nvfuser_execute_partitioned(
  File "/home/rds4/workspace/my_pytorch/torch/_prims/nvfuser_executor.py", line 343, in nvfuser_execute_partitioned
    gm, is_partitioned = maybe_partition_graph(
  File "/home/rds4/workspace/my_pytorch/torch/_prims/nvfuser_executor.py", line 302, in maybe_partition_graph
    partitions = partitioner.propose_partitions()
  File "/home/rds4/workspace/my_pytorch/torch/fx/passes/infra/partitioner.py", line 164, in propose_partitions
    merge_single_node(node, id)
  File "/home/rds4/workspace/my_pytorch/torch/fx/passes/infra/partitioner.py", line 107, in merge_single_node
    assert node not in assignment
```

### Versions

Torchdynamo: 7f84bef3
Pytorch: ad2b04c3

**Comment by jjsjann123** [comment]
linking #86511 
I'm patching this right now.
