### ISSUE TITLE
TestReductionsCUDA.test_reductions_large_half_tensors_cuda_complex32 fails with "mean_cuda" not implemented for 'ComplexHalf'

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#86743]
### 🐛 Describe the bug

TestReductionsCUDA.test_reductions_large_half_tensors_cuda_complex32 fails with "mean_cuda" not implemented for 'ComplexHalf'

```python
root@9dd3e47db792:/opt/pytorch/pytorch# python test/test_reductions.py -v -k TestReductionsCUDA.test_reductions_large_half_tensors_cuda_complex32
test_reductions_large_half_tensors_cuda_complex32 (__main__.TestReductionsCUDA) ... test/test_reductions.py:3390: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/EmptyTensor.cpp:31.)
  t = torch.ones(2**31, device=device, dtype=dtype)
ERROR

======================================================================
ERROR: test_reductions_large_half_tensors_cuda_complex32 (__main__.TestReductionsCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1990, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1990, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 391, in instantiated_test
    raise rte
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 984, in only_fn
    return fn(slf, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 945, in dep_fn
    return fn(self, *args, **kwargs)
  File "test/test_reductions.py", line 3402, in test_reductions_large_half_tensors
    self.assertEqual(torch.mean(t), expected)
RuntimeError: "mean_cuda" not implemented for 'ComplexHalf'

----------------------------------------------------------------------
Ran 1 test in 2.856s

FAILED (errors=1)
```

### Versions

failed: 17074389dec0ee3e2a949fb75bb51cde471d17fe

passed: c6b7c33885eeff9dc125f87c7134772d59d0ba21

cc @ptrblck @ngimel

**Comment by malfet** [comment]
I've just talked to @ngimel about it as it block enabling A10G testing
This check is wrong
https://github.com/pytorch/pytorch/pull/85596/files#diff-32bf0b34f90bc9c125c06a43801a4cbe5fcd8916744991761be00117b6a0bdf4R3398-R3402
Fix is coming
