### ISSUE TITLE
Broadcasting add for nested_tensor

### ISSUE THREAD

**Issue by frankier** [pytorch/pytorch#86888]
### 🚀 The feature, motivation and pitch

It would be useful when multiple a cutoff based ordinal regression heads of the CORAL variety https://github.com/Raschka-research-group/coral-pytorch to be able to do broadcasting addition, like so:

```
>>> import torch
imp^[[Aort torch.nested
>>> torch.nested.as_nested_tensor([torch.tensor([3.4, 2.3, 4.5])]) + torch.nested.nested_tensor([torch.tensor([-2.3, 0.4, 5.3]), torch.tensor([-2.3, 0.4, 5.3])])
/home/frankier/edu/doc/bert_ordinal/nestedplay/.venv/lib/python3.10/site-packages/torch/nested/__init__.py:84: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:175.)
```

### Alternatives

Copy stuff like so (current workaround):

```
>>> torch.nested.as_nested_tensor([torch.tensor([3.4, 2.3, 4.5]),torch.tensor([3.4, 2.3, 4.5])]) + torch.nested.nested_tensor([torch.tensor([-2.3, 0.4, 5.3]), torch.tensor([-2.3,
 0.4, 5.3])])
nested_tensor([
  tensor([1.1000, 2.7000, 9.8000]),
  tensor([1.1000, 2.7000, 9.8000])
])
```

**Comment by frankier** [comment]
I guess it would be nice if mul were supported too (for elementwise affine transform)

```
>>> torch.nested.as_nested_tensor([torch.tensor([1.5])]) * torch.nested.as_nested_tensor([torch.tensor([3.1, 5.4]), torch.tensor([0.5])])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: mul does not support broadcasting when given a NestedTensor
```

It would also be nice if non-nested_tensor worked when it was a compatible shape

```
>>> torch.tensor([1.5]) * torch.nested.as_nested_tensor([torch.tensor([3.1, 5.4]), torch.tensor([0.5])])
/home/frankier/edu/doc/bert_ordinal/.venv/lib/python3.10/site-packages/torch/nested/__init__.py:84: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:175.)
  return torch._nested_tensor_from_tensor_list(tensor_list, dtype, None, device, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected both self and other to be nested, but got a non-nested self and nested other
```

**Comment by drisspg** [comment]
Thanks for commenting with this feature request, I am going to add these to this list: https://github.com/pytorch/pytorch/issues/83994
