### ISSUE TITLE
Add tensor.to()/tensor._to_copy() support to nested_tensor

### ISSUE THREAD

**Issue by frankier** [pytorch/pytorch#87034]
### 🚀 The feature, motivation and pitch

This is quite a common operation so could be used for many things, but a major thing this enables is a module using nested_tensor as a parameter. Many PyTorch frameworks, here huggingface transformers' `Trainer` class will attempt to load a model on the CPU before copying it over to a CUDA device (or this is what it looks like at least). Say we have a module somewhere in the module tree which has

```
    class MyRaggedModule(nn.Module):
        def __init__(self, sizes, device=None):
            super().__init__()
            self.weights = torch.nn.Parameter(torch.nested.nested_tensor([
                torch.empty(size, device=device, dtype=torch.float)
                for size in sizes
            ]))
            self.reset_parameters()

        def reset_parameters(self):
            with torch.no_grad():
                bits = self.weights.unbind()
                for bit in bits:
                    torch.nn.init.normal_(bit)
```

Then when we attempt to train, the framework will try to copy the tensor, which will fail 

```
Traceback (most recent call last):
  File "train.py", line 176, in <module>
    main()
  File "train.py", line 164, in main
    trainer = Trainer(
  File "/users/frrobert/.local/lib/python3.10/site-packages/transformers/trainer.py", line 437, in __init__
    self._move_model_to_device(model, args.device)
  File "/users/frrobert/.local/lib/python3.10/site-packages/transformers/trainer.py", line 703, in _move_model_to_device
    model = model.to(device)
  File "/CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1112, in to
    return self._apply(convert)
  File "/CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 764, in _apply
    module._apply(fn)
  File "/CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 787, in _apply
    param_applied = fn(param)
  File "/CSC_CONTAINER/miniconda/envs/env1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Could not run 'aten::_to_copy' with arguments from the 'NestedTensorCUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_to_copy' is only available for these backends: [CPU, CUDA, HIP, XLA, MPS, IPU, XPU, HPU, VE, Lazy, Meta, PrivateUse1, PrivateUse2, PrivateUse3, FPGA, ORT, Vulkan, Metal, QuantizedCPU, QuantizedCUDA, QuantizedHIP, QuantizedXLA, QuantizedMPS, QuantizedIPU, QuantizedXPU, QuantizedHPU, QuantizedVE, QuantizedLazy, QuantizedMeta, QuantizedPrivateUse1, QuantizedPrivateUse2, QuantizedPrivateUse3, CustomRNGKeyId, MkldnnCPU, SparseCPU, SparseCUDA, SparseHIP, SparseXLA, SparseMPS, SparseIPU, SparseXPU, SparseHPU, SparseVE, SparseLazy, SparseMeta, SparsePrivateUse1, SparsePrivateUse2, SparsePrivateUse3, SparseCsrCPU, SparseCsrCUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].
```

### Alternatives

ModuleList or arrange for model to never be copied

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @mikaylagawarecki

**Comment by drisspg** [comment]
Thanks for opening up this issue, we are actually working on implementing this function and should have a PR soon. The author of that PR is @ani300. Will post updates on this issue.

**Comment by ani300** [comment]
The PR is #87146

**Comment by frankier** [comment]
Looks like it's merged now so closing. Thanks @ani300 !
