### ISSUE TITLE
Segmentation fault: 11 when running "import torch" on Mac OS X

### ISSUE THREAD

**Issue by daocunyang** [pytorch/pytorch#87041]
### 🐛 Describe the bug

Hi team, I'm getting segmentation fault when trying to import torch in my local machine:
```
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:59:23) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Segmentation fault: 11
```
I have looked through past issues and tried to look for similar errors, but haven't found anything related to seg fault 11. 
I installed `gdb` and tried to debug, but I'm not sure if it has some issues and the output looks correct:
`gdb python
r -c "import torch"`
```
Reading symbols from python...

warning: `/tmp/lto.o': can't open to read symbols: No such file or directory.
(No debugging symbols found in python)
(gdb) 
(gdb) r -c "import torch"
Starting program: /Users/Darren/opt/miniconda3/envs/computer-vision/bin/python -c "import torch"

[New Thread 0x1803 of process 21505]
[New Thread 0x1a03 of process 21505]
warning: unhandled dyld version (17)
  File "<string>", line 1
    "import
          ^
SyntaxError: EOL while scanning string literal
[Inferior 1 (process 21505) exited with code 01]

```
Also tried running [collect_env.py](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py), but it gave the same "Segmentation fault: 11" error from the line `import torch`. 

I installed PyTorch with `pip3 install torch torchvision`, the versions are torch 1.12.1  and torchvision 0.13.1. I was trying to install for CPU only since I don't have a GPU. 

Any idea on what might be causing the seg fault? Thanks

### Versions

I had to manually set `TORCH_AVAILABLE` to false to bypass `import torch`, which would otherwise cause a seg fault 11 error. 

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A
OS: macOS 11.4 (x86_64)
GCC version: Could not collect
Clang version: 14.0.4
CMake version: version 3.22.1
Libc version: N/A
Python version: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:59:23)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: Darwin-20.5.0-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A
Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.1
[pip3] torchvision==0.13.1
[conda] numpy                     1.21.6           py37h345d48f_0    conda-forge
[conda] torch                     1.12.1                   pypi_0    pypi
[conda] torchvision               0.13.1                   pypi_0    pypi
```

**Comment by albanD** [comment]
hi,

For gdb, you can just `run`. Then once the python prompt appears (within gdb), do the import torch as usual. That should give you the right stack trace.

**Comment by daocunyang** [comment]
> albanD

Thanks, I got the following output
```
Starting program: /Users/Darren/opt/miniconda3/envs/computer-vision/bin/python 
[New Thread 0x2007 of process 50585]
[New Thread 0x1f17 of process 50585]
warning: unhandled dyld version (17)
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:59:23) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
[New Thread 0x1b03 of process 50585]
[New Thread 0x2013 of process 50585]
[New Thread 0x220f of process 50585]

Thread 4 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x2013 of process 50585]
0x0000000103a9358a in ?? ()
```
Not sure how to proceed from here. Fortunately I was able to bypass the error by creating a new conda env and run `import torch` with no issue there.

**Comment by albanD** [comment]
Once the program stops due to the segfault, you can type "bt" to get the backtrace and share it here please?

**Comment by daocunyang** [comment]
> Once the program stops due to the segfault, you can type "bt" to get the backtrace and share it here please?

Yes, output is the following:
```
Thread 5 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x220f of process 6108]
0x0000000103a9358a in ?? ()
(gdb) bt
#0  0x0000000103a9358a in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb)
```
