### ISSUE TITLE
`split()` method with `torch.ao.quantization.prepare()` or `torch.ao.quantization.prepare_qat()` brokes ONNX export

### ISSUE THREAD

**Issue by omerferhatt** [pytorch/pytorch#87069]
### 🐛 Describe the bug

Tensor `split()` method not working when `prepare()` or `prepare_qat()` added while ONNX exporting.

Here's the model definition:

```python3
import io
import torch
import torch.nn as nn
import torch.ao.quantization
import torch.nn.quantized
from torch.ao.quantization import DeQuantStub, QuantStub

class SplitConvQuant(nn.Module):
    def __init__(self):
        super(SplitConvQuant, self).__init__()
        self.conv1 = nn.Conv2d(32, 32, kernel_size=1, dilation=1, padding=1, groups=2, bias=False)
        self.conv2 = nn.Conv2d(32, 32, kernel_size=1, dilation=4, padding=1, groups=2, bias=False)

        self.quant_float = torch.nn.quantized.FloatFunctional()
        self.quant_stub = QuantStub()
        self.dequant_stub = DeQuantStub()

    def forward(self, x):
        x = self.quant_stub(x)
        x1, x2 = x.split(32, dim=1)
        x1 = self.conv1(x1)
        x2 = self.conv2(x2)
        x = self.quant_float.cat([x1, x2], dim=1)
        x = self.dequant_stub(x)
        return x
```

and export functions

```python3
if __name__ == "__main__":
    model = SplitConvQuant()
    model.qconfig = torch.ao.quantization.get_default_qat_qconfig("fbgemm")

    x = torch.rand(1, 64, 32, 32)
    # torch.ao.quantization.prepare_qat(model, inplace=True)
    torch.ao.quantization.prepare(model, inplace=True)
    model.eval()

    torch.ao.quantization.convert(model, inplace=True)

    model.eval()
    x = torch.rand(1, 64, 32, 32)
    model(x)

    f = io.BytesIO()

    torch.onnx.export(
        model,
        x,
        f,
        opset_version=16,
        input_names=["input"],
        output_names=["output"],
        verbose=True,
    )
```

---

Traceback

```
/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/ao/quantization/observer.py:176: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(
/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/ao/quantization/utils.py:280: UserWarning: must run observer before calling calculate_qparams. Returning default values.
  warnings.warn(
WARNING: The shape inference of prim::TupleConstruct type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
ONNX graph being constructed during exception:
graph(%x : Float(1, 64, 32, 32, strides=[65536, 1024, 32, 1], requires_grad=0, device=cpu),
      %conv1._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %conv2._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase):
  %3 : Long(device=cpu) = onnx::Constant[value={1}]()
  %4 : Long(device=cpu) = onnx::Constant[value={32}]()
  %5 : Long(device=cpu) = onnx::Constant[value={13}](), scope: __module.quant_stub
  %6 : Long(device=cpu) = onnx::Constant[value={0}](), scope: __module.quant_stub
  %7 : Double(device=cpu) = onnx::Constant[value={1}](), scope: __module.quant_stub
  %8 : Byte(device=cpu) = onnx::Cast[to=2](%6), scope: __module.quant_stub # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/nn/quantized/modules/__init__.py:53:0
  %9 : Float(device=cpu) = onnx::Cast[to=1](%7), scope: __module.quant_stub # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/nn/quantized/modules/__init__.py:53:0
  %10 : Byte(1, 64, 32, 32, strides=[65536, 1024, 32, 1], device=cpu) = onnx::QuantizeLinear(%x, %9, %8), scope: __module.quant_stub # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/nn/quantized/modules/__init__.py:53:0
  %11 : Tensor = prim::TupleConstruct(%10, %9, %8), scope: __module.quant_stub # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/nn/quantized/modules/__init__.py:53:0
  %12 : Long(2, strides=[1], device=cpu) = onnx::Constant[value= 32  32 [ CPULongType{2} ]]() # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/_tensor.py:603:0
  %input : Tensor, %input.3 : Tensor = onnx::Split[axis=1](%11, %12) # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/_tensor.py:603:0
  %15 : Char(32, 16, 1, 1, strides=[16, 1, 1, 1], device=cpu) = onnx::Constant[value=<Tensor>]()
  %16 : Float(32, strides=[1], device=cpu) = onnx::Constant[value=<Tensor>]()
  %17 : Int(32, strides=[1], device=cpu) = onnx::Constant[value=<Tensor>]()
  %18 : Long(1, strides=[1], device=cpu) = onnx::Constant[value={0}]()
  %19 : Tensor = prim::TupleConstruct(%15, %16, %17, %18)
  %20 : Float(32, strides=[1], device=cpu) = onnx::Constant[value=<Tensor>]()
  %21 : UNKNOWN_SCALAR(device=cpu) = onnx::Constant[value=[1, 1]]()
  %22 : UNKNOWN_SCALAR(device=cpu) = onnx::Constant[value=[1, 1]]()
  %23 : UNKNOWN_SCALAR(device=cpu) = onnx::Constant[value=[1, 1]]()
  %24 : UNKNOWN_SCALAR(device=cpu) = onnx::Constant[value=2]()
  return ()

Torch IR graph at exception: graph(%x : Float(1, 64, 32, 32, strides=[65536, 1024, 32, 1], requires_grad=0, device=cpu),
      %conv1._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase,
      %conv2._packed_params : __torch__.torch.classes.quantized.Conv2dPackedParamsBase):
  %49 : Long(device=cpu) = prim::Constant[value={1}]()
  %50 : Long(device=cpu) = prim::Constant[value={32}]()
  %51 : Long(device=cpu) = prim::Constant[value={13}](), scope: __module.quant_stub
  %52 : Long(device=cpu) = prim::Constant[value={0}](), scope: __module.quant_stub
  %53 : Double(device=cpu) = prim::Constant[value={1}](), scope: __module.quant_stub
  %11 : Tensor = aten::quantize_per_tensor(%x, %53, %52, %51), scope: __module.quant_stub # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/nn/quantized/modules/__init__.py:53:0
  %input.1 : Tensor, %input : Tensor = aten::split[_outputs=2](%11, %50, %49) # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/_tensor.py:603:0
  %29 : Tensor = prim::Constant[value=<Tensor>]()
  %30 : Tensor = prim::Constant[value=<Tensor>]()
  %31 : Tensor = prim::Constant[value=<Tensor>]()
  %32 : Tensor = prim::Constant[value={0}]()
  %33 : Tensor = prim::TupleConstruct(%29, %30, %31, %32)
  %34 : Tensor = prim::Constant[value=<Tensor>]()
  %35 : Tensor = onnx::Constant[value=[1, 1]]()
  %36 : Tensor = onnx::Constant[value=[1, 1]]()
  %37 : Tensor = onnx::Constant[value=[1, 1]]()
  %38 : Tensor = onnx::Constant[value=2]()
  %16 : Tensor = quantized::conv2d(%input.1, %33, %34, %35, %36, %37, %38, %53, %52), scope: __module.conv1 # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/_ops.py:143:0
  %39 : Tensor = prim::Constant[value=<Tensor>]()
  %40 : Tensor = prim::Constant[value=<Tensor>]()
  %41 : Tensor = prim::Constant[value=<Tensor>]()
  %42 : Tensor = prim::Constant[value={0}]()
  %43 : Tensor = prim::TupleConstruct(%39, %40, %41, %42)
  %44 : Tensor = prim::Constant[value=<Tensor>]()
  %45 : Tensor = onnx::Constant[value=[1, 1]]()
  %46 : Tensor = onnx::Constant[value=[1, 1]]()
  %47 : Tensor = onnx::Constant[value=[4, 4]]()
  %48 : Tensor = onnx::Constant[value=2]()
  %18 : Tensor = quantized::conv2d(%input, %43, %44, %45, %46, %47, %48, %53, %52), scope: __module.conv2 # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/_ops.py:143:0
  %19 : Tensor[] = prim::ListConstruct(%16, %18)
  %Xq : Tensor = quantized::cat(%19, %49, %53, %52) # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/_ops.py:143:0
  %21 : Tensor = aten::dequantize(%Xq), scope: __module.dequant_stub # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/nn/quantized/modules/__init__.py:85:0
  return (%21)

Traceback (most recent call last):
  File "test_layer.py", line 46, in <module>
    torch.onnx.export(
  File "/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/onnx/utils.py", line 731, in _model_to_graph
    graph = _optimize_graph(
  File "/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/onnx/utils.py", line 308, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/onnx/__init__.py", line 416, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/onnx/utils.py", line 1406, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/onnx/symbolic_opset13.py", line 562, in conv2d
    input, input_scale, _, _ = symbolic_helper.dequantize_helper(g, q_input)
  File "/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 1226, in dequantize_helper
    unpacked_qtensors = _unpack_tuple(qtensor)
  File "/home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 154, in _unpack_tuple
    raise RuntimeError(
RuntimeError: ONNX symbolic expected node type `prim::TupleConstruct`, got `%input : Tensor, %input.3 : Tensor = onnx::Split[axis=1](%11, %12) # /home/omer/alpha-trainer/.venv/lib/python3.8/site-packages/torch/_tensor.py:603:0
```

### Versions

```
Collecting environment information...
PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1018-gcp-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB

Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.3
[pip3] pytorch-lightning==1.7.7
[pip3] pytorch-loss==0.0.0
[pip3] pytorch-ranger==0.1.1
[pip3] segmentation-models-pytorch==0.3.0
[pip3] torch==1.12.1+cu116
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.12.1+cu116
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.13.1+cu116
[conda] Could not collect
```

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by dzdang** [comment]
see https://discuss.pytorch.org/t/quantized-pytorch-model-exports-to-onnx/144968/6
