### ISSUE TITLE
pyHIPIFY hangs if you run it as root

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#8707]
Steps to reproduce:

1. `docker run -it 308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-clang3.8-rocmnightly-ubuntu16.04:126` (note that you are running as root)
2. git clone PyTorch
3. `jenkins/pytorch/build.sh`

It hangs at:

```
/root/pytorch-1/aten/src/ATen/cpu/tbb/tbb_remote/src/old/concurrent_queue_v│
2.h                                                                                                   │[#######-------------] 34%
Traceback (most recent call last):                                                                  │
  File "/opt/rocm/bin/hipify-python.py", line 946, in <module>                                        │    main()                                                                                            │
  File "/opt/rocm/bin/hipify-python.py", line 938, in main                                            │    include_dirs=args.include_dirs)                                                                   │
  File "/opt/rocm/bin/hipify-python.py", line 127, in walk_over_directory                             │
    preprocessor(filepath, stats)                                                                     │
  File "/opt/rocm/bin/hipify-python.py", line 473, in preprocessor                                    │
    output_source = processKernelLaunches(output_source, stats)                                       │
  File "/opt/rocm/bin/hipify-python.py", line 239, in processKernelLaunches                           │    get_kernel_positions = [k for k in find_kernel_bounds(string)]                                    │
  File "/opt/rocm/bin/hipify-python.py", line 230, in find_kernel_bounds                              │
    kernel_end = string.find(">>>", kernel_start) + 3
```

It works if I am jenkins user (e.g., pass `-u jenkins` to docker invocation)

**Comment by ezyang** [comment]
I think this is fixed now.
