### ISSUE TITLE
Failing periodic test: test_comprehensive_masked_cumprod_cuda_float16 (__main__.TestInductorOpInfoCUDA) 

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#87089]
### 🐛 Describe the bug

This test started failing periodic:
cuda11.6-py3.10-gcc7-sm86 / test (default, 1, 4, linux.g5.4xlarge.nvidia.gpu):
- test_comprehensive_masked_cumprod_cuda_float16 (__main__.TestInductorOpInfoCUDA) 

(Probably unrelated, but the tests in https://github.com/pytorch/pytorch/issues/87087 started failing a few prs before this one)

You can find the logs from the failure here:
https://hud.pytorch.org/pytorch/pytorch/commit/30f6f6903c7e68d2105d5b8dfe8841a788bab051

Specifically:

```
2022-10-16T21:39:26.1245187Z ======================================================================
2022-10-16T21:39:26.1245375Z FAIL [0.262s]: test_comprehensive_masked_cumprod_cuda_float16 (__main__.TestInductorOpInfoCUDA)
2022-10-16T21:39:26.1245591Z ----------------------------------------------------------------------
2022-10-16T21:39:26.1245691Z Traceback (most recent call last):
2022-10-16T21:39:26.1245973Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2008, in wrapper
2022-10-16T21:39:26.1246061Z     method(*args, **kwargs)
2022-10-16T21:39:26.1246368Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
2022-10-16T21:39:26.1246471Z     result = test(self, **param_kwargs)
2022-10-16T21:39:26.1246763Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 824, in test_wrapper
2022-10-16T21:39:26.1246858Z     return test(*args, **kwargs)
2022-10-16T21:39:26.1247149Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 1020, in only_fn
2022-10-16T21:39:26.1247240Z     return fn(self, *args, **kwargs)
2022-10-16T21:39:26.1247516Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1315, in wrapper
2022-10-16T21:39:26.1247606Z     fn(*args, **kwargs)
2022-10-16T21:39:26.1247756Z   File "/opt/conda/lib/python3.10/unittest/mock.py", line 1369, in patched
2022-10-16T21:39:26.1247864Z     return func(*newargs, **newkeywargs)
2022-10-16T21:39:26.1248063Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor_opinfo.py", line 599, in test_comprehensive
2022-10-16T21:39:26.1248134Z     raise e
2022-10-16T21:39:26.1248331Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor_opinfo.py", line 557, in test_comprehensive
2022-10-16T21:39:26.1248415Z     self.check_model_cuda(
2022-10-16T21:39:26.1248565Z   File "/opt/conda/lib/python3.10/unittest/mock.py", line 1369, in patched
2022-10-16T21:39:26.1248674Z     return func(*newargs, **newkeywargs)
2022-10-16T21:39:26.1248864Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor.py", line 332, in check_model_cuda
2022-10-16T21:39:26.1248941Z     check_model(
2022-10-16T21:39:26.1249088Z   File "/opt/conda/lib/python3.10/unittest/mock.py", line 1369, in patched
2022-10-16T21:39:26.1249196Z     return func(*newargs, **newkeywargs)
2022-10-16T21:39:26.1249377Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor.py", line 288, in check_model
2022-10-16T21:39:26.1249458Z     self.assertEqual(
2022-10-16T21:39:26.1249743Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2472, in assertEqual
2022-10-16T21:39:26.1249822Z     assert_equal(
2022-10-16T21:39:26.1250089Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
2022-10-16T21:39:26.1250190Z     raise error_metas[0].to_error(msg)
2022-10-16T21:39:26.1250380Z AssertionError: Tensor-likes are not close!
2022-10-16T21:39:26.1250387Z 
2022-10-16T21:39:26.1250487Z Mismatched elements: 1 / 5 (20.0%)
2022-10-16T21:39:26.1250689Z Greatest absolute difference: 0.03125 at index (1,) (up to 1e-05 allowed)
2022-10-16T21:39:26.1250841Z Greatest relative difference: 0.0011210762331838565 at index (1,) (up to 0.001 allowed)
2022-10-16T21:39:26.1250867Z 
2022-10-16T21:39:26.1250969Z The failure occurred for item [0]
```

### Versions

n/a

cc @ngimel @jansel @lezcano @fdrocha @mlazos @soumith @voznesenskym @yanboliang

**Comment by ZainRizvi** [comment]
As per @voznesenskym:

> its probably just a flaky test, we just migrated 100k lines of code from pytorch/torchdynamo to pytorch/pytorch
>
> lets put up a PR to relax the comparison on those tests

**Comment by ngimel** [comment]
cc @SherlockNoMad probably tolerance needs to be adjusted

**Comment by eellison** [comment]
Think we can close this, i cant repro..
