### ISSUE TITLE
[JIT] Python value resolution broken for calling functions from script modules

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8715]
```
+    @unittest.skip('TODO: Python value resolution broken')
+    def test_call_tracing_fn_from_script_module(self):
+        @torch.jit.trace(torch.rand(3, 3))
+        def traced_fn(x):
+            return torch.neg(x)
+
+        class ScriptMod(torch.jit.ScriptModule):
+            def __init__(self):
+                super(ScriptMod, self).__init__()
+                self.param = torch.nn.Parameter(torch.rand(4, 3))
+
+            @torch.jit.script_method
+            def forward(self, x):
+                return traced_fn(torch.mm(x, self.param))
+
+        sm = ScriptMod()
+        # FIXME: at the time of writing we fail with the following:
+        # RuntimeError:
+        # undefined value traced_fn:
+        # @torch.jit.script_method
+        # def forward(self, x):
+        #     return traced_fn(torch.mm(x, self.param))
+        #            ~~~~~~~~~ <--- HERE
+        self.assertExpected(str(sm.__getattr__('forward').graph))
+    @unittest.skip('TODO: Python value resolution broken')
+    def test_call_script_fn_from_script_module(self):
+        @torch.jit.script
+        def script_fn(x):
+            return torch.neg(x)
+
+        class ScriptMod(torch.jit.ScriptModule):
+            def __init__(self):
+                super(ScriptMod, self).__init__()
+                self.param = torch.nn.Parameter(torch.rand(4, 3))
+
+            @torch.jit.script_method
+            def forward(self, x):
+                return script_fn(torch.mm(x, self.param))
+
+        sm = ScriptMod()
+        # FIXME: at the time of writing, this failes with
+        # RuntimeError:
+        # undefined value traced_fn:
+        # @torch.jit.script_method
+        # def forward(self, x):
+        #     return traced_fn(torch.mm(x, self.param))
+        #            ~~~~~~~~~ <--- HERE
+        self.assertExpected(str(sm.__getattr__('forward').graph))
```

**Comment by jamesr66a** [comment]
Note, this only seems to break when we're not at global scope. The following works:

```
import torch

@torch.jit.trace(torch.rand(3, 3))
def traced_fn(x):
    return torch.neg(x)

class ScriptMod(torch.jit.ScriptModule):
    def __init__(self):
        super(ScriptMod, self).__init__()
        self.param = torch.nn.Parameter(torch.rand(4, 3))

    @torch.jit.script_method
    def forward(self, x):
        return traced_fn(torch.mm(x, self.param))

sm = ScriptMod()


```

The following doesn't:
```
import torch

def test_fn():
    @torch.jit.trace(torch.rand(3, 3))
    def traced_fn(x):
        return torch.neg(x)

    class ScriptMod(torch.jit.ScriptModule):
        def __init__(self):
            super(ScriptMod, self).__init__()
            self.param = torch.nn.Parameter(torch.rand(4, 3))

        @torch.jit.script_method
        def forward(self, x):
            return traced_fn(torch.mm(x, self.param))

    sm = ScriptMod()

test_fn()
```

```
14:39:04 ~ $ python resolve.py
Traceback (most recent call last):
  File "resolve.py", line 19, in <module>
    test_fn()
  File "resolve.py", line 17, in test_fn
    sm = ScriptMod()
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/jit/__init__.py", line 558, in init_then_register
    self._create_methods(asts, rcbs)
RuntimeError:
undefined value traced_fn:
@torch.jit.script_method
def forward(self, x):
    return traced_fn(torch.mm(x, self.param))
           ~~~~~~~~~ <--- HERE
```
