### ISSUE TITLE
Error using torch in pycharm

### ISSUE THREAD

**Issue by JoyceMind** [pytorch/pytorch#87192]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "D:\Code\TorchProject\main.py", line 7, in <module>
    import torch
  File "D:\Code\TorchProject\venv\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\Code\TorchProject\venv\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.

### Versions

Traceback (most recent call last):
  File "D:\Code\TorchProject\main.py", line 7, in <module>
    import torch
  File "D:\Code\TorchProject\venv\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\Code\TorchProject\venv\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.
![image](https://user-images.githubusercontent.com/108966996/196427450-958e9760-a7fc-4def-aebd-874e01fe93be.png)

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by Blackhex** [comment]
@luxx Can you please add an information from which source and which version of PyTorch you have installed? Can you add result of Dependency Walker analysis (https://www.dependencywalker.com/) on your D:\\Code\\TorchProject\\venv\\lib\\site-packages\\torch\\lib\\torch\_python.dll?

**Comment by bitjerry** [comment]
me too

**Comment by Blackhex** [comment]
@bitjerry If you are experiencing the same issue, can you please provide more detailed information about your PyTorch and system setup to help repreduce and investigate the issue?

**Comment by bitjerry** [comment]
I have solved this problem. You just need to install the appropriate cuda version.

**Comment by Blackhex** [comment]
@bitjerry Thank you for you response. Still, understanding what particular versions of PyTorch and CUDA caused the error could help us reproduce it and improve the error message to something more obvious.

**Comment by iremyux** [comment]
Hi, I'm closing this issue due to inactivity, and it appears that the issue has been resolved. If you encounter any similar issues or have further questions, please don't hesitate to open a new issue.
