### ISSUE TITLE
test_lstm_fusion_cpu is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#8746]
Sample failure:

```
13:30:33 ======================================================================
13:30:33 FAIL: test_lstm_fusion_cpu (__main__.TestJit)
13:30:33 ----------------------------------------------------------------------
13:30:33 Traceback (most recent call last):
13:30:33   File "test_jit.py", line 347, in test_lstm_fusion_cpu
13:30:33     self.assertExpectedGraph(ge.graph_for(*inputs))
13:30:33   File "test_jit.py", line 116, in assertExpectedGraph
13:30:33     self.assertExpected(str(graph), *args, **kwargs)
13:30:33   File "/var/lib/jenkins/workspace/test/common.py", line 487, in assertExpected
13:30:33     self.assertMultiLineEqual(expected, s)
13:30:33 AssertionError: 'grap[531 chars]oat(3!, 20), %14 : Float(3!, 20), %15 : Float([1233 chars]n}\n' != 'grap[531 chars]oat(3, 80) = aten::add[alpha={1}](%9, %12)\n  [536 chars]n}\n'
13:30:33   graph(%0 : Float(3, 10)
13:30:33         %1 : Float(3, 20)
13:30:33         %2 : Float(3, 20)
13:30:33         %3 : Float(80, 10)
13:30:33         %4 : Float(80, 20)
13:30:33         %5 : Float(80)
13:30:33         %6 : Float(80)) {
13:30:33     %7 : Float(10!, 80!) = aten::t(%3)
13:30:33     %8 : Float(3!, 80) = aten::expand[size=[3, 80], implicit=0](%5)
13:30:33     %9 : Float(3, 80) = aten::addmm[alpha={1}, beta={1}](%8, %0, %7)
13:30:33     %10 : Float(20!, 80!) = aten::t(%4)
13:30:33     %11 : Float(3!, 80) = aten::expand[size=[3, 80], implicit=0](%6)
13:30:33     %12 : Float(3, 80) = aten::addmm[alpha={1}, beta={1}](%11, %1, %10)
13:30:33 +   %13 : Float(3, 80) = aten::add[alpha={1}](%9, %12)
13:30:33 -   %13 : Float(3!, 20), %14 : Float(3!, 20), %15 : Float(3!, 20), %16 : Float(3!, 20) = aten::chunk[chunks=4, dim=1](%9)
13:30:33 ?     ^                    ^                    ^                    ^                                                 ^
13:30:33 +   %14 : Float(3!, 20), %15 : Float(3!, 20), %16 : Float(3!, 20), %17 : Float(3!, 20) = aten::chunk[chunks=4, dim=1](%13)
13:30:33 ?     ^                    ^                    ^                    ^                                                 ^^
13:30:33 -   %17 : Float(3!, 20), %18 : Float(3!, 20), %19 : Float(3!, 20), %20 : Float(3!, 20) = aten::chunk[chunks=4, dim=1](%12)
13:30:33 -   %21 : Float(3, 20), %22 : Float(3, 20) = prim::FusionGroup_0[device=-1](%2, %16, %20, %15, %19, %14, %18, %13, %17)
13:30:33 +   %18 : Float(3, 20) = aten::sigmoid(%14)
13:30:33 +   %19 : Float(3, 20) = aten::sigmoid(%15)
13:30:33 +   %20 : Float(3, 20) = aten::tanh(%16)
13:30:33 +   %21 : Float(3, 20) = aten::sigmoid(%17)
13:30:33 +   %22 : Float(3, 20) = aten::mul(%19, %2)
13:30:33 +   %23 : Float(3, 20) = aten::mul(%18, %20)
13:30:33 +   %24 : Float(3, 20) = aten::add[alpha={1}](%22, %23)
13:30:33 +   %25 : Float(3, 20) = aten::tanh(%24)
13:30:33 +   %26 : Float(3, 20) = aten::mul(%21, %25)
13:30:33 -   return (%21, %22);
13:30:33 ?             ^    ^
13:30:33 +   return (%26, %24);
13:30:33 ?             ^    ^
13:30:33   }
13:30:33 - with prim::FusionGroup_0 = graph(%12 : Float(3, 20)
13:30:33 -       %22 : Float(3!, 20)
13:30:33 -       %23 : Float(3!, 20)
13:30:33 -       %25 : Float(3!, 20)
13:30:33 -       %26 : Float(3!, 20)
13:30:33 -       %28 : Float(3!, 20)
13:30:33 -       %29 : Float(3!, 20)
13:30:33 -       %31 : Float(3!, 20)
13:30:33 -       %32 : Float(3!, 20)) {
13:30:33 -   %33 : Float(3, 20) = aten::add[alpha={1}](%31, %32)
13:30:33 -   %30 : Float(3, 20) = aten::add[alpha={1}](%28, %29)
13:30:33 -   %27 : Float(3, 20) = aten::add[alpha={1}](%25, %26)
13:30:33 -   %24 : Float(3, 20) = aten::add[alpha={1}](%22, %23)
13:30:33 -   %21 : Float(3, 20) = aten::sigmoid(%33)
13:30:33 -   %19 : Float(3, 20) = aten::sigmoid(%30)
13:30:33 -   %17 : Float(3, 20) = aten::tanh(%27)
13:30:33 -   %15 : Float(3, 20) = aten::sigmoid(%24)
13:30:33 -   %13 : Float(3, 20) = aten::mul(%19, %12)
13:30:33 -   %10 : Float(3, 20) = aten::mul(%21, %17)
13:30:33 -   %7 : Float(3, 20) = aten::add[alpha={1}](%13, %10)
13:30:33 -   %4 : Float(3, 20) = aten::tanh(%7)
13:30:33 -   %2 : Float(3, 20) = aten::mul(%15, %4)
13:30:33 -   return (%2, %7);
13:30:33 - }
13:30:33 
13:30:33 
13:30:33 ----------------------------------------------------------------------
13:30:33 Ran 911 tests in 33.029s
13:30:33 
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py3.6-gcc7.2-test/8640//console

**Comment by ezyang** [comment]
Haven't seen this one in a while, assuming we fixed it.
