### ISSUE TITLE
[JIT] Weird ArgumentStash bug

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8755]
Example:
```
import torch

# This is how you define a traced function
# Pass in an example input to this decorator and then apply it to the function
@torch.jit.trace(torch.rand(()))
def traced_fn(x):
    return torch.abs(2*x)

# This is how you define a script function
# Apply this decorator directly to the function
@torch.jit.script
def script_fn(x):
    z = torch.ones([1], dtype=torch.int64)
    for i in range(x):
        z = z * (i + 1)
    return z

# This is a normal module that can be traced.
class TracedModule(torch.nn.Module):
    def forward(self, x):
        x = x.type(torch.float32)
        return torch.floor(torch.sqrt(x) / 5.)

# This is how you define a scripted module.
# The module should inherit from ScriptModule and the forward should have the
# script_method decorator applied to it.
class ScriptModule(torch.jit.ScriptModule):
    @torch.jit.script_method
    def forward(self, x):
        r = -x
        if torch.fmod(x, 2.0) == 0.0:
            r = x / 2.0
        return r

# This is a demonstration net that calls all of the different types of
# methods and functions
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # Modules must be attributes on the Module because if you want to trace
        # or script this Module, we must be able to inherit the submodules'
        # params.
        self.traced_module = torch.jit.trace(torch.rand(()))(TracedModule())
        self.script_module = ScriptModule()

        print('traced_fn graph', traced_fn.graph)
        print('script_fn graph', script_fn.graph)
        print('TracedModule graph', self.traced_module.__getattr__('forward').graph)
        print('ScriptModule graph', self.script_module.__getattr__('forward').graph)

    def forward(self, x):
        # Call a traced function
        x = traced_fn(x)

        # Call a script function
        import pdb; pdb.set_trace()
        x = script_fn(x)

        # Call a traced submodule
        x = self.traced_module(x)

        # Call a scripted submodule
        x = self.script_module(x)

        return x


# Instantiate this net and run it
n = Net()
# print(n(torch.tensor([5]))) # 190.

n_traced = torch.jit.trace(torch.tensor([5]))(n)
print(n_traced(torch.tensor([5])))
```

The trace of the base module fails with:

```
Traceback (most recent call last):
  File "frontend_demo.py", line 71, in <module>
    n_traced = torch.jit.trace(torch.tensor([5]))(n)
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/jit/__init__.py", line 305, in wrapper
    module._create_method_from_trace('forward', func, args)
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "frontend_demo.py", line 56, in forward
    x = script_fn(x)
RuntimeError: /Users/jamesreed/onnx-fairseq/pytorch/torch/csrc/jit/attributes.h:180: t_: Assertion `!v.defined() || !v.is_variable()` failed.
```

Stack trace:

```
  * frame #0: 0x00007fff70c3a1f6 libc++abi.dylib`__cxa_throw
    frame #1: 0x000000010875d4ce _C.cpython-36m-darwin.so`torch::barf(fmt="%s:%u: %s: Assertion `%s` failed.") at assertions.cpp:18
    frame #2: 0x0000000108839e70 _C.cpython-36m-darwin.so`torch::jit::Attributes<torch::jit::Node>::t_(this=0x000060f00000de78, name=(value = 1627389961), v=torch::jit::ScalarAttributeValue<at::Tensor, torch::jit::AttributeKind::t>::ConstructorType @ 0x00007ffeefbf6858) atattributes.h:180
    frame #3: 0x00000001098c4b86 _C.cpython-36m-darwin.so`torch::autograd::setattr(n=0x000060f00000de70, name=(value = 1627389961), v=0x00007ffeefbf6d20) at VariableType.cpp:44
    frame #4: 0x0000000109967cbe _C.cpython-36m-darwin.so`torch::autograd::VariableType::s_th_add(this=0x000060600000abe0, self=0x00007ffeefbf6d70, other=0x00007ffeefbf6d58, alpha=Scalar @ 0x00007ffeefbf6d20) const at VariableType.cpp:7116
    frame #5: 0x000000010c2fc3e9 libcaffe2.dylib`at::Type::th_add(this=0x000060600000abe0, self=0x000060300004c810, other=0x000060300004c818, alpha=Scalar @ 0x00007ffeefbf6f48) const at Type.cpp:1275
    frame #6: 0x000000010bfed2cf libcaffe2.dylib`at::th_add(self=0x000060300004c810, other=0x000060300004c818, alpha=Scalar @ 0x00007ffeefbf7020) at Functions.h:1694
    frame #7: 0x000000010bfecfec libcaffe2.dylib`at::native::add(self=0x000060300004c810, other=0x000060300004c818, alpha=Scalar @ 0x00007ffeefbf7268) at LegacyBridge.cpp:161
    frame #8: 0x000000010c343c5d libcaffe2.dylib`at::Type::add(this=0x000060600000abe0, self=0x000060300004c810, other=0x000060300004c818, alpha=Scalar @ 0x00007ffeefbf72f0) const at Type.cpp:4679
    frame #9: 0x0000000109b922e3 _C.cpython-36m-darwin.so`torch::autograd::VariableType::add(this=0x000060600000abe0, self=0x000060300004c810, other=0x000060300004c818, alpha=Scalar @ 0x00007ffeefbf7398) const at VariableType.cpp:29021
    frame #10: 0x0000000108d75b5e _C.cpython-36m-darwin.so`at::add(self=0x000060300004c810, other=0x000060300004c818, alpha=Scalar @ 0x00007ffeefbf7400) at Functions.h:4305
    frame #11: 0x0000000108d78186 _C.cpython-36m-darwin.so`torch::jit::(anonymous namespace)::$_177::operator(this=0x000061f0000b0248, stack=size=1)(torch::jit::Node*) const::'lambda'(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&)::operator()(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&) const at aten_dispatch.cpp:2433
    frame #12: 0x0000000108d7806d _C.cpython-36m-darwin.so`int std::__1::__invoke_void_return_wrapper<int>::__call<torch::jit::(anonymous namespace)::$_177::operator()(torch::jit::Node*) const::'lambda'(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&)&, std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&>(torch::jit::(anonymous namespace)::$_177::operator()(torch::jit::Node*) const::'lambda'(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&)&&&, std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&&&) [inlined] decltype(__f=0x000061f0000b0248, __args=size=1)::$_177::operator()(torch::jit::Node*) const::'lambda'(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&)&>(fp)(std::__1::forward<std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&>(fp0))) std::__1::__invoke<torch::jit::(anonymous namespace)::$_177::operator()(torch::jit::Node*) const::'lambda'(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&)&, std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&>(torch::jit::(anonymous namespace)::$_177::operator()(torch::jit::Node*) const::'lambda'(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&)&&&, std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&&&) at type_traits:4323
    frame #13: 0x0000000108d78050 _C.cpython-36m-darwin.so`int std::__1::__invoke_void_return_wrapper<int>::__call<torch::jit::(anonymous namespace)::$_177::operator(__args=0x000061f0000b0248, __args=size=1)(torch::jit::Node*) const::'lambda'(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&)&, std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&>(torch::jit::(anonymous namespace)::$_177::operator()(torch::jit::Node*) const::'lambda'(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&)&&&, std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&&&) at __functional_base:318
    frame #14: 0x0000000108d77f64 _C.cpython-36m-darwin.so`std::__1::__function::__func<torch::jit::(anonymous namespace)::$_177::operator()(torch::jit::Node*) const::'lambda'(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&), std::__1::allocator<torch::jit::(anonymous namespace)::$_177::operator()(torch::jit::Node*) const::'lambda'(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor>>&)>, int (std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&)>::operator(this=0x000061f0000b0240, __arg=size=1)(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&) at functional:1562
    frame #15: 0x00000001088815fe _C.cpython-36m-darwin.so`std::__1::function<int (std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&)>::operator(this=0x000061f0000b0240, __arg=size=1)(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&) const at functional:1921
    frame #16: 0x000000010883289b _C.cpython-36m-darwin.so`torch::jit::InterpreterStateImpl::runOneStage(this=0x0000608000034020, stack=size=1) at interpreter.cpp:877
    frame #17: 0x0000000108832758 _C.cpython-36m-darwin.so`torch::jit::InterpreterState::runOneStage(this=0x00007ffeefbf7778, stack=size=1) at interpreter.cpp:958
    frame #18: 0x00000001088fea85 _C.cpython-36m-darwin.so`torch::jit::GraphExecutorImpl::runFallback(this=0x000060f0000072a0, inputs=variable_tensor_list @ 0x00007ffeefbf78e0) at graph_executor.cpp:311
    frame #19: 0x00000001088fe0dd _C.cpython-36m-darwin.so`torch::jit::GraphExecutorImpl::runTraced(this=0x000060f0000072a0, inputs=variable_tensor_list @ 0x00007ffeefbf7de0) at graph_executor.cpp:280
    frame #20: 0x00000001088fadce _C.cpython-36m-darwin.so`torch::jit::GraphExecutorImpl::run(this=0x000060f0000072a0, inputs=variable_tensor_list @ 0x00007ffeefbf8148) at graph_executor.cpp:213
    frame #21: 0x00000001088fa59e _C.cpython-36m-darwin.so`torch::jit::GraphExecutor::run(this=0x0000602000009750, inputs=0x00007ffeefbf8238) at graph_executor.cpp:540
    frame #22: 0x000000010882dfe4 _C.cpython-36m-darwin.so`torch::jit::initJITBindings(this=0x000060c00000d338, ge=0x0000602000009750, args=<unavailable>)::$_20::operator()(torch::jit::GraphExecutor&, pybind11::args) const at init.cpp:164
    frame #23: 0x000000010882df13 _C.cpython-36m-darwin.so`pybind11::object pybind11::detail::argument_loader<torch::jit::GraphExecutor&, pybind11::args>::call_impl<pybind11::object, torch::jit::initJITBindings(this=0x00007ffeefbf8440, f=0x000060c00000d338, (null)=index_sequence<0, 1> @ 0x00007ffeefbf8340, (null)=0x00007ffeefbf83a0)::$_20&, 0ul, 1ul, pybind11::detail::void_type>(torch::jit::initJITBindings(_object*)::$_20&&&, pybind11::detail::index_sequence<0ul, 1ul>, pybind11::detail::void_type&&) at cast.h:1866
    frame #24: 0x000000010882de38 _C.cpython-36m-darwin.so`std::__1::enable_if<!(std::is_void<pybind11::object>::value), pybind11::object>::type pybind11::detail::argument_loader<torch::jit::GraphExecutor&, pybind11::args>::call<pybind11::object, pybind11::detail::void_type, torch::jit::initJITBindings(this=0x00007ffeefbf8440, f=0x000060c00000d338)::$_20&>(torch::jit::initJITBindings(_object*)::$_20&&&) at cast.h:1843
    frame #25: 0x000000010882dd41 _C.cpython-36m-darwin.so`void pybind11::cpp_function::initialize<torch::jit::initJITBindings(_object*)::$_20, pybind11::object, torch::jit::GraphExecutor&, pybind11::args, pybind11::name, pybind11::is_method, pybind11::sibling>(this=0x000000010882dc30, call=0x00007ffeefbf8da8)::$_20&&, pybind11::object (*)(torch::jit::GraphExecutor&, pybind11::args), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const at pybind11.h:155
    frame #26: 0x000000010882dc48 _C.cpython-36m-darwin.so`void pybind11::cpp_function::initialize<torch::jit::initJITBindings(_object*)::$_20, pybind11::object, torch::jit::GraphExecutor&, pybind11::args, pybind11::name, pybind11::is_method, pybind11::sibling>(call=0x00007ffeefbf8da8)::$_20&&, pybind11::object (*)(torch::jit::GraphExecutor&, pybind11::args), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) at pybind11.h:132
    frame #27: 0x00000001085f1697 _C.cpython-36m-darwin.so`pybind11::cpp_function::dispatcher(self=0x000000010dea4990, args_in=0x000000010f328108, kwargs_in=0x0000000000000000) at pybind11.h:619
```

**Comment by jramseyer** [comment]
I can take a look!  

Is the desired behavior just: don't throw the error?  Are we expecting it to be either of defined or a variable?

**Comment by apaszke** [comment]
I think I accidentally hit this error during some other changes and found a solution, so it's possible this is already resolved.

**Comment by apaszke** [comment]
Yep, looks like #9414 fixes it.
