### ISSUE TITLE
[JIT] IntList arguments for call are not valid

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#8769]
After PR #8687, we are unable to define something like this:

```
def test(input):
    a = torch.zeros((input.size(0), 50), dtype=torch.double)
```
The problem is that we are now treating the IntList as a listOfInt, but input.size(0) returns a Dynamic, so it will throw up errors like:

```
Traceback (most recent call last):
  File "test/test_jit.py", line 4407, in test_time_sequence_prediction
    self.checkTrace(Sequence(), (torch.rand(97, 999),), verbose=True)
  File "/Users/wanchaol/pytorch/torch/jit/__init__.py", line 558, in init_then_register
    self._create_methods(asts, rcbs)
RuntimeError:
arguments for call are not valid:

  for operator zeros(IntList size, int64_t dtype=<default>, IntList device=<default>, int64_t layout=<default>):
  expected a value of type Tensor for argument 'size' but found (Tensor, int)

```

Currently we seems not doing the TensorToNum if we are into this case. @zou3519 do you have any suggestions on how this could be fix?

**Comment by zou3519** [comment]
I think the problem might be that `input.size(0)` is giving a DynamicType instead of an IntType.

**Comment by wanchaol** [comment]
Hi @zou3519, yes I agree that's what actually happening, I think there're two possible solutions:

1. input.size(0) should actually returns a int type instead of a tensor. 
2. we add an implicit conversion from a List of Tuple/Int mix to a Tensor

I think option 1 probably make more sense. Do you have any suggestions?

**Comment by zou3519** [comment]
I'd recommend (1) so that it can match python semantics more than it does right now.

**Comment by wanchaol** [comment]
@apaszke does that means we should probably stay align with the tracer and keep it as Tensor?
