### ISSUE TITLE
CUDA error: operation not permitted when stream is capturing (2 GPUs)

### ISSUE THREAD

**Issue by shekhovt** [pytorch/pytorch#87794]
### 🐛 Describe the bug

The error occurs when capturing a CUDA graph with a small network on a machine with more than 1 GPU.
The MWE indicates that some temporary requests or allocations are silently made on a different (default) device than where the network and the data reside and may not necessarily be an issue with capturing itself.

The minimal setup to reproduce is as follows. At least 2 GPUs, The MWE is:
```
import torch.nn as nn
import torch
import torch.optim as optim
import torch.nn.functional as F

dev = torch.device('cuda:1') # we intend to create data network and capture the graph on this GPU only

D = 32
input_shape = torch.Size([4, D]) 
s = torch.cuda.Stream(device=dev)
s.wait_stream(torch.cuda.current_stream())
x = torch.rand(input_shape, dtype=torch.float32, device=dev)
L = nn.Linear(D,D, bias=None).to(dev)
x.requires_grad = True

def loss(x):
    x = F.linear(x, L.weight)
    x = F.softplus(x)
    x = F.linear(x, L.weight)
    return x.sum()

with torch.cuda.device(0): # this clause should not have effect, the issue occurs with or without it
    print("Warmup 3 batches")
    with torch.cuda.stream(s): # warmup on a side stream, why?
        for i in range(3):
            l = loss(x)
            l.backward()
    torch.cuda.current_stream().wait_stream(s)
    
    print("Capturing")       
    g = torch.cuda.CUDAGraph()
    with torch.cuda.graph(g):
        l = loss(x)
        l.backward()
    print("Replay 3 batches")
    for i in range(3):
        g.replay()
        
    print(f'Test passed')

```

Output:
```
Warmup 3 batches
Capturing
Traceback (most recent call last):
  File "/home.nfs/shekhole/work/quant/demo/MWE.py", line 35, in <module>
    l.backward()
  File "/mnt/appl/software/PyTorch/1.11.0-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/mnt/appl/software/PyTorch/1.11.0-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: operation not permitted when stream is capturing
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
...
```

The workaround is therefore rather simple: to use CUDA_VISIBLE_DEVICES if we do not need more than 1 GPU or to enclose all the execution into `with torch.cuda.device(dev)'. But it appears to be a bug nevertheless. 

### Versions

At this moment I was able to test only on two servers with older GPUs, where the maximal version of pytorch supporting these GPUs is 1.11. I will try to find a way to run it in a newer setup. 

```
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (GCC) 10.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.9.5 (default, Nov 29 2021, 15:17:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.19.0-21-amd64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to:
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 1080 Ti
GPU 3: NVIDIA GeForce GTX 1080 Ti
GPU 4: NVIDIA GeForce GTX 1080 Ti
GPU 5: NVIDIA GeForce GTX 1080 Ti
GPU 6: NVIDIA GeForce GTX 1080 Ti
GPU 7: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect
```
```
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (GCC) 10.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.9.5 (default, Nov 29 2021, 15:17:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.19.0-18-amd64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to:
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1080
GPU 1: NVIDIA GeForce GTX 1080

Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect
```

**Comment by Aidyn-A** [comment]
Well if you are intend to create data network and capture the graph on `torch.device('cuda:1')` then you should call everything on this device:
```python
import torch.nn as nn
import torch
import torch.optim as optim
import torch.nn.functional as F

dev = torch.device('cuda:1') # we intend to create data network and capture the graph on this GPU only

D = 32
input_shape = torch.Size([4, D], device=dev) 
s = torch.cuda.Stream(device=dev)
s.wait_stream(torch.cuda.current_stream())
x = torch.rand(input_shape, dtype=torch.float32, device=dev, requires_grad=True)
L = nn.Linear(D,D, bias=None).to(dev)

def loss(x):
    x = F.linear(x, L.weight)
    x = F.softplus(x)
    x = F.linear(x, L.weight)
    return x.sum()

with torch.cuda.device(dev): # make sure you use the correct device
    print("Warmup 3 batches")
    with torch.cuda.stream(s):
        for i in range(3):
            l = loss(x)
            l.backward()
    torch.cuda.current_stream().wait_stream(s)
    
    print("Capturing")       
    g = torch.cuda.CUDAGraph()
    with torch.cuda.graph(g):
        l = loss(x)
        l.backward()
    print("Replay 3 batches")
    for i in range(3):
        g.replay()
        
    print(f'Test passed')
```

**Comment by shekhovt** [comment]
Thanks for looking at it. Let me clarify. The error occurs even without the line 
with torch.cuda.device(0): 
I believe the effect is the same, because the default device is 0, just more obscure.
The question is, what operations are attempted on the default device 0 despite the network and the data reside on device 1? It may have undesired side effects in a code without graph capture. Or it could be some issue with graph capture.

**Comment by Aidyn-A** [comment]
> The error occurs even without the line
with torch.cuda.device(0):

Yes, because current device would be 0, you may check it calling `torch.cuda.current_device()`. Within `with torch.cuda.device(dev)` context manager the current device is set to `dev` (which is 1). Alternatively, you may use `torch.cuda.set_device(dev)`.

If all tensors are on device 1, while the current device 0 you may perform operations like `loss(x)` and `l.backward()` (please see [CUDA semantics](https://pytorch.org/docs/stable/notes/cuda.html?highlight=cuda%20semantics)). However, the graph capture will fail because it depends on `current_device`:
https://github.com/pytorch/pytorch/blob/a485528a7e4551461d57db3deb8b40c2acea08d2/aten/src/ATen/cuda/CUDAGraph.cpp#L83
and uses this device to allocate cache using `CUDACachingAllocator`. Obviously it would be wrong to manipulate tensors on device 1 while cache is stored in device 0. Unfortunately, I just noticed that the current master fails silently for this case:
```python
import torch.nn as nn
import torch
import torch.optim as optim
import torch.nn.functional as F

dev = torch.device('cuda:1') # we intend to create data network and capture the graph on this GPU only

D = 32
input_shape = torch.Size([4, D], device=dev)
s = torch.cuda.Stream(device=dev)
s.wait_stream(torch.cuda.current_stream())
x = torch.rand(input_shape, dtype=torch.float32, device=dev)
L = nn.Linear(D,D, bias=None).to(dev)

def loss(x):
    x = F.linear(x, L.weight)
    x = F.softplus(x)
    x = F.linear(x, L.weight)
    return x.sum()

with torch.cuda.device(0): # Wring device
    print("Warmup 3 batches")
    with torch.cuda.stream(s):
        for i in range(3):
            l = loss(x)
    torch.cuda.current_stream().wait_stream(s)

    print("Capturing")
    g = torch.cuda.CUDAGraph()
    with torch.cuda.graph(g):
        l = loss(x)
    print("Replay 3 batches")
    for i in range(3):
        x.normal_()
        g.replay()
        print(l) # Should print different values each iteration, 
                 # but it does not because the current_device is 0 
                 # while all the tensors are on device 1

    print(f'Test passed')
```

It thanks to the autograd your code snippet errored out.

**Comment by shekhovt** [comment]
Thanks for the explanation! Now I start to understand what does it mean in the documentation that " graph() and make_graphed_callables() set a side stream for you". It sets a side stream using the default device. And now I noticed the important modification you made in that code snippet:
```
with torch.cuda.graph(g, stream=s): # specify the stream on device 1
```
which passes in the stream to capture matching to the device where we are computing. 

I understand the initial issue is not a bug but a wrong usage of the tool. Perhaps the documentation could be more expressive about this, and the example in [cuda-graph-semantics](https://pytorch.org/docs/stable/notes/cuda.html#cuda-graph-semantics) could use this solution without the silent creation of the non-default stream. It would make it more explicit and clear in my opinion. Also, the stack trace and the error message are very uninformative.

**Comment by Bustead** [comment]
Hi @shekhovt ! It looks like you're happy with the working solution provided by Aidyn. Do you want to keep this open?
