### ISSUE TITLE
RuntimeError: unable to mmap 29764 bytes from file </torch_10182_3020184674_63991>: Cannot allocate memory (12)

### ISSUE THREAD

**Issue by zhouzinimg** [pytorch/pytorch#87861]
### 🐛 Describe the bug

    for _ in range(flags.num_buffers):
        for key in buffers:
            buffers[key].append(torch.zeros(**specs[key]).share_memory_())
    return buffers

Traceback (most recent call last):
  File "/home/cloudam/rl-baseline (copy)/monobeast.py", line 634, in <module>
  File "/home/cloudam/rl-baseline (copy)/monobeast.py", line 512, in train
  File "/home/cloudam/rl-baseline (copy)/monobeast.py", line 140, in create_buffers
  File "/home/cloudam/miniconda3/lib/python3.9/site-packages/torch/_tensor.py", line 619, in share_memory_
  File "/home/cloudam/miniconda3/lib/python3.9/site-packages/torch/storage.py", line 627, in share_memory_
  File "/home/cloudam/miniconda3/lib/python3.9/site-packages/torch/storage.py", line 208, in share_memory_
RuntimeError: unable to mmap 29764 bytes from file </torch_10182_3020184674_63991>: Cannot allocate memory (12)

### Versions

pytorch 10.0 cu116

**Comment by wshuai190** [comment]
Found same issue also in version 1.9.0
