### ISSUE TITLE
Placing LSTM model on bfloat16 on GPU causes error

### ISSUE THREAD

**Issue by apuny678** [pytorch/pytorch#88136]
### 🐛 Describe the bug

import torch.nn as nn
import torch as th

# If using CPU as the device, the following codes run perfectly
rnn = nn.LSTM(10, 20, 2).to(device="cpu", dtype=th.bfloat16)
input = th.randn(5, 3, 10).to(device="cpu", dtype=th.bfloat16)
h0 = th.randn(2, 3, 20).to(device="cpu", dtype=th.bfloat16)
c0 = th.randn(2, 3, 20).to(device="cpu", dtype=th.bfloat16)
output, (hn, cn) = rnn(input, (h0, c0))

# However, change the device to be GPU, it gives out an error
rnn = nn.LSTM(10, 20, 2).to(device="cuda", dtype=th.bfloat16)
input = th.randn(5, 3, 10).to(device="cuda", dtype=th.bfloat16)
h0 = th.randn(2, 3, 20).to(device="cuda", dtype=th.bfloat16)
c0 = th.randn(2, 3, 20).to(device="cuda", dtype=th.bfloat16)
output, (hn, cn) = rnn(input, (h0, c0))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_20268/1164814484.py in <module>
      3 h0 = th.randn(2, 3, 20).to(device="cuda", dtype=th.bfloat16)
      4 c0 = th.randn(2, 3, 20).to(device="cuda", dtype=th.bfloat16)
----> 5 output, (hn, cn) = rnn(input, (h0, c0))

~\anaconda3\envs\py37\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

~\anaconda3\envs\py37\lib\site-packages\torch\nn\modules\rnn.py in forward(self, input, hx)
    760         if batch_sizes is None:
    761             result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
--> 762                               self.dropout, self.training, self.bidirectional, self.batch_first)
    763         else:
    764             result = _VF.lstm(input, batch_sizes, hx, self._flat_weights, self.bias,

RuntimeError: "_thnn_fused_lstm_cell_cuda" not implemented for 'BFloat16'

# I've also tried datatype 'float16', it works for GPU but doesn't work for CPU.
rnn = nn.LSTM(10, 20, 2).to(device="cpu", dtype=th.float16)
input = th.randn(5, 3, 10).to(device="cpu", dtype=th.float16)
h0 = th.randn(2, 3, 20).to(device="cpu", dtype=th.float16)
c0 = th.randn(2, 3, 20).to(device="cpu", dtype=th.float16)
output, (hn, cn) = rnn(input, (h0, c0))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8944/1937453628.py in <module>
      3 h0 = th.randn(2, 3, 20).to(device="cpu", dtype=th.float16)
      4 c0 = th.randn(2, 3, 20).to(device="cpu", dtype=th.float16)
----> 5 output, (hn, cn) = rnn(input, (h0, c0))

~\anaconda3\envs\py37\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

~\anaconda3\envs\py37\lib\site-packages\torch\nn\modules\rnn.py in forward(self, input, hx)
    760         if batch_sizes is None:
    761             result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
--> 762                               self.dropout, self.training, self.bidirectional, self.batch_first)
    763         else:
    764             result = _VF.lstm(input, batch_sizes, hx, self._flat_weights, self.bias,

RuntimeError: "sigmoid_cpu" not implemented for 'Half'

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1650 Ti
Nvidia driver version: 516.59
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpy-ext==0.9.6
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py37h2bbff1b_0
[conda] mkl_fft                   1.3.1            py37h277e83a_0
[conda] mkl_random                1.2.2            py37hf11a4ad_0
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.20.3           py37ha4e8547_0
[conda] numpy-base                1.20.3           py37hc2deb75_0
[conda] numpy-ext                 0.9.6                    pypi_0    pypi
[conda] pytorch                   1.11.0          py3.7_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.11.0               py37_cu113    pytorch
[conda] torchfile                 0.1.0                      py_0    conda-forge
[conda] torchvision               0.12.0               py37_cu113    pytorch

**Comment by DanTremonti** [comment]
Bump.
I'm facing the same issue with `torch=1.13.1+cu116`

Code piece that I used:
```
import torch
import torch.nn as nn


class Model(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.model = nn.LSTM(10, 1)
        for param in self.model.parameters():
            param.data = param.data.bfloat16()

    def forward(self, inp: torch.Tensor) -> torch.Tensor:
        pred = self.model(inp)
        return pred

# device=cpu
model = Model()
inp = torch.randn((1, 10)).to(torch.bfloat16)
res = model(inp)
print("cpu passes")

# device=cuda
model = Model().to(device="cuda")
inp = torch.randn((1, 10), device="cuda").to(torch.bfloat16)
res = model(inp)
print("cuda passes")
```
stdout:
```
cpu passes
Traceback (most recent call last):
  File "/home/tmp.py", line 27, in <module>
    res = model(inp)
  File "/home/anaconda3/envs/z1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tmp.py", line 15, in forward
    pred = self.model(inp)
  File "/home/anaconda3/envs/z1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/z1/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 774, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: "_thnn_fused_lstm_cell_cuda" not implemented for 'BFloat16'
```

**Comment by ngimel** [comment]
cc @eqy. Why is cudnn not used in this case? Should we enable cudnn for bfloat16, and enable fused lstm cell dispatch too, just in case?

**Comment by eqy** [comment]
I think this is the consequence of some vestigal dtype restrictions in `torch.backends.cudnn`. I'll see if adding a check for >=`sm80` to add `bfloat16` support works.

**Comment by swevrywhere** [comment]
@eqy Adding that check work? It would be great to get this fixed. Thanks!

**Comment by eqy** [comment]
@swevrywhere I'm seeing that this currently works in a recent upstream build on sm80
The fix was merged here: https://github.com/pytorch/pytorch/commit/95041829c8a76755d22df9bd711f25781e57e223 and should be working in nightlies

**Comment by kssmmm** [comment]
@eqy Does this mean that updating pytorch to the nightly version 2.3.0 can solve this problem？Now I'm facing the same issue with torch=2.2.1+cu121

**Comment by apuny678** [comment]
I can confirm that this issue has been addressed in PyTorch nightly 2.3+cuda12.1

**Comment by NiftyliuS** [comment]
@apuny678 facing the same issue, will try to install nightly
on that topic do you know if they addressed optim.Adam with fp16?

**Comment by apuny678** [comment]
My model incorporates optim.Adam and it works well with float16 so far.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NiftyliuS** [comment]
updating to nightly got me this gem
```
import flash_attn_2_cuda as flash_attn_cuda
ImportError: DLL load failed while importing flash_attn_2_cuda: The specified procedure could not be found.
```


I am doing experiments with tinly Llama - i am trying to repurpose it to bert so i cant use Trainer() sadly. when i use

```
outputs = model.train()
loss=loss_fn(outputs, target)
loss.backward()
optimizer.step()
```

the first iteration i get value the 2nd i get inf and nan

but it works with bf16 just fine so im kinda buffled

**Comment by DanTremonti** [comment]
> Bump. I'm facing the same issue with `torch=1.13.1+cu116`
> 
> Code piece that I used:
> 
> ```
> import torch
> import torch.nn as nn
> 
> 
> class Model(nn.Module):
>     def __init__(self) -> None:
>         super().__init__()
>         self.model = nn.LSTM(10, 1)
>         for param in self.model.parameters():
>             param.data = param.data.bfloat16()
> 
>     def forward(self, inp: torch.Tensor) -> torch.Tensor:
>         pred = self.model(inp)
>         return pred
> 
> # device=cpu
> model = Model()
> inp = torch.randn((1, 10)).to(torch.bfloat16)
> res = model(inp)
> print("cpu passes")
> 
> # device=cuda
> model = Model().to(device="cuda")
> inp = torch.randn((1, 10), device="cuda").to(torch.bfloat16)
> res = model(inp)
> print("cuda passes")
> ```
> 
> stdout:
> 
> ```
> cpu passes
> Traceback (most recent call last):
>   File "/home/tmp.py", line 27, in <module>
>     res = model(inp)
>   File "/home/anaconda3/envs/z1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/tmp.py", line 15, in forward
>     pred = self.model(inp)
>   File "/home/anaconda3/envs/z1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/anaconda3/envs/z1/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 774, in forward
>     result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
> RuntimeError: "_thnn_fused_lstm_cell_cuda" not implemented for 'BFloat16'
> ```

Update on this issue. I ran the same snippet shared above, only to face an error while passing a CPU tensor. No issues with GPU tensor. 

<details>
  <summary>CPU</summary>
  
  ### torch 2.0.0+cu117
  ```shell
  Traceback (most recent call last):
    File "/home/bfloat_lstm.py", line 19, in <module>
      res = model(inp)
    File "/home/miniconda3/envs/z1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
      return forward_call(*args, **kwargs)
    File "/home/bfloat_lstm.py", line 13, in forward
      pred = self.model(inp)
    File "/home/miniconda3/envs/z1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
      return forward_call(*args, **kwargs)
    File "/home/miniconda3/envs/z1/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 812, in forward
      result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
  RuntimeError: could not create a primitive descriptor
  ```

  ### torch 2.3.0+cu118
  ```shell
  Traceback (most recent call last):
    File "/home/bfloat_lstm.py", line 19, in <module>
      res = model(inp)
    File "/home/miniconda3/envs/torch-2.3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/home/miniconda3/envs/torch-2.3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
    File "/home/bfloat_lstm.py", line 13, in forward
      pred = self.model(inp)
    File "/home/miniconda3/envs/torch-2.3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/home/miniconda3/envs/torch-2.3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      return forward_call(*args, **kwargs)
    File "/home/miniconda3/envs/torch-2.3/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 911, in forward
      result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
  RuntimeError: could not create a primitive descriptor for an LSTM forward propagation primitive
  ```
</details>

<details>
  <summary>GPU</summary>
  
  ### torch 2.0.0+cu117
  ```shell
  Traceback (most recent call last):
    File "/home/bfloat_lstm.py", line 25, in <module>
      res = model(inp)
    File "/home/miniconda3/envs/z1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
      return forward_call(*args, **kwargs)
    File "/home/bfloat_lstm.py", line 13, in forward
      pred = self.model(inp)
    File "/home/miniconda3/envs/z1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
      return forward_call(*args, **kwargs)
    File "/home/miniconda3/envs/z1/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 812, in forward
      result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
  RuntimeError: "_thnn_fused_lstm_cell_cuda" not implemented for 'BFloat16'
  ```

  ### torch 2.3.0+cu118
  ```shell
  cuda passes
  ```
</details>

**Comment by DanTremonti** [comment]
[The above thread](https://github.com/pytorch/pytorch/issues/88136#issuecomment-2076504270) describes the error while running the code in a machine where the CPU is non-compatible with *bfloat16* dtype.
With a compatible hardware, I'm able to run (both CPU and GPU) without any errors. Sorry about the confusion.
