### ISSUE TITLE
Dynamo C++ compile error

### ISSUE THREAD

**Issue by blzheng** [pytorch/pytorch#88201]
### Reproduce:
```
python benchmarks/dynamo/timm_models.py --performance --float32 -dcpu --inductor-settings --float32 -n50 --inductor --no-skip --quiet -k "botnet26t_256"
python benchmarks/dynamo/timm_models.py --performance --float32 -dcpu --inductor-settings --float32 -n50 --inductor --no-skip --quiet -k "eca_botnext26ts_256"
python benchmarks/dynamo/timm_models.py --performance --float32 -dcpu --inductor-settings --float32 -n50 --inductor --no-skip --quiet -k "eca_halonext26ts"
python benchmarks/dynamo/timm_models.py --performance --float32 -dcpu --inductor-settings --float32 -n50 --inductor --no-skip --quiet -k "sebotnet33ts_256"
```

### Error:
```
cpu  eval  sebotnet33ts_256                   ERROR:common:Failed for dynamo C++ compile error

Command:
/tmp/torchinductor_bzheng/gcc/bin/g++ -shared -fPIC -Wall -std=c++14 -Wno-unused-variable -I/home/bzheng/workspace/pytorch/torch/include -I/home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include -I/home/bzheng/workspace/pytorch/torch/include/TH -I/home/bzheng/workspace/pytorch/torch/include/THC -I/home/bzheng/anaconda3/envs/torchdynamo2/include/python3.8 -lgomp -march=native -O3 -ffast-math -fno-finite-math-only -fopenmp -o/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.so /tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp

Output:
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp: In function 'void kernel(float*, const float*, const float*, const float*, float*, float*, float*)':
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:66:49: error: no matching function for call to 'max(float&, double&)'
   66 |                                 tmp22 = std::max(tmp22, tmp21);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~
In file included from /tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/algorithm:60,
                 from /tmp/torchinductor_bzheng/os/cosa6ygqfwn3e7all36epaxgvxcu2r2idsylr7657mlkau6gex5d.h:1,
                 from /tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:2:
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algobase.h:254:5: note: candidate: 'template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)'
  254 |     max(const _Tp& __a, const _Tp& __b)
      |     ^~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algobase.h:254:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:66:49: note:   deduced conflicting types for parameter 'const _Tp' ('float' and 'double')
   66 |                                 tmp22 = std::max(tmp22, tmp21);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algobase.h:300:5: note: candidate: 'template<class _Tp, class _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)'
  300 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algobase.h:300:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:66:49: note:   deduced conflicting types for parameter 'const _Tp' ('float' and 'double')
   66 |                                 tmp22 = std::max(tmp22, tmp21);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~
In file included from /tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/algorithm:61:
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algo.h:5746:5: note: candidate: 'template<class _Tp> constexpr _Tp std::max(initializer_list<_Tp>)'
 5746 |     max(initializer_list<_Tp> __l)
      |     ^~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algo.h:5746:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:66:49: note:   mismatched types 'std::initializer_list<_Tp>' and 'float'
   66 |                                 tmp22 = std::max(tmp22, tmp21);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algo.h:5756:5: note: candidate: 'template<class _Tp, class _Compare> constexpr _Tp std::max(initializer_list<_Tp>, _Compare)'
 5756 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algo.h:5756:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:66:49: note:   mismatched types 'std::initializer_list<_Tp>' and 'float'
   66 |                                 tmp22 = std::max(tmp22, tmp21);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/home/bzheng/workspace/pytorch/torch/_inductor/codecache.py", line 196, in load
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/home/bzheng/anaconda3/envs/torchdynamo2/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/bzheng/anaconda3/envs/torchdynamo2/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/torchinductor_bzheng/gcc/bin/g++', '-shared', '-fPIC', '-Wall', '-std=c++14', '-Wno-unused-variable', '-I/home/bzheng/workspace/pytorch/torch/include', '-I/home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include', '-I/home/bzheng/workspace/pytorch/torch/include/TH', '-I/home/bzheng/workspace/pytorch/torch/include/THC', '-I/home/bzheng/anaconda3/envs/torchdynamo2/include/python3.8', '-lgomp', '-march=native', '-O3', '-ffast-math', '-fno-finite-math-only', '-fopenmp', '-o/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.so', '/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bzheng/workspace/pytorch/benchmarks/dynamo/common.py", line 1131, in warmup
    fn(model, example_inputs)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/timm_models.py", line 301, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/eval_frame.py", line 157, in _fn
    return fn(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/functorch/_src/aot_autograd.py", line 870, in forward
    return compiled_f(
  File "/home/bzheng/workspace/pytorch/functorch/_src/aot_autograd.py", line 856, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/home/bzheng/workspace/pytorch/functorch/_src/aot_autograd.py", line 579, in create_aot_dispatcher_function
    return aot_dispatch_base(flat_fn, fake_flat_tensor_args, aot_config)
  File "/home/bzheng/workspace/pytorch/functorch/_src/aot_autograd.py", line 295, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/utils.py", line 92, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/compile_fx.py", line 351, in fw_compiler
    return compile_fx_inner(
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/debug_utils.py", line 444, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/debug.py", line 177, in inner
    return fn(*args, **kwargs)
  File "/home/bzheng/anaconda3/envs/torchdynamo2/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/compile_fx.py", line 122, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/bzheng/workspace/pytorch/torch/_inductor/graph.py", line 346, in compile_to_fn
    return self.compile_to_module().call
  File "/home/bzheng/workspace/pytorch/torch/_dynamo/utils.py", line 92, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/graph.py", line 336, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/codecache.py", line 219, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_bzheng/wd/cwdwbfgo5ygz5goq4bfyr5tc7fmhqgeqcgxs25gbkjoz65vohdyb.py", line 3996, in <module>
    async_compile.wait(globals())
  File "/home/bzheng/workspace/pytorch/torch/_inductor/codecache.py", line 389, in wait
    scope[key] = result.result()
  File "/home/bzheng/anaconda3/envs/torchdynamo2/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/bzheng/anaconda3/envs/torchdynamo2/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/bzheng/anaconda3/envs/torchdynamo2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bzheng/workspace/pytorch/torch/_inductor/codecache.py", line 381, in task
    return CppCodeCache.load(source_code).kernel
  File "/home/bzheng/workspace/pytorch/torch/_inductor/codecache.py", line 198, in load
    raise exc.CppCompileError(cmd, e.output)
torch._inductor.exc.CppCompileError: C++ compile error

Command:
/tmp/torchinductor_bzheng/gcc/bin/g++ -shared -fPIC -Wall -std=c++14 -Wno-unused-variable -I/home/bzheng/workspace/pytorch/torch/include -I/home/bzheng/workspace/pytorch/torch/include/torch/csrc/api/include -I/home/bzheng/workspace/pytorch/torch/include/TH -I/home/bzheng/workspace/pytorch/torch/include/THC -I/home/bzheng/anaconda3/envs/torchdynamo2/include/python3.8 -lgomp -march=native -O3 -ffast-math -fno-finite-math-only -fopenmp -o/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.so /tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp

Output:
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp: In function 'void kernel(float*, const float*, const float*, const float*, float*, float*, float*)':
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:66:49: error: no matching function for call to 'max(float&, double&)'
   66 |                                 tmp22 = std::max(tmp22, tmp21);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~
In file included from /tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/algorithm:60,
                 from /tmp/torchinductor_bzheng/os/cosa6ygqfwn3e7all36epaxgvxcu2r2idsylr7657mlkau6gex5d.h:1,
                 from /tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:2:
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algobase.h:254:5: note: candidate: 'template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)'
  254 |     max(const _Tp& __a, const _Tp& __b)
      |     ^~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algobase.h:254:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:66:49: note:   deduced conflicting types for parameter 'const _Tp' ('float' and 'double')
   66 |                                 tmp22 = std::max(tmp22, tmp21);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algobase.h:300:5: note: candidate: 'template<class _Tp, class _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)'
  300 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algobase.h:300:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:66:49: note:   deduced conflicting types for parameter 'const _Tp' ('float' and 'double')
   66 |                                 tmp22 = std::max(tmp22, tmp21);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~
In file included from /tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/algorithm:61:
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algo.h:5746:5: note: candidate: 'template<class _Tp> constexpr _Tp std::max(initializer_list<_Tp>)'
 5746 |     max(initializer_list<_Tp> __l)
      |     ^~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algo.h:5746:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:66:49: note:   mismatched types 'std::initializer_list<_Tp>' and 'float'
   66 |                                 tmp22 = std::max(tmp22, tmp21);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algo.h:5756:5: note: candidate: 'template<class _Tp, class _Compare> constexpr _Tp std::max(initializer_list<_Tp>, _Compare)'
 5756 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/tmp/torchinductor_bzheng/gcc/x86_64-conda-linux-gnu/include/c++/12.2.0/bits/stl_algo.h:5756:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp:66:49: note:   mismatched types 'std::initializer_list<_Tp>' and 'float'
   66 |                                 tmp22 = std::max(tmp22, tmp21);
      |                                         ~~~~~~~~^~~~~~~~~~~~~~

ERROR
cpu              gmean=nanx mean=nanx
sebotnet33ts_256 gmean=nanx mean=nanx
0                gmean=nanx mean=nanx
0.0000           gmean=nanx mean=nanx
```

### Versions

PyTorch master

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @Xia-Weiwen @wenzhe-nrv @jiayisunx

**Comment by jgong5** [comment]
`std::max` cannot work on inputs with different data types. @blzheng Is it ok to share the generated code (e.g., /tmp/torchinductor_bzheng/e3/ce3kcm7tc2yydx67gtk7rtdtdqhcml7iizyv2s4vcvhlp3eudnug.cpp) so that we can know why the mixed data type inputs happened?

**Comment by blzheng** [comment]
```

#include "/tmp/torchinductor_bzheng/os/cosa6ygqfwn3e7all36epaxgvxcu2r2idsylr7657mlkau6gex5d.h"
extern "C" void kernel(float* __restrict__ in_out_ptr0,
                       const float* __restrict__ in_ptr1,
                       const float* __restrict__ in_ptr2,
                       const float* __restrict__ in_ptr3,
                       float* __restrict__ out_ptr0,
                       float* __restrict__ out_ptr2,
                       float* __restrict__ out_ptr4)
{
    auto in_ptr0 = in_out_ptr0;
    auto out_ptr1 = in_out_ptr0;
    auto out_ptr3 = in_out_ptr0;
    #pragma omp parallel num_threads(80)
    {
        #pragma omp for 
        for(long i0=0; i0<256; ++i0)
        {
            #pragma GCC ivdep
            for(long i1=0; i1<1024; ++i1)
            {
                {
                    {
                        float tmp22 = -std::numeric_limits<float>::infinity();
                        for(long i2=0; i2<1024; ++i2)
                        {
                            {
                                auto tmp0 = in_ptr0[i2 + (1024*i1) + (1048576*i0)];
                                auto tmp1 = static_cast<float>(0.1767766952966369);
                                auto tmp2 = tmp0 * tmp1;
                                auto tmp3 = static_cast<long>(31 + (63*(i1 / 32)) + (i2 / 32));
                                auto tmp4 = static_cast<long>(2048);
                                auto tmp5 = tmp3 < tmp4;
                                auto tmp6 = 0.0;
                                if(tmp5)
                                {
                                    auto tmp7 = static_cast<long>((31 + (63*(i1 / 32)) + (i2 / 32)) % 64);
                                    auto tmp8 = static_cast<long>(63);
                                    auto tmp9 = tmp7 < tmp8;
                                    auto tmp10 = 0.0;
                                    if(tmp9)
                                    {
                                        auto tmp11 = in_ptr1[(63*(((31 + (63*(i1 / 32)) + (i2 / 32)) / 64))) + (2016*(i1 % 32)) + (64512*i0) + ((31 + (63*(i1 / 32)) + (i2 / 32)) % 64)];
                                        tmp10 = tmp11;
                                    }
                                    tmp6 = tmp10;
                                }
                                auto tmp12 = static_cast<long>(31 + (63*(i1 % 32)) + (i2 % 32));
                                auto tmp13 = tmp12 < tmp4;
                                auto tmp14 = 0.0;
                                if(tmp13)
                                {
                                    auto tmp15 = static_cast<long>((31 + (63*(i1 % 32)) + (i2 % 32)) % 64);
                                    auto tmp16 = static_cast<long>(63);
                                    auto tmp17 = tmp15 < tmp16;
                                    auto tmp18 = 0.0;
                                    if(tmp17)
                                    {
                                        auto tmp19 = in_ptr2[(63*(((31 + (63*(i1 % 32)) + (i2 % 32)) / 64) % 32)) + (2016*(i1 / 32)) + (64512*i0) + ((31 + (63*(i1 % 32)) + (i2 % 32)) % 64)];
                                        tmp18 = tmp19;
                                    }
                                    tmp14 = tmp18;
                                }
                                auto tmp20 = tmp6 + tmp14;
                                auto tmp21 = tmp2 + tmp20;
                                tmp22 = std::max(tmp22, tmp21);
                            }
                        }
                        out_ptr0[i1 + (1024*i0)] = tmp22;
                    }
                }
            }
        }
        #pragma omp for 
        for(long i0=0; i0<256; ++i0)
        {
            #pragma GCC ivdep
            for(long i1=0; i1<1024; ++i1)
            {
                #pragma GCC ivdep
                for(long i2=0; i2<1024; ++i2)
                {
                    {
                        {
                            auto tmp0 = in_ptr0[i2 + (1024*i1) + (1048576*i0)];
                            auto tmp22 = out_ptr0[i1 + (1024*i0)];
                            auto tmp1 = static_cast<float>(0.1767766952966369);
                            auto tmp2 = tmp0 * tmp1;
                            auto tmp3 = static_cast<long>(31 + (63*(i1 / 32)) + (i2 / 32));
                            auto tmp4 = static_cast<long>(2048);
                            auto tmp5 = tmp3 < tmp4;
                            auto tmp6 = 0.0;
                            if(tmp5)
                            {
                                auto tmp7 = static_cast<long>((31 + (63*(i1 / 32)) + (i2 / 32)) % 64);
                                auto tmp8 = static_cast<long>(63);
                                auto tmp9 = tmp7 < tmp8;
                                auto tmp10 = 0.0;
                                if(tmp9)
                                {
                                    auto tmp11 = in_ptr1[(63*(((31 + (63*(i1 / 32)) + (i2 / 32)) / 64))) + (2016*(i1 % 32)) + (64512*i0) + ((31 + (63*(i1 / 32)) + (i2 / 32)) % 64)];
                                    tmp10 = tmp11;
                                }
                                tmp6 = tmp10;
                            }
                            auto tmp12 = static_cast<long>(31 + (63*(i1 % 32)) + (i2 % 32));
                            auto tmp13 = tmp12 < tmp4;
                            auto tmp14 = 0.0;
                            if(tmp13)
                            {
                                auto tmp15 = static_cast<long>((31 + (63*(i1 % 32)) + (i2 % 32)) % 64);
                                auto tmp16 = static_cast<long>(63);
                                auto tmp17 = tmp15 < tmp16;
                                auto tmp18 = 0.0;
                                if(tmp17)
                                {
                                    auto tmp19 = in_ptr2[(63*(((31 + (63*(i1 % 32)) + (i2 % 32)) / 64) % 32)) + (2016*(i1 / 32)) + (64512*i0) + ((31 + (63*(i1 % 32)) + (i2 % 32)) % 64)];
                                    tmp18 = tmp19;
                                }
                                tmp14 = tmp18;
                            }
                            auto tmp20 = tmp6 + tmp14;
                            auto tmp21 = tmp2 + tmp20;
                            auto tmp23 = tmp21 - tmp22;
                            auto tmp24 = std::exp(tmp23);
                            out_ptr1[i2 + (1024*i1) + (1048576*i0)] = tmp24;
                        }
                    }
                }
            }
        }
        #pragma omp for 
        for(long i0=0; i0<262144; ++i0)
        {
            {
                {
                    float tmp1 = 0;
                    for(long i1=0; i1<1024; ++i1)
                    {
                        {
                            auto tmp0 = out_ptr1[i1 + (1024*i0)];
                            tmp1 += tmp0;
                        }
                    }
                    out_ptr2[i0] = tmp1;
                }
            }
        }
        #pragma omp for 
        for(long i0=0; i0<262144; ++i0)
        {
            #pragma GCC ivdep
            for(long i1=0; i1<1024; ++i1)
            {
                {
                    {
                        auto tmp0 = out_ptr1[i1 + (1024*i0)];
                        auto tmp1 = out_ptr2[i0];
                        auto tmp2 = tmp0 / tmp1;
                        out_ptr3[i1 + (1024*i0)] = tmp2;
                    }
                }
            }
        }
        #pragma omp for 
        for(long i0=0; i0<64; ++i0)
        {
            #pragma GCC ivdep
            for(long i1=0; i1<131072; ++i1)
            {
                {
                    {
                        auto tmp0 = in_ptr3[262144 + i1 + (393216*i0)];
                        out_ptr4[i1 + (131072*i0)] = tmp0;
                    }
                }
            }
        }
    }
}

```

**Comment by jgong5** [comment]
@blzheng Thanks. I think `auto tmp = 0.0` makes the tmp as double instead of float. May consider to avoid using "auto" or do explicit type casting, should not be hard to fix.
