### ISSUE TITLE
Fake tensor RuntimeError: !grad_fn INTERNAL ASSERT FAILED at "../torch/csrc/autograd/variable.cpp":792

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#88205]
### 🐛 Describe the bug

Minimal repro was extracted from 

```
TORCH_SHOW_CPP_STACKTRACES=1 TORCHDYNAMO_DYNAMIC_SHAPES=1 AOT_DYNAMIC_SHAPES=1 python benchmarks/dynamo/huggingface.py  --accuracy --backend aot_eager --training --only AllenaiLongformerBase
```

This script fails internal assert:

```
import torch

x = torch.zeros(2)
with torch.no_grad():
    y = x.view(2)
    y.requires_grad = True
z = y.view(2)

z /= 8.0
```

Fails with:

```
Traceback (most recent call last):
  File "repro.py", line 11, in <module>
    r /= 8.0
RuntimeError: !grad_fn INTERNAL ASSERT FAILED at "../torch/csrc/autograd/variable.cpp":792, please report a bug to PyTorch. 
```

Disabling view preservation in MetaConverter turns this into the expected failure:

```
Traceback (most recent call last):                                                                             
  File "repro.py", line 11, in <module>                                                                        
    r /= 8.0
  RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.  
```

cc @albanD 

### Versions

master

**Comment by ezyang** [comment]
cc @eellison

**Comment by ezyang** [comment]
Simplified repro without fake tensor

```
import torch

x = torch.zeros(2, device='meta')
with torch.no_grad():
    y = x.view(2)
    y.requires_grad = True
z = y.view(2)

z /= 8.0
```

**Comment by ezyang** [comment]
cc @soulitzer
