### ISSUE TITLE
Weird random SIGTERM occurance

### ISSUE THREAD

**Issue by CharlesLeeeee** [pytorch/pytorch#88251]
### 🐛 Describe the bug

After training for a few epochs I get thrown an error SIGTERM. There are some models that this happens during training

```
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 59460 closing signal SIGTERM                     [862/1800]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 59461 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 59462 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 59463 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 59466 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 59470 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 59471 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 5 (pid: 59469) of binary: /home/user/.
conda/envs/deit/bin/python
Traceback (most recent call last):
  File "/home/user/.conda/envs/deit/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/user/.conda/envs/deit/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.p
y", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/user/.conda/envs/deit/lib/python3.7/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/user/.conda/envs/deit/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/user/.conda/envs/deit/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/user/.conda/envs/deit/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_age
nt
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-01_17:31:08
  host      : host1
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 59469)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### Versions

torch==1.10.0
torchvision==0.11.1
timm==0.6.7
transformers==4.5.1

**Comment by H-Huang** [comment]
Can you try setting this debug flag to see if you get more information on the error? https://pytorch.org/docs/master/distributed.html#torch-distributed-debug
