### ISSUE TITLE
Import model from lua torch

### ISSUE THREAD

**Issue by KangolHsu** [pytorch/pytorch#883]
I import lua model to pytorch ,the model was printed like this:

nn.Sequential {
  [input -> (0) -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> (16) -> output]
  (0): nn.SpatialConvolution(3 -> 32, 5x5, 2, 2, 2, 2)
  (1): nn.SpatialBatchNormalization
  (2): nn.ReLU
  (3): nn.SpatialConvolution(32 -> 64, 5x5, 2, 2, 2, 2)
  (4): nn.SpatialBatchNormalization
  (5): nn.ReLU
  (6): nn.SpatialConvolution(64 -> 128, 5x5, 2, 2, 2, 2)
  (7): nn.SpatialBatchNormalization
  (8): nn.ReLU
  (9): nn.SpatialConvolution(128 -> 256, 5x5, 2, 2, 2, 2)
  (10): nn.SpatialBatchNormalization
  (11): nn.ReLU
  (12): nn.View(-1)
  (13): nn.Linear(4096 -> 512)
  (14): nn.BatchNormalization
  (15): nn.ReLU
  (16): nn.Linear(512 -> 18)
}

but when i test the model ,it occure error below:
Input:           inputX (FloatTensor :3*64*64)
Output size :18

(1) 
encZ.forward(inputX)

ERROR:
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    Z = encZ.forward(inputX)  #  net:forward
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Module.py", line 33, in forward
    return self.updateOutput(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Sequential.py", line 36, in updateOutput
    currentOutput = module.updateOutput(currentOutput)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/BatchNormalization.py", line 100, in updateOutput
    self._checkInputDim(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/BatchNormalization.py", line 79, in _checkInputDim
    'only mini-batch supported ({}D tensor), got {}D tensor instead'.format(self.nDim, input.dim()))
RuntimeError: only mini-batch supported (4D tensor), got 3D tensor instead

(2)
inputX=Variable(inputX, volatile=True)
encZ.forward(inputX)

ERROR:
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    Z = encZ.forward(inputX)  #  net:forward
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Module.py", line 33, in forward
    return self.updateOutput(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Sequential.py", line 36, in updateOutput
    currentOutput = module.updateOutput(currentOutput)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/SpatialConvolution.py", line 96, in updateOutput
    self.padW, self.padH
TypeError: FloatSpatialConvolutionMM_updateOutput received an invalid combination of arguments - got (int, Variable, torch.FloatTensor, torch.FloatTensor, torch.FloatTensor, torch.FloatTensor, torch.FloatTensor, int, int, int, int, int, int), but expected (int state, torch.FloatTensor input, torch.FloatTensor output, torch.FloatTensor weight, [torch.FloatTensor bias or None], torch.FloatTensor finput, torch.FloatTensor fgradInput, int kW, int kH, int dW, int dH, int padW, int padH)

(3)
encZ.eval()
encZ.forward(inputX)

ERROR:
Traceback (most recent call last):
  File "test.py", line 68, in <module>
    encZ.eval()
AttributeError: 'Sequential' object has no attribute 'eval'

(4)
X = inputX.resize_(1, 3, 64, 64)
encZ.forward(X)

ERROR:
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    Z = encZ.forward(X)  #  net:forward
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Module.py", line 33, in forward
    return self.updateOutput(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Sequential.py", line 36, in updateOutput
    currentOutput = module.updateOutput(currentOutput)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Linear.py", line 44, in updateOutput
    assert input.dim() == 2
AssertionError

I REALLY don not kown what happen ,could you give me some clues?

**Comment by soumith** [comment]
> RuntimeError: only mini-batch supported (4D tensor), got 3D tensor instead

That's the first error. Instead of passing input of 3d, pass input of 4d.

> AttributeError: 'Sequential' object has no attribute 'eval'
It's `encZ.evaluate()`

> assert input.dim() == 2
Also is the same error as (1)

**Comment by KangolHsu** [comment]
Thank you. 
when i change the input to 4d tensor : X = inputX.resize_(1, 3, 64, 64), and use encZ.evaluate(), 
 the error 'assert input.dim() == 2' still  occures, it must be something wrong in
 '(13): nn.Linear(4096 -> 512)'
we could not change the input size of  '(13): nn.Linear(4096 -> 512)',aren't we?
Should I change the  encZ model ?that means i should redesign the model and train it again?

**Comment by KangolHsu** [comment]
Thank you
I solved it by the code below:

encZ.modules[12] = nn.View(1,4096)

As you said 
(12): nn.View(-1)
cause the error.'assert input.dim() == 2'


Thank you very much @soumith
