### ISSUE TITLE
`nn.utils.rnn.pack_sequence` Trigger heap-buffer-overflow with AddressSanitizer

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#88334]
### 🐛 Describe the bug

A test case for `torch.nn.utils.rnn.pack_sequence` triggers heap-buffer-overflow under the address sanitizer.

Reproduction:
```python
import torch

def test():
    arg_1_0_tensor = torch.rand([1024, 255, 255], dtype=torch.float32)
    arg_1_0 = arg_1_0_tensor.clone()
    arg_1_1_tensor = torch.rand([1, 255], dtype=torch.float16)
    arg_1_1 = arg_1_1_tensor.clone()
    arg_1_2_tensor = torch.rand([1, 0, 0], dtype=torch.float32)
    arg_1_2 = arg_1_2_tensor.clone()
    arg_1_3_tensor = torch.rand([1, 255, 0], dtype=torch.float32)
    arg_1_3 = arg_1_3_tensor.clone()
    arg_1 = [arg_1_0,arg_1_1,arg_1_2,arg_1_3,]
    arg_2 = 0
    res = torch.nn.utils.rnn.pack_sequence(arg_1,arg_2,)

test()
```
Error log:
```
=================================================================
AddressSanitizer:DEADLYSIGNAL
==454591==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6160016b177f at pc 0x7f30ceecfdb6 bp 0x7ffee6844f70 sp 0x7ffee6844f68
READ of size 16 at 0x6160016b177f thread T0
    #0 0x7f30ceecfdb5 in fbgemm::Float16ToFloat_avx2(unsigned short const*, float*, unsigned long) (/home/yuyao/.local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so+0x15b5cdb5) (BuildId: 047b13f0c897b1b6994d0908d15a8c9d114f31b2)
    #1 0x7f30c04bccf9 in std::function<void (long, long)>::operator()(long, long) const (/home/yuyao/.local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so+0x7149cf9) (BuildId: 047b13f0c897b1b6994d0908d15a8c9d114f31b2)
    #2 0x7f30c04a9dc5 in void std::__invoke_impl<void, at::internal::invoke_parallel(long, long, long, std::function<void (long, long)> const&)::$_1&, int, unsigned long>(std::__invoke_other, at::internal::invoke_parallel(long, long, long, std::function<void (long, long)> const&)::$_1&, int&&, unsigned long&&) ParallelNative.cpp
    #3 0x7f30c04ab1ab in std::function<void (int, unsigned long)>::operator()(int, unsigned long) const (/home/yuyao/.local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so+0x71381ab) (BuildId: 047b13f0c897b1b6994d0908d15a8c9d114f31b2)
    #4 0x7f30c04a8692 in at::(anonymous namespace)::_run_with_pool(std::function<void (int, unsigned long)> const&, unsigned long) ParallelNative.cpp
...
```

### Versions

```
PyTorch version: 1.14.0a0+gita86278b
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 11.1.0-6
CMake version: version 3.24.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.14.0a0+gita86278b
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0
```

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @zou3519

**Comment by H-Huang** [comment]
I tried to repro this and did not get a segfault, but got
```
Traceback (most recent call last):
  File "new.py", line 16, in <module>
    test()
  File "new.py", line 14, in test
    res = torch.nn.utils.rnn.pack_sequence(arg_1,arg_2,)
  File "/private/home/howardhuang/pytorch-projects/pytorch/torch/nn/utils/rnn.py", line 484, in pack_sequence
    return pack_padded_sequence(pad_sequence(sequences), lengths, enforce_sorted=enforce_sorted)
  File "/private/home/howardhuang/pytorch-projects/pytorch/torch/nn/utils/rnn.py", line 398, in pad_sequence
    return torch._C._nn.pad_sequence(sequences, batch_first, padding_value)
RuntimeError: The size of tensor a (255) must match the size of tensor b (0) at non-singleto
```

**Comment by Kristoff-starling** [comment]
Hi @H-Huang,
Thanks for your reply! I tried to repro this test on various PyTorch versions, and
* It seems that segfault occurs in the latest stable version (i.e., 1.12.1) and the master branch version I cloned on Oct 13 (gita86278b). 
* In the latest master branch version, PyTorch will throw a runtime error as you mentioned.

I'm sorry that I didn't conduct the test on the latest master branch version before raising this issue. But the heap-buffer-overflow problem caught by address sanitizer still exists in the latest version. I'll modify the title of the issue.

**Comment by Kristoff-starling** [comment]
Here is a [gist](https://colab.research.google.com/gist/Kristoff-starling/561b6300d43ee734d48f0a502882bafd/torch-88334.ipynb) for reproduction. We upload a recent version of PyTorch (built with sanitizers) on pypi and reproduce the error on Colab.
cc @malfet Could you please take a look at this issue when you're available (sorry if I find the wrong developer)? Thanks a lot!

**Comment by Kristoff-starling** [comment]
It seems that in the latest nightly version the problem has been fixed. I'll close this issue.
