### ISSUE TITLE
`BSR/BSC`: impossible to use `.to(dtype)` because `empty_sparse_compressed` does not support block formats.

### ISSUE THREAD

**Issue by nikitaved** [pytorch/pytorch#88419]
### 🐛 Describe the bug

As per title. Unless there are some limitations of which I am not aware of, the error message could be less cryptic.

```python
>>> import torch
>>> torch.rand(4, 4).to_sparse_bsr(2).to(torch.half)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "empty_sparse_compressed" expected sparse compressed (non-block) tensor layout but got SparseBsr
>>> torch.rand(4, 4).to_sparse_bsc(2).to(torch.half)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "empty_sparse_compressed" expected sparse compressed (non-block) tensor layout but got SparseBsc
```

### Versions

Current master.

**Comment by cpuhrsch** [comment]
@nikitaved - do you want to send a fix?
