### ISSUE TITLE
AvgPool2D output shapes can be negative when ceil_mode=True

### ISSUE THREAD

**Issue by MitchellBuckley** [pytorch/pytorch#88464]
### 🐛 Describe the bug

When ceil_mode=True, output shape can potentially be negative, which is nonsensical. I think the calcuation of output shape for that case is wrong.

This seems related to issue https://github.com/pytorch/pytorch/issues/88144

```python
import torch

m = torch.nn.MaxPool1d(kernel_size=4, stride=1, padding=0, dilation=1, ceil_mode=True)
input = torch.randn(20, 16, 1)
output = m(input)
```

```
Traceback (most recent call last):
  File "/Users/mitch/***/avgpool.py", line 6, in <module>
    output = m(input)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/modules/pooling.py", line 92, in forward
    return F.max_pool1d(input, self.kernel_size, self.stride,
  File "/opt/homebrew/lib/python3.10/site-packages/torch/_jit_internal.py", line 485, in fn
    return if_false(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/nn/functional.py", line 696, in _max_pool1d
    return torch.max_pool1d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: max_pool1d() Invalid computed output size: -2
```

My experiments suggest that output shape for ceil_mode = True should be `ceiling((inputsize + padleft) / stride)`.

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)] (64-bit runtime)
Python platform: macOS-12.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchvision==0.14.0
[conda] Could not collect
```

**Comment by Guobing-Chen** [comment]
The PR https://github.com/pytorch/pytorch/pull/88421 for issue https://github.com/pytorch/pytorch/issues/88144 can also fix this issue.

The example above can run pass and output shape will be the same as input -- [20, 16, 1].

I am fixing UT failure in the PR https://github.com/pytorch/pytorch/pull/88421 now.

**Comment by mingfeima** [comment]
@Guobing-Chen could you please also update the test case, so that this issue can been reflected.

**Comment by Guobing-Chen** [comment]
```
import torch

m = torch.nn.MaxPool1d(kernel_size=4, stride=1, padding=0, dilation=1, ceil_mode=True)
input = torch.randn(20, 16, 1)
output = m(input)
```
As for this reported case, the correct output shape should be (20, 16, 1) if we calculate it by hand under ceil_mode=True semantic, so it should be a real issue. I don't have a CUDA env to try the CUDA path behavior and why that. But anyway we should expect pytorch to behave like we get by hand.

**Comment by Valentine233** [comment]
This issue, that output size is 0 or negative, would be triggered when kernel size is bigger than input size whether ceil mode is on or not. Here are the formulas of output shapes.

[maxpool1d](https://pytorch.org/docs/stable/generated/torch.nn.MaxPool1d.html)
<img width="403" alt="image" src="https://user-images.githubusercontent.com/23010269/230301611-d5aaec69-0f77-44ae-b68e-11865c684d49.png">

[avgpool1d](https://pytorch.org/docs/stable/generated/torch.nn.AvgPool1d.html)
<img width="351" alt="image" src="https://user-images.githubusercontent.com/23010269/230298076-51169ecb-e6c2-40e7-8112-5a8952ca5cc3.png">

Actually, I am wondering if this case is legal.

I suggest that it is illegal when ceil mode is off because we could not add any paddings to do the pool. We could add an assertion to restrict the input size and kernel size like `TORCH_CHECK(kernel_size <= input_size)`.

For ceil mode is on, I am not very sure. I prefer to also regard the case as illegal because a big kernel for a small input has little meaning... However, if we want to treat it as legal, we could force the output size to be >=1 to produce a valid output as #98485.
