### ISSUE TITLE
DISABLED test_index_put_accumulate_large_tensor_cpu (__main__.TestIndexingCPU)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#88472]
Platforms: dynamo

This is related to https://github.com/pytorch/pytorch/issues/88413

This test was disabled because it is suspected to cause `test_indexing.py` to become flaky with SIGKILL.  Looking into the log such as https://github.com/pytorch/pytorch/actions/runs/3388902619/jobs/5631574640, it's unclear which sends SIGKILL to the test, but it's always at `test_index_put_accumulate_large_tensor_cpu`.  For example:

```
test_boolean_assignment_value_mismatch_cpu (__main__.NumpyTestsCPU) ... ok
test_boolean_indexing_alldims_cpu (__main__.NumpyTestsCPU) ... ok
test_boolean_indexing_onedim_cpu (__main__.NumpyTestsCPU) ... ok
test_boolean_indexing_twodim_cpu (__main__.NumpyTestsCPU) ... ok
test_boolean_indexing_weirdness_cpu (__main__.NumpyTestsCPU) ...ok
test_boolean_indexing_weirdness_tensors_cpu (__main__.NumpyTestsCPU) ... ok
test_boolean_list_indexing_cpu (__main__.NumpyTestsCPU) ... ok
test_boolean_shape_mismatch_cpu (__main__.NumpyTestsCPU) ... ok
test_broadcast_subspace_cpu (__main__.NumpyTestsCPU) ... ok
test_broaderrors_indexing_cpu (__main__.NumpyTestsCPU) ... ok
test_ellipsis_index_cpu (__main__.NumpyTestsCPU) ... ok
test_empty_fancy_index_cpu (__main__.NumpyTestsCPU) ... ok
test_empty_tuple_index_cpu (__main__.NumpyTestsCPU) ... ok
test_everything_returns_views_cpu (__main__.NumpyTestsCPU) ... ok
test_index_is_larger_cpu (__main__.NumpyTestsCPU) ... ok
test_index_no_floats_cpu (__main__.NumpyTestsCPU) ... ok
test_none_index_cpu (__main__.NumpyTestsCPU) ... ok
test_single_bool_index_cpu (__main__.NumpyTestsCPU) ... ok
test_single_int_index_cpu (__main__.NumpyTestsCPU) ... ok
test_trivial_fancy_out_of_bounds_cpu (__main__.NumpyTestsCPU) ... ok
test_advancedindex_big_cpu (__main__.TestIndexingCPU) ... ok
test_advancedindex_cpu_float16 (__main__.TestIndexingCPU) ... ok
test_advancedindex_cpu_float64 (__main__.TestIndexingCPU) ...ok
test_basic_advanced_combined_cpu (__main__.TestIndexingCPU) ... ok
test_bool_indices_accumulate_cpu (__main__.TestIndexingCPU) ... ok
test_bool_indices_cpu (__main__.TestIndexingCPU) ... ok
test_byte_mask2d_cpu (__main__.TestIndexingCPU) ... ok
test_byte_mask_accumulate_cpu (__main__.TestIndexingCPU) ... ok
test_byte_mask_cpu (__main__.TestIndexingCPU) ... ok
test_byte_tensor_assignment_cpu (__main__.TestIndexingCPU) ... ok
test_cpu_indices_cpu (__main__.TestIndexingCPU) ... skip: Only runs on cuda (0.002s)
test_ellipsis_tensor_cpu (__main__.TestIndexingCPU) ... ok
test_empty_index_cpu (__main__.TestIndexingCPU) ... ok
test_empty_ndim_index_bool_cpu (__main__.TestIndexingCPU) ... ok
test_empty_ndim_index_cpu (__main__.TestIndexingCPU) ... ok
test_empty_slice_cpu (__main__.TestIndexingCPU) ... ok
test_gather_take_along_dim_cross_device_cpu_float32 (__main__.TestIndexingCPU) ... skip: Only runs on cuda
test_getitem_scalars_cpu (__main__.TestIndexingCPU) ... ok
test_index_cpu (__main__.TestIndexingCPU) ... ok
test_index_getitem_copy_bools_slices_cpu (__main__.TestIndexingCPU) ... ok
test_index_ind_dtype_cpu (__main__.TestIndexingCPU) ... ok
test_index_put_accumulate_duplicate_indices_cpu (__main__.TestIndexingCPU) ... ok
test_index_put_accumulate_expanded_values_cpu (__main__.TestIndexingCPU) ... ok
test_index_put_accumulate_large_tensor_cpu (__main__.TestIndexingCPU) ...

Traceback (most recent call last):
  File "test/run_test.py", line 1283, in <module>
    main()
  File "test/run_test.py", line 1258, in main
    raise RuntimeError(err_message)
RuntimeError: test_indexing failed! Received signal: SIGKILL
```

I'm trying to do an experimentation and disable this test for a few days to see if it helps and go from there

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

**Comment by malfet** [comment]
Probably the test is terminated by the kernel OOM killer. To give a better understand of what is going on, perhaps we should add `dmesg -c` in `Setup Linux` step and run `dmesg` (that prints kernel messages) during the shutdown phase if Test step failed (or may be just print it by default, as it should be empty for successful test run)

**Comment by zou3519** [comment]
Test is already skipped, so we don't need this DISABLED issue. I'm closing it.

Separately, I want to try removing the skip from the test, because it sounds like this problem was for a build config that doesn't exist anymore (py37)

**Comment by huydhn** [comment]
For the context, the test has been skipped explicitly in dynamo https://github.com/pytorch/pytorch/blob/07499074bb3333dcb979b45b554a6c6c8c69a822/test/test_indexing.py#L742, so we can definitely close this one.
