### ISSUE TITLE
Add FX support for `torch.Generator`

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#88574]
### 🐛 Describe the bug

Code:
```
def fn1(x):
    return torch.manual_seed(x)

b = make_fx(fn1)
b(1729).print_readable()
```

```
incomplete graph:
class fn1(torch.nn.Module):
    def forward(self, x_1):
        pass

Traceback (most recent call last):
  File "/scratch/chourdiaanjali/work/pytorch/tryy2.py", line 22, in <module>
    b(1729).print_readable()
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 665, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 422, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 412, in create_arg
    return super().create_arg(a)
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/_symbolic_trace.py", line 344, in create_arg
    return super().create_arg(a)
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/proxy.py", line 165, in create_arg
    raise NotImplementedError(f"argument of type: {type(a)}")
NotImplementedError: argument of type: <class 'torch._C.Generator'>
```

### Versions

master

**Comment by anjali411** [comment]
Ran into this while working on model enablement for `hf_Reformer` with dynamo
