### ISSUE TITLE
nn.Linear allocate too many space which lead to CPUAllocator "allocate memory failure" if it's BF16. good for FP32.

### ISSUE THREAD

**Issue by sywangyi** [pytorch/pytorch#88658]
### 🐛 Describe the bug

Torch version: 1.13.0+cpu

BF16 code

```python
from torch import nn
import torch
lm_head = nn.Linear(1536, 250880, bias=False, dtype=torch.bfloat16)
input=torch.ones(size=(8,1024,1536), dtype=torch.bfloat16)
output=lm_head(input)
```

crash:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/skyrex05/wangyi/miniconda3/envs/compatibility_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/skyrex05/wangyi/miniconda3/envs/compatibility_test/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 189079224448 bytes. Error code 12 (Cannot allocate memory)

FP32 code

```python
from torch import nn
import torch
lm_head = nn.Linear(1536, 250880, bias=False)
input=torch.ones(size=(8,1024,1536))
output=lm_head(input)
```

no crash

### Versions

PyTorch version: 1.13.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.13 (main, Oct 13 2022, 21:15:33)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 10.1.243
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.12.300
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] torch==1.13.0+cpu
[pip3] torchaudio==0.13.0+cpu
[pip3] torchvision==0.14.0+cpu
[conda] intel-extension-for-pytorch 1.12.300                 pypi_0    pypi
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] torch                     1.13.0+cpu               pypi_0    pypi
[conda] torchaudio                0.13.0+cpu               pypi_0    pypi
[conda] torchvision               0.14.0+cpu               pypi_0    pypi

**Comment by jingxu10** [comment]
cc @zhuhaozhe

**Comment by sywangyi** [comment]
@yao-matrix

**Comment by zhuhaozhe** [comment]
Hi, @sywangyi. I cannot reproduce it.
May you help to show your system memory here?

And may you help to run:
```python
from torch import nn
import torch
import os
import psutil

lm_head = nn.Linear(1536, 250880, bias=False, dtype=torch.bfloat16)

input=torch.ones(size=(8,1024,1536), dtype=torch.bfloat16)
for i in range(100):
    print(psutil.Process(os.getpid()).memory_info().rss/1024/1024)
    output=lm_head(input)
```
And observe the memory usage in the other terminal with `free -s 0.001`. Please help to observe both fp32/bf16.

**Comment by sywangyi** [comment]
Hi, @zhuhaozhe , in my system, the lm_head(input) will fail for BF16 and throw out "DefaultCPUAllocator: can't allocate memory : you tried to allocate 189079224448 bytes. Error code 12 (Cannot allocate memory)". so, how could it run 100 loop?

my total DDR is 32x4G, so maybe you could reduce the DDRs and reproduce it.
