### ISSUE TITLE
MPS test_embedding_dense_backward is possibly flaky?

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#88679]
### 🐛 Describe the bug

Pretty sure my changes are unrelated.

```
2022-11-08T13:53:53.6168210Z ======================================================================
2022-11-08T13:53:53.6168460Z FAIL [0.341s]: test_embedding_dense_backward (__main__.TestNLLLoss)
2022-11-08T13:53:53.6168870Z ----------------------------------------------------------------------
2022-11-08T13:53:53.6169050Z Traceback (most recent call last):
2022-11-08T13:53:53.6169350Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/test_mps.py", line 4308, in test_embedding_dense_backward
2022-11-08T13:53:53.6169570Z     helper(3, 5, 7, 2)  # test scalar index
2022-11-08T13:53:53.6169890Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/test_mps.py", line 4304, in helper
2022-11-08T13:53:53.6170100Z     self.assertEqual(b_CPU.grad, b_MPS.grad)
2022-11-08T13:53:53.6170440Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3419829967/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2469, in assertEqual
2022-11-08T13:53:53.6170670Z     assert_equal(
2022-11-08T13:53:53.6170970Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3419829967/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
2022-11-08T13:53:53.6171210Z     raise error_metas[0].to_error(msg)
2022-11-08T13:53:53.6171400Z AssertionError: Tensor-likes are not close!
2022-11-08T13:53:53.6171510Z 
2022-11-08T13:53:53.6171560Z Mismatched elements: 5 / 7 (71.4%)
2022-11-08T13:53:53.6171790Z Greatest absolute difference: 3.8305271869972695e-05 at index (4,) (up to 1e-05 allowed)
2022-11-08T13:53:53.6172050Z Greatest relative difference: 242269320.946593 at index (4,) (up to 1.3e-06 allowed)
```

https://github.com/pytorch/pytorch/actions/runs/3419829967/jobs/5694230128

### Versions

master

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by suo** [comment]
I am disabling this test as it is definitely flaky

**Comment by suo** [comment]
Note that I have to do this manually as MPS *still* does not use our standard test infra, @albanD me sad 😛

**Comment by suo** [comment]
wait maybe it does? @clee2000 it is using `common_utils.TestCase`, can you confirm whether this is sufficient to work with our disabled test infra?

**Comment by malfet** [comment]
@suo there is a PR to put MPS on a standard rails: https://github.com/pytorch/pytorch/pull/88829

**Comment by suo** [comment]
wheee! So timely :)

**Comment by malfet** [comment]
But yeah, usually it fails after several re-runs:
```
% python test_mps.py -k test_embedding_dense_backward --repeat 10
/Users/nshulga/git/pytorch/pytorch/torch/nn/functional.py:2106: UserWarning: The operator 'aten::embedding_renorm_' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at ../aten/src/ATen/mps/MPSFallback.mm:11.)
  torch.embedding_renorm_(weight.detach(), input, max_norm, norm_type)
.
----------------------------------------------------------------------
Ran 1 test in 0.148s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.011s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.010s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.010s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.011s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.010s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.010s

OK
F
======================================================================
FAIL: test_embedding_dense_backward (__main__.TestNLLLoss)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nshulga/git/pytorch/pytorch/test/test_mps.py", line 4310, in test_embedding_dense_backward
    helper(3, 5, 7, 2)  # test scalar index
  File "/Users/nshulga/git/pytorch/pytorch/test/test_mps.py", line 4306, in helper
    self.assertEqual(b_CPU.grad, b_MPS.grad)
  File "/Users/nshulga/git/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2492, in assertEqual
    assert_equal(
  File "/Users/nshulga/git/pytorch/pytorch/torch/testing/_comparison.py", line 1118, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 7 / 7 (100.0%)
Greatest absolute difference: 0.0002789647140708229 at index (3,) (up to 1e-05 allowed)
Greatest relative difference: 12346821.016263464 at index (6,) (up to 1.3e-06 allowed)

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (failures=1)
```
