### ISSUE TITLE
test_make_fx_symbolic_exhaustive fails for scalar_tensor

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#88738]
ERROR: test_make_fx_symbolic_exhaustive_scalar_tensor_cpu_float32 (__main__.TestProxyTensorOpInfoCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/chourdiaanjali/work/pytorch/torch/testing/_internal/common_device_type.py", line 391, in instantiated_test
    raise rte
  File "/scratch/chourdiaanjali/work/pytorch/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    result = test(self, **param_kwargs)
  File "/scratch/chourdiaanjali/work/pytorch/torch/testing/_internal/common_device_type.py", line 828, in test_wrapper
    return test(*args, **kwargs)
  File "/scratch/chourdiaanjali/work/pytorch/test/test_proxy_tensor.py", line 1538, in test_make_fx_symbolic_exhaustive
    _test_make_fx_helper(self, device, dtype, op, "symbolic")
  File "/scratch/chourdiaanjali/work/pytorch/test/test_proxy_tensor.py", line 1509, in _test_make_fx_helper
    new_f = make_fx(f, tracing_mode=tracing_mode)(args, kwargs, extra_args)
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 652, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 412, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/_symbolic_trace.py", line 614, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/scratch/chourdiaanjali/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 426, in wrapped
    out = f(*tensors)
  File "/scratch/chourdiaanjali/work/pytorch/test/test_proxy_tensor.py", line 1485, in f
    return fn(*args, **kwargs)
RuntimeError: Cannot call numel() on tensor with symbolic sizes/strides

### Versions

master

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv

**Comment by ZhaoqiongZ** [comment]
Hi @anjali411 , I rebuild pytorch on both cpu and cuda with commit 495e7b1c729e64693e794ea22640b4552816f0ef, and test unit test/test_proxy_tensor.py passed correctly.  Maybe you can have a try with the this commit or provide more details for us to reproduce?
