### ISSUE TITLE
Cannot install VSIXTorch

### ISSUE THREAD

**Issue by mmetwalli96** [pytorch/pytorch#88824]
### 🐛 Describe the bug

I am trying to install VSIXTorch and I am getting this error message 
```
2022-11-10 12:58:47 PM - Microsoft VSIX Installer
2022-11-10 12:58:47 PM - -------------------------------------------
2022-11-10 12:58:47 PM - vsixinstaller.exe version:
2022-11-10 12:58:47 PM - 17.4.2118-17-4P4Inse-ge4c88902
2022-11-10 12:58:47 PM - -------------------------------------------
2022-11-10 12:58:47 PM - Command line parameters:
2022-11-10 12:58:47 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\Downloads\VSIXTorch.vsix
2022-11-10 12:58:47 PM - -------------------------------------------
2022-11-10 12:58:47 PM - Microsoft VSIX Installer
2022-11-10 12:58:47 PM - -------------------------------------------
2022-11-10 12:58:47 PM - Initializing Install...
2022-11-10 12:58:47 PM - Extension Details...
2022-11-10 12:58:47 PM - 	Identifier         : VSIXTorch.58930436-5e14-4760-a334-3ab7650104aa
2022-11-10 12:58:47 PM - 	Name               : LibTorch Project
2022-11-10 12:58:47 PM - 	Author             : Yi Zhang
2022-11-10 12:58:47 PM - 	Version            : 0.6.0
2022-11-10 12:58:47 PM - 	Description        : LibTorch C++ Project Template
2022-11-10 12:58:47 PM - 	Locale             : en-US
2022-11-10 12:58:47 PM - 	MoreInfoURL        : 
2022-11-10 12:58:47 PM - 	InstalledByMSI     : False
2022-11-10 12:58:47 PM - 	SupportedFrameworkVersionRange : [4.5,)
2022-11-10 12:58:47 PM - 
2022-11-10 12:58:47 PM - 	SignatureState     : Unsigned
2022-11-10 12:58:47 PM - 	Supported Products : 
2022-11-10 12:58:47 PM - 		Microsoft.VisualStudio.Community
2022-11-10 12:58:47 PM - 			Version : [16.0,17.0)
2022-11-10 12:58:47 PM - 			ProductArchitecture : x86
2022-11-10 12:58:47 PM - 
2022-11-10 12:58:47 PM - 	References         : 
2022-11-10 12:58:47 PM - 	Prerequisites      : 
2022-11-10 12:58:47 PM - 		-------------------------------------------------------
2022-11-10 12:58:47 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2022-11-10 12:58:47 PM - 		Name         : Visual Studio core editor
2022-11-10 12:58:47 PM - 		Version      : [16.0,17.0)
2022-11-10 12:58:47 PM - 
2022-11-10 12:58:47 PM - Signature Details...
2022-11-10 12:58:47 PM - 	Extension is not signed.
2022-11-10 12:58:47 PM - 
2022-11-10 12:58:47 PM - Searching for applicable products...
2022-11-10 12:58:47 PM - Found installed product - Global Location
2022-11-10 12:58:47 PM - Found installed product - Visual Studio Community 2022
2022-11-10 12:58:47 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

I have a Visual Studio 2022 installed at the moment

### Versions

This is for the Torch 1.13

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @jbschlosser

**Comment by malfet** [comment]
cc: @vladimir-aubrecht

**Comment by mszhanyi** [comment]
@mmetwalli96
So far, VS 2022 isn't supported for this extension. Please try using VS 2019

**Comment by mmetwalli96** [comment]
@mszhanyi  
Do you have a plan for when it will be available for VS 2022?

**Comment by Blackhex** [comment]
@malfet @mszhanyi Can you please give me some context what is the relation of VSIXTorch project to the PyTorch repository? I am mostly currious why this issue is tracked here and not at https://github.com/mszhanyi/VSIXTorch/issues?

**Comment by mantaionut** [comment]
VSIXTorch now supports VS2022 https://marketplace.visualstudio.com/items?itemName=YiZhang.LibTorch001
