### ISSUE TITLE
binary_cross_entropy/bce_with_logits (+ other loss functions) for nested_tensor

### ISSUE THREAD

**Issue by frankier** [pytorch/pytorch#89125]
### 🚀 The feature, motivation and pitch

For multi-task learning, it could be useful to have loss functions support nested_tensors. Some of the reductions might not be so useful for some loss functions as currently implemented since they seem to assume regularly sized inputs, but at least something could be implemented when reduce="none".

```
import torch
from torch.nn.functional import binary_cross_entropy

nt = torch.nested.nested_tensor([[1.0, 0.4, 0.2], [0.1]])
print(binary_cross_entropy(nt, nt, reduce="none"))
```

Current output

```
/home/frankier/edu/doc/bert_ordinal/nightlytorchplay/losstest.py:5: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:177.)
  nt = torch.nested.nested_tensor([[1.0, 0.4, 0.2], [0.1]])
Traceback (most recent call last):
  File "/home/frankier/edu/doc/bert_ordinal/nightlytorchplay/losstest.py", line 7, in <module>
    print(binary_cross_entropy(nt, nt, reduction="none"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frankier/edu/doc/bert_ordinal/nightlytorchplay/venv/lib/python3.11/site-packages/torch/nn/functional.py", line 3087, in binary_cross_entropy
    if target.size() != input.size():
       ^^^^^^^^^^^^^
RuntimeError: Internal error: NestedTensorImpl doesn't support sizes. Please file an issue on https://github.com/pytorch/nestedtensor
```

### Alternatives

If this were possible https://github.com/pytorch/pytorch/issues/89124 it might provide a good/easy workaround.

**Comment by drisspg** [comment]
Thanks for commenting with this feature request, I am going to add these to this list: #83994

**Comment by drisspg** [comment]
The main blocker for implementing these functions for NestedTensors is bandwidth on our team. We would be happy to accept external contributions if you wanted to contribute. Of the Op proposals you created issues for I think that the loss functions would be the most straight forward. 

The reasons why I don't think the other ones are as amenable is because the NestedTensor data structure is still in prototype and likely to be changed somewhat going forward. Specifically on how shape information is stored and tracked. 

If this is something you might be interested in I would be happy to provide more context on what a bce implementation for NestedTensor looks like.
