### ISSUE TITLE
Multiprocessing Self Test Error

### ISSUE THREAD

**Issue by syed-ahmed** [pytorch/pytorch#8913]
Getting this error in multi processing self test. The bug surfaces when I issue the `run_test` command like two more times one after another.

System:
Pytorch (cca24763), CUDA 9, V100

```
Running test_multiprocessing ...
s..........FTraceback (most recent call last):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
.EFTraceback (most recent call last):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 112, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: unable to open shared memory object </torch_34959_822569775> in read-write mode at ../aten/src/TH/THAllocator.cpp:334
```

**Comment by syed-ahmed** [comment]
I was able to reproduce multiprocessing error consistently by changing `time.sleep` to `0.01` here https://github.com/pytorch/pytorch/blob/master/test/test_multiprocessing.py#L288, with the command `python test_multiprocessing.py -v TestMultiprocessing`. However if you run `test_fs` in isolation using `python test_multiprocessing.py -v TestMultiprocessing.test_fs`, it doesn't reproduce. So it tells me that, something has to do with how `time.sleep` is used in the sequence of tests in that module?

**Comment by davidenitti** [comment]
any update on this bug?

**Comment by syed-ahmed** [comment]
Hi @davidenitti . I don't know the root cause for this bug other than that it's flaky and is closely coupled with the machine it's running on. In our CI, we run this test with `time.sleep(0.5)` in this line: https://github.com/pytorch/pytorch/blob/master/test/test_multiprocessing.py#L344.
