### ISSUE TITLE
different behaviour with reshape within torch.fx on different torch version

### ISSUE THREAD

**Issue by westfly** [pytorch/pytorch#89206]
### 🐛 Describe the bug
when I update my torch version from 1.8.2(lts) to 1.12.1 (nearly latest)， I got an error， the script below may reproduce

I test on 1.11.0 1.10.1 get some error

```python
from torch.fx import GraphModule, Tracer
import torch
class GateEmbedding(torch.nn.Module):
    def __init__(self, in_size, out_size, act1=torch.nn.ReLU(), act2=torch.nn.Sigmoid(), act3=torch.nn.ReLU()):
        super().__init__()
        self.layer1 = torch.nn.Linear(in_size, out_size)
        self.out_size = out_size
        self.act2 = act2
        print(f"debug ###{in_size}   {self.out_size}###")

    def forward(self, input):
        gate_out = self.act2(self.layer1(input))
        print(f"debug ###{gate_out.shape}   {self.out_size}###")
        size = gate_out.shape[0]
        print(f"debug ###{gate_out.shape[0]} {type(size)}  {self.out_size}###")
        gate_out_r = torch.reshape(gate_out, (gate_out.shape[0], self.out_size, -1))
        input_r = torch.reshape(input, (input.shape[0], self.out_size, -1))
        gate_out = (gate_out_r * input_r).reshape(input.shape[0], -1)
        # return self.act3(info_out * gate_out)
        return gate_out  # gate_2

my_tracer=Tracer()
print(f"torch version {torch.__version__}")
embedding_model=GateEmbedding(100, 41)
symbolic_traced : torch.fx.Graph = my_tracer.trace(embedding_model)
symbolic_traced.print_tabular()
```
when test on 1.8.2 

```
torch version 1.8.2+cpu
debug ###100   41###
debug ###Proxy(getattr_1)   41###
debug ###Proxy(getitem_1) <class 'torch.fx.proxy.Proxy'>  41###
opcode         name       target                                                      args                            kwargs
-------------  ---------  ----------------------------------------------------------  ------------------------------  --------
placeholder    input_1    input                                                       ()                              {}
call_module    layer1     layer1                                                      (input_1,)                      {}
call_module    act2       act2                                                        (layer1,)                       {}
call_function  getattr_1  <built-in function getattr>                                 (act2, 'shape')                 {}
call_function  getattr_2  <built-in function getattr>                                 (act2, 'shape')                 {}
call_function  getitem    <built-in function getitem>                                 (getattr_2, 0)                  {}
call_function  getattr_3  <built-in function getattr>                                 (act2, 'shape')                 {}
call_function  getitem_1  <built-in function getitem>                                 (getattr_3, 0)                  {}
call_function  getattr_4  <built-in function getattr>                                 (act2, 'shape')                 {}
call_function  getitem_2  <built-in function getitem>                                 (getattr_4, 0)                  {}
call_function  reshape_1  <built-in method reshape of type object at 0x7f68395e6880>  (act2, (getitem_2, 41, -1))     {}
call_function  getattr_5  <built-in function getattr>                                 (input_1, 'shape')              {}
call_function  getitem_3  <built-in function getitem>                                 (getattr_5, 0)                  {}
call_function  reshape_2  <built-in method reshape of type object at 0x7f68395e6880>  (input_1, (getitem_3, 41, -1))  {}
call_function  mul_1      <built-in function mul>                                     (reshape_1, reshape_2)          {}
call_function  getattr_6  <built-in function getattr>                                 (input_1, 'shape')              {}
call_function  getitem_4  <built-in function getitem>                                 (getattr_6, 0)                  {}
call_method    reshape_3  reshape                                                     (mul_1, getitem_4, -1)          {}
output         output     output                                                      (reshape_3,)                    {}
```

but failed after version 1.10.1 above
```
torch version 1.10.1+cpu
debug ###100   41###
debug ###Proxy(getattr_1)   41###
debug ###Proxy(getitem_1) <class 'torch.fx.proxy.Proxy'>  41###
Traceback (most recent call last):
  File "test_oss_fx.py", line 25, in <module>
    symbolic_traced : torch.fx.Graph = my_tracer.trace(embedding_model)
  File "/xxx/python-env/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 615, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "test_oss_fx.py", line 16, in forward
    gate_out_r = torch.reshape(gate_out, (gate_out.shape[0], self.out_size, -1))
TypeError: reshape(): argument 'shape' (position 2) must be tuple of ints, not tuple
```

### Versions

install different version 
```
pip3 install torch==1.8.2 torchvision==0.9.2 torchaudio==0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cpu

pip3 install torch==1.10.1+cpu torchvision==0.11.2+cpu torchaudio==0.10.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html
```

cc @ezyang @SherlockNoMad @soumith @EikanWang @jgong5 @wenzhe-nrv

**Comment by westfly** [comment]
I Rewrite the GateEmbedding network as show blew, keeping the shape[0] as -1 to auto reduce the batchsize 

```python
from torch.fx import GraphModule, Tracer
import torch
class GateEmbedding(torch.nn.Module):
    def __init__(self,
                 in_size,
                 out_size,
                 emb_size,
                 act1=torch.nn.ReLU(),
                 act2=torch.nn.Sigmoid(),
                 act3=torch.nn.ReLU()):
        super().__init__()
        self.layer1 = torch.nn.Linear(in_size, out_size)
        self.out_size = out_size
        self.emb_size = emb_size
        self.act2 = act2
        print(f"debug ###{in_size}   {self.out_size}###")

    def forward(self, input):
        gate_out = self.act2(self.layer1(input))
        print(f"debug ###{gate_out.shape}   {self.out_size}###")
        size = gate_out.shape[0]
        print(f"debug ###{gate_out.shape[0]} {type(size)}  {self.out_size}###")
        gate_out_r = torch.reshape(gate_out,
                                   (-1, self.out_size, 1))
        input_r = torch.reshape(input,
                               (-1, self.out_size, self.emb_size))
        gate_out = (gate_out_r * input_r).reshape(-1, self.out_size* self.emb_size)
        # return self.act3(info_out * gate_out)
        return gate_out  # gate_2


my_tracer = Tracer()
print(f"torch version {torch.__version__}")
embedding_model = GateEmbedding(100, 41, 16)
symbolic_traced: torch.fx.Graph = my_tracer.trace(embedding_model)
symbolic_traced.print_tabular()
```
