### ISSUE TITLE
AdaptiveAvgPool1d throws different exceptions when using the gpu

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89343]
### 🐛 Describe the bug

Test on the CPU:

    import torch
    m = torch.nn.AdaptiveAvgPool1d(-2)
    input = torch.rand([1, 64, 8], dtype=torch.float32)
    m(input)

result: RuntimeError: Trying to create tensor with negative dimension -2: [1, 64, 1, -2]

Test on the GPU:

    import torch
    m = torch.nn.AdaptiveAvgPool1d(-2).cuda()
    input = torch.rand([1, 64, 8], dtype=torch.float32).cuda()
    m(input)

result:RuntimeError: setStorage: sizes [1, 64, -2], strides [64, 1, 1], storage offset 0, and itemsize 4 requiring a storage size of 244 are out of bounds for storage of size 0

As we can see, torch.nn.AdaptiveAvgPool1d running the same code on the CPU and GPU throws different exceptions.

### Versions

pytorch: 1.8.0
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.1
GPU models and configuration: RTX3060
Operating System：Windows 

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel

**Comment by zeshengzong** [comment]
Problem already fixed, it's same now.

```python
>>> import torch
>>> m = torch.nn.AdaptiveAvgPool1d(-2)
>>> input = torch.rand([1, 64, 8], dtype=torch.float32)
>>> m(input)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zong/code/pytorch/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zong/code/pytorch/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zong/code/pytorch/torch/nn/modules/pooling.py", line 1427, in forward
    return F.adaptive_avg_pool1d(input, self.output_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: adaptive_avg_pool2d: elements of output_size must be greater than or equal to 0 but received {1, -2}
>>> import torch
>>> m = torch.nn.AdaptiveAvgPool1d(-2).cuda()
>>> input = torch.rand([1, 64, 8], dtype=torch.float32).cuda()
>>> m(input)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zong/code/pytorch/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zong/code/pytorch/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zong/code/pytorch/torch/nn/modules/pooling.py", line 1427, in forward
    return F.adaptive_avg_pool1d(input, self.output_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: adaptive_avg_pool2d: elements of output_size must be greater than or equal to 0 but received {1, -2}

```
