### ISSUE TITLE
cat with channels-last memory layout is incorrect on MPS

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#89353]
### 🐛 Describe the bug

Added a new sample input for channels last in https://github.com/pytorch/pytorch/pull/89332 and MPS started failing https://github.com/pytorch/pytorch/actions/runs/3504224099/jobs/5869876607

```
2022-11-19T16:36:42.9229520Z ======================================================================
2022-11-19T16:36:42.9229620Z FAIL [0.061s]: test_output_match_cat_cpu_int32 (__main__.TestConsistencyCPU)
2022-11-19T16:36:42.9229740Z ----------------------------------------------------------------------
2022-11-19T16:36:42.9229800Z Traceback (most recent call last):
2022-11-19T16:36:42.9230030Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3504224099/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
2022-11-19T16:36:42.9230100Z     result = test(self, **param_kwargs)
2022-11-19T16:36:42.9230320Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3504224099/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 828, in test_wrapper
2022-11-19T16:36:42.9230380Z     return test(*args, **kwargs)
2022-11-19T16:36:42.9230540Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/test_mps.py", line 7900, in test_output_match
2022-11-19T16:36:42.9230580Z     raise e
2022-11-19T16:36:42.9230730Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/test_mps.py", line 7896, in test_output_match
2022-11-19T16:36:42.9230820Z     self.assertEqual(cpu_out, mps_out, atol=atol, rtol=rtol)
2022-11-19T16:36:42.9231030Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3504224099/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2561, in assertEqual
2022-11-19T16:36:42.9231140Z     assert_equal(
2022-11-19T16:36:42.9231350Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3504224099/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1118, in assert_equal
2022-11-19T16:36:42.9231410Z     raise error_metas[0].to_error(msg)
2022-11-19T16:36:42.9231500Z AssertionError: Tensor-likes are not equal!
2022-11-19T16:36:42.9231510Z 
2022-11-19T16:36:42.9231560Z Mismatched elements: 15 / 16 (93.8%)
2022-11-19T16:36:42.9231640Z Greatest absolute difference: 16 at index (1, 0, 0, 0)
2022-11-19T16:36:42.9231720Z Greatest relative difference: inf at index (0, 0, 1, 1)
```

I'm going to xfail the test for now.

### Versions

master

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
Grabbed for myself.

**Comment by razarmehr** [comment]
Hi @qqaatw . This issue is already fixed, and will be upstreamed to pytorch-master soon.
https://github.com/kulinseth/pytorch/pull/212
