### ISSUE TITLE
[MPS] Using unsqueeze in inference mode returns anomalous result

### ISSUE THREAD

**Issue by kaeru-shigure** [pytorch/pytorch#89407]
### 🐛 Describe the bug

Using unsqueeze in inference mode returns anomalous result.
..It may looks no problem, but it will negatively affect later processing.

```python
@torch.inference_mode() # required
def cake():
    mps = torch.device("mps")
    a = torch.arange(5, device = mps)
    test_idx = 1 # 1..*
    assert torch.equal(
        a[test_idx].unsqueeze(0),
        a[test_idx].cpu().unsqueeze(0).to(mps)
    )
cake()
```

```
Traceback (most recent call last):
  File "/test.py", line 17, in <module>
    cake()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/test.py", line 13, in cake
    assert torch.equal(
AssertionError
```

### Versions

```
PyTorch version: 1.14.0.dev20221119
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.6 (main, Oct  7 2022, 15:17:36) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.6-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.14.0.dev20221119
[pip3] torchvision==0.15.0.dev20221119
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] torch                     1.14.0.dev20221119          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221119          pypi_0    pypi
```

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by jhavukainen** [comment]
Issue no longer reproduces in `torch==2.5.1`. Closing as completed as it looks like this has been fixed somewhere along the way.
