### ISSUE TITLE
pickle fails on sparse CSC/BSR/BSC tensors

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#89497]
## Issue description

As in the title.

## Code example

```python
>>> import torch
>>> import pickle
>>> d = pickle.dumps(torch.tensor([[1, 2], [3, 4]]).to_sparse_csc())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/torch/_tensor.py", line 212, in __reduce_ex__
    return self._reduce_ex_internal(proto)
  File "/path/to/torch/_tensor.py", line 351, in _reduce_ex_internal
    self.data_ptr() == 0
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
>>> d = pickle.dumps(torch.tensor([[1, 2], [3, 4]]).to_sparse_bsr(1, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/torch/_tensor.py", line 212, in __reduce_ex__
    return self._reduce_ex_internal(proto)
  File "/path/to/torch/_tensor.py", line 351, in _reduce_ex_internal
    self.data_ptr() == 0
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
>>> d = pickle.dumps(torch.tensor([[1, 2], [3, 4]]).to_sparse_bsc(1, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/torch/_tensor.py", line 212, in __reduce_ex__
    return self._reduce_ex_internal(proto)
  File "/path/to/torch/_tensor.py", line 351, in _reduce_ex_internal
    self.data_ptr() == 0
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
```

pickle works on the CSR tensors:
```python
>>> d = pickle.dumps(torch.tensor([[1, 2], [3, 4]]).to_sparse_csr())
```

## System Info

- PyTorch version: main branch

cc @nikitaved @cpuhrsch @amjames @bhosmer

**Comment by cpuhrsch** [comment]
Fix might be an extension of https://github.com/pytorch/pytorch/pull/71963 . @pearu can you take this on?
