### ISSUE TITLE
`torch.nn.functional.embedding_bag` Trigger "IOT instruction" Failure

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#89677]
### 🐛 Describe the bug

A test for `torch.nn.functional.embedding_bag` triggers "IOT instruction (core dumpd)" error.
### Test
```python
import torch

self = torch.tensor([2, 4, 8, 8, 7, 3, 1, 8, 7, 8, 1, 1, 0, 0, 3, 1, 0, 2, 1, 5, 8, 7, 9, 7, 0, 0, 7, 6, 5, 5, 9, 1, 6, 2, 9, 1, 4, 3, 2, 3, 1, 1, 0, 6, 3, 9, 3, 9, 6, 6, 9, 2, 8, 5, 7])
weight = torch.rand([100, 5], dtype=torch.float32)
offsets = torch.tensor([0,  6, 12, 15, 25, 32, 40, 42, 46, 53, 53])

res = torch.nn.functional.embedding_bag(
    self, weight, offsets,
    norm_type = 2.0,
    scale_grad_by_freq = False,
    mode = 'mean',
    sparse = True,
    include_last_offset = True,
    padding_idx = 61
)
```
### Error Log
(The error message is non-deterministic, sometimes it also reports `free(): invalid next size (normal)` 
```
double free or corruption (!prev)
[1]    260353 IOT instruction (core dumped)
```

### Versions

```
PyTorch version: 1.14.0a0+gitbdc9911
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 11.1.0-6
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.14.0a0+gitbdc9911
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] torch                     1.14.0a0+gitce2f870          pypi_0    pypi
```

cc @ezyang @gchanan @zou3519

**Comment by Kristoff-starling** [comment]
Some relevant issues are #85213 #88463 #88950.

**Comment by ZailiWang** [comment]
Hi, would you plz share the hardware information?

**Comment by Kristoff-starling** [comment]
Hi @ZailiWang ,
```
# uname -a
Linux 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
I'm not sure what kind of hardware information you want. Is that OK?

**Comment by Kristoff-starling** [comment]
It seems that the code doesn't crash immediately when `embedding_bag()` is invoked, the crash happens when the program terminates.
```python
import torch

self = torch.tensor([2, 4, 8, 8, 7, 3, 1, 8, 7, 8, 1, 1, 0, 0, 3, 1, 0, 2, 1, 5, 8, 7, 9, 7, 0, 0, 7, 6, 5, 5, 9, 1, 6, 2, 9, 1, 4, 3, 2, 3, 1, 1, 0, 6, 3, 9, 3, 9, 6, 6, 9, 2, 8, 5, 7])
weight = torch.rand([100, 5], dtype=torch.float32)
offsets = torch.tensor([0,  6, 12, 15, 25, 32, 40, 42, 46, 53, 53])

res = torch.nn.functional.embedding_bag(
    self, weight, offsets,
    norm_type = 2.0,
    scale_grad_by_freq = False,
    mode = 'mean',
    sparse = True,
    include_last_offset = True,
    padding_idx = 61
)
print('still alive')
```
This program will successfully print `still alive` and crash at last. However, if `embedding_bag()` wasn't called, there's no error.

**Comment by Kristoff-starling** [comment]
Hi @albanD,
I don't think it's fixed by #85433 because this pull request adds dimension check in `EmbeddingBag.cpp` and `EmbeddingBag.cu` but the test here has valid input tensor dimensions according to the doc.
Actually, `torch.nn.functional.embedding_bag` has already have dimension checks and the test passes those checks.

**Comment by kshitij12345** [comment]
Interestingly, it doesn't fail if all inputs live on CUDA. 

@Kristoff-starling  On a quick-glance, all the arguments look valid. Is there anything I missed (which is invalid argument)? 

Thanks!

**Comment by kshitij12345** [comment]
From the back-trace, it seems that we are trying to deallocate an already freed Tensor.

```
double free or corruption (!prev)

Thread 1 "python" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350481728) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350481728) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737350481728) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737350481728, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7cc8476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7cae7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7d0f6f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7e61b8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff7d26d7c in malloc_printerr (str=str@entry=0x7ffff7e647d0 "double free or corruption (!prev)") at ./malloc/malloc.c:5664
#7  0x00007ffff7d28efc in _int_free (av=0x7ffff7e9fc80 <main_arena>, p=0x555559e0d8b0, have_lock=<optimized out>) at ./malloc/malloc.c:4591
#8  0x00007ffff7d2b4d3 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#9  0x00007fffc20c3766 in c10::StorageImpl::~StorageImpl() ()
   from /home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#10 0x00007fffea79d1fa in c10::TensorImpl::~TensorImpl() () from /home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/lib/libc10.so
#11 0x00007fffc23dfc78 in THPVariable_clear(THPVariable*) ()
   from /home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#12 0x00007fffc23dffd6 in THPVariable_subclass_dealloc(_object*) ()
   from /home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#13 0x00005555556705c1 in _Py_Dealloc (op=<optimized out>) at /usr/local/src/conda/python-3.9.13/Objects/object.c:2209
#14 _Py_DECREF (op=<optimized out>) at /usr/local/src/conda/python-3.9.13/Include/object.h:430
#15 _Py_XDECREF (op=<optimized out>) at /usr/local/src/conda/python-3.9.13/Include/object.h:497
#16 insertdict (mp=<optimized out>, key=0x7ffff77c0f30, hash=<optimized out>, value=<optimized out>) at /usr/local/src/conda/python-3.9.13/Objects/dictobject.c:1123
#17 0x00005555556fda47 in _PyModule_ClearDict (d=0x7ffff78d3300) at /usr/local/src/conda/python-3.9.13/Objects/moduleobject.c:612
#18 0x000055555576a131 in _PyImport_Cleanup (tstate=0x55555590ff80) at /usr/local/src/conda/python-3.9.13/Python/import.c:609
#19 0x0000555555769306 in Py_FinalizeEx () at /usr/local/src/conda/python-3.9.13/Python/pylifecycle.c:1429
--Type <RET> for more, q to quit, c to continue without paging--
#20 0x000055555575c682 in Py_RunMain () at /usr/local/src/conda/python-3.9.13/Modules/main.c:683
#21 0x000055555572f059 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at /usr/local/src/conda/python-3.9.13/Modules/main.c:1101
#22 0x00007ffff7cafd90 in __libc_start_call_main (main=main@entry=0x55555572f010 <main>, argc=argc@entry=2, argv=argv@entry=0x7fffffffb988)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#23 0x00007ffff7cafe40 in __libc_start_main_impl (main=0x55555572f010 <main>, argc=2, argv=0x7fffffffb988, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffb978) at ../csu/libc-start.c:392
#24 0x000055555572ef61 in _start ()
```

**Comment by kshitij12345** [comment]
@Kristoff-starling Ah, I see. Thank you very much for the references!

**Comment by mingfeima** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/90358, detailed explanation has been added in the PR comment.

@Kristoff-starling I have verified this #90358 fixed this issue, could you please double check ?

**Comment by Kristoff-starling** [comment]
Hi @mingfeima , I also think that the PR should have fixed the issue. Thanks for the fix!

**Comment by mingfeima** [comment]
close this one as https://github.com/pytorch/pytorch/pull/90358 being merged.
