### ISSUE TITLE
[JIT] Variables in for loop need to escape to the outer scope

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#8972]
test case failes:

```
======================================================================
ERROR: test_script_for_in_range_scope (__main__.TestScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_jit.py", line 1663, in test_script_for_in_range_scope
    @torch.jit.script
  File "/Users/wanchaol/pytorch/torch/jit/__init__.py", line 371, in script
    graph = _script_graph(fn, _frames_up=_frames_up + 1)
  File "/Users/wanchaol/pytorch/torch/jit/__init__.py", line 367, in _script_graph
    return _jit_script_compile(ast, rcb)
RuntimeError:
undefined value output:
@torch.jit.script
def test_script_for_in_range_scope():
    for i in range(1):
        output = FIXME_zerol()
    for i in range(2):
        output1 = output + 1
                 ~~~~~~ <--- HERE
    return output1

```

I think we should fix it and let the mutated vars escape to the outer scope as it matches with the python syntax.

**Comment by wanchaol** [comment]
@zdevito do you have any ideas on how this could be fixed?

**Comment by wanchaol** [comment]
Chatted in person, in the case of for loop not executed at all, we don't want to vars inside to escape to the outer scope as we are statically generating things, so we close it and treat this case not a valid syntax of our subset of python.
