### ISSUE TITLE
torch.jit.trace raises RuntimeError when torch.nn.functional.affine_grid is in the graph

### ISSUE THREAD

**Issue by nlgranger** [pytorch/pytorch#8978]
## Issue description

`torch.jit.trace` fails when `torch.nn.functional.affine_grid` exists in the graph, producing the following error:

```
Traceback (most recent call last):
  File "/home/granger/dev/retrynet/draft/scratch.py", line 58, in <module>
    torch.jit.trace(torch.rand(16, 1, 64, 64))(net)
  File "/home/granger/dev/retrynet/venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 305, in wrapper
    module._create_method_from_trace('forward', func, args)
  File "/home/granger/dev/retrynet/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/granger/dev/retrynet/draft/scratch.py", line 42, in forward
    grid = F.affine_grid(theta, x.size())
  File "/home/granger/dev/retrynet/venv/lib/python3.6/site-packages/torch/nn/functional.py", line 1921, in affine_grid
    return vision.affine_grid_generator(theta, size)
  File "/home/granger/dev/retrynet/venv/lib/python3.6/site-packages/torch/nn/_functions/vision.py", line 32, in affine_grid_generator
    return AffineGridGenerator.apply(theta, size)
  File "/home/granger/dev/retrynet/venv/lib/python3.6/site-packages/torch/nn/_functions/vision.py", line 115, in forward
    grid = torch.bmm(base_grid.view(N, H * W, 3), theta.transpose(1, 2))
RuntimeError: torch/csrc/autograd/generated/VariableType.cpp:27570: transpose: Assertion `jit::tracer::ArgumentStash::empty()` failed.
```

I think to remember plotting a graph with a spatial transformer network in the past so it might be regression.

## Code example

This sample code is very close to the pytorch turorial on Spatial Transformer Networks:

```python
import torch
import torch.nn as nn
import torch.nn.functional as F


class Localizer(nn.Module):
    def __init__(self):
        super(Localizer, self).__init__()

        self.conv1 = nn.Conv2d(1, 8, kernel_size=5, bias=False)
        self.conv2 = nn.Conv2d(8, 16, kernel_size=5, bias=False)
        self.fc1 = nn.Linear(8 * 8 * 16, 32)
        self.fc2 = nn.Linear(32, 2 * 3)

        nn.init.normal_(self.fc1.weight, 0, 1e-5)
        self.fc2.bias.data.copy_(torch.tensor([1., 0., 0., 0., 1., 0.]))

    def forward(self, x):
        x = self.conv1(x)
        x = F.max_pool2d(x, 3)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.max_pool2d(x, 2)
        x = F.relu(x)
        x = x.view(-1, 8 * 8 * 16)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        return x.view(-1, 2, 3)


class STN(nn.Module):
    def __init__(self, localizer):
        super(STN, self).__init__()

        self.localizer = localizer

    def forward(self, x):
        theta = self.localizer(x)
        theta = theta.view(-1, 2, 3)

        grid = F.affine_grid(theta, x.size())
        x = F.grid_sample(x, grid)

        return x


# OK
net = Localizer()
torch.jit.trace(torch.rand(16, 1, 64, 64))(net)

# OK
net = STN(Localizer())
output = net(torch.rand(16, 1, 64, 64))
print(output.shape)

# KO
torch.jit.trace(torch.rand(16, 1, 64, 64))(net)
# torch.onnx.export(net, torch.rand(16, 1, 64, 64), "mymodel", export_params=True)
```

## System Info

```
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Arch Linux
GCC version: (GCC) 8.1.1 20180531
CMake version: version 3.11.4

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.14.5)
[pip3] torch (0.4.0)
[conda] Could not collect
```

The error was observed on `0.5.0a0+e62c3a4` as well.

**Comment by ezyang** [comment]
Flagging @jamesr66a @zou3519

**Comment by kwon-young** [comment]
Hello,
Are there any update on this?
Weirdly, I can reproduce this error using pytorch 0.4.1 but not pytorch 0.4.0 (all of this is tested in anaconda env).
I am willing to spend some time debugging this issue if someone can explain to me how.

**Comment by soumith** [comment]
we dont support this functionality in 0.4.0 and 0.4.1.
Please try PyTorch 1.0 preview build from https://pytorch.org and see if that fixes it.
Reopen issue if that doesn't fix it.

**Comment by kwon-young** [comment]
Thank you @soumith for your fast reply!
I can confirm that using PyTorch 1.0 preview build doesn't raise the RuntimeError anymore.
However, trying to export the model using onnx doesn't work:
```
torch.Size([16, 1, 64, 64])
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/utils.py:501: UserWarning: ONNX export failed on ATen operator grid_sampler because torch.onnx.symbolic.grid_sampler does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "test.py", line 59, in <module>
    torch.onnx.export(net, torch.rand(16, 1, 64, 64), "mymodel", export_params=True)
  File "/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/utils.py", line 287, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export Python operator AffineGridGenerator

Defined at:
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/_functions/vision.py(14): affine_grid_generator
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py(2348): affine_grid
test.py(42): forward
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py(467): _slow_forward
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py(477): __call__
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/jit/__init__.py(225): forward
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py(479): __call__
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/jit/__init__.py(172): get_trace_graph
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/utils.py(192): _trace_and_get_graph_from_model
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/utils.py(224): _model_to_graph
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/utils.py(281): _export
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/utils.py(104): export
/home/kyc/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/__init__.py(27): export
test.py(59): <module>


Graph we tried to export:
graph(%x : Float(16, 1, 64, 64)
      %1 : Float(8, 1, 5, 5)
      %2 : Float(16, 8, 5, 5)
      %3 : Float(32, 1024)
      %4 : Float(32)
      %5 : Float(6, 32)
      %6 : Float(6)) {
  %7 : Float(16, 8, 60, 60) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[0, 0, 0, 0], strides=[1, 1]](%x, %1), scope: STN/Localizer[localizer]/Conv2d[conv1]
  %8 : Float(16, 8, 20, 20) = onnx::MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[3, 3]](%7), scope: STN/Localizer[localizer]
  %9 : Float(16, 8, 20, 20) = onnx::Relu(%8), scope: STN/Localizer[localizer]
  %10 : Float(16, 16, 16, 16) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[0, 0, 0, 0], strides=[1, 1]](%9, %2), scope: STN/Localizer[localizer]/Conv2d[conv2]
  %11 : Float(16, 16, 8, 8) = onnx::MaxPool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%10), scope: STN/Localizer[localizer]
  %12 : Float(16, 16, 8, 8) = onnx::Relu(%11), scope: STN/Localizer[localizer]
  %13 : Dynamic = onnx::Constant[value=   -1  1024 [ CPULongType{2} ]](), scope: STN/Localizer[localizer]
  %14 : Float(16, 1024) = onnx::Reshape(%12, %13), scope: STN/Localizer[localizer]
  %15 : Float(16, 32) = onnx::Gemm[alpha=1, beta=1, transB=1](%14, %3, %4), scope: STN/Localizer[localizer]/Linear[fc1]
  %16 : Float(16, 32) = onnx::Relu(%15), scope: STN/Localizer[localizer]
  %17 : Float(16, 6) = onnx::Gemm[alpha=1, beta=1, transB=1](%16, %5, %6), scope: STN/Localizer[localizer]/Linear[fc2]
  %18 : Dynamic = onnx::Constant[value=-1  2  3 [ CPULongType{3} ]](), scope: STN/Localizer[localizer]
  %19 : Float(16, 2, 3) = onnx::Reshape(%17, %18), scope: STN/Localizer[localizer]
  %20 : Dynamic = onnx::Constant[value=-1  2  3 [ CPULongType{3} ]](), scope: STN
  %21 : Float(16, 2, 3) = onnx::Reshape(%19, %20), scope: STN
  %grid : Float(16, 64, 64, 2) = ^AffineGridGenerator((tensor(16), tensor(1), tensor(64), tensor(64)))(%21), scope: STN
  %23 : Long() = onnx::Constant[value={0}](), scope: STN
  %24 : Long() = onnx::Constant[value={0}](), scope: STN
  %25 : Float(16, 1, 64, 64) = aten::grid_sampler(%x, %grid, %23, %24), scope: STN
  return (%25);
}
```
It seems that it is because the grid_sampler is not a supported operator.
Will this operator be implemented eventually?

**Comment by soumith** [comment]
cc: @houseroad on if AffineGridGenerator will be supported in ONNX

**Comment by wjbKimberly** [comment]
The same problem.

**Comment by luvwinnie** [comment]
does the F.affine_grid is going to support in ONNX?
