### ISSUE TITLE
Batching rule for prelu does not handle case when input is 1-D or scalar and weight is non-scalar

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#89895]
### 🐛 Describe the bug

The test cases are newly added in https://github.com/pytorch/pytorch/pull/89809

```
======================================================================
ERROR: test_vmap_exhaustive_nn_functional_prelu_cpu_float32 (__main__.TestVmapOperatorsOpInfoCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/pytorch4/torch/testing/_internal/common_device_type.py", line 391, in instantiated_test
    raise rte
  File "/local/pytorch4/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    result = test(self, **param_kwargs)
  File "/local/pytorch4/torch/testing/_internal/common_device_type.py", line 828, in test_wrapper
    return test(*args, **kwargs)
  File "/local/pytorch4/torch/testing/_internal/common_cuda.py", line 159, in wrapped
    return f(*args, **kwargs)
  File "/local/pytorch4/test/functorch/test_vmap.py", line 3303, in test_vmap_exhaustive
    self.opinfo_vmap_test(device, dtype, op, check_has_batch_rule=False,
  File "/local/pytorch4/test/functorch/test_vmap.py", line 3193, in opinfo_vmap_test
    test()
  File "/local/pytorch4/test/functorch/test_vmap.py", line 3182, in test
    self.vmap_outplace_test(func, args, kwargs, in_dims, check_shape_only, postprocess_fn)
  File "/local/pytorch4/test/functorch/test_vmap.py", line 3129, in vmap_outplace_test
    for loop_out, vmap_out in compute_quantities_for_vmap_test(func, args, kwargs, in_dims):
  File "/local/pytorch4/test/functorch/common_utils.py", line 283, in compute_quantities_for_vmap_test
    for quantities in _compute_quantities_for_vmap_test(op, orig_batched_args, orig_kwarg_values, in_dims,
  File "/local/pytorch4/test/functorch/common_utils.py", line 253, in _compute_quantities_for_vmap_test
    batched_out = vmap(op, in_dims=in_dims, out_dims=out_dim)(*batched_args, **kwarg_values)
  File "/local/pytorch4/functorch/_src/vmap.py", line 362, in wrapped
    return _flat_vmap(
  File "/local/pytorch4/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
  File "/local/pytorch4/functorch/_src/vmap.py", line 489, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
RuntimeError: Not allow zero-dim input tensor.
```

### Versions

main

cc @zou3519 @Chillee @samdow @soumith

**Comment by zou3519** [comment]
cc @samdow  (IIRC you wrote the original)
