### ISSUE TITLE
Error in Adam.step(): If capturable=True, params and state_steps must be CUDA tensors.

### ISSUE THREAD

**Issue by dengnianchen** [pytorch/pytorch#89987]
When the Adam optimizer is initialized by explicitly specifying the `capturable` flag for each parameter group, if the `capturable` flag of some group is different from default/global setting (e.g. the argument `capturable` of Adam's initializer), the error occurs in `Adam.step()`.

Here is a simple test script:

```python
import torch

x = torch.nn.Parameter(torch.empty(1, device="cuda"))
params_groups = [{
    "params": [x],
    "capturable": True
}]
optimizer = torch.optim.Adam(params_groups)
y = x ** 2
optimizer.zero_grad()
y.backward()
optimizer.step()
```

which outputs:

```shell
Traceback (most recent call last):
  File ".../test_adam.py", line 12, in <module>
    optimizer.step()
  File ".../lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File ".../lib/python3.10/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs)
  File ".../lib/python3.10/site-packages/torch/optim/adam.py", line 234, in step
    adam(params_with_grad,
  File ".../lib/python3.10/site-packages/torch/optim/adam.py", line 300, in adam
    func(params,
  File ".../lib/python3.10/site-packages/torch/optim/adam.py", line 348, in _single_tensor_adam
    assert param.is_cuda and step_t.is_cuda, "If capturable=True, params and state_steps must be CUDA tensors."
AssertionError: If capturable=True, params and state_steps must be CUDA tensors.
```

PyTorch version: 1.13.0

-----------------------------------------

I traced the script of Adam and found that the device of state_steps for each parameter is determined by default `capturable` and `fused` settings:

https://github.com/pytorch/pytorch/blob/0e7918b9317d0a481c3747264b3584c37dc4a28f/torch/optim/adam.py#L212-L216

In `_single_tensor_adam()`, it will check the device of state_steps against the `capturable` setting of the corresponding parameter group:

https://github.com/pytorch/pytorch/blob/0e7918b9317d0a481c3747264b3584c37dc4a28f/torch/optim/adam.py#L347-L348

which is called by `step()` as:

https://github.com/pytorch/pytorch/blob/0e7918b9317d0a481c3747264b3584c37dc4a28f/torch/optim/adam.py#L234-L252

It seems that the inconsistency causes the error.

A simple solution is changing the L212-L216 of adam.py to determine the device by group's `capturable` and `fused` settings, but I'm not sure it's logically correct and will not cause other side effects:

```python
 state['step'] = ( 
     torch.zeros((1,), dtype=torch.float, device=p.device) 
     if group['capturable'] or group['fused'] 
     else torch.tensor(0.) 
 ) 
```

cc @vincentqb @jbschlosser @albanD @janeyx99

**Comment by albanD** [comment]
Thanks for raising this issue, the code indeed assumes that all the groups have the same value as the default for that argument.
We should at least have a nice assert that this is the case or, better, update the code to allow multiple groups to have different values for these arguments.

**Comment by janeyx99** [comment]
Yep thanks!
