### ISSUE TITLE
torch._dynamo.exc.BackendCompilerFailed: compile_fx raised TypeError: tqdm.__init__() got an unexpected keyword argument 'desc'

### ISSUE THREAD

**Issue by kevmo314** [pytorch/pytorch#90126]
### 🐛 Describe the bug

Clean python 3.10.5 virtualenv:

```sh
pip3 install numpy --pre torch[dynamo] --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cu117
```

Then code:

```
import torch
import torch._dynamo as dynamo

@dynamo.optimize("inductor")
def opt_foo2(x, y):
    a = torch.sin(x)
    b = torch.cos(x)
    return a + b
print(opt_foo2(torch.randn(10, 10), torch.randn(10, 10)))
```

Results in:

```
Traceback (most recent call last):
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 546, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 911, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 398, in compile_fx
    return aot_autograd(
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/optimizations/training.py", line 80, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 2093, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 1792, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_tensor_args, aot_config)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 1163, in aot_wrapper_dedupe
    fw_metadata, _out, _num_aliasing_metadata_outs = run_functionalized_fw_and_collect_metadata(
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 272, in inner
    outs = f(*f_args)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 2065, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/fx/interpreter.py", line 123, in run
    for node in tqdm(self.module.graph.nodes,
TypeError: tqdm.__init__() got an unexpected keyword argument 'desc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kevin/fedtorch/plugin/example.py", line 9, in <module>
    print(opt_foo2(torch.randn(10, 10), torch.randn(10, 10)))
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 329, in catch_errors
    return callback(frame, cache_size)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 468, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 102, in _fn
    return fn(*args, **kwargs)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 395, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 382, in transform
    tracer.run()
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1625, in run
    super().run()
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 484, in run
    and self.step()
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 454, in step
    getattr(self, inst.opname)(inst)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1687, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 440, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 511, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/kevin/.pyenv/versions/plugin/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 551, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: compile_fx raised TypeError: tqdm.__init__() got an unexpected keyword argument 'desc'

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Versions

PyTorch version: 1.14.0.dev20221202+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.5 (main, Sep 21 2022, 20:11:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.74.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070 SUPER
Nvidia driver version: 526.98
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.0rc1
[pip3] torch==1.14.0.dev20221202+cu117
[pip3] torchaudio==0.14.0.dev20221203+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221203+cpu

**Comment by kevmo314** [comment]
Apparently it's missing tqdm and the stubbed version in torch.hub is missing the corresponding arguments: https://github.com/pytorch/pytorch/blob/master/torch/hub.py#L25

`pip3 install tqdm` solves the issue, but it seems like the stub should add `**kwargs`.
