### ISSUE TITLE
p.block != nullptr && p.block->ptr != nullptr INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by cainiaoqiuzhu** [pytorch/pytorch#90138]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "main.py", line 141, in <module>
    output = model(train_img)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/timm/models/efficientnet.py", line 557, in forward
    x = self.forward_features(x)
  File "/opt/conda/lib/python3.7/site-packages/timm/models/efficientnet.py", line 545, in forward_features
    x = self.blocks(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/timm/models/efficientnet_blocks.py", line 185, in forward
    x = self.se(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/timm/models/efficientnet_blocks.py", line 56, in forward
    return x * self.gate(x_se)

RuntimeError: p.block != nullptr && p.block->ptr != nullptr INTERNAL ASSERT FAILED at "/pytorch/c10/cuda/CUDACachingAllocator.cpp":689, please report a bug to PyTorch.

### Versions

pytorch1.8+cu11

**Comment by jbschlosser** [comment]
Hey @cainiaoqiuzhu, thanks for the report! If possible, can you please include a small example to reproduce the problem? That will help us root out the issue here. Thanks!
