### ISSUE TITLE
[Dynamo]  torch._dynamo.exc.BackendCompilerFailed: _compile_fn raised RuntimeError: `ptxas`

### ISSUE THREAD

**Issue by jacekplocharczyk** [pytorch/pytorch#90136]
### 🐛 Describe the bug

Hi folks I started playing with PyTorch 2.0 on my RTX3090 and I cannot run even simple example:
```python
import torch
from torchvision import models

DEVICE = torch.device("cuda:0")


model = models.resnet18(weights=None)
model = model.to(DEVICE)

dummy_input = torch.rand([256, 3, 224, 244], device=DEVICE)

#works
model(dummy_input)

#fails
model_compiled = torch.compile(model)
model_compiled(dummy_input)
```

I get the following backtrace:
```
(tmp-py3.9) jacek@jacek-Z390-AORUS-PRO-WIFI:~/projects/external/distillation_test/tmp$ python distillation/main.py 
/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py:361: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled.Consider setting `torch.set_float32_matmul_precision('high')`
  warnings.warn(
/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/storage.py:315: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.
  warnings.warn(message, UserWarning)
/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/storage.py:315: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.
  warnings.warn(message, UserWarning)
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 490, in _worker_compile
    kernel.precompile(warm_cache_only_with_cc=cc)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 58, in precompile
    self.launchers = [
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 59, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 73, in _precompile_config
    triton.compile(
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/triton/compiler.py", line 1256, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/triton/compiler.py", line 901, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: `ptxas` was searched in TRITON_PTXAS_PATH, /usr/local/cuda/bin/ or PATH but a working version could not be found.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 546, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 911, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/__init__.py", line 1177, in _compile_fn
    return compile_fn(model_, inputs_)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 398, in compile_fx
    return aot_autograd(
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/optimizations/training.py", line 80, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 2093, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 1792, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_tensor_args, aot_config)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 1197, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/functorch/_src/aot_autograd.py", line 1416, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, flat_args_with_views_handled)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 373, in fw_compiler
    return inner_compile(
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 494, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/debug.py", line 177, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 140, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/graph.py", line 501, in compile_to_fn
    return self.compile_to_module().call
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/graph.py", line 491, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 461, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_jacek/lw/clwkivnqxfvpgxymz3yehwm6bhqr2d62wmccmaufxanxmrbd3y7p.py", line 1761, in <module>
    async_compile.wait(globals())
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 659, in wait
    scope[key] = result.result()
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 514, in result
    self.future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
RuntimeError: `ptxas` was searched in TRITON_PTXAS_PATH, /usr/local/cuda/bin/ or PATH but a working version could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jacek/projects/external/distillation_test/tmp/distillation/main.py", line 30, in <module>
    model_compiled(dummy_input)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 80, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 329, in catch_errors
    return callback(frame, cache_size)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 468, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 102, in _fn
    return fn(*args, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 395, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 382, in transform
    tracer.run()
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1625, in run
    super().run()
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 484, in run
    and self.step()
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 454, in step
    getattr(self, inst.opname)(inst)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1687, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 440, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 511, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/jacek/.cache/pypoetry/virtualenvs/tmp-pPLYjDRO-py3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 551, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: _compile_fn raised RuntimeError: `ptxas` was searched in TRITON_PTXAS_PATH, /usr/local/cuda/bin/ or PATH but a working version could not be found.

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```

packages installed:
```
Package            Version
------------------ ------------------------
certifi            2022.9.24
charset-normalizer 2.1.1
cmake              3.25.0
filelock           3.8.0
idna               3.4
Jinja2             3.1.2
loguru             0.6.0
MarkupSafe         2.1.1
mpmath             1.2.1
networkx           3.0rc1
numpy              1.24.0rc1
Pillow             9.3.0
pip                22.2.2
requests           2.28.1
setuptools         65.3.0
sympy              1.11.1
torch              1.14.0.dev20221202+cu117
torchaudio         0.14.0.dev20221203+cu117
torchtriton        2.0.0+0d7e753227
torchvision        0.15.0.dev20221203+cpu
tqdm               4.64.1
typing_extensions  4.4.0
urllib3            1.26.13
wheel              0.37.1
```

nvidia-smi
```
Sun Dec  4 13:21:19 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 33%   30C    P8    27W / 350W |     99MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1597      G   /usr/lib/xorg/Xorg                 86MiB |
|    0   N/A  N/A      1884      G   /usr/bin/gnome-shell               10MiB |
+-----------------------------------------------------------------------------+
```

Any help welcome :)

And thanks for great framework!

### Versions

```
Collecting environment information...
PyTorch version: 1.14.0.dev20221202+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 515.86.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.0rc1
[pip3] torch==1.14.0.dev20221202+cu117
[pip3] torchaudio==0.14.0.dev20221203+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221203+cpu
[conda] Could not collect
```

cc @ezyang @soumith @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by jacekplocharczyk** [comment]
I wasn't able to run my code in it unfortunately. I will pass until official release.

Thanks!
