### ISSUE TITLE
Unable to export CFlow model to ONNX

### ISSUE THREAD

**Issue by Tekno-H** [pytorch/pytorch#90169]
### 🐛 Describe the bug

 
I am trying to export the [Cflow-ad](https://github.com/gudovskiy/cflow-ad) model to onnx format.
This model has an Encoder-Decoder architecture.
The Encoder is a feature extractor network (like Resnet18, MoblinetV3 etc..) that takes an image as an input, while the decoder  **loops** over the intermediate feature vectors of the encoder and does some specific "positional encoding" on the layers.
In the source code, the **decoder** is a list of decoders. 
In addition, there is no "Cflow model" class in the source code, therefore I wrote a simple Cflow module class to help export the model, as follows:

```
class CFlow(torch.nn.Module):

    def __init__(self, c):
        super(CFlow, self).__init__()
        L = c.pool_layers
        self.encoder, self.pool_layers, self.pool_dims = load_encoder_arch(c, L)
        self.encoder = self.encoder.to(c.device).eval()
        self.decoders = [load_decoder_arch(c, pool_dim) for pool_dim in self.pool_dims]
        self.decoders = [decoder.to(c.device) for decoder in self.decoders]
        params = list(self.decoders[0].parameters())
        for l in range(1, L):
            params += list(self.decoders[l].parameters())
        # optimizer
        self.optimizer = torch.optim.Adam(params, lr=c.lr)
        self.N=256

    def forward(self, x):
        P = c.condition_vec
        #print(self.decoders)
        self.decoders = [decoder.eval() for decoder in self.decoders]
        height = list()
        width = list()
        i=0
        test_dist = [list() for layer in self.pool_layers]
        test_loss = 0.0
        test_count = 0
        start = time.time()
        _ = self.encoder(x)
        with torch.no_grad():
            for l, layer in enumerate(self.pool_layers):
                e = activation[layer]  # BxCxHxW
                #
                B, C, H, W = e.size()
                S = H * W
                E = B * S
                #
                if i == 0:  # get stats
                    height.append(H)
                    width.append(W)
                #
                p = positionalencoding2d(P, H, W).to(c.device).unsqueeze(0).repeat(B, 1, 1, 1)
                c_r = p.reshape(B, P, S).transpose(1, 2).reshape(E, P)  # BHWxP
                e_r = e.reshape(B, C, S).transpose(1, 2).reshape(E, C)  # BHWxC

                decoder = self.decoders[l]
                FIB = E // self.N + int(E % self.N > 0)  # number of fiber batches
                for f in range(FIB):
                    if f < (FIB - 1):
                        idx = torch.arange(f * self.N, (f + 1) * self.N)
                    else:
                        idx = torch.arange(f * self.N, E)
                    #
                    c_p = c_r[idx]  # NxP
                    e_p = e_r[idx]  # NxC
                    # m_p = m_r[idx] > 0.5  # Nx1
                    #
                    if 'cflow' in c.dec_arch:
                        z, log_jac_det = decoder(e_p, [c_p, ])
                    else:
                        z, log_jac_det = decoder(e_p)
                    #
                    decoder_log_prob = get_logp(C, z, log_jac_det)
                    log_prob = decoder_log_prob / C  # likelihood per dim
                    loss = -log_theta(log_prob)
                    test_loss += t2np(loss.sum())
                    test_count += len(loss)
                    test_dist[l] = test_dist[l] + log_prob.detach().cpu().tolist()
        return height, width, test_dist
```
The argument 'c' is a config variable used to obtain useful parameters.

After the class is defined, I set all the needed parameters as in [main](https://github.com/gudovskiy/cflow-ad/blob/master/main.py).
Then, I added the following code to start the export:
```

model = CFlow(c)
print("Created !!!")
PATH = 'weights/mvtec_mobilenet_v3_large_freia-cflow_pl3_cb8_inp256_run0_Model_2022-11-08-10:50:39.pt'
model=load_weights(model,PATH)
model.eval()
batch_size = 1
x = torch.randn(batch_size, 3, 256, 256).to(c.device)
out=model(x)
```
The load_weights method is as follows:
```
def load_weights(model, filename):

    path = os.path.join(filename)
    state = torch.load(path)
    model.encoder.load_state_dict(state['encoder_state_dict'], strict=False)

    decoders = [decoder.load_state_dict(state, strict=False) for decoder, state in
                zip(model.decoders, state['decoder_state_dict'])]
    print('Loading weights from {}'.format(filename))
    return model
```
Finally:

```
torch.onnx.export(
        model,
        x,
        custom-d.onnx",
        export_params=True,
        verbose=True,
        opset_version=11,
        input_names=["input"],
        output_names=["output"],
    )
```
The code runs successfully, however no model is exported and thousands of lines are printed on the screen, like:
```
 9.5554e-02 -2.4600e-02  7.8328e-02  1.0419e-02
 4.5502e-02  1.4899e-03 -7.2213e-02 -3.1233e-02
 1.0151e-01 -2.4369e-02  5.9177e-03  6.9262e-02
 7.9299e-02 -3.7462e-02  7.7214e-03 -4.8352e-02
 3.6798e-02  6.1700e-02  6.9149e-02  3.8857e-02
 1.8279e-02  2.8520e-02  1.0628e-03 -7.4530e-03
[ torch.cuda.FloatTensor{296,148} ]
```
**What am I doing wrong? How can I export the model correctly?**
Check the full code [here](https://gist.github.com/Tekno-H/e114d6d843b3582f82c4a2a3cea1d46e)
I have been stuck on this problem for a while and can figure out how to solve it, any help is appreciated.
Thanks in advance.

### Versions

```
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1050 Ti
Nvidia driver version: 495.29.05
cuDNN version: Probably one of the following:
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.3
[pip3] torch==1.12.1
[pip3] torchvision==0.13.1
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] torch                     1.12.1                   pypi_0    pypi
[conda] torchvision               0.13.1                   pypi_0    pypi
```

**Comment by Tekno-H** [comment]
@justinchuby @BowenBao 
Sorry for tagging you guys, but could you provide any assistance?
 I have been stuck for nearly a month on this issue, and I am running short on time.
Anything helps. Thanks in advance.

**Comment by justinchuby** [comment]
I suspect some operators were not converted and you saw a graph dump. 

Could you share a single script that we can run for the conversion and all the output you saw?

**Comment by Tekno-H** [comment]
Thanks for the response !
I was able to export the encoder (MobilNetV3_large) alone without errors. 
Therefore, I highly suspect that the decoder is causing the problem.The decoder uses the [FrEIA](https://github.com/vislearn/FrEIA) library which may also be the source of the problem.
So you will have to clone the CFlow directory and run the following [code](https://gist.github.com/Tekno-H/368454cc3278b8b4e65c342142217ec7).
I am sorry for not making it a short script, there are a lot of dependencies

**Comment by Tekno-H** [comment]
@justinchuby @BowenBao were you able to give this issue a look?

**Comment by justinchuby** [comment]
thank for checking in. December tends to be slower, and we may not be able to get to it before Jan realistically.

**Comment by abock** [comment]
cf. https://github.com/onnx/onnx/issues/4691

**Comment by Tekno-H** [comment]
> thank for checking in. December tends to be slower, and we may not be able to get to it before Jan realistically.

I will be waiting patiently, the sooner the better.
Thanks anyhow.

**Comment by justinchuby** [comment]
Could you also share the full output?

**Comment by Tekno-H** [comment]
> Could you also share the full output/error message?

@justinchuby  Here is the problem, there is no actual error message. 
I can only see thousands of lines  printed on the screen (the "graph dump") like :
```
 9.5554e-02 -2.4600e-02  7.8328e-02  1.0419e-02
 4.5502e-02  1.4899e-03 -7.2213e-02 -3.1233e-02
 1.0151e-01 -2.4369e-02  5.9177e-03  6.9262e-02
 7.9299e-02 -3.7462e-02  7.7214e-03 -4.8352e-02
 3.6798e-02  6.1700e-02  6.9149e-02  3.8857e-02
 1.8279e-02  2.8520e-02  1.0628e-03 -7.4530e-03
[ torch.cuda.FloatTensor{296,148} ]
```
And no other message is displayed.
I was able to track the problem by adding print statements to some part of the code, and saving the output of the script in a text file. 
`python3 cflow-onnx-script.py > output.txt `

**Comment by justinchuby** [comment]
Can you paste the graph dump somewhere, maybe in a gist and share?

**Comment by Tekno-H** [comment]
[This](https://gist.github.com/Tekno-H/a989a2d19a100b74d1226977be100dfc#file-graph_dump-txt) is what I could get from the screen.
Since the output is huge, the first part gets truncated.

**Comment by justinchuby** [comment]
Hmm ok. I was hoping that there was more info about the graph, but seems like only the tensor was printed out?

**Comment by Tekno-H** [comment]
> Hmm ok. I was hoping that there was more info about the graph, but seems like only the tensor was printed out by the program?

Yeah, there isn't much useful info....
And it doesn't look like there are other tensors.

Doesn't this info help us in any way?


> 
> Edit: I was able to isolate the error at line [248 in the all_in_one_block.py file](https://github.com/vislearn/FrEIA/blob/14484f1f875d5c4fedb9c4ff9d7eaa3f276bf150/FrEIA/modules/all_in_one_block.py#L248), I am currently trying to understand why it fails there. The "self.subnet" is a simple network made up of Linear layer-> ReLu -> Linear layer. The error occurs when this network is populated in the export method...

**Comment by justinchuby** [comment]
I was hoping to see if we can get any info by just eyeballing the errer - but no 😅

**Comment by Tekno-H** [comment]
> I was hoping to see if we can get any info by just eyeballing the errer - but no sweat_smile

@justinchuby, How should I proceed,in your opinion?

**Comment by justinchuby** [comment]
The team is on vacation. I will follow up after the new year.

**Comment by Tekno-H** [comment]
Hello @justinchuby ,
Happy new year.
Any news for my issue?

**Comment by justinchuby** [comment]
Confirmed errors

pytorch 2.0.0.dev20230104+cpu

```
Traceback (most recent call last):
  File "/home/justinchu/dev/playground/cflow/cflow-ad/cflow_onnx_test.py", line 210, in <module>
    main(c)
  File "/home/justinchu/dev/playground/cflow/cflow-ad/cflow_onnx_test.py", line 196, in main
    torch.onnx.export(
  File "<@beartype(torch.onnx.utils.export) at 0x7f17c2771820>", line 347, in export
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 1533, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "<@beartype(torch.onnx.utils._model_to_graph) at 0x7f17c27805e0>", line 10, in _model_to_graph
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/jit/_trace.py", line 1260, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1469, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/justinchu/dev/playground/cflow/cflow-ad/cflow_onnx_test.py", line 94, in forward
    z, log_jac_det = decoder(
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1469, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/FrEIA/framework/sequence_inn.py", line 106, in forward
    x_or_z, j = self.module_list[i](x_or_z, c=[c[self.conditions[i]]],
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1469, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/FrEIA/modules/all_in_one_block.py", line 248, in forward
    a1 = self.subnet(x1c)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1469, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1469, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
```

**Comment by justinchuby** [comment]
torch.jit.trace is unsuccessful

**Comment by justinchuby** [comment]
@Tekno-H so far we know jit.trace cannot trace your model successfully. Still trying to understand the cause

**Comment by Tekno-H** [comment]
I was able to isolate the error at line [248 in the all_in_one_block.py file](https://github.com/vislearn/FrEIA/blob/14484f1f875d5c4fedb9c4ff9d7eaa3f276bf150/FrEIA/modules/all_in_one_block.py#L248).
I could not understand why it fails there, but I believe it is related to the Freia framework.
The "self.subnet" is a simple [network](https://github.com/gudovskiy/cflow-ad/blob/0d8c20251ec23c827bdd03b2e3bc73f02d2f7449/model.py#L33) made up of Linear layer-> ReLu -> Linear layer. The error occurs when this network is [populated](https://github.com/gudovskiy/cflow-ad/blob/0d8c20251ec23c827bdd03b2e3bc73f02d2f7449/model.py#L51) in the export method...
Maybe some operator is not supported??

**Comment by justinchuby** [comment]
It could be related. You need to make sure all module tensors are Parameters for torch to be able to trace them.

**Comment by Tekno-H** [comment]
Hi @justinchuby,

I have tried converting the input tensor to a nn.Parameter and setting requires_grad to False(also tried True), but the error still persists.
 I have also tried detaching the tensor using the detach() method, but this has not solved the issue. 
Is there anything else I can try to fix this error? I have been struggling with this issue for a while now and am running out of ideas. Any help would be greatly appreciated.

**Comment by thiagocrepaldi** [comment]
I am glad you managed to export the encoder. 

You can also try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
