### ISSUE TITLE
Godel Model fails to compile (python 3.11)

### ISSUE THREAD

**Issue by Titaniumtown** [pytorch/pytorch#90203]
### 🐛 Describe the bug

I was trying out PyTorch 1.14/2.0 and installed the latest nightly build. I then used the new `torch.compile()` method and integrated it into my code like described here: <https://pytorch.org/blog/Accelerating-Hugging-Face-and-TIMM-models/#hugging-face-models>

Here is a small code snip-it that reproduces the error with GODEL (the model I'm working with):
```python
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("microsoft/GODEL-v1_1-large-seq2seq")
model = AutoModelForSeq2SeqLM.from_pretrained("microsoft/GODEL-v1_1-large-seq2seq")

new_model = torch.compile(model)
```

Fails with the error:
```bash
Traceback (most recent call last):
  File "/var/home/riley/test.py", line 7, in <module>
    new_model = torch.compile(model)
                ^^^^^^^^^^^^^^^^^^^^
  File "/var/home/riley/.local/lib/python3.11/site-packages/torch/__init__.py", line 1164, in compile
    import torch._dynamo
  File "/var/home/riley/.local/lib/python3.11/site-packages/torch/_dynamo/__init__.py", line 1, in <module>
    from . import allowed_functions, convert_frame, eval_frame, resume_execution
  File "/var/home/riley/.local/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 16, in <module>
    from .bytecode_analysis import remove_dead_code, remove_pointless_jumps
  File "/var/home/riley/.local/lib/python3.11/site-packages/torch/_dynamo/bytecode_analysis.py", line 8, in <module>
    dis.opmap["JUMP_ABSOLUTE"],
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'JUMP_ABSOLUTE'
```

### Versions
```
Collecting environment information...
PyTorch version: 1.14.0.dev20221205+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Fedora Linux 37 (Container Image) (x86_64)
GCC version: (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
Clang version: 15.0.4 (Fedora 15.0.4-1.fc37)
CMake version: version 3.24.2
Libc version: glibc-2.36

Python version: 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] (64-bit runtime)
Python platform: Linux-6.0.11-300.fc37.x86_64-x86_64-with-glibc2.36
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.0
[pip3] torch==1.14.0.dev20221205+cpu
[conda] Could not collect
```

cc @ezyang @soumith

**Comment by wconstab** [comment]
would you be able to run the minifier and post the results for us?
https://pytorch.org/docs/master/dynamo/troubleshooting.html

if so that helps triage, if not we can still try to repro based on the above. thanks in advance!
(see section "Minifier for any backend" since this looks like a dynamo issue not a backend issue)
set environment variable `TORCHDYNAMO_REPRO_AFTER="dynamo"`

**Comment by anijain2305** [comment]
It could be related to python version. We are not even running the model, the error happens during the import.

Is it possible to open a python prompt and run these commands?

~~~
>>> import dis
>>> dis.opmap["JUMP_FORWARD"]
110
>>> dis.opmap
{'POP_TOP': 1, 'ROT_TWO': 2, 'ROT_THREE': 3, 'DUP_TOP': 4, 'DUP_TOP_TWO': 5, 'ROT_FOUR': 6, 'NOP': 9, 'UNARY_POSITIVE': 10, 'UNARY_NEGATIVE': 11, 'UNARY_NOT': 12, 'UNARY_INVERT': 15, 'BINARY_MATRIX_MULTIPLY': 16, 'INPLACE_MATRIX_MULTIPLY': 17, 'BINARY_POWER': 19, 'BINARY_MULTIPLY': 20, 'BINARY_MODULO': 22, 'BINARY_ADD': 23, 'BINARY_SUBTRACT': 24, 'BINARY_SUBSCR': 25, 'BINARY_FLOOR_DIVIDE': 26, 'BINARY_TRUE_DIVIDE': 27, 'INPLACE_FLOOR_DIVIDE': 28, 'INPLACE_TRUE_DIVIDE': 29, 'RERAISE': 48, 'WITH_EXCEPT_START': 49, 'GET_AITER': 50, 'GET_ANEXT': 51, 'BEFORE_ASYNC_WITH': 52, 'END_ASYNC_FOR': 54, 'INPLACE_ADD': 55, 'INPLACE_SUBTRACT': 56, 'INPLACE_MULTIPLY': 57, 'INPLACE_MODULO': 59, 'STORE_SUBSCR': 60, 'DELETE_SUBSCR': 61, 'BINARY_LSHIFT': 62, 'BINARY_RSHIFT': 63, 'BINARY_AND': 64, 'BINARY_XOR': 65, 'BINARY_OR': 66, 'INPLACE_POWER': 67, 'GET_ITER': 68, 'GET_YIELD_FROM_ITER': 69, 'PRINT_EXPR': 70, 'LOAD_BUILD_CLASS': 71, 'YIELD_FROM': 72, 'GET_AWAITABLE': 73, 'LOAD_ASSERTION_ERROR': 74, 'INPLACE_LSHIFT': 75, 'INPLACE_RSHIFT': 76, 'INPLACE_AND': 77, 'INPLACE_XOR': 78, 'INPLACE_OR': 79, 'LIST_TO_TUPLE': 82, 'RETURN_VALUE': 83, 'IMPORT_STAR': 84, 'SETUP_ANNOTATIONS': 85, 'YIELD_VALUE': 86, 'POP_BLOCK': 87, 'POP_EXCEPT': 89, 'STORE_NAME': 90, 'DELETE_NAME': 91, 'UNPACK_SEQUENCE': 92, 'FOR_ITER': 93, 'UNPACK_EX': 94, 'STORE_ATTR': 95, 'DELETE_ATTR': 96, 'STORE_GLOBAL': 97, 'DELETE_GLOBAL': 98, 'LOAD_CONST': 100, 'LOAD_NAME': 101, 'BUILD_TUPLE': 102, 'BUILD_LIST': 103, 'BUILD_SET': 104, 'BUILD_MAP': 105, 'LOAD_ATTR': 106, 'COMPARE_OP': 107, 'IMPORT_NAME': 108, 'IMPORT_FROM': 109, 'JUMP_FORWARD': 110, 'JUMP_IF_FALSE_OR_POP': 111, 'JUMP_IF_TRUE_OR_POP': 112, 'JUMP_ABSOLUTE': 113, 'POP_JUMP_IF_FALSE': 114, 'POP_JUMP_IF_TRUE': 115, 'LOAD_GLOBAL': 116, 'IS_OP': 117, 'CONTAINS_OP': 118, 'JUMP_IF_NOT_EXC_MATCH': 121, 'SETUP_FINALLY': 122, 'LOAD_FAST': 124, 'STORE_FAST': 125, 'DELETE_FAST': 126, 'RAISE_VARARGS': 130, 'CALL_FUNCTION': 131, 'MAKE_FUNCTION': 132, 'BUILD_SLICE': 133, 'LOAD_CLOSURE': 135, 'LOAD_DEREF': 136, 'STORE_DEREF': 137, 'DELETE_DEREF': 138, 'CALL_FUNCTION_KW': 141, 'CALL_FUNCTION_EX': 142, 'SETUP_WITH': 143, 'LIST_APPEND': 145, 'SET_ADD': 146, 'MAP_ADD': 147, 'LOAD_CLASSDEREF': 148, 'EXTENDED_ARG': 144, 'SETUP_ASYNC_WITH': 154, 'FORMAT_VALUE': 155, 'BUILD_CONST_KEY_MAP': 156, 'BUILD_STRING': 157, 'LOAD_METHOD': 160, 'CALL_METHOD': 161, 'LIST_EXTEND': 162, 'SET_UPDATE': 163, 'DICT_MERGE': 164, 'DICT_UPDATE': 165}
~~~

Otherwise, I will try to build 3.11 python locally and try this out.

**Comment by anijain2305** [comment]
Yes, actually I think this is because many jump-related bytecode ops have been replaced in the Python 3.11 version. This is the relevant snapshot
![image](https://user-images.githubusercontent.com/13822661/205759323-f0cc5ab7-b5d3-4039-9174-00f5108a74a0.png)

Link - https://docs.python.org/3/whatsnew/3.11.html#replaced-opcodes


@williamwen42 This might be a good task to start diving deeper into TorchDynamo bytecode analysis if you are interested.

**Comment by wconstab** [comment]
We don't currently support py 3.11, but we're working on it.  In the time being, please try a supported version if possible (3.8-3.10)

**Comment by Titaniumtown** [comment]
> We don't currently support py 3.11, but we're working on it. In the time being, please try a supported version if possible (3.8-3.10)

Ok, thank you so much!

**Comment by anijain2305** [comment]
Closing this, as this is currently tracked at https://github.com/pytorch/torchdynamo/issues/1960
