### ISSUE TITLE
"dynamo" failed for module with default args in "forward" function

### ISSUE THREAD

**Issue by Francis0103** [pytorch/pytorch#90361]
### 🐛 Describe the bug

A module with default arg in "forward" function called from other module will fail in "dynamo".
```
import torch
import torch._dynamo
from torch import Tensor

class MyInnerModule(torch.nn.Module):
  def __init__(self):
    pass
     
  def forward(self, a:Tensor, b:Tensor = torch.ones((2, 3))):
    c = a + b
    d = c + a
    e = c + b
    f = d + e
    return f

class MyModule(torch.nn.Module):
  def __init__(self):
    super(MyModule, self).__init__()
    self.m = MyInnerModule()

  def forward(self, a:Tensor):
    res = self.m(a)
    return res
 
my_module = MyModule()
my_module = torch._dynamo.optimize("aot_ts")(my_module)

inp = torch.ones((2, 3))
res = my_module(inp)
```

Traceback (most recent call last):
  File "default_arg_dynamo.py", line 31, in <module>
    res = my_module(inp)
  File "pytorch/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "pytorch/torch/_dynamo/eval_frame.py", line 80, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "pytorch/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "pytorch/torch/_dynamo/eval_frame.py", line 329, in catch_errors
    return callback(frame, cache_size)
  File "pytorch/torch/_dynamo/convert_frame.py", line 470, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "pytorch/torch/_dynamo/convert_frame.py", line 102, in _fn
    return fn(*args, **kwargs)
  File "pytorch/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "pytorch/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "pytorch/torch/_dynamo/convert_frame.py", line 395, in _compile
    out_code = transform_code_object(code, transform)
  File "pytorch/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "pytorch/torch/_dynamo/convert_frame.py", line 382, in transform
    tracer.run()
  File "pytorch/torch/_dynamo/symbolic_convert.py", line 1621, in run
    super().run()
  File "pytorch/torch/_dynamo/symbolic_convert.py", line 485, in run
    and self.step()
  File "pytorch/torch/_dynamo/symbolic_convert.py", line 454, in step
    getattr(self, inst.opname)(inst)
  File "pytorch/torch/_dynamo/symbolic_convert.py", line 281, in wrapper
    return inner_fn(self, inst)
  File "pytorch/torch/_dynamo/symbolic_convert.py", line 913, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "pytorch/torch/_dynamo/symbolic_convert.py", line 389, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "pytorch/torch/_dynamo/variables/nn_module.py", line 220, in call_function
    return tx.inline_user_function_return(
  File "pytorch/torch/_dynamo/symbolic_convert.py", line 425, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "pytorch/torch/_dynamo/symbolic_convert.py", line 1693, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "pytorch/torch/_dynamo/symbolic_convert.py", line 1721, in inline_call_
    sub_locals, closure_cells = func.bind_args(parent, args, kwargs)
  File "pytorch/torch/_dynamo/variables/functions.py", line 127, in bind_args
    tuple(map(wrap, fn.__defaults__ or [])),
  File "pytorch/torch/_dynamo/variables/functions.py", line 34, in wrap_bound_arg
    assert isinstance(val, VariableTracker), typestr(val)
AssertionError: Tensor

from user code:
   File "default_arg_dynamo.py", line 24, in forward
    res = self.m(a)

Set torch._dynamo.config.verbose=True for more information

### Versions

Collecting environment information...
PyTorch version: 1.14.0a0+git5654fed
Is debug build: True
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.27

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-132-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 SUPER
Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[pip3] torch==1.14.0a0+git26d1dbc
[pip3] torchaudio==0.14.0a0+c28073c
[pip3] torchvision==0.14.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.20.3           py39hf144106_0  
[conda] numpy-base                1.20.3           py39h74d4b33_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  
[conda] torch                     1.14.0a0+git26d1dbc           dev_0    <develop>
[conda] torchaudio                0.14.0a0+c28073c           dev_0    <develop>
[conda] torchvision               0.14.0                   pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by wconstab** [comment]
Thanks for providing the minimal repro!

There is missing support in dynamo for a tensor provided as a default arg to a function [here](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/functions.py#L33).  It might be trivial to add a case here - @voznesenskym @anijain2305 do you know if there is a reason not to?  Otherwise I can put up a PR.

**Comment by ezyang** [comment]
We should add this support in dynamo. However, faithfully replicating Python default semantics will be somewhat involved, because we need to use the SAME tensor across all invocations (i.e., this is not a fresh allocation, this is actually a variable access to preexisting constant tensor.)
