### ISSUE TITLE
[JIT] INTERNAL ASSERT FAILED when dispatching for `torch.Tensor.view`

### ISSUE THREAD

**Issue by ganler** [pytorch/pytorch#90365]
### 🐛 Describe the bug

```python
import torch

def fn(x):
    return torch.Tensor.view(x, torch.int32)

traced = torch.jit.trace(fn, (torch.zeros((1,), dtype=torch.int32),))

"""
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    traced = torch.jit.trace(fn, (torch.zeros((1,), dtype=torch.int32),))
  File "/miniconda3/lib/python3.9/site-packages/torch/jit/_trace.py", line 856, in trace
    traced = torch._C._create_function_from_trace(
RuntimeError: 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":608, please report a bug to PyTorch. We don't have an op for aten::view but it isn't a special case.  Argument types: Tensor, int, 

Candidates:
        aten::view(Tensor(a) self, SymInt[] size) -> Tensor(a)
        aten::view.dtype(Tensor(a) self, ScalarType dtype) -> Tensor(a)
"""
```

`Tensor.view(dtype=...)` is listed to be supported by PyTorch JIT (see [here](https://pytorch.org/docs/stable/jit_builtin_functions.html#supported-tensor-methods)) and in dispatching it shows the candidate `aten::view.dtype`. However, it is not found so it seems to be a dispatching bug?

### Versions

```python
"""
Collecting environment information...
PyTorch version: 1.14.0.dev20221202+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.3
[pip3] onnx2torch==1.5.3
[pip3] torch==1.14.0.dev20221202+cu117
[pip3] torchaudio==0.14.0.dev20221203+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221203+cpu
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] onnx2torch                1.5.3                    pypi_0    pypi
[conda] torch                     1.14.0.dev20221202+cu117          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20221203+cu117          pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221203+cpu          pypi_0    pypi
"""
```

**Comment by davidberard98** [comment]
Likely due to https://github.com/pytorch/pytorch/issues/47964

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
