### ISSUE TITLE
Pytorch 2 error on provided docker but not on pip installation 

### ISSUE THREAD

**Issue by engharat** [pytorch/pytorch#90377]
## Issue description
I get an error on the model.forward(input) line  if I use a .compile model on the provided docker image: ghcr.io/pytorch/pytorch-nightly:latest
 Removing the .compile line makes the code working again. However, the very same code with .compile line works fine on a pytorch 2.0 pip installation; it fails only on the official docker image.
The 'output = model.forward(input)' line which throws the error refers to a simple resnet18 model 
'model = models.resnet18(pretrained=True)' 

## Error output:
```
root@1ab044f39dea:/workspace# python MultiImgTrain2.py --train_path CWT_train --test_path CWT_test --bs_train 256 --bs_test 1024
/opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /opt/conda/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 488, in _worker_compile
    kernel.precompile(warm_cache_only_with_cc=cc)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 59, in precompile
    self.launchers = [
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 60, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 74, in _precompile_config
    triton.compile(
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 1239, in compile
    so = _build(fn.__name__, src_path, tmpdir)
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 1169, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/opt/conda/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/conda/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/conda/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/lib/python3.10/subprocess.py", line 1722, in _execute_child
    and os.path.dirname(executable)
  File "/opt/conda/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 584, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 915, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/__init__.py", line 1177, in _compile_fn
    return compile_fn(model_, inputs_)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 394, in compile_fx
    return aot_autograd(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/optimizations/training.py", line 80, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2093, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1792, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_tensor_args, aot_config)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1197, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1416, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, flat_args_with_views_handled)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 369, in fw_compiler
    return inner_compile(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 494, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/debug.py", line 177, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 136, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 500, in compile_to_fn
    return self.compile_to_module().call
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 490, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 459, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_root/zg/czghpom6cfixrqvfpmhdywd2gkyfsbft3xetwhub2dznbfkkqb3e.py", line 1724, in <module>
    async_compile.wait(globals())
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 642, in wait
    scope[key] = result.result()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 512, in result
    self.future.result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/MultiImgTrain2.py", line 216, in <module>
    train_model(model,train_loader)
  File "/workspace/MultiImgTrain2.py", line 131, in train_model
    output = model.forward(input)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 80, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 329, in catch_errors
    return callback(frame, cache_size)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 468, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 102, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 395, in _compile
    out_code = transform_code_object(code, transform)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 382, in transform
    tracer.run()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1620, in run
    super().run()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 484, in run
    and self.step()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 453, in step
    getattr(self, inst.opname)(inst)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1682, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 439, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 510, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 589, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: _compile_fn raised TypeError: expected str, bytes or os.PathLike object, not NoneType


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

munmap_chunk(): invalid pointer
Aborted (core dumped)
```

cc @ezyang @gchanan @zou3519 @seemethere @malfet @soumith

**Comment by wconstab** [comment]
@malfet do you know if anything went wrong with matching torchvision version included in docker images recent nightlies?

@engharat it would help if you can provide the model code (MultiImgTrain2.py) so we can try to run it ourselves.  Also, can you confirm the torch.__version__ and torchvision.__version__ you're using in your docker?  (as well as the docker hash?)

**Comment by ngimel** [comment]
The stack trace doesn't look model-specific, so neither exact model, nor torchvision version should matter, looks like some paths are not created or dependencies not found during triton compilation in docker environment, should be reproducible on any model independent of torchvision.

**Comment by engharat** [comment]
I confirm the error happens for any training in my docker setup, even the easiest example of pytorch tutorial cifar10 training.
 I suppose torchvision has not been installed correctly? those are the torch packages:
torch==1.14.0.dev20221206
torchdata==0.6.0.dev20221206
torchelastic==0.2.2
torchtext==0.15.0.dev20221206
torchtriton==2.0.0+0d7e753227
torchvision @ file:///croot/torchvision_1670313549871/work
The docker image sha256 is: sha256:813bd0432c6849150d926a7dac9d3dcffd2e8c9fc7950960a6375a08af7dfd75

The following is the pip freeze output I get inside the docker container. 
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
astunparse==1.6.3
attrs==22.1.0
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
beautifulsoup4 @ file:///opt/conda/conda-bld/beautifulsoup4_1650462163268/work
brotlipy==0.7.0
certifi @ file:///croot/certifi_1665076670883/work/certifi
cffi @ file:///tmp/abs_98z5h56wf8/croots/recipe/cffi_1659598650955/work
chardet @ file:///home/builder/ci_310/chardet_1640804867535/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
cmake==3.25.0
conda==22.11.0
conda-build==3.23.2
conda-package-handling @ file:///croot/conda-package-handling_1666940373510/work
contourpy==1.0.6
cryptography @ file:///croot/cryptography_1665612644927/work
cycler==0.11.0
Cython==0.29.32
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
dnspython==2.2.1
exceptiongroup==1.0.4
executing @ file:///opt/conda/conda-bld/executing_1646925071911/work
expecttest==0.1.4
filelock @ file:///opt/conda/conda-bld/filelock_1647002191454/work
flit_core @ file:///opt/conda/conda-bld/flit-core_1644941570762/work/source/flit_core
fontools==0.5.0
fonttools==4.38.0
future==0.18.2
glob2 @ file:///home/linux1/recipes/ci/glob2_1610991677669/work
gmpy2 @ file:///tmp/build/80754af9/gmpy2_1645455533097/work
greenlet==2.0.1
hypothesis==6.60.0
idna @ file:///croot/idna_1666125576474/work
imageio==2.22.4
ipython @ file:///croot/ipython_1668088122043/work
jedi @ file:///tmp/build/80754af9/jedi_1644315229345/work
Jinja2 @ file:///tmp/build/80754af9/jinja2_1612213139570/work
joblib==1.2.0
kiwisolver==1.4.4
libarchive-c @ file:///tmp/build/80754af9/python-libarchive-c_1617780486945/work
llvmlite==0.39.1
lxml==4.9.1
MarkupSafe @ file:///home/builder/ci_310/markupsafe_1640791577099/work
matplotlib==3.6.2
matplotlib-inline @ file:///opt/conda/conda-bld/matplotlib-inline_1662014470464/work
mkl-fft==1.3.1
mkl-random @ file:///home/builder/ci_310/mkl_random_1641843545607/work
mkl-service==2.4.0
mpmath==1.2.1
networkx==2.8.8
numba==0.56.4
numpy @ file:///opt/conda/conda-bld/numpy_and_numpy_base_1652801679809/work
obspy==1.4.0
opencv-python==4.6.0.66
packaging==21.3
pandas==1.5.2
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==9.2.0
pkginfo @ file:///croot/pkginfo_1666725041340/work
pluggy @ file:///tmp/build/80754af9/pluggy_1648024709248/work
portalocker @ file:///home/builder/ci_310/portalocker_1640806825655/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1633440160888/work
psutil @ file:///opt/conda/conda-bld/psutil_1656431268089/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
pycosat @ file:///croot/pycosat_1666805502580/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyfaidx==0.7.1
pyfnutils==1.3
Pygments @ file:///opt/conda/conda-bld/pygments_1644249106324/work
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyparsing==3.0.9
PySocks @ file:///home/builder/ci_310/pysocks_1640793678128/work
python-dateutil==2.8.2
python-etcd==0.4.5
pytz @ file:///opt/conda/conda-bld/pytz_1654762638606/work
PyWavelets==1.4.1
PyYAML==6.0
requests @ file:///opt/conda/conda-bld/requests_1657734628632/work
ruamel.yaml @ file:///opt/conda/conda-bld/ruamel.yaml_1664988522112/work
ruamel.yaml.clib @ file:///croot/ruamel.yaml.clib_1666302247304/work
scikit-image==0.19.3
scikit-learn==1.1.3
scipy==1.9.3
six @ file:///tmp/build/80754af9/six_1644875935023/work
sortedcontainers==2.4.0
soupsieve @ file:///croot/soupsieve_1666296392845/work
SQLAlchemy==1.4.44
ssqueezepy==0.6.3
stack-data @ file:///opt/conda/conda-bld/stack_data_1646927590127/work
sympy @ file:///croot/sympy_1668202399572/work
threadpoolctl==3.1.0
tifffile==2022.10.10
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
toolz @ file:///croot/toolz_1667464077321/work
torch==1.14.0.dev20221206
torchdata==0.6.0.dev20221206
torchelastic==0.2.2
torchtext==0.15.0.dev20221206
torchtriton==2.0.0+0d7e753227
torchvision @ file:///croot/torchvision_1670313549871/work
tqdm @ file:///opt/conda/conda-bld/tqdm_1664392687731/work
traitlets @ file:///tmp/build/80754af9/traitlets_1636710298902/work
triton==2.0.0
types-dataclasses==0.6.6
typing_extensions @ file:///croot/typing_extensions_1669924550328/work
urllib3 @ file:///croot/urllib3_1666298941550/work
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
zstandard==0.19.0

**Comment by malfet** [comment]
Grabbing for myself, will see what is going on

**Comment by malfet** [comment]
> torchvision @ file:///croot/torchvision_1670313549871/work

Well, this seems to indicate that torchvision has been built locally rather than one grabbed from docker. And if one wants to develop, then `-devel` image needs to be installed (though indeed, torchtriton package right now lacks ptxas)

**Comment by malfet** [comment]
And with `gcc` installed it fails as `cuda.h` is not found:
```
/tmp/tmpv1qfkl_e/main.c:2:10: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
          ^~~~~~~~
compilation terminated.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 488, in _worker_compile
    kernel.precompile(warm_cache_only_with_cc=cc)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 59, in precompile
    self.launchers = [
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 60, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 74, in _precompile_config
```

**Comment by malfet** [comment]
Ok, validated that it works with docker pull ghcr.io/pytorch/pytorch-nightly:2bd3fbe-cu11.6.2 (which is `:latest` at the time of writing)
