### ISSUE TITLE
PyTorch 2.0: AssertionError fake_mode is not None (possibly because of einops.rearrange)

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/pytorch#90375]
### 🐛 Describe the bug

When training my model with `model = torch.compile(model)`, I obtained the following errors:

```bash
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 584, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/optimizations/distributed.py", line 143, in compile_fn
    assert fake_mode is not None
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/code/ViT/main_pretrain.py", line 227, in <module>
    main(opts)
  File "/home/user/code/ViT/main_pretrain.py", line 156, in main
    train_stats = train_one_epoch(args,
  File "/home/user/code/ViT/engine_pretrain.py", line 94, in train_one_epoch
    loss, acc = model(samples, samples, len_keep)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1098, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1051, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 80, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/user/code/ViT/models/ViT.py", line 349, in forward
    features, mask = self.forward_features(inputs, len_keep)
  File "/home/user/code/ViT/models/ViT.py", line 288, in forward_features
    x = rearrange(x, 'b h w d -> b (h w) d')
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 326, in catch_errors
    return hijacked_callback(frame, cache_size)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 468, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 102, in _fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 395, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 382, in transform
    tracer.run()
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1620, in run
    super().run()
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 484, in run
    and self.step()
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 453, in step
    getattr(self, inst.opname)(inst)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 307, in wrapper
    self.output.compile_subgraph(self, reason=reason)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 463, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 510, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 589, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: compile_fn raised AssertionError: 
```

The traceback seems to indicate that the problem lies at `einops.rearrange`. I guess this is not covered by PT2 yet?

### Versions

Nightly of December 7th.

cc @ezyang @gchanan @zou3519 @soumith

**Comment by wconstab** [comment]
@netw0rkf10w would you be able to paste a runnable script that lets us repro the error you're seeing?  If possible, just run the minifier on your original fail case and it will produce a standalone script for us.

**Comment by netw0rkf10w** [comment]
@wconstab Sure. Could you tell me how to run the minifier? Sorry I couldn't find the information anywhere.

**Comment by ezyang** [comment]
cc @voznesenskym

**Comment by ezyang** [comment]
mmm I have a guess for what's going on, let me try to cook up a hotpatch

**Comment by ezyang** [comment]
try this patch

```
diff --git a/torch/_dynamo/optimizations/distributed.py b/torch/_dynamo/optimizations/distributed.py  
index 934a9abc67..f48ba500be 100644
--- a/torch/_dynamo/optimizations/distributed.py
+++ b/torch/_dynamo/optimizations/distributed.py
@@ -140,7 +140,8 @@ class DDPOptimizer:
         and returns its callable.
         """
         fake_mode = fake_mode_from_tensors(example_inputs)
-        assert fake_mode is not None
+        if fake_mode is None:
+            fake_mode = torch._subclasses.fake_tensor.FakeTensorMode()
 
         # 1: compute the partition map according to DDP bucket logic
         buckets = [Bucket()]  # (size, param_names)
```

**Comment by netw0rkf10w** [comment]
> https://pytorch.org/docs/master/dynamo/troubleshooting.html has instructions for the minifier.
> 
> I missed that you're running distributed. It might be hard to run the minifier with more than 1 process. Can you repro with single process (still using DDP but only single device), or does that case pass?
> 
> You could try `TORCHDYNAMO_REPRO_AFTER="dynamo"` in this case.
> 
> I'll also look into that assert that's failing more generally
> 
> ```
> File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/optimizations/distributed.py", line 143, in compile_fn
>     assert fake_mode is not None
> ``` (cc @voznesenskym)
> ```

Thanks, @wconstab! Sorry I was not available at the time to do the requested minification, I was planning to do it a bit later but then @ezyang was too quick to fix the issue 💯 

@ezyang Just a quick question please: After applying the patch, I guess I'll have to build PyTorch from source? If that's the case then maybe I should wait for the new nightly to be released tomorrow instead, because I'm not familiar with building the library from source so that would take a lot of time.

**Comment by ezyang** [comment]
no, it's python only. just apply the patch into your site-packages, or wait for the next nightly.

**Comment by netw0rkf10w** [comment]
@ezyang But of course!! Not sure why I overlooked that. Thanks!

**Comment by netw0rkf10w** [comment]
FYI I still have issues with `torch.compile` and posted as a separate thread here: https://github.com/pytorch/pytorch/issues/90550

@ezyang I have another question please. Does applying your patch simply silent the complaints from `torch.compile` while compromising performance? I mean, `rearrange` no longer gives an error, but should I replace it with `torch.reshape` for better performance of `torch.compile` or it doesn't' make a difference? Thanks.

**Comment by ezyang** [comment]
This patch will not degrade perf, use it to your hearts content lol

**Comment by netw0rkf10w** [comment]
@wconstab @ezyang Unfortunately I still obtained errors with `random_masking`:

```bash
Traceback (most recent call last):
  File "/home/user/code/ViT/main_pretrain.py", line 227, in <module>
    main(opts)
  File "/home/user/code/ViT/main_pretrain.py", line 156, in main
    train_stats = train_one_epoch(args,
  File "/home/user/code/ViT/engine_pretrain.py", line 94, in train_one_epoch
    loss, acc = model(samples, samples, len_keep)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1098, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1051, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 80, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/user/code/ViT/models/ViT.py", line 349, in forward
    features, mask = self.forward_features(inputs, len_keep)
  File "/home/user/code/ViT/models/ViT.py", line 293, in forward_features
    mask, _ = self.random_masking(x, len_keep)
  File "/home/user/code/ViT/models/ViT.py", line 295, in <graph break in forward_features>
    x[mask] = self.mask_token.to(x.dtype)
RuntimeError: Output 0 of CompiledFunctionBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can fix this by cloning the output of the custom Function.
```

Please note that the code works without any warnings if I disable `torch.compile`.

The minifier doesn't seem to help this this case:

```python

import os
from math import inf
import torch
from torch import tensor, device
import torch.fx as fx
import functools
import torch._dynamo
from torch._dynamo.debug_utils import run_fwd_maybe_bwd
from torch._dynamo.optimizations.backends import BACKENDS
from torch._dynamo.testing import rand_strided

# REPLACEABLE COMMENT FOR TESTING PURPOSES

args = [((384, 14, 14), (196, 14, 1), torch.int64, 'cuda', False)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.self_patch_embed_proj = Linear(in_features=32, out_features=768, bias=True).cuda()
        self.self_patch_embed_weight = torch.nn.Parameter(torch.randn([8192, 32], dtype=torch.float32)).cuda()



    def forward(self, x : torch.Tensor):
        self_patch_embed_weight = self.self_patch_embed_weight
        embedding = torch.nn.functional.embedding(x, self_patch_embed_weight);  x = self_patch_embed_weight = None
        self_patch_embed_proj = self.self_patch_embed_proj(embedding);  embedding = None
        reshape = torch.reshape(self_patch_embed_proj, (384, -1, 768));  self_patch_embed_proj = None
        _set_grad_enabled = torch._C._set_grad_enabled(False)
        _set_grad_enabled_1 = torch._C._set_grad_enabled(True)
        return (reshape,)


mod = Repro()

# Setup debug minifier compiler
torch._dynamo.debug_utils.MINIFIER_SPAWNED = True
compiler_fn = BACKENDS["dynamo_minifier_backend"]
raise RuntimeError(
    'Compiler name is None - this likely means that a custom compiler '
    'was called by torchdynamo. Please remove this error, import your '
    'custom compiler function, and replace the compiler_name="None" '
    'line below to compiler_name=<my_imported_custom_function>'
)

dynamo_minifier_backend = functools.partial(
    compiler_fn,
    compiler_name="None",
)
opt_mod = torch._dynamo.optimize(dynamo_minifier_backend)(mod)

with torch.cuda.amp.autocast(enabled=True):
    opt_mod(*args)
```

**Comment by ezyang** [comment]
@bdhirsh has a patch for you!

**Comment by netw0rkf10w** [comment]
@bdhirsh Is there an ETA please? Thanks.
