### ISSUE TITLE
Cannot pickle 'WeakMethod' object when saving state_dict for CyclicLr

### ISSUE THREAD

**Issue by Etienne66** [pytorch/pytorch#90414]
### 🐛 Describe the bug

When trying to save the CyclicLR state_dict and `scale_fn` is left at the default of `None` it will generate the error `cannot pickle 'WeakMethod' object`

```python
# All necessary imports at the beginning
import torch
from pathlib import Path

model = torch.nn.Sequential(
    torch.nn.Linear(3, 1),
    torch.nn.Flatten(0, 1)
)

kwargs = {'lr':             5.0e-6}
optimizer = torch.optim.AdamW(model.parameters(), **kwargs)

kwargs = {'base_lr':        5.0e-6,
          'max_lr':         2.5e-4,
          'cycle_momentum': False,
          'step_size_up':   100_000,
          'mode':           'exp_range',
          'gamma':          0.99999979673105275299293754990642}
scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, **kwargs)
scheduler_dict = scheduler.state_dict()

torch.save(scheduler_dict , Path('./checkpoint.pt'))
```
Outputs the following error:
```python
Traceback (most recent call last):
  File "E:\workspaces\CDVD-TSP\code\main_PWC-Net.py", line 1322, in <module>
    main()
  File "E:\workspaces\CDVD-TSP\code\main_PWC-Net.py", line 793, in main
    torch.save(model_state_dict, args.save_path / args.run_path / 'checkpoint.pt')
  File "C:\Users\Etienne\miniconda3\lib\site-packages\torch\serialization.py", line 423, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "C:\Users\Etienne\miniconda3\lib\site-packages\torch\serialization.py", line 635, in _save
    pickler.dump(obj)
TypeError: cannot pickle 'WeakMethod' object
```
Printing the dictionary showed 
```python
'_scale_fn_ref': <weakref at 0x000001E46B9E7C10; to 'CyclicLR' at 0x000001E47D9FE1F0>
```

Workaround by adding the following to delete the key
```python
scheduler_dict = scheduler.state_dict()

if '_scale_fn_ref' in scheduler_dict.keys():
    scheduler_dict.pop('_scale_fn_ref')

torch.save(scheduler_dict , Path('./checkpoint.pt'))
```

### Versions

```python
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro for Workstations
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:41:22) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.7.99
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 526.86
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[pip3] torch-lr-finder==0.2.1
[pip3] torchaudio==0.13.0
[pip3] torchvision==0.14.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0              16_win64_mkl    conda-forge
[conda] cudatoolkit               11.7.0              ha6f8bbd_10    conda-forge
[conda] libblas                   3.9.0              16_win64_mkl    conda-forge
[conda] libcblas                  3.9.0              16_win64_mkl    conda-forge
[conda] liblapack                 3.9.0              16_win64_mkl    conda-forge
[conda] liblapacke                3.9.0              16_win64_mkl    conda-forge
[conda] mkl                       2022.1.0           h6a75c08_874    conda-forge
[conda] mkl-devel                 2022.1.0           h57928b3_875    conda-forge
[conda] mkl-include               2022.1.0           h6a75c08_874    conda-forge
[conda] numpy                     1.23.5           py39hbccbffa_0    conda-forge
[conda] pytorch                   1.13.0          py3.9_cuda11.7_cudnn8_0    pytorch
[conda] pytorch-cuda              11.7                 h67b0de4_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-lr-finder           0.2.1                    pypi_0    pypi
[conda] torchaudio                0.13.0                   pypi_0    pypi
[conda] torchvision               0.14.0                   pypi_0    pypi
```

cc @vincentqb @jbschlosser @albanD @janeyx99

**Comment by awaelchli** [comment]
Perhaps the `state_dict()` implementation should just drop this key before returning the dict. Looking at the implementation here
https://github.com/pytorch/pytorch/blob/b8b7480065d9aa78116a59e8e1a0dcb99ecfdda9/torch/optim/lr_scheduler.py#L1223-L1233

it looks like it would be enough to store the `self.mode (str)` and reinstantiate the functions upon loading the state.

**Comment by lminer** [comment]
Any workarounds short of bumping torch down to 1.12?

**Comment by awaelchli** [comment]
You could pop the key from the state dict before saving the checkpoint, like so:

```py
state = lr_scheduler.state_dict()
state.pop("_scale_fn_ref")

torch.save({..., "lr_scheduler": state}, ...)
```
