### ISSUE TITLE
Inductor bug because of aten.clone lowering doesn't support memory_format

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#90454]
### 🐛 Describe the bug

This error comes from [7k github models](https://github.com/pytorch/torchdynamo/issues/1198): https://github.com/jansel/pytorch-jit-paritybench/blob/master/generated/test_ritheshkumar95_pytorch_vqvae.py#L159-L162

The minimized repro:
```
import torch
import torch._dynamo

def fn(x):
    y = x.permute(0, 2, 3, 1).contiguous()
    torch._dynamo.graph_break()
    return y.view(-1, 4)

opt_fn = torch._dynamo.optimize("inductor")(fn)
x = torch.rand([4, 4, 4, 4])
print(opt_fn(x))
```

Error:
```
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 1127, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_subclasses/fake_tensor.py", line 886, in __torch_dispatch__
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_ops.py", line 285, in __call__
    return self._op(*args, **kwargs or {})
  File "/scratch/ybliang/work/repos/pytorch/torch/_refs/__init__.py", line 3923, in view
    return _reshape_view_helper(a, *shape, allow_copy=False)
  File "/scratch/ybliang/work/repos/pytorch/torch/_refs/__init__.py", line 3209, in _reshape_view_helper
    raise ValueError(msg)
ValueError: Cannot view a tensor with shape torch.Size([4, 4, 4, 4]) and strides (64, 4, 1, 16) as a tensor with shape (64, 4)!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 1079, in get_fake_value
    return wrap_fake_exception(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 742, in wrap_fake_exception
    return fn()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 1080, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 1134, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_method view(*(FakeTensor(FakeTensor(..., device='meta', size=(4, 4, 4, 4)), cpu), -1, 4), **{}):
Cannot view a tensor with shape torch.Size([4, 4, 4, 4]) and strides (64, 4, 1, 16) as a tensor with shape (64, 4)!
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/debug/debug5.py", line 16, in <module>
    print(opt_fn(x))
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/debug/debug5.py", line 11, in fn
    torch._dynamo.graph_break()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 476, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 395, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 382, in transform
    tracer.run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1621, in run
    super().run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 485, in run
    and self.step()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 454, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 281, in wrapper
    return inner_fn(self, inst)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 913, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 389, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/misc.py", line 596, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/tensor.py", line 351, in call_method
    return wrap_fx_proxy(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/builder.py", line 713, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/builder.py", line 750, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 1099, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError: 

from user code:
   File "/scratch/ybliang/work/repos/pytorch/debug/debug5.py", line 12, in <graph break in fn>
    return y.view(-1, 4)


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

Root cause:
It passed with eager/aot_eager, only failed on inductor. The reason is inductor ```clone``` lowering doesn't support ```memory_format```. The ```contiguous``` calls will be translated to ```aten.clone```, but need to be cloned as the correct ```memory_format```.

This is the first FX graph passed into inductor backend:
```
opcode         name     target                args                    kwargs
-------------  -------  --------------------  ----------------------  ------------------------------------------
placeholder    arg0_1   arg0_1                ()                      {}
call_function  permute  aten.permute.default  (arg0_1, [0, 2, 3, 1])  {}
call_function  clone    aten.clone.default    (permute,)              {'memory_format': torch.contiguous_format}
output         output   output                ((clone,),)             {}
``` 

### Versions

Linux

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ezyang** [comment]
ya ok. short term need to make the strides line up, long term infallible views will help.

**Comment by gchanan** [comment]
@ezyang should we have a view / infallible view label?

**Comment by ngimel** [comment]
Yeah but if we are lining up strides, I think we should line them up at graph boundary, not at arbitrary ops. Like, it's safe to ignore `contiguous` call inside compiled region, inductor has infallible views, but the output strides should match.

**Comment by ezyang** [comment]
yup
