### ISSUE TITLE
InstanceNorm1d throws an error when last dim is specified with affine=True

### ISSUE THREAD

**Issue by michaelklachko** [pytorch/pytorch#90514]
### 🐛 Describe the bug

InstanceNorm1d complains about weight shape when I specify the last dim of 3d tensor AND affine=True (note the weight shape should be 4 (not 6, and not 8) and is in fact 4 as far as I can see, unless 'weight' refers to something other than instance_norm trainable parameters:

```
>>> import torch
>>> t = torch.randn(2, 3, 4)
>>> inst_norm = torch.nn.InstanceNorm1d(4, affine=True)
>>> inst_norm(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/michael/miniconda3/lib/python3.9/site-packages/torch/nn/modules/instancenorm.py", line 74, in forward
    return self._apply_instance_norm(input)
  File "/home/michael/miniconda3/lib/python3.9/site-packages/torch/nn/modules/instancenorm.py", line 34, in _apply_instance_norm
    return F.instance_norm(
  File "/home/michael/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 2495, in instance_norm
    return torch.instance_norm(
RuntimeError: weight should contain 6 elements not 8

>>> inst_norm.weight
Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)

>>> inst_norm = torch.nn.InstanceNorm1d(3, affine=True)
>>> inst_norm(t)
tensor([[[-0.5667, -1.2763,  1.3406,  0.5024],
         [-1.5963,  0.5561, -0.0282,  1.0684],
         [ 0.4945, -1.4742, -0.2525,  1.2322]],

        [[-0.1902,  1.5557, -0.1300, -1.2355],
         [-0.3809,  0.8082,  1.0334, -1.4607],
         [-1.5426,  0.9422,  0.8257, -0.2252]]], grad_fn=<ViewBackward0>)

>>> inst_norm = torch.nn.InstanceNorm1d(3, affine=False)
>>> inst_norm(t)
tensor([[[-0.5667, -1.2763,  1.3406,  0.5024],
         [-1.5963,  0.5561, -0.0282,  1.0684],
         [ 0.4945, -1.4742, -0.2525,  1.2322]],

        [[-0.1902,  1.5557, -0.1300, -1.2355],
         [-0.3809,  0.8082,  1.0334, -1.4607],
         [-1.5426,  0.9422,  0.8257, -0.2252]]])

>>> inst_norm = torch.nn.InstanceNorm1d(4, affine=False)
>>> inst_norm(t)
tensor([[[-0.5667, -1.2763,  1.3406,  0.5024],
         [-1.5963,  0.5561, -0.0282,  1.0684],
         [ 0.4945, -1.4742, -0.2525,  1.2322]],

        [[-0.1902,  1.5557, -0.1300, -1.2355],
         [-0.3809,  0.8082,  1.0334, -1.4607],
         [-1.5426,  0.9422,  0.8257, -0.2252]]])
```

### Versions

```
$ python collect_env.py
Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchvision==0.14.0
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.5           py39he7a7128_2
[conda] numpy-base                1.21.5           py39hf524024_2
[conda] pytorch                   1.13.0              py3.9_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.13.0                 py39_cpu    pytorch
[conda] torchvision               0.14.0                 py39_cpu    pytorch
```

**Comment by jbschlosser** [comment]
Hey @michaelklachko, thanks for the report! As you've noted, the `num_features` arg to `InstanceNorm1d` is only used for the `affine=True` or `track_running_stats=True` cases. While we could tighten up the error checking outside of these cases, I'm a bit worried about people relying on this lax behavior at the moment (i.e. it could be BC-breaking).

**Comment by michaelklachko** [comment]
@jbschlosser how about a compromise:

1. When affine=True, change the error message from "RuntimeError: weight should contain 6 elements not 8" to something that makes more sense, perhaps: "num_features must be equal to 3".

2. When affine=False, let it run, but display a warning "num_features value specified is ignored, using num_features=3".

In my opinion, a better solution is to remove the dimension argument when instantiating `InstanceNorm1`, because even with the proposed changes above we still have a potential for hidden bugs when (N, C, L) tensor has C == L. 

What do you think?

**Comment by jbschlosser** [comment]
I'm good with tweaking the error message and throwing a warning when `num_features` is passed but unused. We'd accept a PR implementing these changes.
