### ISSUE TITLE
Pytorch 2.0: Detection models from torchvision don't work after compilation with no_grad on first run

### ISSUE THREAD

**Issue by Inkorak** [pytorch/pytorch#90527]
### 🐛 Describe the bug

Testing Pytorch 2.0 compilation for detection models from torchvision. If I run a model with no_grad for the first time, it crashes with an error. But if I launch for the first time without using no_grad, then everything is fine and moreover, subsequent launches can be wrapped again in no_grad.

```
model = retinanet_resnet50_fpn_v2(pretrained=True)
device = torch.device('cuda')

model.to(device).eval()
model = torch.compile(model)
input_data = torch.randn(3, 512, 512)
with torch.no_grad():
    result = model([input_data.to(device)])
```

Error:
```
 warnings.warn(
[2022-12-09 11:50:31,626] torch._inductor.graph: [WARNING] Creating implicit fallback for:
  target: aten.upsample_bilinear2d.default
  args[0]: TensorBox(
    ReinterpretView(
      StorageBox(
        InputBuffer(name='arg0_1', layout=FixedLayout('cuda', torch.float32, size=[3, 512, 512], stride=[262144, 512, 1]))
      ),
      FixedLayout('cuda', torch.float32, size=[1, 3, 512, 512], stride=[786432, 262144, 512, 1]),
      no origins?
    )
  )
  args[1]: [800, 800]
  args[2]: False
[2022-12-09 11:50:31,626] torch._inductor.lowering: [WARNING] make_fallback(aten.upsample_bilinear2d.default): a decomposition exists, we should switch to it
[2022-12-09 11:50:31,638] torch._inductor.ir: [WARNING] Using FallbackKernel: torch.ops.aten.upsample_bilinear2d.default
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/fx/passes/shape_prop.py", line 141, in run_node
    result = super().run_node(n)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/fx/interpreter.py", line 243, in call_function
    return target(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_inductor/overrides.py", line 37, in __torch_function__
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 611, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_ops.py", line 285, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 787, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.add.Tensor(*(tensor([[[  0,   0,   0,   0]],

        [[  8,   0,   8,   0]],

        [[ 16,   0,  16,   0]],

        ...,

        [[776, 792, 776, 792]],

        [[784, 792, 784, 792]],

        [[792, 792, 792, 792]]], device='cuda:0', dtype=torch.int32), FakeTensor(FakeTensor(..., device='meta', size=(1, 9, 4)), cuda:0)), **{})
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/fx/passes/shape_prop.py", line 141, in run_node
    result = super().run_node(n)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/fx/interpreter.py", line 243, in call_function
    return target(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_inductor/overrides.py", line 37, in __torch_function__
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 611, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_ops.py", line 285, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 787, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.add.Tensor(*(tensor([[[  0,   0,   0,   0]],

        [[  8,   0,   8,   0]],

        [[ 16,   0,  16,   0]],

        ...,

        [[776, 792, 776, 792]],

        [[784, 792, 784, 792]],

        [[792, 792, 792, 792]]], device='cuda:0', dtype=torch.int32), FakeTensor(FakeTensor(..., device='meta', size=(1, 9, 4)), cuda:0)), **{})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 586, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 915, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/__init__.py", line 1203, in _compile_fn
    return compile_fn(model_, inputs_)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 360, in compile_fx
    model_ = overrides.fuse_fx(model_, example_inputs_)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_inductor/overrides.py", line 556, in fuse_fx
    ShapeProp(gm, fake_mode=fake_mode).propagate(*example_inputs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/fx/passes/shape_prop.py", line 179, in propagate
    return super().run(*args)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/fx/passes/shape_prop.py", line 146, in run_node
    raise RuntimeError(
RuntimeError: ShapeProp error for: node=%add : [#users=1] = call_function[target=operator.add](args = (%view, %view_1), kwargs = {}) with meta={'stack_trace': 'Module stack: {}\n  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 111, in grid_anchors\n    anchors.append((shifts.view(-1, 1, 4) + base_anchors.view(1, -1, 4)).reshape(-1, 4))\n |   File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 127, in forward\n    anchors_over_all_feature_maps = self.grid_anchors(grid_sizes, strides)\n'}

While executing %add : [#users=1] = call_function[target=operator.add](args = (%view, %view_1), kwargs = {})
Original traceback:
Module stack: {}
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 111, in grid_anchors
    anchors.append((shifts.view(-1, 1, 4) + base_anchors.view(1, -1, 4)).reshape(-1, 4))
 |   File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 127, in forward
    anchors_over_all_feature_maps = self.grid_anchors(grid_sizes, strides)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/pytorch2test/main.py", line 55, in <module>
    print(model([input_data.to(device)]))
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/retinanet.py", line 636, in forward
    anchors = self.anchor_generator(images, features)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 476, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 395, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 382, in transform
    tracer.run()
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1621, in run
    super().run()
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 485, in run
    and self.step()
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 454, in step
    getattr(self, inst.opname)(inst)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1683, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 463, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 510, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 591, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: _compile_fn raised RuntimeError: ShapeProp error for: node=%add : [#users=1] = call_function[target=operator.add](args = (%view, %view_1), kwargs = {}) with meta={'stack_trace': 'Module stack: {}\n  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 111, in grid_anchors\n    anchors.append((shifts.view(-1, 1, 4) + base_anchors.view(1, -1, 4)).reshape(-1, 4))\n |   File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 127, in forward\n    anchors_over_all_feature_maps = self.grid_anchors(grid_sizes, strides)\n'}

While executing %add : [#users=1] = call_function[target=operator.add](args = (%view, %view_1), kwargs = {})
Original traceback:
Module stack: {}
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 111, in grid_anchors
    anchors.append((shifts.view(-1, 1, 4) + base_anchors.view(1, -1, 4)).reshape(-1, 4))
 |   File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 127, in forward
    anchors_over_all_feature_maps = self.grid_anchors(grid_sizes, strides)


Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```

### Versions

PyTorch version: 1.14.0.dev20221208+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.0rc2
[pip3] torch==1.14.0.dev20221208+cu116
[pip3] torch2trt==0.4.0
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221208+cu116
[conda] numpy                     1.24.0rc2                pypi_0    pypi
[conda] torch                     1.14.0.dev20221208+cu116          pypi_0    pypi
[conda] torch2trt                 0.4.0                    pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221208+cu116          pypi_0    pypi

**Comment by bdhirsh** [comment]
It looks like with `no_grad()` is enabled, inductor goes down a different code path that involves running some extra FX passes, including ShapeProp.

The ShapeProp pass doesn't look like it fully works with FakeTensors - looking into a fix.

**Comment by bdhirsh** [comment]
I think this should be fixed by https://github.com/pytorch/pytorch/pull/90556

**Comment by ezyang** [comment]
TBH, Inductor shouldn't be running ShapeProp, IMO.

**Comment by bdhirsh** [comment]
> TBH, Inductor shouldn't be running ShapeProp, IMO.

kinda related to "should aot autograd run by default". We probably wouldn't have to run ShapeProp here if inductor just unconditionally used aot autograd, even when `is_grad_enabled() == False`. Probably worth investigating why inductor isn't just always running aot autograd today.
