### ISSUE TITLE
UBSAN error: downcast of address 0x7ffe0ba79e58 which does not point to an object of type 'torch::jit::Node'

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#9055]
`test_decompose_addmm` in `TestJit` fails with UBSAN:
(error line: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/attributes.h#L198)
```
test_decompose_addmm (__main__.TestJit) ... /var/lib/jenkins/pytorch/torch/csrc/jit/attributes.h:200:12: runtime error: downcast of address 0x7ffe0ba79e58 which does not point to an object of type 'torch::jit::Node'
0x7ffe0ba79e58: note: object has invalid vptr
 00 00 00 00  90 74 74 41 00 10 00 00  f0 a6 2c 00 20 60 00 00  f8 a6 2c 00 20 60 00 00  f8 a6 2c 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x7fdcb3355a3d in torch::jit::Attributes<torch::jit::Node>::This() /var/lib/jenkins/pytorch/torch/csrc/jit/attributes.h:200:12
    #1 0x7fdcb33541a7 in torch::jit::Node* torch::jit::Attributes<torch::jit::Node>::set<torch::jit::ScalarAttributeValue<at::Tensor, (torch::jit::AttributeKind)6> >(torch::jit::Symbol, torch::jit::ScalarAttributeValue<at::Tensor, (torch::jit::AttributeKind)6>::ConstructorType) /var/lib/jenkins/pytorch/torch/csrc/jit/attributes.h:212:12
    #2 0x7fdcb33518aa in torch::jit::Attributes<torch::jit::Node>::t_(torch::jit::Symbol, at::Tensor) /var/lib/jenkins/pytorch/torch/csrc/jit/attributes.h:182:12
    #3 0x7fdcb4886db8 in torch::jit::script::liftConstantAttributes(torch::jit::FunctionSchema const&, torch::jit::Node*) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:358:22
    #4 0x7fdcb4891de7 in torch::jit::script::tryEmitBuiltin(torch::jit::FunctionSchema const&, std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&, torch::jit::script::SourceRange const&, torch::jit::script::Method&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, at::ArrayRef<torch::jit::NamedValue>, at::ArrayRef<torch::jit::NamedValue>) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:586:3
    #5 0x7fdcb488fe70 in torch::jit::script::emitBuiltinCall(torch::jit::script::SourceRange const&, torch::jit::script::Method&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, at::ArrayRef<torch::jit::NamedValue>, at::ArrayRef<torch::jit::NamedValue>, bool) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:620:23
    #6 0x7fdcb4893b6c in torch::jit::script::BuiltinFunction::call(torch::jit::script::SourceRange, torch::jit::script::Method&, at::ArrayRef<torch::jit::NamedValue>, at::ArrayRef<torch::jit::NamedValue>, unsigned long) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:682:10
    #7 0x7fdcb499bdbc in torch::jit::script::to_ir::emitApplyExpr(torch::jit::script::Expr, std::vector<torch::jit::NamedValue, std::allocator<torch::jit::NamedValue> > const&, at::ArrayRef<torch::jit::NamedValue>, unsigned long) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:1275:16
    #8 0x7fdcb497ccb7 in torch::jit::script::to_ir::emitSugaredExpr(torch::jit::script::Expr, unsigned long) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:1483:16
    #9 0x7fdcb4978b95 in torch::jit::script::to_ir::emitAssignment(torch::jit::script::Assign const&) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:1122:19
    #10 0x7fdcb495c18d in torch::jit::script::to_ir::emitStatements(torch::jit::script::ListIterator<torch::jit::script::Stmt>, torch::jit::script::ListIterator<torch::jit::script::Stmt>) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:788:11
    #11 0x7fdcb4957057 in torch::jit::script::to_ir::to_ir(torch::jit::script::Def, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, torch::jit::script::Method&, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, torch::jit::script::Method&> > >&, std::function<std::shared_ptr<torch::jit::script::SugaredValue> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&, std::shared_ptr<torch::jit::script::SugaredValue>, torch::jit::script::Method&) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:726:5
    #12 0x7fdcb489f4cf in torch::jit::script::defineMethodsInModule(torch::jit::script::Module&, std::vector<torch::jit::script::Def, std::allocator<torch::jit::script::Def> > const&, std::vector<std::function<std::shared_ptr<torch::jit::script::SugaredValue> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::allocator<std::function<std::shared_ptr<torch::jit::script::SugaredValue> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> > > const&, std::shared_ptr<torch::jit::script::SugaredValue>)::$_4::operator()(torch::jit::script::Method&) const /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:1737:7
    #13 0x7fdcb489e753 in std::_Function_handler<void (torch::jit::script::Method&), torch::jit::script::defineMethodsInModule(torch::jit::script::Module&, std::vector<torch::jit::script::Def, std::allocator<torch::jit::script::Def> > const&, std::vector<std::function<std::shared_ptr<torch::jit::script::SugaredValue> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::allocator<std::function<std::shared_ptr<torch::jit::script::SugaredValue> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> > > const&, std::shared_ptr<torch::jit::script::SugaredValue>)::$_4>::_M_invoke(std::_Any_data const&, torch::jit::script::Method&) /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:1871:2
    #14 0x7fdcb49e6801 in std::function<void (torch::jit::script::Method&)>::operator()(torch::jit::script::Method&) const /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:2267:14
    #15 0x7fdcb49e3b9b in torch::jit::script::Method::ensure_defined() /var/lib/jenkins/pytorch/torch/csrc/jit/script/module.cpp:58:5
    #16 0x7fdcb489754d in torch::jit::script::defineMethodsInModule(torch::jit::script::Module&, std::vector<torch::jit::script::Def, std::allocator<torch::jit::script::Def> > const&, std::vector<std::function<std::shared_ptr<torch::jit::script::SugaredValue> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::allocator<std::function<std::shared_ptr<torch::jit::script::SugaredValue> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> > > const&, std::shared_ptr<torch::jit::script::SugaredValue>) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:1750:13
    #17 0x7fdcb4898b84 in torch::jit::script::compileFunction(torch::jit::script::Def, std::function<std::shared_ptr<torch::jit::script::SugaredValue> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&) /var/lib/jenkins/pytorch/torch/csrc/jit/script/compiler.cpp:1767:3
    #18 0x7fdcb4a16996 in torch::jit::script::initJitScriptBindings(_object*)::$_15::operator()(torch::jit::script::Def, std::function<pybind11::function (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>) const /var/lib/jenkins/pytorch/torch/csrc/jit/script/init.cpp:474:12
    #19 0x7fdcb4a16637 in std::shared_ptr<torch::jit::Graph> pybind11::detail::argument_loader<torch::jit::script::Def, std::function<pybind11::function (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)> >::call_impl<std::shared_ptr<torch::jit::Graph>, torch::jit::script::initJitScriptBindings(_object*)::$_15&, 0ul, 1ul, pybind11::detail::void_type>(torch::jit::script::initJitScriptBindings(_object*)::$_15&, pybind11::detail::index_sequence<0ul, 1ul>, pybind11::detail::void_type&&) /var/lib/jenkins/pytorch/third_party/pybind11/include/pybind11/cast.h:1866:16
    #20 0x7fdcb4a161a0 in _ZNO8pybind116detail15argument_loaderIJN5torch3jit6script3DefESt8functionIFNS_8functionENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEEE4callISt10shared_ptrINS3_5GraphEENS0_9void_typeERZNS4_21initJitScriptBindingsEP7_objectE4$_15EENSt9enable_ifIXntsr3std7is_voidIT_EE5valueESR_E4typeEOT1_ /var/lib/jenkins/pytorch/third_party/pybind11/include/pybind11/cast.h:1843:42
    #21 0x7fdcb4a15bb8 in void pybind11::cpp_function::initialize<torch::jit::script::initJitScriptBindings(_object*)::$_15, std::shared_ptr<torch::jit::Graph>, torch::jit::script::Def, std::function<pybind11::function (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>, pybind11::name, pybind11::scope, pybind11::sibling>(torch::jit::script::initJitScriptBindings(_object*)::$_15&&, std::shared_ptr<torch::jit::Graph> (*)(torch::jit::script::Def, std::function<pybind11::function (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#1}::operator()(pybind11::detail::function_call&) const /var/lib/jenkins/pytorch/third_party/pybind11/include/pybind11/pybind11.h:155:52
    #22 0x7fdcb4a155ca in void pybind11::cpp_function::initialize<torch::jit::script::initJitScriptBindings(_object*)::$_15, std::shared_ptr<torch::jit::Graph>, torch::jit::script::Def, std::function<pybind11::function (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>, pybind11::name, pybind11::scope, pybind11::sibling>(torch::jit::script::initJitScriptBindings(_object*)::$_15&&, std::shared_ptr<torch::jit::Graph> (*)(torch::jit::script::Def, std::function<pybind11::function (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#1}::__invoke(pybind11::detail::function_call&) /var/lib/jenkins/pytorch/third_party/pybind11/include/pybind11/pybind11.h:132:21
    #23 0x7fdcb2e47482 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) /var/lib/jenkins/pytorch/third_party/pybind11/include/pybind11/pybind11.h:619:30
    #24 0x55adf5410b93 in _PyCFunction_FastCallDict (/opt/conda/bin/python3.6+0x10eb93)
    #25 0x55adf54a067b in call_function (/opt/conda/bin/python3.6+0x19e67b)
    #26 0x55adf54c2cb9 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c0cb9)
    #27 0x55adf5499a93 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x197a93)
    #28 0x55adf549a940 in fast_function (/opt/conda/bin/python3.6+0x198940)
    #29 0x55adf54a0754 in call_function (/opt/conda/bin/python3.6+0x19e754)
    #30 0x55adf54c3a79 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1a79)
    #31 0x55adf5499a93 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x197a93)
    #32 0x55adf549a940 in fast_function (/opt/conda/bin/python3.6+0x198940)
    #33 0x55adf54a0754 in call_function (/opt/conda/bin/python3.6+0x19e754)
    #34 0x55adf54c2cb9 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c0cb9)
    #35 0x55adf549a70a in fast_function (/opt/conda/bin/python3.6+0x19870a)
    #36 0x55adf54a0754 in call_function (/opt/conda/bin/python3.6+0x19e754)
    #37 0x55adf54c2cb9 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c0cb9)
    #38 0x55adf5499a93 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x197a93)
    #39 0x55adf549b03a in _PyFunction_FastCallDict (/opt/conda/bin/python3.6+0x19903a)
    #40 0x55adf5410f5e in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ef5e)
    #41 0x55adf5415a02 in _PyObject_Call_Prepend (/opt/conda/bin/python3.6+0x113a02)
    #42 0x55adf541099d in PyObject_Call (/opt/conda/bin/python3.6+0x10e99d)
    #43 0x55adf54c446f in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c246f)
    #44 0x55adf5499a93 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x197a93)
    #45 0x55adf549ae1a in _PyFunction_FastCallDict (/opt/conda/bin/python3.6+0x198e1a)
    #46 0x55adf5410f5e in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ef5e)
    #47 0x55adf5415a02 in _PyObject_Call_Prepend (/opt/conda/bin/python3.6+0x113a02)
    #48 0x55adf541099d in PyObject_Call (/opt/conda/bin/python3.6+0x10e99d)
    #49 0x55adf546d9b6 in slot_tp_call (/opt/conda/bin/python3.6+0x16b9b6)
    #50 0x55adf5410d7a in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ed7a)
    #51 0x55adf54a07cd in call_function (/opt/conda/bin/python3.6+0x19e7cd)
    #52 0x55adf54c2cb9 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c0cb9)
    #53 0x55adf5499a93 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x197a93)
    #54 0x55adf549b03a in _PyFunction_FastCallDict (/opt/conda/bin/python3.6+0x19903a)
    #55 0x55adf5410f5e in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ef5e)
    #56 0x55adf5415a02 in _PyObject_Call_Prepend (/opt/conda/bin/python3.6+0x113a02)
    #57 0x55adf541099d in PyObject_Call (/opt/conda/bin/python3.6+0x10e99d)
    #58 0x55adf54c446f in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c246f)
    #59 0x55adf5499a93 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x197a93)
    #60 0x55adf549ae1a in _PyFunction_FastCallDict (/opt/conda/bin/python3.6+0x198e1a)
    #61 0x55adf5410f5e in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ef5e)
    #62 0x55adf5415a02 in _PyObject_Call_Prepend (/opt/conda/bin/python3.6+0x113a02)
    #63 0x55adf541099d in PyObject_Call (/opt/conda/bin/python3.6+0x10e99d)
    #64 0x55adf546d9b6 in slot_tp_call (/opt/conda/bin/python3.6+0x16b9b6)
    #65 0x55adf5410d7a in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ed7a)
    #66 0x55adf54a07cd in call_function (/opt/conda/bin/python3.6+0x19e7cd)
    #67 0x55adf54c2cb9 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c0cb9)
    #68 0x55adf5499a93 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x197a93)
    #69 0x55adf549b03a in _PyFunction_FastCallDict (/opt/conda/bin/python3.6+0x19903a)
    #70 0x55adf5410f5e in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ef5e)
    #71 0x55adf5415a02 in _PyObject_Call_Prepend (/opt/conda/bin/python3.6+0x113a02)
    #72 0x55adf541099d in PyObject_Call (/opt/conda/bin/python3.6+0x10e99d)
    #73 0x55adf54c446f in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c246f)
    #74 0x55adf5499a93 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x197a93)
    #75 0x55adf549ae1a in _PyFunction_FastCallDict (/opt/conda/bin/python3.6+0x198e1a)
    #76 0x55adf5410f5e in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ef5e)
    #77 0x55adf5415a02 in _PyObject_Call_Prepend (/opt/conda/bin/python3.6+0x113a02)
    #78 0x55adf541099d in PyObject_Call (/opt/conda/bin/python3.6+0x10e99d)
    #79 0x55adf546d9b6 in slot_tp_call (/opt/conda/bin/python3.6+0x16b9b6)
    #80 0x55adf5410d7a in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ed7a)
    #81 0x55adf54a07cd in call_function (/opt/conda/bin/python3.6+0x19e7cd)
    #82 0x55adf54c2cb9 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c0cb9)
    #83 0x55adf549a70a in fast_function (/opt/conda/bin/python3.6+0x19870a)
    #84 0x55adf54a0754 in call_function (/opt/conda/bin/python3.6+0x19e754)
    #85 0x55adf54c2cb9 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c0cb9)
    #86 0x55adf549a70a in fast_function (/opt/conda/bin/python3.6+0x19870a)
    #87 0x55adf54a0754 in call_function (/opt/conda/bin/python3.6+0x19e754)
    #88 0x55adf54c2cb9 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c0cb9)
    #89 0x55adf5499f20 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x197f20)
    #90 0x55adf549b03a in _PyFunction_FastCallDict (/opt/conda/bin/python3.6+0x19903a)
    #91 0x55adf5410f5e in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ef5e)
    #92 0x55adf5415a02 in _PyObject_Call_Prepend (/opt/conda/bin/python3.6+0x113a02)
    #93 0x55adf541099d in PyObject_Call (/opt/conda/bin/python3.6+0x10e99d)
    #94 0x55adf546d02a in slot_tp_init (/opt/conda/bin/python3.6+0x16b02a)
    #95 0x55adf54a09b6 in type_call (/opt/conda/bin/python3.6+0x19e9b6)
    #96 0x55adf5410d7a in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10ed7a)
    #97 0x55adf549ac29 in _PyObject_FastCallKeywords (/opt/conda/bin/python3.6+0x198c29)
    #98 0x55adf54a07cd in call_function (/opt/conda/bin/python3.6+0x19e7cd)
    #99 0x55adf54c3a79 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1a79)
    #100 0x55adf5441a2a in _PyFunction_FastCall (/opt/conda/bin/python3.6+0x13fa2a)
    #101 0x55adf54a0754 in call_function (/opt/conda/bin/python3.6+0x19e754)
    #102 0x55adf54c2cb9 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c0cb9)
    #103 0x55adf549b458 in PyEval_EvalCodeEx (/opt/conda/bin/python3.6+0x199458)
    #104 0x55adf549c1eb in PyEval_EvalCode (/opt/conda/bin/python3.6+0x19a1eb)
    #105 0x55adf55169a3 in run_mod (/opt/conda/bin/python3.6+0x2149a3)
    #106 0x55adf5516da0 in PyRun_FileExFlags (/opt/conda/bin/python3.6+0x214da0)
    #107 0x55adf5516fa3 in PyRun_SimpleFileExFlags (/opt/conda/bin/python3.6+0x214fa3)
    #108 0x55adf551aa9d in Py_Main (/opt/conda/bin/python3.6+0x218a9d)
    #109 0x55adf53e24bd in main (/opt/conda/bin/python3.6+0xe04bd)
    #110 0x7fdccdfec82f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #111 0x55adf54c9772 in _start (/opt/conda/bin/python3.6+0x1c7772)
```

**Comment by yf225** [comment]
@zdevito Should we just ask UBSAN to ignore it, or is there a better fix for this?

**Comment by zdevito** [comment]
This looks out of date, closing.
