### ISSUE TITLE
Intel MKL ERROR with pytorch 1.10.0

### ISSUE THREAD

**Issue by Daniel-Chin** [pytorch/pytorch#90606]
### 🐛 Describe the bug

When input has `nan`, `torch.linalg.lstsq` throws `RuntimeError` with intel MKL. Ideally the error message should tell you about the `nan`s, but currently it tells you to report a bug to PyTorch. 

Error Output: 
```
Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.
Traceback (most recent call last):
  File "...", line 51, in <module>
    main()
  File "...", line 41, in main
    thread.run()
  File "...", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "...", line 52, in main
    ...
  File "...", line 12, in projectionMSE
    solution, residuals, _, _ = lstsq(X, Y)
RuntimeError: falseINTERNAL ASSERT FAILED at "..\\aten\\src\\ATen/native/LinearAlgebraUtils.h":244, please report a bug to PyTorch. torch.linalg.lstsq: Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
```

### Versions

```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] numpydoc==1.4.0
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py38h2bbff1b_0
[conda] mkl_fft                   1.3.0            py38h277e83a_2
[conda] mkl_random                1.2.1            py38hf11a4ad_2
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.20.1           py38haf7ebc8_0
[conda] numpydoc                  1.4.0            py38haa95532_0
[conda] pytorch                   1.10.0              py3.8_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.10.0                 py38_cpu  [cpuonly]  pytorch
[conda] torchvision               0.11.1                 py38_cpu  [cpuonly]  pytorch
```

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Daniel-Chin** [comment]
Related: #5100

**Comment by lezcano** [comment]
This is expected behaviour. See https://pytorch.org/docs/master/notes/numerical_accuracy.html#non-finite-values

**Comment by Daniel-Chin** [comment]
> This is expected behaviour. See https://pytorch.org/docs/master/notes/numerical_accuracy.html#non-finite-values

I see. You may close this issue if that will be intended.
