### ISSUE TITLE
`torch.inverse` multi-threading RuntimeError: lazy wrapper should be called at most once

### ISSUE THREAD

**Issue by wyli** [pytorch/pytorch#90613]
### 🐛 Describe the bug

`torch.inverse` and the related modules won't work with multi-threading:

```py
import concurrent.futures
import torch

def run_task(req):
    out = torch.inverse(torch.eye(4, device="cuda:0"))
    return req, out


infer_tasks = [1, 2, 3, 4, 5, 6, 7, 8]

with concurrent.futures.ThreadPoolExecutor(4, "BatchTask") as executor:
    futures = {executor.submit(run_task, t) for t in infer_tasks}
    for fut in concurrent.futures.as_completed(futures):
        print("outcome", fut.result())

```

run this script will raise a runtime error:
```
Traceback (most recent call last):
  File "my_test_6.py", line 15, in <module>
    print("outcome", fut.result())
  File "/home/anaconda3/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/anaconda3/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/anaconda3/envs/py38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "my_test.py", line 5, in run_task
    out = torch.inverse(torch.eye(4, device="cuda:0"))
RuntimeError: lazy wrapper should be called at most once
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.4.48
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA TITAN Xp COLLECTORS EDITION
GPU 1: NVIDIA TITAN Xp COLLECTORS EDITION

(monai ref: https://github.com/Project-MONAI/MONAI/issues/5696)

**Comment by lezcano** [comment]
@malfet

**Comment by lezcano** [comment]
As a workaround, you can call any linear algebra function before running the concurrent tasks to initialise the linalg module. For example, adding
```python
torch.inverse(torch.ones((0, 0), device="cuda:0"))
```
after the imports does the trick.

**Comment by wyli** [comment]
> As a workaround, you can call any linear algebra function before running the concurrent tasks to initialise the linalg module. For example, adding
> 
> ```python
> torch.inverse(torch.ones((0, 0), device="cuda:0"))
> ```
> 
> after the imports does the trick.

Thanks, this removes the runtime error (we use a similar logic here https://github.com/Project-MONAI/MONAILabel/pull/1199). But it seems that it'll allocate some 200+MB memory, and is not possible to release them, any idea? because of this we couldn't put it as a generic workaround:

```py
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.memory_reserved(0)
0
>>> x = torch.inverse(torch.ones((0, 0), device="cuda:0"))
>>> del x
>>> torch.cuda.memory_reserved(0)
2097152
```

**Comment by lezcano** [comment]
What's going on here (and what caused this error) is that the `torch.linalg` module, as it's a fairly heavy dependency, it's lazily loaded. I reckon that when loaded, its creating some CUDA context... 
@malfet or @IvanYashchuk may know what's going on here

**Comment by xwang233** [comment]
Cuda 11.7 already provides the lazy loading feature. Is it a good time to remove this weird lazy loading logic of linalg module in pytorch now?

It's already causing problems in "parallel unit testing", which introduces unnecessary cuda synchronizations that reduces the performances in linalg functions. https://github.com/pytorch/pytorch/issues/82894

cc @ptrblck @ngimel @IvanYashchuk

**Comment by lezcano** [comment]
We still support CUDA 11.6, so I don't think we can completely remove that logic, but it'd be good to start moving it to the new CUDA API when available.

About the initialisation, that is only needed when the first call may be performed in a concurrent setting. This is clearly not the most common use case, so the current logic still works as expected for most people.

**Comment by xwang233** [comment]
@lezcano , I agree with you. What I'm complaining here is that the **extra cuda synchronizations** introduce regressions, which is not the most common use case and unnecessary for most people.

**Comment by lezcano** [comment]
ping @malfet. See also @xwang233's comment:
>Cuda 11.7 already provides the lazy loading feature. Is it a good time to remove this weird lazy loading logic of linalg module in pytorch now?

**Comment by Alpe6825** [comment]
I have the similar issue too with pytorch 2.0+cuda 11.8. The workaround from above doesn't work for me.

**Comment by lezcano** [comment]
@Alpe6825 can you provide a small reproducer of your issue?

**Comment by howardgriffin** [comment]
any update？

**Comment by agural** [comment]
> I have the similar issue too with pytorch 2.0+cuda 11.8. The workaround from above doesn't work for me.

Try using (1, 1) instead of (0, 0) (the latter might not trigger loading of the linalg module).
`torch.inverse(torch.ones((1, 1), device="cuda:0"))`
