### ISSUE TITLE
[Bug] torch.compile fails with broadcast_all in torch.distributions.utils

### ISSUE THREAD

**Issue by mctigger** [pytorch/pytorch#90623]
## Issue description

`broadcast_all` in `torch.distributions.utils` causes a `torch.compile`d function to fail with `AssertionError: torch.* op returned non-Tensor dtype call_function <built-in function get_default_dtype>`

## Code example
```
import torch
from torch.distributions import Normal

def fn(inputs):
    normal = Normal(inputs, 1)
    return normal.log_prob(inputs)

a = torch.tensor([1])
compiled = torch.compile(fn)
compiled(a)
```

```
/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:366: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled.Consider setting `torch.set_float32_matmul_precision('high')`
  warnings.warn(
>>> compiled(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 476, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 395, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 382, in transform
    tracer.run()
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1621, in run
    super().run()
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 485, in run
    and self.step()
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 454, in step
    getattr(self, inst.opname)(inst)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 281, in wrapper
    return inner_fn(self, inst)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 913, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 389, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/variables/user_defined.py", line 105, in call_function
    return var.add_options(var.call_method(tx, "__init__", args, kwargs))
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/variables/user_defined.py", line 208, in call_method
    return UserMethodVariable(method, self, **options).call_function(
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 226, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 196, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 67, in call_function
    return tx.inline_user_function_return(
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 425, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1693, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1747, in inline_call_
    tracer.run()
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 485, in run
    and self.step()
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 454, in step
    getattr(self, inst.opname)(inst)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 281, in wrapper
    return inner_fn(self, inst)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 913, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 389, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 196, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 67, in call_function
    return tx.inline_user_function_return(
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 425, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1693, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1747, in inline_call_
    tracer.run()
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 485, in run
    and self.step()
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 454, in step
    getattr(self, inst.opname)(inst)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 281, in wrapper
    return inner_fn(self, inst)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 913, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 389, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/variables/torch.py", line 443, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 709, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/user/Envs/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 892, in wrap_fx_proxy_cls
    raise AssertionError(
AssertionError: torch.* op returned non-Tensor dtype call_function <built-in function get_default_dtype>

from user code:
   File "/home/user/Envs/lib/python3.10/site-packages/torch/distributions/normal.py", line 51, in __init__
    self.loc, self.scale = broadcast_all(loc, scale)
  File "/home/user/Envs/lib/python3.10/site-packages/torch/distributions/utils.py", line 34, in broadcast_all
    options: Dict[str, Any] = dict(dtype=torch.get_default_dtype())

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

## System Info

PyTorch version: 1.14.0.dev20221208+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB
GPU 3: NVIDIA A100-PCIE-40GB
GPU 4: NVIDIA A100-PCIE-40GB
GPU 5: NVIDIA A100-PCIE-40GB

Nvidia driver version: 525.60.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.0rc2
[pip3] torch==1.14.0.dev20221208+cu117
[pip3] torchaudio==0.14.0.dev20221208+cu117
[pip3] torchmetrics==0.11.0
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221208+cu117
[conda] Could not collect

cc @fritzo @neerajprad @alicanb @nikitaved @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ShisuiUzumaki** [comment]
@samdow You have labeled this as an issue. How complicated is it? if not too much, I would like to take it up. Also, if you could guide me on how to fix it, that would be really helpful?

**Comment by samdow** [comment]
PT2 oncall will be able to help scope the issue

**Comment by bdhirsh** [comment]
Hmm maybe this will be fixed by https://github.com/pytorch/pytorch/pull/89918

**Comment by yanboliang** [comment]
We had support for ```torch.get_default_dtype``` at #89790, pls update to master.

**Comment by ngimel** [comment]
Closing, reopen if doesn't work on master
