### ISSUE TITLE
Pytorch nightly conda builds for Linux and Windows failing

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#90696]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/actions/runs/3673791849/jobs/6213742922
Failure:
```
+ python -c 'import torch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/testenv/lib/python3.9/site-packages/torch/__init__.py", line 1232, in <module>
    from . import _meta_registrations
  File "/opt/conda/envs/testenv/lib/python3.9/site-packages/torch/_meta_registrations.py", line 7, in <module>
    from torch._decomp import _add_op_to_registry, global_decomposition_table, meta_table
  File "/opt/conda/envs/testenv/lib/python3.9/site-packages/torch/_decomp/__init__.py", line 168, in <module>
    import torch._decomp.decompositions
  File "/opt/conda/envs/testenv/lib/python3.9/site-packages/torch/_decomp/decompositions.py", line 10, in <module>
    import torch._prims as prims
  File "/opt/conda/envs/testenv/lib/python3.9/site-packages/torch/_prims/__init__.py", line 34, in <module>
    from torch.fx.experimental.symbolic_shapes import sym_float
  File "/opt/conda/envs/testenv/lib/python3.9/site-packages/torch/fx/experimental/symbolic_shapes.py", line 451, in <module>
    class Symbol(sympy.Dummy):
NameError: name 'sympy' is not defined
```

### Versions

nightly

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by atalman** [comment]
Looks like not added as a dep yet. Will look inot it. cc @malfet @seemethere

**Comment by malfet** [comment]
It's a bug in our nightly testing framework, but we need to figure out a more resilient way of:
- Installing new dependencies for conda, when they are added
- At the same time ensuring that the package in question gets installed, not the previous nightly

**Comment by atalman** [comment]
Reopening, since still observing the failure in nightly pipeline https://hud.pytorch.org/hud/pytorch/pytorch/nightly
With latest nightly that contains the Guard for SYMPY https://github.com/pytorch/pytorch/commit/3612f8bd54d7ebd3da83971355ac80f66d95e2a9

**Comment by atalman** [comment]
sympy issue is resolved. closing

**Comment by xuyingzhongguo** [comment]
Still have this problem here. Any advice? Thanks!
