### ISSUE TITLE
test_ind_worker_queue: Address already in use / Sometimes hangs

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#9086]
Intermittent OS X failure:

```
15:29:51 test_ind_worker_queue (__main__.TestIndividualWorkerQueue) ... libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: Address already in use
15:29:53 Process Process-48:
15:29:53 Traceback (most recent call last):
15:29:53   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
15:29:53     self.run()
15:29:53   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
15:29:53     self._target(*self._args, **self._kwargs)
15:29:53   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 110, in _worker_loop
15:29:53     data_queue.put((idx, samples))
15:29:53   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/multiprocessing/queues.py", line 341, in put
15:29:53     obj = _ForkingPickler.dumps(obj)
15:29:53   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
15:29:53     cls(buf, protocol).dump(obj)
15:29:53   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 112, in reduce_storage
15:29:53     metadata = storage._share_filename_()
15:29:53 RuntimeError: std::exception at /private/var/lib/jenkins/workspace/pytorch-builds/pytorch-macos-10.13-py3-build/torch/lib/libshm/core.cpp:125
15:29:53 ERROR
15:29:53 test_shuffle_pin_memory (__main__.TestStringDataLoader) ... skipped 'CUDA unavailable'
15:29:53 test_getitem (__main__.TestTensorDataset) ... ok
15:29:53 test_getitem_1d (__main__.TestTensorDataset) ... ok
15:29:53 test_len (__main__.TestTensorDataset) ... ok
15:29:53 test_many_tensors (__main__.TestTensorDataset) ... ok
15:29:54 test_single_tensor (__main__.TestTensorDataset) ... ok
15:29:54 
15:29:54 ======================================================================
15:29:54 ERROR: test_ind_worker_queue (__main__.TestIndividualWorkerQueue)
15:29:54 ----------------------------------------------------------------------
15:29:54 Traceback (most recent call last):
15:29:54   File "test_dataloader.py", line 714, in test_ind_worker_queue
15:29:54     self._run_ind_worker_queue_test(batch_size=batch_size, num_workers=num_workers)
15:29:54   File "test_dataloader.py", line 704, in _run_ind_worker_queue_test
15:29:54     for i, (worker_ids, sample) in enumerate(loader):
15:29:54   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 330, in __next__
15:29:54     idx, batch = self._get_batch()
15:29:54   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 309, in _get_batch
15:29:54     return self.data_queue.get()
15:29:54   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/multiprocessing/queues.py", line 335, in get
15:29:54     res = self._reader.recv_bytes()
15:29:54   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
15:29:54     buf = self._recv_bytes(maxlength)
15:29:54   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
15:29:54     buf = self._recv(4)
15:29:54   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
15:29:54     chunk = read(handle, remaining)
15:29:54   File "/var/lib/jenkins/pytorch-ci-env/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 227, in handler
15:29:54     _error_if_any_worker_fails()
15:29:54 RuntimeError: DataLoader worker (pid 8952) exited unexpectedly with exit code 1.
15:29:54 
```

Sample log: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-macos-10.13-py3-test1/2484/console

**Comment by ezyang** [comment]
Log where it hung:

```
12:40:07 test_ind_worker_queue (__main__.TestIndividualWorkerQueue) ... Build timed out (after 55 minutes). Marking the build as failed.
13:13:04 Build was aborted
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-py3-clang5-asan-test2/4180//console

**Comment by SsnL** [comment]
It's been a while since I saw this. Closing it for now. Reopen if it happens again.
