### ISSUE TITLE
Torch Dynamo/Inductor fails when `/tmp` is mounted `noexec`

### ISSUE THREAD

**Issue by RuRo** [pytorch/pytorch#91005]
### 🐛 Describe the bug

1) Mount `/tmp` as `noexec` (ie `sudo mount -o remount,noexec /tmp`)

2) Run `python tools/dynamo/verify_dynamo.py`

Expected outcome: `All required checks passed`

Actual outcome:

<detail>

```python
Traceback (most recent call last):
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 637, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 913, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 913, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 394, in compile_fx
    return aot_autograd(
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/optimizations/training.py", line 78, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2329, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2026, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_tensor_args, aot_config)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1293, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1540, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 369, in fw_compiler
    return inner_compile(
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 490, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/debug.py", line 223, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 136, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/graph.py", line 497, in compile_to_fn
    return self.compile_to_module().call
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/graph.py", line 486, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 459, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_username/45/c45rvcppnhilzdeefe56n6uxeeyfa2e7he7josu5k4jjj2lip5kw.py", line 38, in <module>
    async_compile.wait(globals())
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 642, in wait
    scope[key] = result.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 634, in task
    return CppCodeCache.load(source_code).kernel
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 440, in load
    cls.cache[key] = cls._load_library(output_path)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 407, in _load_library
    return cdll.LoadLibrary(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/torchinductor_username/wv/cwvczan5s5eh65qc7oe7cfwbdtcthtuu72tszvwvcb43rl5pw7un.so: failed to map segment from shared object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "verify_dynamo.py", line 127, in check_dynamo
    y = f(x)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 398, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 385, in transform
    tracer.run()
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1686, in run
    super().run()
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 537, in run
    and self.step()
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 500, in step
    getattr(self, inst.opname)(inst)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1752, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 490, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 561, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/username/.venv/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 642, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: compile_fx raised OSError: /tmp/torchinductor_username/wv/cwvczan5s5eh65qc7oe7cfwbdtcthtuu72tszvwvcb43rl5pw7un.so: failed to map segment from shared object

Set torch._dynamo.config.verbose=True for more information
```

</detail>

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20221214+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40
GPU 2: NVIDIA A40
GPU 3: NVIDIA A40
GPU 4: NVIDIA A40
GPU 5: NVIDIA A40
GPU 6: NVIDIA A40
GPU 7: NVIDIA A40
GPU 8: NVIDIA A40
GPU 9: NVIDIA A40

Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.0rc2
[pip3] torch==2.0.0.dev20221214+cu117
[pip3] torchmetrics==0.11.0
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221214+cu117
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
We need to be able to load the generated so files, alas. I suppose we might be able to see if we can write to your user dir if tmp is noexec (easy but risks clogging up filesystem with stale libraries) or manually reading the so into exec'able memory (annoying to implement) but honestly, if you can, I'd recommend not mounting tmp with noexec

**Comment by RuRo** [comment]
@ezyang Understandable, it's just that docker mounts tmp filesystems as noexec by default if you do `docker run --tmpfs /tmp`. Also, you might want to at least catch this exception and reraise something more obvious. It's really not obvious what "failed to map segment from shared object" even means.

**Comment by ezyang** [comment]
Yup sgtm. (If anyone wants to submit a PR for this, feel free to tag me for review!)

**Comment by Guobing-Chen** [comment]
https://github.com/pytorch/pytorch/pull/91385 created for this issue.

**Comment by Guobing-Chen** [comment]
Can we consider this issue has been fixed as https://github.com/pytorch/pytorch/pull/91385 merged? @RuRo, any more comments?

**Comment by RuRo** [comment]
Yup, LGTM.
