### ISSUE TITLE
[FSDP] cannot find engine to run cudnn convolutions

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#91025]
### 🐛 Describe the bug

Repro: run this from within the torchbench directory:
```
import torch
import importlib
import os

from torch.distributed.fsdp import FullyShardedDataParallel as FSDP

os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "6782"
torch.distributed.init_process_group("nccl", rank=0, world_size=1)

mod = importlib.import_module("torchbenchmark.models.Background_Matting")
m = mod.Model(test="train", device="cuda")

m.netG = FSDP(m.netG, use_orig_params=True)

m.invoke()
```

I think this regression happened some time in the last few days, this previously didn't fail

Error:
```
/scratch/dberard/dynamo38/pytorch/torch/distributed/fsdp/_init_utils.py:287: UserWarning: FSDP is switching to use `NO_SHARD` instead of ShardingStrategy.FULL_SHARD since the world size is 1.
  warnings.warn(
Traceback (most recent call last):
  File "runner.py", line 16, in <module>
    m.invoke()
  File "/scratch/dberard/dynamo38/benchmark/torchbenchmark/util/model.py", line 276, in invoke
    self.train()
  File "/scratch/dberard/dynamo38/benchmark/torchbenchmark/models/Background_Matting/__init__.py", line 161, in train
    alpha_pred, fg_pred = self.netG(image, bg, seg, multi_fr)
  File "/scratch/dberard/dynamo38/pytorch/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 689, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/dberard/dynamo38/benchmark/torchbenchmark/models/Background_Matting/networks.py", line 107, in forward
    out_dec_fg1=self.model_dec_fg1(out_dec_fg)
  File "/scratch/dberard/dynamo38/pytorch/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/scratch/dberard/dynamo38/pytorch/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/scratch/dberard/dynamo38/pytorch/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: FIND was unable to find an engine to execute this computation
```

### Versions

viable/strict (`140a3139d6c5fd48852865af5675ab533db51b37`), AWS cluster

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @csarofeen @ptrblck @xwang233

**Comment by davidberard98** [comment]
@awgu since I have a setup for this I will run a bisect to figure out when this broke...

**Comment by davidberard98** [comment]
bisect still running but I'm pretty sure the problematic commit is https://github.com/pytorch/pytorch/pull/89022

**Comment by davidberard98** [comment]
yes, confirmed that the bisect identifies https://github.com/pytorch/pytorch/pull/89022 as the offending commit

cc @eqy @ngimel

**Comment by ngimel** [comment]
Ok let me revert it. @eqy it would be good to beef up v8 error reporting to also print out the failing conv params (we had that in v7).

**Comment by awgu** [comment]
Thanks @davidberard98 for identifying this and bisecting!

**Comment by eqy** [comment]
@ngimel could you please review https://github.com/pytorch/pytorch/pull/91032 as I believe that should resolve the issue?

**Comment by eqy** [comment]
@davidberard98 
Could you please check if the issue is resolved following https://github.com/pytorch/pytorch/commit/ce4900f3bb64da2b5bced9106d26c44363189155 ? You can enable the V8 frontend via the `TORCH_CUDNN_V8_API_ENABLED=1` environment variable.

**Comment by davidberard98** [comment]
@eqy I ran this again with `TORCH_CUDNN_V8_API_ENABLED=1` on 731f417f60bfd5bb8d2ec756c23c0e6624ea3351 (which is a few commits after ce4900f3bb6 ) and this appears to be fixed. Thanks!

**Comment by ngimel** [comment]
Ok we should try landing v8 again then, @eqy can you please resubmit? Sorry for the churn.
