### ISSUE TITLE
Simple deleting from the sys cache fails on reimport

### ISSUE THREAD

**Issue by as51340** [pytorch/pytorch#91039]
### Bug description
I am working on a project in which I need to throw `torch` package out of the sys cache in order to be able to reload new version of the torch package. However, this minimal example fails:
```
import torch
import sys

if __name__ == "__main__":
    sys.modules.pop("torch", None)
    import torch
```
With the following error:
```
Traceback (most recent call last):
  File "/home/andi/Memgraph/code/mage/python/test_mage/test_submodules.py", line 10, in <module>
    import torch
  File "/home/andi/.local/lib/python3.10/site-packages/torch/__init__.py", line 233, in <module>
    for name in dir(_C):
NameError: name '_C' is not defined
```

### Versions

```
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] numpydoc==1.5.0
[pip3] torch==1.12.1+cpu
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.12.1+cpu
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.4           py39h14f4228_0  
[conda] numpy-base                1.23.4           py39h31eccc5_0  
[conda] pytorch                   1.13.1              py3.9_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.13.1                 py39_cpu    pytorch
[conda] torchvision               0.14.1                 py39_cpu    pytorch
```

**Comment by albanD** [comment]
Hi,

I'm afraid you cannot `reload(torch)` either. This is mainly due to the fact that we have very statefull C++ extensions.
We would accept contributions towards this though!

**Comment by as51340** [comment]
Do you know maybe which extensions are problem?

**Comment by albanD** [comment]
Hey!
From checking again, it looks like some of the recent changes we did allow you to do `reload(torch)` just fine now!
Does the following works for you?
```python
from importlib import reload

import torch

reload(torch)
```
