### ISSUE TITLE
Pytorch 2.0: SSD from torchvision don't compile

### ISSUE THREAD

**Issue by Inkorak** [pytorch/pytorch#91084]
### 🐛 Describe the bug

ssd300_vgg16 and ssdlite320_mobilenet_v3_large from torchvision don't compile and gives an error.

Code:
```
model = ssdlite320_mobilenet_v3_large(pretrained=True)
device = torch.device('cuda')

model.to(device).eval()
model= torch.compile(model)
input_data = torch.randn(3, 512, 512)
with torch.no_grad():
    out = model([input_data.to(device)])
```

Error:
```
[2022-12-19 11:21:20,164] torch._inductor.graph: [WARNING] Creating implicit fallback for:
  target: aten.upsample_bilinear2d.default
  args[0]: TensorBox(
    View(
      StorageBox(
        Pointwise(
          'cuda',
          torch.float32,
          tmp0 = load(arg0_1, i2 + 512 * i1 + 262144 * i0)
          tmp1 = index_expr(i0, torch.int64)
          tmp2 = constant(1, torch.int64)
          tmp3 = tmp1 < tmp2
          tmp4 = constant(0.5, torch.float32)
          tmp5 = index_expr(i0, torch.int64)
          tmp6 = constant(2, torch.int64)
          tmp7 = tmp5 < tmp6
          tmp8 = constant(0.5, torch.float32)
          tmp9 = constant(0.5, torch.float32)
          tmp10 = where(tmp7, tmp8, tmp9)
          tmp11 = where(tmp3, tmp4, tmp10)
          tmp12 = tmp0 - tmp11
          tmp13 = index_expr(i0, torch.int64)
          tmp14 = constant(1, torch.int64)
          tmp15 = tmp13 < tmp14
          tmp16 = constant(0.5, torch.float32)
          tmp17 = index_expr(i0, torch.int64)
          tmp18 = constant(2, torch.int64)
          tmp19 = tmp17 < tmp18
          tmp20 = constant(0.5, torch.float32)
          tmp21 = constant(0.5, torch.float32)
          tmp22 = where(tmp19, tmp20, tmp21)
          tmp23 = where(tmp15, tmp16, tmp22)
          tmp24 = tmp12 / tmp23
          return tmp24
          ,
          ranges=[3, 512, 512],
          origins={lift_fresh_copy_1, _tensor_constant0, unsqueeze_2, unsqueeze, slice_1, lift_fresh_copy, _tensor_constant1, div, slice_2, unsqueeze_3, sub, arg0_1, unsqueeze_1}
        )
      ),
      size=(1, 3, 512, 512),
      reindex=lambda i0, i1, i2, i3: [i1, i2, i3],
      origins={lift_fresh_copy_1, _tensor_constant0, unsqueeze_2, unsqueeze, slice_1, lift_fresh_copy, _tensor_constant1, div, slice_2, unsqueeze_4, unsqueeze_3, sub, arg0_1, unsqueeze_1}
    )
  )
  args[1]: [320, 320]
  args[2]: False
[2022-12-19 11:21:20,165] torch._inductor.lowering: [WARNING] make_fallback(aten.upsample_bilinear2d.default): a decomposition exists, we should switch to it
[2022-12-19 11:21:20,180] torch._inductor.ir: [WARNING] Using FallbackKernel: torch.ops.aten.upsample_bilinear2d.default
Traceback (most recent call last):
  File "/home/user/PycharmProjects/pytorch2test/main.py", line 55, in <module>
    out = model([input_data.to(device)])
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 83, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/ssd.py", line 371, in forward
    features = self.backbone(images.tensors)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1684, in run
    super().run()
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 307, in wrapper
    return inner_fn(self, inst)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 966, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 435, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 220, in call_function
    return tx.inline_user_function_return(
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 471, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1762, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1817, in inline_call_
    tracer.run()
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 307, in wrapper
    return inner_fn(self, inst)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1015, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 435, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 244, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 214, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 67, in call_function
    return tx.inline_user_function_return(
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 471, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1762, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1790, in inline_call_
    sub_locals, closure_cells = func.bind_args(parent, args, kwargs)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 129, in bind_args
    tuple(map(wrap, fn.__defaults__ or [])),
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 34, in wrap_bound_arg
    assert isinstance(val, VariableTracker), typestr(val)
AssertionError: dtype

from user code:
   File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/ssd.py", line 381, in <graph break in forward>
    anchors = self.anchor_generator(images, features)
  File "/home/user/anaconda3/envs/pytorch2test/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 253, in forward
    default_boxes = self._grid_default_boxes(grid_sizes, image_size, dtype=dtype)

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20221218+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.0
[pip3] torch==2.0.0.dev20221218+cu116
[pip3] torch2trt==0.4.0
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221218+cu116
[conda] numpy                     1.24.0                   pypi_0    pypi
[conda] torch                     2.0.0.dev20221218+cu116          pypi_0    pypi
[conda] torch2trt                 0.4.0                    pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221218+cu116          pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by williamwen42** [comment]
Attempting to minify this error gives cryptic errors (CUDA illegal memory access when backend is inductor and FakeTensor exception when backend is eager).

**Comment by ezyang** [comment]
This is still failing as of 8f3600b966d896986e334b9a22c43e937ee0169d

**Comment by ezyang** [comment]
The assert failure blames to @jansel, assigning you to look

**Comment by ezyang** [comment]
It kind of looks like function inlining for kwarg that is dtype isn't wrapping VariableTracker correctly. Maybe cc @wconstab too

**Comment by wconstab** [comment]
I'll take a look, the stack trace in `bind_args` looks like it could be from the defaults stuff

**Comment by wconstab** [comment]
@Inkorak I put up a PR #92880 with a proposed fix.  I'll proceed with getting that landed but in the mean time you can apply it locally to unblock.
