### ISSUE TITLE
[Inductor] `test_tmp_not_defined_issue1_cuda` raises `RuntimeError` but passes

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#91088]
### 🐛 Describe the bug

Steps to reproduce:
```python
python inductor/test_torchinductor.py -v -k test_tmp_not_defined_issue1_cuda
...
  File "/usr/local/lib/python3.8/dist-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: !schema.hasAnyAliasInfo() INTERNAL ASSERT FAILED at "../aten/src/ATen/FunctionalizeFallbackKernel.cpp":32, please report a bug to PyTorch. mutating and aliasing ops should all have codegen'd kernels

While executing %broadcast_in_dim_default : [#users=1] = call_function[target=torch.ops.prims.broadcast_in_dim.default](args = (%var_default_1, [1, 512, 1], [0, 1]), kwargs = {})
Original traceback:
Module stack: {}
  File "inductor/test_torchinductor.py", line 4685, in forward
    broadcast_in_dim_default_2 = torch.ops.prims.broadcast_in_dim.default(
 |   File "inductor/test_torchinductor.py", line 316, in run
    return model(*ex, **kwargs)
...
[2022-12-19 06:53:09,515] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 0
inductor/test_torchinductor.py:244: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor._storage() instead of tensor.storage()
  buffer = torch.as_strided(x, (x.storage().size(),), (1,), 0).clone()
Failed to collect metadata on function, produced code may be suboptimal.  Known situations this can occur are inference mode only compilation involving resize_ or prims (!schema.hasAnyAliasInfo() INTERNAL ASSERT FAILED); if your situation looks different please file a bug to PyTorch.
Traceback (most recent call last):
...
RuntimeError: !schema.hasAnyAliasInfo() INTERNAL ASSERT FAILED at "../aten/src/ATen/FunctionalizeFallbackKernel.cpp":32, please report a bug to PyTorch. mutating and aliasing ops should all have codegen'd kernels
...
----------------------------------------------------------------------
Ran 1 test in 2.063s

OK
```

Based on this output the test passes with `OK` but a `RuntimeError` is raised (it could thus be missed in CI and I found it by manually checking some tests).
I don't think this test is expected to check for this `RuntimeError` (unless I'm missing something from its definition [here](https://github.com/pytorch/pytorch/blob/ce4900f3bb64da2b5bced9106d26c44363189155/test/inductor/test_torchinductor.py#L4656-L4703)).

### Versions

```
python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.0.dev20221218+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-80-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 12.0.76
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.0.0.dev20221218+cu117
[pip3] torch-tensorrt==1.4.0.dev0
[pip3] torchtext==0.13.0a0+fae8e8c
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221218+cu117
[conda] Could not collect
```

**Comment by ngimel** [comment]
cc @bdhirsh, the error message says 
```
Failed to collect metadata on function, produced code may be suboptimal.  Known situations this can occur are inference mode only compilation involving resize_ or prims (!schema.hasAnyAliasInfo() INTERNAL ASSERT FAILED); if your situation looks different please file a bug to PyTorch.
```
and indeed `INTERNAL_ASSERT_FAILED` is thrown on torch.ops.prims.broadcast_in_dim.default, is this a won't fix, or should we add aliasing info to prims schemas?

**Comment by bdhirsh** [comment]
Oh this would be fixed by https://github.com/pytorch/pytorch/issues/83923. Although tbh we'll need to support custom ops that alias/mutate at some point anyway, so it might be worth doing that instead of trying to get functionalization working specifically with prim view ops.

I'm not sure that this is very hi-pri though, since it only affects user code that directly calls prim view ops. It is pretty unfortunate that it makes the logs spammy in that test case though (maybe we can suppress the logs somehow?)

**Comment by ngimel** [comment]
Ah ok, so if it's `broadcast_in_dim` inserted by a decomposition, and not directly in the user code, this wouldn't happen? Yeah that should be good enough.

**Comment by bdhirsh** [comment]
Yep exactly (as long as the decomposition runs after autograd / functionalization, aka the decomp table that AOT Autograd uses)

**Comment by eellison** [comment]
Test no longer fails so assuming it's fixed. re-open if otherwise.
