### ISSUE TITLE
[sparse] regressions after moving into ATen

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9110]
1. create cuda sparse tensor with cpu indices tensor
	master:
	```py
	>>> torch.sparse.FloatTensor(torch.zeros(1,4).long().cuda(), torch.randn(4,4,4), [3,4,4])
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	RuntimeError
	```
	0.4:
	```py
	>>> torch.sparse.FloatTensor(torch.zeros(1,4).long().cuda(), torch.randn(4,4,4), [3,4,4])
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #1 'indices'
	```

2. add cuda sparse tensor to cpu dense tensor
	master:
	```py
	>>> x = torch.zeros(3,4)
	>>> sparse_y = torch.cuda.sparse.FloatTensor(torch.zeros(1,4).long().cuda(), torch.randn(4,4,4).cuda(), [3,4,4])
	>>> x + sparse_y
	[1]    2065657 segmentation fault (core dumped)  python -i ~/env.py
	```
	0.4:
	```py
	>>> x + sparse_y
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
	```

3. dense + sparse with wrong number of dimdensions
    master:
    ```py
    >>> x = torch.zeros(3,4)
	>>> sparse_y = torch.cuda.sparse.FloatTensor(torch.zeros(1,4).long().cuda(), torch.randn(4,4,4).cuda(), [3,4,4])
	>>> x.cuda()+sparse_y
	tensor([[ 2.1478, -0.7767, -0.8796, -2.2104],
	        [ 0.0000,  0.0000,  0.0000,  0.0000],
	        [ 0.0000,  0.0000,  0.0000,  0.0000]], device='cuda:0')
    ```
    0.4:
    ```py
	>>> x = torch.zeros(3,4)
	>>> sparse_y = torch.cuda.sparse.FloatTensor(torch.zeros(1,4).long().cuda(), torch.randn(4,4,4).cuda(), [3,4,4])
	>>> x.cuda() + sparse_y
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
    ```

cc @ezyang

**Comment by ezyang** [comment]
Root cause of 1 and 2 was that the old TH binding code used to do some extra checks, which native functions don't do. Added those tests back manually.

3 is a bit weirder; I'm not sure how the old code managed to report an error. In any case, adding the shape tests at the appropriate places was easy. PR coming.

**Comment by SsnL** [comment]
Also, afaict, `sparseElementwiseKernelScalar` in `SparseCUDAApplyUtils.cuh` doesn't work with `dimV > 1`. But it is called in `add_out_dense_sparse_cuda` when input is coalesced. I haven't checked if it gives correct results on `dimV > 1`. (It's definitely broken with noncontig I and V.)
