### ISSUE TITLE
RuntimeError: status != cudaStreamCaptureStatus::cudaStreamCaptureStatusInvalidated

### ISSUE THREAD

**Issue by tchaton** [pytorch/pytorch#91302]
### 🐛 Describe the bug

Trying to apply Cuda Graphs to Stable Diffusion Unet, it seems this line breaks: https://github.com/CompVis/stable-diffusion/blob/ce05de28194041e030ccfc70c635fe3707cdfc30/ldm/modules/diffusionmodules/util.py#L165

with the following error. 

```python
Traceback (most recent call last):
  File "/home/thomas/stablediffusion/ldm/lightning.py", line 140, in _create_cuda_graph
    self.static_output = self._forward(*self.static_inputs, **self.static_kwargs)
  File "/home/thomas/stablediffusion/ldm/lightning.py", line 145, in _forward
    return self.unet(sample, timestamp, c_crossattn=c_crossattn)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thomas/stablediffusion/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/home/thomas/stablediffusion/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/thomas/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 767, in forward
    t_emb = timestep_embedding(timesteps, self.model_channels, repeat_only=False)
  File "/home/thomas/stablediffusion/ldm/modules/diffusionmodules/util.py", line 168, in timestep_embedding
    args = timesteps[:, None].float() * freqs[None]
RuntimeError: status != cudaStreamCaptureStatus::cudaStreamCaptureStatusInvalidated INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1220, please report a bug to PyTorch.
```

I tried to re-write the operation with other operators such as reshape, view, unsqueeze. It didn't help.

Here was my replay cuda graph nn.Module:

```python
class ReplayCudaGraphUnet(torch.nn.Module):
    def __init__(self, unet, enable_cuda_graph=True):
        super().__init__()
        self.unet = unet
        # SD pipeline accesses this attribute
        self.device = self.unet.device
        self.dtype = self.unet.dtype
        self.fwd_count = 0
        self.unet.requires_grad_(requires_grad=False)
        self.unet.to(memory_format=torch.channels_last)
        self.cuda_graph_created = False
        self.enable_cuda_graph = enable_cuda_graph

    def __getattr__(self, key):
        if hasattr(self._modules["unet"], key) and key not in self.__dict__:
            return getattr(self._modules["unet"], key)
        if key == "unet":
            return self._modules["unet"]
        return object.__getattribute__(self, key)

    def _graph_replay(self, *inputs, **kwargs):
        for i in range(len(inputs)):
            if torch.is_tensor(inputs[i]):
                self.static_inputs[i].copy_(inputs[i])
        for k in kwargs:
            if torch.is_tensor(kwargs[k]):
                self.static_kwargs[k].copy_(kwargs[k])
        self._cuda_graphs.replay()
        return self.static_output

    def forward(self, *inputs, **kwargs):
        if self.enable_cuda_graph:
            if self.cuda_graph_created:
                outputs = self._graph_replay(*inputs, **kwargs)
            else:
                self._create_cuda_graph(*inputs, **kwargs)
                outputs = self._graph_replay(*inputs, **kwargs)
            return outputs
        else:
            return self._forward(*inputs, **kwargs)

    def _create_cuda_graph(self, *inputs, **kwargs):
        # warmup to create the workspace and cublas handle
        cuda_stream = torch.cuda.Stream()
        cuda_stream.wait_stream(torch.cuda.current_stream())
        with torch.cuda.stream(cuda_stream):
            for i in range(3):
                ret = self._forward(*inputs, **kwargs)
        torch.cuda.current_stream().wait_stream(cuda_stream)

        # create cuda_graph and assign static_inputs and static_outputs
        self._cuda_graphs = torch.cuda.CUDAGraph()
        self.static_inputs = inputs
        self.static_kwargs = kwargs

        with torch.cuda.graph(self._cuda_graphs):
            self.static_output = self._forward(*self.static_inputs, **self.static_kwargs)

        self.cuda_graph_created = True

    def _forward(self, sample, timestamp, c_crossattn):
        return self.unet(sample, timestamp, c_crossattn=c_crossattn)
```

### Versions

```python
aiohttp==3.8.3
aiosignal==1.3.1
antlr4-python3-runtime==4.8
anyio==3.6.2
arrow==1.2.3
async-timeout==4.0.2
attrs==22.2.0
beautifulsoup4==4.11.1
blessed==1.19.1
certifi==2022.12.7
charset-normalizer==2.1.1
click==8.1.3
commonmark==0.9.1
croniter==1.3.8
deepdiff==6.2.2
dnspython==2.2.1
einops==0.3.0
email-validator==1.3.0
fastapi==0.88.0
filelock==3.8.2
frozenlist==1.3.3
fsspec==2022.11.0
ftfy==6.1.1
h11==0.14.0
httpcore==0.16.3
httptools==0.5.0
httpx==0.23.1
huggingface-hub==0.11.1
idna==3.4
imageio==2.9.0
imageio-ffmpeg==0.4.2
inquirer==3.1.1
itsdangerous==2.1.2
Jinja2==3.1.2
lightning==1.8.6
lightning-cloud==0.5.14
lightning-utilities==0.4.2
MarkupSafe==2.1.1
multidict==6.0.3
numpy==1.24.0
omegaconf==2.1.1
open-clip-torch==2.7.0
opencv-python==4.6.0.66
ordered-set==4.1.0
orjson==3.8.3
packaging==22.0
Pillow==9.3.0
protobuf==3.20.1
psutil==5.9.4
pudb==2019.2
pydantic==1.10.2
Pygments==2.13.0
PyJWT==2.6.0
python-dateutil==2.8.2
python-dotenv==0.21.0
python-editor==1.0.4
python-multipart==0.0.5
pytorch-lightning==1.8.6
PyYAML==6.0
readchar==4.0.3
regex==2022.10.31
requests==2.28.1
rfc3986==1.5.0
rich==12.6.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
-e git+https://github.com/Lightning-AI/stablediffusion.git@69ed1042b836757f581f8c1b7811bb74bf644ce6#egg=stable_diffusion
starlette==0.23.1
starsessions==1.3.0
tensorboardX==2.5.1
tokenizers==0.13.2
torch==1.13.1+cu116
torchmetrics==0.11.0
torchvision==0.14.1+cu116
tqdm==4.64.1
traitlets==5.8.0
transformers==4.25.1
typing-extensions==4.4.0
ujson==5.6.0
urllib3==1.26.13
urwid==2.1.2
uvicorn==0.20.0
uvloop==0.17.0
watchfiles==0.18.1
wcwidth==0.2.5
websocket-client==1.4.2
websockets==10.4
yarl==1.8.2
```

```python
(.venv) thomas@lambda-server1:~/stablediffusion$ nvidia-smi
Thu Dec 22 04:17:42 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| 30%   32C    P8    17W / 350W |      3MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
```

cc @mcarilli @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by drisspg** [comment]
Could you run and paste the output of https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py

**Comment by ngimel** [comment]
`freqs` is created on cpu and copied to cuda, this is not supported with cudagraphs

**Comment by ezyang** [comment]
@eellison think your pt2 cudagraphs stuff will support this? 😊

**Comment by ngimel** [comment]
A neat thing about inductor is that it just moves `arange` to the device by itself, so no additional tricks for cudagraphs are necessary.

**Comment by tchaton** [comment]
Hey @ngimel,

Thanks, this was the error. I think the error message was misleading me as I thought the `timesteps[:, None].float() * freqs[None]` was the operation causing the error, but not the `freqs` tensor creation.
