### ISSUE TITLE
cannot reload on CPU model saved on GPU

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#9139]
Here is the error I get when I try to reload on my laptop a model saved on a GPU server:

```python
reloaded = torch.load(params.reload_model)
```

```
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    reloaded = torch.load(params.reload_model)#, map_location=lambda storage, location: 'cpu')
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 88, in default_restore_location
    result = fn(storage, location)
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 70, in _cuda_deserialize
    return obj.cuda(device)
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 68, in _cuda
    with torch.cuda.device(device):
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 225, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'
```

I modified it so that it loads the model on CPU directly:

```python
reloaded = torch.load(params.reload_model, map_location=lambda storage, location: 'cpu')
```

But now I get this:

```
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    reloaded = torch.load(params.reload_model, map_location=lambda storage, location: 'cpu')
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 98, in _rebuild_tensor_v2
    tensor = _rebuild_tensor(storage, storage_offset, size, stride)
  File "/Users/guismay/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 92, in _rebuild_tensor
    module = importlib.import_module(storage.__module__)
AttributeError: 'str' object has no attribute '__module__'
```

Note that I'm using pytorch 0.5 on my GPU server and pytorch 0.4 on my Mac (as I was not able to build pytorch from source on my mac).
Any ideas?

Thank you

**Comment by SsnL** [comment]
When you do `torch.load(.....)`, set `torch.load(...., map_location='cpu')`. If you don't, since you are loading GPU tensors, PyTorch will try to reconstruct GPU tensors, and fail.

**Comment by SsnL** [comment]
Just give it `'cpu'`, not a lambda.

**Comment by glample** [comment]
It worked, thanks!

**Comment by ayoubbenaissa** [comment]
try this:
torch.load('my_file.pt', map_location=lambda storage, location: 'cpu')

or this:
torch.load('my_file.pt', map_location={'cuda:0': 'cpu'})

First one will forcefully remap everything onto CPU
and the second will only map storages from GPU0
