### ISSUE TITLE
Pytorch2.0 doesn't support compiling GRU and RNN model

### ISSUE THREAD

**Issue by Tribleave** [pytorch/pytorch#91439]
### 🐛 Describe the bug

I am trying to boost model with compiling model in PyTorch2.0. However, GRU modules are not abled to be compiled. 

Following is the MWE:
```python
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.gru = nn.GRU(16, 16, batch_first=True)
    
    def forward(self, x):
        return self.gru(x)

def test():
    device = torch.device('cuda')
    model = Model().to(device)
    model = torch.compile(model)
    x = torch.rand(1024, 20, 16).to(device)
    model(x)
```

The error message was saying:
```plain
Traceback (most recent call last):
  File "example.py", line 23, in <module>
    test()
  File "example.py", line 20, in test
    model(x)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 83, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 88, in time_wrapper
    r = func(*args, **kwargs)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1684, in run
    super().run()
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1750, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 553, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 600, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/miniconda3/envs/pytorch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 681, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised NotImplementedError: could not find kernel for aten._cudnn_rnn_flatten_weight.default at dispatch key DispatchKey.Meta
```

The code run smoothly if I use nn.LSTM, but got the same error if use nn.RNN.

### Versions

```plain
PyTorch version: 2.0.0.dev20221227+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA TITAN RTX
Nvidia driver version: 522.25
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0.dev20221227+cu117
[pip3] torchaudio==2.0.0.dev20221222+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221222+cu117
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.0.0.dev20221227+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20221222+cu117          pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221222+cu117          pypi_0    pypi
```

**Comment by ngimel** [comment]
LSTM and GRU models that go directly to cudnn won't be accelerated by `torch.compile`, cudnn is already very efficient.

**Comment by anijain2305** [comment]
Yes, as @ngimel mentioned we do not expect speedups for RNN if most of the code is going through CuDNN.

However, we should not fail with the above error message. I think we need to add a meta kernel for  `aten._cudnn_rnn_flatten_weight` op, or have a graceful fallback mechanism for fake tensor. 

cc @eellison for any ideas on graceful fallback mechanism if any.

**Comment by caidao22** [comment]
This seems to be a great limitation of PyTorch2.0. `Torch.compile()` fails when the model contains a component that is not supported. My model has a GRU layer but the other layers are way more expensive. Is it possible to accelerate the other parts of the model?

**Comment by ngimel** [comment]
`torch.compile` usually can graph break on unsupported parts, GRU/LSTM errors are a bug, we are fixing it. cc @voznesenskym

**Comment by voznesenskym** [comment]
> This seems to be a great limitation of PyTorch2.0. `Torch.compile()` fails when the model contains a component that is not supported. My model has a GRU layer but the other layers are way more expensive. Is it possible to accelerate the other parts of the model?

Quick answer - it should not fail! So first thing first, I'll take a look at generally identifying these and graph breaking on them.

Long answer - defer to @ngimel for what should and shouldn't be optimized ;)

**Comment by anhnami** [comment]
Any update on this issue?

**Comment by lifeiteng** [comment]
@ngimel Any update?

**Comment by eellison** [comment]
Test no longer fails but we do graph break.

**Comment by anijain2305** [comment]
We are not looking at supporting GRU/LSTMS it H1 2024. So, marking low priority. But, accepting PRs in case anyone is interested.

**Comment by vadimkantorov** [comment]
It should not fail this bad with a graph break, right? (especially if torch.scan higher-order with dynamic seqlen starts to be supported) Because decomps for LSTM cells are really nothing special, right?

For some inference scenarios having torch.compile + export for a single step (of LSTM/GRU Cell) might be sufficient and useful

**Comment by vadimkantorov** [comment]
A problem is that this seems to be blocking torch.onnx.dynamo_export of these models as well?

**Comment by eellison** [comment]
I don't think it's a short term priority but maybe cc @thiagocrepaldi could pick it up and @anijain2305 / @bdhirsh can provide guidance.

**Comment by debasish-mihup** [comment]
Facing same issue here. Can not export to onnx, using torch.onnx.dynamo_export. Given pytorch version 2+ has seen same multiple releases already, can not understand why such a regression in overall functionality was overlooked.

**Comment by penguinwu** [comment]
cc @avikchaudhuri on the part related to export.

**Comment by BowenBao** [comment]
cc @xadupre @titaiwangms

**Comment by ezyang** [comment]
There is `torch._dynamo.config.allow_rnn = True` which may or may not help you get things working

**Comment by ezyang** [comment]
These patches are probably not good ideas

```
diff --git a/torch/_dynamo/trace_rules.py b/torch/_dynamo/trace_rules.py
index 0211728836b..8b300cf94dc 100644
--- a/torch/_dynamo/trace_rules.py
+++ b/torch/_dynamo/trace_rules.py
@@ -160,8 +160,6 @@ manual_torch_name_rule_map = {
     "torch.cuda.set_rng_state": SkipFunctionVariable,
     # https://github.com/pytorch/pytorch/issues/107187
     "torch.manual_seed": SkipFunctionVariable,
-    # https://github.com/pytorch/pytorch/issues/93501
-    "torch.nn.utils.rnn.pack_padded_sequence": SkipFunctionVariable,
     "torch.nn.Parameter": TorchInGraphFunctionVariable,
     "torch.nn.Buffer": TorchInGraphFunctionVariable,
     "torch._nested_tensor_from_mask": SkipFunctionVariable,
diff --git a/torch/nn/modules/rnn.py b/torch/nn/modules/rnn.py
index 8455b7299a4..ba194e49485 100644
--- a/torch/nn/modules/rnn.py
+++ b/torch/nn/modules/rnn.py
@@ -1048,7 +1048,7 @@ class LSTM(RNNBase):
         num_directions = 2 if self.bidirectional else 1
         real_hidden_size = self.proj_size if self.proj_size > 0 else self.hidden_size
         if isinstance(orig_input, PackedSequence):
-            input, batch_sizes, sorted_indices, unsorted_indices = input
+            input, batch_sizes, sorted_indices, unsorted_indices = input.data, input.batch_sizes, input.sorted_indices, input.unsorted_indices
             max_batch_size = batch_sizes[0]
             if hx is None:
                 h_zeros = torch.zeros(
```
