### ISSUE TITLE
DISABLED test_fs_preserve_sharing (__main__.TestMultiprocessing)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#91467]
Platforms: dynamo

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_fs_preserve_sharing%2CTestMultiprocessing)).

It looks like the temp `/dev/shm/torch_*` files are not cleaned up properly when running with dynamo

cc @VitalyFedyunin @ezyang @chauhang @penguinwu @rec @ejguan @mlazos @soumith @voznesenskym @yanboliang @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by huydhn** [comment]
The following tests `test_fs `, `test_fs_pool`, `test_fs_preserve_sharing`, `test_fs_sharing` all fails with the same reason (not flaky):

```
pytest test_multiprocessing.py -k test_fs --verbose
=================================================================== test session starts ====================================================================
platform linux -- Python 3.7.15, pytest-7.2.0, pluggy-1.0.0 -- /opt/conda/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/var/lib/jenkins/workspace/test/.hypothesis/examples')
rootdir: /var/lib/jenkins/workspace, configfile: pytest.ini
plugins: hypothesis-5.35.1, flakefinder-1.1.0, rerunfailures-10.3, shard-0.1.2, xdist-3.1.0, xdoctest-1.0.2
collected 37 items / 32 deselected / 5 selected
Running 5 items in this shard: test/test_multiprocessing.py::TestMultiprocessing::test_fs, test/test_multiprocessing.py::TestMultiprocessing::test_fs_is_shared, test/test_multiprocessing.py::TestMultiprocessing::test_fs_pool, test/test_multiprocessing.py::TestMultiprocessing::test_fs_preserve_sharing, test/test_multiprocessing.py::TestMultiprocessing::test_fs_sharing

test_multiprocessing.py::TestMultiprocessing::test_fs FAILED                                                                                         [ 20%]
test_multiprocessing.py::TestMultiprocessing::test_fs_is_shared PASSED                                                                               [ 40%]
test_multiprocessing.py::TestMultiprocessing::test_fs_pool FAILED                                                                                    [ 60%]
test_multiprocessing.py::TestMultiprocessing::test_fs_preserve_sharing FAILED                                                                        [ 80%]
test_multiprocessing.py::TestMultiprocessing::test_fs_sharing FAILED                                                                                 [100%]

========================================================================= FAILURES =========================================================================
_______________________________________________________________ TestMultiprocessing.test_fs ________________________________________________________________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 370, in test_fs
    queue_put()
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 360, in queue_put
    x = torch.DoubleStorage(4)
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 361, in <graph break in queue_put>
    q = mp.Queue()
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 362, in <graph break in queue_put>
    self.assertFalse(lc.has_shm_files())
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 362, in <graph break in queue_put>
    self.assertFalse(lc.has_shm_files())
  File "/opt/conda/lib/python3.7/unittest/case.py", line 699, in assertFalse
    raise self.failureException(msg)
AssertionError: True is not false
------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------
Exception ignored in: <generator object <genexpr> at 0x7fbee36e9ad0>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/setuptools/_vendor/pyparsing/results.py", line 8, in <genexpr>
    _generator_type = type((_ for _ in ()))
SystemError: error return without exception set
/var/lib/jenkins/workspace/test/test_multiprocessing.py:360: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x = torch.DoubleStorage(4)
/var/lib/jenkins/workspace/test/test_multiprocessing.py:360: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x = torch.DoubleStorage(4)
_____________________________________________________________ TestMultiprocessing.test_fs_pool _____________________________________________________________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 355, in test_fs_pool
    self._test_pool(repeat=TEST_REPEATS)
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 327, in _test_pool
    do_test()
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 206, in __exit__
    self.test_case.assertFalse(self.has_shm_files())
  File "/opt/conda/lib/python3.7/unittest/case.py", line 699, in assertFalse
    raise self.failureException(msg)
AssertionError: True is not false
_______________________________________________________ TestMultiprocessing.test_fs_preserve_sharing _______________________________________________________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 351, in test_fs_preserve_sharing
    self._test_preserve_sharing(repeat=TEST_REPEATS)
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 306, in _test_preserve_sharing
    do_test()
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 206, in __exit__
    self.test_case.assertFalse(self.has_shm_files())
  File "/opt/conda/lib/python3.7/unittest/case.py", line 699, in assertFalse
    raise self.failureException(msg)
AssertionError: True is not false
------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------
/opt/conda/lib/python3.7/site-packages/torch/_dynamo/utils.py:1054: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return getattr(args[0], node.target)(*args[1:], **kwargs)
/var/lib/jenkins/workspace/test/test_multiprocessing.py:294: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  data = [x.storage(), x, x[2], x[:, 1]]
/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:1904: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  device=typed_storage.device,
/var/lib/jenkins/workspace/test/test_multiprocessing.py:302: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  self.assertEqual(t.storage()._cdata, storage_cdata)
/var/lib/jenkins/workspace/test/test_multiprocessing.py:294: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  data = [x.storage(), x, x[2], x[:, 1]]
/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:1904: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  device=typed_storage.device,
___________________________________________________________ TestMultiprocessing.test_fs_sharing ____________________________________________________________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 347, in test_fs_sharing
    self._test_sharing(repeat=TEST_REPEATS)
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 289, in _test_sharing
    test_receive()
  File "/var/lib/jenkins/workspace/test/test_multiprocessing.py", line 206, in __exit__
    self.test_case.assertFalse(self.has_shm_files())
  File "/opt/conda/lib/python3.7/unittest/case.py", line 699, in assertFalse
    raise self.failureException(msg)
AssertionError: True is not false
------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------
/var/lib/jenkins/workspace/test/test_multiprocessing.py:274: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  s1 = t1.storage()
/var/lib/jenkins/workspace/test/test_multiprocessing.py:275: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  s2 = t2.storage()
/var/lib/jenkins/workspace/test/test_multiprocessing.py:277: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  self.assertEqual(s1.data_ptr(), s1.data_ptr())
/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:1904: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  device=typed_storage.device,
================================================================= short test summary info ==================================================================
FAILED test_multiprocessing.py::TestMultiprocessing::test_fs - AssertionError: True is not false
FAILED test_multiprocessing.py::TestMultiprocessing::test_fs_pool - AssertionError: True is not false
FAILED test_multiprocessing.py::TestMultiprocessing::test_fs_preserve_sharing - AssertionError: True is not false
FAILED test_multiprocessing.py::TestMultiprocessing::test_fs_sharing - AssertionError: True is not false
======================================================= 4 failed, 1 passed, 32 deselected in 10.09s ========================================================
```

**Comment by huydhn** [comment]
Just a note to keep this open https://hud.pytorch.org/failure/test_fs_sharing%2CTestMultiprocessing
