### ISSUE TITLE
PyTorch 2.0 compiled torch.linspace crashes when given steps=1

### ISSUE THREAD

**Issue by m-lyon** [pytorch/pytorch#91506]
### 🐛 Describe the bug

torch.compile fails when `torch.linspace` is given the arg `step=1`. When omitting the `torch.compile` step the code behaves correctly.

Below is an example of code that will fail.

```python
import torch

class Model(torch.nn.Module):
    def forward(self):
        tensor = torch.linspace(0, 1, 1)

        return tensor

compiled_model = torch.compile(Model())
a = compiled_model()
```

Below is the full traceback.
```
/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py:372: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled.Consider setting `torch.set_float32_matmul_precision('high')`
  warnings.warn(
Traceback (most recent call last):
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/graph.py", line 296, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/lowering.py", line 222, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/lowering.py", line 1346, in linspace
    step_size = (end - start) / (steps - 1)
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 676, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 1032, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/__init__.py", line 1151, in __call__
    return self.compile_fn(model_, inputs_)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 398, in compile_fx
    return aot_autograd(
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/optimizations/training.py", line 78, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2353, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 88, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2050, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_tensor_args, aot_config)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1305, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 955, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 88, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 373, in fw_compiler
    return inner_compile(
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 588, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/debug.py", line 223, in inner
    return fn(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 139, in compile_fx_inner
    graph.run(*example_inputs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 88, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/graph.py", line 170, in run
    return super().run(*args)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/fx/interpreter.py", line 136, in run
    self.env[node] = self.run_node(node)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/graph.py", line 369, in run_node
    result = super().run_node(n)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/fx/interpreter.py", line 177, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/graph.py", line 299, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torch._inductor.exc.LoweringException: ZeroDivisionError: division by zero
  target: aten.linspace.default
  args[0]: 0
  args[1]: 1
  args[2]: 1
  kwargs: {'device': device(type='cpu'), 'pin_memory': False}

While executing %linspace : [#users=1] = call_function[target=torch.ops.aten.linspace.default](args = (0, 1, 1), kwargs = {device: cpu, pin_memory: False})
Original traceback:
Module stack: {}
  File "linspace_problem.py", line 6, in forward
    tensor = torch.linspace(0, 1, 1)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "linspace_problem.py", line 18, in <module>
    a = compiled_model()
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 83, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 88, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1684, in run
    super().run()
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1750, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 529, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 600, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 681, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised LoweringException: ZeroDivisionError: division by zero
  target: aten.linspace.default
  args[0]: 0
  args[1]: 1
  args[2]: 1
  kwargs: {'device': device(type='cpu'), 'pin_memory': False}

While executing %linspace : [#users=1] = call_function[target=torch.ops.aten.linspace.default](args = (0, 1, 1), kwargs = {device: cpu, pin_memory: False})
Original traceback:
Module stack: {}
  File "linspace_problem.py", line 6, in forward
    tensor = torch.linspace(0, 1, 1)


Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Versions

```
PyTorch version: 2.0.0.dev20221225+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 515.86.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.0
[pip3] phd-torch==1.0.0
[pip3] phd-torchscripts==1.0.0
[pip3] pytorch-lightning==1.7.7
[pip3] pytorch-memlab==0.2.4
[pip3] se3-transformer-pytorch==0.8.13
[pip3] torch==2.0.0.dev20221225+cu117
[pip3] torchaudio==2.0.0.dev20221222+cu117
[pip3] torchConvNd==0.2.0
[pip3] torchinfo==1.7.0
[pip3] torchmetrics==0.7.2
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221222+cu117
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.19.2                   pypi_0    pypi
[conda] phd-torch                 1.0.0                     dev_0    <develop>
[conda] phd-torchscripts          1.0.0                     dev_0    <develop>
[conda] pytorch-cuda              11.7                 h67b0de4_1    pytorch
[conda] pytorch-lightning         1.7.7                    pypi_0    pypi
[conda] pytorch-memlab            0.2.4                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] se3-transformer-pytorch   0.8.13                   pypi_0    pypi
[conda] torch                     2.0.0.dev20221225+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20221222+cu117          pypi_0    pypi
[conda] torchconvnd               0.2.0                    pypi_0    pypi
[conda] torchinfo                 1.7.0                    pypi_0    pypi
[conda] torchmetrics              0.7.2                    pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221222+cu117          pypi_0    pypi
```

cc @ezyang @mruberry @ngimel @Lezcano @peterbell10 @soumith @msaroufim @wconstab @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by jancervenka** [comment]
Hi! I tried to fix this in https://github.com/pytorch/pytorch/pull/91578
