### ISSUE TITLE
CUDA error: initialization error

### ISSUE THREAD

**Issue by vors** [pytorch/pytorch#91754]
### 🐛 Describe the bug

Consider the following code.

```python
from multiprocessing import Process
import os
import torch

print(torch.__version__)

@torch.jit.script
def distance_classification():
    return "distance_classification"

class X(torch.nn.Module):
    x = distance_classification()


def train_on_node():
    print(f"XXXXXYYYYZZZZ 3 pid={os.getpid()}")
    torch._C._cuda_init()
    print(f"XXXXXYYYYZZZZ 4 pid={os.getpid()}")
    return 123

p = Process(target=train_on_node, args=())
p.start()
p.join()
```

On PyTorch 1.11 it executed without a problem:
```
1.11.0+cu102
XXXXXYYYYZZZZ 3 pid=3739
XXXXXYYYYZZZZ 4 pid=3739
```

On PyTorch 1.12.0 it throws this error
```
1.12.0+cu102
XXXXXYYYYZZZZ 3 pid=2660
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-7de82f15ef1a>", line 17, in train_on_node
    torch._C._cuda_init()
RuntimeError: !in_bad_fork INTERNAL ASSERT FAILED at "../torch/csrc/cuda/Module.cpp":587, please report a bug to PyTorch. 
```

On PyTorch 1.13.0 it throws this error
```
1.13.0+cu117
XXXXXYYYYZZZZ 3 pid=4944
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-7de82f15ef1a>", line 17, in train_on_node
    torch._C._cuda_init()
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

I'd like to understand if is this a regression or intended behavior. If it's intended behavior, what would be a recommendation to fix it in our user code?

### Versions

1.13.0
1.12.0

**Comment by ngimel** [comment]
Thanks for reporting, looks like regression.

**Comment by ptrblck** [comment]
A quick check of removing `torch::jit::fuser::cuda::isEnabled()` in [`getOptimizedPlanFor`](https://github.com/pytorch/pytorch/blob/e33f3229a23be2984b3b9b68e097f7a75125c46e/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp#L654) allows the code snippet to pass. This is of course not the right solution, but I was wondering if:
* the call into [`nvfuserCanBeEnabled`](https://github.com/pytorch/pytorch/blob/7b419e8513a024e172eae767e24ec1b849976b13/torch/csrc/jit/codegen/cuda/interface.cpp#L45) could be delayed until the method should be executed instead of during the function definition
* or if the `at::globalContext().hasCUDA()` call could be replaced with a weaker method such as `is_compiled` introduced in https://github.com/pytorch/pytorch/pull/84877/files (this is a pure Python method for now but maybe a similar approach could be done in the backend). I'm unsure if a less strict check could have other side effects. 

CC @kevinstephano
