### ISSUE TITLE
torch.jit.trace failure in custom dynamo backend for a Bert model

### ISSUE THREAD

**Issue by anwang2009** [pytorch/pytorch#91780]
### 🐛 Describe the bug

FakeTensor causes a simple graph to fail torch.jit.trace with a `torch._subclasses.fake_tensor.DataDependentOutputException: aten._local_scalar_dense.default`. Is tracing no longer supported in dynamo backends?

to repro:

```python
import torch
from torch import _dynamo as dynamo

def backend_fn(gm: torch.fx.GraphModule, example_inputs):
    torchscript = torch.jit.trace(gm, example_inputs)
    example_outputs = torchscript(*example_inputs)
    print("example outputs", example_outputs)

@dynamo.optimize(backend_fn)
def add_one(x):
    return x + 1

x = torch.ones((2, 2))
add_one(x)
```

This worked fine with approx version `1.14.0.dev20221118+cu117`. Here is the full stack trace:
```
Traceback (most recent call last):
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1224, in assert_equal
    pair.compare()
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/testing/_comparison.py", line 704, in compare
    self._compare_values(actual, expected)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/testing/_comparison.py", line 822, in _compare_values
    compare_fn(
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/testing/_comparison.py", line 995, in _compare_regular_values_close
    if torch.all(matches):
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 639, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 908, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 386, in local_scalar_dense
    raise DataDependentOutputException(func)
torch._subclasses.fake_tensor.DataDependentOutputException: aten._local_scalar_dense.default

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 680, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 1032, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/anwang/dynamite/examples/repro.py", line 7, in backend_fn
    torchscript = torch.jit.trace(gm, example_inputs)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/jit/_trace.py", line 792, in trace
    return trace_module(
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/jit/_trace.py", line 1076, in trace_module
    _check_trace(
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/jit/_trace.py", line 553, in _check_trace
    if compare_outputs(traced_outs, fn_outs, "Python function"):
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/jit/_trace.py", line 527, in compare_outputs
    torch.testing.assert_close(
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1493, in assert_close
    assert_equal(
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1230, in assert_equal
    raise RuntimeError(
RuntimeError: Comparing

TensorLikePair(
    id=(),
    actual=FakeTensor(FakeTensor(..., device='meta', size=(2, 2), dtype=torch.float64), cpu),
    expected=FakeTensor(FakeTensor(..., device='meta', size=(2, 2), dtype=torch.float64), cpu),
    rtol=1e-05,
    atol=1e-05,
    equal_nan=True,
    check_device=True,
    check_dtype=True,
    check_layout=True,
    check_stride=False,
    check_is_coalesced=True,
)

resulted in the unexpected exception above. If you are a user and see this message during normal operation please file an issue at https://github.com/pytorch/pytorch/issues. If you are a developer and working on the comparison functions, please except the previous error and raise an expressive `ErrorMeta` instead.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anwang/dynamite/examples/repro.py", line 18, in <module>
    add_one(x)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 88, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1684, in run
    super().run()
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1750, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 533, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 604, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/anwang/.pyenv/versions/3.9.7/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 685, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: backend_fn raised RuntimeError: Comparing
```

### Versions

[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230105+cu117
[pip3] torchaudio==2.0.0.dev20230105+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20230105+cu117

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
This works (need to add `check_trace=False` argument:
```
import torch
from torch import _dynamo as dynamo

def backend_fn(gm: torch.fx.GraphModule, example_inputs):
    torchscript = torch.jit.trace(gm, example_inputs, check_trace=False)
    example_outputs = torchscript(*example_inputs)
    print("example outputs", example_outputs)
    return torchscript

@dynamo.optimize(backend_fn)
def add_one(x):
    return x + 1

x = torch.ones((2, 2))
add_one(x)
```

**Comment by ngimel** [comment]
Closing, @anwang2009 please reopen if this workaround is not acceptable

**Comment by anwang2009** [comment]
Ok, turns out the model I was originally having trouble with is still failing with `check_trace=False` 🤔 Let me know if I should open another issue

Here's the error I'm seeing: `BackendCompilerFailed: backend_fn raised Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.embedding.default(*(Parameter containing:`

here's the full repro. 

```python
import torch
from torch import _dynamo as dynamo
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification


def backend_fn(gm: torch.fx.GraphModule, example_inputs):
    torchscript = torch.jit.trace(gm, example_inputs, check_trace=False)
    example_outputs = torchscript(*example_inputs)
    print("example outputs", example_outputs)
    return torchscript

model_id = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = DistilBertTokenizer.from_pretrained(model_id)
model = DistilBertForSequenceClassification.from_pretrained(model_id).eval()

examples = [
    "Hello, world!",
    "Goodbye, world!"
]

inputs = tokenizer(examples, return_tensors="pt")

@dynamo.optimize(backend_fn)
def run(inputs):
    return model(**inputs)

with torch.no_grad():
    result = run(inputs)

predicted_class_ids = result.logits.argmax(dim=1)

for id in predicted_class_ids.numpy():
    print(model.config.id2label[id])
```

**Comment by anwang2009** [comment]
Ok, turns out the model I was originally having trouble with is still failing with `check_trace=False` 🤔 Let me know if I should open another issue

Here's the error I'm seeing: `BackendCompilerFailed: backend_fn raised Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.embedding.default(*(Parameter containing:`

here's the full repro. 

```python
import torch
from torch import _dynamo as dynamo
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification


def backend_fn(gm: torch.fx.GraphModule, example_inputs):
    torchscript = torch.jit.trace(gm, example_inputs, check_trace=False)
    example_outputs = torchscript(*example_inputs)
    print("example outputs", example_outputs)
    return torchscript

model_id = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = DistilBertTokenizer.from_pretrained(model_id)
model = DistilBertForSequenceClassification.from_pretrained(model_id).eval()

examples = [
    "Hello, world!",
    "Goodbye, world!"
]

inputs = tokenizer(examples, return_tensors="pt")

@dynamo.optimize(backend_fn)
def run(inputs):
    return model(**inputs)

with torch.no_grad():
    result = run(inputs)

predicted_class_ids = result.logits.argmax(dim=1)

for id in predicted_class_ids.numpy():
    print(model.config.id2label[id])
```

**Comment by ezyang** [comment]
Cc @tugsbayasgalan @eellison @Chillee

**Comment by eellison** [comment]
@anwang2009 any particular reason you are using torchscript instead of the default inductor backend ?

**Comment by anwang2009** [comment]
I would like serialization

**Comment by ezyang** [comment]
cc export crew @SherlockNoMad @suo @voznesenskym

**Comment by anwang2009** [comment]
I see you've added `@fake_tensor_unsupported`. Thank you!

**Comment by akshaybaviskar** [comment]
> I see you've added `@fake_tensor_unsupported`. Thank you!

I am getting the same issue as above, with `check_trace=False` I get `BackendCompilerFailed: backend_fn raised Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'.`
How was this resolved?

**Comment by anwang2009** [comment]
@akshaybaviskar you can do something like this
```
def _convert_symval_to_tensor(x):
    if isinstance(x, (torch.SymInt, torch.SymBool, torch.SymFloat)):
        return torch.tensor(x.node.hint)
    else:
        return x

@fake_tensor_unsupported
def _defake_tensors(gm, defaked_example_inputs):
    return list(map(_convert_symval_to_tensor, defaked_example_inputs))

def backend_fn(gm: torch.fx.GraphModule, example_inputs):
    defaked_example_inputs = _defake_tensors(gm, example_inputs)
    torchscript = torch.jit.trace(gm, defaked_example_inputs)
    example_outputs = torchscript(*defaked_example_inputs)

```
