### ISSUE TITLE
dynamo specializing the size of module's tensor attribute

### ISSUE THREAD

**Issue by ydwu4** [pytorch/pytorch#91901]
### 🚀 The feature, motivation and pitch

When using dynamo to export a module, we'd like to specialize on the shape of its tensor attributes in order to support use cases like below.

```python
import torch
import torch._dynamo as dynamo
dynamo.config.dynamic_shapes = True

class MyModule(torch.nn.Module):
    def __init__(self, const_w):
        super().__init__()
        self.w = const_w
   
    def forward(self, x):
        if len(self.w) == 0:
            return x
        else:
            return x + 1

const_w = torch.ones((4, 5))

def test():
    mod = MyModule(const_w)
    d = torch.ones(2)
    gm, guards = dynamo.export(mod.forward, d)

test()
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by voznesenskym** [comment]
Removing export:

```
import torch
import torch._dynamo as dynamo
dynamo.config.dynamic_shapes = True

class MyModule(torch.nn.Module):
    def __init__(self, const_w):
        super().__init__()
        self.w = const_w
   
    def forward(self, x):
        if len(self.w) == 0:
            return x
        else:
            return x + 1

const_w = torch.ones((4, 5))

mod = MyModule(const_w)
d = torch.ones(2)
dynamo.optimize("eager")(mod.forward)(d)
```

I get 

`'SymInt' object cannot be interpreted as an integer`

Not an export bug - but worth looking into for dyn shapes.

**Comment by ezyang** [comment]
to be clear, the full trace is

```
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 1078, in run_node
    return node.target(*args, **kwargs)
TypeError: 'SymInt' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 1037, in get_fake_value
    return wrap_fake_exception(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 714, in wrap_fake_exception
    return fn()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 1038, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 1090, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <built-in function len>(*(FakeTensor(FakeTensor(..., device='meta', size=(s1, s2)), cpu),), **{}):
'SymInt' object cannot be interpreted as an integer
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/foo.py", line 20, in <module>
    dynamo.optimize("eager")(mod.forward)(d)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 94, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 1684, in run
    super().run()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 307, in wrapper
    return inner_fn(self, inst)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 966, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/symbolic_convert.py", line 435, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/builtin.py", line 322, in call_function
    result = handler(tx, *args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/builtin.py", line 548, in call_len
    return args[0].call_method(tx, "__len__", args[1:], kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/tensor.py", line 319, in call_method
    return wrap_fx_proxy(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/builder.py", line 731, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/variables/builder.py", line 766, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 1057, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError: 

from user code:
   File "/data/users/ezyang/a/pytorch/foo.py", line 11, in forward
    if len(self.w) == 0:

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True


```

**Comment by ezyang** [comment]
The problem is that len() requires you to return an actual int, but because the len of a tensor is equivalent to x.size(0) and needs to return a SymInt. The fix is to not use the built-in len and implement this logic ourselves. I am happy to review a PR that does this.
