### ISSUE TITLE
elastic job failed when scale down

### ISSUE THREAD

**Issue by davidstack** [pytorch/pytorch#91943]
### 🐛 Describe the bug

i run one job with three worker in k8s cluster,just like this command:
```shell
torchrun --nnodes=1:3 --nproc_per_node=1 --rdzv_id=1 --rdzv_backend=c10d --max_restarts=100 --rdzv_endpoint=172.22.154.120:60001 /wdk/elasticjob/pytorch/main.py --arch resnet50 --epochs 100 --batch-size 128 /wdk/imagenet/
```
when i delete a worker,the  job should keep running .but in my test,the job is terminated,the worker0 job is like this
![image](https://user-images.githubusercontent.com/5036200/211448842-76590e23-ab00-48fd-9bcf-614f890f1417.png)
![image](https://user-images.githubusercontent.com/5036200/211448861-2f367af1-875b-44e0-a0f2-035862926986.png)

the worker 1 log is like this:
![image](https://user-images.githubusercontent.com/5036200/211448941-1f99b21a-5fa2-4148-b393-c0c0939ee8a7.png)

any suggestions? thanks

### Versions

1.13

**Comment by d4l3k** [comment]
Can you try rerunning this with `LOGLEVEL=DEBUG` or `INFO` to get more information on the rendezvous error?

cc @kiukchung

**Comment by davidstack** [comment]
i use ctrl+c  to terminate one worker process. the worker 0 log is like this:
`
root@2usvea5pf85qb-0:/wangdk# torchrun --nnodes=1:3 --nproc_per_node=1 --rdzv_id=1 --rdzv_backend=c10d --max_restarts=100 --rdzv_endpoint=172.21.114.242:60001 /wangdk/elasticjob/pytorch/main.py --arch resnet50 --epochs 100 --batch-size 128 /wangdk/imagenet/
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : /wangdk/elasticjob/pytorch/main.py
  min_nodes        : 1
  max_nodes        : 3
  nproc_per_node   : 1
  run_id           : 1
  rdzv_backend     : c10d
  rdzv_endpoint    : 172.21.114.242:60001
  rdzv_configs     : {'timeout': 900}
  max_restarts     : 100
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_6bge4c0j/1_4qbphyvq
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=2usvea5pf85qb-0
  master_port=55539
  group_rank=0
  group_world_size=3
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[3]
  global_world_sizes=[3]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_6bge4c0j/1_4qbphyvq/attempt_0/0/error.json
=> set cuda device = 0
=> creating model: resnet50
=> no workers have checkpoints, starting from epoch 0
=> start_epoch: 0, best_acc1: 0
Epoch: [0][ 0/68]       Time  9.123 ( 9.123)    Data  4.943 ( 4.943)    Loss 7.0963e+00 (7.0963e+00)    Acc@1   0.00 (  0.00)  Acc@5   0.00 (  0.00)
Epoch: [0][10/68]       Time  6.651 ( 6.576)    Data  4.328 ( 4.479)    Loss 1.6200e+01 (1.1323e+01)    Acc@1   5.47 (  4.33)  Acc@5  25.00 ( 23.86)
[E ProcessGroupNCCL.cpp:341] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error: unhandled system error, NCCL version 21.0.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 2019) of binary: /usr/bin/python
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 100/100 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "RendezvousClosedError: ",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 345, in wrapper\n    return f(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/run.py\", line 719, in main\n    run(args)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/run.py\", line 713, in run\n    )(*cmd_args)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/launcher/api.py\", line 131, in __call__\n    return launch_agent(self._config, self._entrypoint, list(args))\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/launcher/api.py\", line 252, in launch_agent\n    result = agent.run()\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/agent/server/api.py\", line 709, in run\n    result = self._invoke_run(role)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/agent/server/api.py\", line 866, in _invoke_run\n    self._restart_workers(self._worker_group)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/agent/server/api.py\", line 700, in _restart_workers\n    self._initialize_workers(worker_group)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/agent/server/api.py\", line 678, in _initialize_workers\n    self._rendezvous(worker_group)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/agent/server/api.py\", line 538, in _rendezvous\n    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py\", line 1024, in next_rendezvous\n    self._op_executor.run(join_op, deadline)\n  File \"/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py\", line 634, in run\n    raise RendezvousClosedError()\ntorch.distributed.elastic.rendezvous.api.RendezvousClosedError\n",
      "timestamp": "1674887871"
    }
  }
}
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launcher/api.py", line 252, in launch_agent
    result = agent.run()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/agent/server/api.py", line 866, in _invoke_run
    self._restart_workers(self._worker_group)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/agent/server/api.py", line 700, in _restart_workers
    self._initialize_workers(worker_group)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
    self._rendezvous(worker_group)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/agent/server/api.py", line 538, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1024, in next_rendezvous
    self._op_executor.run(join_op, deadline)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 634, in run
    raise RendezvousClosedError()
torch.distributed.elastic.rendezvous.api.RendezvousClosedError
`
