### ISSUE TITLE
export does not support boolean tensor indexing

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#91990]
```
import torch._dynamo
torch._dynamo.config.dynamic_shapes=True
def foo(images, handedness):
    right_hand_mask = handedness == 1
    images[right_hand_mask] = images[right_hand_mask].flip(-1)

torch._dynamo.export(foo, torch.randint(0, 256, (512, 1, 1, 96, 96)), torch.randint(0, 1, (512, 1, 1)))
```
raises:
```
dynamic shape operator: aten.index.Tensor
```

My ideal behavior would be that we are capable of returning a tensor with "new" shapes that are unbacked symints, similar to what we want from nonzero. 

Internal command to reproduce the issue: P595150412

cc @ezyang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @mlazos @soumith @yanboliang @anijain2305 @chunyuan-w @Xia-Weiwen @desertfire

**Comment by ezyang** [comment]
the full backtrace

```
Traceback (most recent call last):
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/utils.py", line 1078, in run_node
    return node.target(*args, **kwargs)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_subclasses/fake_tensor.py", line 908, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_subclasses/fake_tensor.py", line 431, in index_tensor
    check_no_bool_index_tensors(func, *args, **kwargs)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_subclasses/fake_tensor.py", line 410, in check_no_bool_index_tensors
    raise DynamicOutputShapeException(func)
torch._subclasses.fake_tensor.DynamicOutputShapeException: aten.index.Tensor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/utils.py", line 1037, in get_fake_value
    return wrap_fake_exception(
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/utils.py", line 714, in wrap_fake_exception
    return fn()
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/utils.py", line 1038, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/utils.py", line 1090, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <built-in function getitem>(*(FakeTensor(FakeTensor(..., device='meta', size=(s0, 1, 1, s1, s1), dtype=torch.int64), cpu), FakeTensor(FakeTensor(..., device='meta', size=(s0, 1, 1), dtype=torch.bool), cpu)), **{}):
aten.index.Tensor
(scroll up for backtrace)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ezyang/Dev/pytorch-cpu/b.py", line 7, in <module>
    torch._dynamo.export(foo, torch.randint(0, 256, (512, 1, 1, 96, 96)), torch.randint(0, 1, (512, 1, 1)))
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/eval_frame.py", line 623, in export
    result_traced = opt_f(*args, **kwargs)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/utils.py", line 94, in time_wrapper
    r = func(*args, **kwargs)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/symbolic_convert.py", line 1692, in run
    super().run()
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/symbolic_convert.py", line 307, in wrapper
    return inner_fn(self, inst)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/symbolic_convert.py", line 137, in impl
    self.push(fn_var.call_function(self, self.popn(nargs), {}))
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/variables/builtin.py", line 288, in call_function
    return wrap_fx_proxy(tx, proxy, **options)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/variables/builder.py", line 731, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/variables/builder.py", line 766, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/utils.py", line 1056, in get_fake_value
    unimplemented(f"dynamic shape operator: {cause.func}")
  File "/Users/ezyang/Dev/pytorch-cpu/torch/_dynamo/exc.py", line 67, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: dynamic shape operator: aten.index.Tensor

from user code:
   File "/Users/ezyang/Dev/pytorch-cpu/b.py", line 5, in foo
    images[right_hand_mask] = images[right_hand_mask].flip(-1)

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```

(these backtraces are useful, I encourage people to post them in the issue)

**Comment by ngimel** [comment]
@suo if you get a tensor with unbacked SymInts, how long do you expect it to last before the next error happens (e.g. it participates in a pointwise op so you have to guard that its unknown size is equal to something, or triton wants to guard on the size being multiple of 16). In a good case you'd reduce over SymInt dimension, to take a fixed size slice along it, and SymInt will disappear, but I'm wondering  how often good vs bad cases happen.

**Comment by suo** [comment]
In the case of this model (and we've seen similar patterns elsewhere), the unbacked-symint-shaped tensor is immediately "consumed", e.g. we use it to mask and flip images in the batch but then don't keep it live. So far we haven't seen a "bad" case actually, but I'm not confident that that's not just sampling bias.

**Comment by ngimel** [comment]
Ok, cool, if there's a nontrivial number of good cases then we should support it.

**Comment by bobrenjc93** [comment]
doesn't repro anymore, closing this out
