### ISSUE TITLE
PyTorch 2.0:      KeyError: 'JUMP_ABSOLUTE'  when using torch.compile()

### ISSUE THREAD

**Issue by TejaGollapudi** [pytorch/pytorch#92112]
## Issue description

I get the following error when I try to use torch.compile()

    dis.opmap["JUMP_ABSOLUTE"],
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'JUMP_ABSOLUTE'


## Code example
import torch

print(torch.cuda.is_available())

def fn(x, y):
    a = torch.sin(x).cuda()
    b = torch.sin(y).cuda()
    return a + b
new_fn = torch.compile(fn, backend="inductor")
input_tensor = torch.randn(10000).to(device="cuda:0")
a = new_fn()

## Stack trace

True
Traceback (most recent call last):
  File "/home/projects/project-vaqa-qa/torch-2.0/test.py", line 9, in <module>
    new_fn = torch.compile(fn, backend="inductor")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projects/project-vaqa-qa/torch-2.0/torch-nightly/lib/python3.11/site-packages/torch/__init__.py", line 1285, in compile
    import torch._dynamo
  File "/home/projects/project-vaqa-qa/torch-2.0/torch-nightly/lib/python3.11/site-packages/torch/_dynamo/__init__.py", line 1, in <module>
    from . import allowed_functions, convert_frame, eval_frame, resume_execution
  File "/home/projects/project-vaqa-qa/torch-2.0/torch-nightly/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 16, in <module>
    from .bytecode_analysis import remove_dead_code, remove_pointless_jumps
  File "/home/projects/project-vaqa-qa/torch-2.0/torch-nightly/lib/python3.11/site-packages/torch/_dynamo/bytecode_analysis.py", line 8, in <module>
    dis.opmap["JUMP_ABSOLUTE"],
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'JUMP_ABSOLUTE'



## System Info

PyTorch version: 2.0.0.dev20230111+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-62-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: GRID V100D-16C
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230111+cu117

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by soumith** [comment]
Python 3.11 is not yet supported, and thats why the error. we are working on it.

**Comment by TejaGollapudi** [comment]
Thank you for clarifying.
