### ISSUE TITLE
[Bug][Dataloader] unable to mmap 2048 bytes from file <filename not specified>: Cannot allocate memory (12)

### ISSUE THREAD

**Issue by zejun-chen** [pytorch/pytorch#92134]
### 🐛 Describe the bug

Hi,

Here is the results i observed when i was running my workload with PyTorch 1.13 on Ubuntu 20.04 to train RN50 with imageNet:
When i run 25 epochs, the error is thrown as below:

```
Epoch: [25][3096/5005]	Time  0.551 ( 0.548)	Data  0.000 ( 0.001)	Loss 1.9055e+00 (2.1268e+00)	Acc@1  57.81 ( 51.79)	Acc@5  79.69 ( 76.05)
Epoch: [25][3097/5005]	Time  0.547 ( 0.548)	Data  0.000 ( 0.001)	Loss 1.9593e+00 (2.1268e+00)	Acc@1  55.08 ( 51.80)	Acc@5  81.25 ( 76.06)
Exception in thread Thread-52:
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/zejun/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/gta/miniconda3/envs/zejun/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gta/miniconda3/envs/zejun/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 52, in _pin_memory_loop
    do_one_step()
  File "/home/gta/miniconda3/envs/zejun/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 29, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/gta/miniconda3/envs/zejun/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/gta/miniconda3/envs/zejun/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    storage = cls.**_new_shared_fd**(fd, size)
**RuntimeError: falseINTERNAL ASSERT FAILED** at "/home/gta/zejun/pytorch/aten/src/ATen/MapAllocator.cpp":323, please report a bug to PyTorch. **unable to mmap 2048 bytes** from file <filename not specified>: **Cannot allocate memory (12)**
```

This Runtime Error is thrown from torch dataloader. I found the community has had this issue: https://discuss.pytorch.org/t/pytorch-cannot-allocate-memory/134754.

I set the dataloader workers to be 0 and the error is missing, but the training time increases too much when using the single process to fetch and decode the dataset. I also check the host memory usage and no oom happen. The fd limitation of one process is also not exceeded. Thus we wonder if the issue can be fixed, otherwise it may block the model training with PyTorch.

### Versions

PyTorch 1.13
Python 3.8
Torchvision 1.14
RN50 + ImageNet

**Comment by ejguan** [comment]
Based on the log, it implies you just ran out of shared memory. It would be good if you can share a minimum script.

**Comment by zejun-chen** [comment]
> Based on the log, it implies you just ran out of shared memory. It would be good if you can share a minimum script.

Thank you for your attention. We encounter this error when running the pytorch example for RN50 in the below link:
https://github.com/pytorch/examples/blob/main/imagenet/main.py

We enable this model script on XPU and got this mmap issue. (Cannot allocate the memory)
When i set the dataloader workers to 0, the error is gone.

We are using 64bit Linux machine. The mmap can map files into a excessive virtual memory space with large size in theory. The memory mapping segments could be very large. Is it possible the munmap is demand releasing memory, so the virtual memory mapped by previous iterations are not immediately released, then the memory mapping segments don't have enough size for next iteration dataloader's mapping ? Additionally, this issue needs to run much time to reproduce. It needs about running 50 epochs.

**Comment by zejun-chen** [comment]
@ejguan Thank you for sharing the link.
We checked our failure and it is not caused by exceeding the limitation of the opened fd resources in OS.
We wonder here failed mmap is _**mapping the opened disk file into the worker's memory space**_ or **_mapping the shared memory from other workers in to this process_** ?

**Comment by ejguan** [comment]
You might want to profile your training script to see when you run out of memory. You might be able to rely on `psutil` to check your shared memory during each step

**Comment by zejun-chen** [comment]
@ejguan Thank you for your help. I will check the memory footprint with psutil.
I see here is a open issue related to above: https://github.com/pytorch/pytorch/issues/13246

**Comment by zejun-chen** [comment]
Hi, @ejguan 

I check the memory usage with `psutil`. Here is the log:
```
epoch =  1 . iter =  809
svmem(total=540768874496, available=523621277696, percent=3.2, used=11168075776, free=287612063744, active=145943617536, inactive=90581217280, buffers=1317834752, cached=240670900224, shared=2472620032, slab=11804663808)
sswap(total=0, used=0, free=0, percent=0.0, sin=0, sout=0)

epoch =  1 . iter =  810
svmem(total=540768874496, available=523618697216, percent=3.2, used=11170656256, free=287609483264, active=145943617536, inactive=90583797760, buffers=1317834752, cached=240670900224, shared=2472620032, slab=11804909568)
sswap(total=0, used=0, free=0, percent=0.0, sin=0, sout=0)

epoch =  1 . iter =  811
svmem(total=540768874496, available=523610955776, percent=3.2, used=11178397696, free=287601741824, active=145943617536, inactive=90591539200, buffers=1317834752, cached=240670900224, shared=2472620032, slab=11804909568)
sswap(total=0, used=0, free=0, percent=0.0, sin=0, sout=0)

epoch =  1 . iter =  812
svmem(total=540768874496, available=523675918336, percent=3.2, used=11113103360, free=287665991680, active=145958989824, inactive=90516205568, buffers=1317834752, cached=240671944704, shared=2472976384, slab=11804872704)
sswap(total=0, used=0, free=0, percent=0.0, sin=0, sout=0)
```

For the shared memory usage, there is no sharply increasing found.

**Comment by zejun-chen** [comment]
Hi, @ejguan 

Here is a linked issue, which is similar with the error message i reported in this kicked off jira.
https://github.com/pytorch/pytorch/issues/65198

I checked the FD the worker consumes while no FD exceeding is found.

**Comment by zejun-chen** [comment]
Hi, @ejguan 

Sorry to interrupt you. I have some confusion about how the pytorch dataloader works with multi workers.
![image](https://user-images.githubusercontent.com/74231238/222306173-4878c647-b76a-4b6a-a060-1912d19037a9.png)

Here the workers will put their result data into the data queue. The worker process will call `reduce_tensor `and `reduce_storage`. Then the main process will call `rebuild_storage_fd`. I wonder why the `reduce_tensor `and `reduce_storage `need to be called ?

**Comment by ejguan** [comment]
>  I wonder why the reduce_tensor and reduce_storage need to be called ?

We need to move the underlying data to shared memory then the main process would be able to get data from worker process.

**Comment by zejun-chen** [comment]
> > I wonder why the reduce_tensor and reduce_storage need to be called ?
> 
> We need to move the underlying data to shared memory then the main process would be able to get data from worker process.

Thank you for your reply. I see the worker will immediately delete the data when it finishes the processing and put data into the queue. The code is here: https://github.com/pytorch/pytorch/blob/728dfeee486fbd965710ccbb225fd275dd7bd35c/torch/utils/data/_utils/worker.py#L323
Does it mean the data queue will move this data from worker's virtual memory space into the /dev/shm ?
Then the data queue will wait for main process to use `mmap` to map this memory from /dev/shm into its virtual memory space ?

**Comment by ejguan** [comment]
> Does it mean the data queue will totally copy this data from worker's virtual memory space into the /dev/shm so the worker can safely `del data` ?
> Then the data queue will wait for main process to use `mmap` to map this memory from /dev/shm into its virtual memory space ?

Right.

**Comment by ASMIftekhar** [comment]
Hi @zejun-chen, did you find a solution to the problem?

**Comment by zejun-chen** [comment]
> Hi @zejun-chen, did you find a solution to the problem?

Hi, @ASMIftekhar 
We have no root cause but this issue disappeared now after we fixed a host mem leak issue in our project.
If you also met this problem, you can set the OS mmap limitation much higher as a work around. Or set the worker = 0 in dataloader also helps.
Thank you.

**Comment by ASMIftekhar** [comment]
Hello,
I am just writing the workable solution for my case. I didnt do a deep analysis. From my dataloader, I was returning images(almost 12K images) and annotations (a list of size ~12K, each element in the list is a python dictionary) for every mini-batch. For 'file_system' sharing strategy, the workers dumped the fetched data in /dev/shm (mentioned above by @zejun-chen) and main process reads them via mmap. The error is coming from this reading. Instead of returning, a list for annotations, I wrapped it in the following way:
`return images, pickle.dumps(annotations)`. Then while reading, I just used (pickle.loads). Error is gone in this way.
 
 I get this idea from: [this blog](https://ppwwyyxx.com/blog/2022/Demystify-RAM-Usage-in-Multiprocess-DataLoader/) and [this issue](https://github.com/pytorch/pytorch/issues/13246#issuecomment-905703662)

**Comment by zejun-chen** [comment]
Hello, @ASMIftekhar 
Thank you for sharing. It looks like the read using pickle.dump will not trigger the COW of the annotations(python object). Then the host mem or /dev/shm will not be consumed out, thus the mmap issue(cannot allocate mem) is gone.
Thank you.

**Comment by prefer-potato** [comment]
i meet a same problem. and it is solved when i init 'data_list' in '__getitem__()' instead of '__init__()' in a Dataset class.
class my_dataset(Dataset):
def __init__():
     self.data_list=[]
     ******

def init_data_list():
    ******

def __init__():
     if data_list() == []:
            self.init_data_list()

**Comment by GoenitzYs** [comment]
Hello, I met the problem, too. Finally, I found the problem might be in the customized allocation function adopted by the `dataloader` (`collate_fn=...`), which might cause the problem when the return type is "`list`" and "`tuple`". 

As I used `DGL` library and the data structure is `dgl.DGLGraph`, I solved the problem by merging the group of the graphs using `dg.batch()` in the allocation function, and the problem is gone since I returned a tuple of `dgl.DGLGraph` object rather than a group of graph lists or tuples.

Anyway, anyone who is confronted with the same problem could try this solution, I believe the problem might be caused by not just one reason, but the approach might also be the solution of one of them :)

**Comment by ZhiyuanChen** [comment]
> Hello, I met the problem, too. Finally, I found the problem might be in the customized **allocation** function adopted by the `Dataloader` (`collate_fn=...`), which might cause the problem when the return type is "`list`" or "`tuple`".
> 
> As I utilized `DGL` library and the data structure is `dgl.DGLGraph`, I solved the problem by merging the group of the graphs using `dg.batch()` in the allocation function, and the problem is gone when the allocation functoin returned a tuple of `dgl.DGLGraph` object rather than a group of graph lists or tuples.
> 
> Anyway, anyone who is confronted with the same problem could try this solution, I believe the problem might be caused by not just one reason, but the approach might also be the solution of one of them :)

I believe this is the key, as we encountered this problem just like you.

**Comment by uanu2002** [comment]
> Hello, I met the problem, too. Finally, I found the problem might be in the customized **allocation** function adopted by the `Dataloader` (`collate_fn=...`), which might cause the problem when the return type is "`list`" or "`tuple`".
> 
> As I utilized `DGL` library and the data structure is `dgl.DGLGraph`, I solved the problem by merging the group of the graphs using `dg.batch()` in the allocation function, and the problem is gone when the allocation functoin returned a tuple of `dgl.DGLGraph` object rather than a group of graph lists or tuples.
> 
> Anyway, anyone who is confronted with the same problem could try this solution, I believe the problem might be caused by not just one reason, but the approach might also be the solution of one of them :)

I encountered the same problem as you, but when I set num_workers to 0, or reduced the data set size, the problem disappeared. Is there a better solution?

**Comment by wangtianrui** [comment]
set num_workers=0 can solve this problem.
