### ISSUE TITLE
NameError: name 'sympy' is not defined - still exists in CPU build from source installation

### ISSUE THREAD

**Issue by vinubama** [pytorch/pytorch#92172]
### 🐛 Describe the bug

I tried to build the pytorch from source for a CPU version on a Ubuntu  OS

Steps I followed:
1. Created a Conda environment
2. Installed the dependancies `conda install astunparse numpy ninja pyyaml setuptools cmake cffi typing_extensions future six requests dataclasses`  and `export CMAKE_PREFIX_PATH=/home/mcw/miniconda3/envs/pytorch_build/`
3. To avoid conda symbolic link mistakes did this change `cd ~/miniconda3/envs/pytorch-build/compiler_compat
mv ld ld-old`
4. Explicitly installed the openMP `sudo apt-get install libomp-dev`
5. Repo clone, `git clone --recursive https://github.com/pytorch/pytorch`
6. Since its a CPU based installation, `export USE_CUDA=0 USE_CUDNN=0 USE_MKLDNN=1
cd ~/pytorch
python setup.py install`
7. Installation was completed, then to verify the installtion , tried 
```
(pytorch_build) mcw@cluster-29:~/Vinubama/vision$ python -c "import torch"
No sympy found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mcw/miniconda3/envs/pytorch_build/lib/python3.10/site-packages/torch/__init__.py", line 1316, in <module>
    from . import _meta_registrations
  File "/home/mcw/miniconda3/envs/pytorch_build/lib/python3.10/site-packages/torch/_meta_registrations.py", line 7, in <module>
    from torch._decomp import _add_op_to_registry, global_decomposition_table, meta_table
  File "/home/mcw/miniconda3/envs/pytorch_build/lib/python3.10/site-packages/torch/_decomp/__init__.py", line 168, in <module>
    import torch._decomp.decompositions
  File "/home/mcw/miniconda3/envs/pytorch_build/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 10, in <module>
    import torch._prims as prims
  File "/home/mcw/miniconda3/envs/pytorch_build/lib/python3.10/site-packages/torch/_prims/__init__.py", line 33, in <module>
    from torch._subclasses.fake_tensor import FakeTensor, FakeTensorMode
  File "/home/mcw/miniconda3/envs/pytorch_build/lib/python3.10/site-packages/torch/_subclasses/__init__.py", line 3, in <module>
    from torch._subclasses.fake_tensor import (
  File "/home/mcw/miniconda3/envs/pytorch_build/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 12, in <module>
    from torch._guards import Source
  File "/home/mcw/miniconda3/envs/pytorch_build/lib/python3.10/site-packages/torch/_guards.py", line 78, in <module>
    class ShapeGuard(NamedTuple):
  File "/home/mcw/miniconda3/envs/pytorch_build/lib/python3.10/site-packages/torch/_guards.py", line 79, in ShapeGuard
    expr: sympy.Expr
NameError: name 'sympy' is not defined
```

CMAKE version: 3.22.1
torch version tried: 2.0

packages listed in pip list,
`(pytorch_build) mcw@cluster-29:~/Vinubama/vision$ pip list
Package            Version
------------------ ------------------
astunparse         1.6.3
brotlipy           0.7.0
certifi            2022.12.7
cffi               1.15.1
charset-normalizer 2.0.4
cryptography       38.0.4
flit_core          3.6.0
future             0.18.2
idna               3.4
mkl-fft            1.3.1
mkl-random         1.2.2
mkl-service        2.4.0
numpy              1.23.5
pip                22.3.1
pycparser          2.21
pyOpenSSL          22.0.0
PySocks            1.7.1
PyYAML             6.0
requests           2.28.1
setuptools         65.6.3
six                1.16.0
torch              2.0.0a0+git4d07ad7
typing_extensions  4.4.0
urllib3            1.26.13
wheel              0.37.1`

Similar issue: [https://github.com/pytorch/vision/issues/7034](url)
[https://github.com/pytorch/pytorch/issues/90696](url)

### Versions

torch version - 2.0

**Comment by ptrblck** [comment]
`sympy` is tagged as a dependency in [`requirements.txt`](https://github.com/pytorch/pytorch/blob/4d07ad74f1c11efa55501433d6cf1f06840f5207/requirements.txt#L14) while it seems to be missing in your environment.
Could you install it (and other requirements) and see if this solves the issue?

**Comment by vinubama** [comment]
Thanks, issue resolved

Steps I did:
`conda install --file requirements.txt`
then did `export USE_CUDA=0 USE_CUDNN=0 USE_MKLDNN=1` and `python setup.py develop`
