### ISSUE TITLE
jit.fork stalls multiprocessing dataloader

### ISSUE THREAD

**Issue by srasmussenvl** [pytorch/pytorch#92294]
### 🐛 Describe the bug

Using `torch.jit.fork` with multiprocessing dataloaders stalls the dataloader.

I would expect one of the following:

1. The dataloader would simply work.
2. An error would result from trying to run `jit.fork` outside of the main process.
3. The documentation would warn of incompatability between `jit.fork` and parallel dataloaders.

Option #2 and/or #3 would probably be most realistic, due to the nature of the `multiprocessing` module.

``` python
import torch as th

def foo(x):
    return x+1

@th.jit.script
def jit_fork_foo(x):
    return th.jit.wait(th.jit.fork(foo, x))

class Dataset(th.utils.data.IterableDataset):
    def __iter__(self):
        while True:
            yield jit_fork_foo(th.tensor([1]))

ds = Dataset()
dl_nomp = th.utils.data.DataLoader(ds, batch_size=2, num_workers=0)
dl_mp = th.utils.data.DataLoader(ds, batch_size=2, num_workers=2)

print("No multiprocessing ", next(iter(dl_nomp))) #returns as expected
print("multiprocessing ", next(iter(dl_mp))) #stalls
``` 

### Versions

```PyTorch version: 1.14.0a0+410ce96
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY

Nvidia driver version: 470.141.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.14.0a0+410ce96
[pip3] torch-tensorrt==1.3.0a0
[pip3] torchtext==0.13.0a0+fae8e8c
[pip3] torchvision==0.15.0a0```

**Comment by alexsin368** [comment]
I'm able to reproduce this issue and I believe option #2 is happening:
_An error would result from trying to run jit.fork outside of the main process._

The stalling happens only when we're calling torch.jit.fork() in the main process AND a subprocess. No issue running when we only stick to the main process (num_workers=0, two times) or using only subprocesses (num_workers=2, two times).

Here is the traceback during the stall:
No multiprocessing  tensor([[2],
        [2]])
^CTraceback (most recent call last):
  File "test_code.py", line 22, in <module>
    print("multiprocessing ", next(iter(dl_mp))) #stalls
  File "/home/pytorch/miniconda3/envs/github92294_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/pytorch/miniconda3/envs/github92294_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/home/pytorch/miniconda3/envs/github92294_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "/home/pytorch/miniconda3/envs/github92294_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/pytorch/miniconda3/envs/github92294_env/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/home/pytorch/miniconda3/envs/github92294_env/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/pytorch/miniconda3/envs/github92294_env/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/home/pytorch/miniconda3/envs/github92294_env/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/pytorch/miniconda3/envs/github92294_env/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
