### ISSUE TITLE
Distributed tests failing with python 3.11

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#92301]
There are 3 distributed tests that fail with Python 3.11:

Failures related to dataclasses:
```
Traceback (most recent call last):
  File "/home/albandes/local/pytorch/3.11_release_source/test/distributed/test_distributed_spawn.py", line 16, in <module>
    from torch.testing._internal.distributed.distributed_test import (
  File "/home/albandes/local/pytorch/3.11_release_source/torch/testing/_internal/distributed/distributed_test.py", line 34, in <module>
    from torch.distributed.optim import _apply_optimizer_in_backward
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/optim/__init__.py", line 20, in <module>
    from .named_optimizer import _NamedOptimizer
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/optim/named_optimizer.py", line 10, in <module>
    from torch.distributed._shard.sharded_tensor import ShardedTensor
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/_shard/__init__.py", line 1, in <module>
    from .api import (
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/_shard/api.py", line 6, in <module>
    from torch.distributed._shard.sharded_tensor import (
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/_shard/sharded_tensor/__init__.py", line 8, in <module>
    import torch.distributed._shard.sharding_spec as shard_spec
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/_shard/sharding_spec/__init__.py", line 1, in <module>
    from .api import (
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/_shard/sharding_spec/api.py", line 16, in <module>
    import torch.distributed._shard.sharded_tensor.metadata as sharded_tensor_meta
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/_shard/sharded_tensor/metadata.py", line 70, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/albandes/local/installs/python3.11/release/install/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/albandes/local/installs/python3.11/release/install/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/installs/python3.11/release/install/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/installs/python3.11/release/install/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'torch.distributed._shard.sharded_tensor.metadata.TensorProperties'> for field tensor_properties is not allowed: use default_factory
```
Most likely due to https://docs.python.org/3/whatsnew/3.11.html#dataclasses

One error test_launch_user_script
```
======================================================================
ERROR: test_launch_user_script (__main__.TestDistributedLaunch.test_launch_user_script)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/albandes/local/pytorch/3.11_release_source/test/distributed/test_launcher.py", line 52, in test_launch_user_script
    launch.main(args)
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/run.py", line 770, in run
    elastic_launch(
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/elastic/agent/server/api.py", line 858, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/elastic/agent/server/api.py", line 695, in _initialize_workers
    worker_ids = self._start_workers(worker_group)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 271, in _start_workers
    self._pcontext = start_processes(
                     ^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/elastic/multiprocessing/__init__.py", line 206, in start_processes
    redirs = to_map(redirects, nprocs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albandes/local/pytorch/3.11_release_source/torch/distributed/elastic/multiprocessing/api.py", line 162, in to_map
    map[i] = val_or_map.get(i, Std.NONE)
             ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

One error test_from_value
```
======================================================================
FAIL: test_from_value (__main__.StdTest.test_from_value)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/albandes/local/pytorch/3.11_release_source/test/distributed/elastic/multiprocessing/api_test.py", line 94, in test_from_value
    self.assertEqual(Std.NONE, Std.from_str("0"))
  File "/home/albandes/local/pytorch/3.11_release_source/torch/testing/_internal/common_utils.py", line 2911, in assertEqual
    assert_equal(
  File "/home/albandes/local/pytorch/3.11_release_source/torch/testing/_comparison.py", line 1244, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: None mismatch: 0 is not None
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by fduwjj** [comment]
Commented in this one for the failure:

https://github.com/pytorch/pytorch/issues/92319, also https://github.com/pytorch/pytorch/pull/91795 is trying to fix the first one.

**Comment by albanD** [comment]
Ok!
Let's close this issue to avoid duplicate as the other has a lot more details on investigation.
