### ISSUE TITLE
Cannot build triton at pinned hash: TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#92326]
### 🐛 Describe the bug

on a devgpu fails like

```
running develop
/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing triton.egg-info/PKG-INFO
writing dependency_links to triton.egg-info/dependency_links.txt
writing requirements to triton.egg-info/requires.txt
writing top-level names to triton.egg-info/top_level.txt
reading manifest file 'triton.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'triton.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "/data/users/ezyang/a/triton/python/setup.py", line 169, in <module>
    setup(
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/ezyang/local/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/data/users/ezyang/a/triton/python/setup.py", line 126, in run
    self.build_extension(ext)
  File "/data/users/ezyang/a/triton/python/setup.py", line 147, in build_extension
    "-DLLVM_EXTERNAL_LIT=" + lit_dir,
TypeError: can only concatenate str (not "NoneType") to str
```

### Versions

master

**Comment by ezyang** [comment]
The answer is, Triton is not actually at the pinned hash
