### ISSUE TITLE
`torch.compile` failed on `torch.add` with a constant python number

### ISSUE THREAD

**Issue by Co1lin** [pytorch/pytorch#92324]
### 🐛 Describe the bug

Program to reproduce:

```python
import torch

class Model(torch.nn.Module):
    def __init__(self, ):
        super().__init__()
    
    def forward(self, v1):
        v2 = torch.add(v1, 3.589, alpha=57) # ERROR!
        # v2 = torch.add(v1, v1, alpha=57) # works fine
        # v2 = v1 + 3.589820384979248 + 57 # works fine
        return v2

model = Model()
x = torch.rand(1024)
compiled = torch.compile(model, fullgraph=True)
print(compiled(x))
```

Error logs:

```python
/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py:372: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled.Consider setting `torch.set_float32_matmul_precision('high')`
  warnings.warn(
[2023-01-17 13:08:11,131] torch._inductor.graph: [ERROR] Error from lowering
Traceback (most recent call last):
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/graph.py", line 294, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 223, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 321, in inner
    inputs[-1] = mul(inputs[-1], alpha)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 223, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 3490, in mul
    return make_pointwise(fn)(a, b)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 317, in inner
    inputs = promote_constants(inputs, override_return_dtype)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 291, in promote_constants
    ex = next(x for x in inputs if isinstance(x, TensorBox))
StopIteration
Traceback (most recent call last):
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/graph.py", line 294, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 223, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 321, in inner
    inputs[-1] = mul(inputs[-1], alpha)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 223, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 3490, in mul
    return make_pointwise(fn)(a, b)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 317, in inner
    inputs = promote_constants(inputs, override_return_dtype)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 291, in promote_constants
    ex = next(x for x in inputs if isinstance(x, TensorBox))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 674, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 1050, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 1050, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/__init__.py", line 1233, in __call__
    return self.compile_fn(model_, inputs_)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 398, in compile_fx
    return aot_autograd(
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/optimizations/training.py", line 78, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2443, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 94, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2140, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1402, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1052, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 94, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 373, in fw_compiler
    return inner_compile(
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 589, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/debug.py", line 221, in inner
    return fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 139, in compile_fx_inner
    graph.run(*example_inputs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 94, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/graph.py", line 171, in run
    return super().run(*args)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/fx/interpreter.py", line 136, in run
    self.env[node] = self.run_node(node)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/graph.py", line 368, in run_node
    result = super().run_node(n)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/fx/interpreter.py", line 177, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/graph.py", line 298, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torch._inductor.exc.LoweringException: StopIteration: 
  target: aten.add.Tensor
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='arg0_1', layout=FixedLayout('cpu', torch.float32, size=[1024], stride=[1]))
  ))
  args[1]: 3.589
  kwargs: {'alpha': 57}

While executing %add : [#users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%arg0_1, 3.589), kwargs = {alpha: 57})
Original traceback:
  File "/JawTitan/colin-data/code/proj/tbug3.py", line 8, in forward
    v2 = torch.add(v1, 3.589, alpha=57)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/JawTitan/colin-data/code/proj/tbug3.py", line 16, in <module>
    print(compiled(x))
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 83, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 94, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1692, in run
    super().run()
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1758, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 527, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 598, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 679, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised LoweringException: StopIteration: 
  target: aten.add.Tensor
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='arg0_1', layout=FixedLayout('cpu', torch.float32, size=[1024], stride=[1]))
  ))
  args[1]: 3.589
  kwargs: {'alpha': 57}

While executing %add : [#users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%arg0_1, 3.589), kwargs = {alpha: 57})
Original traceback:
  File "/JawTitan/colin-data/code/proj/tbug3.py", line 8, in forward
    v2 = torch.add(v1, 3.589, alpha=57)


Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Versions

```python
Collecting environment information...
PyTorch version: 2.0.0.dev20230117+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-136-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 510.68.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230117+cu117
[pip3] torchaudio==2.0.0.dev20230117+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20230117+cu117
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230117+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230117+cu117          pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230117+cu117          pypi_0    pypi
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by eellison** [comment]
cc @ngimel or @desertfire wanna take this ? should be an easy one.
