### ISSUE TITLE
`torch.compile` generates wrong profiling program for `randn_like`

### ISSUE THREAD

**Issue by Co1lin** [pytorch/pytorch#92368]
### 🐛 Describe the bug

The following program leads to an error.

```python
import torch

class Model(torch.nn.Module):
    def __init__(self, ):
        super().__init__()
    
    def forward(self, v1: torch.Tensor):
        vx = v1.min(dim=1).values # works fine if we remove this operation
        # vx has shape [10, 0]
        v2 = torch.randn_like(vx)
        return v2

model = Model()
x = torch.rand(10, 3, 0) # ERROR
# x = torch.rand(10, 3, 1) # works fine
compiled = torch.compile(model, fullgraph=False)
print(compiled(x))
```
<details>
<summary>Error logs</summary>

```python
[2023-01-17 19:37:21,319] torch._inductor.graph: [WARNING] Creating implicit fallback for:
  target: aten.randn_like.default
  args[0]: TensorBox(StorageBox(
    Pointwise(
      'cpu',
      torch.float32,
      tmp0 = load(arg0_1, i1 + 3 * i0)
      tmp1 = load(arg0_1, 1 + i1 + 3 * i0)
      tmp2 = minimum(tmp0, tmp1)
      tmp3 = load(arg0_1, 2 + i1 + 3 * i0)
      tmp4 = minimum(tmp2, tmp3)
      return tmp4
      ,
      ranges=[10, 0],
      origins={arg0_1, min_1}
    )
  ))
  kwargs: {'dtype': torch.float32, 'layout': torch.strided, 'device': device(type='cpu'), 'pin_memory': False}
[2023-01-17 19:37:21,323] torch._inductor.ir: [WARNING] Using FallbackKernel: torch.ops.aten.randn_like.default
Traceback (most recent call last):
  File "/JawTitan/colin-data/code/proj/tbug3.py", line 16, in <module>
    print(compiled(x))
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 83, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/JawTitan/colin-data/code/proj/tbug3.py", line 7, in forward
    def forward(self, v1: torch.Tensor):
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2457, in forward
    return compiled_fn(full_args)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1056, in new_fn
    fw_outs = call_func_with_args(compiled_fw, args, disable_amp=disable_amp)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1012, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/tmp/torchinductor_colin/rb/crbn2pnyv3fmlvwj4ig6xk4qljdmjvrqyrydlzyri2y353bu7yrh.py", line 30, in call
    assert_size_stride(buf2, (10, 0), (1, 1))
AssertionError: expected size 10==10, stride 0==1 at dim=0
```
</details>

If we take a look at the `AssertionError` coming from a temporarily generated program that seems to do some profiling, we can find that the generated program has a mistake (see the comment in the following program).

```python
from ctypes import c_void_p, c_long
import torch
import random
from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()

import triton
import triton.language as tl
from torch._inductor.triton_ops.autotune import grid
from torch._C import _cuda_getCurrentRawStream as get_cuda_stream


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, = args
    args.clear()
    buf0 = empty_strided((10, 0), (0, 1), device='cpu', dtype=torch.float32)
    del arg0_1
    buf1 = torch.ops.aten.randn_like.default(buf0, dtype=torch.float32, layout=torch.strided, device=device(type='cpu'), pin_memory=False)
    del buf0
    buf2 = buf1
    assert_size_stride(buf2, (10, 0), (1, 1)) # WRONG! should be (10, 0), (0, 1)
    del buf1
    return (buf2, )


if __name__ == "__main__":
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((10, 3, 0), (3, 1, 1), device='cpu', dtype=torch.float32)
    print_performance(lambda: call([arg0_1]))
```

Something interesting is that, if we remove the `min` operation, it works fine, as the following program shows. Note that we give `randn_like` with an input tensor of the same shape as above.

```python
import torch

class Model(torch.nn.Module):
    def __init__(self, ):
        super().__init__()
    
    def forward(self, v1: torch.Tensor):
        # v1 has shape [10, 0]
        v2 = torch.randn_like(v1)
        return v2

model = Model()
x = torch.rand(10, 0) # works fine
compiled = torch.compile(model, fullgraph=False)
print(compiled(x))
```

### Versions

<details><summary>version info</summary>

```python
Collecting environment information...
PyTorch version: 2.0.0.dev20230117+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-136-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 510.68.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230117+cu117
[pip3] torchaudio==2.0.0.dev20230117+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20230117+cu117
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230117+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230117+cu117          pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230117+cu117          pypi_0    pypi
```
</details>

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by eellison** [comment]
There are a few possible fixes here :

- Fix [compute_elementwise_output_strides](https://github.com/pytorch/pytorch/blob/master/torch/_refs/__init__.py#L4248) for non overlapping and dense case 
- Potentially relax assertions on strides for 0-dim tensors in inductor, since their values wont be read anyway. Potentially might cause subsequent tensors to be incorrect, not clear
- Decompose `randn_like` so that we don't fallback to eager, also better for perf.

The last option here is the only thing that fixes the issue and improves perf. However, currently it's blocked by https://github.com/pytorch/pytorch/pull/89797 which is blocked by fixed either https://github.com/pytorch/pytorch/issues/92092 (cc @tugsbayasgalan) or https://github.com/pytorch/pytorch/issues/92920
