### ISSUE TITLE
Segfault in CuPy -> dlpack -> PyTorch

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#9260]
Hi,

I'm not sure whether this is a PyTorch or a CuPy issue, but
```
import cupy
import torch.utils.dlpack

for i in range(100):
   l = torch.nn.Linear(1000,1000).cuda()
   b = l(torch.randn(1000,1000, device='cuda'))
   a = torch.utils.dlpack.from_dlpack(cupy.random.randn(1000,1000, dtype=cupy.float32).toDlpack())
   b.backward(a)
```
seems to sefault for me relative reliably (python 3.6, PyTorch recent master, CuPy recent master, both built with gcc 5).
I'm not entirely sue whether the module and backward is strictly necessary, but I got the repro down from 1000 to less then 10 lines already and it's relatively quick to fail.

It could be a refcounting issue. Stacktrace:
```
0  0x0000000000000000 in ?? ()
#1  0x00007fff8df01fec in at::call_deleter () from /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so
#2  0x00007fff8dff3c8f in THCStorage_free () from /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so
#3  0x00007fff8e00e3c5 in THCTensor_free () from /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so
#4  0x00007fff8df048b9 in at::CUDAFloatTensor::~CUDAFloatTensor() () from /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_gpu.so
#5  0x00007fff9d053782 in at::Retainable::release (this=<optimized out>) at /home/tv/pytorch/pytorch/torch/lib/tmp_install/include/ATen/Retainable.h:16
#6  at::detail::TensorBase::~TensorBase (this=0x3b7d5808, __in_chrg=<optimized out>) at /home/tv/pytorch/pytorch/torch/lib/tmp_install/include/ATen/TensorBase.h:30
#7  at::Tensor::~Tensor (this=0x3b7d5808, __in_chrg=<optimized out>) at /home/tv/pytorch/pytorch/torch/lib/tmp_install/include/ATen/Tensor.h:44
#8  torch::autograd::Variable::Impl::~Impl (this=0x3b7d57d0, __in_chrg=<optimized out>) at /home/tv/pytorch/pytorch/torch/csrc/autograd/variable.h:282
#9  0x00007fff9d0538b9 in torch::autograd::Variable::Impl::~Impl (this=0x3b7d57d0, __in_chrg=<optimized out>) at /home/tv/pytorch/pytorch/torch/csrc/autograd/variable.h:282
#10 0x00007fff9d06a54e in at::Retainable::release (this=<optimized out>) at /home/tv/pytorch/pytorch/torch/lib/tmp_install/include/ATen/Retainable.h:16
#11 at::detail::TensorBase::~TensorBase (this=<optimized out>, __in_chrg=<optimized out>) at /home/tv/pytorch/pytorch/torch/lib/tmp_install/include/ATen/TensorBase.h:30
#12 at::detail::TensorBase::reset (this=0x7fff827ad640) at /home/tv/pytorch/pytorch/torch/lib/tmp_install/include/ATen/TensorBase.h:47
#13 THPVariable_clear (self=self@entry=0x7fff827ad630) at torch/csrc/autograd/python_variable.cpp:114
#14 0x00007fff9d06a631 in THPVariable_dealloc (self=0x7fff827ad630) at torch/csrc/autograd/python_variable.cpp:121
#15 0x00000000004d8395 in subtype_dealloc (self=<Tensor at remote 0x7fff827ad630>) at ../Objects/typeobject.c:1222
Python Exception <class 'RuntimeError'> Type does not have a target.: 
#16 0x00000000004b5e55 in insertdict (value=<Tensor at remote 0x7ffff69ebaf8>, hash=-7244025631456083716, key=, mp=0x7ffff6b8c2d0) at ../Objects/dictobject.c:1181
Python Exception <class 'RuntimeError'> Type does not have a target.: 
Python Exception <class 'RuntimeError'> Type does not have a target.: 
#17 PyDict_SetItem (op=, key=, value=<Tensor at remote 0x7ffff69ebaf8>) at ../Objects/dictobject.c:1575
#18 0x0000000000557859 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:2223
Python Exception <class 'RuntimeError'> Type does not have a target.: 
#19 0x000000000054fbe1 in PyEval_EvalFrameEx (throwflag=0, f=) at ../Python/ceval.c:753
#20 _PyEval_EvalCodeWithName (_co=_co@entry=<code at remote 0x7ffff6b48810>, globals=globals@entry=<code at remote 0x7ffff6b48810>, 
    locals=locals@entry=<error reading variable: Cannot access memory at address 0x3>, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, 
    defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at ../Python/ceval.c:4153
#21 0x0000000000550b93 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, 
    locals=locals@entry=<error reading variable: Cannot access memory at address 0x3>, globals=globals@entry=<code at remote 0x7ffff6b48810>, _co=_co@entry=<code at remote 0x7ffff6b48810>)
    at ../Python/ceval.c:4174
Python Exception <class 'RuntimeError'> Type does not have a target.: 
Python Exception <class 'RuntimeError'> Type does not have a target.: 
#22 PyEval_EvalCode (co=co@entry=<code at remote 0x7ffff6b48810>, globals=globals@entry=, locals=locals@entry=) at ../Python/ceval.c:730
Python Exception <class 'RuntimeError'> Type does not have a target.: 
Python Exception <class 'RuntimeError'> Type does not have a target.: 
Python Exception <class 'RuntimeError'> Type does not have a target.: 
#23 0x000000000042b519 in run_mod (arena=0x7ffff6ba7270, flags=0x7fffffffe3cc, locals=, globals=, filename=, mod=0xb54778) at ../Python/pythonrun.c:1025
Python Exception <class 'RuntimeError'> Type does not have a target.: 
Python Exception <class 'RuntimeError'> Type does not have a target.: 
#24 PyRun_FileExFlags (fp=0xb3e8a0, filename_str=<optimized out>, start=<optimized out>, globals=, locals=, closeit=1, flags=0x7fffffffe3cc) at ../Python/pythonrun.c:978
#25 0x000000000042b705 in PyRun_SimpleFileExFlags (fp=0xb3e8a0, filename=<optimized out>, closeit=1, flags=0x7fffffffe3cc) at ../Python/pythonrun.c:420
#26 0x0000000000441fcb in run_file (p_cf=0x7fffffffe3cc, filename=0xa90650 L"dlpack_fail.py", fp=0xb3e8a0) at ../Modules/main.c:340
#27 Py_Main (argc=argc@entry=2, argv=argv@entry=0xa8f260) at ../Modules/main.c:810
#28 0x0000000000421ff4 in main (argc=2, argv=<optimized out>) at ../Programs/python.c:69
```

Best regards

Thomas

**Comment by t-vi** [comment]
So if I see this correctly, the memory allocated by CuPy should not be deallocated in ATen but the deleter should be called. Is that approximately correct?

**Comment by t-vi** [comment]
The segfault was caused by CuPy's pycapsule calling the deleter even if PyTorch consumed the DLPack. I submitted the above PR.

**Comment by ezyang** [comment]
Nice analysis and follow up, thank you!
