### ISSUE TITLE
Torchscript troubles with complex values. RuntimeError: isInt() INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by JuliaA369** [pytorch/pytorch#92683]
### 🐛 Describe the bug

Torchscript errors out when creating imaginary coefficients. This simple example runs fine in pytorch without torchscript. I'd expect to get the same result with torch and torchscript. 

```
import torch

class SimpleEx(torch.nn.Module):
    def __init__(self):
        super(SimpleEx, self).__init__()
        self.k = 1.23

    def forward(self):
        a = torch.randn(3)
        b = torch.randn(11,11)
        return 1j*self.k/2*(1-a[1])/a[0]*b

if __name__ == '__main__':

    se = torch.jit.script(SimpleEx())
    se_out = se()
    print(se_out)
```

The following error is produced when running as a module

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/SimpleEx.py", line 17, in <module>
    se_out = se()
  File "/home/user/my_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/user/SimpleEx.py", line 12, in forward
        a = torch.randn(3)
        b = torch.randn(11,11)
        return 1j*self.k/2*(1-a[1])/a[0]*b
               ~~~~~~~~~~~ <--- HERE
RuntimeError: isInt() INTERNAL ASSERT FAILED at "../aten/src/ATen/core/ivalue.h":602, please report a bug to PyTorch.



### Versions

Collecting environment information...
PyTorch version: 1.13.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-136-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: Quadro P1000
Nvidia driver version: 495.29.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.13.1+cpu
[pip3] torchvision==0.14.1+cpu
[conda] Could not collect

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by ezyang** [comment]
that looks pretty interesting, seems like some sort of type promotion problem on 1j. Try converting 1j into a scalar tensor.

**Comment by JuliaA369** [comment]
> that looks pretty interesting, seems like some sort of type promotion problem on 1j. Try converting 1j into a scalar tensor.

Thanks @ezyang ! That does the trick. Feel free to close this issue if this is the intended behavior.

**Comment by ezyang** [comment]
It's not so we will let this issue grow old like fine wine

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
