### ISSUE TITLE
[JIT] Applying `conv2d` over Constants Leads to Exception

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#92740]
### 🐛 Describe the bug

The following program throws an exception in JIT. This seems to be a fault in evaluating a constant expression. i.e., applying `conv2d` over a constant.
```python
import torch

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = torch.nn.Conv2d(1, 288, kernel_size=(1, 1))
        self.v0 = torch.nn.Parameter(torch.rand([1, 1, 14, 14]))

    def forward(self):
        v1 = self.conv(self.v0)
        v2 = torch.nn.functional.relu(v1, inplace=True) # works w/o this line
        return v2


fn = Model().eval()
fn()
print("Eager mode ... OK!")

exported = torch.jit.trace(fn, ())
exported = torch.jit.optimize_for_inference(exported)
exported()
print("JIT mode ... OK!")

"""
Eager mode ... OK!
Traceback (most recent call last):
  File "model.py", line 22, in <module>
    exported()
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
          %transposed:bool, %output_padding:int[], %groups:int, %benchmark:bool,
          %deterministic:bool, %cudnn_enabled:bool, %allow_tf32:bool):
        %r = aten::conv2d(%a, %w, %b, %stride, %padding, %dilation, %groups)
             ~~~~ <--- HERE
        return (%r) 
RuntimeError: Input type (torch.FloatTensor) and weight type (Mkldnntorch.FloatTensor) should be the same
"""
```

### Versions

<details><summary> <b> Environment </b> <i> [Click to expand] </i></summary>

```
PyTorch version: 2.0.0.dev20230119+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 11.1.0-6
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230119+cu117
[pip3] torchaudio==2.0.0.dev20230118+cu117
[pip3] torchvision==0.15.0.dev20230118+cu117
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] torch                     1.14.0a0+gitce2f870          pypi_0    pypi
```

</details>

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @mingfeima @XiaobingSuper @ashokei @jingxu10

**Comment by jingxu10** [comment]
Is there any specific reason why you passed a Parameter into a Conv2d op as its input? The input to an op should be a data.

**Comment by Kristoff-starling** [comment]
> Is there any specific reason why you passed a Parameter into a Conv2d op as its input? The input to an op should be a data.

Thanks for your reply! The program here is not user facing since the input is a constant. It's generated and found by a fuzzer, but we still reported it because theoretically the usage is valid and it actually tests the functionality of constant folding.

**Comment by Kristoff-starling** [comment]
Meanwhile, only using `self.v0 = torch.rand([1, 1, 14, 14])` also triggers the bug
```python
def __init__(self):
        super().__init__()
        self.conv = torch.nn.Conv2d(1, 288, kernel_size=(1, 1))
        self.v0 = torch.rand([1, 1, 14, 14])
```
and possibly some users could use constants for debugging.

**Comment by jingxu10** [comment]
Is it possible to validate with this sample?
```
import torch

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = torch.nn.Conv2d(1, 288, kernel_size=(1, 1))

    def forward(self, v0):
        v1 = self.conv(v0)
        v2 = torch.nn.functional.relu(v1, inplace=True) # works w/o this line
        return v2

v0 = torch.rand([1, 1, 14, 14])
fn = Model().eval()
fn(v0)
print("Eager mode ... OK!")

exported = torch.jit.trace(fn, v0)
exported = torch.jit.optimize_for_inference(exported)
exported(v0)
print("JIT mode ... OK!")
```

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
