### ISSUE TITLE
Dynamo graph break due to context manager (e.g., stream context) do not resume inside/outside the context manager

### ISSUE THREAD

**Issue by sujoysaraswati** [pytorch/pytorch#92804]
### 🐛 Describe the bug

Dynamo doesn't seem to support user defined cuda streams and doesn't create graphs for ops in the user stream context.
Example code:

```from torch._dynamo import optimize
import torch._dynamo as dynamo
import torch

dynamo.config.log_level = dynamo.config.logging.DEBUG
torch._dynamo.reset()

def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    print(gm.code)
    print(gm.graph)
    gm.graph.print_tabular()
    return gm.forward

s = torch.cuda.Stream()

@dynamo.optimize(my_compiler)
def fn(t) -> torch.Tensor:
    tmp1 = torch.mul(t, 5)
    tmp2 = torch.add(tmp1, 2)
    with torch.cuda.stream(s):
      r = torch.relu(tmp2)
    return r

i = torch.Tensor([-2, 3]).to('cuda')
r = fn(i)
print(f"r = {r}")
```

Even though the output is correct, Dynamo seems to break the graph when the user stream context is seen -

```[2023-01-23 04:54:12,808] torch._dynamo.symbolic_convert: [DEBUG] break_graph_if_unsupported triggered compile
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 420, in proxy_args_kwargs
    proxy_args = tuple(arg.as_proxy() for arg in args)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 420, in <genexpr>
    proxy_args = tuple(arg.as_proxy() for arg in args)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/base.py", line 206, in as_proxy
    raise NotImplementedError(str(self))
NotImplementedError: UserDefinedObjectVariable(Stream)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 307, in wrapper
    return inner_fn(self, inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 974, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 435, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/torch.py", line 476, in call_function
    *proxy_args_kwargs(args, kwargs),
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 427, in proxy_args_kwargs
    raise unimplemented(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function args: UserDefinedObjectVariable(Stream) 
[2023-01-23 04:54:12,810] torch._dynamo.output_graph: [DEBUG] restore_graphstate: removed 0 nodes
[2023-01-23 04:54:12,811] torch._dynamo.output_graph: [DEBUG] COMPILING GRAPH due to GraphCompileReason(reason='call_function args: UserDefinedObjectVariable(Stream) ', user_stack=[<FrameSummary file <ipython-input-12-f1436f0fcd91>, line 20 in fn>])
```

It seems there is no graph captured for the ops in the user stream context, as there is a no graph with relu (op in the user stream context in the example code) seen below -

```
def forward(self, t : torch.Tensor):
    mul = torch.mul(t, 5);  t = None
    add = torch.add(mul, 2);  mul = None
    return (add,)
    
graph():
    %t : torch.Tensor [#users=1] = placeholder[target=t]
    %mul : [#users=1] = call_function[target=torch.mul](args = (%t, 5), kwargs = {})
    %add : [#users=1] = call_function[target=torch.add](args = (%mul, 2), kwargs = {})
    return (add,)
opcode         name    target                                                  args       kwargs
-------------  ------  ------------------------------------------------------  ---------  --------
placeholder    t       t                                                       ()         {}
call_function  mul     <built-in method mul of type object at 0x7f2e333dbe40>  (t, 5)     {}
call_function  add     <built-in method add of type object at 0x7f2e333dbe40>  (mul, 2)   {}
output         output  output                                                  ((add,),)  {}
```

Is there a way to capture the user stream ops in a graph via dynamo?

### Versions

PyTorch version: 2.0.0.dev20230122+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.147+-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.2.152
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230122+cu117
[pip3] torchaudio==0.13.1+cu116
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.14.1
[pip3] torchvision==0.14.1+cu116
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
We have to support this. Distributed crew might be interested since this affects your tracing regime (cc @wconstab @aazzolini @wanchaol).

There are actually two orthogonal problems here. First, Dynamo needs to actually support preserving user stream ops. This can be done similarly to how we support `with no_grad()` context manager (see https://github.com/pytorch/torchdynamo/commit/a8b2b45cfe7653afcfc56b7efae3a1228886fe74 for @jansel's original implementation in this case).

Second, we need to actually respect the user stream ops when lowering. Unlike grad enable/disable (which AOTAutograd respects), stream setting will NOT be respected by default by AOTAutograd tracing. My plan was to use the stream hooks that we built for CUDA Sanitizer to trace these (https://github.com/pytorch/pytorch/pull/82824) but someone has to implement it and there are some persnickety details.

Finally, the backend compiler aka inductor has to actually do something useful with them. This is probably not too bad. But it also has to be done.

**Comment by ngimel** [comment]
Why does AOT need to know about streams? 
Inductor does proper device guards now, streams shouldn't be too bad.

**Comment by sujoysaraswati** [comment]
> We have to do work to support this. Distributed crew might be interested since this affects your tracing regime (cc @wconstab @aazzolini @wanchaol).
> 
> There are actually two orthogonal problems here. First, Dynamo needs to actually support preserving user stream ops. This can be done similarly to how we support `with no_grad()` context manager (see [pytorch/torchdynamo@a8b2b45](https://github.com/pytorch/torchdynamo/commit/a8b2b45cfe7653afcfc56b7efae3a1228886fe74) for @jansel's original implementation in this case).
> 
> Second, we need to actually respect the user stream ops when lowering. Unlike grad enable/disable (which AOTAutograd respects), stream setting will NOT be respected by default by AOTAutograd tracing. My plan was to use the stream hooks that we built for CUDA Sanitizer to trace these (#82824) but someone has to implement it and there are some persnickety details.
> 
> Finally, the backend compiler aka inductor has to actually do something useful with them. This is probably not too bad. But it also has to be done.

Thanks for the response. Can you please elaborate on why the stream ops need to be preserved? For stream context, there should be a graph break I believe as the ops will be sent to a potentially different stream given by user. Isn't it possible to fallback to eager for the stream context enter/exit and create an FX graph for the ops in the stream context? I couldn't follow why downstream components like Inductor need to know which stream context they are in, as they should be set/reset by the stream context manager.

**Comment by bdhirsh** [comment]
> Why does AOT need to know about streams?

> It needs to know to preserve them

I take this to mean, when AOTAutograd sees `torch.cuda.set_stream(cur_stream)` calls in the torch graph from dynamo, it needs to actually keep them in the lowered graph? Today we have no aten representation for `set_stream` (that I'm aware of), so tracing through a `torch.cuda.set_stream` call will actually go ahead and execute that code, instead of properly tracing it.

That's kinda like the situation with `torch.no_grad()` (we don't preserve the call to set grad context in the aten graph, although that one is probably fine).

**Comment by wconstab** [comment]
What are our options for preserving stream info in our graphs?
1) graph-break, where each graph is tagged with a stream  -- this seems like a particularly bad strategy since stream management can be quite fine grained
2) insert stream-change ops in graph -- these would essentially be 'side-effectful' ops, and that's problematic for a variety of reasons
3) tag stream info on ops as 'metadata' -- would this be a good way to avoid the issues with (1) and (2)?  Backends have to be on the honor system in consuming this metadata, or else semantics get lost.  Decomps and transforms would also have to propagate such metadata, which is a bigger problem unless we can do it in a general way somewhere.

**Comment by ezyang** [comment]
Actually, I think I have misunderstood the user request. I have proposed a harder thing: do not graph break, incorporate streams into the graph. But the user is asking for something simpler: graph break at the stream op, but capture the relu in the stream. One obvious thought is, because this is one op, we may have suppressed passing it to the compiler.

**Comment by ezyang** [comment]
If a non-default stream is impeding dynamo from capturing, then it's pretty simple, we need to guard on stream OR make sure our backends respect current stream (which also seems fine)

**Comment by sujoysaraswati** [comment]
I was indeed proposing a solution where the graphs can be broken at the stream context boundary. The user stream context may have more than one op, so a compiled graph may be beneficial there.
Would it be a better solution to keep the ops within stream context in the same graph from Dynamo? I thought eventually they had to be split anyway in separate graphs as the ops go to different streams, so couldn't see the value of keeping them in same graph at Dynamo level.
One more additional comment - Habana backends also provide stream interfaces to end users, similar to torch.cuda.Stream. When Dynamo attempts to create graphs for the ops in stream context, it would be great to consider streams other than torch.cuda.Streams as well. Maybe there should be a way for other backends to register their PyTorch user level APIs/context managers for Dynamo to consider?

**Comment by ezyang** [comment]
Ok I think I know what the problem with your code is. Try moving the code inside the stream into a separate function. I bet the problem is we don't know how to resume after graph breaking due to context manager

**Comment by ezyang** [comment]
Re passing on streams internally, probably the right long term representation is nodes in the graph are annotated with what stream they are run on. This keeps everything functional but you now have enough information to appropriately do stream syncs. We would need a concept of a stream placeholder though to allow for varying user streams (or maybe constant streams are good enough)

**Comment by ngimel** [comment]
Nodes in the graph having steam information is a good end state (similar to how today they have device information), but as @wconstab pointed out we'd have to find a way to propagate it. FakeTensor has device info, which makes propagating device natural, but no stream info. 
The stream syncs should come from the user code, though, and not be automatically inserted by a compiler?

**Comment by sujoysaraswati** [comment]
> Ok I think I know what the problem with your code is. Try moving the code inside the stream into a separate function. I bet the problem is we don't know how to resume after graph breaking due to context manager

True, if I change by moving the code inside stream in another function, then the ops under stream in that function gets into a graph. I modified the original code to have a few more ops -
```
s = torch.cuda.Stream()

def stream_fn(t) -> torch.Tensor:
    tmp = torch.sin(t)
    r = torch.relu(tmp)
    return r

@dynamo.optimize(my_compiler)
def fn(t) -> torch.Tensor:
    tmp1 = torch.mul(t, 5)
    tmp2 = torch.add(tmp1, 2)
    with torch.cuda.stream(s):
        r = stream_fn(tmp2)
    s1 = torch.add(r, 2)
    s2 = torch.cos(s1)
    return s2
```
Now, there is a graph with mul and add (before the steam context) -
```
def forward(self, t : torch.Tensor):
    mul = torch.mul(t, 5);  t = None
    add = torch.add(mul, 2);  mul = None
    return (add,)
```
Also, and there is another graph for sin and relu which is within the stream context and in a separate function -
```
def forward(self, t : torch.Tensor):
    sin = torch.sin(t);  t = None
    relu = torch.relu(sin);  sin = None
    return (relu,)
```
However, the ops after the stream context (add and cos) doesn't seem to form a graph. 

If I move the "with torch.cuda.stream(s):" inside the stream_fn, then the ops in the function fn forms two graphs (first one with mul and add, and the second with add and cos) though the ops within stream_fn (sin and relu) doesn't create a graph.

**Comment by ezyang** [comment]
Ok so to complete the workaround you need two functions: one to hold the with statement, and another to hold the contents of the with statement. We should probably fix this but this should unblock you.

**Comment by sujoysaraswati** [comment]
> 

Agree, but it would be good to see the support in Dynamo itself as this requires asking the user to change their code.

**Comment by yanboliang** [comment]
At dynamo level, this is because if the context manager is not supported yet, it will graph break:
https://github.com/pytorch/pytorch/blob/b179a097ea03154de6d21abbbc7436adec0d3f73/torch/_dynamo/symbolic_convert.py#L832-L836

To avoid graph break and make dynamo capture the graph, there are two ways:
* Add support for this context manager.
* Ignore the context manager via wrapping the context in a [```nullcontext```](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/misc.py#L421).

For option 2, the ops under the context manager can be captured in the FX graph and there is no graph break. Since AOT is not aware of ```torch.cuda.set_stream```, so I think we can ignore this function during dynamo capturing.
I'll send a PR with option 2 if no objection.

**Comment by ezyang** [comment]
Reopening the PR for the more general problem

**Comment by sujoysaraswati** [comment]
> Reopening the PR for the more general problem

What is the plan for the PR next? Since https://github.com/pytorch/pytorch/pull/93808 captures the set streams in the FX graph without break, is the next change to enable compilers to handle this?

**Comment by kbadz-pl** [comment]
@ezyang any update on context manager support? As I understood from this and other tickets, it seems that plan is to include stream, device, etc operations as part of nodes metadata. But this is still very limited case that will probably work only on predefined streams like CUDA and probably won't support custom context managers, right? I guess supporting every other context manager by doing graph breaks on enter and exit by default (so that user don't have to wrap everything with functions OR manually call implementations of enter/exit in-place) would be enough for us. Is there plan for it?

**Comment by sujoysaraswati** [comment]
> At the triage review meeting we said we should shepherd through AOTAutograd and Inductor, and inductor should do something. It’ll take us a while before we can get there.

Thanks, it would be also important to know what would be the flow for a backend which doesn't use inductor.

**Comment by zou3519** [comment]
We will need to represent the stream change somehow in the graph. Open question as to how: the stream change could be a subgraph, or there could be an annotation on the FX node about the current stream, or there could be an enter and exit node somewhere in the graph.

A backend (like inductor) would then ingest this graph, and then it would be up to them to preserve the stream semantics (or not, open question if backends should be allowed to change the stream semantics).

**Comment by cora-codes** [comment]
We've also ran into this issue and found it quite frustrating to debug.

Perhaps preventing functions dealing with streams from being traced by inductor would make it more clear to users that they are doing something unsupported?

**Comment by ezyang** [comment]
@yf225 do you have an update about this?

**Comment by yf225** [comment]
No recent new thoughts on this yet. I wonder if the following is possible:
1. Have stream info in FakeTensor to allow assigning streams to AOTAutograd graph nodes (tracked in node.meta).
2. Preserve the stream info all the way to inductor, and only do fusion / reordering within each same-stream graph region.

One thing somewhat unclear is the backward behavior when forward is partially wrapped with custom stream. Maybe the answer there is just "preserve eager behavior"?

cc. @FindHao who is working on multi-stream support in Inductor - maybe there is appetite to expand the scope of the project?

**Comment by kbadz** [comment]
Just FYI, not sure if it solves the initial issue but passing this kind of data to backend(like stream for subgraph) is possible for some cases via this feature:
https://github.com/pytorch/pytorch/issues/126393
https://github.com/pytorch/pytorch/pull/132860

**Comment by FindHao** [comment]
> No recent new thoughts on this yet. I wonder if the following is possible:
> 
> 1. Have stream info in FakeTensor to allow assigning streams to AOTAutograd graph nodes (tracked in node.meta).
> 2. Preserve the stream info all the way to inductor, and only do fusion / reordering within each same-stream graph region.
> 
> One thing somewhat unclear is the backward behavior when forward is partially wrapped with custom stream. Maybe the answer there is just "preserve eager behavior"?
> 
> cc. @FindHao who is working on multi-stream support in Inductor - maybe there is appetite to expand the scope of the project?

I agree. This is a good user case to convincing me that respecting user stream assignment is a real need. What I'm currently working on is the wrapper codegen and stream assignment by developer pattern definitions, but doesn't respect user stream assignments. We can see the stream assignment code in fxgraph but no more in lowered steps. So, passing the information to inductor is the key.

**Comment by ngimel** [comment]
>One thing somewhat unclear is the backward behavior when forward is partially wrapped with custom stream. Maybe the answer there is just "preserve eager behavior"?

Eager behavior is to run corresponding backward ops on the same stream forward was run, and yes, it makes sense to preserve it.

**Comment by crinard** [comment]
Fwiw I'm also running into this issue.
