### ISSUE TITLE
[SDPA] Investigate compiled code not calling the same fused kernel

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#92887]
# Summary

When using the simple mha nn module the eager implementation with the new main branch of flash attention produces:
``` Bash
-------------------------------------Profile for Composite MHA--------------------------------------
STAGE:2023-01-24 02:17:48 3368:3368 ActivityProfilerController.cpp:300] Completed Stage: Warm Up
STAGE:2023-01-24 02:17:51 3368:3368 ActivityProfilerController.cpp:306] Completed Stage: Collection
STAGE:2023-01-24 02:17:51 3368:3368 ActivityProfilerController.cpp:310] Completed Stage: Post Processing
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                  cudaDeviceSynchronize        96.85%        3.266s        96.85%        3.266s        3.266s       0.000us         0.00%       0.000us       0.000us             1
                                          Composite MHA         0.56%      18.890ms         3.15%     106.302ms     106.302ms       0.000us         0.00%        3.666s        3.666s             1
                     aten::scaled_dot_product_attention         0.05%       1.746ms         1.18%      39.942ms     399.420us       0.000us         0.00%        1.736s      17.364ms           100
              aten::_scaled_dot_product_flash_attention         0.20%       6.652ms         1.13%      38.196ms     381.960us       0.000us         0.00%        1.736s      17.364ms           100
                                           aten::linear         0.14%       4.651ms         0.97%      32.827ms     164.135us       0.000us         0.00%        1.929s       9.647ms           200
                                            aten::addmm         0.50%      16.706ms         0.67%      22.630ms     113.150us        1.804s        53.53%        1.929s       9.647ms           200
                                           aten::arange         0.16%       5.497ms         0.58%      19.515ms      48.788us     807.000us         0.02%     145.852ms     364.630us           400
                         aten::_flash_attention_forward         0.14%       4.606ms         0.31%      10.579ms     105.790us        1.565s        46.44%        1.664s      16.635ms           100
                                        aten::transpose         0.19%       6.573ms         0.31%      10.497ms      10.497us       0.000us         0.00%       0.000us       0.000us          1000
                                            aten::chunk         0.02%     604.000us         0.22%       7.331ms      73.310us       0.000us         0.00%       0.000us       0.000us           100
                                            aten::split         0.04%       1.513ms         0.20%       6.727ms      67.270us       0.000us         0.00%       0.000us       0.000us           100
                                            aten::empty         0.20%       6.644ms         0.20%       6.644ms      11.073us       0.000us         0.00%       0.000us       0.000us           600
                                       cudaLaunchKernel         0.18%       6.145ms         0.18%       6.145ms      12.290us     166.309ms         4.94%     166.309ms     332.618us           500
                                          aten::reshape         0.12%       3.984ms         0.16%       5.495ms      13.738us       0.000us         0.00%       0.000us       0.000us           400
                                       aten::as_strided         0.15%       5.214ms         0.15%       5.214ms       4.011us       0.000us         0.00%       0.000us       0.000us          1300
                                           aten::narrow         0.06%       1.909ms         0.15%       5.214ms      17.380us       0.000us         0.00%       0.000us       0.000us           300
                                             aten::view         0.14%       4.889ms         0.14%       4.889ms       6.111us       0.000us         0.00%       0.000us       0.000us           800
                                            aten::slice         0.06%       2.015ms         0.10%       3.305ms      11.017us       0.000us         0.00%       0.000us       0.000us           300
                                                aten::t         0.03%     985.000us         0.09%       3.067ms      15.335us       0.000us         0.00%       0.000us       0.000us           200
                                       aten::empty_like         0.04%       1.258ms         0.08%       2.734ms      27.340us       0.000us         0.00%       0.000us       0.000us           100
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 3.373s
Self CUDA time total: 3.369s

----------------------------------Execution time of Composite MHA-----------------------------------
Time: 33925.569616258144 us
```
While the compiled module produces:
``` Bash
[2023-01-24 02:17:58,900] torch._inductor.graph: [WARNING] Using FallbackKernel: torch.ops.aten._scaled_dot_product_efficient_attention.default
[2023-01-24 02:17:58,902] torch._inductor.scheduler: [DEBUG] removed dead node: buf3
[2023-01-24 02:17:58,920] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 0
[2023-01-24 02:17:58,920] torch._inductor.debug: [WARNING] model__0_inference_0 debug trace: /scratch/drisspg/work/pytorch/torch_compile_debug/run_2023_01_24_02_17_54_320631/aot_torchinductor/model__0_inference_0.0
[2023-01-24 02:17:58,921] torch._dynamo.output_graph: [INFO] Step 2: done compiler function debug_wrapper
[2023-01-24 02:17:58,991] torch._dynamo.eval_frame: [DEBUG] skipping _fn /scratch/drisspg/work/pytorch/torch/_dynamo/eval_frame.py
[2023-01-24 02:17:58,991] torch._dynamo.eval_frame: [DEBUG] skipping nothing /scratch/drisspg/work/pytorch/torch/_dynamo/eval_frame.py
[2023-01-24 02:17:58,996] torch._dynamo.eval_frame: [DEBUG] skipping __exit__ /scratch/drisspg/work/3_9_env/lib/python3.9/contextlib.py
[2023-01-24 02:17:58,996] torch._dynamo.eval_frame: [DEBUG] skipping __exit__ /scratch/drisspg/work/3_9_env/lib/python3.9/contextlib.py
STAGE:2023-01-24 02:17:58 3368:3368 ActivityProfilerController.cpp:300] Completed Stage: Warm Up
STAGE:2023-01-24 02:18:03 3368:3368 ActivityProfilerController.cpp:306] Completed Stage: Collection
STAGE:2023-01-24 02:18:03 3368:3368 ActivityProfilerController.cpp:310] Completed Stage: Post Processing
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                  cudaDeviceSynchronize        98.48%        4.715s        98.48%        4.715s        4.715s       0.000us         0.00%       0.000us       0.000us             1
                                 Compiled Composite MHA         0.69%      33.209ms         1.52%      72.666ms      72.666ms       0.000us         0.00%        4.535s        4.535s             1
                                            aten::addmm         0.24%      11.680ms         0.36%      17.433ms      87.165us        1.744s        38.46%        1.744s       8.721ms           200
          aten::_scaled_dot_product_efficient_attention         0.07%       3.536ms         0.31%      14.782ms     147.820us       0.000us         0.00%        2.790s      27.904ms           100
                     aten::_efficient_attention_forward         0.06%       3.016ms         0.14%       6.762ms      67.620us        2.790s        61.54%        2.790s      27.904ms           100
                                            aten::empty         0.11%       5.431ms         0.11%       5.431ms      13.578us       0.000us         0.00%       0.000us       0.000us           400
                                       aten::as_strided         0.11%       5.366ms         0.11%       5.366ms       4.472us       0.000us         0.00%       0.000us       0.000us          1200
                                        aten::transpose         0.06%       2.824ms         0.09%       4.484ms      11.210us       0.000us         0.00%       0.000us       0.000us           400
                                       cudaLaunchKernel         0.08%       3.839ms         0.08%       3.839ms      12.797us       0.000us         0.00%       0.000us       0.000us           300
                                    aten::empty_strided         0.07%       3.536ms         0.07%       3.536ms      17.680us       0.000us         0.00%       0.000us       0.000us           200
cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFla...         0.00%     229.000us         0.00%     229.000us       1.145us       0.000us         0.00%       0.000us       0.000us           200
ampere_fp16_s16816gemm_fp16_128x128_ldg8_relu_f2f_st...         0.00%       0.000us         0.00%       0.000us       0.000us        1.744s        38.46%        1.744s       8.721ms           200
void attention_kernel_batched<AttentionKernel<cutlas...         0.00%       0.000us         0.00%       0.000us       0.000us        2.790s        61.54%        2.790s      27.904ms           100
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 4.788s
Self CUDA time total: 4.535s

------------------------------Execution time of Compiled Composite MHA------------------------------
Time: 45262.85193860531 us
```

The discrepancy in runtime is exaggerated because the MHA hyperparams is more advantageous for FlashAtten kernels.

**Comment by drisspg** [comment]
Tried disabling mem_efficient attention and:
```
[2023-01-24 02:25:36,652] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION_KW 6 [TorchVariable(<built-in function scaled_dot_product_attention>), TensorVariable(), TensorVariable(), TensorVariable(), ConstantVariable(NoneType), ConstantVariable(float), ConstantVariable(bool), ConstantVariable(tuple)]
/scratch/drisspg/work/pytorch/torch/_dynamo/utils.py:1155: UserWarning: Memory efficient kernel not used because: (Triggered internally at /scratch/drisspg/work/pytorch/aten/src/ATen/native/transformers/cuda/sdp_utils.h:472.)
  return node.target(*args, **kwargs)
/scratch/drisspg/work/pytorch/torch/_dynamo/utils.py:1155: UserWarning: Memory Efficient attention has been runtime disabled. (Triggered internally at /scratch/drisspg/work/pytorch/aten/src/ATen/native/transformers/cuda/sdp_utils.h:301.)
  return node.target(*args, **kwargs)
/scratch/drisspg/work/pytorch/torch/_dynamo/utils.py:1155: UserWarning: Flash attention kernel not used because: (Triggered internally at /scratch/drisspg/work/pytorch/aten/src/ATen/native/transformers/cuda/sdp_utils.h:474.)
  return node.target(*args, **kwargs)
/scratch/drisspg/work/pytorch/torch/_dynamo/utils.py:1155: UserWarning: Flash Attention does not currently support training. (Triggered internally at /scratch/drisspg/work/pytorch/aten/src/ATen/native/transformers/cuda/sdp_utils.h:162.)
  return node.target(*args, **kwargs)
[2023-01-24 02:25:36,672] torch._dynamo.utils: [ERROR] Unable to write execution record /scratch/drisspg/work/pytorch/torch_compile_debug/run_2023_01_24_02_25_36_604003/error_recordings/forward_TorchRuntimeError_54.rec
Traceback (most recent call last):
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/utils.py", line 1155, in run_node
    return node.target(*args, **kwargs)
  File "/scratch/drisspg/work/pytorch/torch/_subclasses/fake_tensor.py", line 905, in __torch_dispatch__
    r = func.decompose(*args, **kwargs)
  File "/scratch/drisspg/work/pytorch/torch/_ops.py", line 306, in decompose
    return self._op_dk(dk, *args, **kwargs)
RuntimeError: No available kernel.  Aborting execution.
```

Is there a way turn off autograd for FakeTensor

**Comment by drisspg** [comment]
This is because of this line: https://github.com/pytorch/pytorch/blob/550f98332bfd296bf10b50ae43f5677e1f04f4bd/aten/src/ATen/native/transformers/cuda/sdp_utils.h#L155

this will be removed when backward is wiredup anyways
