### ISSUE TITLE
torch.where + DDPoptimizer + Dynamo causes faketensor error

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#92941]
### Summary
When `torch.where(tensor, c, d)` with scalar constants c and d appears in a submod graph of DDP graph optimizer, it the constants c, d appear to get interpreted as Tensors that are not FakeTensors.  It is unclear why they are being interpreted as tensors in the first place.

Something seems to be going wrong in the faketensor layer around DDPOptimizer and its interface calling into the submod compiler.  (cc @ezyang @soumith @msaroufim @ngimel @bdhirsh @voznesenskym)

### Repro

```
import torch
import os
import torch.distributed as dist
from torch import nn
from torch.nn.parallel import DistributedDataParallel as DDP

def setup(rank, world_size):
    os.environ["MASTER_ADDR"] = os.getenv("MASTER_ADDR", "localhost")
    os.environ["MASTER_PORT"] = os.getenv("MASTER_PORT", "12355")
    os.environ["RANK"] = os.getenv("RANK", "0")
    os.environ["WORLD_SIZE"] = os.getenv("WORLD_SIZE", "1")
    dist.init_process_group("nccl")


class MyModule(torch.nn.Module):
    def __init__(self, a, b):
        super(MyModule, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(a, b),
            nn.ReLU(),
        )

    def forward(self, x):
        tmp = self.net(x)
        return torch.where(tmp <= 0.5, 0.4, 1.0)


class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net = nn.Sequential(
            *[nn.Linear(10, 100000)]
            + [MyModule(100000, 5)]
        )

    def forward(self, x):
        return self.net(x)

setup(0, 1)
model = ToyModel()
model.cuda()
inputs = (torch.randn(20, 10, device="cuda"),)

omodel = torch.compile(DDP(model))
omodel(*inputs)
```

gives

```
Traceback (most recent call last):
  File "repro.py", line 45, in <module>
    omodel(*inputs)
  File "/scratch/whc/work/pytorch/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/whc/work/pytorch/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/scratch/whc/work/pytorch/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/scratch/whc/work/pytorch/torch/nn/parallel/distributed.py", line 1158, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/scratch/whc/work/pytorch/torch/nn/parallel/distributed.py", line 1114, in _run_ddp_forward
    return module_to_run(*inputs, **kwargs)
  File "/scratch/whc/work/pytorch/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/whc/work/pytorch/torch/_dynamo/eval_frame.py", line 329, in catch_errors
    return hijacked_callback(frame, cache_size, hooks)
  File "/scratch/whc/work/pytorch/torch/_dynamo/convert_frame.py", line 401, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/scratch/whc/work/pytorch/torch/_dynamo/convert_frame.py", line 102, in _fn
    return fn(*args, **kwargs)
  File "/scratch/whc/work/pytorch/torch/_dynamo/utils.py", line 96, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/whc/work/pytorch/torch/_dynamo/convert_frame.py", line 260, in _convert_frame_assert
    return _compile(
  File "/scratch/whc/work/pytorch/torch/_dynamo/convert_frame.py", line 321, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/whc/work/pytorch/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/whc/work/pytorch/torch/_dynamo/convert_frame.py", line 308, in transform
    tracer.run()
  File "/scratch/whc/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1692, in run
    super().run()
  File "/scratch/whc/work/pytorch/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/scratch/whc/work/pytorch/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/whc/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1758, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/scratch/whc/work/pytorch/torch/_dynamo/output_graph.py", line 527, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/scratch/whc/work/pytorch/torch/_dynamo/output_graph.py", line 598, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/scratch/whc/work/pytorch/torch/_dynamo/output_graph.py", line 674, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
torch._dynamo.exc.BackendCompilerFailed: compile_fn raised BdbQuit: While executing %submod_1 : [#users=1] = call_module[target=submod_1](args = (%submod_0,), kwargs = {})
Original traceback:
None
```

### Versions

repro'd locally on a 1/20 snapshot of master only (9db4323e4c147d258683ca23c9a5a85800c82af6), but issue has been reported more recently on internal fbcode builds.

cc @ezyang @soumith @msaroufim @ngimel @bdhirsh

**Comment by wconstab** [comment]
I came up with a new repro that cuts dynamo, ddp, and graph-splits out of the picture.

```
import torch
from torch._dynamo.utils import deepcopy_to_fake_tensor

class Module(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.self_net_1_net_0 = torch.nn.Linear(in_features=100000, out_features=5, bias=True)
        self.self_net_1_net_1 = torch.nn.ReLU()

    def forward(self, self_net_0):
        self_net_1_net_0 = self.self_net_1_net_0(self_net_0);  self_net_0 = None
        self_net_1_net_1 = self.self_net_1_net_1(self_net_1_net_0);  self_net_1_net_0 = None
        le = self_net_1_net_1 <= 0.5;  self_net_1_net_1 = None
        where = torch.where(le, 0.4, 1.0);  le = None
        return where

m = Module()
input = torch.randn((20, 100000))

fake_mode = torch._subclasses.fake_tensor.FakeTensorMode()

fake_m = deepcopy_to_fake_tensor(m, fake_mode)
fake_input = fake_mode.from_tensor(input)
out = fake_m(fake_input)
```

gives this stacktrace, which is slightly more informative than the one above

```
Traceback (most recent call last):
  File "repro2.py", line 26, in <module>
    out = fake_m(fake_input)
  File "/scratch/whc/work/pytorch/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "repro2.py", line 16, in forward
    where = torch.where(le, 0.4, 1.0);  le = None
  File "/scratch/whc/work/pytorch/torch/_subclasses/fake_tensor.py", line 639, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/scratch/whc/work/pytorch/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/scratch/whc/work/pytorch/torch/_subclasses/fake_tensor.py", line 818, in __torch_dispatch__
    args, kwargs = self.validate_and_convert_non_fake_tensors(
  File "/scratch/whc/work/pytorch/torch/_subclasses/fake_tensor.py", line 966, in validate_and_convert_non_fake_tensors
    return tree_map_only(
  File "/scratch/whc/work/pytorch/torch/utils/_pytree.py", line 259, in tree_map_only
    return tree_map(map_only(ty)(fn), pytree)
  File "/scratch/whc/work/pytorch/torch/utils/_pytree.py", line 195, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/whc/work/pytorch/torch/utils/_pytree.py", line 195, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/whc/work/pytorch/torch/utils/_pytree.py", line 244, in inner
    return f(x)
  File "/scratch/whc/work/pytorch/torch/_subclasses/fake_tensor.py", line 958, in validate
    raise Exception(
Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.where.self(*(FakeTensor(FakeTensor(..., device='meta', size=(20, 5), dtype=torch.bool), cpu), tensor(0.4000), tensor(1.)), **{}) 
```

**Comment by ngimel** [comment]
`where.scalar` is a CompositeImplicitAutograd function https://github.com/pytorch/pytorch/blob/a6ac922eabee8fce7a48dedac81e82ac8cfe9a45/aten/src/ATen/native/native_functions.yaml#L5997, so it's traced to tensor overload.

**Comment by wconstab** [comment]
I see.  It seems to me that the fix for both repros would be to activate a fake mode before executing the composite op,  so the scalar->tensor promotion gets fakeified.  I'll try to make this change.

**Comment by ezyang** [comment]
It's weird that there isn't already a fake tensor mode in the original code

**Comment by bdhirsh** [comment]
Actually, it looks like scalar->tensor conversions get special treatment in torch_dispatch: `__torch_dispatch__` has some special logic to convert "wrapped tensor-scalars" back into scalar python constants ([code](https://github.com/pytorch/pytorch/blob/c0ed0f22cdc5ea80710c845f64d2e9a8026fb810/torch/csrc/jit/python/pybind_utils.cpp#L511))

But that doesn't work properly here, because `where.Scalar` does the scalar->tensor conversion a weird way, probably to preserve type promotion behavior ([code](https://github.com/pytorch/pytorch/blob/c0ed0f22cdc5ea80710c845f64d2e9a8026fb810/aten/src/ATen/native/TensorCompare.cpp#L536)).


@wconstab let me know if your fix pans out. If it doesn't, I think we can tweak the `where.Scalar` decomp to preserve the "wrapped-number"-ness of the scalar-tensor.

**Comment by bdhirsh** [comment]
I tried that briefly and it caused some problems (but maybe we should just fix those problems haha)

Specifically, because the `where.Scalar` decomp **also** changes the dtype when converting the scalar to a tensor, we can end up with a scalar-tensor of arbitrary dtype. And I don't think we support converting arbitrary `c10::Scalar`'s into python numbers today (maybe we should?)

**Comment by ngimel** [comment]
Ah I see, yeah for where we do manual type promotion instead of letting TI handle it, so yeah that means that wrapped numbers can end up being neither Long nor Double which is their usual state.

**Comment by bdhirsh** [comment]
@ngimel do you think it would be reasonable not to do the device move or type promotion at all, and make them ordinary wrapped numbers (that the `where.self` overload needs to properly handle)? I guess that is minorly BC breaking

**Comment by wconstab** [comment]
I also seem to have a fix via https://github.com/pytorch/pytorch/pull/92986 -- do you guys think my fix should not be necessary?  It seems to me that my fix is logically good even if in this instance there is also a bug in `where` op.

**Comment by bdhirsh** [comment]
Oh if that does fix the problem, then it doesn't seem super critical to fix this. I think that arguably, we might be able to make the compiled `where.Scalar` faster if we keep the scalars around as wrapped numbers, but probably isn't critical? (But Natalia lmk if you think it's worth fixing)

**Comment by ngimel** [comment]
@bdhirsh it would be great to fix `where`, the problem with wrapped number is I don't know of a way to move it to device in a non-synchronizing way (probably there is an API for that, I just don't know it, roughly, I need to get the value out of wrapped number and then call `scalar_tensor` on this value, but I don't know off the top of my head how to do the first part :-) )
