### ISSUE TITLE
Test Failure: TestUpgraders.test_aten_div_scalar_at_3 on a big-endian machine (issue in torch.jit.load())

### ISSUE THREAD

**Issue by kiszk** [pytorch/pytorch#92987]
### 🐛 Describe the bug

When I execute the following test case on a big-endian machine, I got the test failure due to the runtime error. We expect that this test should also pass on a big-endian machine.

```python
$ python test/test_jit.py TestUpgraders.test_aten_div_scalar_at_3
CUDA not available, skipping tests
monkeytype is not installed. Skipping tests for Profile-Directed Typing
E
======================================================================
ERROR: test_aten_div_scalar_at_3 (jit.test_upgraders.TestUpgraders)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ishizaki/PyTorch/master/test/jit/test_upgraders.py", line 246, in test_aten_div_scalar_at_3
    loaded_model = torch.jit.load(model_path)
  File "/home/ishizaki/PyTorch/master/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: Unexpected end of pickler archive.
```

The minimum program to reproduce this issue is here. So, `torch.jit.load()` does not seem to work correctly on a big-endian platform.   

```python
import torch
loaded_model = torch.jit.load("test/jit/fixtures/test_versioned_div_scalar_float_v3.pt")
```

I believe that `torch.jit.load()` reads the multiple-byte data without swapping on a big-endian machine while pickle serialization store data as mostly little-endian (as shown in #92910).

### Versions

```
PyTorch version: 2.0.0a0+git215f4fc
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (s390x)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-125-generic-s390x-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0a0+git17c570c
[conda] Could not collect
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by AlekseiNikiforovIBM** [comment]
This test is passing now on s390x for me. I think one of byte order fixes did the job.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
