### ISSUE TITLE
building sources on Windows fails due missing cmake cache variable CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by biocodz** [pytorch/pytorch#93023]
### 🐛 Describe the bug

Plainly following [build pytorch from source ](https://github.com/pytorch/pytorch#from-source) on Windows 11 with CUDA 11.8. .
```
... # all preliminaries are done
git branch
  * master
python setup.py develop
          Traceback (most recent call last):
          File "C:\Users\biocodz\a1\libs\pytorch\setup.py", line 237, in <module>
              from tools.build_pytorch_libs import build_caffe2
          File "C:\Users\biocodz\a1\libs\pytorch\tools\build_pytorch_libs.py", line 9, in <module>
              from .setup_helpers.cmake import CMake, USE_NINJA
          File "C:\Users\biocodz\a1\libs\pytorch\tools\setup_helpers\cmake.py", line 15, in <module>
              from .env import BUILD_DIR, check_negative_env_flag, IS_64BIT, IS_DARWIN, IS_WINDOWS
          File "C:\Users\biocodz\a1\libs\pytorch\tools\setup_helpers\env.py", line 98, in <module>
              build_type = BuildType()
          File "C:\Users\biocodz\a1\libs\pytorch\tools\setup_helpers\env.py", line 72, in __init__
              self.build_type_string = cast(str, cmake_cache_vars["CMAKE_BUILD_TYPE"])
          KeyError: 'CMAKE_BUILD_TYPE'
```
Note that using `python setup.py develop --cmake-only` doesn't help as the above error happens before `the user has a chance to adjust build options` (see [setup.py:262](https://github.com/pytorch/pytorch/blob/master/setup.py#L262))

The docs are incomplete at best. 
If 'cmake configure' is not done prior running `setup.py` where the CMAKE_BUILD_TYPE is supposed to appear from?
I need to better understand the idea of the build to propose fixes.

### Versions

```
python torch/utils/collect_env.py

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: N/A

Python version: 3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: N/A
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Ti Laptop GPU
Nvidia driver version: 527.41
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.5
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-include               2022.1.0           haa95532_193
[conda] mkl-service               2.4.0            py39h2bbff1b_0
[conda] mkl_fft                   1.3.1            py39h277e83a_0
[conda] mkl_random                1.2.2            py39hf11a4ad_0
[conda] numpy                     1.23.5           py39h3b20f71_0
[conda] numpy-base                1.23.5           py39h4da318b_0
```
(these results are irrelevant to the problem)

**Comment by biocodz** [comment]
Turned out generating cmake configuration (by running `cmake -G ...` or using `cmake-gui`) prior `python setup.py`, causes the problem described above. I.e. if the setup.py finds an existing `build` with cmake generated configuration, it crashes. So, now I'm up to the next error but that's another story.
