### ISSUE TITLE
DISABLED test_fn_grad_linalg_det_singular_cuda_complex128 (__main__.TestBwdGradientsCUDA)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#93044]
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/FAILED%20test_ops_gradients.py%3A%3ATestBwdGradientsCUDA%3A%3Atest_fn_grad_linalg_det_singular_cuda_complex128%20-%20torch.autograd.gradcheck.GradcheckError%3A%20While%20considering%20the%20imaginary%20part%20of%20complex%20outputs%20only%2C%20Jacobian%20mismatch%20for%20output%200%20with%20respect%20to%20input%200%2C)).

```

2023-02-11T01:56:39.7602066Z ____ TestBwdGradientsCUDA.test_fn_grad_linalg_det_singular_cuda_complex128 _____
2023-02-11T01:56:39.7602422Z Traceback (most recent call last):
2023-02-11T01:56:39.7602787Z   File "/var/lib/jenkins/pytorch/test/test_ops_gradients.py", line 26, in test_fn_grad
2023-02-11T01:56:39.7603184Z     self._grad_test_helper(device, dtype, op, op.get_op())
2023-02-11T01:56:39.7603774Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 4266, in _grad_test_helper
2023-02-11T01:56:39.7604415Z     return self._check_helper(device, dtype, op, variant, 'gradcheck', check_forward_ad=check_forward_ad,
2023-02-11T01:56:39.7605075Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 4235, in _check_helper
2023-02-11T01:56:39.7605514Z     self.assertTrue(gradcheck(fn, gradcheck_args,
2023-02-11T01:56:39.7606082Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3790, in gradcheck
2023-02-11T01:56:39.7606529Z     return torch.autograd.gradcheck(fn, inputs, **kwargs)
2023-02-11T01:56:39.7607096Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1470, in gradcheck
2023-02-11T01:56:39.7607468Z     return _gradcheck_helper(**args)
2023-02-11T01:56:39.7608020Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1484, in _gradcheck_helper
2023-02-11T01:56:39.7608503Z     _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
2023-02-11T01:56:39.7609132Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1104, in _gradcheck_real_imag
2023-02-11T01:56:39.7609590Z     gradcheck_fn(imag_fn, imag_func_out, tupled_inputs, imag_outputs, eps,
2023-02-11T01:56:39.7610268Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1363, in _fast_gradcheck
2023-02-11T01:56:39.7610751Z     _check_analytical_numerical_equal(analytical_vJu, numerical_vJu, complex_indices,
2023-02-11T01:56:39.7611411Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1335, in _check_analytical_numerical_equal
2023-02-11T01:56:39.7611948Z     raise GradcheckError(_get_notallclose_msg(a, n, j, i, complex_indices, test_imag, is_forward_ad) + jacobians_str)
2023-02-11T01:56:39.7612577Z torch.autograd.gradcheck.GradcheckError: While considering the imaginary part of complex outputs only, Jacobian mismatch for output 0 with respect to input 0,
2023-02-11T01:56:39.7613233Z numerical:tensor(-0.0969+0.7254j, device='cuda:0', dtype=torch.complex128)
2023-02-11T01:56:39.7613704Z analytical:tensor(0.+0.j, device='cuda:0', dtype=torch.complex128)
2023-02-11T01:56:39.7613922Z 
2023-02-11T01:56:39.7614193Z The above quantities relating the numerical and analytical jacobians are computed
2023-02-11T01:56:39.7614644Z in fast mode. See: https://github.com/pytorch/pytorch/issues/53876 for more background
2023-02-11T01:56:39.7615095Z about fast mode. Below, we recompute numerical and analytical jacobians in slow mode:
2023-02-11T01:56:39.7615334Z 
2023-02-11T01:56:39.7615410Z Numerical:
2023-02-11T01:56:39.7615691Z  tensor([[-0.7813+0.5384j],
2023-02-11T01:56:39.7615976Z         [ 0.3935-1.0799j],
2023-02-11T01:56:39.7616235Z         [-0.5603-0.2725j],
2023-02-11T01:56:39.7616509Z         [-0.0583-0.5772j],
2023-02-11T01:56:39.7616730Z         [ 0.4626+0.5289j],
2023-02-11T01:56:39.7616982Z         [ 0.3111-0.2199j],
2023-02-11T01:56:39.7617250Z         [ 1.1665-0.1440j],
2023-02-11T01:56:39.7617517Z         [-1.0504+0.9609j],
2023-02-11T01:56:39.7617888Z         [ 0.4595+0.6201j]], device='cuda:0', dtype=torch.complex128)
2023-02-11T01:56:39.7618174Z Analytical:
2023-02-11T01:56:39.7618395Z tensor([[0.+0.j],
2023-02-11T01:56:39.7618602Z         [0.+0.j],
2023-02-11T01:56:39.7618815Z         [0.+0.j],
2023-02-11T01:56:39.7619026Z         [0.+0.j],
2023-02-11T01:56:39.7619221Z         [0.+0.j],
2023-02-11T01:56:39.7619424Z         [0.+0.j],
2023-02-11T01:56:39.7619627Z         [0.+0.j],
2023-02-11T01:56:39.7619816Z         [0.+0.j],
2023-02-11T01:56:39.7620170Z         [0.+0.j]], device='cuda:0', dtype=torch.complex128)
2023-02-11T01:56:39.7620363Z 
2023-02-11T01:56:39.7620614Z The max per-element difference (slow mode) is: 1.4236150551283344.
```
cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by soulitzer** [comment]
Should be addressed by https://github.com/pytorch/pytorch/pull/96707
