### ISSUE TITLE
`dstack` + `reciprocal` produce wrong result in compile mode

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#93078]
### 🐛 Describe the bug

The following program prints different results in eager mode and compile mode:
```python
import torch

def fn(input):
    v1 = torch.dstack([input, input, input])   # works fine with [input, input]
                                               # works fine if directly passing tensor to reciprocal
    return torch.reciprocal(v1)

x = torch.tensor(True)

ret_eager = fn(x)

compiled = torch.compile(fn)
ret_compiled = compiled(x)

for r1, r2 in zip(ret_eager, ret_compiled):
    assert torch.allclose(r1, r2), (r1, r2)
print('==== Check OK! ====')

"""
Traceback (most recent call last):
  File "repro.py", line 15, in <module>
    assert torch.allclose(r1, r2), (r1, r2)
AssertionError: (tensor([[1., 1., 1.]]), tensor([[1.0000, 1.0000, 0.0115]]))
"""
```
According to the doc, `tensor([[1, 1, 1]])` should be the correct result. In compile mode, the third value is nondeterministic and always not equal to 1.
It's worth noting that if we directly pass a tensor with shape `[1, 1, 3]` to `torch.reciprocal`, the result is correct. Also, if we only pass `input` twice in `dstack`, i.e., `v1 = torch.dstack([input, input])`, the program also works fine.

### Versions

<details><summary><b>Environment</b> <i>[Click to expand]</i></summary>

```
PyTorch version: 2.0.0.dev20230121+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 11.1.0-6
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230121+cu117
[pip3] torchaudio==2.0.0.dev20230118+cu117
[pip3] torchvision==0.15.0.dev20230118+cu117
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] torch                     1.14.0a0+gitce2f870          pypi_0    pypi
```

</details>

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @Guobing-Chen @chunyuan-w @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by eellison** [comment]
I ran this on master, and couldn't repro.

**Comment by ganler** [comment]
*tried Python 3.9 as well which does not repro this bug. So it might be specific to Python 3.10.

**Comment by malfet** [comment]
Hmm, perhaps I'm doing something wrong, but I can not repro it with Jan 27th nightly:
```python
print(f'==== Check OK! ==== version {torch.__version__} version_info {sys.version_info}')
```
```
$ python ~/test/compile-cpu.py 
/home/nshulga/miniconda3/envs/py310/lib/python3.10/site-packages/torch/_inductor/compile_fx.py:90: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
==== Check OK! ==== version 2.0.0.dev20230127 version_info sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)
```

**Comment by malfet** [comment]
@ganler can you share a bit more information about your host compiler, openmp runtime, etc?

**Comment by ganler** [comment]
Here is the information collected by `collect_env.py`:

```
PyTorch version: 2.0.0.dev20230126+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230126+cu117
[pip3] torchaudio==2.0.0.dev20230126+cu117
[pip3] torchvision==0.15.0.dev20230126+cu117
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230126+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230126+cu117          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230126+cu117          pypi_0    pypi
```

**Comment by ganler** [comment]
Notably,  the value of the third output seems to be deterministic:

Round 1:

```
/home/jiawei/miniconda3/envs/test/lib/python3.10/site-packages/torch/_inductor/compile_fx.py:89: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
[2023-01-27 13:41:03,605] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 0

from ctypes import c_void_p, c_long
import torch
import random
from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()

import triton
import triton.language as tl
from torch._inductor.triton_ops.autotune import grid
from torch._C import _cuda_getCurrentRawStream as get_cuda_stream


kernel_cpp_0 = async_compile.cpp('''
#include "/tmp/torchinductor_jiawei/77/c7773nj5pwikpmm2pwa62rcudlf7p3if7eyqb5k4sjsvewwje4le.h"
extern "C" void kernel(const bool* __restrict__ in_ptr0,
                       const bool* __restrict__ in_ptr1,
                       bool* __restrict__ out_ptr0,
                       bool* __restrict__ out_ptr1,
                       bool* __restrict__ out_ptr2,
                       float* __restrict__ out_ptr3)
{
    {
        auto tmp0 = in_ptr0[0];
        out_ptr0[0] = tmp0;
        out_ptr1[0] = tmp0;
        out_ptr2[0] = tmp0;
    }
    {
        #pragma GCC ivdep
        for(long i0=0; i0<3; i0+=1)
        {
            auto tmp0 = in_ptr1[i0];
            auto tmp1 = static_cast<float>(tmp0);
            auto tmp2 = 1 / tmp1;
            out_ptr3[i0] = tmp2;
        }
    }
}
''')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, = args
    args.clear()
    buf3 = empty_strided((1, 1, 3), (3, 3, 1), device='cpu', dtype=torch.bool)
    buf0 = as_strided(buf3, (1, 1, 1), (3, 3, 1))  # alias
    buf1 = as_strided(buf3, (1, 1, 1), (3, 3, 1), 1)  # alias
    buf2 = as_strided(buf3, (1, 1, 1), (3, 3, 1), 2)  # alias
    buf4 = empty_strided((1, 1, 3), (3, 3, 1), device='cpu', dtype=torch.float32)
    kernel_cpp_0(c_void_p(arg0_1.data_ptr()), c_void_p(buf3.data_ptr()), c_void_p(buf0.data_ptr()), c_void_p(buf1.data_ptr()), c_void_p(buf2.data_ptr()), c_void_p(buf4.data_ptr()))
    del arg0_1
    del buf0
    del buf1
    del buf2
    return (buf4, )


if __name__ == "__main__":
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((), (), device='cpu', dtype=torch.bool)
    print_performance(lambda: call([arg0_1]))

[2023-01-27 13:41:05,438] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 0
Traceback (most recent call last):
  File "/home/jiawei/dev/nnsmith-exp/test.py", line 19, in <module>
    assert torch.allclose(r1, r2), (r1, r2)
AssertionError: (tensor([[1., 1., 1.]]), tensor([[1., 1., inf]]))
```

Round 2:

```
/home/jiawei/miniconda3/envs/test/lib/python3.10/site-packages/torch/_inductor/compile_fx.py:89: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
[2023-01-27 13:41:08,982] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 0

from ctypes import c_void_p, c_long
import torch
import random
from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()

import triton
import triton.language as tl
from torch._inductor.triton_ops.autotune import grid
from torch._C import _cuda_getCurrentRawStream as get_cuda_stream


kernel_cpp_0 = async_compile.cpp('''
#include "/tmp/torchinductor_jiawei/77/c7773nj5pwikpmm2pwa62rcudlf7p3if7eyqb5k4sjsvewwje4le.h"
extern "C" void kernel(const bool* __restrict__ in_ptr0,
                       const bool* __restrict__ in_ptr1,
                       bool* __restrict__ out_ptr0,
                       bool* __restrict__ out_ptr1,
                       bool* __restrict__ out_ptr2,
                       float* __restrict__ out_ptr3)
{
    {
        auto tmp0 = in_ptr0[0];
        out_ptr0[0] = tmp0;
        out_ptr1[0] = tmp0;
        out_ptr2[0] = tmp0;
    }
    {
        #pragma GCC ivdep
        for(long i0=0; i0<3; i0+=1)
        {
            auto tmp0 = in_ptr1[i0];
            auto tmp1 = static_cast<float>(tmp0);
            auto tmp2 = 1 / tmp1;
            out_ptr3[i0] = tmp2;
        }
    }
}
''')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, = args
    args.clear()
    buf3 = empty_strided((1, 1, 3), (3, 3, 1), device='cpu', dtype=torch.bool)
    buf0 = as_strided(buf3, (1, 1, 1), (3, 3, 1))  # alias
    buf1 = as_strided(buf3, (1, 1, 1), (3, 3, 1), 1)  # alias
    buf2 = as_strided(buf3, (1, 1, 1), (3, 3, 1), 2)  # alias
    buf4 = empty_strided((1, 1, 3), (3, 3, 1), device='cpu', dtype=torch.float32)
    kernel_cpp_0(c_void_p(arg0_1.data_ptr()), c_void_p(buf3.data_ptr()), c_void_p(buf0.data_ptr()), c_void_p(buf1.data_ptr()), c_void_p(buf2.data_ptr()), c_void_p(buf4.data_ptr()))
    del arg0_1
    del buf0
    del buf1
    del buf2
    return (buf4, )


if __name__ == "__main__":
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((), (), device='cpu', dtype=torch.bool)
    print_performance(lambda: call([arg0_1]))

[2023-01-27 13:41:10,837] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 0
Traceback (most recent call last):
  File "/home/jiawei/dev/nnsmith-exp/test.py", line 19, in <module>
    assert torch.allclose(r1, r2), (r1, r2)
AssertionError: (tensor([[1., 1., 1.]]), tensor([[1.0000, 1.0000, 0.0097]]))
```

**Comment by ngimel** [comment]
The cpu code generated is wrong, it decorates aliased pointers (`in_ptr1` and `out_ptr*`) with `__restrict__`. cc @jgong5

**Comment by ezyang** [comment]
cc @bdhirsh 

This kind of seems like something functionalization in inference mode would fix. Could you try running with https://github.com/pytorch/pytorch/pull/92857 patched in?

**Comment by eellison** [comment]
@ezyang we'll still need to handle aliased storages

**Comment by ezyang** [comment]
Not if your graph is functionalized? Or at least, incorrect `__restrict__` annotation on read-only pointers should be harmless.

**Comment by ngimel** [comment]
```
    v1 = torch.dstack([input, input, input])   
    return torch.reciprocal(v1)
```
is functional already, v1-as-output is naturally aliased with v1-as-input even in a functional graph, and they are put in the same kernel, which is a bug. Just putting things in brackets that cpu uses for codegen of the different fusion groups is not the same hard separation as putting them in the distinct functions.

**Comment by ezyang** [comment]
Hmm... this gets worse and worse then. Suppose we instead compile:

```
    v1 = torch.dstack([a, b, c])   
    return torch.reciprocal(v1)
```

Memory planning may decide that it wants to allocate v1 on top of a. Omitting the restrict between v1_out and a_in, this code would even work, unless we called it in another context where a was an alias with b and c. This means, somehow, the memory planner needs to know how to install a guard (@voznesenskym) whenever it makes a memory planning assumption that requires some inputs to alias. I... struggle to understand how most backends will be able to do this correctly.

**Comment by voznesenskym** [comment]
> This means, somehow, the memory planner needs to know how to install a guard 

sad trombone noises - do we have enough info upfront to build a heuristic for this? without waiting for us to hit the memory planner?

**Comment by ganler** [comment]
Just want to update that at the nightly version this bug seems to be fixed:

https://colab.research.google.com/drive/1o8PoSDeWmxEhc-2hJlDXn9Sv51qH-iGB?usp=sharing

So maybe feel free to close the issue as resolved. Thanks!
