### ISSUE TITLE
Dynamo crashes on code that contains torchvision transforms

### ISSUE THREAD

**Issue by 7andrew7** [pytorch/pytorch#93180]
### 🐛 Describe the bug

Running a torchvision transform within the optimization target generates an assertion failure.

### Error logs

```
(venv2) ubuntu@ip-172-31-37-11:~/dynamite$ python repro.py
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "repro.py", line 21, in <module>
    print(opt_f(im))
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "repro.py", line 16, in f
    return transform(img)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 346, in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 466, in resize
    _, image_height, image_width = get_dimensions(img)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 403, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 261, in _convert_frame_assert
    return _compile(
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 160, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 323, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 310, in transform
    tracer.run()
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1717, in run
    super().run()
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 563, in run
    and self.step()
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 526, in step
    getattr(self, inst.opname)(inst)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 362, in wrapper
    self.output.compile_subgraph(self, reason=reason)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 532, in compile_subgraph
    pass1.foreach(stack_values)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/codegen.py", line 158, in foreach
    self(i)
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/codegen.py", line 89, in __call__
    output.extend(value.source.reconstruct(self))
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/source.py", line 334, in reconstruct
    codegen.create_load_const(self.index),
  File "/home/ubuntu/venv2/lib/python3.8/site-packages/torch/_dynamo/codegen.py", line 221, in create_load_const
    assert is_safe_constant(value), f"unsafe constant {value}"
AssertionError: unsafe constant InterpolationMode.BILINEAR

from user code:
   File "/home/ubuntu/venv2/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 478, in <graph break in resize>
    return F_pil.resize(img, size=output_size, interpolation=pil_interpolation)

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Minified repro

```
import torch
import torch._dynamo as dynamo

from torchvision import transforms
from PIL import Image

transform = transforms.Compose([
  transforms.Resize(256),
  transforms.CenterCrop(224),
  transforms.ToTensor(),
  transforms.Normalize(
      mean=[0.485, 0.456, 0.406],
      std=[0.229, 0.224, 0.225])])

def f(img):
    return transform(img)

im = Image.new(mode="RGB", size=(20, 20))

opt_f = dynamo.optimize("inductor")(f)
print(opt_f(im))
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230127+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1026-aws-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0.dev20230127+cpu
[pip3] torchaudio==2.0.0.dev20230127+cpu
[pip3] torchvision==0.15.0.dev20230127+cpu
[conda] No relevant packages

cc @datumbox @vfdev-5 @pmeier @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ezyang** [comment]
This actually does not error for me

```
$ python n.py
/data/users/ezyang/a/pytorch/torch/_inductor/compile_fx.py:90: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         ...,
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         ...,
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357]],

        [[-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
         [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
         [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
         ...,
         [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
         [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
         [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044]]])
```

I'm on 0dceaf07cd1236859953b6f85a61dc4411d10f87 with Python 3.9. Wonder if it's a Python version thing. InterpolationMode is an Enum in torchvision as of 93df9a50885d0345e31bba691576c83d5cee7737 and therefore should clearly pass if_safe_constant

```
def is_safe_constant(v):
    if istype(v, (tuple, frozenset)):
        return all(map(is_safe_constant, v))
    return istype(
        v,
        (
            types.CodeType,
            int,
            float,
            bool,
            str,
            bytes,
            type(None),
            slice,
            type(type),
            torch.device,
        ),
    ) or isinstance(v, enum.Enum)
```

As a workaround, you could monkeypatch this function to return True

**Comment by ezyang** [comment]
Ah yes, because Enum support added in https://github.com/pytorch/pytorch/pull/93026 . upgrade and it will be fixed!
