### ISSUE TITLE
`torch.compile` generates wrong profiling program for function having `transpose` and `lerp`

### ISSUE THREAD

**Issue by Co1lin** [pytorch/pytorch#93229]
### 🐛 Describe the bug

The following program leads to an error.

```python
import torch

def fn(i0, i1):
    # i0: (10, 3, 10)
    # i1: (3, 10, 10)
    x1 = i0.transpose(-2, -3)
    y = torch.lerp(x1, x1, 70000)
    z = torch.lerp(i1, x1, 70000)
    return y, z

x0 = torch.rand(10, 3, 10)
x1 = torch.rand(3, 10, 10)
ret_eager = fn(x0, x1)
print('==== Eager mode OK! ====')
compiled = torch.compile(fn, fullgraph=True)
ret_compiled = compiled(x0, x1)
print('==== compile mode OK! ====')
```

<details>
<summary>Error logs</summary>

```python
==== Eager mode OK! ====
/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_inductor/compile_fx.py:90: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
[2023-01-29 12:24:11,298] torch._inductor.graph: [WARNING] Creating implicit fallback for:
  target: aten.lerp.Scalar
  args[0]: TensorBox(
    ReinterpretView(
      StorageBox(
        InputBuffer(name='arg0_1', layout=FixedLayout('cpu', torch.float32, size=[10, 3, 10], stride=[30, 10, 1]))
      ),
      FixedLayout('cpu', torch.float32, size=[3, 10, 10], stride=[10, 30, 1]),
      no origins?
    )
  )
  args[1]: TensorBox(
    ReinterpretView(
      StorageBox(
        InputBuffer(name='arg0_1', layout=FixedLayout('cpu', torch.float32, size=[10, 3, 10], stride=[30, 10, 1]))
      ),
      FixedLayout('cpu', torch.float32, size=[3, 10, 10], stride=[10, 30, 1]),
      no origins?
    )
  )
  args[2]: 70000
[2023-01-29 12:24:11,298] torch._inductor.lowering: [WARNING] make_fallback(aten.lerp.Scalar): a decomposition exists, we should switch to it
[2023-01-29 12:24:11,302] torch._inductor.graph: [WARNING] Using FallbackKernel: torch.ops.aten.lerp.Scalar
Traceback (most recent call last):
  File "/JawTitan/colin-data/code/nnsmith-autoinf/path/program/bug.py", line 16, in <module>
    ret_compiled = compiled(x0, x1)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/JawTitan/colin-data/code/nnsmith-autoinf/path/program/bug.py", line 3, in fn
    def fn(i0, i1):
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2497, in forward
    return compiled_fn(full_args)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1065, in new_fn
    fw_outs = call_func_with_args(compiled_fw, args, disable_amp=disable_amp)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1021, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/tmp/torchinductor_colin/7e/c7ecgf4cpwsxbchmld4r45sobcztirjkhnmn4nlavrws4swss3b6.py", line 33, in call
    assert_size_stride(buf3, (3, 10, 10), (10, 30, 1))
AssertionError: expected size 3==3, stride 100==10 at dim=0
```
</details>

<details>
<summary>The generated profiling program</summary>

```python

from ctypes import c_void_p, c_long
import torch
import random
from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()

import triton
import triton.language as tl
from torch._inductor.triton_ops.autotune import grid
from torch._C import _cuda_getCurrentRawStream as get_cuda_stream


triton__0 = async_compile.triton('''
import triton
import triton.language as tl
from torch._inductor.ir import ReductionHint
from torch._inductor.ir import TileHint
from torch._inductor.triton_ops.autotune import pointwise
from torch._inductor.utils import instance_descriptor

@pointwise(size_hints=[512], filename=__file__, meta={'signature': {0: '*fp32', 1: '*fp32', 2: 'i32'}, 'device': 0, 'constants': {}, 'mutated_arg_names': [], 'configs': [instance_descriptor(divisible_by_16=(0, 1), equal_to_1=())]})
@triton.jit
def triton_(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 300
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), xmask)
    tmp1 = tl.libdevice.expm1(tmp0)
    tl.store(out_ptr0 + (x0 + tl.zeros([XBLOCK], tl.int32)), tmp1, xmask)
''')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1 = args
    args.clear()
    with torch.cuda._DeviceGuard(0):
        torch.cuda.set_device(0) # no-op to ensure context
        buf0 = empty_strided((3, 10, 10), (10, 30, 1), device='cuda', dtype=torch.float32)
        stream0 = get_cuda_stream(0)
        triton__0.run(arg0_1, buf0, 300, grid=grid(300), stream=stream0)
        buf1 = torch.ops.aten.lerp.Scalar(as_strided(arg0_1, (3, 10, 10), (10, 30, 1)), as_strided(arg0_1, (3, 10, 10), (10, 30, 1)), 70000)
        buf2 = buf1
        assert_size_stride(buf2, (3, 10, 10), (10, 30, 1))
        del buf1
        buf3 = torch.ops.aten.lerp.Scalar(arg1_1, as_strided(arg0_1, (3, 10, 10), (10, 30, 1)), 70000)
        del arg0_1
        del arg1_1
        buf4 = buf3
        assert_size_stride(buf4, (3, 10, 10), (10, 30, 1))
        del buf3
        return (buf0, buf2, as_strided(buf4, (10, 3, 10), (30, 10, 1)), )


if __name__ == "__main__":
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((10, 3, 10), (30, 10, 1), device='cuda:0', dtype=torch.float32)
    arg1_1 = rand_strided((3, 10, 10), (100, 10, 1), device='cuda:0', dtype=torch.float32)
    print_performance(lambda: call([arg0_1, arg1_1]))

```
</details>

### Versions

```python
Collecting environment information...
PyTorch version: 2.0.0.dev20230129+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-137-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 510.68.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230129+cu117
[pip3] torchaudio==2.0.0.dev20230129+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20230129+cu117
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230129+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230129+cu117          pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230129+cu117          pypi_0    pypi
```

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by XiaobingSuper** [comment]
**https://github.com/pytorch/pytorch/pull/93336** has been merged, closed it now.
