### ISSUE TITLE
DistributedDataParallel call _get_code_from_file every epoch

### ISSUE THREAD

**Issue by thjashin** [pytorch/pytorch#93220]
### 🐛 Describe the bug

I was using DistributedDataParallel but I kept finding that when I changed my source code after I ran it, the program crashes as it is affected by the code change. I looked into this problem and find that every epoch DDP is calling _get_code_from_file. Is this a bug? 

error message if I removed one ")" from the code after I ran it:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../jiaxins/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File ".../jiaxins/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File ".../jiaxins/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File ".../jiaxins/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File ".../jiaxins/miniconda3/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File ".../jiaxins/miniconda3/lib/python3.10/runpy.py", line 257, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File ".../jiaxins/code/multires/seq_cifar.py", line 489
    model = DDP(model, device_ids=[rank]
SyntaxError: '(' was never closed
```

### Similar issues in the forum (unsolved)

https://discuss.pytorch.org/t/ddp-is-affected-by-code-modification/148046
https://discuss.pytorch.org/t/with-the-pytorch-distributed-training-model-code-changes-affect-running-applications/142020

### Versions

```
Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Clang version: Could not collect
CMake version: version 3.5.1
Libc version: glibc-2.23

Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-65-generic-x86_64-with-glibc2.23
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti
GPU 4: NVIDIA GeForce RTX 2080 Ti
GPU 5: NVIDIA GeForce RTX 2080 Ti
GPU 6: NVIDIA GeForce RTX 2080 Ti
GPU 7: NVIDIA GeForce RTX 2080 Ti
GPU 8: NVIDIA GeForce RTX 2080 Ti
GPU 9: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchtext==0.13.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.23.5          py310hd5efca6_0  
[conda] numpy-base                1.23.5          py310h8e6c178_0  
[conda] pytorch                   1.12.0          py3.10_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.0              py310_cu113    pytorch
[conda] torchtext                 0.13.0                   pypi_0    pypi
[conda] torchvision               0.13.0              py310_cu113    pytorch
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by wanchaol** [comment]
@dagitses As you have found out already, this is because of the multiprocessing module (spawn) in python load the modified content dynamically when you load the code to the python interpreter, there's nothing related to DDP. Did you build it in develop mode? I think if you do python setup.py install it might not pick up your changes on the fly. 

Closing, feel free to reopen it if you need additional help.

**Comment by thjashin** [comment]
Hi @wanchaol @dagitses , I want to clarify that this happens even **after the training has been executed for many epochs**. From what I understand the spawn has already finished loading the code by then. What is strange is that DDP seems to be calling spawn every epoch. I didn't use the develop mode. I use a standard version from pip install.

**Comment by thjashin** [comment]
@wanchaol @dagitses Any ideas on this?
