### ISSUE TITLE
squeezenet1_1 fails accuracy with AMP (but not on CI and dashboard); minifier does not work (when not using cuDNN?)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93227]
### 🐛 Describe the bug

Passes:

```
$ python benchmarks/dynamo/torchbench.py --accuracy --ci --inductor --explain --float32  --only squeezenet1_1             
cuda eval  squeezenet1_1                       PASS 

```

Fails:

```
$ python benchmarks/dynamo/torchbench.py --accuracy --ci --inductor --explain  --only squeezenet1_1                                                                            cuda eval  squeezenet1_1                       [2023-01-29 10:08:26,792] torch._dynamo.utils: [ERROR] RMSE 
(res-fp64): 0.00684, (ref-fp64): 0.00162 and shape=torch.Size([4, 1000])
```

The generated minifier script does not work. Script: https://gist.github.com/2e8cf91ee94dc60aeb08fad36338bfd1

Fails with https://gist.github.com/ezyang/3112ada879393bbbb8c0e70d740e7fac

```
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/utils.py", line 1167, in run_node
    return nnmodule(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/users/ezyang/b/pytorch/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::Half) and bias type (float) should be the same
```

Maybe my problem is I don't have cuDNN on this build (smh)

```
PyTorch built with:
  - GCC 8.5
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.1-Product Build 20220311 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.4
  - NVCC architecture flags: -gencode;arch=compute_80,code=sm_80
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.4, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 
 ```

### Versions

master

**Comment by leslie-fang-intel** [comment]
Not sure bout CUDA AMP, @ezyang but look likes you disabled AMP in your generated minifier script?https://gist.github.com/ezyang/2e8cf91ee94dc60aeb08fad36338bfd1#file-minifier_launcher-py-L172

**Comment by ezyang** [comment]
I could believe it; I've recently been trying to figure out why the minifier is busted at part of the problem is it's not properly propagating config lol
