### ISSUE TITLE
`index_put_` failed to run on GPU

### ISSUE THREAD

**Issue by Co1lin** [pytorch/pytorch#93248]
### 🐛 Describe the bug

Program to reproduce:

```python
import torch

def fn(x, index, src):
    x.index_put_([index], src, accumulate=True) # RuntimeError
    # o = torch.index_put(x, [index], src, accumulate=True) # RuntimeError
    # x[index] += src # works fine
    return x

x = torch.rand(3, 3)
src = torch.rand(3)
index = torch.tensor([1, 1, 1])

fn(x, index, src)
print('==== cpu eager mode OK! ====')

fn(x.cuda(), index.cuda(), src.cuda())
print('==== gpu eager mode OK! ====')
```

Error logs:

```python
==== cpu eager mode OK! ====
Traceback (most recent call last):
  File "/home/colin/code/bug.py", line 16, in <module>
    fn(x.cuda(), index.cuda(), src.cuda())
  File "/home/colin/code/bug.py", line 5, in fn
    x.index_put_([index], src, accumulate=True)
RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == expandedValue.numel() INTERNAL ASSERT FAILED at "../aten/src/ATen/native/cuda/Indexing.cu":389, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor: 9 vs 3
```

### Versions

```python
Collecting environment information...
PyTorch version: 2.0.0.dev20230129+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-137-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 510.68.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230129+cu117
[pip3] torchaudio==2.0.0.dev20230129+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20230129+cu117
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230129+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230129+cu117          pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230129+cu117          pypi_0    pypi
```

**Comment by ngimel** [comment]
duplicate of #79987
