### ISSUE TITLE
MMEditing meets `NotImplementedError: UserDefinedClassVariable() has no type` error in training with EAGER backend...

### ISSUE THREAD

**Issue by LeoXing1996** [pytorch/pytorch#93260]
### 🐛 Describe the bug

Training GAN models with `eager` backend got `NotImplementedError: UserDefinedClassVariable() has no type`.

Error traceback is shown as below:
<details>

```
Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 323, in _compile
    out_code = transform_code_object(code, transform)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 310, in transform
    tracer.run()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1727, in run
    super().run()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 333, in wrapper
    return inner_fn(self, inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1000, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 289, in call_function
    return super().call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 259, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 92, in call_function
    return tx.inline_user_function_return(
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 497, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1805, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1861, in inline_call_
    tracer.run()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 333, in wrapper
    return inner_fn(self, inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1000, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 289, in call_function
    return super().call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 259, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 92, in call_function
    return tx.inline_user_function_return(
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 497, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1805, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1861, in inline_call_
    tracer.run()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 333, in wrapper
    return inner_fn(self, inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1000, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 670, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 70, in call_method
    inner_fn = self.const_getattr(self, name)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 53, in const_getattr
    type_to_use = self.objvar.python_type()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/base.py", line 146, in python_type
    raise NotImplementedError(f"{self} has no type")
NotImplementedError: UserDefinedClassVariable() has no type

from user code:
   File "/mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/base_models/base_gan.py", line 438, in train_step
    message_hub = MessageHub.get_current_instance()
  File "/mnt/petrelfs/xingzhening/mmengine-compile/mmengine/logging/message_hub.py", line 100, in get_current_instance
    return super().get_current_instance()

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main()
  File "tools/train.py", line 108, in main
    runner.train()
  File "/mnt/petrelfs/xingzhening/mmengine-compile/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File "/mnt/petrelfs/xingzhening/mmengine-compile/mmengine/runner/loops.py", line 264, in run
    self.run_iter(data_batch)
  File "/mnt/petrelfs/xingzhening/mmengine-compile/mmengine/runner/loops.py", line 287, in run_iter
    outputs = self.runner.model.train_step(
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 403, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 261, in _convert_frame_assert
    return _compile(
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 160, in time_wrapper
    r = func(*args, **kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 393, in _compile
    raise InternalTorchDynamoError() from e
torch._dynamo.exc.InternalTorchDynamoError
```

</details>

### Minified repro

1. Install dependencied of OpenMMLab

```
ninja
git+https://github.com/open-mmlab/mmengine@experimental/compile
git+https://github.com/open-mmlab/mmcv@2.x
```

3. Install MMEditing from source

```bash
git clone git@github.com:open-mmlab/mmediting.git
cd mmediting
git checkout dev-1.x
pip install -r requirements.txt
pip install -e .
```

4. Launch training

```bash
# all GAN models failed since they all build upon `BaseGAN`
python tools/train.py configs/wgan-gp/wgangp_GN_1xb64-160kiters_celeba-cropped-128x128.py \
    --cfg-options compile.target='train_step' compile.backend='eager'
```

### Versions

Pytorch version: 2.0.0.dev20230129+cu116

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by yanboliang** [comment]
This is because ```UserDefinedClassVariable``` is lack of ```python_type``` support, will send a PR to fix it.

**Comment by LeoXing1996** [comment]
@yanboliang, I tried Pytorch `2.0.0.dev20230202+cu116` which contains your modification, but the error still occurs.

When I tried to set `torch._dynamo.config.verbose=True` at the start of my code, `NotImplementedError` was raised but training continued. 

Detailed output is shown as below:

<details>

```
02/06 20:56:28 - mmengine - INFO - Working directory: work_dirs/biggan-pt20
02/06 20:56:28 - mmengine - INFO - Log directiry: /mnt/petrelfs/xingzhening/mmedit-pt20/work_dirs/biggan-pt20/20230206_205625
02/06 20:56:28 - mmengine - WARNING - The "dataset" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:56:31 - mmengine - WARNING - The "transform" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:03 - mmengine - WARNING - The "data sampler" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:03 - mmengine - WARNING - The "optimizer wrapper constructor" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:03 - mmengine - WARNING - The "optimizer" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:03 - mmengine - WARNING - The "optim_wrapper" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:03 - mmengine - WARNING - The "loop" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:35 - mmengine - WARNING - The "evaluator" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:35 - mmengine - WARNING - The "metric" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:35 - mmengine - INFO - Text logs will be saved to work_dirs/pt20/biggan-pt20 after the training process.
02/06 20:57:35 - mmengine - INFO - Checkpoints will be saved to work_dirs/pt20/biggan-pt20.
[2023-02-06 20:57:35,948] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT train_step /mnt/petrelfs/xingzhening/mmengine-compile/mmengine/model/wrappers/seperate_distributed.py line 89 
due to: 
Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 58, in const_getattr
    return getattr(super(search_type, type_to_use), name)
TypeError: super(type, obj): obj must be an instance or subtype of type

from user code:
   File "/mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/base_models/base_gan.py", line 438, in train_step
    message_hub = MessageHub.get_current_instance()
  File "/mnt/petrelfs/xingzhening/mmengine-compile/mmengine/logging/message_hub.py", line 100, in get_current_instance
    return super().get_current_instance()

Set torch._dynamo.config.verbose=True for more information


[2023-02-06 20:57:35,978] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT train_step /mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/base_models/base_gan.py line 420 
due to: 
Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 58, in const_getattr
    return getattr(super(search_type, type_to_use), name)
TypeError: super(type, obj): obj must be an instance or subtype of type

from user code:
   File "/mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/base_models/base_gan.py", line 438, in train_step
    message_hub = MessageHub.get_current_instance()
  File "/mnt/petrelfs/xingzhening/mmengine-compile/mmengine/logging/message_hub.py", line 100, in get_current_instance
    return super().get_current_instance()

Set torch._dynamo.config.verbose=True for more information


[2023-02-06 20:57:43,635] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:48,062] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:48,492] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:48,523] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT disc_loss /mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/editors/wgan_gp/wgan_gp.py line 32 
due to: 
Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/base.py", line 209, in reconstruct
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: reconstruct: ConstantVariable(dict)

Set torch._dynamo.config.verbose=True for more information


[2023-02-06 20:57:48,538] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:57,963] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:57,979] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:57,995] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT gen_loss /mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/editors/wgan_gp/wgan_gp.py line 61 
due to: 
Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/base.py", line 209, in reconstruct
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: reconstruct: ConstantVariable(dict)

Set torch._dynamo.config.verbose=True for more information


02/06 20:58:24 - mmengine - INFO - Iter(train) [   100/160000]  generator.lr: 1.0000e-04 discriminator.lr: 1.0000e-04  eta: 21:41:52  time: 0.2578  data_time: 0.0332  memory: 9478  loss: -124.6310  loss_disc_fake: -91.5469  loss_disc_real: -90.6519  loss_gp: 57.5678  loss_gen: 118.4739
```

</details>
