### ISSUE TITLE
compiled batchnorm fails

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [pytorch/pytorch#93338]
### 🐛 Describe the bug

The model was a very simple conv + batch norm but the error comes from the batchnorm:

```python
import torch

class NORM(torch.nn.Module):
    def __init__(self,):
        super().__init__()
        self.norm = torch.nn.BatchNorm3d(14)

    def forward(self, x):
        x = self.norm(x)
        return x

model = NORM()
model = torch.compile(model)
rand_input = torch.rand(8, 14, 10, 10, 10)
model(rand_input)
```

### Error logs

The error:
<details>
Traceback (most recent call last):
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1167, in run_node
    return nnmodule(*args, **kwargs)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2450, in batch_norm
    return torch.batch_norm(
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_decomp/decompositions.py", line 1460, in native_batch_norm_decomposition
    return aten._native_batch_norm_legit(
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_ops.py", line 499, in __call__
    return self._op(*args, **kwargs or {})
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 903, in __torch_dispatch__
    return decomposition_table[func](*args, **kwargs)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_decomp/decompositions.py", line 1488, in _native_batch_norm_legit
    output, save_mean, save_rstd, _, _ = native_batch_norm_helper(
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_decomp/decompositions.py", line 1347, in native_batch_norm_helper
    mean = torch.mean(input_acc, dim=reduction_dims, keepdim=True)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 933, in __torch_dispatch__
    r = func(*args, **kwargs)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_refs/__init__.py", line 2383, in mean
    result = true_divide(result, nelem)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 223, in _fn
    result = fn(*args, **kwargs)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_prims_common/wrappers.py", line 133, in _fn
    result = fn(**bound.arguments)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_refs/__init__.py", line 925, in _ref
    return prim(a, b)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_refs/__init__.py", line 1618, in true_divide
    return prims.div(a, b)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_prims/__init__.py", line 349, in _elementwise_meta
    shape = utils.extract_shape(*args_, allow_cpu_scalar_tensors=True)
AttributeError: module 'torch._prims.utils' has no attribute 'extract_shape'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1121, in get_fake_value
    return wrap_fake_exception(
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 783, in wrap_fake_exception
    return fn()
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1122, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1174, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_module self_norm(*(FakeTensor(FakeTensor(..., device='meta', size=(8, 14, 10, 10, 10)), cpu),), **{}):
module 'torch._prims.utils' has no attribute 'extract_shape'
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "minimal_code.py", line 25, in <module>
    model(rand_input)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 403, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 261, in _convert_frame_assert
    return _compile(
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 160, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 323, in _compile
    out_code = transform_code_object(code, transform)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 310, in transform
    tracer.run()
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1727, in run
    super().run()
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 333, in wrapper
    return inner_fn(self, inst)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1000, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/variables/nn_module.py", line 203, in call_function
    return wrap_fx_proxy(
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 764, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 799, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/usr/users/sdi1/sdi1_29/.local/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1141, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError: 

from user code:
   File "minimal_code.py", line 14, in forward
    x = self.norm(x)

Set torch._dynamo.config.verbose=True for more information

You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
</details>

### Versions

```
PyTorch version: 2.0.0.dev20230129+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-35-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.4.152
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-lightning==1.9.0
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230129+cu117
[pip3] torchaudio==2.0.0.dev20230129+cu117
[pip3] torchmetrics==0.11.0
[pip3] torchvision==0.15.0.dev20230129+cu117
[conda] Could not collect
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
This looks like a problem with the installation that pick old torch version from somewhere, nigthly should have `extract_shape` in _prims.utils. Try uninstalling all pytorch versions, and then install nightly.
