### ISSUE TITLE
minifier_launcher.py silently swallows "ran into runtime exception which is likely an unrelated an issue" warnings

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93354]
### 🐛 Describe the bug

Sometimes, minifier launcher complains that "Input graph did not fail the tester". But in fact, there was just a problem in the minifier infrastructure code itself. However, minifier runs are done in a subprocess, and the stdout/stderr is piped to a file, so you can't see a message like this:

```
(/home/ezyang/local/b/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/b/pytorch (4162c7e9)]$ python /data/users/ezyang/b/pytorch/torch_compile_debug/run_2023_01_30_14_12_59_772449/minifier/minifier_launcher.py
While minifying the program in accuracy minification mode,ran into a runtime exception which is likely an unrelated issue. Skipping this graph
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/debug_utils.py", line 881, in backend_accuracy_fails
    compiled_gm = compiler_fn(copy.deepcopy(gm), clone_inputs(example_inputs))
  File "/home/ezyang/local/b/pytorch-env/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/data/users/ezyang/b/pytorch/torch/fx/graph_module.py", line 708, in __deepcopy__
    fake_mod.__dict__ = copy.deepcopy(self.__dict__, memo)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ezyang/local/b/pytorch-env/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread._local' object
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/torch_compile_debug/run_2023_01_30_14_12_59_772449/minifier/minifier_launcher.py", line 517, in <module>
    minifier(
  File "/data/users/ezyang/b/pytorch/torch/_functorch/fx_minifier.py", line 97, in minifier
    raise RuntimeError("Input graph did not fail the tester")
RuntimeError: Input graph did not fail the tester
```

This is bad and makes it seem like there was something wrong with the minified example, when there actually was something wrong with the minifier.

### Versions

master

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @soumith @ngimel

**Comment by williamwen42** [comment]
Has this been done? We currently output the stdout/stderr from the subprocess created in `after_aot.py`. I don't see subprocesses being created elsewhere for minifier.
