### ISSUE TITLE
Inductor miscompilation with dynamic shapes from LearningToPaint

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93361]
### 🐛 Describe the bug

To run the repro script, you must patch in https://github.com/pytorch/pytorch/pull/93308 because of dynamic shape related problems in minifier infrastructure

The repro script is https://gist.github.com/0054b61f8e9cc5135e6e6d6f5d2caf0d

When run, it fails with

```
[2023-01-31 06:20:26,667] torch._dynamo.utils: [ERROR] Accuracy failed: allclose not within tol=0.001
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/repro.py", line 75, in <module>
    raise AccuracyError("Dynamo failed")
__main__.AccuracyError: Dynamo failed
```

By turning off dynamic shapes by modifying `USE_DYNAMIC_SHAPES`, you can see that inductor compiles without accuracy error. So it should be a dynamic shapes related miscompilation.

The minifier wasn't able to simplify this repro any further, unfortunately. The aot minifier does not work as it has fundamental problems with dynamic shapes.

This miscompilation is minified from LearningToPaint. Repro command is `TORCHDYNAMO_REPRO_AFTER=dynamo TORCHDYNAMO_REPRO_LEVEL=4 python benchmarks/dynamo/torchbench.py --accuracy --backend inductor --explain --only LearningToPaint  --float32  --dynamic-shapes --disable-cudagraphs` but you need at least the patches I quoted above and possibly more to actually get the minifier to work. My full branch state at time of successful minification was https://github.com/ezyang/pytorch/tree/LearningToPaint-successful-minify

**UPDATE.** Updated repro to avoid running backwards

### Versions

master

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by williamwen42** [comment]
Currently getting a different error:
```
Traceback (most recent call last):
  File "/data/users/williamwen/pytorch/benchmarks/dynamo/common.py", line 2245, in check_accuracy
    new_result = optimized_model_iter_fn(model_copy, example_inputs)
  File "/data/users/williamwen/pytorch/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/data/users/williamwen/pytorch/benchmarks/dynamo/common.py", line 1985, in run_n_iterations
    self.model_iter_fn(mod, inputs, collect_outputs=False)
  File "/data/users/williamwen/pytorch/benchmarks/dynamo/torchbench.py", line 535, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "/data/users/williamwen/pytorch/benchmarks/dynamo/torchbench.py", line 536, in resume_in_forward_and_backward_pass
    self.optimizer_zero_grad(mod)
  File "/data/users/williamwen/pytorch/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/data/users/williamwen/pytorch/torch/_dynamo/convert_frame.py", line 722, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/data/users/williamwen/pytorch/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/data/users/williamwen/pytorch/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/williamwen/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/williamwen/pytorch/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/williamwen/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/williamwen/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/data/users/williamwen/pytorch/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/data/users/williamwen/pytorch/torch/_dynamo/symbolic_convert.py", line 2121, in run
    super().run()
  File "/data/users/williamwen/pytorch/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/data/users/williamwen/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/data/users/williamwen/pytorch/torch/_dynamo/symbolic_convert.py", line 465, in wrapper
    return handle_graph_break(self, inst, speculation.reason)
  File "/data/users/williamwen/pytorch/torch/_dynamo/symbolic_convert.py", line 521, in handle_graph_break
    self.output.compile_subgraph(self, reason=reason)
  File "/data/users/williamwen/pytorch/torch/_dynamo/output_graph.py", line 938, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/data/users/williamwen/py310-env/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/williamwen/pytorch/torch/_dynamo/output_graph.py", line 1080, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/users/williamwen/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/williamwen/pytorch/torch/_dynamo/output_graph.py", line 1152, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/data/users/williamwen/pytorch/torch/_dynamo/output_graph.py", line 1133, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/data/users/williamwen/pytorch/torch/_dynamo/repro/after_dynamo.py", line 80, in debug_wrapper
    compiled_gm = compiler_fn(copy.deepcopy(gm), example_inputs)
  File "/data/users/williamwen/pytorch/torch/_dynamo/backends/inductor.py", line 9, in inductor
    return compile_fx(*args, **kwargs)
  File "/data/users/williamwen/pytorch/torch/_inductor/compile_fx.py", line 1168, in compile_fx
    return aot_autograd(
  File "/data/users/williamwen/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/data/users/williamwen/pytorch/torch/_functorch/aot_autograd.py", line 887, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/data/users/williamwen/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/williamwen/pytorch/torch/_functorch/aot_autograd.py", line 600, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/williamwen/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 425, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/williamwen/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 630, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/data/users/williamwen/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 295, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, adjusted_flat_args)
  File "/data/users/williamwen/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/williamwen/pytorch/torch/_inductor/compile_fx.py", line 1100, in fw_compiler_base
    return inner_compile(
  File "/data/users/williamwen/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/data/users/williamwen/pytorch/torch/_inductor/debug.py", line 305, in inner
    return fn(*args, **kwargs)
  File "/data/users/williamwen/py310-env/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/williamwen/pytorch/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/data/users/williamwen/pytorch/torch/_inductor/compile_fx.py", line 550, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/data/users/williamwen/pytorch/torch/_inductor/graph.py", line 1117, in compile_to_fn
    return self.compile_to_module().call
  File "/data/users/williamwen/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/williamwen/pytorch/torch/_inductor/graph.py", line 1067, in compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
  File "/data/users/williamwen/pytorch/torch/_inductor/graph.py", line 1044, in codegen
    self.scheduler.codegen()
  File "/data/users/williamwen/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/williamwen/pytorch/torch/_inductor/scheduler.py", line 2214, in codegen
    self.get_backend(device).codegen_nodes(node.get_nodes())
  File "/data/users/williamwen/pytorch/torch/_inductor/codegen/cuda_combined_scheduling.py", line 63, in codegen_nodes
    return self._triton_scheduling.codegen_nodes(nodes)
  File "/data/users/williamwen/pytorch/torch/_inductor/codegen/triton.py", line 2405, in codegen_nodes
    return self.codegen_node_schedule(node_schedule, numel, rnumel)
  File "/data/users/williamwen/pytorch/torch/_inductor/codegen/triton.py", line 2546, in codegen_node_schedule
    tiled_groups = self.select_tiling(node_schedule, numel, reduction_numel)
  File "/data/users/williamwen/pytorch/torch/_inductor/codegen/triton.py", line 2872, in select_tiling
    if all(
  File "/data/users/williamwen/pytorch/torch/_inductor/codegen/triton.py", line 2873, in <genexpr>
    TritonKernel.is_compatible(new_groups, node.get_ranges())
  File "/data/users/williamwen/pytorch/torch/_inductor/codegen/triton.py", line 1023, in is_compatible
    cls._split_iteration_ranges(groups, lengths)
  File "/data/users/williamwen/pytorch/torch/_inductor/codegen/triton.py", line 991, in _split_iteration_ranges
    if sv.size_hint(size) > sv.size_hint(remaining[current_group]):
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
IndexError: list index out of range
```

**Comment by stevendbrown** [comment]
@williamwen42 I got the exact same error as you did above (i.e. IndexError @ line 991 of `_split_iteration_ranges `). Fortunately, I had an environment on the same machine where `torch.compile` did work, and I found that downgrading `rotary-embedding-torch` from 0.3.6 to 0.3.5 also downgraded a bunch of CUDA-related packages, and after those versions all changed, `torch.compile` on my model succeeded without error. I apologize for this not being better narrowed down.

| PyPi package | v. when failing | v. when working |
|--------|--------|--------|
| nvidia-nccl-cu12 | 2.19.3 | 2.18.1 |
| nvidia-cusparse-cu12 | 12.2.0.103 | 12.1.0.106 |
| nvidia-cufft-cu12 | 11.0.12.1 | 11.0.2.54 |
| nvidia-cuda-runtime-cu12 | 12.3.101 | 12.1.105 |
| nvidia-cuda-cupti-cu12 | 12.3.101 | 12.1.105 | 
| nvidia-cublas-cu12 | 12.3.4.1 | 12.1.3.1 | 
| nvidia-cusolver-cu12 | 11.5.4.101 | 11.4.5.107 | 
| rotary-embedding-torch | 0.3.6 | 0.3.5 |
