### ISSUE TITLE
`torch.rsub` with `alpha=xxx` triggers assertion fail in compile mode

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#93376]
### 🐛 Describe the bug

The following program works fine in eager mode but raises assertion fail in compile mode. According to the error message, passing `alpha=xxx` to `torch.rsub` lead to this issue.

### Error logs

<details><summary>[Click to expand]</summary>

```
==== Eager mode OK! ====
==== torchcomp compilation OK! ====
Traceback (most recent call last):
  File "python3.8/site-packages/torch/_dynamo/output_graph.py", line 692, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "python3.8/site-packages/torch/_dynamo/debug_utils.py", line 1047, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "python3.8/site-packages/torch/__init__.py", line 1323, in __call__
    return self.compile_fn(model_, inputs_)
  File "python3.8/site-packages/torch/_dynamo/optimizations/backends.py", line 24, in inner
    return fn(gm, example_inputs, **kwargs)
  File "python3.8/site-packages/torch/_dynamo/optimizations/backends.py", line 61, in inductor
    return compile_fx(*args, **kwargs)
  File "python3.8/site-packages/torch/_inductor/compile_fx.py", line 413, in compile_fx
    return aot_autograd(
  File "python3.8/site-packages/torch/_dynamo/optimizations/training.py", line 74, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2483, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "python3.8/site-packages/torch/_dynamo/utils.py", line 161, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2180, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1411, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1052, in aot_dispatch_base
    fw_module = make_fx(flat_fn, aot_config.decompositions)(*flat_args)
  File "python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 702, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 440, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "python3.8/site-packages/torch/fx/_symbolic_trace.py", line 778, in trace
    (self.create_arg(fn(*args)),),
  File "python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 456, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2455, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "python3.8/site-packages/torch/fx/interpreter.py", line 136, in run
    self.env[node] = self.run_node(node)
  File "python3.8/site-packages/torch/fx/interpreter.py", line 177, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "python3.8/site-packages/torch/fx/interpreter.py", line 249, in call_function
    return target(*args, **kwargs)
  File "python3.8/site-packages/torch/_inductor/overrides.py", line 38, in __torch_function__
    return func(*args, **kwargs)
  File "python3.8/site-packages/torch/utils/_stats.py", line 15, in wrapper
    return fn(*args, **kwargs)
  File "python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 484, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 509, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 248, in proxy_call
    r = CURRENT_DECOMPOSITION_TABLE[func](*args, **kwargs)
TypeError: rsub() got an unexpected keyword argument 'alpha'

While executing %rsub : [#users=1] = call_function[target=torch.rsub](args = (%input_1, %input_1), kwargs = {alpha: 2})
Original traceback:
  File "repro.py", line 4, in fn
    return torch.rsub(input, input, alpha=2)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "repro.py", line 14, in <module>
    ret_compiled = compiled(x)
  File "python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "python3.8/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "python3.8/site-packages/torch/_dynamo/convert_frame.py", line 403, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "python3.8/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "python3.8/site-packages/torch/_dynamo/convert_frame.py", line 261, in _convert_frame_assert
    return _compile(
  File "python3.8/site-packages/torch/_dynamo/utils.py", line 161, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.8/site-packages/torch/_dynamo/convert_frame.py", line 323, in _compile
    out_code = transform_code_object(code, transform)
  File "python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 339, in transform_code_object
    transformations(instructions, code_options)
  File "python3.8/site-packages/torch/_dynamo/convert_frame.py", line 310, in transform
    tracer.run()
  File "python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1715, in run
    super().run()
  File "python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1781, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "python3.8/site-packages/torch/_dynamo/output_graph.py", line 539, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "python3.8/site-packages/torch/_dynamo/output_graph.py", line 610, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "python3.8/site-packages/torch/_dynamo/utils.py", line 161, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.8/site-packages/torch/_dynamo/output_graph.py", line 697, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised TypeError: rsub() got an unexpected keyword argument 'alpha'

While executing %rsub : [#users=1] = call_function[target=torch.rsub](args = (%input_1, %input_1), kwargs = {alpha: 2})
Original traceback:
  File "repro.py", line 4, in fn
    return torch.rsub(input, input, alpha=2)


Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

</details>

### Minified repro

```python
import torch

def fn(input):
    return torch.rsub(input, input, alpha=2)

x = torch.rand([1])

ret_eager = fn(x)
print('==== Eager mode OK! ====')

compiled = torch.compile(fn)
print('==== torchcomp compilation OK! ====')

ret_compiled = compiled(x)
print('==== torchcomp mode OK! ====')
```

### Versions

<details><summary><b>Environment</b> <i>[Click to expand]</i></summary>

```
PyTorch version: 2.0.0.dev20230130+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-137-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 510.68.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230130+cu117
[pip3] torchaudio==2.0.0.dev20230126+cu117
[pip3] torchvision==0.15.0.dev20230126+cu117
[conda] No relevant packages
```

</details>

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
This one is easy, just need to add alpha support to rsub decomp

**Comment by Ar-Ed** [comment]
I would like to work on this issue as my first issue. 
I have looked at the following lines [`torch/_decomp/decompositions.py`](https://github.com/pytorch/pytorch/blob/master/torch/_decomp/decompositions.py?plain=1#L1026-L1033), but "alpha" parameter is already present.
Could you elaborate on "adding alpha support to rsub decomp", please?

**Comment by ezyang** [comment]
That's puzzling. Maybe it's the one in primtorch? You will need to debug

**Comment by ngimel** [comment]
You need to remove `rsub` decomp in `_inductor/decompositions.py` and instead import those 2 you pointed out.
