### ISSUE TITLE
[tacotron2] One of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#93440]
### 🐛 Describe the bug

Even eager backend fails 

`python benchmarks/dynamo/torchbench.py --training --performance --backend=eager --float32 --only=tacotron2`

### Error logs

~~~
cuda train tacotron2                          ERROR:common:Failed for dynamo one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 80, 857]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Traceback (most recent call last):
  File "/scratch/anijain/work/pytorch/benchmarks/dynamo/common.py", line 1181, in warmup
    fn(model, example_inputs)
  File "/scratch/anijain/work/pytorch/torch/_dynamo/eval_frame.py", line 194, in _fn
    return fn(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/benchmarks/dynamo/torchbench.py", line 348, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "/scratch/anijain/work/pytorch/benchmarks/dynamo/torchbench.py", line 353, in <graph break in forward_and_backward_pass>
    self.grad_scaler.scale(loss).backward()
  File "/scratch/anijain/work/pytorch/torch/_tensor.py", line 473, in backward
    torch.autograd.backward(
  File "/scratch/anijain/work/pytorch/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 80, 857]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
~~~

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
deduped is fixed, so it's back to the old error

```
cuda train tacotron2                           ERROR:common:Failed for dynamo one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 80, 857]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/common.py", line 1350, in warmup
    fn(model, example_inputs)
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/torchbench.py", line 364, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/torchbench.py", line 365, in <graph break in forward_and_backward_pass>
    self.optimizer_zero_grad(mod)
  File "/data/users/ezyang/a/pytorch/benchmarks/dynamo/torchbench.py", line 369, in <graph break in forward_and_backward_pass>
    self.grad_scaler.scale(loss).backward()
  File "/data/users/ezyang/a/pytorch/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/data/users/ezyang/a/pytorch/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 80, 857]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

```
