### ISSUE TITLE
[accuracy] [aot_eager] mobilenet_v2_quantized_qat fails accuracy 

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#93445]

**Comment by penguinwu** [comment]
@bdhirsh (since Animesh is out) Is the issue still valid? If not, please close.

**Comment by ydwu4** [comment]
This seems still an issue. Repro:
```python
python benchmarks/dynamo/torchbench.py --training --accuracy --device cuda --backend=aot_eager --float32 --only=mobilenet_v2_quantized_qat
``` 
Error log:
```
python: can't open file '/home/yidi/local/pytorch/pytorch/benchmarks/dynamo/torchbench.py': [Errno 2] No such file or directory
(pytorch-3.10) ~/local/pytorch$ python benchmarks/dynamo/torchbench.py --training --accuracy --device cuda --backend=aot_eager --float32 --only=mobilenet_v2_quantized_qat
loading model: 0it [00:08, ?it/s]
cuda train mobilenet_v2_quantized_qat         
WARNING:common:fp64 golden ref were not generated for mobilenet_v2_quantized_qat. Setting accuracy check to cosine
ERROR:common:output with shape [1] doesn't match the broadcast shape [32]
Traceback (most recent call last):
  File "/home/yidi/local/pytorch/benchmarks/dynamo/common.py", line 2226, in check_accuracy
    new_result = optimized_model_iter_fn(model_copy, example_inputs)
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/benchmarks/dynamo/common.py", line 1966, in run_n_iterations
    self.model_iter_fn(mod, inputs, collect_outputs=False)
  File "/home/yidi/local/pytorch/benchmarks/dynamo/torchbench.py", line 532, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "/home/yidi/local/pytorch/benchmarks/dynamo/torchbench.py", line 533, in resume_in_forward_and_backward_pass
    self.optimizer_zero_grad(mod)
  File "/home/yidi/local/pytorch/benchmarks/dynamo/torchbench.py", line 533, in resume_in_forward_and_backward_pass
    self.optimizer_zero_grad(mod)
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 5029, in forward
    return compiled_fn(full_args)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 2054, in g
    return f(*args)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 3298, in runtime_wrapper
    original_inpt.copy_(updated_inpt)
RuntimeError: output with shape [1] doesn't match the broadcast shape [32]
TorchDynamo optimized model failed to run because of following error
fail_to_run
```
