### ISSUE TITLE
Error while running pytorch

### ISSUE THREAD

**Issue by mhusseinsh** [pytorch/pytorch#9344]
Hey,
I installed pytorch following the commands given on the website
I tried to run python from the cmd to test with `import torch`
and I received this error

```
 import torch
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
```
- PyTorch
- How installed: pip
- Build command you used (if compiling from source):
- OS: Windows 10
- PyTorch version: torch-0.4.0
- Python version: 3.6.5
- CUDA/cuDNN version: 9.0/7.0.5
- GPU models and configuration: NVIDIA Quadro M2000M
- GCC version (if compiling from source): gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 5.1.0
- CMake version: 3.12.0-rc1
- Versions of any other relevant libraries:

If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by SsnL** [comment]
cc @peterjc123

**Comment by mhusseinsh** [comment]
Hello @peterjc123, @SsnL  ,

I checked your solution [there](https://gist.github.com/peterjc123/6b804651288e76db7b5fabe5348e1f03), and I followed it, and also it didn't make a difference
I uninstalled python 3.6, and installed 3.5, but also the same
Below is my comment and result
-------------------------------------------------------------------------------------------------------------------------------------------

I installed torch on windows, but it seems that there is a problem and it doesn't import

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
```
My Specifications are:

- PyTorch
- How installed: pip
- Build command you used (if compiling from source):
- OS: Windows 10
- PyTorch version: torch-0.4.0
- Python version: 3.6.5
- CUDA/cuDNN version: 9.0/7.0.5
- GPU models and configuration: NVIDIA Quadro M2000M
- GCC version (if compiling from source): gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 5.1.0
- CMake version: 3.12.0-rc1

I tried your solution above:
`pip install mkl mkl-fft intel-openmp numpy` then an installation of VC 2017 Redist then rebooting and also, it didn't change

I checked the variables:
```
C:\Python36\
C:\Python36\Scripts\
C:\Python36\Lib\site-packages
```
So they seem okay too
By running this command ` python -v -c 'import torch' `
this is the result
```
import _frozen_importlib # frozen
import _imp # builtin
import sys # builtin
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\__pycache__\__init__.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\__init__.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\encodings\\__pycache__\\__init__.cpython-36.pyc'
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\codecs.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\codecs.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\codecs.cpython-36.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D8486B9DD8>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\__pycache__\aliases.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\aliases.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\encodings\\__pycache__\\aliases.cpython-36.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A315A20>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D8486B93C8>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\__pycache__\utf_8.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\utf_8.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\encodings\\__pycache__\\utf_8.cpython-36.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A327A90>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\__pycache__\latin_1.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\latin_1.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\encodings\\__pycache__\\latin_1.cpython-36.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A327EF0>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\io.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\io.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\io.cpython-36.pyc'
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\abc.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\abc.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\abc.cpython-36.pyc'
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\_weakrefset.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\_weakrefset.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\_weakrefset.cpython-36.pyc'
import '_weakrefset' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A32EE10>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A32E4A8>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A32E0F0>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\site.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\site.cpython-36.pyc'
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\os.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\os.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\os.cpython-36.pyc'
import 'errno' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\stat.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\stat.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\stat.cpython-36.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A355A58>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\ntpath.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\ntpath.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\ntpath.cpython-36.pyc'
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\genericpath.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\genericpath.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\genericpath.cpython-36.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A361978>
import 'ntpath' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A35A128>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\_collections_abc.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\_collections_abc.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\_collections_abc.cpython-36.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A361F28>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A3439E8>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\_sitebuiltins.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\_sitebuiltins.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\_sitebuiltins.cpython-36.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A343E48>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\sysconfig.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\sysconfig.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\sysconfig.cpython-36.pyc'
import 'sysconfig' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A349470>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\_bootlocale.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\_bootlocale.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\_bootlocale.cpython-36.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A4DF908>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\__pycache__\cp1252.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\cp1252.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\encodings\\__pycache__\\cp1252.cpython-36.pyc'
import 'encodings.cp1252' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A4DFE10>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\types.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\types.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\types.cpython-36.pyc'
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\functools.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\functools.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\functools.cpython-36.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\collections\__pycache__\__init__.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\collections\__init__.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\collections\\__pycache__\\__init__.cpython-36.pyc'
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\operator.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\operator.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\operator.cpython-36.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A6180F0>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\keyword.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\keyword.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\keyword.cpython-36.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A624358>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\heapq.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\heapq.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\heapq.cpython-36.pyc'
import '_heapq' # <class '_frozen_importlib.BuiltinImporter'>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A624B70>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\reprlib.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\reprlib.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\reprlib.cpython-36.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A61DA58>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A5F9828>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\weakref.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\weakref.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\weakref.cpython-36.pyc'
import 'weakref' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A5F9C18>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A4E8FD0>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\collections\__pycache__\abc.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\collections\abc.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\collections\\__pycache__\\abc.cpython-36.pyc'
import 'collections.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A4EEE10>
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A4E82B0>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\__pycache__\__init__.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\__init__.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\importlib\\__pycache__\\__init__.cpython-36.pyc'
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\warnings.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\warnings.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\warnings.cpython-36.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A4EED68>
import 'importlib' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A4E8550>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\__pycache__\util.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\util.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\importlib\\__pycache__\\util.cpython-36.pyc'
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\__pycache__\abc.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\abc.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\importlib\\__pycache__\\abc.cpython-36.pyc'
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\__pycache__\machinery.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\machinery.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\importlib\\__pycache__\\machinery.cpython-36.pyc'
import 'importlib.machinery' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A659588>
import 'importlib.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A664E80>
# C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\__pycache__\contextlib.cpython-36.pyc matches C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\contextlib.py
# code object from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\lib\\__pycache__\\contextlib.cpython-36.pyc'
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A659F98>
import 'importlib.util' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A6649B0>
# possible namespace for C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mpl_toolkits
# possible namespace for C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\google
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D84A33A6A0>
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing builtins
# cleanup[2] removing sys
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _warnings
# cleanup[2] removing _thread
# cleanup[2] removing _weakref
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing nt
# cleanup[2] removing winreg
# cleanup[2] removing zipimport
# cleanup[2] removing encodings
# destroy encodings
# cleanup[2] removing codecs
# cleanup[2] removing _codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing io
# destroy io
# cleanup[2] removing abc
# cleanup[2] removing _weakrefset
# destroy _weakrefset
# cleanup[2] removing site
# destroy site
# cleanup[2] removing os
# cleanup[2] removing errno
# cleanup[2] removing stat
# cleanup[2] removing _stat
# cleanup[2] removing ntpath
# cleanup[2] removing genericpath
# cleanup[2] removing os.path
# cleanup[2] removing _collections_abc
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing sysconfig
# destroy sysconfig
# cleanup[2] removing _bootlocale
# destroy _bootlocale
# cleanup[2] removing _locale
# cleanup[2] removing encodings.cp1252
# cleanup[2] removing types
# cleanup[2] removing functools
# cleanup[2] removing _functools
# cleanup[2] removing collections
# cleanup[2] removing operator
# destroy operator
# cleanup[2] removing _operator
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing heapq
# cleanup[2] removing _heapq
# cleanup[2] removing itertools
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing weakref
# destroy weakref
# cleanup[2] removing collections.abc
# cleanup[2] removing importlib
# destroy importlib
# cleanup[2] removing importlib._bootstrap
# cleanup[2] removing importlib._bootstrap_external
# cleanup[2] removing warnings
# cleanup[2] removing importlib.util
# cleanup[2] removing importlib.abc
# cleanup[2] removing importlib.machinery
# cleanup[2] removing contextlib
# destroy contextlib
# cleanup[2] removing mpl_toolkits
# destroy mpl_toolkits
# cleanup[2] removing google
# destroy google
# destroy zipimport
# destroy _signal
# destroy _sitebuiltins
# destroy errno
# destroy ntpath
# destroy _stat
# destroy genericpath
# destroy stat
# destroy os
# destroy _locale
# destroy _functools
# destroy heapq
# destroy collections.abc
# destroy _operator
# destroy _heapq
# destroy _collections
# destroy collections
# destroy itertools
# destroy importlib.util
# destroy importlib.abc
# destroy functools
# destroy types
# destroy warnings
# destroy importlib.machinery
# destroy abc
# destroy _collections_abc
# cleanup[3] wiping _frozen_importlib
# destroy _frozen_importlib_external
# cleanup[3] wiping _imp
# cleanup[3] wiping _warnings
# cleanup[3] wiping _thread
# cleanup[3] wiping _weakref
# cleanup[3] wiping _io
# cleanup[3] wiping marshal
# cleanup[3] wiping nt
# cleanup[3] wiping winreg
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping encodings.cp1252
# cleanup[3] wiping importlib._bootstrap
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
```
and for running this test code
```
import psutil, os
p = psutil.Process( os.getpid() )
for dll in p.memory_maps():
  print(dll.path)
```
This is the result

```
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\DLLs\_bz2.pyd
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python36.dll
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\DLLs\select.pyd
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\DLLs\_socket.pyd
C:\Program Files\Immidio\Flex Profiles\FlexHook64.dll
C:\Windows\System32\locale.nls
C:\Windows\Globalization\Sorting\SortDefault.nls
C:\Windows\System32\en-US\KernelBase.dll.mui
C:\Windows\SysWOW64\en-US\kernel32.dll.mui
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\DLLs\_lzma.pyd
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\site-packages\psutil\_psutil_windows.cp36-win_amd64.pyd
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\vcruntime140.dll
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python3.dll
C:\Windows\System32\wtsapi32.dll
C:\Windows\System32\ntmarta.dll
C:\Windows\System32\rsaenh.dll
C:\Windows\System32\IPHLPAPI.DLL
C:\Windows\System32\cryptbase.dll
C:\Windows\System32\cryptsp.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\version.dll
C:\Windows\System32\privman64.dll
C:\Windows\System32\userenv.dll
C:\Windows\System32\kernel.appcore.dll
C:\Windows\System32\profapi.dll
C:\Windows\System32\powrprof.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\windows.storage.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\KernelBase.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\bcryptprimitives.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\rpcrt4.dll
C:\Windows\System32\shlwapi.dll
C:\Windows\System32\SHCore.dll
C:\Windows\System32\user32.dll
C:\Windows\System32\kernel32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\psapi.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\ws2_32.dll
C:\Windows\System32\shell32.dll
C:\Windows\System32\advapi32.dll
C:\Windows\System32\gdi32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\imm32.dll
C:\Windows\System32\ntdll.dll
```
I hope this can help by any means in finding a solution for my problem, as it is really urgent for me, that I need to get torch running
Thanks in advance

**Comment by peterjc123** [comment]
@mhusseinsh Well, in your first example, Python is located in `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64`. But in the second step, you checked the python instance in `C:\Python36\`. It seems PyTorch was installed in the first environment, but the PATH for the first python environment is not checked.

**Comment by mhusseinsh** [comment]
@peterjc123 so how to get pytorch installed in the second environment ? and let it read from there
After changing to python 3.5, and reinstalled torch. I got this error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
```
and these are my environments
```
C:\Python35\
C:\Python35\Scripts

```

**Comment by peterjc123** [comment]
@mhusseinsh And also `C:\Python35\Library\bin`.

**Comment by mhusseinsh** [comment]
@peterjc123 wow, now it works 👍  Thanks a lot. I was really stuck in this for so long

**Comment by peterjc123** [comment]
@mhusseinsh Would you please close this issue?
