### ISSUE TITLE
aot_eager/inductor mode bug: Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported.

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#93469]
### 🐛 Describe the bug

Error from [7k github models](https://github.com/pytorch/pytorch/issues/93667)
```
import torch
from torch import nn
import torch._dynamo


class RNN(nn.Module):

    def __init__(self):
        super(RNN, self).__init__()
        self.rnn = nn.RNN(input_size=1, hidden_size=32, num_layers=1, batch_first=True)

    def forward(self, x, h_state):
        r_out, h_state = self.rnn(x, h_state)
        return r_out, h_state

model = RNN().eval()
opt_model = torch._dynamo.optimize("aot_eager")(model)
x = torch.rand([4, 4, 1])
y = torch.rand([1, 4, 32])
print(opt_model(x, y))
```

### Error logs

```
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/output_graph.py", line 584, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/debug_utils.py", line 915, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/optimizations/training.py", line 80, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_functorch/aot_autograd.py", line 2093, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_functorch/aot_autograd.py", line 1792, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_tensor_args, aot_config)
  File "/scratch/ybliang/work/repos/pytorch/torch/_functorch/aot_autograd.py", line 1163, in aot_wrapper_dedupe
    fw_metadata, _out, _num_aliasing_metadata_outs = run_functionalized_fw_and_collect_metadata(
  File "/scratch/ybliang/work/repos/pytorch/torch/_functorch/aot_autograd.py", line 272, in inner
    outs = f(*f_args)
  File "/scratch/ybliang/work/repos/pytorch/torch/_functorch/aot_autograd.py", line 2065, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/scratch/ybliang/work/repos/pytorch/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/fx/interpreter.py", line 288, in call_module
    return submod(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/modules/rnn.py", line 477, in forward
    result = _VF.rnn_tanh(input, hx, self._flat_weights, self.bias, self.num_layers,
  File "/scratch/ybliang/work/repos/pytorch/torch/_subclasses/fake_tensor.py", line 760, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.t.default(*(Parameter containing:
tensor([[ 0.0033],
        [ 0.1516],
        [-0.0189],
        [ 0.0530],
        [-0.0756],
        [-0.0354],
        [-0.1211],
        [-0.0938],
        [ 0.0920],
        [ 0.0642],
        [ 0.1412],
        [ 0.0875],
        [ 0.0273],
        [ 0.0895],
        [-0.1393],
        [ 0.0752],
        [-0.0468],
        [-0.0664],
        [-0.0158],
        [-0.0613],
        [ 0.0560],
        [ 0.1625],
        [-0.0567],
        [-0.1457],
        [ 0.1524],
        [-0.1761],
        [-0.1574],
        [-0.0703],
        [-0.1703],
        [-0.1648],
        [-0.1290],
        [ 0.0621]], requires_grad=True),), **{})

While executing %self_rnn : [#users=2] = call_module[target=self_rnn](args = (%x, %h_state), kwargs = {})
Original traceback:
Module stack: {'self_rnn': <class 'torch.nn.modules.rnn.RNN'>}
  File "/scratch/ybliang/work/repos/pytorch/debug/debug1.py", line 18, in forward
    r_out, h_state = self.rnn(x, h_state)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/debug/debug1.py", line 26, in <module>
    print(opt_model(x, y))
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 80, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 329, in catch_errors
    return callback(frame, cache_size)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 468, in _convert_frame
    result = inner_convert(frame, cache_size)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 102, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 90, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 395, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 382, in transform
    tracer.run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1621, in run
    super().run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 485, in run
    and self.step()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 454, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1683, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/output_graph.py", line 463, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/output_graph.py", line 510, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/output_graph.py", line 589, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: compiler_fn raised Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.t.default(*(Parameter containing:
tensor([[ 0.0033],
        [ 0.1516],
        [-0.0189],
        [ 0.0530],
        [-0.0756],
        [-0.0354],
        [-0.1211],
        [-0.0938],
        [ 0.0920],
        [ 0.0642],
        [ 0.1412],
        [ 0.0875],
        [ 0.0273],
        [ 0.0895],
        [-0.1393],
        [ 0.0752],
        [-0.0468],
        [-0.0664],
        [-0.0158],
        [-0.0613],
        [ 0.0560],
        [ 0.1625],
        [-0.0567],
        [-0.1457],
        [ 0.1524],
        [-0.1761],
        [-0.1574],
        [-0.0703],
        [-0.1703],
        [-0.1648],
        [-0.1290],
        [ 0.0621]], requires_grad=True),), **{})

While executing %self_rnn : [#users=2] = call_module[target=self_rnn](args = (%x, %h_state), kwargs = {})
Original traceback:
Module stack: {'self_rnn': <class 'torch.nn.modules.rnn.RNN'>}
  File "/scratch/ybliang/work/repos/pytorch/debug/debug1.py", line 18, in forward
    r_out, h_state = self.rnn(x, h_state)


Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

**Comment by ezyang** [comment]
passes now
