### ISSUE TITLE
test_copy_broadcast

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#93476]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_torch.py -k test_copy_broadcast
```
```
FAIL: test_copy_broadcast (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/binbao/work/pytorch/test/test_torch.py", line 7650, in test_copy_broadcast
    self.assertRaises(RuntimeError, lambda: torch.zeros(5, 6).copy_(torch.zeros(30)))
  File "/scratch/binbao/work/pytorch/torch/testing/_internal/common_utils.py", line 2927, in assertRaises
    return super().assertRaises(expected_exception, *args, **kwargs)
AssertionError: RuntimeError not raised by <lambda>
```

Note: there are two tests with this name, we can rename it.

**Comment by eellison** [comment]
fixed
