### ISSUE TITLE
Get the error: AttributeError: Can't pickle local object 'convert_frame.<locals>._convert_frame'

### ISSUE THREAD

**Issue by fladventurerob** [pytorch/pytorch#93470]
### 🐛 Describe the bug

When adding the line:
`model = torch.compile(model)` after loading the model, this error occurs. When removing the line, the script functions as intended. 

### Error logs

  File "/opt/anaconda3/envs/ml1/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/anaconda3/envs/ml1/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/anaconda3/envs/ml1/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/anaconda3/envs/ml1/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/anaconda3/envs/ml1/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/anaconda3/envs/ml1/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/anaconda3/envs/ml1/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'convert_frame.<locals>._convert_frame'

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ConnorBaker** [comment]
For what it's worth, I'm using `triton` at `HEAD` and this isn't an issue I run into any more (I no longer need to specify `compile_threads=1`) when I built today.

I haven't followed the changes made very closely recently, but I did see this merged today (though perhaps unrelated): https://github.com/openai/triton/pull/1133.

**Comment by VasLem** [comment]
I would not close this issue. It randomly appears when you are going to torch save a model that needs a lot of time to be trained, which means that nothing is saved. Could you update then __getstate__ of that model internally, so that any multithreading related pickling issues won't occur? I find this to be a bug of torch.compile()

**Comment by jansel** [comment]
I believe this one will be fixed by https://github.com/pytorch/pytorch/pull/101651 when it lands

**Comment by kxzxvbk** [comment]
I met the same bug, here is the simplest test case I can offer: 
```
import torch
from torch import nn


class CNNModel(nn.Module):

    def __init__(
        self,
        class_number=10,
        input_channel=3,
        dropout=0.1,
        kernel_sizes=[5, 3, 3],
        paddings=[2, 1, 1],
        hidden_dims=[32, 32, 32]
    ):
        super(CNNModel, self).__init__()

        self.layers = []
        self.layers.append(nn.Conv2d(input_channel, hidden_dims[0], kernel_size=kernel_sizes[0], padding=paddings[0]))
        self.layers.append(nn.ReLU())
        for i in range(len(hidden_dims) - 1):
            self.layers.append(
                nn.Conv2d(hidden_dims[i], hidden_dims[i + 1], kernel_size=kernel_sizes[i + 1], padding=paddings[i + 1])
            )
            self.layers.append(nn.ReLU())
        self.layers.append(nn.Dropout(p=dropout))
        self.layers = nn.Sequential(*self.layers)

        self.glp = nn.AdaptiveAvgPool2d((1, 1))

        self.fc = nn.Sequential(nn.Flatten(), nn.Linear(hidden_dims[-1], class_number))

    def forward(self, x):
        x = self.layers(x)
        x = self.glp(x)
        x = self.fc(x)
        return x


if __name__ == '__main__':
    import pickle
    model = CNNModel()
    from torch._inductor import config
    config.compile_threads = 1
    model = torch.compile(model)
    pickle.dumps(model)
```
The error is: 
```
Traceback (most recent call last):
  File "test", line 46, in <module>
    pickle.dumps(model)
AttributeError: Can't pickle local object 'convert_frame.<locals>._convert_frame'
```
Maybe this information helps :)

**Comment by Parskatt** [comment]
I'm having a similar issue, but with dataloaders with num_workers > 0.

**Comment by Parskatt** [comment]
https://github.com/pytorch/pytorch/issues/101107 seems relevant.

**Comment by sascharo** [comment]
`config.compile_threads = 1` doesn't fix the error for me with 2.1.1.

**Comment by antoinebrl** [comment]
Hello! I encounter this issue while compiling a transformation used within the multi-processing context of the data loader.

Even though I intend for the transformation to run on the CPU, the [GPU is detected](https://github.com/pytorch/pytorch/blob/79ee99e6d2454612cd8c3fc93f468a8830bbb8fc/torch/_dynamo/convert_frame.py#L145) leading to the following error: 
```
RuntimeError: Cannot re-initialize CUDA in forked subprocess. 
    To use CUDA with multiprocessing, you must use the 'spawn' start method
```
Despite attempting to investigate the issue by commenting out calls to `torch.cuda.get_rng_state()` and `torch.cuda.set_rng_state()` in `torch/_dynamo/convert_frame.py::wrap_convert_context` and `torch/_dynamo/utils.py::preserve_rng_state`, the problem persists. I suspect that these two functions are called elsewhere (possibly in the `_inductor` or the compiled code itself). I'm happy to turn this into a dedicated issue.

In an effort to resolve this error, I followed the recommendation and utilized spawn as the multiprocessing context for the `DataLoader`. However, this led to the error mentioned in this issue:
```
AttributeError: Can't pickle local object 'convert_frame.<locals>._convert_frame'
```

While preparing a pull request, I attempted to move the definition of `_convert_frame()` outside of `convert_frame()`. This introduced a new challenge because [two attributes are added to the function](https://github.com/pytorch/pytorch/blob/79ee99e6d2454612cd8c3fc93f468a8830bbb8fc/torch/_dynamo/convert_frame.py#L760C4-L760C4) which change the object and breaks the serialization:
```
_pickle.PicklingError: Can't pickle <function _convert_frame at 0x7f64e40a5ea0>:
    it's not the same object as torch._dynamo.convert_frame._convert_frame
```

**Comment by jansel** [comment]
@anijain2305 to provide update

**Comment by anthai0908** [comment]
(.venv) (.venv) (base) anthai@Ans-Laptop pytorch-ssd % python3 /Users/anthai/42028_Assignment_3/mobilenet_ssd/jetson-inference/python/training/detection/ssd/pytorch-ssd/train_ssd.py --data='/Users/anthai/42028_Assignment_3/job_896071_annotations_2024_05_25_02_20_15_pascal voc 1.1' --model-dir=/Users/anthai/42028_Assignment_3/mobilenet_ssd/jetson-inference/python/training/detection/ssd/pytorch-ssd/models/ --batch-size=4 --epochs=30 --dataset-type=voc --net='mb2-ssd-lite' --pretrained-ssd='models/mb2-ssd-lite-mp-0_686.pth'
2024-05-25 16:33:21 - Namespace(dataset_type='voc', datasets=['/Users/anthai/42028_Assignment_3/job_896071_annotations_2024_05_25_02_20_15_pascal voc 1.1'], balance_data=False, net='mb2-ssd-lite', resolution=300, freeze_base_net=False, freeze_net=False, mb2_width_mult=1.0, base_net=None, pretrained_ssd='models/mb2-ssd-lite-mp-0_686.pth', resume=None, lr=0.01, momentum=0.9, weight_decay=0.0005, gamma=0.1, base_net_lr=0.001, extra_layers_lr=None, scheduler='cosine', milestones='80,100', t_max=100, batch_size=4, num_epochs=30, num_workers=2, validation_epochs=1, validation_mean_ap=False, debug_steps=10, use_cuda=True, checkpoint_folder='/Users/anthai/42028_Assignment_3/mobilenet_ssd/jetson-inference/python/training/detection/ssd/pytorch-ssd/models/', log_level='info')
2024-05-25 16:33:21 - Prepare training datasets.
warning - could not find image d93582ae-a472-4905-aabc-be04ddb0e066 - ignoring from dataset
2024-05-25 16:33:21 - VOC Labels read from file:  ('BACKGROUND', 's50', 's100', 'park', 'stop', 'traffic')
2024-05-25 16:33:21 - Stored labels into file /Users/anthai/42028_Assignment_3/mobilenet_ssd/jetson-inference/python/training/detection/ssd/pytorch-ssd/models/labels.txt.
2024-05-25 16:33:21 - Train dataset size: 168
2024-05-25 16:33:21 - Prepare Validation datasets.
2024-05-25 16:33:21 - VOC Labels read from file:  ('BACKGROUND', 's50', 's100', 'park', 'stop', 'traffic')
2024-05-25 16:33:21 - Validation dataset size: 29
2024-05-25 16:33:21 - Build network.
2024-05-25 16:33:21 - Init from pretrained SSD models/mb2-ssd-lite-mp-0_686.pth
2024-05-25 16:33:21 - Took 0.02 seconds to load the model.
2024-05-25 16:33:21 - Learning rate: 0.01, Base net learning rate: 0.001, Extra Layers learning rate: 0.01.
2024-05-25 16:33:21 - Uses CosineAnnealingLR scheduler.
2024-05-25 16:33:21 - Start training from epoch 0.
Traceback (most recent call last):
  File "/Users/anthai/42028_Assignment_3/mobilenet_ssd/jetson-inference/python/training/detection/ssd/pytorch-ssd/train_ssd.py", line 406, in <module>
    train(train_loader, net, criterion, optimizer, device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
  File "/Users/anthai/42028_Assignment_3/mobilenet_ssd/jetson-inference/python/training/detection/ssd/pytorch-ssd/train_ssd.py", line 139, in train
    for i, data in enumerate(loader):
                   ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 439, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1040, in __init__
    w.start()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TrainAugmentation.__init__.<locals>.<lambda>'. Hi I got this error, and i actually don't know how to fix.

**Comment by ringohoffman** [comment]
@anthai0908 https://github.com/qfgaohao/pytorch-ssd/issues/71 seems more relevant to you. I think your comment is really long and unrelated. It might be nice to remove it as to not clutter this issue.

**Comment by anthai0908** [comment]
thanks @ringohoffman. After training and exporting to onnx, I have one question, is it possible to deploy inferenceon python 3.6.9 with onnx format?

**Comment by masnesral** [comment]
Update from triage meeting: @williamwen42 thought this _might_ have been fixed in another PR??

**Comment by StrongerXi** [comment]
Can't repro what @kxzxvbk provided above, on 9c2c61d2dd.

**Comment by anijain2305** [comment]
I am unable to repro the issue here. I will keep the issue open for a month in case someone comes up with a better repro.

**Comment by jansel** [comment]
My agent was unable to reproduce this on b5f741719293dba49b11165b595d964febaa9ba9. Reopen if you see this on the latest PyTorch nightly
