### ISSUE TITLE
[inductor] Missing Impl - `as_strided` - might help `hf_Longformer`

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#93525]
Repro 
~~~

import torch
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

# torch version: 1.14.0a0+git65b4080
# torch cuda version: 11.6
# torch git version: 65b408074f4ecc99faf5720ea5b3570a483ec9f4


# CUDA Info: 
# nvcc: NVIDIA (R) Cuda compiler driver 
# Copyright (c) 2005-2022 NVIDIA Corporation 
# Built on Thu_Feb_10_18:23:41_PST_2022 
# Cuda compilation tools, release 11.6, V11.6.112 
# Build cuda_11.6.r11.6/compiler.30978841_0 

# GPU Hardware Info: 
# NVIDIA A100-SXM4-40GB : 8 


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()

    
    
    def forward(self, view_132):
        as_strided_17 = torch.ops.aten.as_strided.default(view_132, [24, 3, 512, 64], [64, 393216, 1536, 1]);  view_132 = None
        return (as_strided_17,)
        
args = [((24, 2, 512, 64), (64, 786432, 1536, 1), torch.float32, 'cuda')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
mod = make_fx(Repro().to(device="cuda"))(*args)

from torchinductor.compile_fx import compile_fx_inner
from torchdynamo.debug_utils import same_two_models

compiled = compile_fx_inner(mod, args)
compiled(*args)
~~~

~~~
NotImplementedError: unrealized as_strided(TensorBox(StorageBox(
  InputBuffer(name='arg0_1', layout=FixedLayout('cuda', torch.float32, size=[s0, s1, s2, s3], stride=[s3, s0*s2*s3, s0*s3, 1]))
)), ...)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/anijain/work/torchdynamo/repro.py", line 44, in <module>
    compiled = compile_fx_inner(mod, args)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/debug_utils.py", line 445, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/scratch/anijain/work/torchdynamo/torchinductor/debug.py", line 180, in inner
    return fn(*args, **kwargs)
  File "/scratch/anijain/work/env/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/scratch/anijain/work/torchdynamo/torchinductor/compile_fx.py", line 102, in compile_fx_inner
    graph.run(*example_inputs)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/anijain/work/torchdynamo/torchinductor/graph.py", line 146, in run
    return super().run(*args)
  File "/scratch/anijain/work/pytorch/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/scratch/anijain/work/torchdynamo/torchinductor/graph.py", line 314, in run_node
    result = super().run_node(n)
  File "/scratch/anijain/work/pytorch/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/anijain/work/torchdynamo/torchinductor/graph.py", line 259, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torchinductor.exc.LoweringException: NotImplementedError: unrealized as_strided(TensorBox(StorageBox(
  InputBuffer(name='arg0_1', layout=FixedLayout('cuda', torch.float32, size=[s0, s1, s2, s3], stride=[s3, s0*s2*s3, s0*s3, 1]))
)), ...)
  target: aten.as_strided.default
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='arg0_1', layout=FixedLayout('cuda', torch.float32, size=[s0, s1, s2, s3], stride=[s3, s0*s2*s3, s0*s3, 1]))
  ))
  args[1]: [24, 3, 512, 64]
  args[2]: [64, 393216, 1536, 1]

While executing %as_strided : [#users=1] = call_function[target=torch.ops.aten.as_strided.default](args = (%arg0_1, [24, 3, 512, 64], [64, 393216, 1536, 1]), kwargs = {})
Original traceback:
None
~~~

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @desertfire @SherlockNoMad

**Comment by ezyang** [comment]
repro passes now

```
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/a/pytorch (f987a3be)]$ python a.py
input tensor([[ 0.,  4.,  8., 12., 16., 20.],
        [ 1.,  5.,  9., 13., 17., 21.],
        [ 2.,  6., 10., 14., 18., 22.],
        [ 3.,  7., 11., 15., 19., 23.]])
ref tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
/data/users/ezyang/a/pytorch/torch/_inductor/compile_fx.py:90: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
res tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
```
