### ISSUE TITLE
torch.cuda.nvtx.* causes: `AssertionError: torch.* op returned non-Tensor _GeneratorContextManager call_function`

### ISSUE THREAD

**Issue by danthe3rd** [pytorch/pytorch#93526]
Hello,

Traced functions can't contain calls to `torch.cuda.nvtx` for profiling, as this breaks the compilation with the following error:

```
torchdynamo.convert_frame: [ERROR] [2022-10-10 16:24:15,919] WON'T CONVERT simple_op test_ti.py line 47 
due to: 
Traceback (most recent call last):
  File "/scratch/XXXX/xformers-py38-pytorch113-cu116/lib/python3.8/site-packages/torchdynamo/variables/tensor.py", line 283, in create
    assert (
AssertionError: torch.* op returned non-Tensor _GeneratorContextManager call_function <function range at 0x7ff151029820>

from user code:
   File "test_ti.py", line 48, in simple_op
    with torch.cuda.nvtx.range("model"):

Set torchdynamo.config.verbose=True for more information
==========
```

Here is a minimal example to reproduce:
```python
import torchvision
import torch
import torchdynamo

dtype = torch.float16
model = torchvision.models.resnet50()
model.to(dtype)
model.cuda()
model.eval()

example_inputs = torch.randn((32,3,224,224), device="cuda", dtype=dtype)

def simple_op():
    with torch.cuda.nvtx.range("model"):  # <-- This causes the BUG
        return model(example_inputs)

@torchdynamo.optimize("inductor")
def run_once_dynamo_ind():
    return simple_op()

run_once_dynamo_ind()
```

I believe the fix would be just to add another exception to [the list](https://github.com/pytorch/torchdynamo/blob/6c2f81ec47d6acff464a883c207e7d94884435d4/torchdynamo/variables/torch.py#L230-L234).

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
this passes now

```
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/a/pytorch (f987a3be)]$ cat > a.py
import torchvision
import torch
import torchdynamo

dtype = torch.float16
model = torchvision.models.resnet50()
model.to(dtype)
model.cuda()
model.eval()

example_inputs = torch.randn((32,3,224,224), device="cuda", dtype=dtype)

def simple_op():
    with torch.cuda.nvtx.range("model"):  # <-- This causes the BUG
        return model(example_inputs)

@torchdynamo.optimize("inductor")
def run_once_dynamo_ind():
    return simple_op()

run_once_dynamo_ind()
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/a/pytorch (f987a3be)]$ vim a.py
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/a/pytorch (f987a3be)]$ python a.py
/data/users/ezyang/a/pytorch/torch/_inductor/compile_fx.py:90: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(

```
