### ISSUE TITLE
[opbench] NameError: name 'tensor' is not defined

### ISSUE THREAD

**Issue by Krovatkin** [pytorch/pytorch#93535]
Opbench doesn't seem to handle inputs with lists correctly.

Command to reproduce 

```
python operatorbench.py --op=aten.cat.default --dtype=float16
```

Stacktrace
```
Traceback (most recent call last):
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/torch/fx/graph_module.py", line 269, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.0", line 5, in forward
    cat_default = torch.ops.aten.cat.default([tensor([[[[-7.1172, -0.0527,  4.3867,  ..., -3.2422, -2.5586,  2.8047],
NameError: name 'tensor' is not defined

Call using an FX-traced Module, line 5 of the traced Module's generated forward function:
def forward(self):
    cat_default = torch.ops.aten.cat.default([tensor([[[[-7.1172, -0.0527,  4.3867,  ..., -3.2422, -2.5586,  2.8047],

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
              [ 1.7490,  3.8242,  1.8721,  ..., -5.0781, -7.3281,  4.6953],

              [ 1.3975, -2.2070,  3.8047,  ...,  5.4141,  8.4844,  3.2266],

error aten.cat.default
name 'tensor' is not defined
Traceback (most recent call last):
  File "/home/villedepommes/github/torchdynamo2/benchmarks/microbenchmarks/operatorbench.py", line 281, in <module>
    benchmark()
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/villedepommes/github/torchdynamo2/benchmarks/microbenchmarks/operatorbench.py", line 262, in benchmark
    raise e
  File "/home/villedepommes/github/torchdynamo2/benchmarks/microbenchmarks/operatorbench.py", line 247, in benchmark
    microbenchmark(
  File "/home/villedepommes/github/torchdynamo2/benchmarks/microbenchmarks/operatorbench.py", line 78, in microbenchmark
    cudagraphs_eager = cudagraphs_inner(gm, gm_args, copy_outputs=False)
  File "/home/villedepommes/github/torchdynamo2/torchdynamo/optimizations/backends.py", line 526, in cudagraphs_inner
    model(*inputs)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/torch/fx/graph_module.py", line 660, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/home/villedepommes/miniconda3/envs/torchdynamo2/lib/python3.10/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e.with_traceback(None)
NameError: name 'tensor' is not defined

```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by ESI-SYD** [comment]
Observed same error message after https://github.com/pytorch/pytorch/commit/da7ca82121bff9acc4087f86d3dc22bdbc620d11
```bash
python benchmarks/dynamo/microbenchmarks/operatorbench.py --op=aten.cat.default --dtype=float32 --device cpu
```

**Comment by Valentine233** [comment]
The issue also exists in CUDA. @eellison @desertfire Do you have any idea about this?
