### ISSUE TITLE
 Failed building wheel for triton

### ISSUE THREAD

**Issue by Shiro-LK** [pytorch/pytorch#93544]
I tried to install triton as indicated in this repo but got this error. I was wondering if some dependencies are needed?

```
pip install -U "git+https://github.com/openai/triton@af76c989eb4799b015f8b288ccd8421558772e56#subdirectory=python"
Collecting git+https://github.com/openai/triton@af76c989eb4799b015f8b288ccd8421558772e56#subdirectory=python
  Cloning https://github.com/openai/triton (to revision af76c989eb4799b015f8b288ccd8421558772e56) to /tmp/pip-req-build-im8_rrz4
  Running command git clone --filter=blob:none --quiet https://github.com/openai/triton /tmp/pip-req-build-im8_rrz4
  Running command git rev-parse -q --verify 'sha^af76c989eb4799b015f8b288ccd8421558772e56'
  Running command git fetch -q https://github.com/openai/triton af76c989eb4799b015f8b288ccd8421558772e56
  Running command git checkout -q af76c989eb4799b015f8b288ccd8421558772e56
  Resolved https://github.com/openai/triton to commit af76c989eb4799b015f8b288ccd8421558772e56
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cmake in /home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages (from triton==2.0.0) (3.24.1.1)
Requirement already satisfied: filelock in /home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages (from triton==2.0.0) (3.8.0)
Requirement already satisfied: torch in /home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages (from triton==2.0.0) (1.14.0.dev20221014+cu117)
Requirement already satisfied: typing-extensions in /home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages (from torch->triton==2.0.0) (4.4.0)
Requirement already satisfied: sympy in /home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages (from torch->triton==2.0.0) (1.10.1)
Requirement already satisfied: networkx in /home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages (from torch->triton==2.0.0) (2.6.3)
Requirement already satisfied: mpmath>=0.19 in /home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages (from sympy->torch->triton==2.0.0) (1.2.1)
Building wheels for collected packages: triton
  Building wheel for triton (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [160 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/triton
      copying triton/compiler.py -> build/lib.linux-x86_64-cpython-37/triton
      copying triton/testing.py -> build/lib.linux-x86_64-cpython-37/triton
      copying triton/utils.py -> build/lib.linux-x86_64-cpython-37/triton
      copying triton/__init__.py -> build/lib.linux-x86_64-cpython-37/triton
      creating build/lib.linux-x86_64-cpython-37/triton/language
      copying triton/language/random.py -> build/lib.linux-x86_64-cpython-37/triton/language
      copying triton/language/__init__.py -> build/lib.linux-x86_64-cpython-37/triton/language
      copying triton/language/core.py -> build/lib.linux-x86_64-cpython-37/triton/language
      copying triton/language/libdevice.py -> build/lib.linux-x86_64-cpython-37/triton/language
      copying triton/language/extern.py -> build/lib.linux-x86_64-cpython-37/triton/language
      copying triton/language/semantic.py -> build/lib.linux-x86_64-cpython-37/triton/language
      creating build/lib.linux-x86_64-cpython-37/triton/runtime
      copying triton/runtime/jit.py -> build/lib.linux-x86_64-cpython-37/triton/runtime
      copying triton/runtime/__init__.py -> build/lib.linux-x86_64-cpython-37/triton/runtime
      copying triton/runtime/autotuner.py -> build/lib.linux-x86_64-cpython-37/triton/runtime
      creating build/lib.linux-x86_64-cpython-37/triton/tools
      copying triton/tools/compare_asm.py -> build/lib.linux-x86_64-cpython-37/triton/tools
      copying triton/tools/__init__.py -> build/lib.linux-x86_64-cpython-37/triton/tools
      copying triton/tools/disasm.py -> build/lib.linux-x86_64-cpython-37/triton/tools
      copying triton/tools/build_extern.py -> build/lib.linux-x86_64-cpython-37/triton/tools
      creating build/lib.linux-x86_64-cpython-37/triton/ops
      copying triton/ops/matmul.py -> build/lib.linux-x86_64-cpython-37/triton/ops
      copying triton/ops/__init__.py -> build/lib.linux-x86_64-cpython-37/triton/ops
      copying triton/ops/matmul_perf_model.py -> build/lib.linux-x86_64-cpython-37/triton/ops
      copying triton/ops/cross_entropy.py -> build/lib.linux-x86_64-cpython-37/triton/ops
      creating build/lib.linux-x86_64-cpython-37/triton/ops/blocksparse
      copying triton/ops/blocksparse/matmul.py -> build/lib.linux-x86_64-cpython-37/triton/ops/blocksparse
      copying triton/ops/blocksparse/softmax.py -> build/lib.linux-x86_64-cpython-37/triton/ops/blocksparse
      copying triton/ops/blocksparse/__init__.py -> build/lib.linux-x86_64-cpython-37/triton/ops/blocksparse
      running egg_info
      creating triton.egg-info
      writing triton.egg-info/PKG-INFO
      writing dependency_links to triton.egg-info/dependency_links.txt
      writing requirements to triton.egg-info/requires.txt
      writing top-level names to triton.egg-info/top_level.txt
      writing manifest file 'triton.egg-info/SOURCES.txt'
      reading manifest file 'triton.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'triton.egg-info/SOURCES.txt'
      copying triton/language/libdevice.10.bc -> build/lib.linux-x86_64-cpython-37/triton/language
      running build_ext
      -- The C compiler identification is GNU 7.5.0
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Adding Python module
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-req-build-im8_rrz4/python/build/temp.linux-x86_64-cpython-37
      [  2%] Building CXX object CMakeFiles/triton.dir/lib/codegen/analysis/align.cc.o
      [  5%] Building CXX object CMakeFiles/triton.dir/lib/codegen/analysis/allocation.cc.o
      [  7%] Building CXX object CMakeFiles/triton.dir/lib/codegen/analysis/axes.cc.o
      [ 12%] Building CXX object CMakeFiles/triton.dir/lib/codegen/analysis/liveness.cc.o
      [ 12%] Building CXX object CMakeFiles/triton.dir/lib/codegen/analysis/layout.cc.o
      [ 15%] Building CXX object CMakeFiles/triton.dir/lib/codegen/analysis/swizzle.cc.o
      [ 17%] Building CXX object CMakeFiles/triton.dir/lib/codegen/extern_lib.cc.o
      [ 20%] Building CXX object CMakeFiles/triton.dir/lib/codegen/pass.cc.o
      [ 23%] Building CXX object CMakeFiles/triton.dir/lib/codegen/selection/generator.cc.o
      [ 25%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/coalesce.cc.o
      [ 28%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/cts.cc.o
      [ 30%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/inline.cc.o
      [ 33%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/disassociate.cc.o
      [ 35%] Building CXX object CMakeFiles/triton.dir/lib/codegen/target.cc.o
      [ 38%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/membar.cc.o
      [ 41%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/dce.cc.o
      [ 43%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/peephole.cc.o
      [ 46%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/pipeline.cc.o
      [ 48%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/prefetch.cc.o
      [ 51%] Building CXX object CMakeFiles/triton.dir/lib/codegen/transform/reorder.cc.o
      [ 53%] Building CXX object CMakeFiles/triton.dir/lib/driver/dispatch.cc.o
      [ 56%] Building CXX object CMakeFiles/triton.dir/lib/driver/error.cc.o
      [ 58%] Building CXX object CMakeFiles/triton.dir/lib/driver/llvm.cc.o
      [ 61%] Building CXX object CMakeFiles/triton.dir/lib/ir/basic_block.cc.o
      [ 64%] Building CXX object CMakeFiles/triton.dir/lib/ir/builder.cc.o
      [ 66%] Building CXX object CMakeFiles/triton.dir/lib/ir/constant.cc.o
      [ 69%] Building CXX object CMakeFiles/triton.dir/lib/ir/context.cc.o
      [ 71%] Building CXX object CMakeFiles/triton.dir/lib/ir/function.cc.o
      [ 74%] Building CXX object CMakeFiles/triton.dir/lib/ir/instructions.cc.o
      [ 76%] Building CXX object CMakeFiles/triton.dir/lib/ir/metadata.cc.o
      [ 79%] Building CXX object CMakeFiles/triton.dir/lib/ir/module.cc.o
      [ 82%] Building CXX object CMakeFiles/triton.dir/lib/ir/print.cc.o
      [ 84%] Building CXX object CMakeFiles/triton.dir/lib/ir/type.cc.o
      [ 87%] Building CXX object CMakeFiles/triton.dir/lib/ir/utils.cc.o
      [ 89%] Building CXX object CMakeFiles/triton.dir/lib/ir/value.cc.o
      [ 92%] Building CXX object CMakeFiles/triton.dir/python/src/main.cc.o
      [ 94%] Building CXX object CMakeFiles/triton.dir/python/src/triton.cc.o
      [ 97%] Building CXX object CMakeFiles/triton.dir/python/src/superblock.cc.o
      /tmp/pip-req-build-im8_rrz4/lib/driver/llvm.cc: In function ‘std::__cxx11::string triton::driver::ptx_to_cubin(const string&, const string&, int)’:
      /tmp/pip-req-build-im8_rrz4/lib/driver/llvm.cc:222:14: warning: ignoring return value of ‘char* tmpnam(char*)’, declared with attribute warn_unused_result [-Wunused-result]
         std::tmpnam(_fsrc);
         ~~~~~~~~~~~^~~~~~~
      /tmp/pip-req-build-im8_rrz4/lib/driver/llvm.cc:223:14: warning: ignoring return value of ‘char* tmpnam(char*)’, declared with attribute warn_unused_result [-Wunused-result]
         std::tmpnam(_flog);
         ~~~~~~~~~~~^~~~~~~
      [100%] Linking CXX shared library /tmp/pip-req-build-im8_rrz4/python/build/lib.linux-x86_64-cpython-37/triton/_C/libtriton.so
      /usr/bin/ld: cannot find -lz
      /usr/bin/ld: cannot find -lz
      collect2: error: ld returned 1 exit status
      CMakeFiles/triton.dir/build.make:688: recipe for target '/tmp/pip-req-build-im8_rrz4/python/build/lib.linux-x86_64-cpython-37/triton/_C/libtriton.so' failed
      make[2]: *** [/tmp/pip-req-build-im8_rrz4/python/build/lib.linux-x86_64-cpython-37/triton/_C/libtriton.so] Error 1
      CMakeFiles/Makefile2:838: recipe for target 'CMakeFiles/triton.dir/all' failed
      make[1]: *** [CMakeFiles/triton.dir/all] Error 2
      Makefile:100: recipe for target 'all' failed
      make: *** [all] Error 2
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-im8_rrz4/python/setup.py", line 195, in <module>
          "tabulate",
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-im8_rrz4/python/setup.py", line 113, in run
          self.build_extension(ext)
        File "/tmp/pip-req-build-im8_rrz4/python/setup.py", line 148, in build_extension
          subprocess.check_call(["cmake", "--build", "."] + build_args, cwd=self.build_temp)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j16']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for triton
  Running setup.py clean for triton
Failed to build triton
Installing collected packages: triton
  Running setup.py install for triton ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for triton did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running install
      /home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      running egg_info
      writing triton.egg-info/PKG-INFO
      writing dependency_links to triton.egg-info/dependency_links.txt
      writing requirements to triton.egg-info/requires.txt
      writing top-level names to triton.egg-info/top_level.txt
      reading manifest file 'triton.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'triton.egg-info/SOURCES.txt'
      running build_ext
      -- Adding Python module
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-req-build-im8_rrz4/python/build/temp.linux-x86_64-cpython-37
      Consolidate compiler generated dependencies of target triton
      [  2%] Linking CXX shared library /tmp/pip-req-build-im8_rrz4/python/build/lib.linux-x86_64-cpython-37/triton/_C/libtriton.so
      /usr/bin/ld: cannot find -lz
      /usr/bin/ld: cannot find -lz
      collect2: error: ld returned 1 exit status
      CMakeFiles/triton.dir/build.make:688: recipe for target '/tmp/pip-req-build-im8_rrz4/python/build/lib.linux-x86_64-cpython-37/triton/_C/libtriton.so' failed
      make[2]: *** [/tmp/pip-req-build-im8_rrz4/python/build/lib.linux-x86_64-cpython-37/triton/_C/libtriton.so] Error 1
      CMakeFiles/Makefile2:838: recipe for target 'CMakeFiles/triton.dir/all' failed
      make[1]: *** [CMakeFiles/triton.dir/all] Error 2
      Makefile:100: recipe for target 'all' failed
      make: *** [all] Error 2
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-im8_rrz4/python/setup.py", line 195, in <module>
          "tabulate",
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-im8_rrz4/python/setup.py", line 113, in run
          self.build_extension(ext)
        File "/tmp/pip-req-build-im8_rrz4/python/setup.py", line 148, in build_extension
          subprocess.check_call(["cmake", "--build", "."] + build_args, cwd=self.build_temp)
        File "/home/Shiro/anaconda3/envs/whisper_dynamo/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j16']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> triton

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
not really our problem
