### ISSUE TITLE
[Bug]: GoogleFnet failed to load with amp

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#93549]
### 🐛 Describe the bug

Command that fails:
```bash
python benchmarks/huggingface.py --performance --training -d cuda --backend=aot_eager --skip-accuracy-check --only GoogleFnet --amp
```

### Error logs

```py
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/fnet/modeling_fnet.py", line 220, in forward
    self_outputs = self.self(hidden_states)
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/fnet/modeling_fnet.py", line 199, in forward
    outputs = self.fourier_transform(hidden_states).real
RuntimeError: cuFFT only supports dimensions whose sizes are powers of two when computing in half precision, but got a signal size of[512, 768]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pytorch/torchdynamo/benchmarks/common.py", line 1881, in main
    device, name, model, example_inputs, batch_size = runner.load_model(
  File "benchmarks/huggingface.py", line 402, in load_model
    self.validate_model(model, example_inputs)
  File "/opt/pytorch/torchdynamo/benchmarks/common.py", line 1009, in validate_model
    raise NotImplementedError("Eager model failed to run")
NotImplementedError: Eager model failed to run

WARNING:root:GoogleFnet failed to load
```

### Did Dynamo succeed?

- [ ] Does dynamo.optimize("eager") succeed?

### Did AOT succeed?

- [ ] Did dynamo.optimize("aot_eager") succeed?

### Did Inductor succeed?

- [ ] Does dynamo.optimize("inductor") succeed?

### Minified repro

.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Close the issue as the error is gone. Repro:
```
python benchmarks/dynamo/huggingface.py --performance --training -d cuda --backend=aot_eager --skip-accuracy-check --only GoogleFnet --amp
```
