### ISSUE TITLE
LSTM and RNN fail dynamo lowering in eval mode due to FakeTensor issues

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#93555]
Fails to lower for the `validation` function, but doesn't really crash or anything.

```
$ python main.py --cuda --model LSTM
make_fallback(aten.unfold): a decomposition exists, we should switch to it
make_fallback(aten.unfold_backward): a decomposition exists, we should switch to it
[2022-10-19 22:33:01,885] torch._inductor.lowering: [WARNING] using triton random, expect difference from eager
[2022-10-19 22:33:02,712] torch._inductor.lowering: [WARNING] using triton random, expect difference from eager
| epoch   1 |   200/ 2983 batches | lr 20.00 | ms/batch 19.71 | loss  7.62 | ppl  2039.35
| epoch   1 |   400/ 2983 batches | lr 20.00 | ms/batch 11.68 | loss  6.85 | ppl   943.85
| epoch   1 |   600/ 2983 batches | lr 20.00 | ms/batch 12.93 | loss  6.48 | ppl   650.65
| epoch   1 |   800/ 2983 batches | lr 20.00 | ms/batch  8.14 | loss  6.29 | ppl   537.32
| epoch   1 |  1000/ 2983 batches | lr 20.00 | ms/batch  8.09 | loss  6.14 | ppl   464.14
| epoch   1 |  1200/ 2983 batches | lr 20.00 | ms/batch  8.10 | loss  6.06 | ppl   429.59
| epoch   1 |  1400/ 2983 batches | lr 20.00 | ms/batch  8.03 | loss  5.94 | ppl   379.93
| epoch   1 |  1600/ 2983 batches | lr 20.00 | ms/batch  7.97 | loss  5.93 | ppl   377.54
| epoch   1 |  1800/ 2983 batches | lr 20.00 | ms/batch  8.02 | loss  5.80 | ppl   329.85
| epoch   1 |  2000/ 2983 batches | lr 20.00 | ms/batch  8.03 | loss  5.77 | ppl   320.32
| epoch   1 |  2200/ 2983 batches | lr 20.00 | ms/batch  8.06 | loss  5.65 | ppl   285.32
| epoch   1 |  2400/ 2983 batches | lr 20.00 | ms/batch  8.03 | loss  5.66 | ppl   287.72
| epoch   1 |  2600/ 2983 batches | lr 20.00 | ms/batch  7.99 | loss  5.65 | ppl   284.09
| epoch   1 |  2800/ 2983 batches | lr 20.00 | ms/batch  8.13 | loss  5.54 | ppl   254.32
[2022-10-19 22:33:29,785] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT forward /home/soumith/code/examples/word_language_model/model.py line 48
due to:
Traceback (most recent call last):
  File "/home/soumith/code/pytorch/torch/_subclasses/fake_tensor.py", line 701, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten._cudnn_rnn.default(*(FakeTensor(FakeTensor(..., device='meta', size=(25, 20, 200),
           grad_fn=<NativeDropoutBackward0>), cuda:0), [FakeTensor(Parameter(FakeTensor(..., device='meta', size=(800, 200), requires_grad=True)), cuda:0), FakeTensor(Parameter(FakeTensor(..., device='meta', size=(800, 200), requires_grad=True)), cuda:0), FakeTensor(Parameter(FakeTensor(..., device='meta', size=(800,), requires_grad=True)), cuda:0), FakeTensor(Parameter(FakeTensor(..., device='meta', size=(800,), requires_grad=True)), cuda:0), FakeTensor(Parameter(FakeTensor(..., device='meta', size=(800, 200), requires_grad=True)), cuda:0), FakeTensor(Parameter(FakeTensor(..., device='meta', size=(800, 200), requires_grad=True)), cuda:0), FakeTensor(Parameter(FakeTensor(..., device='meta', size=(800,), requires_grad=True)), cuda:0), FakeTensor(Parameter(FakeTensor(..., device='meta', size=(800,), requires_grad=True)), cuda:0)], 4, None, FakeTensor(FakeTensor(..., device='meta', size=(2, 20, 200)), cuda:0), FakeTensor(FakeTensor(..., device='meta', size=(2, 20, 200)), cuda:0), 2, 200, 0, 2, False, 0.2, True, False, [], tensor([196, 214, 156,  ...,   0,   0,   0], device='cuda:0',
       dtype=torch.uint8)), **{})

from user code:
   File "/home/soumith/code/examples/word_language_model/model.py", line 50, in forward
    output, hidden = self.rnn(emb, hidden)

Set torch._dynamo.config.verbose=True for more information
==========
```

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Closes as it seems fixed repro here: [D51598964](https://www.internalfb.com/diff/D51598964) by changing --model to LSTM
