### ISSUE TITLE
PyTorch test suite regression test_module_backward_global_hook_writeable

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93627]
Bisected to https://github.com/pytorch/torchdynamo/pull/763

Repro command

```
PYTORCH_TEST_WITH_DYNAMO=1 python test/test_nn.py -k test_module_backward_global_hook_writeable
```

error

```
======================================================================                               
FAIL: test_module_backward_global_hook_writeable (__main__.TestModuleGlobalHooks)
----------------------------------------------------------------------                             
Traceback (most recent call last):                                                                   
  File "test/test_nn.py", line 21073, in test_module_backward_global_hook_writeable                  
    def test_module_backward_global_hook_writeable(self):                                            
  File "test/test_nn.py", line 21073, in test_module_backward_global_hook_writeable
    def test_module_backward_global_hook_writeable(self):                                          
  File "test/test_nn.py", line 21073, in test_module_backward_global_hook_writeable
    def test_module_backward_global_hook_writeable(self):             
  [Previous line repeated 1 more time]
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_internal/common_utils.py", line 2382, in assert
Equal
    assert_equal(                                                                                    
  File "/data/users/ezyang/pytorch-tmp/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 25 / 25 (100.0%)
Greatest absolute difference: 0.24967582497447965 at index (4, 2) (up to 1e-07 allowed)
Greatest relative difference: 0.5 at index (0, 0) (up to 1e-07 allowed)

----------------------------------------------------------------------
```

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel

**Comment by ydwu4** [comment]
The specific test mentioned in the issue is fixed. And I'm able to remove most of skipIfDynamo for the module hook tests in test_module_hooks.py in https://github.com/pytorch/pytorch/pull/114387

Repro:
```
PYTORCH_TEST_WITH_DYNAMO=1 pytest test/nn/test_module_hooks.py
```

However, there are still som tests failing with dynamo on:
```
FAILED [0.2588s] test/nn/test_module_hooks.py::TestModuleGlobalHooks::test_global_and_local_hooks_order - AssertionError: False is not true
FAILED [0.1678s] test/nn/test_module_hooks.py::TestModuleGlobalHooks::test_module_global_forward_preforward_hook_writeable - RecursionError: maximum recursion depth exceeded
FAILED [0.2042s] test/nn/test_module_hooks.py::TestModuleGlobalHooks::test_module_global_hooks - AssertionError: False is not true
```
