### ISSUE TITLE
botorch dynamo errors

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#93633]
botorch is a library for bayesian optimization in pytorch https://github.com/pytorch/botorch

`pip install botorch`

## Repro

```python
import torch
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_model
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood
import torchdynamo

train_X = torch.rand(10, 2)
Y = 1 - torch.norm(train_X - 0.5, dim=-1, keepdim=True)
Y = Y + 0.1 * torch.randn_like(Y)  # add some noise
train_Y = standardize(Y)

gp = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)

with torchdynamo.optimize("eager"):
    model = fit_gpytorch_model(mll)
print(model)
```

## Logs without torchdynamo

```
ExactMarginalLogLikelihood(
  (likelihood): GaussianLikelihood(
    (noise_covar): HomoskedasticNoise(
      (noise_prior): GammaPrior()
      (raw_noise_constraint): GreaterThan(1.000E-04)
    )
  )
  (model): SingleTaskGP(
    (likelihood): GaussianLikelihood(
      (noise_covar): HomoskedasticNoise(
        (noise_prior): GammaPrior()
        (raw_noise_constraint): GreaterThan(1.000E-04)
      )
    )
    (mean_module): ConstantMean()
    (covar_module): ScaleKernel(
      (base_kernel): MaternKernel(
        (lengthscale_prior): GammaPrior()
        (raw_lengthscale_constraint): Positive()
        (distance_module): Distance()
      )
      (outputscale_prior): GammaPrior()
      (raw_outputscale_constraint): Positive()
    )
  )
)
```

## Logs with torchdynamo

```
(myenv) ubuntu@ip-172-31-21-78:~/tests$ python bo.py 
Traceback (most recent call last):
  File "bo.py", line 17, in <module>
    model = fit_gpytorch_model(mll)
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/botorch/fit.py", line 38, in fit_gpytorch_model
    def fit_gpytorch_model(
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/botorch/fit.py", line 38, in fit_gpytorch_model
    def fit_gpytorch_model(
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/botorch/fit.py", line 38, in fit_gpytorch_model
    def fit_gpytorch_model(
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/botorch/fit.py", line 130, in fit_gpytorch_model
    mll, _ = optimizer(mll, track_iterations=False, **kwargs)
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/botorch/optim/fit.py", line 174, in fit_gpytorch_scipy
    def fit_gpytorch_scipy(
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/botorch/optim/fit.py", line 174, in fit_gpytorch_scipy
    def fit_gpytorch_scipy(
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/botorch/optim/fit.py", line 239, in fit_gpytorch_scipy
    res = minimize(
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 45, in minimize
    def minimize(fun, x0, args=(), method=None, jac=None, hess=None,
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 45, in minimize
    def minimize(fun, x0, args=(), method=None, jac=None, hess=None,
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 699, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/scipy/optimize/_lbfgsb_py.py", line 212, in _minimize_lbfgsb
    def _minimize_lbfgsb(fun, x0, args=(), jac=None, bounds=None,
  File "/home/ubuntu/.conda/envs/myenv/lib/python3.8/site-packages/scipy/optimize/_lbfgsb_py.py", line 212, in _minimize_lbfgsb
    def _minimize_lbfgsb(fun, x0, args=(), jac=None, bounds=None,
NameError: name 'torch' is not defined
```

But I do have `torch` installed and it does run just fine without dynamo

```
(myenv) ubuntu@ip-172-31-21-78:~/tests$ pip list
Package             Version     Editable project location
------------------- ----------- -------------------------
attrs               22.1.0
black               22.6.0
botorch             0.6.6
certifi             2022.6.15
charset-normalizer  2.1.0
click               8.1.3
coolname            1.1.0
docstring-parser    0.14.1
expecttest          0.1.3
flake8              4.0.1
gpytorch            1.8.1
idna                3.3
importlib-metadata  4.12.0
importlib-resources 5.9.0
iniconfig           1.1.1
isort               5.10.1
Jinja2              3.1.2
joblib              1.1.0
jsonschema          4.7.2
MarkupSafe          2.1.1
mccabe              0.6.1
mosaicml            0.9.0
mpmath              1.2.1
multipledispatch    0.6.0
mypy-extensions     0.4.3
networkx            2.8.5
ninja               1.10.2.3
numpy               1.22.4
opt-einsum          3.3.0
packaging           21.3
pathspec            0.9.0
Pillow              9.2.0
pip                 22.2.2
platformdirs        2.5.2
pluggy              1.0.0
psutil              5.9.1
py                  1.11.0
py-cpuinfo          8.0.0
pycodestyle         2.8.0
pyDeprecate         0.3.2
pyflakes            2.4.0
pyparsing           3.0.9
pyro-api            0.1.2
pyro-ppl            1.8.1
pyrsistent          0.18.1
pytest              7.1.2
pytorch-ranger      0.1.1
PyYAML              6.0
requests            2.28.1
ruamel.yaml         0.17.21
ruamel.yaml.clib    0.2.6
scikit-learn        1.1.2
scipy               1.9.0
setuptools          65.0.2
six                 1.16.0
sympy               1.10.1
tabulate            0.8.9
threadpoolctl       3.1.0
tomli               2.0.1
torch               1.12.1
torch-optimizer     0.1.0
torchdynamo         1.13.0.dev0 /home/ubuntu/torchdynamo
torchmetrics        0.7.3
torchvision         0.13.1
tqdm                4.64.0
typing_extensions   4.3.0
urllib3             1.26.11
wheel               0.37.1
yahp                0.1.3
zipp                3.8.1
```

cc @ezyang @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @wconstab @zou3519 @aakhundov @soumith @ngimel

**Comment by ydwu4** [comment]
eager run succeeds but torch.compile with eager backend fails.
Repro
```
conda install botorch -c pytorch -c gpytorch -c conda-forge
```
```python
import torch
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_model
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood

train_X = torch.rand(10, 2)
Y = 1 - torch.norm(train_X - 0.5, dim=-1, keepdim=True)
Y = Y + 0.1 * torch.randn_like(Y)  # add some noise
train_Y = standardize(Y)

gp = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)

# fit_gpytorch_model(mll)
torch.compile(fit_gpytorch_model, backend="eager")(mll)

```
Error log:
```
/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/botorch/models/gp_regression.py:161: UserWarning: The model inputs are of type torch.float32. It is strongly recommended to use double precision in BoTorch, as this improves both precision and stability and can help avoid numerical errors. See https://github.com/pytorch/botorch/discussions/1444
  self._validate_tensor_args(X=transformed_X, Y=train_Y, Yvar=train_Yvar)
[2023-11-22 11:17:56,546] [7/0] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,558] [8/0] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,577] [9/0] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,610] [7/1] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,623] [8/1] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,641] [7/2] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,653] [8/2] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,668] [7/3] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,680] [8/3] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,695] [7/4] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,708] [8/4] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,723] [7/5] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,737] [8/5] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,752] [7/6] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,765] [8/6] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,780] [7/7] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,793] [8/7] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_map of BuiltinVariable(map)> too many positional arguments and no constant handler
[2023-11-22 11:17:56,804] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (8)
[2023-11-22 11:17:56,804] torch._dynamo.convert_frame: [WARNING]    function: 'edge' (/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/conflict.py:97)
[2023-11-22 11:17:56,804] torch._dynamo.convert_frame: [WARNING]    last reason: ___check_obj_id(L['a'][0], 79750480)                          # return supercedes(a, b) and (  # miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/conflict.py:104 in edge
[2023-11-22 11:17:56,804] torch._dynamo.convert_frame: [WARNING] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[2023-11-22 11:17:56,804] torch._dynamo.convert_frame: [WARNING] To diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
[2023-11-22 11:17:56,805] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (8)
[2023-11-22 11:17:56,805] torch._dynamo.convert_frame: [WARNING]    function: 'supercedes' (/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/conflict.py:9)
[2023-11-22 11:17:56,805] torch._dynamo.convert_frame: [WARNING]    last reason: ___check_obj_id(L['a'][0], 79750480)                          # if len(a) < len(b):  # miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/conflict.py:11 in supercedes
[2023-11-22 11:17:56,805] torch._dynamo.convert_frame: [WARNING] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[2023-11-22 11:17:56,805] torch._dynamo.convert_frame: [WARNING] To diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
Traceback (most recent call last):
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/botorch/utils/dispatcher.py", line 70, in __getitem__
    func = self._cache[types]
KeyError: (<class 'gpytorch.mlls.exact_marginal_log_likelihood.ExactMarginalLogLikelihood'>, <class 'gpytorch.likelihoods.gaussian_likelihood.GaussianLikelihood'>, <class 'botorch.models.gp_regression.SingleTaskGP'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 255, in ordering
    return self._ordering
AttributeError: 'Dispatcher' object has no attribute '_ordering'. Did you mean: 'ordering'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yidi/local/pytorch/repro6.py", line 16, in <module>
    torch.compile(fit_gpytorch_model, backend="eager")(mll)
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/botorch/fit.py", line 139, in fit_gpytorch_model
    warn(
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/botorch/fit.py", line 164, in resume_in_fit_gpytorch_model
    mll = fit_gpytorch_mll(
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/botorch/fit.py", line 105, in fit_gpytorch_mll
    return FitGPyTorchMLL(
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/botorch/utils/dispatcher.py", line 91, in __call__
    func = self.__getitem__(types=types)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/botorch/utils/dispatcher.py", line 72, in __getitem__
    func = self.dispatch(*types)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/botorch/utils/dispatcher.py", line 123, in dispatch
    return next(self.dispatch_iter(*types))
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 333, in dispatch_iter
    for signature in self.ordering:
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 257, in ordering
    return self.reorder()
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 260, in reorder
    self._ordering = od = ordering(self.funcs)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/conflict.py", line 121, in ordering
    return _toposort(edges)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/utils.py", line 50, in _toposort
    incoming_edges = reverse_dict(edges)
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 721, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 645, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/yidi/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2123, in run
    super().run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1213, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 652, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/misc.py", line 643, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/user_defined.py", line 284, in call_method
    keys = self.call_method(tx, "keys", [], {})
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/user_defined.py", line 260, in call_method
    assert all(map(ConstantVariable.is_literal, keys))
AssertionError: 

from user code:
   File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/multipledispatch/utils.py", line 52, in resume_in__toposort
    for k, val in incoming_edges.items())

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by lezcano** [comment]
@anijain2305 This doesn't fail with the same error in master. I think that, after the dict clean-up I did, most of the dynamo intersection dicts issues should now be gone.

FWIW, it now fails with:
```python
  File "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 1566, in LOAD_ATTR                                                                                                                
    self._load_attr(inst)                                                                                                                                                                                            
  File "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/symbolic_convert.py", line 1556, in _load_attr                                                                                                               
    result = BuiltinVariable(getattr).call_function(                                                                                                                                                                 
  File "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builtin.py", line 962, in call_function                                                                                                            
    return handler(tx, args, kwargs)
  File "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builtin.py", line 846, in builtin_dipatch
    rv = fn(tx, args, kwargs)
  File "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builtin.py", line 764, in call_self_handler
    result = self_handler(tx, *args, **kwargs)
  File "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builtin.py", line 1626, in call_getattr
    return obj.var_getattr(tx, name)
  File "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/misc.py", line 110, in var_getattr
    value, source = self._resolved_getattr_and_source(self, name)
  File "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/misc.py", line 88, in _resolved_getattr_and_source
    start_index = search_mro.index(search_type) + 1
torch._dynamo.exc.InternalTorchDynamoError: tuple.index(x): x not in tuple
```
