### ISSUE TITLE
Fake tensor `profiler::_record_function_enter()` errors from moco

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93649]
Repro
```
./benchmarks/torchbench.py --only moco
```

`torchdynamo.config.fake_tensor_propagation = False`
```
cuda eval  moco                               STAGE:2022-08-26 17:56:59 2219380:2219380 ActivityProfilerController.cpp:294] Completed Stage: Warm Up
STAGE:2022-08-26 17:56:59 2219380:2219380 ActivityProfilerController.cpp:300] Completed Stage: Collection
  1/  1 +0 frames   1s  1 graphs  1 graph calls    3/   4 =  75% ops 100% time
```

`torchdynamo.config.fake_tensor_propagation = True`
```
cuda eval  moco                               torchdynamo.convert_frame: [ERROR] WON'T CONVERT forward_pass ./benchmarks/torchbench.py line 368 
due to: 
Traceback (most recent call last):
  File "/home/jansel/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: profiler::_record_function_enter() expected at most 2 argument(s) but received 3 argument(s). Declaration: profiler::_record_function_enter(str name, str? args=None) -> Tensor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jansel/torchdynamo/torchdynamo/variables/tensor.py", line 146, in create
    raise TorchRuntimeError() from e
torchdynamo.exc.TorchRuntimeError

from user code:
   File "./benchmarks/torchbench.py", line 369, in forward_pass
    return mod(*inputs)

Set torchdynamo.config.verbose=True for more information
==========
torchdynamo.convert_frame: [ERROR] WON'T CONVERT concat_all_gather /home/jansel/torchbenchmark/torchbenchmark/models/moco/moco/builder.py line 164 
due to: 
Traceback (most recent call last):
  File "/home/jansel/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Tensors must be CUDA and dense

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jansel/torchdynamo/torchdynamo/variables/tensor.py", line 146, in create
    raise TorchRuntimeError() from e
torchdynamo.exc.TorchRuntimeError

from user code:
   File "/home/jansel/torchbenchmark/torchbenchmark/models/moco/moco/builder.py", line 172, in concat_all_gather
    torch.distributed.all_gather(tensors_gather, tensor, async_op=False)

Set torchdynamo.config.verbose=True for more information
==========
torchdynamo.convert_frame: [ERROR] WON'T CONVERT _batch_shuffle_ddp /home/jansel/torchbenchmark/torchbenchmark/models/moco/moco/builder.py line 68 
due to: 
Traceback (most recent call last):
  File "/home/jansel/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Tensors must be CUDA and dense

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jansel/torchdynamo/torchdynamo/variables/tensor.py", line 146, in create
    raise TorchRuntimeError() from e
torchdynamo.exc.TorchRuntimeError

from user code:
   File "/home/jansel/torchbenchmark/torchbenchmark/models/moco/moco/builder.py", line 85, in _batch_shuffle_ddp
    torch.distributed.broadcast(idx_shuffle, src=0)

Set torchdynamo.config.verbose=True for more information
==========
STAGE:2022-08-26 17:58:33 2219502:2219502 ActivityProfilerController.cpp:294] Completed Stage: Warm Up
STAGE:2022-08-26 17:58:33 2219502:2219502 ActivityProfilerController.cpp:300] Completed Stage: Collection
 16/ 19 +1 frames   2s 11 graphs  7 graph calls    0/  -4 =   0% ops   0% time
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @eellison

**Comment by ezyang** [comment]
moco passes on master
