### ISSUE TITLE
optimizer.step fails on fake tensor mode

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#93654]
Repro:
```
import torch
import torch.optim as optim
import torchdynamo

torchdynamo.config.fake_tensor_propagation = True

input = torch.ones([10, 10])
model = torch.nn.Sequential(*[torch.nn.Linear(10, 10) for _ in range(2)])
opt_model = torchdynamo.optimize("aot_nop")(model)
opt_model(input).sum().backward()

optimizer = optim.SGD(opt_model.parameters(), lr=5e-5)
opt_fn = torchdynamo.optimize("aot_nop")(optimizer.step)
opt_fn()
```

Error:
```
Traceback (most recent call last):
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/variables/tensor.py", line 87, in run_proxy
    return getattr(args[0], proxy.node.target)(*args[1:], **kwargs)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/variables/tensor.py", line 146, in create
    raise TorchRuntimeError() from e
torchdynamo.exc.TorchRuntimeError

from user code:
   File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs)

Set torchdynamo.config.verbose=True for more information
==========
----------------------------------------
TORCHDYNAMO: backend compiler failed
Traceback (most recent call last):
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/output_graph.py", line 392, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/optimizations/training.py", line 34, in compile_fn
    return cls(gm, example_inputs).verified_candidate()
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/optimizations/training.py", line 75, in __init__
    mutated = has_mutation(self.gm, self.example_inputs, inputs_only=True)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/optimizations/training.py", line 84, in example_inputs
    return clone_inputs(self.original_example_inputs)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/utils.py", line 368, in clone_inputs
    res[i] = clone_input(res[i])
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/utils.py", line 339, in clone_input
    result.copy_(x.clone())
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 470, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 679, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.copy_.default(*(tensor([[-5.3634e-33,  4.5797e-41, -5.3908e-33,  4.5797e-41, -5.3153e-33,
          4.5797e-41, -5.3010e-33,  4.5797e-41, -5.3901e-33,  4.5797e-41],
        [-5.4168e-33,  4.5797e-41, -5.4390e-33,  4.5797e-41, -5.3907e-33,
          4.5797e-41, -5.3066e-33,  4.5797e-41, -5.3629e-33,  4.5797e-41],
        [-5.3903e-33,  4.5797e-41, -5.3016e-33,  4.5797e-41, -5.4077e-33,
          4.5797e-41, -5.3901e-33,  4.5797e-41, -5.1979e-33,  4.5797e-41],
        [-5.0980e-32,  4.5797e-41, -5.3904e-33,  4.5797e-41, -5.3516e-33,
          4.5797e-41, -5.2259e-33,  4.5797e-41, -5.4216e-33,  4.5797e-41],
        [-5.3020e-33,  4.5797e-41, -5.3626e-33,  4.5797e-41, -5.4225e-33,
          4.5797e-41, -5.3146e-33,  4.5797e-41, -5.3920e-33,  4.5797e-41],
        [-5.4213e-33,  4.5797e-41, -5.3389e-33,  4.5797e-41, -5.3636e-33,
          4.5797e-41, -5.4216e-33,  4.5797e-41, -5.4645e-33,  4.5797e-41],
        [-5.4448e-33,  4.5797e-41, -5.4213e-33,  4.5797e-41, -5.3320e-33,
          4.5797e-41, -5.4389e-33,  4.5797e-41, -5.4214e-33,  4.5797e-41],
        [-5.4170e-33,  4.5797e-41, -5.3632e-33,  4.5797e-41, -5.4215e-33,
          4.5797e-41, -5.3324e-33,  4.5797e-41, -5.4641e-33,  4.5797e-41],
        [-5.3909e-33,  4.5797e-41, -5.4480e-33,  4.5797e-41, -1.1955e-31,
          4.5797e-41, -5.4226e-33,  4.5797e-41, -5.4646e-33,  4.5797e-41],
        [-5.2261e-33,  4.5797e-41, -5.4224e-33,  4.5797e-41, -5.2819e-33,
          4.5797e-41, -5.3225e-33,  4.5797e-41, -5.4218e-33,  4.5797e-41]]), FakeTensor(<torch._subclasses.fake_tensor.FakeTensorMode object at 0x7faa89dc73d0>, FakeTensor(..., device='meta', size=(10, 10)), cpu)), **{})
----------------------------------------
torchdynamo.convert_frame: [ERROR] WON'T CONVERT step /fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/optim/sgd.py line 119 
due to: 
Traceback (most recent call last):
  File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 679, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.copy_.default(*(tensor([[-5.3634e-33,  4.5797e-41, -5.3908e-33,  4.5797e-41, -5.3153e-33,
          4.5797e-41, -5.3010e-33,  4.5797e-41, -5.3901e-33,  4.5797e-41],
        [-5.4168e-33,  4.5797e-41, -5.4390e-33,  4.5797e-41, -5.3907e-33,
          4.5797e-41, -5.3066e-33,  4.5797e-41, -5.3629e-33,  4.5797e-41],
        [-5.3903e-33,  4.5797e-41, -5.3016e-33,  4.5797e-41, -5.4077e-33,
          4.5797e-41, -5.3901e-33,  4.5797e-41, -5.1979e-33,  4.5797e-41],
        [-5.0980e-32,  4.5797e-41, -5.3904e-33,  4.5797e-41, -5.3516e-33,
          4.5797e-41, -5.2259e-33,  4.5797e-41, -5.4216e-33,  4.5797e-41],
        [-5.3020e-33,  4.5797e-41, -5.3626e-33,  4.5797e-41, -5.4225e-33,
          4.5797e-41, -5.3146e-33,  4.5797e-41, -5.3920e-33,  4.5797e-41],
        [-5.4213e-33,  4.5797e-41, -5.3389e-33,  4.5797e-41, -5.3636e-33,
          4.5797e-41, -5.4216e-33,  4.5797e-41, -5.4645e-33,  4.5797e-41],
        [-5.4448e-33,  4.5797e-41, -5.4213e-33,  4.5797e-41, -5.3320e-33,
          4.5797e-41, -5.4389e-33,  4.5797e-41, -5.4214e-33,  4.5797e-41],
        [-5.4170e-33,  4.5797e-41, -5.3632e-33,  4.5797e-41, -5.4215e-33,
          4.5797e-41, -5.3324e-33,  4.5797e-41, -5.4641e-33,  4.5797e-41],
        [-5.3909e-33,  4.5797e-41, -5.4480e-33,  4.5797e-41, -1.1955e-31,
          4.5797e-41, -5.4226e-33,  4.5797e-41, -5.4646e-33,  4.5797e-41],
        [-5.2261e-33,  4.5797e-41, -5.4224e-33,  4.5797e-41, -5.2819e-33,
          4.5797e-41, -5.3225e-33,  4.5797e-41, -5.4218e-33,  4.5797e-41]]), FakeTensor(<torch._subclasses.fake_tensor.FakeTensorMode object at 0x7faa89dc73d0>, FakeTensor(..., device='meta', size=(10, 10)), cpu)), **{})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/output_graph.py", line 401, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torchdynamo.exc.BackendCompilerFailed: compile_fn raised Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.copy_.default(*(tensor([[-5.3634e-33,  4.5797e-41, -5.3908e-33,  4.5797e-41, -5.3153e-33,
          4.5797e-41, -5.3010e-33,  4.5797e-41, -5.3901e-33,  4.5797e-41],
        [-5.4168e-33,  4.5797e-41, -5.4390e-33,  4.5797e-41, -5.3907e-33,
          4.5797e-41, -5.3066e-33,  4.5797e-41, -5.3629e-33,  4.5797e-41],
        [-5.3903e-33,  4.5797e-41, -5.3016e-33,  4.5797e-41, -5.4077e-33,
          4.5797e-41, -5.3901e-33,  4.5797e-41, -5.1979e-33,  4.5797e-41],
        [-5.0980e-32,  4.5797e-41, -5.3904e-33,  4.5797e-41, -5.3516e-33,
          4.5797e-41, -5.2259e-33,  4.5797e-41, -5.4216e-33,  4.5797e-41],
        [-5.3020e-33,  4.5797e-41, -5.3626e-33,  4.5797e-41, -5.4225e-33,
          4.5797e-41, -5.3146e-33,  4.5797e-41, -5.3920e-33,  4.5797e-41],
        [-5.4213e-33,  4.5797e-41, -5.3389e-33,  4.5797e-41, -5.3636e-33,
          4.5797e-41, -5.4216e-33,  4.5797e-41, -5.4645e-33,  4.5797e-41],
        [-5.4448e-33,  4.5797e-41, -5.4213e-33,  4.5797e-41, -5.3320e-33,
          4.5797e-41, -5.4389e-33,  4.5797e-41, -5.4214e-33,  4.5797e-41],
        [-5.4170e-33,  4.5797e-41, -5.3632e-33,  4.5797e-41, -5.4215e-33,
          4.5797e-41, -5.3324e-33,  4.5797e-41, -5.4641e-33,  4.5797e-41],
        [-5.3909e-33,  4.5797e-41, -5.4480e-33,  4.5797e-41, -1.1955e-31,
          4.5797e-41, -5.4226e-33,  4.5797e-41, -5.4646e-33,  4.5797e-41],
        [-5.2261e-33,  4.5797e-41, -5.4224e-33,  4.5797e-41, -5.2819e-33,
          4.5797e-41, -5.3225e-33,  4.5797e-41, -5.4218e-33,  4.5797e-41]]), FakeTensor(<torch._subclasses.fake_tensor.FakeTensorMode object at 0x7faa89dc73d0>, FakeTensor(..., device='meta', size=(10, 10)), cpu)), **{})

You can suppress this exception and fall back to eager by setting:
    torchdynamo.config.raise_on_backend_error = False

from user code:
   File "/fsx/users/ybliang/conda/envs/dynamo-gpu/lib/python3.9/site-packages/torch/optim/sgd.py", line 168, in step
    return loss

Set torchdynamo.config.verbose=True for more information
```
It works well if turning off fake tensor.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
this is fixed now

```
import torch
import torch.optim as optim

input = torch.ones([10, 10])
model = torch.nn.Sequential(*[torch.nn.Linear(10, 10) for _ in range(2)])
opt_model = torch.compile(model)
opt_model(input).sum().backward()

optimizer = optim.SGD(opt_model.parameters(), lr=5e-5)
opt_fn = torch.compile(optimizer.step)
opt_fn()

```
