### ISSUE TITLE
PyTorch Lightning AssertionError on trainer.fit()

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#93658]
## Repro

Could probably make this shorter, this was the original tutorial https://colab.research.google.com/github/kornia/tutorials/blob/master/source/data_augmentation_kornia_lightning_gpu.ipynb - this is not a "weird model". It's a PyTorch lightning example leveraging Kornia which is a preprocessing framework written in pure PyTorch and is something I actually wanted to accelerate

```python
import torchdynamo
from torchdynamo import optimize
import os

import torch
import torch.nn as nn
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision.datasets import CIFAR10
import time
import torchmetrics
import pytorch_lightning as pl
import kornia as K

import numpy as np
from PIL import Image

"""## Define Data Augmentations module"""

class DataAugmentation(nn.Module):
    """Module to perform data augmentation using Kornia on torch tensors."""
    def __init__(self, apply_color_jitter: bool = False) -> None:
        super().__init__()
        self._apply_color_jitter = apply_color_jitter

        self._max_val: float = 255.

        self.transforms = nn.Sequential(
            K.enhance.Normalize(0., self._max_val),
            K.augmentation.RandomHorizontalFlip(p=0.5)
        )

        self.jitter = K.augmentation.ColorJitter(0.5, 0.5, 0.5, 0.5)

    @torch.no_grad()  # disable gradients for effiency
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x_out = self.transforms(x)  # BxCxHxW
        if self._apply_color_jitter:
            x_out = self.jitter(x_out)
        return x_out

"""## Define a Pre-processing model"""

class PreProcess(nn.Module):
    """Module to perform pre-process using Kornia on torch tensors."""
    def __init__(self) -> None:
        super().__init__()
 
    @torch.no_grad()  # disable gradients for effiency
    def forward(self, x: Image) -> torch.Tensor:
        x_tmp: np.ndarray = np.array(x)  # HxWxC
        x_out: torch.Tensor = K.image_to_tensor(x_tmp, keepdim=True)  # CxHxW
        return x_out.float()

"""## Define PyTorch Lightning model"""

class CoolSystem(pl.LightningModule):

    def __init__(self):
        super(CoolSystem, self).__init__()
        # not the best model...
        self.l1 = torch.nn.Linear(3 * 32 * 32, 10)

        self.preprocess = PreProcess()

        self.transform = DataAugmentation()

        self.accuracy = torchmetrics.Accuracy()

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def training_step(self, batch, batch_idx):
        # REQUIRED
        x, y = batch
        x_aug = self.transform(x)  # => we perform GPU/Batched data augmentation
        logits = self.forward(x_aug)
        loss = F.cross_entropy(logits, y)
        self.log('train_acc_step', self.accuracy(logits.argmax(1), y))
        self.log('train_loss', loss)
        return loss

    def validation_step(self, batch, batch_idx):
        # OPTIONAL
        x, y = batch
        logits = self.forward(x)
        self.log('val_acc_step', self.accuracy(logits.argmax(1), y))
        return F.cross_entropy(logits, y)

    def configure_optimizers(self):
        # REQUIRED
        # can return multiple optimizers and learning_rate schedulers
        # (LBFGS it is automatically supported, no need for closure function)
        return torch.optim.Adam(self.parameters(), lr=0.0004)

    def prepare_data(self):
        CIFAR10(os.getcwd(), train=True, download=True, transform=self.preprocess)
        CIFAR10(os.getcwd(), train=False, download=True, transform=self.preprocess)

    def train_dataloader(self):
        # REQUIRED
        dataset = CIFAR10(os.getcwd(), train=True, download=False, transform=self.preprocess)
        loader = DataLoader(dataset, batch_size=32)
        return loader

    def val_dataloader(self):
        dataset = CIFAR10(os.getcwd(), train=True, download=False, transform=self.preprocess)
        loader = DataLoader(dataset, batch_size=32)
        return loader

"""## Run training"""

from pytorch_lightning import Trainer

# init model
model = CoolSystem()

# Initialize a trainer
num_gpus: int = 0  # change to 1
trainer = Trainer(gpus=1, max_epochs=1)

tic = time.time()

# Train the model ⚡
# trainer.fit(model)
toc = time.time()

duration = toc - tic
print(f"Total running time without dynamo was {duration}")


tic = time.time()

@torchdynamo.optimize("inductor")
def wrapper_func():
    trainer.fit(model)

# Train the model ⚡
wrapper_func()
toc = time.time()

duration = toc - tic
print(f"Total running time with dynamo was {duration}")
```

## Error

The training actually completes and then fails with an assertion error

```
(korn) ubuntu@ip-172-31-18-178:~/torchdynamo$ python data.py 
/home/ubuntu/.conda/envs/korn/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:447: LightningDeprecationWarning: Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.
  rank_zero_deprecation(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Total running time without dynamo was 1.6689300537109375e-06
Files already downloaded and verified
Files already downloaded and verified
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type             | Params
------------------------------------------------
0 | l1         | Linear           | 30.7 K
1 | preprocess | PreProcess       | 0     
2 | transform  | DataAugmentation | 0     
3 | accuracy   | Accuracy         | 0     
------------------------------------------------
30.7 K    Trainable params
0         Non-trainable params
30.7 K    Total params
0.123     Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/home/ubuntu/.conda/envs/korn/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:225: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/home/ubuntu/.conda/envs/korn/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:225: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 3126/3126 [00:28<00:00, 110.54it/s, loss=2.26, v_num=4]`Trainer.fit` stopped: `max_epochs=1` reached.                                                                                                                        
Epoch 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 3126/3126 [00:28<00:00, 110.53it/s, loss=2.26, v_num=4]
Traceback (most recent call last):
  File "data.py", line 136, in <module>
    a = torchdynamo.optimize("inductor")(trainer.fit(model))
  File "/home/ubuntu/torchdynamo/torchdynamo/eval_frame.py", line 154, in __call__
    assert callable(fn)
AssertionError
```

cc @ezyang @soumith @wconstab @ngimel @bdhirsh

**Comment by lantiga** [comment]
As an update: we added support for running `torch.compile` on `LightningModule` subclasses in Lightning 1.9.

See our tests here:
https://github.com/Lightning-AI/lightning/blob/master/tests/tests_pytorch/trainer/test_trainer.py#L2131
https://github.com/Lightning-AI/lightning/blob/master/tests/tests_pytorch/core/test_lightning_module.py#L475
