### ISSUE TITLE
pytorch core test failure: ValueError: gradcheck expects at least one input tensor to require gradient, but none of the them have requires_grad=True.

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#93676]
Repro:
cherry-pick https://github.com/pytorch/pytorch/pull/85183
```
PYTORCH_TEST_WITH_INDUCTOR=1 pytest test/distributions/test_distributions.py  -k  test_bernoulli
```

Error:
```
========================================================================================================= FAILURES ==========================================================================================================
_____________________________________________________________________________________________ TestDistributions.test_bernoulli ______________________________________________________________________________________________
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 1035, in test_bernoulli
    def test_bernoulli(self):
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 1045, in <graph break in test_bernoulli>
    self._gradcheck_log_prob(Bernoulli, (p,))
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 820, in _gradcheck_log_prob
    gradcheck(apply_fn, (s,) + tuple(ctor_params), raise_exception=True)
  File "/fsx/users/binbao/pytorch/torch/testing/_internal/common_utils.py", line 3302, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/fsx/users/binbao/pytorch/torch/autograd/gradcheck.py", line 1418, in gradcheck
    return _gradcheck_helper(**args)
  File "/fsx/users/binbao/pytorch/torch/autograd/gradcheck.py", line 1425, in _gradcheck_helper
    _check_inputs(tupled_inputs, check_sparse_nnz)
  File "/fsx/users/binbao/pytorch/torch/autograd/gradcheck.py", line 675, in _check_inputs
    raise ValueError(
ValueError: gradcheck expects at least one input tensor to require gradient, but none of the them have requires_grad=True.
----------------------------------------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------------------------------------
ERROR    torchdynamo.convert_frame:convert_frame.py:360 WON'T CONVERT <graph break in test_bernoulli> /fsx/users/binbao/pytorch/test/distributions/test_distributions.py line 1039 
due to: 
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/variables/constant.py", line 63, in const_getattr
    member = getattr(self.value, name)
AttributeError: 'tuple' object has no attribute '_extended_shape'

from user code:
   File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 1039, in <graph break in test_bernoulli>
    self.assertEqual(Bernoulli(p).sample((8,)).size(), (8, 3))

Set torchdynamo.config.verbose=True for more information
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by gchanan** [comment]
This passed for me.
