### ISSUE TITLE
pytorch core test failure: RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#93677]
Repro:
cherry-pick https://github.com/pytorch/pytorch/pull/85183
```
PYTORCH_TEST_WITH_INDUCTOR=1 pytest test/distributions/test_distributions.py  -k  test_pareto
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 2556, in test_pareto
    self._check_log_prob(Pareto(scale, alpha), ref_log_prob)
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 837, in _check_log_prob
    asset_fn(i, val.squeeze(), log_prob)
  File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 2550, in ref_log_prob
    def ref_log_prob(idx, x, log_prob):
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 1884, in logpdf
    def logpdf(self, x, *args, **kwds):
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 1907, in <graph break in logpdf>
    args, loc, scale = self._parse_args(*args, **kwds)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 1908, in <graph break in logpdf>
    x, loc, scale = map(asarray, (x, loc, scale))
  File "/fsx/users/binbao/pytorch/torch/_tensor.py", line 945, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
----------------------------------------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------------------------------------
ERROR    torchdynamo.convert_frame:convert_frame.py:357 WON'T CONVERT test_pareto /fsx/users/binbao/pytorch/test/distributions/test_distributions.py line 2535 
due to: 
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/variables/tensor.py", line 266, in create
    assert (
AssertionError: torch.* op returned non-Tensor dtype call_function <built-in function get_default_dtype>

from user code:
   File "/fsx/users/binbao/pytorch/test/distributions/test_distributions.py", line 2541, in test_pareto
    self.assertEqual(Pareto(scale_1d, 0.5).mean, inf)

Set torchdynamo.config.verbose=True for more information
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by desertfire** [comment]
fixed on trunk
