### ISSUE TITLE
Unexpected assertionError when export tensor.numel

### ISSUE THREAD

**Issue by ydwu4** [pytorch/pytorch#93686]
@voznesenskym Hi, I got this unexpected result when I was playing with the export API.

Repro 1:
```python
import torch
import torchdynamo
def f(x: torch.Tensor):
    return x.numel()

torchdynamo.config.capture_scalar_outputs = True
print(torchdynamo.explain(f, torch.ones(1)))
torchdynamo.export(f, torch.ones(1))
```
The above code outputs the following:

```
('Dynamo produced 0 graphswith -1 graph break and 0 ops\n Break reasons: \n\nTorchDynamo compilation metrics:\nFunction                                               Runtimes (s)\n---------------------------------------------------  --------------\nconvert_frame_assert.<locals>._convert_frame_assert          0.0057', [], [], [], [])
Traceback (most recent call last):
  File "test_dynamo.py", line 8, in <module>
    torchdynamo.export(f, torch.ones(1))
  File "/usr/lib/python3.8/site-packages/torchdynamo-1.13.0.dev0-py3.8-linux-x86_64.egg/torchdynamo/eval_frame.py", line 508, in export
    assert graph is not None, "whole graph export entails exactly one call"
AssertionError: whole graph export entails exactly one call
```
Try
Repro 2:
```python
import torch
import torchdynamo
def f(x: torch.Tensor):
    return x.numel() + x.sin().numel()

torchdynamo.config.capture_scalar_outputs = True
print(torchdynamo.explain(f, torch.ones(1)))
torchdynamo.export(f, torch.ones(1))
```
The above code produces the following error:
```
('Dynamo produced 1 graphswith 0 graph break and 0 ops\n Break reasons: \n\nTorchDynamo compilation metrics:\nFunction                                               Runtimes (s)\n---------------------------------------------------  --------------\nconvert_frame_assert.<locals>._convert_frame_assert          0.0084', [{Guard(name='x', source=<GuardSource.LOCAL: 0>, create_fn=<function GuardBuilder.TENSOR_MATCH at 0x7fe53c4c8f70>, is_volatile=False, guard_types=['TENSOR_MATCH'], code_list=None, obj_weakref=<weakref at 0x7fe53d444130; dead>, guarded_class_weakref=<weakref at 0x7fe5452804a0; to 'torch._C._TensorMeta' at 0x55f9ccd80230 (Tensor)>)}], [GraphModule()], [[]], [])
flat both [tensor([1.])] flat_results_traced [2]
Traceback (most recent call last):
  File "test_dynamo.py", line 8, in <module>
    torchdynamo.export(f, torch.ones(1))
  File "/usr/lib/python3.8/site-packages/torchdynamo-1.13.0.dev0-py3.8-linux-x86_64.egg/torchdynamo/eval_frame.py", line 517, in export
    matched_output_elements_positions = produce_matching(flat_both, flat_results_traced)
  File "/usr/lib/python3.8/site-packages/torchdynamo-1.13.0.dev0-py3.8-linux-x86_64.egg/torchdynamo/eval_frame.py", line 464, in produce_matching
    assert (
AssertionError: Dynamo input and output is a strict subset of traced input/output
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Repro
```python
import torch
def f(x: torch.Tensor):
    return x.numel()

torch._dynamo.config.capture_scalar_outputs = True
out =  torch.compile(f, backend="eager", fullgraph=True)(torch.randn(10))
```
Issue is fixed.
