### ISSUE TITLE
AotAutograd - Leaf Variable inplace operation issue

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#93682]
~~~
import torch
import functorch.compile
from functorch.compile import aot_function, nop
functorch.compile.config.debug_graphs = True
def fn(param, y):
    prev_grad = torch.is_grad_enabled()
    try:
        torch.set_grad_enabled(False)
        param.add_(y)
    finally:
        torch.set_grad_enabled(prev_grad)
    return y

y = torch.randn(4)
x = torch.nn.Parameter(torch.randn(4))
fn(x, y)


opt_fn = aot_function(fn, nop)
opt_fn(x, y)
~~~

@yanboliang observed this while running optimizer with inductor. I expected this to fail for `aot_eager` as well, but then found that we skip it in `aot_eager` because of this logic

https://github.com/pytorch/torchdynamo/blob/31d2f67bc5e0b471cb04be1b58032ea56e43c460/torchdynamo/optimizations/training.py#L63-L80

Error

~~~
Traceback (most recent call last):
  File "/scratch/anijain/work/torchdynamo/failures/o.py", line 22, in <module>
    opt_fn(x, y)
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 766, in returned_function
    compiled_fn = create_aot_dispatcher_function(
  File "/scratch/anijain/work/torchdynamo/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 500, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/scratch/anijain/work/pytorch/functorch/_src/aot_autograd.py", line 372, in aot_dispatch_autograd
    fx_g = make_fx(functionalize(fake_fn), aot_config.decompositions)(*joint_inputs)
  File "/scratch/anijain/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 634, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/scratch/anijain/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 397, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/scratch/anijain/work/pytorch/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/scratch/anijain/work/pytorch/torch/fx/_symbolic_trace.py", line 614, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/scratch/anijain/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 411, in wrapped
    out = f(*tensors)
  File "/scratch/anijain/work/pytorch/functorch/_src/eager_transforms.py", line 1468, in wrapped
    _propagate_functional_input_mutation(unwrapped, wrapped)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
~~~

cc @Chillee @ezyang

**Comment by ezyang** [comment]
This got done by aotautograd v2
