### ISSUE TITLE
[User model][tracker] Improve compilation of PPO model (Stable-baselines3)

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#93697]
`pip install stable-baselines3[extra]`

## Repro

```python
from stable_baselines3 import PPO
import torchdynamo 



@torchdynamo.optimize("inductor")
def train():
    model = PPO("MlpPolicy", "CartPole-v1").learn(10_000)


import time 
tic = time.time()
train()
toc = time.time()
print(toc - tic)
```

Lots of assertion errors

## Logs

Current state of things (feel free to edit as we fix things):
https://github.com/pytorch/pytorch/issues/93697#issuecomment-1984826847

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @kadeng @amjames @Lucaskabela @jataylo @ezyang @bdhirsh @anijain2305 @chenyang78 @mruberry @rgommers @wconstab @zou3519 @aakhundov @soumith @ngimel

**Comment by ydwu4** [comment]
This appears to be a dynamo issue. Repro:
```
pip install stable-baselines3[extra]
```
and run:
```python
import time
from stable_baselines3 import PPO
import torch


def train():
    model = PPO("MlpPolicy", "CartPole-v1").learn(10_000)


tic = time.time()
torch.compile(train)()
toc = time.time()
print(toc - tic)
```
Error message:
```
Traceback (most recent call last):
  File "/home/yidi/local/pytorch/repro6.py", line 11, in <module>
    torch.compile(train)()
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/repro6.py", line 7, in train
    model = PPO("MlpPolicy", "CartPole-v1").learn(10_000)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/stable_baselines3/ppo/ppo.py", line 109, in __init__
    super().__init__(
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 85, in __init__
    super().__init__(
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 123, in __init__
    self.policy_class = self._get_policy_from_name(policy)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 168, in resume_in___init__
    env = maybe_make_env(env, self.verbose)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 60, in maybe_make_env
    env = gym.make(env_id, render_mode="rgb_array")
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/gymnasium/envs/classic_control/cartpole.py", line 111, in __init__
    np.finfo(np.float32).max,
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/gymnasium/envs/classic_control/cartpole.py", line 113, in resume_in___init__
    np.finfo(np.float32).max,
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/gymnasium/envs/classic_control/cartpole.py", line 108, in resume_in___init__
    high = np.array(
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 721, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 664, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 645, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/yidi/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2123, in run
    super().run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1213, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 652, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/user_defined.py", line 174, in call_function
    var.call_method(tx, "__init__", args, kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/user_defined.py", line 306, in call_method
    return UserMethodVariable(method, self, source=source).call_function(
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/functions.py", line 294, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/functions.py", line 248, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/functions.py", line 81, in call_function
    return tx.inline_user_function_return(
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 688, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2256, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2371, in inline_call_
    tracer.run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1213, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 652, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/misc.py", line 995, in call_function
    *proxy_args_kwargs(args, kwargs),
  File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 555, in proxy_args_kwargs
    proxy_args = tuple(arg.as_proxy() for arg in args)
  File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 555, in <genexpr>
    proxy_args = tuple(arg.as_proxy() for arg in args)
  File "/home/yidi/local/pytorch/torch/_dynamo/variables/misc.py", line 1022, in as_proxy
    tnp_dtype = tnp.dtype(attr)
  File "/home/yidi/local/pytorch/torch/_numpy/_dtypes.py", line 241, in dtype
    return DType(arg)
  File "/home/yidi/local/pytorch/torch/_numpy/_dtypes.py", line 261, in __init__
    sctype = sctype_from_string(arg)
  File "/home/yidi/local/pytorch/torch/_numpy/_dtypes.py", line 228, in sctype_from_string
    raise TypeError(f"data type {s!r} not understood")
torch._dynamo.exc.InternalTorchDynamoError: data type 'integer' not understood

from user code:
   File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/gymnasium/envs/classic_control/cartpole.py", line 118, in resume_in___init__
    self.action_space = spaces.Discrete(2)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/gymnasium/spaces/discrete.py", line 41, in __init__
    assert np.issubdtype(

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by ezyang** [comment]
This seems to be torch._numpy related, cc'ing @lezcano

**Comment by lezcano** [comment]
After the stack starting at https://github.com/pytorch/pytorch/pull/116459, the new error is having quite a few of
```
[ERROR] Name: "L['self']"
[ERROR]     Source: local
[ERROR]     Create Function: NN_MODULE
[ERROR]     Guard Types: ['ID_MATCH']
[ERROR]     Code List: ["___check_obj_id(L['self'], 139962171127504)"]
[ERROR]     Object Weakref: <weakref at 0x7f4b72f7c9a0; to
'ActorCriticPolicy' at 0x7f4b7b7df6d0>
[ERROR]     Guarded Class Weakref: <weakref at 0x7f4afbd08b30; to
'ABCMeta' at 0x56463a727840 (ActorCriticPolicy)>
[ERROR] Created at:
[ERROR]   File
"/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builder.py",
line 248, in __call__
[ERROR]     vt = self._wrap(value)
[ERROR]   File
"/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builder.py",
line 474, in _wrap
[ERROR]     return self.wrap_module(value)
[ERROR]   File
"/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builder.py",
line 941, in wrap_module
[ERROR]     return self.tx.output.register_attr_or_module(
[ERROR]   File
"/home/lezcano/git/pytorch/pytorch/torch/_dynamo/output_graph.py", line
735, in register_attr_or_module
[ERROR]     install_guard(source.make_guard(GuardBuilder.NN_MODULE))
[ERROR] Error while creating guard:
```
although the compilation seems to continue after these errors

**Comment by anijain2305** [comment]
@lezcano - seems like your latest dict refactor stack can fix this issue?

**Comment by lezcano** [comment]
Not quite. There is still this error that needs investigation: https://github.com/pytorch/pytorch/issues/93697#issuecomment-1870399452

I'll look into it.

**Comment by bhack** [comment]
I have just the same https://github.com/pytorch/pytorch/issues/93697#issuecomment-1870399452 error with the last nightly

**Comment by bhack** [comment]
Can you give a pointer or it will be hard to evaluate what it is requried?

**Comment by lezcano** [comment]
I really don't know much about the error. I would start by dropping a breakpoint where the error is raised, see if it's obvious what's failing. If not, since these are guards, guards are installed lazily. I would put a breakpoint in the constructor of the relevant guard, see where it was created. With all that, it should hopefully be possible to figure out what's going on.

btw, what's printed in the error regarding "     Create Function: NN_MODULE" may be a red herring. I think I have seen that error before in things that are completely unrelated to nn modules. It may be coming from us printing the wrong part of the trace.

**Comment by bhack** [comment]
> I think I have seen that error before in things that are completely unrelated to nn modules

This could be a problem as this could be not my case but just a generic unrelated error.

**Comment by lezcano** [comment]
So, I had a look at the guard emission errors, and they all were of the form:
```
torch._dynamo.exc.Unsupported: Guard setup for uninitialized class <class 'stable_baselines3.common.policies.ActorCriticPolicy'> 
```
for 3-4 different classes. I haven't dug up more into what's going on.

Other than that, there are quite a few DeviceCopies, and there's
```
W0308 00:01:48.281659 140655978846016 torch/_dynamo/convert_frame.py:357]    function: 'torch_dynamo_resume_in_step_at_139' (/home/lezcano/.conda/envs/pytorch-dev/lib/python3.8/site-packages/gymnasium/envs/classic_control/cartpole.py:139)
W0308 00:01:48.281659 140655978846016 torch/_dynamo/convert_frame.py:357]    last reason: L['___stack0'] == 0.9998404669789352  
```
which looks like a variable that's changing and we fail to capture symbolically.

Then, 5 min in, there's this misterious error I had never seen:
```
Error in codegen for ComputedBuffer(name='buf2', layout=FixedLayout('cpu', torch.float32, size=[64, 1], stride=[1, 64]), data=Pointwise(
  'cpu',
  torch.float32,
  def inner_fn(index):
      i0, _ = index
      tmp0 = ops.load(arg1_1, i0)
      tmp1 = ops.load(arg2_1, (tmp0))
      return tmp1
  ,
  ranges=[64, 1],
  origin_node=index_1,
  origins={index_1}
))
```

But other than that, the compilation finishes in 5 min. There is a decent number of graphbreaks related to numpy things that are easy to fix. We also graphbreak on `self.train(mode)` where `self` is an `nn.Module`. Then there are plenty of DataDependentOutput exceptions. Grinding through all these would be a great onboarding task.

That being said, what do we want to do with this issue? cc @anijain2305 @ezyang @yanboliang @msaroufim

**Comment by ezyang** [comment]
If you have an abundance of time on your hand, filing individual issues (with repros, if it would be helpful) for each of the distinct issues is the best way to feed it into the overall bug fixing machine. Otherwise, I suppose we can rename this issue to just be a tracking issue for compilation of the model in question.

**Comment by lezcano** [comment]
Edited the OP. Might use this one to onboard someone internally into dynamo.

**Comment by williamwen42** [comment]
Closing as the compilation issues tracked here have been resolved. torch.compile works cleanly on the PPO model with no graph breaks.
