### ISSUE TITLE
retro inductor OOM

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#93699]
## Repro
Another lucidrains model

` pip install retro-pytorch`

```python
import torch
from retro_pytorch import RETRO
import torchdynamo

retro = RETRO(
    chunk_size = 64,                         # the chunk size that is indexed and retrieved (needed for proper relative positions as well as causal chunked cross attention)
    max_seq_len = 2048,                      # max sequence length
    enc_dim = 896,                           # encoder model dim
    enc_depth = 2,                           # encoder depth
    dec_dim = 796,                           # decoder model dim
    dec_depth = 12,                          # decoder depth
    dec_cross_attn_layers = (3, 6, 9, 12),   # decoder cross attention layers (with causal chunk cross attention)
    heads = 8,                               # attention heads
    dim_head = 64,                           # dimension per head
    dec_attn_dropout = 0.25,                 # decoder attention dropout
    dec_ff_dropout = 0.25,                   # decoder feedforward dropout
    use_deepnet = True                       # turn on post-normalization with DeepNet residual scaling and initialization, for scaling to 1000 layers
).cuda()


seq = torch.randint(0, 20000, (2, 2048 + 1)).cuda()      # plus one since it is split into input and labels for training
retrieved = torch.randint(0, 20000, (2, 32, 2, 128)).cuda() # retrieved tokens - (batch, num chunks, num retrieved neighbors, retrieved chunk with continuation)

@torchdynamo.optimize("inductor")
def train():
    loss = retro(seq, retrieved, return_loss = True)
    loss.backward()

train()
```

## Logs

```
(dynamo) ubuntu@ip-172-31-31-152:~/tests$ python retro.py 
torchdynamo.symbolic_convert: [WARNING] Graph break: missing: BUILD_MAP_UNPACK_WITH_CALL from user code at   File "retro.py", line 26, in train
    loss = retro(seq, retrieved, return_loss = True)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 618, in forward
    pos_emb = rearrange(pos_emb, 'n d -> 1 n d')
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/einops/einops.py", line 487, in rearrange
    return reduce(tensor, pattern, reduction='rearrange', **axes_lengths)

torchdynamo.symbolic_convert: [WARNING] Graph break: call_method ConstDictVariable() __contains__ [GetAttrVariable(UserDefinedClassVariable(), framework_name)] {} from user code at   File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/einops/einops.py", line 231, in _apply_recipe
    backend = get_backend(tensor)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/einops/_backends.py", line 42, in get_backend
    if BackendSubclass.framework_name not in _backends:

torchdynamo.symbolic_convert: [WARNING] Graph break: call_function UserDefinedObjectVariable(_lru_cache_wrapper) [UserDefinedObjectVariable(TransformRecipe), ShapeVariable()] {} from user code at   File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/einops/einops.py", line 233, in <graph break in _apply_recipe>
    _reconstruct_from_shape(recipe, backend.shape(tensor))

torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
torchinductor.lowering: [WARNING] using triton random, expect difference from eager
torchinductor.lowering: [WARNING] using triton random, expect difference from eager
torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
torchdynamo.symbolic_convert: [WARNING] Graph break: missing: BUILD_MAP_UNPACK_WITH_CALL from user code at   File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 87, in forward
    out = self.fn(x, *args, **kwargs) + residual
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 276, in forward
    k_pos_emb = repeat(k_pos_emb, 'b h n d -> b h (r n) d', r = num_retrieved)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/einops/einops.py", line 537, in repeat
    return reduce(tensor, pattern, reduction='repeat', **axes_lengths)

torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
torchinductor.compile_fx: [WARNING] skipping cudagraphs due to complex input striding
torchinductor.lowering: [WARNING] using triton random, expect difference from eager
torchinductor.lowering: [WARNING] using triton random, expect difference from eager
torchinductor.lowering: [WARNING] using triton random, expect difference from eager
torchinductor.lowering: [WARNING] using triton random, expect difference from eager
torchinductor.lowering: [WARNING] using triton random, expect difference from eager
torchinductor.lowering: [WARNING] using triton random, expect difference from eager
torchinductor.lowering: [WARNING] using triton random, expect difference from eager
Traceback (most recent call last):
  File "retro.py", line 29, in <module>
    train()
  File "/home/ubuntu/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "retro.py", line 24, in train
    @torchdynamo.optimize("inductor")
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 564, in forward
    def forward(
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 618, in <graph break in forward>
    pos_emb = rearrange(pos_emb, 'n d -> 1 n d')
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 627, in <graph break in forward>
    encoder_retrieved_mask = rearrange(mask, 'b k r n -> (b k r) n')
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 404, in forward
    def forward(self, x, *, encoder = None, encoder_retrieved_mask = None, context_mask = None, retrieved = None):
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 406, in <graph break in forward>
    self_attn_pos_emb = self.rotary_pos_emb(seq_len, device = device)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 418, in <graph break in forward>
    cross_attn_q_pos_emb = self.rotary_pos_emb(self.chunk_size, device = device, offset = self.chunk_size - 1)  # need to add extra chunk size, since it will be shifted
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 430, in <graph break in forward>
    x = attn(x, pos_emb = self_attn_pos_emb)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/retro_pytorch/retro_pytorch.py", line 85, in forward
    def forward(self, x, *args, **kwargs):
  File "/home/ubuntu/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 904, in forward
    return compiled_f(
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 895, in new_func
    return compiled_fn(args)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 228, in g
    return f(*args)
  File "/home/ubuntu/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 354, in forward
    fw_outs = call_func_with_args(
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 250, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 228, in g
    return f(*args)
  File "/home/ubuntu/torchdynamo/torchinductor/compile_fx.py", line 125, in run
    compiled_fn = cudagraphify_impl(model, new_inputs, static_input_idxs)
  File "/home/ubuntu/torchdynamo/torchinductor/compile_fx.py", line 150, in cudagraphify_impl
    static_inputs = [
  File "/home/ubuntu/torchdynamo/torchinductor/compile_fx.py", line 151, in <listcomp>
    static_input(x) if idx not in static_input_idxs else inputs[idx]
  File "/home/ubuntu/torchdynamo/torchinductor/compile_fx.py", line 143, in static_input
    buffer = torch.zeros(needed_size, dtype=x.dtype, device=x.device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 15.78 GiB total capacity; 13.71 GiB already allocated; 11.94 MiB free; 14.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

cc @ezyang @wconstab @bdhirsh @anijain2305 @zou3519 @soumith @ngimel

**Comment by ydwu4** [comment]
Repro:
```
 pip install retro-pytorch
```

```python
import torch
from retro_pytorch import RETRO

retro = RETRO(
    chunk_size = 64,                         # the chunk size that is indexed and retrieved (needed for proper relative positions as well as causal chunked cross attention)
    max_seq_len = 2048,                      # max sequence length
    enc_dim = 896,                           # encoder model dim
    enc_depth = 2,                           # encoder depth
    dec_dim = 796,                           # decoder model dim
    dec_depth = 12,                          # decoder depth
    dec_cross_attn_layers = (3, 6, 9, 12),   # decoder cross attention layers (with causal chunk cross attention)
    heads = 8,                               # attention heads
    dim_head = 64,                           # dimension per head
    dec_attn_dropout = 0.25,                 # decoder attention dropout
    dec_ff_dropout = 0.25,                   # decoder feedforward dropout
    use_deepnet = True                       # turn on post-normalization with DeepNet residual scaling and initialization, for scaling to 1000 layers
).cuda()


seq = torch.randint(0, 20000, (2, 2048 + 1)).cuda()      # plus one since it is split into input and labels for training
retrieved = torch.randint(0, 20000, (2, 32, 2, 128)).cuda() # retrieved tokens - (batch, num chunks, num retrieved neighbors, retrieved chunk with continuation)

def train():
    loss = retro(seq, retrieved, return_loss = True)
    loss.backward()

torch.compile(train)()
```

The error log:
```
home/yidi/local/pytorch/torch/_inductor/compile_fx.py:140: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
/home/yidi/local/pytorch/torch/autograd/__init__.py:411: UserWarning: Error detected in ViewBackward0. Traceback of forward call that caused the error:
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/retro_pytorch/retro_pytorch.py", line 87, in forward
    out = self.fn(x, *args, **kwargs) + residual
  File "/home/yidi/local/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/retro_pytorch/retro_pytorch.py", line 289, in forward
    out = self.cross_attn(x, context = context, mask = context_mask, pos_emb = pos_emb)
  File "/home/yidi/local/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/retro_pytorch/retro_pytorch.py", line 225, in forward
    out = einsum('b h i j, b h j d -> b h i d', attn, v)
 (Triggered internally at /home/yidi/local/pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:113.)
  result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/home/yidi/local/pytorch/repro6.py", line 27, in <module>
    torch.compile(train)()
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/repro6.py", line 24, in train
    loss = retro(seq, retrieved, return_loss = True)
  File "/home/yidi/local/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/retro_pytorch/retro_pytorch.py", line 638, in forward
    embed = self.decoder(
  File "/home/yidi/local/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/site-packages/retro_pytorch/retro_pytorch.py", line 441, in forward
    x = cross_attn(
  File "/home/yidi/local/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 721, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 645, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/yidi/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2123, in run
    super().run()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2238, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/yidi/local/pytorch/torch/_dynamo/output_graph.py", line 912, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/yidi/local/miniconda3/envs/repro/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/yidi/local/pytorch/torch/_dynamo/output_graph.py", line 1080, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/output_graph.py", line 1152, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/yidi/local/pytorch/torch/_dynamo/output_graph.py", line 1133, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/yidi/local/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/yidi/local/pytorch/torch/__init__.py", line 1657, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/yidi/local/pytorch/torch/_inductor/compile_fx.py", line 1168, in compile_fx
    return aot_autograd(
  File "/home/yidi/local/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 4938, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 4478, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 2813, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 2999, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 3700, in aot_dispatch_autograd
    fx_g, joint_inputs, maybe_subclass_meta = aot_dispatch_autograd_graph(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 3680, in aot_dispatch_autograd_graph
    fx_g = create_graph(joint_fn_to_trace, updated_joint_inputs, aot_config=aot_config)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 1943, in create_graph
    fx_g = make_fx(f, decomposition_table=aot_config.decompositions)(*args)
  File "/home/yidi/local/pytorch/torch/fx/experimental/proxy_tensor.py", line 869, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/home/yidi/local/pytorch/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/fx/experimental/proxy_tensor.py", line 481, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/home/yidi/local/pytorch/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/fx/_symbolic_trace.py", line 821, in trace
    (self.create_arg(fn(*args)),),
  File "/home/yidi/local/pytorch/torch/fx/_symbolic_trace.py", line 688, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/home/yidi/local/pytorch/torch/fx/experimental/proxy_tensor.py", line 517, in wrapped
    out = f(*tensors)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 1929, in joint_helper
    return functionalized_f_helper(primals, tangents)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 1882, in functionalized_f_helper
    f_outs = fn(*f_args)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 1850, in inner_fn_with_anomaly
    return inner_fn(*args)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 1833, in inner_fn
    backward_out = torch.autograd.grad(
  File "/home/yidi/local/pytorch/torch/autograd/__init__.py", line 411, in grad
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/yidi/local/pytorch/torch/_subclasses/functional_tensor.py", line 297, in __torch_dispatch__
    outs_unwrapped = func(*args_unwrapped, **kwargs_unwrapped)
  File "/home/yidi/local/pytorch/torch/_ops.py", line 509, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/yidi/local/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/fx/experimental/proxy_tensor.py", line 594, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/home/yidi/local/pytorch/torch/fx/experimental/proxy_tensor.py", line 629, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_dispatch, args, kwargs)
  File "/home/yidi/local/pytorch/torch/fx/experimental/proxy_tensor.py", line 374, in proxy_call
    out = func(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_ops.py", line 509, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/yidi/local/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_subclasses/fake_tensor.py", line 1392, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/yidi/local/pytorch/torch/_subclasses/fake_tensor.py", line 1604, in dispatch
    return decomposition_table[func](*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_refs/__init__.py", line 4427, in view
    return _reshape_view_helper(a, *shape, allow_copy=False)
  File "/home/yidi/local/pytorch/torch/_refs/__init__.py", line 3616, in _reshape_view_helper
    if length == a_.shape[idx]:
  File "/home/yidi/local/pytorch/torch/__init__.py", line 365, in __bool__
    return self.node.bool_()
  File "/home/yidi/local/pytorch/torch/fx/experimental/sym_node.py", line 392, in bool_
    return self.guard_bool("", 0)
  File "/home/yidi/local/pytorch/torch/fx/experimental/sym_node.py", line 358, in guard_bool
    r = self.shape_env.evaluate_expr(self.expr, self.hint, fx_node=self.fx_node)
  File "/home/yidi/local/pytorch/torch/fx/experimental/recording.py", line 226, in wrapper
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/fx/experimental/symbolic_shapes.py", line 3521, in evaluate_expr
    assert static_expr == hint, f"{static_expr} != {hint}"
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: False != True

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```
Looking at the stack trace, it appears to be a inductor/aot_autograd issue.

**Comment by bdhirsh** [comment]
This no longer repros for me - closing (feel free to re-open if you still see issues)

**Comment by zou3519** [comment]
@bdhirsh did you try with a GPU with 16gb of memory? (If the model works in eager-mode pytorch with that much memory, but OOMs with torch.compile, then that's probably not good).

**Comment by bdhirsh** [comment]
That is a good point - no, I was repro'ing on my 40gb A100.

I'll tentatively re-open (although I don't have a 16gb GPU)
