### ISSUE TITLE
MLP mixer functorch error

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#93700]
## Repro

Yet another lucidrains model

`pip install mlp-mixer-pytorch`

```python
import torch
from mlp_mixer_pytorch import MLPMixer
import torchdynamo

model = MLPMixer(
    image_size = 256,
    channels = 3,
    patch_size = 16,
    dim = 512,
    depth = 12,
    num_classes = 1000
).cuda()

img = torch.randn(1, 3, 256, 256).cuda()

@torchdynamo.optimize("inductor")
def pred():
    pred = model(img) # (1, 1000)

pred()

```

## Logs

```
(dynamo) ubuntu@ip-172-31-31-152:~/tests$ python mixer.py 
Traceback (most recent call last):
  File "mixer.py", line 20, in <module>
    pred()
  File "/home/ubuntu/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "mixer.py", line 16, in pred
    @torchdynamo.optimize("inductor")
  File "/home/ubuntu/torchdynamo/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 904, in forward
    return compiled_f(
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 890, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/home/ubuntu/torchdynamo/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 465, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 327, in aot_dispatch_autograd
    fw_module, bw_module = aot_config.partition_fn(fx_g, joint_inputs)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/functorch/_src/partitioners.py", line 396, in min_cut_rematerialization_partition
    cut_value, partition = nx.minimum_cut(nx_graph, "source", "sink")
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/networkx/algorithms/flow/maxflow.py", line 458, in minimum_cut
    R = flow_func(flowG, _s, _t, capacity=capacity, value_only=True, **kwargs)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 421, in preflow_push
    R = preflow_push_impl(G, s, t, capacity, residual, global_relabel_freq, value_only)
  File "/opt/conda/envs/dynamo/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 27, in preflow_push_impl
    raise nx.NetworkXError(f"node {str(t)} not in graph")
networkx.exception.NetworkXError: node sink not in graph
```

cc @ezyang @soumith @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
Actually i bet this will be fixed when we turn on inference functionalization @bdhirsh

**Comment by ngimel** [comment]
Closing, inference functionalization is turned on, reopen if still an issue
