### ISSUE TITLE
[fake tensor][aot_nvfuser] non-fake and fake tensor together

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#93711]
Repro

This is for `aot_nvfuser` backend, so something special might be happening with Aot Autograd `ts_compile`. But, lets ensure that its not FakeTensor issue.

~~~
from math import inf
import torch
from torch import tensor, device
import torch.fx as fx
import torchdynamo
from torchdynamo.testing import rand_strided
from torchdynamo.debug_utils import run_fwd_maybe_bwd
from torchdynamo.debug_utils import same_two_models

args = [((2, 1024), (1024, 1), torch.int64, 'cuda', False), ((2, 1024, 768), (786432, 768, 1), torch.float32, 'cuda', True)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.self_self_embeddings_word_embeddings = Embedding(50358, 768, padding_idx=0)



    def forward(self, input_ids : torch.Tensor, self_self_embeddings_layer_norm):
        ones = torch.ones((2, 1024), device = device(type='cuda', index=0))
        view = ones.view(2, 16, 64);  ones = None
        self_self_embeddings_word_embeddings = self.self_self_embeddings_word_embeddings(input_ids);  input_ids = None
        return [self_self_embeddings_layer_norm, view]



mod = Repro().cuda()
opt_mod = torchdynamo.optimize("aot_nvfuser")(mod)


with torch.cuda.amp.autocast(enabled=False):
    ref = run_fwd_maybe_bwd(mod, args)
    res = run_fwd_maybe_bwd(opt_mod, args)

~~~

Error
~~~
Traceback (most recent call last):
  File "/tmp/anijain/6.py", line 37, in <module>
    res = run_fwd_maybe_bwd(opt_mod, args)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/debug_utils.py", line 475, in run_fwd_maybe_bwd
    loss = reduce_to_scalar_loss(out)
  File "/scratch/anijain/work/torchdynamo/torchdynamo/testing.py", line 86, in reduce_to_scalar_loss
    return sum([reduce_to_scalar_loss(x) for x in out]) / len(out)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 525, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/_ops.py", line 257, in __call__
    return self._op(*args, **kwargs or {})
  File "/scratch/anijain/work/pytorch/torch/utils/_python_dispatch.py", line 101, in __torch_dispatch__
    return old.__torch_dispatch__(func, types, args, kwargs)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 682, in __torch_dispatch__
    raise Exception(
Exception: Invoking operators with non-Fake Tensor inputs in FakeTensorMode is not yet supported. Please convert all Tensors to FakeTensors first. Found in aten.add.Tensor(*(tensor(-0.0005, device='cuda:0', grad_fn=<AddBackward0>), FakeTensor(FakeTensor(..., device='meta', size=(), grad_fn=<DivBackward0>), cuda:0)), **{})
~~~

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
closing this as obsolete
