### ISSUE TITLE
Hitting AssertionError from autocast query with torchdynamo: `AssertionError: torch.* op returned non-Tensor bool call_function <built-in function is_autocast_enabled>`

### ISSUE THREAD

**Issue by jjsjann123** [pytorch/pytorch#93713]
Don't know how to describe the error precisely, here's the issue I'm running into.
Luckily enough, this AssertionError doesn't break the benchmark run. But an AssertionError sounds scary enough to bring this up as a github issue.

```
root@56d364f47b61:/opt/pytorch/torchdynamo# python benchmarks/huggingface.py --training -d cuda --fast --backend aot_eager --skip-accuracy-check --performance  --generate-aot-autograd-stats --dump-raw-metrics --
float32 -k T5ForConditionalGeneration
WARNING:__main__:Running smaller batch size=2 for MT5ForConditionalGeneration, orig batch_size=8
WARNING:__main__:Sequence Length not defined for MT5ForConditionalGeneration. Choosing 128 arbitrarily
torchdynamo.testing: [WARNING] High loss value alert - 109.45. Can result in unstable gradients.
cuda train MT5ForConditionalGeneration        torchdynamo.testing: [WARNING] High loss value alert - 109.30. Can result in unstable gradients.
torchdynamo.testing: [WARNING] High loss value alert - 106.99. Can result in unstable gradients.
torchdynamo.testing: [WARNING] High loss value alert - 108.87. Can result in unstable gradients.
torchdynamo.testing: [WARNING] High loss value alert - 109.26. Can result in unstable gradients.
torchdynamo.testing: [WARNING] High loss value alert - 108.38. Can result in unstable gradients.
torchdynamo.symbolic_convert: [WARNING] Graph break: call_function in skip_files /opt/pytorch/torchdynamo/torchdynamo/utils.py from user code at   File "benchmarks/huggingface.py", line 439, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)

torchdynamo.symbolic_convert: [WARNING] Graph break: call_method NNModuleVariable() zero_grad [ConstantVariable(bool)] {} from user code at   File "benchmarks/huggingface.py", line 440, in <graph break in forward_and_backward_pass>
    mod.zero_grad(True)

torchdynamo.convert_frame: [ERROR] WON'T CONVERT forward /opt/conda/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py line 1537
due to:
Traceback (most recent call last):
  File "/opt/pytorch/torchdynamo/torchdynamo/variables/tensor.py", line 271, in create
    assert (
AssertionError: torch.* op returned non-Tensor bool call_function <built-in function is_autocast_enabled>

from user code:
   File "/opt/conda/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1601, in forward
    encoder_outputs = self.encoder(

Set torchdynamo.config.verbose=True for more information
==========

```

I'm using torchdynamo commit:
```
commit 0c96ddbad26216671861762c161ebcfb0fdbeb9f (HEAD)
Author: Natalia Gimelshein <ngimel@fb.com>
Date:   Tue Oct 4 16:57:40 2022 -0700

    use simple codegen for where (#1470)
    
    * use simple codegen for where
    
    * disable simple where for now
    
    * another try
```

With pytorch commit:
```
Date:   Wed Oct 5 21:06:01 2022 -0700

    Delete torch::deploy from pytorch core (#85953)
    
    As we have migrated torch::deploy over to https://github.com/pytorch/multipy, we can now delete it from pytorch core as ongoing development will happen there.
    
    This PR was created due to syncing issues with https://github.com/pytorch/pytorch/pull/85443 which is where the review history can be found.
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/85953
    Approved by: https://github.com/seemethere, https://github.com/malfet

```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
passes now

```
$ python benchmarks/dynamo/huggingface.py --training -d cuda  --backend aot_eager  --performance   --only T5ForConditionalGeneration --float32
WARNING:__main__:Running smaller batch size=4 for T5ForConditionalGeneration, orig batch_size=8
cuda train T5ForConditionalGeneration          0.843x p=0.00
```
