### ISSUE TITLE
Support capturing code in exception handlers

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93720]
Today, everything after an exception won't be captured by TorchDynamo:
```
try:
   x = x + 1  # should be captured fine
   assert False
except:
   x = x + 2  # won't be captured
   return x
```

To add support for this there are two main cases:
1) Both the `raise` and the `except` are in the same capture context.  In this case TorchDynamo can remove the `raise` and combine the above example into a single graph.  Logically the raise becomes a jump.
2) The raise/except is in a different capture contexts.  In this case we need to actually throw the exception.  To handle this case we need extend our [resume_execution](https://github.com/facebookresearch/torchdynamo/blob/052b8dab6df5f027a34edb00dee73870433883d5/torchdynamo/resume_execution.py) codegen to put the exception handler in a new python function/frame.  This allows dynamo to capture the body of the except as if it were defined in a function.  I started implementing this, but never finished it.

Handling the first case seems more useful, but eventually we need to handle both.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel

**Comment by ydwu4** [comment]
Repro:
```python
import torch

def test_capture(x):
    try:
       x = x + 1  # should be captured fine
       assert False
    except:
       x = x + 2  # won't be captured
       return x

torch.compile(test_capture, backend="eager", fullgraph=False)(torch.rand(10))
```
Produces following log, which shows no graph is captured (ideally this should create a single graph).
```
(pytorch-3.10) ~/local/pytorch$ TORCH_LOGS="+dynamo" python repro6.py 
[2023-11-20 15:58:52,975] torch._dynamo.eval_frame: [DEBUG] Saving dynamo config and hash for new compiled object(s). Hash: 3fb534e6212b0f66ef1729df61d25764
[2023-11-20 15:58:52,981] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* _splitext             /home/yidi/local/miniconda3/envs/pytorch-3.10/lib/python3.10/genericpath.py 121
[2023-11-20 15:58:52,981] torch._dynamo.eval_frame: [DEBUG] Setting top-level compile config hash: 3fb534e6212b0f66ef1729df61d25764
[2023-11-20 15:58:52,984] [0/0] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing test_capture /home/yidi/local/pytorch/repro6.py:3
[2023-11-20 15:58:52,984] [0/0] torch.fx.experimental.symbolic_shapes: [INFO] create_env
[2023-11-20 15:58:52,987] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line /home/yidi/local/pytorch/repro6.py:3 in test_capture (test_capture)
[2023-11-20 15:58:52,987] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]     def test_capture(x):
[2023-11-20 15:58:52,987] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line /home/yidi/local/pytorch/repro6.py:4 in test_capture (test_capture)
[2023-11-20 15:58:52,987] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]         try:
[2023-11-20 15:58:52,987] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE SETUP_FINALLY 14 []
[2023-11-20 15:58:52,987] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line /home/yidi/local/pytorch/repro6.py:5 in test_capture (test_capture)
[2023-11-20 15:58:52,987] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]            x = x + 1  # should be captured fine
[2023-11-20 15:58:52,987] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST x []
[2023-11-20 15:58:52,987] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST 1 [LazyVariableTracker()]
[2023-11-20 15:58:52,987] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE BINARY_ADD None [LazyVariableTracker(), ConstantVariable(int)]
[2023-11-20 15:58:52,988] [0/0] torch._dynamo.output_graph: [DEBUG] create_graph_input L_x_ L['x']
[2023-11-20 15:58:52,988] [0/0] torch._dynamo.variables.builder: [DEBUG] wrap_to_fake L['x'] (10,) [<DimDynamic.STATIC: 2>] [None]
[2023-11-20 15:58:52,992] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST x [TensorVariable()]
[2023-11-20 15:58:52,992] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line /home/yidi/local/pytorch/repro6.py:6 in test_capture (test_capture)
[2023-11-20 15:58:52,992] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]            assert False
[2023-11-20 15:58:52,992] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ASSERTION_ERROR None []
[2023-11-20 15:58:52,992] [0/0] torch._dynamo.symbolic_convert: [DEBUG] empty checkpoint
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] WON'T CONVERT test_capture /home/yidi/local/pytorch/repro6.py line 3 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] due to: 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] Traceback (most recent call last):
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 721, in _convert_frame
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     result = inner_convert(frame, cache_entry, hooks, frame_state)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     compiled_product = _compile(
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 645, in _compile
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     guarded_code = compile_inner(code, one_graph, hooks, transform)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     r = func(*args, **kwargs)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 562, in compile_inner
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     out_code = transform_code_object(code, transform)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     transformations(instructions, code_options)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     return fn(*args, **kwargs)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 527, in transform
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     tracer.run()
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2123, in run
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     super().run()
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 818, in run
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     and self.step()
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in step
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     getattr(self, inst.opname)(inst)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1715, in LOAD_ASSERTION_ERROR
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     unimplemented("assert with non-string message")
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/exc.py", line 193, in unimplemented
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     raise Unsupported(msg)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] torch._dynamo.exc.Unsupported: assert with non-string message
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] from user code:
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]    File "/home/yidi/local/pytorch/repro6.py", line 6, in test_capture
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     assert False
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] You can suppress this exception and fall back to eager by setting:
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     import torch._dynamo
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     torch._dynamo.config.suppress_errors = True
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] Traceback (most recent call last):
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 721, in _convert_frame
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     result = inner_convert(frame, cache_entry, hooks, frame_state)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     compiled_product = _compile(
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 645, in _compile
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     guarded_code = compile_inner(code, one_graph, hooks, transform)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     r = func(*args, **kwargs)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 562, in compile_inner
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     out_code = transform_code_object(code, transform)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     transformations(instructions, code_options)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     return fn(*args, **kwargs)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/convert_frame.py", line 527, in transform
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     tracer.run()
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 2123, in run
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     super().run()
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 818, in run
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     and self.step()
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in step
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     getattr(self, inst.opname)(inst)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/symbolic_convert.py", line 1715, in LOAD_ASSERTION_ERROR
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     unimplemented("assert with non-string message")
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]   File "/home/yidi/local/pytorch/torch/_dynamo/exc.py", line 193, in unimplemented
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     raise Unsupported(msg)
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] torch._dynamo.exc.Unsupported: assert with non-string message
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] from user code:
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]    File "/home/yidi/local/pytorch/repro6.py", line 6, in test_capture
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     assert False
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] 
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] You can suppress this exception and fall back to eager by setting:
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     import torch._dynamo
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO]     torch._dynamo.config.suppress_errors = True
[2023-11-20 15:58:52,993] torch._dynamo.convert_frame: [INFO] 
[2023-11-20 15:58:52,994] torch._dynamo.eval_frame: [DEBUG] Unsetting top-level compile config hash: 3fb534e6212b0f66ef1729df61d25764
[2023-11-20 15:58:52,994] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[2023-11-20 15:58:52,994] torch._dynamo.utils: [INFO] Function, Runtimes (s)
[2023-11-20 15:58:52,994] torch._dynamo.utils: [INFO] _compile.<locals>.compile_inner, 0.0000
```

**Comment by anijain2305** [comment]
We have fixed the first bullet. Closing this for now. If we see the need for second case, we will open a new issue.
