### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93781]
I wanted to make it easier to unconditionally turn on torchdynamo when testing random scripts, so I added this to my `torch/__init__.py`

```
    import torchdynamo
    torchdynamo.config.cache_size_limit = 1
    _DYNAMO_CTX = torchdynamo.optimize("eager")
    _DYNAMO_CTX.__enter__()
```

When I run `test/test_torch.py` with this, I get some odd errors at initialization:

```
Exception ignored in: <generator object <genexpr> at 0x7f8ce3d2f4a0>                                 
Traceback (most recent call last):                                                                                             
  File "/scratch/ezyang/pytorch-scratch2-env/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing/results.py", line 8, i
n <genexpr>                                                                                                                    
    _generator_type = type((_ for _ in ()))                                                                                    
SystemError: error return without exception set                                                                                
Exception ignored in: <generator object <genexpr> at 0x7f8ce374e510>                                                
Traceback (most recent call last):                                                                                             
  File "/scratch/ezyang/pytorch-scratch2-env/lib/python3.8/site-packages/setuptools/_vendor/pyparsing/results.py", line 8, in <
genexpr>                                                                                                                       
    _generator_type = type((_ for _ in ()))    
```

The script seems to continue to run, so this doesn't seem too damaging, but it would be nice to work out what is causing this problem.

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by gchanan** [comment]
Minimal repro:

```
import torch

@torch.compile
def f():
    _generator_type = type((_ for _ in ()))

f()
```

**Comment by jansel** [comment]
I think this has to do with dynamo's fallback to eager when no graph is generated.  This version works fine:
```
import torch

@torch.compile
def f(x):
    _generator_type = type((_ for _ in ()))
    return x+1

f(torch.randn(10))
```
