### ISSUE TITLE
torchdynamo needs to graph break for resize_ calls to AOTAutograd based backends

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93780]
Repro:

```
    def test_mutated_metadata(self):
        def model(x):
            y = x.view(0)
            x.resize_(20)
            x.fill_(2)
            y.fill_(3)

        from torchdynamo.optimizations.backends import aot_autograd
        with torchdynamo.optimize("aot_autograd"):
            for i in range(5):
                with self.subTest(i):
                    x = torch.empty(0)
                    r = model(x)
                    self.assertEqual(x, torch.full((20,), 2.))
```

Fails with

```
ERROR torchdynamo.eval_frame: error in verify_correctness
Traceback (most recent call last):
  File "/raid/ezyang/torchdynamo/torchdynamo/eval_frame.py", line 191, in __call__
    result = self.candidate(*self.example_inputs)
  File "/raid/ezyang/pytorch-scratch2/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/raid/ezyang/functorch/functorch/_src/aot_autograd.py", line 658, in forward
    return compiled_f(
  File "/raid/ezyang/torchdynamo/torchdynamo/eval_frame.py", line 97, in _fn
    return fn(*args, **kwargs)
  File "/raid/ezyang/functorch/functorch/_src/aot_autograd.py", line 207, in forward
    fw_module, bw_module = partition_fn(fx_g, joint_inputs)
  File "/raid/ezyang/functorch/functorch/_src/partitioners.py", line 363, in min_cut_rematerialization_partition
    cut_value, partition = nx.minimum_cut(nx_graph, "source", "sink")
  File "/scratch/ezyang/pytorch-scratch2-env/lib/python3.8/site-packages/networkx/algorithms/flow/maxflow.py", line 458, in minimum_cut
    R = flow_func(flowG, _s, _t, capacity=capacity, value_only=True, **kwargs)
  File "/scratch/ezyang/pytorch-scratch2-env/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 421, in preflow_push
    R = preflow_push_impl(G, s, t, capacity, residual, global_relabel_freq, value_only)
  File "/scratch/ezyang/pytorch-scratch2-env/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 27, in preflow_push_impl
    raise nx.NetworkXError(f"node {str(t)} not in graph")
networkx.exception.NetworkXError: node sink not in graph
```

Even if the partitioner handled this correctly, it's not possible to mutate the metadata of input arguments to an AOTAutograd invocation (since AOTAutograd creates copies of the tensors for the inputs). 

We could force `resize_` to unconditionally graph break but this seems bad in cases where AOTAutograd is not involved

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by gchanan** [comment]
No longer reproduces.
