### ISSUE TITLE
torchinductor fallback cannot deal op that returns tuple of list of tensors

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93798]
```

Traceback (most recent call last):
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/graph.py", line 196, in call_function
    return lowerings[target](*args, **kwargs)
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/lowering.py", line 139, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/lowering.py", line 583, in handler
    result = ir.FallbackKernel.create(kernel, *args)
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/ir.py", line 2264, in create
    return [
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/d5479947763d4841/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/ir.py", line 2268, in <listcomp>
    example_output[i].device,
AttributeError: 'list' object has no attribute 'device'
```

Triggered by fbgemm.jagged_dense_dense_elementwise_add_jagged_output.default

to repro in fbcode, check out V2 of https://www.internalfb.com/diff/D38488051

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by ydwu4** [comment]
Is this issue still relevant?
