### ISSUE TITLE
Ptx error too much parameter space from legacy_senet154

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93802]
This one might be a case where we fuse too much into a single kernel.  We should add some sort of limit the breaks kernels up if they are getting too large.

```
./benchmarks/timm_models.py -dcuda --float16 --inductor --training -k legacy_senet154
```

Output:
```
cuda train legacy_senet154                    Accuracy failed for key name layer1.0.conv1.weight.grad
INCORRECT - Variation in Eager runs itself
WARNING torchinductor.codegen.triton: 2 tiling choices: [(65536, 196), (16384, 784)]
WARNING torchinductor.codegen.triton: 2 tiling choices: [(32768, 196), (131072, 49)]
WARNING torchinductor.codegen.triton: 2 tiling choices: [(8192, 3136), (32768, 784)]
WARNING torchinductor.codegen.triton: 2 tiling choices: [(4096, 12544), (16384, 3136)]
ERROR:root:unhandled error
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 879, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "./benchmarks/timm_models.py", line 289, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/timm/models/senet.py", line 394, in forward
    def forward(self, x):
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 94, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/functorch/functorch/_src/aot_autograd.py", line 652, in forward
    return compiled_f(
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 94, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/functorch/functorch/_src/aot_autograd.py", line 212, in forward
    compiled_bw = bw_compiler(bw_module, bw_args)
  File "/home/jansel/torchdynamo/torchdynamo/optimizations/backends.py", line 542, in _wrapped_bw_compiler
    return torchdynamo.disable(bw_compiler(*args, **kwargs))
  File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 264, in bw_compiler
    return compile_fx_inner(model, example_inputs, num_fixed=fixed)
  File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 157, in compile_fx_inner
    return cudagraphify(
  File "/home/jansel/torchdynamo/torchinductor/compile_fx.py", line 187, in cudagraphify
    model(*inputs)
  File "/tmp/torchinductor_jansel/hg/chga4j6vyau7oo6h7liefg43va4urls277bfhpvq3nppc6xlvcb6.py", line 9499, in call
    kernel0[grid(65536, 196)](convolution_default_127, mean_dim_103, var_dim_158, primals_325, primals_322, convolution_default_128, mean_dim_104, var_dim_160, primals_329, primals_326, convolution_default_132, mean_dim_107, var_dim_164, primals_344, primals_341, convolution_default_133, mean_dim_108, var_dim_166, primals_348, primals_345, convolution_default_137, mean_dim_111, var_dim_170, primals_363, primals_360, convolution_default_138, mean_dim_112, var_dim_172, primals_367, primals_364, convolution_default_142, mean_dim_115, var_dim_176, primals_382, primals_379, convolution_default_143, mean_dim_116, var_dim_178, primals_386, primals_383, convolution_default_147, mean_dim_119, var_dim_182, primals_401, primals_398, convolution_default_148, mean_dim_120, var_dim_184, primals_405, primals_402, convolution_default_152, mean_dim_123, var_dim_188, primals_420, primals_417, convolution_default_153, mean_dim_124, var_dim_190, primals_424, primals_421, convolution_default_157, mean_dim_127, var_dim_194, primals_439, primals_436, convolution_default_158, mean_dim_128, var_dim_196, primals_443, primals_440, convolution_default_162, mean_dim_131, var_dim_200, primals_477, primals_474, convolution_default_163, mean_dim_132, var_dim_202, primals_481, primals_478, convolution_default_167, mean_dim_135, var_dim_206, primals_496, primals_493, convolution_default_168, mean_dim_136, var_dim_208, primals_500, primals_497, convolution_default_172, mean_dim_139, var_dim_212, primals_515, primals_512, convolution_default_173, mean_dim_140, var_dim_214, primals_519, primals_516, convolution_default_177, mean_dim_143, var_dim_218, primals_534, primals_531, convolution_default_178, mean_dim_144, var_dim_220, primals_538, primals_535, convolution_default_182, mean_dim_147, var_dim_224, primals_553, primals_550, convolution_default_183, mean_dim_148, var_dim_226, primals_557, primals_554, convolution_default_187, mean_dim_151, var_dim_230, primals_572, primals_569, convolution_default_188, mean_dim_152, var_dim_232, primals_576, primals_573, convolution_default_192, mean_dim_155, var_dim_236, primals_591, primals_588, convolution_default_193, mean_dim_156, var_dim_238, primals_595, primals_592, convolution_default_197, mean_dim_159, var_dim_242, primals_610, primals_607, convolution_default_198, mean_dim_160, var_dim_244, primals_614, primals_611, convolution_default_202, mean_dim_163, var_dim_248, primals_629, primals_626, convolution_default_203, mean_dim_164, var_dim_250, primals_633, primals_630, convolution_default_207, mean_dim_167, var_dim_254, primals_648, primals_645, convolution_default_208, mean_dim_168, var_dim_256, primals_652, primals_649, convolution_default_212, mean_dim_171, var_dim_260, primals_686, primals_683, convolution_default_213, mean_dim_172, var_dim_262, primals_690, primals_687, convolution_default_217, mean_dim_175, var_dim_266, primals_705, primals_702, convolution_default_218, mean_dim_176, var_dim_268, primals_709, primals_706, convolution_default_222, mean_dim_179, var_dim_272, primals_724, primals_721, convolution_default_223, mean_dim_180, var_dim_274, primals_728, primals_725, convolution_default_227, mean_dim_183, var_dim_278, primals_743, primals_740, convolution_default_228, mean_dim_184, var_dim_280, primals_747, primals_744, convolution_default_232, mean_dim_187, var_dim_284, primals_762, primals_759, convolution_default_233, mean_dim_188, var_dim_286, primals_766, primals_763, convolution_default_237, mean_dim_191, var_dim_290, primals_781, primals_778, convolution_default_238, mean_dim_192, var_dim_292, primals_785, primals_782, convolution_default_25, mean_dim_21, var_dim_34, primals_107, primals_104, convolution_default_241, mean_dim_194, var_dim_294, primals_929, primals_926, convolution_default_30, mean_dim_25, var_dim_40, primals_126, primals_123, convolution_default_35, mean_dim_29, var_dim_46, primals_145, primals_142, convolution_default_40, mean_dim_33, var_dim_52, primals_164, primals_161, convolution_default_45, mean_dim_37, var_dim_58, primals_183, primals_180, convolution_default_50, mean_dim_41, var_dim_64, primals_202, primals_199, convolution_default_55, mean_dim_45, var_dim_70, primals_221, primals_218, convolution_default_61, mean_dim_50, var_dim_78, primals_244, primals_241, convolution_default_62, mean_dim_51, var_dim_80, primals_248, primals_245, convolution_default_67, mean_dim_55, var_dim_86, primals_458, primals_455, convolution_default_68, mean_dim_56, var_dim_88, primals_462, primals_459, convolution_default_72, mean_dim_59, var_dim_92, primals_667, primals_664, convolution_default_73, mean_dim_60, var_dim_94, primals_671, primals_668, convolution_default_77, mean_dim_63, var_dim_98, primals_800, primals_797, convolution_default_78, mean_dim_64, var_dim_100, primals_804, primals_801, convolution_default_82, mean_dim_67, var_dim_104, primals_819, primals_816, convolution_default_83, mean_dim_68, var_dim_106, primals_823, primals_820, convolution_default_87, mean_dim_71, var_dim_110, primals_838, primals_835, convolution_default_88, mean_dim_72, var_dim_112, primals_842, primals_839, convolution_default_92, mean_dim_75, var_dim_116, primals_857, primals_854, convolution_default_93, mean_dim_76, var_dim_118, primals_861, primals_858, convolution_default_97, mean_dim_79, var_dim_122, primals_876, primals_873, convolution_default_98, mean_dim_80, var_dim_124, primals_880, primals_877, convolution_default_102, mean_dim_83, var_dim_128, primals_895, primals_892, convolution_default_103, mean_dim_84, var_dim_130, primals_899, primals_896, convolution_default_107, mean_dim_87, var_dim_134, primals_914, primals_911, convolution_default_108, mean_dim_88, var_dim_136, primals_918, primals_915, convolution_default_112, mean_dim_91, var_dim_140, primals_268, primals_265, convolution_default_113, mean_dim_92, var_dim_142, primals_272, primals_269, convolution_default_117, mean_dim_95, var_dim_146, primals_287, primals_284, convolution_default_118, mean_dim_96, var_dim_148, primals_291, primals_288, convolution_default_122, mean_dim_99, var_dim_152, primals_306, primals_303, convolution_default_123, mean_dim_100, var_dim_154, primals_310, primals_307, convolution_default_65, convolution_default_63, mean_dim_52, var_dim_82, primals_256, primals_253, convolution_default_70, convolution_default_75, convolution_default_80, convolution_default_85, convolution_default_90, convolution_default_95, convolution_default_100, convolution_default_105, convolution_default_110, convolution_default_115, convolution_default_120, convolution_default_125, convolution_default_130, convolution_default_135, convolution_default_140, convolution_default_145, convolution_default_150, convolution_default_155, convolution_default_160, convolution_default_165, convolution_default_170, convolution_default_175, convolution_default_180, convolution_default_185, convolution_default_190, convolution_default_195, convolution_default_200, convolution_default_205, convolution_default_210, convolution_default_215, convolution_default_220, convolution_default_225, convolution_default_230, convolution_default_235, convolution_default_240, buf100, buf101, buf104, buf105, buf108, buf109, buf112, buf113, buf116, buf117, buf120, buf121, buf124, buf125, buf128, buf129, buf132, buf133, buf136, buf137, buf140, buf141, buf144, buf145, buf148, buf149, buf152, buf153, buf156, buf157, buf160, buf161, buf164, buf165, buf168, buf169, buf172, buf173, buf176, buf177, buf180, buf181, buf184, buf185, buf188, buf189, buf19, buf191, buf23, buf27, buf31, buf35, buf39, buf43, buf48, buf49, buf52, buf53, buf56, buf57, buf60, buf61, buf64, buf65, buf68, buf69, buf72, buf73, buf76, buf77, buf80, buf81, buf84, buf85, buf88, buf89, buf92, buf93, buf96, buf97, buf50, buf54, buf58, buf62, buf66, buf70, buf74, buf78, buf82, buf86, buf90, buf94, buf98, buf102, buf106, buf110, buf114, buf118, buf122, buf126, buf130, buf134, buf138, buf142, buf146, buf150, buf154, buf158, buf162, buf166, buf170, buf174, buf178, buf182, buf186, buf190, 65536, 196)
  File "/home/jansel/triton/python/triton/code_gen.py", line 999, in __call__
    return self.kernel(*wargs, **kwargs, grid=self.grid)
  File "/home/jansel/triton/python/triton/code_gen.py", line 1073, in __call__
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/jansel/triton/python/triton/code_gen.py", line 1073, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/jansel/torchdynamo/torchinductor/triton_ops/autotune.py", line 25, in _bench
    return super()._bench(*args, config=config, **kwargs)
  File "/home/jansel/triton/python/triton/code_gen.py", line 1054, in _bench
    return triton.testing.do_bench(kernel_call)
  File "/home/jansel/triton/python/triton/testing.py", line 137, in do_bench
    fn()
  File "/home/jansel/triton/python/triton/code_gen.py", line 1053, in kernel_call
    self.kernel(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "/home/jansel/triton/python/triton/code_gen.py", line 988, in __call__
    return _triton.runtime.launch(wargs, self.fn.do_not_specialize, cache_key, self.fn.arg_names,
  File "/home/jansel/triton/python/triton/code_gen.py", line 956, in add_to_cache
    return self.fn._warmup(key, arg_types=arg_types, device=device_idx, attributes=attributes, constants=constants, num_warps=num_warps, num_stages=num_stages,
  File "/home/jansel/triton/python/triton/code_gen.py", line 1285, in _warmup
    binary = self._compile(**compile)
  File "/home/jansel/triton/python/triton/code_gen.py", line 1320, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, generator.module, device, num_warps, num_stages, extern_libs)
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileK1AVj4, line 12155; error   : Entry function 'kernel0__Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp16_Pfp32_Pfp32_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16_Pfp16__557c65536_558c196_559c32_560c32' uses too much parameter space (0x1168 bytes, 0x1100 max).
ptxas fatal   : Ptx assembly aborted due to errors

ERROR
ERROR
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
Likely fixed (can't run legacy_senet154 model, it's no longer in the timm_models_list)
