### ISSUE TITLE
[VDD] unique_by_key from _embedding_bag_dense_backward  isn't blocklisted by CUDA graphs

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93807]
repro:

```
jf get --update D38599092
CUDA_LAUNCH_BLOCKING=1 buck2 run @mode/opt -c python.package_style=inplace //hpc/torchrec/models/feed/benchmark:vdd_benchmark -- --iters 31 --compile True --cudagraphs True --pad_seq_embs=true --dynamo True
```

Fails with

```
RuntimeError: unique_by_key: failed to synchronize: cudaErrorStreamCaptureUnsupported: operation not permitted when stream is capturing
```

Relevant backtrace:

```
Traceback (most recent call last):
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/b01f384851ab2430/hpc/torchrec/models/feed/benchmark/__vdd_benchmark__/vdd_benchmark#link-tree/torchinductor/compile_fx.py", line 195, in cudagraphify
    static_outputs = model(*static_inputs)
  File "/tmp/torchinductor_ezyang/gj/cgjht4biqqcp6eqw6noomuiivkokp3rk5czqlfqt3ttsy27p2xlj.py", line 3408, in call
    buf304 = torch.ops.aten._embedding_bag_dense_backward.default(buf302, buf303, getitem_80, getitem_81, getitem_82, 100, False, 0, None)
```

cc @mcarilli @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ydwu4** [comment]
Is this issue still relevant? Close it for now but feel free to re-open
