### ISSUE TITLE
[Inductor] [CPU] AttributeError: 'int' object has no attribute 'free_symbols'

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#93833]
### 🐛 Describe the bug

From WW04.2 [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1411294041), we observed low passrate of model bench with `AttributeError: 'int' object has no attribute 'free_symbols'`.

****SW information****

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[6f611c5](https://github.com/pytorch/pytorch/commit/6f611c50305244c6f365e123c49fb4e5ce7eadf0)|[20bf77f](https://github.com/pytorch/pytorch/commit/20bf77f9bd3cd7cb4da758afb58042e2980ee6ba)
Torchbench|/|[ef39f8c](https://github.com/pytorch/benchmark/commit/ef39f8ca47e288ce7206fe92a0eaac03e85623b8)
torchaudio|[ecc2781](https://github.com/pytorch/audio/commit/ecc2781b5b5c353e85a8ca9f16741cf92dd08344)|[4a037b0](https://github.com/pytorch/audio/commit/4a037b03915c4f6f81407e697fb11a7e7ace27fa)
torchtext|[112d757](https://github.com/pytorch/text/commit/112d757efd2482ea5f60bc23d85c2c09f0cfde61)	| [c7cc5fc](https://github.com/pytorch/text/commit/c7cc5fc1e669f548eef619ae055690831d6cc75e)
torchvision|[ac06efe](https://github.com/pytorch/vision/commit/ac06efed4ad2867c68e6b49ac31b554fcbbaa472)|[35f68a0](https://github.com/pytorch/vision/commit/35f68a09f94b2d7afb3f6adc2ba850216413f28e)
torchdata|[049fb62](https://github.com/pytorch/data/commit/049fb626615e6cd965897af8fea2fa73cecd6a2a)|[c0934b9](https://github.com/pytorch/data/commit/c0934b9afa96458c0f8aa3bef528830835c22195)
dynamo_benchmarks|[fac4361](https://github.com/pytorch/pytorch/commit/fac4361e840f6da36ba8c83359c7d0ab5e00cf37)|/

<details><summary>
Error log
</summary>

(take Background_Matting as an example here)
```
cpu  eval  Background_Matting                 [2023-01-23 13:49:41,422] torch._inductor.graph: [ERROR] Error from lowering
Traceback (most recent call last):
  File "/workspace/pytorch/torch/_inductor/graph.py", line 314, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/lowering.py", line 225, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/lowering.py", line 862, in convolution_unary
    ir.ConvolutionUnary.create(
  File "/workspace/pytorch/torch/_inductor/ir.py", line 3434, in create
    (inputs, constant_args, kernel_layout, _) = _prepare_convolution_fusion_create(
  File "/workspace/pytorch/torch/_inductor/ir.py", line 3359, in _prepare_convolution_fusion_create
    x_fake = ir_node_to_tensor(x, guard_shape=True)
  File "/workspace/pytorch/torch/_inductor/ir.py", line 149, in ir_node_to_tensor
    t = torch.empty_strided(
  File "/workspace/pytorch/torch/_inductor/overrides.py", line 37, in __torch_function__
    return func(*args, **kwargs)
  File "/workspace/pytorch/torch/_subclasses/fake_tensor.py", line 908, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/workspace/pytorch/torch/_subclasses/fake_tensor.py", line 338, in constructors
    r = func(*args, **new_kwargs)
  File "/workspace/pytorch/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 432, in binary_magic_impl
    expr = self.shape_env.replace(self.expr)
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 157, in expr
    self._update_expr()
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 161, in _update_expr
    self._expr = self.shape_env.replace(self._expr)
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 571, in wrapper
    return fn_cache(self, *args, **kwargs)
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 1014, in replace
    replacements = {s: self._find(cast(sympy.Symbol, s)) for s in expr.free_symbols}
AttributeError: 'int' object has no attribute 'free_symbols'
ERROR:common:Failed for dynamo inductor raised LoweringException: AttributeError: 'int' object has no attribute 'free_symbols'
  target: mkldnn._convolution_pointwise.default
  args[0]: TensorBox(StorageBox(
    Pointwise(
      'cpu',
      torch.float32,
      tmp0 = constant(127, torch.int32)
      tmp1 = index_expr(i2, torch.int32)
      tmp2 = constant(1, torch.int32)
      tmp3 = tmp1 - tmp2
      tmp4 = abs(tmp3)
      tmp5 = tmp0 - tmp4
      tmp6 = abs(tmp5)
      tmp7 = tmp0 - tmp6
      tmp8 = constant(127, torch.int32)
      tmp9 = index_expr(i3, torch.int32)
      tmp10 = constant(1, torch.int32)
      tmp11 = tmp9 - tmp10
      tmp12 = abs(tmp11)
      tmp13 = tmp8 - tmp12
      tmp14 = abs(tmp13)
      tmp15 = tmp8 - tmp14
      tmp16 = load(buf35, i1 + 256 * (tmp15) + 32768 * (tmp7))
      return tmp16
      ,
      ranges=[1, 256, 130, 130],
      origins={_convolution_pointwise_15, cat_4, arg60_1, arg61_1, reflection_pad2d_4}
    )
  ))
  args[1]: TensorBox(StorageBox(
    InputBuffer(name='arg64_1', layout=FixedLayout('cpu', torch.float32, size=[256, 256, 3, 3], stride=[1, 0, 0, 0]))
  ))
  args[2]: TensorBox(StorageBox(
    InputBuffer(name='arg65_1', layout=FixedLayout('cpu', torch.float32, size=[256], stride=[1]))
  ))
  args[3]: [0, 0]
  args[4]: [1, 1]
  args[5]: [1, 1]
  args[6]: 1
  args[7]: relu
  args[8]: []
  args[9]: 

While executing %_convolution_pointwise_16 : [#users=1] = call_function[target=torch.ops.mkldnn._convolution_pointwise.default](args = (%reflection_pad2d_4, %arg64_1, %arg65_1, [0, 0], [1, 1], [1, 1], 1, relu, [], ), kwargs = {})
Original traceback:
  File "/workspace/benchmark/torchbenchmark/models/Background_Matting/networks.py", line 243, in forward
    out = x + self.conv_block(x)
 |   File "/workspace/benchmark/torchbenchmark/models/Background_Matting/networks.py", line 101, in forward
    out_dec=self.model_res_dec(torch.cat([img_feat,oth_feat],dim=1))


Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
Traceback (most recent call last):
  File "/workspace/pytorch/torch/_inductor/graph.py", line 314, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/lowering.py", line 225, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/lowering.py", line 862, in convolution_unary
    ir.ConvolutionUnary.create(
  File "/workspace/pytorch/torch/_inductor/ir.py", line 3434, in create
    (inputs, constant_args, kernel_layout, _) = _prepare_convolution_fusion_create(
  File "/workspace/pytorch/torch/_inductor/ir.py", line 3359, in _prepare_convolution_fusion_create
    x_fake = ir_node_to_tensor(x, guard_shape=True)
  File "/workspace/pytorch/torch/_inductor/ir.py", line 149, in ir_node_to_tensor
    t = torch.empty_strided(
  File "/workspace/pytorch/torch/_inductor/overrides.py", line 37, in __torch_function__
    return func(*args, **kwargs)
  File "/workspace/pytorch/torch/_subclasses/fake_tensor.py", line 908, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/workspace/pytorch/torch/_subclasses/fake_tensor.py", line 338, in constructors
    r = func(*args, **new_kwargs)
  File "/workspace/pytorch/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 432, in binary_magic_impl
    expr = self.shape_env.replace(self.expr)
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 157, in expr
    self._update_expr()
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 161, in _update_expr
    self._expr = self.shape_env.replace(self._expr)
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 571, in wrapper
    return fn_cache(self, *args, **kwargs)
  File "/workspace/pytorch/torch/fx/experimental/symbolic_shapes.py", line 1014, in replace
    replacements = {s: self._find(cast(sympy.Symbol, s)) for s in expr.free_symbols}
AttributeError: 'int' object has no attribute 'free_symbols'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 676, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/workspace/pytorch/torch/_dynamo/debug_utils.py", line 1047, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/optimizations/backends.py", line 24, in inner
    return fn(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/optimizations/backends.py", line 61, in inductor
    return compile_fx(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 410, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/optimizations/training.py", line 74, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2477, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 153, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2174, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1412, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1062, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 153, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 385, in fw_compiler
    return inner_compile(
  File "/workspace/pytorch/torch/_dynamo/debug_utils.py", line 586, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 149, in compile_fx_inner
    graph.run(*example_inputs)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 153, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 182, in run
    return super().run(*args)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 136, in run
    self.env[node] = self.run_node(node)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 388, in run_node
    result = super().run_node(n)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 177, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 318, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torch._inductor.exc.LoweringException: AttributeError: 'int' object has no attribute 'free_symbols'
  target: mkldnn._convolution_pointwise.default
  args[0]: TensorBox(StorageBox(
    Pointwise(
      'cpu',
      torch.float32,
      tmp0 = constant(127, torch.int32)
      tmp1 = index_expr(i2, torch.int32)
      tmp2 = constant(1, torch.int32)
      tmp3 = tmp1 - tmp2
      tmp4 = abs(tmp3)
      tmp5 = tmp0 - tmp4
      tmp6 = abs(tmp5)
      tmp7 = tmp0 - tmp6
      tmp8 = constant(127, torch.int32)
      tmp9 = index_expr(i3, torch.int32)
      tmp10 = constant(1, torch.int32)
      tmp11 = tmp9 - tmp10
      tmp12 = abs(tmp11)
      tmp13 = tmp8 - tmp12
      tmp14 = abs(tmp13)
      tmp15 = tmp8 - tmp14
      tmp16 = load(buf35, i1 + 256 * (tmp15) + 32768 * (tmp7))
      return tmp16
      ,
      ranges=[1, 256, 130, 130],
      origins={_convolution_pointwise_15, cat_4, arg60_1, arg61_1, reflection_pad2d_4}
    )
  ))
  args[1]: TensorBox(StorageBox(
    InputBuffer(name='arg64_1', layout=FixedLayout('cpu', torch.float32, size=[256, 256, 3, 3], stride=[1, 0, 0, 0]))
  ))
  args[2]: TensorBox(StorageBox(
    InputBuffer(name='arg65_1', layout=FixedLayout('cpu', torch.float32, size=[256], stride=[1]))
  ))
  args[3]: [0, 0]
  args[4]: [1, 1]
  args[5]: [1, 1]
  args[6]: 1
  args[7]: relu
  args[8]: []
  args[9]: 

While executing %_convolution_pointwise_16 : [#users=1] = call_function[target=torch.ops.mkldnn._convolution_pointwise.default](args = (%reflection_pad2d_4, %arg64_1, %arg65_1, [0, 0], [1, 1], [1, 1], 1, relu, [], ), kwargs = {})
Original traceback:
  File "/workspace/benchmark/torchbenchmark/models/Background_Matting/networks.py", line 243, in forward
    out = x + self.conv_block(x)
 |   File "/workspace/benchmark/torchbenchmark/models/Background_Matting/networks.py", line 101, in forward
    out_dec=self.model_res_dec(torch.cat([img_feat,oth_feat],dim=1))


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 1278, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/torchbench.py", line 354, in forward_pass
    return mod(*inputs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 403, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 261, in _convert_frame_assert
    return _compile(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 153, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 323, in _compile
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 310, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1692, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 1758, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 552, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 599, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 153, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 681, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: inductor raised LoweringException: AttributeError: 'int' object has no attribute 'free_symbols'
  target: mkldnn._convolution_pointwise.default
  args[0]: TensorBox(StorageBox(
    Pointwise(
      'cpu',
      torch.float32,
      tmp0 = constant(127, torch.int32)
      tmp1 = index_expr(i2, torch.int32)
      tmp2 = constant(1, torch.int32)
      tmp3 = tmp1 - tmp2
      tmp4 = abs(tmp3)
      tmp5 = tmp0 - tmp4
      tmp6 = abs(tmp5)
      tmp7 = tmp0 - tmp6
      tmp8 = constant(127, torch.int32)
      tmp9 = index_expr(i3, torch.int32)
      tmp10 = constant(1, torch.int32)
      tmp11 = tmp9 - tmp10
      tmp12 = abs(tmp11)
      tmp13 = tmp8 - tmp12
      tmp14 = abs(tmp13)
      tmp15 = tmp8 - tmp14
      tmp16 = load(buf35, i1 + 256 * (tmp15) + 32768 * (tmp7))
      return tmp16
      ,
      ranges=[1, 256, 130, 130],
      origins={_convolution_pointwise_15, cat_4, arg60_1, arg61_1, reflection_pad2d_4}
    )
  ))
  args[1]: TensorBox(StorageBox(
    InputBuffer(name='arg64_1', layout=FixedLayout('cpu', torch.float32, size=[256, 256, 3, 3], stride=[1, 0, 0, 0]))
  ))
  args[2]: TensorBox(StorageBox(
    InputBuffer(name='arg65_1', layout=FixedLayout('cpu', torch.float32, size=[256], stride=[1]))
  ))
  args[3]: [0, 0]
  args[4]: [1, 1]
  args[5]: [1, 1]
  args[6]: 1
  args[7]: relu
  args[8]: []
  args[9]: 

While executing %_convolution_pointwise_16 : [#users=1] = call_function[target=torch.ops.mkldnn._convolution_pointwise.default](args = (%reflection_pad2d_4, %arg64_1, %arg65_1, [0, 0], [1, 1], [1, 1], 1, relu, [], ), kwargs = {})
Original traceback:
  File "/workspace/benchmark/torchbenchmark/models/Background_Matting/networks.py", line 243, in forward
    out = x + self.conv_block(x)
 |   File "/workspace/benchmark/torchbenchmark/models/Background_Matting/networks.py", line 101, in forward
    out_dec=self.model_res_dec(torch.cat([img_feat,oth_feat],dim=1))


Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

ERROR

```
</details>

### Repro cmd
```
python -m torch.backends.xeon.run_cpu --core_list 0 --ncores_per_instance 1 benchmarks/dynamo/torchbench.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only Background_Matting  --cold_start_latency --batch_size 1 --threads 1
```

**Comment by Guobing-Chen** [comment]
https://github.com/pytorch/pytorch/pull/93349 is created to fix this.
