### ISSUE TITLE
[pt2] (`interpolate` with `mode=nearest`) + `kthvalue` triggers assertion fail in compile mode

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#93849]
### 🐛 Describe the bug

The following program works fine in eager mode but raises assertion fail in compile mode.
```python
import torch

def fn(input):
    v = torch.nn.functional.interpolate(input, [11], mode="nearest") 
      # works fine if `mode` is set to other values such as "linear"
    return torch.kthvalue(v, 2)

x = torch.rand([5, 5, 5])

ret_eager = fn(x)
print('==== Eager mode OK! ====')

compiled = torch.compile(fn)
print('==== torchcomp compilation OK! ====')

ret_compiled = compiled(x)
print('==== torchcomp mode OK! ====')
```

### Error logs

<details><summary>[Click to expand]</summary>

```
==== Eager mode OK! ====
==== torchcomp compilation OK! ====
/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/compile_fx.py:90: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
[2023-02-01 08:28:38,037] torch._inductor.graph: [WARNING] Creating implicit fallback for:
  target: aten.kthvalue.default
  args[0]: TensorBox(StorageBox(
    Pointwise(
      'cpu',
      torch.float32,
      tmp0 = index_expr(i2, torch.float32)
      tmp1 = constant(0.45454545454545453, torch.float32)
      tmp2 = tmp0 * tmp1
      tmp3 = to_dtype(tmp2, torch.int32)
      tmp4 = load(arg0_1, (tmp3) + 5 * i1 + 25 * i0)
      return tmp4
      ,
      ranges=[5, 5, 11],
      origins={upsample_nearest1d, arg0_1}
    )
  ))
  args[1]: 2
[2023-02-01 08:28:38,039] torch._inductor.graph: [ERROR] Error from lowering
Traceback (most recent call last):
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/graph.py", line 314, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/lowering.py", line 226, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/lowering.py", line 983, in handler
    TensorBox.create, ir.FallbackKernel.create(kernel, *args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/ir.py", line 2960, in create
    ) = cls.process_kernel(kernel, *args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/ir.py", line 2511, in process_kernel
    example_args.append(ir_node_to_tensor(x, guard_shape=True))
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/ir.py", line 150, in ir_node_to_tensor
    t = torch.empty_strided(
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 925, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 339, in constructors
    r = func(*args, **new_kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 456, in binary_magic_impl
    expr = self.shape_env.replace(self.expr)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 160, in expr
    self._update_expr()
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 164, in _update_expr
    self._expr = self.shape_env.replace(self._expr)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 595, in wrapper
    return fn_cache(self, *args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 1038, in replace
    replacements = {s: self._find(cast(sympy.Symbol, s)) for s in expr.free_symbols}
AttributeError: 'int' object has no attribute 'free_symbols'
[2023-02-01 08:28:38,054] torch._dynamo.debug_utils: [WARNING] Writing minified repro to /home/yuyao/bug_repro/torch_compile_debug/run_2023_02_01_08_28_38_053729/minifier/minifier_launcher.py
[2023-02-01 08:28:38,054] torch._dynamo.debug_utils: [ERROR] CompilerError
Traceback (most recent call last):
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/graph.py", line 314, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/lowering.py", line 226, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/lowering.py", line 983, in handler
    TensorBox.create, ir.FallbackKernel.create(kernel, *args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/ir.py", line 2960, in create
    ) = cls.process_kernel(kernel, *args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/ir.py", line 2511, in process_kernel
    example_args.append(ir_node_to_tensor(x, guard_shape=True))
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/ir.py", line 150, in ir_node_to_tensor
    t = torch.empty_strided(
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 925, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 339, in constructors
    r = func(*args, **new_kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 456, in binary_magic_impl
    expr = self.shape_env.replace(self.expr)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 160, in expr
    self._update_expr()
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 164, in _update_expr
    self._expr = self.shape_env.replace(self._expr)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 595, in wrapper
    return fn_cache(self, *args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/experimental/symbolic_shapes.py", line 1038, in replace
    replacements = {s: self._find(cast(sympy.Symbol, s)) for s in expr.free_symbols}
AttributeError: 'int' object has no attribute 'free_symbols'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "repro.py", line 15, in <module>
    ret_compiled = compiled(x)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "repro.py", line 3, in fn
    def fn(input):
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2497, in forward
    return compiled_fn(full_args)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1065, in new_fn
    fw_outs = call_func_with_args(compiled_fw, args, disable_amp=disable_amp)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1021, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 563, in deferred_for_real_inputs
    inner_compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 150, in compile_fx_inner
    graph.run(*example_inputs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 161, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/graph.py", line 182, in run
    return super().run(*args)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/interpreter.py", line 136, in run
    self.env[node] = self.run_node(node)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/graph.py", line 388, in run_node
    result = super().run_node(n)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/fx/interpreter.py", line 177, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/graph.py", line 318, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torch._inductor.exc.LoweringException: AttributeError: 'int' object has no attribute 'free_symbols'
  target: aten.kthvalue.default
  args[0]: TensorBox(StorageBox(
    ComputedBuffer(name='buf0', layout=FixedLayout('cpu', torch.float32, size=[5, 5, 11], stride=[55, 11, 1]), data=Pointwise(
      'cpu',
      torch.float32,
      tmp0 = index_expr(i2, torch.float32)
      tmp1 = constant(0.45454545454545453, torch.float32)
      tmp2 = tmp0 * tmp1
      tmp3 = to_dtype(tmp2, torch.int32)
      tmp4 = load(arg0_1, (tmp3) + 5 * i1 + 25 * i0)
      return tmp4
      ,
      ranges=[5, 5, 11],
      origins={upsample_nearest1d, arg0_1}
    ))
  ))
  args[1]: 2

While executing %kthvalue : [#users=2] = call_function[target=torch.ops.aten.kthvalue.default](args = (%upsample_nearest1d, 2), kwargs = {})
Original traceback:
  File "repro.py", line 5, in fn
    return torch.kthvalue(v, 2)
```

</details>

### Minified repro

```python
import torch._inductor.overrides

import torch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

import torch._dynamo.config
import torch._inductor.config
torch._dynamo.config.load_config(b'\x80\x04\x95\xad\x07\x00\x00\x00\x00\x00\x00}\x94(\x8c\x08__name__\x94\x8c\x14torch._dynamo.config\x94\x8c\x07__doc__\x94N\x8c\x0b__package__\x94\x8c\rtorch._dynamo\x94\x8c\n__loader__\x94\x8c\x1a_frozen_importlib_external\x94\x8c\x10SourceFileLoader\x94\x93\x94)\x81\x94}\x94(\x8c\x04name\x94h\x02\x8c\x04path\x94\x8cF/home/yuyao/.local/lib/python3.8/site-packages/torch/_dynamo/config.py\x94ub\x8c\x08__spec__\x94\x8c\x11_frozen_importlib\x94\x8c\nModuleSpec\x94\x93\x94)\x81\x94}\x94(h\x0ch\x02\x8c\x06loader\x94h\n\x8c\x06origin\x94h\x0e\x8c\x0cloader_state\x94N\x8c\x1asubmodule_search_locations\x94N\x8c\r_set_fileattr\x94\x88\x8c\x07_cached\x94\x8c^/home/yuyao/.local/lib/python3.8/site-packages/torch/_dynamo/__pycache__/config.cpython-38.pyc\x94\x8c\r_initializing\x94\x89ub\x8c\x08__file__\x94h\x0e\x8c\n__cached__\x94h\x1b\x8c\x07abspath\x94\x8c\tposixpath\x94h\x1f\x93\x94\x8c\x07dirname\x94h h"\x93\x94\x8c\tlog_level\x94K\x1e\x8c\x0boutput_code\x94\x89\x8c\rlog_file_name\x94N\x8c\x07verbose\x94\x89\x8c\x11output_graph_code\x94\x89\x8c\x12verify_correctness\x94\x89\x8c\x12minimum_call_count\x94K\x01\x8c\x15dead_code_elimination\x94\x88\x8c\x10cache_size_limit\x94K@\x8c\x14specialize_int_float\x94\x88\x8c\x0edynamic_shapes\x94\x89\x8c\x10guard_nn_modules\x94\x89\x8c\x0cnormalize_ir\x94\x89\x8c\x1btraceable_tensor_subclasses\x94\x8f\x94\x8c\x0fsuppress_errors\x94\x89\x8c\x15replay_record_enabled\x94\x89\x8c rewrite_assert_with_torch_assert\x94\x88\x8c\x12print_graph_breaks\x94\x89\x8c\x07disable\x94\x89\x8c*allowed_functions_module_string_ignorelist\x94\x8f\x94(\x8c\rtorch._decomp\x94\x8c\x0btorch._refs\x94\x8c\rtorch.testing\x94\x8c\x0ctorch._prims\x94\x8c\x13torch.distributions\x94\x90\x8c\x16capture_scalar_outputs\x94\x89\x8c\x19enforce_cond_guards_match\x94\x88\x8c\x0coptimize_ddp\x94\x88\x8c\x1araise_on_ctx_manager_usage\x94\x88\x8c\x1craise_on_unsafe_aot_autograd\x94\x89\x8c\rdynamo_import\x94\x8c\rtorch._dynamo\x94\x8c\x0finductor_import\x94\x8c\x0ftorch._inductor\x94\x8c\x18error_on_nested_fx_trace\x94\x88\x8c\tallow_rnn\x94\x89\x8c\x08base_dir\x94\x8c./home/yuyao/.local/lib/python3.8/site-packages\x94\x8c\x0edebug_dir_root\x94\x8c)/home/yuyao/bug_repro/torch_compile_debug\x94\x8c)DO_NOT_USE_legacy_non_fake_example_inputs\x94\x89\x8c\x15_AccessLimitingConfig\x94}\x94(\x8c\n__module__\x94h\x02\x8c\x0b__setattr__\x94\x8c\x14torch._dynamo.config\x94\x8c!_AccessLimitingConfig.__setattr__\x94\x93\x94h\x03Nu\x8c\x15_allowed_config_names\x94\x8f\x94(hLhA\x8c\nModuleType\x94h\x0f\x8c\x02os\x94h7hJhNh"h6\x8c\x0eexternal_utils\x94h&h\x1fhB\x8c\x07logging\x94h)\x8c!skipfiles_inline_module_allowlist\x94hIh\x1dh-h.h(h?\x8c\x0brepro_after\x94h4h0h%h\x03h*h$hDhF\x8c\x0brepro_level\x94h\x1eh\x04hOh8\x8c\x05torch\x94h/h1hHh,h@\x8c\x0c__builtins__\x94\x8c\x12constant_functions\x94h+hCh\x01h\'h\x06h5h3\x8c\x03sys\x94\x90\x8c\x1cget_config_serialization_fns\x94\x8c\x1atorch._dynamo.config_utils\x94hc\x93\x94u.')
torch._inductor.config.load_config(b'\x80\x04\x95\x07\t\x00\x00\x00\x00\x00\x00}\x94(\x8c\x08__name__\x94\x8c\x16torch._inductor.config\x94\x8c\x07__doc__\x94N\x8c\x0b__package__\x94\x8c\x0ftorch._inductor\x94\x8c\n__loader__\x94\x8c\x1a_frozen_importlib_external\x94\x8c\x10SourceFileLoader\x94\x93\x94)\x81\x94}\x94(\x8c\x04name\x94h\x02\x8c\x04path\x94\x8cH/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/config.py\x94ub\x8c\x08__spec__\x94\x8c\x11_frozen_importlib\x94\x8c\nModuleSpec\x94\x93\x94)\x81\x94}\x94(h\x0ch\x02\x8c\x06loader\x94h\n\x8c\x06origin\x94h\x0e\x8c\x0cloader_state\x94N\x8c\x1asubmodule_search_locations\x94N\x8c\r_set_fileattr\x94\x88\x8c\x07_cached\x94\x8c`/home/yuyao/.local/lib/python3.8/site-packages/torch/_inductor/__pycache__/config.cpython-38.pyc\x94\x8c\r_initializing\x94\x89ub\x8c\x08__file__\x94h\x0e\x8c\n__cached__\x94h\x1b\x8c\x05debug\x94\x89\x8c\x10disable_progress\x94\x88\x8c\x10verbose_progress\x94\x89\x8c\x0bcpp_wrapper\x94\x89\x8c\x03dce\x94\x89\x8c\x14static_weight_shapes\x94\x88\x8c\x0csize_asserts\x94\x88\x8c\x10pick_loop_orders\x94\x88\x8c\x0finplace_buffers\x94\x88\x8c\x11benchmark_harness\x94\x88\x8c\x0fepilogue_fusion\x94\x89\x8c\x15epilogue_fusion_first\x94\x89\x8c\x0cmax_autotune\x94\x89\x8c\x17realize_reads_threshold\x94K\x04\x8c\x17realize_bytes_threshold\x94M\xd0\x07\x8c\x1brealize_acc_reads_threshold\x94K\x08\x8c\x0ffallback_random\x94\x89\x8c\x12implicit_fallbacks\x94\x88\x8c\rprefuse_nodes\x94\x88\x8c\x0btune_layout\x94\x89\x8c\x11aggressive_fusion\x94\x89\x8c\x0fmax_fusion_size\x94K@\x8c\x1bunroll_reductions_threshold\x94K\x08\x8c\x0ecomment_origin\x94\x89\x8c\tis_fbcode\x94\x8c\x16torch._inductor.config\x94h7\x93\x94\x8c\x0fcompile_threads\x94K \x8c\x13kernel_name_max_ops\x94K\n\x8c\x0finductor_import\x94\x8c\x0ftorch._inductor\x94\x8c\rshape_padding\x94\x89\x8c\x0epermute_fusion\x94\x89\x8c\x1aprofiler_mark_wrapper_call\x94\x89\x8c\x03cpp\x94}\x94(\x8c\n__module__\x94h\x02\x8c\x07threads\x94J\xff\xff\xff\xff\x8c\x0fdynamic_threads\x94\x89\x8c\x07simdlen\x94N\x8c\x0emin_chunk_size\x94M\x00\x10\x8c\x03cxx\x94N\x8c\x03g++\x94\x86\x94\x8c\x15enable_kernel_profile\x94\x89h\x03Nu\x8c\x06triton\x94}\x94(hCh\x02\x8c\ncudagraphs\x94\x88\x8c\x10debug_sync_graph\x94\x89\x8c\x11debug_sync_kernel\x94\x89\x8c\x0bconvolution\x94\x8c\x04aten\x94\x8c\x0edense_indexing\x94\x89\x8c\tmax_tiles\x94K\x02\x8c\x12autotune_pointwise\x94\x88\x8c tiling_prevents_pointwise_fusion\x94\x88\x8c tiling_prevents_reduction_fusion\x94\x88\x8c\x14ordered_kernel_names\x94\x89\x8c\x18descriptive_kernel_names\x94\x89h\x03Nu\x8c\x05trace\x94}\x94(hCh\x02\x8c\x07enabled\x94\x89\x8c\tdebug_log\x94\x88\x8c\x08info_log\x94\x89\x8c\x08fx_graph\x94\x88\x8c\rir_pre_fusion\x94\x88\x8c\x0eir_post_fusion\x94\x88\x8c\x0boutput_code\x94\x88\x8c\rgraph_diagram\x94\x89\x8c\x0fcompile_profile\x94\x89\x8c\nupload_tar\x94Nh\x03Nu\x8c\x15InductorConfigContext\x94}\x94(hCh\x02\x8c\x0f__annotations__\x94}\x94(\x8c\rstatic_memory\x94\x8c\x08builtins\x94\x8c\x04bool\x94\x93\x94\x8c\x0ematmul_padding\x94hm\x8c\x0cmax_autotune\x94hm\x8c\x12triton_convolution\x94hk\x8c\x03str\x94\x93\x94\x8c\x17rematerialize_threshold\x94hk\x8c\x03int\x94\x93\x94\x8c\x1brematerialize_acc_threshold\x94huu\x8c\x05_save\x94h8\x8c\x1bInductorConfigContext._save\x94\x93\x94\x8c\x06_apply\x94h8\x8c\x1cInductorConfigContext._apply\x94\x93\x94\x8c\x08__init__\x94h8\x8c\x1eInductorConfigContext.__init__\x94\x93\x94\x8c\t__enter__\x94h8\x8c\x1fInductorConfigContext.__enter__\x94\x93\x94\x8c\x08__exit__\x94h8\x8c\x1eInductorConfigContext.__exit__\x94\x93\x94h\x03Nu\x8c\x1cget_config_serialization_fns\x94\x8c\x1atorch._dynamo.config_utils\x94h\x86\x93\x94u.')


# REPLACEABLE COMMENT FOR TESTING PURPOSES


# torch version: 2.0.0.dev20230131+cu117
# torch cuda version: 11.7
# torch git version: b2690c3ceae36fa6681a0c7cedcc8db7f5d9814a


# CUDA Info: 
# nvcc not found
# GPU Hardware Info: 
# NVIDIA RTX A6000 : 4 


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()

    
    
    def forward(self, arg0_1, getitem):
        upsample_nearest1d = torch.ops.aten.upsample_nearest1d.default(arg0_1, [11]);  arg0_1 = None
        kthvalue = torch.ops.aten.kthvalue.default(upsample_nearest1d, 2);  upsample_nearest1d = None
        return [getitem]
        
args = [((5, 5, 5), (25, 5, 1), torch.float32, 'cpu'), ((5, 5), (5, 1), torch.float32, 'cpu')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
mod = make_fx(Repro())(*args)

from torch._inductor.compile_fx import compile_fx_inner
from torch._dynamo.debug_utils import same_two_models

compiled = compile_fx_inner(mod, args)
ref = compiled(args)
```

### Versions

<details><summary><b>Environment</b> <i>[Click to expand]</i></summary>

```
PyTorch version: 2.0.0.dev20230201+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-137-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 510.68.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230201+cu117
[pip3] torchaudio==2.0.0.dev20230126+cu117
[pip3] torchvision==0.15.0.dev20230126+cu117
[conda] No relevant packages
```

</details>

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ezyang** [comment]
@Kristoff-starling to help us triage, are these issues coming from real models, or are you running a fuzzer against PT2?

**Comment by XiaobingSuper** [comment]
This issue may be fixed by https://github.com/pytorch/pytorch/pull/93349.

**Comment by chunyuan-w** [comment]
I've checked that this issue can be fixed by https://github.com/pytorch/pytorch/pull/93349 and it has been merged.
