### ISSUE TITLE
"Expected a value of type 'float' for argument 'p' but instead found type 'int'." occurs during saving a quantized model using FX Graph Mode Post Training Static Quantization

### ISSUE THREAD

**Issue by Coderx7** [pytorch/pytorch#93862]
### 🐛 Describe the bug

I'm trying to quantize an already trained model using "**FX Graph Mode Post Training Static Quantization**", the quantization itself seems to run OK without any issues, however, upon trying to save the model to the disk, it crashes with the following error : 

```python
python3 test.py
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22.0M/22.0M [00:27<00:00, 844kB/s]
/home/hossein/.local/lib/python3.8/site-packages/torch/ao/quantization/observer.py:214: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(
converting...
saving....
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    torch.jit.save(torch.jit.script(quantized_model.cpu()), 'quantized.pt')
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 

dropout2d(Tensor input, float p=0.5, bool training=True, bool inplace=False) -> Tensor:
Expected a value of type 'float' for argument 'p' but instead found type 'int'.
:
  File "/home/hossein/.local/lib/python3.8/site-packages/torch/nn/modules/dropout.py", line 150
    def forward(self, input: Tensor) -> Tensor:
        return F.dropout2d(input, self.p, self.training, self.inplace)
               ~~~~~~~~~~~ <--- HERE
```

Here is the sample snippet to reproduce this issue : 
model: 
```python
class Simplenet(nn.Module):
    def __init__(self,drop_rates={}):
        super().__init__()
        self.features = self._make_layers()
        self.classifier = nn.Linear(9,10)

    def forward(self, x):
        out = self.features(x)
        out = F.max_pool2d(out, kernel_size=out.size()[2:])
        out = F.dropout2d(out, 0.5, training=self.training)
        out = out.view(out.size(0), -1)
        out = self.classifier(out)
        return out

    def _make_layers(self):
        model = nn.Sequential(nn.Conv2d(3,3,kernel_size=3),
                      nn.BatchNorm2d(3),
                      nn.ReLU(inplace=True),
                      nn.Dropout2d(p=0),
                      nn.MaxPool2d(2,2),
                      
                      nn.Conv2d(3,6,kernel_size=3),
                      nn.BatchNorm2d(6),
                      nn.ReLU(inplace=True),
                      nn.Dropout2d(p=0),
                      nn.MaxPool2d(2,2),
                      
                      nn.Conv2d(6,9,kernel_size=3),
                      nn.BatchNorm2d(9),
                      nn.ReLU(inplace=True),
                      nn.Dropout2d(p=0),
                      nn.MaxPool2d(2,2),
                      )
        for m in model.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.xavier_uniform_(m.weight.data, gain=nn.init.calculate_gain("relu"))
        return model

```
quantization test:
```python
import torch
from torchvision import datasets,transforms,models
from torch.utils.data import dataloader

from torch.ao.quantization import get_default_qconfig
from torch.ao.quantization.quantize_fx import prepare_fx, convert_fx
from torch.ao.quantization import QConfigMapping

from simplenetv1 import *

float_model = simplenet(True)
float_model.eval()
#define fake dataset and fake dataload for testing
dataset = datasets.FakeData(1000,num_classes=1000,transform=transforms.ToTensor())
loader = dataloader.DataLoader(dataset,256)

qconfig = get_default_qconfig("fbgemm")
qconfig_mapping = QConfigMapping().set_global(qconfig)

def calibrate(model, data_loader):
    model.eval()
    with torch.no_grad():
        for image, target in data_loader:
            model =  model.cuda()
            model(image.cuda())
            break

example_inputs = (next(iter(loader))[0]) # get an example input
prepared_model = prepare_fx(float_model, qconfig_mapping, example_inputs)  # fuse modules and insert observers
calibrate(prepared_model, loader)  # run calibration on sample data
print(f'converting...')
quantized_model = convert_fx(prepared_model.eval().cpu())  # convert the calibrated model to a quantized model
print(f'saving....')
torch.jit.save(torch.jit.script(quantized_model.cpu()), 'quantized.pt')
```

side note: 
I noticed this doesnt happen if I use `resnet18` for example!

### Versions

output of collect_env.py
```python
hossein@hossein-pc:~$ python3 collect_env.py 
Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-51-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080
Nvidia driver version: 515.86.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.0
[pip3] torch==1.13.1
[pip3] torch-pruning==1.0.0
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1
[conda] Could not collect

```

**Comment by Coderx7** [comment]
I tested the model with the normal post training static quantization, and quantization goes smoothly without a hitch, however, the saving part crashes nonetheless.
The torch script seems to work normally if we dont quantize the model, but somehow it crashes after the quantization.
