### ISSUE TITLE
DISABLED test_nccl_warn_not_in_group_debug_detail (__main__.CommTest)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#93865]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_nccl_warn_not_in_group_debug_detail%2CCommTest)).

sometimes
```
2023-02-01T11:55:12.3954500Z FAIL [6.214s]: test_nccl_warn_not_in_group_debug_detail (__main__.CommTest)
2023-02-01T11:55:12.3954981Z ----------------------------------------------------------------------
2023-02-01T11:55:12.3955346Z Traceback (most recent call last):
2023-02-01T11:55:12.3955888Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 541, in wrapper
2023-02-01T11:55:12.3956300Z     self._join_processes(fn)
2023-02-01T11:55:12.3956864Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 767, in _join_processes
2023-02-01T11:55:12.3957300Z     self._check_return_codes(elapsed_time)
2023-02-01T11:55:12.3957869Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 822, in _check_return_codes
2023-02-01T11:55:12.3958283Z     self.assertEqual(
2023-02-01T11:55:12.3958816Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2926, in assertEqual
2023-02-01T11:55:12.3959200Z     assert_equal(
2023-02-01T11:55:12.3959690Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1244, in assert_equal
2023-02-01T11:55:12.3960096Z     raise error_metas[0].to_error(msg)
2023-02-01T11:55:12.3960399Z AssertionError: Scalars are not equal!
2023-02-01T11:55:12.3960592Z 
```
and other times
```
2023-02-01T12:56:19.6712479Z ERROR [300.087s]: test_nccl_warn_not_in_group_debug_detail (__main__.CommTest)
2023-02-01T12:56:19.6712750Z ----------------------------------------------------------------------
2023-02-01T12:56:19.6712889Z Traceback (most recent call last):
2023-02-01T12:56:19.6713513Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 541, in wrapper
2023-02-01T12:56:19.6713655Z     self._join_processes(fn)
2023-02-01T12:56:19.6714071Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 767, in _join_processes
2023-02-01T12:56:19.6714220Z     self._check_return_codes(elapsed_time)
2023-02-01T12:56:19.6714639Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 817, in _check_return_codes
2023-02-01T12:56:19.6714742Z     raise RuntimeError(
2023-02-01T12:56:19.6714941Z RuntimeError: Process 1 terminated or timed out after 300.08388471603394 seconds
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by huydhn** [comment]
This looks fixed on trunk, let me close this to let the test run again and confirm

**Comment by wanchaol** [comment]
Similar to https://github.com/pytorch/pytorch/issues/94003 

I tried to run it locally and it always passed, not sure why there's flakiness of this test.

**Comment by kumpera** [comment]
The test is checking the return code of the process so it's hard to tell what happened without the output from them.
In all likelyhood something unrelated happened and caused one of the child process to hang or crash.
