### ISSUE TITLE
NameError: name 'sympy' is not defined

### ISSUE THREAD

**Issue by xuyingzhongguo** [pytorch/pytorch#93881]
### 🐛 Describe the bug

NameError: name 'sympy' is not defined, while I already installed sympy in my venv.
```sympy                     1.11.1          py310h06a4308_0 ```
```
No sympy found
Traceback (most recent call last):
  File "/home/ying/code/try_python/dataset.py", line 1, in <module>
    import torchvision
  File "/home/ying/.conda/envs/video-api/lib/python3.10/site-packages/torchvision/__init__.py", line 5, in <module>
    import torch
  File "/home/ying/.conda/envs/video-api/lib/python3.10/site-packages/torch/__init__.py", line 1408, in <module>
    from . import _meta_registrations
  File "/home/ying/.conda/envs/video-api/lib/python3.10/site-packages/torch/_meta_registrations.py", line 7, in <module>
    from torch._decomp import _add_op_to_registry, global_decomposition_table, meta_table
  File "/home/ying/.conda/envs/video-api/lib/python3.10/site-packages/torch/_decomp/__init__.py", line 168, in <module>
    import torch._decomp.decompositions
  File "/home/ying/.conda/envs/video-api/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 10, in <module>
    import torch._prims as prims
  File "/home/ying/.conda/envs/video-api/lib/python3.10/site-packages/torch/_prims/__init__.py", line 33, in <module>
    from torch._subclasses.fake_tensor import FakeTensor, FakeTensorMode
  File "/home/ying/.conda/envs/video-api/lib/python3.10/site-packages/torch/_subclasses/__init__.py", line 3, in <module>
    from torch._subclasses.fake_tensor import (
  File "/home/ying/.conda/envs/video-api/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 12, in <module>
    from torch._guards import Source
  File "/home/ying/.conda/envs/video-api/lib/python3.10/site-packages/torch/_guards.py", line 78, in <module>
    class ShapeGuard(NamedTuple):
  File "/home/ying/.conda/envs/video-api/lib/python3.10/site-packages/torch/_guards.py", line 79, in ShapeGuard
    expr: sympy.Expr
NameError: name 'sympy' is not defined
```

Thanks for the help in advance.

### Versions

--2023-02-01 20:55:55--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17278 (17K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py                     100%[=============================================================>]  16,87K  --.-KB/s    in 0s      

2023-02-01 20:55:55 (78,8 MB/s) - ‘collect_env.py’ saved [17278/17278]

Collecting environment information...
PyTorch version: 2.0.0.dev20230201
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 515.86.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.991
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.5.0
[pip3] torch==2.0.0.dev20230201
[pip3] torchaudio==2.0.0.dev20230201
[pip3] torchvision==0.15.0.dev20230201
[conda] blas                      1.0                         mkl  
[conda] magma-cuda117             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.1.0           h06a4308_224  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.21.5          py310h1794996_3  
[conda] numpy-base                1.21.5          py310hcba007f_3  
[conda] numpydoc                  1.5.0           py310h06a4308_0  
[conda] pytorch                   2.0.0.dev20230201 py3.10_cuda11.7_cudnn8.5.0_0    pytorch-nightly
[conda] pytorch-cuda              11.7                 h67b0de4_2    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                2.0.0.dev20230201     py310_cu117    pytorch-nightly
[conda] torchtriton               2.0.0+0d7e753227           py310    pytorch-nightly
[conda] torchvision               0.15.0a0+82c51c4          pypi_0    pypi

**Comment by jbschlosser** [comment]
Sounds like an environment issue - if you can't `import sympy`, that's not a good sign that it's available. Closing as non-PyTorch-related but feel free to reopen if you think I've made a mistake.
