### ISSUE TITLE
Cannot export models which access int/float stored as module attributes (they get unspecialized into inputs, which makes export choke)

### ISSUE THREAD

**Issue by tugsbayasgalan** [pytorch/pytorch#93927]
### 🐛 Describe the bug

```python
import torch
import torch._dynamo as torchdynamo

class Foo(torch.nn.Module):
    def __init__(
        self,
        input_dim,
    ):
        super().__init__()
        self.torch_module = torch.nn.LayerNorm(
            input_dim, eps=1e-5, elementwise_affine=True
        )

    def forward(self, input):
        output = torch.nn.functional.layer_norm(
            input,
            self.torch_module.normalized_shape,
            self.torch_module.weight,
            self.torch_module.bias,
            self.torch_module.eps,
        ).type_as(input)
        return output

mod = Foo(128)
inp = torch.randn(3, 128)
gm, _ = torchdynamo.export(mod, inp, aten_graph=True, tracing_mode="symbolic")
print(gm.graph)
```
Above snippet fails with following error:
```
RuntimeError                              Traceback (most recent call last)
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/utils.py in run_node(output_graph, node, args, kwargs, nnmodule)
   1185         if op == "call_function":
-> 1186             return node.target(*args, **kwargs)
   1187         elif op == "call_method":
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/nn/functional.py in layer_norm(input, normalized_shape, weight, bias, eps)
   2514         )
-> 2515     return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
   2516 
RuntimeError: tried to get Double out of SymFloat

The above exception was the direct cause of the following exception:
RuntimeError                              Traceback (most recent call last)
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/utils.py in get_fake_value(node, tx)
   1143         with tx.fake_mode, enable_python_dispatcher():
-> 1144             return wrap_fake_exception(
   1145                 lambda: run_node(tx.output, node, args, kwargs, nnmodule)
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/utils.py in wrap_fake_exception(fn)
    805     try:
--> 806         return fn()
    807     except UnsupportedFakeTensorException as e:
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/utils.py in <lambda>()
   1144             return wrap_fake_exception(
-> 1145                 lambda: run_node(tx.output, node, args, kwargs, nnmodule)
   1146             )
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/utils.py in run_node(output_graph, node, args, kwargs, nnmodule)
   1197     except Exception as e:
-> 1198         raise RuntimeError(
   1199             f"Failed running {op} {node.target}(*{args}, **{kwargs}):\n{e}\n(scroll up for backtrace)"
RuntimeError: Failed running call_function <function layer_norm at 0x7fb50495c5e0>(*(FakeTensor(FakeTensor(..., device='meta', size=(s0, s1)), cpu), (128,), FakeTensor(Parameter(FakeTensor(..., device='meta', size=(128,), requires_grad=True)), cpu), FakeTensor(Parameter(FakeTensor(..., device='meta', size=(128,), requires_grad=True)), cpu), FakeTensor(FakeTensor(..., device='meta', size=()), cpu)), **{}):
tried to get Double out of SymFloat
(scroll up for backtrace)

The above exception was the direct cause of the following exception:
TorchRuntimeError                         Traceback (most recent call last)
<ipython-input-33-58348d11309a> in <module>
     24 mod = Foo(128)
     25 inp = torch.randn(3, 128)
---> 26 gm, _ = torchdynamo.export(mod, inp, aten_graph=True, tracing_mode="symbolic")
     27 print(gm.graph)
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/eval_frame.py in export(f, aten_graph, decomposition_table, tracing_mode, *args, **kwargs)
    602         )(f)
    603         # TODO(voz): We may have instances of `f` that mutate inputs, we should track sideffects and reject.
--> 604         result_traced = opt_f(*args, **kwargs)
    605     remove_from_cache(f)
    606 
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1486                 or _global_backward_pre_hooks or _global_backward_hooks
   1487                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1488             return forward_call(*args, **kwargs)
   1489         # Do not call functions when jit is used
   1490         full_backward_hooks, non_full_backward_hooks = [], []
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/eval_frame.py in forward(self, *args, **kwargs)
     80 
     81     def forward(self, *args, **kwargs):
---> 82         return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
     83 
     84 
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/eval_frame.py in _fn(*args, **kwargs)
    209             dynamic_ctx.__enter__()
    210             try:
--> 211                 return fn(*args, **kwargs)
    212             finally:
    213                 set_eval_frame(prior)
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/eval_frame.py in catch_errors(frame, cache_size)
    330 
    331         with compile_lock:
--> 332             return callback(frame, cache_size, hooks)
    333 
    334     catch_errors._torchdynamo_orig_callable = callback  # type: ignore[attr-defined]
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/convert_frame.py in _fn(*args, **kwargs)
    101         torch.fx.graph_module._forward_from_src = fx_forward_from_src_skip_result
    102         try:
--> 103             return fn(*args, **kwargs)
    104         finally:
    105             torch._C._set_grad_enabled(prior_grad_mode)
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/convert_frame.py in _convert_frame_assert(frame, cache_size, hooks)
    259         initial_grad_state = torch.is_grad_enabled()
    260 
--> 261         return _compile(
    262             frame.f_code,
    263             frame.f_globals,
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/utils.py in time_wrapper(*args, **kwargs)
    160                 compilation_metrics[key] = []
    161             t0 = time.time()
--> 162             r = func(*args, **kwargs)
    163             time_spent = time.time() - t0
    164             # print(f"Dynamo timer: key={key}, latency={latency:.2f} sec")
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/convert_frame.py in _compile(code, globals, locals, builtins, compiler_fn, one_graph, export, hooks, frame)
    321         for attempt in itertools.count():
    322             try:
--> 323                 out_code = transform_code_object(code, transform)
    324                 orig_code_map[out_code] = code
    325                 break
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/bytecode_transformation.py in transform_code_object(code, transformations, safe)
    337     propagate_line_nums(instructions)
    338 
--> 339     transformations(instructions, code_options)
    340 
    341     fix_vars(instructions, code_options)
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/convert_frame.py in transform(instructions, code_options)
    308             mutated_closure_cell_contents,
    309         )
--> 310         tracer.run()
    311         output = tracer.output
    312         assert output is not None
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/symbolic_convert.py in run(self)
   1713     def run(self):
   1714         _step_logger()(logging.INFO, f"torchdynamo start tracing {self.f_code.co_name}")
-> 1715         super().run()
   1716 
   1717     def match_nested_cell(self, name, cell):
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/symbolic_convert.py in run(self)
    562                 self.instruction_pointer is not None
    563                 and not self.output.should_exit
--> 564                 and self.step()
    565             ):
    566                 pass
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/symbolic_convert.py in step(self)
    525             if not hasattr(self, inst.opname):
    526                 unimplemented(f"missing: {inst.opname}")
--> 527             getattr(self, inst.opname)(inst)
    528 
    529             return inst.opname != "RETURN_VALUE"
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/symbolic_convert.py in wrapper(self, inst)
    331             reason = None
    332             try:
--> 333                 return inner_fn(self, inst)
    334             except Unsupported as excp:
    335                 if self.has_backedge() and self.should_compile_partial_graph():
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/symbolic_convert.py in CALL_FUNCTION(self, inst)
    988         args = self.popn(inst.argval)
    989         fn = self.pop()
--> 990         self.call_function(fn, args, {})
    991 
    992     @break_graph_if_unsupported(push=1)
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/symbolic_convert.py in call_function(self, fn, args, kwargs)
    459             for x in itertools.chain(args, kwargs.values())
    460         )
--> 461         self.push(fn.call_function(self, args, kwargs))
    462 
    463     def update_locals_and_stack(self, oldvar: VariableTracker, newvar: VariableTracker):
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/variables/torch.py in call_function(self, tx, args, kwargs)
    469                     fn_ = sym_sqrt
    470 
--> 471             tensor_variable = wrap_fx_proxy(
    472                 tx=tx,
    473                 proxy=tx.output.create_proxy(
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/variables/builder.py in wrap_fx_proxy(tx, proxy, example_value, **options)
    754 
    755 def wrap_fx_proxy(tx, proxy, example_value=None, **options):
--> 756     return wrap_fx_proxy_cls(
    757         target_cls=TensorVariable,
    758         tx=tx,
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/variables/builder.py in wrap_fx_proxy_cls(target_cls, tx, proxy, example_value, ignore_subclass, **options)
    789     with preserve_rng_state():
    790         if example_value is None:
--> 791             example_value = get_fake_value(proxy.node, tx)
    792 
    793         # Handle recursive calls here
/mnt/xarfuse/uid-245563/fcd20915-seed-nspid4026531836_cgpid15299599-ns-4026531840/torch/_dynamo/utils.py in get_fake_value(node, tx)
   1163         ):
   1164             unimplemented("guard on data-dependent symbolic int/float")
-> 1165         raise TorchRuntimeError() from e
   1166 
   1167 
TorchRuntimeError: 

from user code:
   File "<ipython-input-33-58348d11309a>", line 15, in forward
    output = torch.nn.functional.layer_norm(

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Versions

master 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel @mlazos @yanboliang @Xia-Weiwen @desertfire

**Comment by bdhirsh** [comment]
It looks like it's because we're trying to pass a SymFloat into an aten layer_norm kernel, but `at::layer_norm`'s schema currently is marked as taking in a float.

Maybe we just need to allow SymFloats in our native schemas? Or maybe there's another option eluding me.

**Comment by ngimel** [comment]
Yeah but it shouldn't be a float, we should specialize on `eps`, at least in the near term

**Comment by ezyang** [comment]
I think a simple short term fix is to make float arguments in Python arg parser induce a guard automatically. This can be done without adding SymFloat schema support (which is the correct long term fix).

**Comment by ezyang** [comment]
OK, the *real* answer to this is to run the export with specialize_int_float = True, which will force self.torch_module.eps to be specialized and then everything is fine.

I actually did look into what would it take to solve the proximal problem. It's a rabbit hole.

First, you fix float parsing to accept SymFloat but induce a guard in this case:

```
diff --git a/torch/csrc/utils/python_arg_parser.cpp b/torch/csrc/utils/python_arg_parser.cpp
index 62b536d0b2d..8f8158a19e6 100644
--- a/torch/csrc/utils/python_arg_parser.cpp
+++ b/torch/csrc/utils/python_arg_parser.cpp
@@ -779,6 +779,12 @@ auto FunctionParameter::check(
       if (THPUtils_checkDouble(obj)) {
         return true;
       }
+      // HACK: we allow symbolic type but will force
+      // a guard.  Remove this when SymFloat supported
+      // in native_functions.yaml
+      if (torch::is_symint(py::handle(obj)) || torch::is_symfloat(py::handle(obj))) {
+        return true;
+      }
       if (THPVariable_Check(obj)) {
         const auto& var = THPVariable_Unpack(obj);
         return !var.requires_grad() && var.dim() == 0;
diff --git a/torch/csrc/utils/python_arg_parser.h b/torch/csrc/utils/python_arg_parser.h
index d9d14a83a9c..9f30de8e264 100644
--- a/torch/csrc/utils/python_arg_parser.h
+++ b/torch/csrc/utils/python_arg_parser.h
@@ -942,8 +942,18 @@ inline c10::optional<double> PythonArgs::toDoubleOptional(int i) {
 }
 
 inline double PythonArgs::toDouble(int i) {                                                          
-  if (!args[i])
+  if (!args[i]) {
     return signature.params[i].default_double;
+  }
+  // HACK: we allow symbolic type but will force
+  // a guard.  Remove this when SymFloat supported
+  // in native_functions.yaml
+  if (torch::is_symfloat(py::handle(args[i]))) {
+    return py::cast<c10::SymFloat>(args[i]).guard_float(__FILE__, __LINE__);
+  }
+  if (torch::is_symint(py::handle(args[i]))) {
+    return py::cast<c10::SymInt>(args[i]).guard_int(__FILE__, __LINE__);
+  }
   return THPUtils_unpackDouble(args[i]);
 }
 
```

However, it turns out you're not getting a SymFloat as eps here; you're getting a FakeTensor! How come? It's because of how we make unspecialized values: we turn them into one element tensors, unless it's an int and you are dynamic shapes. OK, so you fix that...

```
diff --git a/torch/_dynamo/variables/builder.py b/torch/_dynamo/variables/builder.py
index fa4eca12890..62edaca73fb 100644
--- a/torch/_dynamo/variables/builder.py
+++ b/torch/_dynamo/variables/builder.py
@@ -720,17 +720,17 @@ class VariableBuilder:
         else:
             if (
                 config.dynamic_shapes
-                and isinstance(value, int)
+                and isinstance(value, (int, float, bool))
                 and not is_constant_source(self.get_source())
             ):
                 shape_env = self.tx.output.shape_env
-                wrapped_value = shape_env.create_symintnode(
+                wrapped_value = shape_env.create_sym_number(
+                    type(value),
                     shape_env.create_symbol(value, source=self.source)
                 )
                 self.tx.output.tracked_fakes.append(
                     TrackedFake(wrapped_value, self.source)
                 )
-                # TODO: Do float
             else:
                 # TODO: Eliminate this case entirely
                 wrapped_value = torch.tensor(value)
```

But you've got a problem, you've got to have some generalized way of creating SymFloat (the same way you can create SymInt with create_symintnode). You can do the "obvious" thing and just generalize `create_symintnode`

```
diff --git a/torch/fx/experimental/symbolic_shapes.py b/torch/fx/experimental/symbolic_shapes.py
index 0335d05f2cc..ae0f61e67a2 100644
--- a/torch/fx/experimental/symbolic_shapes.py
+++ b/torch/fx/experimental/symbolic_shapes.py
@@ -824,6 +824,17 @@ class ShapeEnv(object):
     def create_symintnode(self, sym: "sympy.Expr"):
         return SymInt(SymNode(sym, self, int))
 
+    def create_sym_number(self, pytype, sym: "sympy.Expr"):
+        if pytype is int:
+            wrapper = SymInt
+        elif pytype is float:
+            wrapper = SymFloat
+        elif pytype is bool:
+            wrapper = SymBool
+        else:
+            raise AssertionError(f"invalid type {pytype}")
+        return wrapper(SymNode(sym, self, pytype))
+
     def create_unbacked_symfloat(self):
         symbol = Symbol(f"f{next(self.unbacked_symfloat_counter)}")
         symbol.stack = ''.join(traceback.format_list(traceback.extract_stack()[:-1]))
```

But this doesn't even make the export call pass, because the epsilon parameter access is being promoted into a full-fledged input and so you get the dreaded Dynamo input/output is not consistent with traced input/output

```
Traceback (most recent call last):
  File "/data/users/ezyang/b/pytorch/e.py", line 26, in <module>
    gm, _ = torchdynamo.export(mod, inp, aten_graph=True, tracing_mode="symbolic")
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/eval_frame.py", line 599, in export
    matched_input_elements_positions = produce_matching(flat_args, graph_captured_input)
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/eval_frame.py", line 547, in produce_matching
    raise AssertionError(
AssertionError: Dynamo input/output is not consistent with traced input/output
```

"But wait!" You might say. "Even though epsilon wasn't supposed to be an input for export, it seems like a reasonable input for regular PT2." So you try that.

```
import torch
import torch._dynamo as torchdynamo

class Foo(torch.nn.Module):
    def __init__(
        self,
        input_dim,
    ):
        super().__init__()
        self.torch_module = torch.nn.LayerNorm(
            input_dim, eps=1e-5, elementwise_affine=True
        )

    def forward(self, input):
        output = torch.nn.functional.layer_norm(
            input,
            self.torch_module.normalized_shape,
            self.torch_module.weight,
            self.torch_module.bias,
            self.torch_module.eps,
        ).type_as(input)
        return output

mod = Foo(128)
inp = torch.randn(3, 128)
torch.compile(mod, dynamic=True, backend='inductor')(inp)
```

But oh yeah, and you ALSO have to update guard generation to work for SymFloat now that your float guard is now in the ShapeEnv subsystem

```
@@ -965,8 +976,8 @@ class ShapeEnv(object):
         # not be available to inner levels.  For example, Dynamo can guard on
         # tensors that never actually become graph arguments (they are
         # pruned).  In this case, only Dynamo knows about these arguments.
-        def track_symint(source, val):
-            if isinstance(val, SymInt):
+        def track_sym(source, val):
+            if isinstance(val, SymTypes):
                 s = val.node.expr
 
                 if isinstance(s, sympy.Symbol):
@@ -976,21 +987,21 @@ class ShapeEnv(object):
 
                 input_guards.append((source, s))
             else:
-                input_guards.append((source, sympy.Integer(val)))
+                input_guards.append((source, sympy.sympify(val)))
 
         for t, source in zip(placeholders, sources):
             assert isinstance(source, Source)
             if t is None:
                 continue
-            if isinstance(t, SymInt):
-                track_symint(source, t)
+            if isinstance(t, SymTypes):
+                track_sym(source, t)
                 continue
             assert isinstance(t, torch.Tensor)
             for i, s in enumerate(t.size()):
-                track_symint(TensorPropertySource(source, TensorProperty.SIZE, i), s)
+                track_sym(TensorPropertySource(source, TensorProperty.SIZE, i), s)
             for i, s in enumerate(t.stride()):
-                track_symint(TensorPropertySource(source, TensorProperty.STRIDE, i), s)
-            track_symint(TensorPropertySource(source, TensorProperty.STORAGE_OFFSET), t.storage_offset())
+                track_sym(TensorPropertySource(source, TensorProperty.STRIDE, i), s)
+            track_sym(TensorPropertySource(source, TensorProperty.STORAGE_OFFSET), t.storage_offset())
 
         # 1. Every input must equal the final simplified symbolic expression
         #    stored on the placeholder.  Given a placeholder (s0*2, s1),
```

But even then it doesn't even compile with inductor

```
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/cpp.py", line 1784, in codegen_define_and_call                 
    arg_defs, call_args, arg_types = self.args.cpp_argdefs()                                                                
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/common.py", line 278, in cpp_argdefs                           
    {name: val.get_dtype() for name, val in V.graph.graph_inputs.items()}      
  File "/data/users/ezyang/b/pytorch/torch/_inductor/codegen/common.py", line 278, in <dictcomp>
    {name: val.get_dtype() for name, val in V.graph.graph_inputs.items()}                   
AttributeError: 'Symbol' object has no attribute 'get_dtype'  
```

and it doesn't work with aot_eager either:

```
  File "/data/users/ezyang/b/pytorch/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_functorch/aot_autograd.py", line 2512, in forward
    return compiled_fn(full_args)
  File "/data/users/ezyang/b/pytorch/torch/_functorch/aot_autograd.py", line 996, in g
    return f(*args)
  File "/data/users/ezyang/b/pytorch/torch/_functorch/aot_autograd.py", line 2071, in debug_compiled_function
    assert not isinstance(a, Tensor)
AssertionError
```

and if you look at the guards they're wrong too

```
            shape_env '' SHAPE_ENV                                                                                          
            {                                                                                                               
                'guard_types': ['SHAPE_ENV', 'SHAPE_ENV', 'SHAPE_ENV', 'SHAPE_ENV', 'SHAPE_ENV', 'SHAPE_ENV', 'SHAPE_ENV', '
SHAPE_ENV', 'SHAPE_ENV', 'SHAPE_ENV', 'SHAPE_ENV', 'SHAPE_ENV'],                                                            
                'code': ['input.size()[1] == 128', 'input.stride()[0] == 128', 'input.stride()[1] == 1', 'input.storage_offs
et() == 0', 'self.torch_module.weight.size()[0] == 128', 'self.torch_module.weight.stride()[0] == 1', 'self.torch_module.wei
ght.storage_offset() == 0', 'self.torch_module.bias.size()[0] == 128', 'self.torch_module.bias.stride()[0] == 1', 'self.torc
h_module.bias.storage_offset() == 0', 'input.size()[0] != 0 and input.size()[0] != 1', 'self.torch_module.eps != 0 and self.
torch_module.eps != 1'],                                                                                                    
                'obj_weakref': None                                                                                         
                'guarded_class': None                                                                                       
            }
```

oops shouldn't have used create_symbol for floating point symbols...

**Comment by ezyang** [comment]
For what @tugsbayasgalan cares about we just need to fix the specialize_int_float situation. @voznesenskym I think this rolls into forbidding specialization (what we used to call guard inversion), but it's the inverse thing where we need to get export specializing everything that isn't marked as dynamic.
