### ISSUE TITLE
`report_compile_source_on_error` does not work with python 3.11

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#94189]
Namely, running the current test in `test_utils.py` leads to:
```
Traceback (most recent call last):
  File "/home/albandes/local/pytorch/3.11_debug_source/test/test_utils.py", line 900, in test_basic
    out["f"](1)
  File "/tmp/tmpdrjv3dey.py", line 3, in f
    raise RuntimeError()  # HEYA
python: Objects/codeobject.c:990: PyCode_Addr2Location: Assertion `addrq >= 0 && addrq < _PyCode_NBYTES(co)' failed.
Aborted (core dumped)
```

Looks like the current line pointer is not correct? This needs investigation.

**Comment by malfet** [comment]
I have 3.11 build, let me try to reproduce...

**Comment by malfet** [comment]
This has been fixed a while back, closing
