### ISSUE TITLE
torch.var's backward may have a bug？

### ISSUE THREAD

**Issue by BBuf** [pytorch/pytorch#94184]
when I run the code below :

```python
import torch

x = torch.tensor([[1.0]], requires_grad=True)
print(x.shape)
y = x.var()
y.backward()
print(x.grad)
```

It will throw the following error message：

```
torch.Size([1, 1])
Traceback (most recent call last):
  File "../../debug.py", line 6, in <module>
    y.backward()
  File "/home/zhangxiaoyu/miniconda3/envs/clang10/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/zhangxiaoyu/miniconda3/envs/clang10/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function VarBackward0 returned an invalid gradient at index 0 - got [] but expected shape compatible with [1, 1]
```

From the perspective of automatic differentiation, `x.grad` should return a tensor with shape (1, 1) instead of throwing an exception ？

PyTorch verison：

```bash
torch                    1.13.1
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by mingfeima** [comment]
@min-jean-cho so we need to update the `derivatives.yaml`, return `Tensor()` when grad is none?

**Comment by min-jean-cho** [comment]
Thanks @mingfeima, `x.grad` should be the same shape as `x`. 
I think the root cause is that `is_expandable_to_shape` returning `false` for when gradient is `nan`. Gradient of sample unbiased variance is `nan` when there's just one sample (i.e., product of dim=1 such as `[1, 1, 1]`, `[1, 1]`).

```python
import torch

x = torch.zeros([1, 1, 1], requires_grad=True) 
y = x.var(unbiased=True) # unbiased=False is fine, no divide by zero
print("var(x): ", y) # if one sample, unbiased variance is nan (undefined); if more than one sample (e.g., [1, 2]), variance is 0
y.backward()
print("d var(x)/dx: ", x.grad) # if one sample, grad is nan; if more than one sample, grad is 0
```
