### ISSUE TITLE
torchdynamo.export doesn't work with float multiplication

### ISSUE THREAD

**Issue by tugsbayasgalan** [pytorch/pytorch#94293]
### 🐛 Describe the bug

```python
class A(torch.nn.Module):
    def __init__(self, feature=4.0):
        super().__init__()
        self.feature = feature

    def forward(self, x):
        return int(x.shape[-1] * self.feature // 3)
       

torchdynamo.config.dynamic_shapes = True
torchdynamo.config.specialize_int_float = False
gm, _ = torchdynamo.export(A(), torch.ones(6, 1), aten_graph=True, tracing_mode="symbolic")
print(gm.graph)
print(gm(torch.ones(6, 1)))
```
Gives following error:
```
[2023-02-07 01:02:45,906] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing forward
[2023-02-07 01:02:45,910] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo done tracing forward (RETURN_VALUE)
[2023-02-07 01:02:45,912] torch._dynamo.output_graph: [INFO] Step 2: calling compiler function dynamo_normalization_capturing_compiler
[2023-02-07 01:02:45,912] torch._dynamo.output_graph: [INFO] Step 2: done compiler function dynamo_normalization_capturing_compiler
Traceback (most recent call last):
  File "/mnt/xarfuse/uid-25280/92716d6a-seed-nspid4026533181_cgpid14161962-ns-4026533178/torch/fx/graph_module.py", line 269, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/mnt/xarfuse/uid-25280/92716d6a-seed-nspid4026533181_cgpid14161962-ns-4026533178/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.44", line 8, in forward
    floordiv = mul.__floordiv__(3);  mul = None
AttributeError: 'NotImplementedType' object has no attribute '__floordiv__'

Call using an FX-traced Module, line 8 of the traced Module's generated forward function:
    mul = getitem_1.__mul__(4.0);  getitem_1 = None
    floordiv = mul.__floordiv__(3);  mul = None

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    sym_int = torch.sym_int(floordiv);  floordiv = None

    return (sym_int,)

'NotImplementedType' object has no attribute '__floordiv__'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-abb9cc343398> in <module>
     10 torchdynamo.config.dynamic_shapes = True
     11 torchdynamo.config.specialize_int_float = False
---> 12 gm, _ = torchdynamo.export(A(), torch.ones(6, 1), aten_graph=True, tracing_mode="symbolic")
     13 print(gm.graph)
     14 print(gm(torch.ones(6, 1)))
/mnt/xarfuse/uid-25280/92716d6a-seed-nspid4026533181_cgpid14161962-ns-4026533178/torch/_dynamo/eval_frame.py in export(f, aten_graph, decomposition_table, tracing_mode, *args, **kwargs)
    591         )(f)
    592         # TODO(voz): We may have instances of `f` that mutate inputs, we should track sideffects and reject.
--> 593         result_traced = opt_f(*args, **kwargs)
    594     remove_from_cache(f)
    595 
/mnt/xarfuse/uid-25280/92716d6a-seed-nspid4026533181_cgpid14161962-ns-4026533178/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []
/mnt/xarfuse/uid-25280/92716d6a-seed-nspid4026533181_cgpid14161962-ns-4026533178/torch/_dynamo/eval_frame.py in forward(self, *args, **kwargs)
     80 
     81     def forward(self, *args, **kwargs):
---> 82         return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
     83 
     84 
/mnt/xarfuse/uid-25280/92716d6a-seed-nspid4026533181_cgpid14161962-ns-4026533178/torch/_dynamo/eval_frame.py in _fn(*args, **kwargs)
    207             dynamic_ctx.__enter__()
    208             try:
--> 209                 return fn(*args, **kwargs)
    210             finally:
    211                 set_eval_frame(prior)
<ipython-input-16-abb9cc343398> in forward(self, x)
      4         self.feature = feature
      5 
----> 6     def forward(self, x):
      7         return int(x.shape[-1] * self.feature // 3)
      8 
/mnt/xarfuse/uid-25280/92716d6a-seed-nspid4026533181_cgpid14161962-ns-4026533178/torch/_dynamo/eval_frame.py in _fn(*args, **kwargs)
    207             dynamic_ctx.__enter__()
    208             try:
--> 209                 return fn(*args, **kwargs)
    210             finally:
    211                 set_eval_frame(prior)
/mnt/xarfuse/uid-25280/92716d6a-seed-nspid4026533181_cgpid14161962-ns-4026533178/torch/_dynamo/eval_frame.py in result_capturing_wrapper(*graph_inputs)
    575             graph_captured_input = graph_inputs
    576             assert graph is not None
--> 577             graph_captured_result = graph(*graph_inputs)
    578             return graph_captured_result
    579 
/mnt/xarfuse/uid-25280/92716d6a-seed-nspid4026533181_cgpid14161962-ns-4026533178/torch/fx/graph_module.py in call_wrapped(self, *args, **kwargs)
    658 
    659         def call_wrapped(self, *args, **kwargs):
--> 660             return self._wrapped_call(self, *args, **kwargs)
    661 
    662         cls.__call__ = call_wrapped
/mnt/xarfuse/uid-25280/92716d6a-seed-nspid4026533181_cgpid14161962-ns-4026533178/torch/fx/graph_module.py in __call__(self, obj, *args, **kwargs)
    275                 print(_WrappedCall._generate_error_message(topmost_framesummary),
    276                       file=sys.stderr)
--> 277                 raise e.with_traceback(None)
    278             else:
    279                 raise e
AttributeError: 'NotImplementedType' object has no attribute '__floordiv__'
```

I think this happens when we try to extract example_value by running the node which throws an NotImplemented exception which is incorrectly wrapped as python value. 

cc: @ezyang @voznesenskym @Chillee 

### Versions

master

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @avikchaudhuri @gmagogsfm @zhxchen17 @angelayi @suo @ydwu4 @soumith @ngimel @yanboliang @Xia-Weiwen @desertfire

**Comment by ezyang** [comment]
@jbschlosser do you think you could look into this? Looks related to reversibility, since a NotImplemented is showing up

**Comment by williamwen42** [comment]
@tugsbayasgalan Is this still a problem?

**Comment by zhxchen17** [comment]
@williamwen42  I guess I will close this because I hear no one complaining about this anymore lol
