### ISSUE TITLE
`TypeError: super(type, obj): obj must be an instance or subtype of type` has no type error in training with EAGER backend

### ISSUE THREAD

**Issue by LeoXing1996** [pytorch/pytorch#94299]
### 🐛 Describe the bug

Training GAN models with eager backend got NotImplementedError: UserDefinedClassVariable() has no type.

PR #93310 attempted to fix this issue but the same error still occurs.

When I tried to set torch._dynamo.config.verbose=True at the start of my code, `NotImplementedError` was raised but training continued.

### Error logs

```
02/06 20:56:28 - mmengine - INFO - Working directory: work_dirs/biggan-pt20
02/06 20:56:28 - mmengine - INFO - Log directiry: /mnt/petrelfs/xingzhening/mmedit-pt20/work_dirs/biggan-pt20/20230206_205625
02/06 20:56:28 - mmengine - WARNING - The "dataset" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:56:31 - mmengine - WARNING - The "transform" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:03 - mmengine - WARNING - The "data sampler" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:03 - mmengine - WARNING - The "optimizer wrapper constructor" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:03 - mmengine - WARNING - The "optimizer" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:03 - mmengine - WARNING - The "optim_wrapper" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:03 - mmengine - WARNING - The "loop" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:35 - mmengine - WARNING - The "evaluator" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:35 - mmengine - WARNING - The "metric" registry in mmedit did not set import location. Fallback to call `mmedit.utils.register_all_modules` instead.
02/06 20:57:35 - mmengine - INFO - Text logs will be saved to work_dirs/pt20/biggan-pt20 after the training process.
02/06 20:57:35 - mmengine - INFO - Checkpoints will be saved to work_dirs/pt20/biggan-pt20.
[2023-02-06 20:57:35,948] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT train_step /mnt/petrelfs/xingzhening/mmengine-compile/mmengine/model/wrappers/seperate_distributed.py line 89 
due to: 
Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 58, in const_getattr
    return getattr(super(search_type, type_to_use), name)
TypeError: super(type, obj): obj must be an instance or subtype of type

from user code:
   File "/mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/base_models/base_gan.py", line 438, in train_step
    message_hub = MessageHub.get_current_instance()
  File "/mnt/petrelfs/xingzhening/mmengine-compile/mmengine/logging/message_hub.py", line 100, in get_current_instance
    return super().get_current_instance()

Set torch._dynamo.config.verbose=True for more information


[2023-02-06 20:57:35,978] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT train_step /mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/base_models/base_gan.py line 420 
due to: 
Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 58, in const_getattr
    return getattr(super(search_type, type_to_use), name)
TypeError: super(type, obj): obj must be an instance or subtype of type

from user code:
   File "/mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/base_models/base_gan.py", line 438, in train_step
    message_hub = MessageHub.get_current_instance()
  File "/mnt/petrelfs/xingzhening/mmengine-compile/mmengine/logging/message_hub.py", line 100, in get_current_instance
    return super().get_current_instance()

Set torch._dynamo.config.verbose=True for more information


[2023-02-06 20:57:43,635] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:48,062] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:48,492] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:48,523] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT disc_loss /mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/editors/wgan_gp/wgan_gp.py line 32 
due to: 
Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/base.py", line 209, in reconstruct
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: reconstruct: ConstantVariable(dict)

Set torch._dynamo.config.verbose=True for more information


[2023-02-06 20:57:48,538] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:57,963] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:57,979] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-02-06 20:57:57,995] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT gen_loss /mnt/petrelfs/xingzhening/mmedit-pt20/mmedit/models/editors/wgan_gp/wgan_gp.py line 61 
due to: 
Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/base.py", line 209, in reconstruct
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: reconstruct: ConstantVariable(dict)

Set torch._dynamo.config.verbose=True for more information


02/06 20:58:24 - mmengine - INFO - Iter(train) [   100/160000]  generator.lr: 1.0000e-04 discriminator.lr: 1.0000e-04  eta: 21:41:52  time: 0.2578  data_time: 0.0332  memory: 9478  loss: -124.6310  loss_disc_fake: -91.5469  loss_disc_real: -90.6519  loss_gp: 57.5678  loss_gen: 118.4739
```

### Minified repro

1. Install dependencied of OpenMMLab

```
ninja
git+https://github.com/open-mmlab/mmengine@experimental/compile
git+https://github.com/open-mmlab/mmcv@2.x
```

3. Install MMEditing from source

```bash
git clone git@github.com:open-mmlab/mmediting.git
cd mmediting
git checkout dev-1.x
pip install -r requirements.txt
pip install -e .
```

4. Launch training

```bash
# all GAN models failed since they all build upon `BaseGAN`
python tools/train.py configs/wgan-gp/wgangp_GN_1xb64-160kiters_celeba-cropped-128x128.py \
    --cfg-options compile.target='train_step' compile.backend='eager'
```

### Versions

Pytorch version: 2.0.0.dev20230202+cu116

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by yanboliang** [comment]
@LeoXing1996 
These are different errors, the original error ```NotImplementedError: UserDefinedClassVariable() has no type``` has been fixed. These are two new patterns that we don't support yet. Not all ```NotImplementedError``` are the same error.

**Comment by LeoXing1996** [comment]
@yanboliang, thanks for your response. I saw the error raised at `return super().get_current_instance()` and regarded them as the same error 😢 .

**Comment by yanboliang** [comment]
@LeoXing1996 #94547 will fix the first issue I mentioned. I can't reproduce the second issue, can you paste your whole debug log here or prepare a smaller repro?

**Comment by LeoXing1996** [comment]
@yanboliang, thanks for your hard work. I add patch #94547 manually and here is my [full debug log](https://drive.google.com/file/d/11hWonVTzPGMUQcHsukrvVj4kX6ZH0z0j/view?usp=sharing).
