### ISSUE TITLE
[pt2]  MMSeg meets torch._dynamo.exc.BackendCompilerFailed

### ISSUE THREAD

**Issue by xiexinch** [pytorch/pytorch#94302]
### Error logs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/petrelfs/xiexinchen/mmsegv2-pt2.0/repro.py", line 116, in <module>
    res = run_fwd_maybe_bwd(opt_mod, args)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 624, in run_fwd_maybe_bwd
    out = gm(args)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 996, in g
    return f(*args)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 403, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 261, in _convert_frame_assert
    return _compile(
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 160, in time_wrapper
    r = func(*args, **kwargs)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 323, in _compile
    out_code = transform_code_object(code, transform)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 310, in transform
    tracer.run()
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1727, in run
    super().run()
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1793, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 563, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 610, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 160, in time_wrapper
    r = func(*args, **kwargs)
  File "/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 697, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: compiler_fn raised Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.index.Tensor(*(FakeTensor(FakeTensor(..., device='meta', size=(3, 512, 1024), dtype=torch.uint8), cuda:0), [tensor([2, 1, 0], device='cuda:0')]), **{}) 

### Minified repro

**Minified repro**

1. Install dependencied of OpenMMLab

```shell
ninja
git+https://github.com/open-mmlab/mmengine@experimental/compile
git+https://github.com/open-mmlab/mmcv@2.x

git clone git@github.com:open-mmlab/mmsegmentation.git
cd mmsegmentation
git checkout dev-1.x
pip install -r requirements.txt
pip install -e .
```

2. Modify the configs/_base_/default_runtime.py

```python
compile = dict(
    target='train_step',  # (train_step, forward, model)
    verbose=True,
    backend='aot_eager',  
    dynamic=False, 
)
```

3. Launch training

```shell
python tools/train.py configs/stdc/stdc1_in1k-pre_4xb12-80k_cityscapes-512x1024.py     
```

4. repro.py

```python

from math import inf
import torch
from torch import tensor, device
import torch.fx as fx
import torch._dynamo
from torch._dynamo.testing import rand_strided
from torch._dynamo.debug_utils import run_fwd_maybe_bwd
from torch._dynamo.debug_utils import same_two_models

import torch._dynamo.config
import torch._inductor.config
torch._dynamo.config.load_config(b'\x80\x04\x95\'\x08\x00\x00\x00\x00\x00\x00}\x94(\x8c\x08__name__\x94\x8c\x14torch._dynamo.config\x94\x8c\x07__doc__\x94N\x8c\x0b__package__\x94\x8c\rtorch._dynamo\x94\x8c\n__loader__\x94\x8c\x1a_frozen_importlib_external\x94\x8c\x10SourceFileLoader\x94\x93\x94)\x81\x94}\x94(\x8c\x04name\x94h\x02\x8c\x04path\x94\x8cb/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/config.py\x94ub\x8c\x08__spec__\x94\x8c\x11_frozen_importlib\x94\x8c\nModuleSpec\x94\x93\x94)\x81\x94}\x94(h\x0ch\x02\x8c\x06loader\x94h\n\x8c\x06origin\x94h\x0e\x8c\x0cloader_state\x94N\x8c\x1asubmodule_search_locations\x94N\x8c\r_set_fileattr\x94\x88\x8c\x07_cached\x94\x8c{/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_dynamo/__pycache__/config.cpython-310.pyc\x94\x8c\r_initializing\x94\x89ub\x8c\x08__file__\x94h\x0e\x8c\n__cached__\x94h\x1b\x8c\x07abspath\x94\x8c\tposixpath\x94h\x1f\x93\x94\x8c\x07dirname\x94h h"\x93\x94\x8c\x0eHAS_REFS_PRIMS\x94\x88\x8c\tlog_level\x94K\x1e\x8c\x0boutput_code\x94\x89\x8c\rlog_file_name\x94N\x8c\x07verbose\x94\x88\x8c\x11output_graph_code\x94\x89\x8c\x12verify_correctness\x94\x89\x8c\x12minimum_call_count\x94K\x01\x8c\x15dead_code_elimination\x94\x88\x8c\x10cache_size_limit\x94K@\x8c\x14specialize_int_float\x94\x88\x8c\x0edynamic_shapes\x94\x89\x8c\x10guard_nn_modules\x94\x89\x8c\x0cnormalize_ir\x94\x89\x8c\x1btraceable_tensor_subclasses\x94\x8f\x94\x8c\x0fsuppress_errors\x94\x89\x8c\x15replay_record_enabled\x94\x89\x8c rewrite_assert_with_torch_assert\x94\x88\x8c\x12print_graph_breaks\x94\x89\x8c\x07disable\x94\x89\x8c*allowed_functions_module_string_ignorelist\x94\x8f\x94(\x8c\x0ctorch._prims\x94\x8c\rtorch._decomp\x94\x8c\rtorch.testing\x94\x8c\x13torch.distributions\x94\x8c\x0btorch._refs\x94\x90\x8c\x16capture_scalar_outputs\x94\x89\x8c\x19enforce_cond_guards_match\x94\x88\x8c\x0coptimize_ddp\x94\x88\x8c\x1araise_on_ctx_manager_usage\x94\x88\x8c\x1craise_on_unsafe_aot_autograd\x94\x89\x8c\rdynamo_import\x94\x8c\rtorch._dynamo\x94\x8c\x0finductor_import\x94\x8c\x0ftorch._inductor\x94\x8c\x18error_on_nested_fx_trace\x94\x88\x8c\tallow_rnn\x94\x89\x8c\x08base_dir\x94\x8cJ/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages\x94\x8c\x0edebug_dir_root\x94\x8c:/mnt/petrelfs/xiexinchen/mmsegv2-pt2.0/torch_compile_debug\x94\x8c)DO_NOT_USE_legacy_non_fake_example_inputs\x94\x89\x8c\x15_AccessLimitingConfig\x94}\x94(\x8c\n__module__\x94h\x02\x8c\x0b__setattr__\x94\x8c\x14torch._dynamo.config\x94\x8c!_AccessLimitingConfig.__setattr__\x94\x93\x94h\x03Nu\x8c\x15_allowed_config_names\x94\x8f\x94(\x8c\x05torch\x94h\x06hDh.h\x1fh$hJhPh4h"h\x1eh\x03h+h6\x8c\nModuleType\x94hO\x8c\x02os\x94hEhGh)\x8c\x0c__builtins__\x94h1hIh\x0fh&h*h%h9h0h/\x8c\x03sys\x94hBhChA\x8c!skipfiles_inline_module_allowlist\x94h2hM\x8c\x0brepro_level\x94h(\x8c\x07logging\x94h,h7\x8c\x12constant_functions\x94h\x1dh\'h8h@h5h\x01hKh\x04\x8c\x0eexternal_utils\x94h-\x8c\x0brepro_after\x94\x90\x8c\x1cget_config_serialization_fns\x94\x8c\x1atorch._dynamo.config_utils\x94hd\x93\x94u.')
torch._inductor.config.load_config(b'\x80\x04\x95@\t\x00\x00\x00\x00\x00\x00}\x94(\x8c\x08__name__\x94\x8c\x16torch._inductor.config\x94\x8c\x07__doc__\x94N\x8c\x0b__package__\x94\x8c\x0ftorch._inductor\x94\x8c\n__loader__\x94\x8c\x1a_frozen_importlib_external\x94\x8c\x10SourceFileLoader\x94\x93\x94)\x81\x94}\x94(\x8c\x04name\x94h\x02\x8c\x04path\x94\x8cd/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_inductor/config.py\x94ub\x8c\x08__spec__\x94\x8c\x11_frozen_importlib\x94\x8c\nModuleSpec\x94\x93\x94)\x81\x94}\x94(h\x0ch\x02\x8c\x06loader\x94h\n\x8c\x06origin\x94h\x0e\x8c\x0cloader_state\x94N\x8c\x1asubmodule_search_locations\x94N\x8c\r_set_fileattr\x94\x88\x8c\x07_cached\x94\x8c}/mnt/petrelfs/xiexinchen/anaconda3/envs/pt2.0/lib/python3.10/site-packages/torch/_inductor/__pycache__/config.cpython-310.pyc\x94\x8c\r_initializing\x94\x89ub\x8c\x08__file__\x94h\x0e\x8c\n__cached__\x94h\x1b\x8c\x05debug\x94\x89\x8c\x10disable_progress\x94\x88\x8c\x10verbose_progress\x94\x89\x8c\x0bcpp_wrapper\x94\x89\x8c\x03dce\x94\x89\x8c\x14static_weight_shapes\x94\x88\x8c\x0csize_asserts\x94\x88\x8c\x10pick_loop_orders\x94\x88\x8c\x0finplace_buffers\x94\x88\x8c\x11benchmark_harness\x94\x88\x8c\x0fepilogue_fusion\x94\x89\x8c\x15epilogue_fusion_first\x94\x89\x8c\x0cmax_autotune\x94\x89\x8c\x17realize_reads_threshold\x94K\x04\x8c\x17realize_bytes_threshold\x94M\xd0\x07\x8c\x1brealize_acc_reads_threshold\x94K\x08\x8c\x0ffallback_random\x94\x89\x8c\x12implicit_fallbacks\x94\x88\x8c\rprefuse_nodes\x94\x88\x8c\x0btune_layout\x94\x89\x8c\x11aggressive_fusion\x94\x89\x8c\x0fmax_fusion_size\x94K@\x8c\x1bunroll_reductions_threshold\x94K\x08\x8c\x0ecomment_origin\x94\x89\x8c\tis_fbcode\x94\x8c\x16torch._inductor.config\x94h7\x93\x94\x8c\x0fcompile_threads\x94K \x8c\x13kernel_name_max_ops\x94K\n\x8c\x0finductor_import\x94\x8c\x0ftorch._inductor\x94\x8c\rshape_padding\x94\x89\x8c\x0epermute_fusion\x94\x89\x8c\x1aprofiler_mark_wrapper_call\x94\x89\x8c\x03cpp\x94}\x94(\x8c\n__module__\x94h\x02\x8c\x07threads\x94J\xff\xff\xff\xff\x8c\x0fdynamic_threads\x94\x89\x8c\x07simdlen\x94N\x8c\x0emin_chunk_size\x94M\x00\x10\x8c\x03cxx\x94N\x8c\x03g++\x94\x86\x94\x8c\x15enable_kernel_profile\x94\x89h\x03Nu\x8c\x06triton\x94}\x94(hCh\x02\x8c\ncudagraphs\x94\x88\x8c\x10debug_sync_graph\x94\x89\x8c\x11debug_sync_kernel\x94\x89\x8c\x0bconvolution\x94\x8c\x04aten\x94\x8c\x0edense_indexing\x94\x89\x8c\tmax_tiles\x94K\x02\x8c\x12autotune_pointwise\x94\x88\x8c tiling_prevents_pointwise_fusion\x94\x88\x8c tiling_prevents_reduction_fusion\x94\x88\x8c\x14ordered_kernel_names\x94\x89\x8c\x18descriptive_kernel_names\x94\x89h\x03Nu\x8c\x05trace\x94}\x94(hCh\x02\x8c\x07enabled\x94\x89\x8c\tdebug_log\x94\x88\x8c\x08info_log\x94\x89\x8c\x08fx_graph\x94\x88\x8c\rir_pre_fusion\x94\x88\x8c\x0eir_post_fusion\x94\x88\x8c\x0boutput_code\x94\x88\x8c\rgraph_diagram\x94\x89\x8c\x0fcompile_profile\x94\x89\x8c\nupload_tar\x94Nh\x03Nu\x8c\x15InductorConfigContext\x94}\x94(hCh\x02\x8c\x0f__annotations__\x94}\x94(\x8c\rstatic_memory\x94\x8c\x08builtins\x94\x8c\x04bool\x94\x93\x94\x8c\x0ematmul_padding\x94hm\x8c\x0cmax_autotune\x94hm\x8c\x12triton_convolution\x94hk\x8c\x03str\x94\x93\x94\x8c\x17rematerialize_threshold\x94hk\x8c\x03int\x94\x93\x94\x8c\x1brematerialize_acc_threshold\x94huu\x8c\x05_save\x94h8\x8c\x1bInductorConfigContext._save\x94\x93\x94\x8c\x06_apply\x94h8\x8c\x1cInductorConfigContext._apply\x94\x93\x94\x8c\x08__init__\x94h8\x8c\x1eInductorConfigContext.__init__\x94\x93\x94\x8c\t__enter__\x94h8\x8c\x1fInductorConfigContext.__enter__\x94\x93\x94\x8c\x08__exit__\x94h8\x8c\x1eInductorConfigContext.__exit__\x94\x93\x94h\x03Nu\x8c\x1cget_config_serialization_fns\x94\x8c\x1atorch._dynamo.config_utils\x94h\x86\x93\x94u.')


# REPLACEABLE COMMENT FOR TESTING PURPOSES


args = [((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False), ((3, 512, 1024), (524288, 1024, 1), torch.uint8, 'cuda', False)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer('self_self_self_self_mean', torch.randn([3, 1, 1], dtype=torch.float32).cuda())
        self.register_buffer('self_self_self_self_std', torch.randn([3, 1, 1], dtype=torch.float32).cuda())



    def forward(self, _stack0_inputs_0_ : torch.Tensor, _stack0_inputs_1_ : torch.Tensor, _stack0_inputs_2_ : torch.Tensor, _stack0_inputs_3_ : torch.Tensor, _stack0_inputs_4_ : torch.Tensor, _stack0_inputs_5_ : torch.Tensor, _stack0_inputs_6_ : torch.Tensor, _stack0_inputs_7_ : torch.Tensor, _stack0_inputs_8_ : torch.Tensor, _stack0_inputs_9_ : torch.Tensor, _stack0_inputs_10_ : torch.Tensor, _stack0_inputs_11_ : torch.Tensor):
        getitem = _stack0_inputs_0_[([2, 1, 0], Ellipsis)];  _stack0_inputs_0_ = None
        getitem_1 = _stack0_inputs_1_[([2, 1, 0], Ellipsis)];  _stack0_inputs_1_ = None
        getitem_2 = _stack0_inputs_2_[([2, 1, 0], Ellipsis)];  _stack0_inputs_2_ = None
        getitem_3 = _stack0_inputs_3_[([2, 1, 0], Ellipsis)];  _stack0_inputs_3_ = None
        getitem_4 = _stack0_inputs_4_[([2, 1, 0], Ellipsis)];  _stack0_inputs_4_ = None
        getitem_5 = _stack0_inputs_5_[([2, 1, 0], Ellipsis)];  _stack0_inputs_5_ = None
        getitem_6 = _stack0_inputs_6_[([2, 1, 0], Ellipsis)];  _stack0_inputs_6_ = None
        getitem_7 = _stack0_inputs_7_[([2, 1, 0], Ellipsis)];  _stack0_inputs_7_ = None
        getitem_8 = _stack0_inputs_8_[([2, 1, 0], Ellipsis)];  _stack0_inputs_8_ = None
        getitem_9 = _stack0_inputs_9_[([2, 1, 0], Ellipsis)];  _stack0_inputs_9_ = None
        getitem_10 = _stack0_inputs_10_[([2, 1, 0], Ellipsis)];  _stack0_inputs_10_ = None
        getitem_11 = _stack0_inputs_11_[([2, 1, 0], Ellipsis)];  _stack0_inputs_11_ = None
        float_1 = getitem.float();  getitem = None
        float_2 = getitem_1.float();  getitem_1 = None
        float_3 = getitem_2.float();  getitem_2 = None
        float_4 = getitem_3.float();  getitem_3 = None
        float_5 = getitem_4.float();  getitem_4 = None
        float_6 = getitem_5.float();  getitem_5 = None
        float_7 = getitem_6.float();  getitem_6 = None
        float_8 = getitem_7.float();  getitem_7 = None
        float_9 = getitem_8.float();  getitem_8 = None
        float_10 = getitem_9.float();  getitem_9 = None
        float_11 = getitem_10.float();  getitem_10 = None
        float_12 = getitem_11.float();  getitem_11 = None
        self_self_self_self_mean = self.self_self_self_self_mean
        sub = float_1 - self_self_self_self_mean;  float_1 = self_self_self_self_mean = None
        self_self_self_self_std = self.self_self_self_self_std
        truediv = sub / self_self_self_self_std;  sub = self_self_self_self_std = None
        self_self_self_self_mean_1 = self.self_self_self_self_mean
        sub_1 = float_2 - self_self_self_self_mean_1;  float_2 = self_self_self_self_mean_1 = None
        self_self_self_self_std_1 = self.self_self_self_self_std
        truediv_1 = sub_1 / self_self_self_self_std_1;  sub_1 = self_self_self_self_std_1 = None
        self_self_self_self_mean_2 = self.self_self_self_self_mean
        sub_2 = float_3 - self_self_self_self_mean_2;  float_3 = self_self_self_self_mean_2 = None
        self_self_self_self_std_2 = self.self_self_self_self_std
        truediv_2 = sub_2 / self_self_self_self_std_2;  sub_2 = self_self_self_self_std_2 = None
        self_self_self_self_mean_3 = self.self_self_self_self_mean
        sub_3 = float_4 - self_self_self_self_mean_3;  float_4 = self_self_self_self_mean_3 = None
        self_self_self_self_std_3 = self.self_self_self_self_std
        truediv_3 = sub_3 / self_self_self_self_std_3;  sub_3 = self_self_self_self_std_3 = None
        self_self_self_self_mean_4 = self.self_self_self_self_mean
        sub_4 = float_5 - self_self_self_self_mean_4;  float_5 = self_self_self_self_mean_4 = None
        self_self_self_self_std_4 = self.self_self_self_self_std
        truediv_4 = sub_4 / self_self_self_self_std_4;  sub_4 = self_self_self_self_std_4 = None
        self_self_self_self_mean_5 = self.self_self_self_self_mean
        sub_5 = float_6 - self_self_self_self_mean_5;  float_6 = self_self_self_self_mean_5 = None
        self_self_self_self_std_5 = self.self_self_self_self_std
        truediv_5 = sub_5 / self_self_self_self_std_5;  sub_5 = self_self_self_self_std_5 = None
        self_self_self_self_mean_6 = self.self_self_self_self_mean
        sub_6 = float_7 - self_self_self_self_mean_6;  float_7 = self_self_self_self_mean_6 = None
        self_self_self_self_std_6 = self.self_self_self_self_std
        truediv_6 = sub_6 / self_self_self_self_std_6;  sub_6 = self_self_self_self_std_6 = None
        self_self_self_self_mean_7 = self.self_self_self_self_mean
        sub_7 = float_8 - self_self_self_self_mean_7;  float_8 = self_self_self_self_mean_7 = None
        self_self_self_self_std_7 = self.self_self_self_self_std
        truediv_7 = sub_7 / self_self_self_self_std_7;  sub_7 = self_self_self_self_std_7 = None
        self_self_self_self_mean_8 = self.self_self_self_self_mean
        sub_8 = float_9 - self_self_self_self_mean_8;  float_9 = self_self_self_self_mean_8 = None
        self_self_self_self_std_8 = self.self_self_self_self_std
        truediv_8 = sub_8 / self_self_self_self_std_8;  sub_8 = self_self_self_self_std_8 = None
        self_self_self_self_mean_9 = self.self_self_self_self_mean
        sub_9 = float_10 - self_self_self_self_mean_9;  float_10 = self_self_self_self_mean_9 = None
        self_self_self_self_std_9 = self.self_self_self_self_std
        truediv_9 = sub_9 / self_self_self_self_std_9;  sub_9 = self_self_self_self_std_9 = None
        self_self_self_self_mean_10 = self.self_self_self_self_mean
        sub_10 = float_11 - self_self_self_self_mean_10;  float_11 = self_self_self_self_mean_10 = None
        self_self_self_self_std_10 = self.self_self_self_self_std
        truediv_10 = sub_10 / self_self_self_self_std_10;  sub_10 = self_self_self_self_std_10 = None
        self_self_self_self_mean_11 = self.self_self_self_self_mean
        sub_11 = float_12 - self_self_self_self_mean_11;  float_12 = self_self_self_self_mean_11 = None
        self_self_self_self_std_11 = self.self_self_self_self_std
        truediv_11 = sub_11 / self_self_self_self_std_11;  sub_11 = self_self_self_self_std_11 = None
        return (truediv, truediv_1, truediv_2, truediv_3, truediv_4, truediv_5, truediv_6, truediv_7, truediv_8, truediv_9, truediv_10, truediv_11)



mod = Repro()
opt_mod = torch._dynamo.optimize("aot_eager")(mod)


with torch.cuda.amp.autocast(enabled=False):
    ref = run_fwd_maybe_bwd(mod, args)
    res = run_fwd_maybe_bwd(opt_mod, args)


```

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230129+cu116
[pip3] torchvision==0.15.0.dev20230129+cu116
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230129+cu116          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230129+cu116          pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
cc @eellison @tugsbayasgalan for fake tensor error

**Comment by bdhirsh** [comment]
when I run the repro on tip-of-master, it passes for me. Can you see if you still see this failure on the latest nightly? (And if you do, could you run the minifier again on it?)
