### ISSUE TITLE
DEBUG=1 build crashes at exit

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#94376]
### 🐛 Describe the bug

Building PyTorch from source with DEBUG=1 leads to crash at program exit

Build Command: 
```
time TORCH_CUDA_ARCH_LIST="7.5" USE_DISTRIBUTED=1 USE_GLOO=1 BUILD_TEST=0 BUILD_CAFFE2=0 USE_CUDA=0 USE_ASAN=0 USE_MKLDNN=0 USE_KINETO=0 DEBUG=1 MAX_JOBS=$NCORES USE_XNNPACK=0 USE_FBGEMM=0 USE_NNPACK=0 USE_QNNPACK=0 USE_CUDNN=0 USE_NCCL=0  python setup.py develop
```

Snippet
```python
import torch
```

Output
```
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```

GDB Trace
```c++
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350465344) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737350465344) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737350465344, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7cc4476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7caa7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fffe128b036 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#6  0x00007fffe1289524 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#7  0x00007fffe1289576 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#8  0x00007fffe128a063 in __cxxabiv1::__cxa_pure_virtual () at ../../../../libstdc++-v3/libsupc++/pure.cc:50
#9  0x00007fffeeff8dd1 in c10::SafePyObject::~SafePyObject (this=0x5555597ed658, __in_chrg=<optimized out>)
    at /home/kshiteej/Pytorch/pytorch_functorch/c10/core/SafePyObject.h:32
#10 0x00007fffef86ba70 in torch::impl::dispatch::PythonKernelHolder::~PythonKernelHolder (this=0x5555597ed640, __in_chrg=<optimized out>)
    at /home/kshiteej/Pytorch/pytorch_functorch/torch/csrc/utils/python_dispatch.cpp:103
#11 0x00007fffef86ba98 in torch::impl::dispatch::PythonKernelHolder::~PythonKernelHolder (this=0x5555597ed640, __in_chrg=<optimized out>)
    at /home/kshiteej/Pytorch/pytorch_functorch/torch/csrc/utils/python_dispatch.cpp:103
#12 0x00007fffe1fc9b27 in c10::intrusive_ptr<c10::OperatorKernel, c10::detail::intrusive_target_default_null_type<c10::OperatorKernel> >::reset_ (
    this=0x555555aa65b8) at /home/kshiteej/Pytorch/pytorch_functorch/c10/util/intrusive_ptr.h:291
#13 0x00007fffe1fc7700 in c10::intrusive_ptr<c10::OperatorKernel, c10::detail::intrusive_target_default_null_type<c10::OperatorKernel> >::~intrusive_ptr (
    this=0x555555aa65b8, __in_chrg=<optimized out>) at /home/kshiteej/Pytorch/pytorch_functorch/c10/util/intrusive_ptr.h:370
#14 0x00007fffe1fc1a5c in c10::BoxedKernel::~BoxedKernel (this=0x555555aa65b8, __in_chrg=<optimized out>)
    at /home/kshiteej/Pytorch/pytorch_functorch/aten/src/ATen/core/boxing/BoxedKernel.h:74
#15 0x00007fffe1fc322a in c10::KernelFunction::~KernelFunction (this=0x555555aa65b8, __in_chrg=<optimized out>)
    at /home/kshiteej/Pytorch/pytorch_functorch/aten/src/ATen/core/boxing/KernelFunction.h:74
#16 0x00007fffe23479b0 in std::array<c10::KernelFunction, 112ul>::~array (this=0x555555aa6458, __in_chrg=<optimized out>)
    at /home/kshiteej/.conda/envs/pytorch-cuda-dev/x86_64-conda-linux-gnu/include/c++/10.4.0/array:94
#17 0x00007fffe2347a46 in c10::impl::OperatorEntry::~OperatorEntry (this=0x555555aa6360, __in_chrg=<optimized out>)
    at /home/kshiteej/Pytorch/pytorch_functorch/aten/src/ATen/core/dispatch/OperatorEntry.h:70
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x00007fffe2354af6 in c10::Dispatcher::OperatorDef::~OperatorDef (this=0x555555aa6360, __in_chrg=<optimized out>)
    at /home/kshiteej/Pytorch/pytorch_functorch/aten/src/ATen/core/dispatch/Dispatcher.h:66
#19 0x00007fffe2354b16 in __gnu_cxx::new_allocator<std::_List_node<c10::Dispatcher::OperatorDef> >::destroy<c10::Dispatcher::OperatorDef> (
    this=0x7fffee81e700 <c10::Dispatcher::realSingleton()::_singleton>, __p=0x555555aa6360)
    at /home/kshiteej/.conda/envs/pytorch-cuda-dev/x86_64-conda-linux-gnu/include/c++/10.4.0/ext/new_allocator.h:162
#20 0x00007fffe23525fb in std::allocator_traits<std::allocator<std::_List_node<c10::Dispatcher::OperatorDef> > >::destroy<c10::Dispatcher::OperatorDef> (
    __a=..., __p=0x555555aa6360) at /home/kshiteej/.conda/envs/pytorch-cuda-dev/x86_64-conda-linux-gnu/include/c++/10.4.0/bits/alloc_traits.h:531
#21 0x00007fffe234f6f8 in std::__cxx11::_List_base<c10::Dispatcher::OperatorDef, std::allocator<c10::Dispatcher::OperatorDef> >::_M_clear (
    this=0x7fffee81e700 <c10::Dispatcher::realSingleton()::_singleton>)
    at /home/kshiteej/.conda/envs/pytorch-cuda-dev/x86_64-conda-linux-gnu/include/c++/10.4.0/bits/list.tcc:77
#22 0x00007fffe234c485 in std::__cxx11::_List_base<c10::Dispatcher::OperatorDef, std::allocator<c10::Dispatcher::OperatorDef> >::~_List_base (
    this=0x7fffee81e700 <c10::Dispatcher::realSingleton()::_singleton>, __in_chrg=<optimized out>)
    at /home/kshiteej/.conda/envs/pytorch-cuda-dev/x86_64-conda-linux-gnu/include/c++/10.4.0/bits/stl_list.h:499
#23 0x00007fffe2347f6c in std::__cxx11::list<c10::Dispatcher::OperatorDef, std::allocator<c10::Dispatcher::OperatorDef> >::~list (
    this=0x7fffee81e700 <c10::Dispatcher::realSingleton()::_singleton>, __in_chrg=<optimized out>)
    at /home/kshiteej/.conda/envs/pytorch-cuda-dev/x86_64-conda-linux-gnu/include/c++/10.4.0/bits/stl_list.h:827
#24 0x00007fffe234831d in c10::Dispatcher::~Dispatcher (this=0x7fffee81e700 <c10::Dispatcher::realSingleton()::_singleton>, __in_chrg=<optimized out>)
    at /home/kshiteej/Pytorch/pytorch_functorch/aten/src/ATen/core/dispatch/Dispatcher.cpp:59
#25 0x00007ffff7cc7495 in __run_exit_handlers (status=0, listp=0x7ffff7e9b838 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, 
    run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:113
#26 0x00007ffff7cc7610 in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143


#27 0x00007ffff7cabd97 in __libc_start_call_main (main=main@entry=0x55555572f010 <main>, argc=argc@entry=2, argv=argv@entry=0x7fffffffb8e8)
    at ../sysdeps/nptl/libc_start_call_main.h:74

#28 0x00007ffff7cabe40 in __libc_start_main_impl (main=0x55555572f010 <main>, argc=2, argv=0x7fffffffb8e8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffb8d8) at ../csu/libc-start.c:392
#29 0x000055555572ef61 in _start ()
```

### Versions

master

cc @ezyang @gchanan @zou3519

**Comment by malfet** [comment]
Would this be reproducible in release-with-asserts config? Or you need a full DEBUG build?

**Comment by albanD** [comment]
cc @ZainRizvi who worked on a PR to fix the debug build in CI.

**Comment by albanD** [comment]
Having smoke test is an easy first step.
We should run OpInfo tests to make sure we cover all autograd asserts.

**Comment by speediedan** [comment]
Thanks for looking into this!

**Comment by noisystreet** [comment]
same crash for me
