### ISSUE TITLE
pytorch1.9.1-->1.12.1 error RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation:

### ISSUE THREAD

**Issue by pedroHuang123** [pytorch/pytorch#94387]
### 🐛 Describe the bug

D:\software\miniconda3\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "D:\KdWork\OpenmmLab\mmflow\tools\train.py", line 208, in <module>
    main()
  File "D:\KdWork\OpenmmLab\mmflow\tools\train.py", line 197, in main
    train_model(
  File "D:\KdWork\OpenmmLab\mmflow\mmflow\apis\train.py", line 238, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "D:\software\miniconda3\lib\site-packages\mmcv\runner\iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "D:\software\miniconda3\lib\site-packages\mmcv\runner\iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "D:\software\miniconda3\lib\site-packages\mmcv\runner\base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "D:\software\miniconda3\lib\site-packages\mmcv\runner\hooks\optimizer.py", line 61, in after_train_iter
    runner.outputs['loss'].backward()
  File "D:\software\miniconda3\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\software\miniconda3\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 128, 46, 96]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Process finished with exit code 1

### Versions

none

**Comment by soulitzer** [comment]
Thanks for the report, have you tried anomaly mode as the error suggested? Does this still happen on the latest version of pytorch? Without having more information here are some ways you could fix this:
- Try running your code under this context manager. It automatically inserts a clone when needed to avoid this error. https://github.com/pytorch/pytorch/blob/master/torch/autograd/graph.py#L508
- This could be potentially due to an optimizer using an in-place operation and you are directly saving a parameter for backward AND you are using retain_graph=True.
I'm going to close this for now because it doesn't seem like a bug in PyTorch. Feel free to ask on the https://discuss.pytorch.org/.
