### ISSUE TITLE
SIGSEGV when using DDP + NCCL + nsys profiling + Pytorch 1.13

### ISSUE THREAD

**Issue by jhoareau** [pytorch/pytorch#94393]
### 🐛 Describe the bug

This is a regression in Pytorch 1.13, potentially due to the nccl library version upgrade, that only happens when running nsys profiling.

Using the DDP sample code from Pytorch documentation (https://pytorch.org/tutorials/intermediate/ddp_tutorial.html):

```python
import os

import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
import torch.optim as optim
from torch.nn.parallel import DistributedDataParallel as DDP


def setup(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'

    # initialize the process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)

def cleanup():
    dist.destroy_process_group()

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))


def demo_basic(rank, world_size):
    print(f"Running basic DDP example on rank {rank}.")
    setup(rank, world_size)

    # create model and move it to GPU with id rank
    model = ToyModel().to(rank)
    ddp_model = DDP(model, device_ids=[rank])

    loss_fn = nn.MSELoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

    optimizer.zero_grad()
    outputs = ddp_model(torch.randn(20, 10))
    labels = torch.randn(20, 5).to(rank)
    loss_fn(outputs, labels).backward()
    optimizer.step()

    cleanup()


def run_demo(demo_fn, world_size):
    mp.start_processes(demo_fn,
             args=(world_size,),
             nprocs=world_size,
             join=True,
             start_method="fork")

if __name__ == "__main__":
    run_demo(demo_basic, torch.cuda.device_count())
```

When running this script with Pytorch 1.13.1+cu117, under nsys profiling only:

`/usr/local/cuda-11.8/bin/nsys profile python test_ddp.py` yields:
```
Traceback (most recent call last):
  File "test_ddp.py", line 59, in <module>
    run_demo(demo_basic, torch.cuda.device_count())
  File "test_ddp.py", line 53, in run_demo
    mp.spawn(demo_fn,
  File "torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV
```

The standalone script is running fine.

When running this script with Pytorch 1.12.0+cu116:

Both the `/usr/local/cuda-11.8/bin/nsys profile python test_ddp.py` and standalone scripts yield:
```
Running basic DDP example on rank 1.
Running basic DDP example on rank 0.
```

Some extra logging that could help debug the issue:

In Pytorch 1.13.1+cu117:
```
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I debug.cpp:49] [c10d] The debug level is set to DETAIL.
[I socket.cpp:442] [c10d - debug] The server socket will attempt to listen on an IPv6 address.
[I socket.cpp:492] [c10d - debug] The server socket is attempting to listen on [::]:12355.
[I socket.cpp:566] [c10d] The server socket has started to listen on [::]:12355.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:787] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:46560.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:46560.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:46570.
[I socket.cpp:787] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:46570.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:46578.
[I socket.cpp:787] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:46578.
[I socket.cpp:624] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:699] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:295] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:46590.
[I socket.cpp:787] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:46590.
[I ProcessGroupNCCL.cpp:642] [Rank 1] NCCL_DESYNC_DEBUG and NCCL_ASYNC_ERROR_HANDLING must both be enabled. Enabling NCCL_ASYNC_ERROR_HANDLING.
[I ProcessGroupNCCL.cpp:669] [Rank 1] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 1
NCCL_DESYNC_DEBUG: 1
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
[I ProcessGroupNCCL.cpp:835] [Rank 1] NCCL watchdog thread started!
[I ProcessGroupNCCL.cpp:642] [Rank 0] NCCL_DESYNC_DEBUG and NCCL_ASYNC_ERROR_HANDLING must both be enabled. Enabling NCCL_ASYNC_ERROR_HANDLING.
[I ProcessGroupNCCL.cpp:669] [Rank 0] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 1
NCCL_DESYNC_DEBUG: 1
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
[I ProcessGroupNCCL.cpp:835] [Rank 0] NCCL watchdog thread started!
cph-testbench:352272:352272 [0] NCCL INFO Bootstrap : Using enp5s0:172.26.45.54<0>
cph-testbench:352272:352272 [0] NCCL INFO NET/Plugin : Plugin load returned 0 : dlopen hook: 'libnccl-net.so': cannot open shared object file: No such file or directory.
cph-testbench:352272:352272 [0] NCCL INFO cudaDriverVersion 12000
NCCL version 2.14.3+cuda11.7
cph-testbench:352272:352272 [0] NCCL INFO init.cc:1147 Cuda Host Alloc Size 4 pointer 0x7f0543200000
Traceback (most recent call last):
  File "test_ddp.py", line 62, in <module>
    run_demo(demo_basic, world_size)
  File "test_ddp.py", line 53, in run_demo
    mp.spawn(demo_fn,
  File "torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV
```

In Pytorch 1.12.0+cu116:
```
[I debug.cpp:47] [c10d] The debug level is set to DETAIL.
[I debug.cpp:47] [c10d] The debug level is set to DETAIL.
[I debug.cpp:47] [c10d] The debug level is set to DETAIL.
[I socket.cpp:580] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:648] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:710] [c10d - trace] The server socket on [::ffff:127.0.0.1]:12355 is not yet listening (errno: 111 - Connection refused), will retry.
[I socket.cpp:417] [c10d - debug] The server socket will attempt to listen on an IPv6 address.
[I socket.cpp:462] [c10d - debug] The server socket is attempting to listen on [::]:12355.
[I socket.cpp:522] [c10d] The server socket has started to listen on [::]:12355.
[I socket.cpp:580] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:648] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:725] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:51350.
[I socket.cpp:276] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:51350.
[I socket.cpp:648] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:276] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:51360.
[I socket.cpp:725] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:51360.
[I socket.cpp:580] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:648] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:276] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:51372.
[I socket.cpp:725] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:51372.
[I ProcessGroupNCCL.cpp:587] [Rank 1] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 0
NCCL_DESYNC_DEBUG: 0
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
[I ProcessGroupNCCL.cpp:751] [Rank 1] NCCL watchdog thread started!
[I socket.cpp:580] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (localhost, 12355).
[I socket.cpp:648] [c10d - trace] The client socket is attempting to connect to [::ffff:127.0.0.1]:12355.
[I socket.cpp:276] [c10d - debug] The server socket on [::]:12355 has accepted a connection from [::ffff:127.0.0.1]:51374.
[I socket.cpp:725] [c10d] The client socket has connected to [::ffff:127.0.0.1]:12355 on [::ffff:127.0.0.1]:51374.
[I ProcessGroupNCCL.cpp:587] [Rank 0] ProcessGroupNCCL initialized with following options:
NCCL_ASYNC_ERROR_HANDLING: 0
NCCL_DESYNC_DEBUG: 0
NCCL_BLOCKING_WAIT: 0
TIMEOUT(ms): 1800000
USE_HIGH_PRIORITY_STREAM: 0
[I ProcessGroupNCCL.cpp:751] [Rank 0] NCCL watchdog thread started!
cph-testbench:353117:353117 [0] NCCL INFO Bootstrap : Using enp5s0:172.26.45.54<0>
cph-testbench:353117:353117 [0] NCCL INFO NET/Plugin : Plugin load returned 0 : dlopen hook: 'libnccl-net.so': cannot open shared object file: No such file or directory.
cph-testbench:353117:353117 [0] NCCL INFO NET/IB : No device found.
cph-testbench:353117:353117 [0] NCCL INFO NET/Socket : Using [0]enp5s0:172.26.45.54<0> [1]br-7ef2ebc742b4:172.20.0.1<0> [2]br-929d72973484:172.18.0.1<0> [3]br-e2ff7a2944d2:172.19.0.1<0>
cph-testbench:353117:353117 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda11.6
cph-testbench:353118:353118 [1] NCCL INFO Bootstrap : Using enp5s0:172.26.45.54<0>
cph-testbench:353118:353118 [1] NCCL INFO NET/Plugin : Plugin load returned 0 : dlopen hook: 'libnccl-net.so': cannot open shared object file: No such file or directory.
cph-testbench:353118:353118 [1] NCCL INFO NET/IB : No device found.
cph-testbench:353118:353118 [1] NCCL INFO NET/Socket : Using [0]enp5s0:172.26.45.54<0> [1]br-7ef2ebc742b4:172.20.0.1<0> [2]br-929d72973484:172.18.0.1<0> [3]br-e2ff7a2944d2:172.19.0.1<0>
cph-testbench:353118:353118 [1] NCCL INFO Using network Socket
cph-testbench:353117:353265 [0] NCCL INFO Could not enable P2P between dev 1(=41000) and dev 0(=a000)
cph-testbench:353118:353267 [1] NCCL INFO Could not enable P2P between dev 1(=41000) and dev 0(=a000)
cph-testbench:353117:353265 [0] NCCL INFO Could not enable P2P between dev 0(=a000) and dev 1(=41000)
cph-testbench:353118:353267 [1] NCCL INFO Could not enable P2P between dev 0(=a000) and dev 1(=41000)
cph-testbench:353117:353265 [0] NCCL INFO Could not enable P2P between dev 1(=41000) and dev 0(=a000)
cph-testbench:353118:353267 [1] NCCL INFO Could not enable P2P between dev 1(=41000) and dev 0(=a000)
...
```

### Versions

Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Oct 14 2022, 09:37:54)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 525.60.11
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          48
On-line CPU(s) list:             0-47
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       1
NUMA node(s):                    4
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           8
Model name:                      AMD Ryzen Threadripper 2970WX 24-Core Processor
Stepping:                        2
Frequency boost:                 enabled
CPU MHz:                         1734.315
CPU max MHz:                     3000.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        5987.88
Virtualization:                  AMD-V
L1d cache:                       768 KiB
L1i cache:                       1.5 MiB
L2 cache:                        12 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-5,24-29
NUMA node1 CPU(s):               12-17,36-41
NUMA node2 CPU(s):               6-11,30-35
NUMA node3 CPU(s):               18-23,42-47
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] torch==1.13.1+cu117
[conda] Could not collect

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by kumpera** [comment]
@kwen2501 are you aware of any NCCL regressions when using with nsys?

**Comment by kwen2501** [comment]
Hi, do you have a core dump and backtrace? 
I can't find obvious errors from the NCCL or PyTorch logs.
Thanks!

**Comment by jhoareau** [comment]
Hi @kwen2501, here is a GDB backtrace:
```
#0  0x0000000000000000 in ?? ()
#1  0x00007ff5c8b0f1da in ?? () from /home/juh/.local/share/nsight_systems/libToolsInjection64.so
#2  0x00007ff5c885f606 in NSYS_DL_dlvsym () from /home/juh/.local/share/nsight_systems/libToolsInjection64.so
#3  0x00007ff58be01168 in initOnceFunc () at misc/ibvwrap.cc:94
#4  0x00007ff5c83ae4df in __pthread_once_slow (once_control=0x7ff59acdfba4 <initOnceControl>, init_routine=0x7ff58be00ec0 <initOnceFunc()>) at pthread_once.c:116
#5  0x00007ff5c83ae595 in __GI___pthread_once (once_control=once_control@entry=0x7ff59acdfba4 <initOnceControl>, init_routine=init_routine@entry=0x7ff58be00ec0 <initOnceFunc()>) at pthread_once.c:143
#6  0x00007ff58be01847 in wrap_ibv_symbols () at misc/ibvwrap.cc:139
#7  0x00007ff58bde3349 in ncclIbInit (logFunction=<optimized out>) at transport/net_ib.cc:150
#8  0x00007ff58bdbb84a in netGetState (state=<synthetic pointer>, i=1) at net.cc:245
#9  ncclNetInit (comm=comm@entry=0x555d647315b0) at net.cc:273
#10 0x00007ff58bd7e687 in commAlloc (comret=comret@entry=0x555d64123530, ndev=ndev@entry=1, rank=rank@entry=0) at init.cc:323
#11 0x00007ff58bd8363e in ncclCommInitRankFunc (job_=<optimized out>) at init.cc:1088
#12 0x00007ff58bd7bd68 in ncclAsyncJobMain (arg=0x555d29662100) at group.cc:62
#13 0x00007ff5c88b4c0d in ?? () from /home/juh/.local/share/nsight_systems/libToolsInjection64.so
#14 0x00007ff5c83a5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007ff5c816e133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Unfortunately the corefile dump is 16GB and does not really seem to contain any extra information. It would probably be easiest for you to try to reproduce the issue with my script and the nsys installation from CUDA 11.8, or from the latest version of Nsight Systems.

I'm no GDB expert, but does that sound like it's a problem purely on nccl/nsys side? Would potentially including a different version of Nsys in the Pytorch pre-built wheels help?

**Comment by jhoareau** [comment]
The issue is fully in Nsight Systems - it will be fixed in the next version. See https://forums.developer.nvidia.com/t/profiling-nccl-2-14-3-leads-to-segmentation-fault/242371/6
