### ISSUE TITLE
[fake_tensor] torch._subclasses.fake_tensor.DynamicOutputShapeException when calling torch.nonzero using aot_function

### ISSUE THREAD

**Issue by Adam27X** [pytorch/pytorch#94414]
### 🐛 Describe the bug

This issue appears related to https://github.com/pytorch/torchdynamo/issues/1886 but for torch.nonzero instead of torch.repeat_interleave (there are probably others as well).

For some reason using torch._dynamo.optimize works but using aot_function does not. I think this has something to do with needing a graph break but I'm not sure.

It's possible my minimal use case here is too simple; my real use case involves a bunch of computation and then using torch.nonzero to precompute tensor indices that are used later. I'm using aot_function to try and automatically generate code for the forward and backward passes. As a workaround I'm able to split my input into two functions, one that contains everything before the torch.nonzero call and another that takes the resulting indices from the torch.nonzero call as a parameter.

### Error logs

Failed to collect metadata on function, produced code may be suboptimal.  Known situations this can occur are inference mode only compilation involving resize_ or prims (!schema.hasAnyAliasInfo() INTERNAL ASSERT FAILED); if your situation looks different please file a bug to PyTorch.
Traceback (most recent call last):
  File "/torch/_functorch/aot_autograd.py", line 1381, in aot_wrapper_dedupe
    fw_metadata, _out = run_functionalized_fw_and_collect_metadata(flat_fn)(
  File "/torch/_functorch/aot_autograd.py", line 578, in inner
    flat_f_outs = f(*flat_f_args)
  File "/torch/_functorch/aot_autograd.py", line 2314, in flat_fn
    tree_out = fn(*args, **kwargs)
  File "<stdin>", line 2, in f
  File "/torch/utils/_stats.py", line 15, in wrapper
    return fn(*args, **kwargs)
  File "/torch/_subclasses/fake_tensor.py", line 928, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/torch/_subclasses/fake_tensor.py", line 379, in dyn_shape
    raise DynamicOutputShapeException(func)
torch._subclasses.fake_tensor.DynamicOutputShapeException: aten.nonzero.default

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/torch/_functorch/aot_autograd.py", line 2334, in returned_function
    compiled_fn = create_aot_dispatcher_function(
  File "/torch/2.0.0-03c7/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/torch/_functorch/aot_autograd.py", line 2184, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/torch/_functorch/aot_autograd.py", line 1504, in aot_wrapper_dedupe
    compiled_fn = compiler_fn(wrapped_flat_fn, deduped_flat_args, aot_config)
  File "/torch/2.0.0-03c7/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1056, in aot_dispatch_base
    fw_module = make_fx(flat_fn, aot_config.decompositions)(*tmp_flat_args)
  File "/torch/2.0.0-03c7/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 716, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/torch/2.0.0-03c7/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/torch/2.0.0-03c7/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 450, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/torch/2.0.0-03c7/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/torch/fx/_symbolic_trace.py", line 778, in trace
    (self.create_arg(fn(*args)),),
  File "/torch/fx/experimental/proxy_tensor.py", line 466, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "/torch/_functorch/aot_autograd.py", line 1502, in wrapped_flat_fn
    return flat_fn(*add_dupe_args(args))
  File "/torch/_functorch/aot_autograd.py", line 2314, in flat_fn
    tree_out = fn(*args, **kwargs)
  File "<stdin>", line 2, in f
  File "/torch/utils/_stats.py", line 15, in wrapper
    return fn(*args, **kwargs)
  File "/torch/fx/experimental/proxy_tensor.py", line 494, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/torch/2.0.0-03c7/lib/python3.10/site-packages/torch/fx/experimental/proxy_tensor.py", line 519, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "/torch/fx/experimental/proxy_tensor.py", line 352, in proxy_call
    out = func(*args, **kwargs)
  File "/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/torch/utils/_stats.py", line 15, in wrapper
    return fn(*args, **kwargs)
  File "/torch/_subclasses/fake_tensor.py", line 928, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/torch/_subclasses/fake_tensor.py", line 379, in dyn_shape
    raise DynamicOutputShapeException(func)
torch._subclasses.fake_tensor.DynamicOutputShapeException: aten.nonzero.default

### Minified repro

import torch
import functorch
from typing import List
import torch._dynamo
from functorch.compile import aot_function, aot_module
def f(x):
  return torch.nonzero(x > 0)

x = torch.ones([4,4])
x[0][3] = 0
x[1][2] = 0
opt_fn = torch._dynamo.optimize("eager")(f)
y = opt_fn(x) #Works

def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
  print(gm.code)
  return gm.forward

aot_fun = aot_function(f,fw_compiler=my_compiler,bw_compiler=my_compiler)
y1 = aot_fun(x) #Error

### Versions

>>> print(torch.__version__)
2.0.0.dev20230207+cu117
>>> torch.version.git_version
'1530b798ceeff749a7cc5833d9d9627778bd998a'

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @soumith @ngimel

**Comment by ezyang** [comment]
This won't work until unbacked symints are working https://dev-discuss.pytorch.org/t/state-of-symbolic-shapes-branch/777/32

Splitting in the way you have done is the right workaround.

**Comment by Chillee** [comment]
Also to clarify, the reason `torch._dynamo.optimize` works is that it automatically does the splitting here.

**Comment by Adam27X** [comment]
Thank you both for your clarifications!

In general what are my options for generating backward pass code from a given model or function? It seems like `torch._dynamo.optimize`, `aot_function`, and `symbolic_trace` can all produce FXGraphs and therefore emit code, but it's hard for me to reason about the pros and cons of each (and if/how they'll work with `autograd`).

**Comment by ezyang** [comment]
The general heuristic is that if torch._dynamo.export works, you should use that, as it has the most safety guarantees. I wouldn't use aot_function for the most part; we wanted to delete it but there are some old users of it, but torch.compile is just better at this. symbolic_trace won't give you a backwards graph.

**Comment by Adam27X** [comment]
> The general heuristic is that if torch._dynamo.export works, you should use that, as it has the most safety guarantees. I wouldn't use aot_function for the most part; we wanted to delete it but there are some old users of it, but torch.compile is just better at this. symbolic_trace won't give you a backwards graph.

How can I get a `torch.fx.GraphModule` object for the _backward_ pass of a model via `torch._dynamo.export` or `torch._dynamo.optimize`? So far I've only been able to do this with `aot_function` because as far as I can tell from the documentation only `aot_function` has an option to specify a `bw_compiler`.

**Comment by ezyang** [comment]
We're actively discussing this right now; cc @SherlockNoMad

**Comment by shingjan** [comment]
The same error I got from running yolov8 with fake mode:
```
 File "/home/yshi/miniconda3/envs/dy_client/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 594, in index_tensor
    out = meta_index_Tensor(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dy_client/lib/python3.8/site-packages/torch/_meta_registrations.py", line 2647, in meta_index_Tensor
    nonzero = index.nonzero()
  File "/home/yshi/miniconda3/envs/dy_client/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dy_client/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1233, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/yshi/miniconda3/envs/dy_client/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1470, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/yshi/miniconda3/envs/dy_client/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 519, in nonzero
    raise DynamicOutputShapeException(func)
torch._subclasses.fake_tensor.DynamicOutputShapeException: aten.nonzero.default
```

Looks like it is this [line](https://github.com/pytorch/pytorch/blob/497571df5810790a0e82591747ef38cda8f02463/torch/_meta_registrations.py#L2647) in _meta_registration.py that is causing this problem. If we pass the fake mode a little bit different:
```
FakeTensorMode(
    shape_env=ShapeEnv(  # all default values
        allow_scalar_outputs=True,
        allow_dynamic_output_shape_ops=True,
        assume_static_by_default=False,
    ),
)
```

I got another error:
```
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent (and thus we do not know the true value.)  The expression we were trying to evaluate is i0 (unhinted: i0).  Scroll up to see where each of these data-dependent accesses originally occurred.
```

I wonder if there is update on unbacked symint and if this looks like something that can be resolved by unbacked symint? Thanks!

cc: @ezyang

**Comment by ezyang** [comment]
What version of PyTorch are you using? Can you try a nightly?

**Comment by shingjan** [comment]
Thanks @ezyang for the reply! I later found out the `allow_dynamic_output_shape_ops` works for `nonzero` but not `repeat_interleave`. I put more details in this #108195. This is on nightly==0817.

**Comment by ezyang** [comment]
Ah yes, we need to do the unbacked treatment to `repeat_interleave`

**Comment by Adam27X** [comment]
This error no longer occurs, closing.
