### ISSUE TITLE
[Functionalization] `index_reduce_` op tests with functionalization enabled

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/pytorch#94471]
### 🐛 Describe the bug

With functionalization, the existing `index_reduce_` python op test (https://github.com/pytorch/pytorch/blob/master/test/test_torch.py#L3035) fails.

To reproduce (this is one of the sample inputs to the `index_reduce_` test linked above):
```
import torch
import functorch
def test():
	dest = torch.tensor([[[ 0.0322,  1.2734, -3.4688,  8.1875, -4.2500],
	         [-5.6250,  1.3828,  7.7188,  0.3887,  5.5312],
	         [ 3.2344,  5.0312, -7.4062,  1.2422, -0.1719],
	         [-6.0312,  6.2188, -1.1641, -0.3203,  0.2637]],

	        [[-6.9688, -3.5938,  2.6406,  4.3125,  0.1348],
	         [ 4.5000, -0.5938, -5.5312, -1.8281,  1.1562],
	         [ 1.5781, -1.7891,  3.8906,  1.2969,  1.9688],
	         [-6.5000,  2.4375, -4.8125,  3.0312,  1.9453]],

	        [[ 0.2002,  7.7188,  1.5547, -7.6875, -2.5781],
	         [-4.1562,  1.8125,  6.5625,  8.2500,  5.4062],
	         [ 4.2812,  6.5625, -3.3906,  1.7266,  8.8750],
	         [-6.9375,  7.0625,  3.4844, -7.9375,  8.5625]]], dtype=torch.bfloat16)
	idx = torch.tensor([], dtype=torch.int64)
	src = torch.empty((3, 4, 0), dtype=torch.bfloat16)
	dest.index_reduce_(2, idx, src, 'mean', include_self=False)
```
Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/vmap.py", line 39, in fn
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/eager_transforms.py", line 1582, in wrapped
    func_outputs = func(*func_args, **func_kwargs)
  File "<stdin>", line 18, in test
  File "/opt/conda/lib/python3.8/site-packages/torch/_decomp/decompositions.py", line 3314, in inplace_op
    out = outplace_op(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_ops.py", line 499, in __call__
    return self._op(*args, **kwargs or {})
IndexError: select(): index 0 out of range for tensor of size [3, 4, 0] at dimension 2
```
Full dispatch trace logs: https://gist.github.com/wonjoolee95/d6c2c31df8a3342ddbf56523c0eeab66
Full dispatch trace logs without functionalization: https://gist.github.com/wonjoolee95/8a9c2543b0b017f9df049da57fc84dce

The error itself seems to be clear -- due to some index out-bound-error, as the code tries to access index 0 at dimension 2 of shape [3, 4, 0] as mentioned in the error logs; however, this only happens when functionalization is enabled. The last few bits of the dispatch trace seems suspicious. Without functionalization, the dispatch looks like:
```
 [call] op=[aten::index_reduce_], key=[AutogradCPU]
  [redispatch] op=[aten::index_reduce_], key=[ADInplaceOrView]
   [redispatch] op=[aten::index_reduce_], key=[CPU]
    [call] op=[aten::to.dtype], key=[CPU]
    [call] op=[aten::index_fill_.int_Scalar], key=[CPU]
     [call] op=[aten::as_strided], key=[CPU]
     [call] op=[aten::as_strided], key=[CPU]
```
However, with functionalization, it looks like:
```
 [call] op=[aten::index_reduce_], key=[FuncTorchDynamicLayerFrontMode]
  [callBoxed] op=[aten::index_reduce_], key=[Functionalize]
   [call] op=[aten::index_reduce_], key=[Meta]
    [callBoxed] op=[aten::index_reduce], key=[Meta]
     [call] op=[aten::select.int], key=[Meta]
      [call] op=[aten::as_strided], key=[Meta]
     [call] op=[aten::select.int], key=[Meta]
```
Just looking at it at a high-level, seems like functionalization now decomposes into `select.int` that might deal with indices differently compared to the previous ops?

Please let me know if you need any more information.

cc @alanwaketan 

### Versions

Nightly

**Comment by bdhirsh** [comment]
Looks like `index_reduce_` has a bug in its meta implementation:
```
>>> dest = torch.ones(3, 4, 5)
>>> src = torch.ones(3, 4, 0)
>>> idx = torch.tensor([], dtype=torch.int64)
>>> dest_ = dest.to(device='meta')
>>> idx_ = idx.to(device='meta')
>>> src_ = src.to(device='meta')
>>> # this fails
>>> dest_.index_reduce_(2, idx_, src_, 'mean', include_self=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/hirsheybar1/work/pytorch/torch/_decomp/decompositions.py", line 3314, in inplace_op
    out = outplace_op(*args, **kwargs)
  File "/scratch/hirsheybar1/work/pytorch/torch/_ops.py", line 499, in __call__
    return self._op(*args, **kwargs or {})
IndexError: select(): index 0 out of range for tensor of size [3, 4, 0] at dimension 2
>>> # But this works
>>> dest.index_reduce_(2, idx, src, 'mean', include_self=False)
```

**Comment by bdhirsh** [comment]
Sigh, I bet it's because there's a special case for device==meta in `index_reduce_` [here](https://github.com/pytorch/pytorch/blob/67513aee6d28a764ac7178a3b32e6b05cc5d6b2a/aten/src/ATen/native/TensorAdvancedIndexing.cpp#L352). That bit of code probably isn't resilient to size 0 dimension (while the normal path TensorIterator code is).

**Comment by ezyang** [comment]
@bdhirsh are you gonna fix this?

**Comment by bdhirsh** [comment]
I think @voznesenskym agreed to take a look (otherwise I'm happy to grab)

**Comment by atalman** [comment]
@wonjoolee95 Today is last day for cherry-picking, we will be removing this issue from milestones

**Comment by voznesenskym** [comment]
My apologies, this feel between the cracks. I can take a look at this shortly.

**Comment by atalman** [comment]
@voznesenskym  Removing from milestones, from 2.27 we are picking only critical fixes

**Comment by voznesenskym** [comment]
Sorry, lost track of this a but, but not forgotten.
