### ISSUE TITLE
Abort Caused by Virtual Function

### ISSUE THREAD

**Issue by wschin** [pytorch/pytorch#94544]
### 🐛 Describe the bug

`Abort` happens when PyTorch releasing its resources (i.e., when Python terminates) in

```
struct TORCH_API OperatorKernel : public c10::intrusive_ptr_target {
  virtual ~OperatorKernel() = default;
};
```

After reverting `f172feae0d6e6e510d2133ed10dd76dbcaf0f0fe`, it works again. My build command is `DEBUG=1 VERBOSE=1 USE_KINETO=0 TORCH_CUDA_ARCH_LIST="7.0;7.2" PATH=/cuda-11.8/lib64:/cuda-11.8/include:/cuda-11.8/bin:$PATH CUDACXX=/cuda-11.8/bin/nvcc ONNX_NAMESPACE=onnx1 BUILD_SHARED_LIBS=1 BUILD_CAFFE2=0 BUILD_CAFFE2_OPS=0 USE_GLOO=1 USE_NCCL=0 USE_NUMPY=1 USE_OBSERVERS=1 USE_OPENMP=1 USE_DISTRIBUTED=1 USE_MPI=1 BUILD_PYTHON=1 USE_MKLDNN=0 USE_CUDA=1 BUILD_TEST=1 USE_FBGEMM=1 USE_NNPACK=1 USE_QNNPACK=0 USE_XNNPACK=1 python3 setup.py develop 2>&1 | tee build.log`
`.

### Versions

Latest master branch.

**Comment by malfet** [comment]
@wschin can can you pease share exactly the backtrace when this one crashes? And compiler type/version
Change sounds like a no-op, though older compilers could be confused about it, as destruction visibility is getting changed from protected to public.
cc:  @cyyever

**Comment by wschin** [comment]
(gdb) bt
#6  0x00007ffff60957bd in c10::SafePyObject::~SafePyObject (this=0x5555597c7f48, __in_chrg=<optimized out>)
    at pytorch-clean/c10/core/SafePyObject.h:32
#7  0x00007ffff697891c in torch::impl::dispatch::PythonKernelHolder::~PythonKernelHolder (this=0x5555597c7f30, __in_chrg=<optimized out>)
    at pytorch-clean/torch/csrc/utils/python_dispatch.cpp:103
#8  0x00007ffff6978948 in torch::impl::dispatch::PythonKernelHolder::~PythonKernelHolder (this=0x5555597c7f30, __in_chrg=<optimized out>)
    at pytorch-clean/torch/csrc/utils/python_dispatch.cpp:103
#9  0x00007fffe9835fc9 in c10::intrusive_ptr<c10::OperatorKernel, c10::detail::intrusive_target_default_null_type<c10::OperatorKernel> >::reset_ (this=0x555555acdc08)
    at pytorch-clean/c10/util/intrusive_ptr.h:291
#10 0x00007fffe9833ba0 in c10::intrusive_ptr<c10::OperatorKernel, c10::detail::intrusive_target_default_null_type<c10::OperatorKernel> >::~intrusive_ptr (
    this=0x555555acdc08, __in_chrg=<optimized out>) at pytorch-clean/c10/util/intrusive_ptr.h:370
#11 0x00007fffe982fd7c in c10::BoxedKernel::~BoxedKernel (this=0x555555acdc08, __in_chrg=<optimized out>)
    at pytorch-clean/aten/src/ATen/core/boxing/BoxedKernel.h:74
#12 0x00007fffe9831610 in c10::KernelFunction::~KernelFunction (this=0x555555acdc08, __in_chrg=<optimized out>)
    at pytorch-clean/aten/src/ATen/core/boxing/KernelFunction.h:74
#13 0x00007fffe9bd7cf4 in std::array<c10::KernelFunction, 112ul>::~array (this=0x555555acdaa8, __in_chrg=<optimized out>) at /usr/include/c++/9/array:94
#14 0x00007fffe9bd7d96 in c10::impl::OperatorEntry::~OperatorEntry (this=0x555555acd9b0, __in_chrg=<optimized out>)
    at pytorch-clean/aten/src/ATen/core/dispatch/OperatorEntry.h:70
#15 0x00007fffe9bdfe52 in c10::Dispatcher::OperatorDef::~OperatorDef (this=0x555555acd9b0, __in_chrg=<optimized out>)
    at pytorch-clean/aten/src/ATen/core/dispatch/Dispatcher.h:66
#16 0x00007fffe9bdfe76 in __gnu_cxx::new_allocator<std::_List_node<c10::Dispatcher::OperatorDef> >::destroy<c10::Dispatcher::OperatorDef> (
    this=0x7ffff5172560 <c10::Dispatcher::realSingleton()::_singleton>, __p=0x555555acd9b0) at /usr/include/c++/9/ext/new_allocator.h:152
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x00007fffe9bde1e1 in std::allocator_traits<std::allocator<std::_List_node<c10::Dispatcher::OperatorDef> > >::destroy<c10::Dispatcher::OperatorDef> (__a=..., 
    __p=0x555555acd9b0) at /usr/include/c++/9/bits/alloc_traits.h:496
#18 0x00007fffe9bdbab0 in std::__cxx11::_List_base<c10::Dispatcher::OperatorDef, std::allocator<c10::Dispatcher::OperatorDef> >::_M_clear (
    this=0x7ffff5172560 <c10::Dispatcher::realSingleton()::_singleton>) at /usr/include/c++/9/bits/list.tcc:77
#19 0x00007fffe9bd95b8 in std::__cxx11::_List_base<c10::Dispatcher::OperatorDef, std::allocator<c10::Dispatcher::OperatorDef> >::~_List_base (
    this=0x7ffff5172560 <c10::Dispatcher::realSingleton()::_singleton>, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_list.h:495
#20 0x00007fffe9bd81b2 in std::__cxx11::list<c10::Dispatcher::OperatorDef, std::allocator<c10::Dispatcher::OperatorDef> >::~list (
    this=0x7ffff5172560 <c10::Dispatcher::realSingleton()::_singleton>, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_list.h:823
#21 0x00007fffe9bd1d1e in c10::Dispatcher::~Dispatcher (this=0x7ffff5172560 <c10::Dispatcher::realSingleton()::_singleton>, __in_chrg=<optimized out>)
    at pytorch-clean/aten/src/ATen/core/dispatch/Dispatcher.h:61
#22 0x00007ffff7c8c8a7 in __run_exit_handlers (status=0, listp=0x7ffff7e32718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, 
    run_dtors=run_dtors@entry=true) at exit.c:108
#23 0x00007ffff7c8ca60 in __GI_exit (status=<optimized out>) at exit.c:139
#24 0x00007ffff7c6a08a in __libc_start_main (main=0x555555675cc0 <main>, argc=2, argv=0x7fffffffdf28, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdf18) at ../csu/libc-start.c:342
#25 0x00005555557556a0 in _start ()

**Comment by lijing-mt** [comment]
maybe #95464 fixed this?
