### ISSUE TITLE
torch.compile() ignores LD_LIBRARY_PATH variable

### ISSUE THREAD

**Issue by 3outeille** [pytorch/pytorch#94582]
### 🐛 Describe the bug

Given the `Specs` section below, pytorch 2 works flawless with the following snippet

```python
import torch
import torchvision.models as models

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.get_device_name(0))

print("Create Resnet")
model = models.resnet18().cuda()
print("Create optimizer")
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

x = torch.randn(16, 3, 224, 224).cuda()
optimizer.zero_grad()
print("Forward pass")
out = model(x)
print("Backward pass")
out.sum().backward()
print("Step optimizer")
optimizer.step()

print("Done")
```

- However, using the `torch.compile()` feature as follow  results in `/usr/bin/ld: cannot find -lcuda`

```python
import torch
import torchvision.models as models

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.get_device_name(0))

print("Create Resnet")
model = models.resnet18().cuda()
print("Create optimizer")
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
print("Compile model")
compiled_model = torch.compile(model)

x = torch.randn(16, 3, 224, 224).cuda()
optimizer.zero_grad()
print("Forward pass")
out = compiled_model(x) # <--- CRASH HERE
print("Backward pass")
out.sum().backward()
print("Step optimizer")
optimizer.step()

print("Done")
```

- **I have multiple versions of CUDA in my machine, this is why in my `bashrc` I need to specify the `LD_LIBRARY_PATH`**

# Specs

- in my `bashrc`

```
# CUDA
export PATH=/usr/local/cuda-11.7/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.7/targets/x86_64-linux/lib/stubs/libcuda.so:$LD_LIBRARY_PATH
```
![image](https://user-images.githubusercontent.com/47445085/218073016-6987b87d-2b47-4a87-b8c1-664f9972edd8.png)

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0.dev20230209+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.17

Python version: 3.9.12 (main, Feb  9 2023, 16:08:09)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (64-bit runtime)
Python platform: Linux-5.4.188-1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla V100-PCIE-16GB
Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6134 CPU @ 3.20GHz
Stepping:              4
CPU MHz:               1296.153
CPU max MHz:           3700.0000
CPU min MHz:           1200.0000
BogoMIPS:              6400.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              25344K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_pkg_req pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230209+cu117
[pip3] torchaudio==2.0.0.dev20230208+cu117
[pip3] torchvision==0.15.0.dev20230209+cu117
[conda] Could not collect
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by mactavish91** [comment]
I met the same problem.

**Comment by 3outeille** [comment]
> I met the same problem.

Did you find a way to solve it ?

**Comment by mactavish91** [comment]
@3outeille 
I test it on two machine, one with cuda11.4 can run the code, the other machine is installed with 11.3 and 11.7 at the same time and cause this error. I don't know how to solve it.

**Comment by ezyang** [comment]
Are you able to post a backtrace of the error

**Comment by malfet** [comment]
By the way, one should never try to load an executable with LD_LIBRARY_PATH pointing to stubs, which as they name suggest are just stubs that return an error on every API call

**Comment by ngimel** [comment]
`libcuda` comes as part of the driver, not toolkit, and you can have only one driver installed on your system. LD_LIBRARY_PATH pointing to some toolkit should not affect being able to link with libcuda.

**Comment by 3outeille** [comment]
@ezyang 

```
2.0.0.dev20230209+cu117
11.7
Tesla V100-PCIE-16GB
Create Resnet
Create optimizer
Compile model
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
Forward pass
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/f.mom/sync/.pyenv/versions/3.9.12/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 548, in _worker_compile
    kernel.precompile(warm_cache_only_with_cc=cc)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 67, in precompile
    self.launchers = [
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 68, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 81, in _precompile_config
    triton.compile(
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/triton/compiler.py", line 1239, in compile
    so = _build(fn.__name__, src_path, tmpdir)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/triton/compiler.py", line 1169, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/home/f.mom/sync/.pyenv/versions/3.9.12/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpgvzrwqxb/main.c', '-O3', '-I/usr/local/cuda/include', '-I/home/f.mom/sync/.pyenv/versions/3.9.12/include/python3.9', '-I/tmp/tmpgvzrwqxb', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpgvzrwqxb/triton_.cpython-39-x86_64-linux-gnu.so']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 670, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/__init__.py", line 1379, in __call__
    return self.compile_fn(model_, inputs_, config_patches=self.config)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 426, in compile_fx
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
    return aot_autograd(
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2483, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2180, in create_aot_dispatcher_function
/usr/bin/ld: cannot find -lcuda
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1412, in aot_wrapper_dedupe
collect2: error: ld returned 1 exit status
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1689, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 401, in fw_compiler
    return inner_compile(
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/3.9.12/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 155, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/graph.py", line 588, in compile_to_fn
    return self.compile_to_module().call
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/graph.py", line 577, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 527, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_f.mom/zz/czzu22sthbnpal7yuf2dks6s3q6yfsynproybes7lq4kcnl26lgu.py", line 1411, in <module>
    async_compile.wait(globals())
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 714, in wait
    scope[key] = result.result()
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 572, in result
    self.future.result()
  File "/home/f.mom/sync/.pyenv/versions/3.9.12/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/f.mom/sync/.pyenv/versions/3.9.12/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpgvzrwqxb/main.c', '-O3', '-I/usr/local/cuda/include', '-I/home/f.mom/sync/.pyenv/versions/3.9.12/include/python3.9', '-I/tmp/tmpgvzrwqxb', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpgvzrwqxb/triton_.cpython-39-x86_64-linux-gnu.so']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/nfs/home/f.mom/nanoGPT/draft.py", line 19, in <module>
    out = compiled_model(x)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 330, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 377, in transform_code_object
    transformations(instructions, code_options)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1681, in run
    super().run()
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 569, in run
    and self.step()
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 532, in step
    getattr(self, inst.opname)(inst)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1747, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 517, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/f.mom/sync/.pyenv/versions/env-torch2-cuda117/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpgvzrwqxb/main.c', '-O3', '-I/usr/local/cuda/include', '-I/home/f.mom/sync/.pyenv/versions/3.9.12/include/python3.9', '-I/tmp/tmpgvzrwqxb', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpgvzrwqxb/triton_.cpython-39-x86_64-linux-gnu.so']' returned non-zero exit status 1.

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
```

**Comment by 3outeille** [comment]
I did a reinstall but this time without manually changing the env variables but this return the same error. What is weird is the installation seemed to properly set LD_LIBARY_PATH alone `/home/f.mom/opt/cudnn/cudnn-8.5.0/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/nvvm/lib64:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el7_9.x86_64/jre/lib/amd64/server:/opt/hadoop2/hadoop/lib/native:/opt/nccl/cuda9.2_2.3.5/lib:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el7_9.x86_64/jre/lib/amd64/server:/opt/hadoop2/hadoop/lib/native:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el7_9.x86_64/jre/lib/amd64/server:/opt/hadoop2/hadoop/lib/native::/usr/local/cuda/compat:/usr/local/nvidia/lib:/usr/local/nvidia/lib64::/usr/local/cuda/compat:/usr/local/nvidia/lib:/usr/local/nvidia/lib64::/usr/local/cuda/compat:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:`

**Comment by SomeoneSerge** [comment]
Seems like a duplicate of https://github.com/pytorch/pytorch/issues/92745

**Comment by 3outeille** [comment]
`export LIBRARY_PATH=/usr/local/nvidia/lib64:$LIBRARY_PATH` did the trick, thanks
