### ISSUE TITLE
torch.autocast + einops.rearrange breaks torch.compile

### ISSUE THREAD

**Issue by Parskatt** [pytorch/pytorch#94598]
### 🐛 Describe the bug

The following code crashes
```python
import torch
from einops import rearrange
    

class MyAutocastModel(torch.nn.Module):
    def forward(self,x):
        with torch.autocast(device_type="cuda"):
            return rearrange(x,"B C H W -> B H W C")
        
model = torch.compile(MyAutocastModel())
model(torch.randn(3,3,32,32).cuda())
```

Note that this is specific for the **combination** of autocast and rearrange. Running them separately works fine.
Possibly related issues:
https://github.com/pytorch/pytorch/issues/90375

### Error logs

```
Traceback (most recent call last):
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1692, in run
    super().run()
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 337, in wrapper
    self.output.compile_subgraph(self, reason=reason)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 468, in compile_subgraph
    tx.prune_dead_locals()
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 420, in prune_dead_locals
    self.output.side_effects.prune_dead_object_new(self)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/side_effects.py", line 268, in prune_dead_object_new
    VariableTracker.apply(visit, (tx.stack, tx.symbolic_locals))
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/variables/base.py", line 106, in apply
    result = tuple(cls.apply(fn, v, cache, skip_fn) for v in value)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/variables/base.py", line 106, in <genexpr>
    result = tuple(cls.apply(fn, v, cache, skip_fn) for v in value)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/variables/base.py", line 104, in apply
    result = [cls.apply(fn, v, cache, skip_fn) for v in value]
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/variables/base.py", line 104, in <listcomp>
    result = [cls.apply(fn, v, cache, skip_fn) for v in value]
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/variables/base.py", line 96, in apply
    updated_dict[key] = cls.apply(
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/variables/base.py", line 99, in apply
    result = fn(value.clone(**updated_dict))
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/variables/base.py", line 65, in clone
    return self.__class__(**args)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/variables/base.py", line 27, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/variables/misc.py", line 386, in __init__
    super(AutocastModeVariable, self).__init__(
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/variables/misc.py", line 170, in __init__
    super(ContextWrappingVariable, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'mode'

from user code:
   File "compile_experiment.py", line 7, in forward
    return rearrange(x,"B C H W -> B H W C")


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "compile_experiment.py", line 12, in <module>
    model(torch.randn(3,3,32,32).cuda())
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 83, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 94, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/johed950/miniconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 470, in _compile
    raise InternalTorchDynamoError() from e
torch._dynamo.exc.InternalTorchDynamoError
```

### Versions

[conda] cudatoolkit               11.8.0              h37601d7_11    conda-forge
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-lightning         1.3.5                    pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230116+cu117          pypi_0    pypi
[conda] torchmetrics              0.6.0                    pypi_0    pypi
[conda] torchvision               0.15.0.dev20230116+cu117          pypi_0    pypi

(also einops 0.6.0)

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by Parskatt** [comment]
When replacing 
```python 
return rearrange(x,"B C H W -> B H W C")
```
with
```python 
return x.permute(0,2,3,1)
```
the example does not crash.

**Comment by Parskatt** [comment]
![image](https://user-images.githubusercontent.com/22053118/218132032-280e0193-5ad7-4537-8822-a19ca756f54b.png)

Not sure whether this is helpful, but the mysterious "mode" kwarg has "enter_functional_autocast"
![image](https://user-images.githubusercontent.com/22053118/218132387-8a5f757a-7969-4ee2-9035-e8594aa518e7.png)

It seems like this kwarg is something quite reasonable, so not sure what happened. Perhaps I have some version mismatch?

**Comment by Chillee** [comment]
I can repro this error.

**Comment by yanboliang** [comment]
I think this is a bug of ```AutocastModeVariable```, which is triggered when there is graph break under the context manager.   If you switch to use ```x.permute(0,2,3,1)```, there is no graph break and won't trigger this bug. The bug has been tracked at https://github.com/pytorch/pytorch/issues/93890

**Comment by Parskatt** [comment]
@yanboliang yes, that seems like the reason. Looking forward to the fix :)

**Comment by Parskatt** [comment]
@yanboliang on latest version of pytorch this no longer breaks, (thanks to this https://github.com/pytorch/pytorch/commit/d1d5d16df3766bc6a6c9ebe1168ff652bcdcaa5e I'm gonna assume). Thanks :)
