### ISSUE TITLE
Dynamo: BUILD_SET op is unsupported

### ISSUE THREAD

**Issue by Skylion007** [pytorch/pytorch#94738]
### 🐛 Describe the bug

While applying flake8-comprehensions in https://github.com/pytorch/pytorch/actions/runs/4152340071/jobs/7183309255 I had to revert and whitelist one of the changes because the BUILD_SET instruction operation was not supported. Seems to be a somewhat rare instruction since it hasn't caused any issues so far. I just wanted to make the maintainers of Dynamo aware of it in case it's an easy fix as it would expand the amount of Python code that is compilable with dynamo.

The full testcase stack trace is here. It's a little surprising that constructing the set with a generator works, but constructing the set with simple Python synax directly does not.
```
======================================================================
ERROR [0.006s]: test_reformer_min_chunk_len (__main__.ReproTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "dynamo/test_repros.py", line 1156, in test_reformer_min_chunk_len
    self.assertEqual(opt_fn(cfg), 64)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 330, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 376, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1681, in run
    super().run()
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 569, in run
    and self.step()
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 532, in step
    getattr(self, inst.opname)(inst)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 338, in wrapper
    return inner_fn(self, inst)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 958, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 466, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 259, in call_function
    return super().call_function(tx, args, kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 92, in call_function
    return tx.inline_user_function_return(
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 502, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1761, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1817, in inline_call_
    tracer.run()
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 569, in run
    and self.step()
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 531, in step
    unimplemented(f"missing: {inst.opname}")
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: missing: BUILD_SET

from user code:
   File "dynamo/test_repros.py", line 1150, in fn
    t.fill_(_get_min_chunk_len(cfg))
  File "dynamo/test_repros.py", line 652, in _get_min_chunk_len
    elif len(attn_types_set) == 2 and attn_types_set == {"lsh", "local"}:

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

To repro, just change the line test_repros.py to the following:
```
File "dynamo/test_repros.py", line 652, in _get_min_chunk_len
    elif len(attn_types_set) == 2 and attn_types_set == {"lsh", "local"}:
```

### Versions

master. All other info for repro should be available in the PR.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by yanboliang** [comment]
Yea, there is no ```SetVariable``` in dynamo yet.

**Comment by ezyang** [comment]
This should be pretty easy to do, can advise if you're interested.

**Comment by bhavyanarang** [comment]
Hi @ezyang, I am interested in solving this but don't how to. Can you please advise me?

**Comment by ezyang** [comment]
need to add a BUILD_SET implementation to torch/_dynamo/symbolic_convert.py similar to BUILD_TUPLE and friends

**Comment by bhavyanarang** [comment]
Got it, thanks! Can you please assign this issue to me?

**Comment by Rakshith-sakhamuri** [comment]
Hey @ezyang,I'm interested in solving this and got what to do ,can you assign this to me?

**Comment by ezyang** [comment]
Please check commentary on https://github.com/pytorch/pytorch/pull/95102 this is not a trivial fix now

**Comment by yanboliang** [comment]
@ezyang @Rakshith-sakhamuri  Torchbench ```hf_Reformer``` model requires this feature as well, do you mind if I take over this task?

**Comment by ezyang** [comment]
yes

**Comment by Rakshith-sakhamuri** [comment]
@yanboliang you can take over this task
