### ISSUE TITLE
test_as_strided intermittently fails

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#9479]
Examples: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py2.7.9-test/11014/console https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-macos-10.13-py3-test1/3757/console

```
00:20:35 ======================================================================
00:20:35 ERROR: test_as_strided (__main__.TestAutograd)
00:20:35 ----------------------------------------------------------------------
00:20:35 Traceback (most recent call last):
00:20:35   File "test_autograd.py", line 2122, in test_as_strided
00:20:35     test(torch.randn(10), None, [1, 2, 1, 5], [0, 5, 100, 1], 2)
00:20:35   File "test_autograd.py", line 2115, in test
00:20:35     gradcheck(closure, [x])
00:20:35   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/autograd/gradcheck.py", line 214, in gradcheck
00:20:35     'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
00:20:35   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/autograd/gradcheck.py", line 194, in fail_test
00:20:35     raise RuntimeError(msg)
00:20:35 RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
00:20:35 numerical:tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,    nan,
00:20:35          0.0000],
00:20:35         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,    nan,
00:20:35          0.0000],
00:20:35         [1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,    nan,
00:20:35          0.0000],
00:20:35         [0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,    nan,
00:20:35          0.0000],
00:20:35         [0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,    nan,
00:20:35          0.0000],
00:20:35         [0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,    nan,
00:20:35          0.0000],
00:20:35         [0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000,    nan,
00:20:35          0.0000],
00:20:35         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000,    nan,
00:20:35          0.0000],
00:20:35         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000,    nan,
00:20:35          0.0000],
00:20:35         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000,    nan,
00:20:35          0.0000]])
00:20:35 analytical:tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
00:20:35         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
00:20:35         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
00:20:35         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
00:20:35         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
00:20:35         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
00:20:35         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
00:20:35         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
00:20:35         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
00:20:35         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])
00:20:35 
```

CC @SsnL, since you fixed `as_strided` backward recently.

**Comment by SsnL** [comment]
ah I know what's wrong. will fix tomorrow.
