### ISSUE TITLE
EAGER backend raise `torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(RLock) acquire [] {}` error but training is continuing

### ISSUE THREAD

**Issue by LeoXing1996** [pytorch/pytorch#94795]
### 🐛 Describe the bug

Refers to issue #94299, I manually add patch #94547 to `torch._dynamo/variables/misc.py` to fix bug 1 (`TypeError: super(type, obj) `)

When I add `dynamo.config.log_level = logging.DEBUG` and `dynamo.config.suppress_errors = True` to my code,  `torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(RLock) acquire [] {}` occurs, but the training is continuing.
If a remove `dynamo.config.log_level = logging.DEBUG` and `dynamo.config.suppress_errors = True`, no error will be printed on the screen. 
I wonder whether this `torch._dynamo.exc.Unsupported` error will harm the training process, or should I just simply ignore this error?

### Error logs

The complete debug log: [Google Drive](https://drive.google.com/file/d/11hWonVTzPGMUQcHsukrvVj4kX6ZH0z0j/view?usp=sharing)

Error Traceback of the debug log:

```
Traceback (most recent call last):
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 333, in wrapper
    return inner_fn(self, inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 990, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 289, in call_function
    return super().call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 259, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 92, in call_function
    return tx.inline_user_function_return(
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 497, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1793, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1849, in inline_call_
    tracer.run()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 333, in wrapper
    return inner_fn(self, inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 990, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 289, in call_function
    return super().call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 259, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 92, in call_function
    return tx.inline_user_function_return(
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 497, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1793, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1849, in inline_call_
    tracer.run()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 333, in wrapper
    return inner_fn(self, inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 990, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 675, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 80, in call_method
    return variables.UserMethodVariable(
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 289, in call_function
    return super().call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 259, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 92, in call_function
    return tx.inline_user_function_return(
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 497, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1793, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1849, in inline_call_
    tracer.run()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 333, in wrapper
    return inner_fn(self, inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 990, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 259, in call_function
    return super(UserFunctionVariable, self).call_function(tx, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 92, in call_function
    return tx.inline_user_function_return(
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 497, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1793, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1849, in inline_call_
    tracer.run()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 333, in wrapper
    return inner_fn(self, inst)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 990, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 675, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/user_defined.py", line 233, in call_method
    return super().call_method(tx, name, args, kwargs)
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/variables/base.py", line 253, in call_method
    raise unimplemented(f"call_method {self} {name} {args} {kwargs}")
  File "/mnt/petrelfs/xingzhening/miniforge3/envs/pt20-cu116/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(RLock) acquire [] {}
```

### Minified repro

1. Install dependencied of OpenMMLab

```
ninja
git+https://github.com/open-mmlab/mmengine@experimental/compile
git+https://github.com/open-mmlab/mmcv@2.x
```

3. Install MMEditing from source

```bash
git clone git@github.com:open-mmlab/mmediting.git
cd mmediting
git checkout dev-1.x
pip install -r requirements.txt
pip install -e .
```

4. Launch training

```bash
# all GAN models failed since they all build upon `BaseGAN`
python tools/train.py configs/wgan-gp/wgangp_GN_1xb64-160kiters_celeba-cropped-128x128.py \
    --cfg-options compile.target='train_step' compile.backend='eager'
```

### Versions

Pytorch version: 2.0.0.dev20230202+cu116 (with Patch #94547)

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by jon-chuang** [comment]
Can you show the full log? If there is a graph break (seems like it here due to Rlock) then this message is printed as the cause for the graph break.

**Comment by jansel** [comment]
`Unsupported` means there is a graph break on `RLock.acquire()`, so part of the model is being run in eager mode rather than being compiled.

**Comment by LeoXing1996** [comment]
> Can you show the full log? If there is a graph break (seems like it here due to Rlock) then this message is printed as the cause for the graph break.
> 
> (i.e. you should not worry)

@jon-chuang  and @jansel, thanks for your response! My complete debug log can be downloaded from this URL: [Google Drive](https://drive.google.com/file/d/11hWonVTzPGMUQcHsukrvVj4kX6ZH0z0j/view).

**Comment by jon-chuang** [comment]
Indeed, it's a graph break:
```
[2023-02-10 13:34:14,628] torch._dynamo.symbolic_convert: [DEBUG] break_graph_if_unsupported triggered compile
Traceback (most recent call last):
```

**Comment by LeoXing1996** [comment]
@jon-chuang. Thanks for your response! Sorry that I didn't read the technical documentation on graph break and dynamo before. Now I know what happens to my code.
