### ISSUE TITLE
RuntimeError: Tensors must be contiguous (DeepSpeed)

### ISSUE THREAD

**Issue by FarzanT** [pytorch/pytorch#94907]
### Description
The DeepSpeed package uses the `broadcast` function in [torch/distributed/distributed_c10d.py](https://github.com/pytorch/pytorch/blob/3ace14eb8b5e437322acf962d2f170561fd4e3bc/torch/distributed/distributed_c10d.py). However it seems to pass non-contiguous tensors when contiguous ones are expected, throwing an error like so:
<details><summary>Stack Trace</summary>

```
Traceback (most recent call last):
  File "src/pretrain_sctranspert.py", line 287, in <module>
    perturbation_model = train_transformer(
  File "src/pretrain_sctranspert.py", line 274, in train_transformer
    trainer.fit(model, train_loader, valid_loader)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1093, in _run
    self.strategy.setup(self)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/pytorch_lightning/strategies/deepspeed.py", line 345, in setup
    self.init_deepspeed()
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/pytorch_lightning/strategies/deepspeed.py", line 456, in init_deepspeed
    self._initialize_deepspeed_train(model)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/pytorch_lightning/strategies/deepspeed.py", line 493, in _initialize_deepspeed_train
    model, deepspeed_optimizer = self._setup_model_and_optimizer(model, optimizer, scheduler)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/pytorch_lightning/strategies/deepspeed.py", line 414, in _setup_model_and_optimizer
    deepspeed_engine, deepspeed_optimizer, _, _ = deepspeed.initialize(
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 301, in __init__
    self._configure_distributed_model(model)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1187, in _configure_distributed_model
    self._broadcast_model()
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1102, in _broadcast_model
    dist.broadcast(p,
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 127, in log_wrapper
    return func(*args, **kwargs)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 232, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 70, in broadcast
    return torch.distributed.broadcast(tensor=tensor,
  File "/home/l/lstein/ftaj/.conda/envs/autopath/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1404, in broadcast
    work = group.broadcast([tensor], opts)
RuntimeError: Tensors must be contiguous
```
</details>

The error originates here:
https://github.com/pytorch/pytorch/blob/3ace14eb8b5e437322acf962d2f170561fd4e3bc/torch/distributed/distributed_c10d.py#L1555
A simple fix is to force the tensors to be contiguous, e.g.:
```python
work = group.broadcast([tensor.contiguous()], opts)
```
This has removed errors on my side. If this change is acceptable, I'll open a pull request.
A potentially related issue may be #79043. Fixes in #79060 may be related to this.

Thank you

### Versions
I am using PyTorch 1.13.0 with CUDA 11.4.4 with DeepSpeed 0.8.0 (which doesn't show in the report below).
<details><summary>collect_env.py results</summary>

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux 8.4 (Ootpa) (ppc64le)
GCC version: (GCC) 10.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.8.8 (default, Apr 13 2021, 20:11:25)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.18.0-305.72.1.el8_4.ppc64le-ppc64le-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: 11.4.152
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 450.191.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:        ppc64le
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  4
Core(s) per socket:  16
Socket(s):           2
NUMA node(s):        6
Model:               2.3 (pvr 004e 1203)
Model name:          POWER9, altivec supported
CPU max MHz:         3800.0000
CPU min MHz:         2300.0000
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            10240K
NUMA node0 CPU(s):   0-63
NUMA node8 CPU(s):   64-127
NUMA node252 CPU(s):
NUMA node253 CPU(s):
NUMA node254 CPU(s):
NUMA node255 CPU(s):

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] numpydoc==1.1.0
[conda] nomkl                     3.0                           0
[conda] numpy                     1.20.1           py38h960add4_0
[conda] numpy-base                1.20.1           py38hc5590f2_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
```
</details>

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by H-Huang** [comment]
Thanks for raising the issue! `torch.distributed` collectives are in-place operations. With this change, assuming a non-contiguous tensor is passed in,. then a new block of memory is allocated for the contiguous tensor to be created. Thus the returned tensor will be different than the one passed in, which changes the semantics of the API. I think it might be better to handle this at the application level (e.g. DeepSpeed) to ensure the tensor is contiguous before being passed in.

**Comment by FarzanT** [comment]
Thank you @H-Huang for explaining the consequences of making such a change!
I'll bring this to the attention of DeepSpeed maintainers.
