### ISSUE TITLE
[numpy] mean & nanmean should support int dtypes

### ISSUE THREAD

**Issue by khushi-411** [pytorch/pytorch#94909]
#### NumPy
```python
>>> import numpy as np
>>> k = np.array([1, 2, 3], dtype=np.int32)
>>> np.mean(k)
2.0
>>> np.nanmean(k)
2.0
```
#### PyTorch
```python
>>> import torch
>>> k = torch.tensor([1, 2, 3], dtype=torch.int32)
>>> torch.mean(k)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Int
>>> torch.nanmean(k)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: nanmean(): expected input to have floating point dtype but got Int
```
As discussed here: https://github.com/pytorch/pytorch/pull/93199#issuecomment-1431169963

**Comment by Laurent2916** [comment]
Hi @khushi-411 !

I ran into the same issue, workarounds obviously include:
```python
>>> torch.mean(k.float())
tensor(2.)
>>> torch.mean(k, dtype=torch.float)
tensor(2.)
```
Though not having to "convert to floats" would be great.

The same could be done for `std` and `var` (and all their derivatives), which currently output:
```python
>>> torch.std(k)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: std and var only support floating point and complex dtypes
>>> torch.var(k)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: std and var only support floating point and complex dtypes
```
