### ISSUE TITLE
pytorch2.0 from nvidia docker image: cannot import name 'Backend' from 'torch._C._distributed_c10d'

### ISSUE THREAD

**Issue by rijobro** [pytorch/pytorch#94902]
### 🐛 Describe the bug

I have a docker image that I create with:
```dockerfile
FROM nvcr.io/nvidia/pytorch:23.01-py3

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b && \
    eval "$(/home/${UNAME}/miniconda3/bin/conda shell.bash hook)" && \
    conda init && \
    conda create -n py3.11-pt2 -c conda-forge python=3.11 -y && \
    conda activate py3.11-pt2 && \
    pip install numpy --pre torch --force-reinstall --index-url https://download.pytorch.org/whl/nightly/cu117
```
This succeeds, but when I run the docker image, and run `python -c "import torch"`, I get the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rbrown/miniconda3/envs/test3/lib/python3.10/site-packages/torch/__init__.py", line 1179, in <module>
    from .functional import *  # noqa: F403
  File "/home/rbrown/miniconda3/envs/test3/lib/python3.10/site-packages/torch/functional.py", line 8, in <module>
    import torch.nn.functional as F
  File "/home/rbrown/miniconda3/envs/test3/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/rbrown/miniconda3/envs/test3/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/home/rbrown/miniconda3/envs/test3/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 7, in <module>
    from .. import functional as F
  File "/home/rbrown/miniconda3/envs/test3/lib/python3.10/site-packages/torch/nn/functional.py", line 19, in <module>
    from .._jit_internal import boolean_dispatch, _overload, BroadcastingList1, BroadcastingList2, BroadcastingList3
  File "/home/rbrown/miniconda3/envs/test3/lib/python3.10/site-packages/torch/_jit_internal.py", line 40, in <module>
    import torch.distributed.rpc
  File "/home/rbrown/miniconda3/envs/test3/lib/python3.10/site-packages/torch/distributed/__init__.py", line 26, in <module>
    from torch._C._distributed_c10d import (
ImportError: cannot import name 'Backend' from 'torch._C._distributed_c10d' (unknown location)
```

### Versions

The above code snippet is for python3.11, but the same error is shown for python3.9 and 3.10.

cc @ngimel

**Comment by rijobro** [comment]
Duplicate (but not fixed, only worked around): https://github.com/pytorch/pytorch/issues/94806

**Comment by ngimel** [comment]
As @ptrblck said, it's a duplicate.

**Comment by rijobro** [comment]
I pointed out that it was a duplicate (not @ptrblck). But the original wasn't fixed, it was only worked around. I don't mind if you keep this one closed, but I think that either this issue or https://github.com/pytorch/pytorch/issues/94806 should be open until the issue is fixed.
