### ISSUE TITLE
`Tensor.select` + `add_` triggers C++ Compile Error

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#94960]
### 🐛 Describe the bug

The following program works fine in eager mode but triggers C++ compile error when using `torch.compile`.
```python
import torch

def fn(input):
    v = input.select(2, 0)
    return v.add_(1) # works w/ non-inplace op "add"

x = torch.rand([1, 2, 1, 2, 1, 2]) # works fine w/ other shapes like [1, 1, 1, 1, 1, 1]

ret_eager = fn(x)
print('==== Eager mode OK! ====')

compiled = torch.compile(fn)
print('==== torchcomp compilation OK! ====')

ret_compiled = compiled(x)
print('==== torchcomp mode OK! ====')
```
<details><summary>Error log</summary>

```
==== Eager mode OK! ====
==== torchcomp compilation OK! ====
Traceback (most recent call last):
  File "python3.8/site-packages/torch/_inductor/codecache.py", line 505, in load
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/opt/miniconda3/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/miniconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['g++', '/tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp', '-shared', '-fPIC', '-Wall', '-std=c++17', '-Wno-unused-variable', '-Ipython3.8/site-packages/torch/include', '-Ipython3.8/site-packages/torch/include/torch/csrc/api/include', '-Ipython3.8/site-packages/torch/include/TH', '-Ipython3.8/site-packages/torch/include/THC', '-I/opt/miniconda3/include/python3.8', '-Lpython3.8/site-packages/torch/lib', '-L/opt/miniconda3/lib', '-lc10', '-ltorch', '-ltorch_cpu', '-ltorch_python', '-lgomp', '-DCPU_CAPABILITY_AVX2', '-O3', '-ffast-math', '-fno-finite-math-only', '-march=native', '-fopenmp', '-D', 'C10_USING_CUSTOM_GENERATED_MACROS', '-o/tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.so']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "python3.8/site-packages/torch/_dynamo/output_graph.py", line 670, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "python3.8/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "python3.8/site-packages/torch/__init__.py", line 1390, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "python3.8/site-packages/torch/_inductor/compile_fx.py", line 455, in compile_fx
    return aot_autograd(
  File "python3.8/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2798, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2491, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1713, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1326, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args_with_views_handled)
  File "python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.8/site-packages/torch/_inductor/compile_fx.py", line 430, in fw_compiler
    return inner_compile(
  File "python3.8/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "python3.8/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "python3.8/site-packages/torch/_inductor/compile_fx.py", line 177, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "python3.8/site-packages/torch/_inductor/graph.py", line 586, in compile_to_fn
    return self.compile_to_module().call
  File "python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.8/site-packages/torch/_inductor/graph.py", line 575, in compile_to_module
    mod = PyCodeCache.load(code)
  File "python3.8/site-packages/torch/_inductor/codecache.py", line 528, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_/jt/cjtufhxsjunkl2rm3lmj2loxacznfviktb4w236u3m2pre5y62e4.py", line 55, in <module>
    async_compile.wait(globals())
  File "python3.8/site-packages/torch/_inductor/codecache.py", line 715, in wait
    scope[key] = result.result()
  File "/opt/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/opt/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/miniconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "python3.8/site-packages/torch/_inductor/codecache.py", line 692, in task
    return CppCodeCache.load(source_code).kernel
  File "python3.8/site-packages/torch/_inductor/codecache.py", line 507, in load
    raise exc.CppCompileError(cmd, e.output) from e
torch._inductor.exc.CppCompileError: C++ compile error

Command:
g++ /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp -shared -fPIC -Wall -std=c++17 -Wno-unused-variable -Ipython3.8/site-packages/torch/include -Ipython3.8/site-packages/torch/include/torch/csrc/api/include -Ipython3.8/site-packages/torch/include/TH -Ipython3.8/site-packages/torch/include/THC -I/opt/miniconda3/include/python3.8 -Lpython3.8/site-packages/torch/lib -L/opt/miniconda3/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lgomp -DCPU_CAPABILITY_AVX2 -O3 -ffast-math -fno-finite-math-only -march=native -fopenmp -D C10_USING_CUSTOM_GENERATED_MACROS -o/tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.so

Output:
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:8,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec_base.h:1011: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
 1011 | # pragma unroll
      | 
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:10,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_float.h:438: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  438 | #pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_float.h:442: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  442 | #pragma unroll
      | 
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:12,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_bfloat16.h:693: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  693 | #pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_bfloat16.h:698: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  698 | #pragma unroll
      | 
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:13,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_double.h:403: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  403 | #pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_double.h:407: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  407 | #pragma unroll
      | 
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:14,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:287: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  287 | # pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:295: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  295 | # pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:307: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  307 | # pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:315: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  315 | # pragma unroll
      | 
In file included from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
/tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:66: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   66 | #pragma unroll
      | 
/tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:75: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   75 | #pragma unroll
      | 
/tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:88: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   88 | #pragma unroll
      | 
/tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp: In function ‘void kernel(const float*, float*, float*)’:
/tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:15:60: error: cannot convert ‘at::vec::CPU_CAPABILITY::Vectorized<int>’ to ‘const at::vec::CPU_CAPABILITY::Vectorized<float>&’
   15 |             auto tmp5 = decltype(tmp4)::blendv(tmp2, tmp4, tmp1);
      |                                                            ^~~~
      |                                                            |
      |                                                            at::vec::CPU_CAPABILITY::Vectorized<int>
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:10,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_float.h:46:56: note:   initializing argument 3 of ‘static at::vec::CPU_CAPABILITY::Vectorized<float> at::vec::CPU_CAPABILITY::Vectorized<float>::blendv(const at::vec::CPU_CAPABILITY::Vectorized<float>&, const at::vec::CPU_CAPABILITY::Vectorized<float>&, const at::vec::CPU_CAPABILITY::Vectorized<float>&)’
   46 |                               const Vectorized<float>& mask) {
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:24:30: warning: self-comparison always evaluates to true [-Wtautological-compare]
   24 |             auto tmp1 = tmp0 == tmp0;
      |                         ~~~~ ^~ ~~~~


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "repro.py", line 15, in <module>
    ret_compiled = compiled(x)
  File "python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "python3.8/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "python3.8/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "python3.8/site-packages/torch/_dynamo/output_graph.py", line 517, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "python3.8/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.8/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised CppCompileError: C++ compile error

Command:
g++ /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp -shared -fPIC -Wall -std=c++17 -Wno-unused-variable -Ipython3.8/site-packages/torch/include -Ipython3.8/site-packages/torch/include/torch/csrc/api/include -Ipython3.8/site-packages/torch/include/TH -Ipython3.8/site-packages/torch/include/THC -I/opt/miniconda3/include/python3.8 -Lpython3.8/site-packages/torch/lib -L/opt/miniconda3/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lgomp -DCPU_CAPABILITY_AVX2 -O3 -ffast-math -fno-finite-math-only -march=native -fopenmp -D C10_USING_CUSTOM_GENERATED_MACROS -o/tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.so

Output:
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:8,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec_base.h:1011: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
 1011 | # pragma unroll
      | 
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:10,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_float.h:438: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  438 | #pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_float.h:442: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  442 | #pragma unroll
      | 
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:12,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_bfloat16.h:693: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  693 | #pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_bfloat16.h:698: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  698 | #pragma unroll
      | 
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:13,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_double.h:403: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  403 | #pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_double.h:407: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  407 | #pragma unroll
      | 
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:14,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:287: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  287 | # pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:295: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  295 | # pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:307: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  307 | # pragma unroll
      | 
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:315: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  315 | # pragma unroll
      | 
In file included from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
/tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:66: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   66 | #pragma unroll
      | 
/tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:75: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   75 | #pragma unroll
      | 
/tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:88: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   88 | #pragma unroll
      | 
/tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp: In function ‘void kernel(const float*, float*, float*)’:
/tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:15:60: error: cannot convert ‘at::vec::CPU_CAPABILITY::Vectorized<int>’ to ‘const at::vec::CPU_CAPABILITY::Vectorized<float>&’
   15 |             auto tmp5 = decltype(tmp4)::blendv(tmp2, tmp4, tmp1);
      |                                                            ^~~~
      |                                                            |
      |                                                            at::vec::CPU_CAPABILITY::Vectorized<int>
In file included from python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:10,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.8/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:10,
                 from /tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:2:
python3.8/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_float.h:46:56: note:   initializing argument 3 of ‘static at::vec::CPU_CAPABILITY::Vectorized<float> at::vec::CPU_CAPABILITY::Vectorized<float>::blendv(const at::vec::CPU_CAPABILITY::Vectorized<float>&, const at::vec::CPU_CAPABILITY::Vectorized<float>&, const at::vec::CPU_CAPABILITY::Vectorized<float>&)’
   46 |                               const Vectorized<float>& mask) {
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/tmp/torchinductor_/co/ccotvczo3jgclpphl44niyz6h6sp7wkbggmhhjk57bcz44wzxd4z.cpp:24:30: warning: self-comparison always evaluates to true [-Wtautological-compare]
   24 |             auto tmp1 = tmp0 == tmp0;
      |                         ~~~~ ^~ ~~~~


Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

</details>

### Versions

<details><summary><b> Environment </b><i> [Click to expand]</i></summary>

```
Collecting environment information...
PyTorch version: 2.0.0.dev20230215+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-137-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 510.68.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+c8bfe3f548
[pip3] torch==2.0.0.dev20230215+cu117
[pip3] torchaudio==2.0.0.dev20230215+cu117
[pip3] torchvision==0.15.0.dev20230215+cu117
[conda] No relevant packages
```

</details>

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ngimel** [comment]
IT might be fixed on master

**Comment by bdhirsh** [comment]
I can repro on a master commit from this morning (only for cpu though - it passes on cuda)

**Comment by EikanWang** [comment]
@blzheng , will you PR fix this issue and any progress?

**Comment by blzheng** [comment]
This issue is fixed by https://github.com/pytorch/pytorch/pull/96502 
Close it.
