### ISSUE TITLE
`torch.compile` fails when using `torch.sub` with python constant

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#95181]
### 🐛 Describe the bug

The following program works fine in eager mode but triggers exceptions under `torch.compile`. It seems that there is a type mismatch when casting the input constants into tensors.
```python
import torch

def fn(input):
    return input.sub(1, alpha=2) # ❌
    # input.sub(1) ✅
    # input.sub(torch.tensor([1]), alpha=2) ✅

x = torch.rand([1], dtype=torch.float64) # float16, float32 ✅

ret_eager = fn(x)
print('==== Eager mode OK! ====')

compiled = torch.compile(fn)
print('==== torchcomp compilation OK! ====')

ret_compiled = compiled(x)
print('==== torchcomp mode OK! ====')

"""
==== Eager mode OK! ====
==== torchcomp compilation OK! ====
Traceback (most recent call last):
  File "python3.10/site-packages/torch/_dynamo/utils.py", line 1196, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 989, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1172, in dispatch
    r = func(*args, **kwargs)
  File "python3.10/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "python3.10/site-packages/torch/_prims_common/wrappers.py", line 220, in _fn
    result = fn(*args, **kwargs)
  File "python3.10/site-packages/torch/_prims_common/wrappers.py", line 130, in _fn
    result = fn(**bound.arguments)
  File "python3.10/site-packages/torch/_refs/__init__.py", line 1608, in sub
    return prims.sub(a, b)
  File "python3.10/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "python3.10/site-packages/torch/_prims/__init__.py", line 341, in _elementwise_meta
    utils.check_same_dtype(*args)
  File "python3.10/site-packages/torch/_prims_common/__init__.py", line 1079, in check_same_dtype
    raise RuntimeError(msg)
RuntimeError: Tensor with dtype torch.float32 is not the expected dtype of torch.float64!
"""
```
It's probably related to #93224 and #92324.

### Versions

<details><summary><b> Environment </b><i>[Click to expand]</i></summary>

```
PyTorch version: 2.0.0.dev20230220+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 525.78.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] pytorch-triton==2.0.0+c8bfe3f548
[pip3] torch==2.0.0.dev20230220+cu117
[pip3] torchaudio==2.0.0.dev20230220+cu117
[pip3] torchvision==0.15.0.dev20230220+cu117
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0
```

</details>

cc @ezyang @mruberry @ngimel @Lezcano @peterbell10 @soumith @msaroufim @wconstab @bdhirsh

**Comment by bdhirsh** [comment]
This looks like a primtorch type promotion issue (special care needed for handling scalars)

**Comment by bdhirsh** [comment]
https://github.com/pytorch/pytorch/pull/95421 should fix the primtorch issue

**Comment by bdhirsh** [comment]
That repro now passes on cuda, with the fix. Unfortunately, i get an error when i run with inductor + cpu. The invalid code generated is:
```
#if defined(CPU_CAPABILITY_AVX512) || defined(CPU_CAPABILITY_AVX2)
template <typename SRC>
inline at::vec::Vectorized<float> to_float_mask(at::vec::Vectorized<SRC>& src) {
  assert(
      at::vec::Vectorized<float>::size() == at::vec::Vectorized<SRC>::size());
  at::vec::Vectorized<float> res_vec(0);
#pragma unroll
  for (int i = 0; i < at::vec::Vectorized<float>::size(); i++) {
    res_vec[i] = src[i] ? 0xFFFFFFFF : 0;
  }
  return res_vec;
}
```

Which gives this error:
```
/tmp/torchinductor_hirsheybar/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:90:12: error: overload resolution selected deleted operator '[]'
    res_vec[i] = src[i] ? 0xFFFFFFFF : 0;
    ~~~~~~~^~
/scratch/hirsheybar2/work/pytorch/torch/include/ATen/cpu/vec/vec512/vec512_float.h:125:10: note: candidate function has been explicitly deleted
  float& operator[](int idx) = delete;
         ^
/scratch/hirsheybar2/work/pytorch/torch/include/ATen/cpu/vec/vec512/vec512_float.h:124:16: note: candidate function has been explicitly deleted
  const float& operator[](int idx) const  = delete;
               ^
```

**Comment by XiaobingSuper** [comment]
Yes, it is a CPU backend issue, @bdhirsh , is this error caused by running this test case? I run this test case which applies your path, but I didn't meet such an error.  If not, could you give a reproduce code. Thanks!

**Comment by EikanWang** [comment]
@bdhirsh , I have created a PR https://github.com/pytorch/pytorch/pull/95459 to fix the issue you mentioned. I'm wondering if you could share the case with me. I plan to add the failed case in the CI.

**Comment by bdhirsh** [comment]
@EikanWang yep - when I run this repro on top of https://github.com/pytorch/pytorch/pull/95421, I see inductor cpu failing:

```
import torch
@torch.compile
def f(x):
    return x.sub(1, alpha=2)

f(torch.ones(2, device="cpu", dtype=torch.float64))
```

**Comment by EikanWang** [comment]
@bdhirsh , I applied PR #95421 but could not reproduce this issue. I also changed the `dtype` to `torch.float32` as `Inductor` vectorization has not supported `double` yet and could not reproduce it. But anyway, it is a bug due to `at::vec` does not support indexing. Not sure if there is any other PR that has workaround this issue.
