### ISSUE TITLE
Pytorch 2.0 [compile] Runtime error when compiling torchvision.resnet18

### ISSUE THREAD

**Issue by djwessel** [pytorch/pytorch#95223]
### 🐛 Describe the bug

When running the current nightly build `torch==2.0.0.dev20230202+cu116` and `torchvision==0.15.0.dev20230201+cu116` and using the following example compilation from the PyTorch 2.0 "Get Started" documentation, we are getting an error
```python
import torch
import torchvision.models as models

model = models.resnet18().cuda()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
compiled_model = torch.compile(model)

x = torch.randn(16, 3, 224, 224).cuda()
optimizer.zero_grad()
out = compiled_model(x)
out.sum().backward()
optimizer.step()
```
Error:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    out = compiled_model(x)
  File ".venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/torchvision/models/resnet.py", line 284, in forward
    def forward(self, x: Tensor) -> Tensor:
  File ".venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2497, in forward
    return compiled_fn(full_args)
  File ".venv/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 996, in g
    return f(*args)
  File ".venv/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2066, in debug_compiled_function
    return compiled_function(*args)
  File ".venv/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1930, in compiled_function
    all_outs = CompiledFunction.apply(*args_with_synthetic_bases)
  File ".venv/lib/python3.8/site-packages/torch/autograd/function.py", line 508, in apply
    return super().apply(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1714, in forward
    fw_outs = call_func_with_args(
  File ".venv/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1021, in call_func_with_args
    out = normalize_as_list(f(args))
  File ".venv/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 224, in run
    return model(new_inputs)
  File "/tmp/torchinductor_dwessel/zz/czzu22sthbnpal7yuf2dks6s3q6yfsynproybes7lq4kcnl26lgu.py", line 1428, in call
    triton__2.run(buf0, buf2, buf3, buf5, 448, 28672, grid=grid(448), stream=stream0)
  File ".venv/lib/python3.8/site-packages/torch/_inductor/triton_ops/autotune.py", line 188, in run
    result = launcher(
  File "<string>", line 6, in launcher
RuntimeError: Triton Error [CUDA]: invalid argument
free(): invalid pointer
Aborted (core dumped)

```

This, however, isn't an issue if I use an older build, e.g. `torchvision-0.15.0.dev20230115+cu116` and `torch-2.0.0.dev20230115+cu116`

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0.dev20230202+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          24
On-line CPU(s) list:             0-23
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           33
Model name:                      AMD Ryzen 9 5900X 12-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     4950,1948
CPU min MHz:                     2200,0000
BogoMIPS:                        7400.35
Virtualization:                  AMD-V
L1d cache:                       384 KiB
L1i cache:                       384 KiB
L2 cache:                        6 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.1
[pip3] pytorch-lightning==1.9.2
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230202+cu116
[pip3] torch-optimizer==0.3.0
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.15.0.dev20230201+cu116
[conda] Could not collect

```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by vadimkantorov** [comment]
@malfet maybe this kind of thing should be added to auto-tests?

**Comment by ptrblck** [comment]
> When running the current nightly build torch==2.0.0.dev20230202+cu116 and torchvision==0.15.0.dev20230201+cu116

These builds aren't the newest nightly releases and are ~20 days old.
Could you install the latest one with CUDA 11.7 or 11.8 using the instructions from [here](https://pytorch.org/get-started/locally/) and check if you would still see the issue, please?

**Comment by weiwangmeta** [comment]
This issue has been fixed with new binaries, unfortunately our nightly binary building are failing due to some unrelated internal maintenance work. We will try to fix it today. 
In the meanwhile, you can refer to discussion in https://github.com/pytorch/builder/issues/1318 to temporarily workaround it.

**Comment by weiwangmeta** [comment]
An alternative workaround is to download and pip install these wheels with latest torch 2.0.0. 

[pytorch_triton-2.0.0+d54c04abe2-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/test/pytorch_triton-2.0.0%2Bd54c04abe2-cp310-cp310-linux_x86_64.whl)
[pytorch_triton-2.0.0+d54c04abe2-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/test/pytorch_triton-2.0.0%2Bd54c04abe2-cp311-cp311-linux_x86_64.whl)
[pytorch_triton-2.0.0+d54c04abe2-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/test/pytorch_triton-2.0.0%2Bd54c04abe2-cp38-cp38-linux_x86_64.whl)
[pytorch_triton-2.0.0+d54c04abe2-cp39-cp39-linux_x86_64.whl](https://download.pytorch.org/whl/test/pytorch_triton-2.0.0%2Bd54c04abe2-cp39-cp39-linux_x86_64.whl) 

Step 1: Get torch and domain libraries RC1
pip3 install --no-cache-dir  torch torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu117 

Step 2: Uninstall a broken pytorch-triton package
pip3 uninstall pytorch-triton 

Step 3:  (Download and install the new wheel package, remember to use --no-deps, otherwise it will install pytorch 1.13.1)  
pip install pytorch_triton-2.0.0+d54c04abe2-cp310-cp310-linux_x86_64.whl   --no-deps

After we do RC2, Step 1 would be enough.

**Comment by weiwangmeta** [comment]
As of now, "pip install torch torchvision torchAudio --index-url https://download.pytorch.org/whl/nightly/cu117" should resolve this issue.

**Comment by weiwangmeta** [comment]
Closing this issue. Please re-open if the above suggestion does not work.
