### ISSUE TITLE
`Tensor.copy_` + `moveaxis` Trigger Exception in Compile Mode

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#95262]
### 🐛 Describe the bug

The following program works fine in eager mode but triggers an exception in compile mode:
```python
import torch

def fn(x, y):
    _ = y.copy_(x)
    return torch.moveaxis(y, source=0, destination=1)

x = torch.rand([2, 3], dtype=torch.float16)
y = torch.rand([2, 3], dtype=torch.float32) # works fine if x&y has the same type

ret_eager = fn(x, y)
print('==== Eager mode OK! ====')

compiled = torch.compile(fn)
print('==== torchcomp compilation OK! ====')

ret_compiled = compiled(x, y)
print('==== torchcomp mode OK! ====')

"""
==== Eager mode OK! ====
==== torchcomp compilation OK! ====
Traceback (most recent call last):
  File "repro.py", line 15, in <module>
    ret_compiled = compiled(x, y)
  File "python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "repro.py", line 3, in fn
    def fn(x, y):
  File "python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2812, in forward
    return compiled_fn(full_args)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1222, in g
    return f(*args)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1895, in runtime_wrapper
    all_outs = call_func_with_args(
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1247, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/tmp/torchinductor/75/c75w2gc5qdvwzlouzm2j2qf2kow35v3nlkpbq2tiunw6kht3swv7.py", line 47, in call
    return (as_strided(buf0, (2, 2), (1, 2)), )
NameError: name 'buf0' is not defined
"""
```
It's worth noting that the error occurs only when the two input tensors have different `dtype`. Also, the two operators are both necessary for triggering this issue.

### Versions

<details><summary><b>Environment</b> <i>[Click to expand]</i></summary>

```
PyTorch version: 2.0.0.dev20230220+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 525.78.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] pytorch-triton==2.0.0+c8bfe3f548
[pip3] torch==2.0.0.dev20230220+cu117
[pip3] torchaudio==2.0.0.dev20230222+cu117
[pip3] torchvision==0.15.0.dev20230221+cu117
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0
```

</details>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel @yanboliang @Xia-Weiwen @desertfire

**Comment by bdhirsh** [comment]
I printed the FX graph sent to inductor, and I see an extra view op after the `copy_()`, which probably makes inductor unhappy:
```
def forward(self, arg0_1, arg1_1):
    convert_element_type = torch.ops.prims.convert_element_type.default(arg0_1, torch.float32);  arg0_1 = None
    permute = torch.ops.aten.permute.default(convert_element_type, [1, 0])
    copy_ = torch.ops.aten.copy_.default(arg1_1, convert_element_type);  arg1_1 = None
    permute_1 = torch.ops.aten.permute.default(convert_element_type, [1, 0]);  convert_element_type = None
    return (permute_1,)
```

This seems like something we can fix in aot autograd (guarantee that the input mutation `copy_()` nodes show up at the end of the graph).

**Comment by williamwen42** [comment]
Repro no longer fails - closing as fixed.
