### ISSUE TITLE
AttributeError: Method AffineChannelNd is not a registered operator. Did you mean: [AffineChannel]

### ISSUE THREAD

**Issue by naren142** [pytorch/pytorch#9527]
Traceback (most recent call last):
File "tools/test_net.py", line 151, in
main(ind_range=args.range, multi_gpu_testing=False)
File "tools/test_net.py", line 113, in main
engine.test_net_on_dataset(multi_gpu=multi_gpu_testing)
File "/home/chandu/workspace/tracking/DaT/lib/core/test_engine.py", line 321, in test_net_on_dataset
all_boxes, all_segms, all_keyps = test_net()
File "/home/chandu/workspace/tracking/DaT/lib/core/test_engine.py", line 135, in test_net
model = initialize_model_from_cfg()
File "/home/chandu/workspace/tracking/DaT/lib/core/test_engine.py", line 59, in initialize_model_from_cfg
init_params=cfg.TEST.INIT_RANDOM_VARS_BEFORE_LOADING)
File "/home/chandu/workspace/tracking/DaT/lib/modeling/model_builder.py", line 63, in create
return get_func(model_name)(init_model(model_name, train, init_params))
File "/home/chandu/workspace/tracking/DaT/lib/modeling/model_builder.py", line 156, in keypoint_rcnn
add_roi_keypoint_head_func=get_func(cfg.KRCNN.ROI_KEYPOINTS_HEAD))
File "/home/chandu/workspace/tracking/DaT/lib/modeling/model_builder.py", line 307, in build_generic_fast_rcnn_model
build_data_parallel_model(model, _single_gpu_build_func)
File "/home/chandu/workspace/tracking/DaT/lib/modeling/model_builder.py", line 953, in build_data_parallel_model
single_gpu_build_func(model)
File "/home/chandu/workspace/tracking/DaT/lib/modeling/model_builder.py", line 199, in _single_gpu_build_func
blob_conv, dim_conv, spatial_scale_conv = add_conv_body_func(model)
File "/home/chandu/workspace/tracking/DaT/lib/modeling/FPN3D.py", line 51, in add_fpn_ResNet101_conv5_body
ResNet.stage_info_ResNet101_conv5)
File "/home/chandu/workspace/tracking/DaT/lib/modeling/FPN3D.py", line 98, in add_fpn_generic_onto_body
conv_body_func(model)
File "/home/chandu/workspace/tracking/DaT/lib/modeling/ResNet3D.py", line 389, in add_ResNet101_conv5_body
return add_ResNet_convX_body(model, (3, 4, 23, 3), freeze_at=2)
File "/home/chandu/workspace/tracking/DaT/lib/modeling/ResNet3D.py", line 262, in add_ResNet_convX_body
p = model.AffineChannelNd(p, 'res_conv1_bn', dim_out=feat_dims[0], inplace=True)
File "/home/chandu/workspace/tracking/DaT/lib/modeling/detector.py", line 94, in AffineChannelNd
if cfg.MODEL.USE_BN:
File "/home/chandu/workspace/tracking/anaconda2/envs/gtracking/lib/python2.7/site-packages/caffe2/python/core.py", line 2082, in getattr
",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method AffineChannelNd is not a registered operator. Did you mean: [AffineChannel]

**Why am I getting this error?**

**Comment by zou3519** [comment]
Could you please fill out the issue template so that we have more information to work with? In particular, a code sample would be helpful.

**Comment by naren142** [comment]
I have resolved this issue by following the instructions in the installation process.

**Comment by my-hello-world** [comment]
> I have resolved this issue by following the instructions in the installation process.

can you help me？same errors
