### ISSUE TITLE
Caffe2 - How to save a trained model as proto file and as C++?

### ISSUE THREAD

**Issue by CarlosYeverino** [pytorch/pytorch#9533]
Hi all,

can you please share the way I can save a trained Caffe2 model network as proto file. Is it also possible to save it directly as C++ files?

**Comment by CarlosYeverino** [comment]
Hello @BIGBALLON ,

thanks for the code, man!

do you know also how I can save a trained network in python? I am trying the following saving way, however, when I load the saved files I got an error.

```
from caffe2.python import workspace, model_helper, core
from caffe2.proto import caffe2_pb2
import numpy as np
# Create random tensor of three dimensions
x = np.random.rand(4, 3, 2)
print(x)
print(x.shape)

workspace.FeedBlob("my_x", x)

x2 = workspace.FetchBlob("my_x")
print(x2)

# Create the input data
data = np.random.rand(16, 100).astype(np.float32)

# Create labels for the data as integers [0, 9].
label = (np.random.rand(16) * 10).astype(np.int32)

workspace.FeedBlob("data", data)
workspace.FeedBlob("label", label)

# Create model using a model helper
m = model_helper.ModelHelper(name="my first net")

weight = m.param_init_net.XavierFill([], 'fc_w', shape=[10, 100])
bias = m.param_init_net.ConstantFill([], 'fc_b', shape=[10, ])

fc_1 = m.net.FC(["data", "fc_w", "fc_b"], "fc1")
pred = m.net.Sigmoid(fc_1, "pred")
softmax, loss = m.net.SoftmaxWithLoss([pred, "label"], ["softmax", "loss"])

print(m.net.Proto())

print(m.param_init_net.Proto())

m.AddGradientOperators([loss])

print(m.net.Proto())

workspace.RunNetOnce(m.param_init_net)

workspace.CreateNet(m.net)

# Run 100 x 10 iterations
for _ in range(100):
    data = np.random.rand(16, 100).astype(np.float32)
    label = (np.random.rand(16) * 10).astype(np.int32)

    workspace.FeedBlob("data", data)
    workspace.FeedBlob("label", label)

    workspace.RunNet(m.name, 10)   # run for 10 times

print(workspace.FetchBlob("softmax"))
print(workspace.FetchBlob("loss"))



print '\nsaving trained model'

INIT_NET = 'D:/Yeverino/Python_scripts/intro_tutorial/init_net.pb' 
PREDICT_NET = 'D:/Yeverino/Python_scripts/intro_tutorial/predict_net.pb'


def save_net(INIT_NET, PREDICT_NET, model) :

    with open(PREDICT_NET, 'wb') as f:
        f.write(model.net._net.SerializeToString())
    init_net = caffe2_pb2.NetDef()
    for param in model.params:
        blob = workspace.FetchBlob(param)
        shape = blob.shape
        op = core.CreateOperator("GivenTensorFill", [], [param],arg=[ utils.MakeArgument("shape", shape),utils.MakeArgument("values", blob)])
        init_net.op.extend([op])
    init_net.op.extend([core.CreateOperator("ConstantFill", [], ["data"], shape=(1,30,30))])
    with open(INIT_NET, 'wb') as f:
        f.write(init_net.SerializeToString())

def load_net(INIT_NET, PREDICT_NET, device_opts):

    init_def = caffe2_pb2.NetDef()
    with open(INIT_NET, 'r') as f:
        init_def.ParseFromString(f.read())
        init_def.device_option.CopyFrom(device_opts)
        #workspace.RunNetOnce(init_def.SerializeToString())

    net_def = caffe2_pb2.NetDef()
    with open(PREDICT_NET, 'r') as f:
        net_def.ParseFromString(f.read())
        net_def.device_option.CopyFrom(device_opts)
        #workspace.CreateNet(net_def.SerializeToString(), overwrite=True)

save_net(INIT_NET, PREDICT_NET, m)

device_opts = core.DeviceOption(caffe2_pb2.CPU, 0) # change to 'core.DeviceOption(caffe2_pb2.CUDA, 0)' for GPU processing

print 'loading trained model'
load_net(INIT_NET, PREDICT_NET, device_opts=device_opts)

```
I got the following error:
Traceback (most recent call last):
  File "D:\Yeverino\Python_scripts\intro_tutorial\intro_tutorial.py", line 99, in <module>
    load_net(INIT_NET, PREDICT_NET, device_opts=device_opts)
  File "D:\Yeverino\Python_scripts\intro_tutorial\intro_tutorial.py", line 84, in load_net
    init_def.ParseFromString(f.read())
  File "C:\Python27\lib\site-packages\google\protobuf\message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "C:\Python27\lib\site-packages\google\protobuf\internal\python_message.py", line 1083, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Python27\lib\site-packages\google\protobuf\internal\python_message.py", line 1120, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Python27\lib\site-packages\google\protobuf\internal\decoder.py", line 610, in DecodeRepeatedField
    raise _DecodeError('Truncated message.')
DecodeError: Truncated message.
>>>

**Comment by BIGBALLON** [comment]
@CarlosYeverino 

- save net without BN layer:

```python
def SaveNet(INIT_NET, PREDICT_NET, workspace, model):
    init_net, predict_net = mobile_exporter.Export(
        workspace, model.net, model.params
    )
    
    with open(PREDICT_NET, 'wb') as f:
        f.write(model.net._net.SerializeToString())
    with open(INIT_NET, 'wb') as f:
        f.write(init_net.SerializeToString())
    print("== saved init_net and predict_net. ==")

def LoadNet(INIT_NET, PREDICT_NET, device_opts):
    init_def = caffe2_pb2.NetDef()
    with open(INIT_NET, 'rb') as f:
        init_def.ParseFromString(f.read())
        init_def.device_option.CopyFrom(device_opts)
        workspace.RunNetOnce(init_def.SerializeToString())
    
    net_def = caffe2_pb2.NetDef()
    with open(PREDICT_NET, 'rb') as f:
        net_def.ParseFromString(f.read())
        net_def.device_option.CopyFrom(device_opts)
        workspace.CreateNet(net_def.SerializeToString(), overwrite=True)
    print("== loaded init_net and predict_net. ==")
```

- save net **with BN layer** :

```
def save_net(init_net_pb, predict_net_pb, model):
    extra_params = []
    extra_blobs = []
    for blob in workspace.Blobs():
        name = str(blob)
        if name.endswith("_rm") or name.endswith("_riv"):
            extra_params.append(name)
            extra_blobs.append(workspace.FetchBlob(name))
    for name, blob in zip(extra_params, extra_blobs):
        model.params.append(name)

    init_net, predict_net = mobile_exporter.Export(
        workspace,
        model.net,
        model.params
    )

    with open(predict_net_pb, 'wb') as f:
        f.write(model.net._net.SerializeToString())
    with open(init_net_pb, 'wb') as f:
        f.write(init_net.SerializeToString())


def load_net(init_net_pb, predict_net_pb, device_opts):
    init_def = caffe2_pb2.NetDef()
    with open(init_net_pb, 'rb') as f:
        init_def.ParseFromString(f.read())
        init_def.device_option.CopyFrom(device_opts)
        workspace.RunNetOnce(init_def.SerializeToString())

    net_def = caffe2_pb2.NetDef()
    with open(predict_net_pb, 'rb') as f:
        net_def.ParseFromString(f.read())
        net_def.device_option.CopyFrom(device_opts)
        workspace.CreateNet(net_def.SerializeToString(), overwrite=True)
```

**Comment by CarlosYeverino** [comment]
Hi @BIGBALLON ,

thanks for all the info, man.
