### ISSUE TITLE
Disabled test still running on trunk CI and failing the job

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#95341]
In the Job below (attempt #1) two tests failed and caused the job to be marked as failed. However, both those tests were disabled more than a week ago and HUD even showed that the job was failing on the disabled tests ([test1](https://github.com/pytorch/pytorch/issues/91479), [test2](https://github.com/pytorch/pytorch/issues/91478))

**Ask:** Understand why these tests were run even when they were disabled, and ensure disabled tests don't cause CI failures again

![Image](https://user-images.githubusercontent.com/4468967/220795714-1d1be652-d88c-459d-8c2d-b0faf1d0b835.png)

[Link to failing github run](https://github.com/pytorch/pytorch/actions/runs/4247689968/jobs/7386207755) (check attempt #1)

[HUD link](https://hud.pytorch.org/pytorch/pytorch/commit/f6f413c6b6912e33884a7510cc04a3488416a8a4)

Logs from failing tests
```
2023-02-22T23:14:29.9181359Z ======================================================================
2023-02-22T23:14:29.9181542Z ERROR [0.017s]: test_partial_eval_stitching (jit.test_symbolic_shape_analysis.TestSymbolicShapeAnalysis)
2023-02-22T23:14:29.9181745Z ----------------------------------------------------------------------
2023-02-22T23:14:29.9181841Z Traceback (most recent call last):
2023-02-22T23:14:29.9182033Z   File "/var/lib/jenkins/workspace/test/jit/test_symbolic_shape_analysis.py", line 440, in test_partial_eval_stitching
2023-02-22T23:14:29.9182203Z     self.checkSymShapeCompute(shape_compute_graph, nodes, output_shapes, ([1, 3, 224, 224],))
2023-02-22T23:14:29.9182391Z   File "/var/lib/jenkins/workspace/test/jit/test_symbolic_shape_analysis.py", line 405, in checkSymShapeCompute
2023-02-22T23:14:29.9182510Z     g = shape_compute_graph.partial_eval_shape_graph()
2023-02-22T23:14:29.9182724Z AttributeError: 'NoneType' object has no attribute 'partial_eval_shape_graph'
2023-02-22T23:14:29.9183123Z ##[endgroup]
2023-02-22T23:14:29.9183133Z 
2023-02-22T23:14:29.9183234Z ======================================================================
2023-02-22T23:14:29.9183451Z ERROR [0.008s]: test_refinement_through_graph_stitching (jit.test_symbolic_shape_analysis.TestSymbolicShapeAnalysis)
2023-02-22T23:14:29.9183654Z ----------------------------------------------------------------------
2023-02-22T23:14:29.9183747Z Traceback (most recent call last):
2023-02-22T23:14:29.9183950Z   File "/var/lib/jenkins/workspace/test/jit/test_symbolic_shape_analysis.py", line 461, in test_refinement_through_graph_stitching
2023-02-22T23:14:29.9184045Z     self.assertTrue(out1[2] != out2[2])
2023-02-22T23:14:29.9184194Z TypeError: 'NoneType' object is not subscriptable
2023-02-22T23:14:29.9184212Z 
2023-02-22T23:14:29.9184395Z ----------------------------------------------------------------------
2023-02-22T23:14:29.9184471Z Ran 2678 tests in 79.793s
2023-02-22T23:14:29.9184476Z 
2023-02-22T23:14:29.9184590Z FAILED (errors=2, skipped=135, expected failures=17)
```
Further down are the lines:
```
2023-02-22T23:14:29.9213151Z Traceback (most recent call last):
2023-02-22T23:14:29.9213258Z   File "test/run_test.py", line 1394, in <module>
2023-02-22T23:14:29.9213325Z     main()
2023-02-22T23:14:29.9213425Z   File "test/run_test.py", line 1369, in main
2023-02-22T23:14:29.9213518Z     raise RuntimeError(err_message)
2023-02-22T23:14:29.9213613Z RuntimeError: test_jit_legacy failed!
```

**Comment by ZainRizvi** [comment]
cc: @clee2000

**Comment by clee2000** [comment]
TestSymbolicShapeAnalysis in test_symbolic_shape_analysis.py has a setUp function that doesn't call super().setUp(), which is what checks for disabled test issues.  I tried adding super().setUp(), but some tests fail.

The fastest solution would be to submit a PR to skip the test in the code
