### ISSUE TITLE
Issues with torch.compile on A100 when finetuning DistilBERT

### ISSUE THREAD

**Issue by rasbt** [pytorch/pytorch#95407]
### 🐛 Describe the bug

LLVM ERROR when using `torch.compile`, following up on a discussion with @msaroufim (https://twitter.com/marksaroufim/status/1628833167481376768?s=20)

```
/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py:90: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
[2023-02-23 15:04:36,012] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 630, in _worker_compile
    kernel.precompile(warm_cache_only_with_cc=cc)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 69, in precompile
    self.launchers = [
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 70, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 83, in _precompile_config
    triton.compile(
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/compiler.py", line 1619, in compile
    next_module = compile(module)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/compiler.py", line 1554, in <lambda>
    lambda src: llir_to_ptx(src, capability)),
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/compiler.py", line 1018, in llir_to_ptx
    _, cuda_version = path_to_ptxas()
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/compiler.py", line 1077, in path_to_ptxas
    raise RuntimeError("Cannot find ptxas")
RuntimeError: Cannot find ptxas
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 700, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/__init__.py", line 1390, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 455, in compile_fx
    return aot_autograd(
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2798, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2491, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1713, in aot_wrapper_dedupe
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2130, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 430, in fw_compiler
    return inner_compile(
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 177, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/graph.py", line 586, in compile_to_fn
    return self.compile_to_module().call
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/graph.py", line 575, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 609, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_sebastian/un/cunb6vctjebsyge5j5na2f6fxvdcm5qpohbbouyvivvn3dbytuws.py", line 1232, in <module>
    async_compile.wait(globals())
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 796, in wait
    scope[key] = result.result()
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 654, in result
    self.future.result()
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
RuntimeError: Cannot find ptxas

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sebastian/Developer/faster-blog-code/1_pytorch-distilbert.py", line 162, in <module>
    train(
  File "/home/sebastian/Developer/faster-blog-code/1_pytorch-distilbert.py", line 35, in train
    outputs = model(
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1738, in run
    super().run()
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 588, in run
    and self.step()
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 552, in step
    getattr(self, inst.opname)(inst)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 372, in wrapper
    self.output.compile_subgraph(self, reason=reason)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 571, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 618, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 705, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised RuntimeError: Cannot find ptxas

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
LLVM ERROR: Can't find libdevice at neither /home/sebastian/miniforge3/envs/faster-blog2/lib/python3.9/site-packages/triton/third_party/cuda/lib/libdevice.10.bc nor /tmp/tmpqoukkez6/triton/python/triton/third_party/cuda/lib/libdevice.10.bc
```

Attached the code files to reproduce this:

[python-scripts.zip](https://github.com/pytorch/pytorch/files/10817996/python-scripts.zip)

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0.dev20230220+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)  [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-254
Off-line CPU(s) list:            255
Thread(s) per core:              1
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7742 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1499.829
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4499.91
Virtualization:                  AMD-V
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-63,128-191
NUMA node1 CPU(s):               64-127,192-254
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; LFENCE, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] pytorch-triton==2.0.0+c8bfe3f548
[pip3] torch==2.0.0.dev20230220+cu117
[pip3] torchaudio==2.0.0.dev20230223+cu117
[pip3] torchmetrics==0.11.1
[pip3] torchvision==0.15.0.dev20230223+cu117
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+c8bfe3f548          pypi_0    pypi
[conda] torch                     2.0.0.dev20230220+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230223+cu117          pypi_0    pypi
[conda] torchmetrics              0.11.1                   pypi_0    pypi
[conda] torchvision               0.15.0.dev20230223+cu117          pypi_0    pypi
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by msaroufim** [comment]
Does doing this solve things? `TRITON_PTXAS_PATH=/usr/bin/ptxas python your_script.py` @atalma, @agunapal @weiwangmeta  as FYI

Seems like this is a known issue and is being tracked here https://github.com/pytorch/builder/issues/1318

**Comment by weiwangmeta** [comment]
This looks like the same issue as comments in https://github.com/pytorch/pytorch/issues/95223 and https://github.com/pytorch/builder/issues/1318 

In the meanwhile, we just fixed nightly branch push. Expecting new nightly binary and this issue would be fixed. 

Alternative, try our 2.0.0-RC2, 

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu117

**Comment by weiwangmeta** [comment]
In short, [pip3] pytorch-triton==2.0.0+c8bfe3f548 is broken. 

Latest is pytorch-triton           2.0.0+d54c04abe2. You can get it through the above RC2 installation command. Or via the download links here: 

https://download.pytorch.org/whl/test/pytorch-triton/index.html

**Comment by rasbt** [comment]
Thanks for the pointer, let me try this with the new nightly release then tomorrow and report back!

**Comment by rasbt** [comment]
The new nightly fixed it! Thanks @msaroufim @weiwangmeta !
