### ISSUE TITLE
TorchInductor fails with memoy violations in `test_comprehensive_grid_sampler_2d_cuda_float16` and `test_reflection_pad2d_dynamic_shapes_cuda`

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#95595]
### 🐛 Describe the bug

The latest nightly build fails with illegal memory accesses when the caching allocator is disabled as reported by `compute-sanitizer` on an A100:
```
PYTORCH_NO_CUDA_MEMORY_CACHING=1 compute-sanitizer python test_torchinductor_opinfo.py -v -k test_comprehensive_grid_sampler_2d_cuda_float16
========= COMPUTE-SANITIZER
test_comprehensive_grid_sampler_2d_cuda_float16 (__main__.TestInductorOpInfoCUDA) ... ========= Invalid __global__ read of size 2 bytes
=========     at 0x17b0 in triton__0d1d2d3d4d5d6d7
=========     by thread (23,0,0) in block (0,0,0)
=========     Address 0x7f403ba00512 is out of bounds
=========     and is 99 bytes after the nearest allocation at 0x7f403ba00000 of size 1200 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x30b492]
=========                in /usr/local/cuda/compat/lib.real/libcuda.so.1
=========     Host Frame:_launch [0x14e9]
=========                in /tmp/torchinductor_root/triton/0/1a11982c9e681e0725af1fbdec50f2bc/triton_.so
=========     Host Frame: [0x1d61]
=========                in /tmp/torchinductor_root/triton/0/1a11982c9e681e0725af1fbdec50f2bc/triton_.so
=========     Host Frame:PyCFunction_Call [0x1f5bda]
=========                in /usr/bin/python


root@nvdl-a52-luna02:/workspace/src/libs/pytorch/test/inductor# PYTORCH_NO_CUDA_MEMORY_CACHING=1 compute-sanitizer python test_torchinductor_dynamic_shapes.py -v -k test_reflection_pad2d_dynamic_shapes_cuda
========= COMPUTE-SANITIZER
test_reflection_pad2d_dynamic_shapes_cuda (__main__.DynamicShapesCudaTests) ... ========= Invalid __global__ read of size 4 bytes
=========     at 0xb50 in triton__0d1d2
=========     by thread (17,0,0) in block (0,0,0)
=========     Address 0x7f86cb1fffe4 is out of bounds
=========     and is 28 bytes before the nearest allocation at 0x7f86cb200000 of size 256 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x30b492]
=========                in /usr/local/cuda/compat/lib.real/libcuda.so.1
=========     Host Frame:_launch [0x148d]
=========                in /tmp/torchinductor_root/triton/0/b9ee7217453ddfeba9422db9c01a70ef/triton_.so
=========     Host Frame: [0x17d2]
=========                in /tmp/torchinductor_root/triton/0/b9ee7217453ddfeba9422db9c01a70ef/triton_.so
=========     Host Frame:PyCFunction_Call [0x1f5bda]
=========                in /usr/bin/python
```

Another IMA is raised in `test_torchinductor.py` but I'm currently unable to isolate the failing test case and will update the issue later once I have a small repro.

CC @ngimel @malfet 

### Versions

```
PyTorch version: 2.0.0.dev20230226+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-80-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 525.85.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.8.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

[removed CPU information as not interesting]

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-triton==2.0.0+b8b470bc59
[pip3] torch==2.0.0.dev20230226+cu118
[pip3] torch-tensorrt==1.4.0.dev0
[pip3] torchtext==0.13.0a0+fae8e8c
[pip3] torchvision==0.15.0.dev20230226+cu118
[conda] Could not collect

```

cc @ezyang @gchanan @zou3519 @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @soumith

**Comment by ptrblck** [comment]
> Another IMA is raised in test_torchinductor.py but I'm currently unable to isolate the failing test case and will update the issue later once I have a small repro.

Unfortunately, I'm still unable to isolate the issue, but as a heads-up:
the IMA is raised when the entire test is executed via:
```
PYTORCH_NO_CUDA_MEMORY_CACHING=1 compute-sanitizer python test_torchinductor.py
```
The output of this test file is quite verbose and prints a lot of code. However, failure seems to point to:
```
[2023-02-27 22:19:27,665] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 2671
.[2023-02-27 22:19:29,365] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 2672

from ctypes import c_void_p, c_long
import torch
import math
import random
from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()

import triton
import triton.language as tl
from torch._inductor.triton_ops.autotune import grid, start_graph, end_graph
from torch._C import _cuda_getCurrentRawStream as get_cuda_stream


triton__0 = async_compile.triton('''
import triton
import triton.language as tl
from torch._inductor.ir import ReductionHint
from torch._inductor.ir import TileHint
from torch._inductor.triton_ops.autotune import pointwise
from torch._inductor.utils import instance_descriptor

@pointwise(size_hints=[64], filename=__file__, meta={'signature': {0: '*fp16', 1: '*fp16', 2: 'i32'}, 'device': 0, 'constants': {}, 'mutated_arg_names': [], 'configs': [instance_descriptor(divisible_by_16=(0, 1, 2), equal_to_1=())]})
@triton.jit
def triton_(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 64
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x1 = (xindex // 8)
    x0 = xindex % 8
    x2 = xindex
    tmp0 = 3 + x1
    tmp1 = 1 + x0
    tmp2 = tl.load(in_ptr0 + (tmp1 + (11*tmp0)), None).to(tl.float32)
    tmp3 = x0
    tmp4 = tmp3 >= 1
    tmp5 = tmp3 <= 1
    tmp6 = tmp4 & tmp5
    tmp7 = 3 + x1 + tl.zeros([XBLOCK], tl.int32)
    tmp8 = 1 + ((-1)*x0) + tl.zeros([XBLOCK], tl.int32)
    tmp9 = tl.load(in_ptr0 + (tmp8 + (11*tmp7)), tmp6, other=0).to(tl.float32)
    tmp10 = tl.where(tmp6, tmp9, 0.0)
    tmp11 = tmp2 + tmp10
    tmp12 = tmp3 >= 5
    tmp13 = tmp3 <= 6
    tmp14 = tmp12 & tmp13
    tmp15 = 3 + x1 + tl.zeros([XBLOCK], tl.int32)
    tmp16 = 15 + ((-1)*x0) + tl.zeros([XBLOCK], tl.int32)
    tmp17 = tl.load(in_ptr0 + (tmp16 + (11*tmp15)), tmp14, other=0).to(tl.float32)
    tmp18 = tl.where(tmp14, tmp17, 0.0)
    tmp19 = tmp11 + tmp18
    tmp20 = x1
    tmp21 = tmp20 >= 1
    tmp22 = tmp20 <= 3
    tmp23 = tmp21 & tmp22
    tmp24 = 3 + ((-1)*x1) + tl.zeros([XBLOCK], tl.int32)
    tmp25 = 1 + x0 + tl.zeros([XBLOCK], tl.int32)
    tmp26 = tl.load(in_ptr0 + (tmp25 + (11*tmp24)), tmp23, other=0).to(tl.float32)
    tmp27 = tl.where(tmp23, tmp26, 0.0)
    tmp28 = tmp19 + tmp27
    tmp29 = tmp20 >= 3
    tmp30 = tmp20 <= 6
    tmp31 = tmp29 & tmp30
    tmp32 = 17 + ((-1)*x1) + tl.zeros([XBLOCK], tl.int32)
    tmp33 = 1 + x0 + tl.zeros([XBLOCK], tl.int32)
    tmp34 = tl.load(in_ptr0 + (tmp33 + (11*tmp32)), tmp31, other=0).to(tl.float32)
    tmp35 = tl.where(tmp31, tmp34, 0.0)
    tmp36 = tmp28 + tmp35
    tmp37 = tmp23 & tmp6
    tmp38 = 3 + ((-1)*x1) + tl.zeros([XBLOCK], tl.int32)
    tmp39 = 1 + ((-1)*x0) + tl.zeros([XBLOCK], tl.int32)
    tmp40 = tl.load(in_ptr0 + (tmp39 + (11*tmp38)), tmp37, other=0).to(tl.float32)
    tmp41 = tl.where(tmp37, tmp40, 0.0)
    tmp42 = tmp36 + tmp41
    tmp43 = tmp23 & tmp14
    tmp44 = 3 + ((-1)*x1) + tl.zeros([XBLOCK], tl.int32)
    tmp45 = 15 + ((-1)*x0) + tl.zeros([XBLOCK], tl.int32)
    tmp46 = tl.load(in_ptr0 + (tmp45 + (11*tmp44)), tmp43, other=0).to(tl.float32)
    tmp47 = tl.where(tmp43, tmp46, 0.0)
    tmp48 = tmp42 + tmp47
    tmp49 = tmp31 & tmp6
    tmp50 = 17 + ((-1)*x1) + tl.zeros([XBLOCK], tl.int32)
    tmp51 = 1 + ((-1)*x0) + tl.zeros([XBLOCK], tl.int32)
    tmp52 = tl.load(in_ptr0 + (tmp51 + (11*tmp50)), tmp49, other=0).to(tl.float32)
    tmp53 = tl.where(tmp49, tmp52, 0.0)
    tmp54 = tmp48 + tmp53
    tmp55 = tmp31 & tmp14
    tmp56 = 17 + ((-1)*x1) + tl.zeros([XBLOCK], tl.int32)
    tmp57 = 15 + ((-1)*x0) + tl.zeros([XBLOCK], tl.int32)
    tmp58 = tl.load(in_ptr0 + (tmp57 + (11*tmp56)), tmp55, other=0).to(tl.float32)
    tmp59 = tl.where(tmp55, tmp58, 0.0)
    tmp60 = tmp54 + tmp59
    tl.store(out_ptr0 + (x2 + tl.zeros([XBLOCK], tl.int32)), tmp60, xmask)
''')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1 = args
    args.clear()
    with torch.cuda._DeviceGuard(0):
        torch.cuda.set_device(0) # no-op to ensure context
        buf0 = empty_strided((1, 1, 8, 8), (64, 64, 8, 1), device='cuda', dtype=torch.float16)
        stream0 = get_cuda_stream(0)
        triton__0.run(arg0_1, buf0, 64, grid=grid(64), stream=stream0)
        del arg0_1
        return (buf0, )


if __name__ == "__main__":
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((1, 1, 15, 11), (165, 165, 11, 1), device='cuda:0', dtype=torch.float16)
    arg1_1 = rand_strided((1, 1, 8, 8), (64, 64, 8, 1), device='cuda:0', dtype=torch.float16)
    print_performance(lambda: call([arg0_1, arg1_1]))

[2023-02-27 22:19:29,414] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 2672
========= Invalid __global__ read of size 4 bytes
=========     at 0xb50 in triton__0d1d2
=========     by thread (17,0,0) in block (0,0,0)
=========     Address 0x7f89f13e55e4 is out of bounds
=========     and is 28 bytes before the nearest allocation at 0x7f89f13e5600 of size 256 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x30b492]
=========                in /usr/local/cuda/compat/lib.real/libcuda.so.1
=========     Host Frame:_launch [0x148d]
=========                in /tmp/torchinductor_root/triton/0/b9ee7217453ddfeba9422db9c01a70ef/triton_.so
=========     Host Frame: [0x17d2]
=========                in /tmp/torchinductor_root/triton/0/b9ee7217453ddfeba9422db9c01a70ef/triton_.so
=========     Host Frame:PyCFunction_Call [0x1f5bda]
=========                in /usr/bin/python
```
Running the previously printed code does not reproduce the IMA even after a lot of reruns.
I now think I'm mistaken and the actual failure would be the *next* test (which is not shown). Is this the case?
If so, do you know how the actual test names could be displayed?

**Comment by ptrblck** [comment]
New IMA in `test_triton_bsr_dense_bmm_block_size_16_int32_cuda_bfloat16` on H100 using the current nightly pip wheel `2.1.0.dev20230405+cu118`:
```python
python test_sparse_csr.py -v -k test_triton_bsr_dense_bmm_block_size_16_int32_cuda_bfloat16
test_triton_bsr_dense_bmm_block_size_16_int32_cuda_bfloat16 (__main__.TestSparseCSRCUDA) ... test_sparse_csr.py:1498: UserWarning: Sparse BSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at ../aten/src/ATen/SparseCsrTensorImpl.cpp:53.)
  bsr = bsr.to_sparse_bsr(block_size)
TEST SUITE EARLY TERMINATION due to torch.cuda.synchronize() failure
ERROR
TEST SUITE EARLY TERMINATION due to torch.cuda.synchronize() failure

======================================================================
ERROR: test_triton_bsr_dense_bmm_block_size_16_int32_cuda_bfloat16 (__main__.TestSparseCSRCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/testing/_internal/common_utils.py", line 2144, in wrapper
    method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    raise rte
  File "/usr/local/lib/python3.8/dist-packages/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
    result = test(self, **param_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/testing/_internal/common_device_type.py", line 1005, in only_fn
    return fn(slf, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/testing/_internal/common_utils.py", line 1123, in wrapper
    fn(*args, **kwargs)
  File "test_sparse_csr.py", line 1501, in test_triton_bsr_dense_bmm
    res_dense = bsr.to_dense() @ dense.transpose(-2, -1)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
`compute-sanitizer` points to:
```python
========= COMPUTE-SANITIZER
test_triton_bsr_dense_bmm_block_size_16_int32_cuda_bfloat16 (__main__.TestSparseCSRCUDA) ... ========= Invalid __shared__ read of size 16 bytes
=========     at 0xc80 in _bsr_strided_dense_rowspace_kernel_0d1d2d3d4d5d6c7d89c10d11d12c13d14d15d16d17c18d19d20d21d22d
=========     by thread (112,0,0) in block (0,1,0)
=========     Address 0x800 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x30b492]
=========                in /usr/local/cuda/compat/lib.real/libcuda.so.1
=========     Host Frame: [0x1c07]
=========                in /root/.triton/cache/09334ad7fbfce99a7dc4461a01fb036c/_bsr_strided_dense_rowspace_kernel.so
```

**Comment by ngimel** [comment]
This is not an inductor failure, that is the failure from triton bsr kernel, cc @nikitaved

**Comment by ptrblck** [comment]
Oh, you are right, sorry. Let me know if I should create a new issue as I don't want to pollute this one with unrelated issues.

**Comment by albanD** [comment]
We should try to have periodic runs with compute sanitizers.
Part of the issues mentioned here have been fixed, @ptrblck will rerun the remaining ones to see what still fails.

**Comment by voznesenskym** [comment]
@ptrblck is this still an issue?
