### ISSUE TITLE
AssertionError: expected FunctionType found method <bound method ...

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#95630]
### 🐛 Describe the bug

```
pip uninstall torch lightning -y
pip install lightning==1.9.2
# first nightly where it started failing
pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu --no-deps
```

It can be reproduced with: 

```python
import torch

from lightning.pytorch import Trainer
from lightning.pytorch.demos.boring_classes import BoringModel

import torch._dynamo as dynamo
dynamo.config.verbose = True

model = BoringModel()
compiled_model = torch.compile(model)
trainer = Trainer(fast_dev_run=True)
trainer.fit(compiled_model)
```

```python
python script.py
```

The LightningModule implementation is: https://github.com/Lightning-AI/lightning/blob/e3efbaa7f6e3eef9096173cdcb603a92acf3fb4b/src/lightning/pytorch/demos/boring_classes.py#L78-L132

### Error logs

```python
Traceback (most recent call last):
  File "/home/carmocca/git/lightning/kk3.py", line 13, in <module>
    trainer.fit(compiled_model)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/trainer/trainer.py", line 517, in fit
    call._call_and_handle_interrupt(
  File "/home/carmocca/git/lightning/src/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/trainer/trainer.py", line 556, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/trainer/trainer.py", line 928, in _run
    results = self._run_stage()
  File "/home/carmocca/git/lightning/src/lightning/pytorch/trainer/trainer.py", line 967, in _run_stage
    self._run_train()
  File "/home/carmocca/git/lightning/src/lightning/pytorch/trainer/trainer.py", line 988, in _run_train
    self.fit_loop.run()
  File "/home/carmocca/git/lightning/src/lightning/pytorch/loops/fit_loop.py", line 192, in run
    self.advance()
  File "/home/carmocca/git/lightning/src/lightning/pytorch/loops/fit_loop.py", line 365, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/loops/training_epoch_loop.py", line 218, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/loops/optimization/automatic.py", line 185, in run
    self._optimizer_step(kwargs.get("batch_idx", 0), closure)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/loops/optimization/automatic.py", line 261, in _optimizer_step
    call._call_lightning_module_hook(
  File "/home/carmocca/git/lightning/src/lightning/pytorch/trainer/call.py", line 142, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/core/module.py", line 1233, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/core/optimizer.py", line 158, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/strategies/strategy.py", line 224, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/plugins/precision/precision_plugin.py", line 114, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/optim/optimizer.py", line 32, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/optim/sgd.py", line 67, in step
    loss = closure()
  File "/home/carmocca/git/lightning/src/lightning/pytorch/plugins/precision/precision_plugin.py", line 101, in _wrap_closure
    closure_result = closure()
  File "/home/carmocca/git/lightning/src/lightning/pytorch/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
  File "/home/carmocca/git/lightning/src/lightning/pytorch/loops/optimization/automatic.py", line 308, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/carmocca/git/lightning/src/lightning/pytorch/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/carmocca/git/lightning/src/lightning/pytorch/strategies/strategy.py", line 366, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 215, in _fn
    return fn(*args, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 343, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1862, in run
    super().run()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 619, in run
    and self.step()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 583, in step
    getattr(self, inst.opname)(inst)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 349, in wrapper
    return inner_fn(self, inst)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1014, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 517, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 292, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 260, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 93, in call_function
    return tx.inline_user_function_return(
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 553, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1955, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2011, in inline_call_
    tracer.run()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 619, in run
    and self.step()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 583, in step
    getattr(self, inst.opname)(inst)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 349, in wrapper
    return inner_fn(self, inst)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1014, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 517, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 263, in call_function
    return tx.inline_user_function_return(
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 553, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1955, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2011, in inline_call_
    tracer.run()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 619, in run
    and self.step()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 583, in step
    getattr(self, inst.opname)(inst)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1087, in LOAD_ATTR
    result = BuiltinVariable(getattr).call_function(
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 564, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 939, in call_getattr
    return obj.var_getattr(tx, name).add_options(options)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 159, in var_getattr
    return VariableBuilder(tx, NNModuleSource(source))(subobj)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 172, in __call__
    return self._wrap(value).clone(**self.options())
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 435, in _wrap
    return UserFunctionVariable(
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/base.py", line 28, in __call__
    obj.__post_init__(*args, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/base.py", line 281, in __post_init__
    VariableTracker.apply(
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/base.py", line 99, in apply
    result = fn(value.clone(**updated_dict))
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/base.py", line 65, in clone
    return self.__class__(**args)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/base.py", line 27, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 115, in __init__
    assert isinstance(
AssertionError: expected FunctionType found method <bound method BoringModel.forward of BoringModel(
  (layer): Linear(in_features=32, out_features=2, bias=True)
)>

from user code:
   File "/home/carmocca/git/lightning/src/lightning/pytorch/demos/boring_classes.py", line 105, in step
    output = self(batch)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1495, in _call_impl
    forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.forward)


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```

TorchDynamo seems to create an `UserFunctionVariable` with a function (correct!) but then the function reference becomes a method, and the assertion triggers.

### Minified repro

The environment variable did not make a difference in the error shown

### Versions

All nightly versions after 2023-01-27 fail to run (`torch==2.0.0.dev20230128`).
Current master and the 2.0 release candidate also fail.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by carmocca** [comment]
I debugged further: we have this piece of code for `torch.compile()` support: https://github.com/Lightning-AI/lightning/blob/a54f37391f364fb75654b69519bd7e906b3e5f1d/src/lightning/pytorch/utilities/compile.py

If we don't override `training_step` with it's compiled function (https://github.com/Lightning-AI/lightning/blob/a54f37391f364fb75654b69519bd7e906b3e5f1d/src/lightning/pytorch/utilities/compile.py#L58) then this error doesn't pop up.

I believe it's because when the `training_step` method is compiled, internally it uses the `BoringModel.forward` method instead of the compiled function that was patched one line above.

**Comment by carmocca** [comment]
I was able to pull out Lightning:

```python
import torch


class MyModel(torch.nn.Module):
    def forward(self):
        ...

    def training_step(self):
        self()


model = MyModel()
compiled_model = torch.compile(model)

model.forward = compiled_model.dynamo_ctx(model.forward)
model.training_step = compiled_model.dynamo_ctx(model.training_step)

model.training_step()
```

**Comment by carmocca** [comment]
https://github.com/pytorch/pytorch/blob/f43ce9553bbf35c1b71c362cd5441eddcdb7ecbf/torch/_dynamo/variables/functions.py#L119 is where things go wrong, as it returns a method instead of a function. In fact, if I do

```
model.forward = compiled_model.dynamo_ctx(model.forward)
model.forward._torchdynamo_inline = model.forward
model.training_step = compiled_model.dynamo_ctx(model.training_step)
```

Things work. I'll stop debugging here before going further into a fix as I'd like to know first if the patching we use is meant to be supported (meaning this is a bug), or if we should use a different approach to support `torch.compile` with Lightning

cc @lantiga

**Comment by ngimel** [comment]
cc @wconstab, @voznesenskym

**Comment by voznesenskym** [comment]
This is a bug in `VariableTracker.apply`, the `value.__dict__` is misaligned with internal repr. 

value.__dict__:
```
{'guards': {Guard(name='self.forward', source=<GuardSource.LOCAL_NN_MODULE: 2>, create_fn=<function GuardBuilder.FUNCTION_MATCH at 0x7f934b5c0f70>, is_volatile=False, guard_types=None, code_list=None, obj_weakref=None, guarded_class_weakref=None)}, 'source': NNModuleSource(inner=AttrSource(base=LocalInputSource(local_name='self', pos=0), member='forward')), 'mutable_local': None, 'recursively_contains': set(), 'is_constant': False, 'fn': <bound method MyModel.forward of MyModel()>}
```

We actually want fn to be a function here, or to change the UserFunctionVariable in this init to be permissive of taking the __func__ from the method, or relaxing the assert.

In fact, removing that assert makes your sample script pass ;)

**Comment by voznesenskym** [comment]
https://github.com/pytorch/pytorch/pull/95667

**Comment by lantiga** [comment]
Since we saw that the window to get new commits in PyTorch 2.0 is closing, @voznesenskym @wconstab do you see any  glaring issue if we go with @carmocca's fix for now https://github.com/pytorch/pytorch/issues/95630#issuecomment-1447023590 and we'll re-evaluate?

We'd like to understand the implications of re-assigning _torchdynamo_inline to the optimized function (or maybe there are better ways to temporarily address this).

We are in the process of releasing Lightning 2.0 ourselves and we would like to feature the fact it fully supports PyTorch 2.0 cc @msaroufim

**Comment by voznesenskym** [comment]
> Since we saw that the window to get new commits in PyTorch 2.0 is closing, @voznesenskym @wconstab do you see any glaring issue if we go with @carmocca's fix for now [#95630 (comment)](https://github.com/pytorch/pytorch/issues/95630#issuecomment-1447023590) and we'll re-evaluate?
> 
> We'd like to understand the implications of re-assigning _torchdynamo_inline to the optimized function (or maybe there are better ways to temporarily address this).
> 
> We are in the process of releasing Lightning 2.0 ourselves and we would like to feature the fact it fully supports PyTorch 2.0 cc @msaroufim

At first blush, It looks reasonable to me. I do not know if it has any implication on hooks, or on model state. 

More on the root cause tho:

```
class HasPostInit(type):
    def __call__(cls, *args, **kwargs):
        obj = type.__call__(cls, *args, **kwargs)
        obj.__post_init__(*args, **kwargs)
        return obj
```
Invokes __call__ on type, which is a `UserFunctionVariable`. 

The *args here is `(<function MyModel.forward at 0x7ffaa2bf1ea0>,)`
But after, if you print obj.fn, you get 

`<bound method MyModel.forward of MyModel()>`

Why?

Because of `fn = inspect.getattr_static(fn, "_torchdynamo_inline", fn)` - this unpacks a method out of the field! Then, when we apply, we copy the __dict__ and recreate the object, and boom!

So, the solution, naively, might be to just... not do that so late? Perhaps we can just let the builder take out the  value from `_torchdynamo_inline`? It does make the reference case above pass... open to discussion here: https://github.com/pytorch/pytorch/pull/95771

**Comment by wconstab** [comment]
is this fixed now that #95771 landed?

**Comment by carmocca** [comment]
I'll check once the patch is available in a nightly

**Comment by carmocca** [comment]
Fixed. Thanks!
