### ISSUE TITLE
AssertionError: ModuleDict with torch.compile

### ISSUE THREAD

**Issue by ezhang887** [pytorch/pytorch#95735]
### 🐛 Describe the bug

I get a `AssertionError: ModuleDict` when using `torch.compile`. But it works fine if I remove the `torch.compile()` line. Repro below.

### Error logs

```
2.0.0a0+git7ebb309
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    out = net(torch.Tensor([1, 2, 3, 4]))
  File "/my-conda-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 959, in GET_ITER
    self.call_function(BuiltinVariable(iter), [self.pop()], {})
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/variables/builtin.py", line 566, in call_function
    result = handler(tx, *args, **kwargs)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/variables/builtin.py", line 739, in _call_iter_tuple_list
    elif obj.has_unpack_var_sequence(tx):
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/variables/base.py", line 216, in has_unpack_var_sequence
    self.unpack_var_sequence(tx)
  File "/my-conda-env/lib/python3.8/site-packages/torch/_dynamo/variables/nn_module.py", line 48, in unpack_var_sequence
    assert isinstance(
AssertionError: ModuleDict

from user code:
   File "test.py", line 13, in forward
    for k in self.submodules:

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Minified repro

```
user@host:$ cat test.py
import torch
import torch.nn as nn

print(torch.__version__)

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.submodules = nn.ModuleDict({"key": nn.Identity()})

    def forward(self, x):
        rv = {}
        for k in self.submodules:
            rv[k] = self.submodules[k](x)
        return rv

net = Net()
net = net.cuda()
net = torch.compile(net)
out = net(torch.Tensor([1, 2, 3, 4]))
print(out)
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0a0+git7ebb309
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 12.0.1 (https://github.com/conda-forge/clangdev-feedstock d44358f44aef33e9fa7c5f93e2481ee8f1a04ab6)
CMake version: version 3.19.1
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-64-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM-80GB
Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by voznesenskym** [comment]
TY for triage, I can get to it in a few days

**Comment by joglekara** [comment]
Any suggested workarounds in the meantime? Just store all modules explicitly instead? Do ModuleLists work?

**Comment by ptr-br** [comment]
I'm facing the same issue.

**Comment by voznesenskym** [comment]
https://github.com/pytorch/pytorch/pull/99503
