### ISSUE TITLE
test_grad_assignment intermittently fails with SIGSEGV

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#9586]
```
10:29:14 test_grad_assignment (__main__.TestAutograd) ... Traceback (most recent call last):
10:29:14   File "test/run_test.py", line 345, in <module>
10:29:14     main()
10:29:14   File "test/run_test.py", line 337, in main
10:29:14     raise RuntimeError(message)
10:29:14 RuntimeError: test_autograd failed! Received signal: SIGSEGV
```

Unfortunately, the error message is not very helpful.

I've seen it twice. Here's one log:
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda8-cudnn6-py3-NO_AVX-NO_AVX2-test2/3736//console

**Comment by ngimel** [comment]
Closing due to age.
