### ISSUE TITLE
Errors using torch.compile() on open-clip ViT-L-14 model

### ISSUE THREAD

**Issue by nkflash** [pytorch/pytorch#95939]
### 🐛 Describe the bug

Enable torch2 on open-clip with torch.compile
![image](https://user-images.githubusercontent.com/42488903/222622270-3b124dce-7d39-47b5-b3f2-425104229075.png)

    if is_master(args):
        logging.info("Model:")
        logging.info(f"{str(model)}")
        logging.info("Params:")
        params_file = os.path.join(args.logs, args.name, "params.txt")
        with open(params_file, "w") as f:
            for name in sorted(vars(args)):
                val = getattr(args, name)
                logging.info(f"  {name}: {val}")
                f.write(f"{name}: {val}\n")

    model = torch.compile(model)
    if args.distributed and not args.horovod:
        if args.use_bn_sync:
            model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
        ddp_args = {}
        if args.ddp_static_graph:
            # this doesn't exist in older PyTorch, arg only added if enabled
            ddp_args['static_graph'] = True
        model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[device], **ddp_args)

        if args.distill:

I got such error:

```
[2023-03-03 11:16:07,077] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 0
[2023-03-03 11:16:07,396] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 0
[2023-03-03 11:16:07,950] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 1
[2023-03-03 11:16:10,016] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 1
[2023-03-03 11:16:10,598] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 2
[2023-03-03 11:16:11,482] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 2
[2023-03-03 11:16:12,078] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 3
[2023-03-03 11:16:12,857] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 3
[2023-03-03 11:16:13,416] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 4
[2023-03-03 11:16:14,115] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 4
[2023-03-03 11:16:14,692] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 5
[2023-03-03 11:16:15,670] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 5
[2023-03-03 11:16:16,282] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 6
[2023-03-03 11:16:17,014] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 6
[2023-03-03 11:16:17,557] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 7
[2023-03-03 11:16:18,248] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 7
[2023-03-03 11:16:18,809] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 8
[2023-03-03 11:16:19,514] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 8
[2023-03-03 11:16:20,283] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 9
[2023-03-03 11:16:21,040] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 9
[2023-03-03 11:16:21,647] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 10
[2023-03-03 11:16:22,368] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 10
[2023-03-03 11:16:22,959] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 11
[2023-03-03 11:16:23,697] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 11
[2023-03-03 11:16:24,478] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 12
[2023-03-03 11:16:24,694] torch._inductor.graph: [INFO] Using FallbackKernel: aten.index
[2023-03-03 11:16:28,768] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 12
[2023-03-03 11:16:28,901] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 13
[2023-03-03 11:16:29,024] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 13
[2023-03-03 11:16:29,236] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 14
[2023-03-03 11:16:29,475] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 14
[2023-03-03 11:16:29,858] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 15
Traceback (most recent call last):
  File "/home/elrond/code/open_clip_orig/open_clip/src/training/main.py", line 471, in <module>
    main(sys.argv[1:])
  File "/home/elrond/code/open_clip_orig/open_clip/src/training/main.py", line 399, in main
    train_one_epoch(model, data, loss, epoch, optimizer, scaler, scheduler, dist_model, args, tb_writer=writer)
  File "/home/elrond/code/open_clip_orig/open_clip/src/training/train.py", line 100, in train_one_epoch
    model_out = model(images, texts)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1129, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1083, in _run_ddp_forward
    return self.module(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 94, in __call__
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 235, in _fn
    return fn(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 369, in catch_errors
    return hijacked_callback(frame, cache_size, hooks)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1862, in run
    super().run()
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 619, in run
    and self.step()
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 583, in step
    getattr(self, inst.opname)(inst)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1941, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 579, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 626, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 712, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 708, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/backends/distributed.py", line 348, in compile_fn
    submod_compiler.run(*example_inputs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/fx/interpreter.py", line 137, in run
    self.env[node] = self.run_node(node)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/backends/distributed.py", line 329, in run_node
    compiled_submod_real = self.compile_submod(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/backends/distributed.py", line 272, in compile_submod
    self.compiler(input_mod, args),
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/__init__.py", line 1393, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 488, in compile_fx
    return aot_autograd(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2818, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2511, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1715, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2135, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 462, in fw_compiler
    return inner_compile(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 179, in compile_fx_inner
    graph.run(*example_inputs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/graph.py", line 212, in run
    return super().run(*args)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/fx/interpreter.py", line 137, in run
    self.env[node] = self.run_node(node)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/graph.py", line 438, in run_node
    result = super().run_node(n)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/fx/interpreter.py", line 179, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/graph.py", line 343, in call_function
    error.operator_str(target, args, kwargs),
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/exc.py", line 22, in operator_str
    lines = [f"target: {target}"] + [
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/exc.py", line 23, in <listcomp>
    f"args[{i}]: {arg}" for i, arg in enumerate(args)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/ir.py", line 3888, in __str__
    indent(str(inner)),
  File "/opt/anaconda3/lib/python3.9/dataclasses.py", line 370, in wrapper
    result = user_function(self)
  File "<string>", line 3, in __repr__
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/_inductor/ir.py", line 365, in __str__
    self.inner_fn_str(max_lines=config.debug_max_lines),
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
TypeError: wrapper() got an unexpected keyword argument 'max_lines'

While executing %submod_1 : [#users=2] = call_module[target=submod_1](args = (%getitem_38, %getitem_39, %self_visual_transformer_resblocks_0_ln_2_weight, %self_visual_transformer_resblocks_0_ln_2_bias), kwargs = {})
Original traceback:
None


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2840) of binary: /opt/anaconda3/bin/python
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
training/main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-03_11:16:32
  host      : job-17608551-6987-430a-8cf4-0fac393788c8-master-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2840)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git5bdd054
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-113-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 470.129.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-255
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7742 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         3152.410
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4491.51
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-15,128-143
NUMA node1 CPU(s):               16-31,144-159
NUMA node2 CPU(s):               32-47,160-175
NUMA node3 CPU(s):               48-63,176-191
NUMA node4 CPU(s):               64-79,192-207
NUMA node5 CPU(s):               80-95,208-223
NUMA node6 CPU(s):               96-111,224-239
NUMA node7 CPU(s):               112-127,240-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.4.0
[pip3] open-clip-torch==2.15.0
[pip3] torch==2.1.0a0+git5bdd054
[pip3] torchaudio==2.0.0a0+15ca386
[pip3] torchdata==0.7.0a0+1a3a4a0
[pip3] torchtext==0.15.0a0+2c02373
[pip3] torchvision==0.15.0a0+3bb3f10
[conda] blas                      1.0                         mkl    https://repo.anaconda.com/pkgs/main
[conda] magma-cuda118             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-include               2023.0.0         h06a4308_25399    defaults
[conda] mkl-service               2.4.0            py39h7f8727e_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_fft                   1.3.1            py39hd3c417c_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_random                1.2.2            py39h51133e4_0    https://repo.anaconda.com/pkgs/main
[conda] numpy                     1.21.5           py39h6c91a56_3    defaults
[conda] numpy-base                1.21.5           py39ha15fc14_3    https://repo.anaconda.com/pkgs/main
[conda] numpydoc                  1.4.0            py39h06a4308_0    https://repo.anaconda.com/pkgs/main
[conda] open-clip-torch           2.15.0                    dev_0    <develop>
[conda] torch                     2.1.0a0+git5bdd054          pypi_0    pypi
[conda] torchaudio                2.0.0a0+15ca386          pypi_0    pypi
[conda] torchdata                 0.7.0a0+1a3a4a0          pypi_0    pypi
[conda] torchtext                 0.15.0a0+2c02373          pypi_0    pypi
[conda] torchvision               0.15.0a0+3bb3f10          pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by nkflash** [comment]
cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire @mthrok

**Comment by jansel** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/96014
