### ISSUE TITLE
Shape error calculating gradients for linalg.solve

### ISSUE THREAD

**Issue by JackBuck** [pytorch/pytorch#95974]
### 🐛 Describe the bug

When using `torch.linalg.solve` with a 1x1 matrix and a 1-element vector, I get an error. The error does not happen for, say, a 2x2 matrix and 2-element vector.

For example:
```python
import torch

a = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
c = torch.linalg.solve(a, b)
torch.autograd.grad(c.sum(), a)
# ^^ This line blows up
```
Stack trace:
```
Traceback (most recent call last):
  File ".../linalgsolve_mwe.py", line 6, in <module>
    torch.autograd.grad(c.sum(), a)
  File ".../lib/python3.10/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function LinalgSolveExBackward0 returned an invalid gradient at index 0 - got [1] but expected shape compatible with [1, 1]
```

### Versions

```
PyTorch version: 1.13.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.14.0-1058-oem-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: Quadro P620
Nvidia driver version: 470.161.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           165
Model name:                      Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
Stepping:                        2
CPU MHz:                         2700.000
CPU max MHz:                     5100.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5399.81
Virtualisation:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        1.5 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-11
[Vulnerabilities redacted]

Versions of relevant libraries:
[pip3] botorch==0.8.1
[pip3] gpytorch==1.9.1
[pip3] numpy==1.24.2
[pip3] torch==1.13.1+cpu
[conda] botorch                   0.8.1                    pypi_0    pypi
[conda] gpytorch                  1.9.1                    pypi_0    pypi
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     1.13.1+cpu               pypi_0    pypi
```

**Comment by ZailiWang** [comment]
Hi I tried the case with a nightly build and the error was not re-produced. Would you update with nightly build and help confirm it? Thanks.

**Comment by ngimel** [comment]
Works on nightly, please reopen if still doesn't work for you

**Comment by JackBuck** [comment]
Thanks, yes this seems to be fixed on the nightly build. Thanks for looking into it.
