### ISSUE TITLE
Linking libtorch with QT5 OpenGL application using llvmpipe mesa opengl crashes

### ISSUE THREAD

**Issue by wvalcke** [pytorch/pytorch#96060]
### 🐛 Describe the bug

Using a very simple OpenGL Qt5 application running inside a Thinlinc session works when the binary is NOT linked to libtorch libraries.
As soon you link libtorch libraries (NOT even using ANY torchlib method in the application itself, just linking)  makes the application crashing. 
This is both the case with CPU & GPU (cuda) version of libtorch (1.13.1)
The funny fact is that the application not even has an #include of any torchlib header. Just linking with torchlib is enough to have the issue. (using official supported cmake procedure)
When OpenGL is NOT used, eveything works. A similar issue (#75336) has been reported as well, probably the root cause is the same.
If the application is run on a native machine and using a real Nvidia card and libraries, everything works. There must be a conflict caused by libtorch to crash applications using software OpenGL. 

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Linux Mint 21.1 (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 515.43.04
cuDNN version: Probably one of the following:
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
CPU family:                      6
Model:                           63
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        2
CPU max MHz:                     3200,0000
CPU min MHz:                     1200,0000
BogoMIPS:                        4789.26
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear flush_l1d
Virtualization:                  VT-x
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        1,5 MiB (6 instances)
L3 cache:                        15 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] No relevant packages
[conda] Could not collect

**Comment by wvalcke** [comment]
Some more info when running with address sanitizer:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==437919==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fce721fa124 bp 0x6030009bd310 sp 0x7ffd225dcfb0 T0)
==437919==The signal is caused by a READ memory access.
==437919==Hint: address points to the zero page.
    #0 0x7fce721fa124  (/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so+0x675124)
    #1 0x7fce721f6b4d  (/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so+0x671b4d)
    #2 0x7fce7226b665  (/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so+0x6e6665)
    #3 0x7fce7225c9a7  (/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so+0x6d79a7)
    #4 0x7fce7224115f  (/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so+0x6bc15f)
    #5 0x7fce71dfb034  (/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so+0x276034)
    #6 0x562a5984ca08 in QOpenGLFunctions::glDrawArrays(unsigned int, int, int) /usr/include/x86_64-linux-gnu/qt5/QtGui/qopenglfunctions.h:749
    #7 0x562a5984ba98 in TriangleWindow::render() /mnt/DV/wim/BEP/Software/Projects/OpenGLTest/src/TriangleWindow.cpp:67
    #8 0x562a5984d79d in OpenGLWindow::renderNow() /mnt/DV/wim/BEP/Software/Projects/OpenGLTest/src/OpenGLWindow.cpp:78
    #9 0x562a5984d473 in OpenGLWindow::exposeEvent(QExposeEvent*) /mnt/DV/wim/BEP/Software/Projects/OpenGLTest/src/OpenGLWindow.cpp:53
    #10 0x7fce979c55a4 in QWindow::event(QEvent*) (/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x14d5a4)
    #11 0x562a5984d440 in OpenGLWindow::event(QEvent*) /mnt/DV/wim/BEP/Software/Projects/OpenGLTest/src/OpenGLWindow.cpp:44
    #12 0x7fce975d0e39 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2b9e39)
    #13 0x7fce979ba6a0 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) (/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x1426a0)
    #14 0x7fce9798ea2b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x116a2b)
    #15 0x7fce76845d6d  (/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5+0x73d6d)
    #16 0x7fce7cfa2d3a in g_main_context_dispatch (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x55d3a)
    #17 0x7fce7cff76c7  (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0xaa6c7)
    #18 0x7fce7cfa03e2 in g_main_context_iteration (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x533e2)
    #19 0x7fce9762a0b7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x3130b7)
    #20 0x7fce975cf75a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2b875a)
    #21 0x7fce975d7cf3 in QCoreApplication::exec() (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2c0cf3)
    #22 0x562a5984ab21 in main /mnt/DV/wim/BEP/Software/Projects/OpenGLTest/src/TriangleMain.cpp:17
    #23 0x7fce7dc39d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #24 0x7fce7dc39e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #25 0x562a5984a8c4 in _start (/mnt/DV/wim/BEP/Software/Projects/OpenGLTest/build/install/bin/TriangleWindow+0x198c4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so+0x675124) 
==437919==ABORTING
```
