### ISSUE TITLE
Torch Dynamo Error when Compiling `fasterrcnn_mobilenet_v3_large_320_fpn`

### ISSUE THREAD

**Issue by gs-olive** [pytorch/pytorch#96151]
### 🐛 Describe the bug

Encountered `torch._dynamo.exc.InternalTorchDynamoError` when compiling Torchvision model `torchvision.models.detection.fasterrcnn_mobilenet_v3_large_320_fpn`, via `torch.compile` using the "eager" and "inductor" backends. This compilation was functional in the Feb 19 PyTorch 2.0 nightly, but is not working on the Mar 1 nightly.

### Error logs

```python
Traceback (most recent call last):
  File "~/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "~/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "~/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "~/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1862, in run
    super().run()
  File "~/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 619, in run
    and self.step()
  File "~/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 583, in step
    getattr(self, inst.opname)(inst)
  File "~/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 379, in wrapper
    self.output.compile_subgraph(self, reason=reason)
  File "~/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 562, in compile_subgraph
    pass1.foreach(stack_values)
  File "~/lib/python3.8/site-packages/torch/_dynamo/codegen.py", line 166, in foreach
    self(i)
  File "~/lib/python3.8/site-packages/torch/_dynamo/codegen.py", line 148, in __call__
    output.extend(value.reconstruct(self))
  File "~/lib/python3.8/site-packages/torch/_dynamo/variables/dicts.py", line 40, in reconstruct
    codegen.create_load_python_module(collections),
TypeError: create_load_python_module() missing 1 required positional argument: 'push_null'

from user code:
   File "~/lib/python3.8/site-packages/torchvision/models/detection/backbone_utils.py", line 58, in forward
    x = self.fpn(x)

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 94, in __call__
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
  File "~/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 228, in _fn
    return fn(*args, **kwargs)
  File "~/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/lib/python3.8/site-packages/torchvision/models/detection/generalized_rcnn.py", line 83, in forward
    images, targets = self.transform(images, targets)
  File "~/lib/python3.8/site-packages/torchvision/models/detection/generalized_rcnn.py", line 101, in <graph break in forward>
    features = self.backbone(images.tensors)
  File "~/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 356, in catch_errors
    return callback(frame, cache_size, hooks)
  File "~/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "~/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "~/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "~/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "~/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 394, in _compile
    raise InternalTorchDynamoError() from e
torch._dynamo.exc.InternalTorchDynamoError
```

### Minified repro

Original Failing Code:
```python
import torch
import torchvision

model = torchvision.models.detection.fasterrcnn_mobilenet_v3_large_320_fpn().eval().cuda()

input1 = torch.rand((3, 300, 400)).cuda()
input2 = torch.rand((3, 500, 400)).cuda()

compiled = torch.compile(backend="eager")(model)

out = compiled([input1, input2])
```

### Versions

```python
Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==2.0.0.dev20230301+cu117
[pip3] torchdata==0.7.0.dev20230301
[pip3] torchinfo==1.7.2
[pip3] torchmetrics==0.11.3
[pip3] torchtext==0.15.0.dev20230301+cpu
[pip3] torchvision==0.15.0.dev20230301+cu117
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by gs-olive** [comment]
Thank you for the update - the error is no longer occurring for me with the newest nightly, `2.1.0.dev20230308+cu117`.
