### ISSUE TITLE
dynamo + dict subclass + tensor instance check: NotImplementedError

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#96198]
### 🐛 Describe the bug

Torchdynamo fails to understand the `self.__dict__` type when it's `isinstance` checked with `torch.Tensor`

Note that `dict(self.__dict__)` does work as a workaround

### Error logs

```python
Traceback (most recent call last):
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1862, in run
    super().run()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 619, in run
    and self.step()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 583, in step
    getattr(self, inst.opname)(inst)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 349, in wrapper
    return inner_fn(self, inst)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1014, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 517, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 561, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 799, in call_isinstance
    arg_type = arg.python_type()
  File "/home/carmocca/git/py310/lib/python3.10/site-packages/torch/_dynamo/variables/base.py", line 146, in python_type
    raise NotImplementedError(f"{self} has no type")
NotImplementedError: GetAttrVariable(UserDefinedObjectVariable(MyDict), __dict__) has no type

from user code:
   File "/home/carmocca/git/lightning/kk4.py", line 7, in foo
    print(isinstance(self.__dict__, torch.Tensor))
```

### Minified repro

```python
import torch

class MyDict(dict):
    def foo(self):
        print(isinstance(self.__dict__, torch.Tensor))

def x():
    d = MyDict()
    d.foo()

c_x = torch.compile(x)
c_x()
```

### Versions

`torch==2.1.0.dev20230302+cpu`

cc @ezyang @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @zou3519 @aakhundov @soumith @ngimel

**Comment by anijain2305** [comment]
I think this reprod for me on main. Reopening for now, will double check
