### ISSUE TITLE
Mnist model training with "reduce-overhead" mode is flaky

### ISSUE THREAD

**Issue by agunapal** [pytorch/pytorch#96391]
### 🐛 Describe the bug

I was trying out an end-to-end training/test example with torch.compile

https://github.com/agunapal/examples/blob/pt2.0_example/pt2.0/mnist/main.py#L140:L146

When I don't specify a mode, the code runs correctly.

When I specify the mode "reduce-overhead", I see that its flaky. It runs correctly some times, errors most times

### Error logs

[success.txt](https://github.com/pytorch/pytorch/files/10927346/success.txt)
[failure.txt](https://github.com/pytorch/pytorch/files/10927348/failure.txt)

### Minified repro

```
import os
from math import inf
import torch
from torch import tensor, device
import torch.fx as fx
import functools
import torch._dynamo
from torch._dynamo.debug_utils import run_fwd_maybe_bwd
from torch._dynamo.backends.registry import lookup_backend
from torch._dynamo.testing import rand_strided

import torch._dynamo.config
import torch._inductor.config
import torch._functorch.config
torch._dynamo.config.load_config(b'\x80\x02}q\x00(X\x0b\x00\x00\x00output_codeq\x01\x89X\r\x00\x00\x00log_file_nameq\x02NX\x07\x00\x00\x00verboseq\x03\x89X\x11\x00\x00\x00output_graph_codeq\x04\x89X\x12\x00\x00\x00verify_correctnessq\x05\x89X\x12\x00\x00\x00minimum_call_countq\x06K\x01X\x15\x00\x00\x00dead_code_eliminationq\x07\x88X\x10\x00\x00\x00cache_size_limitq\x08K@X\x14\x00\x00\x00specialize_int_floatq\t\x88X\x0e\x00\x00\x00dynamic_shapesq\n\x89X\x10\x00\x00\x00guard_nn_modulesq\x0b\x89X\x1b\x00\x00\x00traceable_tensor_subclassesq\x0cc__builtin__\nset\nq\r]q\x0e\x85q\x0fRq\x10X\x0f\x00\x00\x00suppress_errorsq\x11\x89X\x15\x00\x00\x00replay_record_enabledq\x12\x89X \x00\x00\x00rewrite_assert_with_torch_assertq\x13\x88X\x12\x00\x00\x00print_graph_breaksq\x14\x89X\x07\x00\x00\x00disableq\x15\x89X*\x00\x00\x00allowed_functions_module_string_ignorelistq\x16h\r]q\x17(X\x13\x00\x00\x00torch.distributionsq\x18X\x0b\x00\x00\x00torch._refsq\x19X\r\x00\x00\x00torch.testingq\x1aX\r\x00\x00\x00torch._decompq\x1bX\x0c\x00\x00\x00torch._primsq\x1ce\x85q\x1dRq\x1eX\x12\x00\x00\x00repro_forward_onlyq\x1f\x89X\x0f\x00\x00\x00repro_toleranceq G?PbM\xd2\xf1\xa9\xfcX\x16\x00\x00\x00capture_scalar_outputsq!\x89X\x19\x00\x00\x00enforce_cond_guards_matchq"\x88X\x0c\x00\x00\x00optimize_ddpq#\x88X\x1a\x00\x00\x00raise_on_ctx_manager_usageq$\x88X\x1c\x00\x00\x00raise_on_unsafe_aot_autogradq%\x89X\x17\x00\x00\x00raise_on_backend_changeq&\x89X\x18\x00\x00\x00error_on_nested_fx_traceq\'\x88X\t\x00\x00\x00allow_rnnq(\x89X\x08\x00\x00\x00base_dirq)XG\x00\x00\x00/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packagesq*X\x0e\x00\x00\x00debug_dir_rootq+X:\x00\x00\x00/home/ubuntu/fork/examples/pt2.0/mnist/torch_compile_debugq,X)\x00\x00\x00DO_NOT_USE_legacy_non_fake_example_inputsq-\x89X\x13\x00\x00\x00_save_config_ignoreq.h\r]q/(X!\x00\x00\x00skipfiles_inline_module_allowlistq0X\x12\x00\x00\x00constant_functionsq1X\x0b\x00\x00\x00repro_afterq2X\x0b\x00\x00\x00repro_levelq3e\x85q4Rq5u.')
torch._inductor.config.load_config(b'\x80\x02}q\x00(X\x05\x00\x00\x00debugq\x01\x89X\x10\x00\x00\x00disable_progressq\x02\x88X\x10\x00\x00\x00verbose_progressq\x03\x89X\x0b\x00\x00\x00cpp_wrapperq\x04\x89X\x03\x00\x00\x00dceq\x05\x89X\x14\x00\x00\x00static_weight_shapesq\x06\x88X\x0c\x00\x00\x00size_assertsq\x07\x88X\x10\x00\x00\x00pick_loop_ordersq\x08\x88X\x0f\x00\x00\x00inplace_buffersq\t\x88X\x11\x00\x00\x00benchmark_harnessq\n\x88X\x0f\x00\x00\x00epilogue_fusionq\x0b\x89X\x15\x00\x00\x00epilogue_fusion_firstq\x0c\x89X\x0f\x00\x00\x00pattern_matcherq\r\x88X\n\x00\x00\x00reorderingq\x0e\x89X\x0c\x00\x00\x00max_autotuneq\x0f\x89X\x17\x00\x00\x00realize_reads_thresholdq\x10K\x04X\x17\x00\x00\x00realize_bytes_thresholdq\x11M\xd0\x07X\x1b\x00\x00\x00realize_acc_reads_thresholdq\x12K\x08X\x0f\x00\x00\x00fallback_randomq\x13\x89X\x12\x00\x00\x00implicit_fallbacksq\x14\x88X\x0b\x00\x00\x00tune_layoutq\x15\x89X\x11\x00\x00\x00aggressive_fusionq\x16\x89X\x0f\x00\x00\x00max_fusion_sizeq\x17K@X\x1b\x00\x00\x00unroll_reductions_thresholdq\x18K\x08X\x0e\x00\x00\x00comment_originq\x19\x89X\x12\x00\x00\x00developer_warningsq\x1a\x88X\x0f\x00\x00\x00compile_threadsq\x1bK\x08X\x13\x00\x00\x00kernel_name_max_opsq\x1cK\nX\r\x00\x00\x00shape_paddingq\x1d\x89X\x0e\x00\x00\x00permute_fusionq\x1e\x89X\x1a\x00\x00\x00profiler_mark_wrapper_callq\x1f\x89X\x18\x00\x00\x00_raise_error_for_testingq \x89X\x0b\x00\x00\x00cpp.threadsq!J\xff\xff\xff\xffX\x13\x00\x00\x00cpp.dynamic_threadsq"\x89X\x0b\x00\x00\x00cpp.simdlenq#NX\x12\x00\x00\x00cpp.min_chunk_sizeq$M\x00\x10X\x07\x00\x00\x00cpp.cxxq%NX\x03\x00\x00\x00g++q&\x86q\'X\x19\x00\x00\x00cpp.enable_kernel_profileq(\x89X\x12\x00\x00\x00cpp.weight_prepackq)\x88X\x11\x00\x00\x00triton.cudagraphsq*\x89X\x17\x00\x00\x00triton.debug_sync_graphq+\x89X\x18\x00\x00\x00triton.debug_sync_kernelq,\x89X\x15\x00\x00\x00triton.dense_indexingq-\x89X\x10\x00\x00\x00triton.max_tilesq.K\x02X\x19\x00\x00\x00triton.autotune_pointwiseq/\x88X\'\x00\x00\x00triton.tiling_prevents_pointwise_fusionq0\x88X\'\x00\x00\x00triton.tiling_prevents_reduction_fusionq1\x88X\x1b\x00\x00\x00triton.ordered_kernel_namesq2\x89X\x1f\x00\x00\x00triton.descriptive_kernel_namesq3\x89X\x1c\x00\x00\x00triton.persistent_reductionsq4\x89X\r\x00\x00\x00trace.enabledq5\x89X\x0f\x00\x00\x00trace.debug_logq6\x88X\x0e\x00\x00\x00trace.info_logq7\x89X\x0e\x00\x00\x00trace.fx_graphq8\x88X\x1a\x00\x00\x00trace.fx_graph_transformedq9\x88X\x13\x00\x00\x00trace.ir_pre_fusionq:\x88X\x14\x00\x00\x00trace.ir_post_fusionq;\x88X\x11\x00\x00\x00trace.output_codeq<\x88X\x13\x00\x00\x00trace.graph_diagramq=\x89X\x15\x00\x00\x00trace.compile_profileq>\x89X\x10\x00\x00\x00trace.upload_tarq?Nu.')
torch._functorch.config.load_config(b'\x80\x02}q\x00(X\x11\x00\x00\x00use_functionalizeq\x01\x88X\x0f\x00\x00\x00use_fake_tensorq\x02\x88X\x16\x00\x00\x00fake_tensor_allow_metaq\x03\x88X\x0c\x00\x00\x00debug_assertq\x04\x88X\x14\x00\x00\x00debug_fake_cross_refq\x05\x89X\x11\x00\x00\x00debug_partitionerq\x06\x89X\x0c\x00\x00\x00debug_graphsq\x07\x89X\x0b\x00\x00\x00debug_jointq\x08\x89X\x12\x00\x00\x00use_dynamic_shapesq\t\x89X\x14\x00\x00\x00static_weight_shapesq\n\x88X\x03\x00\x00\x00cseq\x0b\x88X\x10\x00\x00\x00max_dist_from_bwq\x0cK\x03X\t\x00\x00\x00log_levelq\rK\x14u.')


# REPLACEABLE COMMENT FOR TESTING PURPOSES


args = [((64, 1, 28, 28), (784, 784, 28, 1), torch.float32, 'cuda', False)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]


from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.self_conv1 = Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1)).cuda()
        self.self_conv2 = Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1)).cuda()
        self.self_dropout1 = Dropout(p=0.25, inplace=False)
        self.self_fc1 = Linear(in_features=9216, out_features=128, bias=True).cuda()
        self.self_dropout2 = Dropout(p=0.5, inplace=False)
        self.self_fc2 = Linear(in_features=128, out_features=10, bias=True).cuda()



    def forward(self, x : torch.Tensor):
        self_conv1 = self.self_conv1(x);  x = None
        relu = torch.nn.functional.relu(self_conv1);  self_conv1 = None
        self_conv2 = self.self_conv2(relu);  relu = None
        relu_1 = torch.nn.functional.relu(self_conv2);  self_conv2 = None
        max_pool2d = torch.nn.functional.max_pool2d(relu_1, 2);  relu_1 = None
        self_dropout1 = self.self_dropout1(max_pool2d);  max_pool2d = None
        flatten = torch.flatten(self_dropout1, 1);  self_dropout1 = None
        self_fc1 = self.self_fc1(flatten);  flatten = None
        relu_2 = torch.nn.functional.relu(self_fc1);  self_fc1 = None
        self_dropout2 = self.self_dropout2(relu_2);  relu_2 = None
        self_fc2 = self.self_fc2(self_dropout2);  self_dropout2 = None
        log_softmax = torch.nn.functional.log_softmax(self_fc2, dim = 1);  self_fc2 = None
        return (log_softmax,)


mod = Repro()

# Setup debug minifier compiler
torch._dynamo.debug_utils.MINIFIER_SPAWNED = True
compiler_fn = lookup_backend("dynamo_minifier_backend")

dynamo_minifier_backend = functools.partial(
    compiler_fn,
    compiler_name="inductor",
)
opt_mod = torch._dynamo.optimize(dynamo_minifier_backend)(mod)

with torch.cuda.amp.autocast(enabled=False):
    opt_mod(*args)

```

### Versions
```
Collecting environment information...
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1028-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7R32
Stepping:                        0
CPU MHz:                         2799.516
BogoMIPS:                        5599.03
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        2 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save rdpid

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.0+cu118
[pip3] torchvision==0.15.0+cu118
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torchaudio                2.0.0+cu118              pypi_0    pypi
[conda] torchvision               0.15.0+cu118             pypi_0    pypi

cc @csarofeen @ptrblck @xwang233 @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh
```

**Comment by davidberard98** [comment]
@agunapal can you try running with `TORCH_SHOW_CPP_STACKTRACES=1`? (actually I'm not sure if this works on your build or with this error, but worth a try)

Can you also run `python -c "import torch; print(torch.backends.cudnn.version())"`?

@ngimel since this seems like a cudnn issue do you know who we could tag on this?

fwiw, I haven't been able to repro after trying a few different configurations (two local builds, and RC 2.0 build).

**Comment by ngimel** [comment]
@ptrblck for cudnn errors

**Comment by ngimel** [comment]
But tbh mnist is a toy network, so even if cudnn does something not compatible with graph capture for some of those convolutions, it's not very high pri

**Comment by ptrblck** [comment]
I wasn't able to reproduce the cuDNN issue yet, but I have also used an A100 node, so would need to grab another one with sm_86.
However, I also see potential convergence issues when `reduce-overhead` is used.
For my initial testing I installed the 2.0.0+cu118 RC wheels via:
```
pip install torch torchvision --index-url https://download.pytorch.org/whl/test/cu118
```
and let the code run 10 times via:
```
for i in {1..10}; do python tmp.py; done
```
The outputs show a model convergence using `torch.compile` in its default mode:
```python
[2023-03-10 21:19:38,344] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.305176
Train Epoch: 1 [6400/60000 (11%)]	Loss: 0.370721
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.120223
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.143823
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.153311
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.188869
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.136129
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.060853
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.131968
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.032771
[2023-03-10 21:19:49,161] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
Training Time: 19.7331875

Test set: Average loss: 0.0532, Accuracy: 9825/10000 (98%)

Evaluation Time: 1.7148896484375
...
Train Epoch: 4 [0/60000 (0%)]	Loss: 0.004568
Train Epoch: 4 [6400/60000 (11%)]	Loss: 0.001349
Train Epoch: 4 [12800/60000 (21%)]	Loss: 0.109541
Train Epoch: 4 [19200/60000 (32%)]	Loss: 0.005593
Train Epoch: 4 [25600/60000 (43%)]	Loss: 0.062648
Train Epoch: 4 [32000/60000 (53%)]	Loss: 0.002450
Train Epoch: 4 [38400/60000 (64%)]	Loss: 0.028670
Train Epoch: 4 [44800/60000 (75%)]	Loss: 0.000512
Train Epoch: 4 [51200/60000 (85%)]	Loss: 0.013152
Train Epoch: 4 [57600/60000 (96%)]	Loss: 0.016910
Training Time: 8.675451171875

Test set: Average loss: 0.0302, Accuracy: 9886/10000 (99%)

Evaluation Time: 1.376868408203125
```
but fails with `opt_model = torch.compile(model, mode="reduce-overhead")`:
```python
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.305176
Train Epoch: 1 [6400/60000 (11%)]	Loss: 2.310328
Train Epoch: 1 [12800/60000 (21%)]	Loss: 2.338835
Train Epoch: 1 [19200/60000 (32%)]	Loss: 2.310786
Train Epoch: 1 [25600/60000 (43%)]	Loss: 2.319447
Train Epoch: 1 [32000/60000 (53%)]	Loss: 2.327922
Train Epoch: 1 [38400/60000 (64%)]	Loss: 2.342568
Train Epoch: 1 [44800/60000 (75%)]	Loss: 2.277673
Train Epoch: 1 [51200/60000 (85%)]	Loss: 2.333785
Train Epoch: 1 [57600/60000 (96%)]	Loss: 2.336643
[2023-03-10 21:33:22,653] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
Training Time: 13.2455

Test set: Average loss: 2.3118, Accuracy: 1066/10000 (11%)

Evaluation Time: 1.51864208984375
...
Train Epoch: 4 [0/60000 (0%)]	Loss: 2.314523
Train Epoch: 4 [6400/60000 (11%)]	Loss: 2.319013
Train Epoch: 4 [12800/60000 (21%)]	Loss: 2.298557
Train Epoch: 4 [19200/60000 (32%)]	Loss: 2.322405
Train Epoch: 4 [25600/60000 (43%)]	Loss: 2.301838
Train Epoch: 4 [32000/60000 (53%)]	Loss: 2.298177
Train Epoch: 4 [38400/60000 (64%)]	Loss: 2.324035
Train Epoch: 4 [44800/60000 (75%)]	Loss: 2.308752
Train Epoch: 4 [51200/60000 (85%)]	Loss: 2.319532
Train Epoch: 4 [57600/60000 (96%)]	Loss: 2.324502
Training Time: 8.7441689453125

Test set: Average loss: 2.3118, Accuracy: 1066/10000 (11%)

Evaluation Time: 1.389031982421875
```
Note that all 10 repetitions of these training runs show the same behavior.
@agunapal did you see the same issues and would it be possible to provide cuDNN API logs for the cuDNN error?

**Comment by agunapal** [comment]
@davidberard98 
```
python -c "import torch; print(torch.backends.cudnn.version())"
8700
```

**Comment by agunapal** [comment]
@ptrblck Sure, I can do that.

I am able to consistently reproduce the error.

I ran it with `CUDA_LAUNCH_BLOCKING=1`

This is what I see 

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 328, in cudagraphify_impl
    static_outputs = model(list(static_inputs))
  File "/tmp/torchinductor_ubuntu/mn/cmn7hcpe7mhptfdogyeiuv3updxvfnzzppbkcv6oxewxgm2qwnr4.py", line 182, in call
    buf0 = aten.convolution(arg8_1, arg0_1, None, (1, 1), (0, 0), (1, 1), False, (0, 0), 1)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_ops.py", line 499, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/fork/examples/pt2.0/mnist/main.py", line 166, in <module>
    main()
  File "/home/ubuntu/fork/examples/pt2.0/mnist/main.py", line 158, in main
    print(f"Evaluation Time: {timed(lambda: test(opt_model, device, test_loader))[1]}")
  File "/home/ubuntu/fork/examples/pt2.0/mnist/main.py", line 80, in timed
    result = fn()
  File "/home/ubuntu/fork/examples/pt2.0/mnist/main.py", line 158, in <lambda>
    print(f"Evaluation Time: {timed(lambda: test(opt_model, device, test_loader))[1]}")
  File "/home/ubuntu/fork/examples/pt2.0/mnist/main.py", line 65, in test
    output = model(data)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/fork/examples/pt2.0/mnist/main.py", line 25, in forward
    def forward(self, x):
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2819, in forward
    return compiled_fn(full_args)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1222, in g
    return f(*args)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1898, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1247, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 248, in run
    return model(new_inputs)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 265, in run
    compiled_fn = cudagraphify_impl(model, new_inputs, static_input_idxs)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 327, in cudagraphify_impl
    with torch.cuda.graph(graph, stream=stream):
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/cuda/graphs.py", line 173, in __exit__
    self.cuda_graph.capture_end()
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/cuda/graphs.py", line 79, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

**Comment by ngimel** [comment]
Looks like it's fixed on master
