### ISSUE TITLE
torch.compile(dynamic=True) does not work with a simple Transformer + embedding at inference

### ISSUE THREAD

**Issue by jhoareau** [pytorch/pytorch#96414]
### 🐛 Describe the bug

Using yesterday's CI build (possibly with previous builds too), I am getting the following error while trying to run `torch.compile` in dynamic mode for a simple TransformerEncoder with an embedding layer.
The compilation works fine with the embedding layer only, the encoder only, but not with the combination of both.
The compilation also works fine if `dynamic=False`.

```python
import torch
from torch import nn
from torch.nn import TransformerEncoder, TransformerEncoderLayer


class TransformerWithEmbedding(nn.Module):
    def __init__(self):
        super().__init__()

        layer = TransformerEncoderLayer(4, 1, 16)
        self.encoder = TransformerEncoder(layer, 1)
        self.embedding = nn.Embedding(16, 4, padding_idx=0)
    
    def forward(self, input):
        embedded = self.embedding(input)
        return self.encoder(embedded)

network = TransformerWithEmbedding().eval().cuda()
compiled_network = torch.compile(network, dynamic=True)
input = torch.tensor([[1, 2, 3, 4]], device="cuda:0", dtype=torch.int)
compiled_network(input)
```

Throws the following error in inductor compilation:
```
Traceback (most recent call last):
  File "lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1202, in run_node
    return nnmodule(*args, **kwargs)
  File "lib/python3.10/site-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 315, in forward
    output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)
  File "lib/python3.10/site-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 591, in forward
    x = self.norm1(x + self._sa_block(x, src_mask, src_key_padding_mask))
  File "lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 599, in _sa_block
    x = self.self_attn(x, x, x,
  File "lib/python3.10/site-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1210, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "lib/python3.10/site-packages/torch/nn/functional.py", line 5339, in multi_head_attention_forward
    attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1155, in get_fake_value
    return wrap_fake_exception(
  File "lib/python3.10/site-packages/torch/_dynamo/utils.py", line 808, in wrap_fake_exception
    return fn()
  File "lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1156, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1209, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_module self_encoder(*(FakeTensor(FakeTensor(..., device='meta', size=(1, s0, 4), grad_fn=<EmbeddingBackward0>), cuda:0),), **{}):
Cannot call sizes() on tensor with symbolic sizes/strides
(scroll up for backtrace)
```

@ezyang 

### Versions
```
PyTorch version: 2.1.0.dev20230308+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.7 (main, Sep 21 2022, 07:59:18) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-139-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.8.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.8.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          48
On-line CPU(s) list:             0-47
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       1
NUMA node(s):                    4
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           8
Model name:                      AMD Ryzen Threadripper 2970WX 24-Core Processor
Stepping:                        2
Frequency boost:                 enabled
CPU MHz:                         1758.465
CPU max MHz:                     3000.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        5987.96
Virtualization:                  AMD-V
L1d cache:                       768 KiB
L1i cache:                       1.5 MiB
L2 cache:                        12 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-5,24-29
NUMA node1 CPU(s):               12-17,36-41
NUMA node2 CPU(s):               6-11,30-35
NUMA node3 CPU(s):               18-23,42-47
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+b8b470bc59
[pip3] torch==2.1.0.dev20230308+cu118
[pip3] torchdata==0.7.0.dev20230308
[pip3] torchmetrics==0.11.1
```

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @mikaylagawarecki

**Comment by ezyang** [comment]
Sdpa related coverage regression . Should be easy to fix

**Comment by cpuhrsch** [comment]
cc @drisspg

**Comment by jhoareau** [comment]
I see that @janeyx99 marked this as being part of the nested tensor module, but the error is still happening when I set `enable_nested_tensor=False` in the TransformerEncoder.
It also happens when the fast path is disabled (with `norm_first=True` for example), in `unflatten`:
```
  File "lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1189, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "lib/python3.10/site-packages/torch/nn/functional.py", line 5193, in multi_head_attention_forward
    q, k, v = _in_projection_packed(query, key, value, in_proj_weight, in_proj_bias)
  File "lib/python3.10/site-packages/torch/nn/functional.py", line 4772, in _in_projection_packed
    proj = proj.unflatten(-1, (3, E)).unsqueeze(0).transpose(0, -2).squeeze(-2).contiguous()
  File "lib/python3.10/site-packages/torch/_tensor.py", line 1189, in unflatten
    return super().unflatten(dim, sizes)
RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides
```

@ezyang

**Comment by drisspg** [comment]
I'll take a look at this today
