### ISSUE TITLE
Not implemented error for `aten.quantize_per_tensor.tensor_qparams`

### ISSUE THREAD

**Issue by shingjan** [pytorch/pytorch#96435]
### 🐛 Describe the bug

The aforementioned error exists for quantized models in torchbench like `resnet50_quantized_qat` and `mobilenet_v2_quantized_qat`. My repro:
```
python benchmarks/dynamo/torchbench.py --only resnet50_quantized_qat -dcpu --performance
```

Stacktrace:
```
Traceback (most recent call last):
  File "/home/yj/pytorch/torch/_subclasses/fake_tensor.py", line 1243, in dispatch
    r = func(*args, **kwargs)
  File "/home/yj/pytorch/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/yj/pytorch/torch/_ops.py", line 377, in _get_dispatch
    final_key = resolve_key(self, key)
  File "/home/yj/pytorch/torch/_ops.py", line 106, in resolve_key
    raise NotImplementedError(f"could not find kernel for {op} at dispatch key {k}")
NotImplementedError: could not find kernel for aten.quantize_per_tensor.tensor_qparams at dispatch key DispatchKey.Meta
```

### Versions

PyTorch version: 2.0.0a0+git64b8fae
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070
Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          24
On-line CPU(s) list:             0-23
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           33
Model name:                      AMD Ryzen 9 5900X 12-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     4950.1948
CPU min MHz:                     2200.0000
BogoMIPS:                        7400.08
Virtualization:                  AMD-V
L1d cache:                       384 KiB
L1i cache:                       384 KiB
L2 cache:                        6 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.0
[pip3] CoCa-pytorch==0.0.7
[pip3] dalle2-pytorch==1.10.5
[pip3] ema-pytorch==0.1.4
[pip3] functorch==1.14.0a0+408bcf1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] pytorch-transformers==1.2.0
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.2.1
[pip3] torch==2.0.0a0+git64b8fae
[pip3] torch-fidelity==0.3.0
[pip3] torch-struct==0.5
[pip3] torchaudio==2.0.0a0+9368f33
[pip3] torchdata==0.7.0a0+f083d52
[pip3] torchmetrics==0.11.0
[pip3] torchrec-nightly==2023.1.25
[pip3] torchtext==0.15.0a0+bb0efcd
[pip3] torchvision==0.15.0a0+85983a5
[pip3] torchx==0.4.0
[pip3] vector-quantize-pytorch==0.10.15
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] clip-anytorch             2.5.0                    pypi_0    pypi
[conda] coca-pytorch              0.0.7                    pypi_0    pypi
[conda] dalle2-pytorch            1.10.5                   pypi_0    pypi
[conda] ema-pytorch               0.1.4                    pypi_0    pypi
[conda] functorch                 1.14.0a0+408bcf1          pypi_0    pypi
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.2.1                    pypi_0    pypi
[conda] torch                     2.0.0a0+git64b8fae           dev_0    <develop>
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torchaudio                2.0.0a0+9368f33          pypi_0    pypi
[conda] torchdata                 0.7.0a0+f083d52          pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchrec-nightly          2023.1.25                pypi_0    pypi
[conda] torchtext                 0.15.0a0+bb0efcd          pypi_0    pypi
[conda] torchvision               0.15.0a0+85983a5          pypi_0    pypi
[conda] torchx                    0.4.0                    pypi_0    pypi
[conda] vector-quantize-pytorch   0.10.15                  pypi_0    pypi

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by davidberard98** [comment]
minimal repro (minifier didn't work):

```python
import torch
import torch._dynamo

def fn(x, scale, zero_point):
    return torch.quantize_per_tensor(x, scale, zero_point, torch.quint8)

x = torch.rand((2, 2), requires_grad=True) * 2 + 10
scale = torch.tensor(2.)
zero_point = torch.tensor(10.)

torch._dynamo.optimize("aot_eager")(fn)(x, scale, zero_point)
```

Full log:
```
Traceback (most recent call last):
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1240, in dispatch
    r = func(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_ops.py", line 316, in __call__
    return self._op(*args, **kwargs or {})
  File "/scratch/dberard/dynamo38/pytorch/torch/_ops.py", line 382, in _get_dispatch
    final_key = resolve_key(self, key)
  File "/scratch/dberard/dynamo38/pytorch/torch/_ops.py", line 186, in resolve_key
    raise NotImplementedError(f"could not find kernel for {op} at dispatch key {k}")
NotImplementedError: could not find kernel for aten.quantize_per_tensor.tensor_qparams at dispatch key DispatchKey.Meta

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 1196, in run_node
    return node.target(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1057, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1245, in dispatch
    return run_fallback_kernel(self, func, args, kwargs, not_implemented_error)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1464, in run_fallback_kernel
    return tree_map(map_out, r)
  File "/scratch/dberard/dynamo38/pytorch/torch/utils/_pytree.py", line 196, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/dberard/dynamo38/pytorch/torch/utils/_pytree.py", line 196, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 1460, in map_out
    return fake_mode.fake_tensor_converter(fake_mode, e)
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 314, in __call__
    return self.from_real_tensor(
  File "/scratch/dberard/dynamo38/pytorch/torch/_subclasses/fake_tensor.py", line 252, in from_real_tensor
    raise UnsupportedFakeTensorException("quantized nyi in meta tensors")
torch._subclasses.fake_tensor.UnsupportedFakeTensorException: quantized nyi in meta tensors

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 1154, in get_fake_value
    return wrap_fake_exception(
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 808, in wrap_fake_exception
    return fn()
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 1155, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 1208, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <built-in method quantize_per_tensor of type object at 0x7fb817c0e440>(*(FakeTensor(FakeTensor(..., device='meta', size=(2, 2), grad_fn=<CloneBackward0>), cpu), FakeTensor(FakeTensor(..., device='meta', size=()), cpu), FakeTensor(FakeTensor(..., device='meta', size=()), cpu), torch.quint8), **{}):
quantized nyi in meta tensors
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "quantization.py", line 11, in <module>
    torch._dynamo.optimize("aot_eager")(fn)(x, scale, zero_point)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/eval_frame.py", line 254, in _fn
    return fn(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/eval_frame.py", line 391, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/convert_frame.py", line 406, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/convert_frame.py", line 105, in _fn
    return fn(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/convert_frame.py", line 263, in _convert_frame_assert
    return _compile(
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/convert_frame.py", line 326, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/convert_frame.py", line 313, in transform
    tracer.run()
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 1840, in run
    super().run()
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 346, in wrapper
    return inner_fn(self, inst)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 992, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/symbolic_convert.py", line 494, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/variables/torch.py", line 565, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/variables/builder.py", line 865, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/variables/builder.py", line 900, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/scratch/dberard/dynamo38/pytorch/torch/_dynamo/utils.py", line 1175, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError:

from user code:
   File "quantization.py", line 5, in fn
    return torch.quantize_per_tensor(x, scale, zero_point, torch.quint8)

Set torch._dynamo.config.verbose=True or TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

Note: I see that this model is disabled in the benchmark due to failing baseline - but in the past, other issues suggest that this used to work.

**Comment by Xia-Weiwen** [comment]
Looks like it's the same as https://github.com/pytorch/pytorch/issues/93430
Quantization is not supported right now and it's under dev.

**Comment by vkuzo** [comment]
cc @andrewor14 , @jerryzh168 

Support for torch.compile'ing through quantized models is not there yet, but it is planned.  Specifically, we are adding functionality to replace the aten quantization functions (torch.quantize_per_tensor, etc) with their decomposed representations (torch.ops.quantized_decomposed.quantize_per_tensor, etc).  For now this is only planned for quant/dequant/fake_quant, but in the future it also may extend to quantized operations (linear, conv, etc).

**Comment by leslie-fang-intel** [comment]
Thanks @vkuzo, I have created some PRs https://github.com/pytorch/pytorch/pull/96477 here to support lowering to inductor based on quantization 2.0 graph. It still needs some work before ready to be review. Will ask yours' review when it's ready. Thanks~

**Comment by williamwen42** [comment]
Command no longer errors - closing as fixed.
