### ISSUE TITLE
Unable to move torch.jit.load-ed models to XLA devices

### ISSUE THREAD

**Issue by alanwaketan** [pytorch/pytorch#96448]
### 🐛 Describe the bug

Here are the steps to reproduce and the error:
```
>>> import torch
>>> import torch_xla.core.xla_model as xm
>>> x = torch.nn.Linear(8, 32)
>>> torch.jit.save(torch.jit.script(x), 'x.pt')
>>> xsr = torch.jit.load('x.pt')
>>> xsr.to(xm.xla_device())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 987, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 668, in _apply
    assert isinstance(param, Parameter)
AssertionError
```
Here is when it works if I try just scripting (without save&load):
```
>>> x.to(xm.xla_device())
Linear(in_features=8, out_features=32, bias=True)
>>> xs = torch.jit.script(x)
>>> xs.to(xm.xla_device())
RecursiveScriptModule(original_name=Linear)
```
However, the version that's read back into xsr fails:
```
>>> xsr
RecursiveScriptModule(original_name=Linear)
>>> xsr.to(xm.xla_device())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 987, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 668, in _apply
    assert isinstance(param, Parameter)
AssertionError
```

Let me know if you need any more information or a way to install pytorch/xla.

### Versions

pt-1.13

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @bdhirsh @yyetim

**Comment by miladm** [comment]
@janeyx99 any update on this ticket?

**Comment by janeyx99** [comment]
@bdhirsh  should we pull in someone from the XLA side?

**Comment by alanwaketan** [comment]
> @bdhirsh should we pull in someone from the XLA side?

We are from the XLA side. 😂 We are trying to consult some of the TorchScript folks.

**Comment by davidberard98** [comment]
Sorry, I don't have bandwidth to investigate this.  If it's blocking you, I'd recommend looking further into the differences between the original and reloaded modules: e.g. what attribute used to be a Parameter but is now no longer a parameter; and in csrc/jit/serialization/... why is it getting loaded?

also fwiw, I tried this with `.to('cuda')` (I don't have xla set up) and I can't repro. Does xla have some special handling? If not, maybe upgrading your pytorch version will fix this.

**Comment by alanwaketan** [comment]
> Sorry, I don't have bandwidth to investigate this. If it's blocking you, I'd recommend looking further into the differences between the original and reloaded modules: e.g. what attribute used to be a Parameter but is now no longer a parameter; and in csrc/jit/serialization/... why is it getting loaded?
> 
> also fwiw, I tried this with `.to('cuda')` (I don't have xla set up) and I can't repro. Does xla have some special handling? If not, maybe upgrading your pytorch version will fix this.

Thanks, David. I'm guessing a more general question is for cuda, doest TorchScript implement anythings special to handle this move? I guess XLA will probably need to handle that. Also, is anyone else still working on TorchScript and potential having the bandwidth to help us?

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
