### ISSUE TITLE
[Inductor] C++ compile error when doing computation involving a modified tensor

### ISSUE THREAD

**Issue by soodoshll** [pytorch/pytorch#96446]
### 🐛 Describe the bug

Hi! I found that modifying an element of a tensor followed by an element-wise multiplication (or addition) will trigger a C++ compiler error for CPU code generation.

Here is a code snippet:

```
import torch
a = torch.rand(1) 
b = torch.rand(2)
def forward(a, b):
    a[0] = 2
    return a * b
fn_compiled = torch.compile(forward)
print(fn_compiled(a, b))
```

### Error logs

```
[2023-03-09 16:02:29,645] torch._dynamo.debug_utils: [WARNING] Writing minified repro to /home/su/accdiff/torch_compile_debug/run_2023_03_09_16_02_29_645148-pid_373992/minifier/minifier_launcher.py
[2023-03-09 16:02:29,645] torch._dynamo.debug_utils: [ERROR] CompilerError
Traceback (most recent call last):
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/codecache.py", line 580, in load
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['g++', '/tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp', '-shared', '-fPIC', '-Wall', '-std=c++17', '-Wno-unused-variable', '-I/home/su/accdiff/thirdparty/pytorch/torch/include', '-I/home/su/accdiff/thirdparty/pytorch/torch/include/torch/csrc/api/include', '-I/home/su/accdiff/thirdparty/pytorch/torch/include/TH', '-I/home/su/accdiff/thirdparty/pytorch/torch/include/THC', '-I/usr/include/python3.9', '-L/home/su/accdiff/thirdparty/pytorch/torch/lib', '-L/usr/lib/x86_64-linux-gnu', '-lc10', '-ltorch', '-ltorch_cpu', '-ltorch_python', '-lgomp', '-DCPU_CAPABILITY_AVX2', '-O3', '-ffast-math', '-fno-finite-math-only', '-march=native', '-fopenmp', '-D', 'C10_USING_CUSTOM_GENERATED_MACROS', '-o/tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.so']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/su/accdiff/test.py", line 8, in <module>
    print(fn_compiled(a, b))
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/eval_frame.py", line 254, in _fn
    return fn(*args, **kwargs)
  File "/home/su/accdiff/test.py", line 4, in forward
    def forward(a, b):
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/eval_frame.py", line 254, in _fn
    return fn(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_functorch/aot_autograd.py", line 2887, in forward
    return compiled_fn(full_args)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_functorch/aot_autograd.py", line 1241, in g
    return f(*args)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_functorch/aot_autograd.py", line 1920, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/home/su/accdiff/thirdparty/pytorch/torch/_functorch/aot_autograd.py", line 1266, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/debug_utils.py", line 575, in deferred_for_real_inputs
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/compile_fx.py", line 180, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/graph.py", line 633, in compile_to_fn
    return self.compile_to_module().call
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/graph.py", line 622, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/codecache.py", line 608, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_su/ig/cigv3tqrjmehguutdpruv6ylypfwk3usj26yindgefhoc3h5kfbb.py", line 64, in <module>
    async_compile.wait(globals())
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/codecache.py", line 795, in wait
    scope[key] = result.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/codecache.py", line 772, in task
    return CppCodeCache.load(source_code).kernel
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/codecache.py", line 582, in load
    raise exc.CppCompileError(cmd, e.output) from e
torch._inductor.exc.CppCompileError: C++ compile error

Command:
g++ /tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp -shared -fPIC -Wall -std=c++17 -Wno-unused-variable -I/home/su/accdiff/thirdparty/pytorch/torch/include -I/home/su/accdiff/thirdparty/pytorch/torch/include/torch/csrc/api/include -I/home/su/accdiff/thirdparty/pytorch/torch/include/TH -I/home/su/accdiff/thirdparty/pytorch/torch/include/THC -I/usr/include/python3.9 -L/home/su/accdiff/thirdparty/pytorch/torch/lib -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lgomp -DCPU_CAPABILITY_AVX2 -O3 -ffast-math -fno-finite-math-only -march=native -fopenmp -D C10_USING_CUSTOM_GENERATED_MACROS -o/tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.so

Output:
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:8,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec_base.h:1011: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
 1011 | # pragma unroll
      |
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:10,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_float.h:438: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  438 | #pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_float.h:442: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  442 | #pragma unroll
      |
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:12,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_bfloat16.h:693: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  693 | #pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_bfloat16.h:698: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  698 | #pragma unroll
      |
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:13,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_double.h:403: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  403 | #pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_double.h:407: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  407 | #pragma unroll
      |
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:14,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_int.h:287: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  287 | # pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_int.h:295: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  295 | # pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_int.h:307: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  307 | # pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_int.h:315: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  315 | # pragma unroll
      |
In file included from /tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp:2:
/tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:66: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   66 | #pragma unroll
      |
/tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:75: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   75 | #pragma unroll
      |
/tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:92: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   92 | #pragma unroll
      |
/tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp: In function ‘void kernel(const float*, const float*, float*, float*)’:
/tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp:16:60: error: cannot convert ‘at::vec::CPU_CAPABILITY::Vectorized<int>’ to ‘const at::vec::CPU_CAPABILITY::Vectorized<float>&’
   16 |             auto tmp4 = decltype(tmp2)::blendv(tmp3, tmp2, tmp1);
      |                                                            ^~~~
      |                                                            |
      |                                                            at::vec::CPU_CAPABILITY::Vectorized<int>
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:10,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_float.h:46:56: note:   initializing argument 3 of ‘static at::vec::CPU_CAPABILITY::Vectorized<float> at::vec::CPU_CAPABILITY::Vectorized<float>::blendv(const at::vec::CPU_CAPABILITY::Vectorized<float>&, const at::vec::CPU_CAPABILITY::Vectorized<float>&, const at::vec::CPU_CAPABILITY::Vectorized<float>&)’
   46 |                               const Vectorized<float>& mask) {
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp:26:30: warning: self-comparison always evaluates to true [-Wtautological-compare]
   26 |             auto tmp1 = tmp0 == tmp0;
      |                         ~~~~ ^~ ~~~~
/tmp/torchinductor_su/xp/cxper7g2vlft53l2lcnw52z3gdkdirgitblwctcljdvfuv6gggng.cpp:36:26: warning: self-comparison always evaluates to true [-Wtautological-compare]
   36 |         auto tmp1 = tmp0 == tmp0;
      |                     ~~~~ ^~ ~~~~
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gitfe05266
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.112
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070
Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.4
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.6.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           1
Model name:                      AMD Ryzen Threadripper 1950X 16-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     3400.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        6786.49
Virtualization:                  AMD-V
L1d cache:                       512 KiB
L1i cache:                       1 MiB
L2 cache:                        8 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0a0+gitfe05266
[conda] Could not collect

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by EikanWang** [comment]
@jgong5 , your PR will fix this issue, right?

**Comment by jgong5** [comment]
> @jgong5 , your PR will fix this issue, right?

Yes.
