### ISSUE TITLE
[Inductor] C++ compile error when using integer type lower than int32

### ISSUE THREAD

**Issue by soodoshll** [pytorch/pytorch#96487]
### 🐛 Describe the bug

Hi! I met a C++ compile error when using int16 together with `+` and `min` for CPU code generation. Here is the reproducing script:
```
import torch
a = torch.randint(4, (2, ), dtype=torch.int16)

def forward(a):
    a = a + 1
    return a.min()

fn_compiled = torch.compile(forward)
print(fn_compiled(a))
```

### Error logs

```
Traceback (most recent call last):
  File "/home/su/accdiff/test.py", line 9, in <module>
    print(fn_compiled(a))
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/eval_frame.py", line 254, in _fn
    return fn(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/eval_frame.py", line 391, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/convert_frame.py", line 406, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/convert_frame.py", line 105, in _fn
    return fn(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/convert_frame.py", line 263, in _convert_frame_assert
    return _compile(
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/convert_frame.py", line 326, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/convert_frame.py", line 313, in transform
    tracer.run()
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/symbolic_convert.py", line 1840, in run
    super().run()
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/symbolic_convert.py", line 1919, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/output_graph.py", line 545, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/output_graph.py", line 615, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/output_graph.py", line 701, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/output_graph.py", line 697, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/debug_utils.py", line 1064, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/__init__.py", line 1382, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/compile_fx.py", line 488, in compile_fx
    return aot_autograd(
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_functorch/aot_autograd.py", line 2873, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_functorch/aot_autograd.py", line 2554, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_functorch/aot_autograd.py", line 1735, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_functorch/aot_autograd.py", line 1346, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args_with_views_handled)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/compile_fx.py", line 462, in fw_compiler
    return inner_compile(
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/debug_utils.py", line 598, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/compile_fx.py", line 180, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/graph.py", line 633, in compile_to_fn
    return self.compile_to_module().call
  File "/home/su/accdiff/thirdparty/pytorch/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/graph.py", line 622, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/codecache.py", line 608, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_su/lp/clpahzraewfwreemm2z673mix7qi2pppelqxtu4p4e32tppqpkkq.py", line 42, in <module>
    async_compile.wait(globals())
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/codecache.py", line 795, in wait
    scope[key] = result.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/codecache.py", line 772, in task
    return CppCodeCache.load(source_code).kernel
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/codecache.py", line 582, in load
    raise exc.CppCompileError(cmd, e.output) from e
torch._dynamo.exc.BackendCompilerFailed: backend='debug_wrapper' raised:
CppCompileError: C++ compile error

Command:
g++ /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp -shared -fPIC -Wall -std=c++17 -Wno-unused-variable -I/home/su/accdiff/thirdparty/pytorch/torch/include -I/home/su/accdiff/thirdparty/pytorch/torch/include/torch/csrc/api/include -I/home/su/accdiff/thirdparty/pytorch/torch/include/TH -I/home/su/accdiff/thirdparty/pytorch/torch/include/THC -I/usr/include/python3.9 -L/home/su/accdiff/thirdparty/pytorch/torch/lib -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lgomp -DCPU_CAPABILITY_AVX2 -O3 -ffast-math -fno-finite-math-only -march=native -fopenmp -D C10_USING_CUSTOM_GENERATED_MACROS -o/tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.so

Output:
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:8,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec_base.h:1011: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
 1011 | # pragma unroll
      |
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:10,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_float.h:438: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  438 | #pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_float.h:442: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  442 | #pragma unroll
      |
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:12,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_bfloat16.h:693: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  693 | #pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_bfloat16.h:698: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  698 | #pragma unroll
      |
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:13,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_double.h:403: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  403 | #pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_double.h:407: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  407 | #pragma unroll
      |
In file included from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256.h:14,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from /home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:10,
                 from /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:2:
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_int.h:287: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  287 | # pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_int.h:295: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  295 | # pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_int.h:307: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  307 | # pragma unroll
      |
/home/su/accdiff/thirdparty/pytorch/torch/include/ATen/cpu/vec/vec256/vec256_int.h:315: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  315 | # pragma unroll
      |
In file included from /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:2:
/tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:66: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   66 | #pragma unroll
      |
/tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:75: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   75 | #pragma unroll
      |
/tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:92: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
   92 | #pragma unroll
      |
/tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp: In function ‘void kernel(const short int*, short int*)’:
/tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:14:43: error: no matching function for call to ‘min(short int&, int&)’
   14 |                 tmp3 = std::min(tmp3, tmp2);
      |                                           ^
In file included from /usr/include/c++/9/algorithm:61,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:1,
                 from /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:2:
/usr/include/c++/9/bits/stl_algobase.h:198:5: note: candidate: ‘template<class _Tp> constexpr const _Tp& std::min(const _Tp&, const _Tp&)’
  198 |     min(const _Tp& __a, const _Tp& __b)
      |     ^~~
/usr/include/c++/9/bits/stl_algobase.h:198:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:14:43: note:   deduced conflicting types for parameter ‘const _Tp’ (‘short int’ and ‘int’)
   14 |                 tmp3 = std::min(tmp3, tmp2);
      |                                           ^
In file included from /usr/include/c++/9/algorithm:61,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:1,
                 from /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:2:
/usr/include/c++/9/bits/stl_algobase.h:246:5: note: candidate: ‘template<class _Tp, class _Compare> constexpr const _Tp& std::min(const _Tp&, const _Tp&, _Compare)’
  246 |     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
/usr/include/c++/9/bits/stl_algobase.h:246:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:14:43: note:   deduced conflicting types for parameter ‘const _Tp’ (‘short int’ and ‘int’)
   14 |                 tmp3 = std::min(tmp3, tmp2);
      |                                           ^
In file included from /usr/include/c++/9/algorithm:62,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:1,
                 from /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:2:
/usr/include/c++/9/bits/stl_algo.h:3450:5: note: candidate: ‘template<class _Tp> constexpr _Tp std::min(std::initializer_list<_Tp>)’
 3450 |     min(initializer_list<_Tp> __l)
      |     ^~~
/usr/include/c++/9/bits/stl_algo.h:3450:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:14:43: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘short int’
   14 |                 tmp3 = std::min(tmp3, tmp2);
      |                                           ^
In file included from /usr/include/c++/9/algorithm:62,
                 from /tmp/torchinductor_su/dl/cdljpywww2h2ag4o35mwbvm45hhasxnxkhqgbupxnk3y7olula65.h:1,
                 from /tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:2:
/usr/include/c++/9/bits/stl_algo.h:3456:5: note: candidate: ‘template<class _Tp, class _Compare> constexpr _Tp std::min(std::initializer_list<_Tp>, _Compare)’
 3456 |     min(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/usr/include/c++/9/bits/stl_algo.h:3456:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_su/he/ches4h3plhq5uqf3yf5dvsxje3yzz2tr6usd3yzufedzfgmciyd6.cpp:14:43: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘short int’
   14 |                 tmp3 = std::min(tmp3, tmp2);
      |                                           ^



You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Versions

PyTorch version: 2.1.0a0+gitfe05266
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.112
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070
Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.4
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.6.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           1
Model name:                      AMD Ryzen Threadripper 1950X 16-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     3400.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        6786.49
Virtualization:                  AMD-V
L1d cache:                       512 KiB
L1i cache:                       1 MiB
L2 cache:                        8 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0a0+gitfe05266
[conda] Could not collect

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by XiaobingSuper** [comment]
The root cause is that two short number add will be promoted to int(https://stackoverflow.com/questions/39060852/why-does-the-addition-of-two-shorts-return-an-int), we need to fix it.

**Comment by EikanWang** [comment]
@XiaobingSuper , will you fix it?

**Comment by williamwen42** [comment]
No longer repros - closing as fixed.
