### ISSUE TITLE
Unable to load nngraph-built Lua Torch models in PyTorch, even with unknown_classes=True flag

### ISSUE THREAD

**Issue by Amir-Arsalan** [pytorch/pytorch#9649]
I am trying to convert/load a model I built and trained some time ago using Lua Torch's nngraph in PyTorch but I get the following error:

`torch.utils.serialization.read_lua_file.T7ReaderException: don't know how to deserialize Lua class nn.gModule. If you want to ignore this error and load this object as a dict, specify unknown_classes=True in reader's constructor`

So I made an instance of the `T7Reader` class and set `unknown_classes=True` and called the `.read()` function but I get the following error:

```
with open('trainedModel/model.t7', 'rb') as f:
     reader = torch.utils.serialization.read_lua_file.T7Reader(f, unknown_classes=True)
     model = reader.read()


Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 548, in read_object
    return TorchObject(cls_name, self.read())
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 548, in read_object
    return TorchObject(cls_name, self.read())
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 548, in read_object
    return TorchObject(cls_name, self.read())
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 548, in read_object
    return TorchObject(cls_name, self.read())
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 571, in read_table
    k = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 593, in read
    return self.read_object()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 548, in read_object
    return TorchObject(cls_name, self.read())
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 572, in read_table
    v = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 595, in read
    return self.read_table()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 571, in read_table
    k = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 591, in read
    return self.read_function()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 532, in read_function
    upvalues = self.read()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 579, in read
    typeidx = self.read_int()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 475, in read_int
    return self._read('i')
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/serialization/read_lua_file.py", line 466, in _read
    result = struct.unpack(fmt, self.f.read(sz))
struct.error: unpack requires a bytes object of length 4
```

Why am I not able to load the model and get these errors? Does PyTorch support importing Lua Torch models built by nngraph?

**Comment by soumith** [comment]
pytorch doesn't support models built with `nngraph`

**Comment by Amir-Arsalan** [comment]
@soumith Could you please at least suggest some other way to do this? I cannot train that particular model anymore and need to convert it to PyTorch. Is there a way to convert nngraph models to normal modules in Torch?

**Comment by Amir-Arsalan** [comment]
@soumith Honestly I am surprised. Whole bunch of people used nngraph in Torch to build their models in the past and I'm surprised that PyTorch has no functionality to convert such models. I hope there is no assumption that people never want to load their nngraph-built models in PyTorch. Please advice!

**Comment by soumith** [comment]
we dont have any mechanism that has nngraph -> pytorch. You can read the nngraph model manually, convert it to torch7's `nn` model and then save it to disk. 
Alternatively, you can construct same model architecture in PyTorch, and only save the `parameters` of the `nngraph` model to disk and load those parameters into PyTorch and copy into this carefully constructed new model.

**Comment by tsellam** [comment]
Hi @Amir-Arsalan, did you manage to solve the problem? I am experiencing the same issue... thanks!

**Comment by Amir-Arsalan** [comment]
@tsellam Not really. It's very bothering ...
