### ISSUE TITLE
[Dynamo][AOTAutograd] DataDependentOutputException: aten._local_scalar_dense.default when using assert

### ISSUE THREAD

**Issue by ymwangg** [pytorch/pytorch#96529]
### 🐛 Describe the bug

Assertion statement is frequently seen in pytorch models. By default dynamo tries to rewrite assert with torch._assert. I'm hitting an error while running the following code:
```py
import torch
import torch._dynamo
import logging
torch._dynamo.logging.set_loggers_level(logging.DEBUG)
#torch._dynamo.config.rewrite_assert_with_torch_assert = False

def f(x):
    y = x.sin().abs()
    assert torch.sum(y) > 0
    # torch._assert(torch.sum(y) > 0, "message")
    return y

x = torch.randn(10)
opt_f = torch.compile(f, backend="aot_eager")
print(opt_f(x))
```

```
[2023-03-10 17:44:07,599] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/ubuntu/anaconda3/lib/python3.9/contextlib.py
[2023-03-10 17:44:07,599] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/ubuntu/anaconda3/lib/python3.9/contextlib.py
[2023-03-10 17:44:07,599] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/ubuntu/anaconda3/lib/python3.9/contextlib.py
[2023-03-10 17:44:07,599] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/ubuntu/anaconda3/lib/python3.9/contextlib.py
[2023-03-10 17:44:07,600] torch._dynamo.eval_frame: [DEBUG] skipping enable_dynamic /home/ubuntu/src/pytorch/torch/_dynamo/eval_frame.py
[2023-03-10 17:44:10,249] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing f
[2023-03-10 17:44:10,249] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line /home/ubuntu/src/detr/test_assert/test3.py:8
[2023-03-10 17:44:10,249] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST x []
[2023-03-10 17:44:10,250] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR sin [TensorVariable()]
[2023-03-10 17:44:10,250] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION 0 [GetAttrVariable(TensorVariable(), sin)]
[2023-03-10 17:44:10,253] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR abs [TensorVariable()]
[2023-03-10 17:44:10,254] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION 0 [GetAttrVariable(TensorVariable(), abs)]
[2023-03-10 17:44:10,255] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST y [TensorVariable()]
[2023-03-10 17:44:10,255] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line /home/ubuntu/src/detr/test_assert/test3.py:9
[2023-03-10 17:44:10,255] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL torch []
[2023-03-10 17:44:10,255] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR sum [TorchVariable(<module 'torch' from '/home/ubuntu/src/pytorch/torch/__init__.py'>)]
[2023-03-10 17:44:10,255] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST y [TorchVariable(<built-in method sum of type object at 0x7f2a0dc6f120>)]
[2023-03-10 17:44:10,255] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION 1 [TorchVariable(<built-in method sum of type object at 0x7f2a0dc6f120>), TensorVariable()]
[2023-03-10 17:44:10,257] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST 0 [TensorVariable()]
[2023-03-10 17:44:10,257] torch._dynamo.symbolic_convert: [DEBUG] TRACE COMPARE_OP > [TensorVariable(), ConstantVariable(int)]
[2023-03-10 17:44:10,258] torch._dynamo.symbolic_convert: [DEBUG] TRACE POP_JUMP_IF_TRUE 30 [TensorVariable()]
[2023-03-10 17:44:10,258] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line /home/ubuntu/src/detr/test_assert/test3.py:11
[2023-03-10 17:44:10,258] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST y []
[2023-03-10 17:44:10,258] torch._dynamo.symbolic_convert: [DEBUG] TRACE RETURN_VALUE None [TensorVariable()]
[2023-03-10 17:44:10,258] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo done tracing f (RETURN_VALUE)
[2023-03-10 17:44:10,258] torch._dynamo.symbolic_convert: [DEBUG] RETURN_VALUE triggered compile
[2023-03-10 17:44:10,258] torch._dynamo.output_graph: [DEBUG] COMPILING GRAPH due to GraphCompileReason(reason='return_value', user_stack=[<FrameSummary file /home/ubuntu/src/detr/test_assert/test3.py, line 11 in f>])
[2023-03-10 17:44:10,259] torch._dynamo.output_graph: [INFO] Step 2: calling compiler function compiler_fn
Failed to collect metadata on function, produced code may be suboptimal.  Known situations this can occur are inference mode only compilation involving resize_ or prims (!schema.hasAnyAliasInfo() INTERNAL ASSERT FAILED); if your situation looks different please file a bug to PyTorch.
Traceback (most recent call last):
  File "/home/ubuntu/src/pytorch/torch/_functorch/aot_autograd.py", line 1694, in aot_wrapper_dedupe
    fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "/home/ubuntu/src/pytorch/torch/_functorch/aot_autograd.py", line 616, in inner
    flat_f_outs = f(*flat_f_args)
  File "/home/ubuntu/src/pytorch/torch/_functorch/aot_autograd.py", line 2837, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/home/ubuntu/src/pytorch/torch/fx/interpreter.py", line 137, in run
    self.env[node] = self.run_node(node)
  File "/home/ubuntu/src/pytorch/torch/fx/interpreter.py", line 179, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/ubuntu/src/pytorch/torch/fx/interpreter.py", line 251, in call_function
    return target(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/__init__.py", line 1211, in _assert
    assert condition, message
  File "/home/ubuntu/src/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/_subclasses/fake_tensor.py", line 1057, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/ubuntu/src/pytorch/torch/_subclasses/fake_tensor.py", line 1232, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/_subclasses/fake_tensor.py", line 410, in local_scalar_dense
    raise DataDependentOutputException(func)
torch._subclasses.fake_tensor.DataDependentOutputException: aten._local_scalar_dense.default

While executing %_assert : [#users=0] = call_function[target=torch._assert](args = (%gt, assertion error), kwargs = {})
Original traceback:
  File "/home/ubuntu/src/detr/test_assert/test3.py", line 9, in f
    assert torch.sum(y) > 0

Traceback (most recent call last):
  File "/home/ubuntu/src/detr/test_assert/test3.py", line 15, in <module>
    print(opt_f(x))
  File "/home/ubuntu/src/pytorch/torch/_dynamo/eval_frame.py", line 254, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/eval_frame.py", line 391, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/convert_frame.py", line 406, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/convert_frame.py", line 105, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/convert_frame.py", line 263, in _convert_frame_assert
    return _compile(
  File "/home/ubuntu/src/pytorch/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/convert_frame.py", line 326, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/convert_frame.py", line 313, in transform
    tracer.run()
  File "/home/ubuntu/src/pytorch/torch/_dynamo/symbolic_convert.py", line 1840, in run
    super().run()
  File "/home/ubuntu/src/pytorch/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/home/ubuntu/src/pytorch/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/symbolic_convert.py", line 1919, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/ubuntu/src/pytorch/torch/_dynamo/output_graph.py", line 545, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/output_graph.py", line 615, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/output_graph.py", line 701, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/ubuntu/src/pytorch/torch/_dynamo/output_graph.py", line 697, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/ubuntu/src/pytorch/torch/_dynamo/debug_utils.py", line 1064, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/ubuntu/src/pytorch/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/_functorch/aot_autograd.py", line 2874, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/ubuntu/src/pytorch/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/_functorch/aot_autograd.py", line 2555, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/home/ubuntu/src/pytorch/torch/_functorch/aot_autograd.py", line 1824, in aot_wrapper_dedupe
    compiled_fn = compiler_fn(wrapped_flat_fn, deduped_flat_args, aot_config)
  File "/home/ubuntu/src/pytorch/torch/_functorch/aot_autograd.py", line 1298, in aot_dispatch_base
    _fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "/home/ubuntu/src/pytorch/torch/_functorch/aot_autograd.py", line 616, in inner
    flat_f_outs = f(*flat_f_args)
  File "/home/ubuntu/src/pytorch/torch/_functorch/aot_autograd.py", line 1822, in wrapped_flat_fn
    return flat_fn(*add_dupe_args(args))
  File "/home/ubuntu/src/pytorch/torch/_functorch/aot_autograd.py", line 2837, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/home/ubuntu/src/pytorch/torch/fx/interpreter.py", line 137, in run
    self.env[node] = self.run_node(node)
  File "/home/ubuntu/src/pytorch/torch/fx/interpreter.py", line 179, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/ubuntu/src/pytorch/torch/fx/interpreter.py", line 251, in call_function
    return target(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/__init__.py", line 1211, in _assert
    assert condition, message
  File "/home/ubuntu/src/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/_subclasses/fake_tensor.py", line 1057, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/ubuntu/src/pytorch/torch/_subclasses/fake_tensor.py", line 1232, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/_subclasses/fake_tensor.py", line 410, in local_scalar_dense
    raise DataDependentOutputException(func)
torch._dynamo.exc.BackendCompilerFailed: backend='compiler_fn' raised:
DataDependentOutputException: aten._local_scalar_dense.default
```
Note the same code can pass if I manually replace `assert` with `torch._assert`. The same exception still exists but it can be captured by [break_graph_if_unsupported](https://github.com/pytorch/pytorch/blob/d7db5b05b4c81a8e36945e354ccbacd261b9146e/torch/_dynamo/symbolic_convert.py#L339) and breaks the graph. So maybe dynamo should always break the graph if the condition variable is a tensor?

### Versions

```
PyTorch version: 2.1.0a0+git6c061e5
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1030-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
Yeah, should just get this to properly graph break. Shouldn't be too hard, I can review.

I'm going to add symbolic shapes label to this, even though technically there is no dynamic=True in the repro sample.

**Comment by ymwangg** [comment]
Thanks for the advice, I'll try to figure out a PR to fix it.

**Comment by ezyang** [comment]
cc @tugsbayasgalan

**Comment by ymwangg** [comment]
cc @ezyang @tugsbayasgalan A few observations:
1. After [#88246](https://github.com/pytorch/pytorch/issues/88246), statement like `assert torch.sum(y) > 0` can be graph captured and it works with non-aot backends like `eager`, even though the equivalent `torch._assert(torch.sum(y) > 0, "message")` always breaks the graph.
2. `torch._assert(torch.sum(y) > 0, "message")` breaks the graph while running `example_value = get_fake_value(proxy.node, tx)` [trace](https://gist.github.com/ymwangg/da2631ab88200b430f27d242a6e1914e) which eventually triggers `DataDependentOutputException` [here](https://github.com/pytorch/pytorch/blob/master/torch/_subclasses/fake_tensor.py).

So maybe one way to fix it is to add an extra `get_fake_value` to break the graph like this:
```diff
diff --git a/torch/_dynamo/symbolic_convert.py b/torch/_dynamo/symbolic_convert.py
index ea72840343d..6d45fb96834 100644
--- a/torch/_dynamo/symbolic_convert.py
+++ b/torch/_dynamo/symbolic_convert.py
@@ -248,11 +248,12 @@ def generic_jump(truth_fn: typing.Callable[[object], bool], push: bool):
 
             # Manually insert torch._assert instead of python assert and jump over
             # assert related instructions as we don't need them anymore.
-            self.output.create_proxy(
+            proxy = self.output.create_proxy(
                 "call_function",
                 torch._assert,
                 *proxy_args_kwargs((value, error_msg), {}),
             )
+            torch._dynamo.utils.get_fake_value(proxy.node, self)
             self.jump(inst)
             return
```
But doing so seems to be the same as reverting [#88246](https://github.com/pytorch/pytorch/issues/88246).

**Comment by ezyang** [comment]
@tugsbayasgalan we discussed this at the off site last week. Once we propagate assert all the way to inductor, we can avoid erroring on it when we trace it with make_fx. Does that make sense? Do you think you can also help with the inductor side integration?

**Comment by ymwangg** [comment]
Yes, that sounds reasonable and it appears that the original purpose of this PR is to let the backend compiler handle `torch._assert`. I'm willing to work on inductor side integration and additional technical details would be very helpful.

**Comment by ezyang** [comment]
I'll let @tugsbayasgalan coordinate. There are some delicate technical details that we haven't completely worked out yet.

**Comment by dnlby96** [comment]
Hi there, I'm running into the same issue. Are there any updates?

**Comment by bdhirsh** [comment]
The repro above now passes for me (probably because [this](https://github.com/pytorch/pytorch/pull/100101) PR landed recently, which adds support for asserts in the compiled graph)

**Comment by ymwangg** [comment]
Yeah, the repro passes with latest pytorch master. Thanks for the great work! I'm closing it now.
@BrettRyland your issue seems to be specific to aot_ts_nvfuser, please open a separate issue as needed.
