### ISSUE TITLE
ImportError: workspace/torch_extendsions/fused_adam/fused_adam.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zhenzi0322** [pytorch/pytorch#96589]
### 🐛 Describe the bug

```
/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py:428: UserWarning: Error handling mechanism for deadlock detection is uninitialized. Skipping check.
  rank_zero_warn("Error handling mechanism for deadlock detection is uninitialized. Skipping check.")
Traceback (most recent call last):
  File "/mnt/data/long/finetune_taiyi_stable_diffusion/finetune.py", line 210, in <module>
    trainer.fit(model, datamoule, ckpt_path=args.load_ckpt_path)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1147, in _run
    self.strategy.setup(self)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 376, in setup
    self.init_deepspeed()
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 490, in init_deepspeed
    self._initialize_deepspeed_train(model)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 523, in _initialize_deepspeed_train
    optimizer, lr_scheduler, _ = self._init_optimizers()
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/strategies/deepspeed.py", line 496, in _init_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = _init_optimizers_and_lr_schedulers(self.lightning_module)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 179, in _init_optimizers_and_lr_schedulers
    optim_conf = model.trainer._call_lightning_module_hook("configure_optimizers", pl_module=model)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/mnt/data/long/finetune_taiyi_stable_diffusion/finetune.py", line 125, in configure_optimizers
    return configure_optimizers(self)
  File "/mnt/data/long/finetune_taiyi_stable_diffusion/fengshen/models/model_utils.py", line 69, in configure_optimizers
    optimizer = FusedAdam(
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 73, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 485, in load
    return self.jit_load(verbose)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 520, in jit_load
    op_module = load(
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1534, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/kemove/anaconda3/envs/finetune_taiyi_stable_diffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1936, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: workspace/torch_extendsions/fused_adam/fused_adam.so: cannot open shared object file: No such file or directory
```

### Versions

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla P40
GPU 1: Tesla P40
GPU 2: Tesla P40
GPU 3: Tesla P40

Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
架构：                           x86_64
CPU 运行模式：                   32-bit, 64-bit
字节序：                         Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU:                             48
在线 CPU 列表：                  0-47
每个核的线程数：                 2
每个座的核数：                   12
座：                             2
NUMA 节点：                      2
厂商 ID：                        GenuineIntel
CPU 系列：                       6
型号：                           63
型号名称：                       Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
步进：                           2
CPU MHz：                        1200.000
CPU 最大 MHz：                   3300.0000
CPU 最小 MHz：                   1200.0000
BogoMIPS：                       5000.06
虚拟化：                         VT-x
L1d 缓存：                       768 KiB
L1i 缓存：                       768 KiB
L2 缓存：                        6 MiB
L3 缓存：                        60 MiB
NUMA 节点0 CPU：                 0-11,24-35
NUMA 节点1 CPU：                 12-23,36-47
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
标记：                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear flush_l1d

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] pytorch-lightning==1.7.5
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchmetrics==0.11.3
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl    defaults
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py39h7f8727e_0    defaults
[conda] mkl_fft                   1.3.1            py39hd3c417c_0    defaults
[conda] mkl_random                1.2.2            py39h51133e4_0    defaults
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] numpy-base                1.23.5           py39h31eccc5_0    defaults
[conda] pytorch                   1.13.1          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-cuda              11.6                 h867d48c_0    pytorch
[conda] pytorch-lightning         1.7.5                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torchaudio                0.13.1               py39_cu116    pytorch
[conda] torchmetrics              0.11.3                   pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi

**Comment by malfet** [comment]
Why do you think it is a PyTorch problem?
I.e. you have some module called `torch_extendsions`, which to the best of my knowledge is not shipped with PyTorch, that failed to recompile, but nothing in the log you've posted indicates that this might be due to some problem in PyTorch.

Closing for now. Please use https://discuss.pytorch.org to ask general questions on how PyTorch can be used. If you believe that missing shared library is due to pytorch problems, please do not hesitate to open another issue with details on the build failure.
