### ISSUE TITLE
[MPS] pinverse dtype error

### ISSUE THREAD

**Issue by tT0NG** [pytorch/pytorch#96773]
I am trying to do the pinverse on MPS machine. 

I am setting the variable as:
```
debug = torch.Tensor([[1,2,3],[4,5,6]]).to(device=torch.device('mps')).to(dtype=torch.float32)
```
confirming variable is loaded in mps:
````
>> debug.dtype
torch.float32
>> debug
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='mps:0')
````

Calling the following command would give me error:
```
>> debug_pinv = debug.pinverse()

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

### Versions

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torchaudio                0.13.1                   pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi

### does this mean the pinverse's implementation is fixed on float64 for MPS? 

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
I don't think MPS supports `linalg.linalg.pinv` at the moment, but error is not very helpful.

**Comment by hvaara** [comment]
Not getting the error anymore. `aten::linalg_svd` is falling back to the CPU, which might affect performance.

```python
import torch
x_cpu = torch.tensor([[1,2,3],[4,5,6]], device='cpu', dtype=torch.float32)
x_mps = x_cpu.detach().clone().to('mps')
print(f"{x_cpu.dtype = }")
print(f"{x_cpu.dtype == x_mps.dtype = }")
print(f"{x_cpu = }")
print(f"{(x_cpu == x_mps.cpu()).all() = }")
pinv_cpu = x_cpu.pinverse()
pinv_mps = x_mps.pinverse()
print(f"{pinv_cpu = }")
print(f"{((pinv_cpu - pinv_mps.cpu()).abs() > 1e-7).sum() = }")

# Ouput:
# x_cpu.dtype = torch.float32
# x_cpu.dtype == x_mps.dtype = True
# x_cpu = tensor([[1., 2., 3.],
#         [4., 5., 6.]])
# (x_cpu == x_mps.cpu()).all() = tensor(True)
# <stdin>:1: UserWarning: The operator 'aten::linalg_svd' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/hvaara/dev/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
#   pinv_mps = x_mps.pinverse()
# pinv_cpu = tensor([[-0.9444,  0.4444],
#         [-0.1111,  0.1111],
#         [ 0.7222, -0.2222]])
# ((pinv_cpu - pinv_mps.cpu()).abs() > 1e-7).sum() = tensor(0)
```

**Comment by jhavukainen** [comment]
As mentioned above there is no longer issues with missing pinverse dtype error and we have different issues tracking the linalg_svd and other missing op implementations. Closing this issue.
