### ISSUE TITLE
[dynamo] support cond with multiple args

### ISSUE THREAD

**Issue by ydwu4** [pytorch/pytorch#96777]
### 🚀 The feature, motivation and pitch

Currentlly, when we export the following code:
```python
import torch
import torch._dynamo as torchdynamo

from functorch.experimental.control_flow import cond

class Module(torch.nn.Module):
    def forward(self, pred, x, y):
        def true_fn(x):
            return x[0] + x[1]

        def false_fn(x):
            return x[0] - x[1]

        return cond(pred, true_fn, false_fn, [x, y])

mod = Module()
x = torch.randn(2, 2)
y = torch.randn(2, 2)
out_graph, _ = torchdynamo.export(mod, torch.tensor(True), x, y)
out_graph.print_readable()
# also errors for optimize
# torchdynamo.optimize(nopython=True)(mod)(torch.tensor(True), x, y)
```
produces error below:
```
[2023-03-14 21:31:38,601] torch._dynamo.symbolic_convert: [WARNING] test_dynamo/test_multi_arg_cond.py <function true_fn at 0x7f9244527f70> [TensorVariable(), TensorVariable()] {} too many positional arguments
Traceback (most recent call last):
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1968, in inline_call_
    sub_locals, closure_cells = func.bind_args(parent, args, kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 433, in bind_args
    bound = inspect.signature(func).bind(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/inspect.py", line 2958, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_dynamo/test_multi_arg_cond.py", line 19, in <module>
    out_graph, _ = torchdynamo.export(mod, torch.tensor(True), x, y)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 706, in export
    result_traced = opt_f(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 118, in __call__
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 254, in _fn
    return fn(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 391, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 105, in _fn
    return fn(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 263, in _convert_frame_assert
    return _compile(
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 326, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 313, in transform
    tracer.run()
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1842, in run
    super().run()
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in run
    and self.step()
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 561, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 346, in wrapper
    return inner_fn(self, inst)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 994, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 494, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 928, in call_function
    ) = speculate_branch(True)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 918, in speculate_branch
    return speculate_subgraph(
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 854, in speculate_subgraph
    output = f.call_function(tx, args, {})
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py", line 98, in call_function
    return tx.inline_user_function_return(
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 530, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1935, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1973, in inline_call_
    unimplemented("arg mismatch inlining")
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: arg mismatch inlining

from user code:
   File "test_dynamo/test_multi_arg_cond.py", line 14, in forward
    return cond(pred, true_fn, false_fn, [x, y])

Set torch._dynamo.config.verbose=True or TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ydwu4** [comment]
```python
import torch
import torch._dynamo as torchdynamo
from functorch.experimental.control_flow import cond

class Module2(torch.nn.Module):
    def forward(self, pred, x, y):
        def true_fn(x):
            return x + y

        def false_fn(x, y):
            return x - y

        return cond(pred, true_fn, false_fn, x, y)

mod = Module()
x = torch.randn(2, 2)
y = torch.randn(2, 2)
out_graph, _ = torchdynamo.export(mod, torch.tensor(True), x, y)
out_graph.print_readable()
```
produces following:
``` python
Traceback (most recent call last):
  File "../test_dynamo/test_multi_arg_cond.py", line 30, in <module>
    out_graph, _ = torchdynamo.export(mod, torch.tensor(True), x, y)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 687, in export
    result_traced = opt_f(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 99, in __call__
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 235, in _fn
    return fn(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 372, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 105, in _fn
    return fn(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 263, in _convert_frame_assert
    return _compile(
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 325, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 312, in transform
    tracer.run()
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1842, in run
    super().run()
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in run
    and self.step()
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 561, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 346, in wrapper
    return inner_fn(self, inst)
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 994, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 494, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/scratch/yidi/work/tc/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 892, in call_function
    assert len(args) == 4
AssertionError: 

from user code:
   File "../test_dynamo/test_multi_arg_cond.py", line 24, in forward
    return cond(pred, true_fn, false_fn, x, y)

Set torch._dynamo.config.verbose=True or TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

**Comment by ydwu4** [comment]
The ideal interface of cond would be:
'''python
def cond(pred, true_fn, false_fn, *operands):
    if pred:
        return true_fn(*operands)
    else:
        return false_fn(*operands)
'''
where operands can be
