### ISSUE TITLE
SpatialFullConvolution loaded from Lua doesn't have finput attribute

### ISSUE THREAD

**Issue by KangolHsu** [pytorch/pytorch#968]
I am new to python，when i solve the promblem with the help below：
https://github.com/pytorch/pytorch/issues/897

I find some confusion in the code：
https://github.com/pytorch/pytorch/blob/master/torch/legacy/nn/JoinTable.py#L7

I set ‘dimension=1；self.dimension = dimension’，it seem ok for me，but i don’t kown how the value of ’dimension‘ was initialled. 

Thank you !

**Comment by KangolHsu** [comment]
I already Konw it comes from
 'module = JoinTable(dimension, nInputDims)'
But when I convert the model  to pytorch , error appears:

Traceback (most recent call last):
  File "test.py", line 173, in <module>
    G_net_f       =generator.forward(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Module.py", line 33, in forward
    return self.updateOutput(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Sequential.py", line 36, in updateOutput
    currentOutput = module.updateOutput(currentOutput)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/JoinTable.py", line 37, in updateOutput
    self.output.narrow(dim, offset, currentOutput.size(dim)).copy_(currentOutput)
RuntimeError: inconsistent tensor size at /home/lxl/pytorch-master/torch/lib/TH/generic/THTensorCopy.c:51

**Comment by KangolHsu** [comment]
I Use "generator.modules[0] = nn.JoinTable(1)",it was fine ,but  error again:

Traceback (most recent call last):
  File "test.py", line 171, in <module>
    G_net_f       =generator.forward(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Module.py", line 33, in forward
    return self.updateOutput(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Sequential.py", line 36, in updateOutput
    currentOutput = module.updateOutput(currentOutput)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/SpatialFullConvolution.py", line 96, in updateOutput
    if self.finput is None:
AttributeError: 'SpatialFullConvolution' object has no attribute 'finput'

**Comment by apaszke** [comment]
How old is the Lua model file you're trying to import? Can you please try to load it in Lua, save again, and load it in PyTorch? Also, please update PyTorch to the newest version.

**Comment by KangolHsu** [comment]
the version i use：
Metadata-Version: 1.0
Name: torch
Version: 0.1.9

I Build from source last week
