### ISSUE TITLE
gdb stack traces for libtorch are missing debug symbols

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#9684]
Example:
```
(gdb) up
#1  0x00007fffd7130d80 in torch::barf(char const*, ...) () from /data/users/zdevito/pytorch/torch/lib/libtorch.so.1
(gdb)
#2  0x00007fffd70e237d in torch::jit::IValue::toTensor() && [clone .part.171] () from /data/users/zdevito/pytorch/torch/lib/libtorch.so.1
(gdb)
#3  0x00007fffd745e975 in torch::jit::GraphExecutorImpl::run(torch::jit::variable_tensor_list) () from /data/users/zdevito/pytorch/torch/lib/libtorch.so.1
(gdb)
#4  0x00007fffd7459c37 in torch::jit::GraphExecutor::run(torch::jit::variable_tensor_list&&) () from /data/users/zdevito/pytorch/torch/lib/libtorch.so.1
(gdb)
#5  0x00007fffe7c1bf0c in torch::jit::script::Method::run (inputs=..., this=0x1a77700) at /data/users/zdevito/pytorch/torch/csrc/jit/script/module.h:60
60	    return get_executor().run(std::move(inputs));
(gdb)
#6  torch::jit::script::runMethodFromPython (m=..., args=...) at torch/csrc/jit/script/init.cpp:359
359	  auto outputs = m.run(std::move(inputs));
```
Note that files like `script/init.cpp` which are still part of _C.so have debug symbols. This makes it extremely hard to debug anything.

**Comment by t-vi** [comment]
Is this still a problem? As far as I can tell, with DEBUG=1 I get source files and line numbers for libtorch.

**Comment by ezyang** [comment]
@zdevito All we need to do is edit setup.py with the extra knob:

```
if DEBUG:
    if IS_WINDOWS:
        extra_link_args.append('/DEBUG:FULL')
    else:
        extra_compile_args += ['-O0', '-g']
        extra_link_args += ['-O0', '-g']
```

Just need a way of saying "DEBUG and OPT".

**Comment by zdevito** [comment]
This knob exists now: https://github.com/pytorch/pytorch/blob/master/setup.py#L8
