### ISSUE TITLE
[Inductor] Softmax + Dropout fused kernel fails with illegal memory access

### ISSUE THREAD

**Issue by parthmannan** [pytorch/pytorch#96978]
### 🐛 Describe the bug

Triton generated kernel fails with `illegal memory access` error with a specific input size. Same code works for slightly different input size.

### Error logs

```
Traceback (most recent call last):
  File "/scratch/mojitos/debug_scripts/debug_softmax_in_mha.py", line 43, in <module>
    outputs = network_fn(*input_tensors)
  File "/opt/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 99, in __call__
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 235, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/mojitos/debug_scripts/debug_softmax_in_mha.py", line 10, in forward
    def forward(self, out):
  File "/opt/pytorch/pytorch/torch/_dynamo/eval_frame.py", line 235, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 3001, in forward
    return compiled_fn(full_args)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 1175, in g
    return f(*args)
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 2056, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 1200, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 1175, in g
    return f(*args)
  File "/opt/pytorch/pytorch/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 2294, in forward
    fw_outs = call_func_with_args(
  File "/opt/pytorch/pytorch/torch/_functorch/aot_autograd.py", line 1200, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/opt/pytorch/pytorch/torch/_inductor/compile_fx.py", line 256, in run
    return model(new_inputs)
  File "/tmp/torchinductor_me/qu/cquebfqvgm4ohe6hy53nu75gly7e4yn6tsivaokokv6gecaxk73q.py", line 109, in call
    triton_fused__softmax__to_copy_gt_mul_philox_rand_like_0.run(primals_1, seed_cuda_0, buf2, buf3, 524288, 8192, grid=grid(524288), stream=stream0)
  File "/opt/pytorch/pytorch/torch/_inductor/triton_ops/autotune.py", line 203, in run
    return launcher(
  File "<string>", line 6, in launcher
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
```

### Minified repro

```
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self, config):
        super(Net, self).__init__()
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, out):
        out = self.softmax(out)    
        out = F.dropout(out, p=0.1, training=True)

        return out

def generate_io_tensor(net):
    input_tensors = []
    for idx, shape in enumerate(input_shapes):
        tensor = torch.rand(shape, dtype=torch.float16, requires_grad=True, device='cuda')
        input_tensors.append(tensor)
    
    target_tensor = net(*input_tensors)
    
    return input_tensors, target_tensor

config = {'seq_len': 8192, 'num_attn_heads':16, 'batch_size': 4} #Fails
#config = {'seq_len': 8192, 'num_attn_heads':16, 'batch_size': 2} #Works

net = Net(config)
net.cuda()
net = net.half()
                   
network_fn = torch.compile(net)

bench_iters = 5
input_shapes = [(config['batch_size'], config['num_attn_heads'], config['seq_len'], config['seq_len'])]

for idx in range(bench_iters):

    input_tensors, target_tensor = generate_io_tensor(net)
    for inp_tensor in input_tensors:
        inp_tensor.grad = None
    
    outputs = network_fn(*input_tensors)
    outputs.backward(target_tensor)
```

### Versions

PyTorch version: 2.1.0a0+git731bb6e
Triton version: 2.0.0

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by Chillee** [comment]
Is this just an OOM?

**Comment by parthmannan** [comment]
Runs fine without `torch.compile` so not the traditional OOM I think.

**Comment by ngimel** [comment]
Yeah support for large tensor (2**32 elements or more) is spotty so far, will be fixed soon
