### ISSUE TITLE
Get error: "tuple index with non-constant index" when exporting a model to ONNX format

### ISSUE THREAD

**Issue by feiyuhuahuo** [pytorch/pytorch#96996]
### 🐛 Describe the bug

I’m trying to convert a model to onnx format. A function was wrapped by torch.jit.script() in the model forward method. No other torch.jit.script() was uesd. The forward method is following:
```
   def forward(self, img):
        img = self.onnx_trans(img)
        x = self.backbone(img)
        x = self.neck(x)
        mask_feat_pred = self.mask_feat_head(x[self.mask_feat_head.start_level:self.mask_feat_head.end_level + 1])
        cate_preds, kernel_preds = self.bbox_head(x)
        get_seg = torch.jit.script(get_seg_scripted)
        seg_result = get_seg(cate_preds, kernel_preds, mask_feat_pred)
        print(seg_result)
        return seg_result
```
I use the following code to export the model:
```
    cfg = Custom_light_res50(mode='detect')
    cfg.print_cfg()
    model = SOLOv2(cfg).cuda()
    model.load_state_dict(torch.load(cfg.val_weight), strict=True)
    model.eval()

    input_size = (512, 512)
    input_img = cv2.imread('detect_imgs/test1.bmp', cv2.IMREAD_COLOR)
    input_img = cv2.resize(input_img, input_size)
    input_img = torch.from_numpy(input_img).cuda()

    torch.onnx.export(model,
                      input_img,
                      'seg.onnx',
                      input_names=['seg'],
                      output_names=['output'],
                      verbose=False,
                      opset_version=14)

```
I can get the correct value of variable `seg_result`. But still I get the error:
```
Traceback (most recent call last):
  File "/home/feiyu/SOLOv2_minimal/ttt.py", line 99, in <module>
    torch.onnx.export(model,
  File "/home/feiyu/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/feiyu/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/feiyu/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/home/feiyu/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 582, in _optimize_graph
    _C._jit_pass_lower_all_tuples(graph)
RuntimeError: tuple index with non-constant index
```
Did I do anything wrong? Since I can already get the correct value, which means the forward computation is totally right. Why there’s still an error? Besides, the variable `seg_result` is the final result that I want to get. It's structure: `[[torch.Tensor, torch.Tensor, torch.Tensor]]`. No other procedure after `seg_result` returned.

### Versions

Collecting environment information...
PyTorch version: 1.13.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          20
On-line CPU(s) list:             0-19
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
CPU family:                      6
Model:                           165
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       1
Stepping:                        5
CPU max MHz:                     5300.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7399.70
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       320 KiB (10 instances)
L1i cache:                       320 KiB (10 instances)
L2 cache:                        2.5 MiB (10 instances)
L3 cache:                        20 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-19
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==1.13.1+cu116
[pip3] torchvision==0.14.1+cu116
[conda] Could not collect

**Comment by thiagocrepaldi** [comment]
What do you mean by "I can get the correct value of variable `seg_result`"? Does it mean that during `torch.onnx.export`, `reg_result` is executed and printed?

Without a full repro script, I would guess the problem is related to `torch.jit.script(get_seg_scripted)`. `get_seg_scripted` may 1) not have all arguments type hinted (which makes  torch.jit.script` to assume all arguments are of `torch.Tensor` type or 2) you are hitting a torchscript limitation as listed [here](https://pytorch.org/docs/stable/jit.html#known-issues).

For 1), add type hints to all arguments in the `get_seg_scripted()` signature. For 2), a good strategy is [mixing tracing and scripting](https://pytorch.org/docs/stable/jit.html#mixing-tracing-and-scripting) to minimize the amount of code that needs to be scripted. `torch.jit.script` is super limited, so the lesser scipted code, the better

**Comment by feiyuhuahuo** [comment]
The whole model is:
```
class SOLOv2(nn.Module):
    def __init__(self, cfg):
        super(SOLOv2, self).__init__()
        self.backbone = ResNet(depth=cfg.resnet_depth, frozen_stages=1)
        self.neck = FPN(cfg.fpn_in_c)
        self.mask_feat_head = MaskFeatHead(num_classes=cfg.mask_feat_num_classes)

        self.bbox_head = SOLOv2Head(num_classes=cfg.num_classes, stacked_convs=cfg.head_stacked_convs,
                                    scale_ranges=cfg.head_scale_ranges, seg_feat_channels=cfg.head_seg_feat_c,
                                    ins_out_channels=cfg.head_ins_out_c, in_detect=(cfg.mode == 'detect'))
        self.postprocess_cfg = cfg.postprocess_para

        if cfg.mode == 'train':
            self.init_weights(pretrained=cfg.pretrained)

        self.onnx_trans = cfg.onnx_trans
        self.onnx_shape = cfg.onnx_shape

    def init_weights(self, pretrained=None):
        if pretrained is not None:
            print('load model from: {}'.format(pretrained))

        self.backbone.init_weights(pretrained=pretrained)
        self.neck.init_weights()
        self.mask_feat_head.init_weights()
        self.bbox_head.init_weights()

    def forward(self, img):
        img = self.onnx_trans(img)
        x = self.backbone(img)
        x = self.neck(x)
        mask_feat_pred = self.mask_feat_head(x[self.mask_feat_head.start_level:self.mask_feat_head.end_level + 1])
        cate_preds, kernel_preds = self.bbox_head(x)
        get_seg = torch.jit.script(get_seg_scripted)
        seg_result = get_seg(cate_preds, kernel_preds, mask_feat_pred)
        print(seg_result)
        return seg_result
```
The `get_seg_scripted` function is:
```
def get_seg_scripted(cate_list: list[torch.Tensor], kernel_list: list[torch.Tensor], seg_pred: torch.Tensor):
    num_grids = (40, 36, 24, 16, 12)
    strides_set = (8, 8, 16, 32, 32)
    score_thre = 0.1
    mask_thre = 0.5
    nms_pre = 500
    update_thre = 0.05
    max_ins = 100

    cate_num = 12
    head_ins_out_c = 128
    resize_h = 512
    resize_w = 512

    num_levels = len(cate_list)
    featmap_size = seg_pred.size()[-2:]
    feat_size = [int(featmap_size[0]), int(featmap_size[1])]
    non_tensor = [torch.tensor([0.], device='cuda'), torch.tensor([0.], device='cuda'),
                  torch.tensor([0.], device='cuda')]
    result_batch_list = [[] for _ in range(seg_pred.shape[0])]
    for j in range(seg_pred.shape[0]):
        cate_list = [cate_list[i][j].view(-1, cate_num).detach() for i in range(num_levels)]
        seg_preds = seg_pred[j, ...].unsqueeze(0)
        kernel_list = [kernel_list[i][j].permute(1, 2, 0).view(-1, head_ins_out_c).detach()
                       for i in range(num_levels)]

        cate_preds = torch.cat(cate_list, dim=0)
        kernel_preds = torch.cat(kernel_list, dim=0)

        # process.
        inds = (cate_preds > score_thre)

        cate_scores = cate_preds[inds]
        if cate_scores.shape[0] == 0:
            result_batch_list[j] = non_tensor
            continue

        # cate_labels & kernel_preds
        inds = inds.nonzero()
        cate_labels = inds[:, 1]
        kernel_preds = kernel_preds[inds[:, 0]]

        # trans vector.
        size_trans = torch.tensor(num_grids, device=cate_labels.device, dtype=cate_labels.dtype).pow(2).cumsum(0)
        # size_trans = cate_labels.new_tensor(num_grids).pow(2).cumsum(0)
        strides = kernel_preds.new_ones(size_trans[-1])

        strides[:size_trans[0]] *= strides_set[0]
        for ind_ in range(1, len(num_grids)):
            strides[size_trans[ind_ - 1]:size_trans[ind_]] *= strides_set[ind_]
        strides = strides[inds[:, 0]]

        # mask encoding.
        I, N = kernel_preds.shape
        kernel_preds = kernel_preds.view(I, N, 1, 1)
        seg_preds = F.conv2d(seg_preds, kernel_preds, stride=1).squeeze(0).sigmoid()

        # mask.
        seg_masks = seg_preds > mask_thre
        sum_masks = seg_masks.sum((1, 2)).float()

        # filter.
        keep = sum_masks > strides
        if keep.sum() == 0:
            result_batch_list[j] = non_tensor
            continue

        seg_masks = seg_masks[keep, ...]
        seg_preds = seg_preds[keep, ...]
        sum_masks = sum_masks[keep]
        cate_scores = cate_scores[keep]
        cate_labels = cate_labels[keep]

        # maskness.
        seg_scores = (seg_preds * seg_masks.float()).sum((1, 2)) / sum_masks
        cate_scores *= seg_scores

        # sort and keep top nms_pre
        sort_inds = torch.argsort(cate_scores, descending=True)
        if sort_inds.shape[0] > nms_pre:
            sort_inds = sort_inds[:nms_pre]
        seg_masks = seg_masks[sort_inds, :, :]
        seg_preds = seg_preds[sort_inds, :, :]
        sum_masks = sum_masks[sort_inds]
        cate_scores = cate_scores[sort_inds]
        cate_labels = cate_labels[sort_inds]

        # Matrix NMS
        cate_scores = matrix_nms(seg_masks, cate_labels, cate_scores, sum_masks=sum_masks)

        # filter.
        keep = cate_scores >= update_thre
        if keep.sum() == 0:
            result_batch_list[j] = non_tensor
            continue

        seg_preds = seg_preds[keep, :, :]
        cate_scores = cate_scores[keep]
        cate_labels = cate_labels[keep]

        # sort and keep top_k
        sort_inds = torch.argsort(cate_scores, descending=True)
        if sort_inds.shape[0] > max_ins:
            sort_inds = sort_inds[:max_ins]
        seg_preds = seg_preds[sort_inds, :, :]
        cate_scores = cate_scores[sort_inds]
        cate_labels = cate_labels[sort_inds]

        s1 = int(feat_size[0] * 4)
        s2 = int(feat_size[1] * 4)
        seg_masks = F.interpolate(seg_preds.unsqueeze(0), size=[s1, s2], mode='bilinear')
        seg_masks = seg_masks[:, :, :resize_h, :resize_w].squeeze(0)
        seg_masks = seg_masks > mask_thre

        one_result = [seg_masks, cate_labels, cate_scores]
        result_batch_list[j] = one_result

    return result_batch_list
```
So all arguments are type hinted. And, here I do use  `mixing tracing and scripting` right? The whole model is traced except the `get_seg_scripted` function, which is scripted. And yes, I printed the `seg_result` during `torch.onnx.export`. Its value is correct, does this mean that there's no error with my code?

**Comment by thiagocrepaldi** [comment]
Hi @feiyuhuahuo this is still not the full repro. Please provide a code snippet with all imports, classes, functions, etc so that I can repro the issue on my machine

`Custom_light_res50`, `SOLOv2Head` and `ResNet` are undefined on the example above, for example. Please create a python script, validate it runs locally and only then attach to this issue for further investigation.

**Comment by feiyuhuahuo** [comment]
Hi，the whole project is here. https://github.com/feiyuhuahuo/SOLOv2_minimal/tree/dev  Just clone it,  and then use `python export2onnx.py`, it should show the bug.  The environment is described above.

**Comment by nivtri** [comment]
Hi @feiyuhuahuo , did you get any solution to this error? I am facing the same.

**Comment by feiyuhuahuo** [comment]
@nivtri  No, I still don't know how to use script mode correctly.

**Comment by feiyuhuahuo** [comment]
@nivtri   I don't know whether I use script mode correctly or it's just it's limitation.
