### ISSUE TITLE
Torch 2 regression: `torch.asarray(np.array(1))` fail (scalar array)

### ISSUE THREAD

**Issue by Conchylicultor** [pytorch/pytorch#97021]
### 🐛 Describe the bug

It looks like `torch` 2 cannot convert `float` to `int` when the input is a scalar `np.ndarray`.

```python
torch.asarray(1., dtype=torch.int32)  # Works
torch.asarray(np.array(1.), dtype=torch.int32)  # Fail
torch.asarray(np.array([1.]), dtype=torch.int32)  # Works
```

Traceback

```
>>> torch.asarray(np.asarray(1.), dtype=torch.int32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

### Versions

2.0.0

cc @ezyang @gchanan @zou3519 @mruberry @rgommers

**Comment by cpuhrsch** [comment]
@Conchylicultor - is this something that used to work and doesn't work anymore now?

**Comment by Conchylicultor** [comment]
Yes, it was working before torch 2.

**Comment by Conchylicultor** [comment]
Note that the `dtype=` kwargs can actually be removed. The same fail even when there's no casting:

```python
# Works
torch.asarray(1)
torch.asarray(np.array([1]))

# Fail
torch.asarray(np.array(1))
torch.asarray(np.zeros(shape=()))
```

**Comment by cpuhrsch** [comment]
I can reproduce this as well.

torch 1.13.1
```
tensor(1, dtype=torch.int32)
>>> torch.asarray(np.array(1.), dtype=torch.int32)
```

torch 2.0
```
>>> torch.asarray(np.array(1.), dtype=torch.int32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

**Comment by mruberry** [comment]
@ysiraichi Maybe this was regressed by https://github.com/pytorch/pytorch/pull/90914?

**Comment by malfet** [comment]
Reverting https://github.com/pytorch/pytorch/commit/3f64c96655289a1874b968d6bd9287eeb99a2cec indeed fixes the e problem. But fwd fix seems straightforward as well
