### ISSUE TITLE
[compile] TypeError: __init__() missing 1 required positional argument: 'parent_module'

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#97078]
### 🐛 Describe the bug

model.compile() (defaults) gives me:

```
stderr:  - 5543 - torch._dynamo.symbolic_convert - Step 1: torchdynamo start tracing forward
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
stderr:     out_code = transform_code_object(code, transform)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
stderr:     transformations(instructions, code_options)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 311, in transform
stderr:     tracer.run()
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
stderr:     super().run()
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
stderr:     and self.step()
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
stderr:     getattr(self, inst.opname)(inst)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
stderr:     return inner_fn(self, inst)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1014, in CALL_FUNCTION_KW
stderr:     self.call_function(fn, args, kwargs)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
stderr:     self.push(fn.call_function(self, args, kwargs))
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/nn_module.py", line 244, in call_function
stderr:     return tx.inline_user_function_return(
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 510, in inline_user_function_return
stderr:     result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1806, in inline_call
stderr:     return cls.inline_call_(parent, func, args, kwargs)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1862, in inline_call_
stderr:     tracer.run()
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
stderr:     and self.step()
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
stderr:     getattr(self, inst.opname)(inst)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
stderr:     return inner_fn(self, inst)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1014, in CALL_FUNCTION_KW
stderr:     self.call_function(fn, args, kwargs)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
stderr:     self.push(fn.call_function(self, args, kwargs))
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/nn_module.py", line 244, in call_function
stderr:     return tx.inline_user_function_return(
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 510, in inline_user_function_return
stderr:     result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1806, in inline_call
stderr:     return cls.inline_call_(parent, func, args, kwargs)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1862, in inline_call_
stderr:     tracer.run()
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
stderr:     and self.step()
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
stderr:     getattr(self, inst.opname)(inst)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
stderr:     return inner_fn(self, inst)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 965, in CALL_FUNCTION
stderr:     self.call_function(fn, args, {})
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
stderr:     self.push(fn.call_function(self, args, kwargs))
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/nn_module.py", line 244, in call_function
stderr:     return tx.inline_user_function_return(
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 510, in inline_user_function_return
stderr:     result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1806, in inline_call
stderr:     return cls.inline_call_(parent, func, args, kwargs)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1862, in inline_call_
stderr:     tracer.run()
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
stderr:     and self.step()
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
stderr:     getattr(self, inst.opname)(inst)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
stderr:     return inner_fn(self, inst)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 965, in CALL_FUNCTION
stderr:     self.call_function(fn, args, {})
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
stderr:     self.push(fn.call_function(self, args, kwargs))
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/nn_module.py", line 203, in call_function
stderr:     return wrap_fx_proxy(
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/builder.py", line 754, in wrap_fx_proxy
stderr:     return wrap_fx_proxy_cls(
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/builder.py", line 789, in wrap_fx_proxy_cls
stderr:     example_value = get_fake_value(proxy.node, tx)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 1143, in get_fake_value
stderr:     nnmodule = deepcopy_to_fake_tensor(nnmodule, tx.fake_mode)
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 819, in deepcopy_to_fake_tensor
stderr:     return wrap_fake_exception(lambda: copy.deepcopy(obj))
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 808, in wrap_fake_exception
stderr:     return fn()
stderr:   File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 819, in <lambda>
stderr:     return wrap_fake_exception(lambda: copy.deepcopy(obj))
stderr:   File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
stderr:     y = _reconstruct(x, memo, *rv)
stderr:   File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
stderr:     state = deepcopy(state, memo)
stderr:   File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
stderr:     y = copier(x, memo)
stderr:   File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
stderr:     y[deepcopy(key, memo)] = deepcopy(value, memo)
stderr:   File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
stderr:     y = _reconstruct(x, memo, *rv)
stderr:   File "/usr/lib/python3.8/copy.py", line 264, in _reconstruct
stderr:     y = func(*args)
stderr: TypeError: __init__() missing 1 required positional argument: 'parent_module'
```

### Versions

pt-2.0

@Chil

**Comment by ezyang** [comment]
cc'ing @eellison as this is in the deepcopy to fake logic

**Comment by eellison** [comment]
Hey @stas00, would you please give repro instructions ?

**Comment by stas00** [comment]
I don't have a simple repro at the moment. It has come from an m4 multi-modal HuggingFace project which is not ready yet for a release and thus isn't public yet. 

If you're interested, I can give access to it and then it'd be one of the tests to run - I'd give you copy-n-paste instructions if you'd like to go on this path. Other than installing pip packages everything else is automatic.

**Comment by stas00** [comment]
@msaroufim et al, I think I have a good idea for where you can get a massive amount of unit tests that will exercise `compile` in real world situations. Basically take `transformers`' test suite, change the first line of:

https://github.com/huggingface/transformers/blob/cae78c46d658a8e496a815c2ee49b9b178fb9c9a/src/transformers/trainer.py#L1560-L1561

to `if 1` so it's always true and now run:

```
pytest tests
RUN_SLOW=1 pytest tests
```
the 2 lines will run different sets of tests - the second one will run the slowest tests.

Just make sure not to uninstall `tensorflow` and `jaxlib` from python environment in order to run only pytorch tests.

That should give you a ton of reproduction scripts.

Just make sure to preinstall all the dependencies:
```
pip install -e .[dev-torch,testing]
```

**Comment by msaroufim** [comment]
@stas00 It's an interesting proposal I figure the only constraint will be cost but it might be worth doing - cc @anijain2305 @xuzhao9

**Comment by msaroufim** [comment]
Also cc @ezyang on the dynamic examples

**Comment by williamwen42** [comment]
Does this issue still happen? Can we get an updated repro?

**Comment by stas00** [comment]
@msaroufim and the Deepspeed team are working on reproducing and subsequently fixing this on the pytorch slack. 

Same goes for https://github.com/pytorch/pytorch/issues/97079

**Comment by chauhang** [comment]
@msaroufim Is there any update for this?

**Comment by tugsbayasgalan** [comment]
@msaroufim has this been resolved?

**Comment by msaroufim** [comment]
No sorry I hvaen't looked into this
