### ISSUE TITLE
[compile] `KeyError: 'HOME'` (env var missing)

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#97076]
### 🐛 Describe the bug

Trying to run `compile` on github actions via AWS instance gives me:

```
E           Traceback (most recent call last):
E             File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
E               r = call_item.fn(*call_item.args, **call_item.kwargs)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/codecache.py", line 549, in _worker_compile
E               kernel.precompile(warm_cache_only_with_cc=cc)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/triton_ops/autotune.py", line 69, in precompile
E               self.launchers = [
E             File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/triton_ops/autotune.py", line 70, in <listcomp>
E               self._precompile_config(c, warm_cache_only_with_cc)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/triton_ops/autotune.py", line 83, in _precompile_config
E               triton.compile(
E             File "/usr/local/lib/python3.8/dist-packages/triton/compiler.py", line 1587, in compile
E               so_path = make_stub(name, signature, constants)
E             File "/usr/local/lib/python3.8/dist-packages/triton/compiler.py", line 1467, in make_stub
E               so_cache_manager = CacheManager(so_cache_key)
E             File "/usr/local/lib/python3.8/dist-packages/triton/compiler.py", line 1317, in __init__
E               self.cache_dir = os.environ.get('TRITON_CACHE_DIR', default_cache_dir())
E             File "/usr/local/lib/python3.8/dist-packages/triton/compiler.py", line 1303, in default_cache_dir
E               return os.path.join(os.environ["HOME"], ".triton", "cache")
E             File "/usr/lib/python3.8/os.py", line 675, in __getitem__
E               raise KeyError(key) from None
E           KeyError: 'HOME'
```

I will of course set `HOME` up now, but it shouldn't crash like that. 

May be it should use `cwd` as a fallback?

### Versions

pt-2.0

@Chillee 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by msaroufim** [comment]
Is this a multitenant setup? Also curious which distro are you running, I was under the impression that most linux distros set home by default

**Comment by stas00** [comment]
this is AWS `ubuntu-latest` image.

**Comment by ezyang** [comment]
We should update triton to use pathlib or something
