### ISSUE TITLE
"Adaptive pool MPS: input sizes must be divisible by output sizes", I keep getting this error even when I try to adjust for size

### ISSUE THREAD

**Issue by genuine511** [pytorch/pytorch#97109]
### 🐛 Describe the bug

I am running a facet-pytorch library for facial recognition. I initialised the mtcnn class and passed on MPS as the device so I can run the program on that GPU for faster results. 

'''
device = torch.device("mps")
mtcnn1 = MTCNN(image_size=(160,160) device=device)
'''

The problem starts when I try to iterate though an image folder and pass it in the mtcnn i.e.
for imge, index in dataLoader:
    face, prob = mtcnn0(image, return_prob=True) 

it keeps coming up with this error:

RuntimeError: Adaptive pool MPS: input sizes must be divisible by output sizes

Can someone help please?

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

**Comment by swapniel99** [comment]
Hi, Im alsi facing the same issue. Did you find a solution for this?

**Comment by praveen-iyer** [comment]
Any updates on this? Is it likely to be a problem with pytorch itself or is it my code?

Urgently need this to work and would truly appreciate someone looking into this please.

**Comment by cha2lenger** [comment]
Have a similar problem. Any attempt to train a model with `mps` device results in the following error:
```
RuntimeError: Adaptive pool MPS: output sizes must be divisible by input sizes.
```

**Comment by BrianPark314** [comment]
same here, seems to be one of so many bugs related to mps

**Comment by abhinav-k** [comment]
seeing same error. Please help.

**Comment by freesky-edward** [comment]
I got the same error message when calling the linear training test on Mac. Much appreciated  if any workaround way.

**Comment by ahbalbaid** [comment]
I got the same error any updates ?

**Comment by kapipapi** [comment]
Python: 3.11.4
Torch: 2.0.1

```      
Python 3.11.4 (main, Aug 21 2023, 16:23:18) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> m = torch.nn.AdaptiveAvgPool2d((5, 7))
>>> m = m.to(torch.device('mps'))
>>> input = torch.randn(1, 64, 8, 9)
>>> input = input.to(torch.device("mps"))
>>> output = m(input)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kacper/.pyenv/versions/test_torch_mps/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kacper/.pyenv/versions/test_torch_mps/lib/python3.11/site-packages/torch/nn/modules/pooling.py", line 1196, in forward
    return F.adaptive_avg_pool2d(input, self.output_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kacper/.pyenv/versions/test_torch_mps/lib/python3.11/site-packages/torch/nn/functional.py", line 1214, in adaptive_avg_pool2d
    return torch._C._nn.adaptive_avg_pool2d(input, _output_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Adaptive pool MPS: input sizes must be divisible by output sizes.
>>> torch.__version__
'2.0.1'
>>> 
```

**Comment by LYLeon** [comment]
seeing the same error

**Comment by kstan79** [comment]
same error, macbook pro intel i9+amd gpu

**Comment by gangula-karthik** [comment]
issue still persists, trying to fine tune a vgg-16 model on mac

**Comment by MEXIST-1818** [comment]
I‘m also having this issue with Mac M3 pro.

**Comment by cavivie** [comment]
I‘m also having this issue with Mac M1 Air.

**Comment by rohitsainier** [comment]
locate this function im_resample and replace with below code:
it will resolve the issue 

`def imresample(img, sz):
    # Check if the tensor is on MPS device
    if img.device.type == 'mps':
        # Transfer tensor to CPU
        img_cpu = img.cpu()
        # Perform the interpolation on CPU
        im_data = interpolate(img_cpu, size=sz, mode="area")
        # Transfer the result back to MPS device
        im_data = im_data.to('mps')
    else:
        # If not on MPS, proceed as usual
        im_data = interpolate(img, size=sz, mode="area")
    return im_data`
