### ISSUE TITLE
[dynamo+XLA] lowering error with Bert model and multi-batch inputs

### ISSUE THREAD

**Issue by jsheng-jian** [pytorch/pytorch#97121]
### 🐛 Describe the bug

```
torch: 2.0.0+cu117
torch_xla: 2.0
```
I tested `torch.compile` with `aot_torchxla_trace_once` backend and met the following error with `Bert` model and input `(2,512)`. I can run same input size with eager mode and inductor backend.
```
batch_size: 2, seq_len: 512
Traceback (most recent call last):
  File "reproduce.py", line 23, in <module>
    outputs = model(**input_dict)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 1359, in forward
    outputs = self.bert(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 992, in forward
    extended_attention_mask: torch.Tensor = self.get_extended_attention_mask(attention_mask, input_shape)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 992, in <graph break in forward>
    extended_attention_mask: torch.Tensor = self.get_extended_attention_mask(attention_mask, input_shape)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2819, in forward
    return compiled_fn(full_args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1222, in g
    return f(*args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1898, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1247, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1222, in g
    return f(*args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_dynamo/backends/torchxla.py", line 24, in fwd
    compiled_graph = bridge.extract_compiled_graph(model, args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch_xla/core/dynamo_bridge.py", line 207, in extract_compiled_graph
    xm.mark_step()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 949, in mark_step
    torch_xla._XLAC._xla_step_marker(
RuntimeError: Error while lowering: [] aten::as_strided, xla_shape=s64[2,512]{1,0}, size=(2, 512), stride=(512, 1), storage_offset=0
Error: /pytorch/xla/torch_xla/csrc/ops/as_strided.cpp:24 : Check failed: storage_offset + slice_size <= input_element_count (1024 vs. 512)
```
reproduce script:
```
import torch
import torch_xla.core.xla_model as xm
import transformers
import os

os.environ['GPU_NUM_DEVICES'] = '1'
device = xm.xla_device()
model = transformers.BertForMaskedLM.from_pretrained('bert-base-uncased')
model.to(device)
model.eval()
model = torch.compile(model, backend='aot_torchxla_trace_once')

for batch_size in [1,2,4]:
    for seq_len in [64,128,256,512]:
        print(f'batch_size: {batch_size}, seq_len: {seq_len}')
        input_dict = {
            'input_ids':
                torch.ones((batch_size, seq_len)).to(torch.int64).to(device),
            'attention_mask':
                torch.ones((batch_size, seq_len)).to(torch.int64).to(device),
        }
        with torch.no_grad():
            outputs = model(**input_dict)
            xm.mark_step()

print('Done')
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1031-aws-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A10G
GPU 1: NVIDIA A10G
GPU 2: NVIDIA A10G
GPU 3: NVIDIA A10G

Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          48
On-line CPU(s) list:             0-47
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7R32
Stepping:                        0
CPU MHz:                         2800.000
BogoMIPS:                        5600.00
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        12 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-47
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save rdpid

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] pytorch-triton==2.1.0+2c32f43999
[pip3] torch==2.0.0
[pip3] torch-model-archiver==0.7.1
[pip3] torch-xla==2.0
[pip3] torchaudio==2.0.1
[pip3] torchserve==0.7.1
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] No relevant packages

cc @bdhirsh @ezyang @soumith @msaroufim @wconstab @ngimel

**Comment by Chillee** [comment]
@bdhirsh Do you know if anybody is maintaining this backend?

**Comment by wconstab** [comment]
i think aot_ is the training backend that is WIP and there is another one that is stable for inference.  I think we can assign this to the torch-xla team unless @bdhirsh has a line of sight on that as_strided backtrace and wants to keep it.

**Comment by alanwaketan** [comment]
@jsheng-jian It looks like you are doing inference. Can you try 'torchxla_trace_once' backend to see if it works? Here is the dynamo user guide for XLA: https://github.com/pytorch/xla/blob/r2.0/docs/dynamo.md

**Comment by jsheng-jian** [comment]
using backend `torchxla_trace_once` gives following error:
```
batch_size: 1, seq_len: 64
Traceback (most recent call last):
  File "reproduce.py", line 23, in <module>
    outputs = model(**input_dict)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 1359, in forward
    outputs = self.bert(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 911, in forward
    @add_start_docstrings_to_model_forward(BERT_INPUTS_DOCSTRING.format("batch_size, sequence_length"))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_dynamo/backends/torchxla.py", line 26, in fwd
    return compiled_graph(*args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch_xla/core/dynamo_bridge.py", line 291, in optimized_mod
    assert len(args) > 0  # can not handle no args case for now
AssertionError
```

**Comment by alanwaketan** [comment]
Sorry for not getting back to the issue on time. @jsheng-jian you have it working somehow?

**Comment by andyehrenberg** [comment]
@jsheng-jian I'm also getting that `assert len(args) > 0  # can not handle no args case for now` error. Did you figure that out?

**Comment by miladm** [comment]
following up on this issue - has this problem been resolved on your end, @jsheng-jian?
