### ISSUE TITLE
DISABLED test_dtensor_op_db_lerp_cpu_float32 (__main__.TestDTensorOpsCPU)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#97178]
Platforms: linux

Ex: https://hud.pytorch.org/pytorch/pytorch/commit/4a99b4f12b813c58a3411f4d87324cff14c1e0db#12119852183
linux cpu distributed tests

```
2023-03-20T06:39:42.0226903Z ____________ TestDTensorOpsCPU.test_dtensor_op_db_lerp_cpu_float32 _____________
2023-03-20T06:39:42.0226998Z Traceback (most recent call last):
2023-03-20T06:39:42.0227319Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 954, in wrapper
2023-03-20T06:39:42.0227448Z     self._join_threads(self.threads, fn)
2023-03-20T06:39:42.0227752Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 1074, in _join_threads
2023-03-20T06:39:42.0227870Z     cls._check_return_codes(failed_ranks, timeout, fn)
2023-03-20T06:39:42.0228167Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 1098, in _check_return_codes
2023-03-20T06:39:42.0228253Z     raise RuntimeError(msg)
2023-03-20T06:39:42.0228387Z RuntimeError: Thread 0 terminated or timed out after 300 seconds
2023-03-20T06:39:42.0228393Z 
2023-03-20T06:39:42.0228616Z ------------------------------ Captured log call -------------------------------
2023-03-20T06:39:42.0228822Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:479 Added key: store_based_barrier_key:1 to store for rank: 0
2023-03-20T06:39:42.0229026Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:479 Added key: store_based_barrier_key:1 to store for rank: 2
2023-03-20T06:39:42.0229221Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:479 Added key: store_based_barrier_key:1 to store for rank: 1
2023-03-20T06:39:42.0229562Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:513 Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2023-03-20T06:39:42.0229794Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:479 Added key: store_based_barrier_key:1 to store for rank: 3
2023-03-20T06:39:42.0230173Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:513 Rank 3: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2023-03-20T06:39:42.0230360Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:479 Added key: store_based_barrier_key:2 to store for rank: 1
2023-03-20T06:39:42.0230554Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:479 Added key: store_based_barrier_key:2 to store for rank: 3
2023-03-20T06:39:42.0230891Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:513 Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2023-03-20T06:39:42.0231230Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:513 Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2023-03-20T06:39:42.0231426Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:479 Added key: store_based_barrier_key:2 to store for rank: 0
2023-03-20T06:39:42.0231757Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:513 Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 4 nodes.
2023-03-20T06:39:42.0231955Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:479 Added key: store_based_barrier_key:2 to store for rank: 2
2023-03-20T06:39:42.0232296Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:513 Rank 2: Completed store-based barrier for key:store_based_barrier_key:2 with 4 nodes.
2023-03-20T06:39:42.0232621Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:513 Rank 1: Completed store-based barrier for key:store_based_barrier_key:2 with 4 nodes.
2023-03-20T06:39:42.0232957Z INFO     torch.distributed.distributed_c10d:distributed_c10d.py:513 Rank 3: Completed store-based barrier for key:store_based_barrier_key:2 with 4 nodes.
2023-03-20T06:39:42.0233160Z ERROR    torch.testing._internal.common_distributed:common_distributed.py:1097 Thread 0 terminated or timed out after 300 seconds
```

distributed/_tensor/test_dtensor_ops is really flaky on linux cpu distributed but not always on this test, like https://hud.pytorch.org/pytorch/pytorch/commit/16e7e5a24b92251f9e90d29573ee9e39ec296ad9#12138543586.  I am hoping that disabling this test will make it a little better the failure more consistent.

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/FAILED%20distributed%2F_tensor%2Ftest_dtensor_ops.py%3A%3ATestDTensorOpsCPU%3A%3Atest_dtensor_op_db_lerp_cpu_float32%20-%20RuntimeError%3A%20Thread%200%20terminated%20or%20timed%20out%20after%20300%20seconds)).

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by huydhn** [comment]
@wanchaol So here are the remaining issues with dtensor CPU tests that @clee2000 and I have compiled:

* This issue https://github.com/pytorch/pytorch/issues/97178
* SIGIOT, i.e. https://github.com/pytorch/pytorch/actions/runs/4471295825/jobs/7856320587
* Test timeout, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/6718e3ca7cc7a9e5ad13a98033ad25536305a70a

We will let it running in unstable for a day more, then will move it back into CI tomorrow but with dtensor test disabled.  At least there will be signals from other distributed tests I guess.

**Comment by wanchaol** [comment]
> @wanchaol So here are the remaining issues with dtensor CPU tests that @clee2000 and I have compiled:
> 
> * This issue [DISABLED test_dtensor_op_db_lerp_cpu_float32 (__main__.TestDTensorOpsCPU) #97178](https://github.com/pytorch/pytorch/issues/97178)
> * SIGIOT, i.e. https://github.com/pytorch/pytorch/actions/runs/4471295825/jobs/7856320587.
>   
>   * Another dtensor test was disabled a while ago [DISABLED test_dtensor_op_db_linalg_tensorsolve_cpu_float32 (__main__. TestDTensorOpsCPU) #94954](https://github.com/pytorch/pytorch/issues/94954) as an attempt to mitigate a SIGSEGV, may be this SIGIOT crash is also related to a specific op
> * Test timeout, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/6718e3ca7cc7a9e5ad13a98033ad25536305a70a
> 
> We will let it running in unstable for a day more, then will move it back into CI tomorrow but with dtensor test disabled. At least there will be signals from other distributed tests I guess.

Thanks @huydhn This is so weird... I did a local run for all tests and I couldn't repro both this and https://github.com/pytorch/pytorch/issues/94954, do you know why this CI run is different from local run?

I do found some test failures locally, disabling them in https://github.com/pytorch/pytorch/pull/97358

**Comment by huydhn** [comment]
After all the recent tweaks, the job looks much better now.  The last issue is job timing out when `test_dtensor_ops.py` hangs somehow (only on CPU), i.e. https://hud.pytorch.org/pytorch/pytorch/commit/95c166cd3d84a1ebab2c4cc13dce68a2cfd94802.

Here is the last test that was printed on the run above.  However, this is probably not the cause because other timeout stopped at different tests

```
distributed/_tensor/test_dtensor_ops.py::TestDTensorOpsCPU::test_dtensor_op_db_normal_in_place_cpu_float32 INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 2
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 1
INFO:torch.distributed.distributed_c10d:Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
INFO:torch.distributed.distributed_c10d:Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 3
INFO:torch.distributed.distributed_c10d:Rank 3: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
```

It looks like a deadlock or waiting forever for some sub-processes to return.  I vaguely remember a timeout of 300s is used in distributed test, not quite sure why it doesn't apply here.
