### ISSUE TITLE
Should print list of valid log names when invalid name is passed

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#97244]
### 🐛 Describe the bug

```
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/a/pytorch (85112b0d)]$ TORCH_LOGS="aot_autograd,torch.fx.experimental.symbolic_shapes" python mnist.py --epochs 1
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/mnist.py", line 4, in <module>
    import torch
  File "/data/users/ezyang/a/pytorch/torch/__init__.py", line 1645, in <module>
    _logging._init_logs()
  File "/data/users/ezyang/a/pytorch/torch/_logging/_internal.py", line 391, in _init_logs
    _update_log_state_from_env()
  File "/data/users/ezyang/a/pytorch/torch/_logging/_internal.py", line 319, in _update_log_state_from_env
    log_state = _parse_log_settings(log_setting)
  File "/data/users/ezyang/a/pytorch/torch/_logging/_internal.py", line 264, in _parse_log_settings
    raise ValueError(
ValueError: Invalid log settings: aot_autograd,torch.fx.experimental.symbolic_shapes, must be a comma separated list of registerered log or artifact names.
```

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos 

### Versions

master

**Comment by mlazos** [comment]
Yeah this is a good idea for discoverability.
