### ISSUE TITLE
[torchbench] The 20230321 nightly release breaks torchrec_dlrm model

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/pytorch#97308]
### 🐛 Describe the bug

The error exists on 20230321, and doesn't exist on 20230317.

```
$ pip install --pre torch torchvision torchtext torchaudio -f https://download.pytorch.org/whl/nightly/cu117/torch_nightly.html
$ git clone https://github.com/pytorch/benchmark.git && cd benchmark
$ python install.py torchrec_dlrm
$ python test.py -k test_torchrec_dlrm_train_cpu
E
======================================================================
ERROR: test_torchrec_dlrm_train_cpu (__main__.TestBenchmark)
----------------------------------------------------------------------
components._impl.workers.subprocess_rpc.ChildTraceException: Traceback (most recent call last):
  File "/data/xzhao9/benchmark/components/_impl/workers/subprocess_rpc.py", line 482, in _run_block
    exec(  # noqa: P204
  File "<subprocess-worker>", line 2, in <module>
  File "/data/xzhao9/benchmark/torchbenchmark/util/model.py", line 286, in invoke
    self.train()
  File "/data/xzhao9/benchmark/torchbenchmark/models/torchrec_dlrm/__init__.py", line 129, in train
    self.train_pipeline.progress(self.iterator)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/distributed/train_pipeline.py", line 554, in progress
    losses, output = cast(Tuple[torch.Tensor, Out], self._model(self._batch_i))
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/models/dlrm.py", line 895, in forward
    logits = self.model(batch.dense_features, batch.sparse_features)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/models/dlrm.py", line 573, in forward
    embedded_sparse = self.sparse_arch(sparse_features)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/models/dlrm.py", line 99, in forward
    sparse_features: KeyedTensor = self.embedding_bag_collection(features)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/distributed/train_pipeline.py", line 239, in __call__
    return self._module.compute_and_output_dist(
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/distributed/embeddingbag.py", line 629, in compute_and_output_dist
    awaitables=[
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/distributed/embeddingbag.py", line 630, in <listcomp>
    dist(lookup(features), sharding_ctx)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/distributed/embedding_lookup.py", line 313, in forward
    embeddings.append(emb_op(features))
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/distributed/batched_embedding_kernel.py", line 729, in forward
    offsets=features.offsets().long(),
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/sparse/jagged_tensor.py", line 966, in offsets
    _offsets = _maybe_compute_offsets(self._lengths, self._offsets)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/sparse/jagged_tensor.py", line 62, in _maybe_compute_offsets
    offsets = _to_offsets(lengths)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torchrec/sparse/jagged_tensor.py", line 37, in _to_offsets
    return torch.ops.fbgemm.asynchronous_complete_cumsum(lengths)
  File "/home/xzhao9/miniconda3/envs/py310/lib/python3.10/site-packages/torch/_ops.py", line 528, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: t_in must be a CUDA tensor; it is currently on device CPU

    working_dir: /tmp/tmpty6wfr70
    stdout:
        [2023-03-21] 21:19:38.078331: TIMER_SUBPROCESS_BEGIN_EXEC
        [2023-03-21] 21:19:38.118176: TIMER_SUBPROCESS_FAILED
        [2023-03-21] 21:19:38.118248: TIMER_SUBPROCESS_FINISHED
        [2023-03-21] 21:19:38.118266: TIMER_SUBPROCESS_BEGIN_READ

    stderr:


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/xzhao9/benchmark/test.py", line 88, in train_fn
    task.invoke()
  File "/data/xzhao9/benchmark/torchbenchmark/__init__.py", line 378, in invoke
    self.worker.run("""
  File "/data/xzhao9/benchmark/components/_impl/workers/subprocess_worker.py", line 148, in run
    self._run(snippet)
  File "/data/xzhao9/benchmark/components/_impl/workers/subprocess_worker.py", line 309, in _run
    subprocess_rpc.SerializedException.raise_from(
  File "/data/xzhao9/benchmark/components/_impl/workers/subprocess_rpc.py", line 458, in raise_from
    raise e from ChildTraceException(traceback_str)
RuntimeError: t_in must be a CUDA tensor; it is currently on device CPU

----------------------------------------------------------------------
Ran 1 test in 5.249s

FAILED (errors=1)
```

### Versions

Between 20230317 and 20230321 nightly releases.

**Comment by weiwangmeta** [comment]
(pytorch_issue_97308) ~/repos/benchmark $ python test.py -k test_torchrec_dlrm_train_cpu
.
----------------------------------------------------------------------
Ran 1 test in 5.883s

OK
(pytorch_issue_97308)  ~/repos/benchmark$ pip list |grep torch
pytorch-triton     2.1.0+2c32f43999
torch              2.1.0.dev20230320+cu117

The 20230320 is also ok.

**Comment by xuzhao9** [comment]
> bisect process commit [b1e8f2f](https://github.com/pytorch/pytorch/commit/b1e8f2fc11e4cb16567e19ee33e82ea925d6ffa8) is giving the following error.
> 
> File "/fsx/users/weiwangmeta/conda/envs/pytorch_issue_97308/lib/python3.10/site-packages/torchrec/distributed/embedding_types.py", line 14, in from fbgemm_gpu.split_table_batched_embeddings_ops import EmbeddingLocation File "/fsx/users/weiwangmeta/conda/envs/pytorch_issue_97308/lib/python3.10/site-packages/fbgemm_gpu/**init**.py", line 21, in from . import _fbgemm_gpu_docs # noqa: F401, E402 File "/fsx/users/weiwangmeta/conda/envs/pytorch_issue_97308/lib/python3.10/site-packages/fbgemm_gpu/_fbgemm_gpu_docs.py", line 18, in torch.ops.fbgemm.jagged_2d_to_dense, File "/fsx/users/weiwangmeta/conda/envs/pytorch_issue_97308/lib/python3.10/site-packages/torch/_ops.py", line 595, in **getattr** raise AttributeError( AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'
> 
> Need to resolve this first before continuing bisecting.

This can be fixed by installing gcc-11

**Comment by xuzhao9** [comment]
Can confirm that the problem is gone on 20230323, closed.
