### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorboardX'

### ISSUE THREAD

**Issue by hktalent** [pytorch/pytorch#97306]
### 🐛 Describe the bug

Mac OS
I do
```
conda create -n pytorch python=3.6.4
conda activate pytorch;conda init zsh
conda update --all

conda install pytorch torchvision torchaudio -c pytorch

conda install matplotlib opencv scikit-image dill easydict dlib    
conda install pytorch torchvision torchaudio -c pytorch
pip install tensorboardX
conda update --all    
conda run py3 ./run.py --input_folder /Users/51pwn/Downloads/old --output_folder /Users/51pwn/Downloads/old/output --GPU 0 --with_scratch

```
error:
```
initializing the dataloader
model weights loaded
Running Stage 1: Overall restoration
Finish Stage 1 ...


Running Stage 2: Face Detection
Finish Stage 2 ...


Running Stage 3: Face Enhancement
Finish Stage 3 ...


Running Stage 4: Blending
Finish Stage 4 ...


All the processing is done. Please check the results.

Traceback (most recent call last):
  File "/Users/51pwn/MyWork/Bringing-Old-Photos-Back-to-Life/Global/detection.py", line 178, in <module>
    main(config)
  File "/Users/51pwn/MyWork/Bringing-Old-Photos-Back-to-Life/Global/detection.py", line 97, in main
    model.to(config.GPU)
  File "/Users/51pwn/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/Users/51pwn/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/51pwn/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/51pwn/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/Users/51pwn/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/Users/51pwn/miniconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "/Users/51pwn/MyWork/Bringing-Old-Photos-Back-to-Life/Global/test.py", line 97, in <module>
    opt = TestOptions().parse(save=False)
  File "/Users/51pwn/MyWork/Bringing-Old-Photos-Back-to-Life/Global/options/base_options.py", line 354, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/Users/51pwn/miniconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
Traceback (most recent call last):
  File "/Users/51pwn/MyWork/Bringing-Old-Photos-Back-to-Life/Face_Enhancement/test_face.py", line 10, in <module>
    from util.visualizer import Visualizer
  File "/Users/51pwn/MyWork/Bringing-Old-Photos-Back-to-Life/Face_Enhancement/util/visualizer.py", line 15, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
```

### Versions

 $ conda run py3 collect_env.py
```
Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.24.1
Libc version: N/A

Python version: 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53)  [Clang 6.0 (clang-600.0.57)] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz

Versions of relevant libraries:
[pip3] clip-anytorch==2.5.0
[pip3] CoCa-pytorch==0.0.7
[pip3] dalle2-pytorch==1.12.1
[pip3] ema-pytorch==0.2.1
[pip3] imagen-pytorch==1.22.0
[pip3] make-a-video-pytorch==0.0.9
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] open-clip-torch==2.10.1
[pip3] pytorch-lightning==1.9.0
[pip3] pytorch-warmup==0.1.1
[pip3] pytorch-wavelets==1.3.0
[pip3] rotary-embedding-torch==0.2.1
[pip3] torch==1.10.1
[pip3] torch-fidelity==0.3.0
[pip3] torchaudio==0.10.1
[pip3] torchdiffeq==0.2.3
[pip3] torchfile==0.1.0
[pip3] torchmetrics==0.11.0
[pip3] torchsde==0.2.5
[pip3] torchtext==0.12.0
[pip3] torchvision==0.11.2
[pip3] tritonclient==2.31.0
[pip3] vector-quantize-pytorch==1.0.1
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] cudatoolkit               9.0                  h41a26b3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] libblas                   3.9.0              12_osx64_mkl    conda-forge
[conda] libcblas                  3.9.0              12_osx64_mkl    conda-forge
[conda] liblapack                 3.9.0              12_osx64_mkl    conda-forge
[conda] liblapacke                3.9.0              12_osx64_mkl    conda-forge
[conda] mkl                       2021.4.0           hecd8cb5_637    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.4.0           py310hca72f7f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.3.1           py310hf879493_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.2.2           py310hc081a56_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.23.5          py310h9638375_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy-base                1.23.5          py310ha98c3c9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   2.0.0                  py3.10_0    pytorch
[conda] torchaudio                2.0.0                 py310_cpu    pytorch
[conda] torchvision               0.15.0                py310_cpu    pytorch
```

**Comment by hktalent** [comment]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/18223385/226775672-d625e3d2-b268-4a9e-8b8d-69f29c346604.png">

#### How run on MacOS
```
conda create -n pytorch python=3.6.4
conda activate pytorch;conda init zsh
conda update --all
conda install pytorch torchvision torchaudio -c pytorch
conda install -n pytorch matplotlib opencv scikit-image dill easydict dlib tensorboardX
pip install tensorboardX
conda update --all    

rm $HOME/Downloads/old/.DS_Store
conda run py3 ./run.py --input_folder $HOME/Downloads/old --output_folder $HOME/Downloads/output --GPU -1 --with_scratch
```
