### ISSUE TITLE
Torch Dynamo Error when Compiling/Exporting Module which Uses Amp Utility

### ISSUE THREAD

**Issue by gs-olive** [pytorch/pytorch#97320]
### 🐛 Describe the bug

Encountered errors when compiling the small code sample provided in the "Minified Repro" section, which uses `torch.cuda.amp.autocast(enabled=False)` on an operation.

1. When using `torch.compile(model)`
```python
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
```
2. When using `torch._dynamo.explain(model, input)`
```python
torch._dynamo.exc.BackendCompilerFailed: backend='dynamo_graph_accumulating_compiler' raised:
AttributeError: 'GraphModule' object has no attribute 'compile_subgraph_reason'
```

### Error logs

<details>

<summary>
1. When using compiled = torch.compile()(model); compiled(input)
</summary>

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 105, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 263, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 326, in _compile
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 313, in transform
    tracer.run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1841, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1920, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 545, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 615, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 701, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 697, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/debug_utils.py", line 1043, in debug_wrapper
    run_fwd_maybe_bwd(compiled_gm, example_inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/debug_utils.py", line 636, in run_fwd_maybe_bwd
    out = gm(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 1241, in g
    return f(*args)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 254, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 2888, in forward
    return compiled_fn(full_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 1241, in g
    return f(*args)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 2440, in debug_compiled_function
    return compiled_function(*args)
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 1920, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 1266, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 1241, in g
    return f(*args)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 2188, in forward
    fw_outs = call_func_with_args(
  File "/usr/local/lib/python3.8/dist-packages/torch/_functorch/aot_autograd.py", line 1266, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/compile_fx.py", line 252, in run
    return model(new_inputs)
  File "/tmp/torchinductor_root/jk/cjk4od2crwdgbwjtyuvulms7q6tr7o7borciqbnrqvmxe6ejood7.py", line 82, in call
    triton_fused__to_copy_native_layer_norm_0.run(buf1, primals_3, primals_1, primals_2, buf3, 100, 10, grid=grid(100), stream=stream0)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/triton_ops/autotune.py", line 196, in run
    self.autotune_to_one_config(*args, grid=grid)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/triton_ops/autotune.py", line 186, in autotune_to_one_config
    timings = self.benchmark_all_configs(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/triton_ops/autotune.py", line 178, in benchmark_all_configs
    timings = {
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/triton_ops/autotune.py", line 179, in <dictcomp>
    launcher: self.bench(launcher, *cloned_args, **kwargs)[0]
  File "/usr/local/lib/python3.8/dist-packages/torch/_inductor/triton_ops/autotune.py", line 161, in bench
    return do_bench(kernel_call, rep=40, fast_flush=True)
  File "/usr/local/lib/python3.8/dist-packages/triton/testing.py", line 147, in do_bench
    torch.cuda.synchronize()
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 711, in synchronize
    return torch._C._cuda_synchronize()
torch._dynamo.exc.BackendCompilerFailed: backend='debug_wrapper' raised:
RuntimeError: CUDA error: an illegal memory access was encountered
```

</details>

<details>

<summary>
2. When using torch._dynamo.explain(model, input)
</summary>

```python
Traceback (most recent call last):
  File "case.py", line 36, in <module>
    explanation_verbose = explain(model, embedding)
  File "/usr/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 548, in explain
    opt_f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 118, in __call__
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 254, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 391, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 406, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 105, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 263, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 326, in _compile
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 313, in transform
    tracer.run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1841, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 597, in run
    and self.step()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 560, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1920, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 545, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 615, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 701, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 697, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/debug_utils.py", line 1042, in debug_wrapper
    compiled_gm = compiler_fn(copy.deepcopy(gm), example_inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 533, in dynamo_graph_accumulating_compiler
    if gm.compile_subgraph_reason is not None:
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
torch._dynamo.exc.BackendCompilerFailed: backend='dynamo_graph_accumulating_compiler' raised:
AttributeError: 'GraphModule' object has no attribute 'compile_subgraph_reason'
```

</details>

### Minified repro

**File - error.py**
```python
import logging

import torch
from torch._dynamo import config, explain

config.verbose = True
config.log_level = logging.DEBUG

config.repro_after = "dynamo"
config.repro_level = 3

config.output_code = True
config.output_graph_code = True
config.print_graph_breaks = True


class CastToFloat(torch.nn.Module):

    def __init__(self, mod):
        super(CastToFloat, self).__init__()
        self.mod = mod

    def forward(self, x):
        with torch.cuda.amp.autocast(enabled=False):
            ret = self.mod.forward(x.to(torch.float32)).to(x.dtype)
        return ret

embedding = torch.randn(20, 5, 10).int().cuda()

layer_norm = torch.nn.LayerNorm(10).cuda()
model = CastToFloat(layer_norm)

##### fails
explain(model, embedding)


##### Also fails
compiled = torch.compile(model)
compiled(embedding)
```

### Versions

```python
Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] torch==2.1.0.dev20230314+cu118
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by SherlockNoMad** [comment]
cc @yanboliang  who recently has a dynamo fix for amp. 
https://github.com/pytorch/pytorch/pull/95416

**Comment by yanboliang** [comment]
@gs-olive I can't reproduce this locally, can you verify it again?

**Comment by gs-olive** [comment]
I am still seeing the error on the Apr 5 dev release of Torch (`2.1.0.dev20230405+cu118`). I realized there was a small bug in the reproducer script, which has now been fixed. Could you retry the script with the new changes?

**Comment by yanboliang** [comment]
```config.output_graph_code``` has been remove if you are using Apr 5 dev release, it errors there. Please use the updated logging level setting:
```
torch._logging.set_logs(dynamo=logging.DEBUG, aot=logging.DEBUG, inductor=logging.DEBUG)
```
After applying this change, your script passed.

**Comment by gs-olive** [comment]
Thank you for the suggestion - it is now passing on my end as well. I appreciate the help!
