### ISSUE TITLE
Cannot open db - LMDB, via python, Windows 10

### ISSUE THREAD

**Issue by CarlosYeverino** [pytorch/pytorch#9736]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
I was able to compile pytorch with the aim of using Caffe2. I have tested some libraries using python and it works well. However, I would like to use data bases for training but when I try to use lmdb there is an error:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-107e99931720> in <module>()
     17 
     18 # Initialize and create the training network
---> 19 workspace.RunNetOnce(train_model.param_init_net)
     20 workspace.CreateNet(train_model.net, overwrite=True)
     21 # Initialize and create validation network

D:\Yeverino\git_projects\pytorch\build\caffe2\python\workspace.pyc in RunNetOnce(net)
    197         C.Workspace.current._last_failed_op_net_position,
    198         GetNetName(net),
--> 199         StringifyProto(net),
    200     )
    201 

D:\Yeverino\git_projects\pytorch\build\caffe2\python\workspace.pyc in CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs)
    176 def CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs):
    177     try:
--> 178         return func(*args, **kwargs)
    179     except Exception:
    180         op_id = op_id_fetcher()

RuntimeError: [enforce fail at db.h:190] db_. Cannot open db: D:\caffe2_notebooks\tutorial_data\cifar10\training_lmdb of type lmdb Error from operator: 
output: "dbreader_D:\\caffe2_notebooks\\tutorial_data\\cifar10\\training_lmdb" name: "" type: "CreateDB" arg { name: "db_type" s: "lmdb" } arg { name: "db" s: "D:\\caffe2_notebooks\\tutorial_data\\cifar10\\training_lmdb" }
```
**For the setup I used python 2.7 and installed all required packages. I installed the package lmdb as well. However, it seems that it is not recognized for the compilation of Caffe2. Furthermore, I set USE_LMDB=ON but it is not recognized by CMake since it has no impact in the CMake configuration that is printed out in the console. The file CMake_Cache.txt (attached) 
[CMakeCache.txt](https://github.com/pytorch/pytorch/files/2221447/CMakeCache.txt)
also indicates that path for LMDB was not found LMDB_DIR:PATH=LMDB_DIR-NOTFOUND . How can I successfully use LMDB for Caffe2 using my configuration? I am stuck at this step for a while, any help would be very appreciated.**

Provide a short description.
LMDB error - cannot open db

## Code example
Follow Cifar10 or MNIST Tutorial.

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: Pythorch cloned to be able to use Caffe2
- How you installed PyTorch (conda, pip, source): github
- Build command you used (if compiling from source):
- OS: Windows 10
- PyTorch version: current version
- Python version: 2.7
- CUDA/cuDNN version: 8.0/7.0.5
- GPU models and configuration: NVIDIA GeForce GTX 1050
- GCC version (if compiling from source):
- CMake version: cmake-3.12.0-rc2-win64-x64.msi
- Versions of any other relevant libraries: Visual Studio 2015

**Comment by CarlosYeverino** [comment]
Hi @pjh5 ,

when the compilation fails, I delete the folder pytorch\build and then set configurations(including set USE_LMDB=ON) and finally execute build_windows.bat 

thanks for your help. I installed lmdb via python 2.7 using:
`pip install lmdb`

lmdb is installed in path C:\Python27\Lib\site-packages. There are two folders:
lmdb and lmdb-0.94-py2.7.egg-info

![image](https://user-images.githubusercontent.com/25825048/43165929-75ad6950-8f95-11e8-962f-802f7d52d79a.png)

![image](https://user-images.githubusercontent.com/25825048/43165963-8668f9c6-8f95-11e8-8909-60c3050921a2.png)

There is no error for code lines like:
`import lmdb`
...
`env = lmdb.open(lmdb_path, map_size=LMDB_MAP_SIZE)`

However when the execution reaches the following:
`workspace.RunNetOnce(train_model.param_init_net)`
the above-mentioned error appears.

**Comment by zhaiyuqiang** [comment]
I have the same problem when I run the MNIST example and I install caffe2 by miniconda. 
Many guys have this problem, Why not fix it ??

my env is

"
PyTorch version: 1.0.0.dev20181029
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 14.04.5 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
CMake version: version 2.8.12.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration: GPU 0: Quadro P4000
Nvidia driver version: 384.59
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.7.0.3
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.15.3)
[pip] torch (1.0.0.dev20181029)
[conda] cuda80                    1.0                  h205658b_0    pytorch
[conda] pytorch-nightly           1.0.0.dev20181029 py2.7_cuda8.0.61_cudnn7.1.2_0  [cuda80]  pytorch
"

**Comment by orionr** [comment]
@zhaiyuqiang looks like CMake can't find LMDB when building. Can you see if there's some adjustment to `cmake/Modules/FindLMDB.cmake` that you could do to have it find this? Maybe just try changing

```
if(MSVC)
  find_package(LMDB NO_MODULE)
else()
  find_path(LMDB_INCLUDE_DIR NAMES  lmdb.h PATHS "$ENV{LMDB_DIR}/include")
  find_library(LMDB_LIBRARIES NAMES lmdb   PATHS "$ENV{LMDB_DIR}/lib" )
endif()
```

to

```
find_path(LMDB_INCLUDE_DIR NAMES  lmdb.h PATHS "$ENV{LMDB_DIR}/include")
find_library(LMDB_LIBRARIES NAMES lmdb   PATHS "$ENV{LMDB_DIR}/lib" )
```

 Unfortunately I don't think we test LMDB installs on CI.

**Comment by pjh5** [comment]
@zhaiyuqiang to add to this, the binaries are not built with lmdb, so if by "install caffe2 by miniconda" you mean you used "conda install" then it won't work. To use lmdb right now you'd have to build with source.

**Comment by CarlosYeverino** [comment]
Hello @orionr ,

I try changing the cmake file as you mentioned. However, it still does not work. I got the same error:

 ```
workspace.RunNetOnce(train_model.param_init_net)
  File "D:\Yeverino\git_projects\pytorch\build\caffe2\python\workspace.py", line 199, in RunNetOnce
    StringifyProto(net),
  File "D:\Yeverino\git_projects\pytorch\build\caffe2\python\workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at db.h:190] db_. Cannot open db: ./data\mnist_mnistClassifier_net\mnist-train-nchw-lmdb of type lmdb Error from operator:
output: "dbreader_./data\\mnist_mnistClassifier_net\\mnist-train-nchw-lmdb" name: "" type: "CreateDB" arg { name: "db_type" s: "lmdb" } arg { name: "db" s: "./data\\mnist_mnistClassifier_net\\mnist-train-nchw-lmdb" } device_option { device_type: 1 cuda_gpu_id: 0 }
[F context_gpu.h:117] Check failed: error == cudaSuccess driver shutting down
```
I noticed that the LMDB flag was OFF even when I set it to ON before executing build_windows.bat.

**Is it possible to get a LMDB fix/patch for the tag v0.4.0?** I already developed some CNN predictors using that tag on ubuntu and I would like to extend the support for windows 10.
