### ISSUE TITLE
Expanded weights tests broken

### ISSUE THREAD

**Issue by sclarkson** [pytorch/pytorch#97395]
### 🐛 Describe the bug

```
$ python pytorch/test/run_test.py -i test_expanded_weights -v
<omitted>
Ran 495 tests in 26.571s

FAILED (failures=29, errors=82, skipped=34)
FINISHED PRINTING LOG FILE of test_expanded_weights (/home/sclarkson/pytorch/test/test-reports/test_expanded_weights_24ydgznv.log)

test_expanded_weights failed!
Traceback (most recent call last):
  File "/home/sclarkson/pytorch/test/run_test.py", line 1394, in <module>
    main()
  File "/home/sclarkson/pytorch/test/run_test.py", line 1352, in main
    raise RuntimeError(
RuntimeError: test_expanded_weights failed!

Tip: You can keep running tests even on failure by passing --keep-going to run_test.py.
If running on CI, add the 'keep-going' label to your PR and rerun your jobs.
```

The errors all look like the example below

```
======================================================================
ERROR: test_Conv1d_cuda (__main__.TestExpandedWeightModuleCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sclarkson/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2069, in wrapper
    method(*args, **kwargs)
  File "/home/sclarkson/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/sclarkson/pytorch/test/test_expanded_weights.py", line 695, in <lambda>
    setattr(TestExpandedWeightModule, test_name, lambda self, test=test: test.test_context_manager(self, 'cpu'))
  File "/home/sclarkson/pytorch/test/test_expanded_weights.py", line 661, in test_context_manager
    test_case._do_test(module, input)
  File "/home/sclarkson/pytorch/test/test_expanded_weights.py", line 412, in _do_test
    actual_grads.append(input.grad.clone())
AttributeError: 'NoneType' object has no attribute 'clone'
```

And the failures all look like the example below.

```
======================================================================
FAIL: test_Conv1d_multiple_inputs_cuda (__main__.TestExpandedWeightModuleCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sclarkson/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2069, in wrapper
    method(*args, **kwargs)
  File "/home/sclarkson/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/sclarkson/pytorch/test/test_expanded_weights.py", line 697, in <lambda>
    lambda self, test=test: test.test_context_manager_multiple_inputs(self, 'cpu'))
  File "/home/sclarkson/pytorch/test/test_expanded_weights.py", line 670, in test_context_manager_multiple_inputs
    test_case._do_test_multi_input(module, input)
  File "/home/sclarkson/pytorch/test/test_expanded_weights.py", line 476, in _do_test_multi_input
    assert [self.assertEqual(actual, 2 * expected) for (actual, expected) in zip(actual_grads, expected_grads)]
  File "/home/sclarkson/pytorch/test/test_expanded_weights.py", line 476, in <listcomp>
    assert [self.assertEqual(actual, 2 * expected) for (actual, expected) in zip(actual_grads, expected_grads)]
  File "/home/sclarkson/miniconda3/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2967, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 80 / 80 (100.0%)
Greatest absolute difference: 2.188215970993042 at index (0, 0, 2) (up to 1e-05 allowed)
Greatest relative difference: 1.0000067267518076 at index (0, 2, 1) (up to 1.3e-06 allowed)
```

This didn't occur in the 1.13 release. I was able to bisect it back to #91807

It looks like the `TestExpandedWeightModule` is not overloaded to run two fundamentally different types of tests, some that are parameterized manually [here](https://github.com/pytorch/pytorch/blob/116a4f23016ecea430c947785d07702f20290bbd/test/test_expanded_weights.py#L679-L701) and others parameterized by device type [here](https://github.com/pytorch/pytorch/blob/116a4f23016ecea430c947785d07702f20290bbd/test/test_expanded_weights.py#L778)

This conflict is apparent in test names like `test_Conv1d_cuda_double_cpu (__main__.TestExpandedWeightModuleCPU)`

### Versions

```
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-37-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 525.89.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        1
CPU max MHz:                     2900.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4400.12
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
Virtualization:                  VT-x
L1d cache:                       384 KiB (12 instances)
L1i cache:                       384 KiB (12 instances)
L2 cache:                        3 MiB (12 instances)
L3 cache:                        30 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.23.5          py310hd5efca6_0  
[conda] numpy-base                1.23.5          py310h8e6c178_0  
[conda] pytorch                   2.0.0           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_3    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.0               py310_cu118    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.0              py310_cu118    pytorch
```

**Comment by sclarkson** [comment]
Something like this would fix the tests, splitting out the device parameterized `test_module` into its own class.

```
--- a/test/test_expanded_weights.py
+++ b/test/test_expanded_weights.py
@@ -386,7 +386,7 @@
         with self.assertRaisesRegex(RuntimeError, r"Expected number of channels in input to be divisible"):
             F.group_norm(inp, 2)  # 5 is not divisible by 2
 
-class TestExpandedWeightModule(TestCase):
+class TestExpandedWeightModuleBase(TestCase):
     def _do_test(self, module, input, args=None, kwargs=None, batch_first=True, atol=None, rtol=None):
         args = args or ()
         kwargs = kwargs or {}
@@ -512,6 +512,7 @@
             self.assertEqual(actual_res, expected_res)
             [self.assertEqual(actual, expected, atol=atol, rtol=rtol) for (actual, expected) in zip(actual_grads, expected_grads)]
 
+class TestExpandedWeightModule(TestExpandedWeightModuleBase):
     @modules(filter(lambda m_info: m_info.module_cls in (torch.nn.RNN, torch.nn.LSTM, torch.nn.GRU), module_db))
     def test_module(self, device, dtype, module_info, training):
         class RNNWrapper(torch.nn.Module):
@@ -567,6 +568,7 @@
             else:
                 self._do_test(m, input, args[1:], kwargs, batch_first=batch_first, atol=atol, rtol=rtol)
 
+class TestExpandedWeightModuleLegacy(TestExpandedWeightModuleBase):
     def test_per_sample_api_failing(self):
         module = nn.Linear(10, 10)
         input = torch.randn(64, 10)
@@ -692,12 +694,13 @@
     if decorator is not None:
         fn = decorator(fn)
     if test.test_cpu:
-        setattr(TestExpandedWeightModule, test_name, lambda self, test=test: test.test_context_manager(self, 'cpu'))
-        setattr(TestExpandedWeightModule, test_name_multi_input,
+        setattr(TestExpandedWeightModuleLegacy, test_name,
+                lambda self, test=test: test.test_context_manager(self, 'cpu'))
+        setattr(TestExpandedWeightModuleLegacy, test_name_multi_input,
                 lambda self, test=test: test.test_context_manager_multiple_inputs(self, 'cpu'))
     if TEST_CUDA and test.test_cuda:
         # since this checks derivatives, only use double for precision
-        setattr(TestExpandedWeightModule, test_name + '_cuda_double',
+        setattr(TestExpandedWeightModuleLegacy, test_name + '_cuda_double',
                 lambda self, test=test: test.test_context_manager(self, 'cuda'))
 
 # ------------- HELPER FUNCTIONS -----------------
```

**Comment by daisyden** [comment]
Seems test_Linear_no_bias_multiple_inputs_cpu could break test_Linear_no_bias_cpu, when I renaming the 'test_Linear_no_bias_multiple_inputs_cpu' to 'test_Linear_no_bias_amultiple_inputs_cpu', the test_Linear_no_bias_cpu after that will be broken and input.grad is None after backward. Running test_Linear_no_bias_cpu independently it can pass.

```
pytest -vs test/test_expanded_weights.py -k "test_Linear_no_bias_amultiple_inputs_cpu or test_Linear_no_bias_cpu"
============================================================================================ test session starts ============================================================================================
platform linux -- Python 3.10.18, pytest-7.3.2, pluggy-1.6.0 -- /home/daisydeng/miniforge3/envs/pytorch/bin/python3.10
cachedir: .pytest_cache
hypothesis profile 'dev' -> database=None, max_examples=10, suppress_health_check=[HealthCheck.too_slow]
rootdir: /home/daisydeng/pytorch
configfile: pytest.ini
plugins: rerunfailures-14.0, cpp-2.3.0, hypothesis-6.56.4, xdist-3.3.1, xdoctest-1.3.0, subtests-0.13.1, flakefinder-1.1.0
collecting ... /home/daisydeng/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/testing/_internal/common_nn.py:3404: PytestCollectionWarning: cannot collect 'test' because it is not a function.
  def __call__(self, test_case):
/home/daisydeng/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/testing/_internal/common_nn.py:3331: PytestCollectionWarning: cannot collect test class 'TestBase' because it has a __init__ constructor (from: test/test_expanded_weights.py)
  class TestBase:
collected 225 items / 223 deselected / 2 selected
Running 2 items in this shard

test/test_expanded_weights.py::TestExpandedWeightModuleCPU::test_Linear_no_bias_amultiple_inputs_cpu PASSED [0.0059s]
test/test_expanded_weights.py::TestExpandedWeightModuleCPU::test_Linear_no_bias_cpu input cpu
/home/daisydeng/pytorch/test/test_expanded_weights.py:649: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print(input.grad, flush=True)
None
/home/daisydeng/pytorch/test/test_expanded_weights.py:651: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  actual_grads.append(input.grad.clone())
FAILED [0.0017s]

================================================================================================= FAILURES ==================================================================================================
____________________________________________________________________________ TestExpandedWeightModuleCPU.test_Linear_no_bias_cpu ____________________________________________________________________________
Traceback (most recent call last):
  File "/home/daisydeng/pytorch/test/test_expanded_weights.py", line 1034, in <lambda>
    decorator(lambda self, test=test: test.test_context_manager(self, "cpu")),
  File "/home/daisydeng/pytorch/test/test_expanded_weights.py", line 982, in test_context_manager
    test_case._do_test(module, input)
  File "/home/daisydeng/pytorch/test/test_expanded_weights.py", line 651, in _do_test
    actual_grads.append(input.grad.clone())
AttributeError: 'NoneType' object has no attribute 'clone'

To execute this test, run the following from the base repo dir:
    python test/test_expanded_weights.py TestExpandedWeightModuleCPU.test_Linear_no_bias_cpu

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
========================================================================================== short test summary info ==========================================================================================
FAILED [0.0017s] test/test_expanded_weights.py::TestExpandedWeightModuleCPU::test_Linear_no_bias_cpu - AttributeError: 'NoneType' object has no attribute 'clone'
================================================================================ 1 failed, 1 passed, 223 deselected in 1.61s ============================================

```
