### ISSUE TITLE
Torch Dynamo Error when Compiling/Exporting Module which Uses `getattr`

### ISSUE THREAD

**Issue by gs-olive** [pytorch/pytorch#97480]
### 🐛 Describe the bug

Encountered error when Dynamo tracing the small code sample provided in the "Minified Repro" section, which uses the `getattr` function:

```python
def f():
    getattr(None, 'arg', 3)
```

```python
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: hasattr: ConstantVariable(NoneType)
```

### Error logs

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 346, in wrapper
    return inner_fn(self, inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 993, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 494, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/builtin.py", line 561, in call_function
    result = handler(tx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/builtin.py", line 965, in call_getattr
    hasattr_var = self.call_hasattr(tx, obj, name_var)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/builtin.py", line 889, in call_hasattr
    return obj.call_hasattr(tx, name).add_options(self, obj, attr)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/base.py", line 225, in call_hasattr
    unimplemented(f"hasattr: {repr(self)}")
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: hasattr: ConstantVariable(NoneType)
```

### Minified repro

```python
import logging

from torch._dynamo import config, explain

config.verbose = True
config.log_level = logging.DEBUG

config.repro_after = "dynamo"
config.repro_level = 3

config.output_code = True
config.output_graph_code = True
config.print_graph_breaks = True


def f():
    getattr(None, 'arg', 3)

##### fails
explain(f)

##### also fails
torch.compile()(f)()
```

### Versions

```python
Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] torch==2.1.0.dev20230314+cu118
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
Should be pretty easy to fix, can advise.

**Comment by chengzhou9** [comment]
Hi, I'd like to pick up this up as a first issue. Is the goal here just to have `getattr` run without raising an exception?

**Comment by jjmmchema** [comment]
Hey there, I'd like to give this a try as a first issue.

**Comment by chengzhou9** [comment]
@jjmmchema Could you give me a couple more days to work on this? I think I should be able to get a PR out soon.
