### ISSUE TITLE
DISABLED test_memory_snapshot (__main__.TestCudaComm)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#97560]
```
2023-03-24T20:59:52.1975677Z ______________________ TestCudaComm.test_memory_snapshot _______________________
2023-03-24T20:59:52.1976006Z Traceback (most recent call last):
2023-03-24T20:59:52.1976358Z   File "/opt/conda/envs/py_3.8/lib/python3.8/urllib/request.py", line 1354, in do_open
2023-03-24T20:59:52.1976760Z     h.request(req.get_method(), req.selector, req.data, headers,
2023-03-24T20:59:52.1977160Z   File "/opt/conda/envs/py_3.8/lib/python3.8/http/client.py", line 1256, in request
2023-03-24T20:59:52.1977553Z     self._send_request(method, url, body, headers, encode_chunked)
2023-03-24T20:59:52.1977943Z   File "/opt/conda/envs/py_3.8/lib/python3.8/http/client.py", line 1302, in _send_request
2023-03-24T20:59:52.1978328Z     self.endheaders(body, encode_chunked=encode_chunked)
2023-03-24T20:59:52.1978723Z   File "/opt/conda/envs/py_3.8/lib/python3.8/http/client.py", line 1251, in endheaders
2023-03-24T20:59:52.1979102Z     self._send_output(message_body, encode_chunked=encode_chunked)
2023-03-24T20:59:52.1979501Z   File "/opt/conda/envs/py_3.8/lib/python3.8/http/client.py", line 1011, in _send_output
2023-03-24T20:59:52.1979821Z     self.send(msg)
2023-03-24T20:59:52.1980140Z   File "/opt/conda/envs/py_3.8/lib/python3.8/http/client.py", line 951, in send
2023-03-24T20:59:52.1980441Z     self.connect()
2023-03-24T20:59:52.1980773Z   File "/opt/conda/envs/py_3.8/lib/python3.8/http/client.py", line 1425, in connect
2023-03-24T20:59:52.1981152Z     self.sock = self._context.wrap_socket(self.sock,
2023-03-24T20:59:52.1981508Z   File "/opt/conda/envs/py_3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
2023-03-24T20:59:52.1981857Z     return self.sslsocket_class._create(
2023-03-24T20:59:52.1982204Z   File "/opt/conda/envs/py_3.8/lib/python3.8/ssl.py", line 1040, in _create
2023-03-24T20:59:52.1982502Z     self.do_handshake()
2023-03-24T20:59:52.1982826Z   File "/opt/conda/envs/py_3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
2023-03-24T20:59:52.1983152Z     self._sslobj.do_handshake()
2023-03-24T20:59:52.1983605Z ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)
2023-03-24T20:59:52.1983909Z 
2023-03-24T20:59:52.1984095Z During handling of the above exception, another exception occurred:
2023-03-24T20:59:52.1984319Z 
2023-03-24T20:59:52.1984445Z Traceback (most recent call last):
2023-03-24T20:59:52.1984767Z   File "test_cuda.py", line 5009, in test_memory_snapshot
2023-03-24T20:59:52.1985298Z     torch.cuda.memory._save_segment_usage(f.name)
2023-03-24T20:59:52.1985881Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/cuda/memory.py", line 651, in _save_segment_usage
2023-03-24T20:59:52.1986269Z     f.write(_segments(snapshot))
2023-03-24T20:59:52.1986781Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/cuda/_memory_viz.py", line 104, in segments
2023-03-24T20:59:52.1987225Z     return format_flamegraph(f.getvalue())
2023-03-24T20:59:52.1987950Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/cuda/_memory_viz.py", line 62, in format_flamegraph
2023-03-24T20:59:52.1988363Z     urllib.request.urlretrieve(
2023-03-24T20:59:52.1988724Z   File "/opt/conda/envs/py_3.8/lib/python3.8/urllib/request.py", line 247, in urlretrieve
2023-03-24T20:59:52.1989118Z     with contextlib.closing(urlopen(url, data)) as fp:
2023-03-24T20:59:52.1989581Z   File "/opt/conda/envs/py_3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
2023-03-24T20:59:52.1990004Z     return opener.open(url, data, timeout)
2023-03-24T20:59:52.1990378Z   File "/opt/conda/envs/py_3.8/lib/python3.8/urllib/request.py", line 525, in open
2023-03-24T20:59:52.1990723Z     response = self._open(req, data)
2023-03-24T20:59:52.1991082Z   File "/opt/conda/envs/py_3.8/lib/python3.8/urllib/request.py", line 542, in _open
2023-03-24T20:59:52.1991474Z     result = self._call_chain(self.handle_open, protocol, protocol +
2023-03-24T20:59:52.1991895Z   File "/opt/conda/envs/py_3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
2023-03-24T20:59:52.1992228Z     result = func(*args)
2023-03-24T20:59:52.1992557Z   File "/opt/conda/envs/py_3.8/lib/python3.8/urllib/request.py", line 1397, in https_open
2023-03-24T20:59:52.1992969Z     return self.do_open(http.client.HTTPSConnection, req,
2023-03-24T20:59:52.1993383Z   File "/opt/conda/envs/py_3.8/lib/python3.8/urllib/request.py", line 1357, in do_open
2023-03-24T20:59:52.1993717Z     raise URLError(err)
2023-03-24T20:59:52.1994145Z urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>
```

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_cuda.py%3A%3ATestCudaComm%3A%3Atest_memory_snapshot)).

cc @ngimel

**Comment by clee2000** [comment]
possibly due to https://www.githubstatus.com/incidents/x7njwb481j9b
