### ISSUE TITLE
[caffe2] TypeError: conv_transpose() takes at least 6 arguments (9 given)

### ISSUE THREAD

**Issue by XiongChengxin** [pytorch/pytorch#9761]
I need to use conv_transpose(), but I always receive the same error. My code are as follows, any help would be highly appreciated. Thanks in advance.

upconv = brew.conv_transpose(
    model,
    blob_in = final_avg,
    blob_out = 'upconv',
    dim_in = =512,
    dim_out = 2048,
    kernels = [4,1,1],
    strides = [2,1,1],
    pads = [1,0,0],
)

**Comment by jerryzh168** [comment]
The error message doesn't make sense to me, but for arguments, I think pads should have 6 elements.

**Comment by jerryzh168** [comment]
Since you are doing 3d conv according to the arguments.

**Comment by XiongChengxin** [comment]
@jerryzh168 The whole error message are as follows. At the same time, for 3d conv, pads should have 3 elements, one for temporal dimension, two for spatial dimension. 

Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
E0724 22:27:31.919901 10520 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0724 22:27:31.920105 10520 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0724 22:27:31.920117 10520 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
INFO:train_net:Namespace(base_learning_rate=0.0001, batch_size=4, clip_length_of=8, clip_length_rgb=32, crop_size=112, cudnn_workspace_limit_mb=64, db_type='pickle', display_iter=10, do_flow_aggregation=0, epoch_size=100000, file_store_path='.', flow_data_type=0, frame_gap_of=2, gamma=0.1, get_video_id=0, gpus='0,1,2', input_type=0, is_checkpoint=0, model_depth=34, model_name='r2plus1d', num_channels=3, num_decode_threads=4, num_epochs=4, num_gpus=1, num_labels=101, pred_layer_name=None, pretrained_model='/home/xiongcx/R2Plus1D-master/models/r2.5d_d34_l32.pkl', profiling=0, sampling_rate_of=2, sampling_rate_rgb=1, scale_h=128, scale_w=171, step_epoch=2, test_data='/home/xiongcx/R2Plus1D-master/lmdb/TH14_testing_lmdb', train_data='/home/xiongcx/R2Plus1D-master/lmdb/TH14_training_lmdb', use_cudnn=1, use_dropout=0, use_local_file=0, weight_decay=0.005)
INFO:model_builder:Validated: r2plus1d with 34 layers
INFO:model_builder:with input 32x112x112
INFO:train_net:Running on GPUs: [0, 1, 2]
INFO:train_net:Using epoch size: 99996
WARNING:root:[====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO:train_net:train set has 9990 examples
INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:model_helper:outputing rgb data
INFO:model_builder:creating r2plus1d, depth=34...
INFO:video_model:Number of middle filters: 144
INFO:video_model:Number of middle filters: 144
INFO:video_model:Number of middle filters: 144
INFO:video_model:Number of middle filters: 144
INFO:video_model:Number of middle filters: 144
INFO:video_model:Number of middle filters: 144
INFO:video_model:Number of middle filters: 230
INFO:video_model:Number of middle filters: 288
INFO:video_model:Number of middle filters: 288
INFO:video_model:Number of middle filters: 288
INFO:video_model:Number of middle filters: 288
INFO:video_model:Number of middle filters: 288
INFO:video_model:Number of middle filters: 288
INFO:video_model:Number of middle filters: 288
INFO:video_model:Number of middle filters: 460
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 576
INFO:video_model:Number of middle filters: 921
INFO:video_model:Number of middle filters: 1152
INFO:video_model:Number of middle filters: 1152
INFO:video_model:Number of middle filters: 1152
INFO:video_model:Number of middle filters: 1152
INFO:video_model:Number of middle filters: 1152
Traceback (most recent call last):
  File "/home/xiongcx/R2Plus1D-master/tools/train_net.py", line 528, in <module>
    main()
  File "/home/xiongcx/R2Plus1D-master/tools/train_net.py", line 523, in main
    Train(args)
  File "/home/xiongcx/R2Plus1D-master/tools/train_net.py", line 303, in Train
    net_type=('prof_dag' if args.profiling == 1 else 'dag'),
  File "/home/xiongcx/files/duhaijun/pytorch/build/caffe2/python/data_parallel_model.py", line 32, in Parallelize_GPU
    Parallelize(*args, **kwargs)
  File "/home/xiongcx/files/duhaijun/pytorch/build/caffe2/python/data_parallel_model.py", line 209, in Parallelize
    losses = forward_pass_builder_fun(model_helper_obj, loss_scale)
  File "/home/xiongcx/R2Plus1D-master/tools/train_net.py", line 240, in create_model_ops
    pred_layer_name=args.pred_layer_name,
  File "../lib/models/model_builder.py", line 134, in build_model
    is_test=is_test,
  File "../lib/models/r3d_model.py", line 101, in create_model
    is_decomposed=(model_name == 'r2plus1d'),
  File "../lib/models/r3d_model.py", line 236, in create_r3d
    pads=[1,0,0],
  File "/home/xiongcx/files/duhaijun/pytorch/build/caffe2/python/brew.py", line 107, in scope_wrapper
    return func(*args, **new_kwargs)
TypeError: conv_transpose() takes at least 6 arguments (9 given)

**Comment by jerryzh168** [comment]
I think we'll need 6 for pads, we'll need 2 pads in each direction. e.g. left pad and right pad

**Comment by XiongChengxin** [comment]
I found it works when the kernel has only 1 argument, but I am confusing about what I should do if I want to do 3D convtranspose.

**Comment by XiongChengxin** [comment]
I found it works when the kernel has only 1 argument, but I am confusing about what I should do if I want to do 3D convtranspose(not square, eg. kernel=(4,1,1)).

**Comment by jerryzh168** [comment]
have you tried changing the arguments to have 6 padding numbers?

**Comment by jerryzh168** [comment]
Feels like ConvTranspose does not support 3D yet: https://github.com/pytorch/pytorch/blob/master/caffe2/operators/conv_transpose_op_impl.h

**Comment by XiongChengxin** [comment]
I modify my 3D data to 2D now, but I am comfused about how to use stride and padding in convtranspose, the API said "Note that other parameters, such as the stride and kernel size, or the pads’ sizes in each direction are not necessary for input because they are provided by the ConvTransposeUnpoolOpBase operator", but I didn't find the " the ConvTransposeUnpoolOpBase operator". Any suggestions? Thanks in advance.

**Comment by XiongChengxin** [comment]
I modify my 3D data to 2D now, but I am comfused about how to use stride and padding in convtranspose, the API said "Note that other parameters, such as the stride and kernel size, or the pads’ sizes in each direction are not necessary for input because they are provided by the ConvTransposeUnpoolOpBase operator", I found the 'ConvTransposeUnpoolOpBase operator' but still have no idea how to use stride and pads.

I tried:
kernel_h=4,
kernel_w=1,
stride_h=2,
stride_w=1,
pad_t=1,
pad_l=1,
pad_b=0,
pad_r=0,
but this didn't work. If I don't add the stride and padding parameter, it will work. But the shape of output feature map is not I want.
 Any suggestions? Thanks in advance.

**Comment by jerryzh168** [comment]
What is the error message right now?
