### ISSUE TITLE
Test Failure: TestUnaryUfuncsCPU.test_reference_numerics_large_cos_cpu_float32 on s390x

### ISSUE THREAD

**Issue by kiszk** [pytorch/pytorch#97731]
### 🐛 Describe the bug

When I execute the following test case on s390x, I got the failure.
```
% python test/test_unary_ufuncs.py TestUnaryUfuncsCPU.test_reference_numerics_large_cos_cpu_float32

======================================================================
FAIL: test_reference_numerics_large_cos_cpu_float32 (__main__.TestUnaryUfuncsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ishizaki/PyTorch/master/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/ishizaki/PyTorch/master/torch/testing/_internal/common_device_type.py", line 851, in test_wrapper
    return test(*args, **kwargs)
  File "/home/ishizaki/PyTorch/master/torch/testing/_internal/common_utils.py", line 1390, in wrapper
    fn(*args, **kwargs)
  File "/home/ishizaki/PyTorch/master/test/test_unary_ufuncs.py", line 299, in test_reference_numerics_large
    self._test_reference_numerics(dtype, op, tensors)
  File "/home/ishizaki/PyTorch/master/test/test_unary_ufuncs.py", line 256, in _test_reference_numerics
    _helper_reference_numerics(
  File "/home/ishizaki/PyTorch/master/test/test_unary_ufuncs.py", line 217, in _helper_reference_numerics
    self.assertEqualHelper(
  File "/home/ishizaki/PyTorch/master/test/test_unary_ufuncs.py", line 171, in assertEqualHelper
    self.assertEqual(
  File "/home/ishizaki/PyTorch/master/torch/testing/_internal/common_utils.py", line 3023, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 3 / 100 (3.0%)
Greatest absolute difference: 1.1338233947753906 at index (29,) (up to 1e-05 allowed)
Greatest relative difference: 2.0 at index (9,) (up to 1.3e-06 allowed)
```

When I compared the behavior of this test on s390x and x86_64, I realized the expected values (by `numpy`) are different on s390x and x86_64.

The first 10 elements for onput tensor on s390x
```
actual: tensor([-5.0100e+02, -5.0100e+02, -5.0100e+02, -5.0100e+02, -5.0100e+02,
        -5.0100e+02, -5.0100e+02, -5.0100e+02, -5.0100e+02, -5.0100e+02,

expected: [-5.010000e+02 -5.010000e+02 -5.010000e+02 -5.010000e+02 -5.010000e+02
 -5.010000e+02 -5.010000e+02 -5.010000e+02 -5.010000e+02 -5.010000e+02
```
The first 10 elements for Input tensor on x86_64
```
actual: tensor([-5.0100e+02, -5.0100e+02, -5.0100e+02, -5.0100e+02, -5.0100e+02,
        -5.0100e+02, -5.0100e+02, -5.0100e+02, -5.0100e+02, -5.0100e+02,

expected: [-5.010000e+02 -5.010000e+02 -5.010000e+02 -5.010000e+02 -5.010000e+02
 -5.010000e+02 -5.010000e+02 -5.010000e+02 -5.010000e+02 -5.010000e+02
```

The first 10 elements for output tensor on s390x
```
actual: tensor([-0.0839, -0.0839, -0.0839, -0.0839, -0.0839, -0.0839, -0.0839, -0.0839,
        -0.0839, -0.0839, 

expected: [-0.0839294  -0.0839294  -0.0839294  -0.0839294  -0.0839294  -0.0839294
 -0.0839294  -0.0839294  -0.0839294   0.0839294        
```

The first 10 elements for output tensor on x86_64
```
actual: tensor([-0.0839, -0.0839, -0.0839, -0.0839, -0.0839, -0.0839, -0.0839, -0.0839,
        -0.0839, -0.0839,
        
expected: [-0.0839294  -0.0839294  -0.0839294  -0.0839294  -0.0839294  -0.0839294
 -0.0839294  -0.0839294  -0.0839294  -0.0839294
```

In the elements of output, only 10th element of expected tensor s390x has a value `0.0839294` (probably expected `-0.0839294`). This is a reason why this test reports a failure on s390x.

on s390x
```
pip list | grep numpy
numpy                1.24.1
```

on x86_64
```
pip list | grep numpy
numpy                1.24.2
```

### Versions

```
python ../collect_env.py 
Collecting environment information...
PyTorch version: 2.1.0a0+gite3df6a7
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (s390x)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-144-generic-s390x-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.1.0a0+gite3df6a7
[conda] Could not collect
```

**Comment by kiszk** [comment]
When I update numpy on s390x to 1.24.2, this problem disappears.
