### ISSUE TITLE
TypeError: 'torch._C._TensorMeta' object is not iterable

### ISSUE THREAD

**Issue by raydleemsc** [pytorch/pytorch#97748]
### 🐛 Describe the bug

Error on initial use
pip install torch
import torch
x = torch.rand(5,3)
print(x)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Clouds\OneDrive\Documents\dev\github\openai\ChatGPT-at-Home\env\lib\site-packages\torch\__init__.py", line 934, in <module>
    from .storage import _StorageBase, TypedStorage, _LegacyStorage, UntypedStorage, _warn_typed_storage_removal
  File "D:\Clouds\OneDrive\Documents\dev\github\openai\ChatGPT-at-Home\env\lib\site-packages\torch\storage.py", line 230, in <module>
    class UntypedStorage(torch._C.StorageBase, _StorageBase):
TypeError: 'torch._C._TensorMeta' object is not iterable

Running on -
# Python 3.10.0b2
# GNU bash, version 5.1.16(1)-release (x86_64-pc-msys)
# VS Code Version: 1.76.2 (system setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

# Hardware - Nitro AN515-43
Processor	AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx     2.10 GHz
Installed RAM	40.0 GB (37.9 GB usable)

# OS
Edition	Windows 10 Home Single Language
Version	22H2
OS build	19045.2728
Experience	Windows Feature Experience Pack 120.2212.4190.0

### Versions

$ python collect_env.py
Traceback (most recent call last):
  File "D:\Clouds\OneDrive\Documents\dev\github\openai\ChatGPT-at-Home\collect_env.py", line 15, in <module>
    import torch
  File "D:\Clouds\OneDrive\Documents\dev\github\openai\ChatGPT-at-Home\env\lib\site-packages\torch\__init__.py", line 934, in <module>
    from .storage import _StorageBase, TypedStorage, _LegacyStorage, UntypedStorage, _warn_typed_storage_removal
  File "D:\Clouds\OneDrive\Documents\dev\github\openai\ChatGPT-at-Home\env\lib\site-packages\torch\storage.py", line 230, in <module>
    class UntypedStorage(torch._C.StorageBase, _StorageBase):
TypeError: 'torch._C._TensorMeta' object is not iterable

**Comment by raydleemsc** [comment]
pip list gives this -
filelock==3.10.7
Jinja2==3.1.2
MarkupSafe==2.1.2
mpmath==1.3.0
networkx==3.0
sympy==1.11.1
torch==2.0.0
typing_extensions==4.5.0

**Comment by jithunnair-amd** [comment]
Also, do you intend to use PyTorch on your AMD GPUs, or just on the AMD CPUs? If it's the former, you should definitely install wheels as in above comment.

**Comment by raydleemsc** [comment]
Looking in indexes: https://download.pytorch.org/whl/rocm5.4.2
ERROR: Could not find a version that satisfies the requirement torch (from
versions: none)
ERROR: No matching distribution found for torch
Just looking for a version to work, really
Raymond D. Lee, M.Sc.

**Comment by raydleemsc** [comment]
Raymond D. Lee, M.Sc.

**Comment by laddg95** [comment]
same error. How did solve it?

**Comment by laddg95** [comment]
Solution: Downgrade Python version. The recommended version is 3.8, but please be aware not to go too low. Refer to the discussion at https://discuss.pytorch.org/t/pytorch-2-0-supported-python-version/174962.

I just resolved the same error. Initially, my CUDA version was 12.0, PyTorch version was torch 2.0.1 for CUDA 11.8, and Python versions were 3.10.0 and 3.9.0, but all gave me an error. I thought the issue was due to the compatibility between PyTorch and CUDA versions, so I tried installing CUDA 11.8. The result proved that the issue was not due to CUDA, although this might also be a potential important factor.

Now, my CUDA version is 11.8, PyTorch version is torch 2.0.1 for CUDA 11.8. I failed to load torch using Python 3.9.0, but successfully loaded it using Python 3.8.8.

**Comment by alinpahontu2912** [comment]
Hello @raydleemsc, are you still dealing with this issue ? Right now, ROCm is not available for windows so you can not use pytorch with AMD GPUs on Windows. Did you run into this issue by using the latest cpu build of pytorch ?

![Image](https://github.com/pytorch/pytorch/assets/56953855/148d6de0-250e-443a-821d-f7384a7ed986)
