### ISSUE TITLE
The first epoch is very slow when using torch.compile

### ISSUE THREAD

**Issue by zhuangweiji** [pytorch/pytorch#97783]
### 🐛 Describe the bug

We tried using torch.compile on our training code and the first epoch was very slow.

### Error logs

```bash
# uncompiled mode: out = model(x)
$ python torch2_compile.py
```
2.0.0+cu117
/mnt/nfs/env/py-venv/py39_cuda117_torch200/lib/python3.9/site-packages/torch/autograd/__init__.py:200: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
**Epoch 0/10 time: 0.09859752655029297**
Epoch 1/10 time: 0.09461498260498047
Epoch 2/10 time: 0.09749722480773926
Epoch 3/10 time: 0.09946417808532715
Epoch 4/10 time: 0.09831523895263672
Epoch 5/10 time: 0.0978553295135498
Epoch 6/10 time: 0.09766864776611328
Epoch 7/10 time: 0.0983278751373291
Epoch 8/10 time: 0.09094047546386719
Epoch 9/10 time: 0.09506630897521973
Epoch avg time: 0.09683477878570557

```bash
# compiled mode: out = compiled_model(x)
$ python torch2_compile.py
```
2.0.0+cu117
/mnt/nfs/env/py-venv/py39_cuda117_torch200/lib/python3.9/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/mnt/nfs/env/cuda/cuda-11.7'
[2023-03-28 22:20:57,063] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
**Epoch 0/10 time: 18.54069495201111**
Epoch 1/10 time: 0.10959434509277344
Epoch 2/10 time: 0.10520339012145996
Epoch 3/10 time: 0.10396909713745117
Epoch 4/10 time: 0.10267758369445801
Epoch 5/10 time: 0.10393261909484863
Epoch 6/10 time: 0.10507917404174805
Epoch 7/10 time: 0.10506296157836914
Epoch 8/10 time: 0.10470414161682129
Epoch 9/10 time: 0.10574936866760254
Epoch avg time: 1.948666763305664

### Minified repro

```bash
$ CUDA_VISIBLE_DEVICES=0
$ python torch2_compile.py
```

```bash
$ cat torch2_compile.py
#!/usr/bin/env python3

import time
import torch
import torch._dynamo as dynamo
import torchvision.models as models

model = models.alexnet()

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
compiled_model = torch.compile(model)

x = torch.randn(16, 3, 224, 224)
optimizer.zero_grad()

epoches=10
count = []
for epoch in range(epoches):
    start = time.time()

    #out = model(x)
    out = compiled_model(x)
    out.sum().backward()
    optimizer.step()

    end = time.time()
    count.append(end - start)
    print(f"Epoch {epoch}/{epoches} time: {end - start}")

print(f"Epoch avg time: {sum(count)/len(count)}")

```

### Versions

$ python ~/env/bin/collect_env.py
Collecting environment information...
/mnt/nfs/env/py-venv/py39_cuda117_torch200/lib/python3.9/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.3.1611 (Core)  (x86_64)
GCC version: (GCC) 7.5.0
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.17

Python version: 3.9.15 (main, Nov 12 2022, 16:52:40)  [GCC 5.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-693.21.1.std7a.el7.0.x86_64-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 530.30.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Platinum 8350C CPU @ 2.60GHz
Stepping:              6
CPU MHz:               3500.000
BogoMIPS:              5206.54
Virtualization:        VT-x
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              49152K
NUMA node0 CPU(s):     0-31,64-95
NUMA node1 CPU(s):     32-63,96-127

Versions of relevant libraries:
[pip3] audio2numpy==0.1.2
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] Could not collect

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by zhuangweiji** [comment]
The attachments are the output of strace.ur code and data are on NFS.

**Comment by ezyang** [comment]
This reproduces for me.

**Comment by zhuangweiji** [comment]
> Oh, your epoch is trivial. The slow start is because we're compiling your model. This is expected.

This is just a Minified repro. In fact, it's also slow on thousands of hours of speech data. The speed of the first 500+batch (batch size 64) will be 1% speed of the latter

**Comment by zhuangweiji** [comment]
![image](https://user-images.githubusercontent.com/31652817/228292826-8cbe4e5c-3869-4a27-96c1-679065a214df.png)

I see some ptxas programs are in the disk sleep state when the program is running very slowly. The speed becomes faster after hundreds of batches.

**Comment by ezyang** [comment]
Are you potentially able to run with logging turned on, and upload the logfile? What I mostly want to know is if we're recompiling a lot on the first epoch in your real example.

**Comment by zhuangweiji** [comment]
Sure! @ezyang 
I saw the torchinductor compiling log appeared up to line 1208663. by which point the model had been trained to "epoch 0/10 batch 262/44775".It took 1 hour 3 minutes. After that, the training speed returned to normal.
The log file size is 93MB(25MB are allowed), so I gzip it.

[torch2_sw_tdnnf_ce_epoch10_gpu4_adam_batch64_compile_debug_20230329-135440.1.log.gz](https://github.com/pytorch/pytorch/files/11100923/torch2_sw_tdnnf_ce_epoch10_gpu4_adam_batch64_compile_debug_20230329-135440.1.log.gz)

**Comment by ezyang** [comment]
woof debug logs haha

**Comment by ezyang** [comment]
You're compiling 575 graphs in total

```
[2023-03-29 14:59:00,015] torch._inductor.compile_fx: [INFO] Step 3: torchinductor compiling BACKWARDS graph 575
[2023-03-29 14:59:00,292] torch._inductor.compile_fx: [INFO] Step 3: torchinductor done compiling BACKWARDS graph 575
```

so it makes sense that it is slow. Need to figure out why it is recompiling so much. Do you have dynamic shapes in your model by any chance?

**Comment by yanboliang** [comment]
```RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides```, seems a known issue. cc @ezyang

**Comment by ezyang** [comment]
Can you try a nightly? This is normally coverage problem but it's failing in F.linear and I'm pretty sure we support that op 🤔

**Comment by zhuangweiji** [comment]
Yes! 
I used PyTorch version: 2.1.0.dev20230330+cu117 and got following error: 
```
[2023-03-31 11:49:40,579] torch._inductor.ir: [WARNING] Could not do split reduction due to dynamic shapes; performance may be worse                                                                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                     
  File "/mnt/user/zhuangweiji/workspace/salween/egs/xatx_l_k2/salween/train/train.py", line 1305, in <module>                                                                                                                                                                                                                                                                          
    ret = main()                                                                                                                                                                                                                                                                                                                                                                       
  File "/mnt/user/zhuangweiji/workspace/salween/egs/xatx_l_k2/salween/train/train.py", line 1287, in main                                                                                                                                                                                                                                                                              
    trainer.train(                                                                                                                                                                                                                                                                                                                                                                     
  File "/mnt/user/zhuangweiji/workspace/salween/egs/xatx_l_k2/salween/train/train.py", line 456, in train                                                                                                                                                                                                                                                                              
    self.train_epoch(curr_epoch)                                                                                                                                                                                                                                                                                                                                                       
  File "/mnt/user/zhuangweiji/workspace/salween/egs/xatx_l_k2/salween/train/train.py", line 780, in train_epoch                                                                                                                                                                                                                                                                        
    model_outputs = self.model(*input_tensors)                                                                                                                                                                                                                                                                                                                                         
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl                                                                                                                                                                                                                                              
    return forward_call(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                               
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1550, in forward                                                                                                                                                                                                                                           
    else self._run_ddp_forward(*inputs, **kwargs)                                                                                                                                                                                                                                                                                                                                      
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1403, in _run_ddp_forward                                                                                                                                                                                                                                  
    return self.module(*args, **kwargs)  # type: ignore[index]                                                                                                                                                                                                                                                                                                                         
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 101, in __call__                                                                                                                                                                                                                                                
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)                                                                                                                                                                                                                                                                                                                   
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 237, in _fn                                                                                                                                                                                                                                                     
    return fn(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                         
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl                                                                                                                                                                                                                                              
    return forward_call(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                               
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 371, in catch_errors                                                                                                                                                                                                                                            
    return hijacked_callback(frame, cache_size, hooks)                                                                                                                                                                                                                                                                                                                                 
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 424, in _convert_frame                                                                                                                                                                                                                                       
    result = inner_convert(frame, cache_size, hooks)                                                                                                                                                                                                                                                                                                                                   
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 111, in _fn                                                                                                                                                                                                                                                  
    return fn(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                         
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 276, in _convert_frame_assert                                                                                                                                                                                                                                
    return _compile(                                                                                                                                                                                                                                                                                                                                                                   
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 166, in time_wrapper                                                                                                                                                                                                                                                 
    r = func(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                          
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 341, in _compile                                                                                                                                                                                                                                             
    out_code = transform_code_object(code, transform)                                                                                                                                                                                                                                                                                                                                  
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object                                                                                                                                                                                                                      
    transformations(instructions, code_options)                                                                                                                                                                                                                                                                                                                                        
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 328, in transform                                                                                                                                                                                                                                            
    tracer.run()                                                                                                                                                                                                                                                                                                                                                                       
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1857, in run                                                                                                                                                                                                                                              
    super().run()                                                                                                                                                                                                                                                                                                                                                                      
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 604, in run                                                                                                                                                                                                                                               
    and self.step()                                                                                                                                                                                                                                                                                                                                                                    
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in step                                                                                                                                                                                                                                              
    getattr(self, inst.opname)(inst)                                                                                                                                                                                                                                                                                                                                                   
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1936, in RETURN_VALUE                                                                                                                                                                                                                                     
    self.output.compile_subgraph(                                                                                                                                                                                                                                                                                                                                                      
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 581, in compile_subgraph                                                                                                                                                                                                                                      
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)                                                                                                                                                                                                                                                                                                             
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 650, in compile_and_call_fx_graph                                                                                                                                                                                                                             
    compiled_fn = self.call_user_compiler(gm)                                                                                                                                                                                                                                                                                                                                          
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 166, in time_wrapper                                                                                                                                                                                                                                                 
    r = func(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                          
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 729, in call_user_compiler                                                                                                                                                                                                                                    
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(                                                                                                                                                                                                                                                                                                                   
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 725, in call_user_compiler                                                                                                                                                                                                                                    
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())                                                                                                                                                                                                                                                                                                                          
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/backends/distributed.py", line 348, in compile_fn                                                                                                                                                                                                                                    
    submod_compiler.run(*example_inputs)                                                                                                                                                                                                                                                                                                                                               
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/fx/interpreter.py", line 137, in run                                                                                                                                                                                                                                                         
    self.env[node] = self.run_node(node)                                                                                                                                                                                                                                                                                                                                               
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/backends/distributed.py", line 342, in run_node                                                                                                                                                                                                                                      
    return curr_submod(*new_args, **kwargs)                                                                                                                                                                                                                                                                                                                                            
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/fx/graph_module.py", line 662, in call_wrapped                                                                                                                                                                                                                                               
    return self._wrapped_call(self, *args, **kwargs)                                                                                                                                                                                                                                                                                                                                   
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/fx/graph_module.py", line 281, in __call__                                                                                                                                                                                                                                                   
    raise e                                                                                                                                                                                                                                                                                                                                                                            
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/fx/graph_module.py", line 271, in __call__                                                       
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]                                                                                                            
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)                                                     
  File "<eval_with_key>.17", line 63, in forward                                             
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)                                                     
  File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward                                                      
    return F.linear(input, self.weight, self.bias)                                           
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:                                                                                                                      
RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides                                                                                                                    

While executing %submod_1 : [#users=1] = call_module[target=compiled_submod_1](args = (%getitem, %getitem_1), kwargs = {})                                                                 
Original traceback:                                                                          
None                                                                                         


You can suppress this exception and fall back to eager by setting:                           
    torch._dynamo.config.suppress_errors = True                                              

```

**Comment by ezyang** [comment]
RIP. I guess I need to do some code reading.

**Comment by ezyang** [comment]
I read through our implementation of linear and I don't see where the size() call could be coming from. I'm going to work with @zdevito to get a nightly going that will print the C++ backtrace automatically, but in lieu of that, if you are able to attach gdb and get a backtrace when it raises the `Cannot call sizes() on tensor with symbolic sizes/strides` exception that would help. https://docs.google.com/document/d/1GgvOe7C8_NVOMLOCwDaYV1mXXyHMXY7ExoewHqooxrs/edit#heading=h.9ozikwcc6g7b explains how to do it.

**Comment by flishwang** [comment]
> Yes! I used PyTorch version: 2.1.0.dev20230330+cu117 and got following error:
> 
> ```
> [2023-03-31 11:49:40,579] torch._inductor.ir: [WARNING] Could not do split reduction due to dynamic shapes; performance may be worse                                                                                                                                                                                                                                                   
> Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                     
>   File "/mnt/user/zhuangweiji/workspace/salween/egs/xatx_l_k2/salween/train/train.py", line 1305, in <module>                                                                                                                                                                                                                                                                          
>     ret = main()                                                                                                                                                                                                                                                                                                                                                                       
>   File "/mnt/user/zhuangweiji/workspace/salween/egs/xatx_l_k2/salween/train/train.py", line 1287, in main                                                                                                                                                                                                                                                                              
>     trainer.train(                                                                                                                                                                                                                                                                                                                                                                     
>   File "/mnt/user/zhuangweiji/workspace/salween/egs/xatx_l_k2/salween/train/train.py", line 456, in train                                                                                                                                                                                                                                                                              
>     self.train_epoch(curr_epoch)                                                                                                                                                                                                                                                                                                                                                       
>   File "/mnt/user/zhuangweiji/workspace/salween/egs/xatx_l_k2/salween/train/train.py", line 780, in train_epoch                                                                                                                                                                                                                                                                        
>     model_outputs = self.model(*input_tensors)                                                                                                                                                                                                                                                                                                                                         
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl                                                                                                                                                                                                                                              
>     return forward_call(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                               
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1550, in forward                                                                                                                                                                                                                                           
>     else self._run_ddp_forward(*inputs, **kwargs)                                                                                                                                                                                                                                                                                                                                      
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1403, in _run_ddp_forward                                                                                                                                                                                                                                  
>     return self.module(*args, **kwargs)  # type: ignore[index]                                                                                                                                                                                                                                                                                                                         
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 101, in __call__                                                                                                                                                                                                                                                
>     return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)                                                                                                                                                                                                                                                                                                                   
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 237, in _fn                                                                                                                                                                                                                                                     
>     return fn(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                         
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl                                                                                                                                                                                                                                              
>     return forward_call(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                               
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 371, in catch_errors                                                                                                                                                                                                                                            
>     return hijacked_callback(frame, cache_size, hooks)                                                                                                                                                                                                                                                                                                                                 
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 424, in _convert_frame                                                                                                                                                                                                                                       
>     result = inner_convert(frame, cache_size, hooks)                                                                                                                                                                                                                                                                                                                                   
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 111, in _fn                                                                                                                                                                                                                                                  
>     return fn(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                         
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 276, in _convert_frame_assert                                                                                                                                                                                                                                
>     return _compile(                                                                                                                                                                                                                                                                                                                                                                   
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 166, in time_wrapper                                                                                                                                                                                                                                                 
>     r = func(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                          
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 341, in _compile                                                                                                                                                                                                                                             
>     out_code = transform_code_object(code, transform)                                                                                                                                                                                                                                                                                                                                  
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object                                                                                                                                                                                                                      
>     transformations(instructions, code_options)                                                                                                                                                                                                                                                                                                                                        
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 328, in transform                                                                                                                                                                                                                                            
>     tracer.run()                                                                                                                                                                                                                                                                                                                                                                       
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1857, in run                                                                                                                                                                                                                                              
>     super().run()                                                                                                                                                                                                                                                                                                                                                                      
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 604, in run                                                                                                                                                                                                                                               
>     and self.step()                                                                                                                                                                                                                                                                                                                                                                    
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in step                                                                                                                                                                                                                                              
>     getattr(self, inst.opname)(inst)                                                                                                                                                                                                                                                                                                                                                   
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1936, in RETURN_VALUE                                                                                                                                                                                                                                     
>     self.output.compile_subgraph(                                                                                                                                                                                                                                                                                                                                                      
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 581, in compile_subgraph                                                                                                                                                                                                                                      
>     self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)                                                                                                                                                                                                                                                                                                             
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 650, in compile_and_call_fx_graph                                                                                                                                                                                                                             
>     compiled_fn = self.call_user_compiler(gm)                                                                                                                                                                                                                                                                                                                                          
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 166, in time_wrapper                                                                                                                                                                                                                                                 
>     r = func(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                          
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 729, in call_user_compiler                                                                                                                                                                                                                                    
>     raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(                                                                                                                                                                                                                                                                                                                   
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 725, in call_user_compiler                                                                                                                                                                                                                                    
>     compiled_fn = compiler_fn(gm, self.fake_example_inputs())                                                                                                                                                                                                                                                                                                                          
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/backends/distributed.py", line 348, in compile_fn                                                                                                                                                                                                                                    
>     submod_compiler.run(*example_inputs)                                                                                                                                                                                                                                                                                                                                               
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/fx/interpreter.py", line 137, in run                                                                                                                                                                                                                                                         
>     self.env[node] = self.run_node(node)                                                                                                                                                                                                                                                                                                                                               
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/_dynamo/backends/distributed.py", line 342, in run_node                                                                                                                                                                                                                                      
>     return curr_submod(*new_args, **kwargs)                                                                                                                                                                                                                                                                                                                                            
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/fx/graph_module.py", line 662, in call_wrapped                                                                                                                                                                                                                                               
>     return self._wrapped_call(self, *args, **kwargs)                                                                                                                                                                                                                                                                                                                                   
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/fx/graph_module.py", line 281, in __call__                                                                                                                                                                                                                                                   
>     raise e                                                                                                                                                                                                                                                                                                                                                                            
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/fx/graph_module.py", line 271, in __call__                                                       
>     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]                                                                                                            
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)                                                     
>   File "<eval_with_key>.17", line 63, in forward                                             
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)                                                     
>   File "/mnt/nfs/env/py-venv/py39_cuda117_torch2nightly/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward                                                      
>     return F.linear(input, self.weight, self.bias)                                           
> torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:                                                                                                                      
> RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides                                                                                                                    
> 
> While executing %submod_1 : [#users=1] = call_module[target=compiled_submod_1](args = (%getitem, %getitem_1), kwargs = {})                                                                 
> Original traceback:                                                                          
> None                                                                                         
> 
> 
> You can suppress this exception and fall back to eager by setting:                           
>     torch._dynamo.config.suppress_errors = True                                              
> ```

This may be a bug when both using DDP and dynamic shapes. See:

**Comment by tugsbayasgalan** [comment]
@zhuangweiji  could you retry to see if this issue still persist?
