### ISSUE TITLE
Test failure: TestTensorCreationCPU.test_float_to_int_conversion_finite_cpu_uint8 on s390x

### ISSUE THREAD

**Issue by kiszk** [pytorch/pytorch#97794]
### 🐛 Describe the bug

When I execute the following test case on s390x, I got the failure.

```python
% python test/test_tensor_creation_ops.py TestTensorCreationCPU.test_float_to_int_conversion_finite_cpu_uint8
/home/ishizaki/PyTorch/master/test/test_tensor_creation_ops.py:945: RuntimeWarning: invalid value encountered in cast
F
======================================================================
FAIL: test_float_to_int_conversion_finite_cpu_uint8 (__main__.TestTensorCreationCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ishizaki/PyTorch/master/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/ishizaki/PyTorch/master/torch/testing/_internal/common_device_type.py", line 1046, in only_fn
    return fn(self, *args, **kwargs)
  File "/home/ishizaki/PyTorch/master/test/test_tensor_creation_ops.py", line 973, in test_float_to_int_conversion_finite
    self._float_to_int_conversion_helper(vals, device, dtype)
  File "/home/ishizaki/PyTorch/master/test/test_tensor_creation_ops.py", line 947, in _float_to_int_conversion_helper
    self.assertEqual(torch.from_numpy(a), t.cpu())
  File "/home/ishizaki/PyTorch/master/torch/testing/_internal/common_utils.py", line 3023, in assertEqual
    raise error_metas[0].to_error(
AssertionError: Tensor-likes are not equal!

Mismatched elements: 2 / 9 (22.2%)
Greatest absolute difference: 255 at index (2,)
Greatest relative difference: 1.0 at index (1,)

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (failures=1)
```

When I execute the following small programs, I saw strange behavior in numpy  (Python 3.10.6, numpy 1.24.2) only on s390x. I imagine that this issue is also related to `numpy`

on s390x
```
$ python -c "import torch; import numpy as np; vals = (0, -2, -1.5, -0.5, 0, 0.5, 1.5, 2, 0); t = torch.tensor(vals, dtype=torch.float).to(torch.uint8); print(t); a = np.array(vals, dtype=np.float32).astype(np.uint8); print (a)"
tensor([  0, 254, 255,   0,   0,   0,   1,   2,   0], dtype=torch.uint8)
<string>:1: RuntimeWarning: invalid value encountered in cast
[0 0 0 0 0 0 1 2 0]
```

on x86_64
```
python -c "import torch; import numpy as np; vals = (0, -2, -1.5, -0.5, 0, 0.5, 1.5, 2, 0); t = torch.tensor(vals, dtype=torch.float).to(torch.uint8); print(t); a = np.array(vals, dtype=np.float32).astype(np.uint8); print (a)"
tensor([  0, 254, 255,   0,   0,   0,   1,   2,   0], dtype=torch.uint8)
[  0 254 255   0   0   0   1   2   0]
```
cc @Andreas-Krebbel 

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0a0+gite3df6a7
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (s390x)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-144-generic-s390x-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0a0+gite3df6a7
[conda] Could not collect
```

**Comment by kiszk** [comment]
cc @Andreas-Krebbel

**Comment by kiszk** [comment]
on s390x
```
$ python -c "import numpy as np; vals = (0, -2, -1.5, -0.5, 0, 0.5, 1.5, 2, 0); a = np.array(vals, dtype=np.float32).astype(np.uint8); print(a)"
<string>:1: RuntimeWarning: invalid value encountered in cast
[0 0 0 0 0 0 1 2 0]
```

**Comment by janeyx99** [comment]
For numpy issues that aren't due to torch, could you please flesh out the repros (and add output) and open a new issue on https://github.com/numpy/numpy/issues?

**Comment by kiszk** [comment]
I ask a question at https://discuss.pytorch.org/t/tensor-to-specification-for-out-of-range-value/176973

**Comment by ptrblck** [comment]
Might also be related to: https://github.com/numpy/numpy/issues/19881

**Comment by kiszk** [comment]
Thank you. [Similar issue](https://github.com/pytorch/pytorch/issues/39671) was reported on PowerPC.

**Comment by kiszk** [comment]
Might also related to https://github.com/pytorch/pytorch/issues/38752

**Comment by kiszk** [comment]
I will create a PR to address this soon.
