### ISSUE TITLE
Test failure: TestQuantizedEmbeddingOps.test_embedding_bag_2bit on s390x

### ISSUE THREAD

**Issue by kiszk** [pytorch/pytorch#97801]
### 🐛 Describe the bug

When I run the following test, I get the failure.

```python
$ python test/test_quantization.py TestQuantizedEmbeddingOps.test_embedding_bag_2bit 
...
F
======================================================================
FAIL: test_embedding_bag_2bit (quantization.core.test_quantized_op.TestQuantizedEmbeddingOps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ishizaki/PyTorch/master/test/quantization/core/test_quantized_op.py", line 4367, in test_embedding_bag_2bit
    embedding_dim=st.integers(5, 50).filter(lambda x: x % 8 == 0),
  File "/home/ishizaki/PyTorch/master/.pytorch-master-build/lib/python3.10/site-packages/hypothesis/core.py", line 1397, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/ishizaki/PyTorch/master/test/quantization/core/test_quantized_op.py", line 4383, in test_embedding_bag_2bit
    self.embedding_bag_rowwise_offsets_run(2, num_embeddings,
  File "/home/ishizaki/PyTorch/master/test/quantization/core/test_quantized_op.py", line 4288, in embedding_bag_rowwise_offsets_run
    torch.testing.assert_close(reference_result, result, atol=atol, rtol=rtol)
  File "/home/ishizaki/PyTorch/master/torch/testing/_comparison.py", line 1519, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 24 / 24 (100.0%)
Greatest absolute difference: 21.839494705200195 at index (2, 7) (up to 1.0 allowed)
Greatest relative difference: 12.448298519374724 at index (2, 0) (up to 0.1 allowed)
Falsifying example: test_embedding_bag_2bit(
    num_embeddings=10,
    embedding_dim=8,
    num_offsets=1,
    use_32bit_indices=False,
    use_32bit_offsets=False,
    enable_per_sample_weights=False,
    include_last_offset=False,
    fallback_to_no_sparse=False,
    sparsity=0.0,
    self=<quantization.core.test_quantized_op.TestQuantizedEmbeddingOps testMethod=test_embedding_bag_2bit>,
)

----------------------------------------------------------------------
Ran 1 test in 0.306s

FAILED (failures=1)
```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0a0+gite3df6a7
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (s390x)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-144-generic-s390x-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0a0+gite3df6a7
[conda] Could not collect
```

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by kiszk** [comment]
Sorry for my bad. #97801 can fix this failure.
