### ISSUE TITLE
Test failure: TestQuantizedEmbeddingOps.test_embedding_bag_2bit on big-endian machine

### ISSUE THREAD

**Issue by kiszk** [pytorch/pytorch#97803]
### 🐛 Describe the bug

When I run the following test, I get the failure.

```python
$ python test/test_quantization.py TestQuantizedEmbeddingOps.test_embedding_bag_2bit_unpack
/home/ishizaki/PyTorch/master/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
WARNING:root:This caffe2 python run failed to load cuda module:No module named 'caffe2.python.caffe2_pybind11_state_gpu',and AMD hip module:No module named 'caffe2.python.caffe2_pybind11_state_hip'.Will run in CPU only mode.
[W init.h:137] Caffe2 GlobalInit should be run before any other API calls.
E
======================================================================
ERROR: test_embedding_bag_2bit_unpack (quantization.core.test_quantized_op.TestQuantizedEmbeddingOps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ishizaki/PyTorch/master/test/quantization/core/test_quantized_op.py", line 4175, in test_embedding_bag_2bit_unpack
    @given(num_embeddings=st.integers(10, 100),
  File "/home/ishizaki/PyTorch/master/.pytorch-master-build/lib/python3.10/site-packages/hypothesis/core.py", line 1397, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/ishizaki/PyTorch/master/test/quantization/core/test_quantized_op.py", line 4184, in test_embedding_bag_2bit_unpack
    self._test_embedding_bag_unpack_fn(
  File "/home/ishizaki/PyTorch/master/test/quantization/core/test_quantized_op.py", line 4137, in _test_embedding_bag_unpack_fn
    self._test_embedding_bag_unpack_impl(pack_fn, unpack_fn, bit_rate, optimized_qparams, unsplit_weight)
  File "/home/ishizaki/PyTorch/master/test/quantization/core/test_quantized_op.py", line 4121, in _test_embedding_bag_unpack_impl
    w_packed_c2, w_unpacked_c2 = get_c2_weights(c2_copy, engine)
  File "/home/ishizaki/PyTorch/master/test/quantization/core/test_quantized_op.py", line 4094, in get_c2_weights
    workspace.RunOperatorOnce(
  File "/home/ishizaki/PyTorch/master/caffe2/python/workspace.py", line 206, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at fused_rowwise_nbit_conversion_ops.h:31] internal::is_little_endian(). Unsupported endianness (Error from operator: 
input: "weights" output: "quantized_weights" name: "" type: "FloatToFused2BitRowwiseQuantized" engine: "")
Falsifying example: test_embedding_bag_2bit_unpack(
    num_embeddings=10,
    embedding_dim=8,
    optimized_qparams=False,
    data_type=numpy.float32,
    self=<quantization.core.test_quantized_op.TestQuantizedEmbeddingOps testMethod=test_embedding_bag_2bit_unpack>,
)

----------------------------------------------------------------------
Ran 1 test in 0.216s

FAILED (errors=1)
```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0a0+gite3df6a7
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (s390x)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-144-generic-s390x-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0a0+gite3df6a7
[conda] Could not collect
```

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by janeyx99** [comment]
Could you actually test this on latest master? I think the latest commit (https://github.com/pytorch/pytorch/commit/8289120ef025c3ec9ee89ef2dc972e26743e852e) should fix this.

**Comment by kiszk** [comment]
IMHO, this failure is intentionally caused by this [assertion](https://github.com/pytorch/pytorch/blob/master/caffe2/operators/fused_rowwise_nbit_conversion_ops.h#L31). This is because this function does not seem to support big endianness so far.
