### ISSUE TITLE
Graph break update script doesn't work

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#97939]
### 🐛 Describe the bug

```
$ pp python benchmarks/dynamo/ci_expected_accuracy/update_expected.py 3a3449f22aefdec1e070630cdbcf9d0b7c12c3ce
Traceback (most recent call last):
  File "/data/users/ezyang/c/pytorch/benchmarks/dynamo/ci_expected_accuracy/update_expected.py", line 127, in <module>
    results = query_job_sha(repo, args.sha)
  File "/data/users/ezyang/c/pytorch/benchmarks/dynamo/ci_expected_accuracy/update_expected.py", line 43, in query_job_sha
    return data["results"]
KeyError: 'results'
```

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire 

### Versions

master

**Comment by wconstab** [comment]
this is fixed already, iiuc.  https://github.com/pytorch/pytorch/pull/97898

The wobble was actually caused by debugging steps related to a confirmed rocksdb outage, and hopefully shouldn't happen again
