### ISSUE TITLE
[pt2] `bitwise_and` + `clamp_max` Triggers Compilation Error

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#97968]
### 🐛 Describe the bug

The following program works fine in eager mode but triggers a compilation error when using `torch.compile`. Some details for debugging are illustrated in the comments (✔️ means that the program terminates without error, ❌ means that compilation error occurs).

It's probably related to #94055.

```python
import torch

def fn(x, y):
    t = torch.bitwise_and(x, y) # ✔️ works fine w/o this line
    return torch.clamp_max(t, y)
    # ❌ return torch.max(t, y)

x = torch.rand([5, 10, 1]).to(torch.int8)
y = torch.rand([10, 1]).to(torch.int8)

# ✔️ x, y are cuda tensors

# ❌ torch.bool, torch.int8, torch.int16, torch.uint8, torch.uint16
# ✔️ torch.int32, torch.int64

ret_eager = fn(x, y)
print('==== Eager mode OK! ====')

compiled = torch.compile(fn)
print('==== torchcomp compilation OK! ====')

ret_compiled = compiled(x, y)
print('==== torchcomp mode OK! ====')
```

<details><summary><b>Error log</b></summary>

```
==== Eager mode OK! ====
==== torchcomp compilation OK! ====
Traceback (most recent call last):
  File "repro.py", line 22, in <module>
    ret_compiled = compiled(x, y)
  File "python3.10/site-packages/torch/_dynamo/eval_frame.py", line 235, in _fn
    return fn(*args, **kwargs)
  File "python3.10/site-packages/torch/_dynamo/eval_frame.py", line 372, in catch_errors
    return callback(frame, cache_size, hooks)
  File "python3.10/site-packages/torch/_dynamo/convert_frame.py", line 412, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "python3.10/site-packages/torch/_dynamo/convert_frame.py", line 110, in _fn
    return fn(*args, **kwargs)
  File "python3.10/site-packages/torch/_dynamo/convert_frame.py", line 269, in _convert_frame_assert
    return _compile(
  File "python3.10/site-packages/torch/_dynamo/utils.py", line 166, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.10/site-packages/torch/_dynamo/convert_frame.py", line 331, in _compile
    out_code = transform_code_object(code, transform)
  File "python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 530, in transform_code_object
    transformations(instructions, code_options)
  File "python3.10/site-packages/torch/_dynamo/convert_frame.py", line 318, in transform
    tracer.run()
  File "python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1854, in run
    super().run()
  File "python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 604, in run
    and self.step()
  File "python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in step
    getattr(self, inst.opname)(inst)
  File "python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1933, in RETURN_VALUE
    self.output.compile_subgraph(
  File "python3.10/site-packages/torch/_dynamo/output_graph.py", line 581, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "python3.10/site-packages/torch/_dynamo/output_graph.py", line 651, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "python3.10/site-packages/torch/_dynamo/utils.py", line 166, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.10/site-packages/torch/_dynamo/output_graph.py", line 730, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "python3.10/site-packages/torch/_dynamo/output_graph.py", line 726, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "python3.10/site-packages/torch/_dynamo/debug_utils.py", line 1088, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "python3.10/site-packages/torch/__init__.py", line 1527, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "python3.10/site-packages/torch/_inductor/compile_fx.py", line 578, in compile_fx
    return aot_autograd(
  File "python3.10/site-packages/torch/_dynamo/backends/common.py", line 62, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3044, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "python3.10/site-packages/torch/_dynamo/utils.py", line 166, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2687, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1794, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1960, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1260, in aot_dispatch_base
    compiled_fw = compiler(fw_module, flat_args)
  File "python3.10/site-packages/torch/_dynamo/utils.py", line 166, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.10/site-packages/torch/_inductor/compile_fx.py", line 542, in fw_compiler_base
    return inner_compile(
  File "python3.10/site-packages/torch/_dynamo/debug_utils.py", line 622, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "python3.10/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "python3.10/site-packages/torch/_inductor/compile_fx.py", line 194, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "python3.10/site-packages/torch/_inductor/graph.py", line 666, in compile_to_fn
    return self.compile_to_module().call
  File "python3.10/site-packages/torch/_dynamo/utils.py", line 166, in time_wrapper
    r = func(*args, **kwargs)
  File "python3.10/site-packages/torch/_inductor/graph.py", line 642, in compile_to_module
    mod = PyCodeCache.load(code, linemap=linemap)
  File "python3.10/site-packages/torch/_inductor/codecache.py", line 645, in load
    return cls.load_by_key_path(key, path, linemap)
  File "python3.10/site-packages/torch/_inductor/codecache.py", line 660, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_/zx/czx4fhtl3knnqoxowgikjammt4bixjnyojep57ndf6hwewerkwr3.py", line 49, in <module>
    async_compile.wait(globals())
  File "python3.10/site-packages/torch/_inductor/codecache.py", line 876, in wait
    scope[key] = result.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "python3.10/site-packages/torch/_inductor/codecache.py", line 853, in task
    return CppCodeCache.load(source_code).kernel
  File "python3.10/site-packages/torch/_inductor/codecache.py", line 629, in load
    raise exc.CppCompileError(cmd, e.output) from e
torch._dynamo.exc.BackendCompilerFailed: backend='debug_wrapper' raised:
CppCompileError: C++ compile error

Command:
g++ /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp -shared -fPIC -Wall -std=c++17 -Wno-unused-variable -Ipython3.10/site-packages/torch/include -Ipython3.10/site-packages/torch/include/torch/csrc/api/include -Ipython3.10/site-packages/torch/include/TH -Ipython3.10/site-packages/torch/include/THC -I/usr/include/python3.10 -Lpython3.10/site-packages/torch/lib -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lgomp -DCPU_CAPABILITY_AVX2 -O3 -ffast-math -fno-finite-math-only -march=native -fopenmp -D C10_USING_CUSTOM_GENERATED_MACROS -o/tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.so

Output:
In file included from python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:8,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:10,
                 from /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:2:
python3.10/site-packages/torch/include/ATen/cpu/vec/vec_base.h:1025: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
 1025 | # pragma unroll
      | 
In file included from python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:10,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:10,
                 from /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:2:
python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_float.h:438: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  438 | #pragma unroll
      | 
python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_float.h:442: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  442 | #pragma unroll
      | 
In file included from python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:12,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:10,
                 from /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:2:
python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_bfloat16.h:693: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  693 | #pragma unroll
      | 
python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_bfloat16.h:698: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  698 | #pragma unroll
      | 
In file included from python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:13,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:10,
                 from /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:2:
python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_double.h:403: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  403 | #pragma unroll
      | 
python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_double.h:407: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  407 | #pragma unroll
      | 
In file included from python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256.h:14,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/vec.h:6,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/functional_base.h:6,
                 from python3.10/site-packages/torch/include/ATen/cpu/vec/functional.h:3,
                 from /tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:10,
                 from /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:2:
python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:287: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  287 | # pragma unroll
      | 
python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:295: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  295 | # pragma unroll
      | 
python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:307: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  307 | # pragma unroll
      | 
python3.10/site-packages/torch/include/ATen/cpu/vec/vec256/vec256_int.h:315: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  315 | # pragma unroll
      | 
In file included from /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:2:
/tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:77: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
   77 | #pragma unroll
      | 
/tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:86: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
   86 | #pragma unroll
      | 
/tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:122: warning: ignoring ‘#pragma unroll ’ [-Wunknown-pragmas]
  122 | #pragma unroll
      | 
/tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp: In function ‘void kernel(const signed char*, const signed char*, signed char*)’:
/tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:17:35: warning: self-comparison always evaluates to false [-Wtautological-compare]
   17 |                 auto tmp3 = (tmp1 != tmp1) ? tmp1 : std::min(tmp2, tmp1);
      |                              ~~~~ ^~ ~~~~
/tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:17:61: error: no matching function for call to ‘min(int&, signed char&)’
   17 |                 auto tmp3 = (tmp1 != tmp1) ? tmp1 : std::min(tmp2, tmp1);
      |                                                     ~~~~~~~~^~~~~~~~~~~~
In file included from /usr/include/c++/11/algorithm:61,
                 from /tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:1,
                 from /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:2:
/usr/include/c++/11/bits/stl_algobase.h:230:5: note: candidate: ‘template<class _Tp> constexpr const _Tp& std::min(const _Tp&, const _Tp&)’
  230 |     min(const _Tp& __a, const _Tp& __b)
      |     ^~~
/usr/include/c++/11/bits/stl_algobase.h:230:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:17:61: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘signed char’)
   17 |                 auto tmp3 = (tmp1 != tmp1) ? tmp1 : std::min(tmp2, tmp1);
      |                                                     ~~~~~~~~^~~~~~~~~~~~
In file included from /usr/include/c++/11/algorithm:61,
                 from /tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:1,
                 from /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:2:
/usr/include/c++/11/bits/stl_algobase.h:278:5: note: candidate: ‘template<class _Tp, class _Compare> constexpr const _Tp& std::min(const _Tp&, const _Tp&, _Compare)’
  278 |     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
/usr/include/c++/11/bits/stl_algobase.h:278:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:17:61: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘signed char’)
   17 |                 auto tmp3 = (tmp1 != tmp1) ? tmp1 : std::min(tmp2, tmp1);
      |                                                     ~~~~~~~~^~~~~~~~~~~~
In file included from /usr/include/c++/11/algorithm:62,
                 from /tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:1,
                 from /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:2:
/usr/include/c++/11/bits/stl_algo.h:3449:5: note: candidate: ‘template<class _Tp> constexpr _Tp std::min(std::initializer_list<_Tp>)’
 3449 |     min(initializer_list<_Tp> __l)
      |     ^~~
/usr/include/c++/11/bits/stl_algo.h:3449:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:17:61: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
   17 |                 auto tmp3 = (tmp1 != tmp1) ? tmp1 : std::min(tmp2, tmp1);
      |                                                     ~~~~~~~~^~~~~~~~~~~~
In file included from /usr/include/c++/11/algorithm:62,
                 from /tmp/torchinductor_/hw/chwr6vy6e6sd25sfh42qtywkuf2emodexm2aomp3lbrcxwznfwyi.h:1,
                 from /tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:2:
/usr/include/c++/11/bits/stl_algo.h:3455:5: note: candidate: ‘template<class _Tp, class _Compare> constexpr _Tp std::min(std::initializer_list<_Tp>, _Compare)’
 3455 |     min(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/usr/include/c++/11/bits/stl_algo.h:3455:5: note:   template argument deduction/substitution failed:
/tmp/torchinductor_/pr/cprgbrpws767xnx62v6vtnuwn4gume3dt5hiu3falizrfr2hqfmu.cpp:17:61: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
   17 |                 auto tmp3 = (tmp1 != tmp1) ? tmp1 : std::min(tmp2, tmp1);
      |                                                     ~~~~~~~~^~~~~~~~~~~~



You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

</details>

### Versions

<details><summary><b>Environment</b> <i>[Click to expand]</i></summary>

```
PyTorch version: 2.1.0.dev20230329+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 525.78.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] pytorch-triton==2.1.0+46672772b4
[pip3] torch==2.1.0.dev20230329+cu117
[pip3] torchaudio==2.1.0.dev20230329+cu117
[pip3] torchvision==0.16.0.dev20230329+cu117
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0
```

</details>

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by yanboliang** [comment]
Seems Inductor C++ backend issue. cc @XiaobingSuper @EikanWang @jgong5

**Comment by jgong5** [comment]
Asked @Valentine233 to take a look.
