### ISSUE TITLE
GroupNorm cpu/gpu parity tests fail with pretty large differences

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/pytorch#98089]
### 🐛 Describe the bug

Differences look too big to be tolerance errors, investigate why this is the case

```
 =================================== FAILURES ===================================
2023-03-31T17:42:23.8945917Z _________ TestModuleCUDA.test_cpu_gpu_parity_nn_GroupNorm_cuda_float32 _________
2023-03-31T17:42:23.8946180Z Traceback (most recent call last):
2023-03-31T17:42:23.8946431Z   File "test_modules.py", line 578, in test_cpu_gpu_parity
2023-03-31T17:42:23.8946690Z     check_backward(cpu_outputs, gpu_outputs)
2023-03-31T17:42:23.8946944Z   File "test_modules.py", line 570, in check_backward
2023-03-31T17:42:23.8947185Z     self.assertEqual(cpu_p.grad, gpu_p.grad)
2023-03-31T17:42:23.8947635Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3023, in assertEqual
2023-03-31T17:42:23.8947942Z     raise error_metas[0].to_error(
2023-03-31T17:42:23.8948212Z AssertionError: Tensor-likes are not close!
2023-03-31T17:42:23.8948359Z 
2023-03-31T17:42:23.8948451Z Mismatched elements: 6 / 6 (100.0%)
2023-03-31T17:42:23.8948716Z Greatest absolute difference: 9.029479503631592 at index (4,) (up to 0.05 allowed)
2023-03-31T17:42:23.8949112Z Greatest relative difference: 1.9686480656500926 at index (2,) (up to 1.3e-06 allowed)
```

### Versions

master

**Comment by albanD** [comment]
We should check the input range and size. These normalization kernel do big reduction and so can be sensitive to the way the reduction is done.
But it might be a real error where some intermediary computation is not done with the right precision. We should check which one matches the result from fp64 computation.
