### ISSUE TITLE
T5 model taking too long with torch compile.

### ISSUE THREAD

**Issue by AdamLouly** [pytorch/pytorch#98102]
### 🐛 Describe the bug

I have been trying to use the T5 model with the torch compile feature in PyTorch, but it seems to be taking an unreasonably long time to compile compared to using the eager mode.

how to reproduce using the transformers examples: 
go to this folder : transformers/examples/pytorch/translation/ 

**to run eager mode:** 
`python run_translation.py     --model_name_or_path t5-base     --do_train --do_eval    --source_lang en     --target_lang de     --source_prefix "translate English to German: "     --dataset_name stas/wmt14-en-de-pre-processed     --output_dir /tmp/tst-translation    --num_train_epochs 1 --per_device_train_batch_size=1     --max_train_samples 1000     --overwrite_output_dir     --seed 1137     --per_device_eval_batch_size 1     --max_eval_samples 1000   --fp16  --predict_with_generate
`

**to run torch compile:**
`python run_translation.py     --model_name_or_path t5-base     --do_train --do_eval    --source_lang en     --target_lang de     --source_prefix "translate English to German: "     --dataset_name stas/wmt14-en-de-pre-processed     --output_dir /tmp/tst-translation    --num_train_epochs 1 --per_device_train_batch_size=1     --max_train_samples 1000     --overwrite_output_dir     --seed 1137     --per_device_eval_batch_size 1     --max_eval_samples 1000   --fp16  --predict_with_generate --torch_compile 
`

Results : 
|                    | Eager Mode Result | Torch Compile Result |
|--------------------|------------------|----------------------|
| Avg of 2nd Half    | 127.83201 ms     | 7328.91910 ms         |
| Epoch              | 1.0              | 1.0                   |
| Train Loss         | 1.022            | 1.0191                |
| Train Runtime      | 0:02:52.89      | 5:43:32.32            |
| Train Samples      | 1000             | 1000                  |
| Train Samples/Second | 5.784            | 0.049                 |
| Train Steps/Second   | 5.784            | 0.049                 |
| Eval BLEU           | 29.0279          | 28.7266               |
| Eval Gen Len       | 33.0037          | 32.9691               |
| Eval Loss          | 1.0541           | 1.0543                |
| Eval Runtime       | 0:25:40.88      | 0:29:09.11            |
| Eval Samples       | 2169             | 2169                  |
| Eval Samples/Second | 1.408            | 1.24                  |
| Eval Steps/Second   | 1.408            | 1.24                  |

you can see that it took over 5hrs to run compared to only 2 mins for eager mode.

The problem happens in all T5 versions, as well as other models we've tested so far like jean-baptiste-camembert-ner and Summarization/sshleifer/distilbart-cnn-12-6 

### Versions

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+2c32f43999
[pip3] torch==2.1.0.dev20230313+cu117
[pip3] torch-ort==1.14.0
[pip3] torchaudio==2.0.0.dev20230313+cu117
[pip3] torchvision==0.15.0.dev20230313+cu117
[pip3] triton==2.0.0
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+2c32f43999          pypi_0    pypi
[conda] torch                     2.1.0.dev20230313+cu117          pypi_0    pypi
[conda] torch-ort                 1.14.0                   pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230313+cu117          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230313+cu117          pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by yanboliang** [comment]
Can you print and share ```torch._dynamo.utils.compilation_metrics```?

**Comment by ezyang** [comment]
At a guess, you need to use dynamic=True.

**Comment by AdamLouly** [comment]
> torch._dynamo.utils.compilation_metrics

that's the output :  OrderedDict([('_compile', [28.510122776031494, 0.006930112838745117, 0.002085447311401367, 0.0017774105072021484]), ('OutputGraph.call_user_compiler', [23.453813552856445]), ('create_aot_dispatcher_function', [20.985525846481323]), ('compile_fx.<locals>.fw_compiler', [6.880029678344727]), ('GraphLowering.run', [1.3998785018920898, 1.8204922676086426]), ('GraphLowering.compile_to_module', [4.990485668182373, 5.290128231048584]), ('Scheduler.__init__', [2.3708276748657227, 2.292379140853882]), ('Scheduler.codegen', [1.463493824005127, 1.810530424118042]), ('WrapperCodeGen.generate', [0.19363665580749512, 0.2001209259033203]), ('compile_fx.<locals>.bw_compiler', [7.222400903701782])])



> At a guess, you need to use dynamic=True.
I modified the trainer.py in transformers torch.compile and added Dynamic = True as a parameter, but it will fail with a different error, 

```
    assert not e.free_symbols, f"free variables NYI: {e}"
AssertionError: free variables NYI: 32128*s26
```

**Comment by yanboliang** [comment]
> that's the output : OrderedDict([('_compile', [28.510122776031494, 0.006930112838745117, 0.002085447311401367, 0.0017774105072021484]), ('OutputGraph.call_user_compiler', [23.453813552856445]), ('create_aot_dispatcher_function', [20.985525846481323]), ('compile_fx..fw_compiler', [6.880029678344727]), ('GraphLowering.run', [1.3998785018920898, 1.8204922676086426]), ('GraphLowering.compile_to_module', [4.990485668182373, 5.290128231048584]), ('Scheduler.init', [2.3708276748657227, 2.292379140853882]), ('Scheduler.codegen', [1.463493824005127, 1.810530424118042]), ('WrapperCodeGen.generate', [0.19363665580749512, 0.2001209259033203]), ('compile_fx..bw_compiler', [7.222400903701782])])

Nothing looks suspicious and indicates where takes 5 hours.
Can you print out ```torch._dynamo.utils.counters``` and check if there is abnormal recompilation?

**Comment by ezyang** [comment]
I patched this in:

```
diff --git a/src/transformers/trainer.py b/src/transformers/trainer.py
index 2eb081af7..f299ef878 100755
--- a/src/transformers/trainer.py
+++ b/src/transformers/trainer.py
@@ -1573,7 +1573,7 @@ class Trainer:
         # torch.compile() needs to be called after wrapping the model with FSDP or DDP
         # to ensure that it accounts for the graph breaks required by those wrappers
         if self.args.torch_compile:
-            model = torch.compile(model, backend=self.args.torch_compile_backend, mode=self.args.torch_compile_mode)
+            model = torch.compile(model, backend=self.args.torch_compile_backend, mode=self.args.torch_compile_mode, dynamic=True)
 
         return model
```

and then ran the example. It doesn't appear to error, but it does not seem to have improved perf:

```
  epoch                    =        1.0
  train_loss               =     1.0298
  train_runtime            = 0:03:42.51
  train_samples            =       1000
  train_samples_per_second =      4.494
  train_steps_per_second   =      0.562
```

I don't have loss as it failed due to some other problem

```
Traceback (most recent call last):                                                                                           
  File "/data/users/ezyang/a/transformers/examples/pytorch/translation/run_translation.py", line 664, in <module>
    main()                                                                                                                   
  File "/data/users/ezyang/a/transformers/examples/pytorch/translation/run_translation.py", line 605, in main                
    metrics = trainer.evaluate(max_length=max_length, num_beams=num_beams, metric_key_prefix="eval")                         
  File "/data/users/ezyang/a/transformers/src/transformers/trainer_seq2seq.py", line 159, in evaluate
    return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)                      
  File "/data/users/ezyang/a/transformers/src/transformers/trainer.py", line 2990, in evaluate                               
    output = eval_loop(                                                                                                      
  File "/data/users/ezyang/a/transformers/src/transformers/trainer.py", line 3171, in evaluation_loop                        
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)                
  File "/data/users/ezyang/a/transformers/src/transformers/trainer_seq2seq.py", line 280, in prediction_step
    gen_config = model.generation_config                                                                                     
  File "/data/users/ezyang/a/pytorch/torch/nn/modules/module.py", line 1614, in __getattr__                                  
    raise AttributeError("'{}' object has no attribute '{}'".format(                                                         
AttributeError: 'DataParallel' object has no attribute 'generation_config'  
```

**Comment by stas00** [comment]
```
  File "/data/users/ezyang/a/transformers/src/transformers/trainer_seq2seq.py", line 280, in prediction_step
    gen_config = model.generation_config                                                                                     
  File "/data/users/ezyang/a/pytorch/torch/nn/modules/module.py", line 1614, in __getattr__                                  
    raise AttributeError("'{}' object has no attribute '{}'".format(                                                         
AttributeError: 'DataParallel' object has no attribute 'generation_config'  
```

Looks like it got `self.model` to be wrapped in `DataParallel` which doesn't know anything about the model's real attributes.

I think somewhere some wrong assumption is made, could you please re-run with `CUDA_VISIBLE_DEVICES=0` which would not trigger `DataParallel` wrapping.

**Comment by ezyang** [comment]
Once I apply @stas00's change to make it stop using DataParallel, I also see that the script now takes a very long time to run, even with dynamic=True.

**Comment by ezyang** [comment]
@AdamLouly can you confirm that a more recent nightly + dynamic=True advances you past the "NYI" error, and gets you slow compilation again? I think this makes sense to me, that we fixed the NYI.

**Comment by stas00** [comment]
@ezyang, sorry, I changed the cmd line args while I was testing so it was quick to run - I changed `--max_train_samples 10`, I think to match the original you need `--max_train_samples 1000`, so:

```
cd transformers
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python \
examples/pytorch/translation/run_translation.py --model_name_or_path t5-base \
--do_train --source_lang en --target_lang de --source_prefix \
'translate English to German: ' --dataset_name stas/wmt14-en-de-pre-processed \
--output_dir /tmp/tst-translation --num_train_epochs 1 \
--per_device_train_batch_size=1 --max_train_samples 1000 --overwrite_output_dir \
--seed 1137 --per_device_eval_batch_size 1 --fp16

```

**Comment by stas00** [comment]
@AdamLouly, your 2 entries to compare in the OP aren't matching on their common parts:

to run eager mode:
python run_translation.py     --model_name_or_path t5-base     --do_train --do_eval    --source_lang en     --target_lang de     --source_prefix "translate English to German: "     --dataset_name stas/wmt14-en-de-pre-processed     --output_dir /tmp/tst-translation    --num_train_epochs 1 --per_device_train_batch_size=1     --max_train_samples 1000     --overwrite_output_dir     --seed 1137     --per_device_eval_batch_size 1     --max_train_samples 1000     --predict_with_generate --fp16  

to run torch compile:
python run_translation.py     --model_name_or_path t5-base     --do_train --do_eval    --source_lang en     --target_lang de     --source_prefix "translate English to German: "     --dataset_name stas/wmt14-en-de-pre-processed     --output_dir /tmp/tst-translation    --num_train_epochs 1 --per_device_train_batch_size=1     --max_train_samples 1000     --overwrite_output_dir     --seed 1137     --per_device_eval_batch_size 1     --max_eval_samples 1000   --fp16  --predict_with_generate --torch_compile  

in the first one you mistakengly used `--max_train_samples 1000` twice. The second time it probably had to be `--max_eval_samples 1000` - so that apples to apples are compared.

**Comment by AdamLouly** [comment]
> 

Hey, I ran it using the latest nightly version, and these are the results
***** train metrics *****
  epoch                    =        1.0
  train_loss               =     0.7757
  train_runtime            = 0:29:06.93
  train_samples            =         10
  train_samples_per_second =      0.006
  train_steps_per_second   =      0.006

note that you have to add --torch_compile in your example.

**Comment by AdamLouly** [comment]
> 

correct, its supposed to be eval steps.

**Comment by stas00** [comment]
> correct, its supposed to be eval steps.

Then it might be a good idea to fix the OP, no? Others won't be able to repro your report w/o it.

**Comment by ezyang** [comment]
With a few local changes (need https://github.com/pytorch/pytorch/pull/98347 and https://github.com/pytorch/pytorch/pull/98223 and https://github.com/pytorch/pytorch/pull/98350), here is a log from dynamic=True: https://gist.github.com/ezyang/25be1fc14312c34fdfcddad895225877

Repro with

```
PYTHONUNBUFFERED=1 WANDB_DISABLED=true TORCH_LOGS=dynamo,guards CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python examples/pytorch/translation/run_translation.py --model_name_or_path t5-base --do_train --source_lang en --target_lang de --source_prefix 'translate English to German: ' --dataset_name stas/wmt14-en-de-pre-processed --output_dir /tmp/tst-translation --num_train_epochs 1 --per_device_train_batch_size=1 --max_train_samples 1000 --overwrite_output_dir --seed 1137 --per_device_eval_batch_size 1 --fp16 --torch_compile 2>&1 | tee tran2.log
```

Among other interesting things,  `L['input_ids'].size()[1]` keeps getting new guards issued for it: 

```
$ grep "input_ids'\].size()\[1\] <" ../transformers/tran2.log
  L['input_ids'].size()[1] < 33
  L['decoder_input_ids'].size()[1] < 17
  L['input_ids'].size()[1] < 33
  L['input_ids'].size()[1] < 129
  L['input_ids'].size()[1] < 65
  L['decoder_input_ids'].size()[1] < 65
  L['input_ids'].size()[1] < 33
```

**Comment by AdamLouly** [comment]
> > correct, its supposed to be eval steps.
> 
> Then it might be a good idea to fix the OP, no? Others won't be able to repro your report w/o it.

@stas00  I just did thank you,


@ezyang how long did it took to finish? did it resolve the perf issue?

**Comment by ezyang** [comment]
@AdamLouly 

```
  epoch                    =        1.0
  train_loss               =     1.0189
  train_runtime            = 0:40:49.77
  train_samples            =       1000
  train_samples_per_second =      0.408
  train_steps_per_second   =      0.408
```

It is better, but still not great. I think the problem now is that Inductor is specializing too aggressively and we need to make it generate more generic kernels. The first thing to do is kill the modulus of 16 specialization (cc @jansel)

**Comment by ngimel** [comment]
tbh, I don't think we can kill modulus 16 specialization without serious perf consequences.

**Comment by ngimel** [comment]
The guards above look like persistent reduction guards, so probably we should try disabling persistent reduction (there's a config for that)?

**Comment by ezyang** [comment]
YOOOO 2x speedup

```
  epoch                    =        1.0
  train_loss               =     1.0188
  train_runtime            = 0:05:26.29
  train_samples            =       1000
  train_samples_per_second =      3.065
  train_steps_per_second   =      3.065
```

This is with

```
diff --git a/torch/_inductor/sizevars.py b/torch/_inductor/sizevars.py
index e8ca94f0d44..587da12ce47 100644
--- a/torch/_inductor/sizevars.py
+++ b/torch/_inductor/sizevars.py
@@ -288,6 +288,7 @@ class SizeVarAllocator:
         if sympy.gcd(numerator, denominator) == denominator:
             # can prove it symbolically
             return True
+        return False
         if self.size_hint(numerator) % self.size_hint(denominator) == 0:
             self.guard_equals(numerator % denominator, 0)
             return True
```

**Comment by ngimel** [comment]
we need padding to multiple of 16

**Comment by ezyang** [comment]
With @AdamLouly's updated trainer, here are the avg of 2nd half results with persistent reductions and divisible by 16 annotations turned off:

With torch.compile: Avg of 2nd half: 50.84254 ms
Without torch.compile: Avg of 2nd half: 96.06191 ms

So that's now a nearly 2x speedup.

**Comment by ezyang** [comment]
Interesting negative result: turning divisible by 16 back on quadruples compile time, and makes perf worse: Avg of 2nd half: 57.60326 ms

**Comment by AdamLouly** [comment]
> Interesting negative result: turning divisible by 16 back on quadruples compile time, and makes perf worse: Avg of 2nd half: 57.60326 ms

how can I reproduce this?

**Comment by ezyang** [comment]
I finished landing all the fixes to master just now. If you take a master build f98c1809a42f49d64849f66ea0abc939377b96f7 or later, you should be able to run your experiment as is (using your modified trainer script, and with dynamic=True on torch.compile) without any other changes. I am running

```
PYTHONUNBUFFERED=1 WANDB_DISABLED=true TORCH_LOGS=dynamo,inductor,guards CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src pp python examples/pytorch/translation/run_translation.py --model_name_or_path t5-base --do_train --source_lang en --target_lang de --source_prefix 'translate English to German: ' --dataset_name stas/wmt14-en-de-pre-processed --output_dir /tmp/tst-translation --num_train_epochs 1 --per_device_train_batch_size=1 --max_train_samples 1000 --overwrite_output_dir --seed 1137 --per_device_eval_batch_size 1 --fp16 --torch_compile
```

on this version and I will double check that this reproduces.

To reproduce the negative result, revert bdb79a8f5254bdbe4dcc08d74548d6b8e9926405 and run the same command as before.

**Comment by AdamLouly** [comment]
@ezyang noob question, where do I change skip_nnmodule_hook_guards = True ?

**Comment by wconstab** [comment]
`torch._dynamo.config.skip_nnmodule_hook_guards`

**Comment by anijain2305** [comment]
Closing due to inactivity. Please reopen if issue still exists.
