### ISSUE TITLE
[pt2] `movedim` + `add_` + `cat` triggers exception

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#98122]
### 🐛 Describe the bug

The following program works fine in eager mode but triggers RuntimeError when using `torch.compile`.
* On GPU the issue still exists.
* All the three operators are necessary for triggering the exception.
```python
import torch

def fn(x):
    # x: (2, 2, 3, 3, 2)
    v1_0 = torch.movedim(x, source=1, destination=2)
    v4_0 = x.add_(1)
    v0_0 = torch.cat([v4_0, v4_0], dim=2) # v0_0: (2, 2, 6, 3, 2)
    return [v1_0, v0_0]

x = torch.rand([2, 2, 3, 3, 2])

ret_eager = fn(x)
print('==== Eager mode OK! ====')

compiled = torch.compile(fn)
print('==== torchcomp compilation OK! ====')

ret_compiled = compiled(x)
print('==== torchcomp mode OK! ====')

"""
==== Eager mode OK! ====
==== torchcomp compilation OK! ====
Traceback (most recent call last):
  File "repro.py", line 18, in <module>
    ret_compiled = compiled(x)
  File "python3.10/site-packages/torch/_dynamo/eval_frame.py", line 237, in _fn
    return fn(*args, **kwargs)
  File "/home/yuyao/bug_repro/repro.py", line 3, in fn
    def fn(v3_0):
  File "python3.10/site-packages/torch/_dynamo/eval_frame.py", line 237, in _fn
    return fn(*args, **kwargs)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3065, in forward
    return compiled_fn(full_args)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1182, in g
    return f(*args)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2202, in runtime_wrapper
    regenerated_out = gen_alias_from_base(aliased_base_tensor, o_, o_grad)
  File "python3.10/site-packages/torch/_functorch/aot_autograd.py", line 576, in gen_alias_from_base
    reshaped_base_tensor = aliased_base_tensor.as_strided(
RuntimeError: setStorage: sizes [2, 2, 6, 3, 2], strides [72, 36, 6, 2, 1], storage offset 0, and itemsize 4 requiring a storage size of 576 are out of bounds for storage of size 288
"""
```

### Versions

<details><summary><b>Environment</b> <i>[Click to expand]</i></summary>

```
PyTorch version: 2.1.0.dev20230331+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 525.78.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] pytorch-triton==2.1.0+46672772b4
[pip3] torch==2.1.0.dev20230331+cu117
[pip3] torchaudio==2.1.0.dev20230331+cu117
[pip3] torchvision==0.16.0.dev20230331+cu117
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0
```

</details>

**Comment by yanboliang** [comment]
This passed eager and aot_eager backend, identified as inductor issue. cc @ngimel

**Comment by eellison** [comment]
no longer repros.
