### ISSUE TITLE
torch.cuda.DeferredCudaCallError

### ISSUE THREAD

**Issue by Mahrkeenerh** [pytorch/pytorch#98172]
### 🐛 Describe the bug

I would very much like to provide all the required info on this, but there's quite a lot of stuff I've modified, and the model itself is not public yet.

quick version - I tried to run a modified hugging face vision encoder decoder model (vit + gpt2) on two nvidia A100 GPUs, and got this error.

When I tried with just one, it works fine. It also was working just fine until the last iteration, and I will probably try to find the specific reason why it doesn't work. If I find it, I'll post a follow-up.

If you have any idea what might have caused this, I will be happy to provide further details.

### Versions

```
Collecting environment information...
Traceback (most recent call last):
  File "/home/xbuban1/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 242, in _lazy_init
    queued_call()
  File "/home/xbuban1/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 125, in _check_capability
    capability = get_device_capability(d)
  File "/home/xbuban1/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 357, in get_device_capability
    prop = get_device_properties(device)
  File "/home/xbuban1/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 375, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "collect_env.py", line 605, in <module>
    main()
  File "collect_env.py", line 588, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 583, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 454, in get_env_info
    cuda_module_loading=get_cuda_module_loading_config(),
  File "collect_env.py", line 409, in get_cuda_module_loading_config
    torch.cuda.init()
  File "/home/xbuban1/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 198, in init
    _lazy_init()
  File "/home/xbuban1/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 246, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch.

CUDA call was originally invoked at:

['  File "collect_env.py", line 15, in <module>\n    import torch\n', '  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 848, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n', '  File "/home/xbuban1/.local/lib/python3.8/site-packages/torch/__init__.py", line 798, in <module>\n    _C._initExtension(manager_path())\n', '  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 848, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n', '  File "/home/xbuban1/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 179, in <module>\n    _lazy_call(_check_capability)\n', '  File "/home/xbuban1/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 177, in _lazy_call\n    _queued_calls.append((callable, traceback.format_stack()))\n']
```

cc @ngimel

**Comment by Mahrkeenerh** [comment]
This error was caused by an error when setting up nvidia MIG on the server.

**Comment by ngimel** [comment]
Please provide your environment collected via torch/utils/collect_env.py

**Comment by Mahrkeenerh** [comment]
I don't know enough about the architecture to know, if this could be fixed or bypassed, so I suppose so?

**Comment by dathudeptrai** [comment]
@ngimel @Mahrkeenerh I met the same problem, is there any solution ?

**Comment by Mahrkeenerh** [comment]
@dathudeptrai 
Did you also setup MIG on your server? If so, it doesn't look like that's compatible with parallel processing, so you'll either have to disable it, or run on a single instance.

**Comment by dathudeptrai** [comment]
@Mahrkeenerh, somehow my torch program can not recognize some GPU ids. For example the nvidia-smi show I have 8 GPUS but some how torch is only able to recognize the first 4 GPUs

**Comment by Mahrkeenerh** [comment]
@dathudeptrai that seems like a separate issue

Do you have 8 physical GPUs? If not, then you won't be able to run something parallel on 8 of them

**Comment by dathudeptrai** [comment]
@Mahrkeenerh yeah I think something wrong with my lambdalambs instances. Now, if I set the  CUDA_VISIBLE_DEVICES is 0,1,2,3,4 then it run on GPU ids: 0,2,4,6 :))).

**Comment by miccooper9** [comment]
@dathudeptrai I am facing the same issue. I can only run on gpu_ids = 0,2,3,4 even though i have 8 gpus. Were you able to fix this issue ?

**Comment by Mahrkeenerh** [comment]
@miccooper9 The issue in my case was using MIG, which is not compatible with parallel computing
