### ISSUE TITLE
Bad error message when OOM with torch.compile

### ISSUE THREAD

**Issue by jcjohnson** [pytorch/pytorch#98186]
### 🐛 Describe the bug

When I run a model that has been `torch.compile`d that runs out of GPU memory, I see one of two things happen:

(1) A nice error message saying that I ran of of memory (good)
(2) A confusing cascade of exceptions deep into the guts of `torch._dynamo` that gives no indication that OOM was the root cause (bad)

The smallest example I could find that consistently triggers (2) is a model consisting of nothing but two Dropout layers. In the attached code below, setting `should_compile=False` or `num_dropout=1` triggers (1).

### Error logs

```
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 937, in build_triton_ir
    generator.visit(fn.parse())
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 183, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 252, in visit_FunctionDef
    has_ret = self.visit_compound_statement(node.body)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 177, in visit_compound_statement
    self.last_ret_type = self.visit(stmt)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 301, in visit_Assign
    values = self.visit(node.value)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 778, in visit_Call
    generator.visit(fn.parse())
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 183, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 252, in visit_FunctionDef
    has_ret = self.visit_compound_statement(node.body)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 177, in visit_compound_statement
    self.last_ret_type = self.visit(stmt)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 301, in visit_Assign
    values = self.visit(node.value)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 797, in visit_Call
    return fn(*args, _builder=self.builder, **kws)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/impl/base.py", line 22, in wrapper
    return fn(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/language/core.py", line 653, in to
    return semantic.bitcast(self, dtype, _builder)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/language/semantic.py", line 633, in bitcast
    raise ValueError("Cannot bitcast data-type of size " + str(src_bits) + "to "
ValueError: Cannot bitcast data-type of size 64to data-type of size 32

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 549, in _worker_compile
    kernel.precompile(warm_cache_only_with_cc=cc)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 69, in precompile
    self.launchers = [
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 70, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 83, in _precompile_config
    triton.compile(
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 1620, in compile
    next_module = compile(module)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 1549, in <lambda>
    lambda src: ast_to_ttir(src, signature, configs[0], constants)),
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 962, in ast_to_ttir
    mod, _ = build_triton_ir(fn, signature, specialization, constants)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/triton/compiler.py", line 942, in build_triton_ir
    raise CompilationError(fn.src, node) from e
triton.compiler.CompilationError: at 11:25:
def triton_(seed0, in_ptr1, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 4294967296
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0_load = tl.load(seed0 + (0))
    tmp0 = tl.broadcast_to(tmp0_load, [XBLOCK])
    tmp10 = tl.load(in_ptr1 + (x0), xmask)
    tmp1 = 4294967296 + x0
    tmp2 = tl.rand(tmp0, tmp1)
                         ^
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 670, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/__init__.py", line 1390, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 455, in compile_fx
    return aot_autograd(
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2805, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2498, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1713, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1326, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args_with_views_handled)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 430, in fw_compiler
    return inner_compile(
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 177, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/graph.py", line 586, in compile_to_fn
    return self.compile_to_module().call
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/graph.py", line 575, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 528, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_justin/cc/ccc2hm7aocw4viyw7ve73pqddjvlbjkymfxjnl7t2qaouryyswaw.py", line 58, in <module>
    async_compile.wait(globals())
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 715, in wait
    scope[key] = result.result()
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 573, in result
    self.future.result()
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
triton.compiler.CompilationError: at 11:25:
def triton_(seed0, in_ptr1, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 4294967296
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0_load = tl.load(seed0 + (0))
    tmp0 = tl.broadcast_to(tmp0_load, [XBLOCK])
    tmp10 = tl.load(in_ptr1 + (x0), xmask)
    tmp1 = 4294967296 + x0
    tmp2 = tl.rand(tmp0, tmp1)
                         ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/justin/code/transformer-benchmarks/repro.py", line 13, in <module>
    out = model(x)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 517, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/justin/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised CompilationError: at 11:25:
def triton_(seed0, in_ptr1, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 4294967296
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0_load = tl.load(seed0 + (0))
    tmp0 = tl.broadcast_to(tmp0_load, [XBLOCK])
    tmp10 = tl.load(in_ptr1 + (x0), xmask)
    tmp1 = 4294967296 + x0
    tmp2 = tl.rand(tmp0, tmp1)
                         ^

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Minified repro

```python
import torch

should_compile = True
num_dropout = 2

layers = [torch.nn.Dropout(0.5) for _ in range(num_dropout)]
model = torch.nn.Sequential(*layers).cuda()
if should_compile:
    model = torch.compile(model)

x = torch.randn(1024 * 1024, 4096, device='cuda')
out = model(x)
```

### Versions

PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 9 7950X 16-Core Processor
CPU family:                      25
Model:                           97
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
Stepping:                        2
Frequency boost:                 enabled
CPU max MHz:                     5879.8818
CPU min MHz:                     3000.0000
BogoMIPS:                        8983.04
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d
Virtualization:                  AMD-V
L1d cache:                       512 KiB (16 instances)
L1i cache:                       512 KiB (16 instances)
L2 cache:                        16 MiB (16 instances)
L3 cache:                        64 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.5           py39h14f4228_0  
[conda] numpy-base                1.23.5           py39h31eccc5_0  
[conda] pytorch                   2.0.0           py3.9_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_3    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.0                py39_cu118    pytorch
[conda] torchtriton               2.0.0                      py39    pytorch
[conda] torchvision               0.15.0               py39_cu118    pytorch

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by yanboliang** [comment]
cc @mlazos

**Comment by mlazos** [comment]
This actually isn't an oom this is a compilation error from Triton, could you share the original error trace @jcjohnson? I'm thinking that you saw the oom after falling back to eager, but want to make sure this is the case.

**Comment by jcjohnson** [comment]
@mlazos when I set `torch._dynamo.config.verbose = True` and rerun my reproduction script, [this is the entire output to stderr](https://gist.github.com/jcjohnson/c1ca634ae0fba315a7a9c7b402a9d552). It looks pretty much the same as the stack trace I posted above, is there any other way to get more detailed debugging info?

**Comment by jcjohnson** [comment]
Also if I make `x` smaller (e.g. shape 1024 x 1024) so the eager mode version doesn't OOM, then it runs without error when compiled as well.

**Comment by mlazos** [comment]
Hmm I think I was just curious why you thought it was an OOM, other than eager OOMing? There doesn't look to be an indication of an OOM in the logs.

**Comment by jcjohnson** [comment]
In this example at least, the input is 4B float32; that takes 16GB. If dropout is in-place but you still need to store a boolean mask, each mask will take another 4GB, so I'd expect the whole forward pass here to take 24GB of memory. This is running on a 4090 in my desktop, which has 24GB of VRAM (some of which is used to drive the display) so this computation should go OOM unless either the dropout masks are not being stored, or they are being stored more compactly than one byte per element of the input tensor.

I originally got here by running speed and memory benchmarks of Transformers of varying sizes, trying to see how big I could go with just barely avoiding OOM, and started seeing these crashes in some larger models. It could be possible that this particular crash is actually unrelated to OOM, but I haven't been able to trigger it on any computations that I'd expect to fit in memory.

**Comment by mlazos** [comment]
Ok makes sense thank you, the solution is to add a check in inductor which will throw on values that are too large to fit in a 32 bit value. I can get to this later this week.

**Comment by mlazos** [comment]
I see, yeah the longer term fix here would be to split the dropout across multiple kernels to make sure you can run it. I can also look into that vs. the better assert.

**Comment by ngimel** [comment]
This is a duplicate of #93606 (not oom part, int64 argument to tl.rand). I think this would hit not only for large tensors - rand accumulates offset between kernel, so a series of dropouts on smaller inputs could also get to this situation. We'd need a more serious refactor of `rand` to solve this, ideally combined with efficiency improvements (currently we throw away 3 out of 4 generated randoms).

**Comment by jcjohnson** [comment]
Thanks @ngimel for the pointer! I think this is worth fixing, as it will come up in practice when training large transformers. In particular, the hidden layer of the FFN in a transformer often uses dropout on a tensor of shape (batch_size, 4 * model_dim, context_size); [PaLM](https://arxiv.org/abs/2204.02311) uses model_dim = 18,432, and GPT4 uses context_size = 32K (they don't disclose model_dim). Putting these together means you are running dropout on a tensor with 2.4B entries when training with batch_size = 1, so you'll easily exceed int32 on the forward pass of even a small chunk of such a model, especially if the rand offset accumulates across kernels.

**Comment by mlazos** [comment]
closing this as a dupe of https://github.com/pytorch/pytorch/issues/93606
