### ISSUE TITLE
assert GLOBALS.in_onnx_export is False when call torch.onnx.export

### ISSUE THREAD

**Issue by shirlyyang-tcc** [pytorch/pytorch#98271]
### 🐛 Describe the bug

I am trying to convert pytorch to onnx model with torch.onnx.torch, when I run the script It reports following errors ans I can't find reason.  I try to run code in offical document and get same error. Don't know how it comes and how to solve it.

my code:
```python
import torch
import torchvision
device = torch.device('cpu')
dummy_input = torch.randn(10, 3, 224, 224)
model = torchvision.models.alexnet(weights=torchvision.models.AlexNet_Weights.DEFAULT).cpu()


input_names = [ "actual_input_1" ] + [ "learned_%d" % i for i in range(16) ]
output_names = [ "output1" ]

torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)
```

got error:
```
[root@VM-117-21-centos src]# python3 onnx.py 
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "/root/nails_segmentation/src/onnx.py", line 56, in <module>
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/onnx/utils.py", line 1620, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/onnx/_internal/onnx_proto_utils.py", line 219, in _add_onnxscript_fn
    import onnx
  File "/root/nails_segmentation/src/onnx.py", line 56, in <module>
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/onnx/utils.py", line 1468, in _export
    assert GLOBALS.in_onnx_export is False
AssertionError
```

### Versions

got same error on two machines:
machine1:
```
Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: TencentOS Server 3.2 (Final) (x86_64)
GCC version: (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
Clang version: 11.0.0 (Red Hat 11.0.0-1.module_tl3+111+365647ce)
CMake version: version 3.26.0
Libc version: glibc-2.28

Python version: 3.9.16 (main, Apr  3 2023, 16:48:53)  [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] (64-bit runtime)
Python platform: Linux-5.4.119-1-tlinux4-0010.2-x86_64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      Smdbmds
CPU family:          6
Model:               94
Model name:          Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz
BIOS Model name:     3.0
Stepping:            3
CPU MHz:             2494.130
BogoMIPS:            4988.26
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            28160K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 arat

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.24.2
[pip3] segmentation-models-pytorch==0.3.0
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] Could not collect
```

machine2:
```
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2)
CMake version: version 3.25.2
Libc version: N/A

Python version: 3.8.16 (default, Mar 30 2023, 19:32:13)  [Clang 13.1.6 (clang-1316.0.21.2)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.24.2
[pip3] segmentation-models-pytorch==0.3.0
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchvision==0.15.1
[conda] Could not collect
```

**Comment by pat749** [comment]
You have not installed `onnx` module You need to install the `onnx `package to use the `torch.onnx` module to export PyTorch models to the `ONNX` format. You can install it using `pip`:
```
pip install onnx
```
Here is the [implementation](https://colab.research.google.com/drive/1ZCf8ApZbz_kRlyfbqvbyYi3sPRZ5Kl3s?usp=sharing) of this code without error in colab.

```
import torch
import torchvision
import onnx

device = torch.device('cpu')
dummy_input = torch.randn(10, 3, 224, 224)
model = torchvision.models.alexnet(weights=torchvision.models.AlexNet_Weights.DEFAULT).cpu()

input_names = [ "actual_input_1" ] + [ "learned_%d" % i for i in range(16) ]
output_names = [ "output1" ]

torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)

# Load the saved ONNX model
onnx_model = onnx.load("alexnet.onnx")

# Print the ONNX model
print(onnx_model)
```
OUTPUT: 
```
============= Diagnostic Run torch.onnx.export version 2.0.0+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs) 
```
Please see the google colab link above for more.
Thank you

**Comment by thiagocrepaldi** [comment]
Either your `pytorch` or `onnx` are corrupted (or `onnx` is not installed, as mentioned by @pat749)
do a `pip uninstall torch onnx` followed by `pip install torch onnx` and try again

@pat749 thank you for helping in several issues. We really appreciate it!

**Comment by shirlyyang-tcc** [comment]
solved, thank you very much

**Comment by AUTOMATIC1111** [comment]
For people who find this page via search, one possibility for why this could be happening is because you created a file named `onnx.py` - and, in fact, the cause here is exactly that - you can see the file `/root/nails_segmentation/src/onnx.py` in the stack trace.

**Comment by fabyr** [comment]
> For people who find this page via search, one possibility for why this could be happening is because you created a file named `onnx.py` - and, in fact, the cause here is exactly that - you can see the file `/root/nails_segmentation/src/onnx.py` in the stack trace.

It does in-fact raise an empty AssertionError without any more information if your python script is called "onnx.py". If that is not the case, you get the proper "Module onnx is not installed!" exception.
Exactly what happened to me 😅

**Comment by linrio** [comment]
> For people who find this page via search, one possibility for why this could be happening is because you created a file named `onnx.py` - and, in fact, the cause here is exactly that - you can see the file `/root/nails_segmentation/src/onnx.py` in the stack trace.

In factly, I created a file named 'onnx.py'. Solved it!

**Comment by cfl-chenfangliang** [comment]
> For people who find this page via search, one possibility for why this could be happening is because you created a file named `onnx.py` - and, in fact, the cause here is exactly that - you can see the file `/root/nails_segmentation/src/onnx.py` in the stack trace.

还真是，谢谢你嘞

**Comment by xdd12135** [comment]
> > For people who find this page via search, one possibility for why this could be happening is because you created a file named `onnx.py` - and, in fact, the cause here is exactly that - you can see the file `/root/nails_segmentation/src/onnx.py` in the stack trace.
> 
> It does in-fact raise an empty AssertionError without any more information if your python script is called "onnx.py". If that is not the case, you get the proper "Module onnx is not installed!" exception. Exactly what happened to me 😅

nb
