### ISSUE TITLE
TestReduceFrontSum.test_col2im_gradients flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#9832]
Sample log:

```
8:04:53 =================================== FAILURES ===================================
18:04:53 ___________________ TestReduceFrontSum.test_col2im_gradients ___________________
18:04:53 
18:04:53 self = <caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>
18:04:53 
18:04:53     @given(batch_size=st.integers(1, 3),
18:04:53 >          stride=st.integers(1, 3),
18:04:53            pad=st.integers(0, 3),
18:04:53            kernel=st.integers(1, 5),
18:04:53            dilation=st.integers(1, 3),
18:04:53            size=st.integers(7, 10),
18:04:53            channels=st.integers(1, 8),
18:04:53            order=st.sampled_from(["NCHW"]),
18:04:53            **hu.gcs)
18:04:53     def test_col2im_gradients(self, batch_size, stride, pad, kernel,
18:04:53                               dilation, size, channels, order, gc, dc):
18:04:53 
18:04:53 lib/python2.7/dist-packages/caffe2/python/operator_test/im2col_col2im_test.py:115: 
18:04:53 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
18:04:53 ../lib/python2.7/dist-packages/hypothesis/core.py:632: in execute
18:04:53     ) % (test.__name__, text_repr[0],))
18:04:53 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
18:04:53 
18:04:53 self = <hypothesis.core.StateForActualGivenExecution object at 0x7f47b9e94410>
18:04:53 message = "Hypothesis test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=t...7, order=u'NCHW', gc=, dc=[]) produces unreliable results: Falsified on the first call but did not on a subsequent one"
18:04:53 
18:04:53     def __flaky(self, message):
18:04:53         if len(self.falsifying_examples) <= 1:
18:04:53 >           raise Flaky(message)
18:04:53 E           Flaky: Hypothesis test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=3, stride=1, pad=2, kernel=5, dilation=1, size=9, channels=7, order=u'NCHW', gc=, dc=[]) produces unreliable results: Falsified on the first call but did not on a subsequent one
18:04:53 
18:04:53 ../lib/python2.7/dist-packages/hypothesis/core.py:891: Flaky
18:04:53 ----------------------------- Captured stdout call -----------------------------
18:04:53 Failed. [idx, grad, grad_estimate] are:
18:04:53 [[3.60000000e+01 3.44265044e-01 3.51562500e-01]
18:04:53  [4.90000000e+02 3.62680405e-01 3.71093750e-01]]
18:04:53 ---------------------------------- Hypothesis ----------------------------------
18:04:53 Trying example: test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=1, stride=1, pad=0, kernel=1, dilation=1, size=7, channels=1, order=u'NCHW', gc=, dc=[])
18:04:53 Trying example: test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=2, stride=2, pad=0, kernel=5, dilation=2, size=8, channels=8, order=u'NCHW', gc=, dc=[])
18:04:53 Trying example: test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=3, stride=3, pad=1, kernel=2, dilation=1, size=7, channels=3, order=u'NCHW', gc=, dc=[])
18:04:53 Trying example: test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=3, stride=3, pad=1, kernel=3, dilation=3, size=7, channels=5, order=u'NCHW', gc=, dc=[])
18:04:53 Trying example: test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=2, stride=2, pad=2, kernel=4, dilation=1, size=9, channels=7, order=u'NCHW', gc=, dc=[])
18:04:53 Trying example: test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=3, stride=1, pad=0, kernel=2, dilation=1, size=10, channels=5, order=u'NCHW', gc=, dc=[])
18:04:53 Trying example: test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=3, stride=1, pad=2, kernel=5, dilation=1, size=9, channels=4, order=u'NCHW', gc=, dc=[])
18:04:53 Trying example: test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=3, stride=1, pad=2, kernel=5, dilation=1, size=9, channels=7, order=u'NCHW', gc=, dc=[])
18:04:53 Traceback (most recent call last):
18:04:53   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 689, in evaluate_test_data
18:04:53     result = self.execute(data, collect=True)
18:04:53   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 604, in execute
18:04:53     result = self.test_runner(data, run)
18:04:53   File "/usr/local/lib/python2.7/dist-packages/hypothesis/executors.py", line 58, in default_new_style_executor
18:04:53     return function(data)
18:04:53   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 600, in run
18:04:53     return test(*args, **kwargs)
18:04:53   File "/usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/operator_test/im2col_col2im_test.py", line 115, in test_col2im_gradients
18:04:53     stride=st.integers(1, 3),
18:04:53   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 542, in test
18:04:53     result = self.test(*args, **kwargs)
18:04:53   File "/usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/operator_test/im2col_col2im_test.py", line 136, in test_col2im_gradients
18:04:53     self.assertGradientChecks(gc, op, [X], 0, [0])
18:04:53   File "/usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/hypothesis_test_util.py", line 397, in assertGradientChecks
18:04:53     "Gradient check failed for input " + str(op.input[outputs_to_check])
18:04:53   File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
18:04:53     raise self.failureException(msg)
18:04:53 AssertionError: Gradient check failed for input X
18:04:53 
18:04:53 Trying example: test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=3, stride=1, pad=2, kernel=5, dilation=1, size=9, channels=7, order=u'NCHW', gc=, dc=[])
18:04:53 Falsifying example: test_col2im_gradients(self=<caffe2.python.operator_test.im2col_col2im_test.TestReduceFrontSum testMethod=test_col2im_gradients>, batch_size=3, stride=1, pad=2, kernel=5, dilation=1, size=9, channels=7, order=u'NCHW', gc=, dc=[])
18:04:53 Failed to reproduce exception. Expected: 
18:04:53 Traceback (most recent call last):
18:04:53   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 689, in evaluate_test_data
18:04:53     result = self.execute(data, collect=True)
18:04:53   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 604, in execute
18:04:53     result = self.test_runner(data, run)
18:04:53   File "/usr/local/lib/python2.7/dist-packages/hypothesis/executors.py", line 58, in default_new_style_executor
18:04:53     return function(data)
18:04:53   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 600, in run
18:04:53     return test(*args, **kwargs)
18:04:53   File "/usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/operator_test/im2col_col2im_test.py", line 115, in test_col2im_gradients
18:04:53     stride=st.integers(1, 3),
18:04:53   File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 542, in test
18:04:53     result = self.test(*args, **kwargs)
18:04:53   File "/usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/operator_test/im2col_col2im_test.py", line 136, in test_col2im_gradients
18:04:53     self.assertGradientChecks(gc, op, [X], 0, [0])
18:04:53   File "/usr/local/caffe2/lib/python2.7/dist-packages/caffe2/python/hypothesis_test_util.py", line 397, in assertGradientChecks
18:04:53     "Gradient check failed for input " + str(op.input[outputs_to_check])
18:04:53   File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
18:04:53     raise self.failureException(msg)
18:04:53 AssertionError: Gradient check failed for input X
18:04:53 
18:04:53 
18:04:53 You can reproduce this example by temporarily adding @reproduce_failure('3.66.8', 'AAIGAAQCAgMDAA==') as a decorator on your test case
18:04:53  generated xml file: /var/lib/jenkins/workspace/caffe2_tests/python/result.xml -
```

https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-gcc5-ubuntu16.04-test/9359//console

**Comment by ezyang** [comment]
CC @asaadaldien who added this test
