### ISSUE TITLE
PyTorch 1.12 with CUDA 11.7.0, test_optim fails on A40s

### ISSUE THREAD

**Issue by VRehnberg** [pytorch/pytorch#98414]
### 🐛 Describe the bug

Similar to https://github.com/pytorch/pytorch/issues/63079 but this is for test_nadam under test_optim instead.

I've done some initial investigations on other nodes (8xT4,4xV100,4xA100) and other CUDA &/ PyTorch versions. I'll try to collect what worked and what didn't in separate comments. If I remember correctly it is only for combination PyTorch-1.12.x CUDA-11.7.0 on A40s I've observed the test failure.

## To Reproduce
1. Build PyTorch 1.12.1 from source with GCC 11.3.0 with CUDA 11.7.0
2. Run `python test_optim.py -k test_nadam`
ensuing error message:
```
/dev/shm/PyTorch/1.12.1/foss-2022a-CUDA-11.7.0/pytorch-v1.12.1/build/lib.linux-x86_64-cpython-310/torch/testing/_internal/common_cuda.py:19: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  CUDA11OrLater = torch.version.cuda and LooseVersion(torch.version.cuda) >= "11.0"
/apps/Arch/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
F
======================================================================
FAIL: test_nadam (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cephyr/NOBACKUP/priv/c3-staff/vikren/build/EasyBuild/PyTorch/test_optim.py", line 671, in test_nadam
    self._test_basic_cases(
  File "/cephyr/NOBACKUP/priv/c3-staff/vikren/build/EasyBuild/PyTorch/test_optim.py", line 259, in _test_basic_cases
    self._test_state_dict(
  File "/cephyr/NOBACKUP/priv/c3-staff/vikren/build/EasyBuild/PyTorch/test_optim.py", line 241, in _test_state_dict
    self.assertEqual(bias, bias_cuda)
  File "/dev/shm/PyTorch/1.12.1/foss-2022a-CUDA-11.7.0/pytorch-v1.12.1/build/lib.linux-x86_64-cpython-310/torch/testing/_internal/common_utils.py", line 2219, in assertEqual
    assert_equal(
  File "/dev/shm/PyTorch/1.12.1/foss-2022a-CUDA-11.7.0/pytorch-v1.12.1/build/lib.linux-x86_64-cpython-310/torch/testing/_comparison.py", line 1095, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 10 (10.0%)
Greatest absolute difference: 1.609325408935547e-05 at index (1,) (up to 1e-05 allowed)
Greatest relative difference: 1.477008233390933e-05 at index (1,) (up to 1.3e-06 allowed)

----------------------------------------------------------------------
Ran 1 test in 5.343s

FAILED (failures=1)
```

### Versions

```
Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.6 (Green Obsidian) (x86_64)
GCC version: (GCC) 11.3.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.28

Python version: 3.10.4 (main, Aug 14 2022, 22:57:54) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-4.18.0-372.32.1.el8_6.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: 
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40
GPU 2: NVIDIA A40
GPU 3: NVIDIA A40

Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[conda] Could not collect
```

**Comment by VRehnberg** [comment]
**FAILURE** PyTorch 1.12.0, CUDA 11.7.0, 4xA40
### Versions
```Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.6 (Green Obsidian) (x86_64)
GCC version: (GCC) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.10.4 (main, Aug 14 2022, 22:57:54) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-4.18.0-372.32.1.el8_6.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: 
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40
GPU 2: NVIDIA A40
GPU 3: NVIDIA A40

Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0
[pip3] torchdata==0.13.0
[pip3] torchvision==0.13.0
[conda] Could not collect
```

**Comment by VRehnberg** [comment]
**Failure** PyTorch 1.12.1, GCC 11.3.0, CUDA 11.7.0, 8xT4
didn't collect versions, but still got logs from build. Could add as gist if of interest.

I must have misremembered this thought it had succeeded. I'll have to update title.

**Comment by mikaylagawarecki** [comment]
Hi @VRehnberg, I see that you are using PyTorch 1.12, could you check whether this error persist on the latest version of PyTorch (2.0)?

**Comment by VRehnberg** [comment]
I'll see. First build attempt failed, I'll have to tweak some stuff first.

**Comment by ptrblck** [comment]
> I've done some initial investigations on other nodes (8xT4,4xV100,4xA100) and other CUDA &/ PyTorch versions. I'll try to collect what worked and what didn't in separate comments. If I remember correctly it is only for combination PyTorch-1.12.x CUDA-11.7.0 on A40s I've observed the test failure.

I think this test might be sensitive to the seed and instead of running it once on different setups, you could rerun it in e.g. the latest one using different seeds.
Using:
```python
     def test_nadam(self):
+        import os
+        seed = int(os.getenv("TORCH_SEED", 0))
+        print(f"seeding with: {seed}")
+        torch.manual_seed(seed)
         self._test_basic_cases(
             lambda weight, bias, foreach: optim.NAdam(
```
and executing the test via:
```
for seed in {1..100}; do TORCH_SEED=$seed python test_optim.py -v -k test_nadam; done 2>&1 | tee out01
```
showed 3/100 failures on a V100 using a current build form `master` and 2/100 on a 3090.
Are you seeing similar failure rates or are yours higher?

**Comment by VRehnberg** [comment]
> I see that you are using PyTorch 1.12, could you check whether this error persist on the latest version of PyTorch (2.0)?

Yes, it does (among 9 other test failures and 55 errors, but I haven't checked if any of those got patches already).

> showed 3/100 failures on a V100 using a current build form `master` and 2/100 on a 3090. Are you seeing similar failure rates or are yours higher?

With 1.12.1 and 1.12.0 I'm seeing something between 5 % and 10 % of tests that are failing.

Considering how many tests there are in the PyTorch test suite, even a 2 % error rate seems a bit too high for any individual test, if the entire test suite is expected to pass.

**Comment by ptrblck** [comment]
> Considering how many tests there are in the PyTorch test suite, even a 2 % error rate seems a bit too high for any individual test, if the entire test suite is expected to pass.

Yes, I agree and I wanted to point out that the actual test might be too sensitive to the used seed in the current and previous PyTorch releases. An increase in the failure rate could indicate a real underlying regression, but assuming the failure rate is approx. constant we might need to increase the thresholds or use pre-defined input/target data.
Seeding the code might not work due to potentially different outputs between different PyTorch/CUDA versions and GPUs.

**Comment by VRehnberg** [comment]
This is the patch I used for PyTorch-1.12.1 I'll try to find the time to do a PR for PyTorch as well if I find the time
https://github.com/easybuilders/easybuild-easyconfigs/pull/17726/files#diff-dfb5010b61f811a6bbbd255dbaa33210d97b09fcdada6988522e4b5ceb5f101f

**Comment by albanD** [comment]
@VRehnberg would setting the random seed explicitly also help stability in your case.

cc @cpuhrsch who was planning on making testing more deterministic.

**Comment by VRehnberg** [comment]
> VRehnberg would setting the random seed explicitly also help stability in your case.

You could probably find a seed that you set for this precise test that would work just as well as what I've done. But, I wasn't sure how rng could change between toolchains and versions so this seemed more certain.

**Comment by VRehnberg** [comment]
It seems that test_nadam isn't the only flaky test in test_optim. This change caused other test failures in test_optim on some machines, see e.g. https://github.com/easybuilders/easybuild-easyconfigs/pull/17732 and https://github.com/easybuilders/easybuild-easyconfigs/pull/17733

**Comment by ptrblck** [comment]
> would setting the random seed explicitly also help stability in your case.

No, it won't as one seed might work in one specific setup while failing on another one.
