### ISSUE TITLE
Strided to BSR conversion fails when blocks contains different number of zeros

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#98495]
## Issue description

As in the title.

## Code example

```python
>>> torch.tensor([[[1, 2]], [[3, 4]]]).to_sparse_bsr((1, 1))
tensor(crow_indices=tensor([[0, 2],
                            [0, 2]]),
       col_indices=tensor([[0, 1],
                           [0, 1]]),
       values=tensor([[[[1]],

                       [[2]]],


                      [[[3]],

                       [[4]]]]), size=(2, 1, 2), nnz=2,
       layout=torch.sparse_bsr)
>>> torch.tensor([[[1, 2]], [[0, 4]]]).to_sparse_bsr((1, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expect the same number of specified elements per batch.
>>> torch.tensor([[[1, 0]], [[0, 4]]]).to_sparse_bsr((1, 1))
tensor(crow_indices=tensor([[0, 1],
                            [0, 1]]),
       col_indices=tensor([[0],
                           [1]]),
       values=tensor([[[[1]]],


                      [[[4]]]]), size=(2, 1, 2), nnz=1,
       layout=torch.sparse_bsr)
```

Notice that in the failing conversion example, the number of zeros in the first block is 0 and in the second block it is 1.

Apparently, the check logic in
https://github.com/pytorch/pytorch/blob/ccc27bc361f2fa5043534b8f898922ffd0ca9340/aten/src/ATen/native/TensorConversions.cpp#L95-L98
is flawed for BSR and BSC conversion cases.

## System Info

- PyTorch version: master

**Comment by pearu** [comment]
This issue applies to all sparse compressed layouts:
```python
>>> torch.tensor([[[1, 0]], [[3, 4]]]).to_sparse_csr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expect the same number of specified elements per batch.
```

**Comment by cpuhrsch** [comment]
@pearu - Thanks for discovering this! Can you send a fix for this?

**Comment by pearu** [comment]
This issue is blocked by the lack of support for variable NSE in batches of sparse tensors (the BSR example that is provided in the description, requires variable NSE support). The solution provided in https://github.com/pytorch/pytorch/pull/84843 requires further discussion, see https://github.com/pytorch/pytorch/issues/104193.
