### ISSUE TITLE
Symbolic tracing with dynamic shapes broken with custom meta kernel

### ISSUE THREAD

**Issue by kumpera** [pytorch/pytorch#98519]
### 🐛 Describe the bug

When using make_fx with symbolic tracing custom ops implemented in python their meta kernel don't work.

```python

import torch
from functorch import make_fx


lib = torch.library.Library("foo", "DEF")
lib.define("wait_tensor(Tensor self) -> Tensor")

lib_impl = torch.library.Library("foo", "IMPL")

def my_wait(tensor):
    return tensor.clone()
lib_impl.impl("wait_tensor", my_wait, "CompositeExplicitAutograd")

def my_wait_meta(tensor):
    return torch.empty_like(tensor)
lib_impl.impl("wait_tensor", my_wait_meta, "Meta")

def my_fun(a):
    return torch.ops.foo.wait_tensor(a)

x = torch.rand([4])
res = make_fx(my_fun, tracing_mode="real")(x)
print(f"fx graph:\n{res.graph}")
print("----")
res = make_fx(my_fun, tracing_mode="symbolic")(x)
print(f"fx graph:\n{res.graph}")
print("----")
res = make_fx(my_fun, tracing_mode="fake")(x)
print("----")
print(f"fx graph:\n{res.graph}")
```

Fails with
```
I get the following output:

----
Traceback (most recent call last):
  File "/data/home/kumpera/repos/fx/repro.py", line 24, in <module>
    res = make_fx(my_fun, tracing_mode="symbolic")(x)
  File "/scratch/kumpera/pytorch/torch/fx/experimental/proxy_tensor.py", line 761, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_autograd), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/scratch/kumpera/pytorch/torch/fx/experimental/proxy_tensor.py", line 467, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/scratch/kumpera/pytorch/torch/fx/_symbolic_trace.py", line 778, in trace
    (self.create_arg(fn(*args)),),
  File "/scratch/kumpera/pytorch/torch/fx/experimental/proxy_tensor.py", line 484, in wrapped
    out = f(*tensors)
  File "/data/home/kumpera/repos/fx/repro.py", line 19, in my_fun
    return torch.ops.foo.wait_tensor(a)
  File "/scratch/kumpera/pytorch/torch/_ops.py", line 642, in __call__
    return self._op(*args, **kwargs or {})
  File "/scratch/kumpera/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/scratch/kumpera/pytorch/torch/fx/experimental/proxy_tensor.py", line 533, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/scratch/kumpera/pytorch/torch/fx/experimental/proxy_tensor.py", line 558, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_autograd, args, kwargs)
  File "/scratch/kumpera/pytorch/torch/fx/experimental/proxy_tensor.py", line 369, in proxy_call
    out = func(*args, **kwargs)
  File "/scratch/kumpera/pytorch/torch/_ops.py", line 394, in __call__
    return self._op(*args, **kwargs or {})
  File "/scratch/kumpera/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/scratch/kumpera/pytorch/torch/_subclasses/fake_tensor.py", line 1073, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/scratch/kumpera/pytorch/torch/_subclasses/fake_tensor.py", line 1263, in dispatch
    r = func(*args, **kwargs)
  File "/scratch/kumpera/pytorch/torch/_ops.py", line 394, in __call__
    return self._op(*args, **kwargs or {})
  File "/data/home/kumpera/repos/fx/repro.py", line 15, in my_wait_meta
    return torch.empty_like(tensor)
RuntimeError: Cannot call strides() on tensor with symbolic sizes/strides
```

### Versions

master from April 6th: bbf180af9f837e06a20aa3b31c759620c1a648dc

cc @ezyang

**Comment by kumpera** [comment]
Turned out to be a local merge issue 🤦
