### ISSUE TITLE
Unsupported annotation when using generics for typing

### ISSUE THREAD

**Issue by abidwael** [pytorch/pytorch#98521]
### 🐛 Describe the bug

When using [generics for typing](https://peps.python.org/pep-0585/#reference-implementation) in Python 3.9, I run into this error
```
Traceback (most recent call last):
  File "/Users/scripts/torchscript_bug.py", line 24, in <module>
    out = torch.jit.script(pad)
  File "/usr/local/Caskroom/miniforge/base/envs/ludwig/lib/python3.9/site-packages/torch/jit/_script.py", line 1341, in script
    fn = torch._C._jit_script_compile(
  File "/usr/local/Caskroom/miniforge/base/envs/ludwig/lib/python3.9/site-packages/torch/jit/annotations.py", line 366, in try_ann_to_type
    assert maybe_type, msg.format(repr(ann), repr(maybe_type))
AssertionError: Unsupported annotation typing.Union[int, tuple[int, int]] could not be resolved because None could not be resolved.
```
repro script
```
import torch
import torchvision.transforms.functional as F
from typing import Union


def to_tuple(v: Union[int, tuple[int, int]]) -> tuple[int, int]:
    """Converts int or tuple to tuple of ints."""
    if torch.jit.isinstance(v, int):
        return v, v
    else:
        return v


def pad(img: torch.Tensor, new_size: Union[int, tuple[int, int]]) -> torch.Tensor:
    new_size = to_tuple(new_size)
    old_size = img.shape[-2:]
    pad_size = (torch.tensor(new_size) - torch.tensor(old_size)) / 2
    padding = torch.cat((torch.floor(pad_size), torch.ceil(pad_size)))
    padding[padding < 0] = 0
    padding = [int(x) for x in padding]
    return F.pad(img, padding=padding, padding_mode="edge")


out = torch.jit.script(pad)
```

### Versions

`Python 3.9.16`
```
torch                                    2.0.0
torchaudio                               2.0.1
torchdata                                0.6.0
torchinfo                                1.7.2
torchmetrics                             0.11.4
torchtext                                0.15.1
torchvision                              0.15.1
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by malfet** [comment]
Sounds like little fun problem to fix.

**Comment by malfet** [comment]
Following simple patch fixes it:
```python
diff --git a/torch/_jit_internal.py b/torch/_jit_internal.py
index 0cdc566243f..4bbf4ce3055 100644
--- a/torch/_jit_internal.py
+++ b/torch/_jit_internal.py
@@ -79,6 +79,8 @@ class SourceLoader:
 loader = SourceLoader()
 
 
+IS_PY39_PLUS = sys.version_info >= (3, 9)
+
 def createResolutionCallbackFromEnv(lookup_base):
     """
     Creates a resolution callback that will look up qualified names in an
@@ -339,7 +341,7 @@ def get_annotation_str(annotation):
         return ".".join([get_annotation_str(annotation.value), annotation.attr])
     elif isinstance(annotation, ast.Subscript):
         # In Python3.9+ subscript indicies are not wrapped in ast.Index
-        subscript_slice = annotation.slice if sys.version_info >= (3, 9) else annotation.slice.value  # type: ignore[attr-defined]
+        subscript_slice = annotation.slice if IS_PY39_PLUS else annotation.slice.value  # type: ignore[attr-defined]
         return f"{get_annotation_str(annotation.value)}[{get_annotation_str(subscript_slice)}]"
     elif isinstance(annotation, ast.Tuple):
         return ",".join([get_annotation_str(elt) for elt in annotation.elts])
@@ -983,9 +985,12 @@ def is_tuple(ann) -> bool:
     # For some reason Python 3.7 violates the Type[A, B].__origin__ == Type rule
     if not hasattr(ann, "__module__"):
         return False
+
+    ann_origin = getattr(ann, "__origin__", None)
+    if IS_PY39_PLUS and ann.__module__ == "builtins" and ann_origin is tuple:
+        return True
     return ann.__module__ == "typing" and (
-        getattr(ann, "__origin__", None) is Tuple
-        or getattr(ann, "__origin__", None) is tuple
+        ann_origin is Tuple or ann_origin is tuple
     )
 
 
@@ -995,9 +1000,12 @@ def is_list(ann) -> bool:
 
     if not hasattr(ann, "__module__"):
         return False
+
+    ann_origin = getattr(ann, "__origin__", None)
+    if IS_PY39_PLUS and ann.__module__ == "builtins" and ann_origin is list:
+        return True
     return ann.__module__ == "typing" and (
-        getattr(ann, "__origin__", None) is List
-        or getattr(ann, "__origin__", None) is list
+        ann_origin is List or ann_origin is list
     )
```
