### ISSUE TITLE
Internal assert failed during torchdyanmo.export

### ISSUE THREAD

**Issue by andrewor14** [pytorch/pytorch#98531]
### 🐛 Describe the bug

Repro:
```
import copy
import torch
import torch._dynamo

class FusedQATConvBnPattern(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = torch.nn.Conv2d(1, 1, 1)
        self.bn = torch.nn.BatchNorm2d(1)

    def forward(self, input):
        """Approximated method to fuse conv and bn. It requires only one forward pass.
        conv_orig = conv / scale_factor where scale_factor = bn.weight / running_std
        """
        running_std = torch.sqrt(self.bn.running_var + self.bn.eps)
        scale_factor = self.bn.weight / running_std
        weight_shape = [1] * len(self.conv.weight.shape)
        weight_shape[0] = -1
        bias_shape = [1] * len(self.conv.weight.shape)
        bias_shape[1] = -1
        scaled_weight = self.conv.weight * scale_factor.reshape(weight_shape)
        zero_bias = torch.zeros_like(self.conv.bias, dtype=input.dtype)
        conv = self.conv._conv_forward(input, scaled_weight, zero_bias)
        conv_orig = conv / scale_factor.reshape(bias_shape)
        conv_orig = conv_orig + self.conv.bias.reshape(bias_shape)
        conv = self.bn(conv_orig)
        return conv

example_inputs = (torch.randn(1, 1, 3, 3),)

pattern, _ = torch._dynamo.export(
    FusedQATConvBnPattern(),
    *copy.deepcopy(example_inputs),
    aten_graph=True,
    tracing_mode="real",
)
```
Stack trace (truncated)
```
Traceback (most recent call last):
  File "scratch/repro.py", line 31, in <module>
    pattern, _ = torch._dynamo.export(
  File "torch/_dynamo/eval_frame.py", line 800, in export
    graph = make_fx(
  File "torch/fx/experimental/proxy_tensor.py", line 761, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_autograd), tracer=fx_tracer, concrete_args=tuple(phs))
  ...
  File "torch/_ops.py", line 398, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: op.is_output INTERNAL ASSERT FAILED at "aten/src/ATen/TensorIterator.cpp":349, please report a bug to PyTorch. Found type undefined input tensor!

While executing %truediv : [#users=2] = call_function[target=operator.truediv](args = (%l__self___bn_weight, %sqrt), kwargs = {})
Original traceback:
  File "scratch/repro.py", line 16, in forward
    scale_factor = self.bn.weight / running_std
```

### Versions

Commit: 7b25976323751291171e60dc557bc61973427d32

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
cc @eellison this kind of looks like a fake tensor went to real kernel problem

**Comment by eellison** [comment]
He has a PR fixing it

**Comment by andrewor14** [comment]
https://github.com/pytorch/pytorch/pull/98769
