### ISSUE TITLE
torch.matmul with batched CSR matrix

### ISSUE THREAD

**Issue by Turakar** [pytorch/pytorch#98675]
### 🐛 Describe the bug

```python
import torch

device = torch.device("cuda:0")
a = torch.tensor([
    [
        [1.0, 0.0],
        [2.0, 1.0]
    ],
    [
        [0.1, 0.1],
        [0.0, 2.0],
    ]
]).to_sparse_csr().to(device)
b = torch.randn(2, 2).to(device)
print(torch.matmul(a, b))
```

This leads to `RuntimeError: Sparse CSR tensors do not have strides`, so seems like this is not implemented, yet. However, it is unclear to me why this is a problem with striding.

```
Traceback (most recent call last):
  File "/<path>/sparse_missing_support.py", line 24, in <module>
    main()
  File "/<path>/sparse_missing_support.py", line 19, in main
    print(torch.matmul(a, b.to_sparse_csr()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sparse CSR tensors do not have strides
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Fedora Linux 37 (KDE Plasma) (x86_64)
GCC version: (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.36

Python version: 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (64-bit runtime)
Python platform: Linux-6.2.7-200.fc37.x86_64-x86_64-with-glibc2.36
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070 SUPER
Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.8.1
/usr/lib64/libcudnn_adv_infer.so.8.8.1
/usr/lib64/libcudnn_adv_train.so.8.8.1
/usr/lib64/libcudnn_cnn_infer.so.8.8.1
/usr/lib64/libcudnn_cnn_train.so.8.8.1
/usr/lib64/libcudnn_ops_infer.so.8.8.1
/usr/lib64/libcudnn_ops_train.so.8.8.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 2700 Eight-Core Processor
CPU family:                      23
Model:                           8
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        2
Frequency boost:                 enabled
CPU(s) scaling MHz:              67%
CPU max MHz:                     3200.0000
CPU min MHz:                     1550.0000
BogoMIPS:                        6387.18
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sev sev_es
Virtualization:                  AMD-V
L1d cache:                       256 KiB (8 instances)
L1i cache:                       512 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] triton==2.0.0
[conda] Could not collect
```

**Comment by Turakar** [comment]
Seems like the problem also occurs on CPU.

**Comment by Turakar** [comment]
https://github.com/pytorch/pytorch/issues/14489 is related, but seems to be about COO format.

**Comment by cpuhrsch** [comment]
@pearu @nikitaved - can one of you take a look at this?

**Comment by tvercaut** [comment]
For the record, we implemented a workaround for batched sparse x dense multiplication (CSR and COO) here:
https://github.com/cai4cai/torchsparsegradutils/blob/main/torchsparsegradutils/sparse_matmul.py

The workaround also addresses the memory issue in the backward pass of the native (non-batched) sparse.mm pointed out in #41128

Would be great to get fix supported upstream of course.

**Comment by cpuhrsch** [comment]
@pearu - Can you take a look at the proposed fix here?

**Comment by tvercaut** [comment]
Yes, indeed, I was pointing to our implementation of a workaround only. It's definitely not a proper fix but hopefully can be useful to other end users.

**Comment by leonardodalinky** [comment]
Fail to compute a simple sparse-dense matrix multiplication due to `RuntimeError: expand is unsupported for Sparse tensors`.

The function is:
```python
def compute_obj_type_align_embeds(
    obj_type_tokens: torch.Tensor, embed_matrix: torch.Tensor, sparse=True
) -> torch.Tensor:
    from einops import repeat

    tokens = obj_type_tokens / obj_type_tokens.sum(dim=-1, keepdim=True)
    print("Tokens shape:", tokens.size())
    print("Embed matrix shape:", embed_matrix.size())
    if sparse:
        tokens = tokens.to_sparse()
    return torch.matmul(tokens, repeat(embed_matrix, "v d -> b v d", b=tokens.size(0)))
```

The Output is:
```
Tokens shape: torch.Size([16, 48, 32000])                                                                                                                                 
Embed matrix shape: torch.Size([32000, 4096])
```

I also notice that #102162 also mentioned this. Would there be any updates in the later version?
