### ISSUE TITLE
Pytorch member variable not working after converting to onnx format

### ISSUE THREAD

**Issue by xincunshuichan** [pytorch/pytorch#98727]
### 🐛 Describe the bug

import torch.nn as nn
import torch

class RNN(nn.Module):
    # you can also accept arguments in your model constructor
    def __init__(self, data_size, hidden_size, output_size):
        super(RNN, self).__init__()
        self.last_hidden = torch.zeros(1, hidden_size)

        input_size = data_size + hidden_size

        self.i2h = nn.Linear(input_size, hidden_size)
        self.h2o = nn.Linear(hidden_size, output_size)

    def forward(self, data):
        input = torch.cat((data, self.last_hidden), 1)
        hidden = self.i2h(input)
        output = self.h2o(hidden)

        self.last_hidden = hidden
        return output

data_size = 50
hidden_size = 20
output_size = 10
rnn_model = RNN(data_size, hidden_size, output_size)
rnn_model.eval()

data = torch.zeros(1, data_size)
last_hidden = torch.zeros(1, hidden_size)

torch.jit.save(torch.jit.script(rnn_model), 'rnn_model.pt')

pytorch_rnn_model = torch.load('rnn_model.pt')

torch.onnx.export(
    pytorch_rnn_model,
    data,
    'rnn_model.onnx',
    opset_version=15,
    input_names=('input',),
    output_names=('output',),
    dynamic_axes={
        'input': {0: 'batch', 1: 'sequence'},
        'output': {0: 'batch', 1: 'sequence'},
    },
    training=torch.onnx.TrainingMode.EVAL,
    do_constant_folding=False,
    verbose=True,
    keep_initializers_as_inputs=True,
)

import onnxruntime

rnn_onnx_model = onnxruntime.InferenceSession('rnn_model.onnx', providers=['CPUExecutionProvider'])
input_name = rnn_onnx_model.get_inputs()[0].name
output_name = rnn_onnx_model.get_outputs()[0].name

print(rnn_onnx_model.run([output_name], {input_name: data.numpy()}))
print(rnn_onnx_model.run([output_name], {input_name: data.numpy()}))
print(rnn_onnx_model.run([output_name], {input_name: data.numpy()}))

print(pytorch_rnn_model.forward(data))
print(pytorch_rnn_model.forward(data))
print(pytorch_rnn_model.forward(data))

### Versions

Hi team, 
we're now investigating the export to onnx feature and we found that some update logic in the original pytorch model is not working in the converted onnx model. The pytorch result kept updating as expected but the onnx result stays the same.
```
# onnx (stays the same)
[array([[ 0.09353793, -0.06549314, -0.17803375,  0.07057121, -0.07197426,
        -0.00245702,  0.09384082, -0.07102646,  0.00091066, -0.012063  ]],
      dtype=float32)]
[array([[ 0.09353793, -0.06549314, -0.17803375,  0.07057121, -0.07197426,
        -0.00245702,  0.09384082, -0.07102646,  0.00091066, -0.012063  ]],
      dtype=float32)]
[array([[ 0.09353793, -0.06549314, -0.17803375,  0.07057121, -0.07197426,
        -0.00245702,  0.09384082, -0.07102646,  0.00091066, -0.012063  ]],
      dtype=float32)]

# pytorch result (keep updating)
tensor([[ 0.1028, -0.0641, -0.1713,  0.0673, -0.0882, -0.0108,  0.1027, -0.0583,
          0.0012, -0.0174]], grad_fn=<DifferentiableGraphBackward>)
tensor([[ 0.0977, -0.0628, -0.1801,  0.0675, -0.0858, -0.0092,  0.1020, -0.0584,
          0.0034, -0.0185]], grad_fn=<DifferentiableGraphBackward>)
tensor([[ 0.0987, -0.0620, -0.1770,  0.0681, -0.0860, -0.0084,  0.1019, -0.0604,
          0.0033, -0.0192]], grad_fn=<DifferentiableGraphBackward>)
```

How to deal with such scenario that we need to update some member variable like self.hidden ?

Versions
```
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.16 (default, Mar  1 2023, 21:19:10)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchvision==0.15.1
[conda] blas                      1.0                         mkl    https://repo.anaconda.com/pkgs/main
[conda] mkl                       2021.4.0           hecd8cb5_637    https://repo.anaconda.com/pkgs/main
[conda] mkl-service               2.4.0            py38h9ed2024_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_fft                   1.3.1            py38h4ab4a9b_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_random                1.2.2            py38hb2f4e1b_0    https://repo.anaconda.com/pkgs/main
[conda] numpy                     1.23.5           py38he696674_0    https://repo.anaconda.com/pkgs/main
[conda] numpy-base                1.23.5           py38h9cd3388_0    https://repo.anaconda.com/pkgs/main
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi
```

**Comment by amritangshudey** [comment]
hey i would like to work on this issue.
can you assign me this?

**Comment by xincunshuichan** [comment]
> hey i would like to work on this issue. can you assign me this?

Hi there, it seems that I cannot do the assignment. I think the operation is only allowed for the repository admin, right? 
<img width="324" alt="image" src="https://user-images.githubusercontent.com/18558024/230870868-e4f44356-744f-4bb0-95d8-40cdbf0fd67d.png">

**Comment by amritangshudey** [comment]
can you send me the repo link, 
i cant find it?

**Comment by xincunshuichan** [comment]
Sorry, I didn't get you. I thought this issue is related to pytorch, the one now we're discussing at. And in this issue, this repository I cannot do the assign operation. Anything I can do?

**Comment by xincunshuichan** [comment]
Add extra information for this issue. 

I tried these code today and I got below mismatch information after the verrification. Hope this help

verrification code
```
import torch.onnx.verification
torch.onnx.verification.find_mismatch(
    pytorch_rnn_model,
    data,
    opset_version=15,
    training=torch.onnx.TrainingMode.EVAL,
    do_constant_folding=False,
    verbose=True,
    keep_initializers_as_inputs=True,
)
```

Got this mismatch code
```
Traceback (most recent call last):
  File "/Users/ytseng/Documents/projects/18_tensorrt_optimization/AIML-model-optimization/investigation/byom_pytorch/tensorrt/rnn/github_issue/reproduce.py", line 55, in <module>
    torch.onnx.verification.find_mismatch(
  File "/Users/ytseng/anaconda3/envs/AIML-model-optimization/lib/python3.8/site-packages/torch/onnx/verification.py", line 1880, in find_mismatch
    graph_info.find_mismatch(options)
  File "/Users/ytseng/anaconda3/envs/AIML-model-optimization/lib/python3.8/site-packages/torch/onnx/verification.py", line 1680, in find_mismatch
    self.mismatch_error, self._onnx_graph, self.pt_outs, _ = self.verify_export(
  File "/Users/ytseng/anaconda3/envs/AIML-model-optimization/lib/python3.8/site-packages/torch/onnx/verification.py", line 1639, in verify_export
    return verify_aten_graph(
  File "/Users/ytseng/anaconda3/envs/AIML-model-optimization/lib/python3.8/site-packages/torch/onnx/verification.py", line 924, in verify_aten_graph
    jit_outs = torch._C._jit_interpret_graph(graph, jit_input_and_parameters)  # type: ignore[attr-defined]
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 12, in <on-demand-func>
    data: Tensor) -> Tensor:
    last_hidden = self.last_hidden
    input = torch.cat([data, last_hidden], 1)
            ~~~~~~~~~ <--- HERE
    i2h = self.i2h
    hidden = (i2h).forward(input, )

Traceback of TorchScript, original code (most recent call last):
  File "/Users/ytseng/Documents/projects/18_tensorrt_optimization/AIML-model-optimization/investigation/byom_pytorch/tensorrt/rnn/github_issue/reproduce.py", line 16, in <on-demand-func>
    def forward(self, data):
        input = torch.cat((data, self.last_hidden), 1)
                ~~~~~~~~~ <--- HERE
        hidden = self.i2h(input)
        output = self.h2o(hidden)
RuntimeError: Expected Tensor but got None

```

**Comment by amritangshudey** [comment]
i cant find the repository where i need to make the changes in the code.
Can you send me the link to this repository?

**Comment by amritangshudey** [comment]
import torch.nn as nn
import torch

class RNN(nn.Module):
    # you can also accept arguments in your model constructor
    def __init__(self, data_size, hidden_size, output_size):
        super(RNN, self).__init__()
        self.last_hidden = torch.zeros(1, hidden_size)

        input_size = data_size + hidden_size

        self.i2h = nn.Linear(input_size, hidden_size)
        self.h2o = nn.Linear(hidden_size, output_size)

    def forward(self, data):
        input = torch.cat((data, self.last_hidden), 1)
        hidden = self.i2h(input)
        output = self.h2o(hidden)

        self.last_hidden = hidden
        return output

data_size = 50
hidden_size = 20
output_size = 10
rnn_model = RNN(data_size, hidden_size, output_size)
rnn_model.eval()

data = torch.zeros(1, data_size)
last_hidden = torch.zeros(1, hidden_size)

torch.jit.save(torch.jit.script(rnn_model), 'rnn_model.pt')

pytorch_rnn_model = torch.jit.load('rnn_model.pt')  # Load the TorchScript module using torch.jit.load

torch.onnx.export(
    pytorch_rnn_model,
    data,
    'rnn_model.onnx',
    opset_version=15,
    input_names=('input',),
    output_names=('output',),
    dynamic_axes={
        'input': {0: 'batch', 1: 'sequence'},
        'output': {0: 'batch', 1: 'sequence'},
    },
    training=torch.onnx.TrainingMode.EVAL,
    do_constant_folding=False,
    verbose=True,
    keep_initializers_as_inputs=True,
)

import onnxruntime

rnn_onnx_model = onnxruntime.InferenceSession('rnn_model.onnx', providers=['CPUExecutionProvider'])
input_name = rnn_onnx_model.get_inputs()[0].name
output_name = rnn_onnx_model.get_outputs()[0].name

print(rnn_onnx_model.run([output_name], {input_name: data.numpy()}))
print(rnn_onnx_model.run([output_name], {input_name: data.numpy()}))
print(rnn_onnx_model.run([output_name], {input_name: data.numpy()}))

print(pytorch_rnn_model.forward(data))
print(pytorch_rnn_model.forward(data))
print(pytorch_rnn_model.forward(data))

**Comment by amritangshudey** [comment]
i think this code should work.
try this.

**Comment by amritangshudey** [comment]
import torch.nn as nn
import torch

class RNN(nn.Module):
    # you can also accept arguments in your model constructor
    def __init__(self, data_size, hidden_size, output_size):
        super(RNN, self).__init__()
        self.last_hidden = torch.zeros(1, hidden_size)

        input_size = data_size + hidden_size

        self.i2h = nn.Linear(input_size, hidden_size)
        self.h2o = nn.Linear(hidden_size, output_size)

    def forward(self, data):
        input = torch.cat((data, self.last_hidden), 1)
        hidden = self.i2h(input)
        output = self.h2o(hidden)

        self.last_hidden = hidden
        return output

data_size = 50
hidden_size = 20
output_size = 10
rnn_model = RNN(data_size, hidden_size, output_size)
rnn_model.eval()

data = torch.zeros(1, data_size)
last_hidden = torch.zeros(1, hidden_size)

torch.jit.save(torch.jit.script(rnn_model), 'rnn_model.pt')

pytorch_rnn_model = torch.jit.load('rnn_model.pt')  # Load the TorchScript module using torch.jit.load

torch.onnx.export(
    pytorch_rnn_model,
    data,
    'rnn_model.onnx',
    opset_version=15,
    input_names=('input',),
    output_names=('output',),
    dynamic_axes={
        'input': {0: 'batch', 1: 'sequence'},
        'output': {0: 'batch', 1: 'sequence'},
    },
    training=torch.onnx.TrainingMode.EVAL,
    do_constant_folding=False,
    verbose=True,
    keep_initializers_as_inputs=True,
)

import onnxruntime

rnn_onnx_model = onnxruntime.InferenceSession('rnn_model.onnx', providers=['CPUExecutionProvider'])
input_name = rnn_onnx_model.get_inputs()[0].name
output_name = rnn_onnx_model.get_outputs()[0].name

print(rnn_onnx_model.run([output_name], {input_name: data.numpy()}))
print(rnn_onnx_model.run([output_name], {input_name: data.numpy()}))
print(rnn_onnx_model.run([output_name], {input_name: data.numpy()}))

print(pytorch_rnn_model.forward(data))
print(pytorch_rnn_model.forward(data))
print(pytorch_rnn_model.forward(data))

**Comment by xincunshuichan** [comment]
> i cant find the repository where i need to make the changes in the code. Can you send me the link to this repository?



> import torch.nn as nn import torch
> 
> class RNN(nn.Module): # you can also accept arguments in your model constructor def **init**(self, data_size, hidden_size, output_size): super(RNN, self).**init**() self.last_hidden = torch.zeros(1, hidden_size)
> 
> ```
>     input_size = data_size + hidden_size
> 
>     self.i2h = nn.Linear(input_size, hidden_size)
>     self.h2o = nn.Linear(hidden_size, output_size)
> 
> def forward(self, data):
>     input = torch.cat((data, self.last_hidden), 1)
>     hidden = self.i2h(input)
>     output = self.h2o(hidden)
> 
>     self.last_hidden = hidden
>     return output
> ```
> 
> data_size = 50 hidden_size = 20 output_size = 10 rnn_model = RNN(data_size, hidden_size, output_size) rnn_model.eval()
> 
> data = torch.zeros(1, data_size) last_hidden = torch.zeros(1, hidden_size)
> 
> torch.jit.save(torch.jit.script(rnn_model), 'rnn_model.pt')
> 
> pytorch_rnn_model = torch.jit.load('rnn_model.pt') # Load the TorchScript module using torch.jit.load
> 
> torch.onnx.export( pytorch_rnn_model, data, 'rnn_model.onnx', opset_version=15, input_names=('input',), output_names=('output',), dynamic_axes={ 'input': {0: 'batch', 1: 'sequence'}, 'output': {0: 'batch', 1: 'sequence'}, }, training=torch.onnx.TrainingMode.EVAL, do_constant_folding=False, verbose=True, keep_initializers_as_inputs=True, )
> 
> import onnxruntime
> 
> rnn_onnx_model = onnxruntime.InferenceSession('rnn_model.onnx', providers=['CPUExecutionProvider']) input_name = rnn_onnx_model.get_inputs()[0].name output_name = rnn_onnx_model.get_outputs()[0].name
> 
> print(rnn_onnx_model.run([output_name], {input_name: data.numpy()})) print(rnn_onnx_model.run([output_name], {input_name: data.numpy()})) print(rnn_onnx_model.run([output_name], {input_name: data.numpy()}))
> 
> print(pytorch_rnn_model.forward(data)) print(pytorch_rnn_model.forward(data)) print(pytorch_rnn_model.forward(data))

Oh 

> i cant find the repository where i need to make the changes in the code. Can you send me the link to this repository?

Oh, got it. The code is not belong to any repository, I just pasted it to the issue description.

**Comment by xincunshuichan** [comment]
I tried the code you just pasted @amritangshudey But the result is the same.

All the change is this right? 
```pytorch_rnn_model = torch.jit.load('rnn_model.pt') # Load the TorchScript module using torch.jit.load```

result:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/18558024/230876537-1ae26fa1-da09-47c0-8b8d-14790d9b5036.png">

**Comment by bugzyz** [comment]
@BowenBao  Hi there, any luck on this issue?

**Comment by thiagocrepaldi** [comment]
Please try the new ONNX exporter and let us know if it works for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

**Comment by BowenBao** [comment]
ONNX model does not allow mutation to model weights during inference. That is, the mutating behavior of this line is not captured `self.last_hidden = hidden`.

In order to achieve the intended behavior in ONNX model, you can modify your original pytorch model, to expose `last_hidden` as both model input and output. Hence when inferencing your exported ONNX model, you can supply the different `last_hidden` value in each iteration, as well as retrieving the updated `last_hidden` value.
