### ISSUE TITLE
[functorch] functorch_maml_omniglot - fails under torch.compile

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#98825]
### 🐛 Describe the bug

Running `functorch_maml_omniglot` from `torchbench` with following patch
```patch
diff --git a/torchbenchmark/models/functorch_maml_omniglot/__init__.py b/torchbenchmark/models/functorch_maml_omniglot/__init__.py
index faf16d73..430eaadf 100644
--- a/torchbenchmark/models/functorch_maml_omniglot/__init__.py
+++ b/torchbenchmark/models/functorch_maml_omniglot/__init__.py
@@ -10,6 +10,17 @@ from typing import Tuple
 from ...util.model import BenchmarkModel
 from torchbenchmark.tasks import OTHER
 
+from torch._dynamo import allow_in_graph
+from functools import wraps
+
+def traceable(f):
+    f = allow_in_graph(f)
+
+    @wraps(f)
+    def wrapper(*args, **kwargs):
+        return f(*args, **kwargs)
+
+    return wrapper
 
 def loss_for_task(net, n_inner_iter, x_spt, y_spt, x_qry, y_qry):
     params, buffers, fnet = net
@@ -66,7 +77,7 @@ class Model(BenchmarkModel):
         self.model = net
 
         root = str(Path(__file__).parent.parent)
-        self.meta_inputs = torch.load(f'{root}/maml_omniglot/batch.pt')
+        self.meta_inputs = torch.load(f'{root}/functorch_maml_omniglot/batch.pt')
         self.meta_inputs = tuple([torch.from_numpy(i).to(self.device) for i in self.meta_inputs])
         self.example_inputs = (self.meta_inputs[0][0],)
 
@@ -90,7 +101,9 @@ class Model(BenchmarkModel):
         # In parallel, trains one model per task. There is a support (x, y)
         # for each task and a query (x, y) for each task.
         compute_loss_for_task = functools.partial(loss_for_task, net, n_inner_iter)
-        qry_losses, qry_accs = vmap(compute_loss_for_task)(x_spt, y_spt, x_qry, y_qry)
+        fn = vmap(compute_loss_for_task)
+        fn = torch.compile(traceable(fn))
+        qry_losses, qry_accs = fn(x_spt, y_spt, x_qry, y_qry)
 
         # Compute the maml loss by summing together the returned losses.
         qry_losses.sum().backward()
```

Leads to failure:
```
Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.convolution.default(*(FakeTensor(FakeTensor(..., device='meta', size=(160, 1, 28, 28)), cpu), 
```

### Versions

master

**Comment by zou3519** [comment]
Yes, we expect this to work (the vmap code is traceable), modulo safety issues on if the function being vmapped over isn't actually traceable.

**Comment by kshitij12345** [comment]
The model compilation works with some tweaks.

**Comment by guilhermeleobas** [comment]
Attempting to compile this model still fails for me:

```bash
$ TORCH_LOGS=+graph_code python run.py -d cpu -t train functorch_maml_omniglot
Running train method from functorch_maml_omniglot on cpu in eager mode with input batch size 1 and precision fp32.
/home/guilhermeleobas/git/benchmark/torchbenchmark/models/functorch_maml_omniglot/__init__.py:114: FutureWarning: We've integrated functorch into PyTorch. As the final step of the integration, `functorch.make_functional_with_buffers` is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use `torch.func.functional_call` instead; see the PyTorch 2.0 release notes and/or the `torch.func` migration guide for more details https://pytorch.org/docs/main/func.migrating.html
  fnet, params, buffers = make_functional_with_buffers(self.model)
/home/guilhermeleobas/git/benchmark/torchbenchmark/models/functorch_maml_omniglot/__init__.py:129: FutureWarning: We've integrated functorch into PyTorch. As the final step of the integration, `functorch.vmap` is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use `torch.vmap` instead; see the PyTorch 2.0 release notes and/or the `torch.func` migration guide for more details https://pytorch.org/docs/main/func.migrating.html
  fn = vmap(compute_loss_for_task)
/home/guilhermeleobas/micromamba/envs/flash-attention/lib/python3.12/site-packages/torch/_dynamo/utils.py:3377: FutureWarning: We've integrated functorch into PyTorch. As the final step of the integration, `functorch.grad` is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use `torch.func.grad` instead; see the PyTorch 2.0 release notes and/or the `torch.func` migration guide for more details https://pytorch.org/docs/main/func.migrating.html
  lambda: run_node(tx.output, node, args, kwargs, nnmodule)
Traceback (most recent call last):
  File "/home/guilhermeleobas/git/benchmark/run.py", line 596, in <module>
    main()  # pragma: no cover
    ^^^^^^
  File "/home/guilhermeleobas/git/benchmark/run.py", line 565, in main
    run_one_step(
  File "/home/guilhermeleobas/git/benchmark/run.py", line 170, in run_one_step
    func()
  File "/home/guilhermeleobas/git/benchmark/torchbenchmark/util/model.py", line 415, in invoke
    self.train()
  File "/home/guilhermeleobas/git/benchmark/torchbenchmark/models/functorch_maml_omniglot/__init__.py", line 131, in train
    qry_losses, qry_accs = fn(x_spt, y_spt, x_qry, y_qry)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilhermeleobas/micromamba/envs/flash-attention/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 841, in compile_wrapper
    raise e.with_traceback(None) from e.__cause__  # User compiler error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._dynamo.exc.Unsupported: Attempted to inline function marked as skipped
  Explanation: Dynamo developers have intentionally marked that the function `FunctionalModuleWithBuffers.forward` should not be traced.
  Hint: Avoid calling the function `FunctionalModuleWithBuffers.forward`.
  Hint: Apply `@torch._dynamo.dont_skip_tracing` to the function `FunctionalModuleWithBuffers.forward` to force tracing into the function. More graph breaks may occur as a result of attempting to trace into the function.
  Hint: Please file an issue to PyTorch.

  Developer debug context: qualname: FunctionalModuleWithBuffers.forward, name: forward, filename: `/home/guilhermeleobas/micromamba/envs/flash-attention/lib/python3.12/site-packages/torch/_functorch/make_functional.py`, skip reason: skipped according trace_rules.lookup MOD_SKIPLIST

 For more details about this graph break, please visit: https://meta-pytorch.github.io/compile-graph-break-site/gb/gb0008.html

from user code:
   File "/home/guilhermeleobas/micromamba/envs/flash-attention/lib/python3.12/site-packages/torch/_functorch/apis.py", line 208, in wrapped
    return vmap_impl(
  File "/home/guilhermeleobas/micromamba/envs/flash-attention/lib/python3.12/site-packages/torch/_functorch/vmap.py", line 282, in vmap_impl
    return _flat_vmap(
  File "/home/guilhermeleobas/micromamba/envs/flash-attention/lib/python3.12/site-packages/torch/_functorch/vmap.py", line 432, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
  File "/home/guilhermeleobas/git/benchmark/torchbenchmark/models/functorch_maml_omniglot/__init__.py", line 28, in loss_for_task
    grads = grad(compute_loss)(new_params, buffers, x_spt, y_spt)
  File "/home/guilhermeleobas/micromamba/envs/flash-attention/lib/python3.12/site-packages/torch/_functorch/apis.py", line 406, in wrapper
    return eager_transforms.grad_impl(func, argnums, has_aux, args, kwargs)
  File "/home/guilhermeleobas/micromamba/envs/flash-attention/lib/python3.12/site-packages/torch/_functorch/eager_transforms.py", line 1406, in grad_impl
    results = grad_and_value_impl(func, argnums, has_aux, args, kwargs)
  File "/home/guilhermeleobas/micromamba/envs/flash-attention/lib/python3.12/site-packages/torch/_functorch/vmap.py", line 47, in fn
    return f(*args, **kwargs)
  File "/home/guilhermeleobas/micromamba/envs/flash-attention/lib/python3.12/site-packages/torch/_functorch/eager_transforms.py", line 1364, in grad_and_value_impl
    output = func(*args, **kwargs)
  File "/home/guilhermeleobas/git/benchmark/torchbenchmark/models/functorch_maml_omniglot/__init__.py", line 22, in compute_loss
    logits = fnet(new_params, buffers, x)
```
