### ISSUE TITLE
Sparse Tensor not working for `torch.cat`

### ISSUE THREAD

**Issue by puririshi98** [pytorch/pytorch#98861]
### 🐛 Describe the bug

cc: @rusty1s 
both of these examples repro the issue:
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/egc.py
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/gcn2_ppi.py

repro:
`cd /opt/pyg; pip uninstall -y torch-geometric torch-scatter torch-sparse torch-spline-conv torch-cluster; rm -rf pytorch_geometric; git clone -b fix-for-collate https://github.com/pyg-team/pytorch_geometric.git; cd /opt/pyg/pytorch_geometric; pip install .; python3 examples/egc.py; python3 examples/gcn2_ppi.py`

error:
```
Traceback (most recent call last):
  File "examples/gcn2_ppi.py", line 93, in <module>
    loss = train()
  File "examples/gcn2_ppi.py", line 67, in train
    for data in train_loader:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 635, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 679, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/loader/dataloader.py", line 20, in __call__
    return Batch.from_data_list(batch, self.follow_batch,
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/batch.py", line 76, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/collate.py", line 85, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/collate.py", line 178, in _collate
    value = torch.cat(values, dim=cat_dim)
RuntimeError: Sparse CSR tensors do not have is_contiguous
```

### Versions

root@979d4b259838:/opt/pyg/pytorch_geometric# python collect_env.py

Collecting environment information...
PyTorch version: 2.0.0a0+1767026
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40
GPU 2: NVIDIA A40
GPU 3: NVIDIA A40

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.8.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7282 16-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1493.554
CPU max MHz:                     2800.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        5589.38
Virtualization:                  AMD-V
L1d cache:                       512 KiB
L1i cache:                       512 KiB
L2 cache:                        8 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] flake8==5.0.3
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.22.3
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.0.0a0+1767026
[pip3] torch_geometric==2.4.0
[pip3] torch-tensorrt==1.4.0.dev0
[pip3] torchmetrics==0.9.3
[pip3] torchtext==0.13.0a0+fae8e8c
[pip3] torchvision==0.15.0a0
[pip3] triton==2.0.0
[pip3] tritonclient==2.29.0
[conda] Could not collect

**Comment by puririshi98** [comment]
okay thanks for clarifying, is there an eta on torch sparse cat support?

**Comment by nikitaved** [comment]
@puririshi98 , not that I am aware of. Could you please open a feature request with some strong motivation (like GPytorch capability) and your use case?

**Comment by puririshi98** [comment]
@nikitaved, checking in if this is possible in the semi near term future. torch sparse sum not works for our use case, torch cat is the last remaining piece of native torch sparse support we need in PyG

**Comment by nikitaved** [comment]
@puririshi98 , could you please be more specific with the use case and the dimension to cat along? I see it is for CSR inputs, right?

**Comment by puririshi98** [comment]
yes that is correct, the use case is to cat CSR inputs for collating data:
```
Traceback (most recent call last):
  File "examples/gcn2_ppi.py", line 93, in <module>
    loss = train()
  File "examples/gcn2_ppi.py", line 67, in train
    for data in train_loader:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 635, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 679, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/loader/dataloader.py", line 20, in __call__
    return Batch.from_data_list(batch, self.follow_batch,
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/batch.py", line 76, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/collate.py", line 85, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/data/collate.py", line 178, in _collate
    value = torch.cat(values, dim=cat_dim)
RuntimeError: Sparse CSR tensors do not have is_contiguous
```

**Comment by puririshi98** [comment]
@nikitaved following up

**Comment by zbh2047** [comment]
@nikitaved PyTorch 2.6 still does not have this feature. However, the documentation mentioned that torch.cat supports sparse tensors. See pytorch.org/docs/stable/sparse.html
In “other functions” section.
Can you look into this? Thank you!
