### ISSUE TITLE
torch.sparse_csr_tensor() stops gradients

### ISSUE THREAD

**Issue by Turakar** [pytorch/pytorch#98929]
### 🐛 Describe the bug

I would expect the following code to produce a gradient w.r.t. `a`, but instead it stops the gradient flow at `torch.sparse_csr_tensor()`.

```python
import torch

a = torch.randn(3, requires_grad=True)
b = torch.sparse_csr_tensor(
    torch.tensor([0, 2, 2, 3]),
    torch.tensor([0, 1, 2]),
    a,
)
print(b.grad_fn)
torch.sum(b).backward()
```

Accordingly, this is the output:
```
None

Traceback (most recent call last):
  File "/path/csr_grad.py", line 58, in <module>
    main_csr()
  File "/path/csr_grad.py", line 36, in main_csr
    torch.sum(b).backward()
  File "/venv/lib64/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/venv/lib64/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

The same code works for COO tensors, but I need the performance benefits of CSR tensors.

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Fedora Linux 37 (KDE Plasma) (x86_64)
GCC version: (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.36

Python version: 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (64-bit runtime)
Python platform: Linux-6.2.7-200.fc37.x86_64-x86_64-with-glibc2.36
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070 SUPER
Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.8.1
/usr/lib64/libcudnn_adv_infer.so.8.8.1
/usr/lib64/libcudnn_adv_train.so.8.8.1
/usr/lib64/libcudnn_cnn_infer.so.8.8.1
/usr/lib64/libcudnn_cnn_train.so.8.8.1
/usr/lib64/libcudnn_ops_infer.so.8.8.1
/usr/lib64/libcudnn_ops_train.so.8.8.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 2700 Eight-Core Processor
CPU family:                      23
Model:                           8
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        2
Frequency boost:                 enabled
CPU(s) scaling MHz:              67%
CPU max MHz:                     3200.0000
CPU min MHz:                     1550.0000
BogoMIPS:                        6387.18
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sev sev_es
Virtualization:                  AMD-V
L1d cache:                       256 KiB (8 instances)
L1i cache:                       512 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] triton==2.0.0
[conda] Could not collect
```

**Comment by nikitaved** [comment]
As a temporary workaround you could construct a COO tensor (this one does support autograd for values), and then use `to_sparse(torch.sparse_csr)` which should work as well as we have both COO-CSR and CSR-COO conversions.

**Comment by nikitaved** [comment]
Even with batch dimensions, if the use case allows that, it is possible to merge batch dims with the row space. But, yeah, I agree, we should support autograd for all sparse constructors...

**Comment by Turakar** [comment]
Merging batch dims with the row space is an interesting idea that might fix my use case. Thanks!

**Comment by nikitaved** [comment]
@Turakar , if you do that, note that there is a limitation in the batch dim support, namely, all matrices in the batch need to have the same nnz. This means it is possible to convert a batched sparse matrix to a matrix, but not the other way around, so make sure a 2D matrix is constructed right from the get-go. If you need any help, please, let us know :)

**Comment by cpuhrsch** [comment]
@amjames - Can you take a look at this?

**Comment by taddyb** [comment]
Since I haven't gotten any updates, or found where to insert my fix, I'll just leave it here for people to use:

``` py
import torch

class BackwardSparse(torch.autograd.Function):
    """
    A custom autograd function for using sparse tensors
    """

    @staticmethod
    def forward(ctx, A_values, crow_indices, col_indices):
        """
        In the forward pass we receive a Tensor containing the input and return
        a Tensor containing the output. ctx is a context object that can be used
        to stash information for backward computation. You can cache arbitrary
        objects for
        """
        A_csr = torch.sparse_csr_tensor(
            crow_indices,
            col_indices,
            A_values,
            dtype=torch.float64,
        )
        ctx.save_for_backward(
            A_values,
            A_csr,
            crow_indices,
            col_indices,
        )
        return A_csr

    @staticmethod
    def backward(ctx, grad_output):
        """
        In the backward pass, we receive a Tensor containing the gradient of the loss
        with respect to the output, and we need to compute the gradient of the loss
        with respect to the input.
        """

        def extract_csr_values(
            col_indices: torch.Tensor,
            crow_indices: torch.Tensor,
            dense_matrix: torch.Tensor,
        ) -> torch.Tensor:
            """
            Taking dense matrices and getting the sparse values
            :param col_indices:
            :param crow_indices:
            :param dense_matrix:
            :return:
            """
            crow_indices_list = crow_indices.tolist()
            col_indices_list = col_indices.tolist()
            rows = []
            cols = []
            for i in range(len(crow_indices_list) - 1):
                start, end = crow_indices_list[i], crow_indices_list[i + 1]
                these_cols = col_indices_list[start:end]
                these_rows = [i] * len(these_cols)
                rows.extend(these_rows)
                cols.extend(these_cols)
            values = dense_matrix[rows, cols]
            return values

        with torch.no_grad():
            A_values, A_csr, crow_indices, col_indices = ctx.saved_tensors
            grad_A_values = extract_csr_values(col_indices, crow_indices, grad_output)
        return grad_A_values, None, None, None
```

to call this, you would run the following where you instantiate your sparse matrix
``` py
A_csr = BackwardSparse.apply(
    A_values,
    mapper.crow_indices,
    mapper.col_indices
)
```
this solution only requires that you know the dimensions of your sparse csr ahead of time.
