### ISSUE TITLE
InternalTorchDynamoError when using torch.compile with Huggingface Llama model and PEFT

### ISSUE THREAD

**Issue by q-hwang** [pytorch/pytorch#98993]
### 🐛 Describe the bug

When `torch.compile` is applied to the Huggingface model `LlamaForCausalLM` wrapped with PEFT (https://github.com/huggingface/peft), the forward compilation failed with `torch._dynamo.exc.InternalTorchDynamoError`.

## Minimal Example 

```python
from transformers import LlamaTokenizer, LlamaForCausalLM
import torch
from peft import LoraConfig, get_peft_model, TaskType, get_peft_config

tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-7b-hf")
model = LlamaForCausalLM.from_pretrained("decapoda-research/llama-7b-hf").to("cuda:6")
lora_config = LoraConfig(
        r=16, lora_alpha=32, target_modules=["q_proj", "v_proj"], lora_dropout=0.05, bias="none", task_type="CAUSAL_LM"
    )
model = get_peft_model(model, lora_config)

model = torch.compile(model)

# generate some dummy input

x = tokenizer("Hello, my dog is cute", return_tensors="pt")
x = x.to("cuda:6")
outputs = model(**x, labels=x["input_ids"])
outputs.loss.backward()
```

Error Trace:
```
Traceback (most recent call last):
  File "/dfs/user/qhwang/toy/mem/bug.py", line 18, in <module>
    outputs = model(**x, labels=x["input_ids"])
  File "/lfs/hyperturing2/0/qhwang/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lfs/hyperturing2/0/qhwang/miniconda3/envs/llm/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/lfs/hyperturing2/0/qhwang/miniconda3/envs/llm/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/lfs/hyperturing2/0/qhwang/miniconda3/envs/llm/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/lfs/hyperturing2/0/qhwang/miniconda3/envs/llm/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/lfs/hyperturing2/0/qhwang/miniconda3/envs/llm/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/lfs/hyperturing2/0/qhwang/miniconda3/envs/llm/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/lfs/hyperturing2/0/qhwang/miniconda3/envs/llm/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/lfs/hyperturing2/0/qhwang/miniconda3/envs/llm/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 394, in _compile
    raise InternalTorchDynamoError() from e
torch._dynamo.exc.InternalTorchDynamoError
```

### Versions

```
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.23

Python version: 3.9.0 (default, Nov 15 2020, 14:28:56)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-122-generic-x86_64-with-glibc2.23
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA Quadro RTX 8000
GPU 1: NVIDIA Quadro RTX 8000
GPU 2: NVIDIA Quadro RTX 8000
GPU 3: NVIDIA Quadro RTX 8000
GPU 4: NVIDIA Quadro RTX 8000
GPU 5: NVIDIA Quadro RTX 8000
GPU 6: NVIDIA Quadro RTX 8000
GPU 7: NVIDIA Quadro RTX 8000
GPU 8: NVIDIA Quadro RTX 8000
GPU 9: NVIDIA Quadro RTX 8000

Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                256
On-line CPU(s) list:   0-254
Off-line CPU(s) list:  255
Thread(s) per core:    1
Core(s) per socket:    64
Socket(s):             2
NUMA node(s):          2
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7742 64-Core Processor
Stepping:              0
CPU MHz:               1498.807
CPU max MHz:           2250.0000
CPU min MHz:           1500.0000
BogoMIPS:              4493.31
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0-63,128-191
NUMA node1 CPU(s):     64-127,192-254
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl $
topology nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse$
a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bm$
2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_sc$
le vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @anijain2305 @desertfire

**Comment by w5688414** [comment]
I meet the same problem, here is my error:

```
│ /root/miniconda3/envs/llm/lib/python3.9/site-packages/torch-2.0.1-py3.9-linux-x86_64.egg/torch/_ │
│ dynamo/variables/builtin.py:931 in call_getattr                                                  │
│                                                                                                  │
│    928 │   │   │   source = None                                                                 │
│    929 │   │                                                                                     │
│    930 │   │   if isinstance(obj, variables.NNModuleVariable):                                   │
│ ❱  931 │   │   │   return obj.var_getattr(tx, name).add_options(options)                         │
│    932 │   │   elif isinstance(obj, variables.TensorVariable) and name == "grad":                │
│    933 │   │   │   if source:                                                                    │
│    934 │   │   │   │   # We are going to be raising this tensor as grapharg. So, ensure          │
│                                                                                                  │
│ /root/miniconda3/envs/llm/lib/python3.9/site-packages/torch-2.0.1-py3.9-linux-x86_64.egg/torch/_ │
│ dynamo/variables/nn_module.py:124 in var_getattr                                                 │
│                                                                                                  │
│   121 │   │   elif "_buffers" in base_dict and name in base_dict["_buffers"]:                    │
│   122 │   │   │   subobj = base_dict["_buffers"][name]                                           │
│   123 │   │   else:                                                                              │
│ ❱ 124 │   │   │   subobj = inspect.getattr_static(base, name)                                    │
│   125 │   │   │   object_member = False                                                          │
│   126 │   │                                                                                      │
│   127 │   │   if name == "__class__" and not object_member:                                      │
│                                                                                                  │
│ /root/miniconda3/envs/llm/lib/python3.9/inspect.py:1650 in getattr_static                        │
│                                                                                                  │
│   1647 │   │   │   │   │   pass                                                                  │
│   1648 │   if default is not _sentinel:                                                          │
│   1649 │   │   return default                                                                    │
│ ❱ 1650 │   raise AttributeError(attr)                                                            │
│   1651                                                                                           │
│   1652                                                                                           │
│   1653 # ------------------------------------------------ generator introspection                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: config

......

│ ❱ 104 │   │   │   return fn(*args, **kwargs)                                                     │
│   105 │   │   finally:                                                                           │
│   106 │   │   │   torch._C._set_grad_enabled(prior_grad_mode)                                    │
│   107 │   │   │   torch.random.set_rng_state(rng_state)                                          │
│                                                                                                  │
│ /root/miniconda3/envs/llm/lib/python3.9/site-packages/torch-2.0.1-py3.9-linux-x86_64.egg/torch/_ │
│ dynamo/convert_frame.py:262 in _convert_frame_assert                                             │
│                                                                                                  │
│   259 │   │   global initial_grad_state                                                          │
│   260 │   │   initial_grad_state = torch.is_grad_enabled()                                       │
│   261 │   │                                                                                      │
│ ❱ 262 │   │   return _compile(                                                                   │
│   263 │   │   │   frame.f_code,                                                                  │
│   264 │   │   │   frame.f_globals,                                                               │
│   265 │   │   │   frame.f_locals,                                                                │
│                                                                                                  │
│ /root/miniconda3/envs/llm/lib/python3.9/site-packages/torch-2.0.1-py3.9-linux-x86_64.egg/torch/_ │
│ dynamo/utils.py:163 in time_wrapper                                                              │
│                                                                                                  │
│    160 │   │   │   if key not in compilation_metrics:                                            │
│    161 │   │   │   │   compilation_metrics[key] = []                                             │
│    162 │   │   │   t0 = time.time()                                                              │
│ ❱  163 │   │   │   r = func(*args, **kwargs)                                                     │
│    164 │   │   │   time_spent = time.time() - t0                                                 │
│    165 │   │   │   # print(f"Dynamo timer: key={key}, latency={latency:.2f} sec")                │
│    166 │   │   │   compilation_metrics[key].append(time_spent)                                   │
│                                                                                                  │
│ /root/miniconda3/envs/llm/lib/python3.9/site-packages/torch-2.0.1-py3.9-linux-x86_64.egg/torch/_ │
│ dynamo/convert_frame.py:394 in _compile                                                          │
│                                                                                                  │
│   391 │   │   raise                                                                              │
│   392 │   except Exception as e:                                                                 │
│   393 │   │   exception_handler(e, code, frame)                                                  │
│ ❱ 394 │   │   raise InternalTorchDynamoError() from e                                            │
│   395                                                                                            │
│   396                                                                                            │
│   397 def convert_frame(compiler_fn: CompilerFn, hooks: Hooks):                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
InternalTorchDynamoError
....
```

**Comment by vasudev-sharma** [comment]
Any fix to the issue? I am facing the same issue as well.

**Comment by huynhbaobk** [comment]
Any update for the issue

**Comment by MindKrypted** [comment]
Using the Ludwig framework, I just got the same issue while trying the compilation option finetuning llama model (it also stops at the forward pass).

**Comment by anijain2305** [comment]
This seems to work on `main` branch. @q-hwang @MindKrypted Can you check again? If it does not work, can you please provide a repro script.

**Comment by BenjaminBossan** [comment]
The offending line in PEFT apparently was this one:

https://github.com/huggingface/peft/blob/139624750a6a431b9958be5c9485aec5571d64c1/src/peft/peft_model.py#L933

It doesn't matter what comes in the if-block, simply accessing `self.base_model.config` caused the error. With PyTorch v2.1.0, it is working though, so next release should fix it.

**Comment by anijain2305** [comment]
Ok, I will close the issue then. Please feel free to reopen if you still see the issue.

**Comment by mrunal-create** [comment]
But PyTorch v2.1.0 hasnt been released yet. SO is there any work around for this?

**Comment by mrunal-create** [comment]
i installed 2.1.0 still facing the error

**Comment by RylanSchaeffer** [comment]
I have something similar to this error
