### ISSUE TITLE
[ppc64le pytorch] Failure when running test_c10d.py  on CPU only server

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#9906]
when building pytorch master from July 25,   I'm getting failure described below.
I'm building on CPU only system.

Possibly caused by #9670

Maybe just add a check to see if a GPU is available if not skip the test.
I do have CUDA libraries installed but it is just running on a system without a GPU.

here is the build log :  https://powerci.osuosl.org/job/pytorch-master-nightly-py3-linux-ppc64le/386/

The error messages

FAIL: test_allreduce_ops (__main__.ProcessGroupGlooTest)
Traceback (most recent call last):
  File "test_c10d.py", line 205, in wrapper
    self._join_processes(fn)
  File "test_c10d.py", line 250, in _join_processes
    self._check_return_codes()
  File "test_c10d.py", line 263, in _check_return_codes
    self.assertEqual(first_process.exitcode, 0)
  File "/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/test/common.py", line 362, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 6 not less than or equal to 1e-05 : 

FAIL: test_broadcast_ops (__main__.ProcessGroupGlooTest)
Traceback (most recent call last):
  File "test_c10d.py", line 205, in wrapper
    self._join_processes(fn)
  File "test_c10d.py", line 250, in _join_processes
    self._check_return_codes()
  File "test_c10d.py", line 263, in _check_return_codes
    self.assertEqual(first_process.exitcode, 0)
  File "/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/test/common.py", line 362, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 6 not less than or equal to 1e-05 : 

The logs also show
test_allreduce_ops (__main__.ProcessGroupGlooTest) ... THCudaCheck FAIL file=/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
terminate called without an active exception
THCudaCheck FAIL file=/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
terminate called without an active exception
THCudaCheck FAIL file=/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
terminate called without an active exception
THCudaCheck FAIL file=/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
terminate called without an active exception
FAIL
test_broadcast_ops (__main__.ProcessGroupGlooTest) ... THCudaCheck FAIL file=/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
terminate called without an active exception
THCudaCheck FAIL file=/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
terminate called without an active exception
THCudaCheck FAIL file=/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
terminate called without an active exception
THCudaCheck FAIL file=/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
terminate called without an active exception
FAIL

**Comment by avmgithub** [comment]
this seem to have been fixed, closing
