### ISSUE TITLE
`torch.compile` failed in multi node distributed training

### ISSUE THREAD

**Issue by BruceChang9688** [pytorch/pytorch#99067]
### 🐛 Describe the bug

We tested mnist multi nodes distributed training with `gloo backend` and `torch.compiler inductor`.
Initiated model here
```
# Based on https://github.com/pytorch/examples/blob/master/mnist/main.py
class Net(nn.Module):
    def __init__(self):
        logger.info("Create neural network module")

        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)
```
training script is
```
model = Net()

    if is_distributed:
        if use_cuda:
            device_id = dist.get_rank() % torch.cuda.device_count()
            device = torch.device(f"cuda:{device_id}")
            # multi-machine multi-gpu case
            logger.debug("Multi-machine multi-gpu cuda: using DistributedDataParallel.")
        # for multiprocessing distributed, the DDP constructor should always set
        # the single device scope. otherwise, DDP will use all available devices.
        model = torch.nn.parallel.DistributedDataParallel(model).to(device)
    else:
        # single-machine or multi-machine cpu case
        logger.debug("Single-machine cpu: using DistributedDataParallel.")
    model = model.to(device)

    if use_inductor:
        logger.debug("Inductor: using Inductor.")
        model = torch.compile(model, backend="inductor", mode="default")

    optimizer = optim.SGD(model.parameters(), lr=args.lr, momentum=args.momentum)

    for epoch in range(1, args.epochs + 1):
        model.train()
        for batch_idx, (data, target) in enumerate(train_loader, 1):
            if is_distributed and use_cuda:
                # multi-machine multi-gpu case - allow asynchrous GPU copies of the data
                data, target = data.to(device, non_blocking=True), target.to(device, non_blocking=True)
            else:
                data, target = data.to(device), target.to(device)
            optimizer.zero_grad()
            output = model(data)
            loss = F.nll_loss(output, target)
            loss.backward()
            if is_distributed:
                # average gradients manually for multi-machine cpu case only
                _average_gradients(model)
            optimizer.step()
            if batch_idx % args.log_interval == 0:
                logger.debug('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                    epoch, batch_idx * len(data), len(train_loader.sampler),
                    100. * batch_idx / len(train_loader), loss.item()))
        test(model, test_loader, device)
    save_model(model, args.model_dir, args)
```

### Error logs
```
Test set: Average loss: 0.0003, Accuracy: 9111/10000 (91%)
--
DEBUG:__main__:Test set: Average loss: 0.0003, Accuracy: 9111/10000 (91%)
INFO:__main__:Saving the model: model_0.pth
Saving the model: model_0.pth
free(): invalid pointer
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 43) of binary: /opt/conda/bin/python
Traceback (most recent call last):  File "/opt/conda/bin/torchrun", line 33, in <module>
sys.exit(load_entry_point('torch==2.0.0', 'console_scripts', 'torchrun')())  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
return f(*args, **kwargs)  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
run(args)  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
elastic_launch(  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
return launch_agent(self._config, self._entrypoint, list(args))  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
===================================================
mnist.py FAILED
---------------------------------------------------
Failures:  <NO_OTHER_FAILURES>
---------------------------------------------------
Root Cause (first observed failure):
[0]:  time      : 2023-04-12_23:25:14  host      : algo-1  rank      : 1 (local_rank: 0)  exitcode  : -6 (pid: 43)  error_file: <N/A>  traceback : Signal 6 (SIGABRT) received by PID 43
===================================================
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.31

Python version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1031-aws-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          48
On-line CPU(s) list:             0-47
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7R32
Stepping:                        0
CPU MHz:                         2799.594
BogoMIPS:                        5599.18
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        12 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-47
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save rdpid

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] sagemaker-pytorch-training==2.7.0
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.0
[pip3] torchtext==0.15.1
[pip3] torchtnt==0.0.7
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl    conda-forge
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    https://aws-ml-conda-pre-prod-sm.s3.us-west-2.amazonaws.com
[conda] mkl-include               2023.0.0         h84fe81f_26648    conda-forge
[conda] numpy                     1.23.5          py310h53a5b5f_0    conda-forge
[conda] pytorch                   2.0.0           aws_py3.10_cuda11.8_cudnn8.7.0_0    https://aws-ml-conda-pre-prod-sm.s3.us-west-2.amazonaws.com
[conda] pytorch-cuda              11.8                 h7e8668a_3    https://aws-ml-conda-pre-prod-ec2.s3.us-west-2.amazonaws.com
[conda] pytorch-mutex             1.0                        cuda    https://aws-ml-conda-pre-prod-sm.s3.us-west-2.amazonaws.com
[conda] sagemaker-pytorch-training 2.7.0                    pypi_0    pypi
[conda] torchaudio                2.0.1               py310_cu118    https://aws-ml-conda-pre-prod-sm.s3.us-west-2.amazonaws.com
[conda] torchdata                 0.6.0                     py310    https://aws-ml-conda-pre-prod-sm.s3.us-west-2.amazonaws.com
[conda] torchtext                 0.15.1                    py310    https://aws-ml-conda-pre-prod-sm.s3.us-west-2.amazonaws.com
[conda] torchtnt                  0.0.7                    pypi_0    pypi
[conda] torchtriton               2.0.0                     py310    https://aws-ml-conda-pre-prod-sm.s3.us-west-2.amazonaws.com
[conda] torchvision               0.15.1              py310_cu118    https://aws-ml-conda-pre-prod-sm.s3.us-west-2.amazonaws.com
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by nanand2** [comment]
torch.compile failed for me with single node multi-gpu DistributedDataParallel. Error below. No issue and clear speedups with single-gpu training. 

```torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
TypeError: _convert_frame_assert() missing 2 required positional arguments: 'hooks' and 'frame_state'

**Comment by wconstab** [comment]
I tried a bit to piece the mnist example togetherh with the snippets above, but there are some significant missing pieces.  If you can put together one whole script (minimal lines of code if possible), which I can copy-paste and run to repro the error, that would be helpful.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/issues/99067#issuecomment-1571113201 this error should be trivial to fix by code inspection...

**Comment by anijain2305** [comment]
Closing this due to inactivity.  @BruceChang9688 Please feel free to reopen. It would be helpful to have a repro.
