### ISSUE TITLE
OOM in fuse_attention inductor pass

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#99084]
### 🐛 Describe the bug

I have a model from @murphyk that's OOM'ing unless I explicitly disable the inductor pattern matcher. cc @ezyang @soumith @wconstab @ngimel @bdhirsh @cpuhrsch - cuda graphs had no impact 

So just uncomment line `torch._inductor.config.pattern_matcher = False` to get the example to work

I removed a lot of jax related stuff but here is the original code https://github.com/probml/dynamax/blob/main/dynamax/linear_gaussian_ssm/demos/kf_linreg_jax_vs_pt.py

```python
import numpy as np
from typing import Callable, NamedTuple, Union, Tuple, Any
from functools import partial

import time
import platform

import torch



def allclose(u, v):
    # we cast to numpy so we can compare pytorch and jax
    return np.allclose(np.array(u), np.array(v), atol=1e-3)


def predict(m, S, F, Q):
    mu_pred = F @ m 
    Sigma_pred = F @ S @ F.T + Q
    return mu_pred, Sigma_pred


### TORCH

def predict_pt(m, S, F, Q):
    mu_pred = F @ m 
    Sigma_pred = F @ S @ F.T + Q
    return mu_pred, Sigma_pred

def condition_on_pt(m, P, H, R, y):
    S = R + H @ P @ H.T
    K = torch.linalg.solve(S + 1e-6, H @ P).T
    Sigma_cond = P - K @ S @ K.T
    mu_cond = m + K @ (y - H @ m)
    return mu_cond, Sigma_cond

def kf_pt(params, emissions, return_covs=False, compile=False):
    F, Q, R = params['F'], params['Q'], params['R']
    def step(carry, t):
        ll, pred_mean, pred_cov = carry
        H = params['Ht'][t]
        y = emissions[t]
        #ll += MVN(H @ pred_mean, H @ pred_cov @ H.T + R).log_prob(y)
        filtered_mean, filtered_cov = condition_on_pt(pred_mean, pred_cov, H, R, y)
        pred_mean, pred_cov = predict_pt(filtered_mean, filtered_cov, F, Q)
        carry = (ll, pred_mean, pred_cov)
        if return_covs:
            return carry, (filtered_mean, filtered_cov)
        else:
            return carry, filtered_mean
    
    if compile:
        if platform.system() == 'Darwin':
            # https://discuss.pytorch.org/t/torch-compile-seems-to-hang/177089
            step = torch.compile(step, backend="aot_eager")
        else:
            import torch._inductor.config
            torch._inductor.config.triton.cudagraphs = True
            # uncomment this line to get things to work
            # torch._inductor.config.pattern_matcher = False
            step = torch.compile(step, dynamic=True)
    num_timesteps = len(emissions)
    D = len(params['mu0'])
    import torch
    filtered_means = torch.zeros((num_timesteps, D))
    if return_covs:
        filtered_covs = torch.zeros((num_timesteps, D, D))
    else:
        filtered_covs = None
    ll = 0
    carry = (ll, params['mu0'], params['Sigma0'])
    for t in range(num_timesteps):
        if return_covs:
            carry, (filtered_means[t], filtered_covs[t]) = step(carry, 1)
        else:
            carry, filtered_means[t] = step(carry, 1)
    return ll, filtered_means, filtered_covs

## Compare jax and torch

def convert_params_to_pt(params, Y):
    F, Q, R, Ht, mu0, Sigma0 = params['F'], params['Q'], params['R'], params['Ht'], params['mu0'], params['Sigma0']
    Y_pt = torch.tensor(np.array(Y))
    F_pt = torch.tensor(np.array(F))
    Q_pt = torch.tensor(np.array(Q))
    R_pt = torch.tensor(np.array(R))
    Ht_pt = torch.tensor(np.array(Ht))
    mu0_pt = torch.tensor(np.array(mu0))
    Sigma0_pt = torch.tensor(np.array(Sigma0))
    param_dict_pt = {'mu0': mu0_pt, 'Sigma0': Sigma0_pt, 'F': F_pt, 'Q': Q_pt, 'R': R_pt, 'Ht': Ht_pt}
    return param_dict_pt, Y_pt

def make_linreg_data_pt(N, D):
    torch.manual_seed(0)
    X = torch.randn((N, D))
    w = torch.randn((D, 1))
    y = X @ w + 0.1*torch.randn((N, 1))
    return X, y

def make_linreg_data_np(N, D):
    np.random.seed(0)
    X = np.random.randn(N, D)
    w = np.random.randn(D, 1)
    y = X @ w + 0.1*np.random.randn(N, 1)
    return X, y

def make_params_and_data_pt(N, D):
    X_np, Y_np = make_linreg_data_np(N, D)
    N, D = X_np.shape
    X1_np = np.column_stack((np.ones(N), X_np))  # Include column of 1s
    Ht_np = X1_np[:, None, :] # (T,D) -> (T,1,D), yhat = H[t]'z = (b w)' (1 x)
    nfeatures = X1_np.shape[1] # D+1
    Ht_pt = torch.tensor(Ht_np, dtype=torch.double)
    mu0_pt = torch.zeros(nfeatures, dtype=torch.double)
    Sigma0_pt = torch.eye(nfeatures, dtype=torch.double) * 1
    F_pt = torch.eye(nfeatures, dtype=torch.double) # dynamics = I
    Q_pt = torch.zeros((nfeatures, nfeatures), dtype=torch.double)  # No parameter drift.
    R_pt = torch.ones((1, 1), dtype=torch.double) * 0.1
    Y_pt = torch.tensor(Y_np)
    param_dict_pt = {'mu0': mu0_pt, 'Sigma0': Sigma0_pt, 'F': F_pt, 'Q': Q_pt, 'R': R_pt, 'Ht': Ht_pt}
    return param_dict_pt, X_np, Y_pt



def time_torch(N, D, compile=False):
    param_dict_pt, X, Y_pt = make_params_and_data_pt(N, D)
    return_covs = False
    t0 = time.time()
    _ = kf_pt(param_dict_pt, Y_pt, return_covs, compile=compile) 
    return time.time() - t0

def main():
    N = 100
    D = 500


    compile = False
    runtime_torch = time_torch(N, D, compile=compile)
    print('torch, time={:.3f} compile {} N {} D {}'.format(runtime_torch, compile, N, D))

    # Warmup
    compile = True
    runtime_torch = time_torch(N, D, compile=compile)
    print('torch, time={:.3f} compile {} N {} D {}'.format(runtime_torch, compile, N, D))

    # Actual compilation time
    runtime_torch = time_torch(N, D, compile=compile)
    print('torch, time={:.3f} compile {} N {} D {}'.format(runtime_torch, compile, N, D))

if __name__ == '__main__':
    main()
```

### Error logs

```
(nightly) ubuntu@ip-172-31-38-220:~/dynamax/dynamax/linear_gaussian_ssm/demos$ CUDA_LAUNCH_BLOCKING=1 python kf_linreg_jax_vs_pt.py 
torch, time=0.485 compile False N 100 D 500
[2023-04-13 21:20:20,927] torch._inductor.utils: [WARNING] make_fallback(aten.cumprod): a decomposition exists, we should switch to it
Traceback (most recent call last):
  File "/home/ubuntu/dynamax/dynamax/linear_gaussian_ssm/demos/kf_linreg_jax_vs_pt.py", line 151, in <module>
    main()
  File "/home/ubuntu/dynamax/dynamax/linear_gaussian_ssm/demos/kf_linreg_jax_vs_pt.py", line 143, in main
    runtime_torch = time_torch(N, D, compile=compile)
  File "/home/ubuntu/dynamax/dynamax/linear_gaussian_ssm/demos/kf_linreg_jax_vs_pt.py", line 129, in time_torch
    _ = kf_pt(param_dict_pt, Y_pt, return_covs, compile=compile) 
  File "/home/ubuntu/dynamax/dynamax/linear_gaussian_ssm/demos/kf_linreg_jax_vs_pt.py", line 76, in kf_pt
    carry, filtered_means[t] = step(carry, 1)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 253, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 402, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 117, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 318, in _convert_frame_assert
    return _compile(
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 386, in _compile
    out_code = transform_code_object(code, transform)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 683, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 373, in transform
    tracer.run()
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1899, in run
    super().run()
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 611, in run
    and self.step()
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 571, in step
    getattr(self, inst.opname)(inst)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1986, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 647, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/envs/nightly/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 694, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 776, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 772, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 1098, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/__init__.py", line 1531, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 617, in compile_fx
    return compile_fx(
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 730, in compile_fx
    return aot_autograd(
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 62, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3095, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2730, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1827, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1995, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1292, in aot_dispatch_base
    compiled_fw = compiler(fw_module, flat_args)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 683, in fw_compiler_base
    joint_graph_passes(model)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_inductor/fx_passes/joint_graph.py", line 30, in joint_graph_passes
    lazy_init()
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_inductor/fx_passes/joint_graph.py", line 16, in lazy_init
    _sfdp_init()
  File "/opt/conda/envs/nightly/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_inductor/fx_passes/fuse_attention.py", line 165, in _sfdp_init
    (_sfdp_pattern_1, _sfdp_replacement_1, [g(), g(), g(), c()], {}),
  File "/opt/conda/envs/nightly/lib/python3.10/site-packages/torch/_inductor/overrides.py", line 33, in __torch_function__
    return replace_fn(func)(*args, **kwargs)
torch._dynamo.exc.BackendCompilerFailed: backend='debug_wrapper' raised:
RuntimeError: CUDA error: out of memory
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.



You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```

### Minified repro

Minifier is segfaulting

### Versions

(nightly) ubuntu@ip-172-31-38-220:~/dynamax/dynamax/linear_gaussian_ssm/demos$ python collect_env.py
Collecting environment information...
PyTorch version: 2.1.0.dev20230413+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1026-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7R32
Stepping:                        0
CPU MHz:                         2799.818
BogoMIPS:                        5599.63
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        2 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save rdpid

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] pytorch-triton==2.1.0+46672772b4
[pip3] torch==2.1.0.dev20230413+cu117
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+46672772b4          pypi_0    pypi
[conda] torch                     2.1.0.dev20230413+cu117          pypi_0    pypi

**Comment by ezyang** [comment]
Cc @jansel

**Comment by ngimel** [comment]
I'll take a look

**Comment by ngimel** [comment]
This doesn't oom on A100, I'll try limiting memory
```
torch, time=0.265 compile False N 100 D 500
torch, time=12.741 compile True N 100 D 500
torch, time=0.175 compile True N 100 D 500
```

**Comment by ngimel** [comment]
@msaroufim the script as written doesn't put anything on the GPU

**Comment by msaroufim** [comment]
That's right yes, I tried to make the default device cuda but it broke the script in other ways. But I still see the OOM thrown in the stack trace

**Comment by ngimel** [comment]
I'm running this code and it only allocate 418 MB on the GPU, no OOM.

**Comment by msaroufim** [comment]
This is really strange, I just restarted my machine and I can't repro the error I printed. apologies, closing

**Comment by ngimel** [comment]
I can believe there's an oom there, but some changes are needed to the script to put things on cuda.

**Comment by jansel** [comment]
fuse_attention does allocate some (tiny) tensors, we should switch those to FakeTensors.

**Comment by jansel** [comment]
https://github.com/pytorch/pytorch/pull/99128
