### ISSUE TITLE
PT2 dynamo exception Using Guided Diffusion's 256x256_diffusion_uncond compiled model

### ISSUE THREAD

**Issue by amitir22** [pytorch/pytorch#99145]
### 🐛 Describe the bug

_NOTE: Might be related to: https://github.com/pytorch/pytorch/issues/93042 (after independent debugging)._

In short: we are using the [guided_diffusion/gaussian_diffusion.py](https://github.com/talafek96/Diffusion-AD-Project/blob/main/extern/guided_diffusion/guided_diffusion/gaussian_diffusion.py) module which uses the model created in [guided_diffusion/script_util.py:130](https://github.com/talafek96/Diffusion-AD-Project/blob/d43b74654b51ef76efe24ab203c12e67471ba72a/extern/guided_diffusion/guided_diffusion/script_util.py#L130) to denoise a given image using a model defined in  [guided_diffusion/unet.py:396](https://github.com/talafek96/Diffusion-AD-Project/blob/d43b74654b51ef76efe24ab203c12e67471ba72a/extern/guided_diffusion/guided_diffusion/unet.py#L396) using the parameters given by the authors of guided-diffusion [here](https://github.com/talafek96/Diffusion-AD-Project/tree/main/extern/guided_diffusion#classifier-guidance) (in the '256x256 model (unconditional)' box).

- Our repo: https://github.com/talafek96/Diffusion-AD-Project
- Our code control flow that causes the problem:

1. in [initial_experiment.ipynb](https://github.com/talafek96/Diffusion-AD-Project/blob/main/initial_experiment.ipynb) in Part 3 where the line: 
`reconstructed_image = denoiser.denoise(noised_image.unsqueeze(0), NUM_TIMESTEPS, show_progress=True)` 
is executed in that 2nd code block, the notebook crashes with the Error logs attached.

2. `denoiser.denoise` is defined here: [denoiser.py:48](https://github.com/talafek96/Diffusion-AD-Project/blob/main/utils/denoiser.py#L48)
and the problematic line is: [denoiser.py:54](https://github.com/talafek96/Diffusion-AD-Project/blob/main/utils/denoiser.py#L54).

3. The method `.p_sample_loop()` is called and is defined here: [guided_diffusion/gaussian_diffusion.py:395](https://github.com/talafek96/Diffusion-AD-Project/blob/main/extern/guided_diffusion/guided_diffusion/gaussian_diffusion.py#L232).

4. `.p_sample_loop()` invokes the `.forward()` method on the model, which is implemented here: [guided_diffusion/unet.py:396](https://github.com/talafek96/Diffusion-AD-Project/blob/d43b74654b51ef76efe24ab203c12e67471ba72a/extern/guided_diffusion/guided_diffusion/unet.py#L396)

5. The error below occures.

### Error logs

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py:364, in _compile(code, globals, locals, builtins, compiler_fn, one_graph, export, hooks, frame)
    363 CleanupManager.instance[out_code] = output.cleanups
--> 364 check_fn = CheckFunctionManager(
    365     output,
    366     locals,
    367     globals,
    368     hooks.guard_fail_fn if hooks else None,
    369 )
    371 guarded_code = GuardedCode(out_code, check_fn.check_fn)

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/guards.py:547, in CheckFunctionManager.__init__(self, output_graph, f_locals, f_globals, guard_fail_fn)
    546         continue
--> 547     guard.create(local_builder, global_builder)
    548 self.check_fn = self.compile_check_fn(
    549     local_builder, global_builder, guards, guard_fail_fn
    550 )

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_guards.py:163, in Guard.create(self, local_builder, global_builder)
    162 def create(self, local_builder: GuardBuilderBase, global_builder: GuardBuilderBase):
--> 163     return self.create_fn(self.source.select(local_builder, global_builder), self)

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/guards.py:319, in GuardBuilder.LIST_LENGTH(self, guard)
    318 code.append(f"___check_type_id({ref}, {self.id_ref(t)})")
--> 319 code.append(f"len({ref}) == {len(value)}")
    321 self._produce_guard_code(guard, code)

TypeError: object of type 'tuple_iterator' has no len()

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True


The above exception was the direct cause of the following exception:

InternalTorchDynamoError                  Traceback (most recent call last)
Cell In[13], line 1
----> 1 reconstructed_image = denoiser.denoise(noised_image.unsqueeze(0), NUM_TIMESTEPS, show_progress=True)

File ~/repos/Diffusion-AD-Project/utils/denoiser.py:54, in ModelTimestepUniformDenoiser.denoise(self, noisy_images, num_timesteps, clip_denoised, show_progress)
     48 def denoise(self, 
     49             noisy_images: torch.TensorType, 
     50             num_timesteps: int, 
     51             clip_denoised: bool=True, 
     52             show_progress: bool=False) -> torch.TensorType:
     53     self.diffusion.num_timesteps = num_timesteps  # Set the number of time-steps.
---> 54     denoised_images = self.diffusion.p_sample_loop(
     55         model=self.model,
     56         shape=noisy_images.shape,
     57         noise=noisy_images,
     58         clip_denoised=clip_denoised,
     59         progress=show_progress
     60     )
     62     return denoised_images

File ~/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/gaussian_diffusion.py:473, in GaussianDiffusion.p_sample_loop(self, model, shape, noise, clip_denoised, denoised_fn, cond_fn, model_kwargs, device, progress)
    453 """
    454 Generate samples from the model.
    455 
   (...)
    470 :return: a non-differentiable batch of samples.
    471 """
    472 final = None
--> 473 for sample in self.p_sample_loop_progressive(
    474     model,
    475     shape,
    476     noise=noise,
    477     clip_denoised=clip_denoised,
    478     denoised_fn=denoised_fn,
    479     cond_fn=cond_fn,
    480     model_kwargs=model_kwargs,
    481     device=device,
    482     progress=progress,
    483 ):
    484     final = sample
    485 return final["sample"]

File ~/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/gaussian_diffusion.py:525, in GaussianDiffusion.p_sample_loop_progressive(self, model, shape, noise, clip_denoised, denoised_fn, cond_fn, model_kwargs, device, progress)
    523 t = th.tensor([i] * shape[0], device=device)
    524 with th.no_grad():
--> 525     out = self.p_sample(
    526         model,
    527         img,
    528         t,
    529         clip_denoised=clip_denoised,
    530         denoised_fn=denoised_fn,
    531         cond_fn=cond_fn,
    532         model_kwargs=model_kwargs,
    533     )
    534     yield out
    535     img = out["sample"]

File ~/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/gaussian_diffusion.py:422, in GaussianDiffusion.p_sample(self, model, x, t, clip_denoised, denoised_fn, cond_fn, model_kwargs)
    395 def p_sample(
    396     self,
    397     model,
   (...)
    403     model_kwargs=None,
    404 ):
    405     """
    406     Sample x_{t-1} from the model at the given timestep.
    407 
   (...)
    420              - 'pred_xstart': a prediction of x_0.
    421     """
--> 422     out = self.p_mean_variance(
    423         model,
    424         x,
    425         t,
    426         clip_denoised=clip_denoised,
    427         denoised_fn=denoised_fn,
    428         model_kwargs=model_kwargs,
    429     )
    430     noise = th.randn_like(x)
    431     nonzero_mask = (
    432         (t != 0).float().view(-1, *([1] * (len(x.shape) - 1)))
    433     )  # no noise when t == 0

File ~/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/respace.py:91, in SpacedDiffusion.p_mean_variance(self, model, *args, **kwargs)
     88 def p_mean_variance(
     89     self, model, *args, **kwargs
     90 ):  # pylint: disable=signature-differs
---> 91     return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)

File ~/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/gaussian_diffusion.py:260, in GaussianDiffusion.p_mean_variance(self, model, x, t, clip_denoised, denoised_fn, model_kwargs)
    258 B, C = x.shape[:2]
    259 assert t.shape == (B,)
--> 260 model_output = model(x, self._scale_timesteps(t), **model_kwargs)
    262 if self.model_var_type in [ModelVarType.LEARNED, ModelVarType.LEARNED_RANGE]:
    263     assert model_output.shape == (B, C * 2, *x.shape[2:])

File ~/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/respace.py:128, in _WrappedModel.__call__(self, x, ts, **kwargs)
    126 if self.rescale_timesteps:
    127     new_ts = new_ts.float() * (1000.0 / self.original_num_steps)
--> 128 return self.model(x, new_ts, **kwargs)

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:82, in OptimizedModule.forward(self, *args, **kwargs)
     81 def forward(self, *args, **kwargs):
---> 82     return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:209, in _TorchDynamoContext.__call__.<locals>._fn(*args, **kwargs)
    207 dynamic_ctx.__enter__()
    208 try:
--> 209     return fn(*args, **kwargs)
    210 finally:
    211     set_eval_frame(prior)

File ~/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/unet.py:656, in UNetModel.forward(self, x, timesteps, y)
    654 h = x.type(self.dtype)
    655 for module in self.input_blocks:
--> 656     h = module(h, emb)
    657     hs.append(h)
    658 h = self.middle_block(h, emb)

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/unet.py:77, in TimestepEmbedSequential.forward(self, x, emb)
     75         x = layer(x, emb)
     76     else:
---> 77         x = layer(x)
     78 return x

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/unet.py:297, in AttentionBlock.forward(self, x)
    296 def forward(self, x):
--> 297     return checkpoint(self._forward, (x,), self.parameters(), True)

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:337, in catch_errors_wrapper.<locals>.catch_errors(frame, cache_size)
    334             return hijacked_callback(frame, cache_size, hooks)
    336 with compile_lock:
--> 337     return callback(frame, cache_size, hooks)

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py:404, in convert_frame.<locals>._convert_frame(frame, cache_size, hooks)
    402 counters["frames"]["total"] += 1
    403 try:
--> 404     result = inner_convert(frame, cache_size, hooks)
    405     counters["frames"]["ok"] += 1
    406     return result

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py:104, in wrap_convert_context.<locals>._fn(*args, **kwargs)
    102 torch.fx.graph_module._forward_from_src = fx_forward_from_src_skip_result
    103 try:
--> 104     return fn(*args, **kwargs)
    105 finally:
    106     torch._C._set_grad_enabled(prior_grad_mode)

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py:262, in convert_frame_assert.<locals>._convert_frame_assert(frame, cache_size, hooks)
    259 global initial_grad_state
    260 initial_grad_state = torch.is_grad_enabled()
--> 262 return _compile(
    263     frame.f_code,
    264     frame.f_globals,
    265     frame.f_locals,
    266     frame.f_builtins,
    267     compiler_fn,
    268     one_graph,
    269     export,
    270     hooks,
    271     frame,
    272 )

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/utils.py:163, in dynamo_timed.<locals>.dynamo_timed_inner.<locals>.time_wrapper(*args, **kwargs)
    161     compilation_metrics[key] = []
    162 t0 = time.time()
--> 163 r = func(*args, **kwargs)
    164 time_spent = time.time() - t0
    165 # print(f"Dynamo timer: key={key}, latency={latency:.2f} sec")

File ~/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py:394, in _compile(code, globals, locals, builtins, compiler_fn, one_graph, export, hooks, frame)
    392 except Exception as e:
    393     exception_handler(e, code, frame)
--> 394     raise InternalTorchDynamoError() from e

InternalTorchDynamoError: 
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect (Manual edit: 11.7.64 obtained the same way but since we use wsl2, we had to run `nvcc --version` on cmd instead of bash)
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 531.61
cuDNN version: Could not collect (Manual edit: 8.4.1.50 after running `conda list cudnn`)
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 5800X 8-Core Processor
CPU family:                      25
Model:                           33
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        2
BogoMIPS:                        7585.83
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload umip vaes vpclmulqdq rdpid fsrm
Virtualization:                  AMD-V
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        32 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] pytorch-lightning==1.9.4
[pip3] torch==2.0.0
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.0
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               11.8.0              h37601d7_11    conda-forge
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.2.1            intel_16993    intel
[conda] numpy                     1.24.2          py310h8deb116_0    conda-forge
[conda] pytorch                   2.0.0           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_3    pytorch
[conda] pytorch-lightning         1.9.4                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.0              py310_cu118    pytorch
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by wconstab** [comment]
Haven't tried to repro yet, but a couple observations from the stacktrace:

guided_diffusion/unet.py:297 
`return checkpoint(self._forward, (x,), self.parameters(), True)`

1) you appear to be using checkpointing, which i'm not sure is going to work yet.  @anijain2305 is working on supporting activation checkpointing with dynamo.  Is there a way to allow-in-graph and work around for now or should @amitir22 just wait?

2) Assuming you can disable checkpointing or work around it, (maybe you can't if the model is large), then the actual error in the stacktrace looks like something more basic that isn't related to checkpointing.  To be clear, I am saying if we fix the 'tuple len' error, I expect new problems to pop up from checkpointing.

   Idea: can you replace `(x,)` with `[x,]` in the model and see if that works?  Just a long shot, i'll have to debug to confirm.

Before I repro, can you confirm the exact repro steps?  Should I take your .ipynb as-is, or need to modify to call .compile() somewhere?  Or is there an e2e script I can run (might be easier to debug that way) - if so please provide the script and the command and any setup steps.

**Comment by amitir22** [comment]
> Haven't tried to repro yet, but a couple observations from the stacktrace:
> 
> guided_diffusion/unet.py:297 `return checkpoint(self._forward, (x,), self.parameters(), True)`
> 
> 1. you appear to be using checkpointing, which i'm not sure is going to work yet.  @anijain2305 is working on supporting activation checkpointing with dynamo.  Is there a way to allow-in-graph and work around for now or should @amitir22 just wait?
> 2. Assuming you can disable checkpointing or work around it, (maybe you can't if the model is large), then the actual error in the stacktrace looks like something more basic that isn't related to checkpointing.  To be clear, I am saying if we fix the 'tuple len' error, I expect new problems to pop up from checkpointing.
>    Idea: can you replace `(x,)` with `[x,]` in the model and see if that works?  Just a long shot, i'll have to debug to confirm.
> 
> Before I repro, can you confirm the exact repro steps? Should I take your .ipynb as-is, or need to modify to call .compile() somewhere? Or is there an e2e script I can run (might be easier to debug that way) - if so please provide the script and the command and any setup steps.

here:
![image](https://user-images.githubusercontent.com/26043145/232120705-a8ff9056-93f0-42c3-b821-bee685482b64.png)

**Comment by amitir22** [comment]
Update: We created a branch with a bug reproduction script called `__to_be_filled__.py` in the branch `pvt/dev-2.0-dynamo-bug-repro`.

The output is shorter as the former bug was produced in a Jupyter environment that outputs also the region of the code that was involved in each method in the backstack of the crash, and looks like this:

```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 364, in _compile
    check_fn = CheckFunctionManager(
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 547, in __init__
    guard.create(local_builder, global_builder)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_guards.py", line 163, in create
    return self.create_fn(self.source.select(local_builder, global_builder), self)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 319, in LIST_LENGTH
    code.append(f"len({ref}) == {len(value)}")
TypeError: object of type 'tuple_iterator' has no len()

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/repos/Diffusion-AD-Project/bug_reproduce.py", line 36, in <module>
    reconstructed_image = denoiser.denoise(noised_image.unsqueeze(0), NUM_TIMESTEPS, show_progress=True)
  File "/home/user/repos/Diffusion-AD-Project/utils/denoiser.py", line 54, in denoise
    denoised_images = self.diffusion.p_sample_loop(
  File "/home/user/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/gaussian_diffusion.py", line 473, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/home/user/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/gaussian_diffusion.py", line 525, in p_sample_loop_progressive
    out = self.p_sample(
  File "/home/user/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/gaussian_diffusion.py", line 422, in p_sample
    out = self.p_mean_variance(
  File "/home/user/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/respace.py", line 91, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/home/user/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/gaussian_diffusion.py", line 260, in p_mean_variance
    model_output = model(x, self._scale_timesteps(t), **model_kwargs)
  File "/home/user/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/respace.py", line 128, in __call__
    return self.model(x, new_ts, **kwargs)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/user/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/unet.py", line 656, in forward
    h = module(h, emb)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/unet.py", line 77, in forward
    x = layer(x)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/repos/Diffusion-AD-Project/extern/guided_diffusion/guided_diffusion/unet.py", line 297, in forward
    return checkpoint(self._forward, (x,), self.parameters(), True)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/user/miniconda3/envs/diffusion-ad/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 394, in _compile
    raise InternalTorchDynamoError() from e
torch._dynamo.exc.InternalTorchDynamoError
```

**Comment by wconstab** [comment]
running this on a more recent pytorch build from 4/14, I get a different error.  This suggests the dynamo support error has already been fixed, but there is still a problem

```
    return callback(frame, cache_size, hooks, frame_state)
  File "/scratch/whc/work/pytorch/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/scratch/whc/work/pytorch/torch/_dynamo/convert_frame.py", line 117, in _fn
    return fn(*args, **kwargs)
  File "/scratch/whc/work/pytorch/torch/_dynamo/convert_frame.py", line 318, in _convert_frame_assert
    return _compile(
  File "/scratch/whc/work/pytorch/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/whc/work/pytorch/torch/_dynamo/convert_frame.py", line 386, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/whc/work/pytorch/torch/_dynamo/bytecode_transformation.py", line 683, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/whc/work/pytorch/torch/_dynamo/convert_frame.py", line 373, in transform
    tracer.run()
  File "/scratch/whc/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1899, in run
    super().run()
  File "/scratch/whc/work/pytorch/torch/_dynamo/symbolic_convert.py", line 611, in run
    and self.step()
  File "/scratch/whc/work/pytorch/torch/_dynamo/symbolic_convert.py", line 571, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/whc/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1986, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/scratch/whc/work/pytorch/torch/_dynamo/output_graph.py", line 609, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/scratch/whc/work/py38/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/scratch/whc/work/pytorch/torch/_dynamo/output_graph.py", line 704, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/scratch/whc/work/pytorch/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/whc/work/pytorch/torch/_dynamo/output_graph.py", line 801, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/scratch/whc/work/pytorch/torch/_dynamo/output_graph.py", line 797, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/scratch/whc/work/pytorch/torch/_dynamo/debug_utils.py", line 1098, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/scratch/whc/work/pytorch/torch/__init__.py", line 1530, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/scratch/whc/work/pytorch/torch/_inductor/compile_fx.py", line 730, in compile_fx
    return aot_autograd(
  File "/scratch/whc/work/pytorch/torch/_dynamo/backends/common.py", line 62, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/scratch/whc/work/pytorch/torch/_functorch/aot_autograd.py", line 3127, in aot_module_simplified
    assert source not in seen_sources, source
  File "<string>", line 3, in __hash__
  File "<string>", line 3, in __hash__
  File "<string>", line 3, in __hash__
  [Previous line repeated 3 more times]
torch._dynamo.exc.BackendCompilerFailed: backend='debug_wrapper' raised:
TypeError: unhashable type: 'slice'
```

Summarizing repro steps:
```
git clone git@github.com:talafek96/Diffusion-AD-Project.git
git checkout pvt/dev-2.0-dynamo-bug-repro
mkdir models && cd models && wget https://openaipublic.blob.core.windows.net/diffusion/jul-2021/256x256_diffusion_uncond.pt
pip install blobfile
pip install mpi4py
python bug_repro.py
```

**Comment by wconstab** [comment]
ok i have a fix ready for the unhashable slice issue.  (But the fix is on the main branch not the 2.0 baseline).  You can locally patch it or pull from our nightlies to get it.  Pushing soon, you'll see the PR automatically referenced in this issue when it's up.

**Comment by talafek96** [comment]
Hey, how can I know if and when this fix reaches the stable release?

**Comment by wconstab** [comment]
Well, it's not included in v2.0.1 (iiuc - just scanned the commits here: https://github.com/pytorch/pytorch/commits/v2.0.1)

So I would expect it would be in v2.1 but not sure how many months out that is (sometime this summer I would think) - cc @malfet for more accurate information.  Not sure if we plan any more point releases before then and could include this.

**Comment by malfet** [comment]
No plans for 2.0.2, and this issue for some reason was not nominated for 2.0.1 inclusion by compiler team.(cc: @ezyang who nominated a bunch of them)

**Comment by ziyaxuanyi** [comment]
Have you solved this problem? I have encountered the same problem.
Does the latest version of torch solve this problem？
My version of torch is 2.0.0

**Comment by ezyang** [comment]
Probably, try a nightly
