### ISSUE TITLE
loading GPU 

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#992]
As @jzbontar reports:
serialization storage remapping is trying to load somewhere in the codepath.

> I get an error when loading a cuda tensor on a CPU only machine.  Here is the code I use: https://gist.github.com/jzbontar/b50f8c9dd22e49ff68c7c91dad63166a. The error is: AssertionError('\nFound no NVIDIA driver on your system... Both machines use pytorch version 0.1.10.

**Comment by ylhsieh** [comment]
Sorry, but I am still getting this error on 0.1.12_2 (installed from binary) on a CPU-only machine. Specifically, the error msg
```
Loading model file... Traceback (most recent call last):
  File "./translate.py", line 193, in <module>
    translator = onmt.Translator(opt)
  File "/home/user/chunk/onmt/Translator.py", line 12, in __init__
    checkpoint = torch.load(opt.model, map_location=lambda storage, loc: storage)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 229, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 377, in _load
    result = unpickler.load()
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 272, in __new__
    _lazy_init()
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 58, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: (AssertionError('\nFound no NVIDIA driver on your system. Please check that you\nhave an NVIDIA GPU and installed a driver from\nhttp://www.nvidia.com/Download/index.aspx',), <class 'torch.cuda.FloatTensor'>, ())
```

seemed like `unpickler.load()` somehow triggered cuda init?

**Comment by ylhsieh** [comment]
Oops I found out that the model was trained using an older version of pytorch. Retrained it and all is fine. Thanks for all your hard work!

**Comment by suke27** [comment]
i also face this error, as I check version, it is code after "Fix map_location in torch.load #1006 "
could you plz help to check
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    model = torch.load("model_epoch_x3_L1_500.pth")
  File "/home/nianrui/.local/lib/python2.7/site-packages/torch/serialization.py", line 231, in load
    return _load(f, map_location, pickle_module)
  File "/home/nianrui/.local/lib/python2.7/site-packages/torch/serialization.py", line 379, in _load
    result = unpickler.load()
  File "/home/nianrui/.local/lib/python2.7/site-packages/torch/serialization.py", line 350, in persistent_load
    data_type(size), location)
  File "/home/nianrui/.local/lib/python2.7/site-packages/torch/serialization.py", line 85, in default_restore_location
    result = fn(storage, location)
  File "/home/nianrui/.local/lib/python2.7/site-packages/torch/serialization.py", line 67, in _cuda_deserialize
    return obj.cuda(device_id)
  File "/home/nianrui/.local/lib/python2.7/site-packages/torch/_utils.py", line 58, in _cuda
    with torch.cuda.device(device):
  File "/home/nianrui/.local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 125, in __enter__
    _lazy_init()
  File "/home/nianrui/.local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/home/nianrui/.local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 58, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
