### ISSUE TITLE
opacus_cifar10 fails in dynamo due to hooks 

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#99201]
After adding support for hooks on allowed modules via graph-breaks, opacus_cifar10 crashes during dynamo tracing with

`python benchmarks/dynamo/torchbench.py --only opacus_cifar10 --backend aot_eager --accuracy --inference`

```
 /scratch/whc/work/pytorch/torch/_dynamo/bytecode_analysis.py(190)stacksize_analysis()
-> assert low >= 0
```

It looks like the crash is happening while tracing some exception handling code, relating to hooks on GradSampleModule in opacus.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel @Xia-Weiwen @desertfire

**Comment by anijain2305** [comment]
This came up in Dynamo triage. @wconstab Will you be able to provide the new repro command? Current one fails with the following message
~~~
Traceback (most recent call last):
  File "/data/users/anijain/pytorch/benchmarks/dynamo/torchbench.py", line 510, in <module>
    torchbench_main()
  File "/data/users/anijain/pytorch/benchmarks/dynamo/torchbench.py", line 506, in torchbench_main
    main(TorchBenchmarkRunner(), original_dir)
  File "/data/users/anijain/pytorch/benchmarks/dynamo/common.py", line 3022, in main
    process_entry(0, runner, original_dir, args)
  File "/data/users/anijain/pytorch/benchmarks/dynamo/common.py", line 2980, in process_entry
    return maybe_fresh_cache(
  File "/data/users/anijain/pytorch/benchmarks/dynamo/common.py", line 1647, in inner
    return fn(*args, **kwargs)
  File "/data/users/anijain/pytorch/benchmarks/dynamo/common.py", line 3439, in run
    ) = runner.load_model(
  File "/data/users/anijain/pytorch/benchmarks/dynamo/torchbench.py", line 390, in load_model
    benchmark = benchmark_cls(
  File "/data/users/anijain/torchbenchmark/torchbenchmark/util/model.py", line 26, in __call__
    obj.__post__init__()
  File "/data/users/anijain/torchbenchmark/torchbenchmark/util/model.py", line 124, in __post__init__
    assert not self.extra_args, f"Expected no unknown args at this point, found {self.extra_args}"
AssertionError: Expected no unknown args at this point, found ['--rank', '0', '--world_size', '1']
~~~

**Comment by jon-chuang** [comment]
Possibly related: https://github.com/pytorch/opacus/issues/607

**Comment by anijain2305** [comment]
This does not repro on main. Closing.
