### ISSUE TITLE
Unable to run ml task on rocm / mi 100

### ISSUE THREAD

**Issue by ggghamd** [pytorch/pytorch#99234]
```
### 🐛 Describe the bug

Typical run of ML task fails with rocm based torch installed but failing:

nonroot@mi100:~/git/code/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn$ python3 p474-cnn-pyt.py 
15/04/2023 15:21:03: train entered...
Epoch: 0:
training 0th batch...
Traceback (most recent call last):
  File "/home/nonroot/gg/git/codelab/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn/p474-cnn-pyt.py", line 140, in <module>
    hist=train(model, num_epochs, train_dl, valid_dl)
  File "/home/nonroot/gg/git/codelab/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn/p474-cnn-pyt.py", line 31, in wrapper
    result = func(*args, **kwargs)
  File "/home/nonroot/gg/git/codelab/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn/p474-cnn-pyt.py", line 94, in train
    x_batch.cuda()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available
nonroot@mi100:~/git/code/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn$ pip3 list | grep torch
pytorch-triton-rocm    2.0.1
torch                  2.0.0+rocm5.4.2
torchaudio             2.0.1+rocm5.4.2
torchvision            0.15.1+rocm5.4.2
nonroot@mi100:~/git/code/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn$ python3 p474-cnn-pyt.py ^C
nonroot@mi100:~/git/code/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn$ ls -l
total 24
drwxr-xr-x 3 root root 4096 Apr 15 15:20 MNIST
-rw-r--r-- 1 root root 1092 Apr 15 15:20 p459-conv1d.py
-rw-r--r-- 1 root root 1746 Apr 15 15:20 p461-conv2d.py
-rw-r--r-- 1 root root  234 Apr 15 15:20 p465-read-image.py
-rw-r--r-- 1 root root 6279 Apr 15 15:20 p474-cnn-pyt.py
nonroot@mi100:~/git/code/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn$ rocm-smi --showtopo


======================= ROCm System Management Interface =======================
=========================== Weight between two GPUs ============================
       GPU0         GPU1         
GPU0   0            61           
GPU1   61           0            

============================ Hops between two GPUs =============================
       GPU0         GPU1         
GPU0   0            3            
GPU1   3            0            

========================== Link Type between two GPUs ==========================
       GPU0         GPU1         
GPU0   0            PCIE         
GPU1   PCIE         0            

================================== Numa Nodes ==================================
GPU[0]		: (Topology) Numa Node: 0
GPU[0]		: (Topology) Numa Affinity: 0
GPU[1]		: (Topology) Numa Node: 1
GPU[1]		: (Topology) Numa Affinity: 1
============================= End of ROCm SMI Log ==============================
nonroot@mi100:~/git/code/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn$ lspci | grep Disp
1a:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Arcturus GL-XL [Instinct MI100] (rev 01)
88:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Arcturus GL-XL [Instinct MI100] (rev 01)


nonroot@mi100:~/git/code/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
nonroot@mi100:~/git/code/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn$ uname -r
5.15.0-69-generic


nonroot@mi100:~/git/code/gpu/ml/pt/ml-with-pt-and-sk/ch14-cnn$ pip3 list | grep torch
pytorch-triton-rocm    2.0.1
torch                  2.0.0+rocm5.4.2
torchaudio             2.0.1+rocm5.4.2
torchvision            0.15.1+rocm5.4.2




### Versions

Collecting environment information...
PyTorch version: 2.0.0+rocm5.4.2
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.4.22803-474e8620

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI100
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.4.22803
MIOpen runtime version: 2.19.0
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          56
On-line CPU(s) list:             0-55
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              14
Socket(s):                       2
Stepping:                        4
CPU max MHz:                     3700.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        5200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       896 KiB (28 instances)
L1i cache:                       896 KiB (28 instances)
L2 cache:                        28 MiB (28 instances)
L3 cache:                        38.5 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-13,28-41
NUMA node1 CPU(s):               14-27,42-55
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] pytorch-triton-rocm==2.0.1
[pip3] torch==2.0.0+rocm5.4.2
[pip3] torchaudio==2.0.1+rocm5.4.2
[pip3] torchvision==0.15.1+rocm5.4.2
[conda] Could not collect


cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport
```

**Comment by jeffdaily** [comment]
Is your user part of the `render` and/or `video` groups?  Otherwise your user won't have permissions for the /dev/kfd and /dev/dri devices.

**Comment by ggghamd** [comment]
i downgraded to rocm 5.3.2 + pytorch 5.3.2 and it was working with everything else same. if i find the log, will post here.

**Comment by jeffdaily** [comment]
Was your environment running within a docker container or not?

**Comment by ggghamd** [comment]
it is running docker container but this ML tasks running on actual bare metal.

**Comment by jeffdaily** [comment]
Had offline conversation.  Closing issue with last status from @ggghamd:

> if i  install rocrm5.4.0 on freshly installed ubuntu 22.04, it happened, after downgrade 5.3 and upgrade back to 5.4, for some reason, no longer happens

This issue is not specific to pytorch, so closing.
