### ISSUE TITLE
vision_maskrcnn failing in periodic/trunk

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#99230]
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/4984825/232229096-cabf4a9d-23bc-4b3d-ab8e-ebc85e4b6171.png">
Failures appear to start with #98923.

Note: i also tried and failed to bisect an issue with vision_maskrcnn on inductor earlier this week, because looking at the pt2dash it looked like there was a drop between these revisions.  However when bisecting, I found all revs were failing, but the error message changed at some point.
Good: 670c5cf96249db28cde757da5a6aa97569760102 
Bad: c4f81cb6f49fe69f3a04867f9c445923af69113

**Comment by voznesenskym** [comment]
Sympy recursion fiasco :( 

```
2023-04-13T22:51:45.0317721Z Traceback (most recent call last):
2023-04-13T22:51:45.0318230Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1257, in run_node
2023-04-13T22:51:45.0320533Z     return getattr(args[0], node.target)(*args[1:], **kwargs)
2023-04-13T22:51:45.0321145Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
2023-04-13T22:51:45.0321546Z     return fn(*args, **kwargs)
2023-04-13T22:51:45.0321982Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1074, in __torch_dispatch__
2023-04-13T22:51:45.0322329Z     return self.dispatch(func, types, args, kwargs)
2023-04-13T22:51:45.0322752Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1234, in dispatch
2023-04-13T22:51:45.0323083Z     return decomposition_table[func](*args, **kwargs)
2023-04-13T22:51:45.0323528Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_refs/__init__.py", line 4047, in view
2023-04-13T22:51:45.0323947Z     return _reshape_view_helper(a, *shape, allow_copy=False)
2023-04-13T22:51:45.0324524Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_refs/__init__.py", line 3244, in _reshape_view_helper
2023-04-13T22:51:45.0324868Z     while accum % length != 0:
2023-04-13T22:51:45.0325357Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/__init__.py", line 346, in __bool__
2023-04-13T22:51:45.0325686Z     return self.node.bool_()
2023-04-13T22:51:45.0326140Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 738, in bool_
2023-04-13T22:51:45.0327043Z     return self.guard_bool("", 0)
2023-04-13T22:51:45.0327636Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 730, in guard_bool
2023-04-13T22:51:45.0328105Z     r = self.shape_env.evaluate_expr(self.expr, self.hint)
2023-04-13T22:51:45.0328729Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 2303, in evaluate_expr
2023-04-13T22:51:45.0329193Z     static_expr = self._maybe_evaluate_static(expr)
2023-04-13T22:51:45.0329766Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 1344, in wrapper
2023-04-13T22:51:45.0330198Z     return fn_cache(self, *args, **kwargs)
2023-04-13T22:51:45.0330814Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 2086, in _maybe_evaluate_static
2023-04-13T22:51:45.0331282Z     new_expr = expr.xreplace(new_shape_env)
2023-04-13T22:51:45.0331837Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/sympy/core/basic.py", line 1187, in xreplace
2023-04-13T22:51:45.0332232Z     value, _ = self._xreplace(rule)
2023-04-13T22:51:45.0332759Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/sympy/core/basic.py", line 1202, in _xreplace
2023-04-13T22:51:45.0333400Z     a_xr = _xreplace(rule)
2023-04-13T22:51:45.0333903Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/sympy/core/basic.py", line 1209, in _xreplace
2023-04-13T22:51:45.0334283Z     return self.func(*args), True
2023-04-13T22:51:45.0334776Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/sympy/core/cache.py", line 70, in wrapper
2023-04-13T22:51:45.0335149Z     retval = cfunc(*args, **kwargs)
2023-04-13T22:51:45.0335645Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/sympy/core/function.py", line 469, in __new__
2023-04-13T22:51:45.0336049Z     result = super().__new__(cls, *args, **options)
2023-04-13T22:51:45.0336659Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/sympy/core/cache.py", line 70, in wrapper
2023-04-13T22:51:45.0337035Z     retval = cfunc(*args, **kwargs)
2023-04-13T22:51:45.0337488Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/sympy/core/function.py", line 309, in __new__
```
...
```
2023-04-13T22:51:45.0729338Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/sympy/core/numbers.py", line 2241, in __eq__
2023-04-13T22:51:45.0729440Z     elif isinstance(other, Integer):
2023-04-13T22:51:45.0729593Z RecursionError: maximum recursion depth exceeded in __instancecheck__
```

Downstream of evaluate static. I can look into it. However, this is probably not introduced in this PR, so much as this PR changes regimes in a heavy handed enough way to excise this latent bug.

I'll prioritize a patch. Hopefully this is the only model failing.

**Comment by tugsbayasgalan** [comment]
@wconstab  is this still an issue?
