### ISSUE TITLE
cross_entropy with label_smoothing fails in FakeTensorMode

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#99250]
Repro
```py
import torch
from torch._subclasses import FakeTensorMode


with FakeTensorMode():
    input = torch.randn(3, 5)
    target = torch.empty(3, dtype=torch.long).random_(5)
    torch.nn.functional.cross_entropy(input, target, label_smoothing=0.5)
```

Output:
```
Traceback (most recent call last):
  File "/home/jansel/pytorch/repro.py", line 8, in <module>
    torch.nn.functional.cross_entropy(input, target, label_smoothing=0.5)
  File "/home/jansel/pytorch/torch/nn/functional.py", line 3049, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
  File "/home/jansel/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/jansel/pytorch/torch/_subclasses/fake_tensor.py", line 1072, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/jansel/pytorch/torch/_subclasses/fake_tensor.py", line 1164, in dispatch
    ) = self.validate_and_convert_non_fake_tensors(func, converter, args, kwargs)
  File "/home/jansel/pytorch/torch/_subclasses/fake_tensor.py", line 1323, in validate_and_convert_non_fake_tensors
    args, kwargs = tree_map_only(
  File "/home/jansel/pytorch/torch/utils/_pytree.py", line 266, in tree_map_only
    return tree_map(map_only(ty)(fn), pytree)
  File "/home/jansel/pytorch/torch/utils/_pytree.py", line 196, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/home/jansel/pytorch/torch/utils/_pytree.py", line 196, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/home/jansel/pytorch/torch/utils/_pytree.py", line 247, in inner
    return f(x)
  File "/home/jansel/pytorch/torch/_subclasses/fake_tensor.py", line 1311, in validate
    raise Exception(
Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.index_put_.default(*(FakeTensor(FakeTensor(..., device='meta', size=(3,)), cpu), [FakeTensor(FakeTensor(..., device='meta', size=(3,), dtype=torch.bool), cpu)], tensor(0.)), **{}) 
```

cc @eellison @ezyang

**Comment by jansel** [comment]
https://github.com/pytorch/pytorch/pull/99251 contains a partial and temporary workaround
