### ISSUE TITLE
Combining `functional_call` and `jacrev` from `torch.fun` systematically raises an error.

### ISSUE THREAD

**Issue by PierreQuinton** [pytorch/pytorch#99267]
### 🐛 Describe the bug

In the second example of [`functorch.make_functional` section of the tutorial describing of migrating from `functorch` to `torch.func`](https://pytorch.org/docs/master/func.migrating.html#functorch-make-functional), the following code is presented as an example : 
```python
import torch
from torch.func import jacrev, functional_call
inputs = torch.randn(64, 3)
model = torch.nn.Linear(3, 3)

params = dict(model.named_parameters())
jacobians = jacrev(functional_call, argnums=1)(model, params, (inputs,))
```

This raises the following error :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.pyenv/versions/multi_torch2.0/lib/python3.10/site-packages/torch/_functorch/eager_transforms.py", line 488, in wrapper_fn
    error_if_complex("jacrev", args, is_input=True)
  File "/home/me/.pyenv/versions/multi_torch2.0/lib/python3.10/site-packages/torch/_functorch/eager_transforms.py", line 347, in error_if_complex
    if arg.dtype.is_complex:
  File "/home/me/.pyenv/versions/multi_torch2.0/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Linear' object has no attribute 'dtype'. Did you mean: 'type'?
```

This is because the function returned by `jacrev` assumes that all inputs are `Tensor`s but here its first argument is a `Linear`.

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Fedora release 37 (Thirty Seven) (x86_64)
GCC version: (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
Clang version: 15.0.4 (Fedora 15.0.4-1.fc37)
CMake version: version 3.24.2
Libc version: glibc-2.36

Python version: 3.10.6 (main, Dec  3 2022, 11:56:58) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (64-bit runtime)
Python platform: Linux-6.0.10-300.fc37.x86_64-x86_64-with-glibc2.36
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
CPU family:                      6
Model:                           142
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        10
CPU(s) scaling MHz:              87%
CPU max MHz:                     4200.0000
CPU min MHz:                     400.0000
BogoMIPS:                        4199.88
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust sgx bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       128 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        1 MiB (4 instances)
L3 cache:                        8 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==2.0.0+cpu
[pip3] torchmetrics==0.11.1
[pip3] torchvision==0.15.1+cpu
[conda] Could not collect

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by PierreQuinton** [comment]
A (rather unsatisfying) fix to this could be to change the code of the tutorial to something like :

```python
import torch
from torch.func import jacrev, functional_call
inputs = torch.randn(64, 3)
model = torch.nn.Linear(3, 3)

params = dict(model.named_parameters())
def f(params, inputs):
  return functional_call(model, params, (inputs,))

jacobians = jacrev(f)(params, inputs)
```
