### ISSUE TITLE
torch.compile failed when the function to be compiled has argument named `self`

### ISSUE THREAD

**Issue by HansBug** [pytorch/pytorch#99262]
### 🐛 Describe the bug

Here is a simplest example, torch's version is `2.0.0`:

```python
import torch


@torch.compile
def f(x, self):
    return x + self


a = torch.randn(3, 4)
b = torch.randn(3, 4)

print(f(a, b))
```

This is the error log

```
Traceback (most recent call last):
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 517, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 581, in compile_and_call_fx_graph
    gm = fx.GraphModule(root, self.graph)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/fx/graph_module.py", line 370, in __init__
    self.graph = graph
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1674, in __setattr__
    super().__setattr__(name, value)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/fx/graph_module.py", line 411, in graph
    self.recompile()
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/fx/graph_module.py", line 648, in recompile
    cls.forward = _forward_from_src(self._code, python_code.globals)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 82, in fx_forward_from_src_skip_result
    result: types.FunctionType = original_forward_from_src(*args, **kwargs)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/fx/graph_module.py", line 81, in _forward_from_src
    _exec_with_source(src, globals_copy)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/fx/graph_module.py", line 75, in _exec_with_source
    exec(compile(src, key, 'exec'), globals)
  File "<eval_with_key>.0", line 4
SyntaxError: duplicate argument 'self' in function definition

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_bug.py", line 12, in <module>
    print(f(a, b))
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/hansbug/my-projects/treevalue/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 394, in _compile
    raise InternalTorchDynamoError() from e
torch._dynamo.exc.InternalTorchDynamoError
```

This is the source code executed in file "/home/hansbug/sensetime-projects/treevalue/venv/lib/python3.8/site-packages/torch/fx/graph_module.py", line 75, in _exec_with_source

```python
def forward(self, x : torch.Tensor, self : torch.Tensor):
    add = x + self;  x = self = None                                                                                                                                                                       
    return (add,)
```

Therefore, I believe that when compiling code, we should avoid using extremely common names like "self".

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.8.1 (default, Mar  3 2022, 10:18:42)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.2.5
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060
Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
架构：                           x86_64
CPU 运行模式：                   32-bit, 64-bit
字节序：                         Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU:                             12
在线 CPU 列表：                  0-11
每个核的线程数：                 2
每个座的核数：                   6
座：                             1
NUMA 节点：                      1
厂商 ID：                        AuthenticAMD
CPU 系列：                       25
型号：                           33
型号名称：                       AMD Ryzen 5 5600X 6-Core Processor
步进：                           0
Frequency boost:                 enabled
CPU MHz：                        2200.000
CPU 最大 MHz：                   3700.0000
CPU 最小 MHz：                   2200.0000
BogoMIPS：                       7399.98
虚拟化：                         AMD-V
L1d 缓存：                       192 KiB
L1i 缓存：                       192 KiB
L2 缓存：                        3 MiB
L3 缓存：                        32 MiB
NUMA 节点0 CPU：                 0-11
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
标记：                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] flake8==3.9.2
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] triton==2.0.0
[conda] Could not collect

```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by wconstab** [comment]
We could issue a warning or error when dynamo detects a function like this.  I'm not sure if it's worth trying to make it work though.  Any reason it is?

**Comment by ezyang** [comment]
This is a Dynamo bug, plain and simple. We should fix it.

**Comment by HansBug** [comment]
> Any reason it is?

In out project [opendilab/treevalue](https://github.com/opendilab/treevalue)(main branch, 131d60c1029b5142cef0f38fcc2163eb0e8d23aa), there is another similar case.

```python
import torch

from treevalue import FastTreeValue

print('torch version:', torch.__version__)


@torch.compile
def foo(x, y):
    z = x + y
    return z


x = FastTreeValue({'a': torch.randn(3, 4)})
y = FastTreeValue({'a': torch.rand(4)})

print('x:', x)
print('y:', y)

print(foo(x, y))  # this line!!!
```

This `FastTreeValue` is registered as a pytree node in torch. The function `foo` will throw an error completely identical to the one mentioned above. After our investigation, we found that the problem lies in the `__add__` method of the FastTreeValue class. Here is its source code ([link](https://github.com/opendilab/treevalue/blob/131d60c1029b5142cef0f38fcc2163eb0e8d23aa/treevalue/tree/general/general.py#L490)):

```python
        @_decorate_treelize
        def __add__(self, other):
            """
            Overview:
                Add tree values together.
            Example:
                >>> t1 = FastTreeValue({'a': 1, 'b': 2, 'x': {'c': 3, 'd': 4}})
                >>> t2 = FastTreeValue({'a': 11, 'b': 22, 'x': {'c': 30, 'd': 40}})
                >>> t1 + t2  # FastTreeValue({'a': 12, 'b': 24, 'x': {'c': 33, 'd': 44}})
            """
            return self + other
```

The original `__add__` function is wrapped by the decorator, which contains `functools.wrap` inside. But when we compile the `foo` function, this python code of `__add__` generated by torch is like `def forward(self, self, other)`.

I tried to reproduce this error, but `torch.compile` works fine on simple instance method (without decorator).

**Comment by ydwu4** [comment]
Closed as error is gone on main.
