### ISSUE TITLE
FakeTensor lacks support for sparse compressed tensors

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#99404]
## Issue description

As in the title.

This lack of support prevents using `OpInfo.error_input_func` for sparse compressed tensors. For instance, `test_python_ref_errors` would fail with `UnsupportedFakeTensorException` on an `ErrorInput` instance that contains a sparse compressed tensor as a sample input (ref: https://github.com/pytorch/pytorch/actions/runs/4723316774/jobs/8379634648).

## Code example

```python
>>> import torch
>>> from torch._subclasses.fake_tensor import FakeTensorMode, FakeTensor
>>> mode = FakeTensorMode()
>>> FakeTensor.from_tensor(torch.tensor([[1, 2], [3, 4]]).to_sparse_csr(), mode)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_subclasses/fake_tensor.py", line 922, in from_tensor
    return fake_mode.from_tensor(t)
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_subclasses/fake_tensor.py", line 1437, in from_tensor
    return self.fake_tensor_converter(
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_subclasses/fake_tensor.py", line 328, in __call__
    return self.from_real_tensor(
  File "/home/pearu/git/pytorch/pytorch-sparse-compressed/torch/_subclasses/fake_tensor.py", line 292, in from_real_tensor
    raise UnsupportedFakeTensorException("meta converter nyi")
torch._subclasses.fake_tensor.UnsupportedFakeTensorException: meta converter nyi
```

## System Info

- PyTorch version: main

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer

**Comment by cpuhrsch** [comment]
This overall falls into the bucket of PT2 enablement for sparse layouts. I'll add this to our tracker.

**Comment by pearu** [comment]
Fixed via https://github.com/pytorch/pytorch/pull/120920
