### ISSUE TITLE
ONNX -> Caffe2 lstm issue

### ISSUE THREAD

**Issue by Kandarp2516** [pytorch/pytorch#9951]
I am trying to convert ONNX model to caffe2. While trying to run:

```
import onnx
import caffe2.python.onnx.backend as backend
from caffe2.python.onnx.backend import Caffe2Backend

def main():
    model_onnx = onnx.load("lstm.onnx")
    onnx.checker.check_model(model_onnx)
    try:
        input_size_net, predict_net = Caffe2Backend.onnx_graph_to_caffe2_net(model_onnx)
        with open('init_net.pb', "wb") as f:
            f.write(init_net.SerializeToString())
            
        with open('predict_net.pb', "wb") as f:
            f.write(predict_net.SerializeToString())
            
    except (Exception, RuntimeError) as e:
        print(e)
        print(' ===== Unsuccessfull Caffe2 save run, exiting ===== ')
        return
        
    finally:
        print(' ===== Step 3 finished')

```
I get error:

> ONNX FATAL: list index out of range
> Traceback (most recent call last):
>   File "check_pytorch.py", line 13, in <module>
>     prepared_backend = backend.prepare(model)
>   File "/anaconda2/envs/py36_caffe2_onnx/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 788, in prepare
>     init_net, predict_net = cls._onnx_model_to_caffe2_net(model, device, opset_version, False)
>   File "/anaconda2/envs/py36_caffe2_onnx/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 976, in _onnx_model_to_caffe2_net
>     raise RuntimeError('ONNX conversion failed')
> RuntimeError: ONNX conversion failed

I found similar issue here: [https://discuss.pytorch.org/t/onnx-caffe2-for-recurrent-models-issue/21826](url)

It seems like a bug. Is there any easy work around for this?

I am using anaconda and have installed caffe2 from caffe2 channel and onnx from exyang channel.

**Comment by Kandarp2516** [comment]
After looking bit deeper on pytorch to onnx and onnx to caffe2 code, I realized that this might be version conflict. After updating pytorch to 0.4.1, export to caffe2 works fine.
