### ISSUE TITLE
[torch.compile] 

### ISSUE THREAD

**Issue by shingjan** [pytorch/pytorch#99605]
### 🐛 Describe the bug

The following repro works on torch-nightly <= 2.1.0.dev20230403 but failed on nightlies newer than that. 
```
from segment_anything import build_sam, SamAutomaticMaskGenerator
import cv2
from torch import _dynamo as dynamo
image = cv2.imread('astronaut.png')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
mask_generator = SamAutomaticMaskGenerator(build_sam(checkpoint="../segment-anything/sam_vit_h_4b8939.pth"))

def func(image):
    return mask_generator.generate(image)

ex = dynamo.explain(func, image)[-1]
print(ex)
```

with the following error:
```
Traceback (most recent call last):
  File "/home/yj/anaconda3/envs/dyna/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 388, in _compile
    check_fn = CheckFunctionManager(
  File "/home/yj/anaconda3/envs/dyna/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 686, in __init__
    guard.create(local_builder, global_builder)
  File "/home/yj/anaconda3/envs/dyna/lib/python3.8/site-packages/torch/_guards.py", line 182, in create
    return self.create_fn(self.source.select(local_builder, global_builder), self)
  File "/home/yj/anaconda3/envs/dyna/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 327, in CONSTANT_MATCH
    val = self.get(guard.name)
  File "/home/yj/anaconda3/envs/dyna/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 163, in get
    return eval(name, self.scope, CLOSURE_VARS)
  File "<string>", line 1, in <module>
NameError: name 'L' is not defined
```

My guess is that this regression may be caused by #98107 on local/user build of guards. 

### Versions

PyTorch version: 2.1.0.dev20230403+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.31

Python version: 3.8.0 (default, Nov  6 2019, 21:49:08)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070
Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          24
On-line CPU(s) list:             0-23
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           33
Model name:                      AMD Ryzen 9 5900X 12-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     3700.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        7399.70
Virtualization:                  AMD-V
L1d cache:                       384 KiB
L1i cache:                       384 KiB
L2 cache:                        6 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.7
[pip3] dalle2-pytorch==1.12.4
[pip3] ema-pytorch==0.2.1
[pip3] functorch==1.14.0a0+408bcf1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.21.2
[pip3] open-clip-torch==2.16.0
[pip3] pytorch-lightning==2.0.0
[pip3] pytorch-transformers==1.2.0
[pip3] pytorch-triton==2.0.0+b8b470bc59
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.2.1
[pip3] torch==2.1.0.dev20230403+cpu
[pip3] torch-fidelity==0.3.0
[pip3] torch-scatter==2.1.1+pt20cpu
[pip3] torch-sparse==0.6.17+pt20cpu
[pip3] torch-struct==0.5
[pip3] torchaudio==2.1.0.dev20230419+cu118
[pip3] torchdata==0.7.0.dev20230419
[pip3] torchmetrics==0.11.4
[pip3] torchrec-nightly==2023.3.16
[pip3] torchtext==0.16.0.dev20230419+cpu
[pip3] torchvision==0.16.0.dev20230403+cpu
[pip3] vector-quantize-pytorch==1.1.2

**Comment by voznesenskym** [comment]
Enum

pil_modes_mapping = {
    InterpolationMode.NEAREST: 0,
    InterpolationMode.BILINEAR: 2,
    InterpolationMode.BICUBIC: 3,
    InterpolationMode.NEAREST_EXACT: 0,
    InterpolationMode.BOX: 4,
    InterpolationMode.HAMMING: 5,
    InterpolationMode.LANCZOS: 1,
}

**Comment by voznesenskym** [comment]
https://github.com/pytorch/pytorch/pull/99680

**Comment by voznesenskym** [comment]
Resolved

**Comment by shingjan** [comment]
thanks @voznesenskym ! Can confirm the repro works with the patch. Really appreciate the prompt response!
