### ISSUE TITLE
Torch.compile() error with detach() and with torch.no_grad()

### ISSUE THREAD

**Issue by lxysl** [pytorch/pytorch#99616]
### 🐛 Describe the bug

When I using torch.compile(), I encountered the following issues.
The forward pass of my model is:
```python
    def forward(self, x, forward_pass='default', sharpen=True):
        if forward_pass == 'dm':
            features = self.backbone(x)
            out = self.dm_head(features)
            return out

        elif forward_pass == 'pcl':
            features = self.backbone(x)
            q = self.projector(features)
            q = F.normalize(q, dim=1)
            prototypes = self.prototypes.clone().detach()
            if sharpen:
                logits_proto = torch.mm(q, prototypes.t()) / self.temprature
            else:
                logits_proto = torch.mm(q, prototypes.t())
            return q, logits_proto

        elif forward_pass == 'all':
            features = self.backbone(x)
            q = self.projector(features)
            q = F.normalize(q, dim=1)
            prototypes = self.prototypes.clone().detach()
            if sharpen:
                logits_proto = torch.mm(q, prototypes.t()) / self.temprature
            else:
                logits_proto = torch.mm(q, prototypes.t())
            out_dm = self.dm_head(features)
            return out_dm, logits_proto, q
```
The backbone is ResNet18, and `dm_head` and `projector` are several dense layers.
With the `forward_pass` argument is 'all', I want to calculate the 'dm' and 'pcl' simutaneously.

---
In the training procedure, I have two different ways of writing.
The first one is using 'all', and another is using 'dm' and 'pcl'.
```python
# net and net2 are two same networks, train net, and fix net2
net.train()
net2.eval()

with torch.no_grad():
    size_x1, size_x2, size_u1, size_u2 = inputs_x1.size(0), inputs_x2.size(0), inputs_u1.size(0), inputs_u2.size(0)
    inputs = torch.cat([inputs_x1, inputs_x2, inputs_u1, inputs_u2], dim=0)

    # using 'all':
    dm_outputs_1, proto_outputs_1, features_1 = net(inputs, forward_pass='all')
    dm_outputs_2, proto_outputs_2, features_2 = net2(inputs, forward_pass='all')

    # or using 'dm' + 'pcl' as following to replace the above two lines:
    # dm_outputs_1 = net(inputs, forward_pass='dm')
    # dm_outputs_2 = net2(inputs, forward_pass='dm')
    # features_1, proto_outputs_1 = net(inputs, forward_pass='pcl')
    # features_2, proto_outputs_2 = net2(inputs, forward_pass='pcl')

    dm_o_x11, dm_o_x12, dm_o_u11, dm_o_u12 = torch.split(dm_outputs_1, [size_x1, size_x2, size_u1, size_u2], dim=0)
    dm_o_x21, dm_o_x22, dm_o_u21, dm_o_u22 = torch.split(dm_outputs_2, [size_x1, size_x2, size_u1, size_u2], dim=0)

labels_x_soft = torch.zeros(batch_size, args.num_classes, device=device).scatter_(1, labels_x.view(-1, 1), 1)
w_x = w_x.view(-1, 1).type(torch.FloatTensor).to(device)

targets_u = co_guessing(dm_o_u11, dm_o_u12, dm_o_u21, dm_o_u22, args.T)
targets_x = co_refinement(dm_o_x11, dm_o_x12, labels_x_soft, w_x, args.T)

variable_dict = {'inputs_x1': inputs_x1, 'inputs_x2': inputs_x2, 'inputs_u1': inputs_u1,
                 'inputs_u2': inputs_u2, 'targets_x': targets_x, 'targets_u': targets_u}
loss_dm = dividemix_train_step(args, net, 'dm', variable_dict, dm_criterion, batch_size, batch_idx, num_iter, epoch, device)
```
The `co_guessing`, `co_refinement`, `dm_criterion` and `dividemix_train_step` functions are like follows (`dm_criterion` is an instance of class `SemiLoss`):
```python
def co_guessing(outputs_u11, outputs_u12, outputs_u21, outputs_u22, T):
    with torch.no_grad():
        # label co-guessing of unlabeled samples
        pu = (torch.softmax(outputs_u11, dim=1) + torch.softmax(outputs_u12, dim=1) +
              torch.softmax(outputs_u21, dim=1) + torch.softmax(outputs_u22, dim=1)) / 4
        ptu = pu ** (1 / T)  # temperature sharpening

        targets_u = ptu / ptu.sum(dim=1, keepdim=True)  # normalize
        targets_u = targets_u.detach()
    return targets_u


def co_refinement(outputs_x11, outputs_x12, labels_x_soft, w_x, T):
    with torch.no_grad():
        # label refinement of labeled samples
        px = (torch.softmax(outputs_x11, dim=1) + torch.softmax(outputs_x12, dim=1)) / 2
        px = w_x * labels_x_soft + (1 - w_x) * px
        ptx = px ** (1 / T)  # temperature sharpening

        targets_x = ptx / ptx.sum(dim=1, keepdim=True)  # normalize
        targets_x = targets_x.detach()
    return targets_x


class SemiLoss(nn.Module):
    # Based on the implementation of SupContrast
    def __init__(self):
        super(SemiLoss, self).__init__()

    def linear_rampup(self, lambda_u, current, warm_up, rampup_length=16):
        current = np.clip((current - warm_up) / rampup_length, 0.0, 1.0)
        return lambda_u * float(current)

    def forward(self, outputs_x, targets_x, outputs_u, targets_u, lambda_u, epoch, warm_up):
        probs_u = torch.softmax(outputs_u, dim=1)

        Lx = -torch.mean(torch.sum(F.log_softmax(outputs_x, dim=1) * targets_x, dim=1))
        Lu = torch.mean((probs_u - targets_u) ** 2)

        return Lx, Lu, self.linear_rampup(lambda_u, epoch, warm_up)

def dividemix_train_step(args, net, forward, variable_dict, criterion, batch_size, batch_idx, num_iter, epoch, device):
    # Unpack variables
    inputs_x1, inputs_x2, inputs_u1, inputs_u2 = variable_dict['inputs_x1'], variable_dict['inputs_x2'], variable_dict['inputs_u1'], variable_dict['inputs_u2']
    targets_x, targets_u = variable_dict['targets_x'], variable_dict['targets_u']

    # mixmatch
    l = np.random.beta(args.alpha, args.alpha)
    l = max(l, 1 - l)

    all_inputs = torch.cat([inputs_x1, inputs_x2, inputs_u1, inputs_u2], dim=0)
    all_targets = torch.cat([targets_x, targets_x, targets_u, targets_u], dim=0)

    idx = torch.randperm(all_inputs.size(0))

    input_a, input_b = all_inputs, all_inputs[idx]
    target_a, target_b = all_targets, all_targets[idx]

    mixed_input = l * input_a + (1 - l) * input_b
    mixed_target = l * target_a + (1 - l) * target_b

    if forward == 'dm':
        logits = net(mixed_input, forward_pass=forward)
    elif forward == 'pcl':
        _, logits = net(mixed_input, forward_pass=forward)
    else:
        raise NotImplementedError
    logits_x = logits[:batch_size * 2]
    logits_u = logits[batch_size * 2:]

    Lx, Lu, lamb = criterion(logits_x, mixed_target[:batch_size * 2], logits_u, mixed_target[batch_size * 2:],
                             args.lambda_u, epoch + batch_idx / num_iter, args.warm_up)

    # regularization
    prior = torch.ones(args.num_classes) / args.num_classes
    prior = prior.to(device)
    pred_mean = torch.softmax(logits, dim=1).mean(0)
    penalty = torch.sum(prior * torch.log(prior / pred_mean))

    loss = Lx + lamb * Lu + penalty
    return loss
```
When I use 'all' instead of 'dm'+'pcl', this code can successfully run. But when using 'dm'+'pcl', there is an error:
```
Traceback (most recent call last):
  File "/home/lxy/Documents/ClusterTeaching/ClusterTeaching.py", line 194, in <module>
    main()
  File "/home/lxy/Documents/ClusterTeaching/ClusterTeaching.py", line 165, in main
    uniform_proto_train(args, epoch, net1, net2, optimizer1, labeled_trainloader, unlabeled_trainloader, semi_loss, ce_loss, info_nce_loss, meta_info, device)
  File "/home/lxy/Documents/ClusterTeaching/utils/train_utils.py", line 692, in uniform_proto_train
    loss_dm = dividemix_train_step(args, net, 'dm', variable_dict, dm_criterion, batch_size, batch_idx, num_iter, epoch, device)
  File "/home/lxy/Documents/ClusterTeaching/utils/train_utils.py", line 102, in dividemix_train_step
    logits = net(mixed_input, forward_pass=forward)
  File "/opt/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/opt/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/lxy/Documents/ClusterTeaching/models/models.py", line 76, in forward
    def forward(self, x, forward_pass='default', sharpen=True):
  File "/opt/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/opt/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2819, in forward
    return compiled_fn(full_args)
  File "/opt/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1222, in g
    return f(*args)
  File "/opt/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1898, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/opt/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1247, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/opt/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 248, in run
    return model(new_inputs)
  File "/tmp/torchinductor_lxy/wo/cwoko77dmlrgqfxjyv3jpalqkko7ufkqxln7tjwcrwacduz4psjx.py", line 1531, in call
    extern_kernels.addmm(arg55_1, as_strided(buf109, (256, 512), (512, 1)), as_strided(arg54_1, (512, 10), (1, 512)), alpha=1, beta=1, out=buf110)
RuntimeError: addmm(): functions with out=... arguments don't support automatic differentiation, but one of the arguments requires grad.
```
By the way, there is no error without using `torch.compile()`.
And also, when using `detach()` to `dm_outputs_1` and `dm_outputs_1` instead of `with torch.no_grad()`, there is no error, too.
But I still think there is something wrong, because although it run successfully with the above two methods, the accuracy is lower than the baseline.

Here is a link of the codegen’d file [https://gist.github.com/lxysl/5d49e6328988393eebc61b4978e3eabc](https://gist.github.com/lxysl/5d49e6328988393eebc61b4978e3eabc)

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.35

Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6134 CPU @ 3.20GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       2
Stepping:                        4
CPU max MHz:                     3700.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        6400.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       512 KiB (16 instances)
L1i cache:                       512 KiB (16 instances)
L2 cache:                        16 MiB (16 instances)
L3 cache:                        49.5 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-7,16-23
NUMA node1 CPU(s):               8-15,24-31
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchinfo==1.7.2
[pip3] torchvision==0.15.1
[pip3] torchviz==0.0.2
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchaudio                2.0.1                    pypi_0    pypi
[conda] torchinfo                 1.7.2                    pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ezyang** [comment]
cc @bdhirsh, this looks related to the detach stuff you've been looking at recently

**Comment by bdhirsh** [comment]
@lxysl do you have a single repro script that I can run to see the bug locally? (Or a set of repro instructions, like which github repro's to install, etc). That will make finding the bug much faster.

**Comment by bdhirsh** [comment]
hmm @lxysl I tried to piece together the code you have, but so far I'm unable to repro. Here's what I have so far (I manually took `net` and `net2` that you have and torch.compile'd them, but I don't get an error).
```
import torch
import torch.nn as nn

resnet18_ = torch.hub.load('pytorch/vision:v0.10.0', 'resnet18', pretrained=True)
resnet18 = resnet18_.to(device='cuda')

def co_guessing(outputs_u11, outputs_u12, outputs_u21, outputs_u22, T):
    with torch.no_grad():
        # label co-guessing of unlabeled samples
        pu = (torch.softmax(outputs_u11, dim=1) + torch.softmax(outputs_u12, dim=1) +
              torch.softmax(outputs_u21, dim=1) + torch.softmax(outputs_u22, dim=1)) / 4
        ptu = pu ** (1 / T)  # temperature sharpening

        targets_u = ptu / ptu.sum(dim=1, keepdim=True)  # normalize
        targets_u = targets_u.detach()
    return targets_u


def co_refinement(outputs_x11, outputs_x12, labels_x_soft, w_x, T):
    with torch.no_grad():
        # label refinement of labeled samples
        px = (torch.softmax(outputs_x11, dim=1) + torch.softmax(outputs_x12, dim=1)) / 2
        px = w_x * labels_x_soft + (1 - w_x) * px
        ptx = px ** (1 / T)  # temperature sharpening

        targets_x = ptx / ptx.sum(dim=1, keepdim=True)  # normalize
        targets_x = targets_x.detach()
    return targets_x


class SemiLoss(nn.Module):
    # Based on the implementation of SupContrast
    def __init__(self):
        super(SemiLoss, self).__init__()

    def linear_rampup(self, lambda_u, current, warm_up, rampup_length=16):
        current = np.clip((current - warm_up) / rampup_length, 0.0, 1.0)
        return lambda_u * float(current)

    def forward(self, outputs_x, targets_x, outputs_u, targets_u, lambda_u, epoch, warm_up):
        probs_u = torch.softmax(outputs_u, dim=1)

        Lx = -torch.mean(torch.sum(torch.nn.functional.log_softmax(outputs_x, dim=1) * targets_x, dim=1))
        Lu = torch.mean((probs_u - targets_u) ** 2)

        return Lx, Lu, self.linear_rampup(lambda_u, epoch, warm_up)

def dividemix_train_step(args, net, forward, variable_dict, criterion, batch_size, batch_idx, num_iter, epoch, device):
    # Unpack variables
    inputs_x1, inputs_x2, inputs_u1, inputs_u2 = variable_dict['inputs_x1'], variable_dict['inputs_x2'], variable_dict['inputs_u1'], variable_dict['inputs_u2']
    targets_x, targets_u = variable_dict['targets_x'], variable_dict['targets_u']

    # mixmatch
    l = np.random.beta(0.5, 0.5)
    l = max(l, 1 - l)

    all_inputs = torch.cat([inputs_x1, inputs_x2, inputs_u1, inputs_u2], dim=0)
    all_targets = torch.cat([targets_x, targets_x, targets_u, targets_u], dim=0)

    idx = torch.randperm(all_inputs.size(0))

    input_a, input_b = all_inputs, all_inputs[idx]
    target_a, target_b = all_targets, all_targets[idx]

    mixed_input = l * input_a + (1 - l) * input_b
    mixed_target = l * target_a + (1 - l) * target_b

    if forward == 'dm':
        logits = net(mixed_input, forward_pass=forward)
    elif forward == 'pcl':
        _, logits = net(mixed_input, forward_pass=forward)
    else:
        raise NotImplementedError
    logits_x = logits[:batch_size * 2]
    logits_u = logits[batch_size * 2:]
    # HERE
    loss = (logits_x + logits_u).sum()
    return loss

    Lx, Lu, lamb = criterion(logits_x, mixed_target[:batch_size * 2], logits_u, mixed_target[batch_size * 2:],
                             args.lambda_u, epoch + batch_idx / num_iter, args.warm_up)

    # regularization
    prior = torch.ones(args.num_classes) / args.num_classes
    prior = prior.to(device)
    pred_mean = torch.softmax(logits, dim=1).mean(0)
    penalty = torch.sum(prior * torch.log(prior / pred_mean))

    loss = Lx + lamb * Lu + penalty
    return loss

class Mod(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.backbone = resnet18
        #self.backbone = torch.nn.Linear(512, 128).to(device='cuda')
        self.temprature = 0.8
        self.dm_head = torch.nn.Linear(1000, 1000).to(device='cuda')
        self.projector = torch.nn.Linear(1000, 1000).to(device='cuda')
        self.prototypes = torch.randn(1000, 1000, device='cuda')

    def forward(self, x, forward_pass='default', sharpen=True):
        if forward_pass == 'dm':
            features = self.backbone(x)
            out = self.dm_head(features)
            return out

        elif forward_pass == 'pcl':
            features = self.backbone(x)
            q = self.projector(features)
            q = torch.nn.functional.normalize(q, dim=1)
            prototypes = self.prototypes.clone().detach()
            if sharpen:
                logits_proto = torch.mm(q, prototypes.t()) / self.temprature
            else:
                logits_proto = torch.mm(q, prototypes.t())
            return q, logits_proto

        elif forward_pass == 'all':
            features = self.backbone(x)
            q = self.projector(features)
            q = torch.nn.functional.normalize(q, dim=1)
            prototypes = self.prototypes.clone().detach()
            if sharpen:
                logits_proto = torch.mm(q, prototypes.t()) / self.temprature
            else:
                logits_proto = torch.mm(q, prototypes.t())
            out_dm = self.dm_head(features)
            return out_dm, logits_proto, q


# net and net2 are two same networks, train net, and fix net2
net = Mod()
net2 = Mod()
net.to(device='cuda')
net2.to(device='cuda')
net = torch.compile(net)
net2 = torch.compile(net2)
net.train()
net2.eval()

with torch.no_grad():
    inputs_x1 = torch.randn(1, 3, 128, 128, device='cuda')
    inputs_x2 = torch.randn(1, 3, 128, 128, device='cuda')
    inputs_u1 = torch.randn(1, 3, 128, 128, device='cuda')
    inputs_u2 = torch.randn(1, 3, 128, 128, device='cuda')
    size_x1, size_x2, size_u1, size_u2 = inputs_x1.size(0), inputs_x2.size(0), inputs_u1.size(0), inputs_u2.size(0)
    inputs = torch.cat([inputs_x1, inputs_x2, inputs_u1, inputs_u2], dim=0)

    # using 'all':
    # dm_outputs_1, proto_outputs_1, features_1 = net(inputs, forward_pass='all')
    # m_outputs_2, proto_outputs_2, features_2 = net2(inputs, forward_pass='all')

    # or using 'dm' + 'pcl' as following to replace the above two lines:
    dm_outputs_1 = net(inputs, forward_pass='dm')
    dm_outputs_2 = net2(inputs, forward_pass='dm')
    features_1, proto_outputs_1 = net(inputs, forward_pass='pcl')
    features_2, proto_outputs_2 = net2(inputs, forward_pass='pcl')

    dm_o_x11, dm_o_x12, dm_o_u11, dm_o_u12 = torch.split(dm_outputs_1, [size_x1, size_x2, size_u1, size_u2], dim=0)
    dm_o_x21, dm_o_x22, dm_o_u21, dm_o_u22 = torch.split(dm_outputs_2, [size_x1, size_x2, size_u1, size_u2], dim=0)


```

Does this error for you? Or do you have any suggested changes to force the error?

**Comment by lxysl** [comment]
Thank you very much for debugging my code! I'll try to upload a repo easy to debug in a few days.

**Comment by lxysl** [comment]
Sorry for the delay, but I'm working on a conference deadline. It may take me about another two weeks to finish my work, after which I will upload the code! Thanks again to the developers for your continued attention to this issue!

**Comment by bdhirsh** [comment]
I'm going to close this as fixed by https://github.com/pytorch/pytorch/pull/100570.

@lxysl can you try re-running on a nightly, and re-open if you still see the issue?
