### ISSUE TITLE
[torch.compile] ShapeProp error for conv

### ISSUE THREAD

**Issue by payphon** [pytorch/pytorch#99629]
### 🐛 Describe the bug

`torch.compile` will raise `ShapeProp error for: node=%l__self___conv : [#users=1] = call_module[target=L__self___conv](args = (%l_x_,), kwargs = {})` error

```py
import torch
import torch.nn as nn

torch.manual_seed(420)

class Model(torch.nn.Module):

    def __init__(self):
        super(Model, self).__init__()
        self.conv = nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1, bias=False, dtype=torch.bfloat16)
        self.bn = nn.BatchNorm2d(16, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)

    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        return x

input_tensor = torch.randn(1, 3, 64, 64, dtype=torch.bfloat16)

func = Model()

with torch.no_grad():
    func.train(False)
    res1 = func(input_tensor)
    # success
    jit_func = torch.compile(func)
    res2 = jit_func(input_tensor)
    # RuntimeError: ShapeProp error for: node=%l__self___conv : [#users=1] = call_module[target=L__self___conv](args = (%l_x_,), kwargs = {})
```

It seems that it is caused by `fuse_conv_bn`

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0.dev20230419+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.5-051905-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 510.108.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       GenuineIntel
Model name:                      12th Gen Intel(R) Core(TM) i9-12900K
CPU family:                      6
Model:                           151
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
Stepping:                        2
CPU max MHz:                     6700.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6374.40
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       640 KiB (16 instances)
L1i cache:                       768 KiB (16 instances)
L2 cache:                        14 MiB (10 instances)
L3 cache:                        30 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+46672772b4
[pip3] torch==2.1.0.dev20230419+cu118
[pip3] torchaudio==2.1.0.dev20230419+cu118
[pip3] torchvision==0.16.0.dev20230419+cu118
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+46672772b4          pypi_0    pypi
[conda] torch                     2.1.0.dev20230419+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230419+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230419+cu118          pypi_0    pypi
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by yanboliang** [comment]
I can reproduce this, and it passed for dynamo```eager``` and ```aot_eager``` backends, failed for ```inductor``` backend.
```
[2023-04-21 05:00:38,598] torch._dynamo.output_graph: [INFO] Step 2: calling compiler function debug_wrapper
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/torch/fx/passes/shape_prop.py", line 148, in run_node
    result = super().run_node(n)
  File "/scratch/ybliang/work/repos/pytorch/torch/fx/interpreter.py", line 179, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/fx/interpreter.py", line 296, in call_module
    return submod(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::BFloat16) and bias type (float) should be the same
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/debug/debug3.py", line 33, in <module>
    res2 = jit_func(input_tensor)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 116, in __call__
    return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 252, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/eval_frame.py", line 405, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 501, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 122, in _fn
    return fn(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 337, in _convert_frame_assert
    return _compile(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 407, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/convert_frame.py", line 392, in transform
    tracer.run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 1972, in run
    super().run()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 670, in run
    and self.step()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 630, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 2060, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/output_graph.py", line 668, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/scratch/ybliang/work/env/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/output_graph.py", line 763, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/output_graph.py", line 822, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/output_graph.py", line 818, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/repro/after_dynamo.py", line 109, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/scratch/ybliang/work/repos/pytorch/torch/__init__.py", line 1530, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/scratch/ybliang/work/repos/pytorch/torch/_inductor/compile_fx.py", line 657, in compile_fx
    model_ = pre_grad_passes(model_, example_inputs_)
  File "/scratch/ybliang/work/repos/pytorch/torch/_inductor/fx_passes/pre_grad.py", line 48, in pre_grad_passes
    gm = fuse_fx(gm, example_inputs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_inductor/fx_passes/pre_grad.py", line 74, in fuse_fx
    gm = mkldnn_fuse_fx(gm, example_inputs)
  File "/scratch/ybliang/work/repos/pytorch/torch/_inductor/mkldnn.py", line 273, in mkldnn_fuse_fx
    ShapeProp(gm, fake_mode=fake_mode).propagate(*example_inputs)
  File "/scratch/ybliang/work/repos/pytorch/torch/fx/passes/shape_prop.py", line 192, in propagate
    return super().run(*fake_args)
  File "/scratch/ybliang/work/repos/pytorch/torch/fx/interpreter.py", line 137, in run
    self.env[node] = self.run_node(node)
  File "/scratch/ybliang/work/repos/pytorch/torch/fx/passes/shape_prop.py", line 155, in run_node
    raise RuntimeError(
torch._dynamo.exc.BackendCompilerFailed: backend='debug_wrapper' raised:
RuntimeError: ShapeProp error for: node=%l__self___conv : [#users=1] = call_module[target=L__self___conv](args = (%l_x_,), kwargs = {}) with meta={'stack_trace': '  File "/scratch/ybliang/work/repos/debug/debug3.py", line 20, in forward\n    x = self.conv(x)\n', 'nn_module_stack': {'L__self___conv': ("L['self'].conv", <class 'torch.nn.modules.conv.Conv2d'>)}, 'source_fn': <class 'torch.nn.modules.conv.Conv2d'>}

While executing %l__self___conv : [#users=1] = call_module[target=L__self___conv](args = (%l_x_,), kwargs = {})
Original traceback:
  File "/scratch/ybliang/work/repos/debug/debug3.py", line 20, in forward
    x = self.conv(x)



You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```
I think this line tells us the culprit:
```
RuntimeError: Input type (c10::BFloat16) and bias type (float) should be the same
``` 
User's code specified ```bfloat16``` for inputs and ```nn.Conv2d```, so it seems inductor can't propagate ```dtype``` properly.

**Comment by XiaobingSuper** [comment]
can be fixed by https://github.com/pytorch/pytorch/pull/99696.
