### ISSUE TITLE
RuntimeError: Triton Error [HIP]:  Code: 200, Messsage: device kernel image is invalid

### ISSUE THREAD

**Issue by dllehr-amd** [pytorch/pytorch#99725]
### 🐛 Describe the bug

When attempting to run a pytorch benchmark suite,  after commit 
[495e1b4d0e0092de22160c83a0a51d948df6d69f](https://github.com/pytorch/pytorch/commit/495e1b4d0e0092de22160c83a0a51d948df6d69f)

```
python3 benchmarks/dynamo/runner.py --dtypes amp --suites huggingface --training --compilers inductor_no_cudagraphs --no-gh-comment
```

We fail to launch a kernel with the following Traceback
```
cuda train AlbertForMaskedLM                   ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/trees/pytorch/benchmarks/dynamo/common.py", line 1376, in warmup
    fn(model, example_inputs)
  File "/trees/pytorch/torch/_dynamo/eval_frame.py", line 252, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/huggingface.py", line 490, in forward_and_backward_pass
    cloned_inputs = clone_inputs(inputs)
  File "benchmarks/dynamo/huggingface.py", line 491, in <resume in forward_and_backward_pass>
    self.optimizer_zero_grad(mod)
  File "benchmarks/dynamo/huggingface.py", line 491, in <resume in forward_and_backward_pass>
    self.optimizer_zero_grad(mod)
  File "/trees/pytorch/torch/_dynamo/eval_frame.py", line 252, in _fn
    return fn(*args, **kwargs)
  File "/trees/pytorch/torch/_functorch/aot_autograd.py", line 3273, in forward
    return compiled_fn(full_args)
  File "/trees/pytorch/torch/_functorch/aot_autograd.py", line 1239, in g
    return f(*args)
  File "/trees/pytorch/torch/_functorch/aot_autograd.py", line 2170, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/trees/pytorch/torch/_functorch/aot_autograd.py", line 1264, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/trees/pytorch/torch/_functorch/aot_autograd.py", line 1239, in g
    return f(*args)
  File "/trees/pytorch/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/trees/pytorch/torch/_functorch/aot_autograd.py", line 2519, in forward
    fw_outs = call_func_with_args(
  File "/trees/pytorch/torch/_functorch/aot_autograd.py", line 1264, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/trees/pytorch/torch/_inductor/compile_fx.py", line 336, in run
    return model(new_inputs)
  File "/tmp/tmphps291ul/rb/crbkuw7malqrc46ifc5y4bu4dcwz55w3jrq7j4bonaajulfrg43f.py", line 1089, in call
    triton_per_fused__to_copy_add_embedding_native_layer_norm_native_layer_norm_backward_view_0.run(buf2, primals_32, primals_1, primals_30, primals_2, primals_31, primals_3, primals_4, primals_5, buf4, buf5, buf459, 2048, 128, grid=grid(2048), stream=stream0)
  File "/trees/pytorch/torch/_inductor/triton_heuristics.py", line 218, in run
    self.autotune_to_one_config(*args, grid=grid)
  File "/trees/pytorch/torch/_inductor/triton_heuristics.py", line 190, in autotune_to_one_config
    timings = self.benchmark_all_configs(*args, **kwargs)
  File "/trees/pytorch/torch/_dynamo/utils.py", line 169, in time_wrapper
    r = func(*args, **kwargs)
  File "/trees/pytorch/torch/_inductor/triton_heuristics.py", line 182, in benchmark_all_configs
    timings = {
  File "/trees/pytorch/torch/_inductor/triton_heuristics.py", line 183, in <dictcomp>
    launcher: self.bench(launcher, *cloned_args, **kwargs)
  File "/trees/pytorch/torch/_inductor/triton_heuristics.py", line 165, in bench
    return do_bench(kernel_call, rep=40, fast_flush=True)
  File "/trees/pytorch/torch/_inductor/utils.py", line 54, in do_bench
    return triton_do_bench(*args, **kwargs)[0]
  File "/opt/conda/lib/python3.8/site-packages/triton/testing.py", line 144, in do_bench
    fn()
  File "/trees/pytorch/torch/_inductor/triton_heuristics.py", line 159, in kernel_call
    launcher(
  File "<string>", line 6, in launcher
RuntimeError: Triton Error [HIP]:  Code: 200, Messsage: device kernel image is invalid
```

### Versions

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] pytorch-triton-rocm==2.1.0
[pip3] torch==2.1.0a0+git495e1b4
[pip3] torchvision==0.14.0a0+bd70a78
[conda] mkl                       2022.0.1           h06a4308_117
[conda] mkl-include               2022.0.1           h06a4308_117
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch-triton-rocm       2.1.0                    pypi_0    pypi
[conda] torch                     2.1.0a0+git495e1b4           dev_0    <develop>
[conda] torchvision               0.14.0a0+bd70a78          pypi_0    pypi

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by dllehr-amd** [comment]
Hi @ngimel  We should have device asserts setup on triton.  At least the code paths are active.  @jataylo and I was able to triage the issue down to this line

https://github.com/pytorch/pytorch/commit/495e1b4d0e0092de22160c83a0a51d948df6d69f#diff-f29e4d4eb3f727a18970de422f23dbe16f75e3688fdbae820849dc7dfe145d04R87

If we set it to `0` everything starts going.   
e.g. ` compile_meta["debug"] = 0`


The device_assert code was added to triton recently, and we haven't been able to fully test it.  For now I'm okay disabling this on ROCm.  i can submit a PR to sort it out

**Comment by dllehr-amd** [comment]
Would you prefer I modify the `compile_meta["debug"]` or change 
`config.triton.assert_indirect_indexing` in the config.py?

**Comment by ngimel** [comment]
Either fix is fine, thanks!

**Comment by lezcano** [comment]
I don't know if we've moved the pin forward enough, but that line used to be necessary for the asserts to fire in CUDA. Now, I know that there was something related to device_asserts that was fixed in triton core, so perhaps it was that? Could you confirm that the asserts do fire in CUDA even when you remove that line?

**Comment by dllehr-amd** [comment]
I'm working on recreating on the CUDA side.  For ROCm, I noticed the asserts don't fire or at least become no-ops if the `debug` flag isn't passed down to `triton.compile`  so UT's that used `tl.device_assert` ended up being fine for us.  Turning on the `debug` flag seemed to fire them off

**Comment by dllehr-amd** [comment]
CI was passing over the weekend, I noticed @lezcano  was adding more code around this space, so I rebased just now and will rerun to make sure everything goes according to plan.  At that point I think we'll be okay to merge
