### ISSUE TITLE
onnx export produces incorrect dtype for min + full_like

### ISSUE THREAD

**Issue by haijieg** [pytorch/pytorch#99788]
### 🐛 Describe the bug

This is a bug on torch nightly torch==2.1.0.dev20230328 and later.
torch==2.1.0.dev20230327 and before works fine.

torch.onnx.export will add additional `float` cast for an integer tensor used by `min` and `full_like`, which result in incorrect datatype.

Minimal Repro:
```
  import torch


  def f(x):
      z = torch.min(x, torch.full_like(x, 10))
      return z

  x = torch.randint(0, 20, (4, 4), dtype=torch.int64)
  script = torch.jit.trace(f, (x,))
  print(torch.onnx.export_to_pretty_string(script, (x,)))
```

Expected: graph has INT output type.
Actual: graph has FLOAT output type.

Output from  torch==2.1.0.dev20230328 and later:
```
ModelProto {
  producer_name: "pytorch"
  domain: ""
  doc_string: ""
  graph:
    GraphProto {
      name: "torch_jit"
      inputs: [{name: "x", type:Tensor dtype: 7, Tensor dims: 4 4}]
      outputs: [{name: "3", type:Tensor dtype: 1, Tensor dims: 4 4}]    # BUG dtype should be 7
      value_infos: []
      initializers: []
      nodes: [
        Node {type: "Cast", inputs: [x], outputs: [onnx::Min_1], attributes: [{ name: 'to', type: int, value: 1}]},  # BUG cast should be here
        Node {type: "Constant", inputs: [], outputs: [onnx::Min_2], attributes: [{ name: 'value', type: tensor, value:TensorProto shape: [4 4]}]},
        Node {type: "Min", inputs: [onnx::Min_1,onnx::Min_2], outputs: [3], attributes: []}
      ]
    }
  opset_import: [OperatorSetIdProto { domain: , version: 14}],
}
```

Output from torch==2.1.0.dev20230327
```
ModelProto {
  producer_name: "pytorch"
  domain: ""
  doc_string: ""
  graph:
    GraphProto {
      name: "torch_jit"
      inputs: [{name: "x", type:Tensor dtype: 7, Tensor dims: 4 4}]
      outputs: [{name: "2", type:Tensor dtype: 7, Tensor dims: 4 4}]
      value_infos: []
      initializers: []
      nodes: [
        Node {type: "Constant", inputs: [], outputs: [onnx::Min_1], attributes: [{ name: 'value', type: tensor, value:TensorProto shape: [4 4]}]},
        Node {type: "Min", inputs: [x,onnx::Min_1], outputs: [2], attributes: []}
      ]
    }
  opset_import: [OperatorSetIdProto { domain: , version: 14}],
}
```

This causes HuggingFace Transformer T5 model export to fail due to the pattern in relative positional encoding:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L433

Minimal repro on malformed ONNX model export
```
  import torch
  import onnxruntime


  def f(x):
      is_small = x < 10
      y = (x + 0.5).to(torch.int64)
      z = torch.min(y, torch.full_like(x, 10))
      out = torch.where(is_small, x, z)
      return out


  x = torch.randint(0, 20, (4, 4), dtype=torch.int64)
  script = torch.jit.trace(f, (x,))

  torch.onnx.export(script, (x,), 'a.onnx')
  onnxruntime.InferenceSession('a.onnx', providers=['CPUExecutionProvider'])
```

Expected: runs without error
Actual: 
```
Traceback (most recent call last):
  File "repro.py", line 17, in <module>
    onnxruntime.InferenceSession('a.onnx', providers=['CPUExecutionProvider'])
  File "/home/jgu/Projects/dynamite/env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/jgu/Projects/dynamite/env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from a.onnx failed:Type Error: Type parameter (T) of Optype (Where) bound to different types (tensor(int64) and tensor(float) in node (Where_9).
```

The reason is "WhereOp" was fed in x, and z, due to the bug above, "z" was incorrectly treated as "FLOAT".

### Versions

torch==2.1.0.dev20230328  and later

**Comment by haijieg** [comment]
Hello, is there update on this issue?

**Comment by haijieg** [comment]
Sorry for pinging again. Is there a plan to fix this issue soon?

**Comment by haijieg** [comment]
Hello, I want to follow up again on this issue. It seems the path of torchscript -> onnx is not being actively maintained. Is the plan to fully switch `torch.onnx` to use dynamo.export? @BowenBao

**Comment by chentong319** [comment]
Can I have the output of `onnx-mlir --EmitONNXBasic`
