### ISSUE TITLE
.view(dtype) doesn't work in primtorch / dynamo with dynamic=True

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#99804]
### 🐛 Describe the bug

```
Traceback (most recent call last):                                                                       
  File "/data/users/ezyang/a/pytorch/torch/_subclasses/fake_tensor.py", line 1069, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)                                                      
  File "/data/users/ezyang/a/pytorch/torch/_subclasses/fake_tensor.py", line 1263, in dispatch           
    r = func(*args, **kwargs)                                                                            
  File "/data/users/ezyang/a/pytorch/torch/_ops.py", line 398, in __call__                               
    return self._op(*args, **kwargs or {})                                                               
  File "/data/users/ezyang/a/pytorch/torch/_refs/__init__.py", line 4047, in view                        
    return _reshape_view_helper(a, *shape, allow_copy=False)                                             
  File "/data/users/ezyang/a/pytorch/torch/_refs/__init__.py", line 3176, in _reshape_view_helper        
    shape = utils.infer_size(shape, a.numel())                                                           
  File "/data/users/ezyang/a/pytorch/torch/_prims_common/__init__.py", line 789, in infer_size           
    elif d >= 0:                                                                                         
TypeError: '>=' not supported between instances of 'torch.dtype' and 'int'                               
Traceback (most recent call last):                                                                       
  File "/data/users/ezyang/a/pytorch/torch/_dynamo/utils.py", line 1269, in run_node                     
    return getattr(args[0], node.target)(*args[1:], **kwargs)                                            
  File "/data/users/ezyang/a/pytorch/torch/utils/_stats.py", line 20, in wrapper                         
    return fn(*args, **kwargs)                                                                           
  File "/data/users/ezyang/a/pytorch/torch/_subclasses/fake_tensor.py", line 1069, in __torch_dispatch__ 
    return self.dispatch(func, types, args, kwargs)                                                      
  File "/data/users/ezyang/a/pytorch/torch/_subclasses/fake_tensor.py", line 1263, in dispatch           
    r = func(*args, **kwargs)                                                                            
  File "/data/users/ezyang/a/pytorch/torch/_ops.py", line 398, in __call__                                   return self._op(*args, **kwargs or {})                                                               
  File "/data/users/ezyang/a/pytorch/torch/_refs/__init__.py", line 4047, in view                            return _reshape_view_helper(a, *shape, allow_copy=False)                                             
  File "/data/users/ezyang/a/pytorch/torch/_refs/__init__.py", line 3176, in _reshape_view_helper            shape = utils.infer_size(shape, a.numel())                                                           
  File "/data/users/ezyang/a/pytorch/torch/_prims_common/__init__.py", line 789, in infer_size               elif d >= 0:                                                                                         
TypeError: '>=' not supported between instances of 'torch.dtype' and 'int'  
```

### Versions

master

cc @mruberry @Lezcano @peterbell10 @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @ngimel @yf225 @soumith

**Comment by yanboliang** [comment]
Seems we don't implement ```.view(dtype)``` in primTorch, I can send a fix.
