### ISSUE TITLE
torch.multinomial() always returns [0] using MPS

### ISSUE THREAD

**Issue by x4base** [pytorch/pytorch#99802]
### 🐛 Describe the bug

Using MPS, torch.multinomial() always return [0], even when the probability is 0.

It works as expected on CPU:
```
import torch

In [1]: x = torch.tensor([0.5, 0.5], dtype=torch.float, device='cpu')
    ...: print(set(torch.multinomial(x, 1, True).item() for i in range(100)))
{0, 1}

In [2]: x = torch.tensor([0, 0.5], dtype=torch.float, device='cpu')
    ...: print(set(torch.multinomial(x, 1, True).item() for i in range(100)))
{1}
```

But on MPS, it always return [0].

```
In [3]: x = torch.tensor([0.5, 0.5], dtype=torch.float, device='mps:1')
   ...: print(set(torch.multinomial(x, 1, True).item() for i in range(100)))
{0}

In [4]: x = torch.tensor([0, 0.5], dtype=torch.float, device='mps:1')
    ...: print(set(torch.multinomial(x, 1, True).item() for i in range(100)))
{0}

In [5]: torch.multinomial(x, 1, True)
Out[5]: tensor([0], device='mps:0')
```

I am actually quite new to torch, so please let me know if I misunderstood anything.

### Versions

PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.3 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.22.4
Libc version: N/A

Python version: 3.9.6 (default, Jul  7 2021, 12:22:14)  [Clang 12.0.5 (clang-1205.0.22.9)] (64-bit runtime)
Python platform: macOS-12.6.3-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[conda] No relevant packages

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
Hey, I am not able to reproduce it on master with macOS 12.6.

From the environment information you provide, It looks that you're running Python using Rosetta 2, i.e. showing `macOS-12.6.3-x86_64-i386-64bit`. Can you please try running PyTorch on Python built natively on arm platform and see if the incorrect results persist?

MPS backend on x86_64 platform is known to be erroneous in some cases.

**Comment by x4base** [comment]
It works normally on arm. Thanks!

```
In [6]: x = torch.tensor([0, 0.5], dtype=torch.float, device='mps:0')

In [7]: print(set(torch.multinomial(x, 1, True).item() for i in range(100)))
{1}
```

**Comment by qqaatw** [comment]
Glad it works!

**Comment by aaloginov** [comment]
Hi guys!
Seems like the problem still exists even on Python built natively on arm platform:
```
Python 3.11.9 (v3.11.9:de54cf5be3, Apr  2 2024, 07:12:50) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
>>> torch.__version__
'2.3.1'
>>>numpy.__version__
'2.0.0'
>>> platform.platform()
'macOS-12.5.1-arm64-arm-64bit'
```
Is debug build: False
OS: macOS 12.5.1 (21G83)
CPU: M1

Reproducing the example above, I get:

`x = torch.tensor([0.5, 0.5], dtype=torch.float, device='cpu')
print(set(torch.multinomial(x, 1, True).item() for i in range(100)))
{0, 1}
x = torch.tensor([0.5, 0.5], dtype=torch.float, device='mps')
print(set(torch.multinomial(x, 1, True).item() for i in range(100)))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <genexpr>
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0`

**Comment by hvaara** [comment]
I was unable to repro with `v2.3.1` built from source on `macOS 14.6.1`:

```python
import torch
x = torch.tensor([0.5, 0.5], dtype=torch.float, device='cpu')
print(set(torch.multinomial(x, 1, True).item() for i in range(100)))
x = torch.tensor([0.5, 0.5], dtype=torch.float, device='mps')
print(set(torch.multinomial(x, 1, True).item() for i in range(100)))

# Output:
# {0, 1}
# {0, 1}
```

#### env

```
PyTorch version: 2.3.0a0+git63d5e92
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.30.1
Libc version: N/A

Python version: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.15.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.12.1
[pip3] torch==2.3.0a0+git63d5e92
[pip3] torch-tb-profiler==0.4.3
[pip3] torchvision==0.20.0a0+0d80848
[pip3] triton==3.0.0
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] torch                     2.3.0a0+git63d5e92           dev_0    <develop>
[conda] torch-tb-profiler         0.4.3                    pypi_0    pypi
[conda] torchfix                  0.4.0                    pypi_0    pypi
[conda] torchvision               0.20.0a0+0d80848           dev_0    <develop>
[conda] triton                    3.0.0                    pypi_0    pypi
```

**Comment by skotapati** [comment]
I'm also unable to reproduce the issue. Closing for now, please reopen if the bug is observed again
