### ISSUE TITLE
torch.compile errors when calling torch.unbind on an length-0 tensor

### ISSUE THREAD

**Issue by albertfgu** [pytorch/pytorch#99832]
### 🐛 Describe the bug

Full program of a simple cumsum function:
```python
import torch

def sequential_scan(bin_op, x):
    s, x_tail = x[..., 0], x[..., 1:]
    outputs = [s]
    for xs_i in torch.unbind(x_tail, dim=-1):
        s = bin_op(s, xs_i)
        outputs.append(s)

    output = torch.stack(outputs, dim=-1)
    return output

def test_scan(L):
    sum_op = lambda x, y: x + y
    a = 1 + torch.arange(L)

    csum = sequential_scan(sum_op, a)
    print(csum)

    scan_opt = torch.compile(sequential_scan)
    csum = scan_opt(sum_op, a)
    print(csum)
    print()

if __name__ == "__main__":
    test_scan(4)
    test_scan(1)
```

----------------------

Output:
```
❯ TORCHDYNAMO_REPRO_AFTER="aot" python -m scan_bug
tensor([ 1,  3,  6, 10])
tensor([ 1,  3,  6, 10])

tensor([1])

    Traceback (most recent call last):
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1194, in run_node
    return node.target(*args, **kwargs)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 987, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1170, in dispatch
    r = func(*args, **kwargs)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_ops.py", line 287, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_refs/__init__.py", line 3425, in unbind
    torch.squeeze(s, dim) for s in torch.tensor_split(t, t.shape[dim], dim)
RuntimeError: number of sections must be larger than 0, got 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1152, in get_fake_value
    return wrap_fake_exception(
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 808, in wrap_fake_exception
    return fn()
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1153, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1206, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <built-in method unbind of type object at 0x7fb3e3ed7540>(*(FakeTensor(FakeTensor(..., device='meta', size=(0,), dtype=torch.int64), cpu),), **{'dim': -1}):
number of sections must be larger than 0, got 0
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jupyter/hippo/src/models/functional/scan_bug.py", line 92, in <module>
    test_scan(1)
  File "/home/jupyter/hippo/src/models/functional/scan_bug.py", line 86, in test_scan
    csum = scan_opt(sum_op, a)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
    return inner_fn(self, inst)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1014, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/variables/torch.py", line 548, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 754, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 789, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/home/albertgu/miniconda3/envs/s4/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1173, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError:

from user code:
   File "/home/jupyter/hippo/src/models/functional/scan_bug.py", line 14, in sequential_scan
    for xs_i in torch.unbind(x_tail, dim=-1):


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Error logs

See above

### Minified repro

N/A

### Versions

This script does not exist (404 Error) by the way - it got updated from `master` to `main`

```
❯ python collect_env.py
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.28

Python version: 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.19.0-23-cloud-amd64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              12
On-line CPU(s) list: 0-11
Thread(s) per core:  2
Core(s) per socket:  6
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:            7
CPU MHz:             2200.164
BogoMIPS:            4400.32
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            39424K
NUMA node0 CPU(s):   0-11
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.9.3
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchdata==0.6.0
[pip3] torchmetrics==0.11.4
[pip3] torchtext==0.15.1
[pip3] torchvision==0.15.0
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0           py310h7f8727e_0
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0
[conda] mkl_random                1.2.2           py310h00e6091_0
[conda] numpy                     1.23.5          py310hd5efca6_0
[conda] numpy-base                1.23.5          py310h8e6c178_0
[conda] pytorch                   2.0.0           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_3    pytorch
[conda] pytorch-lightning         1.9.3                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.0               py310_cu117    pytorch
[conda] torchdata                 0.6.0                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchtext                 0.15.1                   pypi_0    pypi
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.0              py310_cu117    pytorch
```

cc @ezyang @mruberry @ngimel @Lezcano @peterbell10 @soumith @msaroufim @wconstab @bdhirsh

**Comment by yanboliang** [comment]
This is a bug at ```unbind``` decomposition.
